forem/forem

.travis.yml
package.json
postcss.config.js

We've been getting by log flood from `postcss-custom-properties` which is messing up our Travis build. Because that tool no longer provides warning suppression, this PR will suppress it via bash and output it to a file name `err.log` for future debugging.
Resolves https://github.com/forem/forem/issues/11490
Previous attempts
https://github.com/forem/forem/pull/11518
https://github.com/forem/forem/pull/11520
Run `bin/rails assets:precompile` locally and you should not see any warning.
n/a
n/a

Suppress Postcss warnings & Re-enable Benhalpern deploy

---

app/services/articles/feeds/large_forem_experimental.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb

Include Articles WITH the `SiteConfig.home_feed_minimum_score` in the Feed
Closes: https://github.com/forem/InternalProjectPlanning/issues/347

Bug Fix:User >= when filtering by SiteConfig.home_feed_minimum_score

---

app/javascript/readingList/readingList.jsx

@michael-tharrington requested an update for this text and his wish is my command.
#11483
I decided to make the SVG part of the `span` so it's right next to "bookmark reaction" because I thought that'd be most intuitive for the user. Here's how it looks at two different sizes:
I'm open to changing this of course.

Update empty reading list copy

---

app/views/service_worker/index.js.erb

Currently when we deploy Forem Cloud we do not retain assets for old versions of the platform, and service workers do not seem to reliably retain the in-memory cached version of assets, so we sometimes get flashes of unstyled content and other frontend issues.
This adds more static assets to the serviceworker cache, and also adds functionality to _periodically_ flush that component of the serviceworker cache to make sure we don't over-cache.
Things should _continue to work as normal_. If you open up the application tab of chrome tools and view Cache Storage you'll see static 1.2 cache including a bunch of assets.

Include core assets in serviceworker cache

---

app/services/images/optimizer.rb
spec/services/images/optimizer_spec.rb

Instead of breaking an entire page because of one missing image, `Images::Optimizer` should ignore the empty/missing image and pass it back as is so at the very least we can see the culprit.
Debugging-aid for https://github.com/forem/InternalProjectPlanning/issues/348
- All image should still be rendered normally.
[x] No documentation needed
n/a

Make Images::Optimizer nil-safe

---

app/views/admin/configs/show.html.erb

This PR rewords the bolded warning message below the "Public" checkbox in the SiteConfig, which I stumbled upon while working on something else.
N/A
**Before**:
**After**:
N/A
N/A

Reword "Public" Checkbox Warning Message in the SiteConfig

---

app/views/admin/users/_email_tools.html.erb
spec/requests/admin/users_spec.rb

Email messages point to the wrong path in the admin's user page
Closes https://github.com/forem/forem/issues/11578
1. log in the admin
1. select a user, send them an email, refresh the page
1. verify that the link under "recent emails" works 

Fix email messages link in admin's user page

---

app/controllers/moderations_controller.rb
spec/requests/moderations_spec.rb

Remove score filter for articles for the moderator's article index so they can view all articles. 
Closes https://github.com/forem/tech-private/issues/420

Bug Fix:Remove Score Filter From Tag Mod Index

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feeds/large_forem_experimental.rb
config/field_test.yml
spec/services/articles/feeds/large_forem_experimental_spec.rb

Based [on our data](https://dev.to/abtests/) we have decided to go with the `more_comments_minimal_weight_randomized_at_end` path for the large experimental feed. By choosing a single path here we will not allow ourselves to turn other knobs and pull different levers to try and further improve our feed experience. For this reason I left the AB testing framework in place so we can get a settled baseline to compare future changes to such as #11513 
https://github.com/orgs/forem/projects/6#card-48726981

Refactor/Optimization:Use more_comments_minimal_weight_randomized_at_end for Signed In Feed

---

app/views/service_worker/index.js.erb

We recently added caching of core assets into the serviceworker cache in addition to the general in-memory cache because we have more control over eviction, etc.
However, since locally we do not _fingerprint_ assets, we can't rely on that as a cachebusting mechanism like we can in prod. This makes that that code will not run in development. This is a `.erb` file so we can access Rails where appropriate.
This is kind of a hot fix, but we could re-evaluate for a cleaner approach in the future.
We do not need to adjust other cache eviction logic because if the cache is not accumulating, the eviction logic should be fine if the cache is empty.

Don't do serviceworker asset caching in development

---

app/controllers/api/v0/organizations_controller.rb
app/views/api/v0/organizations/users.json.jbuilder
app/views/api/v0/shared/_user_show.json.jbuilder
app/views/api/v0/users/show.json.jbuilder
config/routes.rb
docs/api_v0.yml
spec/requests/api/v0/organizations_spec.rb

This would provide an api endpoint `dev.to/api/organizations/{org_username}/users` to get a list of an organization's users.
As discussed in issue 9212, This is the 2nd of 4 related endpoints that will include:
```
dev.to/api/organizations/{org_username}/articles
dev.to/api/organizations/{org_username}/listings
```
#9212  #10931

API: Endpoint to get an organization's users

---

app/controllers/chat_channels_controller.rb
app/lib/constants/role.rb
app/models/article.rb
app/models/comment.rb
app/services/moderator/banish_user.rb
app/services/moderator/manage_activity_and_roles.rb
app/views/admin/users/_activity.html.erb
app/views/admin/users/edit.html.erb
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/requests/admin/users_manage_spec.rb
spec/system/admin/admin_bans_or_warns_user_spec.rb

Renames "ban" to "suspend" throughout the `/admin/` space.
closes https://github.com/forem/InternalProjectPlanning/issues/298
I stopped short of changing `banned` and `comment_banned` to `suspended` and `comment_suspended` (respectively) within `app > models > role.rb`, as I am not sure how that move will affect current role assignments in production. I welcome feedback/corrections on my decision. :pray:
1. Navigate to `localhost:xxxx/admin/users` as a `super_admin` role
2. Edit any user and give them either `Suspend` or `Comment Suspend` roles
3. Check that their show page reflects the role changes made
https://www.loom.com/share/6c764ef0ff724b8e8c73433681a2edf1
Changes were made just to certain text, depending on the user's role; there are no UI accessibility concerns introduced, in my …

[EOY 2020] Replace "ban" with "suspend" in Admin

---

app/views/users/_customization.html.erb
app/views/users/_language_settings.html.erb

In the hotfix https://github.com/forem/forem/pull/11615 we left out the `grid gap-4` containers while removing nested forms. This puts them back as `<fieldset>`. 
Thanks to @nickytonline for the help: https://github.com/forem/forem/pull/11615/files#r530371789
#11615

Restore fieldsets in Settings/Customization

---

app/controllers/admin/users_controller.rb
app/controllers/api_secrets_controller.rb
app/controllers/organizations_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/labor/error_message_cleaner.rb
app/models/site_config.rb
app/views/admin/users/_data_export.html.erb
app/views/mailers/notify_mailer/account_deleted_email.text.erb
app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
app/views/mailers/notify_mailer/trusted_role_email.html.erb
app/views/mailers/notify_mailer/trusted_role_email.text.erb
app/views/moderations/_mod_sidebar_left.html.erb
app/views/open_search/show.xml.erb
app/views/users/_org_admin.html.erb
spec/helpers/application_helper_spec.rb
spec/requests/admin/configs_spec.rb
spec/requests/user/user_settings_spec.rb
spec/services/exporter/service_spec.rb

We're adding a new `:contact` email to replace the transactional `noreply` default email across all Forems. 
Closes https://github.com/forem/InternalProjectPlanning/issues/198
1. Go to http://localhost:3000/admin/config
1. Change the contact email
1. Click around and see it changed
We might need to notify Forem admins to change this ASAP from the default.

Add contact email to SiteConfig and replace default where appropriate

---

app/services/loggers/log_worker_queue_stats.rb
app/workers/metrics/record_background_queue_stats_worker.rb
spec/services/loggers/log_worker_queue_stats_spec.rb
spec/workers/metrics/record_background_queue_stats_worker_spec.rb

This PR moves `app/labor/loggers/log_worker_queue_stats.rb` to `app/services/loggers/log_worker_queue_stats.rb` and updates specs and code accordingly.
https://github.com/forem/InternalProjectPlanning/issues/271

Move LogWorkerQueueStats from labor to services

---

app/workers/follows/update_points_worker.rb

There is a chance the `cached_tag_list` for an article is nil, in that case we want to make sure we remove it from our array when we are gathering up tags. 
Fixes: https://app.honeybadger.io/fault/66984/8942c036047ae64eb2372bbcf65e8dc6

Bug Fix:Remove nil cached_tag_lists when Collecting Tags

---

app/views/articles/_reaction_button.html.erb

This is a small optimization of not shipping the "hidden" SVGs in contexts where there is no scenario that we would add the parent class that would make these visible.
It saves the bandwidth from all the characters involved in rendering the SVGs. It's not the hugest optimization, but since it applies to our most trafficked page template, every fractional kb saved in one request amounts to a lot of total bandwidth, and for SEO purposes, the less we ask Google to crawl through, the better, even if it's small things.

Small optimization: Don't include --active variation on button for non-logged-in traffic

---

config/routes.rb
spec/routing/all_routes_spec.rb

Some of the old settings paths have hardcoded links in articles and in general it's a good idea to redirect old to new.
https://github.com/forem/forem/pull/11347
1. load the app
1. go to the old path and see you're redirected to the new one

Redirect old settings routes to new ones

---

app/models/user_subscription.rb
spec/models/user_subscription_spec.rb
spec/requests/user_subscriptions_spec.rb

Currently, you can only use the user subscription feature on an "active" source, aka a published article or a comment that hasn't been deleted. If you try to test out this feature on a source that _isn't_ active, then you'll get an error message about "the Source not being found":
While a user _might_ be able to guess what this means, we could be a little more clear in this message I think! I've updated the message to be a bit more specific :) 
Inspired by [this Slack thread](https://dev-internal.slack.com/archives/C7GE84DEJ/p1606784386377500).
To QA this feature, pull down this branch locally, and make sure the user you are logged in as has the `:restricted_liquid_tag` role. Once you have the role, create a new article that includes the user subscription liquid tag in the markdown (see …

Improve error message of User Subscriptions

---

app/views/users/_publishing_from_rss.html.erb
app/views/users/_response_templates.html.erb
spec/system/user/user_edits_extensions_spec.rb

When an invalid feed is submitted in the "Extensions" page, one of the various templates rendered there breaks with a 500 error, ths is the fix for that.
1. go to dev.to/settings/extensions and add a URL that's not a feed
1. press save/submit
1. witness the finality of the error
1. do the same with this branch and see the actual error message

Fix invalid feed error display in settings

---

app/controllers/registrations_controller.rb
spec/requests/registrations_spec.rb

The first user (the Forem creator) has a `super_admin` role and a `single_resource_admin` role for the `Config`, but they aren't `trusted` by default. This means an extra step they have to go through in order to moderate the first content that is submitted to their Forem instance. We should grant them the `trusted` role by default.
Ultimately, I think we probably need to do something more far-reaching in order to give _every_ superadmin the benefits of being a trusted user (as described in https://github.com/forem/forem/issues/11569), but I didn't want to go through the whole codebase adding a bunch of conditionals without thinking through other alternatives first. In the meantime, adding trusted as a role for all new Forem creators will be helpful for bizdev + @pkfrank.
Addresses part of …

Ensure first user of a Forem has a trusted role

---

app/views/users/show.html.erb

Closes https://github.com/forem/forem/issues/11720
Fix for DEV specific logos that appear in the User Profiles. They are currently saved as empty strings, so the previous check `@user.youtube_url` seems to be evaluating to `true`:
Changing this to `@user.youtube_url.present?`. The idea is that sometimes those fields won't exist so we need to check they are present, and then on top of that check to make sure they're not empty strings.
This one is tricky to test, you'll need to edit `app/models/site_config.rb`:
```ruby
def self.dev_to?
#app_domain == "dev.to"
true
end
```
And then start playing around with the DEV specific fields to make sure none of the ones that are empty are visible
N/A

Adds a present? check to the DEV specific fields [Profile Generalization]

---

app/views/notifications/_aggregated_reactions.html.erb
app/views/notifications/_follow.html.erb
app/views/notifications/shared/_profile_pic.html.erb

This PR removes notifications' user- and organisation avatars from tab-order and accessibility tree, as the same info can be found textually right after the avatars. 
With the case of multiple followers, I decided to go with [@nickytonline 's suggestion](https://github.com/forem/forem/issues/11403#issuecomment-735402472). This solution can be a bit confusing as sighted keyboard users can see that the first avatar on followers list doesn't get focus, and it can be unclear that the first avatar belongs to the user whose name is mentioned, but on the other hand, it saves a keystroke (which could potentially be really painful for some, so this helps them. Also, one tab less for all who use keyboard for navigation.).  Another option I was considering was to keep all of the avatars in the tab …

Bugfix: Remove focus from avatars in notifications for better keyboard navigation

---

db/schema.rb
spec/system/user_selects_looking_for_work_spec.rb

After running `rails db:migrate` we're left with this inadvertently committed whitespace change

Fix schema.db whitespace

---

app/javascript/articles/Feed.jsx

This PR resolves a bug that occurs when the first published post on a Forem does _not_ contain a `main_image`, resulting in the post not being "featured." Prior to these changes, if the first, published post on a Forem did not have a cover image, resulting in the post not being considered "featured," the post would not display in the feed until it was updated to contain a `main_image`, was set as `featured: true`, or another post was published _in addition to_ the first published post.
To resolve the bug, a ternary operator was added to `app/javascript/articles/Feed.jsx` to determine where the splicing of the  `feedItems` array (which separates out `featuredStories` from `subStories`) should occur. This proved necessary because when the first published post _does not_ have a `main_image`, …

Bug Fix: First Published Post Not Showing Properly in the Feed

---

app/views/users/show.html.erb

We recently shipped a [profile fields overhaul](https://github.com/forem/forem/pull/10707) which resulted in a bug (dumb Ruby and the fact that it treats empty string as `truthy` 🤣 ).
We fixed it in https://github.com/forem/forem/pull/11730 but unfortunately the HTML is cached for 10 days. 
The quickest solution is to change the cache key. This will have a performance hit on DEV and possibly other Forems
#10707
#11730 
Possibly the capacity of the DEV web server needs to be upped a bit before we deploy this

Change profile header cache key to purge headers

---

docs/faqs.md
docs/getting-started/start-app.md

Adds a FAQ about how to log into Forem the first time it starts up: information about the default admin account has been hard to find in the current Database section.

Add first time admin login to FAQs

---

app/liquid_tags/user_subscription_tag.rb
app/views/liquids/_user_subscription.html.erb
spec/liquid_tags/user_subscription_tag_spec.rb

We ran into some latency + UX issues today around the user subscription tag. This PR improves on the issues that many users ran into by doing the following:
[This DEV post](https://dev.to/devteam/how-to-claim-your-hacktoberfest-completion-badge-3l2h) and related discussions in our support channel.
To QA this feature, pull down this branch locally, and make sure the user you are logged in as has the `:restricted_liquid_tag` role. Once you have the role, create a new article that includes the user subscription liquid tag in the markdown (see the [relevant docs here](https://app.gitbook.com/@forem/s/team-handbook/tech/user-subscription-liquid-tag)):
```
{% user_subscription I love llamas, click here to subscribe to top-notch llama content!! %}
```
To test my changes, you will want to first …

Improve user subscription UX flow when latency is high

---

app/models/profile.rb

This is a code path that is hit during `rake assets:precompile` when the database is not available. We have the `ENV["ENV_AVAILABLE"] == "false"` indication to check here.
We can't access the database during assets precompile outside the container (as it is built in Forem Cloud) so this doesn't break Heroku but breaks FSS.
@jdoss is also going to enable GitHub checks for this so we'll catch it sooner.

Return from method if env called in boot up not available

---

app/assets/stylesheets/ltags/WikipediaTag.scss

Quick fix for this:
The variable-based z-index is the thing we want to be using anywhere we can, so this cleans things up effectively here.
The failing "build-containers" is not related to this change.

Fix wikipedia tag z-index

---

db/migrate/20201203063435_remove_index_notifications_on_json_data_from_notifications.rb
db/schema.rb

This PR removes the unused (0 index scans according to `pg_catalog.pg_stat_user_indexes`) index `index_notifications_on_json_data` from `notifications`. This index currently weighs in at 15GB. The migration is written in a fully reversible way because that's how I like them, even if it makes them a bit more verbose.
n/a

Remove unused index_notifications_on_json_data

---

app/services/images/generate_social_image.rb
spec/services/images/generate_social_image_spec.rb

This code [recently moved from `app/labor` to `app/services`](https://github.com/forem/forem/pull/11691). In that PR @leewynne spotted a hardcoded dev.to URL, which this PR addresses. It also moves the options hash into a constant.

Generalize social image path and clean up code

---

package.json
yarn.lock

This reverts commit c9a289efed49965fa58ec2f2aa3cd9d671c5c501.
Husky 4.3.4, albeit correctly, doesn't silently ignore the fact that it requires `Git >= 2.13.0` and on Heroku we run 2.7, as we haven't update our Heroku images yet, see [Ubuntu Packages on Heroku Stacks](https://devcenter.heroku.com/articles/stack-packages), we have two options:
- add the env `HUSKY_SKIP_INSTALL=1` to simply skip installation on deployment
- revert Husky to what it was before until we upgrade Heroku stack images from Heroku 16 to Heroku 20
See also the error message in one of the failed builds - https://travis-ci.com/github/forem/forem/jobs/455297246#L563:
>        Husky requires Git >=2.13.0. Got v2.7.4.
>        husky > Failed to install

Revert "Bump husky from 4.3.0 to 4.3.4 (#11764)"

---

spec/labor/assign_tag_moderator_spec.rb

Fixes the following warning:
`WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`.`

Fix Rspec warning regarding specific error class

---

app/controllers/organizations_controller.rb

This uses the [`touch_all` method](https://blog.saeloun.com/2019/08/27/rails-6-touch_all-method.html) to bust a cache key in a user's profile organization section. Specifically, [this key](https://github.com/forem/forem/blob/19a048ecec30363b61db3891001808b3ea9b37c5/app/views/users/_sidebar.html.erb):
```ruby
<% cache "user-profile-sidebar-additional-#{@user.id}-#{@user.github_repos_updated_at}-#{@user.badge_achievements_count}-#{@user.organization_info_updated_at}", expires_in: 2.days do %>
```
Closes #11790
1. Enable caching in development `rails dev:cache`
2. Make an organization: /settings/organization/new
3. Update your organization's **name and slug**
4. Visit your profile page
5. See that your org's name is proper
6. See that your org's link sends you to the new slug
_Please replace …

Invalidate cache for all org users' profiles

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/buildkite.yml
.github/workflows/pr.yml

Add in GitHub workflow for adding the `ci` label to the PR and running Buildkite pipeline(s).
The `ci` label will allow the PR to be built on push without having to continuously issue the `/ci` trigger from a Forem team member.
```
build.pull_request.repository.fork != true || build.pull_request.labels includes "ci"
```
Also using the `/ci` trigger will run the initial pipeline builds too.

GitHub workflow for /ci trigger

---

app/services/edge_cache/bust.rb
app/services/edge_cache/bust_article.rb
spec/services/edge_cache/bust_article_spec.rb
spec/services/edge_cache/bust_spec.rb

My gameplan is to PR for each method I turn into a service. Once all methods are refactored into services, I'll then PR for each reference to the old `CacheBuster` to …

Add bust_article service

---

app/views/articles/tag_index.html.erb

The "feed" option in the select has a value of "blank" instead of "/", which means it doesn't do anything. This is a small fix to this.
Go to "small screen" home feed and toggle between feeds. You'll see now that you can leave the home feed but not come back.

Fix feed select dropdown

---

app/services/edge_cache/bust_events.rb
app/services/edge_cache/bust_page.rb
app/services/edge_cache/bust_podcast.rb
app/services/edge_cache/bust_tag.rb
spec/services/edge_cache/bust_events_spec.rb
spec/services/edge_cache/bust_page_spec.rb
spec/services/edge_cache/bust_podcast_spec.rb
spec/services/edge_cache/bust_tag_spec.rb

_I'm choosing to refactor a handful of methods/services at once in this PR since they're simpler and similar._
My gameplan is to PR for each method I turn into a …

Create services for busting pages, tags, events, and podcasts

---

.github/workflows/pr.yml

This will scope the PR workflow to only run when the pull request is initially opened to avoid late comments like this:
https://github.com/forem/forem/pull/11039#issuecomment-741631685

Scope PR workflow only run when the PR is opened.

---

app/lib/constants/site_config.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb

The img tags used in the config page doesn't have proper width and height specified. This PR addresses that and change some of the descriptions.
Please feel free to commit to this PR directly.
Resolves https://github.com/forem/InternalProjectPlanning/issues/293
0. Pull down this PR, set add the following role to your own local account `me.role(:single_resource_admin, Config)`
1. Start up the server, navigate to `/admin/config`
2. Click on the 'Images' dropdown.
3. All the images there shouldn't look out of proportion. Nothing should look too big or distorted.
I don't think there should be any concern here as I'm just changing the css.
I'll update the docs as soon as we come to an agreement
n/a

Update aspect ratio of images on the Admin's config page

---

.github/CODEOWNERS

Removed the old hells-bells team from the CODEOWNERS file and replaced @nickytonline with the frontend team. I think we could lean even more into this and add the backend team to here but wasn't sure how people felt about that yet so I am holding off.

Refactor:Remove old teams from CODEOWNERS and update general teams

---

app/views/layouts/_top_bar.html.erb

There is a current bug which is having the mod action button in the nav bar be _always_ present. There is one missing class we use to toggle this based on stuff we store client side about the user.
Manually change the `config_body_class` in `user_decorator` to verify that this is showing up properly or not. You'll probably need to refresh twice to see the change.
We _just_ implemented end-to-end testing with cypress and I think to get this hot fix in we should just ship, but this is the kind of thing that could warrant a regression test in the future.

Make mod button only show up for trusted user

---

app/services/edge_cache/bust_listings.rb
app/services/edge_cache/bust_organization.rb
app/services/edge_cache/bust_podcast_episode.rb
app/services/edge_cache/bust_user.rb
spec/services/edge_cache/bust_listings_spec.rb
spec/services/edge_cache/bust_organization_spec.rb
spec/services/edge_cache/bust_podcast_episode_spec.rb
spec/services/edge_cache/bust_user_spec.rb

_I'm choosing to refactor a handful of methods/services at once in this PR since they're similar._
My gameplan is to PR for each method I turn into a service. Once all …

Create services for busting organizations, podcast episodes, listings, and users

---

app/controllers/sidebars_controller.rb
app/views/articles/_sidebar_additional.html.erb

This fixes the issue with the async loading of the home sidebar when there is a campaign present. Hot fix.

Add campaign articles to sidebar controller

---

app/models/profile.rb
config/application.rb

Context:
1. We somewhat recently [merged a PR](https://github.com/forem/forem/pull/10707) that starts ignoring profile columns on  `User` and delegates them to `Profile` instead. This is supposed to be a temporary workaround so we can take our time to with updating existing app code to not rely on certain profile fields directly. This PR was open for a long time, because it was thoroughly tested by 
2. As part of this PR, @rhymes ]suggested an `after_initialize` hook](https://github.com/forem/forem/pull/10707#discussion_r535016233).
3. I [had my reservations](https://github.com/forem/forem/pull/10707#discussion_r535042360), but then decided to [implement the suggestion anyway](https://github.com/forem/forem/pull/11783).
4. Random bug reports about missing methods started showing up in …

Move back from after_initialize to explicit call

---

app/models/html_variant.rb
app/services/images/optimizer.rb
spec/models/html_variant_spec.rb

The current naive prefix logic for images here was only accounting for the cloudinary version. This modifies the logic such that it will also work for the imgproxy way.
Currently if an admin edits this file, they'll keep adding prefixes to infinity. This should aolve the issue.
This is a simple hotfix, but added regression test to ensure things are imrpved for the cases we care about.

Fix html variant image prefix logic

---

app/views/admin/listing_categories/_form.html.erb

This PR changes the social preview color in the listings category admin from a text field to an actual color input. It also changes the label from "Color hex" to "Social preview color".
Closes #11898

Make social preview color a color field

---

app/services/users/delete_articles.rb
app/services/users/delete_comments.rb
spec/services/users/delete_articles_spec.rb
spec/services/users/delete_comments_spec.rb

This PR updates references for busting comment cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustComment`.
My gameplan is to PR for each method so …

Update bust_comment to BustComment

---

app/controllers/admin/tools_controller.rb
app/services/users/delete_articles.rb
app/workers/articles/bust_cache_worker.rb
spec/services/users/delete_articles_spec.rb
spec/workers/articles/bust_cache_worker_spec.rb

This PR updates references for busting article cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustArticle`.
My gameplan is to PR for each method so …

Update bust_article to BustArticle

---

app/assets/javascripts/initializers/runtime.js

Turns out that when using the `ForemWebView` user agent the `AndroidBridge != undefined` check is raising an exception. It didn't appear before because the user agent check now is shared by both Android and iOS, causing the exception to be raised (because `AndroidBridge` is not defined in the iOS ForemWebView context).
This PR changes the check for this global so it works well on all platforms
Open your local environment and try to click on the ellipses (three dots) on any Article. It should open the modal/pop-up with the options to share the article (meaning that it doesn't break).
If you try out in Dev Tools console run these two lines:
```js
// Will likely raise an exception
AndroidBridge != undefined;
// Should return `false` unless AndroidBridge global is available
typeof …
```

Fix the way we check for AndroidBridge global

---

app/views/notifications/_follow.html.erb

In the event that the new follower box overflows, it's better that it be hidden vs escape the box.
There are alternatives to fixing this, maybe it spans multiple lines, but I think this hot fix is better than leaving the problem as it is.

Make followers notification overflow-hidden

---

app/workers/pages/bust_cache_worker.rb
spec/workers/pages/bust_cache_worker_spec.rb

This PR updates references for busting page cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustPage`.
My gameplan is to PR for each method so we can …

Update bust_page to EdgeCache::BustPage

---

app/views/events/index.html.erb
app/views/podcast_episodes/_meta.html.erb

This fixes the issue where there is an outdated DEV social image for `/pod` and `/events`... These are both secondary pages on the site and given current patterns, using the default social image makes sense.
Closes https://github.com/forem/forem/issues/11708

Add missing default social image (and remove DEV version) from /pod and /events

---

app/views/admin/events/_event_form.html.erb

This change makes the date-time picker significantly nicer.
The `datetime_select` elements are now placed within `fieldset` elements, this means the `fieldset` element is the child element in the flexbox column used by `crayons-field` rather than each `select` element.
There may be some additional padding needed on some of the elements.
Closes #11392 
There is an issue: Select elements should have an accessible name. 
I think this an issue with the `datetime_select` component not being accessible out of the box, this is also to be found on other pages, e.g. `admin/sponsorships/:id/edit`. This should probably be dealt with as a separate issue.

Improve date/time picker on admin/events/new

---

app/controllers/admin/users_controller.rb
app/controllers/users_controller.rb
app/views/users/_integrations_github_repositories.html.erb
lib/data_update_scripts/20201217162454_cleanup_orphan_git_hub_repositories.rb
spec/lib/data_update_scripts/cleanup_orphan_git_hub_repositories_spec.rb
spec/requests/admin/users_spec.rb
spec/requests/user/user_settings_spec.rb

Currently we need and use the GitHub user's token to fetch GitHub repositories for a user's profile. 
If they unlink their GitHub identity from Forem, the repositories remain but the user can't remove them. In addition, the server will keep not keep them updated because the authentication key has been deleted.
Now, if a user severes the connection between Forem and GitHub, their repositories will be removed as well.
I also added a data update script to remove existing orphan repositories in the `github_repos` table.
Closes https://github.com/forem/forem/issues/11918
1. open the admin and enable GitHub authentication at localhost:3000/admin/config or load the console and add both `:github` and `:twitter` to the `SiteConfig.available_providers` array (you also need to configure the global …

Remove GitHub repositories when GitHub identity is removed

---

config/environments/production.rb

From @rhymes comment
> Yep, although it's better than March 2019, it's still unclear why we keep short caching periods on fingerprinted static assets, see https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdev.to%2F ("Diagnostics -> Serve static assets with an efficient cache policy"). It's 30 days, it could be years.
This changes the `max-age` on instructions for local caching from 30 days to 3000 days, which seems long enough. 😅
I believe that having a more reasonably short `s-max-age` makes sense because this is a directive for the CDN, where we don't need to hold something for so long, but `max-age` will act as the proper directive for browsers to keep stuff around for a long time.
Closes https://github.com/forem/forem/issues/2147
Double check my logic on how …

Lengthen local caching max-age

---

.travis.yml
config/environments/test.rb

I've rerun the build 4 times for this PR and it's passed every time. I also created a forked branch PR as I noticed @Ridhwana's PR that ran into e2e issues was from a forked repo. I reran the build 4 times on #11978, and everytime it passed.
This potentially appears to be a rails 6 issue when `RAILS_ENV=test`. See https://github.com/rails/rails/issues/40613.
We have the following set in config/environments/test.rb
```
config.cache_classes = true
```
When `config.cache_classes = true` is set to true, apparently it will implicitly set `config.action_view.cache_template_loading` to true as well. The above mentioned Rails issue talks about that and also references [3.10 Configuring Action View](https://guides.rubyonrails.org/configuring.html#configuring-action-view) from the Rails …

Reenable End to End Testing... Again 😄

---

app/controllers/api/v0/organizations_controller.rb
spec/requests/api/v0/organizations_spec.rb

Missing `id` in the organization API controller `SHOW_ATTRIBUTES_FOR_SERIALIZATION` prevented Carrierwave from being able to generate the proper image route. 
Resolves https://github.com/forem/forem/issues/11937
The test should sufficiently provide that it's working but to manually see that it's working,
1. Pull down this PR and start up the Rails server.
2. Obtain an organization's name. An easy way to do that is to run `Organization.first.path` in Rails' console.
3. Access that organization via the API, ie  `http://localhost:3000/api/organizations/the-org-of-your-choice`
4. You should see a profile image URL listed. Prepend `localhost:3000` to it and it should provide you a proper image.
n/a
n/a

Fix API's broken organization image

---

app/views/layouts/_footer.html.erb

Footer links in the "Built on Forem" section should all open in a new tab and use `rel="nopener"`.
Currently some open in the same window and some open in a new tab but do not have the attribute.
1. load the PR
2. make sure the links open in a new tab

Add rel noopener to footer links

---

app/views/listings/index.html.erb

Following pattern from https://github.com/forem/forem/pull/11961 to generalize the social image on `/listings`
https://github.com/forem/forem/pull/11961

Use default social image on /listings

---

app/workers/follows/update_points_worker.rb
config/field_test.yml
spec/workers/follows/update_points_worker_spec.rb

In this PR https://github.com/forem/forem/pull/11675 we added a/b tests to see if any variant was a clear winner.
The results right now don't really show a clear winner (https://dev.to/abtests) however, I believe that there is a clear winner, but that this test was set up with a few flaws.
About a week into the test, "base" (which is the original _new_ feature) _was_ the clear winner across almost all the tests. It was winning by 10% to 20%.... But as the test has gone on, the results have become closer and seemed random. In inspecting the essence of what we are testing for to see success, this is just not a test that is built to run as long as this one.
Because our success metrics deem success if someone reaches some of these criteria _just once_ results become a little too random over …

Declare winner in update points worker

---

app/workers/events/bust_cache_worker.rb
spec/workers/events/bust_cache_worker_spec.rb

This PR updates references for busting events cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustEvents`.
My gameplan is to PR for each method so we …

Update bust_events to EdgeCache::BustEvents

---

app/workers/tags/bust_cache_worker.rb
spec/workers/tags/bust_cache_worker_spec.rb

This PR updates references for busting tag cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustTag`.
My gameplan is to PR for each method so we can …

Update bust_tag to EdgeCache::BustTag

---

app/controllers/admin/display_ads_controller.rb
spec/requests/admin/display_ads_spec.rb

This calls to bust the sidebar when an admin modifies an ad, to help the ad show up more quickly if relevant.

Bust sidebar when display ad is updated

---

lib/data_update_scripts/20201218173445_remove_collective_noun_from_config.rb

This PR contains a `data_update` script that removes `collective_noun` and `collective_noun_disabled` from the SiteConfig.
Relates to PR #11846 
Ensure that all of the checks pass! ♻️ Additionally, you can run the `data_update` script manually to ensure that upon running it, `collective_noun` and `collective_noun_disabled` are deleted.
N/A
We will need to ensure that this `data_update` script runs!

Remove collective_noun and collective_noun_disabled from the Config

---

lib/data_update_scripts/20201217184442_append_collective_noun_to_community_name.rb
lib/data_update_scripts/20201217184442_append_community_to_community_name.rb
lib/data_update_scripts/20201218173445_remove_collective_noun_from_config.rb

When I merged and deployed PR #11846, the `data_upate` script errored out, as shown [here](https://app.honeybadger.io/projects/66984/faults/72660309) on Honeybadger -- it appears that using the predicate method may have caused a `NoMethodError` error: 
```
NoMethodError: undefined method `collective_noun_disabled?' for #<Class:0x00007f5e4e055088>
```
This PR reverts the change from `SiteConfig.collective_noun_disabled?` back to what I initially had, `SiteConfig.collective_noun_disabled`.
Relates to PR #11846 and PR #11973 
Resolves https://app.honeybadger.io/projects/66984/faults/72660309
**To QA this PR, you can do the following:**
- Manually test the `data_update` script
- Ensure all checks pass ♻️ 
N/A
This `data_update` script …

Disable Community Name Data Update Scripts

---

app/workers/organizations/bust_cache_worker.rb
lib/data_update_scripts/20201026155851_resave_to_bust_cache_for_imgproxy.rb
spec/workers/organizations/bust_cache_worker_spec.rb

This PR updates references for busting the organization cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustOrganization`.
My gameplan is to PR for …

Update bust_organization to EdgeCache::BustOrganization

---

app/workers/podcast_episodes/bust_cache_worker.rb
spec/workers/podcast_episodes/bust_cache_worker_spec.rb

This PR updates references for busting a podcast episode cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustPodcastEpisode`.
My gameplan is to PR for …

Update bust_podcast_episode to EdgeCache::BustPodcastEpisode

---

app/workers/podcasts/bust_cache_worker.rb
spec/workers/podcasts/bust_cache_worker_spec.rb
spec/workers/rating_votes/assign_rating_worker_spec.rb

This PR updates references for busting podcast cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustPodcast`.
My gameplan is to PR for each method so …

Update bust_podcast to EdgeCache::BustPodcast

---

app/workers/listings/bust_cache_worker.rb
spec/requests/admin/listings_spec.rb
spec/workers/listings/bust_cache_worker_spec.rb

This PR updates references for busting a listing cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustListings`.
My gameplan is to PR for each method …

Update bust_listings to EdgeCache::BustListings

---

app/controllers/organizations_controller.rb
app/services/users/delete_articles.rb
app/services/users/delete_comments.rb
lib/data_update_scripts/20201026155851_resave_to_bust_cache_for_imgproxy.rb
spec/services/users/delete_articles_spec.rb
spec/services/users/delete_comments_spec.rb

This PR updates references for busting a user cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustUser`.
My gameplan is to PR for each method so we …

Update bust_user to EdgeCache::BustUser

---

app/controllers/admin/tools_controller.rb
app/controllers/application_controller.rb
app/controllers/profile_pins_controller.rb
app/models/article.rb
app/models/badge.rb
app/models/comment.rb
app/models/github_repo.rb
app/models/user.rb
app/services/moderator/banish_user.rb
app/services/moderator/merge_user.rb
app/services/users/delete.rb
app/workers/articles/bust_multiple_caches_worker.rb
app/workers/bust_cache_path_worker.rb
app/workers/reactions/bust_homepage_cache_worker.rb
app/workers/reactions/bust_reactable_cache_worker.rb
spec/models/badge_spec.rb
spec/models/github_repo_spec.rb
spec/services/users/delete_spec.rb
spec/workers/articles/bust_multiple_caches_worker_spec.rb
spec/workers/bust_cache_path_worker_spec.rb
spec/workers/reactions/bust_homepage_cache_worker_spec.rb
spec/workers/reactions/bust_reactable_cache_worker_spec.rb

This PR updates references for busting cache from `CacheBuster` to a new, dedicated service `EdgeCache::Bust`.
My gameplan is to PR for each method so we can test each …

Update bust to EdgeCache::Bust

---

app/services/site_configs/upsert.rb
spec/requests/admin/configs_spec.rb

Currently tags are created if an `Article` is saved, but otherwise the actual model doesn't exist, even if an admin makes it part of the list.
This leads to unexpected behavior where a tag can be listed on the sidebar, but not actually "exist"... This uses methods from `acts-as-taggable` to ensure tags exist as needed.
https://github.com/forem/forem/issues/11487

Create tag model if config updated

---

docs/backend/configuration.md

I fixed `Configuring Environment Variables` link on [this page](https://docs.forem.com/backend/configuration/) that shows `Page Not Found!` when clicking.

Fix broken link to configuring environment variables page

---

app/models/site_config.rb
lib/data_update_scripts/20201228194641_append_collective_noun_to_community_name.rb
spec/lib/data_update_scripts/append_collective_noun_to_community_name_spec.rb

This PR adds the `collective_noun` and `collective_noun_disabled` columns back to the `SiteConfig` model after running into a `data_update` script failure in another PR. This is necessary so that when running the `data_update` script responsible for updating the `community_name`, we have access to the `collective_noun` and `collective_noun_disabled` methods. Additionally, this PR adds a `data_update` script that conditionally updates `SiteConfig.community_name` _if_ `SiteConfig.collective_noun_disabled` returns `false`. If, however, the forem has `collective_noun_disabled` set to `true`, then the `community_name` will remain as-is and untouched.
Relates to PRs #11846 , PR #11973 , and PR #12054 
**To QA these changes, first ensure that all checks pass and the Travis build is green, …

Adds collective_noun Fields Back to SiteConfig Model

---

app/workers/users/bust_cache_worker.rb
spec/workers/users/bust_cache_worker_spec.rb

In https://github.com/forem/forem/pull/12051 I believe I missed a reference to `bust_user`. This PR updates references for busting a user cache from `CacheBuster` to a new, dedicated service `EdgeCache::BustUser`.
More specifically, we want to break up the methods in `CacheBuster` (i.e. `bust_comments`, `bust_article`, etc.) into their own services (i.e. `BustComment`, `BustArticle`, etc.). More on this approach can be found in [this comment](https://github.com/forem/InternalProjectPlanning/issues/ …

Cleanup bust_user

---

app/services/email_digest.rb
app/workers/articles/rss_reader_worker.rb
app/workers/emails/enqueue_digest_worker.rb
spec/services/email_digest_spec.rb
spec/workers/articles/rss_reader_worker_spec.rb

Recently we changed our site name on dev.to from DEV to DEV Community. This is used in our code in a couple of places and needs to be updated. From a prod console
```
irb(main):002:0> SiteConfig.community_name == "DEV Community"
=> true
```

Bug Fix:Update dev.to check to use DEV Community

---

app/javascript/listings/__tests__/ListingDashboard.test.jsx
app/javascript/listings/dashboard/rowElements/actionButtons.jsx
app/views/listings/delete_confirm.html.erb

This fixes an issue where in the listings dashboard, a listing's edit and delete buttons were HTML `<button>` tags, when they should be `<a>` tags that link to the proper page.
Closes #10937
1. Make a listing: http://localhost:3000/listings/new
2. Go to your listings dashboard: http://localhost:3000/listings/dashboard
3. Click the edit button and see that it routes properly
4. Click the delete button and see that it routes to `/:listing_slug/delete_confirm`
Don't think so! Just changed it to a regular link.
No
Can't load Giphy today :(

Use anchor tag instead of button for edit/delete links

---

app/views/articles/tags/_main_feed.html.erb
app/views/articles/tags/_sidebar_additional.html.erb

Rather than iterating over articles and creating each partial individually, [Rails allows us to load them as a collection](https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections) which can [speed up load time](https://medium.com/@coorasse/partial-rendering-performance-in-rails-101fdfb6ffb9). We do this in quite a few places in the code. This just addresses 2 places where I noticed it initially. 
https://github.com/forem/InternalProjectPlanning/issues/273
* Load tag pages and note that you will see the following log instead of 10 separate partial loads
```
Rendered collection of articles/_widget_list_item.html.erb [10 times]
```

Optimization: Convert tags/_main_feed and widget_list_item partial loads to collections

---

app/models/article.rb
app/models/organization.rb
spec/lib/data_update_scripts/update_articles_cached_entities_spec.rb
spec/models/organization_spec.rb

We had a couple of bugs showing up here.
1. When an organization is deleted we were not updating the associate article Elasticsearch documents.
2. Upon finding 1, I also discovered we were not updating the `cached_organization` on articles when an organization was removed. 
Why didn't we notice this sooner? 
We didn't notice this sooner bc technically we will not destroy an organization if it has any associated articles according to our organization policy.
```ruby
def destroyable?
organization_memberships.count == 1 && articles.count.zero?
end
```
Regardless, I still think having these in place would be a good idea in the event we remove that requirement one day OR in the event someone manually removes an organization from a console. Ideally, you don't want that to happen but this …

Bug Fix:Update Article Cached Org and Docs When Org is Deleted

---

app/services/images/optimizer.rb
app/view_objects/cloud_cover_url.rb
spec/services/images/optimizer_spec.rb
spec/views/dashboards/show.html.erb_spec.rb

This feature adds the `max_bytes` default option to help reduce the size of overly big images. This will automatically add optimization only where it is most needed... On the most over-sized images.
This is related to this PR: https://github.com/forem/forem/pull/12089
But as noted, some of that is better implemented with imgproxy ENV vars. But this one seems appropriate.

Add `max_bytes` to imgproxy.

---

app/assets/stylesheets/admin.scss
app/views/admin/badge_achievements/index.html.erb
app/views/admin/moderator_actions/index.html.erb
app/views/admin/mods/index.html.erb
app/views/admin/organizations/index.html.erb
app/views/admin/permissions/index.html.erb
app/views/admin/podcasts/index.html.erb
app/views/admin/privileged_reactions/index.html.erb
app/views/admin/sponsorships/index.html.erb
app/views/admin/users/index.html.erb

There are some formatting issues on some of the tables on the admin page. These include:
- ID's that are overflowing on two lines (see /admin/users)
- Columns that are taking up too much space causing words to wrap unnecessarily
- and more... 
I've attached screenshots in the relevant sections. 
I was tempted to change the css from 
```
.crayons-card {
overflow-wrap: anywhere;
}
```
to 
```
.crayons-card {
overflow-wrap: break-word;
}
```
since this solves some of the formatting issues outlined. However, it also causes the table to exceed the width of the screen, whereas ` overflow-wrap: anywhere;` ensures that the overflow is managed in such a way that the table does not exceed the width of the viewport width. 
_Hence, I went with overriding the specific columns that we don't want to …

Override specified line break behaviour on the ID column

---

.travis.yml

Temporarily ignore a low-severity vulnerability to unblock deployment.

Update bundle-audit to ignore CVE-2020-26247

---

docker-compose.yml

The default retry interval for dockerize when using the `wait`
parameter is 1s. Because it takes several seconds, at least, to boot
up elasticsearch and bundler, the `rails` and `webpacker` services
generate a number of retry messages.
The `seed` and `sidekiq` services both wait for `rails` service to be
up and running. That takes time as well, and these two generate a
sometimes overwhelming level of output.
This change sets the retry interval for dockerize to 10s for `rails`
and `webpacker` and 20s for `seed` and `sidekiq`. These choices are
fairly arbitrary, but aim to strike a balance between keeping the
output readable as services start and not excessively delaying start
times.
With bad luck, this could delay start up on the order of 30s. However,
the increased awareness of where the …

Use wait-retry-interval parameter for dockerize

---

app/javascript/shared/components/tags.jsx
app/views/articles/_v2_form.html.erb

This is a couple low-hanging fruit to fix some behavior in the "write a post" form.
This prevents the "jump" between the server rendered and client rendered view... It does this by eliminating some of what gets rendered on the server. It replaces it with more of a blank canvas until the rest of the form is rendered. The "jump" is most jarring on mobile. I think this will particularly improve that context.
The other small thing is to not render the row in the tag dropdown if that value has already been searched for. So if you type `j` in the tag bar, and select `java`, the next `j` you add will _not_ have `java` in the list.
These are a few low-hanging fruit for usability and code cleanliness.

Small clean ups in post form

---

app/javascript/article-form/components/ArticleCoverImage.jsx

The native bridge interface now supports a `ratio` param on top of the DOM element id and this PR adds the ratio restriction to cover images. This way we're making sure users will always crop perfectly to fit the cover images aspect ratio.
This `ratio` param is optional and the normal image upload in the Editor doesn't use it. This allows users to upload image without the final crop step.
- https://github.com/forem/ForemWebView-ios/issues/21
- https://github.com/forem/ForemWebView-ios/pull/22
This recording shows both image upload steps. The cover image has a final step that forces the user to select a final crop on the images but the image upload doesn't (allowing for any aspect ratio)
https://share.getcloudapp.com/RBu9A4A6
None

Adds ratio param to Cover Image native bridge image picker

---

.travis.yml

Essentially reverting 3764cd6. For some reason, this works again but caches are still not showing up on Travis's dashboard. This should be a UI issue as the cache is working as expected.
n/a
How to verify that it is actually working? There are two dependencies command to look for
`bin/ci-bundle` and `yarn install --frozen-lockfile`. 
Each of these should not take more than 5 seconds.
This is a tiny image but it shows that it took only 1.8 second to run yarn install.
n/a

[Travis] Use directories cache for Bundle and Yarn

---

Gemfile.lock

After setting up Forem on Big Sur, a Darwin-20 version of the `libv8` gem was added to the `Gemfile.lock` file. Following @rhymes prior art in https://github.com/forem/forem/pull/12031, I'm thinking we should commit this change.
(I'm curious why this is happening now though: perhaps libv8 binary gems? Are we going to have to add this for ever type of environment libv8 runs in?!)
https://github.com/forem/forem/pull/12031

Add libv8 library for MacOS 11.0 Big Sur

---

app/lib/constants/role.rb

I have needed to add a Resource Tag admin twice now and both times I had to do it through a console since its not an option in admin. This changes that :) 
1. Go to `/admin/users`
2. Click on any user and select "Manage User"
3. Add the "Resource Admin: Tag" option and they should be able to work with tags in admin.

Feature:Add ability to add a Tag Resource Admin through Admin

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
spec/system/comments/user_fills_out_comment_spec.rb

As outlined in Issue https://github.com/forem/forem/issues/11912: when a use encounters an error with their comment posting, the 'rate limit' modal is displayed instead of an error message. Previously NOTHING was displayed: this PR at least displays the content of the error message.
Long term better error messaging would be desirable, but at least for now this will let users know they aren't actually hitting a rate limit.
resolves https://github.com/forem/forem/issues/11912
https://github.com/forem/forem/pull/11102
1. Attempt to post a comment that contains an error. An easy way to do this is by posting the exactly same comment twice, or using a Twitter liquidtag on a Forem instance that doesn't not have Twitter API keys set.
[Admin …

Show comment posting errors

---

app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
app/models/profile.rb
app/policies/user_policy.rb
app/services/profile_fields/add_work_fields.rb
app/views/articles/_user_metadata.html.erb
app/views/pages/_privacy_text.html.erb
app/views/users/_metadata.html.erb
db/migrate/20210108031718_remove_looking_for_work_from_users.rb
db/schema.rb
lib/data/dev_profile_fields.csv
lib/data_update_scripts/20210108033107_remove_looking_for_work_profile_fields.rb
spec/lib/data_update_scripts/create_profile_fields_spec.rb
spec/services/profiles/update_spec.rb

This PR removes the columns `looking_for_work` and `looking_for_work_publicly` from the `users` table. It also removes code using these columns and has a data update script for removing the associated profile fields that were meant to replace them. The columns where previously due to profile generalization work, so we can just go ahead and remove them.
Question: we have a somewhat related column for "Recruiters can contact me about job opportunities", should we remove this too as part of this PR? /cc @vaidehijoshi
https://github.com/forem/internalEngineering/issues/366
Nothing specific, the specs should cover this. You can go to `http://localhost:3000/settings` and verify that the checkbox in the "Work" section is gone after the data update script removed the profile field.
None
-

Remove looking for work columns

---

config/routes.rb

I noticed that we recently lost our ability to run POST/PUT/DELETE requests in Sidekiq. When I dug into it I found the following error. The error traces back to a [deprecation message that is triggered](https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/http_origin.rb#L37) bc we were using. `origin_whitelist` instead of the updated `permitted_origins`. This updates to use the new method in hope that it will fix this issue bc not triggering that warning code.
```
ArgumentError: wrong number of arguments (given 1, expected 2)
set_cookie_domain.rb  13 call(...)
[PROJECT_ROOT]/app/middlewares/set_cookie_domain.rb:13:in `call'
11       env["rack.session.options"][:domain] = ".#{SiteConfig.app_domain}"
12     end
13     @app.call(env)
14   end
15 end
Full …
```

Bug Fix:Use permitted_origins Instead of Deprecated origin_whitelist

---

config/environments/development.rb

ENV["COMMAND"] no longer seems to be present when a rails command is run. I am not sure when this changed but I have updated our code to use a different method to detect a console or server start in order to prevent it from succeeding if there are data update scripts that need running. 
https://github.com/orgs/forem/projects/6#card-48564710
1. Open a console locally
2. run `DataUpdateScript.last.destroy`
3. close the console
4. Try to reopen the console or start a rails server. Both should fail.
5. run `bundle exec bin/setup`
6. You should be able to open a console and start a server now.

Bug Fix:Fix development.rb to Correctly Detect Rails command

---

db/migrate/20210111151630_add_index_to_users_feed_fetched_at.rb
db/schema.rb

`Feeds::Import` at each run selects users based on `feed_fetched_at` - since #12126 was deployed. We forgot to add an index on that field.
#12126
Nothing, trust the wind

Feeds::Import: add index to users.feed_fetched_at

---

app/services/moderator/manage_activity_and_roles.rb

This updates the admin trusted adding to use `TagModerators::AddTrustedRole` instead of a custom method within the class. Overall this is cleaner and reuses code, and more importantly is safer (can't add banned users).
N/A
1. Try to add trusted to a user
2. See that it works
Nope
No

Use an updated version of adding trusted for admins

---

app/services/twitter_client/client.rb
spec/services/twitter_client/client_spec.rb

Currently we use the `SiteConfig` version of the Twitter keys _only_ for authentication, but still ENV vars for fetching tweets.
I think there are some further adjustments we can make to the Forem Cloud setup such that we actually could provide apps with our own fallback keys in most cases, but we should always use theirs first.
https://github.com/forem/forem/issues/10836

Use SiteConfig twitter keys before env

---

app/models/user.rb

We removed the `looking_for_work` and `looking_for_work_publicly` columns in `https://github.com/forem/forem/pull/12173`, this PR follows up and removes them from the `ignored_columns` list on `User`.
https://github.com/forem/internalEngineering/issues/366
n/a
n/a

Remove looking for work columns from ignore list

---

app/views/articles/tags/_sidebar.html.erb

Quick little route fix for @pkfrank 
Fixes: https://github.com/forem/forem/issues/12212
1. Go to a tag page and click on the Admin button and you should be redirected to the proper edit page in admin

Bug Fix:Update Admin Route in View to go to Edit page

---

.slugignore
.travis.yml
scripts/after_deploy.sh

This will add a marker to our Honeycomb board whenever the app is deployed to Heroku. It provides additional context used for debugging and analytics.
[Honeycomb's documentation](https://docs.honeycomb.io/api/markers/#create-a-marker)
Resolves https://github.com/orgs/forem/projects/6#card-52224759
This is a curl command. I've tested it thoroughly locall.y If it doesn't work, it wouldn't cause any problem and I'll address it immediately.
here's what the feature looks like. It's the dotted line.
n/a

[Travis] Create after_deploy Honeycomb script

---

app/views/articles/show.html.erb
app/views/users/_meta.html.erb
spec/requests/user/user_profile_spec.rb

While doing some research for an RFC earlier today, I noticed that we are a bit inconsistent in our meta tag usage and use both `robots` and `googlebot`. This PR standardizes on the more generic `robots` as I don't think we ever want to restrict `noindex` and `nofollow` specifically to Google only.
n/a
n/a
n/a

Standardize bot meta tags

---

app/controllers/users_controller.rb

We have a bug where we are seeing params get sent to the server during the onboarding flow but then when the server processes them they seems to "disappear". This logging is an effort to try and get us more clarity into what is happening. When I looked into this I found that there are 2 different traces for onboarding_checkbox_update when email_digest is present in the params which seems weird. https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/2qwrFBqJnXC?tab=raw
Trace 1: This does NOT have any sql update, it  loads the user checks a couple things, enqueues a cache bust and indexing job but that is it https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/2qwrFBqJnXC/trace/FpFCLEBCoeE
Trace 2: This DOES update the user with the params. Then does all the redis things. …

Log onboarding_checkbox_update Params

---

app/controllers/registrations_controller.rb
cypress/integration/loginFlows/initialAdminLogin.spec.js
spec/system/authentication/user_logs_in_with_email_spec.rb

Before, some emails were not encoded properly, `andy+hi@forem.com`. This PR ensures that the email is always encoded before redirecting, so that symbols like `+` are not scrubbed accidentally.
Closes https://github.com/forem/internalEngineering/issues/105
1. Visit localhost:3000/confirm-email?email=some+email@test.com
2. Check that it properly displays on the page and form
Nope!
Nope

Encode emails properly before sending to /confirm-email

---

app/controllers/admin/tags_controller.rb
app/views/admin/tags/index.html.erb
spec/system/admin/admin_views_tags_spec.rb

This adds sorting options to `/admin/tags`, and also uses Ransack for all search / sorting related functions. And... that's pretty much it.
Closes https://github.com/forem/internalEngineering/issues/225
1. Visit `localhost:3000/admin/tags` as an admin
2. Click on the headers, name, ID, alias for, and test that the sorting works
3. Click on Supported or Unsupported and see if sorting works there
4. Complete a search with the search function and try to sort your results
Screenshot of sorting arrows (Ransack default):
The sort links should have aria labels for them. Also added some other aria labels for links. Not sure if I needed to add `#{tag.name} tag` to the tag links, but it seemed to make more sense to me?
Nope

Add sorting feature to /admin/tags

---

app/controllers/users_controller.rb

This is a follow up to #12252 after discovering the following:
If `email_digest_periodic` and `email_newsletter` are both false I have found that those traces do not have update commands. Rails is smart enough to figure out that if nothing on the model is being updated then it doesnt hit the database with an update command.
```
[14] pry(main)> u.assign_attributes(email_digest_periodic: false)
=> nil
[15] pry(main)> u.save
(0.3ms)  BEGIN
BanishedUser Exists? (0.3ms)  SELECT 1 AS one FROM "banished_users" WHERE "banished_users"."username" = $1 LIMIT $2  [["username", "mstruve"], ["LIMIT", 1]]
User Update (0.6ms)  UPDATE "users" SET "email_digest_periodic" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["email_digest_periodic", false], ["updated_at", "2021-01-13 21:26:35.351201"], ["id", …
```

Log User Save Error Messages When it Fails

---

.github/dependabot.yml

Dependabot [automatically creates](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#labels) labels based on the language or ecosystem of the dependency its going to update, which in our case means `javascript` and `ruby` 99% of the time. 
We don't want those.
Delete the actual [javascript](https://github.com/forem/forem/labels/javascript) and [ruby](https://github.com/forem/forem/labels/ruby) labels from the repo

Dependabot: disable language/ecosystem labels attached to PRs

---

Gemfile.lock

After upgrading to Bundler 2.2 locally, I had problems bundling on Linux. This is caused by older bundler versions not recording platform-specific information in the lockfile, but trying to resolve it at installation time instead.  I explicitly added support for `x86_64-linux` with `bundle lock --add-platform x86_64-linux` and can now bundle again. 
See [this issue](https://github.com/rubyjs/libv8/issues/310) for context, specifically [this comment](https://github.com/rubyjs/libv8/issues/310#issuecomment-744372178) outlining the problem and [this comment](https://github.com/rubyjs/libv8/issues/310#issuecomment-744461218) with the solution.
n/a
Install Bundler 2.2 on Linux and verify that you can successfully run `bundle install`, especially `bundle install --local`.
n/a

Update Gemfile.lock for Bundler 2.2

---

app/models/user.rb
app/services/broadcasts/welcome_notification/generator.rb
app/views/users/_additional_authentication.html.erb
config/initializers/devise.rb
spec/models/user_spec.rb

#11934 added SIWA (Sign in with Apple) in beta mode (feature flag). We found a problem that made it impossible to connect existing accounts with SIWA ([more info here](https://forem.team/fdoxyz/samesite-cookies-and-siwa-39if)).
#12114 is currently blocked due to that problem so we are going to wait until we can sort that out before taking SIWA out of beta.
This PR adds a workaround to avoid showing the option to connect existing accounts with SIWA in order to enable it for DEV, until we are able to finish #12114 
#11934
#12114 
Apple auth workflow remains unchanged (available in https://community.benhalpern.com) but now the button to connect an existing account shouldn't be visible in `/settings`. In order to check this you can try out these steps:
1. Enable Twitter/GitHub/Facebook auth …

Workaround for Apple auth problems (still in beta)

---

.rubocop.yml
spec/requests/comments_spec.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb

Rubocop 1.8 added a bunch of new rules, this enables them https://github.com/rubocop-hq/rubocop/releases/tag/v1.8.0
Most of them are for Ruby 3.0, I reckon they are going to help with the transition in the future.
https://github.com/rubocop-hq/rubocop/releases/tag/v1.8.0

Enable new rules and run Rubocop autocorrect

---

app/views/admin/configs/_apple_auth_provider_settings.html.erb
spec/system/authentication/creator_config_edit_spec.rb

Our test suite had coverage for OAuth providers user-facing flow, but because of a recent refactor the `/admin/config` flow broke when the `:apple_auth` feature flag is enabled (pretty specific and difficult for to detect manual QA).
This PR fixes the bug and introduces a very simple spec where we check for the available providers in `/admin/config`
In `master` if you enable the feature flag `Flipper.enable(:apple_auth)` and visit `/admin/config` you'll run into a broken page. With this PR the error shouldn't appear and the page should continue to work as expected.
None

Fix creator flow in /admin/config when :apple_auth feature flag is enabled

---

app/models/identity.rb

Rare occurence of missing auth_data_dump from the oauth provider caused email method to return NoMethodError. 
Fix uses safe navigation operator to ensure presence of auth_data_dump:info:email to retrieve email, prints "no email found, please relink.." string when no email found.
#11936 
Tested locally overwriting auth_data_dump = nil, what replicated the reported issue.
No email found string successfuly fills in the #{provider}.
N/A

secure Identity#email in case of missing auth_data_dump hash (#11936)

---

app/javascript/.storybook/preview.js
app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
app/javascript/crayons/Dropdown/__stories__/dropdown-css-helper.scss
app/javascript/crayons/Dropdown/__stories__/dropdown.html.stories.jsx
app/javascript/crayons/Dropdown/__stories__/dropdowns.md

This PR updates the Dropdown Storybook stories so that they are keyboard accessible. The dropdowns can now be opened  and closed by keyboard (Enter / Esc), and can also be closed by clicking outside of the dropdown.
Notes have been added to the stories to give context on accessibility implications when using the dropdown component.
This PR ensures that our Storybook documents accessible usage of the Dropdown component, however wider work is needed to ensure all dropdowns used throughout the app are consistently handling keyboard events and focus in a way optimised for accessibility. This will need to be a generalised approach that accounts for both Preact and non-Preact usage. A new issue has been created for this here: #12297 
Closes #11724 - Storybook dropdown should be accessible
- …

Storybook dropdown should be accessible 11724

---

app/javascript/chat/ChatChannelSettings/ChatChannelSettings.jsx

_Supersedes: https://github.com/forem/forem/pull/9870 (@jacobherrington)_
The messages passed from the back end to the front end when leaving a chat channel are never displayed, this PR addresses that.
I intended to fix this together with #9502, which got fixed by #9804.
Leave a chat channel and see a snackbar notification appear.
Nope.

Display message from the back end when leaving a channel

---

app/services/images/optimizer.rb
app/services/slack/messengers/article_published.rb

Fix some deprecation warnings in _Images::Optimizer_ and _Slack::Messengers::ArticlePublished_. See the commit messages for the deprecation warnings which were addressed.
References #11282 (There are more deprecation warnings, so it's not closing the issue)

Fix deprecation warnings

---

config/initializers/audit_events.rb
config/initializers/carrierwave.rb
config/initializers/honeybadger.rb
config/initializers/reverse_markdown.rb

In #8766 we enabled Rails 6 new autoloader - Zeitwerk - but there were a bunch of deprecation that were left behind. 
- #8766
- https://discuss.rubyonrails.org/t/initialization-autoloaded-the-constants-x-y-and-z-isnt-enough-information/74719/11
- https://discuss.rubyonrails.org/t/initialization-autoloaded-the-constants-x-y-and-z-isnt-enough-information/74719/12
- https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots
1. on `master`, load the console with `bundle exec rails c`, see this blob of text:
```text
DEPRECATION WARNING: Initialization autoloaded the constants Audit, Audit::Helper, Audit::Subscribe, Images, Images::Optimizer, RateLimitChecker, ReverseMarkdown::Converters::CustomPre, and ReverseMarkdown::Converters::CustomText. …
```

Fix autoloading deprecation

---

app/views/pages/_editor_guide_text.html.erb
app/views/pages/_v1_editor_guide_preamble.html.erb

Adds a permalink icon/link to each of the headings in `/p/editor_guide`. Linked icon is hidden until a user hovers over the heading, or tabs to it with the keyboard.
Closes #4507 - Feature request: Add linkable "id" to each Editor Guide section headers
- When a user hovers over a heading on the `/p/editor_guide` page, a link icon appears
- Icon links to the heading's anchor ID & clicking it takes you to that location on the page
- Link icons are also shown when a user tabs through the content of the page with the keyboard, becoming visible on focus, and disappearing when unfocused again
- On mobile devices the link icon becomes visible if the heading is tapped on (since there's no hover)
- The new permalinks are surfaced to screen reader users as "permalink for { heading name }"
I've …

Add permalink to editor guide headings

---

.github/CODEOWNERS

Since we no longer have a dedicated OSS team and will be working off of our rotation I am removing the OSS team from Github. This means we will no longer use it via CODEOWNERS so I have removed it and replaced it in a couple of places with the Backend team. 
I thought about trying to update the team every week with the new people on the rotation but that seemed like it would be too much manual work and that I would eventually start missing or forget so I decided to remove it instead. Let me know if anyone else has thoughts or suggestions regarding this!

Remove OSS team from CODEOWNERS file and add backend team

---

app/models/site_config.rb
app/models/user.rb
app/services/mailchimp/bot.rb
spec/services/mailchimp/bot_spec.rb

This fixes a bug where when destroying a user, we try to unsubscribe them from newsletters that don't exist. This previously had a runtime error with the Mailchimp API where a blank/invalid Mailchimp API key was given when trying to destroy a user.
For the most part, new Forem communities do not have Mailchimp set up. This PR adjusts for that typical situation.
Closes https://github.com/forem/internalCommunity/issues/2
1. Start `rails console --sandbox`
2. Set `SiteConfig.mailchimp_api_key = ""`
3. Attempt to destroy a user: `User.first.destroy`
4. See that it destroys the user successfully
No UI changes
No

Don't try to unsub users when destroying if Mailchimp is not enabled

---

app/models/navigation_link.rb
app/views/admin/navigation_links/_form.html.erb
app/views/admin/navigation_links/index.html.erb
lib/data_update_scripts/20210119060219_make_local_navigation_links_relative.rb
spec/factories/navigation_links.rb
spec/lib/data_update_scripts/make_local_navigation_links_relative_spec.rb
spec/models/navigation_link_spec.rb

When a Forem switches over from the `forem.cloud` subdomain to its live domain, the Navigation Links in the sidebar don't update. To fix this @benhalpern suggested the following plan:
https://github.com/forem/internalEngineering/issues/179
Updated copy to mention relative URLs explicitly:
1. As admin go to http://localhost:3000/admin/navigation_links
2. Try to enter an invalid URL (e.g. "test"), this should not work.
3. Try to enter a relative URL (e.g. "/test"), this should work.
4. Enter an invalid external URL (e.g. "ftp://example.com"), this should not work. 
5. Enter an external URL (e.g. "https://example.com"), this should work.
None

Update NavigationLink handling

---

app/javascript/onboarding/components/EmailPreferencesForm.jsx
app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/ProfileForm.jsx

1. Adding role dialog
2. Adding aria-labelledby and aria-describedby
https://github.com/forem/forem/issues/9585
When navigating the app with keyboard and screen reader on it should read out  aria-labelledby,  aria-describedby of the on-boarding modal
NA

Adding aria labels and role to onboarding modal

---

app/views/notifications/_badgeachievement.html.erb
lib/data_update_scripts/20210121161149_clear_badge_achievement_notification_cache.rb

We had a bug where we cached the custom rewarding message for the notification a user receives when they are awarded a new badge. This fixes it by removing the cache altogether, since it wasn't really preventing any N+1 calls.
Closes #11957 and closes #11646
1. Paste this into `rails console`:
```
ba = BadgeAchievement.create!(badge_id: 1, rewarding_context_markdown_message: "test", user: User.last)
Notifications::NewBadgeAchievement::Send.call(ba)
```
2. Visit `localhost:3000/notifications`, you can add `?username=User.last.username` if you ended up using the last user instead of yourself. You'll need to be a `super_admin`.
Nope
Nope, the data update script should take care of things.

Cache only the static badge achievement data for notifications

---

app/views/admin/articles/index.html.erb

I came across an extra `href=""` in `admin/articles/index.html.erb` while working. This PR removes the superfluous `href=""` from the view.
N/A
**BEFORE**:
- Navigate to `/admin/articles` and click on the "Satellite" tab:
- Observe the `ActiveRecord::RecordNotFound at /admin/href=` error displayed in your browser:
**AFTER**:
- Navigate to `/admin/articles` and click on the "Satellite" tab:
- Observe that you no longer run into this error and are instead, shown the "Satellite" page:
N/A
N/A

Remove Extra href from Admin Articles Index

---

app/controllers/users_controller.rb
spec/system/user/user_self_destroy_spec.rb

This PR adds error logging to Honeycomb to `UsersController#confirm_destroy`. In the event that there is a token mismatch between the `destroy_token` and `params[:token]`, the user's ID, `destroy_token`, and `params[:token]` will be logged to Honeycomb for debugging purposes. Additionally, this PR refactors `#confirm_destroy` ever so slightly to make the conditional a little bit more readable and adds tests around Honeycomb error logging to the existing `user_self_destroy_spec.rb`.
Relates to PR #12266
Please make sure that all checks pass and that Travis builds green! ♻️ 
N/A
N/A
**🐝 🍯**

Log Relevant Data from Self-Deletion Flow to Honeycomb

---

app/javascript/article-form/articleForm.jsx
spec/system/articles/user_fixes_a_draft_spec.rb

#12131 described a workflow that led to the accidental publishing of a draft post after fixing validation errors. This PR fixes that.
#12131 
Follow the steps as outlined in the original issue and ensure that you still have the option to save a draft at the last step, not only "Save changes".
- Create a new blog post
- Add something that is validated, for example: `{% codepen https://codepen.io/DonKarlssonSan/pen/dyMaRJN default-tab=result %}`
- "Save draft"
- Edit the blog post
- Change the content to something that is not valid, for example: `{% codepen https://codepen.io/DonKarlssonSan/pen/dyMaRJN default-tab="result" %}`
- Click "Save draft"
- An error message is displayed: "Whoops, something went wrong: base: Invalid Options"
- Fix the error (remove the "" around result)
-  There …

Fix accidental publishing of draft articles

---

Gemfile

These two gems were originally added in https://github.com/forem/forem/pull/7458 with the intention of speeding up system spec. What we just noticed now is that `mini_racer` comes with large dependencies that are about ~200 MB total.
If there's an area I expect this to slow down is overall compilation during deployment. I don't think there should be any performance impact elsewhere.
Resolves https://github.com/forem/forem/pull/12378
n/a
Keep an eye on production!

Move mini_racer and sassc-rails out of production

---

app/views/layouts/_asset_reconciliation.html.erb
app/views/layouts/_styles.html.erb
app/views/layouts/application.html.erb
app/views/shell/_top.html.erb
spec/requests/stories_index_spec.rb

There is an bug with the timing of how all the CSS is loaded from cold. There is evidence that Google is detecting this as a cumulative layout shift problem that needs to be adjusted, and anecdotally I have run into this occasionally myself.
More details in the linked issue, but here's the visual:
https://user-images.githubusercontent.com/3102842/105424035-8ecf8c80-5c14-11eb-9eaa-d5f8653ce43b.mov
I speculate that all the variables we use in CSS trips up the content rendering tree and we get a flash of the "user agent styling" mid-way through rendering the content. It only shows up for non-logged-in traffic, and I believe this is due to the fact that we run less blocking JS on non-logged-in traffic (a good thing). Signed in traffic incidentally gets other render-blocking resources to hide …

Fix flash of unstyled content

---

db/migrate/20210125085442_add_indexes_to_ahoy_messages_feedback_message_id_and_feedback_messages_status.rb
db/schema.rb

DEV has 30+ million email messages, to display some of them to the admin, they
all are scanned to find those that belong to the requested feedback messages.
This results in SQL queries that can take up to 15 seconds.
By adding an index, we cut the SQL response time to milliseconds.
This is the query (found [via Datadog](https://app.datadoghq.com/apm/resource/practical_developer-postgres/postgres.query/95589555382369c8?end=1611565561961&env=production&index=apm-search&maxPercentile=100&paused=false&query=env%3Aproduction%20service%3Apractical_developer-postgres%20operation_name%3Apostgres.query%20resource_name%3A%22SELECT%20ahoy_messages%20.%20to%2C%20ahoy_messages%20.%20subject%2C%20ahoy_messages%20.%20content%2C%20ahoy_messages%20.%20utm_campaign%2C%20ahoy_messages%20.%20feedback_message_ …

Optimize Admin::FeedbackMessagesController by adding proper indexes

---

app/controllers/admin/articles_controller.rb
app/models/user.rb
app/services/article_api_index_service.rb
app/services/articles/feeds/large_forem_experimental.rb
app/services/articles/get_user_stickies.rb
app/services/articles/suggest_stickies.rb

When `acts-as-taggable-on`'s `.tagged_with()` is used with `any: true`,
the gem will use `SELECT *` regardless of any previous (or following) requests
of selecting a limited amount of columns.
Given that the `articles` table has [73 columns](https://dev.to/admin/blazer/queries/314-number-of-columns-in-all-tables)
that will amount to wasted RAM memory for columns we don't need.
By "unscoping" any previous `select()` we can optimize used memory.
Before:
```ruby
[24] pry(main)> Article.tagged_with([:ruby], any: true).select(:id, :name).to_sql
=> "SELECT \"articles\".*, \"articles\".\"id\", \"name\" FROM \"articles\" WHERE EXISTS (SELECT * FROM \"taggings\" WHERE \"taggings\".\"taggable_id\" = \"articles\".\"id\" AND \"taggings\".\"taggable_type\" = 'Article' AND \"taggings\".\"tag_id\" IN …
```

Optimize column selection for articles belonging to "any" given tag

---

app/views/admin/configs/show.html.erb

Description for `periodic_email_digest_min` field is currently
`periodic_email_digest_max`, but it should be `periodic_email_digest_min`
n/a
You can view the description fix at admin/config -> email digest frequency tab.
n/a
n/a

Fix Typo: should be "min" not "max"

---

config/initializers/sidekiq.rb

When in OSS Rotation we merged the `sidekiq-unique-jobs` [bump to 7.x](https://github.com/forem/forem/pull/12361) version but we missed [this note](https://github.com/mhenrixon/sidekiq-unique-jobs#add-the-middleware) that mentions we need to manually add the middleware in order for it to work properly (it wasn't this way before).
I realized the locks weren't being enforeced while working on [this spike PR](https://github.com/forem/forem/pull/12419)
#12361
Add this dummy worker:
```ruby
class UniqueJobsWorker
include Sidekiq::Worker
sidekiq_options queue: :low_priority,
retry: 10,
lock: :until_executed,
on_conflict: :replace
def perform
puts "SiteConfig.app_domain: #{SiteConfig.app_domain}"
end
end
```
Boot the app locally with `bin/startup` and in a separate console run this:
```ruby …
```

Explicitly adds the unique jobs middleware

---

Containerfile

Since we have removed mini_racer from the Gemfile we need to have a js runtime inside the container

Add nodejs to the production container

---

app/controllers/confirmations_controller.rb
config/routes.rb
spec/system/authentication/user_request_confirmation_spec.rb

This PR adds clearer messaging on the `/confirm-email` page via the global flash.
Closes https://github.com/forem/security/issues/333
1. Go to `/confirm-email`
2. Enter an email address and submit the form
3. Ensure you are on `/users/confirmation` (we render and don't redirect) and see the following flash message.
n/a

Add flash message for email confirmation

---

app/assets/stylesheets/components/modals.scss
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/components/Close.jsx
app/javascript/article-form/components/Header.jsx
app/javascript/article-form/components/__tests__/Close.test.jsx
app/javascript/crayons/Modal/Modal.jsx

This PR closes #11753, by warning a user before they leave the edit post page. Without this modal it can be a jarring experience to the user to click the x navigate away from the page.
You can go to `/new` and test it out
Currently the `x` on the modal doesn't escape with keyboard navigation but it looks like that will be fixed by #12428

updates article form to have warning modal

---

app/views/pages/contact.html.erb
spec/requests/pages_spec.rb

Closes https://github.com/forem/forem/issues/12371 🎉 
Run the app locally, and head to `/contact`. The page should now explicitly describe how to file a bug report, and should link you to forem.dev for feature requests:
This adds text within semantic HTML...so hopefully not 😛 

Update /contact page with links to filing bug reports + forem.dev

---

docs/contributing/forem.md

https://github.com/forem/forem/pull/12472 made some _content_ fixes to the contributing guide, but some extra asterisks got added by mistake 🙈 
This PR removes those, since they seem out of place and will cause grammar nerds like me to not be able to sleep at night 🙃 
_Before this change:_
_After this change:_
Nope :) 

Remove extra asterisks in contributing guide

---

spec/system/articles/user_visits_an_article_spec.rb

This fixes a flakey spec where the "Click to Edit" link on an author's article does not appear yet until the JS has completed. Hopefully using `find` will allow Capybara to finish waiting for the Javascript to run.
1. Hope that CI passes
No

Verify link is available and wait for JS before testing

---

app/views/shell/_bottom.html.erb

Update the footer cache whenever the admin configs are updated. Given we bust this cache every 24 hours and on every deploy, I dont think busting it for an admin config change will impact its use much since that happens far less often than deploys and likely is done less than every 24 hours. I want to also note that on a successful config change we bust our edge cache for the footer, naturally, we should ensure that our Redis cache is also busted. 
Fixes: https://github.com/forem/forem/issues/12473
1. Have caching enabled
2. Update the community name and verify it updates in the footer

Bug Fix:Bust Bottom Shell Content on Admin Config Update

---

app/views/shell/_bottom.html.erb

We use `rfc3339` to convert dates into a nice readable string with no space. Turns out `ForemInstance.deployed_at` is a string and not a DateTime 🤦‍♀️

Bug Fix:ForemInstance.deployed_at is a String, not a datetime

---

db/migrate/20210131000458_add_index_to_articles_collection_id.rb
db/schema.rb

I noticed when looking at Postgres diagnosee tab on Heroku that we were spending a lot of time when looking up by collection_id for articles and discovered we were missing an index. 
Before and after adding the index:
```ruby
[1] pry(main)> Article.where(collection_id: 1, published: true).explain
Article Load (12.8ms)  SELECT "articles".* FROM "articles" WHERE "articles"."collection_id" = $1 AND "articles"."published" = $2  [["collection_id", 1], ["published", true]]
=> EXPLAIN for: SELECT "articles".* FROM "articles" WHERE "articles"."collection_id" = $1 AND "articles"."published" = $2 [["collection_id", 1], ["published", true]]
QUERY PLAN
------------------------------------------------------------
Seq Scan on articles  (cost=0.00..15.34 rows=1 width=2140)
Filter: (published AND …
```

Optimization:Add Index to collection_id on Articles

---

app/models/forem_instance.rb
spec/models/forem_instance_spec.rb

Locally `ForemInstance.deployed_at` is nil. This makes it hard to test certain changes because in production `ForemInstance.deployed_at` is a string and therefore behaves differently. This recent difference led to an outage because I had handled the nil case but not the case where it was a string. With this update, `ForemInstance.deployed_at` will be set to the current time as a string locally which will allow us to better catch errors like the one that caused our recent outage. Here is the same error occurring locally.

Optimization: Set ForemInstance.deployed_at Locally to Better Mirror Production

---

app/workers/metrics/record_data_counts_worker.rb

We want to track the size of the `Message` table across the fleet

Add Message to the postgres.db_table_size dataset on Datadog

---

app/models/user.rb

We use the `feed_admin_publish_permission` attribute in admin views to decide whether or not something can be published to the RSS feed, but there no longer seems to be a way for users to change this setting.
Note: we currently have 406 users (out of ~550k) who have this attribute set to `false`. 
First step of https://github.com/forem/forem/issues/12356
n/a
No UI changes

Ignore feed_admin_publish_permission column

---

app/controllers/registrations_controller.rb

On sign in, do not redirect if referer was /serviceworker.js
I was able to regularly reproduce this issue like so: When as a signed out user, clicking on an email link notifying me about a new follower, I was redirected to the sign in page. Upon signing in, I was redirected to /serviceworker.js path. This should no longer take you to /serviceworker.js.
n/a
n/a

Don't redirect to /serviceworker.js on sign in.

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

Over the past couple of months we have repeatedly gotten latency alerts from our app when someone decides to comb through all of our tag endpoints. The Tag index is notoriously slow which is why when someone tries to hit is 5+ times in a second we end up with latency alerts. This uses the same throttling we apply to messages(via chat) to the `/t/:tag` endpoint. Unless someone reload the page incredibly fast, they should not hit this throttle. The only thing that should hit this throttle would be a bot or script.
https://github.com/orgs/forem/projects/6#card-53073578

Optimization:Throttle Tag Index Endpoints

---

app/controllers/admin/tags_controller.rb
app/workers/tags/alias_retag_worker.rb
spec/requests/admin/tags_spec.rb

Currently, when we make a tag an alias for another tag, the existing articles won't get updated, so they don't show up on the preferred tag's tag page. To [quote @michael-tharrington](https://github.com/forem/forem/issues/3675#issuecomment-724950813):
> When `#a` becomes an alias for `#b` the following happens:
> - `dev.to/t/a` redirects to `dev.to/t/b`
> - any future posts that are posted with the tag `#a` are transformed upon posting to use the tag `#b` instead (this is done with a search and replace behind the scenes) 
> 
> What we're missing is:
> - any previous posts that have been tagged `#a` should also transform their tag to `#b`... right now, they just keep the old tag and thus remain hidden.  
This PR adds the missing piece, i.e. updating tags for existing articles.
Closes …

Fix tag alias problems

---

db/seeds.rb

I'm trying to reduce the additional step of creating an account in the Rails console every time I reset my db. I think this is a sensible change and would save everyone's time.
n/a
0. Pull down this branch
1. `bin/rails db:reset`
2. `bin/setup`
3. Start up the rails server and try to log in. You should see Facebook, Github, and Twitter listed there.
n/a

Provide default authentication providers in seed.rb

---

app/controllers/admin/invitations_controller.rb
spec/requests/admin/invitations_spec.rb

This fixes an issue where a registered user can be accidentally flipped back to `registered: false` if they are invited again, which then leads to their profile and comments not being viewable directly (under the show page).
Resolves https://github.com/forem/internalCommunity/issues/8
1. Visit `localhost:3000/admin/invites/new`
2. Try to send an invite to an existing registered user's email
Nope
Nope

Don't allow invites to users who are already registered

---

app/views/admin/navigation_links/_form.html.erb

Quick fix for a small typo in the Navigation links modal I noticed while reviewing a PR in a similar area
N/A 
In the admin area
- Go to Navigation Links
- Add or edit a navigation link
- "detemines" is changed to "determines"
N/A

fix typo in nav links form

---

app/models/organization.rb
spec/models/organization_spec.rb

This updates deleting an organization's notifications with `:destroy` to `:delete_all`. Hopefully speeds things up.
Since the notifications table has no callbacks I think it's fine to change it to `delete_all`.
#12575

Delete all notifications instead of destroying

---

app/controllers/stories_controller.rb
spec/initializers/rack/attack_spec.rb

Reduce the time it takes to get published articles counts on tag page from >900ms to ~200ms by leveraging indexes
shoutout to @mstruve and @rhymes for their benchmarking tips!
continuation to https://github.com/forem/forem/pull/12574
Navigate to any `/t/[tag]` page, you should see the articles count listed on lower left side without issue
n/a

Optimize StoriesController's tagged article count

---

app/controllers/articles_controller.rb
app/javascript/article-form/actions.js
app/javascript/article-form/articleForm.jsx

This fixes a bug where an error was thrown if you try to preview an empty draft article.
Here, we are passing in the entire `showPreview` function in as a _succcess_ callback:
https://github.com/forem/forem/blob/c6c1950b9e421cf9f3086b6a761ce1f74e797d7a/app/javascript/article-form/articleForm.jsx#L158
And in the success callback, we're trying to handle an error. We should split these apart.
The JS shouldn't throw an error due to empty HTML so we need to update the conditional of `if (response.processed_html)`.
I noticed there's a TODO under the failure callback and all we're doing is logging right now. I moved the error logic to that callback, but that doesn't seem to work quite right yet. Moving that logic would allow us to rely on the `status` code from the server to determine success …

Fix bug when trying to preview a blank draft article

---

app/models/user.rb

We already removed the `feed_admin_publish_permission` and related code, but removing the column from `ignored_columns` slipped through the cracks.
#12356
n/a
n/a

Remove feed_admin_publish_permission from ignored_columns

---

app/services/articles/feeds/large_forem_experimental.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb

Reduce tagged article fetch time from ~1000 ms to ~250 ms.
n/a
Continuation of https://github.com/forem/forem/pull/12581 and https://github.com/forem/forem/pull/12574
n/a

Optimize published_articles_by_tag fetch speed

---

app/helpers/feedback_messages_helper.rb
app/views/admin/feedback_messages/_feedback_message.html.erb
spec/helpers/feedback_messages_helper_spec.rb

Removed the code related to sending an email to the reporter about their feedback message.
The rfc talks about deleting `send_email` as well, but as I see we still need `send_email` and `feedback_message_resolution_email` along with the js function `sendEmail` to send emails to the offender and affected users.
https://github.com/forem/rfcs/pull/9
Before:
After:

Remove old code for feedback messages email to the reporter

---

app/views/articles/index.html.erb

This has been an ongoing error message since November 2020. It was because the time was not in the proper format.
Resolves https://app.honeybadger.io/fault/66984/7ea884586993901ab72615451d8200f6
0. Pull down this branch and start up the rails server
1. Navigate to `/top/week`. You should not need any XHR issue in your browser console nor should you see any Elasticserach 400 errors in your server log.
n/a

Fix incorrect datetime format

---

app/javascript/topNavigation/utilities.js

On the dev.to (mobile or application) when we click on menu its dont close if we click outisde(like on desktop one) or on a menu link.
Closes  #12466
- Pull down this branch and start up the rails server
- Login and open the dropdown menu on mobile view (maybe need a refresh after resize the window).
no

fix dropdown-menu not closing when click outside or click on a item on mobile

---

.travis.yml

In https://github.com/forem/forem/pull/12607 we discovered that the upgrade from Carrierwave 2.1.0 to 2.1.1 is more involved than the minor version increase suggests. However, there are two new CVEs against Carrierwave ([CVE-2021-21288](https://github.com/carrierwaveuploader/carrierwave/security/advisories/GHSA-fwcm-636p-68r5) and [CVE-2021-21305](https://github.com/carrierwaveuploader/carrierwave/security/advisories/GHSA-cf3w-g86h-35x4)) that currently stop our builds from passing due to the `bundle audit` check.
As a **temporary workaround** this PR disables the check for these two specific CVEs to give us a bit more time to address the update issues. We should still try to do this in a timely manner, as the security issues are of medium and high criticality respectively.
n/a
n/a
n/a

Ignore two Carrierwave CVEs

---

.github/PULL_REQUEST_TEMPLATE.md

A recent [incident](https://forem.team/vaidehijoshi/communicating-support-tooling-changes-53pm) prompted me to open this PR, which updates our PR template with a `How will this change be communicated?` section, rolled up with our `Added to documentation?` section. Not only do I think it will help us in communicating things _internally_, but I think it will make us more self-aware as a team as to when + how we need to communicate changes to the broader community as well as our users (like [this recent example](https://github.com/forem/forem/pull/12502#pullrequestreview-582866986)).
https://forem.team/vaidehijoshi/communicating-support-tooling-changes-53pm
None :)
None :)

Update PR template with communicating changes section

---

app/uploaders/article_image_uploader.rb
spec/requests/image_uploads_spec.rb
spec/uploaders/article_image_uploader_spec.rb

Change the upload path for article images to `uploads/articles/` to match our other upload path convention. 
Closes https://github.com/forem/internalEngineering/issues/335
Upload an image locally and see the new path used in your directory tree under the `/public` directory

Refactor:Change Image Article Upload Path to uploads/articles

---

app/models/article.rb
app/models/user.rb

This  is one of the final clean up tasks related to #12356, adding `articles.language` and `users.language_settings` to `ignored_columns` so we can drop them from the DB.
#12356
n/a
n/a

Remove language columns

---

app/models/article.rb
app/models/user.rb
db/migrate/20210216023520_drop_language_columns.rb
db/schema.rb

This PR finally removes the remaining language settings columns from `articles` and `users`.
Closes #12356 
n/a
n/a

Drop language settings columns

---

app/controllers/users_controller.rb
spec/requests/user/user_destroy_spec.rb

This PR redirects users to the sign-up page after they self-delete their account.
closes https://github.com/forem/forem/issues/6139
Here is what it looks like once a user confirms their account deletion:
To test...
1. Log in to an account.
2. Go to **Settings** --> **Account** and delete the account.
3. Follow the confirmation link sent via email (I usually just search `mime` in my console where the server is running and get the link directly from there).
4. Confirm the account deletion.
5. Confirm that you're redirected to the sign-up page with a flash notice 🎉 .

Redirect users to sign up path after they self-delete their account

---

app/controllers/stories_controller.rb
spec/requests/articles/org_redirect_spec.rb

The original issue described a redirect loop and suspected that this is related to the interaction of `username`, `old_username`, and `old_old_username`. However, my investigation led me down a different path and I provided a detailed explanation in [this comment](https://github.com/forem/forem/issues/12444#issuecomment-777197399). I'll only share the tl;dr here:
> 1. This only seems to happen to articles that belong to organizations but are accessed via the author's slug.
> 2. I'm not yet sure if the best possible fix is the one regarding `old_username` and `old_old_username` described in the original issue or if we want to update the logic in `StoriesController#show` instead.
By making the article part of an organization I was able to reproduce the redirect loop.
After digging a bit …

Fix infinite redirect loop for articles

---

app/controllers/page_views_controller.rb
app/workers/articles/update_organic_page_views_worker.rb
app/workers/articles/update_page_views_worker.rb
spec/requests/page_views_spec.rb

We've had a [long-standing issue](https://github.com/forem/forem/issues/8425) about page views being out of sync, which was related to our update logic based on random numbers (a 1:8 chance for updating the article's page view count and a 1:100 chance for updating the organic page views). This PR implements @fdoxyz's [suggestion](https://github.com/forem/forem/issues/8425#issuecomment-771661040). The gist:
1. Extract update logic into a worker (or two in this case).
2. Schedule a [unique worker](https://github.com/mhenrixon/sidekiq-unique-jobs) in the future to update the counts.
Closes https://github.com/forem/forem/issues/8425
I think this is easiest to QA via the specs.
n/a

Extract page view updates into workers

---

app/assets/javascripts/utilities/showUserAlertModal.js
app/assets/stylesheets/admin.scss
app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/modals.scss
app/assets/stylesheets/listings.scss
app/assets/stylesheets/views/article.scss
app/assets/stylesheets/views/signin.scss
app/javascript/admin/adminModal.js
app/javascript/listings/dashboard/rowElements/actionButtons.jsx
app/views/admin/configs/_apple_auth_provider_settings.html.erb
app/views/admin/configs/_auth_provider_settings.html.erb
app/views/admin/configs/show.html.erb
app/views/articles/tag_index.html.erb
app/views/users/_comments_section.html.erb
app/views/users/_extensions.html.erb
app/views/users/_integrations.html.erb
app/views/users/_notifications.html.erb
app/views/users/_response_templates.html.erb
app/views/users/_sidebar.html.erb
app/views/users/confirm_destroy.html.erb

Safari doesn't support the `gap` property on `flex` containers. This PR contains individual fixes for all of the occurrences of `display: flex` + `gap`
- closes #12452: `gap` doesn't work with `flex` on Safari 
There were three general fixes that applied to the majority of instances:
Several layouts used a combo of classes that basically resulted in this:
```css
.example {
display: flex;
flex-direction: column;
gap: 1em;
}
```
With no other flex-related properties in place, this is identical in every way to the default behavior of `display: grid`:
```diff
.example {
- display: flex;
- flex-direction: column;
+ display: grid;
gap: 1em;
}
```
This was applied in the following files: 
- app/views/admin/configs/show.html.erb
- app/views/users/_response_templates.html.erb
- …

Fixing `gap` property for all occurrences of `flex` to work in Safari

---

app/controllers/api/v0/api_controller.rb
app/policies/api_secret_policy.rb
app/services/users/delete_activity.rb
spec/policies/api_secret_policy_spec.rb
spec/requests/api/v0/articles_spec.rb

This PR prevents banned users from using the API, as well prevents them from creating new API keys. It also deletes all API keys that a user has when they are deleted.
I didn't add any error handling here since we don't have a set policy on that response for banned users yet.
https://github.com/forem/internalCommunity/issues/24
1. Make yourself banned `user.add_role :banned`
2. Go to /settings/account
3. Attempt to create a new API
4. Run into a 500 error
1. Visit /api/articles
2. See that you get the unauthorized response 401
Nope
Nope

Prevent banned users from using API

---

lib/data_update_scripts/20210218041143_backfill_usernames.rb
spec/lib/data_update_scripts/backfill_usernames_spec.rb

Before we can add a non-null constraint to the DB to ensure that usernames are present (we already have a validation), we need to fix the existing users that previously slipped through the cracks (45 in the case of DEV). This script assigns them a username of the form "user#{user.id}" for this purpose.
#2207
n/a
n/a

Add data update script for backfilling usernames

---

app/assets/stylesheets/base/reset.scss

This PR fixes clipping title field on `/new` view - caused by `prefers-reduced-motion: reduce` settings that we overwrite in our reset. Kudos to @benhalpern for finding the root cause of this bug since it's been open for several months and we couldn't find what exactly caused this behavior. 
- Closes #10114
1. Go to your system preferences and find settings (in accessibility tab) related to reducing motion. check the checkbox.
2. Go to `/new` and play with the title field. It should no longer be clipped.
**Before:** 
**After:**
[Admin …

[15 mins fix] Title clipping on /new view for `prefers-reduced-motion: reduce` settings.

---

app/assets/stylesheets/base/main.scss

When we scroll to `#main-content` on the home page, the next focusable item (the Feed tab) is currently not visible due to the sticky header. As we roll out skip link functionality to other pages, we will see the same. This PR adds a `scroll-margin-top` to `#main-content` which corrects the current issue on the home feed, and sets us up for extending that skip link functionality to other pages too (which will have the same `main-content` ID).
Contributes towards #1153 
Previous behaviour:
New behaviour:
This helps boost the accessibility of our skip link behaviour, as the next focusable item after skip link click is now visible.
will …

Make sure skip link scroll accounts for sticky header

---

config/schedule.yml

Recently the GithubRepoSyncWorker has been [triggering Datadog alarms to go off](https://app.datadoghq.com/monitors/15346499?live=1w) bc it syncs all of our Github repos at once each day. Rather than syncing everything at the same time, let's spread the load out and rolling update smaller batches at a time. 
After this is deployed I will manually go into DEV and update `updated_at` timestamps of GithubRepos to spread out the load.

Optimization:Sync Smaller Subset of Github Repos Hourly

---

db/migrate/20210219043102_add_check_constraint_for_username.rb
db/schema.rb

This PR adds a [check constraint](https://www.postgresql.org/docs/11/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS) for the `users.username` column.
Why a check constraint?
* Adding a `not-null` constraint to an existing table is not safe, as it acquires an `ACCESS EXCLUSIVE LOCK` blocking all writes on the table. The check constraint only needs a `SHARE UPDATE EXCLUSIVE` lock, which only blocks schema changes (`ALTER TABLE` commands).
* There's a [recommended way for doing this safely with `strong_migrations`](https://github.com/ankane/strong_migrations#setting-not-null-on-an-existing-column), but alas this is only supported in Postgres 12+. We have the following in `config/initializers/strong_migrations.rb` and are still running Postgres 10 on Travis:
```ruby …
```

Add check constraint for users.username

---

app/views/tags/edit.html.erb
spec/system/tags/user_updates_a_tag_spec.rb

**The issue**:
> As a tag admin, I don't want to accidentally set my tag to using #000000 as the color hex for both text and background.
**The solution**:
This PR adds default hex colors to the `color_field_tag` to the `edit.html.erb` form for `/t/tag/edit`. The default `bg_color_hex` has been set to black, `#000000`, and the default `text_color_hex` has been set to white, `#ffffff` if a tag doesn't already have a `text_color_hex` or `bg_color_hex` set. If, however, a tag already has a `bg_color_hex` or `text_color_hex` set, the colors will default to whatever colors the tag already has set.
Additionally, this PR adds a system spec that tests that users with the correct permissions (admins or tag moderators) are able to successfully update the tags as expected.
Closes issue #11522 
To QA …

[15 Min. Fix] Update Default bg_color and text_color Hexes on Tag Edit Page

---

app/views/credits/new.html.erb

A user accidentally purchased credits multiple times, because the submit button didn't give any indication of the form submission, so they pressed it repeatedly. This PR addresses that by adding an `onsubmit` handler which deactivates the button and changes its text.
Note: at first I tried to reuse the existing `onsubmit` handler which gets added in the `createCardElement` function. However, this does not seem to get attached when we already have a stored credit card because `if (document.getElementById("card-element"))` will be false. A separate handler seemed easier. In the long run, we generally might want to reconsider how we handle JS in cases like this, having it embedded at the bottom of the views feels a bit off.
Closes #11588
Here's an example purchase with one of [Stripe's test …

Update credit purchase button on submit

---

app/models/user.rb
spec/models/user_spec.rb

Don't attempt to subscribe a user to Mailchimp if it isn't enabled.
1. Update a user's email in rails console
2. See that it doesn't create a background job in logs
Nope
No

Don't sub mailchimp if mailchimp is not enabled

---

app/views/admin/configs/show.html.erb

Quick grammar update on the `/admin/config` page, and some capitalization. I was actually on that page to do something else but....this was _really_ bothering me so here we are.
N/A
N/A
N/A

Grammar fixes on /admin/config

---

app/lib/throttled_call.rb
app/workers/reactions/update_relevant_scores_worker.rb
spec/lib/throttled_call_spec.rb
spec/workers/reactions/update_relevant_scores_worker_spec.rb

Based on our discussions in #3649, this PR implements an MVP version of a `ThrottledCall` utility class, which will execute a block and then prevent its repeated execution for a specified time interval:
```ruby
ThrottledCall.call(:example, throttle_for: 5.minutes) { sleep 3 }
ThrottledCall.call(:example, throttle_for: 5.minutes) { sleep 3 }
```
Given that this is a spike the utility class is basically just a very thin wrapper around `Rails.cache.fetch` which already handles all the important logic, TTL, etc. The wrapper just adds key namespacing (all keys are prefixed with `throttled_call.`) and normalizes the stored value to `true` instead of the block result. I also experimented with returning the TTL (`Rails.cache.redis.ttl(namespaced_key)`) but I didn't think this provided enough …

Spike: Add ThrottledCall utility class

---

app/controllers/admin/users_controller.rb
app/helpers/application_helper.rb
app/services/users/remove_role.rb
app/views/admin/users/_current_roles.html.erb
app/views/admin/users/edit.html.erb
spec/services/users/remove_role_spec.rb

This PR refactors the work done in PR #12582, which gave admins the ability to remove roles via the admin panel. Specifically, this PR refactors `Admin::UsersController#destroy` extracting the logic into a service, `remove_role.rb`. Additionally, this PR cleans up the `_current_roles.html.erb` view by extracting some of the logic from the view into a helper method, `role_display_name`, for better reusability throughout admin-based views. Finally, this PR adds a spec around role removal within the newly implemented `Users::RemoveRole` service.
Refactors PR #12582 
1️⃣  **To QA the removal of a base role from a user, please first ensure that you are an admin, and then do the following:**
- Navigate to `/admin/users/:id/edit`:
- Click the "X" button next to the role of your choice. You …

Refactor: Extract Role Removal Into a Service

---

app/models/article.rb
spec/models/article_spec.rb

The "Definition of Done" for this RFC is:
> This feature is deployed to all Forems, and we can assert that every size Forem, regardless of Forem size, can render articles on the sidebar. We should be able to see that every Forem (even if those that have few posts or old posts) can always display posts for a tag, regardless of an article's `published_at` date or `score`.
This PR is part one of a two-part solution to ensure that posts show beneath the tags in the homepage's righthand sidebar, regardless of the Forem's size and the article's `published_at` date, `score`, and `comment_count`. The first part of this two-part solution focuses specifically on the #help tag in the homepage's righthand sidebar. To accomplish this, I've updated the `active_help` scope the Article model. This scope …

Part 1: Shows Relevant #help Posts in Homepage Sidebar

---

app/workers/github_repos/repo_sync_worker.rb
spec/workers/github_repos/repo_sync_worker_spec.rb

I noticed that we were still processing a ton of Repos every time we synced them on the hour despite me "spreading out" the updated_at timestamps last week. This led me to discover that the majority of the time we run the worker no data is getting updated for the GithubRepo. Since Rails is smart it saves us a trip to the database and doesn't even bother updating the object. The problem with this is that we never update `updated_at` which leads to us trying to resync every GithubRepo every hour since none of them ever have their `updated_at` timestamps updated. This PR fixes that by manually updating `updated_at` every time a worker runs for a repo. 
Run the job and see that updated_at always gets updated despite data remaining unchanged. 
Rerun my script to spread out the timestamps of …

Bug Fix:Update updated_at Timestamp Every time We Run Repo Sync Worker

---

app/views/layouts/_sidebar_nav_link.html.erb

As #12680 describes, 
> The SVGs [in the sidebar] are decorative in this case and don't need a title attribute.
This PR removes them :)
Closes https://github.com/forem/forem/issues/12680.
Yes, it's an _intentional_ UI accessibility change. It improves upon this current issue:
> The effect is that to assistive technology users, the links are announced "Listings Podcasts", "Listings Videos" etc.
or in a …

Remove superfluous title attribute from sidebar SVGs

---

app/workers/follows/update_points_worker.rb
app/workers/rating_votes/assign_rating_worker.rb

I noticed when looking at our low_priority Sidekiq queue after getting an alert that we were enqueuing a lot of duplicate `RatingVotes::AssignRatingWorker` and `Follows::UpdatePointsWorker` jobs. This change puts a lock on those jobs based on arguments to prevent the same job from being enqueued twice. 
https://github.com/orgs/forem/projects/6#card-55934607
Stop your Sidekiq workers
Try to enqueue multiple of the same job with the same args and see that only one of them is enqueued.

Optimization:Enforce Uniqueness for Follows::UpdatePointsWorker and RatingVotes::AssignRatingWorker

---

app/controllers/stories_controller.rb
spec/requests/user/user_show_spec.rb

This PR removes the `disambiguatingDescription` from the schema.org definition in `StoriesController` as it doesn't massively contribute to SEO but poses some problems with generalized profiles.
Closes #12818
n/a
n/a

[15 minute fix] Remove disambiguatingDescription from user profile

---

app/helpers/authentication_helper.rb
app/views/layouts/mailer.html.erb
spec/helpers/authentication_helper_spec.rb

This is a a quick 15-minute fix I whipped up between meetings! 💪🏽
Our transactional emails render a copy reminder at the bottom of the layout to prompt users to remember how they logged into a Forem when they first signed up; unfortunately, that copy only account for third-party providers. So, if a user signed up with email, that copy reads weird:
> Reminder: You used to authenticate your account, so use any of those to sign in if prompted.
This PR take email authentication into account in that email by modifying the helper that the email body renders. While I was in the code, I took the liberty of refactoring some view logic into the pre-existing `AuthenticationHelper` helper, where other provider and auth-related logic lives 😃 
Now, when a user signs up with an email and password, …

[15 Minute Fix]: Update email footer copy to account for email authentication

---

app/services/markdown_processor/parser.rb
spec/services/markdown_processor/parser_spec.rb

Since the redcarpet gem has issues with `<code>` tags when they are not inline or wrapped by a `<pre>` I decided to create a method that converts the `<code>` tags to triple backticks (```) before rendering it using the redcarpet gem. 
resolves [issue#12046](https://github.com/forem/forem/issues/12046)
We enter the same post as in the issue: 
We get the appropriate code block rendered: 
or in a …
```

Fix Markdown parsing of <code> tag

---

app/javascript/CommentSubscription/CommentSubscription.jsx
app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
app/javascript/packs/articlePage.jsx
cypress/integration/loggedOutFlows/showLoginModal.spec.js

Removed logic that would not load the comment subscription button functionally if a user was not logged in. Added logic inside the onClick function of the subscribe button so that it shows the login modal when a user is not logged in. 
resolves [issue#12571](https://github.com/forem/forem/issues/12571)
When a user tries to subscribe to a discussion and is not logged in:
replace this line with details …

Fix subscribe to discussion button when user is not logged in 

---

app/assets/javascripts/serviceworker-companion.js

This PR turns off serviceworkers on Safari browsers (both desktop and iOS). PR https://github.com/forem/forem/pull/12834 refactored serviceworkers significantly, removing almost all functionality from them except for the offline page support.
Something was lost in translation because that PR has resulted in GitHub, Twitter, and possibly other authentication methods no longer working. In particular the `fetch` eventListener in `app/views/service_worker/index.js.erb` is causing issues in Safari. Bypassing this check in `app/views/service_worker/index.js.erb` is problematic: both `navigator.userAgent` as well as `navigator.vendor` should be checked, but Safari doesn't populate `navigator.vendor` in service workers.
Instead, I'm doing a check in …

Disable serviceworkers on Safari browsers

---

app/assets/javascripts/serviceworker-companion.js

A follow up/correction to PR https://github.com/forem/forem/pull/12907: at the last minute I changed how I was detecting Safari in `app/assets/javascripts/serviceworker-companion.js`. Unfortunately, the new detection method doesn't work on mobile Safari (it's used for web based pushed notification, which Safari on iOS doesn't support!). So, it's back to the old method of looking at the combination of `userAgent` and `vendor`.
A silver lining is that this gives us a chance to look for a registered service worker on Safari, and unregister it if we find it! I tested out this functionality on desktop Safari and mobile Safari, and it successfully unregisters any existing Forem service worker! 
https://github.com/forem/forem/pull/12907 …

Disable serviceworkers in Safari part2

---

app/models/article.rb
app/views/articles/feed.rss.builder
spec/models/article_spec.rb

Based on #10927 requirements this PR introduces a new Article method that sanitizes `processed_html` output with Nokogiri
Closes #10927 
Open http://localhost:3000/feed/username, resulting XML markup doesn't have `highlight__panel` tags anymore

Exclude code highlight panel markup from RSS description 

---

app/assets/stylesheets/scaffolds.scss
app/views/layouts/_nav_menu.html.erb
app/views/layouts/_top_bar.html.erb

Remove the mod button in the top nav bar, since it was causing a bug that pushed off the profile menu button in mobile.
Resolves https://github.com/forem/internalEngineering/issues/393
Should be okay! Just added a link with nothing special about it.
Nope

Remove mod button from top nav bar in mobile

---

app/views/users/_publishing_from_rss.html.erb

This PR removes some outdated language from the RSS settings page as requested by @michael-tharrington.
Closes #12900 
n/a

[15 minute fix] Remove outdated language from RSS import

---

app/lib/forem_stats_drivers/datadog_driver.rb

The `ddtrace` gem is tossing out warnings when the app boots:
```
➜  forem git:(master) ✗ rails runner 'puts Datadog::VERSION::STRING'
W, [2021-03-08T15:59:47.137969 #53934]  WARN -- ddtrace: [ddtrace] Unable to patch Datadog::Contrib::Httpclient::Integration (Available?: true, Loaded? false, Compatible? true, Patchable? false)
W, [2021-03-08T15:59:47.138045 #53934]  WARN -- ddtrace: [ddtrace] Unable to patch Datadog::Contrib::Aws::Integration (Available?: false, Loaded? false, Compatible? false, Patchable? false)
0.46.0
```
This PR fixes those warnings:
- Fixed the `httpclient` warning by loading the gem before the instrumentation
- Seems to be loaded lazily in the `pusher` gem, so it's not being loaded at app boot
- This PR also disables `split_by_domain` to be more cautious about the …

Fix ddtrace warnings at app start

---

app/assets/stylesheets/scaffolds.scss
app/views/layouts/_top_bar.html.erb

This fixes an issue where the mod center button wasn't actually hidden in mobile. 😓 
https://github.com/forem/forem/pull/12906
https://github.com/forem/internalEngineering/issues/393
1. Log in as a `trusted` user
2. See that the mod button icon displays in the top nav bar
3. Go into mobile view
4. See that the same mod button is hidden
1. Log in as a non-trusted user
2. See that mod button icon is not present
Nope

Hide mod button in mobile

---

app/views/chat_channel_memberships/index.html.erb
app/views/layouts/application.html.erb
app/views/moderations/mod.html.erb
app/views/partnerships/_flashes.html.erb
app/views/users/edit.html.erb

Fixes https://github.com/forem/forem/issues/12758.
After reading the [accessibility docs around the alert role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role), I noticed that they suggest using `role="alert"` specifically when you are rendering an error message to the user. I went through and checked all the crayons banners that are rendering errors, and in those cases, I used `role="alert"` instead of `aria-live="polite"`.
Before this change, we were getting a warning from axe about the crayons banner not being accessible. This was due to the fact that it didn't have a `role` attribute with the value of `"alert"` (the main landmark warning is actually incorrect).
Before this change, you'd see this when running axe locally:
After this …

[15 Minute Fix]: Ensure crayons banners are accessible

---

config/initializers/devise.rb

After enabling secure session cookies everywhere I noticed how our `remember_user_token` has a slightly different configuration than the [session cookie's](https://github.com/forem/forem/blob/4b902b01c039550b86d79298415808193e7f7ffc/config/initializers/session_store.rb#L21-L22). As I believe those two go hand in hand, I transferred part of the configuration to the "remember me" cookie (`HttpOnly` is always enabled, so no change there).
This will only affect new users or new logins as, unlike Rails, Devise doesn't "upgrade" properties on the existing `remember_me_token`
1. Start ngrok with `ngrok http 3000`
2. Take note of the https URL
3. set this URL in `.env` in `APP_DOMAIN` and `APP_PROTOCOL` and set `FORCE_SSL_IN_RAILS` to `false`
4. start the app and open the URL in the browser
5. …

[15 min fix] Adopt session cookie configuration for remember me cookie

---

config/initializers/devise.rb

This reverts commit cc2b76f7e43f33e15f5cdf84d8d8665188a0c607.
At 16:00 UTC hours on Wednesday March 10th we've started noticing an uptick on login failures, while we're trying to understand what cause it, we decided to revert this related change
Reverts #12938

Revert "Adopt session cookie configuration for remember me cookie"

---

app/models/comment.rb

As I describe in https://github.com/forem/forem/pull/12923#issuecomment-796313142 we deployed the "limit mentions in comments" functionality yesterday to DEV. After confirming that it works as expected, I realized that the Forem fleet would not be deployed until the next day (today, Thursday March 11th), and that the date I set for the `MAX_USER_MENTION_LIVE_AT` would be in the past, but that there will likely be comments that were created after the `MAX_USER_MENTION_LIVE_AT` and before we deploy the fleet.
It seemed to me like the safest option here is to bump this date and ensure that we deploy the Forem fleet before midnight UTC today. I am coordinating with @Zhao-Andy to make sure that the fleet isn't deployed until this change is a part of it.
A follow up to …

Bump MAX_USER_MENTION_LIVE_AT in comment model

---

app/controllers/search_controller.rb
app/models/tag.rb
app/services/search/postgres/tag.rb
db/migrate/20210310154630_add_index_to_tags_supported.rb
db/schema.rb
spec/requests/search_spec.rb
spec/services/search/postgres/tag_spec.rb

This adds "searching for tags" behind a feature flag, using the new PostgreSQL FTS added in #12905
A few considerations:
- Our current `/search/tags` endpoint, if it's not given a `name` parameter, [returns an arbitrary list of tags](https://dev.to/search/tags) as ES can both be used as a search engine but also to enumerate indexed documents. Given that nowhere in the frontend we use this latter capability, I decided not to implement it
- If a `name` parameter is not given on the URL, nothing happens and an empty result set is returned. I didn't change it to a 404 to avoid breaking the UI
- Thanks to @Ridhwana I decided to skip the recommended activation of feature flags by way of data update script as we don't want to have admins of other Forems to accidentally enable it until we've …

[Search 2.0] Add Search::Postgres::Tag behind a feature flag

---

app/assets/stylesheets/chat.scss
app/javascript/chat/content.jsx
app/javascript/chat/videoContent.jsx

It is the 2nd PR for the changes.
It is related to the 
Issue: background box of the button on a profile via chat section, 
issue:  #12879
#12879
https://user-images.githubusercontent.com/67496096/110204804-14dd2500-7e9b-11eb-96cb-d3c5022f217a.mp4
The button is aligned to the right side and it is quite responsive too.
Now there is no overlapping over the profile picture.
Also, I made the SVG to be in the box.

Fix : background box of the button on profile via chat section issue 2nd PR: #12879 

---

app/controllers/comments_controller.rb
app/helpers/rate_limit_checker_helper.rb
app/models/site_config.rb
app/services/rate_limit_checker.rb
spec/requests/comments_create_spec.rb
spec/services/rate_limit_checker_spec.rb
spec/system/comments/user_fills_out_comment_spec.rb

This PR adds a new rate limit for comments created by new users (account age of 3 days or less). 
https://github.com/forem/rfcs/pull/85
Placed this option right below comment creation, where it seems to make the most sense:
1. Make a new user or update the created_at attribute of an existing one (`user.touch(:created_at)`)
2. Create a comment
3. Create another comment, you should see an error:
n/a

Add rate limit for new user comments

---

app/services/moderator/sink_articles.rb
app/workers/moderator/sink_articles_worker.rb
spec/services/moderator/sink_articles_spec.rb

The user moderation is expected to rescore (downward) all articles for a user when a vomit reaction is added. Additionally the articles should rescore upward when user moderation reactions are removed. This was disabled last year because it caused some unexpected problems (one users articles were clogging the feed for everyone after everything they had written was given the same, very high, score). The underlying cause was the score calculation, which assigned the same total to all articles.
This PR changes the logic to process each articles score one by one when user moderation is being added or removed. Rather than setting all articles' scores to the sum of the reaction points for all articles, set the score equal to the sum of the reaction points of that one article plus the sum of the …

reenable article rescoring when moderators flag users 

---

app/models/user.rb
spec/models/user_spec.rb

Since `@trusted` is a boolean true/false value, we can't use the
`@ivar || value` pattern, and want instead to check if the variable
has been defined.
Fixes #13006
https://github.com/forem/forem/issues/13006
Verification with this fix in place that cache/db are only hit once for both trusted and un-trusted users (prior behavior shown in the issue reproduction notes, db queries were occuring each time u.trusted was called for a non-trusted user).
```
[1] pry(main)> u = User.second
[2] pry(main)> u.trusted
Role Load (0.8ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'trusted') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 2]]
=> false
[3] …
```

Only check cache or database once

---

.env_sample

Add the COVERAGE option, default to false, to the example environment variables.
Running coverage is great, but it's definitely something I don't want
to do when interactively using the test suite (running a single file
or single example, this adds 20+ seconds for me).
copy .sample_env to .env, and run a single spec, for example `bundle exec rspec spec/models/email_message_spec.rb`
Observe that immediately after the rspec test output ( Finished in a few seconds (files took some time to load), 1 example, 0 failures) the command finishes.
To verify this is effective, comment out the COVERAGE or set to "true", and re-test, observing the delay after the test completes for coverage testing, and a coverage percentage being reported.
None …

Add and document COVERAGE environment variable in the sample

---

app/controllers/search_controller.rb
app/models/user.rb
app/services/search/postgres/username.rb
app/services/search/user.rb
db/migrate/20210312191925_add_username_tsvector_index_to_users.rb
db/schema.rb
spec/requests/search_spec.rb
spec/services/search/postgres/username_spec.rb
spec/services/search/user_spec.rb

This PR adds "searching for usernames" behind a feature flag, using the new PostgreSQL FTS added in #12905. I don't believe the current search endpoint is being used yet. It is going to be used to support [mention-autocomplete](https://github.com/forem/rfcs/pull/16).
Here is the query plan when I ran this locally against 5,510 users.
```sql
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=2245.58..2245.86 rows=110 width=1277) (actual time=9.138..9.140 rows=19 loops=1)
Sort Key: (ts_rank(to_tsvector('simple'::regconfig, COALESCE((users_1.username)::text, ''::text)), '''ale'':*'::tsquery, 0)) DESC, users.id
Sort Method: quicksort  Memory: 35kB
->  Hash Join …
```

[Search 2.0] Add Search::Postgres::Username behind a feature flag

---

app/services/search/postgres/tag.rb
spec/services/search/postgres/tag_spec.rb

While researching serializers I noticed the following: when I added `Search::Tag` I used `.as_json` but that uses the default JSON gem which is quite slower than [jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer) that we use for Elasticsearch indexing.
Benchmarking speaks for itself:
```ruby
require 'benchmark/ips'
data = Tag.search_by_name("l").where(supported: true).reorder(hotness_score: :desc).select(%i[id name hotness_score rules_html supported short_summary])
module Search
class TagSerializer < ApplicationSerializer
attributes :id, :name, :hotness_score, :supported, :short_summary, :rules_html
end
end
Benchmark.ips do |x|
x.report("as_json") do
data.as_json
end
x.report("jsonapi-serializer") do
Search::TagSerializer.new(data).serializable_hash[:data].pluck …
```

Use faster serializers for Search::Postgres::Tag

---

app/controllers/stories_controller.rb
spec/requests/podcasts/podcast_episodes_index_spec.rb
spec/requests/podcasts/podcast_episodes_show_spec.rb

**TLDR: you can visit another podcast's episode even with the wrong `podcast.slug`. This fixes that.**
So this bug occurred because podcast A had an episode with the same exact `slug` as podcast B. Podcast B's episode was created before podcast A's episode, so in our controller we pulled that episode instead. This is therefore a two part bug, where we:
1. don't have a uniqueness value for `podcast_episodes.slug`
2. `find_by` a podcast episode to render only by its `slug`, and not including the given `podcast.slug`
Interestingly, this means that you can visit a podcast episode's page and play that episode even if you're looking at a different podcast. For example, the Hanselminutes episode has URL of `/hanselminutes/programmatic-problem-solving-with-nicole-archambault`. You can technically …

Get the correct episode by finding the given podcast's episodes

---

app/models/article.rb
spec/models/article_spec.rb

When we call update_score on Articles, we want to mutate the instance before calling the blackbox methods, since the calculations there use `article.score` as input. Saving `self.score=` before then ensures the newly calculated value is factored in to the hotness and spaminess ratings being persisted.
Fixes #13008 …

When updating article scores, use new score for blackbox

---

config/initializers/zeitwerk.rb
lib/generators/settings_model/USAGE
lib/generators/settings_model/settings_model_generator.rb
lib/generators/settings_model/templates/migration.erb
lib/generators/settings_model/templates/model.erb

This is step 1 in splitting `SiteConfig` into several smaller models in the `Settings::` namespace. This PR adds a generator for a migration and corresponding model, to make it easier to create new settings tables in the future:
```sh
$ rails generate settings_model --help
Usage:
rails generate settings_model [NAME] [options]
Options:
[--skip-namespace], [--no-skip-namespace]  # Skip namespace (affects only isolated applications)
Runtime options:
-f, [--force]                    # Overwrite files that already exist
-p, [--pretend], [--no-pretend]  # Run but do not make any changes
-q, [--quiet], [--no-quiet]      # Suppress status output
-s, [--skip], [--no-skip]        # Skip files that already exist
Description:
Generates a settings model.
Examples:
* Generating a settings model (you …
```

Add settings model generator

---

app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx

Refactors an async/wait back to the `.then()` since a warning is showing up for using `await` inside a `useEffect`. I'm not sure how I missed this warning when I originally changed it from `then` to async/await 🙈 
The other option would be to declare an async function inside the `useEffect` e.g.
```
useEffect(() => {
const myAsyncFunction = async () => {
// Do the things with await
}
// Call the declared function
myAsyncFunction()
})
```
Personally in this particular case I find the `then...` more readable, but happy to change to this style if it's preferred. 
introduced in #13044 
No change to previous behaviour in #13044
N/A

Fix async useEffect warning

---

app/views/articles/show.html.erb

This adds the "Skip to content" functionality to the article page, so that users navigating by keyboard can go directly to the main post content without tabbing through menu elements etc.
NB: In the current implementation, the skip link is only the first focusable element **on a fresh page load** and not on internal navigation. At the moment, if you navigate from home to a post, the first focusable element will be after the header bar.
As part of #1153 we will want to change that, but I think it should be completed last, after the individual pages have the skip link functionality set up. Otherwise we'll be degrading the UX in the interim, with users having to tab through the whole header on each page.
#1153 
Steps to verify:
- Go to any article from the home feed
- Refresh the browser …

Add skip link functionality to article page

---

app/serializers/search/username_serializer.rb
app/services/search/postgres/username.rb
spec/services/search/postgres/username_spec.rb

Inspired by the findings of @rhymes in https://github.com/forem/forem/pull/13022, this PR updates `Search::Postgres::Username` to use a serializer over `.as_json`.
```ruby
require 'benchmark/ips'
data = User.search_by_username("a").limit(6).select(%i[id name profile_image username])
Benchmark.ips do |x|
x.report("as_json") do
data.as_json
end
x.report("jsonapi-serializer") do
Search::UsernameSerializer.new(data, is_collection: true).serializable_hash[:data].pluck(:attributes)
end
x.compare!
end
```
```
Warming up --------------------------------------
as_json   237.000  i/100ms
jsonapi-serializer   828.000  i/100ms
Calculating -------------------------------------
as_json      2.406k (± 4.7%) i/s -     12.087k in   5.035621s
jsonapi-serializer      7.780k (± 4.2%) i/s -     38.916k in …
```

Use faster serializers for Search::Postgres::Username

---

app/controllers/devices_controller.rb
app/services/notifications/new_comment/send.rb
app/services/push_notifications/send.rb
spec/requests/devices_spec.rb
spec/services/notifications/new_comment/send_spec.rb
spec/services/push_notifications/send_spec.rb

The bulk of Push Notifications was implemented in #12419 and lives behind the `mobile_notifications` Feature Flag.
What's included in this PR:
- Add the support to use Rpush to send the Push Notifications for new comments (the same Push Notification we have with Pusher Beams) based on the Feature Flag.
- It slightly changes the way the `PushNotifications::Send` service works. It used to receive a User model but this is actually unnecessary. There is no real need to instantiate the User model since we only used it to get associated Devices. An array of user_ids is the new solution.
- Changes the way we find Devices for `devices#destroy` because the Apps react to when a user has logged out and we no longer make authenticated calls
- #12419
- Related to https://github.com/forem/rfcs/pull/68 …

Change PushNotifications::Send to use user_ids

---

app/views/podcast_episodes/index.html.erb

As spotted by @r3cha - in a previous PR I changed a `div` to a `main` but it seems I didn't update the closing tag.
Introduced in #12769
Podcasts page should look/operate same as before, with no visible change and no impact on the skip link functionality.
N/A

15 min fix - update closing tag in podcast episodes

---

app/assets/stylesheets/components/autocomplete.scss
app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx

After merging #13061 we are seeing builds errors due to a call to `css-loader` which doesn't exist in our production dependencies. This is due to the line importing Reach UI Combobox styles in the `MentionAutocompleteTextArea.jsx` file.
This PR imports the styles in the `scss` instead.
#13061 
We need to double check the MentionAutocomplete dropdown continues to look as before. Locally it all looks good to me:
https://user-images.githubusercontent.com/20773163/111985168-30376980-8b04-11eb-9fe9-8cda3388e3eb.mp4
We also need to check that this should successfully resolve our build issues - running the following locally should succeed:
```
DATABASE_URL=postgresql://localhost/Forem_development RAILS_ENV=production bundle exec rails assets:precompile
```
N/A styling change only
_Will this PR …

Refactor reach UI style import

---

app/helpers/feedback_messages_helper.rb
app/views/admin/feedback_messages/_feedback_message.html.erb
spec/helpers/feedback_messages_helper_spec.rb

This PR re-adds the ability to manually send emails to abuse reporters via `/admin/reports` and adds a new, informative banner to the Reporter Email form that informs Admins of the following: `"Please note that all users who report abuse receive an automatic confirmation email. You can send an additional, follow-up email to this user by using the form below."`. For additional context, here is what needs to be implemented for this work to be considered "done," as stated in the issue for this PR:
> We should bring back that functionality that was removed previously since Forem admins occasionally need to be able to send a manual email in addition to the automatic ones.
>
> Additionally, for full clarity and communication, it seems important to include a note on this page that tells the …

Re-Add Reporter Email Form to /admin/reports

---

app/assets/stylesheets/components/autocomplete.scss

This is a small fix following #13082 which caused some styles not to be pulled in to the autocomplete component correctly
#13082
When running locally, the autocomplete dropdown should have the correct styles. 
When running `bundle exec rake assets:precompile` , the compiled `crayons.css` should include the styles from `@reach`
N/A

small fix to import of reach styles

---

config/routes.rb

Sidekiq 6.2.0 [deprecated](https://github.com/mperham/sidekiq/blob/master/Changes.md#620) `Sidekiq::Web.session_secret =` and `Sidekiq::Web.sessions =`
```
WARNING: Sidekiq::Web.session_secret= is no longer relevant and will be removed in Sidekiq 7.0. /forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.0/lib/sidekiq/web.rb:75:in `set'
WARNING: Sidekiq::Web.sessions= is no longer relevant and will be removed in Sidekiq 7.0. /forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.0/lib/sidekiq/web.rb:75:in `set'
```
this was also discussed in https://github.com/forem/forem/pull/13056#pullrequestreview-616507628
Production https://dev.to/sidekiq is working correctly
#13056
None, QA has already been done in production at https://dev.to/sidekiq
None …

Remove deprecated Sidekiq::Web commands

---

app/views/tags/index.html.erb

This adds the "Skip to content" functionality to the tags page, so that users navigating by keyboard can go directly to the main content without tabbing through menu elements etc.
NB: In the current implementation, the skip link is only the first focusable element **on a fresh page load** and not on internal navigation. At the moment, if you navigate from home to the tags page, the first focusable element will be after the header bar.
As part of #1153 we will want to change that, but I think it should be completed last, after the individual pages have the skip link functionality set up. Otherwise we'll be degrading the UX in the interim, with users having to tab through the whole header on each page.
#1153
- Go to the `/tags` page
- Refresh the browser (fresh page load as per above note) …

Add skip link functionality to tags page

---

app/views/admin/shared/_image_uploader.html.erb

This PR adjusts the formatting of an inline, ERB comment in `/admin/tools` so that the comment does not appear in the view.
None!
**To QA this PR, first ensure that you have an admin-based role, then navigate to `/admin/tools` to ensure that you no longer see a Stimulus Controller-related comment within the "Upload an Image" section of the view**:
- **_Before change_**:
- **_After change_**:
None that I can think of!
or in a …

[15 Minute Fix] Adjust Inline Comment in /admin/tools

---

app/controllers/comments_controller.rb
app/decorators/user_decorator.rb
app/helpers/rate_limit_checker_helper.rb
app/lib/constants/site_config.rb
app/models/site_config.rb
app/services/articles/creator.rb
app/views/admin/configs/show.html.erb
spec/decorators/user_decorator_spec.rb

This PR makes the duration a user is considered new configurable via `SiteConfig`. We use this to limit the number of articles and comments a new user can create within a certain timeframe (currently hardcoded to 5 minutes).
https://github.com/forem/rfcs/pull/85
n/a

Make definition of new user configurable

---

app/assets/javascripts/initializers/initializeBodyData.js
cypress/integration/loginFlows/userLogin.spec.js
cypress/integration/loginFlows/userLogout.spec.js

Immediately after a user logs out, the user object is still present (with their data) on the document. That causes some of our JS code to act a little odd and probably isn't the most secure thing in the world.
There might be a better way to do this, but this is pretty predictable and solves the issue.
Closes https://github.com/forem/forem/issues/12679
Re: #12679
https://user-images.githubusercontent.com/11466782/111477500-2cb77300-86fd-11eb-9d6e-fb04542ca1b4.mp4 …

Ensure user data is unset if no user is logged in

---

app/models/article.rb
spec/factories/articles.rb
spec/models/article_spec.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/articles/articles_update_spec.rb
spec/services/articles/updater_spec.rb

The index on `articles.published` is not being invoked due to lack of diversity in the values in that column (it only has 2 possible values other than `NULL`).
The index on `articles.published_at` is extremely diverse (when it's not `NULL`) and will be invoked any time it can reduce the scope of a query by an order of magnitude or more.
On DEV, this does not change the row count for the scope in production:
```ruby
irb(main):001:0> Article.where(published: true).count == Article.where(published: true).where(Arel.sql("published_at < now()")).count
```
The query plan for the `Articles::Feeds::LargeForemExperimental` service invoked in the `Stories::FeedController#show` endpoint goes from this (measured in production):
Planning Time: 0.271 ms
Execution Time: 329.258 ms
to this:
Planning …

Optimize `Article.published` scope to use an index

---

spec/system/comments/user_fills_out_comment_spec.rb

This one file seems to be associated with segfaults we're observing in
TravisCI.
To narrow down the source of the issue, disable this set of tests. (If
segfaults continue, this was not the cause and should be re-enabled).
TravisCI rspec execution is intermittently seeing segmentation faults. When I narrow down the location of the faults, they seem to be occurring when executing this one spec file, consistently.
Disable this test to see if that's causing the issue (and we can focus on determining why in this very limited context), or if it's more broadly related to system tests and not this specific example.
Test only change.
None
will …

Disable the User Fills Out Comment system spec

---

db/migrate/20210312095649_add_credits_awarded_to_badges.rb
db/schema.rb
lib/data_update_scripts/20210322092753_fill_badges_credits_awarded.rb
spec/lib/data_update_scripts/fill_badges_credits_awarded_spec.rb

This pr is a preparation to configure credits tied to badges. 
My plan is to:
- add a field to the `badges` table (with this or)
- update the badges on DEV (but not other forems) to award 5 credits
- add the logic to award (or not award) the configured number of credits in the next pr. This way the badges created right after the logic is deployed will award the configured number of credits (5), not the default (0).
https://github.com/forem/rfcs/pull/69
No
We need to update all the existing badges so that `credits_awarded` would be `5`.
``` …
```

Added credits_awarded to badges

---

app/views/pages/code_of_conduct.html.erb
app/views/pages/privacy.html.erb
app/views/pages/terms.html.erb

This small change allows for the skip link functionality to work on the default pages for:
- Code of Conduct
- Privacy Policy
- Terms of Use
Also by adding the <main> tag it enhances the accessibility of these pages by using the appropriate landmark region.
NB: In the current implementation, the skip link is only the first focusable element on a fresh page load and not on internal navigation. At the moment, if you navigate from home to the given page, the first focusable element will be after the header bar.
As part of #1153 we will want to change that, but I think it should be completed last, after the individual pages have the skip link functionality set up. Otherwise we'll be degrading the UX in the interim, with users having to tab through the whole header on each page.
#1153
For each …

Add skip link functionality to code of conduct, terms and privacy pages

---

app/models/ahoy/event.rb
lib/tasks/metrics.rake

A quick rake task to grab Ahoy events tracking which links have been clicked in the admin overview.
Usage: `bundle exec rake metrics:overview`
Closes https://github.com/forem/internalEngineering/issues/400
Example:
```
$ bundle exec rake metrics:overview
/admin/invitations: 1
/admin/welcome: 1
```
[Admin …

Add rake task to collect admin overview metrics

---

app/views/notifications/index.html.erb

This small change allows for the skip link functionality to work on the Notifications page. Also by adding the `<main>` tag it enhances the accessibility of the page by using the appropriate landmark region.
NB: In the current implementation, the skip link is only the first focusable element on a fresh page load and not on internal navigation. At the moment, if you navigate from home to the notifications page, the first focusable element will be after the header bar.
As part of #1153 we will want to change that, but I think it should be completed last, after the individual pages have the skip link functionality set up. Otherwise we'll be degrading the UX in the interim, with users having to tab through the whole header on each page.
#1153
- Go to the /notifications page
- Refresh the …

Add skip link to notifications page

---

db/migrate/20210325040245_add_trigram_index_to_comments_ancestry.rb
db/schema.rb

We have a btree index on this table but it is not invoked with a `LIKE` operation that uses `%` - only when using `LIKE` with an exact match.
This query is DEV's second-most intense query by total time spent with a p50 latency of ~130ms. This index brings it down to 5ms at p90.
I don't know if the existing btree index on this column is ever even used. I'll have to investigate that later.
replace this …

Add a GIN index on `comments.ancestry`

---

app/helpers/articles_helper.rb
app/models/article.rb
app/queries/articles/active_threads_query.rb
app/views/articles/tags/_sidebar_additional.html.erb
app/views/sidebars/_homepage_content.html.erb
spec/models/article_spec.rb
spec/queries/articles/active_threads_query_spec.rb

The "Definition of Done" for this RFC is:
> This feature is deployed to all Forems, and we can assert that every size Forem, regardless of Forem size, can render articles on the sidebar. We should be able to see that every Forem (even if those that have few posts or old posts) can always display posts for a tag, regardless of an article's `published_at` date or `score`.
This PR is part two of a two-part solution to ensure that posts show beneath the tags in the homepage's righthand sidebar, regardless of the Forem's size and the article's `published_at` date and `score`. The second part of this two-part solution focuses specifically on all active tags (including the `#discuss` tag) other than the `#help` tag, in the homepage's righthand sidebar. To accomplish this, I've removed the …

Part 2: Shows Relevant Posts in Homepage Sidebar

---

app/models/device.rb

This PR sanitizes PEM certificates used for Rpush iOS notifications. The problem with these certificates is that whether we are adding them via the admin dashboard (future) or other ways (i.e. Heroku ENV variable dashboard) they might end up being modified because of the escape character in `\n` that turns into `\\n`. This in turn makes the certificate invalid when used to sign requests.
This sanitization is already in place for other (Apple related) PEM files that need to be read, like the Apple Authentication from a SiteConfig [here](https://github.com/forem/forem/blob/master/config/initializers/devise.rb#L22).
[RFC 68](https://github.com/forem/rfcs/pull/68)
Jump into [BHC](https://community.benhalpern.com/) Heroku dashboard and check out the ENV variables. Specifically `RPUSH_IOS_PEM` …

Sanitize Rpush iOS PEM certificate

---

app/models/ahoy/event.rb
lib/tasks/metrics.rake
spec/tasks/metrics_spec.rb

We merged a rake task yesterday that was meant to help us in fetching metrics around admin overview link clicks for a given Forem instance (https://github.com/forem/forem/pull/13023).
This was deployed to the fleet today, but when I went to test it out, I noticed that it wasn't working properly on any Forem instance, but it _was_ returning records for me locally.
After checking some assumptions and doing some digging, I figured out that the issue was actually that the scope was incorrect -- we were searching by the wrong event name! The event name for an event when an admin clicks on an overview link is [`Admin Overview Link Clicked`](https://github.com/jacobherrington/dev.to/blob/d0a4775cb823ae65f4e6bb3c7f1ac0dde7975d5f/app/javascript/admin/controllers/ahoy_controller.js#L17): …

[15 Min Fix]: Fix incorrect scope used by metrics:overview rake task

---

app/assets/javascripts/initializers/initScrolling.js
app/views/videos/index.html.erb

This adds the "Skip to content" functionality to the videos page, so that users navigating by keyboard can go directly to the main content without tabbing through menu elements etc. It also adds the `main` landmark to the page, giving more context to screen reader users.
NB: In the current implementation, the skip link is only the first focusable element **on a fresh page load** and not on internal navigation. At the moment, if you navigate from home to the videos page, the first focusable element will be after the header bar.
As part of #1153 we will want to change that, but I think it should be completed last, after the individual pages have the skip link functionality set up. Otherwise we'll be degrading the UX in the interim, with users having to tab through the whole header on each …

Add skip link functionality to videos

---

app/views/articles/_full_comment_area.html.erb
cypress/integration/articleFlows/commentOnArticle.spec.js

After merging the autocomplete work in #13126 we had a couple of instance of a failed Cypress test in CI. After running the specs locally multiple times it seems that occasionally it was not targeting the correct "toggle dropdown menu" because there are multiple on the page.
A later accessibility enhancement will be to make sure controls have unique names on this page, but for now to fix the flakiness I've scoped this test better with a data-testid on the comments container. I think this is good practice anyway, as the comments container is the area currently under test.
#13126 
N/A no change to app functionality
N/A no change to app functionality …

15 min fix - improve reliability of autocomplete cypress test

---

app/services/email_digest_article_collector.rb
app/services/instrumentation.rb

On DEV, since we skip this with sidekiq-cron and instead process them
inline using Heroku Scheduler (which is not instrumented), we miss out
on all instrumentation for this process and have no idea how long it
takes to process each user.
With this instrumentation in place, we can see how long it takes to
process each user and aggregate them to see how long it takes to process
all users.
This commit also adds an Instrumentation mixin that we can use to
instrument blocks easily:
```ruby
instrument "MyClass.my_method", tags: { article: article.id } do |span|
end
```
https://github.com/forem/internalEngineering/issues/274 — Optimize EmailDigestWorker for DEV Article Queries
With this deployed, Datadog should have spans for a resource called `EmailDigestArticleCollector#articles_to_send`. They …

Instrument EmailDigestArticleCollector

---

app/controllers/search_controller.rb
app/models/listing.rb
app/serializers/search/listing_result_serializer.rb
app/services/search/postgres/listing.rb
db/migrate/20210326172406_add_published_index_to_listings.rb
db/schema.rb
spec/requests/search_spec.rb
spec/services/search/postgres/listing_spec.rb

This PR adds "searching for listings" behind a feature flag, using the new PostgreSQL FTS added #12905.
RFC 0153: https://github.com/forem/rfcs/pull/153
https://github.com/orgs/forem/projects/29#card-57639102
1. Load the console, activate the flag with `FeatureFlag.enable(:search_2_listings)`.
2. Go to http://localhost:3000/listings.
2. Click on categories in the left column to make sure listings still filter by category.
3. Search for listings and make sure the results match what you expect.
Monitor our monitors for performance compared to Elasticsearch.

[Search 2.0] Listings

---

cypress/integration/articleFlows/commentOnArticle.spec.js

For some reason on my local the comment E2E test `'should pre-populate a comment field when editing'` was always failing even though it was passing on CI. My only guess is it's a  CPU speed thing maybe. This improves the selector for finding the button to display the comment context menu.
This PR also addresses another flaky test, `'should reply to a comment with user mention autocomplete'`.
N/A E2E Test improvement
N/A E2E Test improvement …

[15 Min Fix] Got rid of some E2E test flakiness

---

app/views/articles/manage.html.erb

We recently removed Buffer from the app and the ability to for users to suggest Tweets. This removes the Suggest a Tweet copy from the Manage page for a post to avoid any confusion. 
Load the manage page for a post and see the copy removed. 
BEFORE:
AFTER:

Bug Fix:Remove Suggest a Tweet since we no longer have that feature

---

app/models/user.rb
app/services/authentication/providers/twitter.rb
spec/models/user_spec.rb
spec/services/authentication/authenticator_spec.rb

When digging through some old issues I came across this one [focused on making a user counters table](https://github.com/forem/forem/issues/4939). When glancing over all the counters that are currently on user it occurred to me that I didn't think many of them were used so I started grep'ing the codebase and I was right. This PR removes `twitter_followers_count` and `twitter_following_count` from the codebase. A follow-up PR with a migration will be used to remove them from the database as well. 
I figured with all the profile generalization work going on it would be nice to slim down the users table to only the columns being used to avoid any confusion about what needs to be generalized and/or moved off of it.

Optimization:✂️  Remove Unused Twitter Counts from User ✂️ 

---

lib/data_update_scripts/20210329172336_remove_pro_roles.rb

This should not be merged until after https://github.com/forem/forem/pull/13156 has been deployed across the fleet and monitored for success!
A follow up to https://github.com/forem/forem/pull/13156, the final task to wrap up https://github.com/forem/internalEngineering/issues/403.
1. To QA this PR, first please temporarily add the `pro` role back into the `Role` model if you don't have it (https://github.com/forem/forem/pull/13156 removes it, so if that has already been merged when you QA this, you will _definitely_ need to add this back in).
https://github.com/forem/forem/blob/624c671fa48b6916345ff23abe0a7c25a0ec11a1/app/models/role.rb#L9
2. Next, add the `pro` role to a user (`user.add_role(:pro)`)
3. Go to your rails console (`rails console`) and check that you have a …

Remove pro role from database + pro users

---

app/models/user.rb
db/migrate/20210331181505_remove_twitter_counts_from_user.rb
db/schema.rb

Followup PR to #13196 that actually removes the columns from the database. Given our recent issues with db backups this will ideally need to go out when we are NOT running a Postgres backup.

Optimization:Remove Twitter Counts From User Table in db

---

spec/system/user/trusted_user_flags_user_spec.rb

This PR fixes a flaky test within the `trusted_user_flags_user_spec` by loading a user's profile page twice to ensure that the dropdown that allows a trusted user to flag another user loads properly within the test. Prior to this fix, occasionally when the spec would run, line `16`, "does not show the flag button," would fail because the "Flag @username" option would appear in the dropdown for non-trusted users. @djuber and @maestromac noticed that upon a page refresh, the dropdown appeared as expected, allowing the spec to consistently pass. 
Additionally, this PR adds an inline comment explaining why the fix was put into place.
Relates to PR #12862 
Ensure that all checks pass and try running the spec locally to ensure that it consistently passes. ♻️ 
N/A
_Will …

[15-Minute Fix] Fix Flaky trusted_user_flags_user_spec

---

app/models/article.rb
app/models/user.rb
spec/models/article_spec.rb

This should improve performance on StoriesController#index.
On DEV, the mismatch between `tagged_with` and `cached_tagged_with` is at most 0.007% — the `javascript` tag, with 4 mismatches, the last of which was published over 3 years ago.
Running it for all the tags I could think of off the top of my head, I came up with 0 mismatches on all articles published within the last year:
```ruby
articles = Article
.published
.where('published_at > ?', 1.year.ago)
%w[ruby javascript discuss meta elixir golang rust career performance].map do |tag|
(articles.tagged_with(tag).count - articles.cached_tagged_with(tag).count).abs
end
```
will share …

User#followed_articles->Article.cached_tagged_with

---

docs/frontend/plain-js.md

We moved the initializePage.js file from ERB to pure/plain js in
https://github.com/forem/forem/pull/8030, and the docs are out of sync
with the code.
Fix up the path to this file so it matches the codebase.
https://docs.forem.com/frontend/plain-js/ should no longer point to the erb file.
None

Change file name to remove ERB suffix

---

app/javascript/article-form/components/Title.jsx
app/javascript/chat/compose.jsx
package.json
yarn.lock

When we implemented the mention autocomplete component, we created a custom Preact hook that we can use to auto-resize textareas. This removes the need for the `preact-textarea-autosize` 3rd party library.
This PR replaces the two remaining usages of that library (post title, chat compose) and removes the library from our dependencies.
N/A
**In the post editor:**
- Start drafting a new post
- In the title input, start typing a really long title. Make sure it goes over multiple lines, and check that the text area expands to show everything you've entered
https://user-images.githubusercontent.com/20773163/113425200-5d6bfd80-93c9-11eb-8511-3e88acdfb337.mp4
**In the chat composer:**
- Go to any chat
- Start writing a message, make sure it goes over multiple lines, and check that the text area …

[15 min fix] ✂️✂️✂️ Remove preact-textarea-autosize library ✂️✂️✂️

---

app/views/users/_profile.html.erb

In Settings > Profile, the top user fields weren't associated with their inputs. This meant that screen reader users missed out on the vital information on what each field is for.
This PR adds a small piece of code to properly link those labels with their inputs.
N/A
- As a logged in user, go to Settings
- Using a screen reader, check that the fields Name/Email/Username/Profile image are all announced with their labels
- You can also use the dev tools accessibility inspector to check this information
Before the change:
(note that no label accompanies the placeholder detail or current input values for the fields mentioned) 
After the change:
(labels now included)
This fixes an accessibility bug for screen reader users. …

[15 min fix] Link settings profile fields with their labels

---

app/views/dashboards/_dashboard_article_row.html.erb

On the main dashboard, the post action links (Edit, Manage, More...) all have the same accessible names, making it hard for screen reader users to go straight to the link they want.
This PR adds aria-labels for the links which give the additional context of the post title, making it easier to skip straight to the relevant link.
N/A
- Log in as a user with multiple posts
- Go the dashboard
- Using a screen reader, check the accessible name of the 'Manage' and 'Edit' links, as well as the overflow menu button
**Before the change:**
(notice many instances of Manage/Edit/More)
**After the change:**
This improves the accessibility of the dashboard
development process, or any of our internal teams? If so, please note …

[15 min fix] improve accessible names of dashboard post actions

---

Containerfile

We started seeing buildkite failures building after the rails 6.1
upgrade
While the bundler version probably isn't important by itself,
changing the containerfile invalidates any cached layers used to speed
up the build - and one of them seems to have been problematic.
https://buildkite.com/forem/build-containers/builds/3852 if this failed then the PR should be rejected - but everyone else's builds are failing otherwise.
Failing docker builds look like this `docker build .` or `scripts/build_containers.sh`:
```
---> 23d72a0cafec
Step 15/50 : COPY . "${APP_HOME}"
---> 4108ac33077a
Step 16/50 : RUN mkdir -p "${APP_HOME}"/public/{assets,images,packs,podcasts,uploads}
---> Running in fe2de9207713
Removing intermediate container fe2de9207713
---> 823173213b7a
Step 17/50 : RUN …
```

Update bundler from 2.1 to 2.2

---

app/models/article.rb
app/models/comment.rb
spec/models/article_spec.rb
spec/models/comment_spec.rb

As a part of [RFC #22](https://github.com/forem/rfcs/pull/22), we need to limit how many @-user mentions can be included in a single post. We [already do this for comments](https://github.com/forem/forem/pull/12923), and we should mirror the same functionality in posts -- for both consistency and anti-spam mitigation reasons.
I decided to make this a separate PR before opening up PRs for actual _notification functionality_ that will be ✨ _coming soon to a theatre near you!_ 🍿 🎥  This should make it easier to test and should take care of any potential spam issues _well before_ we roll out the "notification when mentioned in a post" functionality 😎 
The [design/implementation](https://github.com/forem/rfcs/blob/main/text/0022-expand-at-mention-to-posts.md#designimplementation) section of …

Limit mentions in posts

---

app/uploaders/base_uploader.rb

This PR reduces the maximum number of frames for animate GIFs from 1000 to 500 to match the value we use in imgproxy.
Closes https://github.com/forem/internalEngineering/issues/396
* Try to upload a gif with more than 500 frames, it should not work.
None

Change frame limit to match imgproxy

---

app/javascript/article-form/components/Title.jsx
app/javascript/utilities/textAreaUtils.js

When I removed the preact-textarea-autosize library I missed a small issue with the article editor title, where it was displaying with two lines of height by default, instead of one. This was because the new Preact hook only sets the `min-height` of the field, adjusting it to the content height.
This PR adds an optional setting in the Preact hook to also constrain the max-height. This defaults to `false` as in nearly all situations, the default `textarea` height is what we would want (the `Title` is an odd case, as it looks like a single line input, but is actually a textarea)
Closes #13268
- Run the app and visit the `/new` page
- Check that when empty, the title has only one line's worth of height
- Check that as you type a very long title, it expands to fit the content
- Check that if …

[15 min fix] Allow resize hook to contrain max-height as well as min

---

.rubocop.yml

Rubocop 1.12.0 [introduced](https://github.com/forem/forem/pull/13123) the `Style/StringChars` cop. This enables it.
Nothing has changed in the code since we don't use any related code. This just enables it in the Rubocop configuration
https://github.com/forem/forem/pull/13123
Nope, nothing

[15 min fix] Enable Style/StringChars from Rubocop 1.12.0

---

app/controllers/articles_controller.rb
spec/requests/articles/articles_spec.rb

Since we've removed Buffer related algorithm, posts aren't automatically featured
anymore, leaving the RSS feed pretty empty. The default view should also include
those posts, above a minimum score, that are not featured.
Closes https://github.com/forem/forem/issues/13173
1. start the app
2. create an article
3. load the article in the console, it should have `false` as `article.featured` and `0` as `article.score`
4. make sure `SiteConfig.home_feed_minimum_score` is set to 0
5. issue `curl localhost:3000/feed | grep "Title"` and see it there in the list
6. raise the minimum score in `SiteConfig.home_feed_minimum_score`
7. repeat step 5, the article should have disappeared
8. change `article.featured` to `true`
9. repeat step 5, the article should be there again in the feed
have not been …

Adjust default Forem's RSS feed algorithm to allow non featured articles

---

app/views/pages/badge.html.erb

I noticed some errors come through on the therelicans.com/badge page:
`NoMethodError: undefined method 'html' for nil:NilClass`
I am not entirely sure _why_ `html_variant` would be `nil` at this point, but we should account for it.
Fixes https://app.honeybadger.io/projects/72638/faults/78731893.
_Tests should pass!_
_None_
Nope, I will be sure to resolve the error once it has been deployed to the fleet, though!

[15 Min Fix]: Prevent NoMethodError when Html variant is not present

---

Gemfile.lock

Re-adds Darwin-20 (Mac OS 11.x Big Sur) to `Gemfile.lock`. I suspect it dropped out during the Rails 6.1 upgrade.

Re-add Darwin-20 to gemfile.lock

---

app/assets/stylesheets/dashboard.scss
app/javascript/analytics/dashboard.js
app/views/shared/_stats.html.erb

Move the time navigation to the more modern crayon layout, this will mean the theming stuff will work out the box.
Closes #13214
This should fix the UI accessibility issue mentioned in the original ticket
N/A

Update Analytics Dashboard time navigation to tabs

---

app/models/article.rb
app/services/notifications/notifiable_action/send.rb
app/workers/notifications/notifiable_action_worker.rb
spec/models/article_spec.rb

While working on https://github.com/forem/rfcs/pull/22, I found myself looking at the `Notifications::NotifiableAction::Send` service and noticed that we had some logic in that service for finding the followers of an article. While working on my RFC, I found myself duplicating this logic elsewhere, and realized that it was odd for this logic to be so tightly coupled to a service, when really, the article itself should be able to tell you which users follow it/the article's author!
This PR moves the `followers` method out of the service and onto the `Article` model such that you can ask any article for its followers without being constrained to being in this service:
```ruby
[9] pry(main)> a = Article.last
Article Load (1.1ms)  SELECT "articles".* FROM "articles" ORDER BY "articles"."id" …
```

[15 Min Fix]: Extract a post's followers out of service and onto Article model

---

app/views/admin/feedback_messages/_feedback_message.html.erb

Fixes a bug where `EmailMessage.instance.utm_campaign` was `nil` and chaining `.capitalize` on it was leading to a run time error.
https://app.honeybadger.io/fault/66984/53c7af6c590e2f4ef63b5a41f955bf96
Call `EmailMessage.last&.utm_campaign&.capitalize` and see that it doesn't fail 😅 
Nope
No

[15-min-fix] Use safe navigation in case of nil email messages

---

app/mailers/notify_mailer.rb
spec/mailers/notify_mailer_spec.rb

When we upgraded to the latest `ahoy_email` gem, we removed tracking. However, I forgot we had an edge case of tracking where we "track" what type of email reply we sent (reporter, offender, affected). This PR adds saving the email message column `utm_campaign` back in, and I don't think it will actually track anything.
#13294 
1. go to /admin/reports
2. Click "Send Email"
3. Go in `rails console`
4. `EmailMessage.last.utm_campaign == "reporter"` should return `true`
Nope
Nope

[15-min-fix] Add email type as utm_campaign column

---

app/javascript/profileDropdown/flagButton.js
spec/system/user/trusted_user_flags_user_spec.rb

We saw issues with flaky tests around the new flag user button (when a trusted user was logged in after no user was logged in, the spec would fail because LSO was empty). 
The initial work-around was to request the page twice (the first time sets the LSO user data, the second time can successfully use it). 
This change wraps the logic around setting the flag button visibility in a call to the chat utility `getUserDataAndCsrfToken` as suggested by Nick in https://github.com/forem/forem/issues/13228#issuecomment-812715671
There's a missing reorganization likely needed where the `getUserDataAndCsrfToken` function should be promoted from chat/ to a shared location (`utilities/`?). 
https://github.com/forem/forem/pull/13224 work-around added here (removed in this PR)
fixes …

Ensure we have current user information before deciding how to handle the "flag user" button

---

app/javascript/readingList/readingList.jsx

A small UI blip I noticed while testing out the reading list on dev.to. The load more button remains (if it was present) when filtering in the reading list and only disappears after the new data is filtered. Now it is not visible when loading the reading list between filtering states.
#12755
Same QA instructions as #12755.
N/A …

[15 Min Fix] Now the load more button only appears (if necessary) when the reading list is finished loading

---

app/helpers/articles_helper.rb
app/queries/articles/active_threads_query.rb
app/views/articles/tags/_sidebar_additional.html.erb
app/views/sidebars/_homepage_content.html.erb
spec/queries/articles/active_threads_query_spec.rb

This PR updates a change to the options hash within `Articles::ActiveThreadsQuery` and the related specs, which were causing a single tag's posts to populate the sidebar tags on the homepage. Additionally, this PR fixes a bug where posts would "magically" appear and disappear from beneath sidebar tags on the homepage by filtering by tag at the beginning of `#call` rather than at the end.
Relates to PR #12942 and PR #13256 
**To QA this PR, please first ensure that you have admin-status and then navigate to `/admin/config` and scroll to the `/tags` section**. In order to have tags display in the sidebar and to test this PR, you need to first set some tags, like "discuss," "git," and "watercooler":
- After setting the tags, navigate to the homepage and observe that there are no articles …

[15-Minute Fix] Sidebar Tags Show Relevant Posts on Homepage

---

app/javascript/utilities/textAreaUtils.js

We noticed in long posts (long enough to start scrolling) that the mention autocomplete dropdown was being positioned way lower than it should have. 
After a bit of investigation it seems `useTextAreaAutoResize` was the source of the problems. Although we were manipulating both text area heights, the height we calculated was always that of the `plainTextArea`, and consistently the height of whichever textarea is currently hidden is significantly less than the one without the `hidden` class. 
TL;DR - we were accidentally measuring the position of the cursor against a textarea with a different height from the one presented in the UI.
The proposed fix is to keep all text areas passed to `useTextAreaAutoResize` in step with the _largest_  calculated content size. I think this makes sense from …

Fix mention autocomplete positioning after scroll 

---

app/controllers/feedback_messages_controller.rb
app/models/feedback_message.rb
spec/models/feedback_message_spec.rb

Add some better messaging for when abuse reports fail a validation. Also converts some objects to constants.
1. Make an abuse report via localhost:3000/report-abuse
2. Make the same exact report
3. Confirm that the validation error makes sense
Nope
No

[15-min-fix] Improve invalid FeedbackMessage error msg

---

app/models/reaction.rb
spec/models/notification_spec.rb
spec/models/reaction_spec.rb

We currently don't say anywhere that we prevent reaction notifications when unsubscribing from a post. This removes this feature under the hood since it's more a bug (mismatched behavior).
1. In development, unsubscribe to a post
2. Leave a reaction on your post via a different account (sign in as `User.first.email` and `password`, or create a like reaction in console: `Reaction.create!(user_id: 1, reactable: User.find(your_id).articles.published.last, category: "like")`
3. See that you get a notification (make sure you have Sidekiq running)
Nope
No

[15-min-fix] Don't prevent reaction notifications from being sent

---

app/assets/javascripts/initializePage.js

We were calling `initializeLocalStorageRender` twice (immediately before calling `callInitializers`, and the first thing in `callInitializers`). I don't see why, so I removed the first call.
Once I had removed the redundant call to `initializeLocalStorageRender` in the `initializePage` method, it was a pretty shallow function (it only called, with no arguments, the wrapped function `callInitializers`) - so I inlined the "real" function and renamed it to the public name.
This is related to an investigation into https://github.com/forem/forem/issues/13228 but doesn't fix anything there. 
I _think_ I know why this might have been added (the LSO user data is used to populate the DOM user data in  `document.body.dataset.user` which is used to decide which elements are rendered/removed during …

Clean up initializePage

---

app/javascript/shared/components/useListNavigation.js
app/javascript/utilities/viewport.js

The feature was introduced to navigate between articles using the keyboard commands j and k. Previously we were looking for the completely visible first element. There could be cases where we may have partially visible elements, but no completely visible element. 
Closes https://github.com/forem/forem/issues/11566
* Navigate to /top/infinity
* Make sure your browser's window is not big enough to fit the entire first article
* Try to initialize the article feed navigation (pressing j and k)
* Notice nothing is happening
When no article is focused on, the first article that is visible should be focused on.
We might want to have similar behavior to the current one: we look for the first article that is fully visible and then fall back to any that is partially visible if nothing is found. 
It …

Fix feed navigation shortcuts when first article is not 100% visible

---

app/controllers/api/v0/followers_controller.rb
app/controllers/concerns/json_api_sort_param.rb
spec/controllers/concerns/json_api_sort_param_spec.rb

I recently added the `JsonApiSortParam`  concern. However, the included `parse_sort_param` method always required the param string to be passed it explicitly. Given that is a controller concern we can assume that a `params` method will always be available in the including scope, so I'm using this as the default now.
n/a
Refactoring only, specs should still pass
n/a

15 minute fix: Add default argument to JsonApiSortParam

---

app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
cypress/integration/articleFlows/commentOnArticle.spec.js

There is a small bug in the autocomplete work - if I start a user mention, and then click outside of the dropdown to dismiss the options, we successfully close the dropdown and user can continue typing. However, if you then try to use the up/down arrow keys you will find they don't work. 
This was because we were still in the Reach UI combobox which suppresses the up/down arrow key events.
The fix is to treat the 'click outside dismiss' the same as the other cases where we exit the 'search mode', and flip back to a vanilla text area. This PR handles two types of 'click outside':
- Click outside of the dropdown of options but **inside** the text area
- Click outside of the textarea
Addresses part of #13323 
**Test click outside dropdown, but within textarea:**
- Create a new post
- Add …

Switch from combobox to plaintextArea on click outside

---

app/javascript/readingList/components/ItemListItemArchiveButton.jsx
app/javascript/readingList/components/__tests__/ItemListItemArchiveButton.test.jsx

I noticed if you archive/unarchive a reading list item using the keyboard, it very often removes two items, instead of just the one you chose. Taking a little look it was because we had an additional `keyUp` handler, which isn't needed because the normal button 'onClick' is fired when Enter is pressed on the keyboard.
Screen recording of the bug:
https://user-images.githubusercontent.com/20773163/114703041-b79b8580-9d1c-11eb-8696-5805ac2cc44e.mp4
N/A
- Save some items to your reading list
- Go to the reading list page
- Using the keyboard, select one of the archive buttons
- Press enter and check only the selected post is archived
- Repeat the process from the Archive page
https://user-images.githubusercontent.com/20773163/114703198-e44f9d00-9d1c-11eb-8d68-20f54069cbc3.mp4
This fixes a …

[15 min fix] Remove extra key handler on reading list archive button

---

cypress/fixtures/search/listings.json
cypress/integration/listingFlows/viewListing.spec.js

One of the listings Cypress tests sometimes fails when running locally, due the seeded listing being replaced with the results of the `/search/listings` call. This PR adds some static listing data to return in place of the failed search call, ensuring the test only fails if the behaviour under test fails.
Since the test in question is checking whether a modal opens/closes, we don't lose anything by using the mocked data.
N/A - no user-facing changes
N/A - no user-facing changes …

[15 min fix] Intercept listings search call in listings cypress test

---

cypress/integration/articleFlows/commentOnArticle.spec.js

The previous fix for the flakiness of "Reply with mention autocomplete" Cypress test doesn't appear to work as reliably as we thought. This PR disables it again so our builds are unblocked while we investigate further.
N/A
N/A
N/A
shared_

Disable reply with autocomplete test due to flakiness

---

app/lib/database.rb

When building containers, when there is no postgresql instance, this
check to AR::Base.connection is raising an error. We'd like to be able
to continue running `rake assets:precompile` without needing a live db
to check the schema for a table.
Handle connection errors as though they were a table missing.
https://github.com/forem/forem/pull/13114
Stop postgresql
Run `bundle exec rake assets:precompile`
Succeed.
None
No
(insert picture of me spending more time on an  image search than I did on the commit).

When there is no db connection, answer false as though there were no table

---

lib/tasks/app_initializer.rake

Everytime we run `bin/setup` locally, the order of the columns in the `schema.rb` goes out of place (to be precise it goes back being the order they have been added to the underlying database tables).
If you then manually run `bundle exec rails db:migrate` they go back to being in the alphabetical order.
I added this step to `bin/setup` so that they'll stay in alphabetical order.
1. run `bin/setup` on our main branch, witness columns being out of order
2. run `bin/setup` on this branch, witness columns staying in alphabetical order

[15 min fix] Make sure columns in the schema file stay alphabetized after bin/setup

---

app/views/dashboards/_actions.html.erb

This changes the accessible name of the "Listings" link on the user dashboard from "Listings Moderation" to "Listings"
N/A
To test:
- Using a screen reader, go to the dashboard
- Focus the "Listings" link
- It should be announced as "Listings" and not "Listings Moderation"
Before:
After:
Fixes an accessibility bug on the dashboard

[15 min fix] fix accessible name of listings on dashboard

---

app/lib/database.rb
app/models/profile.rb
config/routes.rb

We added a check for ConnectionNotEstablished, which causes the check
to return false if there is no database available (the case in
buildkite for rake tasks like assets:precompile), this changed the
implementation from an existence check (I can connect to the database,
but the table is not present, the situation when we have created a db,
but not yet populated the schema) to an availability check (either the
db is live but the table is absent, or the db is absent, in either
case we know we can't read from the table yet).
Change table_exists? to table_available? to indicate the new
behavior and update the two call sites.
None. Same as before - travis tests should not fail when db:setup is called, and buildkite should not fail when assets:precompile is run.
None …

Rename table_exists? to table_available? to indicate behavior

---

.github/dependabot.yml

Packages bundles like `storybook/*` have a high frequency of updates, sometimes multiple times a week. To lower the burden on reviewing those updates and managing dependabot's rebases, I think we should lower npm's schedule to weekly.
Unfortunately [bi-weekly isn't an option](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#scheduleinterval).
This will run each Monday.

[15 min fix] Dependabot: change npm schedule to weekly

---

app/views/admin/configs/show.html.erb
cypress/integration/adminFlows/config/emailDigestFrequencySection.js

In https://github.com/forem/forem/pull/13095 I accidentally removed the "Email digest frequency" section from `/admin/config`. The request spec did not flag this since the controller still worked as expected, so I added an e2e test in this PR too.
https://github.com/forem/rfcs/pull/126
1. Go to `/admin/config/`
2. Ensure the "Email digest frequency" section is there right below "Emails"
3. Make sure you can change the digest frequency as expected.
n/a

[Bug fix] Re-add Email digest frequency to admin config

---

app/controllers/devices_controller.rb
spec/requests/devices_spec.rb

Makes for a better way to confirm whether or not a Device has been registered properly. CSRF failures return a 200 response  and the consumers are mistakenly taking this as the Device was properly registered, when in fact it wasn't.
https://github.com/forem/ForemWebView-ios/pull/30
So tricky to manually QA that I'd advice against it. Here are a couple screenshots of the Network tab making the request to my ngrok URL:
None - Backend change
None

[15min fix] Return Device ID upon registration

---

app/views/articles/_single_story.html.erb
spec/requests/stories_index_spec.rb

This adds a missing class back in that shows the featured article's main image in the signed out view.
https://github.com/forem/forem/pull/13350
Closes https://github.com/forem/forem/issues/13419
1. Be signed out
2. Go to the home page
3. See that the cover image is visible
Nope
No

Add missing class back in for signed out featured post on feed

---

app/controllers/api/v0/articles_controller.rb
app/views/api/v0/articles/_article.json.jbuilder
docs/api_v0.yml
spec/requests/api/v0/articles_spec.rb

When we serialize articles for the api, we omit reading time. There are applications that could use this.
Fixes #13436
Exercise the api - expect existing keys, _and_ reading_time, in the json response for the article.
None - api change only
or in a [forem.dev](http://forem.dev) post 
shared_

Add reading_time to articles api responses

---

app/controllers/search_controller.rb
app/models/comment.rb
app/serializers/search/comment_serializer.rb
app/serializers/search/postgres_comment_serializer.rb
app/services/search/postgres/comment.rb
spec/requests/search_spec.rb
spec/services/search/postgres/comment_spec.rb

This PR is beginning the process of porting over the search results page to PostgreSQL FTS from Elasticsearch. Our game plan is to convert each endpoint one by one. This means the controller is going to look quite gnarly during this transition period, please bear with us 😅 
This PR adds the comment search behind a feature flag. Once the feature flag is enabled, any search with the comments filter will use PostgreSQL instead of Elasticsearch.
_**Please note there are code and PR comments below explaining more.**_
RFC 0153: https://github.com/forem/rfcs/pull/153
https://github.com/orgs/forem/projects/29#card-58641161
1. Log into an account (local admin or your own).
2. Leave a comment on an article.
3. Go to search (http://localhost:3000/search).
4. Type a search term in the search box at …

[Search 2.0] Comments on search page

---

app/models/user.rb

There's a (tiny) race condition where if an enclosing transaction
has not yet been committed when a user is created, and a sidekiq
worker begins find(:id) and fails, that the job is enqueued, started,
and skipped.
This changes the after_save hook on User to after_commit, ensuring the
user's assigned id is visible to other processes.
#13293 (does not fix)
Not sure how effectively we can test this outside of an environment where edge caching is live. 
- create, update, and destroy a user.
- edge cache should be busted in each case via an enqueued sidekiq job
Fitness for task check:
since the original context was "a new user is created after a 404 was returned, but the 404 response is cached, and the user is not accessible to the api" the post deploy acceptance check would be something like: …

Bust cache after commit, rather than after save

---

app/services/edge_cache/bust_user.rb
spec/services/edge_cache/bust_user_spec.rb

When we clear the cached responses about a user, also clear the api response. This mirrors what we do for [Articles](https://github.com/forem/forem/blob/main/app/services/edge_cache/bust_article.rb#L28) already
#13293 
None
I can test this post deploy to confirm it behaves

When busting user cache, also clear the api response

---

db/migrate/20210421190438_add_body_markdown_tsvector_index_to_comments.rb
db/migrate/20210421190438_add_body_markdown_tsvector_index_to_users.rb
db/schema.rb

This PR follows https://github.com/forem/forem/pull/13401 and adds a tsvector index on `comments.body_markdown` to help speed up comments search.
https://github.com/forem/forem/pull/13401
https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/oQgEzyaXWqK/a/vtBoa2nkXx4/comments
1. Run `rails db:migrate` and see the index is added.
2. Run `rails db:rollback STEP=1` and see the index is removed.
I'll sync with SRE to monitor the results of this change.

Add tsvector index to comments.body_markdown

---

spec/system/comments/user_fills_out_comment_spec.rb

Reverts forem/forem#13456
Let's ignore that spec some more - it started to segfault within hours of merging this in to master (it's still a real problem, it didn't magically go away, it is slowing us down still to work around it).

Revert "re-enable skipped tests"

---

app/views/comments/_form.html.erb

Fixes a couple of accessibility issues where a decorative image ends up mislabeling buttons with redundant information.
1. Navigate to an article
2. Click on the Add to discussion textarea to write a new comment.
3. The comment toolbar appears.
4. Use the browser tools to select the buttons and notice that there is no longer redundant information in the labels and in the case of the templates button, there is a more descriptive label for screen readers, "Use a response template"
Fixes a couple of accessibility issues where a decorative image ends up mislabeling buttons with redundant information. …

[15 min fix] Removed title attributes from SVGs that are purely decorative

---

app/assets/javascripts/initializers/initScrolling.js
app/views/dashboards/following_tags.html.erb
spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb

The Dashboard > Following Tags page had a few accessibility errors where inputs were not given a unique id or a label. This PR fixes both of those issues.
N/A
- Go to the user dashboard
- Select the 'Following Tags' link
- Check with a screen reader that each of the inputs has a unique/logical name
- Check that you can adjust the weights, and save the form
- Check that when you refresh/revisit the page, the weights are populated with the new values
Axe output before the change:
Axe output after the change:
Screenshot of VoiceOver rotor form controls (after the change):
This improves the accessibility of this section of the dashboard, allowing screen reader users to know what each input is for 
development …

[15 min fix] Fix following tags input a11y errors

---

app/views/articles/search.html.erb

This PR adds the skip link functionality to the search results page. It also fixes an error flagged in axe for two `header` elements being on the same page. Due to the way we transition between pages at the moment, the skip link is currently only the first focusable element on a fresh page load.
As part of #1153 we will want to change that, but it can be done as a final step once the functionality is ready on all of our pages.
#1153
- From the home page, type a search term and submit
- Refresh the page (fresh page load as per above)
- Press the Tab key and check the skip link appears
- Click the skip link with either Enter or the mouse
- Press Tab again and check that the Most relevant/Newest/Oldest tabs are where the focus is, and not in the navigation header …

Add skip link to search results page

---

app/assets/javascripts/utilities/slideSidebar.js
app/views/articles/tag_index.html.erb
app/views/stories/_stories_list_script.html.erb
spec/system/articles/user_visits_articles_by_tag_spec.rb

This PR adds the skip link functionality to the tag page, allowing users to skip directly to the list of articles. Due to the way we transition between pages at the moment, the skip link is currently only the first focusable element on a fresh page load. 
As part of #1153 we will want to change that, but it can be done as a final step once the functionality is ready on all of our pages.
#1153
- From the home page, select a tag you're following
- Refresh the page (fresh page load as per above)
- Press the Tab key
- You should see the skip link is focused
- Activate the link with either Enter or a click
- Press the Tab key again 
- The focus should be on the Feed/Week/Month links and not in the sidebars/navigation header
https://user-images.githubusercontent.com/20773163/115882726-f3cd9500-a …

Add skip link to tag page

---

app/views/pages/show.html.erb

This PR adds a `<main>` and the related skip link functionality to admin-defined pages.
#1153
- As an admin user, go the "Pages" admin section
- Create a page with some content that includes an interactive element (e.g. a link)
- Go to that page's URL and press the Tab key
- The skip link should be visible
- Activate the skip link with `Enter` or mouse click
- Press the Tab key again and verify that your focus is on the first interactive item in the main page content (and not in the navigation bar at the top)
- Repeat the process with both the "contained" and "full_within_layout" page template types
https://user-images.githubusercontent.com/20773163/115873347-bb28be00-a43a-11eb-995d-a86f7b7ccb62.mp4
This rolls out a necessary keyboard accessibility feature to user-defined pages and …

Add skip link functionality to custom pages

---

app/views/articles/stats.html.erb
app/views/dashboards/analytics.erb

This PR adds the skip link functionality to the analytics dashboard and the article stats pages, along with a 'main' landmark. Due to the way we transition between pages at the moment, the skip link is currently only the first focusable element on a fresh page load.
As part of #1153 we will want to change that, but it can be done as a final step once the functionality is ready on all of our pages.
#1153
- Go to `/dashboard/analytics`
- If you navigated there by a link click, refresh the page (as per above note on fresh page loads)
- Press the Tab key and check the skip link appears
- Click the skip link with either the Enter key or the mouse
- Press Tab again and check the next focused element is the Week/Month/Infinity links
- Go to one of your user's published articles and click the …

Add skip link to stats and analytics pages

---

app/services/search/postgres/comment.rb
db/migrate/20210423162805_remove_indexes_from_comments.rb
db/migrate/20210423162847_add_partial_indexes_from_comments.rb
db/schema.rb

Following up on our attempts in https://github.com/forem/forem/pull/13476, we're still not getting the performance we need out of the search for comments. This PR adds partial indexes instead of the full indexes on `comments.deleted` and `comments.hidden_by_commentable_user`. It also explicitly specifies `comments.user_id`.
https://github.com/forem/forem/pull/13476
1. Run `rails db:migrate` and see the indexes are added.
2. Run `rails db:rollback STEP=2` and see the indexes are removed.
I'll sync with SRE to monitor the results of this change.

Performance improvements to comments search

---

app/views/users/edit.html.erb

This PR adds the skip link functionality to the settings page, and refactors to ensure all main content is wrapped in the `main`. Due to the way we transition between pages at the moment, the skip link is currently only the first focusable element on a fresh page load.
As part of #1153 we will want to change that, but it can be done as a final step once the functionality is ready on all of our pages.
#1153
- Go to `/settings`
- If you got to that page by clicking a link, refresh the page (as per above note)
- Press the Tab key and check the skip link appears
- Click the link with either the mouse or by pressing Enter
- Press Tab again and check that the next focused item is your username (settings for `@username`) and not any item in the header …

add skip link to settings page

---

app/serializers/search/postgres_comment_serializer.rb
app/services/search/postgres/comment.rb

The chase continues...somehow comments search, seemingly at random, throws a `500` because it can't find the user for the comment. This PR changes the logic to 1) preload users instead of querying for them separately and 2) add a conditional to the serializer to prevent an error and return an empty hash instead.
https://github.com/forem/forem/pull/13489
Specs should cover us here, but you can pull this locally, enable the `search_2_comments` feature flag, and search for comments.
I'll sync with SRE to monitor the results of this change.

Preload users instead of querying separately when searching for comments

---

app/views/admin/shared/_nested_sidebar.html.erb

The SVGs used in the side navigation are decorative, and should be hidden from assistive technology users. Currently they have the attribute role="img" which causes them to be surfaced to screen reader users as images with missing alternative text.
These SVGs should be updated to:
```
remove role="img"
add aria-hidden="true" to hide them fully from screen reader users
```
Changing aria:true to aria:hidden removes the role="img" and adds aria-hidden="true" instead.
https://github.com/forem/internalEngineering/issues/415 …

aria-hidden accessibility tweak

---

config/environments/development.rb

We disable caching in controller development by default (you can touch an option file to enable this). However, we also disable Rails.cache as a data store.
We expect Rails.cache to be a working inter-process communication channel between sidekiq workers after commit 9973b7361e8936ecd95c938746093524ad56ff63 (passing the podcast episode rss item as a cache key/pointer, rather than a large hash/immediate value, and fetching the hash from cache in the "child" worker to create podcast episode). 
Always enable the rails cache redis data store, but do still disable action controller caching (the intended behavior in develolpment).  
I initially ran into this in the context of Podcasts::GetEpisodesWorker not behaving as expected. 
- Delete `tmp/caching-dev.txt` if present. 
- Restart sidekiq to …

Enable redis cache store in development

---

app/sanitizers/rendered_markdown_scrubber.rb
app/services/markdown_processor/parser.rb
spec/services/markdown_processor/parser_spec.rb

This removes some attributes that would never really be used, or shouldn't be because they would add confusion. It's not documented anywhere that these attributes could have been used, and therefore I think we should remove them.
Also adds a method to scrub the attributes that are used.
None
1. Go to /new
2. Try to 
TODO
Nope

Remove unused attributes from markdown parser

---

app/controllers/search_controller.rb
app/models/article.rb
app/services/search/postgres/article.rb
app/services/search/postgres/reading_list.rb
spec/requests/search_spec.rb
spec/services/search/postgres/article_spec.rb

This implements the following:
- default view of https://dev.to/search/ replacing the combined "articles + users" with just articles
- search articles pages: https://dev.to/search?q=&filters=class_name:Article and https://dev.to/search?q=ruby&filters=class_name:Article
- search articles but only my articles: https://dev.to/search?q=ruby&filters=MY_POSTS 
Basically this PR is a combination of #13339 and #13052 (without joining `reactions` like in the reading list) :D
**FYI:** we can't use "highlighting" for mainly two reasons:
1. this search is done on the `tsvector` column, not on the actual text, so (I tried) it obviously highlights the context of the processed `tsvector` column, making highlighting useless
2. switching back to searching all the columns plus higlighting times out in …

[Search 2.0] Articles

---

app/controllers/search_controller.rb
app/models/podcast_episode.rb
app/serializers/search/postgres_podcast_episode_serializer.rb
app/services/search/postgres/podcast_episode.rb
db/migrate/20210426151459_add_published_partial_index_to_podcasts.rb
db/migrate/20210426152816_add_tsvector_indexes_to_podcast_episodes.rb
db/migrate/20210426165234_add_partial_index_on_reachable_to_podcast_episodes.rb
db/schema.rb
spec/requests/search_spec.rb
spec/services/search/postgres/podcast_episode_spec.rb

This PR is beginning the process of porting over the search results page to PostgreSQL FTS from Elasticsearch. Our game plan is to convert each endpoint one by one. This means the controller is going to look quite gnarly during this transition period, please bear with us 😅 
This PR adds the podcasts search behind a feature flag. Once the feature flag is enabled, any search with the podcast filter will use PostgreSQL instead of Elasticsearch.
RFC 0153: https://github.com/forem/rfcs/pull/153
https://github.com/orgs/forem/projects/29#card-58641170
1. Make sure you have `PodcastEpisodes` and `Podcasts` locally.
2. Log into an account (local admin or your own).
3. Go to search (http://localhost:3000/search).
4. Type a search term in the search box at the top related to the `body`, `title`, or …

[Search 2.0] Podcasts on search page

---

spec/queries/homepage/articles_query_spec.rb

Fix flaky search ordering test case.
We can't rely on the database returning published articles in ID
order, since there are indexes on published_at and on published which
could very well be in any order (btree), and no explicit `ORDER BY id
ASC` was in the query.
I checked the query that's run in the test against blazer, and confirmed that under
real conditions the results are pretty far from ordered:
```
SELECT articles.id FROM articles WHERE (published_at <= '2021-04-27') AND articles.published = true LIMIT 10 OFFSET 0;
----
id
166916
637099
132444
431420
501939
141182
565391
515964
146231
677241
```
Change the expectation to assert Article does not receive :order, and
remove the expectation that the ids are returned in the order created. …

fix flaky Homepage::ArticleQuery spec

---

app/services/articles/suggest.rb

Turns out #13541 was optimizing the wrong query. I overlooked the `organic_page_views_past_month` in the `WHERE` clause. This is the only query I could find in the app that uses this attribute.
#13541 
shared_
Check out [perf on Datadog](https://app.datadoghq.com/apm/resource/practical_developer-postgres/postgres.query/45a1af3b42e9528 …

Optimize `Articles::Suggest` query

---

app/serializers/search/postgres_podcast_episode_serializer.rb
app/services/search/postgres/podcast_episode.rb
spec/services/search/postgres/podcast_episode_spec.rb

In https://github.com/forem/forem/pull/13475 we returned data under the `podcast` key to mimic Elasticsearch. We didn't realize that the values are actually from `PodcastEpisode` and not `Podcast`, despite the name :sweat_smile:.
**Side note**
It feels a little weird we show the same text (`PodcastEpisode.title`) twice...I wonder if the top was originally supposed to be `Podcast.title` and the bottom text was supposed to be `PodcastEpisode.title`. Either way, updating the frontend is out of the scope of this PR and the Search 2.0 RFC. I added [a note to our cleanup list](https://github.com/orgs/forem/projects/29#card-59639576) to revisit this later after Elasticsearch is gone. In other words, this PR _should_ bring it up to par with our _current_ setup. …

[Search 2.0] Fix podcast values

---

app/assets/stylesheets/article-show.scss

Fix scroll-padding on article anchor links.
Closes https://github.com/forem/forem/issues/9749
So there was a lingering issue with anchor links on dev.to: the Section `#anchor` links on articles would make the heading of said section hide behind the header. This PR aims to fix that.
**To test this:**
Load up the minimal default article database, and head to `http://localhost:3000/ricky_ms_franecki/the-mermaids-singing-ut-quasi-91k`
Edit the URL to add `#main-title` at the end (for a position reset). Then, edit it to `#modi` to scroll to that section in the article.
have …

Fix scroll-padding on article anchor links

---

app/services/mentions/create_all.rb
spec/services/mentions/create_all_spec.rb

Ensures that any @-mentions that are _embedded content_ within a comment liquid tag are ignored when deciding which users to send mention notifications to.
Fixes https://github.com/forem/forem/issues/13348.
_You'll want two different user accounts open (using an incognito tab or separate browser to test this):_
1. Create a comment that has a mention within it with one user account. Use that comment to create _another_ comment that uses the `{% comment [comment_id] %}` syntax embedded within it. Any @-mentions _within the embedded comment_ should not turn into mentions, nor should the user be notified about them. For example, a comment like this **should not** trigger a notification for `@vaidehijoshi`, since the mention is embedded as a liquid tag:
2. Create a comment that has a mention …

Do not create mentions when embedded within a comment liquid tag

---

.travis.yml
lib/tasks/assets.rake

Our Heroku Slug size is currently 348.2 MiB of 500 MiB. It's good but could better.  One of our gem `sassc-ruby` currently includes 160MB of binary that we don't need. This PR removes it during the Heroku asset cleanup step.
Update: This changes drop our slug size to 278.3M
follow up to https://github.com/forem/forem/pull/12372
n/a
n/a
I will closely monitor staging first

Add auto-remove .o native extension rake task

---

config/initializers/reserved_words.rb

We had an issue where a user was impersonating the React JS team and publishing posts as them. As per our [Terms of Service](https://dev.to/terms#reserved-names), we don't allow this.
N/A
In `rails console`:
```ruby
user.update(username: 'react')
#=> should return false
user.update(username: 'reactjs')
#=> should return false
```
Nope
Nope

Add react and reactjs to reserved words

---

app/controllers/admin/settings/mandatories_controller.rb
app/controllers/admin/settings/mandatory_settings_controller.rb
app/controllers/concerns/verify_setup_completed.rb
app/helpers/application_helper.rb
app/models/settings/mandatory.rb
app/views/admin/configs/show.html.erb
config/routes.rb
cypress/integration/adminFlows/config/getStartedSection.js
spec/system/admin/admin_manages_configuration_spec.rb

As @juliannatetreault noted in ##13495, the "Get Started" section on `/admin/config` was a bit broken since two of the settings move from `SiteConfig` to `SettingsCommunity` but this section wasn't updated. I used this opportunity to generally clean up how we deal with mandatory settings, adding a new `Settings::Mandatory` model allowed me to move some logic out out of the `VerifySetupCompleted` concern.
https://github.com/forem/rfcs/pull/126
Go to `/admin/config` and ensure the "Get Started" section behaves as expected.
None

Refactor handling of mandatory settings

---

app/services/search/postgres/podcast_episode.rb
db/migrate/20210428190634_add_tsvector_index_on_searchable_columnns_to_podcast_episodes.rb
db/schema.rb

The current query to search `PodcastEpisodes` is too slow in production. This PR changes
the query to force a join over the preload to speed things up.
https://github.com/forem/forem/pull/13475
I'll sync with SRE to monitor performance and re-enable the feature flag.

[Search 2.0] Change podcast_episode query

---

app/controllers/search_controller.rb
spec/requests/search_spec.rb

The time has come :-)  
We can start removing the oldest feature flags for "search 2.0".
The `/search/tags` endpoint has been added 7 weeks ago in #12937 and [has been active since  2021-03-12 18:25:16 UTC](https://dev.to/admin/blazer/queries/454-all-enabled-feature-flags)
Its p99 since then is [74ms](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/zPBVzyS8pg1/a/hSABcJfvT9u/tags), so I think it's safe to remove it.
I haven't purposefully removed any of the indexing code in Elasticsearch, in case anything happens and we have to rollback, this way we avoid having to reindex the content.
We'll remove the Elasticsearch support code when we'll have removed all feature flags. …

[Search 2.0] Remove search_2_tags feature flag ✂️ 

---

app/javascript/utilities/textAreaUtils.js

When an input has a scroll we remove its position from the overall position putting the mention popover in the right place
closes #13513
N/A
N/A
As a side note I finally installed a local copy of forem rather than just winging it 😅

Remove input scroll from position

---

app/controllers/search_controller.rb
spec/requests/search_spec.rb

As we did in #13567 the time has come to remove two other feature flags: `search_2_listings` and `search_2_usernames`
- `search_2_listings` has been active since `2021-03-29 19:15:52 UTC` (1 month ago)
- `search_2_usernames` has been active since `2021-04-08 16:29:41 UTC` (3 weeks ago)
- "search listings" has a p99 of [200ms in the worst case](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/wA3uSwDbLaK/a/99wb3kPifEU/listings) but #13577 should help
- "search usernames" has a p99 of [94ms since we've optimized the query](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/8ueupjEgun9/a/bumpLwBWs6W/usernames) in #13474
#13567
#13474  …

[Search 2.0] Remove search_2_listings, search_2_usernames feature flags

---

app/black_box/black_box.rb
app/controllers/admin/feedback_messages_controller.rb
app/models/user.rb
app/services/authentication/authenticator.rb
app/services/authentication/providers/apple.rb
app/services/authentication/providers/facebook.rb
app/services/authentication/providers/github.rb
app/services/authentication/providers/provider.rb
app/services/authentication/providers/twitter.rb
spec/black_box/black_box_spec.rb
spec/models/user_spec.rb
spec/services/authentication/authenticator_spec.rb

This removes the `*_created_at` columns from `User` and all their usages. The follow-up PR will remove the columns.
Closes https://github.com/forem/forem/issues/11414
* Specs should pass
* Signing up via social auth should work
* Updating user information through social auth should work
None, backend only change

Remove <provider>_created_at columns

---

app/controllers/search_controller.rb
app/queries/homepage/articles_query.rb
app/services/search/postgres/article.rb
db/migrate/20210429094116_add_tsvector_index_on_searchable_columns_to_listings.rb
db/schema.rb
spec/queries/homepage/articles_query_spec.rb

This PR contains 2 performance improvements:
- **listings don't have a `tsvector` index**, thus we add one for it. There's a possibility that PostgreSQL will ignore it in its query plan but we can only know if we add it. I'm using [@jgaskins's technique](https://github.com/forem/forem/pull/13568#pullrequestreview-647417567) implemented by @atsmith813 yesterday [for podcast episodes](https://github.com/forem/forem/pull/13568) aka an index on the combined `tsvector`. I double checked the size of listings and we're way the 1mb limit (the biggest is ~ 800 bytes)
- the query that fetches article's tags to build "tag flares" is slow because it's using the implicit "ranking" order and recently we've had some performance issues due to the fact that rankings are computed at runtime and ordering on …

[Hotfix] [Search 2.0] Optimize performance of listings and articles and fix bugs

---

app/serializers/search/postgres_podcast_episode_serializer.rb

In https://github.com/forem/forem/pull/13568 we fixed the performance of searching podcasts related to the query...but the full request was still slow. After some investigation, we found that we were calling `body_text` in the `PostgresPodcastEpisodeSerialzer`:
https://github.com/forem/forem/blob/5af33a63dd1fd6bc741a8d99d9ef11a8e42f894e/app/models/podcast_episode.rb#L82-L84
This santization on each `PodcastEpisode` was [slow](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/9fkf57uPaSA/trace/mJ54VQ9e2AB).
Since we don't display `body_text` or highlights in the UI when searching `PodcastEpisodes`, we don't really need to worry about the sanitization. To fix this, this PR maps the `body` field on `PodcastEpisodes` to the `body_text` key instead to skip sanitization altogether. …

[Search 2.0] Use body instead of body_text in serializer for podcast_episodes

---

app/assets/javascripts/utilities/buildCommentHTML.js.erb

An `aria-label` attribute had the wrong value. The label is for the edit menu item, but the `aria-label` was referring to deletion. I came across this while getting E2E tests working in #13365.
1. Create a comment on a post.
2. Click on the the three dot menu at the top right of the comment you just created.
3. The available menu items appear.
4. If in a Chromium based browser, use the dev tools to select the Edit menu item.
5. You'll notice that it now says `Edit this comment`.
6. If using Firefox, open the dev tools and switch to the Accessibility panel to view the fix.
7. You the Accessibility selector to select the Edit menu item.
8. The label in the accessibility tree now says "Edit this comment"
As per the description, this fixes an issue when using a screen reader. The mislabeling …

[15 min fix] Fixed aria label for edit menu item of a comment

---

app/javascript/analytics/dashboard.js

I noticed while working on some Cypress tests in #13559 that some unhandled exceptions were being logged to the console when we refresh chart data:
https://user-images.githubusercontent.com/20773163/116678895-cc754b80-a9a1-11eb-9793-fbd8bd0605e9.mp4
This is because chart.js [requires any existing charts to be destroyed before drawing new ones on the same canvas](https://www.chartjs.org/docs/latest/developers/api.html#destroy).
The bug doesn't seem to be affecting the usability of the current analytics dashboard at all, but it does cause cypress tests to fail as cypress will exit if uncaught errors occur.
Unblocks some tests on #13559
If you go to the analytics dashboard and change tabs multiple times, you shouldn't see any error logged out to the console: …

15 min fix for chart js errors

---

app/controllers/search_controller.rb
spec/requests/search_spec.rb
spec/system/search/display_articles_search_spec.rb
spec/system/search/display_comments_search_spec.rb

This PR removes the remaining feature flags for Search 2.0:
- `search_2_homepage`
- `search_2_articles`
- `search_2_comments`
- `search_2_podcast_episodes`
- `search_2_users`
- `search_2_reading_list`
This means we will no longer be using Elasticsearch to perform searches 🎉 . The actual removal of Elasticsearch needs to happen in separate PRs. We'll also update the documentation once it's fully removed.
https://ui.honeycomb.io/thepracticaldev/board/5d4yWi7QsG9/Search
Specs should cover this - all of the feature flags are currently enabled on DEV in production so this functionality is already "live", in a sense
We'll work with SRE to remove the feature flags as they're no longer needed

[Search 2.0] Remove remaining search_2 feature flags

---

app/assets/stylesheets/components/autocomplete.scss

Occasionally the autocomplete dropdown is getting into a bad state when a selection is made by clicking, instead of by keyboard. See video:
https://user-images.githubusercontent.com/20773163/116683681-ddc15680-a9a7-11eb-9da2-917d0cfe0654.mp4
You can see in the UI the dropdown is shrinking to a tiny width, causing the click event to be missed. It's pretty weird, but it seems like we can't rely on the reach UI CSS for the width of this component, and it's better for us to be explicit anyway. I've added a min-width for the dropdown to ensure it never shrinks like this.
N/A
The regression risk on this is very small, since it's only a CSS change.
- We should test this in both the article comments and post editor sections.
- Try mentioning some users, always selecting the option by click with …

15 min fix: make sure autocomplete dropdown occupies width

---

cypress/integration/adminFlows/config/authenticationSection.spec.js

Very very occasionally we were seeing this Cypress spec fail in CI. I tried and failed to reproduce locally, but given the test was failing at the point of sign out, my best guess is that because this chunk of the test was outside of the Promise of the preceding test steps, it was occasionally running too early. 
One failure report:
It's only hunch, but either way it makes sense to change it. If it keeps intermittently failing, then back to the drawing board!
N/A
Nothing to do here other than to run the frontend tests build job a few times before deciding this is good.
N/A …

[15 min fix] Fix a timing issue in a cypress test (possibly) causing flakiness

---

app/javascript/listings/__tests__/AllListings.test.jsx
app/javascript/listings/components/AllListings.jsx
app/javascript/listings/components/ListingFilters.jsx
app/javascript/listings/components/ListingFiltersCategories.jsx
app/javascript/listings/singleListing/AuthorInfo.jsx
app/javascript/listings/singleListing/Header.jsx
app/views/listings/index.html.erb

The listings pages had a few minor accessibility errors for multiple landmarks without unique labels. A little investigation and we had a combination of issues:
- additional headers/footers when a page should only have one at the top level (unless in an iframe / other document)
- the filtering tags were in an `aside` when they're part of the main content
- the navigation wasn't labelled
All minor things, but fixing them gives us a clean axe report for that page's default state now.
N/A
The page should look and behave the same, with no visible user facing changes. For a screen reader user, the navigation to filter listings should now be announced with a label, and duplicate landmarks shouldn't appear in the rotor.
VoiceOver rotor landmark output (with main Listings and Listings by Category …

[15 min fix] Fix some landmark issues in listings

---

bin/container-setup

Whilst following the setup guidelines on windows using container mothed, executing the [script](https://docs.forem.com/installation/containers/#running-forem-with-docker-via-docker-compose): `bin/container-setup` on windows OS, returns:
```sh
Oof! Sorry! This OS is unsupported! :(
Starting the Forem container stack...
```
So, I convert it to this as it is more informative to windows users like myself:
```sh
Oof! Sorry! This OS is unsupported! :(
If you are on Windows OS and have Docker or Podman for windows installed:
Docker: https://docs.docker.com/docker-for-windows/install/
Podman: https://podman.io/getting-started/installation
Execute the following:
docker-compose build
docker-compose up
```
and also exiting on failure so as not to echo `Starting the Forem container stack...`
None
Run …

Improve bash info for windows user

---

cypress/integration/loginFlows/userLogout.spec.js

This Cypress test flaked for me in CI recently. I haven't been able to reproduce locally, but it failed on asserting that the user info had been removed from the body element. My best guess is that it ran too fast for the body element to have updated(?) - it's just a hunch, but either way, the additional step added will either:
- Make sure we wait until the logged out state is updated, or
- Give us a better error if it fails here again (i.e. we'd know for sure if the user was seeing a logged out UI or not)
This is the failure I got, for reference:
N/A 
This is just for a Cypress test so as long as the build goes green, we're all good
N/A
development process, or any of our internal teams? …

[15 min fix] Add a step to remove flake in a cypress test

---

app/views/shared/authentication/_providers_registration_form.html.erb

On the sign up options page, each icon was being announced with the link e.g. "email Sign up with email" / "twitter Sign up with Twitter". This PR hides those icons so the accessible names are just e.g. "Sign up with email".
Behaviour before this fix:
https://user-images.githubusercontent.com/20773163/116853678-5dd8fd80-abee-11eb-8043-c236ea91bd48.mp4
N/A
- Enable some different sign up options
- Log out and click the 'create account' button
- Using either the screen reader or the dev tools accessibility inspector, check the accessible names of each button/link 
VoiceOver on Safari:
https://user-images.githubusercontent.com/20773163/116853663-574a8600-abee-11eb-8140-638e669e4b3f.mp4
This is a minor improvement for anyone using a screen reader on the site
_Will this PR introduce a change …

[15 min fix] fix accessible names of sign up options

---

app/models/admin_menu.rb

The content of the `AdminMenu::ITEMS` hash values was being modified during execution if a feature flag was enabled. This was mostly a test time concern, it would only show in a production release if a feature flag were disabled (possibly until the app was restarted).
When we call `ITEMS.dup`, the values pointed to by the keys are not
duplicated (the hash is, but the keys and values are the same). This means modification of the values (setting profile fields visible, for example) is shared between calls to me
Because the FeatureFlag enabled path is mutating the values, this is interacting during tests.
`deep_dup` the ITEMS hash before mutating when the either of the two menu item feature flags are enabled.
My failing context was this (it was seen a few times today by @vaidehijoshi ).
``` …
```

`deep_dup` the admin menu before modifying its content

---

app/views/shared/authentication/_email_registration_form.html.erb
cypress/integration/registrationFlows/emailRegistration.spec.js
cypress/support/commands.js
spec/support/seeds/seeds_e2e.rb

Currently when registering via email the form gets cleared after an unsuccessful submission. This PR fixes that. Note that work on this was originally started in #11201 but since this PR has stalled I decided to tackle this myself and added an e2e regression test.
Closes  https://github.com/forem/forem/issues/11099
1. Ensure that `Settings::Authentication::allow_email_password_registration` is set to `true`.
2. Log out any logged-in user
3. Go to http://localhost:3000/enter?state=new-user
4. Submit an invalid form (non-matching password or 1 character username).
5. You should see the validation error but the previously entered data (except for the passwords) should still be in the form.
None
-

Retain registration form data on failed submission

---

app/workers/github_repos/repo_sync_worker.rb

We've been seeing a lot of these errors on DEV, and it's a pretty reasonable expectation that if we're being blocked from seeing them using the user's OAuth access token that this isn't temporary.
We already do something similar for other errors, this is mostly the same concept but the exception class is generic, so we can't simply add the client error to the same thing or we'd be dropping repos every time we had a temporary failure.
or in a …

Handle GitHub "Repository access blocked" error

---

app/controllers/admin/badges_controller.rb
app/views/admin/badges/edit.html.erb
app/views/admin/badges/new.html.erb
spec/requests/admin/badges_spec.rb

Remove the slug form field because you can't edit it anyway -- it's auto-generated by the title. Added a description to the title.
https://github.com/forem/internalCommunity/issues/100
Edit page:
1. Go to /admin/content_manager/badges
2. Edit a badge
3. See that the slug is not update-able
Should be okay -- only updated the form text which is readable by a screen reader already.
No

[15-min-fix] Remove badge slug field b/c auto-gen by title

---

spec/requests/follows_create_spec.rb

An interaction was occurring when the data update script test to move
these settings was run prior to the rate limit test - where the rate
limiter was created with the value 23 for the follow count, but the
settings module was reporting 500.
My first attempt was to stub out the database setting to an explicit value - and allow the
user follow count to be one more (so that we trigger the rate limit
and respond with a 429).
On looking more into the settings class itself - I noticed the comment regarding caching, and tested adding a clear cache before the context instead (which is a much smaller change and causes the settings to reload correctly instead of returning the modified version). 
I still don't fully understand why the rate limiter being created/injected and the settings object were …

Clear the cached settings before testing the rate limiter

---

app/controllers/application_controller.rb
app/views/shared/authentication/_email_registration_form.html.erb
spec/requests/registrations_spec.rb

This PR resolves a bug that only happens during the Creator onboarding process; when Forem is newly generated without any user. The bug occurred because we are trying to render a shared template directly with a missing variable.
n/a
1. Enable Creator onboarding mode by adding these two variables to your `.env`
```
export MODE="STARTER"
export FOREM_OWNER_SECRET="test"
```
2. For more straight forward  QA, please reset your database with `bin/rails db:reset && bin/setup`
3. You should be able to load homepage and sign up without an issue.
N/a

Fix invalid form during Creator onboarding.

---

lib/tasks/data_updates.rake

Based on a recent discussion I thought it might be helpful to have a Rake task for quickly getting the status of data update update scripts, inspired by `rails db:migrate:status`. The task is called `rails data_updates:status` and produces output like this:
```
Status     ID              Description
--------------------------------------------------------------------------------
succeeded  20210405152916  invoke update reading list document trigger on articles
succeeded  20210218041143  backfill usernames
succeeded  20200821103718  remove orphaned display ads by organization
succeeded  20201019163242  resave articles and comments for imgproxy
succeeded  20210211164634  fix profile field edge cases
succeeded  20200916202343  backfill co author ids for articles
succeeded  20200826140317 …
```

[15 minute fix] Add data_updates:status rake task

---

app/assets/stylesheets/views/mod-actions.scss
app/javascript/actionsPanel/actionsPanel.js
app/views/moderations/actions_panel.html.erb

Fix a bug with moderator dropdowns and add aria tags.
closes #13318
I'm not really sure what this is meant to do, it looks like it just greys out other dropdowns unless they're open but then still allows click actions to work.
https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/javascript/actionsPanel/actionsPanel.js#L371-L380
N/A

Fix a bug with moderator dropdowns and add aria tags

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb

When you create a new comment on the comments page then try and access its menu no menu opens. This was caused by an error in JS.
Loosely related to #13365
N/A
N/A

🐛 Fix new comment dropdown issue

---

app/views/articles/_actions.html.erb

Edited the title of the inline svg tag when you copy the URL.
```diff
- <%= inline_svg_tag("copy.svg", aria: true, id: "article-copy-icon", class: "crayons-icon mx-2 shrink-0", title: "Notifications") %>
+ <%= inline_svg_tag("copy.svg", aria: true, id: "article-copy-icon", class: "crayons-icon mx-2 shrink-0", title: "Copy this link to the clipboard") %>
```
replace this line …

Edited the title on id="article-copy-link-input"

---

spec/support/seeds/seeds_e2e.rb

I was seeing during testing this console error:
"Error: <path> attribute d: Expected path command, "…0-4 2 2 0 000 4z\\".
Removing the `\"` and leaving just `"` seems like it corrected that (the error stops showing in console when running cypress tests, the icon is unchanged since the prior path was drawn before the error raised).
Run bin/e2e and select the loginFlows/userLogout.spec.js test, when chrome opens show the console - confirm there are no instances of that error (if you're seeing this problem you'll see it multiple times since those dummy navigation items are commonly displayed).  
None

Fix svg path error in e2e seed navigation link svg icon

---

app/javascript/article-form/components/Tabs.jsx

When I added the accessibility enhancements for navigation tabs, I accidentally added code that would add a class of 'false' to the article editor tabs when it wasn't the current one. There was no negative effect, but it's better to clean this up.
There's no user-facing change, and all should look and behave as before, except the "false" class shouldn't be added to either tab:
N/A
N/A

[15 min fix] Stop adding a false class in editor tabs

---

app/models/organization.rb
app/services/organizations/delete.rb
spec/models/organization_spec.rb
spec/services/organizations/delete_spec.rb

- delete org notifications in batches
- moved on destroy callback to the service
#12575 
#13388
No changes in the logic, organization delete should work the same way as it used to.

Organizations delete optimizations and refactoring

---

app/views/articles/_single_story.html.erb

There's a bug in #13720 where a string was passed to the `URL.tag` method instead of a `Tag` object (or something that quacks like a `Tag`)
- #13720
- https://app.honeybadger.io/projects/66984/faults/79332092
- https://app.honeybadger.io/projects/66984/faults/79332104
Viewing an article that has tags should expose it
shared_
- …

Pass a FlareTag instead of a string to URL.tag

---

db/migrate/20210511073505_add_index_on_articles_hotness_score_comments_count.rb
db/schema.rb

In #13599 we added a single index on `articles.comments_count` but, as feared, it didn't improve the performance of the https://dev.to/search/ page - which [still stands at a p50 of over 1 second](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/6ZLjSXAqToH).
According to the PostgreSQL's docs on [Indexes and ORDER BY](https://www.postgresql.org/docs/11/indexes-ordering.html), this wouldn't have worked as we need a multi column index for `hotness_score DESC, comments_count DESC`:
> You might wonder why bother providing all four options, when two options together with the possibility of backward scan would cover all the variants of ORDER BY. In single-column indexes the options are indeed redundant, but in multicolumn indexes they can be useful. **Consider a two-column index …

Add composite index to articles hotness_score and comments_count

---

config/initializers/hypershield.rb

Blazer hides PII through Hypershield.
Hypershield algorithm to match columns [is really basic](https://github.com/ankane/hypershield/blob/2c5fb02f65896f5a8c5d1604772ef177f29d210c/lib/hypershield.rb#L49), it uses `include?(string)`. 
This has the unfortunate side effect of matching every column that contains the word `email`, despite some of them being boolean settings that we need to access.
If you run `select email_comment_notifications from users limit 1` or `select email_badge_notifications from users_notification_settings limit 1` on Blazer you'll be met with an error.
This PR specifies exactly which email fields constitute PII, allowing all the boolean flags in turn.
Thanks @msarit for catching this!
Can only be tested live when the view is refreshed

Hide the correct email PII on Blazer

---

app/decorators/mention_decorator.rb
app/mailers/notify_mailer.rb
app/models/article.rb
app/models/notification.rb
app/services/articles/creator.rb
app/services/articles/updater.rb
app/services/html/parser.rb
app/services/mentions/create_all.rb
app/services/notifications/new_mention/send.rb
app/services/notifications/notifiable_action/send.rb
app/views/mailers/notify_mailer/new_mention_email.html.erb
app/views/notifications/_article.html.erb
app/views/notifications/_mention.html.erb
app/views/notifications/shared/_article_preview.html.erb
app/workers/mentions/create_all_worker.rb
spec/decorators/mention_decorator_spec.rb
spec/mailers/notify_mailer_spec.rb
spec/mailers/previews/notify_mailer_preview.rb
spec/models/article_spec.rb
spec/models/notification_spec.rb
spec/requests/notifications_spec.rb
spec/services/articles/creator_spec.rb
spec/services/articles/updater_spec.rb
spec/services/mentions/create_all_spec.rb
spec/services/notifications/new_mention/send_spec.rb
spec/services/notifications/notifiable_action/send_spec.rb
spec/workers/mentions/send_email_notification_worker_spec.rb

This PR completes the final piece of functionality to _fully_ ship [RFC #22](https://github.com/forem/rfcs/pull/22)! 🥰 
Per the RFC's [design/definition of done](https://github.com/forem/rfcs/blob/main/text/0022-expand-at-mention-to-posts.md#designimplementation), this PR does the following:
Completes https://github.com/forem/rfcs/pull/22! 🎉 
**To QA this PR, open up two browser windows, each with two different users. In this case, I have User A (Admin user) and User B (my user, `vaidehijoshi`).**
1. Start by having User B follow User A. In User A's account, create an article, and mention User B:
2. Publish the article written by User A:
3. Go to User B's account, and check that you see a notification icon:
4. Click on the icon, which takes you to the `/notifications` tab. You should see …

Expand @-mention functionality to posts

---

app/helpers/rate_limit_checker_helper.rb
app/models/article.rb
app/models/comment.rb
app/models/settings/rate_limit.rb
app/models/site_config.rb
app/services/edge_cache/bust/nginx.rb
app/services/rate_limit_checker.rb
app/views/devise/registrations/new.html.erb
app/views/shared/authentication/_email_registration_form.html.erb
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/requests/admin/configs_spec.rb
spec/system/onboardings/user_completes_onboarding_spec.rb

Addresses this `TODO` now that RFC #22 has been completed with https://github.com/forem/forem/pull/13367
https://github.com/forem/forem/blob/11bab732c0ff477b177495e4e1ee9b979c24be9b/app/models/article.rb#L28-L30
Also removes my name from all the `TODO`s I added previously for myself 😿 
Follow up task to [RFC #22](https://github.com/forem/rfcs/pull/22)
1. Check that you _cannot_ create a post with more than 7 @-mentions (this is the default value for `Settings::RateLimit.mention_creation`):
2. Check that you _can_ create a post with 7 or fewer @-mentions:
3. Check that you _cannot_ create a comment with more than 7 @-mentions
4. Check that you _can_ create a comment with 7 or fewer @-mentions:
5. Go to the admin view `/admin/customization/config`, and check that you can see the limit for …

Replace MAX_USER_MENTIONS with Settings::RateLimit.mention_creation

---

app/services/articles/updater.rb
spec/services/articles/updater_spec.rb

Shortly after https://github.com/forem/forem/pull/13367 was deployed to the fleet, @Zhao-Andy helped me test this feature out on a Forem instance, after which we discovered that mention notification were not deleting after a post was unpublished!
As it turns out, we _did_ have code for this in `Articles::Updater`:
https://github.com/forem/forem/blob/e53b6bff853a5f79bbebbf1ce8be98eae6a0b024/app/services/articles/updater.rb#L50-L53
...but there was a typo in the code (🤦🏽‍♀️) and because there were no _pre-existing tests_ for this in the `updater_spec.rb`, this bit of behavior was missed completely in the specs and wasn't caught in code review/QA! 🙈 
While fixing this, I realized that we also _don't_ have any tests for the "remove preexisting comment notifications" behavior for _comments_, …

[15 Min Fix]: Remove any preexisting mention notifications when article is unpublished

---

app/helpers/rate_limit_checker_helper.rb
app/lib/constants/settings/rate_limit.rb

I noticed today that two places still accidentally reference `SiteConfig` instead of `Settings::RateLimit` and this PR fixes that.
RFC#126
n/a
n/a

Fix wrong `SiteConfig` mentions

---

.travis.yml

Our Travis cache is currently 2274.37MB . This PR would cut that down to 1221.85MB
I achieved this by going back to the default caching method, only caching `bundle` and `node_module`. The reason our cache size is so large could be because
- Cypress's binary is 800MB
- caching `~/.cache` may have picked up a lot more things that we would've wanted.
I understand that Cypress's documentation recommended Travis caching the binary, but this is still data that is downloaded from a source which is then uncompressed and compressed at the end of the build. Manually running `yarn cypress install` [only takes 16 seconds](https://travis-ci.com/github/forem/forem/jobs/505285944#L2738) and ensure that we are using only the latest binary. We also wouldn't be caching older versions of the binary which …

[Travis] Only cache vendor/bundle and node_modules

---

docs/getting-started/workflow.md

Fixing a typo in the "Suggested workflow" section of the documention, which states "upsteam" twice instead of "upstream".
None. 
None. 
None. 
This only changes 2 typos in the docs.
No.

Fix typo: 'upsteam' -> 'upstream'

---

app/views/admin/overview/index.html.erb

In the admin check list we still referenced creators.forem.com which doesn't exist anymore. This PR updates the copy to forem.dev as requested by @michael-tharrington.
Closes https://github.com/forem/rfcs/issues/217
None

[15-minute fix] Remove mentions of creators.forem.com

---

app/lib/constants/site_config.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb
app/views/pages/_privacy_text.html.erb
config/routes.rb
lib/data_update_scripts/20210517091342_remove_shop_url_from_site_config.rb
spec/requests/admin/configs_spec.rb
spec/requests/pages_spec.rb
spec/routing/all_routes_spec.rb

This PR removes `shop_url` from `SiteConfig` and also all the related code. This is better handled via a `NavigationLink`. 
#13583
Nothing specific, just removing code.
None

✂✂✂ Remove `shop_url` from `SiteConfig` ✂✂✂

---

.env_sample
app/services/images/optimizer.rb
config/initializers/cloudinary.rb
spec/helpers/application_helper_spec.rb
spec/helpers/social_image_helper_spec.rb
spec/models/html_variant_spec.rb
spec/models/message_spec.rb
spec/models/podcast_episode_spec.rb
spec/services/html/parser_spec.rb
spec/services/images/generate_social_image_spec.rb
spec/services/images/optimizer_spec.rb
spec/services/images/profile_spec.rb
spec/services/markdown_processor/parser_spec.rb
spec/support/initializers/image_processing.rb
spec/system/user_uses_the_editor_spec.rb
spec/view_objects/cloud_cover_url_spec.rb

Currently we tell people to copy `.env_sample` to `.env` but if they then try to link an external image (without uploading it) in a post, the `Images::Optimizer` will try to generate a Cloudinary URL and leave the user with a broken UX.
I think `Images::Optimizer` should just return the image URL verbatim if neither Cloudinary nor Imgproxy are configured and that we should have that as a default for new installs.
1. set `CLOUDINARY_API_KEY` and `CLOUDINARY_CLOUD_NAME` back to `Optional` (or anything really), start the app, get a [image URL](https://media1.tenor.com/images/38764a3868c2dd4f8c1253c4e9ec896e/tenor.gif) and create a post with:
```markdown
```
2. Cloudinary will create a broken URL because
3. empty `CLOUDINARY_API_KEY` and `CLOUDINARY_CLOUD_NAME` again and restart the app, …

[15 min fix] Fallback to the image URL if Cloudinary/Imgproxy are not configured

---

app/controllers/follows_controller.rb
app/services/follows/check_cached.rb
app/services/follows/delete_cached.rb
cypress/integration/profileFlows/followUser.spec.js

After unfollowing a user from their profile page, the UI would initially reflect the correct 'unfollowed' state, but on page refresh it would incorrectly show the UI that suggests you're following them (i.e. a button saying "Following"). Going to the dashboard > following users screen you could verify that the unfollow had been successfully processed, it's just the UI on the profile page was incorrect.
After a bit of investigation, it turned out this was because the call to `/follows/<userid>?followable_type=User` was cached in the backend, and kept returning the original 'followed' state.
As a small disclaimer - I'm not a backend dev 😅  I decided to give this a go since I'd already completed some investigation, but if this totally isn't the way we'd want to go about invalidating the …

Fix UI showing "Following" after unfollowing a user

---

app/views/articles/_actions.html.erb
app/views/articles/_full_comment_area.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/articles/show.html.erb
app/views/comments/_comment_footer.html.erb
app/views/comments/_form.html.erb

This PR optimizes the print view of an article by hiding additional elements such as the moderation button (full list below).
Closes #13759
All elements with a class `print-hidden` should now be hidden in the print preview of an article:
- Header
- Footer
- "Read next"
- Moderation button
- Moderation sidebar
- Article actions (favorite/bookmark/...)
- "Follow" button
- Input field for new comments
- Like/reply buttons for comments
- "Subscribe" button
All other elements should still be visible.
None.

#13759 : hide content in print mode

---

app/assets/javascripts/initializers/runtime.js
app/javascript/article-form/components/EditorBody.jsx
app/javascript/article-form/components/ImageUploader.jsx

When copying to the clipboard (uploaded image url) in the Editor Post sometimes the `navigator.clipboard` is `undefined`.
The promise chain wasn't handling exceptions so this PR adds a `catch` instead of silently failing.
closes https://github.com/forem/forem-ios/issues/55 https://github.com/forem/ForemWebView-ios/issues/26
**Note/disclaimer:** If you don't have the iOS app to test this that's okay, a code review and a manual test this feature works on Desktop is also valuable 👍 
1. Open the Forem iOS app (kill app first for fresh start)
2. Go to the Editor as soon as the page loads
3. Upload an image
4. Click "Copy"
5. It should work or display a Snackbar message with the error
**Video of the Snackbar in action**
https://user-images.githubusercontent.com/6045239/118721802-8d8c2600-b7e8-11 …

Add error handling to clipboard promise - post editor

---

app/views/articles/show.html.erb

PR #13759 hides certain content in order to print an article, but it contains a bug: a CSS class was added to an `id` attribute. Unfortunately this breaks [this call](https://github.com/forem/forem/blob/d195270383d536f3daf5c895efee86a0610db0a5/app/javascript/actionsPanel/initializeActionsPanelToggle.js#L40-L42) to fetch mod actions.
Mods should see the purple button here (the red button is due to a browser extension but also apparently hooks onto the same parent element):
Unfortunately it is missing:
#13759 
- Log in as a mod
- Load an uncached article (if necessary, delete it from the Fastly cache, ask SRE if needed)
- Action button should render …

Move print-hidden to a class attribute

---

app/services/markdown_processor/parser.rb
spec/services/markdown_processor/parser_spec.rb

This allows us to do something like:
````
~~~
hello
```
me showing you how to do a codeblock with triple backticks, nested within triple tildes
```
~~~
````
This isn't a perfect solution, but I definitely went out of my time box for this. Wanted to fix this edge case at least so _some_ users can start using it. See QA instructions for code examples of what I'm talking about.
I think the bigger issue is that we parse codeblocks through Liquid `{% raw %}` tag, when maybe it should be parsed through our Markdown parser Redcarpet. Will make an issue out of it instead.
forem/internalCommunity#116
https://github.com/forem/forem/issues/13823
1. Go to /new
2. Try this codeblock:
````
​~~~
hello
// ```
whatever
// ```
~~~
````
3. Then try this codeblock (which should NOT work) same as above, …

[15-min-fix] Add option for triple tildes for fenced codeblocks

---

docker-compose.yml

Problem: Users are unable to login when using docker in development.
Suspected cause: HTTP Origin header doesn't match the (docker internal) name specified in the APP_DOMAIN.
There was an issue seen with the HTTP Origin header not matching (the error unhelpfully reported "localhost:3000" did not match
"localhost:3000").
Change the APP_DOMAIN internally to localhost:3000 (which is what the user will in fact use, not rails), and since that breaks the http requests from the db seed and sidekiq containers, allow them to only check for a tcp connection instead of expecting a 200
response (sending requests to the disallowed host `rails` triggered a 403).
Related to discussion in https://github.com/forem/forem/issues/4955
https://github.com/forem/forem/issues/13696 looks related as well …

Update docker-compose.yml to use localhost as app domain

---

db/seeds.rb

I had to reset my local development DB and this step kept failing with "Invalid category" because a non moderator was selected as the user to leave a `vomit` reaction.
While debugging this I noticed how I had the `Rails.cache` object pointing to Redis. `user.trusted` kept returning `false` even though the user was a moderator, the reason was the following:
https://github.com/forem/forem/blob/967c65557327f3962f12a492a424c36339e11998/app/models/user.rb#L426
I had data in the cache from the previous version. The alternative to bypassing the cache is to clear it.

Disable cache while seeding to fix "invalid category error"

---

.env_sample
config/initializers/carrierwave.rb

We have "Optional" as the placeholder in the .env_sample, if someone copied .env_sample to .env, they'd have AWS_ID present but not valid or meaningful.
~When that's the "final" value in the .env file, assume we're actually going to use local storage instead.~
~Because there are related guards around production mode this should have limited to no prod impact (outside of self-hosting, where I assume this is a net-improvement in usability). Forem clould has its own configuration. ~
~I'm surprised this hadn't been a bigger problem.~
Ensure `AWS_ID=` in your .env, then load the app
Change a user's profile image.
Ensure the new image is visible.
None, this _should_ be a develop/test only change.
development process, …

When AWS_ID is the placeholder value, act as though AWS not setup

---

app/controllers/profiles_controller.rb
app/controllers/stories_controller.rb
app/models/profile.rb
app/services/profiles/update.rb
app/validators/profile_validator.rb
db/migrate/20210503205816_add_static_profile_fields_to_profile.rb
db/schema.rb
lib/data_update_scripts/20210503175027_move_summary_websiteurl_and_location_to_profile.rb
spec/factories/profiles.rb
spec/system/user/user_edits_profile_spec.rb

Move static profile fields to profiles columns
In order to remove some ambiguity around the availability of certain
profile fields, we can designate certain fields as "static." These
fields are intended to exist on every Forem regardless of configuration;
they contain basic personal info that most Forem's will likely use.
Because these fields already exist on some Forems it is necessary to
migrate the data from existing profile's data column to their respective
columns.
This change should behave as expected irrespective of the existence of
the static fields having associated ProfileFields, however, the UI that
is rendered in a user's settings still depends on the presence of the
ProfileFields. We can address that in a future change when we are
prepared to delete those ProfileFields …

Migrate "static" profile fields into new columns

---

app/assets/javascripts/base.js.erb
app/assets/stylesheets/components/header.scss

This PR aims to fix an issue where Skip Links only functioned when landing on a URL, not when using the keyboard to access internal links. With the added changes we are now sending focus immediately to the Skip Link when visitors are using a keyboard, and hiding it when a mouse is used.
Tested manually with keyboard and mouse on Edge, Chrome and Firefox. Ran checks using Axe DevTools and ANDI to ensure no unwanted behaviours have been introduced.
**QA steps**
- go to the homepage
- use the keyboard to navigate between pages and check that Skip Link appears on every link
- use your mouse to navigate between pages and ensure that Skip Link does not appear
- refresh the page and make sure Skip Link does not appear
- press Tab and make sure Skip Link appears
_Additional notes if you can't see …

autofocus Skip Link on keyboard navigation

---

.yarnclean

Our `.yarnclean` is a bit too aggressive:
1. I noticed Travis builds log this:
```
Failed to write coverage reports:
ERROR: Error: ENOENT: no such file or directory, scandir '/home/travis/build/forem/forem/node_modules/istanbul-reports/lib/html/assets'
STACK: Error: ENOENT: no such file or directory, scandir '/home/travis/build/forem/forem/node_modules/istanbul-reports/lib/html/assets'
at Object.readdirSync (fs.js:1043:3)
at /home/travis/build/forem/forem/node_modules/istanbul-reports/lib/html/index.js:331:16
at Array.forEach (<anonymous>)
at HtmlReport.onStart (/home/travis/build/forem/forem/node_modules/istanbul-reports/lib/html/index.js:328:25)
at LcovReport.<computed> [as onStart] (/home/travis/build/forem/forem/node_modules/istanbul-reports/lib/lcov/index.js:28:23)
at Visitor.value …
```

Remove assets folder from .yarnclean

---

config/environments/development.rb

In [development.rb](https://github.com/forem/forem/blob/main/config/environments/development.rb#L35), `config.action_mailer.perform_caching = false` are called twice, so I deleted one of them. Although I also check production.rb and test.rb in environments directroy, there is no same problem.

Call `config.action_mailer.perform_caching = false` only once in development.rb

---

app/helpers/profile_helper.rb
app/views/users/_profile.html.erb
cypress/integration/profileFlows/userUpdateSettingsProfile.spec.js
spec/factories/profile_fields.rb

After #13641 was merged we lost the ability to correctly display the "profile static fields" in the `Settings -> Profile` page. Update works, it's just display that's looking in the wrong place.
Closes https://github.com/forem/forem/issues/13879
1. Open the branch
2. Change either website URL, summary or location
3. Save the profile information
4. Check they are displayed in the page

Settings: Correctly display profile field static values

---

app/models/article.rb

`Article.cached_tagged_by_approval_with` is unused ✂️  ✂️  ✂️

Remove unused cached_tagged_by_approval_with Article scope ✂️ ✂️ ✂️

---

package.json
yarn.lock

This reverts commit a45d83eafafaedfbeec6786b841925de91558388.
Yesterday I merged an upgrade to `jest-watch-typeahead` which introduced a dependency on node `14.5` or above. This worked locally for me as I have 14.7 installed but it's causing failures in all of our buildkite builds which are using 14.4.
For visibility, cross-posting here some context from @djuber on whether or not we can upgrade the node version in buildkite:
> I think so - it basically boils down to installing node from the upstream package (rather than from the OS) - it's probably something to ask @forem/systems if they care strongly about, if not the change will be in Containerfile to install node directly rather than via dnf.
> #13136 (comment) related discussion/decision in the past
> Talking with Joe in slack - it …

Revert "Bump jest-watch-typeahead from 0.6.3 to 0.6.4 (#13888)"

---

cypress/integration/navigationFlows/homePageLeftSidebar.spec.js

This spec has been giving us a bit of pain in CI recently - I finally managed to reproduce it failing locally and found that where we have "repeat and assert", we were getting a reference to `#page-content-inner` on the previous page, rather than the homepage. The test then fails because the "More" link it's looking for is no longer in the DOM (as it's on the previous page).
I've added a step to make sure we're back on the home page before we continue.
N/A
The spec passing in CI is QA enough on this one
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._N/A
_Will this PR introduce a change that …

[15 min fix] Reduce flake in sidebar navigation spec

---

app/assets/stylesheets/components/stories.scss

I just noticed after #13871 that there is this small overflow where the cover image element does not have the proper border radius now that we have made the small screen different from big screen.
The fix is that the breakpoint is no longer needed.
#13871
Eye-ball it. Should be safe IMO.
No
- [x ] No, and this is why: Tiny eyeball fix.

[Tiny fix] Fix border radius issue on home feed

---

app/views/articles/index.html.erb

Ahead of the broader iOS launch, I'm seeing a couple mobile bugs that are worth squashing. This whole functionality may change with work to the home page, but in the mean time we can fix this issue.
The trailing slash is necessary because otherwise the value for `value` is blank, which results in nothing. Trailing slash is needed for home page. This got removed at some point erroneously. This is a tiny one character fix to get it working as it should as more folks will use the mobile experience.
https://github.com/forem/forem/issues/13901
Go to "month" and then go to "feed" in mobile view. In prod it won't work. It should with this fix.
I don't think so.

[Tiny fix] home page mobile select bug

---

app/models/article.rb
spec/models/article_spec.rb

We're experiencing some errors wrt `FastImage` calls on DEV/Cloudinary. Adding a feature flag guard so it can be enabled and disabled at runtime

Add :detect_animated_images feature flag to guard animated images detection

---

app/assets/stylesheets/components/buttons.scss

This is a hacky way to fix an issue where we don't want click events to bubble up generally, with the exception of `<input>` elements.
Resolves https://github.com/forem/forem/issues/13917
1. Go to /new
2. See that the "Add Cover Image" and "Upload Image" buttons open the file picker
I think not?
Nope

[15-min-fix] Add quick fix to resolve input events not bubbling up

---

config/routes.rb

While looking through our `routes.rb` file I noticed a comment that mentions that a specific route should be removed on January 11th. We are quite a long time past that and we don't have Team Smash anymore, so I decided to remove it in this PR.
n/a
n/a
None

[15-minute fix] Remove deprecated route

---

spec/requests/stories/pinned_articles_spec.rb

Fixes a rubocop warning
Run rubocop on the file and confirm no warnings.
Wow, github loves full sized images.

Change header name to double quoted string literal

---

app/services/feeds/assemble_article_markdown.rb
spec/services/feeds/assemble_article_markdown_spec.rb

When an rss feed includes items with long titles, the created Articles fail validation (silently) and no draft post is created in the dashboard. 
Following the pattern we follow for long article descriptions, if the title is too long, just truncate and add ellipsis. 
The author can fix this up if desired in the editor when setting `published: true`    
This didn't go through any RFC or product decision making process, it's the smallest fix I can think of to stop dropping imported content because of long titles. 
Fixes #13959
I set the test user's feed_url to the reporter's rss feed - https://www.opennms.com/feed/
I then called `Feeds::Import.call(users: User.where(id: the_user_id))`, which is what the feed worker does internally on a refresh.
On main only 7 articles were created (with …

15 minute fix: Shorten long titles from feed items if needed

---

app/assets/javascripts/initializePage.js
app/assets/javascripts/initializers/initializeUserProfilePage.js
app/javascript/packs/profileDropdown.js
app/views/users/show.html.erb
cypress/integration/profileFlows/profileUserActionsMenu.spec.js

This PR continues the work under #12297 - Optimise all dropdowns for accessibility. It applies the new dropdown initializer on the Profile page for the "flag/block user / report abuse" menu.
In doing this work, I've moved the relevant code to packs instead of initializers. I've also fixed a bug we had where once you'd visited a given profile page, we were attaching additional click listeners on every page navigation. This resulted in the confirmation alert being shown _N_ times when you clicked "flag/block", with _N_ being the number of pages you'd visited since the first time you were on the profile page.
#12297
In all cases, the dropdowns mentioned below should function as follows:
- Opens and closes with a mouse click on the relevant button
- Button can be focused by keyboard, and …

Optimise dropdowns for accessibility - Profile page

---

cypress/integration/loginFlows/userChangePassword.spec.js

The spec "should give an error if the new password/confirm new password fields do not match when changing the password of a user" was occasionally flaking both in CI and locally. After a bit of investigation, we figured out that the previous test was actually what was causing the issues.
The prior test "should change the password of a user" finishes with a sign-in action. Signing in results in a couple of async network requests for notification count and base user data firing off, and they were occasionally still in progress when the test finished. This seemed to be causing issues with running our `testSetup` steps, logging in the user for the next test.
I've used Cypress intercepts to identify those network requests and wait for them to be resolved before moving on. It doesn't …

[15 min fix] Flakey "change password" spec

---

package.json
yarn.lock

Reverts forem/forem#13973
It seems like this PR may have bumped jest dependencies or transitively changed something related to `jest-regex-util`, which now requires node version `14.15.x` and we are using `14.14.x` on our Buildkite pipeline.
Maybe we want to bump our node version or we want to revert this `jest-watch-typeahead` patch version until we do.

Revert "Bump jest-watch-typeahead from 0.6.3 to 0.6.4"

---

app/models/user.rb
spec/models/user_spec.rb

`subscribe_to_mailchimp_newsletter` callback is called by `after_save`. `after_save` is called before the transaction is committed, so `Users::SubscribeToMailchimpNewsletterWorker` is called and find the user before the user setting is committed to the database.
https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb#L6-L10
Thus, `Mailchimp::Bot`(instantiated by `Users::SubscribeToMailchimpNewsletterWorker`) might use **old** user data and send it to MailChimp in certain circumstances(e.g. the worker is not busy).
https://github.com/forem/forem/blob/6dfabd578f727cad8776ba65930a2889b1573faf/app/services/mailchimp/bot.rb#L28
Actually, when I set up MailChimp in the local environment and commented the …

Call subscribe_to_mailchimp_newsletter after the transaction is commited

---

app/models/user.rb

I misunderstood our Mailchimp usage when I added this boolean -- this PR simplifies it a bit. We had a weird edge case where a Forem had a Mailchimp newsletter ID set, but no Mailchimp API key. Without an API key, we don't actually interact with the newsletter, and therefore should `return` early instead of also checking for the newsletter ID's blankiness.
https://github.com/forem/internalCommunity/issues/127
None 😅 the tests should handle this.
Nope
Nope

[15-min-fix] Remove check for blank mailchimp newsletter ID

---

cypress/integration/profileFlows/profileUserActionsMenu.spec.js

After merging some new Cypress tests in #13916 there's been a couple of instances of flake in CI (I haven't been able to reproduce locally). After running in a debug build I could see the issue was similar to that in #13979 - the "logged out" user test runs last and previous unfinished network requests interfere with teardown/setup of that last test.
The screenshot grabbed from the failure shows the user was logged in, when we expected them to be logged out:
For the moment, I've switched the order so that logged out tests happen first. I'm not totally happy with "fixing" by relying on a specific order of tests, but I think it makes sense generally to run 'logged out' tests before 'logged in' tests. 
We will need to look at this problem with test setup, but I think it would be worth doing …

[15 min fix] Improve reliability of profile dropdown test

---

app/views/articles/index.html.erb
app/views/stories/tagged_articles/index.html.erb
cypress/integration/homeFeedFlows/feedNavigation.spec.js
cypress/integration/tagsFlows/tagIndexNavigation.spec.js

The `aria-current` attribute should be added only when necessary, IMHO.  Currently, there are multiple `aria-current=""`, which does not pass the HTML validator.
https://github.com/forem/forem/issues/13289

fix usage of aria current - html error

---

app/models/user.rb
spec/requests/admin/invitations_spec.rb
spec/system/user_logs_in_with_password_spec.rb

By default, Devise emails are sent synchronously in `after_commit` callbacks, which means that if any of the callbacks fail (which happened recently when we misconfigured email sending), then all following callbacks aren't run.
I can't find a reason to have invitation and confirmation emails being sent synchronously, thus I'm following [Devise instructions](https://github.com/heartcombo/devise#activejob-integration) to use `ActiveJob` for those emails and thus the async queue.
#13983 

Send Devise emails asynchronously

---

config/initializers/honeycomb.rb

Any production Forem instance that did not configure a Honeycomb API key experiences a memory leak. Anyone who's running on Heroku wouldn't see much impact without a lot of traffic since Heroku restarts all dynos every 24 hours, but anyone hosting it on other platforms would likely see it.
This was added in #4725 to avoid failures when a Honeycomb API key wasn't set. Newer versions of the gem appear not to need this workaround — they switch to the [`NullClient`](https://www.rubydoc.info/gems/libhoney/Libhoney/NullClient) automatically. I had no errors with this.
Shout out to @djuber for discovering where the leak was. I was looking in other areas for differences between self-host and official Forem production configs. I was in the middle of looking at the sitemap generation when Dan found …

Don't use Honeycomb test mode in production

---

app/assets/javascripts/initializers/initializeBaseUserData.js

One of our Cypress tests was occasionally flaking trying to click the "Edit" button on the article page. After a bit of investigation, I noticed what was happening is that the `addRelevantButtonsToArticle` was being called multiple times, effectively removing and replacing the Edit/Manage/Stats buttons again and again. Cypress was occasionally getting a handle to an Edit button that was then immediately removed and replaced by an identical button, resulting in an error when it tried to click the original button which had been removed from the DOM.
This is a very quick fix to stabilise the Cypress test. Longer term, there might be more refactoring useful here.
N/A
To QA this we need to make sure:
- When you view an article the correct buttons appear for your own post (Edit / Manage / …

15 min fix - only initialise article  buttons once

---

app/models/forem_instance.rb
app/views/layouts/_footer.html.erb
spec/system/layout_spec.rb

This PR removes navigation links from the footer for private Forems.
Closes https://github.com/forem/forem/issues/14005
**Before:**
**After:**
None

[15-minute fix] Remove navigation links from footer on private Forems

---

app/controllers/users_controller.rb
app/workers/feeds/import_articles_worker.rb
spec/requests/user/user_settings_spec.rb
spec/workers/feeds/import_articles_worker_spec.rb

While reviewing a PR today I noticed the following call:
```ruby
Feeds::ImportArticlesWorker.perform_async(nil, users_setting.user_id)
```
I found this a bit hard to read so I looked at the method signature:
```ruby
def perform(earlier_than = nil, user_ids = [])
```
I'm not particularly fond of this signature for two reasons:
* It's not clear at all what `nil` represents
* If you want to specify user ids, you have to explicitly pass in `nil` and can't use the default
Originally I wanted to suggest `def perform(user_ids = [], earlier_than: nil)` but then remembered that this is a worker, so I just opted to reverse the argument order instead. 
The reason I decided to do this is that the above example is the only place where we explicitly pass in arguments so I think we should optimize for …

[15-minute fix] Change signature of Feeds::ImportArticlesWorker

---

scripts/build_containers.sh

To help alleviate tag fetching speeds, we're going to auto-expire/delete a container tag after 8 weeks. That should be ample time and if a certain PR needs more time, a commit is all that is needed to create a new tag. shoutout to @jdoss for the intructions.
https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/use_red_hat_quay/working_with_tags
N/A
n/a

Add container tag expiration

---

app/helpers/application_helper.rb
app/helpers/authentication_helper.rb
app/services/authentication/providers.rb
app/views/admin/settings/forms/_authentication.html.erb
app/views/devise/registrations/_registration_form.html.erb
app/views/shared/authentication/_providers_registration_form.html.erb
spec/helpers/authentication_helper_spec.rb
spec/system/authentication/creator_config_edit_spec.rb
spec/system/authentication/user_logs_in_with_email_spec.rb
spec/system/authentication/user_logs_in_with_facebook_spec.rb
spec/system/authentication/user_logs_in_with_github_spec.rb
spec/system/authentication/user_logs_in_with_twitter_spec.rb

#14006 introduced a new helper method, `ForemInstance.private?`. This PR tries to standardize usage across the codebase so we don't check `Settings::Authentication.invite_only_mode` directly. It's also an attempt to unify the domain language we use as I've seen both "invite only mode" and "private" used interchangeably.
n/a
Nothing specific, all existing specs should still be green.
None.

[15-minute fix] Consistently use `ForemInstance.private?`

---

app/assets/stylesheets/profile-preview-card.scss
app/javascript/utilities/dropdownUtils.js

This fixes a small issue in the Profile Preview Card work, where after a user has activated a preview card with a click, the hover functionality no longer worked.
**This is it before:**
https://user-images.githubusercontent.com/20773163/122761189-de81b500-d293-11eb-9c3c-737ca0f8b3e9.mp4
**And this is it now:**
https://user-images.githubusercontent.com/20773163/122761214-e3deff80-d293-11eb-981f-fb28b86864ba.mp4
#13990
- Go to an article on desktop
- Hover over the author name, and check the preview card appears
- Open the preview card fully by clicking on the author name
- Click the button again to close the preview card (or click outside / press Escape)
- Hover over the author name again to check the preview card appears
N/A - the core functionality of the preview card is keyboard …

Always show preview card on hover

---

.gitignore
app/workers/sitemap_refresh_worker.rb
config/sitemap.rb

The memory leak we thought we fixed in #13997 definitely slowed the leak by a lot, but it turns out there was another leak due to 2 different factors:
1. We were [loading the Rake tasks on every invocation of the `SitemapRefreshWorker`](https://github.com/forem/forem/blob/5a75e303bded8de02ddf5d9c1a4fb5623e2f7873/app/workers/sitemap_refresh_worker.rb#L7)
2. `SitemapRefreshWorker` was failing if [AWS credentials were not provided to store the sitemap](thttps://github.com/forem/forem/blob/5a75e303bded8de02ddf5d9c1a4fb5623e2f7873/app/workers/sitemap_refresh_worker.rb#L7), causing the job to be retried 10x beyond each time it was invoked on purpose
To test this, I ran `SitemapRefreshWorker` 1000x before and after this change.
- #13997 
Run `SitemapRefreshWorker` a few thousand times in the …

Fix sitemap for self host, including memory leak

---

app/workers/mentions/send_email_notification_worker.rb
spec/workers/mentions/send_email_notification_worker_spec.rb

This adds `.deliver_now` to the mention email notification worker, which previously was not sending any mention emails.
Run the tests 😎 
```
rspec spec/workers/mentions/send_email_notification_worker_spec.rb
```
Nope, backend change
Nope

[15-min-fix] Ensure mention worker delivers email

---

config/sitemap.rb

Rename a variable that was missed.
Resolves the following sidekiq error
```
NameError: undefined local variable or method `config_hash' for #<SitemapGenerator::Interpreter:0x00007fa7c6830d68> Did you mean? s3_config_hash
```
https://github.com/forem/forem/pull/14036
eh
n/a

Resolve sitemap's undefined variable

---

app/views/admin/tags/edit.html.erb
spec/system/admin/admin_creates_new_tag_spec.rb

This PR fixes a broken "Remove" button on `/admin/content_manager/tags/:id/edit` that enables Admins to remove moderators from tags by adding `local: true` to the form that handles this, `/admin/tags/edit.html.erb`. Additionally, this PR refactors `admin_creates_new_tag_spec.rb`.
Relates to PR #14049 
- Click on the name of an existing tag on the `/admin/content_manager/tags` page:
- Add a moderator to your tag by inputting the ID of a moderator and by clicking the "Add Moderator" button while on the tag's edit and observe that upon clicking the "Add Moderator" button that you are properly redirected to the tag's edit page where you are shown a flash message indicating that the creation was a success!:
- Now, test that you are able to remove the moderator that you added by clicking the …

[15-Minute Fix] Fix Broken Admin Tags "Remove" Mod Button

---

babel.config.js

Squelch this warning that happens a few dozen times during CI by
following the instructions:
```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```
```
yarn build-storybook
```
If you see 800 or more lines of the quoted …

Add explicit loose configuration for babel plugins

---

app/assets/javascripts/base.js.erb
cypress/integration/searchFlows/skipToContent.spec.js

Right now when triggering a search with enter we wrongly show the "Skip to content" link intended for keyboard navigation. This PR adds an exception for the `/search` page as suggested by @aitchiss.
Closes #13876
1. Start a local server
2. Go to the homepage
3. Type something in the search bar and hit enter
4. You should **not** see the "Skip to content" link shown in this screenshot
None

Don't show "Skip to content" link for searches

---

spec/services/search/username_spec.rb

Fixes flaky search test case
```
1) Search::Username::search_documents finds multiple users whose names have common parts
Failure/Error: expect(usernames).not_to include(rhymes.username)
expected ["alex", "username2222", "rhymes"] not to include "rhymes"
```
We could mistakenly be picking up matches on user "name" rather than
user username due to faker giving a name like "Gale" or "Haley" or
"Annalee" which match the search term "ale".
Give an explicitly non-matching pattern for the name string to prevent
this.
Sampling from Faker::Name.name and filtering for case insensitive
matching against the search term shows slightly higher than 1% of
results will match this "ale" triple. Low enough to go unnoticed for a
long time, high enough to happen every week or two forcing a re-run.
Test only …

Prevent occasional matching on random name by specifying one

---

app/javascript/chat/util.js

Thanks to [this tweet](https://twitter.com/jaffathecake/status/1405437361643790337) I found out that resize and inteserction observers leak memory in certain browsers if they aren't manually disconnected, which we do everywhere except in the chat.
Apparently most browsers have in the meantime fixed it upstream but because we want to be good citizens and we can't predict if our users have the latest version already, we should close the loop and cleanup.
1. Load the chat
2. Click on the Forem logo at the top
3. make sure nothing breaks in the console

Chat: disconnect IntersectionObserver to avoid leaking memory

---

app/controllers/admin/invitations_controller.rb
app/controllers/registrations_controller.rb
app/services/authentication/authenticator.rb
db/migrate/20210629174206_change_default_value_for_saw_onboarding.rb
db/schema.rb

Changing default saw_onboarding to false and removing all the manual code we've sprinkled around. I believe it's initially set to true when the feature was implemented and we never got around to changing it.
Initially suggested by @citizen428 on https://github.com/forem/forem/pull/13903/files#r644458615
You should not notice anything with this change
n/a

Change default value for saw_onboarding

---

app/workers/metrics/record_data_counts_worker.rb

I would like to create a monitor for tracking parity between User and Profile but we are currently not tracking any Profile counts. This fixes that.
n/a
n/a
n/a

Track Profile count in RecordDataCountsWorker

---

cypress/integration/articleFlows/pinArticle.spec.js

After merging https://github.com/forem/forem/pull/14102 we still had a Cypress test failure due to a flaky spec.
The test causing the flake was very fast-running - go to a page and verify an element is not there. Despite waiting on user-related network requests, there were still lingering network requests relating to the article page which caused the wrong user to be logged in for the next test.
I've stubbed those network requests to avoid issues, and also added a `find` for the article heading, as I think we want to make sure that the article page has definitely loaded before asserting the pin post button isn't visible.
N/A
A green light on the CI integration tests is all we need
N/A …

[15 min fix] Stub article network requests in pinPost cypress test

---

app/models/profile.rb
app/validators/profile_validator.rb
app/views/users/_profile.html.erb
cypress/integration/profileFlows/userUpdateSettingsProfile.spec.js
lib/data/dev_profile_fields.csv
lib/data_update_scripts/20210630063635_drop_profile_fields_for_static_attributes.rb
spec/lib/data_update_scripts/create_profile_fields_spec.rb
spec/lib/data_update_scripts/drop_profile_fields_for_static_attributes_spec.rb
spec/models/profile_spec.rb

In #13641 we migrated some profile data from `ProfileField`s to actual columns on the profile table. It's time to remove these columns now. Additional clean-up will happen in follow-up PRs if/when necessary.
Nothing specific, specs should suffice.
n/a

Drop profile fields for static attributes

---

scripts/build_containers.sh

This expires the SHA256 tag after 2 months leaving the other production tags alone.

Expire the SHA tag after 2 months.

---

app/controllers/admin/listings_controller.rb
app/views/admin/listings/edit.html.erb
spec/requests/admin/listings_spec.rb

This allows admins to add organization IDs to listings via the admin listings form.
https://github.com/forem/internalCommunity/issues/142
1. Visit http://localhost:3000/admin/apps/listings
2. Click on a listing (Might need to check the "Include unpublished" option)
3. Add an organization ID `1` or something
4. See that it persisted on the listing
Nope
- I will communicate with the relevant teams

[15-min-fix] Add org id to admin listings form

---

db/seeds.rb

I encountered `NoMethodError` after created the user from the application. The detailed log is below.
```
14:03:44 sidekiq.1   | 2021-07-07T05:03:44.594Z pid=7738 tid=3366 class=Notifications::WelcomeNotificationWorker jid=284e62301d2db0968d084069 INFO: start
14:03:44 sidekiq.1   | 2021-07-07T05:03:44.611Z pid=7738 tid=3366 class=Notifications::WelcomeNotificationWorker jid=284e62301d2db0968d084069 elapsed=0.017 INFO: fail
14:03:44 sidekiq.1   | 2021-07-07T05:03:44.611Z pid=7738 tid=3366 WARN: {"context":"Job raised exception","job":{"retry":10,"queue":"low_priority","class":"Notifications::WelcomeNotificationWorker","args":[12,1],"jid":"284e62301d2db0968d084069","created_at":1625633981.08381,"enqueued_at":1625634224.5929441,"error_message":"undefined method `id' for …
```

[Fix] NoMethodError caused because no mascot account exists in a development environment

---

config/initializers/honeycomb.rb

This configures the fallback behavior we're relying on in self-hosted
forems, and disables a warning that the fallback is happening.
https://github.com/forem/forem/pull/13997 changed the initializer to not use test mode (which was leading to a sidekiq memory problem in self-hosted forems without honeycomb configured, as well as affecting long running local sidekiq servers in development). 
[The warning](https://github.com/honeycombio/libhoney-rb/blob/main/lib/libhoney/client.rb#L91-L99) is happening here when `transmission` defaults to nil, in the Libhoney::Client, which is the default when Honeycomb is creating a client. [NullClient](https://github.com/honeycombio/libhoney-rb/blob/main/lib/libhoney/null_client.rb) sets transmission to NullTransmission (the situation that's not warning …

Explicitly configure libhoney null client when no api key detected

---

app/services/podcasts/feed.rb
app/services/podcasts/get_media_url.rb
spec/services/podcasts/get_media_url_spec.rb

- Bug
I've noticed this error on a certain podcast and it's being retried countless time, wasting precious computation resources.
> SocketError: Failed to open TCP connection to [redacted]:443 (getaddrinfo: Name or service not known)
This adds that error to our ignore list.
https://app.honeybadger.io/fault/66984/605b63f08603e2ba1d9476db3b5a54c8
The specs should be enough
- yes
- n/a
n/a

Add SocketError to GetMediaUrl's exception rescue

---

app/workers/migrate_data_to_work_field_worker.rb
lib/data_update_scripts/20210630034523_add_work_profile_field.rb
lib/data_update_scripts/20210630041322_migrate_data_to_work_field.rb
spec/lib/data_update_scripts/add_work_profile_field_spec.rb
spec/lib/data_update_scripts/migrate_data_to_work_field_spec.rb

After talking to @benhalpern we decided that we will get rid of the separate work-related columns. Instead, there will be a single profile field for all work info. This PR adds that field as well as a data update script for migrating existing data, all other related work will be done in #14079.
Nothing specific to QA here, should be covered by tests.
n/a

Add 'Work' profile field

---

app/workers/github_repos/repo_sync_worker.rb

Touching the GithubRepo invokes GithubRepo#clear_caches, so calling `update` and then `touch` [calls `clear_caches` *twice*](https://github.com/forem/forem/blob/fb6e2e231153b2489f7a416efe7e74f9be64b63e/app/models/github_repo.rb#L13). This pulls it back to calling it once.
- #12853
Check to see that latency of `GithubRepos::RepoSyncWorker` goes down on DEV.

Only update GithubRepos once in RepoSyncWorker

---

lib/tasks/data_updates.rake

When a self hosted Forem updates its code it will then reboot. During this process the data update rake task is run to kick off any data update scripts. The problem with the current approach is that those scripts run on a delay. This delay was set to account for the time it takes Heroku to rolling restart dynos with new code. However, for self hosted and other Forems, this delay is unnecessary and really only stands to cause potential downtime. This change will allow us to set an ENV variable on Heroku and BenHalpern Community to ensure the DUS scripts are delayed while everyone else can get them run immediately. 
Grab the line of code from the rake task and put it in a console. Watch the logs as it runs a job immediately if no variable is set.
Set the variable to the number of seconds …

Delay DUS scripts via WORKERS_DATA_UPDATE_DELAY_SECONDS in rake otherwise default run them immediately

---

app/services/notifications/new_comment/send.rb

The user_ids scope got accidentally removed in the final [UserSettings PR](https://github.com/forem/forem/pull/14121). This puts it back. I will followup with a test for this.

Filter by user IDs when sending comment notifications

---

app/assets/javascripts/initializers/initializeArticleReactions.js
app/views/articles/_reaction_button.html.erb

- Added aria-pressed attribute to reaction buttons
#14182 
shared_

Added aria-pressed values to post reaction buttons

---

app/controllers/profile_preview_card_controller.rb
app/javascript/packs/commentDropdowns.js
app/views/profile_preview_card/show.html.erb

The preview card controller introduced in https://github.com/forem/forem/pull/14056 appeared to work locally but was always erroring in production. The impact of this may have been minimal on users, as the controller is currently only used to generate the preview card after a user adds a new comment to a discussion (and they are unlikely to want to view their own preview card).
The errors were due to reliance on query parameters which were stripped out by Fastly. In this PR I've removed the use of those query params, relying instead on the userId in the path, and the preview card ID being added client-side once the card has been generated (we did feel before that passing the preview card ID in a query param was a bit funky, and it feels cleaner this way). 
Relates to preview card work …

Fix bug in preview card controller

---

spec/services/notifications/new_comment/send_spec.rb

We had to push out a hotfix for sending users push notifications for comments https://github.com/forem/forem/pull/14186 This is the followup spec that will ensure it does not happen again. I confirmed the spec fails with the old code but passes with the new code :)

Add spec to ensure we filter by proper user IDs for mobile push notifications

---

spec/models/settings/smtp_spec.rb

When running tests locally (with an older version of the .env_sample file as .env, which did not have `SMTP_DOMAIN`) I was seeing nil, rather than the empty string, when running this spec. I determined the issue is that env vars provided (but blank) are represented as empty strings, while env vars not provided are returned as nil, and to avoid this dependence on the environment file (at test time) it's better to provide the data you're expecting (as we did for the other keys in the settings hash).
It looks like this passes in CI because a fresh .env file is [copied](https://github.com/forem/forem/blob/main/.travis.yml#L46) during the setup steps, so changing the .env_sample during the PR makes these changes immediate for automatic tests (only local testing would/was affected).
Test only …

Make smtp "domain" setting explicit

---

app/assets/javascripts/initializers/initializeArticleReactions.js

When the state of the post reaction button changes we change the button label e.g. from "Like" to "Unlike". This is OK, but a screen reader user won't know that the button name has changed unless they Tab away from it, and then Tab back to it.
This PR removes all setAttribute methods for aria-label and keeps aria-label static for all post reaction buttons.
#14182 
Will this PR introduce a change that impacts Forem members or creators, the
will share this change with the people who need to know about it.

Keep aria-label values static for post reaction buttons

---

app/workers/migrate_data_to_work_field_worker.rb
spec/lib/data_update_scripts/migrate_data_to_work_field_spec.rb

The original DUS for this (added in https://github.com/forem/forem/pull/14106) unfortunately contains a bug:
```ruby
profile = Profile.find_by(id: profile_id)
return unless profile
work_info = profile.employment_title
work_info << " at #{profile.employer_name}" if profile.employer_name.present?
profile.data[:work] = work_info
profile.save(validate: false)
```
While this sets the `work `attribute correctly, it ALSO updates `employment_title` because `work_info` is actually a reference to the same object, a fact we didn't catch during PR review. Here's a `rails console` session illustrating the problem:
```ruby
profile = Profile.last
work_info =  profile.employment_title
work_info.object_id == profile.employment_title.object_id
#=> true
```
So the shovel operator (`<<`) ends up modifying …

Fix data update script for work field migration

---

app/workers/feeds/import_articles_worker.rb
app/workers/push_notifications/cleanup_worker.rb

During the incident the other day I noticed that we were enqueueing multiple of these long running jobs unnecessarily. This change ensures that we are not enqueueing and/or executing multiple of these jobs at once. This will prevent duplicate work from being done at the same time. 
Ensure you can not enqueue multiple jobs for these two workers when they are already enqueued or while they are executing,

Enforce Uniqueness for Feed Import and Push Notification Cleanup Workers

---

app/views/users/_metadata.html.erb

Since the [proper fix](https://github.com/forem/forem/pull/14210) is taking a bit longer than anticipated, this PR introduces a quick fix for the duplicated display of work information:
https://github.com/forem/forem/issues/14188
1. Update a user to replicate the current state of our production DB, e.g. 
```ruby
user.profile.update(
work: "Dev at Forem",
employer_name: "Forem",
employer_url: "https://forem.com",
employment_title: "Dev"
)
```
2. Go to `localhost:3000/:username` you should only see the "old" work info with the employer name being a link:
None

Quickfix for duplicate work display

---

app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb
spec/workers/users/subscribe_to_mailchimp_newsletter_worker_spec.rb

The `Users::SubscribeToMailchimpNewsletterWorker` is failing anywhere from 20-70% of the time (depending on the time window). Turns out we have over 13k users without email addresses on DEV, and we have no guarantees either in the code or in DB constraints that the user record has the `email` attribute populated, so the assumption in this worker that "if the user exists, the email address exists" is misguided.
- https://app.honeybadger.io/projects/66984/faults/80341044
- [`Users::SubscribeToMailchimpNewsLetterWorker` on Datadog](https://app.datadoghq.com/apm/resource/sidekiq/sidekiq.job/4b7a336009623067?query=env%3Aproduction%20service%3Asidekiq%20operation_name%3Asidekiq.job%20resource_name%3A%22Users%3A%3ASubscribeToMailchimpNewsletterWorker%22&env=production&index=apm-search&spanID=9588 …

Don't try to subscribe users without emails

---

app/models/comment.rb
db/schema.rb
spec/models/comment_spec.rb

As discussed in  #14114, text formatting (bold, italics etc) does not render within custom link text in comments. This issue stems from the fact that `shorten_urls!` method in `app/models/comment.rb`, shortens not only URLs but also custom text inside anchor text. This PR fixes the method, so that it detects URLs in text and strips only those out. 
- Resolves #14114 
Text formatting gets rendered correctly -

Fix shorten_urls to not strip out text formatting in comments

---

spec/liquid_tags/link_tag_spec.rb

- Flaky spec
Just fixing some flaky spec
Resolves https://github.com/forem/forem/issues/14245
n/a
n/a

Escape organization name in LinkTag's spec

---

.gitignore
cypress/plugins/index.js
cypress/support/index.js
package.json
yarn.lock

Sometimes the error messages we get in CI for Cypress are a little opaque, especially when the screenshots aren't readily accessible. This dev dependency outputs the complete test steps and `cy.log()`s for failed tests.
I think this will be helpful in debugging exactly where Cypress tests fail.
N/A
You can test this out locally by
- changing `cypress:open` to `cypress:run` in `bin/e2e`
- changing a test to make it deliberately fail
When the test fails, you should see the steps it took prior to the failure output in your terminal. For example:
```
2) "before each" hook for "should show the discussion lock reason on an article"
clearCookies 
getCookies 
request 
get @user
request 
log Login failed. Attempting one more login.
wait 500
request 
saved as log in: …
```

add cypress-failed-log

---

app/models/users/setting.rb
app/services/profiles/update.rb
app/validators/profile_validator.rb
app/views/users/_profile.html.erb
lib/data/dev_profile_fields.csv
lib/data_update_scripts/20210712054300_remove_unused_profile_fields.rb
spec/lib/data_update_scripts/create_profile_fields_spec.rb
spec/models/profile_spec.rb
spec/models/users/setting_spec.rb
spec/services/profiles/update_spec.rb

This PR removes a lot of profile fields we no longer need:
1. Three of them (`display_email_to_profile`, `brand_color1`, `brand_color2`) moved to user settings
2. The link attributes we stopped displaying a while ago but we apparently never removed the actual fields.
All this is necessary so we can remove `settings_only` from the `display_area` enum on `ProfileField` which I will do in one of the following PRs related to profile work.
NOTE: this PR got a bit wider in scope than planned because removing the fields mentioned in (1) above removes their delegation which uncovered some things that weren't migrated during the user settings work. Tbh this is to be expected, these instances can be very hard and tricky to find so I'm ok with taking care of them.
Specs should …

Remove unused profile fields

---

app/models/user.rb
db/migrate/20210715205433_remove_settings_from_user.rb
db/migrate/20210715211923_add_partial_feed_url_index_for_user_settings.rb
db/schema.rb

This PR does 2 things
* It removes the User Setting and User Notification Settings from the user table in the database
* It adds back the partial index for feed_url on the User Settings table to help with the feed imports
https://github.com/forem/rfcs/pull/32
migrate and rollback without any issues

Remove Settings Columns from User

---

app/models/profile_field.rb
app/validators/profile_validator.rb
app/views/users/_profile.html.erb
spec/fixtures/files/profile_fields.csv
spec/services/profile_fields/import_from_csv_spec.rb

Not that we have `Users::Setting` we no longer need color inputs for profiles. After talking to @benhalpern we decided to remove them.
https://github.com/forem/forem/pull/14206
Nothing specific, color fields will get removed in the other PR.
n/a

Remove `color_field` input type from profiles

---

app/assets/stylesheets/profile-preview-card.scss
app/javascript/packs/articlePage.jsx
app/javascript/packs/commentDropdowns.js

When I implemented the initial profile preview cards, I didn't add any delay on the 'hover' effect. The result is that it's pretty easy to trigger the preview card on hover unintentionally:
https://user-images.githubusercontent.com/20773163/125464193-55ed1923-79a8-45bc-8350-29e7188b9564.mp4
In this PR I've added an animation to the CSS to effectively make the hover effect only take place after 500ms, which feels a lot more intuitive.
https://github.com/forem/rfcs/pull/222
- Visit an article with multiple comments
- Move your mouse around the comment area, over comment author names
- Check that when moving the mouse around quickly, the preview card isn't visible
- Check that if you intentionally hover over an author name, the preview card becomes visible as expected
- Open the preview …

Delay the hover appearance of preview card

---

app/models/users/setting.rb
spec/models/users/setting_spec.rb

When we recently moved the brand color validation from `profiles` to `users_settings` the fact that `nil` is a valid value got lost. The old validation in `ProfileValidator` looked like this:
```ruby
hex_value = record.public_send(attribute)
hex_value.nil? || hex_value.match?(HEX_COLOR_REGEXP) # This is where we consider nil valid
```
To restore the old behavior I added `allow_nil: true` to the new validation in `Users::Setting` and added the missing spec which would have helped in preventing this problem.
Closes #14299
In a Rails console, set either brand color to `nil` and verify the the settings record is still valid. Example:
```ruby
user.setting.brand_color1 = nil
user.setting.valid?
#=> true
```
None

[15-minute fix] Fix brand color validation

---

app/views/articles/_block.html.erb
app/views/articles/_fitvids.html.erb
app/views/articles/_v2_form.html.erb
app/views/articles/show.html.erb
app/views/comments/index.html.erb
app/views/layouts/_top_bar.html.erb

This PR removes attribute `async` on small inline js where, IMHO, it's not worth creating a new js file, or where there are dynamic rails parameters passed to the js.
This PR closes https://github.com/forem/forem/issues/13389
As requested during the review of https://github.com/forem/forem/pull/14234, there's no replacement of  `var` with `const` or `let`, the code remains as it is.

remove use of async attribute on inline scripts

---

app/models/profile.rb
app/views/users/_profile.html.erb
lib/data_update_scripts/20210722135549_profile_website_url_format.rb
spec/lib/data_update_scripts/profile_website_url_format_spec.rb
spec/models/profile_spec.rb

When accepting user supplied website urls for the profile, ensure the input is in fact a url (and not just a string like a domain or hostname). This is needed to prevent generating local path links on the user profile (for example, https://dev.to/www.example.com is almost certainly not what the user intended to show).
The reporter did additionally point out that the full "https://my.web.site" format might not have been what they wanted to show on their profile. I didn't attempt to change the generated link to separate the href from the text (currently they're both the same) - we might consider making a "friendly" display for the link text, that feels like it's out of scope for the reported issue but might have been a reason to omit the https:// scheme from the url when prompted. …

Validate profile field "website url" is in fact a url (don't generate local path links).

---

lib/data_update_scripts/20210722135549_profile_website_url_format.rb
lib/data_update_scripts/20210722160452_profile_website_url_format_fixup.rb
spec/lib/data_update_scripts/profile_website_url_format_fixup_spec.rb
spec/lib/data_update_scripts/profile_website_url_format_spec.rb

Update the profile website url fixup script to handle parse errors - we saw a user with a trailing space in the input which raised an error during parsing, rather than giving a generic uri with no scheme, which caused the script to abort.
Attempt to strip spaces from input before building the new url, and handle URI parse errors by clearing the url.
Additionally, if the user had given an email address, check to see if the http user is in the url, and reject those cases.
Rename script class and file. Copy tests and load the new class to test it.
https://app.honeybadger.io/projects/66984/faults/80557297
#14302 
Tests should be sufficient.
None
development process, or any of our internal …

[hotfix] website_url update script should handle parse errors

---

bin/e2e
docs/tests/e2e-tests.md
package.json

Adds support for running end to end (E2E) tests that do not require seeded data. If a developer wants to run E2E tests that do not use seeded data, they add the `--no-seed` argument, e.g. `bin/e2e --no-seed`.  There are also a npm script to handle this, `yarn e2e:noseed`.
#14285
1. Open a terminal in the root folder of the Forem repository and run `yarn e2e:noseed`.
2. Once the checks are verified, it will output `"Running E2E tests without seed data"` before starting Cypress.
```bash
...
[84] ./app/javascript/packs/dashboardTagsDisableUnchangedButtons.js 754 bytes {26} [built]
+ 112 hidden modules
Running E2E tests without seed data
cypress-rails configuration:
============================
CYPRESS_RAILS_DIR....................."/Users/nickytonline/dev/forem" …
```

[15 min fix] Added support for the --no-seed argument to bin/e2e command 

---

app/views/layouts/admin.html.erb

This is not the final solution to be implemented for small screen navigation, but instead is a quick fix so the navigation options are available in the mean time the definitive solution is implemented.
- #13826
- https://github.com/forem/rfcs/pull/264
2. Browse the admin area with a mobile device (or alternatively with the dev tools mobile screen option enabled)
**In bigger screens (things remain the same):**
**In small screens the navigation must appear visible:** 
None - No changes have been made to the page

[15-min fix] Show the navigation options regardless of screen size

---

app/models/tag.rb
spec/models/tag_spec.rb

This reverts commit 71591994029d1cb861b1c82906acd0ba92c4f112.
See https://github.com/forem/forem/issues/12486#issuecomment-886496687

Revert "Clear recent articles cache on updating tags (#14298)"

---

app/controllers/admin/welcome_controller.rb
spec/requests/admin/welcome_spec.rb

When trying to create welcome threads Forem admins currently experience an exception. This PR adds the fix for that. 
https://github.com/forem/forem/issues/14315
* Go to http://localhost:3000/admin/apps/welcome
* Click the "Create A New Welcome Thread" button
* You should see the editor with some text preloaded, not an exception about `Admin::Settings::Community`
None

Fix constant lookup in Admin::WelcomeController

---

app/controllers/admin/welcome_controller.rb
app/models/user.rb
app/services/notifications/moderation/send.rb
db/seeds.rb
spec/models/user_spec.rb
spec/requests/moderations_spec.rb
spec/requests/notifications_spec.rb
spec/services/notifications/moderation/send_spec.rb
spec/system/notifications/notifications_page_spec.rb

While working on https://github.com/forem/forem/pull/14320 I noticed the `User.dev_account` method. Since this looks for a user with via the `staff_user_id` I decided to rename this method to `User.staff_account` which seems like a better name and less DEV specific.
Generalization
Nothing specific, specs should still pass this was search/replace type of PR.
None

[15-minute fix] Rename User.dev_account to User.staff_account

---

app/views/articles/show.html.erb
cypress/fixtures/users/liquidTagsUser.json
cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
spec/support/seeds/seeds_e2e.rb

After merging https://github.com/forem/forem/pull/14246 I realised follow buttons inside liquid tags hadn't been accounted for - they actually are working OK because we expect other follow buttons on the article page, but this PR now adds tests for this.
(NB: there is a "follow button" for the podcast liquid tag, but it is actually a link to the podcast rather than a 'follow button' like these others. This is why it doesn't appear in the e2e test cases, as it wasn't impacted)
Follow up from #14246
- Create an article with a user liquid tag (e.g. `{% user admin_mcadmin%}`) and a tag liquid tag (e.g. `{% tag beginners %}`)
- Save as draft, or publish
- View the article and try interacting with the follow buttons
- Check that `Follow` updates to `Following` and vice versa
- Check that …

Tests: Initialize follow buttons in article liquid tags

---

spec/system/dashboards/user_visits_dashboard_spec.rb

https://github.com/forem/forem/pull/14308 changed the path to the header in the tests (was `main > header` before to distinguish it from `body > header`, as there are two "header" elements on the page). 
However, while it worked in the branch, it failed after merging to main. 
Use `div > header` (shudder), avoiding the nth-child pseudoclass selector, to find
the "header" in the dashboard body containing the summary statistics. The second commit adds the class of the div that this header is the child of, not sure if that makes this more fragile by coupling the div's class to the test, but it looks like it's unlikely to be removed. 
This avoids the conflict with the top header (with community logo, search bar, and dropdowns) from the dashboard summary statistics header (post views, credits …

hotfix dashboard spec failures

---

.travis.yml

Default Travis build uses Ubuntu 16. This changes it to 20.04 so we get all the benefits of using the newer OS. Along with that, update the PSQL version.
Shoutout to @djuber for helping me out.
References
- https://alphahydrae.com/2021/02/how-to-run-postgresql-13-on-travis-ci/
- https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version
n/a

Change Travis to use Focal Fossa and Postgresql 12

---

app/models/comment.rb
spec/models/comment_spec.rb

A comment with the `{% link url-to-an-article %}` tag causes an argument error and a user facing popup to be shown.
If there were no links to shorten in the content, don't try to replace anything.
Follow up to https://github.com/forem/forem/pull/14262
Fixes https://github.com/forem/forem/issues/14372 (reported issue was that two of our moderator response templates including the initial welcome help include these link tags and a moderator was unable to submit a comment).
Comment unit test covers the failure adequately. Otherwise
- Visit an article
- Create a comment
- Add a link to the article you're visiting (or any other, but you have the page url you're on right there) - format is 
```
{% link http://localhost:3000/bechtelar_buffy/the-golden-apples-of-the-sun-sed-eos-1923 %}
```
- Click …

hotfix comments with link tags

---

spec/policies/pinned_article_policy_spec.rb

I noticed a warning from rspec when this policy spec ran:
Using expect { }.not_to permit_actions could produce
confusing results. Please use `.to forbid_actions` instead. To
clarify, `.not_to permit_actions` will look at all of the actions and
checks if ANY actions fail, not if all actions fail. Therefore, you
could result in something like this:
it { is_expected.to permit_actions([:new, :create, :edit]) }
it { is_expected.not_to permit_actions([:edit, :destroy]) }
In this case, edit would be true and destroy would be false, but both
tests would pass.
I just follow the helpful advice.
Tests pass should be sufficient.
None
will share …

expect to forbid, rather than expect not to permit, action for policy

---

spec/requests/profile_preview_cards_spec.rb

Update the test cases to assert the profile preview is showing the
user's `created_at` timestamp, not the profile's.
This matches what happens for the [html preview](https://github.com/forem/forem/blob/main/app/views/shared/_profile_card_content.html.erb#L55-L62) where "Joined" is the user's
created_at timestamp, and what the [json builder](https://github.com/forem/forem/blob/main/app/views/profile_preview_cards/show.json.jbuilder#L14) does:
json.created_at utc_iso_timestamp(@user.created_at)
Since these are almost always the same thing, we didn't notice
this. However, if a user is created just before the second boundary,
and their profile created immediately after the second boundary (so
that the iso8601 values have distinct seconds) this could fail when
looking at the wrong objects …

ProfilePreviewCard serializes the user's created at, not the profile's

---

app/views/comments/index.html.erb
cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
spec/support/seeds/seeds_e2e.rb

When I merged the work to refactor follow buttons (https://github.com/forem/forem/pull/14246), I missed a page that needed the new `followButtons` pack. This PR adds the pack to the comments index page, and adds an E2E test to make sure that functionality doesn't regress.
Fixes #14415
- Visit an article with comments, and add `/comments` onto the end of the URL to view the comments index page
- Hover or click on a comment author name and click the "Follow" button
- Check the UI updates to "Following"
- Refresh the page, and check the same author's preview card, making sure that the "Following" state is still reflected
- Click the button again to unfollow, and repeat the previous steps to make sure the UI changes back to "Follow" and persists on reload
- Add a new comment to the discussion …

[15 min fix] Initialize follow buttons on comment index page

---

scripts/build_containers.sh

The container build script [is failing](https://buildkite.com/forem/build-containers/builds/6845#5a2cbc5d-f610-4bba-9238-2bb2ff51e437/128-5448) because apparently we can't run `-v` and `-z` inside the same `[ ... ]` expression. Somehow we missed this before merging the versioning branch.
- Buildkite builds pass on [this branch](https://buildkite.com/forem/build-containers/builds?branch=fix-container-build-script) …

Separate -v and -z into two separate commands

---

app/views/layouts/_main_nav.html.erb

When a Forem has a small number of social links active, the placement in the navigation sidebar was a little bit off, with the icons being placed centrally. For example in forem.dev:
I've made a small tweak to the classnames so that the icons display left-aligned.
N/A
Experiment with different numbers of social profiles set in Admin > Customization > Config > Social (enable a social icon appearing in the sidebar nav by adding a username for a given field).
The icons should always be shown left-aligned, and evenly spaced. 
Example with only two social profiles enabled:
Example with all social profiles enabled:
NB: There is a top border that is only shown in some colour themes (not the default theme as pictured above). I've double-checked that the changes to padding haven't affected its …

[15 min fix] Left align social icons in nav

---

.travis.yml

From the discussion at https://github.com/forem/forem/pull/14433#issuecomment-894947918 - raise the ruby vm stack depth from default 1MB to 5MB. This was tested against the worse-than-worst case scenario of a single CI node running each spec file individually in Knapsack Queue mode - while it did fail eventually with stack level errors, it made it through all but the last few system tests successfully (roughly 2-2.5x as many rspec runs as we see in failing cases currently).
This should alleviate any SystemStackErrors seen in travis for a substantial period of time.
#14433 was an alternate suggestion to prevent the stack from growing (with only partially considered impact on correctness).
While it _is_ possible to test this, the setup is non-obvious. My local work-around to demonstrate the …

increase ruby stack depth in travis

---

app/controllers/api/v0/listings_controller.rb
app/controllers/api/v0/organizations_controller.rb
app/views/api/v0/shared/_listing.json.jbuilder
spec/requests/api/v0/listings_spec.rb

Our API docs specify that listings responses will include a `created_at` attribute but that was not the case.
Closes #14436
Tests should be sufficient. For manual testing make an API request to the listings endpoint and ensure that the `created_at` attribute is present.
None.

[15-minute fix] Add `created_at` to listings API response

---

app/models/reaction.rb
spec/models/reaction_spec.rb

This method previously assumed that a reaction's `reactable` had a `user_id` attribute, but if the reactable was a User, it wouldn't have a `user_id`. The user id would just be `reactable.id`.
- https://app.honeybadger.io/projects/66984/faults/80839653#notice-params
~~We aren't even sure how this is happening. According to @djuber it's not happening for him locally.~~
Turns out it's because both creating a reaction and deleting it go through [the same endpoint](https://github.com/forem/forem/blob/a24dee8e46a1b15911f879fb499882706fa54e41/app/controllers/reactions_controller.rb#L75-L77), so adding a reaction to a user and then taking that reaction back should reproduce the problem on `main`, but not on this branch. …

Handle users in Reaction#skip_notifications_for

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/assets/javascripts/initializers/runtime.js

In #5034 @JoshCheek pointed out that `readline` keybindings (supported in all web and native text inputs on macOS) are broken in the Forem editor on macOS because we treat Ctrl and Cmd keyboard modifiers as equivalent. This sort of native functionality of the browser [should be respected](http://jgaskins.org/blog/2016/07/30/don-t-change-perceived-browser-functionality).
Josh's suggested solution was to check the return value of `navigator.platform`, which sounded like a much better idea than user-agent sniffing, but unfortunately [it's been deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform), so this PR implements it in terms of user-agent sniffing.
- https://github.com/forem/forem/issues/5034
To see current behavior:
- Head to the DEV homepage on a Mac
- …

Fix readline key bindings for comments on macOS

---

app/services/articles/feeds/large_forem_experimental.rb
spec/requests/stories/tagged_articles_spec.rb

The `Articles::Feeds::LargeForemExperimental` service queries articles under a given tag by traversing the relations via `tags`->`taggings`->`articles` using nested subqueries and `INNER JOIN`s. This may be slower than we'd like, so we're trying the [`Article.cached_tagged_with_any` scope](https://github.com/forem/forem/blob/a24dee8e46a1b15911f879fb499882706fa54e41/app/models/article.rb#L215-L228) to see if we can streamline that query since Postgres is often much faster at filtering a single relation than joining multiple relations and filtering them.
Unfortunately, neither of these are public 😕 
- [Slack conversation](https://forem-team.slack.com/archives/CPGJMAX5F/p1628539914025700?thread_ts=1628539235.023500&cid=CPGJMAX5F) 
- [Datadog trace for the `Stories::TaggedArticles#index` …

Optimize tagged articles under feature flag

---

app/views/profile_preview_cards/show.json.jbuilder
spec/factories/profiles.rb
spec/requests/profile_preview_cards_spec.rb

Currently, the JSON generated for the profile preview cards still relies on hard-coded `work` and `education` profile fields. This PR changes this to be dynamic, as described in [this comment](https://github.com/forem/forem/pull/14210#discussion_r674494314).
Existing tests should be green.
For manual tests:
* Make sure a user has `work` and `education` information in their profiles
* Start a local rails server
* Make a `GET` request to http://localhost:3000/profile_preview_cards/<user_id>.json. The returned JSON document should include the work and education keys and corresponding values.
n/a

Make header fields in profile preview card dynamic

---

app/assets/stylesheets/views/mod-center.scss
app/javascript/modCenter/__tests__/moderationArticles.test.jsx
app/javascript/modCenter/moderationArticles.jsx
app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
app/javascript/modCenter/singleArticle/index.jsx

This pull requests tries to make the articles' list more accessible by introducing a separate section for article links and remove their usage from being inside a `button` element.
Fixes #14100 
This improves upon the accessibility of the articles' list so that the article link anchor tag is accessibile to the screen readers as well.

Add separate section for article link to improve accessibility in the mod center

---

app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/views/articles/show.html.erb
app/views/comments/_comment_date.erb
app/views/comments/_comment_header.html.erb

This PR tweaks the padding on preview card trigger buttons that are already in the codebase (comments, author byline). Previously they didn't have any horizontal padding which looked a bit off. For example:
This PR makes adjustments to the padding of both the button and the surrounding elements where they are placed so that when unhovered it visually looks the same as before, and when hovered, there's a more conventional all-round padding on the element.
https://github.com/forem/rfcs/pull/222
We need to check that the layouts look correct in both mobile (where not preview trigger button exists) and on desktop.
- Visit an article page, and hover over the author byline name. Check the button padding highlight looks OK. Check that when you're not hovering over it, the layout still looks as …

Add horizontal padding on preview card trigger button

---

app/sanitizers/rendered_markdown_scrubber.rb
spec/services/markdown_processor/parser_spec.rb

I don't recall why we are allowing button tag on markdown. I would think this is just an oversight.
n/a
n/a

Remove button from allowed tags

---

app/assets/stylesheets/components/dropdowns.scss
app/javascript/packs/articlePage.jsx
app/javascript/packs/commentDropdowns.js
app/javascript/utilities/dropdownUtils.js
app/views/shared/_profile_preview_card.html.erb

It was suggested that preview cards would be more user-friendly if they "dropped up" when they would otherwise be positioned partly out of the viewport at the bottom of the page (most prevalent with comment threads). 
This PR adds a new helper to `dropdownUtils` which can be used as a scroll listener anywhere we have dropdowns we want to switch position (detected by a data attribute on the dropdown content). Currently, this is only used for preview cards, but it should be generic enough we could pop the data attribute on other crayons dropdowns and get the same effects.
The listener's callback is debounced because scroll events fire _a lot_ at the same time and we don't need to fire the callback every time. 
https://github.com/forem/rfcs/pull/222
This change affects comment and article …

Change preview card position depending on viewport

---

app/javascript/utilities/dropdownUtils.js
app/views/comments/_comment_header.html.erb
cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js

The test flake we saw in https://github.com/forem/forem/pull/14477 was due to a genuine bug in [the PR I merged yesterday](https://github.com/forem/forem/pull/14473) to reposition dropdowns when partially obscured by the viewport. The code didn't properly account for dropdowns which are already opened and require repositioning. I've added a guard now to make sure we don't close them unintentionally 🙂 
I've also thrown in a very minor tweak to the UI for an author's own comment on a post, because while running the test I noticed this was a little off.
Closes https://github.com/forem/forem/issues/14478
- Visit an article with comments, and open a preview card by clicking on an author name
- Scroll up and down to trigger the preview card reposition and make sure the dropdown doesn't …

Make sure open preview cards don't collapse on scroll

---

app/services/users/delete_articles.rb
spec/services/users/delete_articles_spec.rb

This removes any existing discussion lock on an article before trying to delete the article. 
https://app.honeybadger.io/fault/66984/f36076a8740179b74a5a4b5474521d2d
1. Make a discussion lock for some user's article
2. Banish the author
3. See that it banishes successfully
Nope
No

Remove discussion lock prior to deleting an article

---

app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx

- #13601  Fixed the anchor tags with hash routes to prevent navigating to different page.
- Since the stories are inside iFrame, I couldn't keep it in the same story navigatable view, instead it will open the story on fullscreen and the corresponding selected tab is highlighed.
- Took reference from implemented Tab component for className toggles - Tabs.tsx
- Used state to highlight the current tab.
- Used location.hash to set the initial state.
Closes #13601 
The fix is shown in the GIF below
There are no UI changes. …

Fixes #13601 - Storybook redirects off page

---

app/assets/stylesheets/profile-preview-card.scss

@citizen428 noticed that sometimes the hover delay for the preview card didn't seem to be working as expected, with the result being that users were occasionally blocked from completing the action they wanted to (e.g. clicking a link above or below the preview trigger).
A little bit of investigation and the problem was:
- Hover on the preview trigger immediately started the 'delay appear' animation
- Hover on the (invisible) dropdown card continued the animation
The upshot is that hovering on the _invisible_ preview card was causing the preview card to appear 🙈  e.g.:
https://user-images.githubusercontent.com/20773163/129328030-2ed727ab-1404-437b-8a9a-1f2580ca2592.mp4
In this PR I've added `pointer-events: none` to the dropdown content while it's invisibly animating in. This means that …

Streamline hover delay for preview card

---

app/views/users/_profile.html.erb

Removes duplicated "display email on profile" checkbox shown in the users profile below the Website URL input.
Closes #14497
Navigate to a user's profile and verify there's no "display email on profile" checkbox shown below the Website URL input.
Example:
N/A
shared_

fix(user-profile): remove duplicate 'display email on profile' checkbox

---

config/initializers/carrierwave.rb
config/initializers/slack_notifier.rb

Two of the initializers had an ignored rubocop rule about top level method definitions. It's unclear we needed to do this (I don't see us wanting to have defined global methods), and this change moves them to modules to reduce namespace pollution.
The methods were being added to the main object and available as private methods on every object in the app. This didn't make much sense.
I believe the capybara [`wait_for_javascript`](https://github.com/forem/forem/blob/main/spec/support/initializers/capybara.rb#L30-L32) global method is in fact expected to be available everywhere in test, and it's defined in spec/support/initializers so not part of the app in prod or development, and only called from system tests, so I haven't changed anything there. 
I did check that (1) the app boots, I can …

Encapsulate initializer methods in modules

---

config/environments/development.rb
config/environments/test.rb

Bullet 6.1.5 added deprecation of `.add_whitelist`:
```
DEPRECATION WARNING: add_safelist is deprecated in favor of add_safelist. It will be removed from the next major release. (called from block (2 levels) in <main> at /Users/rhymes/Development/forem/config/environments/development.rb:126)
```
This PR uses the new `.add_safelist` method
https://github.com/forem/forem/pull/14514

Bullet: rename deprecated add_whitelist to add_safelist

---

svgo.config.js

svgo 2.4 changed its syntax on how to customize plugins, see [readme](https://github.com/svg/svgo#configuration) and [release notes](https://github.com/svg/svgo/releases/tag/v2.4.0).
This PR updates it to the new syntax
https://github.com/forem/forem/pull/14511
1. open a svg file and change anything
2. commit or run `yarn run svgo --pretty FILENAME`
2. make sure the `viewBox` attribute it still there

svgo: update configuration for 2.4 syntax

---

app/views/moderations/_reactions.html.erb
app/views/moderations/actions_panel.html.erb

Migrating to the twemoji icons, a few images were selected incorrectly. This fixes that.
- when moderating a post, the downvote button should use the
thumb-down image
- when showing the nausea reaction, use the suspicous face emoji
https://github.com/forem/forem/pull/14517 - I actually viewed and attached a screenshot showing the wrong behavior on the actions panel. Sorry! 
When moderating an article, the downvote should show a thumb down, not a thumb up, icon. 
1. Visit /mod (as a moderator)
2. select an article and look in the moderator actions
None
[Admin …

Adjust images used for moderation

---

app/views/layouts/application.html.erb

Currently you can't close the hero banner for CodeLand and have it stay closed. This happens because we perform, the following check in `app/views/layouts/application.html.erb`:
```erb
if (localStorage.getItem('exited_hero') === '<%= @hero_area.name.html_safe %>') {
```
Unfortunately the `&` gets escaped, so we end up with the following comparison:
```js
if (localStorage.getItem('exited_hero') === 'CodeLand Registration &amp; Speaker Announcement') {
```
Since `localStorage` is set from `app/assets/javascripts/initializers/initializeHeroBannerClose.js` no escaping happens and the strings don't match.
n/a
n/a
None

Mark hero banner html_safe

---

app/views/moderations/actions_panel.html.erb

- a closing quote on the `aria-haspopup="true ` caused some issues when
running erblint (lots of keywords were assumed to be strings, and vice versa)
- a warning about Lint/FloatComparison raised about casting the
rating_level value to_f, I chose to convert the float to integer and
compare to the value instead.
I suspect the lint rule (from git hooks) didn't run in the most recent changes to this file.
https://github.com/ludwiczakpawel/dev.to/commit/38214380ddb3445a2cca0ce04d222a8138dac2ce the missing closing quote was introduced a few months ago.
The float cast (which may be a new lint rule triggering?) was added in https://github.com/forem/forem/pull/7777 so has been there for over a year (and seems like it wasn't as unreliable for comparisons as the lint rule suggested).
_Please …

Fix erblint failures

---

app/services/articles/detect_animated_images.rb

We've been witnessing some time out errors for images not responding to the default 2 seconds of open timeout and 2 seconds of read time that FastImage [sets](https://github.com/sdsykes/fastimage/blob/a1131d15bb2caea0f243a088c8239192de93d6e3/lib/fastimage.rb#L204-L205). I raised that to 10, mostly because we're using it asynchronously and it doesn't matter much if it takes a bit longer. 
Some context: we've been testing the `Articles::DetectAnimatedImages` behind a feature flag and its worker. It will be used as the basis of the RFC that disables autoplay for animated images
We can only QA this on DEV in production

Articles::DetectAnimatedImages: raise default timeout for FastImage

---

app/views/users/show.html.erb

The profile fields work changed the displayed user email to the setting (boolean) of whether to share the email.
Undo that change, show the user's email when they've selected to do that.  
fixes #14541 
Visit /admin_mcadmin or another user's profile. 
Edit profile and select "Display email on profile"
Save profile, click on the `@admin_mcadmin` link back to the user show page
Verify "admin@forem.local" or the appropriate email, not "true", is shown.
None. …

[15min fix] Show the user's email on their profile when they chose to share

---

app/assets/stylesheets/base/typography.scss

This PR adds a veeeery basic styling for `<dl>` tags. It almost mimics default browser styling (which we originally scraped out with our reset.css).
- [Internal Slack Thread](https://forem-team.slack.com/archives/CAA200SH5/p1629323460056600).
You can use following HTML:
```
<dl>
<dt>Beast of Bodmin</dt>
<dd>A large feline in asf df asdf safas dfmasdf ,sdf dasm,f sadm,f asfm,sda fm,ds fm,ads fsam,f sdm,f dasm,f dasmhabiting Bodmin Moor.</dd>
<dt>Morgawr</dt>
<dd>A sea serpent.</dd>
<dt>Owlman</dt>
<dd>A giant owl-like creature.</dd>
</dl>
```

Styling of Definition List

---

scripts/build_containers.sh

Only print environment variables if they have been defined.
This was causing errors running the build_containers.sh script
locally, since only buildkite was passing these (and errors stop the
script, so nothing was built).
Follows the work in #13750 where the print statements were introduced.
Run scripts/build_containers.sh, no  error should occur, script should echo "Not running in Buildkite." and start building production images locally. 
None …

Only print BUILDKITE environment variables when they were present

---

app/models/email_message.rb
app/views/admin/email_messages/show.html.erb
app/views/admin/feedback_messages/_feedback_message.html.erb

When looking for the closing `</body>` tag for rendering email messages within the app, it sometimes fails, specifically for the Devise-generated confirmation email. This should fix that, since it grabs the entire `<html>` of the email.
https://app.honeybadger.io/fault/66984/0032f7edebb6170a8eb849a0abb390a1
1. Go into `rails console`
2. `EmailMessage.last.html_content` should render something
Nope
No

Look for <html> tags instead of <body> for email viewing

---

app/javascript/onboarding/components/ProfileForm.jsx
app/views/users/_profile.html.erb

After the recent profile field changes the onboarding page looked a bit empty.
This wasn't really a regression, more of an oversight in terms of thinking through all areas of the product that will be influenced by the recent changes. In a Slack conversation with @benhalpern we decided to add the bio (the `summary` profile attribute) to this modal since it's an actual column of the `profiles` table and therefore will be present on all Forem instances.
Updated modal:
Since I found it weird that we use a `textarea` in the modal but an `input` in the profile page I changed the latter to be a text area too:
None

Add bio to onboarding

---

app/javascript/article-form/actions.js
app/javascript/article-form/articleForm.jsx
cypress/integration/seededFlows/publishingFlows/publishOrSavePost.spec.js

This code was working, but as noted in #12349 it was a bit _funky_ and difficult to understand why it was doing certain things.
I've refactored this area so that:
- We don't touch the 'published' state until the outcome of the network request is known 
- If the network request fails, no change needs to be made to the 'published' state (since we didn't optimistically update it in the first place)
- I removed a 'failure callback' that was never passed in to the `submitArticle` function. Instead, I've replaced it with the general error callback which can be used for the same purpose.
I've added Cypress tests to cover the scenarios of draft/publish for new/existing posts with a variety of success/error situations.
Closes #12349
For the most part this should be captured by the new Cypress …

Revise editor publish logic

---

app/assets/stylesheets/components/header.scss

On mobile devices (particularly iOS - I wasn't able to reproduce on my android Pixel), the skip to content link was intermittently flashing up as visible inside the header bar when a page was loading. For example:
https://user-images.githubusercontent.com/20773163/130227916-32a5011e-c4d2-4bd0-89a8-09515c99b27e.mp4
This PR sets the opacity of the link to 0 when it's not intended to be visible, instead of only relying on it being tucked under the header bar.
NB: Using opacity 0 instead of `hidden` means that assistive tech users will still find the "Skip to content" link in the list of interactive controls, even if it's not visually presented on the screen
Fixes #14492
On a mobile device (ideally iOS, and ideally we also test this from within the mobile app too):
- Navigate to and from the …

[15 min fix] Stop skip content link flashing on mobile

---

app/assets/stylesheets/views/profile.scss
app/views/users/show.html.erb

On small screens (portrait mobile), the dropdown position on a user's profile page led to the dropdown content being partially off-screen - e.g.:
The simplest fix for this is to reliably place the dropdown to the right of screen, so it will always be visible when it opens. The right-side of a group is also a fairly standard place to have an overflow menu, so I just went ahead and swapped this round. 
Fixes #13968
- Check a user's profile in desktop and mobile viewports, making sure you can see the full content of the dropdown menu
- Test it out with a user you follow, a user that also follows you back, and in the logged out state, so you can see the full combination of buttons that appear on this page
Desktop:
Mobile:
N/A - no change to functionality
_Will this PR introduce a change that …

[15 min fix] Swap position of profile dropdown for users

---

app/services/users/suggest_recent.rb

Once upon a time, there was a refactoring. During this refactoring our noble hero (yours truly) changed some code to use newer `ActiveRecord` syntax. However, in one such case `> 0` got refactored to `1` instead of `1..`.  On a more recent adventure, our hero noticed his previous mistake and after hanging his head in shame slew this dragon of his own making. And everyone lived happily until the next bug got introduced.
Nothing specific.
None.

[15-minute fix] Fix `Users::SuggestRecent#established_user_comment_count`

---

app/assets/stylesheets/components/syntax.scss

Different padding was being applied to code blocks depending on their location in a document - e.g. as a list item, vs in the main document. See the screenshots on #14563 for the "before" version 🙂 
This PR moves the padding CSS to the 'catch-all' for codeblocks so that the same applies to all.
One thing I noticed while working on this issue is that in all cases other than the "code block on its own" example, the "full screen mode" icon in the top-right corner is not rendered. This seems to be a separate bug  and is already logged here - #11059
Fixes #14563
Create a new post locally using the different types of code block locations targeted by this CSS. I used:
````md
```
code
```
1. Something
```
code
```
2. Something else
<pre>
something
</pre>
> ```
>code
>```
````
Check the padding …

Unify padding of code blocks

---

.gitpod.yml

Foreman was not installed in gitpod, so bin/startup would fail fast and the system would be stuck at "waiting for port 3000" indefinitely.
Additionally, the APP_DOMAIN can be fetched from the `gp` utility to
get the url for port 3000, so I've added that to the .env file after copying it. 
Since the .env file is read top down - it's easier to implement
appending the corrected value than to replace it at the beginning, but
I'm completely open to redoing this via a sed command or similar, to
change the variable at the top (this would be less confusing for
anyone else dealing with the file I guess - I'm not sure how much anyone will be hand-editing the .env, and if they do change the app domain in gitpod at the top it's unlikely to break anything accidentally. I'm on the fence here).
Notes on …

Install foreman for procfile and setup appdomain in gitpod

---

app/assets/stylesheets/dashboard.scss

The "Pin to profile" button was out of font-styling evenness. This was happening because it was a `<form>` button unlike others which were custom styled anchor links. Therefore, this form button styling overwrote the custom style and made it look different.
Made sure the form button inherits the same font styling as other buttons residing inside that div.
This is a fix related to issue https://github.com/forem/forem/issues/14503
* To verify this fix, need to make sure all the action buttons of a post follow same font-styling.
* Testing location - `Manage` section of any post.
* Here are the screenshots of before/after fix.
* Before fix 
* After fix
* The responsiveness of the app remains intact after the fix. …

Fixed "Pin to profile" button styling

---

app/assets/stylesheets/preact/onboarding-modal.scss

It was noticed on android mobile (not sure if this was affecting iOS also) that when you tapped into an input field during onboarding, the soft keyboard was blocking the input content. Scrolling inputs into view when the keyboard appears is default mobile behaviour, but it seems our fixed height in the CSS was breaking this.
I've made a small change that keeps modal heights consistent on desktop, but allows the mobile browser to "do its thing" and make sure the input stays in view.
Fixes https://github.com/forem/forem/issues/13811
- Onboard as a new user, visiting `/onboarding`
- On a desktop/non-mobile device, check that the modal sizing all looks as before
- On a mobile device, check that when you enter your bio, the keyboard doesn't obscure the input …

Make sure input can scroll into view on mobile

---

app/views/admin/pages/_form.html.erb
spec/requests/admin/pages_spec.rb

When creating a new page as an admin who doesn't also have the role "tech admin" one would see the following:
However, feature flag management is only available to tech admins, so this whole section is now hidden for regular admins.
Note: the issue mentioned two possible solutions, I went for the first but am happy to go with the other one ("how the message, but disable the link and provide a message explaining the `tech_admin `role is required") if people prefer that.
Closes #9737
1. Go to `/admin/customization/pages` as a user who has both "admin" and "tech admin" roles. You should see the message from the screenshot above.
2. Go to `/admin/customization/pages` as a user who has only the "admin" role, you should not see this message.
None

Only tech admins can manage page feature flags

---

app/javascript/runtimeBanner/RuntimeBanner.jsx

Some situations (non-Safari browser + embedded WebView in 3rd party apps) leave a blank page behind after a Deep Link. This PR fixes that.
https://github.com/forem/forem-ios/issues/88
https://github.com/forem/forem-ios/pull/90
If possible and you have an iOS device running the current Testflight release version `1.0.4 (67)` (or greater) you can
1. Open [this Tweet's link](https://twitter.com/noope91/status/1430178695973687311)
- Use the Twitter mobile app or any browser that's **not Safari**
- This self hosted Forem is currently running this PR
2. Open the Runtime banner and deep link into the app
3. Go back to Twitter and a blank page shouldn't be there
If you try this same process ^ but using a Tweet from DEV ([like this one](https://twitter.com/ThePracticalDev/status/1430233699610677251 …

Avoid blank screen in Deep Links Edge cases

---

bin/setup

Check for most recent version of foreman present in the gemset before attempting to install foreman.
When you call `gem install foreman` (or had run bin/setup recently) you get a newer version of foreman than 0.87.1 - which we check for. This results in "installing" the gem every time bin/setup is called - even though foreman was already present. The intent is to install if not present, and additionally it looks like to install if not current. 
This PR moves the definition of "current" to 0.87.2
https://github.com/forem/forem/pull/6007 why do we install it here (and not in the gemfile)
https://github.com/forem/forem/pull/8391 only install when not present  (and a comment in the description that the version check might not make sense)
Really - this is an "avoid needless work" change - the …

Check for the current version of foreman when deciding to install

---

db/seeds.rb

[Faker::Markdown.random](https://github.com/faker-ruby/faker/blob/master/lib/faker/default/markdown.rb#L119-L137) accepts an excluded method list, use this to exclude `:sandwich`.
Since `random` can also be selected by `random` (it is one of the `available_methods` sampled), and it's then called without the exclude list,  we exclude it as well (so that it won't call sandwich after calling random without an exclude list).
This avoids generating body_markdown exceeding 12 newlines (which is validated in Listing and prevents save, breaking the seeds process).
A totally reasonable and probably more readable approach would be to use [citizen428's suggested](https://github.com/forem/forem/issues/14683#issuecomment-914891139) method - take the first 10 lines and join the body back together. …

When calling Faker::Markdown, avoid "sandwich" method

---

.gitpod.yml

Fixes the awaiting web server command in Gitpod. It was previously checking the curl command for `DEV`. Now it checks for `Forem`.
- Launch Gitpod. The gp terminal session in Gitpod should complete successfully if the webserver is running.
- 
Note that there is another issue with Gitpod at the moment with the init command (#14698). That will be addressed in another PR. For the time being, run the following to start the web server in the Forem Server terminal session.
```
cp .env_sample .env &&
echo "APP_DOMAIN=\"$(gp url 3000 | cut -f 3 -d /)\"" >> .env &&
echo 'APP_PROTOCOL="https://"' >> .env &&
gem install solargraph &&
gem install foreman &&
bin/setup &&
bin/startup
```
accessibility is impacted and tested. …

Fixed awaiting web server command in Gitpod

---

app/services/mailchimp/bot.rb
spec/services/mailchimp/bot_spec.rb

Gibbon raises an [unhandled error](https://app.honeybadger.io/projects/72638/faults/73753178
) when an api key is missing. 
Internal discussion with Ben about whether this was a managed api key (part of the hosting product) or an admin managed item:
> I believe they would be on their own to set that up. If it's not present it probably shouldn't result in an error. 
Since this check happens in a background worker, there's no great way to forward this alert to a responsible party - log the error and move on.
I added a test case for this. It might have been smarter to set an empty api key and then check it doesn't raise than to stub the gibbon request - it's easy enough to replicate locally in console:
```ruby
[2] pry(main)> Settings::General.mailchimp_api_key
=> "Optional-valid" …
```

Handle GibbonError when Mailchimp api key was not set

---

.travis.yml
app/models/profile.rb
app/services/profile_fields/remove.rb
spec/models/profile_spec.rb
spec/requests/admin/profile_fields_spec.rb
spec/services/profile_fields/remove_spec.rb

This PR completely refactors how `Profile` dynamically loads `ProfileField`s to define dynamic accessors which should also solve the problems described in #14433. Instead of using `refresh_attributes!` to load all profile fields upfront (which could lead to all sorts of ugliness including redefining the same field and eventually running into a `SystemStackError`) we now dynamically add them on first access. 
In a similar vein, the `attributes` class method no longer relies on the defined store accessors but on the actually available profile fields. To reduce DB hits these are stored for 24 hours. However, the `refresh_attributes!` is still available but now only updates the cache, it doesn't attempt to redefine any accessors.
All specs should still be green. This change touches pretty …

Refactor profile refreshing

---

app/models/device.rb
app/services/notifications/new_comment/send.rb
spec/models/device_spec.rb

As outlined in https://github.com/forem/forem-ios/issues/105, this PR changes the text of mobile notification for new comments to be more informative and useful. The subtitle of the notification now includes and emoji for easy glanceability and explains what this notification is related to. The text of the notification now spells out which user made a comment, which post it was on, and the beginning of the comment text.
**Bonus**: we weren't sending a sound property, which is required for iOS to play a sound or vibrate. It won't assume we want the default: absence of the property tells the OS not to play any sound or vibration!
iOS Before
iOS After
WatchOS short glance before
WatchOS short glance after
WatchOS long glance before
WatchOS long glance after
Related to …

Change mobile new comment notification text and add sound

---

app/controllers/reactions_controller.rb
spec/requests/reactions_spec.rb

When a user adds an article to their reading list we use their self-set experience level to influence the article's experience level. When confirming a question in a discussion with the product team, I noticed that we don't actually check if a user has an experience level set before trying to create the rating. This PR adds a guard clause to avoid that.
n/a
Nothing specific
None

[15-minute fix] Don't try to create invalid RatingVote

---

app/services/users/safe_remote_profile_image_url.rb
spec/services/users/safe_remote_profile_image_url_spec.rb

This fixes a bug where we weren't pulling in the OAuth provider's (Twitter/GitHub/Facebook/etc) profile image, and instead were always auto generating one. The problem is partly because we take a conservative approach of when a URL is not `https`, we default to auto-generating one.
This PR makes it so it always fills in `http` profile image URLs with `https`, and if the URL is still blank, we auto generate the profile image.
Resolves #14432 
1. Log in via Twitter
2. See that your profile image persisted
3. Log in via GitHub
4. See that your profile image persisted
5. (optional) Log in via Facebook (this is kind of a pain -- Forem team members feel free to DM me for instructions and necessary auth tokens)
6. See that your profile image persisted
Nope
or in a [forem.dev](http://forem.dev) …

Fix bug where OAuth signups were not pulling in OAuth provider's profile image

---

spec/models/hair_trigger_spec.rb

HairTrigger uses the ActiveRecord::Base.descendants to find triggers
in the db (from `models`). WithModel (used in the Settings::Base spec)
clears this during its descendants cleanup, causing this test to
ocassionally fail.
Before checking hairtrigger, if AR::Base descendents is empty, add
ApplicationRecord back to the list - there's an assumption here that all of our
application models inherit from application record - this may or may
not be true if we use engine generated models that do not follow this
convention and need to validate triggers there.
`WithModel::Model#cleanup_descendants_tracking` is clearing the descendants list by deleting it from tracking: 
https://github.com/Casecommons/with_model/blob/master/lib/with_model/model.rb#L56-L62 
hair trigger's `models` method uses the …

Ensure ActiveRecord::Base has descendants before checking triggers

---

app/helpers/application_helper.rb
app/views/articles/show.html.erb
app/views/comments/index.html.erb
app/views/dashboards/_dashboard_article.html.erb
app/views/dashboards/_dashboard_article_row.html.erb
spec/helpers/application_helper_spec.rb
spec/system/user_uses_the_editor_spec.rb

Remove the feature originally implemented in https://github.com/forem/forem/pull/7593. Rails' ERB template is already sufficient at rendering given text as is, ie. no processing and already escaped. 
Supersedes https://github.com/forem/forem/pull/12789
Resolves https://github.com/forem/forem/issues/2204, https://github.com/forem/forem/issues/8705
I wrote a test to accompany this so it should be sufficient.
but if you would like to try it.
1. Create an article with title similar to `Hello <span> there`
2. When saved, it should be exactly the same. There shouldn't be a `</span>` appearing out of nowhere.
n/a

Remove ApplicationHelper#sanitize_and_decode

---

app/views/admin/settings/forms/authentication/_apple_auth_provider_settings.html.erb

When an admin user tries to add apple signin using the authentication settings, it's unclear what is needed to preserve the multiple lines in the current text_field/input. 
Using a textarea makes it easier to paste from a pem file and see that the formatting was preserved. 
visit /admin/customization/config and expand "Authentication" then edit "Apple".
Fill in the apple_pem with multiple lines.
Save, and check Settings::Authentication.apple_pem preserved formatting.
development process, or …

Use a textarea for apple_pem in admin

---

app/javascript/listings/components/BodyMarkdown.jsx
app/javascript/listings/listingForm.jsx

We'll eventually remove Connect from Forem. In the meantime, let's no longer add new listings with the "Contact via Connect" option. This PR removes the option for new listings. As a side-effect, one can also no longer disable it for existing listings but I think that's ok, there are only 15 of them in the DB (well 16, but one is our test listing).
n/a
Click around the listings area and make sure everything still works as expected.
n/a

Remove Connect from listings

---

app/controllers/tags_controller.rb
config/routes.rb
spec/requests/tags_spec.rb

This PR adds an *internal* top tags API for suggestion purposes at `/tags/suggest`. I decided to not go with the one available at `/api/tags` for the following reasons:
1. The public API is still unstable which is why we versioned it as v0.
2. The public API returns attributes we won't need, like colors.
3. The public API sorts tags only by `taggings_count`. On the other hand, the Top Tags page (`/tags`) sorts them by "hotness score" which uses recently tagged articles and their comments, etc. During our call, we talked about "easy", "medium", and "hard" approaches to this topic, and reusing the logic from the internal controller gives us "medium" for free.
4. We may want to further tweak the logic in the future in ways that don't necessarily make sense for the public API.
Note: so far …

Add internal top tags API

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

This is a bug fix to allow an organization's admin to view any of the organization's article's stats.
Fixes #14669

Fix organization's admin unable to view an article's stats

---

spec/support/seeds/seeds_e2e.rb

Ensure Listing created when seeding e2e tests pass validation.
This matches the same change made to the db/seeds.rb file at
https://github.com/forem/forem/blob/main/db/seeds.rb#L515
Since there's a validation that Listings are only 12 lines or
shorter, and no technical limit on the length of
`Faker::Markdown.random`'s output, take the first 10 lines only.
#14685 fixed this in the db/seeds.rb file
https://app.travis-ci.com/github/forem/forem/jobs/538669620 observed failure
Well, I guess you could call db:seed:e2e a lot and hope for the best, or run it just once and confirm nothing broke (i.e. passing the e2e seeded flow is sufficient to demonstrate this fixed).
None

Ensure seeded listings are valid for e2e tests

---

app/models/device.rb
spec/models/device_spec.rb

This PR adds a required field and value to the Apple Push Notification Service payload send from Forem to allow the Forem iOS application to add image attachments to said notifications. We want to do this so the Forem iOS app can attach a Forem's logo image to incoming notifications (this image data can not be sent with push notifications).
Per Apple's [docs](https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications#2942066), for an iOS application to modify the content of an incoming push notification the field `mutable-content` must be present in the notification payload with a value of 1. This PR adds that value and an associated test.
Draft pull request for iOS: https://github.com/forem/forem-ios/pull/108
Originating issue for iOS: …

Add mutable flag to APNS notifcation payload

---

app/helpers/application_helper.rb
app/javascript/packs/followButtons.js
cypress/integration/seededFlows/articleFlows/followAuthor.spec.js
cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
cypress/integration/seededFlows/articleFlows/seriesFlows/previewProfileFromSeries.spec.js
cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
cypress/integration/seededFlows/loggedOutFlows/homeFeed.spec.js
cypress/integration/seededFlows/loggedOutFlows/tagIndex.spec.js
cypress/integration/seededFlows/notificationsFlows/followUserFromNotifications.spec.js
cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js
cypress/integration/seededFlows/profileFlows/followOrganisation.spec.js
cypress/integration/seededFlows/profileFlows/followUser.spec.js
cypress/integration/seededFlows/searchFlows/followUser.spec.js
cypress/integration/seededFlows/searchFlows/previewProfileFromPostSearchResults.spec.js
cypress/integration/seededFlows/tagsFlows/followTag.spec.js
cypress/integration/seededFlows/tagsFlows/previewProfileFromTagIndex.spec.js

- This PR changes the already existing follow buttons to [toggle buttons](https://inclusive-components.design/toggle-button/)
- Added `aria-pressed` value to all follow buttons, set to true when followed.
- This PR addresses the second part of Follow button enhancements #14356 

Accessible names for follow buttons

---

app/models/organization_membership.rb
app/services/tag_moderators/add.rb

When we deployed the feature flag for Connect we overlooked a few more places where it could have been used, this PR remedies that. This was flagged because newly assigned tag moderators still received channel invitation emails despite Connect being disabled.
* In the tag moderators case, emails should only have been sent if the tag didn't have a chat channel yet, as we then end up in `ChatChannels::CreateWithUsers` which ends up calling `ChatChannels#invite_users` which eventually calls `NotifyMailer.channel_invite_email`.
* In the organization case we may not actually send an email at all but the feature flag of course still makes sense.
n/a
Nothing specific.
n/a

Check Connect feature flag in more places

---

app/assets/stylesheets/ltags/PodcastTag.scss
app/assets/stylesheets/user-profile-header.scss
app/views/organizations/_header.html.erb
app/views/podcast_episodes/_liquid.html.erb
app/views/podcast_episodes/index.html.erb
app/views/podcast_episodes/show.html.erb
app/views/users/show.html.erb
cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js

This is the clean up of some broken and mangled functionality in podcast land. It doesn't go nearly far enough to bring podcasts up to date with proper styling and being bug-free in general, but it's a small start.
I figured given the bugginess instability in podcast land anything to clean up and fix things is a pretty easy "yes".
- The podcast liquid tag follow button is currently broken. This just removes that button.
- I removed "pattern image" from the view, and I'll remove this from the backend later. This functionality takes way too much upkeep and we don't need it.
Fixes https://github.com/forem/forem/issues/13667
This is what podcasts currently look like: Basically unusable if not properly set up (and it seems really hard for admins to properly set them up).
Yikes.
Now:
Not a huge …

[15 minute fix] Podcast fixes/clean up

---

app/assets/stylesheets/setup-mode.scss
app/views/devise/confirmations/new.html.erb
app/views/devise/registrations/new.html.erb

This PR removes the header and footer from the email confirmation and the signup pages. 
RFC: https://github.com/forem/rfcs/pull/190
Issue: https://github.com/forem/forem/issues/14649
**To test the signup page:**
1. We have to prepare the db.  Open the rails console and run `User.destroy_all`, `Settings::General.mascot_user_id = nil`, `Settings::General.waiting_on_first_user = true`.
2. Thereafter, set the Feature Flag in the rails console with `FeatureFlag.enable(:creator_onboarding)`.
3. Now, go to `http://localhost:3000/enter?state=new-user`. 
You should see the sign up page without a header or footer. 
**To test the email confirmation page:**
1. We have to prepare the db.  Open the rails console and run `User.destroy_all`, `Settings::General.mascot_user_id = nil`, …

Remove header and footer from signup/email confirmation pages 

---

app/views/admin/shared/_nested_sidebar.html.erb

When we added the Connect feature flag we introduced a little bug in the admin navigation: usually, when you open a group the first element will automatically be activated. This doesn't work if the first subitem is invisible, as is the case for  "Chat channels" when the feature flag is disabled. This PR changes the logic to activate the first visible child instead. 
Reported by @ludwiczakpawel via Slack.
1. Enable the Connect feature flag: `FeatureFlag.enable(:connect)`
2. When you go to `/admin` and click on "Apps", "Chat Channels" should be active.
3. Disable the Connect feature flag:  `FeatureFlag.disble(:connect)`
4. When you go to `/admin` and click on "Apps", "Consumer Apps" should be active.
None.

Fix admin menu when Connect feature flag is disabled

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/assets/stylesheets/widgets.scss
app/helpers/display_ad_helper.rb
app/models/display_ad.rb
app/services/html/parser.rb
app/views/admin/display_ads/_form.html.erb
app/views/admin/display_ads/index.html.erb
app/views/articles/_sidebar.html.erb
app/views/sidebars/_homepage_content.html.erb
spec/factories/display_ads.rb
spec/helpers/display_ad_helper_spec.rb
spec/models/display_ad_spec.rb
spec/requests/stories_index_spec.rb
spec/services/html/parser_spec.rb

At the core of this PR, is adding back in sanitation so that we allow for a consistent, safe interface for creating `DisplayAd` content. It's currently awkward and fairly unsafe to use this functionality for many creators. This fixes things.
Therefore removes this code:
>    \# Temporarily disable the sanitisation in order to launch the SheCoded Campaign.
>    \# TODO: find an alternate solution.
I think the core purpose of this is well in the rearview for Forem and DEV needs.
This does remove the capacity for inline styles (not immediately breaking existing stuff, but will on re-save of anything), but adds the same wrapping class to the left-hand ads as the right. This should be a big win for visual consistency while still providing a lot of flexibility as far as how admins might choose …

Fix inconsistencies with DisplayAd

---

app/controllers/sitemaps_controller.rb
app/lib/constants/settings/user_experience.rb
app/models/article.rb
app/models/settings/user_experience.rb
app/views/admin/settings/forms/_user_experience.html.erb
app/views/articles/show.html.erb
spec/requests/stories_show_spec.rb

Remove the check for `<code>` tags (there are a few test cases that exercise this that can be removed still). 
Simplify the presence of two "magic" numbers 3 and 5 in the sitemap generation and article show pages, if an article is going to be included in the sitemap, it should be indexed.
Andy's [forem.team post](https://forem.team/andy/hidden-feature-preventing-articles-without-a-code-tag-to-be-crawled-5eod)
Ben's suggestion from the comment was the guidance here.
Behavior covered by the spec/requests/stories_show_spec.rb cases.
Confirmed new setting shows and can be updated in the admin/customization page:
None. …

Remove unneeded checks for code tags when filtering articles from search indexing

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/services/html/parser.rb

This is a quick fix to follow up on #14789
**JS:**
Changing the JS to use modern approach as opposed to hack, and fixing a problem with fetching the right element all the time.
**Ruby:** We accidentally re-used the `width` variable, which didn't cause a visible problem, but caused the width we pass into the image proxy to be one we retrieve from the original image instead of the one we pass.

[Tiny fix] Fix a couple small bugs from DisplayAd clean up

---

app/controllers/stories_controller.rb
app/services/articles/feeds/find_featured_story.rb
app/services/articles/feeds/large_forem_experimental.rb
spec/services/articles/feeds/find_featured_story_spec.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb

I recently refactored some feed code ([PR](https://github.com/forem/forem/pull/14707)). However, there's one more thing that could have been extracted into an independent object, the finding of the featured story. This PR extracts this so we don't make it part of a feed strategy when it's actually a pretty generic process.
n/a
Nothing specific, specs should be green.
None

Move featured story to separate service

---

app/views/stories/articles_search/index.html.erb

If you didn't specify `q=`, this template would raise an error. HTTP params are basically the only thing `blank?` and `present?` are good for since there is no distinction between an empty string and a missing value.
[Search requests have been failing since last night](https://app.datadoghq.com/apm/resource/practical_developer/rack.request/18301539a1a8bcc8?query=env%3Aproduction%20service%3Apractical_developer%20operation_name%3Arack.request%20resource_name%3A%22Stories%3A%3AArticlesSearchController%23index%22%20status%3Aerror&env=production&index=apm-search&spanID=4314481071243849254&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Aversion_count%2Chits%3Acount&start=1632831153636&end=1632922790000&paused=true).
_Will this PR introduce a change that impacts Forem members …

Allow search endpoint to be used without q param

---

app/javascript/leftSidebar/TagsFollowed.jsx
app/models/article.rb
app/models/user.rb
app/services/broadcasts/welcome_notification/generator.rb
app/services/email_digest_article_collector.rb
app/workers/follows/update_points_worker.rb
config/routes.rb
spec/models/article_spec.rb
spec/services/email_digest_article_collector_spec.rb

The digest emails could include articles for the tags the user "anti-followed". In case you aren't aware of this feature, "anti-following is done somewhat counter-intuitively by following a tag first and then assigning it a negative score.
In the case of the digest email, this led to a problem because `EmailDigestArticleCollector` only checked if `User#cached_followed_tag_names` contains any tags, without also checking if any of them are anti-follows. I suspect that the same mechanism is creating problems in other areas too, e.g. I saw the same method being used in `Users::SuggestRecent` but again we don't seem to differential between follows and anti-follows.
This PR does the following:
* Change `User#cached_followed_tag_names` to only include tags with a score >= 1.
* Introduce …

Don't include "anti-followed" tags in email digest

---

app/assets/stylesheets/views/article-form.scss
app/controllers/tags_controller.rb
app/javascript/shared/components/__tests__/tags.test.jsx
app/javascript/shared/components/tags.jsx
app/models/tag.rb
app/services/search/tag.rb
app/views/layouts/_sidebar_tags.html.erb
app/workers/tags/resave_supported_tags_worker.rb
cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js
spec/system/homepage/user_visits_homepage_spec.rb

When a user hasn't typed in any search term for tags in the v2 article editor, we now suggest the 'top tags' for the community.
An "empty search" includes:
- When the user initially focuses the tags input
- When a user selects a tag from the dropdown, and we immediately move on to a 'fresh search' 
**Some limitations to this PR:**
- There are known accessibility and usability issues with this widget, and this PR does not address them. These issues are captured and are being looked at by the Content Experience pod
Known issues include:
- A bug where if you fully type a search term it disappears (https://github.com/forem/forem/issues/14812)
- Minimal feedback to user on tag selection
- Search occasionally feeling 'slow' / being a character behind
- Appropriate accessible …

Suggest top tags when tag search is empty

---

app/controllers/stories/tagged_articles_controller.rb
spec/requests/stories/tagged_articles_spec.rb

Since tags get created whenever they are included in a post, the tag exists even with no published posts.
It has been determined that the expected behavior should be a `404` response. If the tag is supported than the expectation is that the admin wants it to show up, even with no posts. (Likely a no posts _yet_ scenario.)
Closes https://github.com/forem/rfcs/issues/282
Originally came out of this discussion: https://forem.dev/ildi/is-it-possible-to-delete-hide-tags-16km
This should mostly just fill expected behavior.

Return 404 if empty and unsupported tag

---

app/controllers/sitemaps_controller.rb
spec/requests/sitemaps_spec.rb

This PR adds an endpoint to our sitemap route called `/sitemap-posts.xml`, with an optional number called `/sitemap-posts-2.xml` etc.
Sitemaps need to be at the root of the domain, which is why the logic like this exists in the first place.
Currently we _only_ have "monthly" sitemaps... `/sitemap-Sep-2021.xml`, which forces an admin to go into Google Search Console at the beginning of every month to add a new sitemap.
This allows an admin to provide encapsulated sitemaps and glean information about what Google is searching when, but is not an ideal _default_ sitemap to provide. This is the "default" sitemap for posts on Forem.
There is optionally a zero-indexed value to append here if a Forem has more than 10k published posts, but generally a Forem can get by for a while with just …

Add recent resource sitemap endpoint for posts

---

lib/tasks/add_navigation_links.rake

Changing `Terms of use` to `Terms of Use`
This has been bothering for me a while, and it's now consistent with `Code of Conduct` (which is not `Code of conduct` ) capitalization-wise
N/A
N/A
N/A
appropriately.

Modify capitalization of default navigation link

---

app/javascript/shared/components/tags.jsx
cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js

Now that we show all top tags as soon as the tags input is focused, the UI is pretty overwhelming on DEV in particular, due to the large chunks of HTML for the 'rules'. As a stop-gap while we rethink the tags autocomplete as a whole, this PR removes the rules from the 'top tags' suggestions. Rules are still shown once a user starts searching.
https://github.com/forem/forem/pull/14817
- Make sure you have some rules set for some of your tags locally. You can do this in Admin > Content manager > Tags
- Draft a new post in the V2 editor
- Click on the tags field and check rules are not shown, only the tag names
- Start typing one of the tags with rules
- Check that the rules are shown, as before
N/A …

dont show rules for top tags

---

app/controllers/api/v0/instances_controller.rb
scripts/release

This PR adds the actual released version (via the release script) into the code. The idea is:
- Run `scripts/release` to cut a new release, which automatically adds and commits a `.release-version` file with the tag generated for the release
- Buildkite builds new containers with that file in it
- When you deploy from `stable`, it will have that file in it
- When you hit the `/api/instance` endpoint, the `version` property of the JSON response contains that release tag …

Add real release version into the running code

---

app/views/dashboards/_actions.html.erb

As per issue #14841 I have made the dashboard left-side navigation an unordered list with the anchor elements as the list items. To improve quality of screen reading.
Closes #14841 
I don't believe this change will need any new tests to be written.

Make dashboard left side nav an unordered list

---

app/models/comment.rb
app/views/comments/index.html.erb

Profiles and user settings are loaded for on each comment author. On posts with many comments (such as [this one](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/tejvNGu5MkN/trace/duNeN3TnCTi)), this invokes a *lot* of DB queries. Each of these partials is a comment:
Every single one that isn't cached invokes 3 queries:
1. `user.settings`
2. `user.profile`
3. `ProfileField.header`
The first two are fetched from the database for every comment. This PR replaces the first 2 per comment with 2 queries for all comments.
The third is short-circuited by the ActiveRecord query cache, so while it will return a new instance of that profile field and ActiveRecord reports it as a query, it doesn't actually reach out to the database. I don't know how to avoid that allocation, tbh, but if …

Eager-load comment user data

---

app/controllers/admin/display_ads_controller.rb
app/models/display_ad.rb
app/views/admin/display_ads/_form.html.erb
app/views/admin/display_ads/edit.html.erb
app/views/admin/display_ads/index.html.erb
app/views/admin/display_ads/new.html.erb
app/views/layouts/admin.html.erb
spec/models/display_ad_spec.rb
spec/requests/admin/display_ads_spec.rb

This PR removes the organization dependency for display ads which was confusing admins due to the fact that organization attribution was never fully implemented.
In the future we may implement further features that make use of this, or we could remove it altogether, but this should remove confusion.
In implementation I wanted to fix some other UX issues with display ads and ad clarity. So now we have more instructions, and we also have a preview of the display ad right there in the admin section.
I also changed the "search" UX to include multiple columns instead of just searching by organization name.
**Creating new ad:**
**Displaying saved ad:**
Along the way I noticed that we still have the "help link", but it generally links to the wrong places. I'm not sure what the intentions of this …

Remove organization dependency and improve display ad UX

---

app/services/edge_cache/bust_article.rb

This query is our number 5-6 query (depending on the time frame you look at) and has a _median_ execution time of 200ms, which is kinda wild for a query we run this frequently — especially multiple times in a single Sidekiq job. Comparing the two query scopes in a production Rails console on DEV:
```
irb(main):050:0> Benchmark.ms { Article.cached_tagged_with('ruby').published.where('published_at > ?', 1.day.ago).order(public_reactions_count: :desc).limit(3).ids.count }
=> 5.241397011559457
irb(main):051:0> Benchmark.ms { Article.cached_tagged_with('ruby').published.where('published_at > ?', 1.day.ago).order(public_reactions_count: :desc).limit(3).ids.count }
=> 5.306847975589335
irb(main):052:0> Benchmark.ms { Article.tagged_with('ruby').published.where('published_at > ?', …
```

Optimize `Article` query in `EdgeCache::BustArticle`

---

app/models/users/notification_setting.rb
spec/models/users/notification_setting_spec.rb
spec/requests/user/user_notification_settings_spec.rb

In `Users::NotificationSetting` model, `Users::SubscribeToMailchimpNewsletterWorker` is executed **ONLY** the case `email_newsletter` is true. So a user can not unsubscribe from the newsletter by updating `email_newsletter` to false.
To fix this, I changed `subscribe_to_mailchimp_newsletter` method to check `saved_changes.key?(:email_newsletter)` instead of `email_newsletter`.
And I also make it to check `Settings::General.mailchimp_api_key.blank?` the same as `User` model.
https://github.com/forem/forem/blob/e50db312fb5181c674a80b0c0e86f06752be8afc/app/models/user.rb#L509-L511
_If your PR includes UI changes, …

Subscribe the newsletter if email_newsletter is changed

---

app/assets/stylesheets/profile-preview-card.scss

After some use of `1s` I think this is _too long_ of a wait to show the card. We had previously deemed `500ms` as possibly too short, but I think we went a little too far.
There is no way to prove who is right, and maybe we could do this in a more sophisticated way in the future, but for now I _feel_ that this proposed duration is better than `1s`.
I did move a couple time values in this file into scss variables in case we want to continue changing this up. Just seemed a little cleaner way to store this kind of thing in the file.

Change preview card hover delay

---

app/controllers/api/v0/instances_controller.rb
app/controllers/registrations_controller.rb
spec/requests/api/v0/instances_spec.rb
spec/requests/registrations_spec.rb

Following up on the conversation from https://github.com/forem/forem/pull/14865#discussion_r719663741, this PR adds logic for a Forem to register itself on Forem Discover.
This original implementation was removed in the previous PR, this one brings it back. The primary concern was that by registering the Forem right after the creation of the first user, the value of the Forem's domain would be something like `forem-3232dsdsd.forem.cloud` instead of the actual domain. In other words, we may be registering "too early" in the onboarding process.
As it turns out, the flip of the `app_domain` is done manually and internally by the systems team so we don't have a great, programmatic way to know when it's "okay" to register on Discover. I've explored callbacks in the past on Rails settings, and …

Auto register Forems on Discover

---

app/assets/stylesheets/components/media-cards.scss

As title says: it's a tiny CSS fix for making border-radius on media cards (videos primarily) automatic as we have on other cards... 
When viewing /videos, each individual card should have rounded corners on desktop and NOT rounded corners on mobile.

Media Cards - CSS fix for border radius

---

app/views/admin/navigation_links/_form.html.erb

This ensures it's rendered in the pattern regex field in the browser.
Without `"\\w"` -> `"\w"` we get `"\w"` -> `"w"` and only urls starting with
w (www, for example) are accepted by the matcher.
Visit http://localhost:3000/admin/customization/navigation_links and add a new link or edit an existing one.
Set the url to https://forem.dev 
On main:
this branch (hard to take an image of a warning _not_ being shown, but it's successfully posting the update):
none

Escape the backslash in the regex string so the backslash is preserved

---

spec/views/articles_spec.rb

Time Zones are political things, and move. The timezone database knows
this, and correctly interprets times as they would have been at the
time.
For example, when the Time zone is Africa/Monrovia, the offset now is
0, but the offset in 1970 was [-44.5 minutes](https://en.wikipedia.org/wiki/UTC%E2%88%9200:44#History ), so Time.zone.at(0) is Dec 31st, 1969, 23:15:30 and not Jan 1st, 1970 00:00:00. 
Prevent this spec from randomly failing based on Zonebie's selected
timezone by comparing the offset _then_ against UTC, and predicting
whether the 60's have ended yet.
```
ZONEBIE_TZ="Africa/Monrovia" bundle exec rspec spec/views/articles_spec.rb
```
None …

Compare the utc offset from the timestamp, not now

---

app/services/settings/authentication/upsert.rb
spec/services/settings/authentication/upsert_spec.rb

Assign empty array to `Settings::Authentication.providers` if the providers string is blank (all of them are disabled)
Also add new spec for example cases of the `Settings::Authentication::Upsert` helper
#14975 
- Login as Admin
- Go to Admin -> Customization -> Authentication Settings
- Make sure a provider is enabled
- Disable all providers
- refresh
- all providers should still be disabled
- _click_ `disable`
- _click_ `Update Settings`
- _refresh_ …

Disable all providers when `providers_to_enable` param is blank

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/views/articles/show.html.erb
app/views/comments/_comment.html.erb
app/views/comments/_comment_quality_marker.html.erb
app/views/comments/index.html.erb
app/views/podcast_episodes/show.html.erb
config/locales/views/comments/en.yml
cypress/integration/seededFlows/articleFlows/hideArticleComments.spec.js
cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
spec/requests/comments_spec.rb
spec/support/seeds/seeds_e2e.rb

Shows hidden comments as collapsed on /comments page and the resource page itself of an article/podcast episode/story only for the author/s.
#13360 
1. Create an article/podcast episode as a user (user1)
2. Log in as a different user (user2), and add a comment on the article/podcast episode
3. Log in as the original creator (user1) again, and hide the comment made by user2. Hit confirm when asked by the browser and let the page refresh. Observe that at the location of the comment, a collapsed section (detail) is visible with name of the user that made the comment. Opening the details brings the comment back, with a hidden comment header at the top and has an Unhide link in the dropdown of the comment.
4. Log back in as user2 (who made the comment) and observe that the comment (that was …

Added collapsed hidden comments to author's article/podcast episode view

---

app/assets/javascripts/initializers/runtime.js
app/javascript/.storybook/preview-head.html
app/javascript/article-form/articleForm.jsx
app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
app/javascript/crayons/MarkdownToolbar/__tests__/MarkdownToolbar.test.jsx
app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js
app/javascript/shared/components/useKeyboardShortcuts.js

Our current `KeyboardShortcuts` helper component conflates `ctrl` and `cmd` as the same thing, which causes a problem on macOS where `ctrl` keys have separate readline shortcut bindings, which we shouldn't unintentionally override.
This currently mostly impacts the `MarkdownToolbar` in storybook, where e.g. `ctrl+b` is triggering the same action as `cmd+b`.  It also impacts the editor preview shortcut which is `cmd+shift+p` on macOS, but is also triggered by `ctrl+shift+p`.
The change in this PR updates the `KeyboardShortcuts` to regard `ctrl` and `cmd` separately. It's therefore the responsibility of the caller to decide if `ctrl` and `cmd` should execute the same action, and only listen for the correct modifier key if not.
Fixes https://github.com/forem/forem/issues/15263
- Run `yarn …

treat cmd and ctrl key shortcuts separately on macOS

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb

Remove [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) from comments initializer code to placate the assets precompilation stage
The supported js features in the asset pipeline scripts is different from those in the webpack
https://github.com/forem/forem/pull/14018 added this code (merged earlier today)
https://github.com/forem/forem/pull/9188 sets up our custom uglifier (to enable source maps) which may be related to the syntax difference between the asset pipeline and webpack managed js files.
- buildkite should build containers successfully (not error out)
- locally, asset precompilation should not error out (okay for postcss to fail, it's unrelated) 
```
RAILS_ENV=production NODE_ENV=production bundle exec …
```

Remove optional chaining syntax from comments page initializer

---

db/migrate/20211104161101_add_privileged_users_reaction_sum.rb
db/schema.rb

Adding caching column for reaction sums
In a future commit, I'll introduce the logic to handle the caching of the sum.
Related to  #15240
PR #15240 
None
None

Caching sum privileged reaction scores

---

app/controllers/follows_controller.rb
app/helpers/application_helper.rb
app/views/organizations/_header.html.erb
cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
cypress/integration/seededFlows/articleFlows/followOrganization.spec.js
spec/support/seeds/seeds_e2e.rb

Following an organization from an article show page doesn't work as expected.
Clicking the "Follow" button makes a POST request to FollowsController#create with the following params
```
{
followable_type: "organization",
followable_id: 4094,
verb: "follow"
}
```
Notice the character casing of `followable_type`. 
In the `create` action, as per the current logic, the switch case incorrectly returns from the last else block a `User` object instead of `Organization`. Hence for the above example, a `follow` record is created with `followable_id` as `4094` and `followable_type` as `User` instead of `Organization`. 
This issue only occurs when following from the article show page. It appears to work properly when you try to follow the organization from it's profile.
Fixes #15001
have not been …

Bug Fix: Following an organization from article's sidebar creates an incorrect `follow` record

---

app/views/users/_profile.html.erb

@msarit asked me to help a little with [layout fix](https://github.com/forem/forem/pull/15287) but I had troubles pushing to Arit's PR so I let myself open a new one (only because it's a production bug and I hope we can merge fix ASAP). This PR fixes the layout issue introduced in #15255 by [taking into consideration idea](https://forem-team.slack.com/archives/CSY9DBB2B/p1636359743017200) from @Ridhwana about unifying how we display field descriptions elsewhere.
- https://github.com/forem/forem/pull/15287
- https://github.com/forem/forem/pull/15255
**Updated field layout:**

[Quick fix] Characters counter layout fix

---

app/assets/stylesheets/config/_generator.scss
app/assets/stylesheets/config/_import.scss
app/javascript/article-form/components/Help/EditorFormattingHelp.jsx

This PR cleans up our CSS utility-first classes generator. I've removed unused (and unlikely to be used) classes. That should save us around ~4000k lines of pre-optimized CSS code. If any of these will ever be needed we can simply add them manually.
This could be considered either as preparation to fully adopt official version of TailwindCSS OR preparation to fully drop TailwindCSS **idea** 🤷 . Nevertheless it's optimization.
This should **not** have any affect on UI - all the classes were unused.

CSS Generator Cleanup

---

lib/data_update_scripts/20211112173720_nullify_empty_tag_colors.rb
spec/lib/data_update_scripts/nullify_empty_tag_colors_spec.rb

Set bg_color_hex and text_color_hex to nil when they were an empty
string.
This is a cleanup of legacy data (from form submissions, when the
field was unset and another attribute was updated, the value could be
saved as '' rather than set nil). This is no longer possible due to
validations added in #10495 so only needs to be handled once.
Noticed after #15266 was merged, and these values caused page failures on the stories controller, see [Jamie's explanation](https://forem.team/engineering/2021-11-11-changing-tag-colors-brings-down-the-site-apparently-2olp)
Mitigated by checking for presence rather than truthiness in #15356 
Expected update size is limited to ~544 rows in DEV's db, probably fewer than 10 in most other forem instances.
You could replicate the before actions in the spec …

Nullify invalid tag colors

---

app/assets/stylesheets/components/buttons.scss

`<input type="file" />`s cannot have their buttons styled. The way we currently handle the styling of this is by wrapping `<input type="file" />` with a `<label class="crayons-btn ..." />` and hide the input visually. This looks good and is accessible. However our implementation currently does not provide a focus state for that button like label.
This PR adds a focus state for these kinds of labels via [:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within).
Closes #15234 
Fixes upload button styling in #15363 
1. Create a new post by navigating to http:/:localhost:300/new
2. Click in the content area of the new post to give it focus.
3. Press <kbd></kbd> and <kbd></kbd> to tab backwards.
4. Notice that the upload button now has a focus state.
This makes any file …

Now labels with the CSS class crayons-btn that wrap inputs of type file have focus states

---

app/controllers/admin/tags_controller.rb
spec/requests/admin/tags_spec.rb

Don't allow passing `tag[name]=` in post params to admin tag update. This appears to be the only place someone could edit the name of an existing tag. 
There's no edit field for name in the form, it's not expected that someone
change the name (it serves as a natural key for tags) - it's preferable to
alias an old/unwanted name to a new/wanted tag, in cases where a renaming 
is needed.
https://github.com/forem/forem/pull/15373#discussion_r749544527 discussion in a slightly related update
None
development process, or any of our internal …

Don't permit changing tag names in admin

---

app/services/mentions/create_all.rb
spec/services/mentions/create_all_spec.rb

I looked into the issue and tested it locally. I also added a couple new specs that show my findings. This issue seems to have already been resolved. 
#9077
- Mention a user on an article inside a code block or inside a snippet
- That use should not  have any new notifications and no new Mentions should be created
issue template so …

Issue #9077 has already been resolved, added specs

---

app/views/admin/settings/forms/_authentication.html.erb

Prior to this commit, the field "worked" but you had to toggle email
authentication to enabled, then fill it out.  You could then disable
email notification and it would work.
This builds on #15397
Got to `/admin/customization/config` in the browser and open the Authentication setting
I don't like the padding of these fields (in Safari).  I could use help on that.

Moving blocked registration domains up

---

app/liquid_tags/youtube_tag.rb
spec/liquid_tags/youtube_tag_spec.rb

In production, the Youtube Liquid Tag works when you pass in a video ID with a timestamp query in the following format: `fhH5xX_yW6U?t=1h1m1s` (1hour, 1 minute, 1 second).
Youtube does not appear to format the timestamp query like above anymore. Timestamp queries are now in the format: `fhH5xX_yW6U?t=120` (120 seconds).
However, our current Youtube Liquid Tag does not accept the `?t=120` format. This PR fixes that.
This bug fix is necessary for my ongoing work on [unifying how we generate Liquid Tags](https://github.com/forem/forem/issues/15099#issuecomment-973058737
) in Forem. Specifically, this PR allows my work on the Youtube Liquid Tag to proceed.
- In the app, create a new post. In the body, create a Youtube Liquid Tag with a valid ID, and append a timestamp query in the two formats …

Update Youtube Liquid Tag to accept seconds in timestamp query

---

config/blazer.yml

We need to extend Blazer's timeout in order to run some more intensive queries. This may not be enough and we might still be held back by `STATEMENT_TIMEOUT`
n/a
n/a
n/a

Increase Blazer's timeout

---

app/controllers/omniauth_callbacks_controller.rb
app/errors/authentication/errors.rb
app/services/authentication/authenticator.rb
spec/services/authentication/authenticator_spec.rb

Prior to this commit, when an administrator had indicated blocked email
domains, those blocks were not applied to identities created via the
OAuth sources (e.g., Twitter, Facebook, etc).  With this change, we're
hooking into the similar logic flow as suspended email accounts.
Related to #15403, #15397, and forem/rfcs#281
To QA this locally requires several things:
- First you'll need to configure your instance to allow for OAuth from one of the providers
- Then you'll need to update the blocked domain
- Goto `/admin/customization/config` and open the Authentication setting.
- Assuming you're using your OAuth account, add you email accounts domain to the Block email domains section
- In an incongito browser tab, create an account by connecting to the OAuth account
You should receive a …

Guarding against spam from OAuth Sources

---

app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js
app/javascript/utilities/__tests__/textAreaUtils.test.js
app/javascript/utilities/textAreaUtils.js

This adds another small enhancement to the markdown toolbar in Storybook (not currently live in the app yet).
For block level elements, the formatters currently always insert two new lines before, and one new line after.
This PR tweaks that behaviour so that we only insert those new lines if they don't already exist i.e:
- if the selection is the first text in the textarea (not previous characters/lines), don't add any new lines
- if the selection is immediately preceded by 2 new lines, don't add any before the formatted block
- if the selection is immediately preceded by 1 new line, only add one new line before the formatted block
- if the selection is immediately followed by a new line, don't add any after the formatted block
- in all other cases, continue to add 2 new lines before, and …

Markdown toolbar - update new line logic for block syntaxes

---

.gitpod.yml
gitpod-init.sh

https://github.com/forem/forem/issues/15428 points out an issue where
the command sequence runs (foreman starts the Procfile.dev)
but rails exits early because the database is not up.
Await the db port before proceeding.
Initially I thought to put this in the gitpod-init.sh (called as init) but I believe the initializer may not be run for pre-built containers? The failure in the main branch happened very early (while it took 10+ minutes in a branch build).
fixes #15428 
The behavior in question was happening reliably for me when connecting to a prebuilt environment (where bin/setup had already been run and did not need to re-run) or after stopping and reconnecting to a workspace.
I suppose connecting via the [gitpod link](https://gitpod.io/#https://github.com/forem/forem/pull/15429) to …

Gitpod: wait for postgresql to be listening before startup

---

app/views/stories/articles_search/_meta.html.erb
config/locales/views/misc/en.yml
config/locales/views/misc/fr.yml
spec/system/search/search_title_spec.rb

Best practice for accessible search page titles is to include the search query as part of the title, as well as reflecting it in the `h1` of the page. We have already made the change to show the search term in the `h1`. This PR updates the title to use the search param too.
NB: We previously had concerns about caching issues when we started using the query param in the `h1`: https://github.com/forem/forem/pull/14848. As this PR uses that same query param, I believe there's no negative impact with this change, but I'd appreciate a concept check on that!
Closes #14735
- Visit the search page _without_ an active search - i.e.: `/search`. Check that the page title (on your browser tab) is "Search Results - { community name }"
- Search for a phrase or word. Check that the page title is "Search …

Reflect search query in page title

---

app/models/ahoy/event.rb
app/models/ahoy/visit.rb
app/models/api_secret.rb
app/models/badge_achievement.rb
app/models/discussion_lock.rb
app/models/display_ad_event.rb
app/models/identity.rb
app/models/mention.rb
app/models/note.rb
app/models/notification.rb
app/models/notification_subscription.rb
app/models/organization_membership.rb
app/models/podcast_episode_appearance.rb
app/models/podcast_ownership.rb
app/models/poll_skip.rb
app/models/poll_vote.rb
app/models/profile.rb
app/models/response_template.rb
app/models/user.rb
app/models/users/notification_setting.rb
app/models/users/setting.rb
spec/models/user_spec.rb

Prior to this commit, several of the user's "has_many" were marked as
`depenedent: :destroy`.
In the case of :destroy, ActiveRecord instantiates each object and then
runs destroy. Whereas in the case of :delete, ActiveRecord issues a SQL
command to delete the related files.
It is often "safer" to use :destroy, as it guarantees that you'll
instantiate the record and run it's callbacks. But sometimes you have
to go with the speed of SQL.
And while not directly related to #15424 it is representative of our
callback ecosystem creating some unexpected computational loads.
Related to #15442 and #15424
None
None

Favoring delete_all on user relationships

---

app/views/admin/creator_settings/_form.html.erb

This PR adjusts the booleans that tie back to the labels for the "Who can view content in this community?" section of the Creator Settings form. As it currently stands, when a Creator selects "Everyone," the form does not update in the backend or the Config as expected since "Everyone" is currently set to `public` = `false` when it really should equate to `public` = `true`. There are two ways that we could address this issue and I am happy to implement either of the two fixes, but to keep the text on the form consistent, I opted to go with the first of the two approaches:
- **Approach 1 (Current Implementation)**: Keep the labels as-is and adjust the booleans associated with the labels instead. To accomplish this, I set the "Everyone" radio button to `true` rather than `false`. By doing …

Adjust "Public" Radio Buttons on the Creator Settings Form

---

app/javascript/contentDisplayPolicy/initHiddenComments.js
app/views/comments/_comment_header.html.erb
app/views/comments/_hide_comments_modal.html.erb
cypress/integration/seededFlows/articleFlows/hideArticleComments.spec.js

Implemented accessibility improvements suggested by @aitchiss in #15178 
On hide comment modal:
- added a link to report a comment url
- added a comment permalink
#15178 

Accessibility improvements for hide comments modal

---

app/assets/stylesheets/components/dropdowns.scss
app/assets/stylesheets/components/profile-preview-card.scss
app/assets/stylesheets/views/article-form.scss
app/javascript/CommentSubscription/CommentSubscription.jsx
app/javascript/article-form/components/Options.jsx
app/views/articles/_actions.html.erb

Prior to this change, when you would hover over an author profile that
was "close to" the bottom of the page, the card would be transparent
instead of the expected opaque.
With this change, when you hover over an author profile that is "close"
to the bottom of the page, the card renders as an opaque card.
Now why does this work?  I don't really know, except to say that a
`display: table` imperative is a more "chunky" display element than a
block.  I would love for someone to explain why this works.
Tested against on MacOS Safari, Firefox, and Chrome.
https://developer.mozilla.org/en-US/docs/Web/CSS/display
Fixes #15290
Open to the homepage, and scroll so that the bottom-most visible article card is position just above the browser window.  Hover over the author.  With this fix, the card …

Preventing author profile from going transparent

---

config/environments/development.rb

How many times have you pulled down the latest code only to be told "Nope! Run `rails data_updates:run` first"? What if the robots could do that for us?
Honestly I can't believe it took me this long to get fed up with this error :joy: 
- Delete the record of a random DUS having been executed so that it will be required to run again `psql Forem_development -c 'delete from data_update_scripts where id in (select id from data_update_scripts order by random() limit 1);'`
- Open up a rails console with `rails c`
- Note the "Running data updates..."
- Exit and `rails c` again
- No "Running data updates" message because none were pending
will …

Automatically run DataUpdateScripts in development

---

app/models/reaction.rb
app/services/search/reading_list.rb
spec/services/search/reading_list_spec.rb

Prior to this commit, if a given user adds an article to their reading
list then the author unpublishes the article, the article remains in the
reading list.  When the given user would then "click" on the now
unpublished article, they would get a 404 Not Found notice.
With this commit, we now exclude unpublished articles from the search
results for the reading list.
This should also address the issue of attempting to archive the reading
list item (because it won't be visible in the listing).
One of the behaviors that is expected is if, in the above scenario, the
author again publishes the article, that article will again "appear" on
the reading list for the given user.
Closes #14796
To test this in the UI:
- Sign in
- Create and publish an article
- Add it to your reading list
- Unpublish …

Ensuring reading list excludes unpublished articles

---

app/models/article.rb
app/models/discussion_lock.rb
app/models/mention.rb
app/models/notification_subscription.rb
app/models/page_view.rb
app/models/poll.rb
app/models/poll_option.rb
app/models/poll_skip.rb
app/models/poll_vote.rb
app/models/profile_pin.rb
spec/models/article_spec.rb
spec/models/poll_spec.rb

The `dependent: :destroy` callback is slower than `dependent: :delete`
and `dependent: :delete_all`.  We need only favor the `dependent:
:destroy` when there's callbacks that happen.
In the case of :destroy, ActiveRecord instantiates each object and then
runs destroy.  Whereas in the case of :delete, ActiveRecord issues a SQL
command to delete the related files.
It is often "safer" to use :destroy, as it guarantees that you'll
instantiate the record and run it's callbacks.  But sometimes you have
to go with the speed of SQL.
This relates to #14140.  Note there is still more to consider, but given
that we're looking at moving from :destroy on all of an article's page
views to :delete, we might buy enough time in the callback.
[Article deletion times out if there are existing …

Favoring dependent: :delete_all over :destroy

---

app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx

The markdown toolbar shortcuts were not preventing any default browser action, as they should. For example, if you open Firefox on a mac and execute `cmd + U` in the editor, the underline would be inserted, but view source would also open in a new tab.
This PR adds in a `preventDefault()` to make sure only our shortcut runs.
Related to toolbar work - https://github.com/forem/forem/pull/15347
Fixes https://github.com/forem/forem/issues/15507
Try running the app on multiple browsers, start a new post, and execute the toolbar shortcuts while in the text area:
- cmd/ctrl + b
- cmd/ctrl + i
- cmd/ctrl + k
- cmd/ctr + u
- cmd/ctrl + shift + x
In each case you should see a markdown syntax appear in the editor, but no other browser-specific actions should be apparent
N/A - a general usability …

prevent default on keyboard shortcut presses

---

app/models/poll.rb
app/models/poll_skip.rb
app/models/poll_vote.rb
spec/models/poll_skip_spec.rb
spec/models/poll_spec.rb
spec/models/poll_vote_spec.rb

Favor asking the poll if the user has already voted instead of relying
on the poll vote or skip to know about the implementation
details (e.g. should a poll vote know that there's a related model call
poll skipped?  likely not)
This refactor also tidies up the specs, for which there's quite a bit of
chatter.
Found via the `flay` gem.
None.
None.
None.
not: This is a refactor of a server-side implementation detail.

Refactoring poll/vote/skip logic

---

app/models/settings/community.rb
spec/models/settings/community_spec.rb

If a community name has a < or > it may cause havoc when the community
attempts to send an email.
Closes #15274
None.
Here's the UI when I attempt to update:
None.

Validating community does not include < nor >

---

app/javascript/utilities/gist.js

Solves issue #14428. Added a timeout which gives consistent order of gists.
https://github.com/krux/postscribe#how-to-use-postscribe-to-render-an-ad-after-load
To recreate the issue, make sure you restart your browser or empty the cache. 
- Head to a (post page )[https://dev.to/luvejo/how-to-build-a-carousel-from-scratch-using-vue-js-4ki0]
- Select the author on the right
- Now select the same post from the author page
- Gists should now be mixed up 
(Able to produce behaviour in all browsers.)
To test in your local you can create a post which has multiple gists. And can follow the same steps as above. 
Moving to given branch in PR, issue should be resolved.
None
development process, or any of our internal teams? …

Remove extra script tag from embedded gists to prevent them from mixing up

---

app/models/user.rb
app/views/users/show.html.erb

Prior to this commit, we trusted all user profiles.  There are folks
using DEV.to profiles to help with their spam efforts.
With this commit, we're trying to thwart their efforts.
Closes forem/rfcs#334
In the user's profile (`/:username`) inspect their profile URL.  If they are not a trusted person, then there should be a `rel="ugc"` attribute on the link.
None.

Adding ugc role to untrusted profile URLs

---

app/models/device.rb
spec/services/push_notifications/send_spec.rb

#15212 fixed some of the ConsumerApp issues we had with Android notifications but this was a detailed I missed. The Rpush app should be assigned by what the `ConsumerApps::RpushAppQuery` query returns. This was causing a server error when trying to queue a comment for PN delivery.
Leaving a comment in [this thread](https://community.benhalpern.com/rt4914/test-post-22m1) displays this error:
#15212
If you create an Android Device (model in DB) associated to a ConsumerApp and run this it should work:
```ruby
device.create_notification("Test title", "Test body", { url: URL.url })
```
It's a bit tricky to set this up. Since this is code not currently "under load" in production I'd say it's okay to merge without trying it out locally, unless anyone really wants to 🙂  It's doing the same as the …

Fix Rpush app when creating Android notification

---

config/locales/views/dashboard/en.yml
config/locales/views/dashboard/fr.yml

Fixes an error shown when the article has one view
```
I18n::InvalidPluralizationData: translation data {:other=>"%{scale} views"} can not be used with :count => 1. key 'one' is missing.
```
Add key 'one' to both translation files for this key.
https://app.honeybadger.io/projects/66984/faults/82770707
#15069 
View the articles dashboard. If necessary set article view counter to 1. Confirm no error is raised.
None.

Add single view count translation

---

app/views/admin/creator_settings/_form.html.erb

This PR refactors the COC and TOS description on the Creator Settings form (per @anujbhavsar96's design feedback) by doing the following:
Relates to issue #15524 
_**or**_
```
```
I should have addressed any UI accessibility concerns in this PR!
_Will this PR …

Update the COC and TOS Description on the Creator Settings Form

---

config/locales/views/credits/en.yml
config/locales/views/credits/fr.yml

It's possible an organization or user will have just one credit.
When this happens, the translation will fail to render in the view
(and an error will be raised).
Add key "one:" for personal and organizational credits.
Follow on to #15544 (checking other locale files for missing translation keys turned up these two cases). 
Set user available credits to 1, I had 16 to spend so set to 1 by "spending" the others, removing them would also work:
```ruby
user.credits.drop(1).map {|c| c.update(spent: true) }
```
~View dashboard page (http://localhost:3000/dashboard) (this always says credits available, not localized)~
View credits page http://localhost:3000/credits/
No error raised.
On main branch this does cause an error:
None …

Add translations for one credit

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feeds.rb
app/services/articles/feeds/large_forem_experimental.rb
app/services/articles/feeds/weighted_query_strategy.rb
spec/requests/stories/feeds_spec.rb
spec/services/articles/feeds/weighted_query_strategy_spec.rb
spec/services/articles/feeds_spec.rb

Prior to this commit, I carried over (albeit imprecisely) logic from the
LargeForemExperimental.  That logic was to help limit articles to those
that were published since the user's latest page view.
However, I introduced a bug in this transcription.  Now both
LargeForemExperimental and WeightedQueryStrategy use the same logic to
determine the oldest publication date to search for in the feed.
This resolves a bug reported where users were not seeing a large number
of items in their feed.
Incidentally, if a forem has little activity in the 18 hours, there
might be very few items in the feed.
I believe, going forward, we may need to better parameterize how many
hours is considered "stale since last page view".
Related to #15240
None
None

Fixing weighted query hotness grab logic

---

app/models/reaction.rb

In #15412 I introduced faulty logic, and didn't reuse existing scopes.
For comparison, the original code for comment threshold checks was here:
https://github.com/forem/forem/blob/5d5dbaca95d1fa944a687e07709c530ed7cfbd62/app/models/comment.rb#L303
```ruby
Reaction.comment_vomits.where(reactable_id: user.comments.pluck(:id)).size > 2
```
This change restores that and tightens up the scope usage.
PR #15412
None
None

Fixing broken logic

---

app/views/admin/creator_settings/new.html.erb

This PR lessens the amount of space between the title and subtitle on the Creator Settings form per @anujbhavsar96's design feedback by removing the padding between both titles.
Relates to issue #15524 
_**or**_
```
```
Once on the Creator Settings page, you …

Update the Spacing Between the Title and Subtitle on the Creator Settings Form

---

app/views/admin/creator_settings/_form.html.erb

Gives the form more real estate. Previously radio button options were on separate lines. This came about while working on #15499 
```ruby
```
3. Click on the login link. Since the feature flag is enabled, you'll be redirected to Creator Signup Form.
4. Fill in the necessary information and submit the form.
5. On the next page ensure that the radio buttons for the sections "Who can join this community?" and "Who can view content in this community?" are on the same line.
N/A …

Now radio buttons in creator settings are on the same line in fieldsets

---

app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js

_I'm going to say upfront - this PR looks like it's huge, but that's really because we have a pretty big test suite covering all the formatters, and I had to change each test slightly_ 😄  
After adding the markdown toolbar to the V2 editor, some users mentioned that using the buttons and shortcuts "breaks" the undo queue - i.e. if you make something bold with our toolbar (or its keyboard shortcut), pressing `cmd/ctrl + z` would not undo it.
This PR refactors the approach to use `document.execCommand('insertText')` to update the text area content, which has the effect of adding that formatting edit to the undo queue.
I've noted both in the PR and the code comments, that this function is deprecated ([see the docs here](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)) …

markdown toolbar: refactor formatting insert to allow for undo queue

---

app/assets/stylesheets/ltags/GithubReadmeTag.scss
app/assets/stylesheets/ltags/GithubTag.scss
app/assets/stylesheets/ltags/TwitterTimelineTag.scss

Removed the z-index:1 from liquid tags present in 'GithubReadmeTag.scss', 'GithubTag.scss' and 'TwitterTimelineTag.scss'.
The removal of this eliminates the weird visibility issue when the article-show-more-dropdown overlaps the pretty embeds on the page.
Closes #15500 
Steps to test the changes:
1. Add a post with a pretty embed.
2. Click the 3-dots on the side to open the Show More drop-down.
3. Hover near the pretty embed.
4. No weird overlap happens between the drop-down and the pretty embed.
_Will this PR introduce a change that impacts …

Remove z-index from liquid tags

---

spec/system/articles/user_visits_articles_by_timeframe_spec.rb

Prior to this change, for each of the context's specs, we first visited
the /top/week path then in all but one case immediately visited another
path.
This created extra requests that weren't necessary.
Relates to #15292 and #15475
None, the tests should run just a bit faster.
None.

Refactoring spec

---

app/services/authentication/authenticator.rb
spec/services/authentication/authenticator_spec.rb

Closes https://github.com/forem/forem-passport/issues/44
When someone connects a new OAuth provider to an existing account we don't want to change their primary email. We also trust OAuth service providers to confirm their users' email accounts (prove ownership), so new account that come authenticated by an OAuth service provider should be trusted (no need to send an email to verify for ourselves).
https://github.com/forem/forem-passport/issues/44
1. Enable Email auth on your local environment
2. Enable Forem Passport auth on your local environment
3. Sign up to the local environment using an email address `whatever@email.com`
4. Connect the new account with a Forem passport account that uses a different email `whatever+test@email.com`
- The old adding a `+something` to the end of your …

Avoid email reassignment when connecting OAuth provider

---

app/views/admin/creator_settings/_form.html.erb

This PR removes the italics from the Community Name field per some feedback from @anujbhavsar96 and @ludwiczakpawel.
Relates to issue #15524 
_**or**_
```
```
Once on the Creator Settings page, you will want to test the changes outlined below:
N/A
_Will this …

Remove Italics from Community Name Field on Creator Settings Form

---

README.md

As discussed internally, this PR removes several badges from the top of our README, especially the ones that needed manual updates and tended to be out of date.
n/a
Here's the rich diff of the before and after:
None

Remove some README badges

---

app/views/credits/new.html.erb
spec/views/credits/new.html.erb_spec.rb

The internationalized string inside a javascript snippet in the view was not quoted, causing a parse error, and consequently causing the script (which controls the behavior of the two buttons on the form, enabling credit card management with stripe) not to function.
Quote the string, ensuring the script runs.
fixes #15454 
#15134 added the call to translation t() 
https://app.honeybadger.io/projects/66984/faults/65884099 
As a user, visit /credits/purchase.
If you don't have stripe configured (default) you can see this error in the console:
```
Uncaught IntegrationError: Please call Stripe() with your publishable key. You used an empty string.
```
If you see instead a parse error:
```
Uncaught SyntaxError: missing } after property list
```
Then this is not fixed.
None
_Will this PR …

quote localized strings in credits/purchase embedded script

---

app/controllers/admin/articles_controller.rb
app/controllers/articles_controller.rb
app/models/article.rb
app/services/article_api_index_service.rb
app/services/articles/feeds/find_featured_story.rb
app/services/email_digest_article_collector.rb
app/workers/reactions/bust_homepage_cache_worker.rb

In addition adding commentary on the oddly named
`Articles::Feeds::FindFeaturedStory` class given that it never filters
on "featured".
Related to #15292 and #15475
None
None

Extracting Article.featured scope

---

config/fastly/snippets/bad_bot_detection.vcl

I noticed a dramatic uptick in traffic to the `StoriesController#index` route on DEV at 40 minutes past the hour every single hour of the day like clockwork. Since preventing scraping is also something I've been working on with the community team (they get a _lot_ of complaints about plagiarism), I began investigating.
Turns out the vast majority of those requests are supplying a `User-Agent` header that is simply `Ruby`. So this PR blocks requests with that user agent, but since this is the default user agent string for `Net::HTTP` in the Ruby standard library, this PR only blocks them if they're not using the API (AFAIK, the only blessed path prefix for API clients). We couldn't block it by IP address because it was using a new IP (owned by Amazon) every time, as if a Lambda spins up …

Block more bots

---

app/models/user.rb
app/services/moderator/manage_activity_and_roles.rb
app/services/slack/messengers/comment_user_warned.rb
app/views/admin/users/edit.html.erb
spec/services/moderator/manage_activity_and_roles_spec.rb
spec/system/admin/admin_bans_or_warns_user_spec.rb

A simply refactor to introduce more idiomatic method names.
Related to #15624
None.
None.

Replacing `User#warned` with `User#warned?`

---

app/controllers/notifications_controller.rb
app/models/user.rb
config/initializers/doorkeeper.rb

Given that we have the roles of `:tech_admin`, `:admin`, and
`:super_admin`, I don't want the surprise of assuming that `user.admin?`
means that they have the role of `:admin`.
Related to #15624
None.
None.

Renaming method to reduce surprise

---

app/controllers/sidebars_controller.rb
app/controllers/stories/tagged_articles_controller.rb
app/controllers/stories_controller.rb
app/models/article.rb
app/services/article_api_index_service.rb

As I'm working on #15359 I wanted to favor using scopes over the raw
`where(approved: true)`.
Tangentially related to #15359.
None
None

Factoring code to define Article.approved

---

app/controllers/async_info_controller.rb
app/models/reaction.rb
app/models/response_template.rb
app/models/user.rb
app/services/mailchimp/bot.rb
app/services/moderator/manage_activity_and_roles.rb
app/services/re_captcha/check_enabled.rb
app/views/admin/users/edit.html.erb
app/views/users/_notifications.html.erb

`User#trusted?` is more Ruby idiomatic than `User#trusted`.  This helps
align the various "User#question?" methods.
I've added a deprecation warning, but don't believe that this is active
in the code-base.
Related, kind of sorta, to #15624.
None.
None.
not: The deprecation warning should be adequate.

Deprecating User#trusted in favor of User#trusted?

---

app/views/users/_notifications.html.erb

The Mobile section of the Notifications Settings page has had the 'beta' tag since...it's initial commit in 2018! Mobile notifications are definitely out of beta now, and we can remove this tag!
Before:
After:
appropriately. …

Remove beta tag from mobile notification settings

---

app/javascript/packs/onboardingRedirectCheck.jsx
app/views/admin/creator_settings/_form.html.erb

This PR ensures that both the COC and TOS links open in a new window, without any redirects, upon link click. To accomplish this, this PR does the following:
Closes issue #15546 
_**or**_
```
```
Once on the Creator Settings page, you will want to test the …

Ensure COC and TOS Links Open on the Creator Settings Form

---

spec/workers/follows/update_points_worker_spec.rb

Fixes a failure where the follow did not calculate implicit
points correctly.
The underlying issue was that the factory created `article` did not have
a cached_tags value containing `tag.name`
saved (`article.tags.pluck(:name)` was correct, but the cached_tags
was not). This happens automatically when saving an article from the
post editor, and any time we subsequently modify an article.
Supersedes #15456
```
bundle exec rspec spec/workers/follows/update_points_worker_spec.rb
```
None

Save article (to cache tags) before updating follow points

---

app/views/pages/_terms_text.html.erb

This PR replaces the hardcoded URL, `/privacy`, with the `app_url` path helper to keep things consistent between COC and TOS partials.
Relates to PR #15654 
To QA this PR, navigate to `/terms` and click on the "Privacy Policy" link and ensure that you are redirected to `/privacy` as expected:
Additionally, ensure that all checks pass. ♻️  
N/A
issue template …

Replaces Hardcoded URL with Path Helper in Terms Partial

---

app/services/articles/feeds/find_featured_story.rb
app/services/articles/feeds/weighted_query_strategy.rb
spec/services/articles/feeds/weighted_query_strategy_spec.rb
spec/services/articles/feeds_spec.rb

**Note: I am working on an internal retrospective regarding the discovery and impact of this bug.**
Prior to this fix, in the production rails console we ran the following:
```ruby
Articles::Feeds::WeightedQueryStrategy
.new(user: nil, page: 1, tags: nil)
.featured_story_and_default_home_feed(user_signed_in: false)
```
The result was: `[nil, []]`.  Which in the
[StoriesController#assign_feed_stories][1] is where we have the
following:
```ruby
@featured_story, @stories = feed
.featured_story_and_default_home_feed(
user_signed_in: user_signed_in?)
```
In Blazer, I ran the following query at 2021-12-02 Thu 20:41 EST:
```sql
SELECT * FROM articles
WHERE featured = true
AND published = true
AND published_at > (NOW() - interval '7 days')
AND published_at < NOW()
AND main_image IS NOT NULL
``` …

Fixing blank home page for anonymous/visitor

---

scripts/release

If you run `curl -s https://demo.forem.com/api/instance | jq '.version'`, you'll see a newline in the result:
```js
"stable.20211129.1\n"
```
That newline _shouldn't_ hurt anything but better to be strict about what we emit, so since the newline isn't a part of the version tag it shouldn't be in the string.
We also didn't need to shell out to the `echo` command for this. I don't know why I did that in the script to begin with.
[Changes …

Don't write a \n at the end of the release version

---

app/controllers/credits_controller.rb
app/services/payments/process_credit_purchase.rb
config/locales/services/payments/en.yml
config/locales/services/payments/fr.yml
spec/services/payments/process_credit_purchase_spec.rb

This prevents sending an empty card to stripe (and raising an error in the `find_or_create_card` method when providing an empty selected card to the Payments::Customer.get_source (which is resulting in a 500 error being returned from the credits purchase page).
This does not prevent submission, but handles submission by setting appropriate user facing error messages rather than raising an unhandled error when selected card is nil.
#15454 (I still think disabling the button in the frontend is a better experience)
Visit /credits/purchase
Select 1 credit (you won't have any card selected locally since stripe isn't connecting)
Complete purchase.
An error should be shown and you should be returned to the purchase page 
```
Please select a payment method
```
Because this adds translation keys, …

Validate payment info present before attempting to process

---

app/workers/follows/update_points_worker.rb

This is a follow on to #15456 and #15637
Saving the article in #15637 was a work-around to force the article to
have a valid cached tag list (would reload have worked just as well?). 
Update the worker to use tag_list (rather than the decorator's
cached_tag_list.array) and flatten the tag list rather than flat
mapping String#split over the non-nil cached_tag_lists.
https://github.com/forem/forem/pull/15456#discussion_r754649095 @atsmith813 I believe suggested this change (rather than the change to Article forcing the cache to update), if we can rely on tag_list always to be correct and cached_tag_list appears to be an implementation detail. I don't know if it makes sense in the decorator to continue splitting the cached tags list into any array (as a presentation concern), this changes a …

Use the tag_list method, rather than the cached_tag_list attribute

---

spec/requests/stories_index_spec.rb

I think this is related to some requests triggering the weighted query
field test (which changes the rules for the home feed in a way that
may include these campaign tags and handles relevancy differently from
the scoring), for home page requests where the user is not signed in. 
Signing in and calling GET "/" restores the expected behavior, and the user has original feed strategy set.
```ruby
[7] pry(#<RSpec::ExampleGroups::StoriesIndex::GETStoriesIndex::WithCampaignSidebar>)> get "/"
=> 200                                                                         
[8] pry(#<RSpec::ExampleGroups::StoriesIndex::GETStoriesIndex::WithCampaignSidebar>)> response.body.include?("Unapproved-post")
=> true               
[9] pry(#<RSpec::ExampleGroups::StoriesIndex::GETStoriesIndex::WithCampaignSid …
```

Disable failing test cases

---

config/routes.rb
config/routes/admin.rb

These are administrative engines, and should be mounted within the
`/admin` path.
In a vague way #15640.
Goto:
* `/abtests`, you should get a 404 error.
* `/admin/abtests`, you should see the abtests currently running
* `/sidekiq`, you should get a 404 error.
* `/admin/sidekiq`, you should see the sidekiq queue.
None.
0

Moving engine mount points to admin

---

Containerfile

Currently we have a FROM at the top of the dockerfile (normal, what you would be looking for if you'd seen a dockerfile before) and a nearly identical FROM line half way down, when, having built the builder for the testing image, we build fresh, from the same base image for production. 
I'm naming the common base image `base` and changing the two FROM lines to use it (FROM base). This prevents missing the second (and needless?) `FROM ruby:... as production` line farther down. 
I think I've tripped over this twice already. The next time someone changes the ruby  version tag on the base image, they'll only need to do it once (and maybe in the .ruby-version file, but who's counting).
If buildkite succeeds that's probably the most important thing. Local confirmation can be done via
```
docker …
```

Specify a single base image for builder and production

---

app/models/organization.rb
app/models/page.rb
app/models/podcast.rb
app/models/user.rb
app/validators/unique_cross_model_slug_validator.rb
spec/validators/unique_cross_model_slug_validator_spec.rb

Prior to this commit, we had somewhat duplicated logic across four
models.  In adding this validator we're consolidating the logic and
tidying up each of the other models; letting the validator know which
models are part of the "uniqueness gang."
I made the decision to include the test for `sitemap-` as this was
partially applied to two of the models.
None.
None, though please read through my logic.
None.

Extracting cross-model uniqueness validator

---

app/javascript/admin/controllers/creator_settings_controller.js

There was an issue with the logo preview resizing algorithm.
#15499
```ruby
```
3. Click on the login link. Since the feature flag is enabled, you'll be redirected to Creator Signup Form.
4. Fill in the necessary information and submit the form.
5. On the next page select an image for the logo.
6. The preview of the logo should no longer be skewed. You can test this with the CodeNewbie logo below.
N/A
_Will this PR introduce a change that impacts Forem members or creators, …

Creator Settings: Fixed the resizing of the preview logo

---

app/views/users/_account.html.erb

Rails was escaping the HTML `<time>` tag
This PR tells Rails not to do that:
appropriately.

Fix markup for API key metadata

---

app/queries/admin/moderators_query.rb

While in it's own namespace, the `VALID_ROLES` constant is used
throughout the Policies and Liquid Tags to reflect permissions.  In this
case, the constant is not related to granting permissions but to see who
has these roles.
Only loosely related to [Analysis and remediation [likely] required for creating a Role system · Issue #15624 · forem/forem](https://github.com/forem/forem/issues/15624)
None.
None.

Renaming constant to reflect intention

---

config/fastly/snippets/bad_bot_detection.vcl

I used the wrong VCL property in #15626. It's [`req.url`](https://developer.fastly.com/reference/vcl/variables/client-request/req-url/), not `req.http.url`. This bug led to [some bugs with legit Ruby clients](https://github.com/orbit-love/community-ruby-dev-orbit/issues/22) that didn't explicitly set a `User-Agent` header. That VCL rule was intended to let those clients continue to come in through the front door (the API, a well defined and regulated HTTP entrypoint), but I think my monkey brain got hypnotized by all the `req.http` in the file while writing that rule and ended up writing it again.
- #15626 
This can only be QAed on a Fastly-fronted Forem instance, so we'll just test in production:
```
curl https://dev.to/api/articles -H 'User-Agent: Ruby'
```
… should return `HTTP 200` …

Fix Fastly bot block for Ruby `Net::HTTP` clients

---

Gemfile

Don't require view_component/engine in the gemfile. Let it load automatically.
fixes #15689
Startup should not include a deprecation warning about requiring the engine (was first two lines when running `rails s` or rake tasks, indicating application.rb:20 as the source).
Expected/desired output:
```
djuber@forem:~/src/forem$ bundle exec rails s
=> Booting Puma
```
View components (at http://localhost:3000/admin/users/1 or http://localhost:3000/admin/users/1/tools or http://localhost:3000/admin/users/1/tools/emails) should still render correctly (the tools and tools/emails components are raw forms and exclude most styling, they are intended to be embedded in the parent view at /admin/users/:user_id). 
None …

Remove manual require of view_component from gemfile

---

spec/requests/stories_index_spec.rb

Remove one example that was overspecifying the context (stories index when a campaign is active). 
We're revisiting the behavior of the feed scoring, and the selection
of articles will be independent of the article's score in some cases.
This test was nested within a group related to active campaigns, but
the minimum score is a user experience setting (so if we want to test
for that it should happen outside the context), and minimum article
score will not be a reliable criterion for filtering the home
feed in the future (and was failing based on the feed strategy experiment).
Remove this example (it was already skipped), as it adds little value, 
and is at a minimum misplaced (wrong surrounding context), 
at worst it's wrong or likely to be wrong soon. …

Don't test for article score filtering in home feed

---

app/models/settings/authentication.rb
spec/models/settings/authentication_spec.rb

When blocking domain `hello.com` we want to block subdomains as well (e.g. `world.hello.com`) but not different domains (e.g. `hello-world.com`).
Closes #15714
None.
None.

Blocking subdomains of domains marked as spam

---

app/assets/stylesheets/setup-mode.scss

This PR adjusts the spacing beneath the logo upload field on the Creator Settings page so that the spacing beneath the field is more in line with the spacing on the rest of the page. To accomplish this, this PR removes `height` from `setup-mode.scss`.
Relates to issue #15524 
_**or**_
```
```
Now, run your server and navigate to `http://localhost:3000/` and complete the "Create Account" form. After completing the "Create Account" form, you should be brought to the new Creator Setup page, …

Adjust Spacing Beneath Logo Upload Field on the Creator Settings Page

---

app/services/feeds/assemble_article_markdown.rb
spec/services/feeds/assemble_article_markdown_spec.rb

When we get image links with local, absolute paths (like `<img src="/path/to/image.png">`) we're using the `@feed.url` to find the base url to attach that path to. However, the source of `@feed.url` makes some assumptions about the meaning and content of `<link>` tags in the feed that don't necessarily apply to atom feeds.
Looking at https://developeronfire.com/rss.xml (a podcast rss feed) it's clear the last link (not the two atom10:link's but the unadorned rss `<link>`) could point to a base path for the items, but there's no reason to believe that this is true generally (that the blog post index is not on /blog/, which breaks our assumptions about the way to build absolute paths from relative ones).
For rss, https://web.resource.org/rss/1.0/spec#s5.3.2 the url should be an html …

Use the rss item's url when handling relative image links 

---

lib/data_update_scripts/20211115154021_nullify_invalid_tag_fields.rb
spec/lib/data_update_scripts/nullify_invalid_tag_fields_spec.rb

The data update script "nullify empty tag colors" failed to update
because of the way it was written - in two passes, updating the
background color for tags where the background color was empty, then
updating the foreground color for tags where the foreground color was
empty.
Because both attributes have a validation regex, neither pass updated
any tags (the problematic cases observed had empty string values in both
columns).
Perform in a single loop, over the union of the two sets (expected to
include only the same rows as before), an update for both columns at
once.
Additionally, use update_columns which bypasses _other_ validation
issues (the only one I could suspect is the alias_for check).
Nullify empty strings in alias_for (simplifies a few things, now it's
either valid or null). …

Revisit tag validation script

---

app/models/user.rb
spec/services/users/update_spec.rb

Removed updating user's articles' path and resaving articles in a `before_validation` callback `check_for_username_change`.
When updating via `Users::Update`, the articles will be resaved and the path will be updated in the `Article#set_cache` callback.
Concerns:
When a user is updated without using `Users::Update` service, the articles won't be resaved. Currently, we only update via `user.update` when requesting export and updating user's payment pointer. 
I consider moving the logic related to setting `old_username` and `old_old_username` from the callback to the `Users::Update` service in one of the next prs. 
#15424
When a user changes their username from `/settings/profile`, their articles' URLs should be updated to contain the new username. (the logic wasn't changed)
_Will this PR …

Removed resaving users' articles in a before_validation callback

---

app/views/admin/creator_settings/_form.html.erb
app/views/admin/creator_settings/new.html.erb

This PR adjusts the width of the "Community Name" field, the "Finish" button, and the "Brand Color
field on the Creator Settings form so that both fields are now the same size as the color selector field, creating more of a "block" feel to the form.
For more information on why this change is being made, please refer to the design critique in the issue referenced below.
Closes issue #15524 
_**or**_
```
```
Now, run your server and navigate to `http://localhost:3000/` and complete the "Create Account" form. After …

Adjust Creator Settings Form Width

---

app/models/reaction.rb
app/models/user.rb
app/services/users/delete_activity.rb
lib/data_update_scripts/20211209213849_remove_dangling_user_reactions.rb
spec/factories/reactions.rb
spec/lib/data_update_scripts/remove_dangling_user_reactions_spec.rb
spec/services/users/delete_spec.rb

When a moderator has reacted _to_ a user, and the user is deleted, remove the (now unneeded) reaction.
We had been removing the user's reactions (created by the user, not applying to the user) already.
Fixes #15245, when combined with a data update script.
Flag a user. Delete the flagged user. Visit http://localhost:3000/admin/moderation/privileged_reactions
(this had been "hidden" already by [another PR](https://github.com/forem/forem/pull/15249) so no error is expected in main either)
Ideally the added test case is sufficient demonstration.
None

Remove reactions to a user when deleting the user

---

app/assets/javascripts/base.js.erb

`MtPopUpList is not defined` is one of the most frequent error ([over 100k](https://app.honeybadger.io/projects/67192/faults?sort=last_seen_desc&q=-is%3Aresolved%E2%80%81-is%3Aignored%E2%80%81MtPopUpList+is+not+defined)) caught by Honeybadger. I, for the life of me, could not reproduce it or trigger locally via Firefox or Chrome. I double-checked with @nickytonline and we are quite certain it's not part of our codebase but potentially a ad-block plugin. This PR is going to mute that by following the [guide provided by Honeybadger](https://docs.honeybadger.io/lib/javascript/guides/reducing-noise/).
n/a
Let's test on production!

Ignore MtPopUpList on Honeybadger

---

cypress/integration/seededFlows/mobileFlows/namespacedForemMobile.spec.js
cypress/support/commands.js

The forem mobile cypress test is sometimes failing due to userData not being ready (base data request has not returned a response before we check the content, leading to attribute errors on `undefined`).
The [`loginAndVisit(url)`](https://github.com/forem/forem/blob/main/cypress/support/commands.js#L40-L49) command would _normally_ be used for this, but doesn't accept an option argument to pass to the [visitAndWaitForUserSideEffects](https://github.com/forem/forem/blob/main/cypress/support/commands.js#L51-L65) (which does take an option arg, required to stub out the user agent in the request for this test).
The visitAndWaitForUserSideEffects command relies on a utility to intercept the pending user requests, but assumes the user is logged in (and always passes true to this utility method, …

Wait for async data in forem mobile cypress test

---

spec/forms/creator_settings_form_spec.rb
spec/system/admin/admin_creates_new_page_spec.rb

Running the admin creates new page spec after the creator settings form spec had updated settings was triggering a test failure (`community_name` in the response didn't match the one in the test runner).
Clear the cached settings after updating them.
The sequence of spec files:
```
bundle exec rspec spec/forms/creator_settings_form_spec.rb spec/system/admin/admin_creates_new_page_spec.rb 
```
should pass. 
None, test only change.

Clear changes to settings after checking form saves them
