forem/forem

config/initializers/honeybadger.rb
spec/initializers/honeybadger_spec.rb

In https://github.com/forem/forem/pull/12338 we introduced a regression that reverted the list of required exceptions to ignore.
https://github.com/forem/forem/pull/12338
shared_

Fix regression in Honeybadger.config.exceptions.ignore

---

docs/api_v0.yml

Our API documentation's example should be usable as they are as much as possible. Unfortunately `canonical_url` needs to be unique over *all* the articles, so it can result in a `HTTP 422` error from the get go which is not a super awesome developer experience. 
Given that, and since `canonical_url`, is an optional field, I decided to remove it altogether from the examples.
Closes https://github.com/forem/forem/issues/12712
1. `yarn api-docs:serve`
2. open http://127.0.0.1:8080
3. check that the examples on the right sidebar in `Create a new article`  and `Update an article` don't contain `canonical_url` …

Remove canonical_url from API Article Create/Update examples

---

app/javascript/.eslintrc.js
app/javascript/.storybook/main.js
config/webpack/environment.js
docs/frontend/webpacker.md
jest.config.js
jsconfig.json

Adding the webpack alias `@shared` like our other existing aliases, e.g. `@utilities`, allows us to avoid writing imports like this
`import { useMediaQuery } from '@shared/useMediaQuery'`
instead of something like this.
`import { useMediaQuery } from '../../shared/components/useMediaQuery'`
This is some pre-work for #12755
N/A Code that will use this is not part of the PR, so nothing to test aside from the PR going green.
N/A
or in a …

Added the @shared webpack alias to the project

---

app/controllers/users_controller.rb
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/components/ProfileForm.jsx
app/javascript/onboarding/components/ProfileForm/TextInput.jsx
app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
spec/requests/users_onboarding_spec.rb

This change will allow a new user to change their username in onboarding.
Solves RFC: https://github.com/forem/rfcs/pull/47
Onboarding with OAuth: https://www.loom.com/share/0c9e4dd792544264bfc11140d339bd04
Onboarding with Email: https://www.loom.com/share/7a64332c27244de4b345b09f7c3e0662
When the username is unavailable:
When the username is invalid:
There might be some opportunity to add front-end validation here, but the way we submit this form is a little odd so I'd have to play around with it a bit to figure out exactly how that should be done. For now, I think the backend validation is sufficient and the user doesn't lose anything from the form if the username fails validation so the UX isn't too bad imo. …

Add username to onboarding

---

.vscode/extensions.json

Adds a popular [MDX VS Code extension](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx) to the project for folks who use VS Code. This helps viewing and syntax highlighting for MDX files in Storybook.
N/A
N/A

Added the MDX extension for VS Code.

---

app/services/search/user.rb
app/views/service_worker/index.js.erb
spec/requests/search_spec.rb
spec/services/search/user_spec.rb

Make sure all the data is returned so we can properly complete [the autocomplete mention RFC](https://github.com/forem/rfcs/pull/16)
https://github.com/forem/rfcs/pull/16
Hit the `/search/usernames` endpoint and confirm it returns an array of hashes with username, name, and profile picture.

Return Additional Data Needed for Autocomplete

---

app/javascript/.storybook/main.js

This is pre-work for the @ mention autocomplete RFC. It adds React aliases to the Storybook webpack configuration. This is required because we are using [Reach UI](https://reach.tech)'s [ComboBox component](https://reach.tech/combobox/), a 3rd party package for the autocomplete component.
N/A This is frontend indfrastructure changes.
N/A
replace this line with details on why this change doesn't need …

Added react aliases in Storybook webpack configuration

---

app/views/pages/robots.text.erb

Update Robot.text to keep crawlers off our search path
n/a
n/a
n/a
n/a

Add search/feed_content to robots.text

---

spec/system/user/view_user_index_spec.rb

This spec is flakey. There are a couple of ways to solve this quickly:
1) ~Just test for the CSS and don't worry about the timestamp accuracy (we could just delete the test as other tests check for the presence of the timestamp's parent element.~
2) We can test the timestamp against a regex and not worry about the accuracy of the timestamp, just to be sure *some* timestamp shows up.
3) ~Verify that the timestamp is rendered and matches at least the same day as we expect it to be -- which should give us a little confidence, but not be as flaky.~
After getting some feedback from Molly, I went the regex direction! :capital_abcd: 
development process, or any of our internal teams? If so, …

Fix flaky comment timestamp spec

---

app/controllers/application_controller.rb

By moving `controller_name` to be a tag, it's easier to build monitors tracking this specific metric.
See also https://docs.datadoghq.com/dashboards/faq/when-i-query-can-i-use-wildcards-in-metric-names-and-events/
shout out to @maestromac!
https://docs.datadoghq.com/dashboards/faq/when-i-query-can-i-use-wildcards-in-metric-names-and-events/

Improve ActionController::InvalidAuthenticityToken error handling

---

config/routes.rb

This is part of a [bigger endeavour](https://github.com/forem/rfcs/pull/50) to restructure admin routes and navigation. 
In this PR, I set the foundation by grouping the routes under the `:admin` namespace as follows; 
- At the top I've grouped the routes that will most likely remain as is  (this may change as I start exploring more)   
- Thereafter, I've grouped existing routes that will be replaced by new ones. I've added a comment to indicate that I will be deleting those routes
- Finally, I've grouped the newly scoped routes under a feature flag "admin_restructure". You can find a table of these new routes [here](https://github.com/forem/rfcs/blob/aefc141f386b395cc12d4b9f56816f1de4702eab/text/0050-update-admin-ia-nav.md#3-move-existing-content-into-new-location)
Please note that the …

RFC#50-P1 Restructuring some routes and adding a feature flag

---

app/views/admin/shared/_navbar.html.erb
app/views/layouts/admin.html.erb

I added a bug in #12726 :see_no_evil: 
This gets rid of that bug!
Before:
After:

Fix double render of Overview in admin navbar

---

app/assets/stylesheets/base/helpers.scss

This CSS class isn't used anywhere AFAICT.

Remove unused CSS

---

db/seeds.rb

Noticed that we are setting this even though I don't believe it is still necessary. `super_admin`s can make changes to the site config without this role.
Separate PR from #12858 because we might choose to merge one and not the other. (Maybe? idk) …

Remove single resource admin config from seed data

---

docs/getting-started/committing.md

Update link to rubocop.yml in Thoughtbot's repo
https://github.com/forem/forem/issues/12875
Can check locally using `gitbook serve` or generated preview at https://deploy-preview-12876--docsdevto.netlify.app/getting-started/committing/.
None

Update style guide link

---

app/assets/stylesheets/ltags/TweetTag.scss

Fix the Twitter "engagement" icons and avatar
#12884
1. Visit a post with Twitter liquid tag.
No
shared_

Fix twitter liquid tag buttons misaligned

---

app/lib/forem_stats_drivers/datadog_driver.rb

This commit adds extra telemetry in Datadog for:
- Redis
- We make 3 different Redis connections available, so this change
shows us _which_ Redis instance a given query goes to
- Split HTTP requests by domain using:
- net/http - default for Ruby
- faraday - used by:
- buffer
- elasticsearch
- gibbon
- oauth2
- octokit
- sawyer
- twilio
- excon - used by:
- fog
- AWS
- RestClient
- Cloudinary
- Pusher
- concurrent-ruby
- ActiveSupport
- brpoplpush-redis_script
- i18n
- sidekiq-unique-jobs
- sprockets (do we even use this?)
This gives us more insight into the details, which is awesome for debugging
_If your PR includes UI changes, please replace this line with details on …

Expand Datadog instrumentation

---

app/lib/forem_stats_drivers/datadog_driver.rb

Splitting by domain caused an explosion in "services" tracked in Datadog
because it was counting each podcast platform and each blog as being
another service. Noramlly this would be what we want, but that's a lot
to ask for such a broad range of user-supplied domains.
Since each of these requests is made via HTTParty, which uses `Net::HTTP`
by default, this commit stops splitting in that library.
We'll need to come up with a better way of tracking this. …

Mitigate service explosion in Datadog

---

app/models/article.rb
spec/models/article_spec.rb

When https://github.com/forem/forem/pull/11268 we didn't test it thoroughly and
thus didn't detect that it wasn't working correctly and that it
resulted in an empty string in the `<description>` field.
*After a conversation in https://github.com/forem/forem/pull/11268#issuecomment-791109532 we decided to keep the code close to `.processed_html` until we do a bigger refactor.*
Closes https://github.com/forem/forem/issues/12921
- https://github.com/forem/forem/pull/11268
- https://github.com/forem/forem/issues/10927
1. start the server
2. go to http://localhost:3000/feed
3. make sure the `<description>` tag is not empty
development process, or any of our internal teams? If so, please note …

[Hotfix] Restore article content in RSS feed

---

README.md

Add my dev.to account to the readme.
None
None

Add myself as a core contributor in the readme

---

docs/frontend/styles.md

Adding note about Crayon to forem docs
N/A
1. Run documentation locally by running `yarn gitdocs serve`
2. Visit http://localhost:8000/frontend/styles/
N/A
shared_

Adding note about crayons design system in forem docs

---

README.md

Removed Katie and added Jamie
H/T to @djuber with [his PR](https://github.com/forem/forem/pull/12950)

Update README core team

---

app/views/service_worker/index.js.erb

The problem and fix are detailed [in this comment](https://github.com/forem/forem/issues/12899#issuecomment-794026586)
Closes #12899
1. Try to authenticate to https://dev.to or https://community.benhalpern.com using Apple Auth in Chrome/Firefox (should fail)
1. Try to authenticate to https://fdoxyz.ngrok.io using Apple Auth in Chrome/Firefox (should succeed)
None
None

Add exceptions to service worker navigation preload

---

app/controllers/api/v0/articles_controller.rb
app/controllers/articles_controller.rb
app/services/articles/attributes.rb
app/services/articles/updater.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/articles/articles_update_spec.rb
spec/services/articles/attributes_spec.rb
spec/services/articles/updater_spec.rb

Made changes to `Articles::Updater` in `ArticlesController#update` (not only in `Api::V0::ArticlesController#update`) to avoid duplicating logic
#3811 

Articles update refactoring

---

app/views/admin/overview/index.html.erb

Make small UI fixes of "Overview" section within Admin Portal by optimizing spacing. Note: this is not yet optimized for mobile viewport; that will be handled in a different time.
- Original RFC: https://github.com/forem/rfcs/pull/39 …

Improve UI design through small spacing tweaks

---

app/views/service_worker/index.js.erb

The service worker seems to be intercepting some pages that have forms. Those forms contain an authenticity token that is no longer valid causing CSRF exceptions, most notably in the sign in with OAuth providers
Closes #12969

Adds more exceptions to SW paths

---

.env_sample

This is only useful in production, but helpful to see there is such an
environment variable needed.
Closes #12977
Add a placeholder value for the production-only environment variable `SENDGRID_API_KEY`. This is only used in [config/environments/production.rb](https://github.com/forem/forem/blob/master/config/environments/production.rb#L127-L135) for outbound mail in production mode (so is less useful for setting up a local development environment, but serves as a useful hint to anyone setting up a self-hosted instance.
https://github.com/forem/forem/issues/12977
https://forem.dev/alvarolab/email-sending-is-not-working-1038
Since the sample env file is not inline with any of the code (it's a template used during setup to create a .env file or build out the expected environment variables) …

Add SENDGRID_API_KEY to .env_sample

---

app/javascript/.eslintrc.js

Turned off the deprecated jsx-a11y rule [no-onchange](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md) as per @aitchiss' comment https://github.com/forem/forem/pull/12755#discussion_r593252034.
#12755 
N/A. This is a front-end tooling change. Nothing to test.
N/A
shared_

Turned off the deprecated no-onchange rule of the jsx-a11y eslint plugin.

---

app/controllers/devices_controller.rb
spec/requests/devices_spec.rb

Argh: I got a little excited and merged https://github.com/forem/forem/pull/12419 before pushing my local copy of a test for `DevicesController` 🤦🏻

Add test for DevicesController

---

app/services/images/optimizer.rb

Resolves https://github.com/forem/forem/issues/12987
n/a

Nullify fetch_format for Imgproxy

---

app/assets/stylesheets/ltags/GithubTag.scss
app/views/liquids/_github_issue.html.erb

Update github issue/pull request liquid tag styles to display better on comments and posts descriptions
Closes #12569  …

Fix github issue liquid tag styles

---

bin/setup

Since the Rpush gem was added in PR https://github.com/forem/forem/pull/12419, it's prompting users to run a post install command upon being first installed by bundler: `When upgrading, don't forget to run `bundle exec rpush init` to get all the latest migrations.` While this message is meant to help users, it's actually detrimental for us: we are using Redis as a storage backend for Rpush, so there aren't any migrations that will ever need to be run. Rpush's `init` command is smart enough not to run migrations if it's not configured for ActiveRecord, but this message could still be confusing for users.
The preferred way to silence post install messages from gems is via bundler's `.config` file, however the guidance from the Bundler team is not to check this file into source control (to …

Configure bundler to ignore Rpush install message

---

app/assets/stylesheets/ltags/GithubReadmeTag.scss

The image and text are messed up.
#12772
1. Visit a post with a github liquid tag.
Nope
shared_

Fix github readme liquid tag

---

.eslintrc.js
app/javascript/admin/controllers/ahoy_controller.js
app/javascript/admin/controllers/article_controller.js
app/javascript/admin/controllers/buffer_controller.js
app/javascript/admin/controllers/config_controller.js
app/javascript/admin/controllers/data_update_script_controller.js
app/javascript/admin/controllers/image_upload_controller.js
app/javascript/admin/controllers/modal_controller.js
app/javascript/admin/controllers/reaction_controller.js

Removes the "no default exports" eslint rule on Storybook files and Stimulus controllers. I came across this while testing #12980.
#13031
N/A
N/A

Disabled 'no default exports' rule for Storybook files and Stimulus controllers 

---

app/javascript/article-form/components/Options.jsx

Noticed this `<select>` wasn't styled.
Before:
After:

Add missing CSS class

---

package.json
yarn.lock

The `start-server-and-test` npm package is no longer used. I had used it initially when setting up Cypress in the project, but in the end we opted for the `cypress-rails` gem to handle starting the Cypress test server.
#382
N/A. This removes testing tooling.
N/A. This removes testing tooling.
shared_

Removed the start-server-and-test npm package as it's no longer used

---

app/models/user.rb
spec/services/users/delete_spec.rb

If a user has a sponsorship, we're unable to delete them.
#13099 
Covered in added spec.
Current failure mode:
```
djuber@forem:~/src/forem$ bundle exec rspec spec/services/users/delete_spec.rb:24
Run options: include {:locations=>{"./spec/services/users/delete_spec.rb"=>[24]}}
[Zonebie] Setting timezone: ZONEBIE_TZ="Ljubljana"
F
Failures:
1) Users::Delete deletes user's sponsorships
Failure/Error: user.destroy
ActiveRecord::InvalidForeignKey:
PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_b3190c5fc6" on table "sponsorships"
DETAIL:  Key (id)=(1) is still referenced from table "sponsorships".
Finished in 1.65 seconds (files took 7.87 seconds to load)
1 example, 1 failure
Failed examples:
rspec …
```

Destroy user's sponsorships when destroying the user

---

db/migrate/20210323190443_add_indexes_to_old_usernames.rb
db/schema.rb

We have an index for `username` and for `old_old_username`, but not the one in between.
Querying for users on old usernames is the top query on DEV by total time spent, according to Datadog. A quick experiment showed that this query goes from a 400ms floor to a 7ms ceiling.
shared_

Add an index to users.old_username

---

app/javascript/.eslintrc.js
app/javascript/admin/controllers/ahoy_controller.js
app/javascript/admin/controllers/data_update_script_controller.js
app/javascript/admin/controllers/image_upload_controller.js
app/javascript/chat/chat.jsx
app/javascript/packs/dashboardTagsDisableUnchangedButtons.js
app/javascript/shared/components/useKeyboardShortcuts.js
app/javascript/topNavigation/utilities.js
app/javascript/utilities/codeFullscreenModeSwitcher.js
cypress/.eslintrc.js

Adds the [prefer-const] eslint rule. On the front-end, we prefer this over `let`, so this enforces it.
Several PRs have mentioned this before, but here is the latest, https://github.com/forem/forem/pull/13026#discussion_r599411359
N/A This is front-end infrastructure
N/A This is front-end infrastructure

[15 Minute Fix] Added the prefer-const eslint rule

---

app/views/collections/index.html.erb
app/views/dashboards/followers.html.erb
app/views/dashboards/following_organizations.html.erb
app/views/dashboards/following_podcasts.html.erb
app/views/dashboards/following_tags.html.erb
app/views/dashboards/following_users.html.erb
app/views/dashboards/show.html.erb
app/views/listings/dashboard.html.erb

This adds the "Skip to content" functionality to the dashboard pages so that users navigating by keyboard can go directly to the main content without tabbing through menu elements etc. Pages affected:
- `/dashboard`
- `/<user>/series`
- `/dashboard/user_followers`
- `/dashboard/following_tags`
- `/dashboard/following_users`
- `/dashboard/following_organizations`
- `/dashboard/following_podcasts`
- `/listings/dashboard`
NB: In the current implementation, the skip link is only the first focusable element **on a fresh page load** and not on internal navigation. At the moment, if you navigate from the main dashboard to another of the dashboard pages, the first focusable element will be after the header bar.
As part of #1153 we will want to change that, but I think it should be completed last, …

Add skip link functionality to dashboard pages

---

app/controllers/admin/pages_controller.rb

While working on a task related to Pages, I noticed that there was no indication that my pages had been created, updated, or deleted. This PR adds `flash` messages to indicate to Forem Admins that a page has been successfully updated, created, and deleted. Additionally, this PR adjusts the `#destroy` action to use to the path helper, `admin_pages_path` when redirecting to keep the code consistent.
Relates to [RFC 74](https://github.com/forem/rfcs/pull/74)
**To QA this PR, please first ensure that you have admin-based privileges, then do the following:**
- Navigate to `/admin/pages` and create a new page. Observe the successful `flash` message indicating that the creation of the page has been successful:
- Navigate to `/admin/pages` and edit an existing page. Observe the successful `flash` …

[15-Minute Fix] Adds Flash Messages to Indicate Successful Actions for Pages

---

app/javascript/Search/Search.jsx

Search can currently be triggered by / or ? because they share the same key `code` on event, to fix this I'm using the event's `key` instead
Original PR #10468
Go to a Forem and press / search will be selected,
Click off it and press ? nothing will happen.
N/A
N/A

Shortcuts: Fix search confusion

---

db/migrate/20210325183834_add_landing_page_to_pages.rb
db/schema.rb

This is the first PR of a two to three PR part project. This PR adds a `landing_page` boolean to the `pages` table in preparation for the work that needs to be done for custom landing pages (please see [RFC 74](https://github.com/forem/rfcs/pull/74) for further context!).
Relates to [RFC 74](https://github.com/forem/rfcs/pull/74)
Ensure that all builds pass! ✅ 
None!
None!

RFC #74, Pt.1: Add landing_page to the Pages Table

---

app/models/article.rb
app/models/listing.rb
app/models/tag.rb

I probably should have removed these in the previous PR (#13104) where the Buffer columns and table were removed, but better late than never.
forem/internalEngineering#397
n/a
n/a

Remove ignored Buffer columns

---

datadog/prerun.sh

We currently don't report instrumentation for Heroku scheduler dynos, but we need them for #13153 to work.
#13153 
https://github.com/forem/internalEngineering/issues/274
shared_

Enable instrumentation for Heroku scheduler

---

cypress/support/commands.js
docs/tests/e2e-tests.md

Adds a Cypress custom command for creating canned responses.
#13149
N/A  This is testing infrastructure
N/A  This is testing infrastructure.
shared_

[15 Min Fix] Added the custom Cypress command, createResponseTemplate, to create comment templates.

---

cypress/integration/articleFlows/commentOnArticle.spec.js

Temporary skip a flaky spec.
n/a

Skip a flaky e2e spec

---

app/views/notifications/_badgeachievement.html.erb

https://github.com/forem/forem/pull/13145 was deployed 8 hours ago, and this morning I noticed some new honeybadger errors related to recent changes from that PR. 
This PR fixes those errors by adding a presence check to make sure we aren't calling `zero?` on something that is `nil`. 
Fixes https://app.honeybadger.io/projects/72638/faults/78624140.
Follow up fix to https://github.com/forem/forem/pull/13145
Check that you can render the `app/views/notifications/_badgeachievement.html.erb` view without running into a `ActionView::Template::Error: undefined method zero?' for nil:NilClass` error
_None!_ …

[15 Min Fix]: Fix template error in badge achievement notification view

---

docs/technical-overview/stack.md

Noticed while working on something else that were still had some deprecated technologies in our tech overview docs so I removed them.

Doc Update: Remove no longer used tech from overview docs ✂️ ✂️ ✂️ 

---

app/services/email_digest_article_collector.rb

In this trace, the current live implementation yields the wrong tags. I used the tag format for Datadog's statsd metrics (it's honestly kinda silly that APM and metrics use different formats). Notice the `user_id` tag here contains the value inside the key:
shared_

Fix `user_id` tag in EmailDigestArticleCollector traces

---

docs/backend/roles.md

Michael mentioned we shouldn't be using the `has_role? :whatever` syntax in the codebase, so it makes sense not to do it in the docs either!

Make docs reflect code more accurately

---

app/services/article_api_index_service.rb
config/routes.rb
docs/api_v0.yml
spec/requests/api/v0/articles_spec.rb

This PR adds a way to get ~the most recent articles from the API~ articles sorted by published_at from the API. I'm adding it so that we can use it on a small tool I made for the community success team ([more info](https://forem.team/peter/dashboard-to-monitor-all-posts-across-all-forem-cloud-forems-ojn)). …

Add endpoint for articles sorted by published date

---

app/assets/stylesheets/components/buttons.scss

When looking at the dashboard view on my phone (360 * 800), I noticed that articles with longer titles would cause the text in these anchors to start wrapping. Adding this CSS property to the `.crayons-btn` class fixes the issue.
I'm not sure if we want this property on every button on the site, but I **think** we might. @ludwiczakpawel @lisasy please correct me if we shouldn't do that! :sweat_smile: 
Before:
After:
or in a …

[15 minute fix] Fix word wrapping on mobile dashboard

---

datadog/prerun.sh

Following the example provided by [DataDog's doc](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script), I've added assignment of DD_VERSION for deployment tracking purpose
n/a
n/a
n/a

Declare DD_VERSION in prerun.sh

---

datadog/prerun.sh

Following the example provided by [DataDog's doc](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script), I've added assignment of DD_VERSION for deployment tracking purpose. I made a mistake adding it to the ignored if block in the previous attempt :facepalm: 
n/a
n/a
n/a

Declare DD_VERSION in prerun.sh 2nd try

---

app/controllers/api/v0/organizations_controller.rb

Rendering actions with '.' in the name is deprecated
Fixing a deprecation warning!

Fix deprecation warning

---

app/controllers/articles_controller.rb

Fixes a deprecation warning!
```
DEPRECATION WARNING: Calling `<<` to an ActiveModel::Errors message array in order to add an error is deprecated
. Please call `ActiveModel::Errors#add` instead.
```

Use ActiveModel::Errors#add to fix deprecation warning

---

Containerfile

change second bundler environment variable to match the first
https://github.com/forem/forem/pull/13261
docker pull and run bundle --version - should be 2.2 and not 2.1
None

Update Bundler version

---

app/assets/stylesheets/ltags/WikipediaTag.scss

Update Wikipedia liquid-tag styles issues and refactor css
Before:
After:
or in a …

Fix Wikipedia liquid tag styles

---

app/views/pages/badge.html.erb

Annoyingly, I _thought_ I had fixed this with https://github.com/forem/forem/pull/13276, but as it turns out, this error is ever so slightly different....but occurs for the _exact_ same reason, and within the same file.
I probably should have read the `app/views/pages/badge.html.erb` file more carefully and realized that this error was bound to happen again later on! 🤦🏽‍♀️ In any case, we should just not try to render any of this JS or call any methods on `@html_variant` if it doesn't exist in the template.
Fixes https://app.honeybadger.io/projects/72638/faults/78746996.
Related to https://app.honeybadger.io/projects/72638/faults/78731893.
_Tests should pass!_
_None_
Nope, I will be sure to resolve the error once it has been deployed to the fleet, though!

[15 Min Fix]: Prevent NoMethodError when Html variant is not present, take 2

---

app/sanitizers/rendered_markdown_scrubber.rb
app/services/markdown_processor/parser.rb
spec/services/markdown_processor/parser_spec.rb
spec/spec_helper.rb

This fixes a bug that allows people to do some weird stuff. ([More info for Core Team members](https://forem.team/jacobherrington/how-to-deface-a-forem-thread-for-fun-and-profit-9g))
We may need to consider how this will impact existing content.
Try doing some of the "weird stuff" in the more info tab on your local instance running this branch. …

[15-minute fix] Don't allow markdown to use CSS classes

---

app/views/admin/navigation_links/index.html.erb

While working in the Admin Portal, I noticed that there was an extra `<%= app_url %>` and set of parentheses in `/admin/navigation_links/index.html.erb` -- this PR removes them.
N/A
**First, ensure you are an Admin user, then navigate to `/admin/navigation_links`**:
- Click on the app URL and ensure that you are brought to the homepage as expected:
- Ensure all builds pass! ♻️ 
N/A
N/A

[15-Minute Fix] ✂️ Remove Superfluous app_url From Navigation Links Index

---

lib/slack/notifier/util/link_formatter.rb

Fixing a lint that might be causing merge conflict to others.
n/a
n/a

Fix link_formatter.rb's lints

---

app/services/edge_cache/bust.rb

We were trying to report an exception to Honeybadger but we never actually captured the exception.
https://app.honeybadger.io/projects/72638/faults/78754674

Fix rescue in EdgeCache::Bust

---

app/views/notifications/shared/_comment_box.html.erb

This button isn't for leaving a comment, it's just a link to a new page.

Fix misleading title on svg tag

---

app/sanitizers/rendered_markdown_scrubber.rb

This line was added in #13282 by accident. It doesn't hurt much, but `node.nil?` will never (I hate saying never) evaluate to true.

Remove unused code

---

app/lib/constants/site_config.rb

This PR updates the sidebar tags placeholder to omit the "letters-only" copy from the field, since sidebar tags technically accept numbers, too. Additionally, this updates the field to be more in-line with the sidebar tags documentation in the Admin Guide.
N/A
- First, ensure that you have an Admin-based role, then navigate to `/admin/config` and ensure that the placeholder text has been updated:
N/A …

[15-Minute Fix] Update Sidebar Tags Placeholder in the SiteConfig

---

app/controllers/notification_subscriptions_controller.rb
app/policies/api_secret_policy.rb
app/policies/application_policy.rb
app/policies/article_policy.rb
app/policies/chat_channel_policy.rb
app/policies/comment_policy.rb
app/policies/follow_policy.rb
app/policies/listing_policy.rb
app/policies/message_policy.rb
app/policies/response_template_policy.rb
app/services/broadcasts/welcome_notification/generator.rb
app/services/users/remove_role.rb

@citizen428 pointed out in #12270 that this not-very-Ruby pattern is sprinkled throughout the codebase.
It's certainly not a problem, but it makes sense to be consistent when naming methods that behave similarly.

[15-minute fix] Rename unidiomatic methods

---

app/assets/stylesheets/ltags/RedditTag.scss

Update Reddit liquid-tag styles issues and refactor some css
before:
after:
shared_

Fix Reddit liquid tag styles

---

Gemfile.lock

Ran `bundle install` locally, was left with this diff. I have macOS Catalina

Added missing entries in Gemfile.lock

---

app/controllers/admin/overview_controller.rb
app/models/feedback_message.rb
app/views/admin/overview/index.html.erb

Quick PR to render the number of open abuse reports on the admin overview.
Closes https://github.com/forem/internalEngineering/issues/406
replace this line with details on why this …

Add open reports count to admin overview

---

docs/api_v0.yml

`redoc`'s `x-code-samples` extension has been renamed to `x-codeSamples`: https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-codesamples
https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-codesamples
1. on `master`, go to the `docs/` directory and issue `make` on the command line
2. see the following appear while the tool is building the API doc:
```
Prerendering docs
"x-code-samples" is deprecated. Use "x-codeSamples" instead
```
3. repeat the same with this branch
4. see no such notice appear
[Admin …

[15 min fix] API docs: rename deprecated code samples extension

---

config/initializers/carrierwave.rb

There was a mistake in the current configuration. Keeping the 
n/a
n/a
n/a
- unnessary
shared_
n/a

Simplify CarrierWave's local_storage_config

---

cypress/integration/articleFlows/commentOnArticle.spec.js

Reenabled and fix a flaky E2E test for comments.
#13187
N/A. Just reenabling a test.
N/A. Just reenabling a test.
shared_

[15 min fix] Fixed flaky E2E test for comments

---

cypress/integration/articleFlows/commentOnArticle.spec.js

One of the cypress tests for autocomplete has started causing failures in a number of builds. It reliably passes locally, and there's been no change to the codebase that should have affected it.
This PR disables the test for now, to unblock builds while we look into the flakiness.
N/A
N/A
N/A
N/A

skip flakey autocomplete test

---

app/assets/javascripts/base.js.erb

Tiny refactor I came across while investigating another issue.
N/A
N/A
shared_

[15 min fix] Used the all browser supported document.body.

---

app/models/article.rb
app/validators/bytesize_validator.rb
spec/models/article_spec.rb
spec/services/articles/creator_spec.rb

Adds an upper limit to `Article.body_markdown`
Closes https://github.com/forem/internalEngineering/issues/410
1. load the console and load an article
2. `article.body_markdown = 'a' * 801.kilobytes`
3. `article.validate!`
4. get the error `ActiveRecord::RecordInvalid: Validation failed: Body markdown is too long (maximum is 819200 characters)`
5. `article.body_markdown = 'a' * 800.kilobytes`
6. `article.validate!` should yield `true` …

[15 min fix] Enforce an upper limit for articles.body_markdown

---

docs/backend/data-update-scripts.md

Added a tiny section to the "Data update scripts" documentation to encourage people to log the progress and to reverse the order during processing when there are lots of rows involved. This should help keeping an eye on what's going on.
shared_

[15 min fix] Document data update scripts best practices

---

app/models/device.rb
app/services/notifications/new_comment/send.rb
config/initializers/rpush.rb

Adds `ForemStatsClient` instrumentation to push notification delivery. `ForemStatsClient` is being incremented upon a) successful push notification delivery, and b) when delivery fails

Push Notification stats instrumentation

---

bin/e2e

A couple small tweaks to the E2E script for local development.
1. Run `yarn e2e`
2. The prompt will ask `Do you need to set up your end to end (E2E) testing database? Answer yes if this is your first time running E2E tests on your local machine or you need to recreate your E2E test database. (y/n)`
3. Wait 10 seconds and the script will continue without setting up the E2E database.
N/A
replace this …

[15 minute fix] Added a timeout before continuing if a dev does not respond to rebuild the E2E DB

---

app/models/user.rb
app/services/search/postgres/username.rb
db/migrate/20210420135208_add_name_tsvector_index_to_users.rb
db/schema.rb
spec/requests/search_spec.rb
spec/services/search/postgres/username_spec.rb

This adds "search by `users.name`" to the mention autocomplete component
Closes https://github.com/forem/rfcs/issues/194
1. run `bin/setup`
2. load the website
3. test the mention autocomplete both in the post editor and in the comment editor
4. search using both names and username (I recommend changing the name of a local user so that it doesn't reflect its username completely)
Nope
or in a …

[Search 2.0] Allow mention autocomplete to search users names

---

app/controllers/admin/pages_controller.rb
app/controllers/concerns/caching_headers.rb
app/controllers/concerns/development_dependency_checks.rb
app/controllers/concerns/edge_cache_safety_check.rb
app/controllers/concerns/image_uploads.rb
app/controllers/concerns/listings_toolkit.rb
app/controllers/concerns/session_current_user.rb
app/controllers/concerns/settings_params.rb
app/controllers/concerns/valid_request.rb
app/controllers/concerns/verify_setup_completed.rb
app/controllers/pages_controller.rb

I was reading up on the concerns in our app while waiting for PR review; it made sense to clean stuff up while I was in those files!
No behavior has changed, these are just some code smells detected by Reek.
Additionally, I added some comments to the concerns since they modify the inheritance chain making them a little hard to track down at runtime.

[15-Minute Fix] Refactor code smells

---

spec/system/comments/user_fills_out_comment_spec.rb

Reenable skipped test (was disabled to stop travis from segfaulting).
Reverts the changes in #13013
https://github.com/forem/forem/issues/13226
Nothing to QA? Really this is an issue working around our CI (only a test file was modified) and only the CI can determine if it's working. Original issue was Travis CI would segfault when starting the system test for "User fills out comment box". It only happened on this test, and I can't see what's special about it. …

re-enable skipped tests

---

app/models/user.rb
spec/services/search/postgres/username_spec.rb

After we added `users.name` to the list of fields to search against, the query time spiked up to ~ 500ms, with this change it should go back down to around 5-10ms.
Inline comments explain why.
https://github.com/forem/forem/pull/13462
1. run `bin/setup`
2. load the website
3. activate the feature flag `FeatureFlag.enable(:search_2_usernames)`
3. test the mention autocomplete both in the post editor and in the comment editor
4. search using both names and username (I recommend changing the name of a local user so that it doesn't reflect its username completely)
will share this change with the people who need to …

Use a manual query to find users by their names and usernames

---

.travis.yml
package.json

Small refactor to extract the lint script to run on it's own in Travis instead of a test pre script.
N/A
shared_

Lint script does not need to be a pre test script.

---

db/migrate/20210422171642_add_indexes_to_comments.rb
db/schema.rb

Following https://github.com/forem/forem/pull/13401 and https://github.com/forem/forem/pull/13469 the performance on the comments query still isn't where we want it. This PR adds more indexes to the `comments` table to improve performance.
https://github.com/forem/forem/blob/3ec91dd9368357bfd523305dfd94c7d0c5977df3/app/services/search/postgres/comment.rb#L45-L55
https://github.com/forem/forem/pull/13401
https://github.com/forem/forem/pull/13469
https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/s1uhihjmPKR/trace/5PkgsLrBkdX
1. Run `rails db:migrate` and see the index is added.
2. Run `rails db:rollback STEP=1` and see the index is removed.
I'll sync with SRE to monitor the results of this change.

Add indexes to comments

---

app/services/edge_cache/bust_article.rb

None, this is a backend service.

Cleanup articles cache busting

---

app/liquid_tags/codepen_tag.rb
spec/liquid_tags/codepen_tag_spec.rb

CodePen has public and private Pen URLs but the `codepen_tag` class only parses public URLs. This PR allows the `codepen_tag` class to parse private URLs as well. This PR updates the `URL_REGEXP` used to parse public and private URLs. I added tests with real private URLs to prove the change works.
Run rspec tests for `spec/liquid_tags/codepen_tag_spec.rb` unit test added in this PR.
None
or in a …

Modify codepen_tag to parse public and private Pen urls

---

app/javascript/listings/listings.jsx
cypress/fixtures/search/listings.json
cypress/integration/listingFlows/viewListing.spec.js

Sending a message to a listing author works about half the time. I
can't determine exactly what user behavior causes it to fail or succeed,
but after making this change it doesn't fail anymore. Looking at the
code, I'm not sure how it ever works...
Ater more manual testing, it seems like the failure has something to do with opening and closing the modals before responding. This change fixes the bug and will notify Honeybadger if things start acting out again.
Closes https://github.com/forem/forem/issues/12393
Navigate to listings, attempt to respond to a listing. Try opening and closing multiple listing modals and responding, it shouldn't ever fail.
accessibility is impacted and tested. For more info, check out …

Fix bug when responding to listings

---

app/services/homepage/fetch_tag_flares.rb
spec/services/homepage/fetch_tag_flares_spec.rb

After briefly activating the new homepage query the code encountered a bug triggered for articles whose `cached_tag_list` is nil (there are only 16 of them on DEV :-/).
This solves https://app.honeybadger.io/fault/66984/448f6bcb0bffe67d7a409e92172f78c7
#13339 
shared_

Homepage query should not fail for nil article's cached tag list

---

app/models/user.rb
spec/services/search/postgres/username_spec.rb

As we're not using the `pg_search` gem to search for users's names or usernames, we don't rely on the gem's autoquoting capabilities. This fixes a [bug](https://github.com/forem/forem/pull/13489#issuecomment-825792269) detected by @djuber (thank you!), which would break search for user's names containing single or double quotes.
#13474
There are tests but you can activate the `:search_2_usernames` flag and type a name with a quote in it:
https://user-images.githubusercontent.com/146201/115965392-60ba5b00-a529-11eb-9629-09b352b740cb.mov
[Admin …

Fix search with quotes in users's names

---

app/assets/stylesheets/components/forms.scss

This PR fixes an issue, in which a resize of a textarea was extending the textarea over the bounds of the parent container.
Fixes #13230 
Go to `/settings` when logged in & resize any of the textareas like the "Summary" or "Skills/Languages" one.
Bug:
Fixed:
Tested on Chrome on Ubuntu 18.04.5 LTS

Settings: Fix textarea out of bounds on resize

---

app/views/pages/_editor_guide_h3.html.erb
app/views/pages/_editor_guide_text.html.erb
app/views/pages/_v1_editor_guide_preamble.html.erb

I tried to cleanup a bit the Markdown's editor guide page as its HTML and accessibility score were subpar.
I haven't solved everything (especially in the domain of semantic tags) but I think it's a bit better than before.
Load the branch, visit http://localhost:3000/p/editor_guide and check everything is okay.
In terms of UI:
**before**
**after**
In terms of accessibility score:
**before**
**after** …

Cleanup markup of editor guide

---

.github/dependabot.yml

Locking us in at v. 4.3.8 of the husky package as it still works great for us and version 6 changes how
it works quite a bit. We can upgrade to version 6 or later in the future, but for now, there is no reason to.
#13166
N/A, this freezes an npm package version.
N/A, this freezes an npm package version.
shared_

[15-min-fix] Set husky explicilty to version 4.x

---

app/controllers/search_controller.rb
app/queries/homepage/articles_query.rb
app/services/homepage/fetch_articles.rb
spec/queries/homepage/articles_query_spec.rb
spec/requests/search_spec.rb

While testing #13339 in production, https://github.com/forem/forem/issues/13494 was opened on this repo, thus we learnt we were missing three key features, respectively for the profile page, the organization page and the tag index page.
This PR covers those missing filters.
We've decided not to rename the classes for now and added this to the list of refactorings once we're done with the move.
#13339 
Load the PR, turn on the `search_2_homepage` feature flag, browse the homepage, a profile page of a user, an organization page and the tag index page
will share this change with the people who need to know about …

[Search 2.0] Add query filters for profile, organization and tag index pages

---

app/views/articles/manage.html.erb
app/views/chat_channels/index.html.erb

This PR adds the skip link functionality (and main landmark) to:
- `/connect`
- `/{user}/{post}/manage`
In the case of connect there is no visible change in behaviour, since the input continues to autofocus. However, this adds the `main` landmark and the correct ID has been added so that the skip link does work if used (even though it's unlikely anyone will activate it).
In the case of the /manage route, the skip link is only the first focusable item on a fresh page load, and not on internal navigation, due to the way we handle loading of pages.
We will want to change this eventually so users can get the most out of the skip links, but this will be covered in a separate issue.
Closes #1153
For connect:
- Go to `/connect` and use the axe dev tool to inspect that page and check there is no …

Add skip link to connect and manage post

---

app/serializers/homepage/article_serializer.rb
spec/services/homepage/fetch_articles_spec.rb

JavaScript expects `article.flare_tag`, we're sending back `article.tag_flare`.
https://github.com/forem/forem/blob/6f4382719e75e6fb4935fb0687ef09b40e4dfb15/app/assets/javascripts/utilities/buildArticleHTML.js#L34
#13339 
#13510 
1. Enable the `:search_2_homepage` feature flag
2. Go to http://localhost:3000/admin/tags/ - change the color of `#discuss`
3. Publish a post with the tag `#discuss`
4. Visit http://localhost:3000/latest and check that the tag is highlighted …

[Hotfix] Serialize tag flares correctly in Homepage::ArticleSerializer

---

app/services/articles/get_user_stickies.rb

This is our top query by total time spent:
shared_

Optimize `Articles::GetUserStickies`

---

app/queries/homepage/articles_query.rb
app/services/search/postgres/reading_list.rb
spec/queries/homepage/articles_query_spec.rb
spec/services/search/postgres/reading_list_spec.rb

Follow up to #13547 - we need to match both boundaries, so it only matches entire words. No `go` in `stopandgo` or `script` in `javascript`
#13547
Same as #13547
shared_

[Hotfix] [Search 2.0] Match both word boundaries when filtering tags

---

spec/tasks/metrics_spec.rb

I was running this test in an environment where appdomain was "rails" instead of "localhost" and the spec failed (since the text was wrong).
This makes the test case independent of the environment variables. 
Ran both in local/native and in the container with the different environment variables to confirm nothing breaks while making this fix.
Run this test, confirm it passes. Modify APP_DOMAIN and run again:
```
bundle exec rspec spec/tasks/metrics_spec.rb
APP_DOMAIN=remotehost bundle exec rspec spec/tasks/metrics_spec.rb
```
```
djuber@forem:~/src/forem$ bundle exec rspec spec/tasks/metrics_spec.rb 
[Zonebie] Setting timezone: ZONEBIE_TZ="Mexico City"
.
Finished in 1.72 seconds (files took 3.5 seconds to load)
1 example, 0 failures
djuber@forem:~/src/forem$ APP_DOMAIN=remotehost bundle …
```

Remove hardcoded "localhost:3000" from metrics spec

---

app/javascript/admin/__tests__/controllers/sidebar_controller.test.js
app/views/admin/shared/_nested_sidebar.html.erb
app/views/layouts/admin.html.erb

Change `aria-page` to `aria-current` as that is not a valid aria tag. 
I've also removed the aria tags from the test cases since it wasn't being used.
https://github.com/forem/rfcs/pull/50
https://github.com/forem/internalEngineering/issues/413 …

Fix "invalid aria attribute aria-page"

---

app/models/article.rb
app/queries/homepage/articles_query.rb
app/services/search/postgres/reading_list.rb
spec/models/article_spec.rb

Removing custom code to use `Article.cached_tagged_with` and `Article.cached_tagged_with_any` 👀 
Thanks @jgaskins!
#13547
#13554
shared_

[Search 2.0] Use Article.cached_tagged_with* in queries

---

db/migrate/20210429094116_add_tsvector_index_on_searchable_columns_to_listings.rb

From the Heroku deployment log:
```
+ [[ '' = \b\l\o\c\k\e\d ]]
+ STATEMENT_TIMEOUT=4500000
+ bundle exec rails app_initializer:setup
== Preparing Elasticsearch ==
== Preparing database ==
rails aborted!
NameError: uninitialized constant AddTsvectorIndexOnSearchableColumnsToListings
Did you mean?  AddTsvectorIndexOnSearchableColumnnsToListings
```
replace this line with details on why this change …

Fix typo in migration class name to match filename

---

app/assets/stylesheets/admin.scss
app/javascript/admin/__tests__/controllers/sidebar_controller.test.js
app/javascript/admin/controllers/sidebar_controller.js
app/views/admin/shared/_nested_sidebar.html.erb

☝️ it's all of those really.
These were the problems with the interaction on the sidebar:
1. The animation was jarring and caused a substantial lag 
2. The page would load up before the sidebar item was highlighted. In essence, the sidebar item was taking a really long time to highlight.
The animation is far from perfect, and there is still a slight flicker that occurs from time to time when you click on the menu item but we've spent a lot of time on it (Rhymes was really gracious and played with the code as well). I think that it's good enough for this to go live, unless anyone has any serious concerns about this. I feel like any further changes can be done as an enhancement, or can be implemented once we remove bootstrap collapse.
Aside: When you click on moderation and there is an …

RFC 50: Interaction tweaks (take two)

---

db/migrate/20210430094954_add_index_on_articles_comments_count.rb
db/schema.rb

I ascertained that we don’t have an index on `articles.comments_count`, a condition that is used to search for articles: 
https://github.com/forem/forem/blob/aee1d041d65b7380cd2820779aca173f9df32051/app/services/search/postgres/article.rb#L4
For that reason we have a [slow response](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/zy8Fe7rHMVv?tab=traces) and the `EXPLAIN ANALYZE` on the simplest query for that page ranges around 700ms.
Removing the `comments_count DESC` condition goes back to 3ms, I predict a similar time when the index is added and created.
#13540  …

[Search 2.0] Add index on articles.comments_count

---

lib/data_update_scripts/20210405034117_move_campaign_settings.rb
lib/data_update_scripts/20210420050256_move_mascot_settings.rb

In migrating config variables from `SiteConfig` to various sub-level settings tables, we've been migrating them no matter what their values were. This caused issues in Forem instances that did not have all of these variables set. They're set on DEV and BHC so we didn't get notified about them until we deployed the Forem fleet.
https://app.honeybadger.io/projects/72638/faults/79085713 — there are a lot of these, but I won't link them all
or in …

Only migrate config vars that were explicitly set

---

app/helpers/application_helper.rb
app/lib/constants/site_config.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb
app/views/layouts/_signup_modal.html.erb
app/views/onboardings/_task_card.html.erb
app/views/onboardings/show.html.erb
app/views/stories/_sign_in_invitation.html.erb
lib/data_update_scripts/20210430043750_remove_site_config_secondary_logo.rb
spec/models/site_config_spec.rb
spec/requests/admin/configs_spec.rb
spec/requests/onboardings_spec.rb

I needed a break from my other `SiteConfig` work, so decided to tackle this in between tasks.
Closes #13586
Specs should be green. Not sure about any manual QA steps but they don't seem necessary.
None

[15 minute fix] Remove secondary logo

---

app/javascript/onboarding/components/FollowTags.jsx

Suggested tag during onboarding screen is made screen reader friendly with this PR. more context in https://github.com/forem/forem/pull/12384#discussion_r576524771
closes https://github.com/forem/forem/issues/9585
1. Go to `/onboarding`
2. Go to screen "What are you interested in?"
3. Enable voice over and use keyboard to navigate the app
This PR will make tags to follow during onboarding more accessible
or in a [forem.dev](http://forem.dev) …

Fixing dom structure of Tags to follow

---

app/workers/search/index_worker.rb

When deploying https://github.com/forem/forem/pull/13606, our game plan was to manually delete the Sidekiq errors raised due to the files/workers no longer existing. Come to find out...Sidekiq doesn't let you delete workers because it tries to instantiate the class itself vs treating it as a string/class name. It's fine for DEV, but before this goes out to other instances, we need this no-op class so the Sidekiq queues can clear themselves out, error-free.
After a few days, we'll remove this file again.
https://github.com/forem/forem/pull/13606
https://app.honeybadger.io/projects/66984/faults/79167390
N/A - hotfix
Monitor this deploy across the fleet

Add no-op Search::IndexWorker

---

Gemfile.lock

Bundler wasn't doing this before, but with the newer versions, it's adding this every time I bundle

Add M1 architecture to Gemfile.lock

---

app/helpers/profile_helper.rb
spec/factories/users.rb
spec/helpers/profile_helper_spec.rb

For around 0.6% of identites this method of getting a URL to the social account is not functioning. It is currently causing some 500 errors in production.
This is a hotfix to keep the 500 errors from happening, but for these users their authed social accounts won't show up on their profiles as expected.
From prod ("broken" identites):
```
select provider, count(provider) from identities where auth_data_dump is null group by provider;
provider | count
----------+-------
github   |  1831
twitter  |  1902
```
https://github.com/forem/forem/pull/13252
https://app.honeybadger.io/projects/66984/faults/79167324
See added test!
development process, or any of our internal teams? If so, please note …

[Hot Fix] Add safe navigation operator to stop 500 errors

---

app/views/admin/feedback_messages/_feedback_message.html.erb

In a [previous PR](https://github.com/forem/forem/pull/13473#discussion_r620393397) I passed a data-path value from the erb and referenced it in the javascript. 
This was not needed as the javascript was inlined, hence I could just reference the path using ERB syntax.
Comment on previous PR: https://github.com/forem/forem/pull/13473#discussion_r620393397
- Go to an a comment on an article and click "Report Abuse"
- You'll be redirected to the Report Abuse page, where you will fill out the details
- Thereafter go to http://localhost:3000/admin/moderation/reports where you will find buttons "Save Status", "Send Email" and "Create Note". Click on each of them and ensure that points to the correct URL and is successful.
Send Email = `http://localhost:3000/admin/moderation/reports/send_email` …

[15-min-fix] Remove data-paths and use inline ERB in the js instead

---

spec/requests/admin/nested_sidebar_spec.rb

As [per this comment](https://github.com/forem/forem/pull/13579#discussion_r623184051) the test in this PR was failing and I didn't have the capacity to figure out the reason it was failing before the admin restructure deploy (the functionality was working). Hence, I commented it out temporarily. 
Dan recently came across a similar issue but on the [feature flag for the profile fields](https://forem-team.slack.com/archives/C012YSX5ZC1/p1620052332001500) and he implemented a [fix](https://github.com/forem/forem/pull/13637) which I believe should solve this issue as well. 
Comment can be found in https://github.com/forem/forem/pull/13579#discussion_r623184051
Just to check if the test passes on Travis …

[15-min-fix] Uncomment test in the nested sidebar spec

---

cypress/integration/articleFlows/commentOnArticle.spec.js

Disabled a flaky E2E test for comments.
N/A
N/A
N/A
shared_

[15-min-fix] Disabled flaky E2E comment test

---

docs/admin/admin-search.md
docs/admin/readme.md
docs/backend/auth-apple.md
docs/backend/configuration.md
docs/creators/configure-forem.md
spec/requests/admin/invitations_spec.rb
spec/requests/admin/permissions_spec.rb

There were some hardcoded admin routes that did not not get converted to admin path helpers because it wasn't a priority for the Admin Restructure. Doing some cleanup in this PR to remove the hardcoded values. 
In addition, updated the paths in the developer docs.
https://github.com/forem/forem/pull/13549#issuecomment-828561188
None really. Make sure Travis doesn't fail as they were on spec files. …

[15-min-fix] Remove/Update the last of the admin hardcoded paths

---

app/views/articles/_actions.html.erb

Incorporating aitchiss's suggestion from #13668 
Clarify that "this link" is "article link" or "link to article" in the title.
https://github.com/forem/forem/pull/13668/
The action is not keyboard accessible (out of scope of this change) - already noted by @aitchiss in the comment from the first PR.

Clarify article link copy title

---

.env_sample

In the installation guide we tell people to copy `.env_sample` to `.env` but this file isn't actually valid, as numbers with inline comments will be interpreted as strings, see https://github.com/forem/forem/issues/13298#issuecomment-833590511 for example.
I decided to remove all inline comments from `.env_sample`
https://github.com/forem/forem/issues/13298#issuecomment-833590511
replace this line …

Remove inline comments and variable substitution from .env_sample

---

app/decorators/comment_decorator.rb
app/decorators/podcast_episode_decorator.rb
app/helpers/date_helper.rb
app/models/article.rb
app/models/comment.rb
spec/decorators/podcast_episode_decorator_spec.rb
spec/helpers/date_helper_spec.rb
spec/models/article_spec.rb
spec/models/comment_spec.rb

Removed extra spaces from readable_publish_date by changing format specifiers
Fixes #13612
I'm not sure about this since the only change done is updating format specifiers
N/A
N/A

Update format specifiers in readable_publish_date

---

app/views/badges/show.html.erb

Update the CSS of the badge page title so that the title is still readable for long badges and small screens
Fixes #13652 
No tests written because this is a UI change.
This has been tested on Chrome 90.0.4430.93 on a MacBook Pro (13-inch, Early 2011) with macOS version 10.12.6
Before fixes: 
After fixes: 
As far as I know, accessibility has not been impacted.
replace this line with details on why …

Update the CSS of the badge page title

---

app/assets/javascripts/initializers/initializeCommentDropdown.js
cypress/integration/articleFlows/postSidebarActions.spec.js

Fixed a regression caused by the fix in #13674. The share button on an article page was not opeing the share menu. This is fixed now.
@Zhao-Andy, I don't know when the fleet was last deployed, but if it was deployed after #13764 yesterday, we'll need to push this fix to the fleet.
#13674
Closes #13690
1. Navigate to any article page.
2. Click on the three dot share button below reactions in the article sidebar
3. The share menu opens
1. Navigate to any article page.
2. Click on the three dot share button beside reactions at the bottom of the screen
3. The share menu opens
N/A …

[15 min fix] Fixed broken share button on article page.

---

app/liquid_tags/replit_tag.rb
app/views/pages/_editor_guide_text.html.erb
app/views/pages/_editor_liquid_help.html.erb

Updated replit url in the editor guide from repl.it to replit.com 
Fixes #13665 
No tests written because this is a UI change.
This has been tested on Chrome 90.0.4430.93 on a MacBook Pro (13-inch, Early 2011) with macOS version 10.12.6
No concerns.
shared_

Updated replit url from repl.it to replit.com

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb

Preview button text in comment section did not reset back after the comment is submitted this PR fixes it
closes https://github.com/forem/forem/issues/13182 …

Fixing preview button text in comment section

---

app/lib/url.rb
app/views/admin/tags/edit.html.erb
app/views/articles/_single_story.html.erb
app/views/dashboards/following_tags.html.erb
app/views/tags/_liquid.html.erb
app/views/tags/edit.html.erb
app/views/tags/index.html.erb
spec/lib/url_spec.rb

We've been rendering raw tag names into URLs, but the HTTP specification [requires that URL paths be printable ASCII characters](https://datatracker.ietf.org/doc/html/rfc5322#section-3.2.4) so we need to encode them that way.
#9006 added a validation so people wouldn't add tags that can't be encoded, but these tags still exist and are still causing significant errors in DEV so we need to be able to handle them. With this change, we may actually be able to remove that validation, but I'm not 100% sure on that.
This PR should not have made any changes to the rendered text, just `href` attributes, so we _should_ …

Sanitize tag urls

---

app/services/profiles/update.rb

This PR just adds some minimal YARD docs to the `Profiles::Update` service.

Add documentation for Profiles::Update

---

docs/installation/gitpod.md

Update GitPod setup description

---

app/views/pages/_editor_guide_text.html.erb

This PR adds a new section to the editor guide at `/p/editor_guide` on accessibility, as part of the ground work for https://github.com/forem/rfcs/pull/58. Later, when we add the 'possible accessibility improvements' notice in the post preview, we'll be able to point at these new sections of the editor guide for further detail on why `alt text` and headings are important.
I'm keen for any input on the content - bearing in mind that it needs to be understandable to all kinds of Forem users, and not just developers.
https://github.com/forem/rfcs/pull/58 (RFC: Advise users about potential accessibility failings in their posts)
- Visit `/p/editor_guide` and check the Accessibility section exists and has a functioning permalink
- Check the subsections on adding image descriptions and headings …

add accessibility section to editor guide

---

app/controllers/application_controller.rb
app/controllers/deep_links_controller.rb
spec/requests/universal_links_spec.rb

Non-public forems we're having trouble with Universal Links because `/.well-known/apple-app-site-association` wasn't accessible to the Apple bot
https://github.com/forem/rfcs/pull/72
1. Make your local environment non-public
- `Settings::UserExperience.public = false`
2. Fetch `/.well-known/apple-app-site-association` in incognito window
- It should render despite any other page in the Forem instance being "protected".
None - not affecting any FE code
None

Expose aasa for non-private Forems

---

app/services/feeds/import.rb
spec/services/feeds/import_spec.rb

This PR address a bug where authors who imported articles into Forem from an RSS feed weren't receiving notifications for comments on their articles unless they manually subscribed. Now authors are automatically subscribed to comment notifications when articles are created from a feed.
Technically, articles created from a feed before this PR will still be unsubscribed unless the author manually subscribed on their own. I chose not to include a script to update this since those authors who wanted to receive those notifications still had the option to opt-in. I'm hesitant to programmatically add a lot of notification triggers to users without a warning.
closes https://github.com/forem/forem/issues/7111
1. Fire up the app locally - `bin/startup`.
2. Log in as the local admin - …

Auto-subscribe to comments on articles from feed

---

app/javascript/contentDisplayPolicy/hideBlockedContent.js
app/javascript/profileDropdown/blockButton.js
spec/services/articles/feeds/basic_spec.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb

This PR fixes a bug in the functionality of blocking a user. When you block a user, you shouldn't see their posts in your feed. A bug was causing posts from blocked users to show up in people's feeds.
This probably resulted from some refactorings, but the issue seems to be we were using the wrong element identifier. [Articles are rendered in an `article` component](https://github.com/forem/forem/blob/ba972b2c1d726dabd10445afcbae94432094ab5b/app/javascript/articles/Article.jsx#L46-L52), not a `div`.
closes https://github.com/forem/forem/issues/5342
closes https://github.com/forem/forem/issues/11636
1. Create a new user locally.
2. Fire up the app.
3. Sign in as the local admin (`admin@forem.local` / `password`).
4. Make a new post.
5. Sign out.
6. Sign in as a different user (i.e. from …

Don't show articles from blocked users in the feed

---

spec/factories/articles.rb
spec/services/users/suggest_recent_spec.rb

The articles factory added three tags, but none of them were "flare tags", so tests weren't exercising paths in the view that acted on flare tags (when decorating articles). This is related to [an outage](https://forem.team/jamie/dev-homepage-outage-498d)[internal link] where a flare tag's name, rather than the tag, was [passed to URL.tag](https://github.com/forem/forem/pull/13720/files#diff-bf43b230dce41921c7a2c3c5d82342c9c62adb4bac5a7a234efeee223e13d65fR62)
One reason the error was not detected earlier is that no tests were adding flare tags.
Now, we have flare tags on articles by default. 
https://github.com/forem/forem/pull/13720
https://github.com/forem/forem/pull/13732
Test only change.
None
development …

Change article factory to include a flare tag "discuss"

---

spec/rails_helper.rb

With https://github.com/forem/forem/pull/13754 `test-prof` added a "nate heckler mode" (🤣) which essentially runs tests wrapped by test-prof and displays the amount of time spent building objects in `FactoryBot` (out of the total runtime), see [here](https://test-prof.evilmartians.io/#/profilers/factory_prof?id=instructions) for further details.
This is an example output:
```shell
> bundle exec rspec spec/models/podcast_episode_spec.rb
[Zonebie] Setting timezone: ZONEBIE_TZ="Pretoria"
........................
Finished in 1.33 seconds (files took 6.61 seconds to load)
24 examples, 0 failures
[TEST PROF INFO] Time spent in factories: 00:00.764 (49.76% of total time)
```
https://github.com/forem/forem/pull/13754

[15 min fix] Enable and display test-prof report at the end of a test run

---

README.md

Remove Vaidehi from Forem Core Team

---

.yarnclean

Add yarnclean to reduce our node_module size
n/a
n/a

Add .yarnclean

---

app/views/layouts/_footer.html.erb
app/views/shared/_logo_design.html.erb
app/views/users/_account.html.erb
app/views/users/_account_set_password.html.erb
app/views/users/_extensions.html.erb
app/views/users/_org_admin.html.erb
app/views/users/_org_member.html.erb
app/views/users/_org_non_member.html.erb
app/views/users/_publishing_from_rss.html.erb
app/views/users/edit.html.erb

Fix various accessibility issues flagged by axe.
These issues were found using the axe Firefox extension, there are a few that could still be addressed, but this covers most of the issues that were flagged.

[15 minute fix] Fix accessibility concerns in settings UI

---

app/views/articles/_collection.html.erb
spec/factories/collections.rb
spec/requests/collections_spec.rb

Change math in collection to represent the correct number of hidden posts. I might need some help with writing tests if necessary.
This fixes https://github.com/forem/forem/issues/10956. Since the posts past the first two and before the last two are truncated, the math was slightly off. Instead of accounting for all four visible posts it only accounting for two.
Closes issue #10956 
I tried to recreate and test locally before pushing, but my local stack would not let me publish posts.
This should only change a single text element. There should not be any accessibility concerns. …

Show correct number in series truncation.

---

app/views/articles/_search.html.erb

Currently, when a user searches from the homepage or navigates directly to `/search` none of the tabs are highlighted. By default, the endpoint returns articles so we should denote that in the UI. This does that without making any significant changes to the way the code runs right now.
Relevant: https://github.com/forem/forem/blob/d87537ab2981ce88bd682010cf2788c2b685461d/app/controllers/search_controller.rb#L112-L113
Before:
After:
or in a …

[15 minute fix] Highlight "Posts" tab by default in search

---

app/javascript/article-form/components/PageTitle.jsx
app/javascript/article-form/components/Title.jsx
app/views/articles/_v2_form.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_nav_menu.html.erb
app/views/layouts/_top_bar.html.erb
app/views/stories/tagged_articles/_sidebar.html.erb
db/schema.rb
db/seeds.rb
spec/factories/broadcasts.rb

Update the naming of the create post entrypoint from "Write a post" to "Create post" optimizing for a few things:
1. this makes clear that this composer isn't going to be limited to merely long-form essay format.
2. the new language is more concise
None
shared_

Rename WRITE A POST to CREATE POST

---

app/workers/migrate_user_notification_settings_worker.rb
app/workers/migrate_user_settings_worker.rb

These migrations aren't going as quickly as any of us would like. I'm wondering if putting the `WHERE` clause inside the CTE (as opposed to the top-level query) might improve performance.
- #13848 
- #13390 
If this speeds things up, throughput on [this Datadog resource](https://app.datadoghq.com/apm/resource/sidekiq/sidekiq.job/9ffd218219b6ca64?end=1621976400817&env=production&index=apm-search&paused=false&query=env%3Aproduction%20service%3Asidekiq%20operation_name%3Asidekiq.job%20resource_name%3AMigrateUserSettingsWorker&start=1621972800817&wend=1621970324638&wstart=1621797524638) will be > 7
will share this change with the people who …

Put the user id filter inside the CTEs

---

config/environments/development.rb

If you've ever wondered "where does this HTML come from?", Rails 6.1 has `config.action_view.annotate_rendered_view_with_filenames` which annotates the HTML with the template from which every HTML block comes from 🔥 
shared_

Enable view annotation in development

---

app/assets/stylesheets/views/article.scss

Update the visual styling of the post action bar on small viewport/mobile so that it looks visually more pleasing. The previous design looks a bit outdated and boxy.
I've tested this color change on all color themes and it seems to work properly. I'm not introducing any new color variable here; I'm using an existing one.

Update visual styling of post action bar

---

package.json

After #13837, there is one line remains pointing to lint-openapi which produces an error. This PR fixes it.
See https://github.com/forem/forem/pull/13837#issuecomment-848889853 …

Remove mentioning lint-openapi completely

---

db/seeds.rb

The old URL redirects to the new one, so I've updated it to just point to the new one

Seeds: update correct CodingBlocks podcast feed URL

---

app/javascript/packs/homePage.jsx
cypress/integration/homeFeedFlows/feedNavigation.spec.js
spec/support/seeds/seeds_e2e.rb

We had a small bug where a desktop logged in user would not see the right-hand sidebar content if they viewed the home feed by one of the other tabs (e.g. Week/Month). I've updated the JS to load the sidebar no just when on the root "/" location but any of the filtered feed URLs too.
Closes https://github.com/forem/forem/issues/13873
- Log in to the app
- Navigate through the home feed tabs and check the sidebar loads
- Navigate to some other pages in the app and check we don't load the sidebar in error
N/A
[Admin …

[15 min fix] Show the sidebar on all logged in feed views

---

app/assets/stylesheets/components/stories.scss

Add margin to feed cards for mobile/small viewports so that the visual presentation of content feels less clunky and more spacious
None

Add margin to feed cards on mobile

---

cypress/integration/listingFlows/deleteListing.spec.js

We've observed this test flaking in CI a fair bit, and investigating locally it seems that the issue is we're not always on the page that we expect when we run assertions.
I've added some additional steps to make sure we're on the correct page each time we expect it to have changed - this should hopefully resolve the issues we're seeing.
N/A
The only QA we need is to check this spec passes in CI
N/A
or in a …

[15 min fix] fix flake in delete listing test

---

cypress/integration/articleFlows/pinArticle.spec.js

One of the [latest builds](https://travis-ci.com/github/forem/forem/jobs/511047724#L3270) failed because of a condition that doesn't always happen in Cypress. By adding this guard we ensure the test is more robust
#13807 

Fix flakey test in articleFlows/pinArticle

---

app/models/article.rb
app/services/search/article.rb
db/migrate/20210604161909_create_trigger_articles_insert_update1.rb
db/migrate/20210609103939_create_trigger_articles_insert_update1.rb
db/schema.rb
spec/models/hair_trigger_spec.rb
spec/services/search/article_spec.rb

This PR re-introduces weights on different columns. We used to weigh in this order with Elasticsearch: 
1 - title
2 - body markdown
3 - tags names
4 - everything else
Refers to https://github.com/forem/forem/issues/13746
(Doesn't close it as there's additional UI work that will be implemented in a separate PR)
1. Choose a sentence
1. Create a few articles: use the sentence for the title for one article, the body for another and yet another
1. Search for that _entire_ sentence in the search box
2. Check that the article using the sentence as its title appears first in the search results than the others
3. You can repeat a similar approach with a tag: create two articles, one with the tag as a tag, one with the name of the tag in the body, search for that tag and ensure the tagged article …

Search results: prioritize articles titles

---

app/models/article.rb

@citizen428 helpfully pointed out ActiveSupport's [`String#truncate`](https://api.rubyonrails.org/v6.0.3.3/classes/String.html#method-i-truncate) method, and I had read the processed_description method body immediately before and knew it could also be cleaned up using truncate.
When the body text is present, if it's long, truncate to 101 characters (with trailing ellipsis as needed), removing newlines.
When the body text is absent, populate with a generic "post by user" message.
stems from the discussion in https://github.com/forem/forem/pull/13961 
Covered by test cases. Should be no change in behavior.
None …

Simplify logic around generated article description

---

.github/PULL_REQUEST_TEMPLATE.md

This is a very minor change to our PR template, instead of `Added tests?` the heading now says `Added/updated tests?`. As someone who does a lot of refactorings this makes my life easier, as I usually change `Yes`, to `Updated existing ones` or similar.

Update test section

---

spec/support/seeds/seeds_e2e.rb

There's a unique index page on slugs that failed today during a PR
merge, where 'et' was the `Faker::Lorem.word` selected both times.
Add a suffix to the generated word to ensure these are unique and an
index collision doesn't happen.
Underlying issue is two independent samplings from Lorem.word have a 1 in 182 chance of collision, since there are only 182 unique words in the set. We run the seeds a lot - it's not impossible this would happen once in a while.
```ruby
10_000.times.map { Faker::Lorem.word }.uniq.count 
=> 182
```
https://travis-ci.com/github/forem/forem/jobs/513601871#L2869-L2873
```
7. Creating Pages.
/home/travis/build/forem/forem/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': …
```

Ensure seeded page slugs are unique

---

app/mailers/application_mailer.rb
config/environments/production.rb
spec/mailers/application_mailer_spec.rb
spec/models/settings/smtp_spec.rb
spec/system/user_logs_in_with_password_spec.rb

The App isn't pull proper configuration.

Revert Email config changes

---

app/controllers/credits_controller.rb
app/services/payments/process_credit_purchase.rb

This PR refactors purchasing credits via the Stripe API. All purchase specific functionality has moved out of the controller into the `Payments::ProcessCreditsPurchase` service object.
https://github.com/forem/internalEngineering/issues/364
* Go to `http://localhost:3000/credits/purchase`
* Purchase credits, you can use one of the [Stripe test cards](https://stripe.com/docs/testing)
* The purchase should be successful
None, backend refactoring only

Refactor credit purchasing

---

app/views/api/v0/admin/configs/show.json.jbuilder

This should have been removed in #13934

API: Remove orphan Admin Config jbuilder file ✂️ 

---

app/views/pages/_editor_guide_text.html.erb

Fixed typo in Editor Guide -- 'SlideSare' to 'SlideShare'.
Fixes #14010  …

Fixed typo 'SlideSare'

---

app/javascript/searchableItemList/searchableItemList.js

Reading list pagination is currently broken, see https://github.com/forem/forem/issues/14016
Closes https://github.com/forem/forem/issues/14016
1. You need to add at least 80 articles to your reading list
2. Click "Load More"
3. See that the new page is loaded
https://user-images.githubusercontent.com/146201/122744874-ba6ca680-d288-11eb-944e-fe9319464971.mov
replace this line with details on why this …

[15 minute fix] Reading list: fix broken pagination

---

app/javascript/packs/analyticsDashboard.js

Once a user visits one of their analytics dashboards, we add an InstantClick page change listener, to re-initialize the dashboard when it's called.
The InstantClick callback wasn't needed to reinitialize the page, and it is causing an error when you navigate away from the page, as it tries to update DOM elements that no longer exist.
The error is most noticeable for users navigating by keyboard, because it causes the next page to reload and for the user to lose the skip link focus:
https://user-images.githubusercontent.com/20773163/122935150-03475c80-d368-11eb-8744-cd936be2bbaf.mp4
Bug discovered in #13995 but we decided to fix it in its own PR so we can test and verify it in isolation.
To test this we should make sure we:
- Visit the analytics dashboard, check it loads as expected
- …

[15 min fix] Remove instantclick change listener on analytics dashboard

---

cypress/integration/chatFlows/messageOptions.spec.js

We are getting stung quite regularly by this test in CI, failing due to the problems documented in #13988. I'm planning to pick up that issue this week, and will re-enable this test as part of that work. For now, this `skip` will help unblock our CI.
#13988
N/A
N/A
shared_

Skip message options spec

---

spec/system/admin/admin_manages_organizations_spec.rb

While working on tests within the Admin Portal, I came across `admin_manages_organizations_spec.rb` and noticed that there was a commented out expectation on line 26. After testing out the org feature and running the spec, I decided to uncomment line 26 and keep it in the spec rather than remove it altogether.
N/A
Ensure that all of the builds are green ♻️ 
N/A
N/A

[15-Minute Fix] Uncomment Expectation from admin_manages_organizations_spec.rb

---

app/controllers/admin/tags_controller.rb
app/views/admin/tags/_form.html.erb
app/views/admin/tags/edit.html.erb
spec/system/admin/admin_creates_new_tag_spec.rb
spec/system/admin/admin_updates_tag_spec.rb

This 15-minute fix resolves an issue where Admins were unable to both `create` and `update` tags via `/admin/content_management/tags`. 
What appeared to be a disabled button on the frontend, actually turned out to be an `Unpermitted param :name` error. Once this error was resolved, I noticed that the `create` and `update` forms for tags were not properly displaying flash messages or redirecting (despite my logs confirming that the redirect took place!) as expected. Additionally, I noticed that the "Add Moderator" button on the `edit` form appeared to be disabled as well and also failed to display the expected success message upon adding a moderator to the tag. 
That being said, this PR not only adds `name` to `ALLOWED_PARAMS` within the `Admin::TagsController`, but it also adds `local: …

[15-Minute Fix] Fix Broken Admin Tags #create and #update Forms

---

app/assets/stylesheets/dashboard.scss
app/javascript/packs/analyticsDashboard.js
app/views/dashboards/analytics.erb
cypress/integration/analyticsFlows/analyticsNavigation.spec.js
spec/support/seeds/seeds_e2e.rb

At the moment, when a user is an admin of an organization they can't access their organization's statistics. Their personal stats are duplicated and appear on the organization's analytics page. This is because the `@organizations` variable was accidentally removed from `analytics.erb` as part of an old PR.
In order to fix this issue, I have added these back. As an additional change, I've grouped the organization links into a new `nav`, which I've labelled `Organizations menu`. This menu is only rendered onto the page if the user has organizations. If they don't, they should only see their own stats.
@aitchiss I know you wanted me to remove the `.active` class and use a data attribute instead. I tried this but I couldn't come up with an elegant way to keep track of the currently selected …

add org analytics menu if user has organizations

---

app/models/admin_menu.rb

The comments nav item should have been a part of the admin sidebar navigation, under the heading Content Manager (as per the figma document (https://www.figma.com/file/auEpfZTbdeXdjN5OIXxQ2K/Admin-Portal-Product-Framework?node-id=219%3A5605). 
I've added it to the sidebar. 
Go to the admin section and check that Comments show up under Content Manager in the sidebar.
will share this change with the people who need to …

[15 min fix] - Add the Comments Nav Item in the Admin Sidebar

---

docs/installation/imgproxy.md

[docs] Fix typo in imgproxy.md

---

app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/views/comments/_comment_header.html.erb

When the profile preview card work was completed, an extra margin-right property was included, causing the layout of the comment header to look slightly off.
This PR removes the extra margin. 
Fixes #14070
Before the fix:
After the fix:
None / small spacing adjustment
shared_
N/A

Fix spacing in comment header broken by preview card work

---

app/models/comment.rb
db/schema.rb

@andygeorge reported that strikethrough line was not rendered within links in live comments, however it worked elsewhere in posts, post previews and comment previews. The issue was that the html tag for strikethrough ```<del>``` was being stripped out by ```shorten_urls``` method. This PR modifies the ```shorten_urls``` method to not strip out the del tag. Further changes might be required to the method as and when unexpected bugs occur.
Resolves #13935
Note: PR unintentionally modifies ```schema.rb``` due to migrations. 
markdown for strikethrough within link.
```
[~~strikethrough~~](https://www.example.com)
```
Correctly rendered in live comments after bug fix
development process, or any of our internal teams? …

Bug Fix: Strikethrough markdown within a link is not rendered in live comments

---

yarn.lock

This changes is appearing locally for me and other open PRs.
n/a
n/a

Apply unstaged yarn.lock changes

---

app/views/users/_account_set_password.html.erb

This PR updates the password reset copy as requested in #14120.
Closes #14120.
n/a

[15-minute fix] Update password reset wording

---

docs/tests/e2e-tests.md

This PR adds some more detail on our approach to E2E testing, and some of the common issues we've come across so far.
N/A
Just have a read an check if it makes sense to you / if you have any suggestions 😄 
I've tried to update/add some more headings to make the docs readable/navigable, and I've also noted some of the accessibility considerations in writing e2e tests.
replace this line with details on why this change …

Add some more guidance to E2E docs

---

package.json
yarn.lock

We got a dependabot version update for `@storybook/addon-storyshots` (https://github.com/forem/forem/pull/14151) but I notice that we don't use it anywhere. We already have explicit snapshot testing of the components we want this for, and we have no real plans to utilise this dev dependency. So time to ✂️ ✂️ ✂️ 
https://github.com/forem/forem/pull/14151
N/A - no change to any behaviours
N/A
N/A

✂️  Remove storybook/addon-storysource ✂️ 

---

app/helpers/application_helper.rb
app/views/articles/show.html.erb
app/views/shared/_profile_card_content.html.erb

The markup of the button "follow" seems incorrect  according to the HTML validator. This PR replaces the old markup with a button tag.
The PR fixes several other HTML errors as described by the commits. 
https://github.com/forem/forem/issues/13289

Fix HTML markup in article pages

---

app/helpers/application_helper.rb

Remove CLS introduced in https://github.com/forem/forem/pull/14130 by adding a default text to the follow button.
https://github.com/forem/forem/issues/14164

add default text to follow button

---

cypress/integration/dashboardFlows/dashboardNavigation.spec.js

- Temporary skip for a flakey test
The dashboard navigation cypress test I introduced in https://github.com/forem/forem/pull/14128 seems to be occasionally flaking with an unhandled error from the app code. It's causing a bit of pain in CI, so this PR skips it for now while I investigate and fix.
https://github.com/forem/forem/pull/14128
N/A
N/A
replace this line with details on why this change …

Skip dashboard spec

---

app/workers/metrics/record_background_queue_stats_worker.rb
spec/workers/metrics/record_background_queue_stats_worker_spec.rb

We were missing stats for hours at a time on DEV this week because this worker was blocked behind other jobs. We *especially* need stats when Sidekiq is saturated, so this commit puts these stats at the highest priority.
The tradeoff should be minimal. These jobs take 6-30ms [once every 10 minutes](https://github.com/forem/forem/blob/e87dead7ade397975208d1bbf853db5d0d5d336b/config/schedule.yml#L5-L8).
replace this line …

Boost priority of queue stats worker

---

README.md

This PR removes Jacob from the core team members list in our README.

[15-minute fix] Update core team in README

---

app/lib/forem_stats_drivers/datadog_driver.rb

This PR solves two problems:
1. Redis cache usage is tracked under `redis-rpush` because they use the same Redis URL and `redis-rpush` overrides `redis`.
2. Sidekiq jobs can enqueue an unbounded number of other Sidekiq jobs. The instrumentation cost alone of enqueuing hundreds of thousands of other Sidekiq jobs inside a single trace can be prohibitive, similar to DEBUG-level logging. This commit wraps it in a conditional so it must be enabled explicitly and can be turned on and off at will without a code change.
- Next time a DUS fans out Sidekiq jobs across all users, posts, etc (any table with more than 100k records), there should be no corresponding memory spike
development process, or any of our internal …

Arrange Datadog Redis integrations more meaningfully

---

app/assets/javascripts/base.js.erb

- Mobile feed filters raises `Uncaught TypeError: Failed to construct 'URL': Invalid URL` when changing filters
Fixes #14126 
See https://github.com/forem/forem/issues/14126

Fix changing mobile feed filters raising errors

---

cypress/integration/articleFlows/previewProfile.spec.js

These tests are occasionally flaking in E2E tests due to the follow button not being initialized. I'm investigating this now and should have a fix shortly, but in the meantime, we can skip it to unblock builds.
N/A
Green build in Travis is all we need 🙂 
N/A
shared_

Temporarily disable preview profile spec pending fixes

---

cypress/support/commands.js

We've had some flaky tests in the past week or so related to login failures. This adds a login retry to the `cy.login` custom Cypress command.
N/A This is frontend testing infrastructure changes. …

[15 min fix] Added a retry for logging in a user for the custom Cypress login command

---

db/schema.rb

Several PRs have come in with unnecessary changes to `db/schema.rb` due to the fact that the state of that file and the state of the database have diverged and git optimizes for committing files wholesale — you have to explicitly tell it _not_ to do that every time.
I pulled down the schema from DEV's production DB and ran `rails db:migrate` to find out what changes need to be made and whether the state of development and production DBs have diverged. Surprisingly, most folks' development DBs and DEV's production DB are more aligned than this file is with either one, so this PR fixes that. Hopefully, with this change, we can stop asking people to remove their changes to `db/schema.rb`, at least for a while. …

Add constraints that are in the production DB

---

app/assets/stylesheets/views/dashboard.scss

- Dashboard's top and bottom posts cards had weird borders when hovered.
#14017 
shared_

Fix dashboard posts lists' border when hovered

---

.travis.yml
app/assets/javascripts/initializers/initializeCommentsPage.js.erb
cypress/integration/articleFlows/commentOnArticle.spec.js

HTTP 503 response status code is uncaught in promise when commenting cause comment to sometime to fail silently without any indicator 
Fixes #14227
See #14227 …

Add error handling and UI feedback when submitting comment resulting in a 503 error

---

cypress.json

We run Rspec tests with 3 retry attempts to help combat any flakiness. This PR introduces the same strategy for Cypress tests run in CI (the config amended does not impact running the Cypress tests locally via `yarn e2e`).
I've set the number of retries to 3, to match the Rspec config,  but I'm happy to change this if we feel a lower number would make sense.
Having a retry strategy will help us live with some small amount of flake. If a test still fails after retrying, we'll be able to identify it as exposing a genuine bug or having significant flake problems.
N/A
N/A
N/A
will share this change with the people who need to know about …

Add retries for cypress ci tests

---

app/controllers/stories_controller.rb
app/views/articles/_single_story.html.erb
app/views/stories/_main_stories_feed.html.erb
cypress/integration/articleFlows/pinArticle.spec.js

In #13807 we forgot that logged out users are served a server rendered feed that's different from that one served to authenticated users.
This PR adds the same behavior:
- pinned article first (unless pinned and featured are the same thing so it's going to be a combo pinned AND featured)
- featured article next 
- everything else after
#13807 
1. Log in, pin an article, log out, check the article is still pinned
2. Log in, pin an article with the cover image, log out, check the article is still pinned
3. Make sure the pinned article doesn't appear twice in the feed

[15 min fix] Show pinned article to logged out users

---

app/javascript/runtimeBanner/RuntimeBanner.jsx

The `useEffect` hook from Preact looks like it executes **after** the component renders. This causes the component to appear in view for a split second only to be removed because it shouldn't appear on screen.
closes #14247
Boot app locally and browse any page. The banner shouldn't appear visible for a split second, while it does when using `main` or on DEV. 
None - there are no changes to the existing elements.
Forem fleet deploy

Remove useEffect from RuntimeBanner component

---

package.json
yarn.lock

There's a bunch of bugs fixes/improvements and testing this to see if it helps with any of the flakiness.
#14078
N/A
N/A
shared_

[15 min fix] Upgraded to Cypress 7.7.0

---

app/controllers/admin/settings/general_settings_controller.rb

- Cache was not getting busted after settings update for application layout resulting in the header not getting updated with correct community name.
Closes #14129
Refer to #14129
shared_

Bust Content Cache after updation of Settings

---

app/views/podcast_episodes/show.html.erb

Add missing main-content id to podcast page 
See #14000
- [] Yes
- [] No, and this is why
shared_

fix podcast page missing skip functionality

---

cypress/integration/loggedOutFlows/showLoginModal.spec.js

- Skip a flaking e2e spec
This started flaking after the Cypress upgrade. I have a fix ready to go (https://github.com/forem/forem/pull/14271), but I'm having strange rspec issues both locally and in CI on that PR, so in the meantime I'm skipping the test to unblock our builds.
N/A
Just needs a green build
N/A
shared_

Skip login modal flaky spec

---

README.md

This PR updates the core-team list in README.md file. Added **rajat** to core team …

Add Rajat to core team list

---

app/controllers/profile_preview_card_controller.rb
app/controllers/profile_preview_cards_controller.rb
app/javascript/packs/commentDropdowns.js
app/views/profile_preview_card/show.html.erb
app/views/profile_preview_cards/show.html.erb
app/views/profile_preview_cards/show.json.jbuilder
config/routes.rb
spec/requests/profile_preview_cards_spec.rb

To complete [RFC 222](https://github.com/forem/rfcs/pull/222) we need to be able to fetch via async JS some info about the user's profile. The content mimics the HTML representation, without the profile image which is already available on the client.
This PR only adds the endpoint, @aitchiss will later make use of it in the frontend
https://github.com/forem/rfcs/pull/222
1. start the app
2. Go to `http://localhost:3000/profile_preview_cards/:id` (`:id` is the ID of a user) to see the HTML representation
3. Go to `http://localhost:3000/profile_preview_cards/:id.json` to see the JSON representation
4. Make sure the hover on the profile preview cards still works
development process, or any of …

Add JSON representation of Profile Preview Card info

---

Gemfile.lock

When working on the project locally this line keeps popping up for me in `Gemfile.lock`. I'm not even sure if this is an RVM thing because it happens without having to run anything (something in the background is adding it but I don't know what it is).
This started to happen to me when I started working with an M1 Macbook. So maybe it's just a platform we need to include so we don't have to deal with this locally, similar to #13413
The annoying part is that I sometimes need to switch branches and I can't because git complains that I should "stash my changes before changing branches". But as soon as I get rid of this line it comes back up, so it becomes a race to see if I can switch branch before the line gets popped back in again 😅 
N/A
N/A
N/A

Add ruby platform to Gemfile.lock

---

app/controllers/api/v0/articles_controller.rb
app/views/api/v0/articles/me.json.jbuilder
spec/requests/api/v0/articles_spec.rb

The API endpoint `/api/articles/me` is declaring to have `reading_time_minutes` in its documentation but the field isn't actually present in the response.
Fixes https://github.com/forem/forem/issues/14316
1. create a new API key at http://localhost:3000/settings/account
2. publish an article for your own user if you don't have one
3. Check that `curl -H "api-key: API_KEY" localhost:3000/api/articles/me` has the `reading_time_minutes` field with the expected value

[15 min fix] API: Add reading_time_minutes to /api/articles/me

---

package.json
yarn.lock

This reverts commit 47543f6da8266c2c78b8cad9af652c374c9c05ae.
The PR https://github.com/forem/forem/pull/14324 contained a version bump to `pretty-format@27.0.6` which required a later version of node than our buildkite builds can currently use. As a result, all of our latest buildkite builds are failing with the error:
```
error pretty-format@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 \|\| ^12.13.0 \|\| ^14.15.0 \|\| >=15.0.0". Got "14.14.0"
--
  | error Found incompatible module.
```
This PR reverts the change until we are able to upgrade the node version in buildkite (this is a work in progress with systems team)
N/A
We just need to check all the build checks pass
N/A
_Will this PR introduce a change that impacts Forem members or creators, …

Revert "Bump @testing-library/cypress from 7.0.6 to 8.0.0 (#14324)"

---

app/assets/javascripts/base.js.erb
app/views/articles/search.html.erb
app/views/layouts/application.html.erb

Add a live region to page content to indicate when the route is changed
Related to #14001 
Turn on the screen reader, typing something into the search bar and the first result should be announced 
or in a …

Add aria-live announcement to notify users of the route change

---

.gitattributes
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
package.json
scripts/build_containers.sh
scripts/release
scripts/stage_release

This PR adds scripts to stage and create releases for a given release channel, date, and patch.
- https://forem.team/jamie/versioning-this-is-the-way-50ap
- https://github.com/forem/rfcs/blob/5dc4aeafbd22804b3efa296def7cb7a6f5cd388e/text/0037-add-versioning-to-forem-forem.md#release-channels
- Running `scripts/stage_release` will push the latest changes on `main` to `stable-next`
- Specifying `--channel beta` will stage the `beta` release channel in the `beta-next` branch instead of `stable` via `stable-next`
- Specifying `--remote github` will use `github` instead of `origin` as the git remote
- Specifying `--from my_branch` will pull changes in from `my_branch` instead of `main`
- Running `scripts/release` will tag a release from the specified release channel (defaults to `stable`) and …

Add support for versioned releases

---

.github/ISSUE_TEMPLATE/config.yml

Adding a config.yml to give more options in our issues template. Will likely add some for documentation in the near future.
- [X ] Issue template update
After discussing our issue templates in our forem/forem repo with Peter, we decided to add more templates to better direct people to the appropriate places for bug reports, features, and discussions. I will add a documentation link in the near future once we have the developer docs finalized.
- [ x] No, and this is why: No tests needed to add issue config file to the repo.  …

Create new Issue templates

---

cypress/integration/seededFlows/articleFlows/previewProfile.spec.js

This PR skips a flaky test within `previewProfile.spec.js` by adding a `.skip` to the specific `describe` block that failed per @nickytonline's suggestion.
Relates to issue #14384 
All checks should pass. ♻️ 
N/A
shared_
N/A

Skip Flaky previewProfile.spec.js Test

---

app/views/devise/confirmations/new.html.erb

I added some styles for a class name but forgot to commit the actual classname [in the previous PR](https://github.com/forem/forem/pull/14259) 🤦🏽‍♀️
https://github.com/forem/forem/pull/14259 …

Add Missing Class Name 

---

app/views/admin/overview/index.html.erb
app/views/layouts/admin.html.erb

Small tweaks to enhance usability for small screens in the Admin area
#14313
2. Browse the admin area using a mobile device or use the Dev Tools to mimic a mobile device
3. Cards & Headers should be slightly better aligned/framed in small screens
- Also important to check pages don't break on larger screens
**Current layout (no margin/padding):**
**This PR (adds padding for better display of cards):**
None - These are only some CSS tweaks throughout the admin area

[15-min fix] Small tweaks for small screen usage in Admin

---

app/javascript/article-form/components/ArticleCoverImage.jsx
app/javascript/article-form/components/ImageUploader.jsx
app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
app/javascript/article-form/components/__tests__/Form.test.jsx
app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js

Both the "Add a cover image" and "Upload image" inputs in the article editor had some accessibility issues, and as a result we also had to skip some rules in our frontend tests. 
This PR refactors the markup to keep the same functionality but making sure that we don't nest the input inside of a `button` element. We do however want the `button` element when a user is using a native iOS device, in which case we don't show the 'normal' desktop input but instead surface a button with enhanced native functionality.
I don't have an iOS device, but I tested this out on the simulator and all seemed to be working well. Definitely keen for someone who has a real device to test this PR too 😄 
Fixes #13947
- Log in and click 'Create post'
- Add a cover image, and check it works as expected
- Try …

Refactor problematic markup for upload image (#13947)

---

app/services/podcasts/get_media_url.rb
spec/services/podcasts/get_media_url_spec.rb

When checking if a podcast episode is available via https, we currently fail with an error if an SSLError is raised (certificate problems would be the most obvious situation leading to this). The intent in the code appears to be attempting to fetch the resource via an edited https url when given an http link, and if that fails to use the http link. The actual behavior is to fail to create or update the episode, instead of downgrading to http when https fails.
Unit test seems sufficient.
None. …

handle openssl errors when checking podcast episode for https

---

app/javascript/packs/base.jsx

Quick enhancement to use optional chaining instead of if statement. 
Feedback based on https://github.com/forem/forem/pull/14259#discussion_r685143584
https://github.com/forem/rfcs/pull/190
Tests should pass.  …

Tiny Enhancement: Using Optional Chaining

---

yarn.lock

Looks like the yarn lock is slightly out of step of where it should be - this commits the correct version
N/A
- when you run `yarn install` locally, you shouldn't see any changes to the yarn lock
N/A
shared_

Commit missed yarn lock changes

---

package.json
yarn.lock

This reverts commit 82c24417e0007cd19c9eafa6309e36905acdbfd8.
- Revert of a dependency change
After merging #14474 our buildkite builds were erroring with:
```
error jest-regex-util@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.14.0"
error Found incompatible module.
```
This is due to the known issues with the node version in buildkite, and until we're able to bump this to latest we might have to wait on this changes.
#14474
- Build should pass
- If you're also using node 14.14 locally, you should be able to run `yarn install` successfully
N/A
will …

Revert "Run `yarn upgrade` (#14474)"

---

app/javascript/readingList/readingList.jsx
cypress/integration/seededFlows/readingListFlows/readingList.spec.js
cypress/integration/seededFlows/readingListFlows/readingListArchive.spec.js

- https://github.com/forem/forem/issues/14469 reports `The reading list item count (in the title) isn't reactive`
- The issue was able to reproduce. The reason is that there was forgot to update`itemsTotal` after archived or unarchived. I just make minor changes to get the bug fixed.
Closes https://github.com/forem/forem/issues/14469
- Reproduce the bugs https://github.com/forem/forem/issues/14469
> The reading list item count won't change.
- Fixed. The reading list item count is changed after archived and unarchived.
No. There are no UI changes. …

Fix reading list item count issue #14469

---

app/models/navigation_link.rb
spec/models/navigation_link_spec.rb

Allows the regex which is used to test SVG match multiline SVGs. Fixes #14334 
Closes #14334 
NA
NA
shared_
NA

Navigation Link: fix regex to allow multiline SVG

---

docs/frontend/preact.md

[Preact page](https://docs.forem.com/frontend/preact/) in documentation contains incorrect path to commonly-used PropTypes, this PR replaces it with up-to-date path.
shared_

Fix PropTypes folder path typo in documentation for Preact

---

app/javascript/packs/articlePage.jsx

A while ago #13809 reintroduced `navigator.share` as an option in the Post dropdown. The PR added the "Share Post via..." option, and we started a conversation over the value of each option in that dropdown. We didn't arrive at an absolute/final decision but instead left Ahoy in place to understand which options are being used the most/least, with the intention to make data-driven decisions down the line.
We now have about a couple months worth of usage, and the conclusion I see is that all the specific share intents (i.e. "Share with Reddit") do get a respectable number of clicks, so we should keep them. The vast majority indeed comes from "Share Post via...", but the other options combined take about 28% (4,622) of the total use (16,323). For simplicity this is not taking into account …

Remove ahoy from Share Post dropdown

---

app/controllers/api/v0/instances_controller.rb
spec/requests/api/v0/instances_spec.rb

This PR adds the registered user count to the instance API.
https://discover.forem.com
N/A
N/A
No

Add user count to instance API

---

app/javascript/actionsPanel/actionsPanel.js
cypress.json
cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
cypress/integration/seededFlows/tagsFlows/followTag.spec.js
cypress/support/commands.js
spec/support/seeds/seeds_e2e.rb

We were seeing some frontend errors pop up when adding and removing tags as a moderator (either from `/mod` or from `mod/tagname`). The problem was caused by trying to get a handle to the article iframe's tag section to add/remove the edited tag - I've updated that code, and added Cypress tests to prevent future regression.
Fixes #14554
Log in as a trusted user, and for both the tag moderation page ('/mod/tagname') and the general moderation page ('/mod'), try:
- adding a new tag to one of the articles 
- removing a tag from one of the articles
In each case you'll need to add some text for the 'reason' field, and you should see a snackbar appear with a confirmation, as well as the actual tags updating in the article preview UI. 
https://user-images.githubusercontent.com/20773163/130438638- …

Fix error adding and removing tags as mod

---

package.json
yarn.lock

This reverts commit 6828fe1dcd46ba4a841fbe36cb707b9f34979d31.
Reverting due to breaking changes in this dependency bump. We didn't identify this at PR stage likely because it's only affecting local development and not production builds
#14572
We just need to check that you can locally run the app again 😄 
N/A
replace this line with details on why …

Revert "Bump webpack-dev-server from 3.11.2 to 4.0.0 (#14572)"

---

app/views/admin/settings/forms/_authentication.html.erb

In the past we had this message appear to inform creators that a reboot was needed. At some point we changed the way auth keys worked and it no longer requires a reboot for changes to take effect.
2. Enable/Disable OAuth provider
- It shouldn't require reboot to take effect
3. Reset credentials (Twitter allows to do this easily)
- Authentication should start to fail
- Once updated with the new credentials it should allow login again
None

Remove outdated notice in authentication config

---

app/controllers/dashboards_controller.rb
config/environments/development.rb
config/environments/test.rb

- [*] Bug Fix
- [*] Optimization
Resolves issue #14429 
The N+1 problem is [triggered here](https://github.com/forem/forem/blob/628202646b93c9a25a8142540aa47705e049a55e/app/views/dashboards/_dashboard_article_row.html.erb#L25)
You need to make sure that you are running server in your local. Make sure you are logged in. You need to have a posts that are connected to series. Load your [dashboard page](http://localhost:3000/dashboard) . You should see a bullet warning down at the bottom left. 
Using this new branch you should not see such a warning. 
None
- [*] No, and this is why: too small of a change. Let me know otherwise.
will share …

In dashboard show api eager load collection with articles

---

app/javascript/leftSidebar/TagsFollowed.jsx
app/javascript/packs/homePage.jsx
app/views/layouts/_sidebar_tags.html.erb

This adds temporary ahoy stats for any clicks on a tag in the left sidebar, or on the cog icon to manage those tag settings. 
N/A
N/A
N/A
shared_
We can check we are receiving the stats as expected in ahoy

Add temporary ahoy stats for tag sidebar clicks

---

package.json
yarn.lock

I ran `yarn upgrade to deal with some long-standing Dependabot alerts.
n/a
n/a
n/a

Run yarn upgrade & add resolution for glob-parent

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/themes/night.scss
db/schema.rb

So far we've been using ~11 shades of grey. Greys tinted towards blue shades. While thinking about theming for other communities we came up with conclusion that cold grey may not look well (and conflict) with some colors picked by admins. Pure grey (not tinted towards cold or warm shades) should be much more bullet proof. Hence this update. It takes away a tiny bit of uniqueness from our original branding but it sets us up in much better position when it comes to future theming.
We may want to tweak exact color value for each shade in future, but for now it should be just fine.
This adjusts greys for both: default and night themes.
- [Theming](https://docs.google.com/document/d/13frDxjLeGUHKOP8gmXjbFl3mCy7HPOGS-VXCOERiNdc/edit).
Play with the UI and check if there's anything jarring. Keep …

Warmer shades of grey

---

.gitpod.dockerfile

Upgrades the node version to 14.7.6 for the Gitpod container.
- Load the branch in Gitpod, https://gitpod.io/#https://github.com/forem/forem/tree/nickytonline/update-gitpod-node-version
- There are other issues still in Gitpod, but in the Forem server terminal session, run `node -v`. It should be `14.7.6`.
N/A Node version change.
replace this line …

Updated node version in Gitpod

---

.gitpod.yml
gitpod-init.sh

For some reason in the .gitpod.yml file, the `init` command does not work after the echo commands even with `&&`. The init command has been converted to a script instead.
#14697
#14696 (blocks this PR until it's merged)
- Startup Gitpod for this branch, https://gitpod.io/#https://github.com/forem/forem/tree/nickytonline/fix-gitpod-init
- In the Forem Server terminal session, it completes successfully.
N/A build infrastructure …

Added gitpod-init script

---

.github/PULL_REQUEST_TEMPLATE.md

Adding additional clarification for how the team can communicate that they worked on the Admin area so Community Success can update the appropriate docs.
Updating ReadMe to Add additional clarification for how the team can communicate that they worked on the Admin area so Community Success can update the appropriate docs.
replace this line with …

Update Forem core team only section

---

app/assets/stylesheets/base/layout.scss
app/assets/stylesheets/config/_import.scss
app/assets/stylesheets/views/confirm-email.scss
app/views/devise/confirmations/new.html.erb
app/views/shared/authentication/_forem_creator_signup.html.erb
cypress/integration/creatorOnboardingFlows/confirmEmail.spec.js

This fixes issue with Forem background for email confirmation view.
- Closes #14656 …

Forem background

---

app/controllers/api/v0/instances_controller.rb
spec/requests/api/v0/instances_spec.rb

This adds the context from `FOREM_CONTEXT` to the instance API.
N/A
Hit the instance API endpoint and see that `context` has been added 🎉 
N/A
shared_

Add context to Instance API

---

app/controllers/tags_controller.rb
app/lib/url.rb
app/models/tag.rb
spec/factories/tags.rb
spec/models/tag_spec.rb

Reverts #9006 
Permit non-ascii tag names. The reason we didn't permit this was to prevent a rendering issue - that's been removed since we starting sanitizing tag names when building URLs for rendering.
fixes https://github.com/forem/forem/issues/14422
Any of these would be good scenarios to add as test cases or adjust existing tests.
:heavy_check_mark: Add tags with non-english/non-ascii characters like `miscelânea` or `español` to an article.
:heavy_check_mark: Follow tag links to tag page.
:heavy_check_mark: Subscribe to one of those tags (visit /t/español and Follow)
:heavy_check_mark: Add a tag moderator for one of those tags (/admin/content_manager/tags/:tag_id/edit). Remove tag moderator and confirm it's successful.
:heavy_check_mark: Import articles from an rss feed using …

Relax tag validation restriction to permit non-ascii strings

---

app/controllers/api/v0/instances_controller.rb
app/lib/constants/settings/user_experience.rb
app/models/settings/user_experience.rb
app/views/admin/settings/forms/_user_experience.html.erb
spec/requests/admin/configs_spec.rb
spec/requests/api/v0/instances_spec.rb

This PR allows Forem creators to opt-in/out of being listed in the [Forem Directory](https://discover.forem.com)
N/A
Fire up the app locally and adjust the settings under **User Experience and Brand** in the settings (http://localhost:3000/admin/customization/config)
N/A
shared_

Add display_in_directory setting

---

app/views/tags/index.html.erb

This PR adds a shortcut to access "Following tags" from the "Tags" page.
shared_

Shortcut for "Following tags"

---

app/assets/stylesheets/components/stories.scss
app/assets/stylesheets/profile-preview-card.scss
app/views/layouts/_main_nav.html.erb
app/views/layouts/_nav_menu.html.erb
app/views/layouts/_sidebar_tags.html.erb
spec/system/homepage/user_visits_homepage_spec.rb

Tiny style fixes and updates:
- feed list padding (mobile)
- missing padding on nav
- dropping divider above social links
- updating one icon.
Not providing any screenshots as these are mostly minor changes.
shared_

Style updates

---

app/javascript/admin/controllers/config_controller.js

All providers except apple use a common key/secret form partial, but
the apple authentication section uses client_id, key_id, pem, and
team_id.
Assuming all four of these are required, when the enabled provider
name is 'apple', check for those values. For other providers (github,
facebook, etc) only check secret and key as before.
fixes #14749 
Edit authentication settings at http://localhost:3000/admin/customization/config
Add a github key but leave secret blank
Save settings - modal should appear saying github settings cannot be saved (missing required data).
Enable apple.
Supply some fields (client  id, pem) but leave at least one blank.
Update settings -  modal should appear 
Fill in all four apple fields. Update settings.
snackbar should appear saying settings updated successfully. …

Check required inputs for apple authentication

---

app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/assets/stylesheets/components/dropdowns.scss
app/assets/stylesheets/components/stories.scss
app/assets/stylesheets/views/profile.scss
app/javascript/CommentSubscription/CommentSubscription.jsx
app/views/articles/_actions.html.erb
app/views/comments/_comment_header.html.erb
app/views/dashboards/_dashboard_article.html.erb
app/views/dashboards/_dashboard_article_row.html.erb
app/views/layouts/_nav_menu.html.erb
app/views/users/show.html.erb

This PR mainly refactors padding for our dropdowns and fixes couple CSS bugs.
- Dropdowns should now have slightly increased padding so if you click through these and nothing looks off to you then it's probably good :)
appropriately.
[`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHAN …

Little frontend refactor

---

gitpod-init.sh

Adds the GitHub CLI to our Gitpod setup. Note that [brew is supported in Gitpod](https://www.gitpod.io/blog/brew).
Once the Gitpod installation is complete, type and run `gh` from a terminal session. The output should be the GitHub CLI help.
```
Work seamlessly with GitHub from the command line.
USAGE
gh <command> <subcommand> [flags]
CORE COMMANDS
browse:     Open the repository in the browser
gist:       Manage gists
issue:      Manage issues
pr:         Manage pull requests
release:    Manage GitHub releases
repo:       Create, clone, fork, and view repositories
ACTIONS COMMANDS
actions:    Learn about working with GitHub actions
run:        View details about workflow runs
workflow:   View details about GitHub Actions workflows
ADDITIONAL COMMANDS
alias:      Create command shortcuts …
```

Added GitHub CLI to Gitpod.

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
app/views/shared/_profile_preview_card.html.erb

Padding fix for profile preview cards - which I have unintentionally introduced with some earlier PRs 🤷‍♂️ 
appropriately.

Padding fix for profile preview cards

---

app/javascript/actionsPanel/actionsPanel.js
app/javascript/actionsPanel/initializeActionsPanelToggle.js
app/javascript/packs/articleModerationTools.js
cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
spec/support/seeds/seeds_e2e.rb

When I fixed some errors adding/removing tags from the mod center in https://github.com/forem/forem/pull/14566, I inadvertently introduced that same bug over on the article page mod tools 🙈 
This PR fixes it and introduces some tests to cover this path for moderation too.
Closes https://github.com/forem/forem/issues/14754
From an article page:
- Click the moderator button at the bottom right
- Add a tag to the post - it should result in a snackbar being shown, and the tag appearing on the article
- Remove a different tag from the post - it should result in a snackbar being shown, and the tag disappearing from the article
From the moderator center - `/mod`
- Repeat the above steps for any article and check it works here too
N/A - there are some accessibility issues in this feature as a …

fix error adding removing tags from article mod tools

---

app/javascript/organization/__tests__/OrganizationPicker.test.jsx
testSetup.js

When I made the changes to upgrade jest in #14722 I must have missed noticing some error output in the console while running the tests. We had several tests now complaining about `Not implemented: window.computedStyle(elt, pseudoElt)`. This is a known issue (https://github.com/nickcolley/jest-axe/issues/147) and we were already previously working around this in one of our test files.
I've added a workaround to our `testSetup` file, so that it applies to all tests until the underlying issue is resolved.
#14722
- Run the tests locally using `yarn test`
- Check the console for error messages - you shouldn't see any
N/A
development process, or any of our internal teams? If so, please note how …

Fix getComputedStyle issues in jest tests

---

app/javascript/utilities/connect/getUnopenedChannels.jsx

The onboarding is currently failing because it seems like the connect-link element does not exist hence its failing to call the onclick on that element.  See screenshot attached.
Go through onboarding flow and check that its working.
updated. I have filled …

Onboarding fix

---

.gitpod.dockerfile
gitpod-init.sh

The GitHub CLI currently installs in Gitpod, but if you restart your Gitpod instance the installation is not persisted. This PR fixes that.
1. Navigate to https://gitpod.io/#https://github.com/forem/forem/tree/nickytonline/make-github-cli-install-permanent-on-gitpod
2. From an integrated terminal in the IDE, type `gh`. It should display the GitHub CLI help.
N/A This is Gitpod configuration only.
appropriately.
or in a …

Made GitHub CLI install permanent in Gitpod

---

app/views/articles/_collection.html.erb

Fixes a skipped heading level a11y violation when an article is part of a series.
This was discovered while doing a dry run today of the a11y workshop I'm running with @aitchiss. @msarit and I used this real issue for the open-source workshop.
Closes #14800
1. Navigate to http://localhost:3000/new to create two blog posts
2. Ensure each post has the same series. If you're creating the first post, the series won't exist yet.
2. Run the WebAIM WAVE browser extension on the page. If you haven't already, [install the WAVE browser extension](https://wave.webaim.org/extension/).
3. The series header will not report a skipped heading level a11y violation.
Improves the accessibility of posts that are part of a series …

Fixed article series skipped heading level violation

---

README.md

fix installation URL

---

app/models/github_issue.rb

When a PR has no body, we try to post no `body` to /markdown and ask github to render it. "body" is a required field (see https://docs.github.com/en/rest/reference/markdown#render-a-markdown-document) and an unhandled error is returned (the user sees a 422 response?).
Instead, give an empty `processed_html` body for the issue.
fixes #14803
To reproduce/exercise:
```
{% github https://github.com/ospatil/nats-server/pull/1 %}
```
in main this raises a Whoops, something went wrong. On this branch you get the very slim preview with the "View on Github" button linking to the PR.
None. …

If there is no body of the linked issue or PR, don't render markdown

---

.gitignore

Adding `.pryrc` to the local `.gitignore` so people can customize their own environment. Inspired by @citizen428's post

Add .pryrc to gitignore

---

app/models/user.rb

Instead of explicitly checking `user.has_role?(:creator)`, this PR adds a method to see if a user is the creator of the Forem instance. This follows the pattern in the user model for checking for other roles, like `admin`.
#14659
N/A
N/A
https://github.com/forem/forem/blob/2494076d79a9901d3c27aa77077765ccc79aef58/spec/lib/data_update_scripts/backfill_creator_role_for_first_super_admin_spec.rb#L6-L15
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees= …

Added the creator method to the user model

---

app/views/notifications/_nav_menu.html.erb
config/locales/en.yml
config/locales/fr.yml

This follows existing patterns of internationalization to translate the filters on the notifications page.
The only added translation is "All".
The use of `pluralization` is following existing patterns. This may not be the most scalable as we broaden translations, but I think appropriate for now.
https://dev.to/devteam/forem-hacktoberfest-let-s-internationalize-404n

Translate notification filters

---

.travis.yml
bin/test-console-check

Add DISABLE_SPRING into .travis.yml so it's available to everyone.
Follow up to https://github.com/forem/forem/pull/14691
test should pass 
n/a

Add DISABLE_SPRING to .travis.yml

---

app/assets/stylesheets/scaffolds.scss
app/controllers/application_controller.rb
app/views/layouts/application.html.erb

Quick removal of dead code related to "application shell" service worker logic we no longer use.
At some point we could additionally remove the service worker endpoints altogether, but today they still may serve a purpose of "self-destruction" for longterm installs (Or do they definitively expire after some period?)
All in all this is a quick fix to remove a few lines of unused code.

✂️ Remove dead app shell code

---

app/models/organization.rb
app/models/user.rb
app/views/users/_meta.html.erb
app/views/users/show.html.erb
app/workers/reactions/update_relevant_scores_worker.rb
spec/models/user_spec.rb
spec/workers/reactions/update_relevant_scores_worker_spec.rb

This PR allows spam trigger keywords to trigger an auto-vomit reaction on users based on the name they choose the same way we have this functionality for articles.
Presumably if we are attempting to ban "Abu Dhabi Call Girls" from article titles, the same logic should apply to user names because user profiles are a spam vector due to the title tag and h1 being the name of the user.
Auto-vomit is not a destructive action, but it will have an immediate action on the user. Their _score_ will be lowered below 0 as will their posts' scores.
However, we have not actually been functionally re-calculating user scores. So this PR also fixes that oversight and adds a check for score being less than zero as an indicator for whether to apply `noindex` HTML attributes.
updated. …

Add conditional autovomits to user name and improve user score recalc

---

app/javascript/chat/chat.jsx

I know we're removing Connect, but this fixes a lint issue that is blocking the eslint-plugin-react upgrade.
Blocking #14944
N/A
N/A
appropriately.
replace this line with details …

Fixed lint issue

---

README.md

Jeremy started at Forem on October 4, 2021

Adding jeremyf to core team

---

config/locales/views/editor/fr.yml

Added the French translations
#14888 
[Changes …

locales/views/editor - added FR translation

---

app/controllers/admin/users_controller.rb

When we show the reports on the user edit page in admin, we want to know about reactions to the user, rather than user created reactions (similar to the way we only show reactions to the user's articles or their comments, and not reactions they made for other user's articles or comments).
I think neither the callbacks (`has_many :reactions, dependent: :destroy`) nor the `Users::DeleteActivity` class handle removing reactions _to_ the user object when we remove it - if the user's showing this error are moderators (able to add vomit reactions to users that are subsequently deleted) this makes sense around the surrounding context.
Fixes #15242 
https://github.com/forem/forem/issues/15245 seems to be the underlying issue with the data (which is not corrected here). …

Show reactions to the user, rather than user created reactions to other users

---

app/controllers/admin/application_controller.rb

Update the help icon URL for the config page. 
`https://admin.forem.com/docs/advanced-customization/config/` now redirects to the first nav item  `https://admin.forem.com/docs/advanced-customization/config/api-tokens` within the forem.admin system. Hence, we can simply link to `https://admin.forem.com/docs/advanced-customization/config/`.
https://github.com/forem/rfcs/issues/238
Go to the config page and test that the help icon directs to `https://admin.forem.com/docs/advanced-customization/config/` which in turn redirects to `https://admin.forem.com/docs/advanced-customization/config/api-tokens`
[Forem Accessibility …

Update the config/settings link for the help icon

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feeds/basic.rb

This is a hypothetical and experimental interface change.  The goal of
the change is to begin looking at what a "Feed"'s method interface would
look like.
I would like to reduce the controller logic necessary for deciding on
different strategies, and instead defer to a builder/strategy lookup
pattern.
This inter-relates to https://github.com/forem/forem/pull/15220, #15180, and forem/rfcs#314, as I work towards understanding the feed algorithm. And #15180
None.
None

Refactoring to extract common interface

---

.travis.yml
app/assets/javascripts/initializers/initializeCommentsPage.js.erb

There are some issues that are only surfaced during asset precompilation (typically problems with yarn dependencies, or with javascript syntax compatibility).
We don't build containers (which includes an asset precompile step) for PR's from external contributors.
Add an asset precompilation step to the "miscellaneous" node (lint, jest, storybook) to ensure we're exercising this path during testing, and not surprised when we merge a PR to main.
I'll introduce a failing item to confirm. (looks sane https://app.travis-ci.com/github/forem/forem/jobs/546569306)
None …

Add assets precompile check to the miscellaneous tasks node

---

app/views/articles/_comment_tree.html.erb
app/views/articles/_full_comment_area.html.erb

Shoutout to @citizen428 for the suggestion of leveraging Rails' collection cache feature.
After a bit of pairing with @jgaskins , we agreed to give this implementation a chance. The result looks very promising.
supersedes https://github.com/forem/forem/pull/13692
The performance gain here is quite significant on pages with a lot of comments.
before
```
Cache read: views/articles/_full_comment_area:0bb1b39873ecd90c9a30200586703ca6/comment_root_cached_tree/comments/14-20211103172125446349 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>3600, :race_condition_ttl=>nil})
Read fragment views/articles/_full_comment_area:0bb1b39873ecd90c9a30200586703ca6/comment_root_cached_tree/comments/14-20211103172125446349 (1.9ms)
Cache read: …
```

Add collection cache in articles/full_comment_area

---

spec/requests/stories/tagged_articles_spec.rb
spec/services/articles/enrich_image_attributes_spec.rb

Fixed a couple of warnings in specs

[Quick Fix] Fixed a couple of warnings in specs

---

lib/data_update_scripts/20211109161231_migrate_themes_again.rb

Because of the way the the scripts to run works, there's always
already a script with this file name by the time this starts.
Remove the guard clause and let it run.
Fixes an issue reported by users with themes we had intended to remove which stopped working after #15237
The issue with the original attempt to guard against subsequent runs comes from the timing of the script's insertion into the tracking table and the timing of the enqueued jobs execution. In deployment the script with this filename is always present.
#15237 removes old values from the enum (causing the error)
#15225 original script
Update one row of the users settings table to have config_theme = 1 
`bundle exec rake data_updates:run` to perform pending scripts
confirm user's setting was migrated to config_theme = 0
_If …

Rerun migrate themes script

---

app/views/layouts/admin.html.erb

Adds a skip link to admin pages
Closes #15339
1. Navigate to http://localhost:3000/admin
2. Use the tab key to navigate the page
3. The first focusable element will be the skip link
4. Press ENTER
5. continue to tab. Notice the next thing that has focus is the first focusable element in the `<main />` tag.
https://user-images.githubusercontent.com/833231/141027695-0d0fe4d6-34c2-44ed-b3c1-ef59461c7a5d.mp4
Makes the page more accessible by allowing an admin to jump right to the main content of the page. …

Added a skip link for the admin area

---

app/javascript/articles/components/Meta.jsx
app/javascript/common-prop-types/article-prop-types.js
app/javascript/common-prop-types/index.js
app/javascript/common-prop-types/organization-prop-type.js
app/javascript/leftSidebar/TagsFollowed.jsx
app/javascript/organization/OrganizationPicker.jsx

This cleans up some of the prop type errors shown in the console on the home page (no change to any functionality)
#14837
- Run the app locally
- Check your console for any errors on the home page (`/`) - no prop type errors should be there
- Home feed should render as before (both logged in and out)
- Organization picker should continue to work as before on the 'create post' page (we should check this as one of the refactors affected props to this component too)
None …

Fix some prop type errors on the home page

---

app/services/badges/award.rb
spec/services/badges/award_spec.rb

Don't award badges to banished users. 
https://github.com/forem/rfcs/issues/323
Unit test should be sufficient. If you wanted to simulate this end to end - banish a user, then award them a badge.
None
appropriately. …

Skip badge awards for spam accounts

---

app/views/credits/new.html.erb
spec/views/credits/new.html.erb_spec.rb

Fix an error in the view template for /credits/purchase (the new action) which was causing the page not to display. 
Resolves NoMethodError for `User#dark_theme?` by referencing the current user's setting instead.
https://app.honeybadger.io/projects/66984/faults/82511309
https://github.com/forem/forem/pull/15237 (introduced change as part of theming cleanup)
visit /credits/purchase
on main: no method error raised 
on branch: dark or light theme preference is respected (change your theme in settings/customization : appearance) 
None …

Let users purchase credits

---

app/helpers/application_helper.rb

Fallback on empty string as well as nil to the site default tag color
updated. …

Check for presence rather than falsey when detecting tag color

---

app/assets/stylesheets/components/stories.scss
app/views/articles/show.html.erb
app/views/notifications/shared/_article_preview.html.erb

This PR fixes little UI issues with wrapping long lines of tags to the next line.
- Closes #15357

Tags wrapping fix

---

app/models/display_ad.rb

- [?] Bug Fix
Prior to this commit, this instantiation of `Redcarpet::Markdown` was
different from the other instantiations.  The other ones all included
the second paramenter (e.g., `Constants::Redcarpet::CONFIG`).
My question is, should we (or can we) be using the same configuration in
all cases?
This relates to forem/rfcs#296 and #15338
Maybe none.
None?
Nope

Discussion: Using same markdown config as other instances

---

app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/Meta.jsx

Due to a typo in the Preact `Meta` component, we were rendering `<time>` elements without the relevant `dateTime` attribute, wherever we used the Preact-generated feed cards (e.g. the logged in home feed).
N/A
- Load the app locally and visit the home feed
- Using the dev tools inspector, look at the published date for a story card:
- Check the HTML element has the `dateTime` attribute as expected, e.g:
N/A
[Changes …

[15 min fix] Fix timestamp error in Preact story cards

---

app/models/article.rb
app/services/articles/feeds/basic.rb
app/services/articles/feeds/large_forem_experimental.rb
app/services/articles/feeds/latest.rb
app/services/articles/feeds/tag.rb
app/services/articles/feeds/timeframe.rb

This commit removes a handful of magic numbers and instead relies on a
constant.
This has a small impact in that the Basic feed will now return 50
articles instead of 25.  However, normalizing the feed pagination window
size helps reduce some oddities in reporting.
In addition, this might be something we consider giving administrators
the ability to set (with default options, because we shouldn't allow
page sizes of 10_000 as that's a massive memory hog).
Related to #14709
None.
None

Normalizing feed page size

---

app/controllers/registrations_controller.rb
app/lib/constants/settings/authentication.rb
app/models/settings/authentication.rb
app/views/admin/settings/forms/_authentication.html.erb
spec/models/settings/authentication_spec.rb

Prior to this commit, we had filtering options for email registration:
1. Specific allowed domains.
2. Implicitly allow all domains if no allowed domains specified.
With this commit, we add another option: The adminstrator may block one
or more domains from registering.
Closes forem/rfcs#281
At `/admin/customization/config` you should be able to add one or more blocked domains.  Those are persisted in the database.  Then try to create a new account with an email address from a blocked domain.
I have tested this locally, and extracted a method to assist in the logic of allowed/blocked domains.
Note: I'm eager to get this out to the success team.
None …

Adding ability to block domains from registration

---

app/models/admin_menu.rb

Gives a 404 (no route /admin/apps/events).
Events were removed in #15062 but the sidebar link remained.
Visit /admin/apps/welcome 
Should not see "Events" under Apps
On main this shows, but doesn't work `No route matches [GET] "/admin/apps/events"`
None
appropriately. …

Remove broken link "events" from the admin sidebar

---

app/javascript/admin/controllers/config_controller.js

Fixes an issue where an element didn't exist and it's CSS classes were being changed. Now we only apply CSS class changes if the element exists.
#15219
1. Run `yarn test` and a huge wall of red errors should no longer appear.
```
[2m[31mconsole.error[39m[22m
[31m      Error connecting controller[39m
[31m      [39m
[31m      TypeError: Cannot read property 'classList' of null[39m
[31m          at extended.connect (/home/travis/build/forem/forem/app/javascript/admin/controllers/config_controller.js:35:13)[39m
[31m          at Context.connect (/home/travis/build/forem/forem/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1074:33)[39m
[31m          at Module.connectContextForScope (/home/travis/build/forem/forem/node_modules/@hotwired/stimulus/dist/stimulus.umd.js:1266:21) …
```

Fixed issue where element didn't exist in the config Stimulus controller.

---

app/models/article.rb
app/models/reaction.rb
app/models/settings/rate_limit.rb
app/services/spam/article_handler.rb
spec/models/article_spec.rb
spec/models/reaction_spec.rb
spec/models/settings/rate_limit_spec.rb
spec/services/spam/article_handler_spec.rb

Prior to this refactor, we were checking an Article's title for
spaminess.  This change now checks the Article's title and
body_markdown.
In addition, the PR encapsulates the regular expression implementations in
favor of asking the Settings::RateLimit class to determine if the passed
in text is "spammy".
Furthermore, instead of having lots of inline logic within the article,
this refactor introduces a `Spam::ArticleHandler` class.  This helps
tidy up the already busy Article specs by delegating the business logic
of Spam handling to it's own class.
There are further refactors for Comments and Users that would follow
this pattern, but this change is more important to get out the door.
Closes #15396
Define a spam term, then create an article in which you add the spam term to the markdown. …

Refactoring and extending article spam behavior

---

app/lib/constants/settings/general.rb

Update the periodic email description to reflect the period of days.
Closes https://github.com/forem/forem/issues/15415
Go to http://localhost:3000/admin/customization/config and you will see the updated description under Email digest frequency as per the screenshot below: 
updated. …

Update the periodic email description to reflect the period

---

app/workers/metrics/record_data_counts_worker.rb

Unfreeze models in RecordDataCountsWorker

---

config/routes.rb

We removed the controller in #14734, but some clients are still sending requests to this endpoint, causing routing errors.
- #14734 
appropriately.

Remove Pusher route

---

app/services/articles/feeds/find_featured_story.rb
app/services/articles/feeds/large_forem_experimental.rb
spec/services/articles/feeds/find_featured_story_spec.rb

This begins to ease the resolution of #15292.
If we merge #15240, I could see setting an `Article` constant for this
value and allowing the administrator to choose the particular behavior.
Once we have insight from the product team, we can move forward with a
more comprehensive solution.
#15292 
I'd lean on the tests to enforce that we're doing the right thing.
None

Parameterizing featured story requiring main image

---

app/models/settings/authentication.rb
app/validators/valid_domain_csv_validator.rb
spec/requests/admin/configs_spec.rb
spec/validators/valid_domain_csv_validator_spec.rb

I added a second commit after approval.  This included specs for the validator.
Prior to this commit, our regular expression did not account for the `-`
character as valid within the domain.  The `-` character cannot be the
first nor last character of the domain (e.g. `-hello.com` nor
`hello-.com` are invalid but `hell-o.com` is valid).
In addition I tidied up the default value of the
`blocked_registration_email_domains` to match it's sibling
`allowed_registration_email_domains`.
This relates to the spammer seo-hunt.com
- https://github.com/forem/admin-docs/issues/24
- https://github.com/forem/forem/pull/15404
- https://github.com/forem/forem/pull/15397
- https://github.com/forem/forem/pull/15403
Though I didn't write any tests for this (nor were there tests already
for the validator), I …

Updating valid domain registration

---

.github/CODEOWNERS

The goal is to consider different means of determining who might be able
to help review this code.
After we merge this, we're going to want to have folks self-identify in
the three groups:
- [@forem/ruby](https://github.com/orgs/forem/teams/ruby)
- [@forem/javascript](https://github.com/orgs/forem/teams/javascript)
- [@forem/css](https://github.com/orgs/forem/teams/css)
This relates to conversations amongst pod captains around pull request ownership.
None.
None.

Adding program language lens for Code Ownership

---

app/workers/users/record_field_test_event_worker.rb
spec/workers/users/record_field_test_event_worker_spec.rb

This is a short-circuit to ensure we don't throw exceptions in the
worker.  In #15240 we introduce an AbExperiment module that we could use
to insulate against FieldTest implementations.
See #15240
None, these are background jobs.
None

Guarding against missing experiments

---

package.json
yarn.lock

We're getting warnings during test set submission to the server
{
message: 'Please update client @knapsack-pro/cypress 4.4.1
version to 4.5.0. See CHANGELOG: https://github.com/KnapsackPro/knapsack-pro-cypress/blob/master/CHANGELOG.md#changelog'
}
Try upgrading as suggested.
If cypress (e2e) tests succeed in CI this should be acceptable - we only use knapsack there (locally we're not using the queues and don't have api keys).
None, test only dependency.
[Changes …

Update knapsack-pro/cypress to 4.5.0

---

spec/services/feeds/assemble_article_markdown_spec.rb

Fixup user creation pattern to use [Object#tap](https://ruby-doc.org/core-3.0.2/Kernel.html#method-i-tap) instead of modifying, then returning, via a temporary variable 
None. Tests should still pass.
None
appropriately.
or …

Use tap instead of a temporary variable to modify after create

---

app/views/admin/creator_settings/_form.html.erb

This PR updates the link for the "Terms and Conditions" link on the Creator Settings form.
Relates to #15071 
_**or**_
```
```
**To test that the changes work, please ensure that the "Terms and Conditions" link routes you to the correct page.**
N/A
_Will this …

Fix TOS Link on Creator Settings Form

---

app/javascript/.eslintrc.js
app/javascript/.storybook/main.js
babel.config.js
config/webpack/environment.js
jsconfig.json
package.json
yarn.lock

Adds the [babel-inline-react-svg](https://www.npmjs.com/package/babel-plugin-inline-react-svg) plugin to the application. This is prework for #15311. In #15311, the [react-inline-svg](https://www.npmjs.com/package/react-inlinesvg) package is being used, but it causes issues in tests, and if we mock it (which that PR currently does), we're not really testing it's usage.
It also loads the SVG at runtime as a source in the component, vs. the static import that babel-inline-react-svg provides.
TLDR; the babel-inline-react-svg plugin avoids all those pitfalls.
#15311
This is putting this plugin in place, but there is nothing to test aside from all tests should pass. Actual testing will occur in #15311.
N/A frontend infrastructure changes only.
_Will this PR introduce a change that impacts …

Added the babel-inline-react-svg plugin

---

app/views/devise/mailer/invitation_instructions.html.erb
app/views/devise/mailer/invitation_instructions.text.erb
config/locales/devise_invitable.en.yml
config/locales/devise_invitable.fr.yml
spec/mailers/previews/devise_invitable/mailer_preview.rb

Text should be updated to: 
```
Hello <name> (this is one of the 2 required fields for an invite so I don’t understand why we’re not using it)
You’ve been invited to join the <Forem Name> community at <forem URL>. You can accept the invitation by clicking this link:
Accept invitation
If you don’t want to accept the invitation, please ignore this email. Your account won’t be created until you access the link above and set your password.
```
https://github.com/forem/forem/issues/15447
Go to http://localhost:3000/rails/mailers/devise_invitable/mailer/invitation_instructions to view the updated preview.
None that I know of.
will share this …

Update the User Invitation email copy

---

scripts/build_containers.sh

We don't need it to be "version tag is set OR not empty", we need both to be true.
- https://forem.team/jamie/versioning-this-is-the-way-50ap
Hard to test, really. Needs containers built for `stable`.
appropriately.
or in a …

Fix Buildkite builds for versioning

---

app/controllers/stories/feeds_controller.rb
app/controllers/stories_controller.rb

Prior to this commit, the feed's class was part of the resource.  That
resulted in a more opaque view of things.
With this change, we're adding tags to the view so we should have a
better sense of filtering.
Related to #15240
None
None

Instrumentation: adding tags to data tracing

---

app/services/feature_flag.rb

Related to clarifying behavior for #15475.
Only tangentially related to #15475.
Please read the documentation for accuracy.
None

Updating documentation on FeatureFlag.accessible?

---

app/javascript/article-form/components/ImageUploader.jsx
app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js

This is a bugfix following markdown toolbar work in https://github.com/forem/forem/pull/15347.
Previously, whenever you selected to upload an image from the toolbar, your cursor would be reset to the start of the editor text area, causing you to lose your typing position. Similarly, once the image upload completed, your cursor would then jump to the _end_ of the text area.
This PR adds a fix to make sure we restore the user's current typing position after any image upload-triggered markdown insertion.
Fixes https://github.com/forem/forem/issues/15506
It might be useful when testing this to throttle your internet connection in your browser dev tools, to give you time to experiment with adding text etc while the image is uploading.
- Start a new post in the editor, typing multiple …

maintain cursor position while inserting an image

---

app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx

Previously the link to the editor guide in the markdown toolbar opened in the same browser tab, interrupting the editing flow. This makes sure it opens in a new tab.
Fix/change following https://github.com/forem/forem/issues/15115
- Run the app locally and navigate to `/new`
- Open the toolbar overflow menu and click the help icon
- Verify that the editor guide opens in a new tab, and not the current one
N/A
[Changes …

Markdown toolbar: open editor guide in new tab

---

app/assets/stylesheets/preact/onboarding-modal.scss

This PR fixes scrolling issues for onboarding steps.
- Replacement for #15481, per @jeremyf request.
- Closes #15279 
You should now be able to see all form fields when on /onboarding.

Enabling scrolling for onboarding, attempt 2.

---

app/javascript/shared/components/__tests__/tags.test.jsx

This fixes a component test that is currently breaking on the upgrade to Node.js 16.
#15522
N/A
N/A
appropriately.
replace this line with details on why …

Fixed test that breaks once upgraded to Node 16.

---

app/models/organization_membership.rb
app/models/user.rb

Prior to this commit, four methods had similar purpose but different
implementations.  This commit normalizes that and extracts a few
`ActiveRecord::Base` scopes.
Related to #15624
None.
None.

Refactoring to use scope

---

app/services/articles/feeds/weighted_query_strategy.rb
spec/services/articles/feeds/weighted_query_strategy_spec.rb

Prior to this change, we were forcing features into the feed.
Related to #15292 and #15475 and #15240
None.
None.

Fixing logic error for feed

---

app/javascript/.eslintrc.js
app/javascript/articles/components/CommentsList.jsx
app/javascript/listings/components/Categories.jsx
app/javascript/listings/components/CategoryLinks.jsx
app/javascript/listings/components/CategoryLinksMobile.jsx
app/javascript/listings/dashboard/rowElements/tags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/podcasts/__stories__/TodaysPodcasts.stories.jsx
app/javascript/utilities/color/WCAGColorContrast.js
package.json

The `lint:frontend` npm script was running but was resulting in a false positive for a successful lint of the front end. When I put this script in place, I didn't realize the folders needed to be in quotes. Oddly enough, it ran fine from the command line. Anyway, fixed.
N/A
N/A
appropriately. …

Fixed lint:frontend npm script

---

app/views/layouts/_logo.html.erb

We need to check is the logo_svg is present and then use the method logo_svg instead of the setting …

Revert SVG Logo to using logo_svg

---

app/assets/stylesheets/base/main.scss

Remove a max height on the logo_svg as it causes styling issues. 
Open up localhost and the logo should be centered without this property.
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&temp …

Remove max height on logo

---

app/javascript/article-form/components/ImageUploader.jsx

I'm not sure it happened, but the intention was for this visually hidden `div` to have `aria-live="polite"`, to make sure when the text changes, it's announced to screen reader users. I think I might have accidentally lost it when fixing merge conflicts in the ImageUploader, but this PR adds it back in 🙂 
https://github.com/forem/forem/pull/15347
- Using a screen reader, navigate to `/new` and upload an image
- Check that when the upload completes, a success message is announced
It's a small enhancement for screen reader users …

announce image upload success via aria live

---

app/lib/string_attribute_cleaner.rb
app/models/article.rb
app/models/user.rb
spec/lib/string_attribute_cleaner_spec.rb

In #15281, we introduced the StringAttributeCleaner.  Let's use it!
See #15281
None.
None.

Refactoring to use StringAttributeCleaner

---

app/views/comments/_hide_comments_modal.html.erb
config/locales/views/comments/en.yml
config/locales/views/comments/fr.yml

i18n for some newly added strings & missing French keys.
#15178, #15462
appropriately.
shared_

add some missing i18n strings & keys in views/comments

---

app/controllers/admin/creator_settings_controller.rb
app/uploaders/base_uploader.rb
app/uploaders/logo_uploader.rb
app/views/admin/creator_settings/_form.html.erb
spec/uploaders/logo_uploader_spec.rb

This removes the option to upload an SVG file for a logo. The main reason is it's an XSS attack vector potentially.
```ruby
```
3. Click on the login link. Since the feature flag is enabled, you'll be redirected to Creator Signup Form.
4. Fill in the necessary information and submit the form.
5. On the next page select an image for the logo.
- Note that you should only be able to select a jpeg or png file. This PR removes the ability to upload an SVG, so try adding one.
6. …

Creator Settings: Removed SVG files as an option for logo upload

---

app/controllers/moderations_controller.rb
app/decorators/user_decorator.rb
app/models/rating_vote.rb
app/models/user.rb
app/views/admin/articles/_individual_article.html.erb
app/views/moderations/index.html.erb
spec/decorators/user_decorator_spec.rb
spec/models/user_spec.rb
spec/requests/admin/tags/moderators_spec.rb

`DEPRECATION WARNING` is showing in rspec runs since the user role query method name changes introduced in #15639 and #15628 
This is the find and replace work removing the deprecated calls, based on the details shown in an rspec run.
I could have missed a few - I was only looking at the logged cases in the test suite.
#15639 - User#trusted?
#15628 - User#warned?
Nothing breaks. Nothing changes. Fewer deprecations logged.
None
[Changes …

role deprecation cleanup

---

db/migrate/20160104221355_add_url_to_advertisements.rb
db/migrate/20170206214820_add_secret_to_sponsors.rb
db/migrate/20190327090030_add_indexes_to_identities.rb
db/migrate/20190401100844_add_unique_index_to_users_twitter_username.rb
db/migrate/20190401100850_add_unique_index_to_users_github_username.rb
db/migrate/20200308144606_add_index_to_rating_votes.rb
db/migrate/20200820055018_add_display_columns_to_profile_fields.rb
db/migrate/20210428190634_add_tsvector_index_on_searchable_columns_to_podcast_episodes.rb
db/migrate/20210917023320_drop_connect_tables.rb

Fix spelling errors (db/migrate)
#15669 
appropriately. …

Spelling db migrate

---

app/controllers/stories_controller.rb

Removing feed experiment for non-logged in user

---

app/views/users/edit.html.erb
config/locales/en.yml
config/locales/fr.yml
config/locales/views/main/fr.yml
config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml
config/locales/views/users/en.yml
config/locales/views/users/fr.yml
spec/system/homepage/user_visits_homepage_spec.rb

- Delete no longer useful `core` keys that were not able to remove in the scope of each partial PR
- Fix outdated or erroneous i18n messages caused by PRs having crossed each other
#14888
appropriately.
or in a …

clean up views i18n entries

---

app/models/user.rb
app/services/mailchimp/bot.rb

Prior to this commit, we had two logically identical chunks of code.
With this commit, we consolidate that logic into a single method.  In
addition, we remove one place where the application knows about the
roles implementation.
Loosely related to #15624.
None.
None.

Consolidating role query logic

---

app/assets/stylesheets/config/_generator.scss

One of the values in our CSS generator was causing some build failures. It's been like that for quite some time but it has just started causing build failures for me today... So here's a fix.
No.
It won't be communicated.

CSS Generator Fix

---

app/controllers/users/notification_settings_controller.rb
app/services/notifications/new_mention/send.rb
app/views/users/_notifications.html.erb
config/locales/helpers/en.yml
config/locales/helpers/fr.yml
config/locales/views/notifications/en.yml
config/locales/views/notifications/fr.yml
db/migrate/20211209225729_add_mobile_mention_notification_to_user_notification_settings.rb
db/schema.rb
spec/factories/users_notification_settings.rb
spec/services/notifications/new_mention/send_spec.rb

Adds support for mobile push notifications for mentions of a user in articles and comments. This change is entirely Forem side: there's no code addition needed in Forem-iOS or Forem-Android. Added to the codebase are:
- added column to `users_notification_settings` table to store setting
- added UI in User Settings -> Notifications
- added service to create mobile push notifications in response to mentions
- added tests
Related to https://github.com/forem/forem-ios/issues/106
User settings:
Example of delivered notification:
None. …

Mobile mention notifications

---

app/controllers/api/v0/instances_controller.rb
spec/requests/api/v0/instances_spec.rb

This PR adds a count of comments and published articles to the instance API.
appropriately.
replace this line with details on why this change doesn't need …

Add article and comment count to instance API

---

cypress/support/commands.js

There's an open issue, https://github.com/cypress-io/cypress/issues/781, where many people have mentioned that cookies do not clear. A custom command was attempting a single retry to clear cookies, but now it attempts at most three times to clear cookies.
The hope is this will fix some flaky test issues we've been experiencing recently.
1. All end-to-end (E2E) tests pass for this PR
2. To "fully test" this, it's recommended to restart the build nodes for E2E tests.
N/A this is testing infrastructure. …

Added some retries to cookie clearing

---

README.md

Add Dwight to Core team list in README
n/a
n/a
n/a
appropriately.
n/a

Add me (Dwight) to readme :)

---

app/assets/stylesheets/base/main.scss

There [was](https://github.com/forem/forem/pull/15732) one edge case I forgot about (when paste SVG code did not have any `width` or `height` attributes specified) which was causing some logos to not appear...
No.
It won't.

Logo bug fix

---

app/assets/stylesheets/components/skip-link.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/preact/onboarding-modal.scss
app/assets/stylesheets/themes/dark.scss
app/assets/stylesheets/views/article-form.scss
app/assets/stylesheets/views/footer.scss
app/views/layouts/_footer.html.erb
config/locales/views/main/en.yml
config/locales/views/main/fr.yml

This PR removes few unused (or barely used) variables and refactors few areas to make this initial cleanup possible. There should be no visual changes, except footer which should now have colored links instead of grey (yay a11y!).
Only footer should be different.
Hopefully it's better.
No.
It won't.

CSS Variables cleanup

---

app/views/layouts/_footer.html.erb
config/locales/views/main/en.yml
config/locales/views/main/fr.yml

Restore an i18n key removed in #15828. The i18n is here to absorb differing typographical conventions regarding equivalent of dashes. This time wraps up the link element correctly (I hope).
* I replaced original hyphen `-` with em dash `—` for consistency with the next paragraph.
See above
development process, or …

restore an i18n key in _footer.html.erb

---

app/controllers/tags_controller.rb
spec/requests/tags_spec.rb

add badge to tags suggest response
n/a
Hit the tags suggest endpoint and you should see badge associated badge in the response
n/a
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=cha …

add badge to tags suggest response

---

app/javascript/packs/userProfileSettings.js
app/views/users/_profile.html.erb
config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml

- Adds i18n for recently introduced #15255, #15293
- Modifies character count logic to match the number of Unicode code points (I guess DB works this way)
See above
will share this change with the people who need …

i18n fix for character limit counter

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb

in the hope of resolving https://app.honeybadger.io/projects/67192/faults/83175672 and cutting down noise
n/a
n/a
n/a

Add catch to trackAdImpression()

---

app/controllers/admin/moderator_actions_controller.rb
app/models/audit_log.rb
spec/requests/admin/moderator_actions_spec.rb

Substituting a constant for a string.
None.
None.
None.

Favoring constant over magic string

---

app/workers/articles/update_page_views_worker.rb
spec/workers/articles/update_page_views_worker_spec.rb

Before attempting to create a page view, ensure the article exists.
This should resolve a validation error in PageView.create! when the
article does not exist (perhaps it was deleted, or the user suspended,
or it was invalid data sent from the client).
This had been happening dozens of times per day, for the last 10
months
https://app.honeybadger.io/projects/66984/faults/76497342
Added tests for both the early exit and happy path cases.
None

Load article before creating a page view for an invalid one

---

app/controllers/sidebars_controller.rb
app/controllers/stories_controller.rb
app/models/campaign.rb

Prior to this commit, two controllers had nearly identical chunks of
logic.  This refactor extracts the logic to a common and more canonical
location.
None, though it's inspired by looking for `where(score)` type clauses
to help get a sense for how we apply that logic.
None.
None.

Refactoring to consolidate logic

---

app/views/articles/show.html.erb
app/views/users/_profile.html.erb
config/locales/views/actions/en.yml
config/locales/views/actions/fr.yml
config/locales/views/listings/en.yml
config/locales/views/listings/fr.yml
config/locales/views/main/en.yml
config/locales/views/main/fr.yml
config/locales/views/misc/en.yml
config/locales/views/misc/fr.yml
config/locales/views/tags/en.yml
config/locales/views/tags/fr.yml

- Add a couple of missing i18n lost in interaction between PRs or by mistake
- Remove some i18n entries I found no longer used
#14888 …

delete and add back i18n keys

---

app/models/credit.rb

In addition to using the existing scope, I went ahead and added some
documentation.
As part of my work on "thinking" about the permissions, I've been looking at where we use the `where` method to see if we could repurpose or create model scopes.
None
None
None

Favor repurposing existing scope

---

app/liquid_tags/liquid_tag_base.rb

This PR adds documentation to help with the upcoming Forem Fest.  As part of that effort, I'm writing some guidelines and documentation.  This inline documentation helps create a breadcrumb from my yet to be published post and the work we're thinking of doing.
In addition adding a Rubocop auto-update.
Loosely related to #15906.
None
None

Updating documentation for LiquidTagBase

---

Containerfile

This points the Forem container at a newly-built Ruby container - `quay.io/forem/ruby:3.0.2` - which is based on a Fedora 35 container - `quay.io/forem/fedora:35`.
Internal: https://github.com/forem/infra/issues/358
Semi-related: https://github.com/forem/forem/pull/15522
This will be manually deployed/tested on Forem Cloud canaries.
This will be internally communicated to Forem Cloud stakeholders

Use newly-built Fedora-35-based quay.io/forem/ruby:3.0.2 container

---

config/field_test.yml

Small config change to ensure we can tell the difference between `0.55` and `1.55` on the dashboard. Any test where the outcome % is `1` vs `2` and not `88` vs `89`, this precision is needed. And generally is additional useful information for the dashboard.
No functionality is changed, just updating config in field test gem.
Builds on: https://github.com/forem/forem/pull/15789
Field test gem: https://github.com/ankane/field_test
**Current:**
**New:**

Update precision config on field test dashboard

---

app/controllers/tags_controller.rb
app/serializers/search/tag_serializer.rb
app/services/search/tag.rb
spec/requests/tags_spec.rb
spec/services/search/tag_spec.rb

This PR adds some new tag attributes in the response to `search/tags` and `tags/suggest`. Both endpoints are used in the tag suggestion input in the 'create post' form, and the changes added here are needed to display the new tag suggestion UI being created in https://github.com/forem/forem/issues/14845
No attributes have been removed from the API responses, only new ones added, namely:
- `bg_color_hex`
- `short_summary`
- `badge: badge_image`
Closes https://github.com/forem/forem/issues/15809
- When you first click into the tags field in the editor, the 'top tags' should be shown as before, but you should see the new properties mentioned above in the network response 
- If you start typing some letters in the tags field in the editor, the tag search/autosuggest functionality should …

Update tag search and suggest

---

app/assets/stylesheets/views/article-form.scss
app/javascript/article-form/components/TagAutocompleteOption.jsx
app/javascript/article-form/components/__stories__/TagAutocompleteOption.stories.jsx

This is a small PR which will eventually link in with the work in https://github.com/forem/forem/pull/15796.
All that is new here is a component which will be used to display the 'suggested tags' in the new autocomplete component. Integrating the base autocomplete component together with this, and displaying in the editor will be the final step in completing the larger epic, and this PR is only concerned with that individual tag UI.
Closes https://github.com/forem/forem/issues/15422
- Run `yarn install && yarn storybook`
- Navigate to App Components > Article Form > Tag Autocomplete Option
- Use the Controls panel to experiment with different values being passed to the component
- Experiment with light/dark theme / resizing the window
The component overall should resemble [the one in this …

Add Storybook entry for tag suggestion item

---

app/workers/push_notifications/deliver_worker.rb

The `reject` strategy has been working as expected for `PushNotifications::DeliverWorker` but we're trying to reduce noise in the dead job queues, so in this case the `log` strategy seems like the best option.
None - Backend change
None

Update deliver worker conflict strategy

---

app/views/pages/contact.html.erb

Change link to forem.dev for feature requests to github discussions
fixes #15973
View /contact page
Confirm link to shown github and not forem.dev 
None
appropriately.

Change contact page to open feature requests as discussions

---

app/views/admin/shared/_logo_upload.html.erb

This PR adds the logo size requirements to the Creator Settings form so that Creators are aware of the requirements up front.
N/A
_**or**_
```
```
Once on the Creator Settings page, you will want to take a peek at the changes outlined below:
N/A
_Will this PR …

Add Logo Size Requirements to the Creator Settings Form

---

app/liquid_tags/spotify_tag.rb
app/views/liquids/_spotify.html.erb
spec/liquid_tags/spotify_tag_spec.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Spotify embeds.
closes https://github.com/forem/forem/issues/15582
Example Spotify URLs:
https://open.spotify.com/track/64csu9GsP563GpjaSvU17w?si=eaac508fe9394a93
https://open.spotify.com/track/64csu9GsP563GpjaSvU17w
https://open.spotify.com/artist/2Cnw56yEiRmpVI79f9z6oO?si=AJguBjS5QeeFkvSQq6-o7Q
https://open.spotify.com/playlist/37i9dQZF1E39MihYlvYa83?si=4ca24a67215f4eab
https://open.spotify.com/album/3YA5DdB3wSz4pdfEXoMyRd?si=LQ6ft_T9QfiNA_KHbn6CkA
https://open.spotify.com/episode/3fLyjTYjIdHxC0kdKMpbGj?si=5f45e5032cd5450a
https://open.spotify.com/show/3sRrtlRiByFrOC49vPwP8L?si=c3c6c1180afe4094
Spotify URI: spotify:episode:5V4XZWqZQJvbddd31n56mf
Legacy Spotify URI: …

Implement Spotify Unified Embed

---

app/lib/constants/settings/general.rb
app/views/admin/settings/forms/_images.html.erb
app/views/admin/shared/_logo_upload.html.erb

In preparation for launching the Creator Setup and Onboarding page feature, we've decided to allow the user to preview and update their logos that we convert in [this script](https://github.com/forem/forem/pull/15710). 
I've also updated the descriptions and headings in the Images section to try and be more concise. 
In addition, I've added an id so that we can have a section link (note that the section link can be iffy at times but we're accepting this until update the information architecture and decide how to proceed with the layout).
-
Updates made: 
To QA this please go to `http://localhost:3000/admin/customization/config#images` and view the update. If you haven't tested this [PR](https://github.com/forem/forem/pull/15710) your Logo preview section may be blank which is okay. 
Just …

Update the images section in preparation for Creator Setup and Onboarding Launch [Will deploy on 10/01]

---

app/javascript/packs/followButtons.js

While working on #15916 (via #15983 and later #15994) I was exploring if
we needed to stringify JSON values.  I also injected a few `try, catch,
debug` areas.
Consolidating the parsing does not appear to adversely affect things.
Loosely related to #15916, #15983, and #15994.
Open the homepage and there shouldn't be any JS errors; though if you've been testing #15994 that might not be true, because you might have disruptive data.
None.

Favor using existing variable over re-parsing

---

app/lib/constants/settings/general.rb

After some back-and-forth during today's engineering round table, I've updated the capitalization of "Apple touch icon" within `constants.rb`, in addition to the Images documentation. 😄 Also, I've hyphenated "right-hand" and "left-hand" to keep the wording consistent in `constants.rb`.
N/A
To QA this PR, navigate to `/admin/customization/config#images` and check out the changes and ensure that all checks pass!
N/A
[Changes …

Updates a Few Config Constants

---

app/javascript/packs/onboardingRedirectCheck.jsx

Refactors the onboarding logic to make it clearer what the intent of the localStorage item key/value pair does (based on feed back in https://github.com/forem/forem/pull/14728/files#r731483808).
Closes #15143
1. Create a new account.
2. Log in with that new account.
3. The onboarding flow begins.
```
```
4. Click on the login link. Since the feature flag is enabled, you'll be redirected to Creator Signup Form.
5. Fill in the necessary information and submit the form.
6. …

Refactored client-side onboarding redirect logic.

---

app/workers/broadcasts/send_welcome_notifications_worker.rb

The logic used to calculate the live at time, the week ago time, then
compare them to find the more recent value.
Move all of this logic to a method (there's a guard to exit if
the setting is nil, so this should be safe).
Investigating issue with welcome broadcasts not being sent.
Nothing should change.
None

Simplify and label date calculation

---

app/assets/stylesheets/components/comments.scss

In-feed comments have always been tough to read. There are further design adjustments we _could_ make, but I think letting the paragraphs breath is a one-liner that makes a big positive impact as far as a one-character change goes.
General misc feed focus
This should be a fairly straightforward check from design.

Adjust in-feed-comment p margin for readability

---

db/seeds.rb
lib/data_update_scripts/20220105112823_migrate_logo_svg_data.rb
spec/requests/pages_spec.rb
spec/services/notifications/reactions/send_spec.rb
spec/services/rate_limit_checker_spec.rb
spec/system/authentication/user_logs_in_with_apple_spec.rb
spec/system/authentication/user_logs_in_with_facebook_spec.rb
spec/system/authentication/user_logs_in_with_forem_spec.rb
spec/system/authentication/user_logs_in_with_github_spec.rb
spec/system/authentication/user_logs_in_with_twitter_spec.rb

```shell
$ bundle exec rubocop --auto-correct
```
A very low effort let's see what Rubocop wants us to fix.
None.
None.
None.

Fixing Rubocop's auto-correct recommendations

---

app/javascript/netlify.toml

Updates Storybook node version to match `.nvmrc`. Going to make an issue to spend some time to figure out how to match it to the `.nvmrc` file.

Update storybook node version

---

config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml

Its just a typo test.
appropriately. …

Fix: grammatical error

---

lib/data_update_scripts/20220113085122_enable_creator_onboarding_feature_flag.rb
spec/lib/data_update_scripts/enable_creator_onboarding_feature_flag_spec.rb

This is in Draft to avoid an accidental merge, however I've requested reviewers because it is ready for review. 
We will be [launching the Creator Signup and Onboarding Feature](https://forem.dev/foremteam/changelog-new-creator-setup-process-and-image-improvements-4hc3) on Monday, 17 January. In order to launch the feature we will simply be enabling the feature flag across all the Forems (existing and new ones). 
Here's a brief description of the process to launch:
1. The script was run on all Forem Instances on the 10 January. We reached out to Forem Cloud Instances where the logo conversion failed and told them to upload it themselves. We also released that post to alert all Forems including self hosted ones to please check out a preview of their logo immediately after upgrading to …

Launch creator Onboarding with the Feature Flag [ To merge only on January 17 ]

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/controllers/page_views_controller.rb

This loosely relates to a request for information from Success team
about whether or not viewing a draft article counts towards it's stats.
Related to questions about draft previews counting towards page views.
None.
None.

Adding documentation and constant

---

app/controllers/collections_controller.rb
app/controllers/dashboards_controller.rb
app/models/collection.rb
app/views/dashboards/_actions.html.erb

The series count on the dashboard will only consider empty series from now on.
#16129 
To test this functionality, you can create an article, add a series to that article. Save the Series/article, and create another article and a new series.
After saving the new series/ article, replace the second article series with the first series created.
There should now be one series without any articles.
Go to the dashboard index view, the series count shown will be 2 while on the series index view only 1 series is shown. …

Series count to only include non empty series

---

app/services/articles/feeds/weighted_query_strategy.rb

This PR resolves some rubocop violations within the `weighted_query_strategy.rb` that I came across while trying to push some changes on a different branch just a few minutes ago.
N/A
All checks should pass and rubocop should not spit out a violation for the file. ♻️ 
N/A
appropriately. …

Resolve Rubocop Violations

---

app/controllers/stories/tagged_articles_controller.rb
spec/requests/stories/tagged_articles_spec.rb

Never render a 404 for supported tags and non-supported tags with at least one published approved article.
#15359 
Tag an approved and published article with a non-supported tag. Visit the tag's index view and you should not get a 404. The negative test case would be to remove the tag from aforementioned article and visit the tag index. You should at this point get a 404.
n/a
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees= …

allow approved tags to show articles and not render 404

---

.env_sample
config/initializers/carrierwave.rb

Seeing image breakage on DEV
Reverts forem/forem#15445

Revert "Support alternate S3 endpoints"

---

app/services/articles/feeds/weighted_query_strategy.rb

Adding one to a "always-ish greater than or equal to 0" value.  This
should resolve a flakey test and a seemingly erratic production error.
Resolves https://app.honeybadger.io/projects/66984/faults/83596547
Flakey tests and honeybadger errors.
None.
None

Ensuring that we don't divide by zero

---

app/services/articles/feeds/weighted_query_strategy.rb

https://github.com/forem/forem/pull/16172 introduced a query error (trying to fix another query error).
Untangle the parens to make the query balanced, and change function `max(i,j)` (missing?) to `greatest(i,j)` 
https://www.postgresql.org/docs/11/functions-conditional.html#FUNCTIONS-GREATEST-LEAST 
https://app.honeybadger.io/projects/66984/faults/8359654 query error
https://github.com/forem/forem/pull/16172 
Assuming a user 11:
```ruby
Articles::Feeds::WeightedQueryStrategy.new(user: User.find(11), strategy: "final_order_by_random_weighted_to_last_comment_at").call.first
```
Should not raise an error
None …

Select max from a subquery of two things

---

app/liquid_tags/codepen_tag.rb

We recently merged a contributor's branch that apparently didn't go through the local precommit hook, so we currently have a few errors in `main` which this PR addresses.

Rubocop auto-correct

---

config/locales/misc/en.yml
config/locales/misc/fr.yml
db/seeds.rb
lib/data_update_scripts/20200820153340_insert_facebook_connect_broadcast_message.rb
lib/data_update_scripts/20210921235050_insert_forem_connect_broadcast_message.rb
lib/data_update_scripts/20220107215659_insert_google_ouauth2_connect_broadcast_message.rb
lib/data_update_scripts/20220111192031_insert_apple_connect_broadcast_message.rb
spec/factories/broadcasts.rb

Inspired by [a suggestion from @citizen428](https://github.com/forem/forem/pull/15986#discussion_r782683950), this PR consolidates strings used in welcome broadcasts into a localization file so they can be referenced from multiple places.
https://github.com/forem/forem/pull/15986
You're on a roll! 🎉 
issue template so Community Success …

Constantize broadcast messages

---

app/assets/stylesheets/views/article-form.scss

Another PR went in ahead of the tags autocomplete which removed a CSS variable we were using to style tags without a `bg_color_hex`. This was resulting in those tags having a transparent background color when it went live. This should fix things so instead it falls back to the 'normal' tag bg color.
https://github.com/forem/forem/pull/16025
- Run the app, and create a post 
- Add a tag that isn't support e.g. any random tag without bg_color_hex
- Check that it has a light grey background when added
N/A …

Fix tag autocomplete styling 

---

app/assets/stylesheets/config/_colors.css

This fixes a bug which made primary destructive button invisible :P 
updated. …

Destructive button style fix

---

app/views/admin/comments/index.html.erb
app/views/layouts/admin.html.erb

We're looking to remove or at a minimum load Bootstrap conditionally. While looking into this, I noticed that font-awesome was used. I narrowed it down to two spots that I replaced with our standard icons.
1. Login as admin@forem.local, password: password
1. Load the comments page for the admin, `admin/content_manager/comments`.
2. Comments should look pretty identical. The new Twitter icon is a little bigger but it's our standard one. 
**Before**
**After**
Note that the font is smaller now because an `<h5 />` is not being used. The spacing is a little less too for the same reason. I think the size is fine, but let me know @ludwiczakpawel.
1. Update something to trigger the flash message, e.g. edit a user, `http://localhost:3000/admin/users/1/edit`
2. The success or failure message …

Removed font-awesome from the admin section

---

.gitattributes

Fixes an issue that a contributor had recently with line endings. See https://github.com/forem/forem/pull/16102#issuecomment-1014128284
#16102
N/A
N/A
appropriately.
replace this …

Configured the repository to handle line endings

---

config/initializers/rpush.rb

Adds the host tag to RPush reflection API in order to monitor these events in a more granular way
N/A
N/A
Deploy the fleet

Add host tag in ForemStatsClient

---

db/seeds.rb

Always ensure Rubocop's happiness.
This is unrelated to #16282, as it existed in main before merging.
None.
None.

Appeasing rubocop

---

app/controllers/stories/feeds_controller.rb
app/models/ab_experiment.rb
spec/models/ab_experiment_spec.rb
spec/rails_helper.rb
spec/services/articles/feeds/weighted_query_strategy_spec.rb
spec/workers/users/record_field_test_event_worker_spec.rb

Part one of some adjustments to AB testing which should ensure all variants get tested thoroughly, and fewer misc files need to change to update a feed strategy test week-over-week.
This code adjusts the tests such that all of the specs within the loop test against all the variants. I have also refactored some areas to require fewer file changes to update a test.
I mentioned that this is "part one", because I would like to follow up with broader experimentation of different article edge cases to ensure we don't have "divide by zero" scenarios pop up, etc. I'll seek to add initial edge case exercising when updating for the next experiment.
https://github.com/forem/forem/pull/16172
https://github.com/forem/forem/pull/16177

Refactor AB Experiments and exercise all variants in rspec

---

app/liquid_tags/tweet_tag.rb
app/liquid_tags/unified_embed/tag.rb
config/locales/liquid_tags/en.yml
config/locales/liquid_tags/fr.yml

- Restore an i18n key removed during text update
- Found a new line added just before #16125
#16218, #14888
appropriately. …

i18n key updates in app/liquid_tags

---

app/views/liquids/_stackexchange.html.erb
spec/liquid_tags/stackexchange_tag_spec.rb

-  [x] Bug Fix
Title of questions don't get displayed while StackOverflow / StackExchange Liquid Tags are used. This change fixes that.
Resolves #16225 
To Reproduce:
1. Go to New Article Page (/new)
2. Paste this and preview {% stackoverflow 70779246 %}
OR refer the issue description for quick reference.
UI Accessibility Testing won't be needed since there is no impact
will share this change with the people who …

Added title to be displayed for stackexchange question

---

app/services/articles/feeds/weighted_query_strategy.rb
config/field_test.yml

After a successful test of the "final order" process, and after [some refactoring](https://github.com/forem/forem/pull/16236) which makes these updates simpler, this test is a good deal "simpler" than the last one.
The test here replaces "counting 0, 1 or 2 tags" with one that makes use of the computed points for a user's relationship with a tag they follow. We allow users to configure which tags they care about most — and we also calculate which ones they engage with most to complement their explicit relationship.
This "points calculation" game is one which needs to be examined on an ongoing basis for effectiveness and appropriateness alongside the feed algorithm, but this change seeks to ask whether ordering with calculated points in mind is better than treating all tags as equal. Of …

Feed Experiment round 5: Factor in sum of tag points

---

app/models/article.rb

This is the 4th PR for updating our code to use Sidekiq's relatively new `perform_bulk` feature.
NOTE: I'm doing one PR per change so we can merge them at different times and monitor if we want.
Previous PRs:
#16293
#16324 
#16325
Nothing specific
No UI changes

Use `peform_bulk` in `Article#before_destroy_actions`

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/assets/stylesheets/config/_import.scss
app/javascript/actionsPanel/__tests__/actionsPanel.test.js
app/javascript/actionsPanel/actionsPanel.js
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
app/views/articles/_single_story.html.erb
app/views/moderations/actions_panel.html.erb
app/views/shared/_profile_preview_card.html.erb

Trying to pull out as much as possible [from another PR](https://github.com/forem/forem/pull/16174) and this felt like something tiny and good to isolate :)
- https://github.com/forem/forem/pull/16174
Just review the code.
No.
No.
It won't.

Generator updates

---

lib/data_update_scripts/20220128150709_add_admin_member_view_feature_flag.rb
spec/lib/data_update_scripts/add_admin_member_view_feature_flag_spec.rb
spec/support/seeds/seeds_e2e.rb

There are certain features that we need to hide behind a feature flag while the features are still in development and this PR adds the necessary feature flag to the codebase for the Admin Member View work that is currently in progress. 
Relates to PR #16174 
All of the checks should pass. Additionally, the script should run without an issue.
N/A
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_reque …

Add admin_member_view Feature Flag

---

app/views/pages/robots.text.erb

The actions_panel subpage of articles, forgot my password page, the login and sign-up pages, and the new post page are indexed by search engines including Google. These pages shouldn't be indexed for a good SEO result.
development process, or any of our internal teams? If so, please note …

Disallow additional pages in robots.txt

---

spec/support/seeds/seeds_e2e.rb

Connect (chat), is no longer part of the Forem codebase. A feature flag remained in E2E seed data that is no longer required.
#14644
N/A
N/A
appropriately.
replace this line with …

✂️ ✂️  Removed the Connect feature flag from seed data ✂️ ✂️ 

---

db/seeds.rb

When setting up new local development environment for Forem, `bin/setup` experienced a fatal error while seeding the database.
```
Seeding with multiplication factor: 1
1. Creating Organizations.
2. Creating 10 Users.
User with email = admin@forem.local not found, proceeding...
3. Creating Tags.
4. Creating 25 Articles.
rake aborted!
NoMethodError: undefined method `>' for nil:NilClass
/Users/ryanpalo/Dropbox/My Mac (Janice.local)/Documents/forem/app/models/reaction.rb:207:in `new_untrusted_user'
```
After some debugging, found that all 10 (by default) sample users were being created with `registered_at` and `confirmed_at` attributes, but the additional `admin@forem.local` user was only being created with `confirmed_at`, and thus, when `Reaction#new_untrusted_user` was being called a …

seeds.rb: Add registered_at to admin user to fix setup seed issue.

---

spec/services/analytics_service_spec.rb

This failed in a main build today, testing shows this may give the
same domain very rarely
10_000.times.map do
Addressable::URI.parse(Faker::Internet.url).domain == Addressable::URI.parse(Faker::Internet.url).domain
end.tally
=> {false=>9998, true=>2}
Use a .dev domain, which is absent from faker's internet [domain_suffix](https://github.com/faker-ruby/faker/blob/master/lib/locales/en/internet.yml), to ensure two unique domains are compared.
https://app.travis-ci.com/github/forem/forem/jobs/557756931
Run the test a lot, should pass every time? Run the test once, ensure nothing broke.
Don't worry, CI will do this for you.
None …

Ensure the domain of two faker generated urls are distinct

---

app/views/admin/display_ads/_form.html.erb
app/views/admin/display_ads/edit.html.erb
app/views/admin/display_ads/new.html.erb
app/views/admin/html_variants/_form.html.erb
app/views/admin/html_variants/edit.html.erb
app/views/admin/html_variants/new.html.erb
app/views/admin/navigation_links/_add_navigation_link_modal.html.erb
app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
app/views/admin/navigation_links/_form.html.erb
app/views/admin/navigation_links/index.html.erb
app/views/admin/pages/_form.html.erb
app/views/layouts/admin.html.erb
cypress/integration/seededFlows/adminFlows/navigationLinks/navigationLinks.spec.js
cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js

This PR updates the frontend code of some Admin's views within Customization section (Display Ads, HTML Variants, Navigation links and Pages) to NOT rely on Bootstrap anymore. This is another step towards removing Bootstrap entirely from the codebase.
So instead of using Bootstrap styling we now use Crayons styling which obviously, as a side effect, updates the UI.
**Keep in mind, the primary goal of this PR is NOT to redesign (i.e. improve) the views, but to drop Bootstrap in favor of Crayons. The actual redesigning will be handled separately as it requires more product thinking etc.**
This is an ongoing process that has already been started in separate PRs handling other parts of Admin:
- #16375 
- #16359 
Click through following sections: Display Ads, HTML Variants, Navigation links …

Applying Crayons to some Customization pages

---

app/assets/javascripts/initializers/initializeSettings.js
app/views/users/_org_admin.html.erb
config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml
cypress/integration/seededFlows/settingsFlows/organisationSecretCode.spec.js

In an org admin's settings, there is a secret invite code for the organization. It has a copy to clipboard button that currently isn't working, and this PR fixes that. It also removes use of `clipboard-copy` from this area, as we no longer require it (we have one more place where this is currently used, which we can refactor in a subsequent PR).
Fixes https://github.com/forem/forem/issues/13434
Builds on work an conversation in https://github.com/forem/forem/pull/14934
- Log in with a user who's the admin of an organisation
- Go to `/settings/organization`
- Click the 'Copy' button in the "Grow the team" section
- Check the confirmation "Copied to clipboard!" appears
- Check if you now paste your clipboard contents somewhere that the code was copied successfully …

Copy organization secret code to clipboard

---

app/views/admin/badge_achievements/award.html.erb
app/views/admin/badge_achievements/index.html.erb
app/views/admin/badges/edit.html.erb
app/views/admin/badges/index.html.erb
app/views/admin/badges/new.html.erb
app/views/admin/comments/index.html.erb
app/views/admin/podcasts/edit.html.erb
app/views/admin/shared/_tabbed_navbar.html.erb
app/views/layouts/admin.html.erb

This PR updates the frontend code of Admin's views within Content Manager (except Articles, which, because of its complexity, is handled in a separate PR #16359) section to NOT rely on Bootstrap anymore. This is another step towards removing Bootstrap entirely from the codebase.
So instead of using Bootstrap styling we now use Crayons styling which obviously, as a side effect, updates the UI.
**Keep in mind, the primary goal of this PR is NOT to redesign (i.e. improve) the views, but to drop Bootstrap in favor of Crayons. The actual redesigning will be handled separately as it requires more product thinking etc.**
- Related: #16359 
Click through some views in Admin's Content Manager sections - if they don't look worse, then we're good :D Below I show some that looks _slightly more …

Applying Crayons to Content Manager pages

---

app/javascript/.eslintrc.js
app/javascript/packs/base.jsx
config/webpack/environment.js
jsconfig.json

This changes the `@admin-controllers` webpack alias to `@admin` as part of some prework for #16174. All this changes is how two frontend imports are called for the moment.
#16174
The Forem creator flow should still work as it previously did.
1. From the Rails console
```
```
2. Navigate to http://localhost:3000
3. Click on the login link. You'll be redirected to Creator Signup Form.
Fill in the necessary information and submit the form.
4. You are redirected to the next step of …

Reworked some webpack aliases as prework for the new admin member detail view

---

app/models/rating_vote.rb
app/models/response_template.rb
app/models/user.rb
app/policies/authorizer.rb
spec/models/user_spec.rb

General tidying up work.
Related to #15762, #15691, and #15624

Removing deprecated User methods

---

cypress/support/commands.js

Now there is a custom Cypress command to get our modal component, `cy.getModal()`. I was using this in E2E tests for the new admin member detail view, but it made sense to make this a custom command so that all tests can benefit from it.
#16174
N/A this is testing infrastructure
N/A this is testing infrastructure
issue template so Community Success can help …

Added a custom Cypress command to get the modal compoonent.

---

app/services/articles/feeds/weighted_query_strategy.rb
config/field_test.yml

This PR will be accompanied by a post in https://forem.dev/t/feedalgorithm describing the outcome of last experiment.
This is a simple experiment playing with the day-over-day decay factor. In the future I'd like to experiment with variable decay factor based on the `current_user`'s recent activity, but this will act as a little evidence to make decisions for a future experiment.
This PR also fixes the mistake that we did not promote the winner of a past experiment related to comment count.
https://github.com/forem/forem/pull/16128
https://github.com/forem/forem/pull/15993
https://forem.dev/foremteam/feed-test-experiment-5-results-tag-point-summing-leads-to-mixed-results-3cf9
Latest post: https://forem.dev/foremteam/feed-test-experiment-5-results-tag-point-summing-leads-to-mixed-results-3c …

Feed experiment 6: recency

---

app/controllers/api/v0/instances_controller.rb
spec/requests/api/v0/instances_spec.rb

Remove counts from instance API.
N/A
Hit the instance API and verify the counts are no longer returned.
issue …

Remove counts from instance API

---

app/views/pages/robots.text.erb

Google Search Console unearths crawl stats which can show us uselessly-crawled endpoints. 
This PR removes a couple json endpoints which are loaded for unauthenticated traffic, but not important for bots to expend resources crawling.
https://github.com/forem/forem/issues/16500
This should be pretty straightforward: Just double check for no typos. Definitely don't want an accidentally broad pattern here!
This shouldn't significantly affect anyone.

Add Disallow URLs to robots.txt for uselessly crawled endpoints

---

app/controllers/admin/users_controller.rb

This PR removes two comments within the `Admin::UsersController` related to the removed view component code that slipped through the cracks while fixing merge issues yesterday.
Relates to PR #16475 
Ensure that all checks pass. ✔️ 
N/A
appropriately. …

Removes Leftover Comments from Admin::UsersController

---

app/views/admin/users/emails/_form.html.erb
app/views/admin/users/flags/_index.html.erb
app/views/admin/users/notes/_form.html.erb
app/views/admin/users/notes/_index.html.erb
app/views/admin/users/reports/_index.html.erb

This PR adds some minor accessibility fixes to the new member details view. The Overview section, and shared UI like the header is covered in a separate PR (https://github.com/forem/forem/pull/16524), here I'm covering: Notes, Emails, Reports, Flags.
https://github.com/forem/forem/issues/16504
Visually, the UI should all look the same. I'll place some notes inline in the diff to highlight what each change is intended to do.
Fixes some minor accessibility concerns
[Changes …

Minor accessibility fixes for member detail views

---

app/policies/application_policy.rb

The comments speak for themselves
In support of https://github.com/orgs/forem/projects/46
Related to #16483
None
None

Documenting ApplicationPolicy

---

config/locales/views/misc/fr.yml

#16265 seemed to introduce an i18n key but not to the `fr` locale.
appropriately.
shared_

a missing i18n key (fr only)

---

README.md

- Adding myself to the core team on the readme
- as instructed in our internal onboarding documentation
Read readme, click `asheren` to make sure it correctly links to the dev.to profile
none
appropriately.
or in a …

add asheren to core team

---

app/liquid_tags/github_tag.rb
app/liquid_tags/github_tag/github_issue_tag.rb
app/liquid_tags/github_tag/github_readme_tag.rb
spec/liquid_tags/github_tag/github_issue_tag_spec.rb
spec/support/fixtures/vcr_cassettes/github_client_issue_with_dot_character.yml

Fixing the bug reported on https://github.com/forem/forem/issues/16465 after https://github.com/forem/forem/pull/16422 where Github Liquid Tags would be invalid when generated from repositories with the dot "`.`" character.
Here I'm just adding `/.` in the RegEx that are being used for Liquid Tag Parsing.
I'm also adding another test just to make sure that it works.
1. Start a new blog post
2. Use one of the following github liquid tags:
`{% github https://github.com/discordjs/discord.js/issues/6798 %}`
`{% github https://github.com/ethers-io/ethers.js/issues/2658 %}`
3. Click on `Preview`
4. See that `base: Invalid GitHub issue, pull request or comment link` error message is no longer appearing and the liquid tag is working correctly.
No …

Fix Github Liquid Tag from repositories with dot character

---

app/services/notifications/reactions/send.rb

- bug fix and slight refactor
Resolve a rare but occurring `NoMethodError: undefined method `[]' for nil:NilClass` bug derived from nil `aggregated_siblings`
Resolves https://app.honeybadger.io/projects/66984/faults/83609726
n/a

Apply safe navigation to Reactions::Send

---

cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js

I accidentally broke this E2E test when I merged a change to the E2E seeds that caused the credits user to no longer have an ID of 8. Instead of changing the seeds order, I'm removing the dependency on the user ID, because I think it's quite likely we'll accidentally knock this out in future 😄 
Broken in https://github.com/forem/forem/pull/16460
The build should go green again
N/A
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assig …

Fix admin user credits spec

---

app/javascript/packs/admin/editUser.jsx
app/views/admin/users/widgets/_credits.html.erb
cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js

Prior to the new member details view, there were two forms for adjusting credits. One for adding credits and another for removing credits. Each input to adjust the credit had a different max range. For adding credits, the maximum number of credits you could add was `9999`. For removing credits, the maximum number of credits you could remove was the number of unspent credits.
This PR brings back the correct maximum when removing credits.
Closes #16556
1. Run `bin/rails console`
2. In the rails console, enable the admin member view feature flag by running, `FeatureFlag.enable(:admin_member_view)`
3. exit the Rails console.
4. Login as the Forem admin account, email: admin@forem.local, password: password
5. Navigate to http://localhost:3000/admin/users and click on any username in the USER …

Now the credit amount max toggles when switching between adding/removing credits.

---

app/controllers/async_info_controller.rb

The email field is not guaranteed to be populated.
#16460 contains a subtle bug that we all missed, which is that `email` is not guaranteed to be populated on DEV, and approximately 2.2% of users on DEV do not have an `email` field, presumably due to OAuth logins through platforms that do not provide email addresses for all users.
- #16460 
- https://app.honeybadger.io/projects/66984/faults/84046611
- https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/ffxVgp2EtLT/a/b9ULzjhcP4h?hideMarkers …

Fix NoMethodError on User#email

---

spec/support/shared_context.rb

This also involves removing an un-used configuration.
Related to #16483
None.
None.

Refactoring shared context to remove assumption

---

app/javascript/.eslintrc.js
package.json
yarn.lock

pusher-js was a dependency of Connect which is no longer part of the codebase.
#14734
N/A
N/A
appropriately. …

✂️✂️ Removed the pusher-js dependency ✂️✂️

---

app/assets/stylesheets/config/_generator.scss
app/javascript/admin/controllers/article_controller.js
app/views/admin/articles/_individual_article.html.erb
app/views/admin/articles/index.html.erb
cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
cypress/integration/seededFlows/adminFlows/articles/unpinArticle.spec.js

This PR updates the frontend code of Admin's Articles Index view to NOT rely on Bootstrap anymore. This is the very first step of efforts to remove Bootstrap entirely from the codebase.
So instead of using Bootstrap styling we now use Crayons styling which obviously, as a side effect, updates the UI.
Keep in mind, the primary goal of this PR is NOT to redesign the view, but to drop Bootstrap in favor of Crayons. We will handle redesign separately as it will require more product thinking etc...
**Before:** 
**After:**
This should hopefully improve the accessibility just a little.  …

Admin Articles view update

---

.github/PULL_REQUEST_TEMPLATE.md

Providing further guidance to remind/help folks to indicate if the PR closes an issue.
None.
Submit a pull request!
None

Adding docs regarding auto-linking PR to issue

---

app/controllers/application_controller.rb
app/policies/application_policy.rb
config/application.rb
config/locales/misc/en.yml
config/locales/misc/fr.yml
spec/policies/application_policy_spec.rb

Plumbing application for probable AuthN/Z changes
For further details, core members can read:
- [Forem Article Authorization Discrepencies][1]
- [Forem Authentication and Authorization Principles][2]
(Note: there's nothing "private" about these articles, I happened to
post them on https://forem.team for internal discussion.)
Related to #16529
[1]:https://forem.team/jeremy/forem-article-authorization-discrepencies-45df
[2]:https://forem.team/jeremy/forem-authentication-and-authorization-principles-58l3

Plumbing application for probable AuthN/Z changes

---

app/controllers/api/v0/tags_controller.rb
app/javascript/article-form/components/TagsField.jsx
spec/requests/api/v0/tags_spec.rb

To display the richer tags UI (with background colors etc) we need to fetch some tag information when a user edits an existing post. Previously we did this with up to 4 `/search` requests to grab each tag individually. This refactor uses the tags API to instead fetch all at once.
NB: It was an oversight of mine that we actually need that bulk GET endpoint to return tags by _name_ rather than ID. I've updated the controller to return tags by name, if the param exists, but I haven't replaced the previous 'tags by id' code (and if both IDs and names are provided, IDs are preferred and the names are ignored). 
- Create a post that includes some supported, and some unsupported tags (i.e. some which you select from the dropdown, and some you've freestyled)
- Edit the post and check that only …

Only make one network call to fetch all existing tags in editor

---

app/javascript/articles/Article.jsx
app/javascript/articles/Feed.jsx
app/javascript/packs/homePageFeed.jsx

Filter feed posts to include featured and pinned posts for logged in users where pinned posts only show up top when on "Relevant" tab (timeFrame = '')
Related to #16508 
appropriately.
or in a …

Fix pinned post not showing on feed tabs

---

.github/PULL_REQUEST_TEMPLATE.md

I noticed after https://github.com/forem/forem/pull/16584 issues weren't closing for me after merging PRs using the template. After a little experimentation it seems that if you include the `Closes ...` after a task item (`[ ]`) then the issue isn't properly linked with the PR.
So I'm just removing the task boxes.
N/A
N/A
issue template so Community Success …

Update PR template to ensure issue linking

---

app/models/user.rb
app/serializers/search/user_serializer.rb
app/services/search/user.rb

While slowly offboarding myself I started going through old TODO comments. I think it's time we pull the plug on these methods that according to the comments by me and rhymes should no longer be necessary.
Nothing specific, this should all be covered by existing specs. 🤞
No UI changes

Remove unused methods from `User`

---

app/models/admin_menu.rb

This PR removes what appears to be an unused menu item/comment from `admin_menu.rb`.
N/A
All checks should pass. ♻️  
N/A
appropriately.
N/A

Removes Comment from Admin Menu

---

Gemfile.lock

One of the dependencies for feature flags changed, but the gemfile.lock wasn't updated
This showed as a deploy error in
https://app.travis-ci.com/forem/forem/builds/246802177
```
Bundler Output: You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
```
I assume this started with https://github.com/forem/forem/pull/16630 which looked reasonable (but failed the same way in buildkite) https://buildkite.com/forem/build-containers/builds/11689#c3f77baf-e1ef-4a2d-94e3-5cae758da227
run bundle install or bin/setup, and no additional changes should be seen in the Gemfile.lock
none …

Update flipper in gemfile.lock

---

app/controllers/admin/listing_categories_controller.rb
app/controllers/api/v0/listings_controller.rb
app/controllers/concerns/listings_toolkit.rb
app/controllers/listings_controller.rb
app/models/listing.rb
app/services/listings/bump.rb
spec/requests/listings_spec.rb

This is the 3 PR in the series of listing code refactorings I started a while ago. I just noticed it's been sitting in draft for a while, not quite sure how that happened, I apparently just forgot about it 🤦

More listings refactoring

---

app/controllers/api/v0/api_controller.rb

As I was investigating an approach for #16488, I stumbled upon two
methods partially doing the same thing.  This helps consolidate the
logic and provides some guiding documentation.
- Related to #16488
None.
None.

Removing duplicate logic and adding docs

---

app/controllers/api/v0/api_controller.rb

In conversations with citizen428, this method looked to be a holdover
from a past approach.  Reviewing the code, we can get the same behavior
with other methods.
Further, I added some comments for future considerations, and refactored
for more readily scannable guard clauses.
- Related to forem/forem#16488, forem/forem#16681, and forem/forem#6255
- Closes # :: alas none
Going to rely on our test suite for these.

Removing somewhat duplicated logic

---

app/views/admin/users/show/notes/_form.html.erb
app/views/admin/users/show/notes/_index.html.erb

This PR updates the copy for the "Notes" tab per [this](https://www.figma.com/file/sZBBadfB9OqO6wpfBdXjRf/(copy-edited)-member-detail-view?node-id=0%3A1) figma file.
- Related Issue #16507 
Please ensure that there are no spelling errors. You can also compare these copy changes against the figma file. Finally, ensure that all checks pass. ♻️ 
N/A
issue …

Update the Copy for the "Notes" Tab in the Admin Member Detail View

---

app/views/admin/users/show.html.erb
app/views/admin/users/show/emails/_form.html.erb
app/views/admin/users/show/emails/_index.html.erb
app/views/admin/users/show/emails/_verification.html.erb

This PR updates the copy for the "Emails" tab per [this](https://www.figma.com/file/sZBBadfB9OqO6wpfBdXjRf/(copy-edited)-member-detail-view?node-id=0%3A1) figma file. Additionally, this PR removes some of the previous copy pertainign to verifying emails and refactors the appearance of email verification on a user's page as whole since we do not have copy for the previous email verification section. Please note that not all copy changes for the "Emails" tab will be made at this time, as the AE team is still adding features and polishing the tab.
- Related Issue #16507 
Please ensure that there are no spelling errors. You can also compare these copy changes against the figma file. Finally, ensure that all checks pass. ♻️ 
_If your PR includes UI changes, please replace this line with …

Update the Copy for the "Emails" Tab in the Admin Member Detail View

---

README.md
app/models/article.rb
app/services/users/suggest_for_sidebar.rb
config/environments/development.rb
config/environments/test.rb
config/routes/admin.rb
cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js

✂️  Remove myself from core contributors

---

app/views/admin/users/show/flags/_index.html.erb

This PR updates the copy for the "Flags" tab per [this](https://www.figma.com/file/sZBBadfB9OqO6wpfBdXjRf/(copy-edited)-member-detail-view?node-id=0%3A1) figma file. 
- Related Issue #16507 
Please ensure that there are no spelling errors. You can also compare these copy changes against the figma file. Finally, ensure that all checks pass. ♻️ 
N/A
issue …

Update the Copy for the "Flags" Tab in the Admin Member Detail View

---

app/assets/javascripts/utilities/getCsrfToken.js

This is a very initial effort to investigate https://github.com/forem/forem/issues/16712. All that I'm really changing here is:
- 1.5x retry duration
- retry interval has been greatly increased (but it's still very short - a quarter of a second)
- Related: https://github.com/forem/forem-internal-eng/issues/341
- Closes https://github.com/forem/forem/issues/16712
Not much to see here - app should continue to function as normal
N/A
[Changes …

Amend CSRF token retries

---

app/views/admin/users/show/overview/_organizations.html.erb
app/views/admin/users/show/profile/_actions.html.erb
app/views/admin/users/show/profile/actions/_banish.html.erb
app/views/admin/users/show/profile/actions/_delete.html.erb
app/views/admin/users/show/profile/actions/_export.html.erb
app/views/admin/users/show/profile/actions/_merge.html.erb
app/views/admin/users/show/profile/actions/_social_accounts.html.erb
app/views/admin/users/show/profile/actions/_unpublish.html.erb
cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js

This PR updates the copy for the modals throughout the Admin Member Detail view per [this](https://www.figma.com/file/sZBBadfB9OqO6wpfBdXjRf/(copy-edited)-member-detail-view?node-id=0%3A1) figma file. 
- Closes Issue #16507 
Please ensure that there are no spelling errors. You can also compare these copy changes against the figma file. Finally, ensure that all checks pass. ♻️ 
N/A
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=c …

Update the Copy for all Modals in the Admin Member Detail View

---

app/assets/javascripts/initializers/initializeBodyData.js

This is a small refactor that I'm hoping will solve https://github.com/forem/forem/issues/16713. It removes use of outdated `XmlHttpRequest` for `fetchBaseData()`, instead using `fetch` like elsewhere in our codebase.
- Related: https://github.com/forem/forem-internal-eng/issues/341
- Closes https://github.com/forem/forem/issues/16713
- Spin up the app locally, try logging in and out and check that the correct user (or no user if logged out) is reflected in the `<body>` element dataset. 
- Check the `meta` tags noted in the code are successfully added/updated in the document `<head>`
N/A …

Favour fetch to XmlHttpRequest

---

app/assets/javascripts/initializers/initNotifications.js

We current access the `<meta>` tag with csrf token details directly in this function, and we've seen some errors in Honeybadger where the relevant meta tag isn't available at the time it's accessed. This PR refactors the function to use the `getCsrfToken` helper, which retries and accounts for the async nature of it being set. I've also switched up a couple of requests to use `fetch` just to bring it over to a more modern approach.
- Related Issue https://github.com/forem/forem-internal-eng/issues/341
- Closes https://github.com/forem/forem/issues/16716
- Log in to a user who has notifications
- Read the notifications
- Check in the dev tools network tab the appropriate `/notifications/reads` POST request is still sent to mark them as 'read'
N/A
_Will this PR introduce a change that …

Refactor markNotificationsAsRead to use getCsrfToken helper

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

As I'm looking at limiting feed fetching only for users who are able to
create articles, I needed a means of querying "Who are the users who can
create articles?"  This bit of work was the smallest chunk that I could
think of.
These kinds of questsions are going to propogate (e.g. give me a list of
all the people who can comment? who can create articles in this space?)
For now, this pattern should suffice.
Yes, there's duplication of knowledge between the policy's instance
method and class method.  And there's a bit of knowledge bleed between a
user's method (e.g. `user.any_admin?` and
`*Authorizer::RoleBasedQueries::ANY_ADMIN`) but that's a small "evil".
- Related Issue #16486
None.  This is code that makes things easier in the future.
None.

Adding ArticlePolicy.scope_users_authorized_to_action

---

app/assets/javascripts/utilities/buildArticleHTML.js
cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
spec/support/seeds/seeds_e2e.rb

If you visit any of our pages that use `buildArticleHTML.js` to construct the profile preview card, you'll see an error in the console for any user with an apostrophe in their name, and their follow buttons will not be initialized properly.
Some previous work was completed to escape punctuation in user names here, but due to the way we're constructing the HTML as a string, things get pretty complicated and the TL;DR is that escaping apostrophes (single quotes) with a backslash doesn't work here. In this PR I substitute them with `&apos;` instead.
- Closes https://github.com/forem/forem/issues/16734
- Create some articles locally by users with apostrophes in their name
- Check when you view them in the feed, the profile preview card follow buttons work correctly and no error is present in …

Fix error in feed follow buttons where user name has apostrophe

---

app/views/admin/tags/_form.html.erb
cypress/integration/seededFlows/adminFlows/tags/createATag.spec.js

This adds the new color picker to the admin tag create/edit form: `/admin/content_manager/tags/new` / `/admin/content_manager/tags/${tagID}/edit`
- Related Issue https://github.com/forem/forem/issues/15179
- Log in as an admin user
- Create a new tag via the form at `/admin/content_manager/tags/new`
- You should see the new color picker, and be able to either use the text input or color picker popover to pick the tag color
- Submit the form and check all values are populated correctly
- Try editing the color again, just for good measure 😄 
This is a little bit of an accessibility boost …

Add new color picker to admin tag form

---

app/views/users/_extensions.html.erb
app/views/users/_web_monetization.html.erb
config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml

There are three things I'm introducing in this PR:
1. Extracting a partial
2. Reworking the i18n keys
3. Adding a policy check regarding Web Monetization
In *extracting a partial*, I'm following the existing pattern where other extensions have their own partial.
In *reworking the i18n keys*, I'm ensuring that the keys are part of the same namespace.  This will make finding their usage easier.  Further, if we decide to remove (or convert to a plugin) the web_monetization, then we're just a bit closer to that possibility.
Last, and the reason for the work, is *Adding a policy check regarding Web Monetization*.  This follows on the work in forem/forem#16790.
Closes forem/forem#16820
Related to forem/forem#15098
There are two things to test:
1. Does the feature flag work or not.
2. Are the …

Authorize Web Monetization If User Can Create Article

---

app/controllers/notifications_controller.rb

```shell
❯ rg "@notifications_index"
```
The above shell command exits status code 1, which means there are no
results found.
This relates to exploratory work for forem/forem#16821
None.
None.

Removing unused instance variable

---

.travis.yml
app/lib/url.rb
spec/lib/url_spec.rb

Several members of Fleet Forems have complained about not being able to embed valid, accurate forem-specific links (e.g. post, comment or profile links). This PR tests a potential solution for this problem JUST on the Canary2 forem.
NONE. The QA shall be done on https://canary2.forem.wtf after this PR is deployed to that forem.
None; all backend changes.
If the testing is successful, I will discuss with the relevant team members
about rolling this solution out to the rest of the fleet.

Test Solution for Forem-link Embed issues on Canary2

---

app/assets/stylesheets/article-show.scss

Fixed the bug where the pause/play button is prevented from disappearing.
issue #16759  …

Fix pause button

---

package.json

While writing up some documentation, I discovered jest configuration that isn't even used since we now use a jest.config.js file for configuration.
- Closes #
N/A Testing infrastructure cleanup
N/A Testing infrastructure cleanup
appropriately. …

chore: Removed unused jest configuration setting

---

jest.config.js

Our test coverage in the frontend has gone up, so bumping the jest test coverage thresholds.
File                                                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s          
----------------------------------------------------|---------|----------|---------|---------|----------------------------
All files                                           |   45.14 |    46.31 |   43.61 |   45.31 | 
- Closes #
N/A Testing infrastructure
N/A Testing infrastructure …

chore: Increased jest test coverage thresholds

---

config/locales/views/moderations/fr.yml

Fix an issue changes made by #16544 not reflected in the French locale.
- Closes # …

Correctly update moderations/fr.yml

---

app/models/admin_menu.rb
app/views/admin/shared/_tabbed_navbar.html.erb
spec/models/admin_menu_spec.rb

This relates to PR forem/forem#16847 which addresses issue
forem/forem#16842.
The goal of this PR is to help me develop an understanding of the
AdminMenu so I can further extend it and better understand it.
There's also a bit of knowledge sharing that I'm looking for, and the
comments and tests are there to help "confirm" that knowledge.  There
might be more that I'd consider regarding a refactor, but I want to make
sure I'm on the right path before I go further.
tl;dr - this is the smallest commit I can make to begin to tease out an
understanding of the method I put under test.
- Related Issue forem/forem#16842
Fire up the site and poke around in the admin navigation?  This should be a non-change.1
None.

Adding docs and specs to AdminMenu.nested_menu_items

---

app/views/admin/users/show/profile/actions/_banish.html.erb

This PR removes a duplicate banish confirmation modal from the Member Detail View.
- Relates to #16910 
To QA this PR, navigate to `/admin/users/#id` and ensure that you are only prompted to confirm banishment with one confirmation, rather than two (as shown below):
There shouldn't be! …

Remove Duplicate Banish Confirmation Modal from Member Detail View

---

README.md

Gitpod is not `GitPod`. Fixes up #5931.
Fixes up #5931
Relevant PR on forem-docs: https://github.com/forem/forem-docs/pull/52

Fix typo: Gitpod

---

app/controllers/dashboards_controller.rb

There is an incredible amount of conditionals in play within this
controller.  I'm working to disentangle the logic so we can introduce
unified authorization policies.
The first step is removing the quasi-opaque "before_action" behavior
related to authorization.  My strong preference is to make that explicit
and in doing so begin to see how to adjust the policy enforcement/creation.
This relates to forem/forem#16913
None.  This is a noop change.
None.

Removing before actions in favor of explicit method

---

app/views/admin/users/index.html.erb
app/views/admin/users/index/_controls.html.erb
app/views/admin/users/index/_tabs.html.erb

In this PR I simply move boxes around to match the general of the layout for the new Admin Index View. I've also moved the tabs and filters into its own partials. During subsequent PR's the team will be working on this simultaneously, and having this in place will just make it easier to collaborate on.  
There are no accessibility changes in this PR. I just moved things around. 
- Closes #
1. Run `FeatureFlag.enable(:admin_index_view)`
2. Ensure that the updated changes as per the screenshot show up.
We'll tackle the accessibility concerns in the future PR's. Fore now this provides a skeleton for the new view. 
will …

Updated Member Index View Layout foundation behind a feature flag.

---

.env.test
.travis.yml

Create .env.test file (linked to .env_sample) which isolates the test environment from any developer added credentials in the .env file.
This follows after observing an api key (used for local development) was mistakenly present in a committed spec file. The expectation is that changes to .env still take effect in development, but all tests run with a common configuration (identical to the sample env). If a working configuration is needed (APP_DOMAIN, for example) it should be valid in the .env_sample file (or tests will fail).
You should be able to run the specs without a .env file (`mv .env .env.saveme; bundle exec rspec spec/some/file/path.rb`) but you probably could do that before, too.
More to the point, if you modify a sample value in your .env file ( setting …

symlink .env_sample as .env.test

---

app/views/articles/index.html.erb
app/views/stories/tagged_articles/index.html.erb
spec/requests/stories/tagged_articles_spec.rb
spec/requests/stories_index_spec.rb
spec/system/articles/user_visits_articles_by_tag_spec.rb

Use the canonical URLs (without a trailing slash) to link from sorted pages like `https://dev.to/t/forem/latest` or `https://dev.to/latest` to Relevant pages like `https://dev.to/t/forem` or `https://dev.to/`.
n/a
n/a
Using canonical URLs is SEO-friendly.
issue template so Community Success can …

Use the canonical URLs to link from sorted pages

---

app/liquid_tags/youtube_tag.rb
spec/liquid_tags/youtube_tag_spec.rb

One of my users wanted to embed a YouTube video with timestamp in the format `t=1000s`, which is accepted by the YouTube server. When I looked at past commits, they *purport* to support integer in seconds (`t=1000`) but the code actually not. This PR fixes it.
Now it receives any of below:
```
{% youtube f1A7SdVTlok&t=1000 %}
{% youtube f1A7SdVTlok&t=1000s %}
{% youtube f1A7SdVTlok&t=16m40s %}
```
- Related Issue #15420, #15890
N/A
[Changes …

youtube tag timestamp format fix

---

app/views/admin/users/_member_index.html.erb
app/views/admin/users/index.html.erb
app/views/admin/users/index/_controls.html.erb

This PR is the first of a handful of PRs that focuses on updating the columns and search/filter fields on the Member Index View layout to match the Member Index View designs. This PR lays out the bare-bones columns needed for further work on the Member Index View and has been kept super small to avoid bloat.
To accomplish this, this PR does the following:
- Related Issue #16911 
To QA this PR, please enable the `member_index_view` feature flag and then navigate to `/admin/users` to observe the changes shown below: 
Possibly? I hope not!  …

Update Member Index View Layout

---

app/controllers/dashboards_controller.rb

As I'm looking at the dashboard, there's lots of small duplication.
This refactor is a way to help me collect my thoughts regarding how to
approach the larger issue at hand.
Only loosely related to forem/forem#16913
None
None

Refactoring methods to remove duplication

---

app/javascript/profileDropdown/blockButton.js
spec/rails_helper.rb

Removing a JS message about connect

---

app/policies/organization_policy.rb

As part of my AuthN/AuthZ work I'm reviewing policies.  I've been
looking at Dashboard pseudo-policies.  The dashboard has some implicit
organization policies that I'm looking to expose and describe.
This refactor simply leverages methods already on the user.
Discovered while working on forem/forem#16985
None.
None.

Reducing duplication of knowledge

---

app/models/admin_menu.rb
app/views/admin/users/_menu.html.erb

We're renaming the terminology from "People" to "Members". Hence a small change that we can implement in preparation for the new Member Index View is to change the terminology in the nav item. 
Note that we haven't changed it in the breadcrumbs as it currently maps to the controller name and we'll need to figure out how to approach that. This is not a regression as the breadcrumbs were different to the nav item name in any case before this change was made. 
- Closes #https://github.com/forem/forem/issues/16993
None …

Change the admin nav item from "People" to "Members"

---

app/views/admin/users/index/_controls.html.erb

In member list view role filter, the first dropdown selection is blank but it works as "All roles" filter. Hence, we want to call it "All roles" in dropdown to be more indicative of its use. 
Did not link a ticket, I've just tracked the PR on the board.
updated. I have filled out …

Add a named blank option to the filter dropdown on the Member Index View

---

.github/workflows/issue.yml

This PR updates the feature request link and team tag in for our `github-actions` bot.
- Related Issue #16756 
To QA this PR, please look over the changes and ensure that the link points to the correct forem.dev post, that the team tag is correct, and that there are no typos.
N/A
appropriately. …

Update github-actions Bot

---

app/models/settings/general.rb

- Bug
Resolves https://github.com/forem/forem/issues/17034
n/a

Make onboarding_background_image nullable

---

app/helpers/application_helper.rb

This is the happy byproduct of my waiting for Heroku's git server to
come back online.
What follows is my attempt to provide inline documentation for
application helper methods.  I haven't done all of them, but this is my
effort to inch forward the state of our internal documents.
Along the way, I've discovered a discrepency (and noted it but am not
going to proceed with any refactor).
None
Please read the comments to see if they make sense.
None.

Adding some docs for ApplicationHelper

---

app/controllers/dashboards_controller.rb

Unearthed in a deep read of the code during the review of forem/forem#16997
Please read from a "does this logic make sense" perspective.
forem/forem#16997
None
None.

Adjusting logic to match intention

---

app/views/admin/profile_fields/index.html.erb

From Jennie (in slack, a while ago).
> I want to replace that copy with "To get started, add a group.  Then you can add fields to each group. Groups and fields will show up in this same order on the user's profile page." 
So I did. 
- Related Issue https://github.com/forem/forem-internal-eng/issues/352
Ensure you have the profile_admin feature flag enabled.
Visit the http://localhost:3000/admin/customization/profile_fields page.
At the top of the page you'll see instructions on how to use this feature.
No different from before (text content of a `p` tag was replaced).

Update profile admin instructions

---

cypress/integration/creatorOnboardingFlows/creatorSignup.spec.js

Replaces the word "an" with "a" in the `creatorSignup.spec.js`.
N/A
All checks should pass. ♻️ 
N/A
appropriately.
N/A

Remove a Letter from E2E Expectation in creatorSignup.spec.js

---

app/views/users/_customization.html.erb

Prior to this commit, only those who could create posts could edit their confi
However, we are allowing users who can't create posts to edit posts.  So
we want to allow for them to change their editor configuration.
Revisits
- forem/forem#16516
Supplants
- forem/forem#16778
Related to
- forem/forem#17123
- forem/forem#16908
None
None

Applying more liberal editor config policy

---

app/controllers/async_info_controller.rb

Prior to this commit we hand an unless code block with a return then we
set an instance variable.
On a quick scan I didn't notice the return but saw the render followed
later by the instance variable.
This change is logically the same, my hope is that it's just a bit more legible.
Only because I was in the neighborhood for 
- forem/forem#17119
- forem/forem#17076
None.
None.

Re-arranging method to be less surprising

---

app/views/admin/users/_member_index.html.erb
app/views/admin/users/index/_organizations.html.erb

Instead of going through the join table `organization_memberships` we can just use the `organization` relationship to show the organizations that a user belongs to.
- Closes #
Ensure that the same number of organizations appear when switching between master to this branch. No outcomes should have been changed. 
None, I have not changed any HTML or css here.
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes …

Refactor the way we show organizations on the member index view

---

app/helpers/rate_limit_checker_helper.rb
app/views/admin/settings/forms/_rate_limit.html.erb
spec/helpers/rate_limit_checker_helper_spec.rb

Closes forem/forem#17175
None.  Small UI change.
None.

Removing Listing rate limiting when feature disabled

---

app/views/admin/users/_member_index.html.erb
app/views/admin/users/index/_member_data.html.erb
app/views/admin/users/index/_organizations.html.erb
app/views/admin/users/index/_status_indicator.html.erb

Now we have our responsive layouts pinned down it's clear we have some repeating chunks of HTML code in this new member index view. This PR extracts these chunks into partials.
- Related Issue https://github.com/forem/forem/issues/16911
- Make sure you have the `member_index_view` feature flag enabled
- Check the layout at each breakpoint (mobile, 768, 1024, 1280) against [the designs](https://www.figma.com/file/Ejc7VELuN00n1SZrkUTBcQ/Member-List-View?node-id=945%3A6102)
- There shouldn't be any regression in the UI matching the designs
N/A

Admin member index: bring repeating layout code into partials

---

app/services/podcasts/create_episode.rb
spec/services/podcasts/create_episode_spec.rb
spec/support/fixtures/podcasts/design_takoy.rss

When we generate the slug for a podcast episode, transform the title to ascii so it matches the validation
Original issue (fixed) is exclusively non-latin script in podcast episode titles leads to empty slugs (and the episode consequently cannot be visited via a link). 
I'm adapting the conversion we use for Article#title_to_slug
without the random trailing bits on the end (since podcast episodes
had not worked that way previously, there's an assumption you give unique titles to your episodes in the series).
- Closes #17168 
To test this I added "https://anchor.fm/s/2f18796c/podcast/rss" as a suggested podcast, enabled/published it in admin, and ran the feed import. 
I found I needed to enable caching in dev (because we use rails cache to pass large argument objects via redis to the …

Produce a meaningful slug from podcast episode title

---

app/models/admin_menu.rb
spec/models/admin_menu_spec.rb

Related to forem/forem#16437
- Closes #
None.
None.

Conditionally removing listing from Admin > Consumer Apps menu

---

app/views/pages/_editor_liquid_help.html.erb
app/views/pages/_supported_url_embeds_list.html.erb

Use correct trademarks in supported embeds in the liquid modal on `/new#liquid`.
n/a
| before | after |
|-|-|
| ![forem-liquid-before](https://user-images.githubusercontent.com/10229505/162558751-4c7c9498-42ca-4ed0-a48e-8fb824675847.png) | ![forem-liquid](https://user-images.githubusercontent.com/10229505/162558651-5fa4eb49-abf6-423b-9629-ff8c553a6c31.png) |

Use correct trademarks in supported embeds

---

app/views/mailers/notify_mailer/new_badge_email.html.erb
app/views/mailers/notify_mailer/new_badge_email.text.erb
app/views/notifications/_badgeachievement.html.erb

Prior to this commit, our notifications would send listing related information.
- Related Issue forem/forem#16437
None
None

Conditionally removing listing reference

---

app/controllers/admin/users_controller.rb
app/views/admin/users/_member_index.html.erb

This PR move eager loading from the Member Index View and into the `Admin::UsersController` by updating `Admin::UsersQuery` within the `index` method.
- Related Issue #16911 
Ensure that all checks pass. ♻️ 
N/A
appropriately.
[`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.m …

Refactor Member Index View Users Query 

---

app/views/admin/users/show/profile/actions/_export.html.erb

Fixed Typo

---

spec/requests/articles/articles_feed_spec.rb

I couldn't find any test cases for the rss feed, when reviewing #17219 so I wrote one. Committing the test here, which ensures there's some coverage of this endpoint (if the method is completely broken or the route goes away something will fail).
- Related Issue #17219 
Added a test. It should pass.
None

Add minimal test on rss feed response

---

spec/requests/admin/overview_spec.rb

This follows the work in #17165 - the service test and this request
spec are exercising nearly identical timezone sensitive paths.
- Related Issue #17165 
Run the spec in various timezones (I prefer Alaska and Samoa, but dealers choice).
None
appropriately. …

Disable two time zone sensitive tests 

---

app/assets/stylesheets/components/toggles.scss
app/javascript/crayons/formElements/Toggles/Toggle.jsx
app/javascript/crayons/formElements/Toggles/__stories__/Toggles.stories.jsx
app/javascript/crayons/formElements/Toggles/__tests__/__snapshots__/Toggle.test.jsx.snap

This is a followup for our **just** merged [Toggle component](https://storybook.forem.com/?path=/story/components-form-elements-toggles--default). It's inspired by the [suggestion of one of our community members](https://dev.to/afif/comment/1nd2i) that we can technically create toggle like this without any extra markup. Which I think is a great simplification for our devs.
- https://dev.to/afif/comment/1nd2i
1. Spin up `yarn storybook`
2. Go to our Toggle component `/?path=/story/components-form-elements-toggles--default` and if it looks ok then it's ok to merge :D

Crayons Toggle Update

---

yarn.lock

It looks like some storybook updates crossed and resulted in the lockfile not being quite right. This PR commits the correct lockfile.
N/A
Running `yarn install` locally shouldn't generate any changes to the `yarn.lock`
N/A
appropriately. …

Resolve yarn lockfile

---

app/views/admin/users/gdpr_delete_requests/index.html.erb

This PR applies the [new member index styles](https://www.figma.com/file/Ejc7VELuN00n1SZrkUTBcQ/Member-List-View?node-id=708%3A5065) to the GDPR delete requests table.
There are some slight differences to the design because we don't currently hold on to a user's profile image or name after they're deleted. As such, you'll see only the username, email, and 'deleted on' date reflected in the UI for now.
There's not much data in this view, so the PR covers both the smaller-size layout as well as the large desktop table. The PR however _does not_ add the search feature, or change the 'confirm deleted' flow.
- Closes https://github.com/forem/forem/issues/16961
You will need to some deleted users to be able to test this feature locally. You can manually delete some through the admin interface, …

Admin member index: style the GDPR requests table

---

app/models/settings/rate_limit.rb

Avoid processing user-supplied strings in a regex
- https://app.honeybadger.io/projects/66984/faults/84991369 …

Escape user-supplied regex terms

---

app/lib/constants/settings/general.rb

Avoids redirections by replacing with newer URL in the app.
- Related Issue #17208
- Related PR #6345, #9639, #13851, #13950
Similar to #6345
n/a

Avoid redirection by replacing with newer URL

---

app/controllers/admin/users_controller.rb
app/helpers/admin/users_helper.rb
app/views/admin/users/_member_index.html.erb
app/views/admin/users/index/_organizations.html.erb
spec/helpers/admin/users_helper_spec.rb

In this PR, I limit the organizations displayed on the UI and then display an overflow count.
What still needs to be done: 
- Need to check for accessibility
- It needs to be styled appropriately
- Cypress tests need to be written for its final form
- Related Issue #https://github.com/forem/forem/issues/16911
A brute force method to setup your db and display these changes: 
The end goal is to create a bunch of organizations and add a user to those organizations. We should show the first 3 organization images and then a count of the overflow. 
- Create 6 more organizations by running this script
```
6.times do
Organization.create!(
name: Faker::Company.name,
summary: Faker::Company.bs,
profile_image: logo = File.open(Rails.root.join("app/assets/images/#{rand(1..40)}.png")),
nav_image: …
```

Limit an organizations displayed and add an overflow count 

---

app/views/admin/users/index/controls/_export.html.erb

We have the aria-label on the button, but some screen readers try to announce the SVG as well, so it's nice to hide it.
- Closes #
https://github.com/forem/forem/pull/17259#discussion_r850477026
appropriately.
[`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG. …

Add an aria-hidden attribute

---

app/assets/images/chevron-left.svg

When creating the new pagination layout for member index view, I (incorrectly) assumed I could re-use the `chevron-right` SVG for the left-pointing arrow, by rotating it 180. I found out today Safari ignores that property, meaning that in Safari the pagination had two right-pointing arrows 🙈  TIL
In this PR I update the `chevron-left` SVG accordingly.
- Related Issue https://github.com/forem/forem/issues/16933
- Make sure you have the `member_index_view` feature flag enabled
- In Safari, visit `admin/users`
- Check the pagination UI
Before:
After:
Definitely improves the clarity of what the controls do 😆  …

Update chevron left SVG

---

app/assets/stylesheets/config/_generator.scss
app/views/admin/users/index/_organizations.html.erb
cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
spec/support/seeds/seeds_e2e.rb

This PR styles the organizations data in the new member index view, according to [the designs](https://www.figma.com/file/Ejc7VELuN00n1SZrkUTBcQ/Member-List-View?node-id=708%3A5065). It also adds Cypress tests for the presentation of basic data in the table/list.
- Closes https://github.com/forem/forem/issues/16911
- You will need a minimum of 4 organizations to test this feature. You can add new organizations in the console by using the snippet:
```ruby
Organization.create!(
name: Faker::Company.name,
summary: Faker::Company.bs,
profile_image: logo = File.open(Rails.root.join("app/assets/images/#{rand(1..40)}.png")),
nav_image: logo,
url: Faker::Internet.url,
slug: "org#{rand(10_000)}",
github_username: "org#{rand(10_000)}",
twitter_username: "org#{rand(10_000)}",
bg_color_hex: …
```

Member index: update the organizations UI

---

cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js

A small enhancement to an existing cypress spec
- Closes https://github.com/forem/forem/issues/15483
If all is well, the build should pass 🙂 
Not really, but it means our spec is now testing the a11y of these checkboxes a little more
appropriately. …

Reference checkboxes by name in creatorSettings spec

---

app/views/admin/spaces/index.html.erb

Updating copy.
Closes forem/forem#17322
None.
None.

Adjusting copy per guidance

---

config/locales/views/stories/en.yml
config/locales/views/stories/fr.yml
spec/requests/stories/tagged_articles_spec.rb

Signed-off-by: Harmouch101 <eng.mahmoudharmouch@gmail.com>
- Closes #
updated. I …

Fixed a grammatical error.

---

app/services/podcasts/create_episode.rb
spec/services/podcasts/create_episode_spec.rb
spec/support/fixtures/podcasts/codepunk.rss

There is an early return from add_media_url to prevent using an empty
enclosure_url, which avoids errors in
`GetMediaUrl.call(a_blank_value)`, however there's also a not null
constraint on podcast_episodes.media_url in the database, which causes
upsert to raise an error.
Returning early here avoids the error (which had halted the worker).
See also
https://app.honeybadger.io/projects/66984/faults/80833402
This error happens regularly, 96 times per day in DEV, it looks like at least
one podcast feed_url is for an rss feed filtered by /tag/podcast/,
(and at least one post was tagged "podcast" but didn't include any
media to get).
My understanding is at worst we'll ignore the error silently.
https://app.honeybadger.io/projects/66984/faults/80833402
The issue in DEV is related to the rss feed …

Don't create podcast episodes without any media

---

app/controllers/admin/users_controller.rb

replace `ATTIBUTES` with `ATTRIBUTES` for the user csv columns. 
None

fix typo in constant name

---

.github/workflows/codeql-analysis.yml
spec/models/podcast_spec.rb

Replace git.io with the destination URL.
https://github.blog/changelog/2022-04-25-git-io-deprecation/
None
Skip
None
appropriately.
replace this line with details on why this …

Replace git.io URL

---

app/queries/admin/users_query.rb
app/views/admin/users/index/_controls.html.erb
cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js

In [this PR](https://github.com/forem/forem/pull/17388) we removed the ability to search by email, however, it was brought up [here](https://forem-team.slack.com/archives/C01S4QZUDNC/p1651155172699349) that folks do actually search by email. 
Hence, this PR pops the query back into the codebase.
- Closes #
Go to http://localhost:3000/admin/users and search by a users email. You should also be able to search by name or username.
None …

Add search by email back

---

.travis.yml

The discussion on the gibbon PR (321) suggests the following:
-  "this would only be a problem if you accepted an API key via user
input"
-  author: "I implemented what I believe is a complete fix in 3.4.4"
This conflicts with the github advisory (and bundle audit) interpretation of the fix.
We do accept mailchimp api keys from user input (restricted to
the admin area).
It looks like the underlying conflict is around domain
include?(api.mailchimp.com) permitting matches that aren't
authoritative (for example, api.mailchimp.completelyhijacked.xyz would
"include?" the right domain).
Since we use this Gibbon gem only in our Mailchimp Bot, disabling the gem (suggested "fix" in the advisory) would disable user control of their subscriptions, or require us to reimplement the parts of the gem we …

Ignore CVE-2022-27311

---

app/helpers/articles_helper.rb
spec/helpers/articles_helper_spec.rb

URL strings that have leading or trailing spaces raise exceptions when parsing, so we strip whitespace from the URL before passing it through.
- Visit the new-article page
- Set `canonical_url: www.example.com ` (note the trailing space)
- Save
- Load that article page
On `main`, you should see an HTTP 500 on viewing. On this branch, it should render the canonical URL.
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels …

Sanitize URL before parsing

---

app/views/admin/invitations/index.html.erb

This PR renames the "Invited member" column in the invitations table to "Username".
- Closes #17452 
N/A
appropriately. …

Rename "Invited Member" to "Username"

---

app/controllers/admin/gdpr_delete_requests_controller.rb
app/models/gdpr_delete_request.rb
app/views/admin/users/index/_tabs.html.erb
app/workers/users/delete_worker.rb
config/initializers/inflections.rb
db/migrate/20201012072557_create_users_gdpr_delete_requests.rb
spec/factories/gdpr_delete_requests.rb
spec/requests/admin/gdpr_delete_requests_spec.rb
spec/workers/users/delete_worker_spec.rb

It came up in [this PR](https://github.com/forem/forem/pull/17538#discussion_r864598236) that we're titlizing the sidebar navigation items, and hence "GDPR delete requests".titleize will result in "Gdpr Delete Requests". 
Hence, we want to create an inflection for the GDPR Delete Requests and amend the class names in the files as per this rule. 
Now [when we titleize the sidebar nav item](https://github.com/forem/forem/blob/71e9f2bfb465d2373107995824a678481d0f3bac/app/views/admin/shared/_nested_sidebar.html.erb#L31) it will work as follows:
```
[2] pry(main)> "gdpr".titleize
=> "GDPR"
```
- Closes #
1. Start up the app, and navigate to the [GDPR Delete Requests page](http://localhost:3000/admin/users/gdpr_delete_requests). Click around and make sure that everything still …

Add a GDPR inflection

---

spec/system/dashboards/user_visits_dashboard_spec.rb

While working on [this bug](https://github.com/forem/forem/pull/17513), I realized that the specs for Dashboard were quite sparse. So I decided to beef them up a little.
None; specs should pass
None

Improve Dashboard specs coverage

---

app/views/admin/invitations/index.html.erb
cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js

We already replaced the search by email functionality in https://github.com/forem/forem/pull/17511, so this PR just updates the invitations index aria-labels to reflect the same
- Closes https://github.com/forem/forem/issues/17455
The Cypress tests should cover this, but if you'd like to check locally you can:
- Log in as an admin
- Visit `/admin/invitations`
- Invite a user using the 'invite member' feature
- return to the index view and try searching by a portion of the email address of the invitee
- check they appear in the list
N/A

Update invitations search aria-label

---

app/views/admin/gdpr_delete_requests/index.html.erb
cypress/integration/seededFlows/adminFlows/users/gdprDeleteRequests.spec.js

This PR adds an "empty state" to the GDPR delete requests table, which shows when there are no GDPR delete requests pending.
- Closes #17469 
To QA this PR, navigate to `/admin/member_manager/gdpr_delete_requests` and ensure that when there are no GDPR delete requests, that you are shown the "empty state":
N/A
issue template so …

"Empty State" for GDPR Delete Requests

---

app/views/admin/spaces/index.html.erb

This documentation does not yet exist, so we're removing a broken link.
Closes forem/forem#17593
None.
None.

Removing link to learn more about spaces

---

app/views/api/v0/articles/index.json.jbuilder
app/views/api/v0/articles/show.json.jbuilder

Replace forem/forem instead of thepracticaldev/dev.to (*.jbuilder)

---

app/queries/comments/community_wellness_query.rb
app/services/badges/award_community_wellness.rb
spec/queries/comments/community_wellness_query_spec.rb
spec/services/badges/award_community_wellness_spec.rb

Removes the Community Wellness badge feature flag and includes logic to rollout the badge award over time (instead of allowing users with existing long streaks to _"win them all at once"_)
- Closes #17310
The service has been running in production for a few days now. The only difference is the awarding process of the badge.
[Instructions to QA this PR locally](https://github.com/forem/forem/pull/17394#issue-1211273307)
None
Add the actual badges in the `/admin` dashboard ([see docs here](https://admin.forem.com/docs/forem-basics/badges#how-do-i-set-up-an-automatically-awarded-badge))

Remove Community Wellness badge feature flag

---

Gemfile
config/initializers/datadog.rb

Our recent ddtrace update and revert has led me to check out ddtrace's documentation. These are some of the improvement I think we can. If it doesn't go the way we expect it to we can revert it.
Resources
https://github.com/DataDog/dd-trace-rb/blob/master/docs/AutoInstrumentation.md
https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/auto_instrument.rb
https://github.com/forem/forem/pull/12908
https://github.com/forem/forem/pull/12941
n/a
n/a
n/a
track datadog.

[Datadog] Simplify ddtrace configuration

---

config/initializers/datadog.rb

Oops shouldn't have removed this line.
n/a

Update datadog.rb to include env scope

---

app/javascript/articles/components/SaveButton.jsx

As suggested in #17601 I'm separating the classes that were migrated to functional components into different PRs.

[save-btn] Refactor class components to be functional component

---

app/javascript/packs/admin/users/controls.js
app/javascript/packs/admin/users/filtersModal.js
app/views/admin/users/index/_filters_modal.html.erb
cypress/integration/seededFlows/adminFlows/users/filterUserIndex.spec.js

We only want one set of filters to be expanded at any given time; this PR adds some JS to collapse any previously opened section when a new is toggled.
- Closes https://github.com/forem/forem/issues/17636
- make sure you have the `member_index_view` feature flag enabled
- visit `/admin/member_manager/users`
- Click the filter icon button at the top right
- Inside the modal try clicking different sections and make sure when you click a new one, the previous one collapses
https://user-images.githubusercontent.com/20773163/169847951-6531811d-888f-4757-8248-00d9554d5e0d.mp4
None …

Member index view - collapse other filter sections when one is clicked

---

app/assets/stylesheets/ltags/StackexchangeTag.scss
app/views/liquids/_stackexchange.html.erb

Update stack-overflow/exchange liquid tag embedded styles to better match existing liquid tags and fix some accessibility  issues.
- Closes #
Improved color contrast on bottom button.
appropriately. …

Fix Stackoverflow liquid embedded styles

---

app/javascript/listings/__tests__/Categories.test.jsx
app/javascript/listings/components/Categories.jsx

As suggested in #17601 I'm separating the classes that were migrated to functional components into different PRs.

[categories] Refactor class components to be functional component 

---

app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
app/javascript/modCenter/singleArticle/index.jsx

As suggested in #17601 I'm separating the classes that were migrated to functional components into different PRs.

[single-article] Refactor class components to be functional component

---

.github/workflows/issue.yml

This PR ensures that the Contributing Guide link within the `github-actions` bot message points to a working Contributing Guide link.
- Closes #17762 
All checks should pass. ♻️ Additionally, ensure that the new Contributing Guide link points to the Contributing Guide as expected.
N/A …

Update github-actions Bot Contributing Guide Link

---

config/feed-variants/20220525-variant.json
config/field_test.yml

New feed variant as per Jennie.
n/a
n/a

Implement feed variant 20220525

---

app/assets/stylesheets/components/forms.scss
app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.test.jsx

This PR enhances the BETA DateRangePicker component so that when used on smaller screens it presents itself in a vertical layout to better enable scrolling/picking dates.
- Related Issue https://github.com/forem/forem/issues/17493
- Locally run `yarn install && yarn storybook` and visit the DateRangePicker story
- In your dev tools try experimenting with different screen sizes and using the date picker
Horizontal:
Vertical:
N/A
[Changes …

DateRangePicker: layout tweaks for mobile

---

app/javascript/utilities/runtime.js

Fixed typo.
```
succesful -> successful
```
appropriately.
shared_

Fix typo in runtime.js

---

README.md

- Following on-boarding process
Readme contains `jaw6` , links to `dev.to`
Not that I can detect.
appropriately.

Add jaw6 to core team

---

db/migrate/20220531183553_add_name_to_users_gdpr_delete_requests.rb
db/schema.rb

This PR adds a `name` column to the `users_gdpr_delete_requests` table as a first step to be able to add a user's name to the GDPR Delete Requests view.
- Related Issue #17340 
To QA this PR, run `rails db:migrate` and ensure that the column migrates as expected.
There shouldn't be! …

Part 1: Add "Name" Column to GDPR Delete Requests Table

---

app/assets/stylesheets/components/banners.scss
app/assets/stylesheets/config/_colors.css
app/assets/stylesheets/config/_generator.scss
app/views/layouts/application.html.erb

One of our clients needs a specific banner so we took this opportunity to create a unified template for other clients too. This PR puts some foundations to how it's gonna look like but it does NOT affect any visuals currently. It's basically bunch of CSS that needs to be ready for whenever someone creates a specific campaign banner.
Basically just look at the code as there's no real visual change right here.

Banner template

---

.travis.yml

This CVE was resolved and no longer needed to be ignored.
n/a
n/a
n/a

[Travis] Remove ignore CVE-2022-27311

---

app/javascript/listings/__tests__/ListingDashboard.test.jsx
app/javascript/listings/dashboard/listingRow.jsx
app/javascript/listings/listingDashboard.jsx

Refactors ListingDashboard comp to be a pure comp instead of a class and improves tests structure.

[listing-dashboard] Refactor class components to be functional component

---

app/services/articles/feeds/variant_query.rb

Prior to this commit, we were always using a new random number for a
query.  With this commit we cache the randomized seed; which allows us
to have "a repeatable random" experience within a window of time.
**NOTE:** If we find the cache to not be performant, we can enable the `:halt_caching_for_feeds_random_seed` FeatureFlag.
Closes forem/forem#17826
None.
None.

Adding caching to our feed's random seed

---

.vscode/extensions.json

The VS Code plungins for JavaScript in Chrome and Edge are departed and/or removed now that VS Code has this functionality built in. This PR removes the recommendation of these plugins from the suggested extensions list in the VS Code workspace config.
Alert fixed by this PR:
appropriately. …

Stop recommending deprecated plugins

---

app/javascript/.storybook/main.js
package.json
yarn.lock

We're not using this addon in storybook at the moment, so let's remove it and we can reintroduce if we have the need again
N/A
Running `yarn install && yarn storybook` locally should all work and look the same
N/A
appropriately.
[`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG …

✂️ remove storybook addon-links ✂️

---

app/views/stories/tagged_articles/_meta.html.erb

Every tag has a pretty name, but for the title on the tag, the page used a tag name instead of the pretty name. So Google uses this not pretty tag name. The expected behavior is to use for <title/> pretty name (when it exists) instead of the tag name.
- Related Issue #17851
- Closes #
When tag pretty name exists:
When tag pretty name does not exist:
issue …

feat: tagged articles page title can render tag pretty name

---

app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/javascript/CommentSubscription/CommentSubscription.jsx
app/javascript/packs/articlePage.jsx
app/views/comments/_comment.html.erb
app/views/comments/_comment_footer.html.erb
app/views/comments/_comment_header.html.erb
app/views/comments/_form.html.erb

Inspired by a request from @amywtlin in Slack (https://forem-team.slack.com/archives/C7GE84DEJ/p1654745579543829), this PR adds Ahoy tracking for two events on the articles page:
- when the user clicks anywhere in the `#comments` selector
- when the `#comments` selector becomes visible either through scrolling, or its initial display on a page
Example of recorded stats in database:
will …

Track clicks and views in comments on article page

---

cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js

This PR refactors `userIndexView.spec.js` by pulling the clicking and performing of user actions into a helper method called `openUserActionsDropdown();` and by pulling a heavily used click helper function out into the top of the test file.
- Related PR #17879 
Since this is merely an e2e refactor, ensuring that all of the checks pass should be sufficient. ♻️ 
None.
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&t …

Refactor userIndexView.spec.js

---

app/controllers/social_previews_controller.rb
config/initializers/new_framework_defaults_7_0.rb

Details below
https://github.com/forem/forem-internal-eng/issues/468
n/a

Enable Rails framework 7.0's isolation_level, partial_inserts, & raise_on_open_redirects

---

app/views/users/show.html.erb

Yikes, I made a typo. I missed a `/` 
N/A
N/A
N/A
N/A

Fix typo related to recent PR

---

config/initializers/new_framework_defaults_7_0.rb

Detail below.
https://github.com/forem/forem-internal-eng/issues/468
Everything should work as expected
n/a

Enable Rails 7 framework's default_headers

---

app/views/moderations/actions_panel.html.erb
app/views/moderations/modals/_unpublish_all_posts.html.erb
config/locales/views/comments/fr.yml
config/locales/views/moderations/en.yml
config/locales/views/moderations/fr.yml

- Adds i18n for a handful of newly found strings
- Fixes an out-of-date `fr` entry
- Related Issue #14888, #17867, #17923
- Closes #
appropriately.
replace this line with details …

Supplement some new i18n keys

---

app/models/article.rb
app/models/articles/feeds.rb
app/services/articles/feeds/variant_query.rb
db/schema.rb
lib/data_update_scripts/20220105112823_migrate_logo_svg_data.rb
spec/lib/app_secrets_spec.rb
spec/mailers/devise_mailer_spec.rb
spec/models/article_spec.rb
spec/support/seeds/seeds_e2e.rb
spec/system/admin/admin_invites_user_spec.rb
spec/system/authentication/conditional_registration_spec.rb

Fixed most rubocop issues
[ ] I need help with writing tests
appropriately.

Fixed most rubocop issues

---

config/initializers/datadog.rb

Rename two rails APMs so they are given the proper scope.
https://github.com/forem/forem-internal-eng/issues/356
n/a

Add DD service name for active_support and active_record

---

app/javascript/crayons/formElements/DateRangePicker/__tests__/DateRangePicker.test.jsx

This spec has been flaking in CI a bit too much recently. It's on my todo list to fix, but for now let's skip it so it doesn't keep blocking deploys.
The DateRangePicker is not live anywhere in the app at the moment, so I don't think skipping this is a big concern.
N/A
N/A
N/A
issue template so Community Success can help update the …

Skip flaky date range picker spec

---

config/application.rb

Remove yaml_column_permitted_classes

---

.rubocop.yml

Disables `Style/TopLevelMethodDefinition` rule until a new version (> 1.31.2) is shipped with a fix for some false positives that are coming up.
N/A
N/A
N/A

Temporarily disable Style/TopLevelMethodDefinition

---

app/assets/stylesheets/views/notifications.scss

When I added the markdown toolbar to the comment text areas, I added it _everywhere_ we use comment text areas. On the notifications page some style issues slipped through and the toolbar was overflowing its container.
However, the notifications page has a reduced/simplified version of the comment area, e.g. it doesn't have the functionality to add templates, which we are surfacing in the toolbar. If we want to add the toolbar to the notifications comment text area, we'll need to have a discussion about whether we also add template functionality / whether we also simplify the toolbar options etc. So for a "quick fix" I'm hiding it on this page, and I'll speak to product/design team about whether we want to re-introduce.
- Closes https://github.com/forem/forem/issues/18103
- Make sure you …

Don't show toolbar on notification comments

---

app/controllers/api/v1/users_controller.rb
app/controllers/concerns/api/users_controller.rb
app/views/api/v1/users/unpublish.json.jbuilder
config/routes.rb
spec/requests/api/v1/users_spec.rb

New API endpoint that allows admins to unpublish all comments+articles from a user
- Closes #17658
1. Enable :api_v1 Feature Flag
1. Create an API Key in /settings/extensions
1. Send in a PUT request to /api/users/:id/unpublish with the API Key and application/vnd.forem.api-v1+json in the Accept header
N/A

Unpublish comments+articles by user id in API v1

---

app/helpers/social_image_helper.rb
app/views/comments/index.html.erb
app/views/listings/index.html.erb
app/views/pages/show.html.erb
app/views/podcast_episodes/show.html.erb
app/views/stories/tagged_articles/_meta.html.erb
app/views/users/_meta.html.erb
spec/helpers/social_image_helper_spec.rb

Caching social media images is causing headaches, we want to reduce complexity and *only* construct social media images on `articles#show`. 
- Related Issue [#](https://github.com/forem/forem-internal-eng/issues/485)
[Changes …

Remove generated social images, except for articles#show

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
app/javascript/shared/components/useKeyboardShortcuts.js

The comment text area was still relying on older keyboard shortcut code that we don't need any more, since the markdown toolbar handles it. This PR strips out the old code and makes some minor tweaks to the markdown toolbar shortcuts so that they handle the "replace" behaviour of comment text fields.
- Related Issue https://github.com/forem/forem/issues/16781
- Visit the comments section on a post and try using keyboard shortcuts for bold, italic, underline, etc
- Try the same in a comment reply
https://user-images.githubusercontent.com/20773163/178971206-95ea704b-1761-4ea0-ab65-ecaf1e9d4045.mp4
N/A …

Clean up keyboard shortcuts in comment text area

---

spec/queries/admin/users_query_spec.rb

I saw the spec for "when search is set" flake in CI, because the fake name generated for this test user just so happened to also match the search term "greg". To prevent this from happening in future, I'm giving them an explicit name so we can predict exactly who should appear in search results.
N/A
Tests should pass
N/A
issue template …

Fix flaky UsersQuery spec

---

app/assets/stylesheets/views/article.scss

Ensure header images don't overflow article links
closes #18170 
**Before:**
**After:**
N/A
N/A

Add radius to top of article images

---

app/javascript/packs/CommentTextArea/CommentTextArea.jsx

Users when drafting/editing a comment can paste an image
- Related Issue #17881
- Closes #17881 …

Add copy/paste images in comment editor

---

app/controllers/articles_controller.rb
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/components/EditorActions.jsx
app/javascript/article-form/components/Options.jsx
spec/requests/articles/articles_create_spec.rb
spec/requests/articles/articles_update_spec.rb

Replace the datetimepicker in the post options with separate date and time pickers to solve problems described in #18075
- Closes #18075 
- enable the feature flag: `FeatureFlag.enable(:schedule_articles)`
- create a scheduled article (select date and time in the post options), `published_at` should be saved
If you choose only date, `published_at` should be saved with the time `00:00`. Choosing only time won't take effect.
- edit an existing scheduled article, it should be possible to set a different `published_at`
It would be nice to add at least basic front-end tests. I tried adding a spec to `publishingFlows/postOptions.spec.js`.
To enable a feature flag I added `cy.enableFeatureFlag('schedule_articles');` to `beforeEach()` after the `cy.testSetup();` but it took no effect.
_Will this …

Modify datetime picker for scheduling articles

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb

Um..oops! My script for loading the Google Analytics 4 tag has an `http` scheme hard coded, but the actual scheme will probably be `https` in production. Indeed, it is on Dev.to, and the browser fails to load an insecure script:
Safari: 
Chrome:
This PR removes the scheme form the loading script URL, which causes the browser to default to the current page's scheme
Bug fix for https://github.com/forem/forem/pull/18124
Set your local environment to serve over https, then verify scripts are loading
updated. …

Don't specify scheme when loading GA4 script

---

app/assets/stylesheets/components/multi-input.scss
app/javascript/crayons/MultiInput/MultiInput.jsx
app/javascript/crayons/MultiInput/__stories__/MultiInput.stories.jsx
app/javascript/shared/components/defaultSelectionTemplate.jsx

As part of the efforts to wrap up the Multi Input Crayons component, I've implemented validation on the component. See demo below.
When the input value is invalid the button add a red background and look visually different as per figma . This behaves very similarly to the Google mail address validation.
Added some comments to the PR to expand more. Note: the error message below the field is not implemented.
- Related Issue #https://github.com/forem/forem/issues/17577
Add valid and invalid email addresses. the invalid email address background color will turn red.
https://www.loom.com/share/0cecfda67f2746948cc5d52cbef92aa1
I wanted to do a demo the Accessibility portion as well above, but for some reason when I activated loom to screenshare it wasn't reading out my `aria-assertive`  block. …

Implementing validation for the Multi Input Crayons Component

---

app/javascript/article-form/components/EditorBody.jsx

During a previous refactor, I accidentally impacted the "stickiness" of the editor toolbar, and for long posts it was no longer always visible at the top of the viewport. This PR corrects that.
- Closes https://github.com/forem/forem/issues/18205
- Grab some long text from a current post or lorem ipsum generator
- Create a new post, pasting in the content
- Check that the toolbar remains visible in the viewport as you scroll your post
- Check you can scroll all of your post OK
https://user-images.githubusercontent.com/20773163/180780980-b906027e-daf6-422e-8f66-85fddd433fb3.mp4
N/A …

Minor style fix to editor toolbar

---

app/assets/stylesheets/widgets.scss
app/models/display_ad.rb
app/services/markdown_processor.rb
app/views/articles/show.html.erb

The bulk of our traffic enters via post pages. Our "display ads" don't currently display on these pages. 
- Related Issue # https://github.com/forem/forem-internal-eng/issues/486
I made a simple tweak to the class/CSS, but there's still some baked-in assumptions about image size and scale that I seem to be fighting against. I'm possibly missing something obvious, but the way that DisplayAds work (they are _just_ rendered markdown) I think it's going to be challenging to get the side-by-side layout from the Figma sketch to work well. 
I don't think we've flagged any accessibility issues, yet?
will share this change with the people who …

DisplayAd in post comments area

---

app/validators/profile_validator.rb
spec/models/profile_spec.rb

On html form submission, the line breaks in `<textarea>` are encoded as CRLF when sending to server. So when typing summary for ex.
```
a
b
```
the character counter for summary will show 3/200 but when validating in backend, `record.summary.size` would be 4.
This PR contains change for replacing CRLF with LF before validating summary.
- Related Issue #17644
- Closes #17644
In `Bio` field of profile settings, type multiline string of 200 characters and save it. It should save and not show `summary is too long` 
No …

Convert CRLF to LF when validating summary

---

app/controllers/admin/welcome_controller.rb

Choose the correct articles to be displayed on admin page
n/a

Update WelcomeController's daily_threads query

---

app/javascript/crayons/MultiInput/__stories__/MultiInput.mdx

Update the Multi Input documentation.
- Related Issue #https://github.com/forem/forem/issues/17577
None really. Open Storybook http://localhost:6006/?path=/docs/beta-multiinput--default and read through the docs tab if need be.
[Changes …

Multi Input Crayons Component Documentation (Storybook)

---

config/feed-variants/20220726-variant-a.json
config/feed-variants/20220726-variant-b.json
config/field_test.yml

Adjusts public reaction scores for this week's experiment
Comparison:
Closes forem/forem#181225
Related to forem/forem-internal-eng#453
All variants are exercised in Rspec.
None.

Feed experiment for 2022-07-26

---

app/models/page.rb
app/views/pages/show.html.erb
cypress/e2e/seededFlows/adminFlows/pages/createPage.spec.js
db/seeds.rb

This PR adds a new template for pages added by admins in `/admin/customization/pages`, named `nav_bar_included`. The style of the new template replicates the existing "contained" layout, except it also includes the left-hand nav bar (or hamburger menu navigation when in mobile-size viewport).
- Closes https://github.com/forem/forem/issues/17701
- Visit `/admin/customization/pages` as an admin
- Create a new page, selecting the `nav_bar_included` template
- Save the new page, and then click the link in the index view to visit it
- Check the nav bar is shown and the entered markdown occupies the rest of the space
- Experiment with viewport size / browsers to check for issues
- Check existing templates are unaffected
N/A …

Add a new template to custom pages

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/CommentsCount.jsx
app/javascript/packs/articlePage.jsx
app/views/articles/_single_story.html.erb
config/locales/views/articles/en.yml
config/locales/views/articles/fr.yml
cypress/e2e/seededFlows/homeFeedFlows/feedNavigation.spec.js

On the feed-page, when the user clicks on the add comment, it redirects users to the post-page comment area.
- Related Issue #17883
- Closes #17883 …

Focus comment box when entering by "comments" button from home feed

---

app/models/reaction.rb
app/services/spam/handler.rb
spec/models/reaction_spec.rb
spec/services/spam/handler_spec.rb

This is a draft highlighting a proof of concept to allow for each Forem
to add tighter enforcement of spam.
Related to forem/forem-internal-eng#453
None.
None.

Adding configurations to tighten spam handling

---

README.md

Removing jeremyf and asheren from Core contributors

---

app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/assets/stylesheets/views/article.scss
app/views/articles/_reaction_button.html.erb
app/views/comments/_comment_footer.html.erb
app/views/notifications/_aggregated_reactions.html.erb
app/views/notifications/shared/_comment_box.html.erb
config/locales/views/comments/en.yml
config/locales/views/comments/fr.yml
config/locales/views/reactions/en.yml
cypress/e2e/seededFlows/articleFlows/commentOnArticle.spec.js

All texts of like reactions were changed to 'Like' instead of 'Heart' as well as the style used to display these tooltips.
- Related Issue #17967
- Closes #17967 …

Change all tooltip texts on heart/like reactions to like

---

app/views/api/v0/shared/_follows.json.jbuilder
app/views/api/v0/shared/_user.json.jbuilder
app/views/api/v1/followers/users.json.jbuilder
app/views/api/v1/listings/show.json.jbuilder
app/views/api/v1/organizations/listings.json.jbuilder
app/views/api/v1/organizations/users.json.jbuilder
app/views/api/v1/readinglist/index.json.jbuilder
app/views/api/v1/shared/_follows.json.jbuilder
app/views/api/v1/shared/_user.json.jbuilder
app/views/api/v1/users/show.json.jbuilder

Adds `user_id` to a few API endpoints to optimize the usage from the consumer standpoint. This will avoid the need to make follow up requests to validate user by username.
- Closes #18165
Make GET requests to `/api/followers/users` and `/api/comments?a_id=<article_id>` and ensure the results include `user_id` value in the response
N/A

Include user_id fields in a couple API endpoint responses

---

.codeclimate.yml

See also https://github.com/codeclimate/codeclimate/pull/1040#issuecomment-1135080381
Preliminarily tested in https://github.com/tnir/forem/pull/79
- https://github.com/codeclimate/codeclimate/pull/1040#issuecomment-1135080381
- Related Issue #15614
n/a
No.
- [n/a] I've updated the [Developer Docs](https://developers.forem.com) or
- [n/a] This PR changes the Forem platform and our documentation needs to be
[Changes Requested](https://github.com/forem/admin-docs/issues/new?ass …

Enable ESLint 8 on CodeClimate

---

app/controllers/reactions_controller.rb
app/helpers/admin/users_helper.rb
app/models/role.rb
app/models/tag_adjustment.rb
app/models/user.rb
app/policies/application_policy.rb
app/policies/article_policy.rb
app/policies/authorizer.rb
app/policies/comment_policy.rb
app/policies/response_template_policy.rb
app/policies/user_policy.rb
app/services/moderator/manage_activity_and_roles.rb
lib/data_update_scripts/20220802100730_rename_moderator_to_super_moderator.rb
spec/factories/users.rb
spec/helpers/admin/users_helper_spec.rb
spec/lib/data_update_scripts/rename_moderator_to_super_moderator_spec.rb
spec/models/role_spec.rb
spec/policies/article_policy_spec.rb
spec/policies/authorizer_spec.rb
spec/policies/user_policy_spec.rb
spec/requests/api/v1/articles_spec.rb
spec/services/moderator/manage_activity_and_roles_spec.rb
spec/support/seeds/seeds_e2e.rb

We would like to rename the role formerly known as "moderator" to "super_moderator".
- Related Issue https://github.com/forem/forem/issues/18231#
No particular UI/accessibility concerns that I can see.
appropriately.
or in …

Try renaming moderator -> super_moderator

---

README.md

It's that time!
N/A
N/A
N/A
appropriately.
shared_

remove myself from core team

---

app/javascript/packs/CommentTextArea/CommentTextArea.jsx

Adds drag/drop image uploading function to comment editor.
As a commenter, when drafting/editing a comment, I can drag & drop an image into a comment I am editing (i.e. where the cursor is focused). The dropped image should be uploaded and inserted for me into the comment without me having to manually format further.
- Related Issue #17882
- Closes #17882
- Visit any post and under comment section simply drag-and-drop image to see that it uploads correctly.
https://user-images.githubusercontent.com/9396084/183449789-3f9014c9-fefe-44b2-84a1-a9c70873d512.mov
No
issue template so …

Adds drag/drop image uploading function to comment editor

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/helpers/comments_helper.rb
app/views/comments/_comment_footer.html.erb
config/locales/helpers/en.yml
config/locales/helpers/fr.yml
cypress/e2e/seededFlows/articleFlows/commentOnArticle.spec.js

This PR is the first step towards https://github.com/forem/forem/issues/18126, removing the "Like" text that appears next to comments with 0 likes.
- Related Issue https://github.com/forem/forem/issues/18126
Before you test this locally, it might be helpful to enable caching in development by running `bundle exec rails dev:cache` (see detail in https://github.com/forem/forem/issues/18312, but essentially it can be quite hard to trigger the '0 likes' state otherwise).
- Visit a post, and add a new comment
- Check it appears with just a heart icon, and no "Like" text
- Refresh the page, and you should see the comment has had an automatic like applied to it from you, the author
- Click the button to remove your like
- Check the "Like" text doesn't appear
No, these buttons use an …

Hide like text if no likes on comment

---

app/assets/javascripts/initializers/initializePodcastPlayback.js

- Closes #
1. Checkout the code of this PR https://github.com/forem/ForemWebView-android/pull/56 locally.
2. Checkout in this current branch `rt4914/add-forem-mobile-podcast-options` (basically this PR) locally.
3. Using ngrok fetch the https URL for the local environment
4. Update the url in `env` file.
5. Now set this URL in android code https://github.com/forem/ForemWebView-android/blob/e29fd4f61fbdc8eeb9699a3342f29f9b13e95f4e/app/src/main/java/com/foremlibrary/app/MainActivity.kt#L35
6. Run the android app and play any podcast.
7. From podcast notification, pause the podcast and notice that this change is reflected in Android app too.
(For simplicity you can check the below output.)
https://user-images.githubusercontent.com/9396084/184368290-38ba78db-f11f-43e5-b2c4-5b …

Added more cases to handlePodcastMessages for Android/iOS Podcast Player

---

app/javascript/listings/__tests__/ListingDashboard.test.jsx
app/javascript/shared/components/__tests__/dateTime.test.jsx

A couple tests seem to have locale settings that changes the output of date localization. This PR updates a couple of checks against these strings to ensure a change in separator (`,` vs ` at`) won't break the tests.
N/A
You can also run the jest test locally to ensure it works on your local environment
N/A

Fix jest datetime tests with regex

---

app/models/articles/feeds.rb

Adds a feed relevancy lever named `comments_score` that ranks articles based on the sum of their comment scores
Closes https://github.com/forem/forem/issues/18270
appropriately. …

Added relevancy lever based on comments scores of an article

---

app/assets/javascripts/initializers/initializeReadingListIcons.js
app/assets/javascripts/utilities/buildArticleHTML.js
app/assets/stylesheets/components/stories.scss
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/ReadingTime.jsx
app/javascript/articles/components/SaveButton.jsx
app/javascript/articles/components/__tests__/SaveButton.test.jsx
app/views/articles/_single_story.html.erb

Change article story save button to bookmark icon.
- Related Issue #17880 
- Closes #17880 
appropriately.
replace this line with details on why this change …

Replace article's save button with bookmark

---

app/assets/stylesheets/components/hamburger.scss

Originally this issue was filed at forem/ForemWebView-android library but was transferred to forem/forem because it needs to be fixed in web codebase.
In low end android devices the sidebar scrolling does not work at all. This PR fixes that bug.
- Related Issue #18356
- Closes #18356
**Device/Emulator**
- Android 5.4 FWVGA
- API30
**Steps to Reproduce**
- Checkout into this branch and create a ngrok url.
- Open the ngrok url in your android emulator ( 5.4 FWVGA)
- Open navigation drawer and try to scroll to the bottom options.
- Scrolling does not work
**Before this PR**
[device-2022-08-19-161521.webm](https://user-images.githubusercontent.com/9396084/185604724-14ca1ee1-d8c6-4cf6-9749-a7ee5c5b954e.webm)
**After this PR**
[device-2022-08-19-161351.webm](https://user-images.githubusercontent …

Fix #18356: Sidebar scrolling bug fixed for low end android devices

---

app/controllers/reactions_controller.rb
app/services/reaction_toggle.rb
spec/requests/reactions_spec.rb

Preparing for future Reactions API work, we are extracting the create action out of `reactions#create` into a service, hoping we can re-use it for the API.
`pair` @Ridhwana 
- Related Issue #18263 
[x] We have checked that tests pass.
[x] We will confirm that the UI still works
appropriately.

Extract reaction create from controller to service

---

config/feed-variants/20220823-variant.json
config/field_test.yml

<!--
For Work In Progress Pull Requests, please use the Draft PR feature,
Feed experiment for 08-23-2022 as outlined in the [feed experiments docs](https://docs.google.com/document/d/1H1WsktwvlspsB_1RmsZxfVcJHVcaeorHLjpAWG8Oazw/edit?usp=sharing). Notably this experiment takes the incumbent from 07-26-2022, and swaps it's `public_reactions` lever for the the `public_reactions_scores` lever. Weight is 80% incumbent, 20% new challenger.
[Changes …

Feed experiment for 08-23-2022

---

app/views/shared/_logo_design.html.erb
app/views/users/_profile.html.erb
config/locales/views/misc/en.yml
config/locales/views/misc/fr.yml
cypress/e2e/seededFlows/settingsFlows/updateProfileSettings.spec.js

This PR removes `Brand Color 2` as well renames `Brand Color 1` to `Brand Color`.
**NOTE**: This change has been done only for profile and not for organization.
- Related Issue #17686 
- Closes 
https://user-images.githubusercontent.com/9396084/183352871-0449a903-49f9-4228-8b10-c8da17d47730.mov
None
appropriately.
No

Removed unused brand color field from Profile

---

app/controllers/concerns/api/articles_controller.rb
app/controllers/concerns/api/listings_controller.rb
app/controllers/concerns/api/organizations_controller.rb
app/controllers/concerns/api/podcast_episodes_controller.rb
app/controllers/concerns/api/tags_controller.rb
app/controllers/concerns/api/videos_controller.rb
app/services/article_api_index_service.rb
swagger/v1/api_v1.json

This adds support for using `ApplicationConfig["API_PER_PAGE_MAX"]` within the API. When set to an integer value in `rails.env`, API calls will be limited to a `per_page` value no greater than `API_PER_PAGE_MAX`.
For example, if this is set in `rails.env`:
```
API_PER_PAGE_MAX=10
```
...the following request will be limited to 10 results per-page:
```
/api/articles?per_page=999
```
If `API_PER_PAGE_MAX` is unset, the per-page max functions as it does already: generally limited to 1000, with a few exceptions.
https://github.com/forem/infra/issues/509

Utilize `ApplicationConfig["API_PER_PAGE_MAX"]`

---

app/assets/javascripts/base.js.erb

It looks like this issue is caused by [postscribe](https://github.com/forem/forem/blob/def5de6d28b0621d51b669fd71425254aa5ab29f/app/javascript/utilities/gist.js#L34) conflicting with [InstantClick's script re-evaluation](https://github.com/forem/forem/blob/eae8557cf10e8e8911428b4f7e0aa8036735a94c/app/assets/javascripts/base.js.erb#L421-L444).  This explains why it doesn't happen on a refresh or initial load, but only when clicked from the home page or the author's page.
Since postscribe overrides `document.write`, when InstantClick re-evaluates the gist scripts, it triggers the postscribe callbacks.  (gist scripts make calls to `document.write`).
- Closes #14428
1. Create an article with multiple different embedded gists and publish it.  I had the best luck with 5 or more gists.
2. Click …

Excluded gists from InstantClick

---

swagger/v1/api_v1.json

This removes manual changes to a file that should instead be automatically generated, as part of [our documentation update process](https://developers.forem.com/contributing-guide/api#updating-api-docs).
https://github.com/forem/forem/pull/18394/files#diff-78f1827fd44185fa47cc2b74d9e126bd4b1d47a0f755d4a3e8c855bbce0fb102

Revert manual changes made to `/swagger/v1/api_v1.json`, an autogenerated file

---

app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/Navigation.jsx
app/javascript/onboarding/components/ProfileForm.jsx

Looking into #14483 I noticed some errors in the console related to a mismatch in `propTypes` of the Onboarding components.
I don't think this is the root cause of the issue, but I've been having a hard time reproducing the problem locally and this seems like a good small fix that (with some luck) could fix the issue (in case the problem is caused by JS execution halted due to the console error)
- Related to #14483
1. Register a new user in local environment
2. Walk through the onboarding flow and notice some of these errors no longer appear in the console
3. Delete user via `/admin/member_manager/users`
4. Repeat step 1-4 a few times to see if you're able to reproduce the issue
None
N/A

Fix most propTypes errors in Onboarding components

---

app/views/moderations/index.html.erb

This PR simply removes the banner visible to mods.
- Related Issue #18381
- Closes #18381
No
appropriately. …

Remove mod banner

---

app/views/users/_badges_area.html.erb

There was a lonely div in the badge section that was causing the profile page to break. 
- Related Issue #https://github.com/forem/forem/issues/18442
- Closes #https://github.com/forem/forem/issues/18442
- Go to any users profile and make sure that the page renders correctly like below: 
-  …

Fix the profile page of other users

---

app/assets/stylesheets/views/comments.scss
app/controllers/stories_controller.rb
app/javascript/packs/commentDropdowns.js
app/javascript/utilities/dropdownUtils.js
app/models/comment.rb
app/views/articles/_full_comment_area.html.erb
app/views/comments/_sort_option.html.erb
config/locales/views/articles/en.yml
config/locales/views/articles/fr.yml
cypress/e2e/seededFlows/articleFlows/commentOnArticle.spec.js
cypress/e2e/seededFlows/articleFlows/sortCommentsOnArticle.spec.js
cypress/e2e/seededFlows/publishingFlows/publishOrSavePost.spec.js
spec/models/comment_spec.rb
spec/views/articles_spec.rb

- [* ] Feature
Add the ability the sort comments of Articles View Page. This feature was already merged earlier , [here](https://github.com/forem/forem/pull/16686).  But after deployment issues were found and it was [reverted](https://github.com/forem/forem/pull/17093).  I've followed advice from Aitchiss I've resolved all issues described in this [comment](https://github.com/forem/forem/issues/16133#issuecomment-1205094470). 
- https://github.com/forem/forem/issues/16133
- Closes #
- https://github.com/forem/forem/issues/17084 
- https://github.com/forem/forem/issues/17082
- https://github.com/forem/forem/issues/17081
Any article page with comments should now show the ability sort comments in three ways 
- Top
- Latest 
- Oldest
Web View
Mobile View
- [*] Yes
_Will this …

Sort comments reopen

---

app/views/articles/_full_comment_area.html.erb
app/views/comments/_sort_option.html.erb

Minor sort comments feature tweaks:
- Added margin to SVG icon
- Switched up the anchor used in the link because `#comments` adds auto focus to the comment editor
- Closes #18449
**Before (dev.to):**
**After:** 
N/A

Minor sort comments tweaks

---

app/models/article.rb
spec/models/article_spec.rb

Fixes a bug that doesn't allow for series to be removed when empty
- Closes #18351
2. Create an article (Draft or non-draft shouldn't matter)
3. Assign a new series & save article (it must be the only article in the series)
4. Edit again and remove the series + save
5. Edit the article again and the series name should've been removed
- This can be seen in the dropdown (series name shouldn't be visible)
None

Article collection cleanup callback

---

app/models/badge.rb

badge path was mistakenly removed
n/a

Add back Badge#path

---

app/controllers/profiles_controller.rb
app/decorators/user_decorator.rb
app/models/users/setting.rb
app/services/users/update.rb
app/views/shared/_logo_design.html.erb
db/migrate/20220919222729_remove_brand_color2_from_settings.rb
db/schema.rb
spec/decorators/user_decorator_spec.rb
spec/services/users/update_spec.rb

Removes unused column in `users_settings` table
- Closes #18434
1. `bin/setup`
2. Boot app locally and browse around, including update of user settings
3. Things should continue to work as they do now
None

Remove brand_color2 from users_settings

---

README.md

Remove Josh from core team

---

app/assets/javascripts/initializePage.js
app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/assets/javascripts/initializers/initializeDisplayAdVisibility.js
app/models/display_ad_event.rb
app/models/user.rb
app/views/articles/show.html.erb
spec/models/user_spec.rb
spec/services/users/delete_spec.rb

- Related Issue #18380 
- Built on #18444 
- Related work in #18400 
* This builds on #18444, which hides ads for users who have opted-out of viewing sponsored content
* We'll now create a DisplayAd `impression` and/or `click` event for logged-out users
* We only count an `impression` if at least 25% of the ad is visible in the viewport (prior, we were calculating the width of the window, which worked for the sidebar DisplayAds, but does not work for under-comment DisplayAds).
* For now, we are counting each `impression` and/or `click` distinctly, a further PR will introduce `counts_for` and roll-up tasks for both this table and `page_views`
* Have an Article with a DisplayAd position: "Below the comment section"
* Scroll until the ad is at least partially visible on screen
* Observe that …

DisplayAdEvent tracking changes

---

app/javascript/packs/validateFileInputs.js

Error messages coming from image uploads in the comments section & Post editor should now appear as Snackbar items
- Closes #18368
When uploading a large image you can now see the error message pop up in the Snackbar
https://user-images.githubusercontent.com/6045239/192532667-339787ca-9648-4a9d-88be-8159559aa902.mov
https://user-images.githubusercontent.com/6045239/192532680-dd363790-5ec2-4cd8-a9c9-3ae3301fa0f0.mov
None because the Snackbar component has accessibility features built-in.

Snackbar error message in comments image upload

---

app/javascript/responseTemplates/responseTemplates.js

In comment templates if the template string contains `"` then everything after that is not visible in comment. This PR fixes that issue, which can be seen in below video recordings too.
- Related Issue #17972
- Closes #17972
https://user-images.githubusercontent.com/9396084/193844392-38a77c82-f031-4f9e-b093-c2f293dfe7cc.mov
https://user-images.githubusercontent.com/9396084/193844440-33334d6d-a459-4ad1-84bb-aa5cd0f9eaea.mov
No
[Changes …

Fixed quotations issue

---

app/controllers/admin/tools_controller.rb
app/models/articles/feeds/variant_assembler.rb
app/services/articles/feeds/variant_query.rb
app/views/admin/tools/feed_playground.html.erb
config/routes/admin.rb
spec/requests/admin/feed_playground_spec.rb

This PR adds a small tool to the "tools" area of admin, generally following existing patterns. It does not link to any dashboard as this is primarily only for Forem team members to discuss feed configs before submitting as experiments.
While this is for internal Forem use first and foremost, I think it's fine that it it is _technically_ accessible by any admin.
- Related Issue https://github.com/forem/forem/issues/18543
- Closes https://github.com/forem/forem/issues/18543
This is what the tool looks like.
Submitting a properly formed feed variant (which could be copied from `config/feed-variants/20220920-variant-c.json`) should display a feed, which can later be tweaked.
In local testing you may need to ensure _recent_ articles have been published to verify it works as expected.
have not …

Add internal tool to preview feed configs

---

app/services/audit/notification.rb
spec/requests/admin/users_spec.rb
spec/requests/api/v1/articles_spec.rb
spec/requests/api/v1/users_spec.rb
spec/services/moderator/unpublish_all_articles_spec.rb

After adding a few more `AuditLog` specs we realized there was an inconsistent use of `listen`/`forget` directives. This caused leftover listeners catching events and creating more records than expected, which broke the test suite. This PR addresses those missing places.
CI is ✅ 
None
Be mindful and monitor the deployment of this PR because of the backlog of PRs merged, which include a DB migration.

ActiveSupport::Notifications listen/forget fix

---

Gemfile

Added comment to the following gems:
* "flipper-ui"
* "omniauth-google-oauth2"
* "yard-activerecord"
* "yard-activesupport-concern"
None
- Closes #
None
None
No impact
No

Add comment to a few gems

---

app/javascript/.storybook/preview.js
app/javascript/crayons/guidelines/__stories__/Components.stories.mdx
app/javascript/crayons/guidelines/__stories__/Utility-first-css.stories.mdx
app/javascript/crayons/guidelines/__stories__/Writing-css.stories.mdx
app/javascript/crayons/guidelines/__stories__/introduction.stories.mdx
app/javascript/readingList/components/__stories__/MediaQuery.stories.mdx

This PR simply replaces `@storybook/addon-docs/blocks` with `@storybook/addon-docs` as per https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports
- Related Issue #17910
- Closes #
N/A
N/A
appropriately. …

Updated deprecated storybook code

---

app/services/articles/feeds/variant_query.rb
config/feed-variants/20221011-variant-a.json
config/feed-variants/20221011-variant-b.json
config/field_test.yml
spec/services/articles/feeds/variant_query_spec.rb

This PR includes new experiments outlined in the issue and related docs.
The intention is to split two _close_ winners from last time in to 30/25 instead of 55 to a single incumbent.
We are also introducing two new challengers, and one retry from August.
The PR also includes a bug fix which ensures we never have negative scores in the feed — which is currently possible for negative _user_ reactions. We now have this as a set rule governing all versions, and is tested.
Closes https://github.com/forem/forem/issues/18568 …

Feed experiment for 10-11-2022

---

app/controllers/admin/users_controller.rb
app/lib/constants/user_details.rb
app/queries/audit_log/unpublish_alls_query.rb
app/views/admin/users/show.html.erb
app/views/admin/users/show/_tabs.html.erb
app/views/admin/users/show/unpublish_logs/_index.html.erb
spec/queries/audit_log/unpublish_alls_query_spec.rb
spec/requests/admin/users_spec.rb

Display information about "unpublish all" actions (`audit_logs`) on the user's page in the member manager:
Admin can republish articles manually by clicking "edit" and updating the article.
- Related Issue https://github.com/forem/forem-internal-eng/issues/491
- Logging was done in #18535 #18545
- "unpublish all posts" for the user from moderator action panel or member manager (details in #18535 => QA instructions)
- make sure that the async workers have finshed their job
- in the member manager you should see "Unpublish alls" tab and information about unpublish articles and comments on this page
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=cha …

Display information about "unpublish all" actions in the member manager

---

app/lib/constants/settings/general.rb
app/models/settings/general.rb
app/views/admin/settings/forms/_ahoy.html.erb
app/views/admin/settings/show.html.erb
config/initializers/ahoy.rb
config/locales/lib/en.yml
config/locales/lib/fr.yml
cypress/e2e/seededFlows/adminFlows/config/ahoySection.spec.js

Allows for admins to opt-in Ahoy Tracking
- Closes https://github.com/forem/forem-internal-eng/issues/524
1. As an Admin visit `/admin/customization/config` and ensure Ahoy Tracking is disabled by default
2. Check in rails console the current amount of Ahoy events with `Ahoy::Event.count`
3. In an incognito window
- Open the main feed
- Click on any "Create Account" link
- Check `Ahoy::Event.count` and it should've increased (we currently track this action)
4. Go back to the settings and disable Ahoy tracking
5. Restart the local server & open an incognito window again
- Open the main feed
- Click on any "Create Account" link
- Check `Ahoy::Event.count` and it should remain the same (tracking was disabled)
6. You may want to enable tracking, restarting the server and trying again to …

Opt in settings for Ahoy Tracking

---

.travis.yml
spec/rails_helper.rb
spec/spec_helper.rb

Reintroducing code coverage to the Forem codebase.
More data refinement in upcoming PR.
n/a
n/a

Add Codecov

---

app/views/articles/_full_comment_area.html.erb
app/views/badges/_badge_detail.html.erb
app/views/moderations/modals/_unpublish_post_modal.html.erb
config/locales/views/articles/en.yml
config/locales/views/articles/fr.yml
config/locales/views/main/en.yml
config/locales/views/main/fr.yml
config/locales/views/misc/en.yml
config/locales/views/misc/fr.yml
config/locales/views/moderations/en.yml
config/locales/views/moderations/fr.yml
config/locales/views/reactions/fr.yml
config/locales/views/settings/fr.yml

Fixes for recently found i18n problems.
- `app/views/moderations/modals/_unpublish_post_modal.html.erb` has no i18n
- A couple of French ymls not synched with English
- Key movement following #16268
- Key adjusted for new badges page #18445
- i18n supplement to #18349
- Related Issue #14888
- Closes #
issue template so Community Success can help update the …

Fix recent missing or unsynchronized i18n

---

app/models/tag_adjustment.rb
app/views/moderations/actions_panel.html.erb
app/views/notifications/_tagadjustment.html.erb
config/locales/views/moderations/en.yml
config/locales/views/moderations/fr.yml
cypress/e2e/seededFlows/moderationFlows/adjustPostTags.spec.js
spec/requests/tag_adjustments_spec.rb
spec/services/tag_adjustment_creation_service_spec.rb
spec/services/tag_adjustment_update_service_spec.rb

- Closes #18492
You can adjust a tag and test this locally. You can do this as an admin or by adding the `moderator_role` feature flag and assigning `super_moderator` role to a user.
**Reason for adjustment is now optional**
**Reason for action in notification doesn't appear if the field is empty**
N/A

Make reason for adjustment optional in moderator tag adjustment

---

app/views/organizations/_sidebar.html.erb
config/locales/views/organizations/en.yml
config/locales/views/organizations/fr.yml
cypress/e2e/seededFlows/profileFlows/organisationStats.spec.js

Added a section to the org profile with the following info:
**X posts published**
**X members**
In practice the designs should also be similar to that of user-profile-page but we need exact designs for that and therefore #18616 has been filed.
- Related Issue #18607 #18616
- Closes #18607 …

Show org stats on organisation page

---

cypress/e2e/seededFlows/moderationFlows/adjustPostTags.spec.js

This is a test that seems to fail periodically. In #18606 the reason for adjustment was made optional but this test didn't fail at the time. It's hard to pinpoint exactly why it behaved this way, but there's a chance this is one of the reasons we've been seeing Cypress test hang and fail on and off (see #18577)
- #18606
- #18577
N/A

Remove old cypress test

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/listings.scss

The CSS uses `width: fit-content` in a few places but it was not supported by Firefox until version 94. To support older versions, the browser-vendored `-moz-fit-content` value must be used. https://caniuse.com/mdn-css_properties_width_fit-content
This PR adds the fallback in the 2 places the code uses `width: fit-content`.
- Closes https://github.com/forem/forem/issues/18428
It works fine in newer Firefox versions:
It works fine in older Firefox versions:
the `fit-content` value is in fact invalid in that old firefox version:
It works fine in other browsers like Opera/Chrome/Safari:
No impact on accessibility …

Use -moz-fit-content as a fallback for fit-content in old firefox

---

app/views/admin/display_ads/_form.html.erb
app/views/articles/show.html.erb
app/views/sidebars/_homepage_content.html.erb

This PR improves the consistency of text styles in display ads by adding the `text-styles` class
- Closes #18626
1. Create a display ad below the comment section with some text 
- Multi paragraph at least to check spacing between `<p>` elements
2. Create a comment with the same markdown to check them side by side (one on top of the other actually 😅)
**Before:**
**After:** 
N/A

Improve consistency in display ads text styles

---

.github/workflows/bundle-audit.yml

Remove cURL header from bundle-audit

---

.github/workflows/ci-cd.yml

Explicitly specify which branch to use.
n/a

Specify branch on CD

---

.github/workflows/ci-cd.yml

akhileshns/heroku-deploy isn't working properly. It is double deploying on commits.
n/a

Remove CD workflow

---

README.md

Removed a typo and added acknowledgements to table of contents.

Update Table of Contents.

---

config/field_test.yml

Small uncaught typo which effects a/b test reporting 😌
- Closes https://github.com/forem/forem/issues/18677

Small field test fix

---

db/migrate/20221031133328_add_index_to_display_ads_cached_tag_list.rb

Fix issue:
```
== Preparing database ==
== 20221031133328 AddIndexToDisplayAdsCachedTagList: migrating ================
-- add_index(:display_ads, :cached_tag_list, {:using=>:gin, :opclass=>:gin_trgm_ops, :algorithm=>:concurrently})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:
PG::DuplicateTable: ERROR:  relation "index_display_ads_on_cached_tag_list" already exists
```
- Closes #
[Forem Accessibility …

Add if_not_exists: true to migration

---

app/javascript/packs/searchParams.js
app/views/stories/articles_search/index.html.erb

Add card HTML for loading to list of search page during search.
https://user-images.githubusercontent.com/50684687/199502908-6fe61bf3-6362-4c5a-b128-0734e807d6f6.mov

feat: Display card HTML for loading during search

---

app/models/email_message.rb
spec/models/email_message_spec.rb

Add a guard for email message content that does not have an html tag
- Related Issue #18585
- Closes #18585 
1. Open admin → member manager → specific user → emails → click any confirmation instructions email
2. email displays correctly
updated. I have filled …

Add a guard for email message content that does not have an html tag

---

app/javascript/admin/controllers/config_controller.js

**Steps to reproduce the bug -- on main branch** 
1. Visit http://localhost:3000/admin/customization/config
2. Click on `Authentication`
3. Make sure `github` is enabled
4. Disable the `github-auth` by clicking `Edit` -> `Disable` -> `Confirm Disable`
5. Notice that the button for `Github` still remains as  `Edit`, **this is incorrect**.
[Bug Recording](https://www.loom.com/share/099c9c20b57449eb9a79f2f1b2d9bcfc)
**Steps to check the bug fix-- on this branch** 
1. Visit http://localhost:3000/admin/customization/config
2. Click on `Authentication`
3. Make sure `github` is enabled
4. Disable the `github-auth` by clicking `Edit` -> `Disable` -> `Confirm Disable`
5. Notice that the button for `Github` changes to `Enable`.
- [Video](https://www.loom.com/share/4c890edef2284649a3bd9cf09631a78a) …

Resolve minor UI bug in Admin-Config

---

app/javascript/packs/admin/displayAds.jsx

Trim the targeted tag value so that it does not show up in the Targeted Tags field with as an empty tag.
- Related Issue #https://github.com/forem/forem/issues/18519
- Closes #
https://www.loom.com/share/ee590cb3d5204203be2083181ad61624
1. Enable feature flag `display_ad_tags`
2. You can go to the display ads admin page and click through all the placement areas until you eventually get to Below the Comment section. 
3. On this branch you would see an empty targeted tags field however on main you would see a targeted tag with an empty tag.  …

Trim the targeted tag value so that it does not show up with an empty string

---

config/feed-variants/20221107-variant-a.json
config/feed-variants/20221107-variant-b.json
config/feed-variants/20221107-variant-c.json
config/feed-variants/20221107-variant-d.json
config/field_test.yml

Basic feed adjustments for the week, elevating winner and introducing adjacent experiments.
- Closes https://github.com/forem/forem/issues/18705 …

Feed experiment for 11-07-2022

---

README.md

- [ x] Documentation Update
Add my Dev name to Core Team. First PR 🎉 
- Closes #
- [ x] No, and this is why: _please replace this line with details on why tests …

Add dev username to core team

---

app/views/articles/_actions.html.erb
config/locales/views/actions/en.yml
config/locales/views/actions/fr.yml

Per Slack, it seems we're getting requests for a share-to-Mastodon feature. One small complicating factor with Mastodon is that there isn't any _one_ Mastodon, but there's a way around this via a [proxy](https://toot.kytta.dev/). If Mastodon becomes a _thing_, or if the proxy isn't reliable enough, we might want to revisit this to handle more of it on our end, but seems small enough to try it for now?
`cc` @erinb223 
[Changes …

Try a simple share -> mastodon via proxy

---

app/views/badges/_badge_detail.html.erb

- Related Issue #18690 #18680
- Closes #18690 #18680
[Changes …

removed extra badge description

---

app/services/edge_cache/bust/fastly.rb

Forgot one crucial thing about this code.
n/a

Add missing header to fastly_purge

---

app/controllers/admin/display_ads_controller.rb
app/models/display_ad.rb
app/views/admin/display_ads/_form.html.erb
app/views/admin/display_ads/index.html.erb
db/migrate/20221110130111_add_type_to_display_ads.rb
db/schema.rb

> As an admin, I'd like to be able to categorize Display Ads by "type" in order to stay more organized around the different categories of display ads that I'm running on my Forem.
- Closes https://github.com/forem/forem/issues/18640
- This is thematically similar to https://github.com/forem/forem/pull/18396, which also improved the administration of Display Ads.
appropriately.
replace this line with …

Add 'type_of' to DisplayAds

---

cypress/e2e/seededFlows/adminFlows/displayAds/createDisplayAds.spec.js

Attempt to fixing a breaking spec on `main`
N/A
Specs pass ✅ 
N/A

Fix human readable name of display ad placement in Cypress

---

config/feed-variants/20221122-variant-a.json
config/feed-variants/20221122-variant-b.json
config/feed-variants/20221122-variant-c.json
config/field_test.yml

New feed experiments — only adjusted config files.
- Closes https://github.com/forem/forem/issues/18768

Feed experiment for 11-22-2022

---

app/assets/stylesheets/views/mod-actions.scss

This PR changes the background of selected-tag inside `mod-panel` so that it can look like its actually visible.
- Related Issue #18683
- Closes 
1. Login as admin locally
2. Visit any post and open mod-panel
3. Under adjust tags option select any tag and see it gets reflected in UI also or not. Try this in dark-mode and light mode too.
Or you can simply look at before and after screenshots mentioned below.
No
[Changes …

CSS fix: Improve visibility of mod panel actions when in dark mode

---

app/assets/stylesheets/ltags/LinkTag.scss

When embedding a link to another Post and the author of the post is publishing under the umbrella of an organization, the icon for the author is too close to the Post title.
This PR makes sure that the UI for embeds like regular author post or org-author post, both look good.
- Related Issue #18734
- Closes #18734
1. Create an org post -- example "Post 1"
2. Create a regular author post (not org) -- example "Post 2"
3. Now create a new post and embed the "Post 1" and also "Post 2"
4. Compare the UI of both the embeds as shown in below screenshots.
5. You can also compare them in dark-theme too.
Check before vs after screenshots below:
1. Earlier the text content available on right was not aligned within different types of embeds.
6. In org-author based embed the gap between the …

CSS fix: Adjusted space between the author + org logo and post title in embeds

---

app/javascript/packs/admin/displayAds.jsx
cypress/e2e/seededFlows/adminFlows/displayAds/createDisplayAds.spec.js

This Display Ad location can target by tag, but the input is not hooked up to show for this location in the admin. This is a small fix to make that work.
- Related Issues:
https://github.com/forem/forem/issues/18519
https://github.com/forem/forem/issues/18638

Show tag admin input for Sidebar Right (Individual Post) location

---

app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/syntax.scss
app/assets/stylesheets/config/_colors.css
app/assets/stylesheets/themes/dark.css

CSS Fixes: Minor visibility fixes suggested by community
This PR fixes 2 minor issues mentioned in detailed below.
- Related Issue #18683
- Closes #18683
[Make the "I agree" signup check boxes more visible](https://github.com/forem/forem/discussions/17896)
As shown in [this](https://discourse.julialang.org/t/the-julia-forem-is-live-https-forem-julialang-org/82055/21) image the checkboxes for I-agree button are not very well visible to some users. To fix this as suggested by @anujbhavsar96  ([here](https://github.com/forem/forem/issues/18683#issuecomment-1325963338)) , I have changed the width from 1px to 1.5 px
1. Locally, create a new user. (You can do this easily by first enabling "Email Address" from http://localhost:3000/admin/customization/config)
2. Once new user is created, …

CSS Fixes: Minor visibility fixes suggested by community

---

spec/models/article_spec.rb

This pr fixes failing specs, these specs were not failing in `main` because the error was caught while evaluating frontmatter, so were false positives. 
- Related Issue #18754
- Closes #18763 
I recommend adding a space after `published_at` for the mentioned tests in the `main` branch first, to check that the tests are failing (for better understanding), then check the pr.
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&la …

Fixed problematic Article specs related to unpublishing

---

spec/requests/api/v1/docs/articles_spec.rb
spec/requests/api/v1/docs/users_spec.rb
swagger/v1/api_v1.json

- #18741
Spec change only. You can run this command locally if you'd like to re-generate the docs as well:
```
SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag PATTERN="spec/requests/api/v1/**/*_spec.rb"
```
N/A

V1 API docs for GET /articles/me/all

---

config/locales/views/articles/fr.yml
config/locales/views/settings/fr.yml

Fixes several broken key names in French locale files that caused errors.
- Related Issue #14888, #15098, #18177, #18457
- Closes # …

i18n: Fix several wrong French keys

---

app/assets/stylesheets/widgets.scss

CSS Design fixes for "Meet the team" section available in organisation.
- Related Issue #18812
- Closes #18812
1. Checkout this branch locally and sign-in as admin.
2. Visit `/admin/content_manager/organizations` and select one of the organisation to which you want to add multiple users. By default you might have id:1, 2, 3
3. Visit `/admin/member_manager/users`, click on each user and click `Add Organisation`, you will need to enter the org-id from step 2.
4. Visit the organisation by `/admin/content_manager/organizations`, click on org which you selected earlier, click on "View @<org-name>"
5. View `Meet the team` section.
| Before this PR  | After this PR |
| ------------- | ------------- |
| <img width="862" alt="Screenshot 2022-12-06 at 5 37 34 PM" …

CSS fixes for Meet the team section on org page

---

codecov.yml

SVG should not be considered part of code coverage
n/a

Ignore svg for codecov

---

app/views/articles/show.html.erb

Small bug fix to address a caching issue.
I observed multiple layers of caching here that are reasonably redundant. The _possibly slow query_ we are caching internally is already accounted for in another layer of fragment caching.
This seemed like a complexity-reducing way to fix the bug which is unlikely to cause a performance issue.
- Closes https://github.com/forem/forem/issues/18819
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&temp …

Remove redundant cache key to fix billboard issue

---

app/controllers/application_controller.rb
app/views/users/_additional_authentication.html.erb
spec/controllers/concerns/omniauth_redirect_spec.rb

When connecting an OAuth provider from an existing user's settings sometimes InstantClick interferes with the redirect path (after success) by introducing the `i=i` param. This causes the page to load and appear broken. This PR fixes this by ensuring this param is never introduced to that redirect path.
- Closes #18816
- Closes #18184
Note: You can remove an already associated account on `/settings/account` in the **Danger Zone** section
**To reproduce on `main` or a production site:**
1. Load the homepage with an authenticated user
2. Click on "Settings" from the top navigation dropdown menu
3. Click on "Connect Twitter Account"
4. You should arrive at `/new?signin=true&i=i`
https://user-images.githubusercontent.com/6045239/206677214-d6969450-1ece-4974-b219-de1727e2e30d.mov
**On this …

Fix connect account bug from settings

---

app/views/admin/users/show/profile/_status.html.erb

Change the case of comment suspended to match I18n key from here
https://github.com/forem/forem/blob/d94515b806e06cde98bd31f9b42dfff715230902/config/locales/views/admin/users/en.yml#L343-L344
- Closes #
Change a users status to comment suspended on main and then try to access their profile on http://localhost:3000/admin/member_manager/users page. It should error out but on this branch it will click through.  
none 
[Changes …

Change the case of comment suspended to match I18n key

---

app/services/feeds/import.rb

No need to be alerted on 0 messages if nothing was imported.
n/a

Make WorkflowWebhookWorker usage more mindful

---

README.md

Update Build status badge on README

---

config/feed-variants/20221215-variant-a.json
config/feed-variants/20221215-variant-b.json
config/feed-variants/20221215-variant-c.json
config/field_test.yml

After taking a break from weekly adjustments due to planning period, we're going to kick this back up.
This time we got the benefit of letting the last test run longer for extra conviction on a winner.
- Closes https://github.com/forem/forem/issues/18865
appropriately. …

Feed experiment for 12-15-2022

---

spec/requests/api/v1/docs/readinglist_spec.rb
swagger/v1/api_v1.json

We are using [rswag](https://github.com/rswag/rswag) to implement API V1 docs and are missing the following Reading List endpoints
- Related Issue #https://github.com/forem/forem/issues/18747
- Closes #https://github.com/forem/forem/issues/18747
Spec change only. You can run this command locally if you'd like to re-generate the docs as well:
```
SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag PATTERN="spec/requests/api/v1/**/*_spec.rb"
```
development process, or any of …

[API V1 docs] Reading List 

---

app/assets/stylesheets/components/buttons.scss
app/views/admin/feedback_messages/_abuse_reports.html.erb
app/views/admin/feedback_messages/_feedback_message.html.erb
app/views/admin/feedback_messages/_style.html.erb
app/views/admin/feedback_messages/index.html.erb
app/views/admin/profile_fields/_grouped_profile_fields.html.erb

This PR is a step towards removing bootstrap completely and replacing it with crayons.
The changes are only design related for which all before vs after screenshots have been shown below.
Note: This PR does not remove all the bootstrap classes. The classes which are not removed in this PR are `collapse`, `show`, `hide`, `nav`, `nav-tabs`, `nav-item`, `active`, `nav-link`, `tab-content`, `tab-pane` and `fade`.
These classes will be replaced with crayons in next PR.
- Related Issue #18756
- Closes #
**Before this PR**: whenever we collapse the below show menu at the end of animation there is glitch which has been fixed in in this PR.
**Glitch**
https://user-images.githubusercontent.com/9396084/209184697-6d7dffba-a2b0-4551-9bb7-e49eb1a9f410.mov
**Problem Fixed** …

Remove bootstrap from admin/feedback and use Crayons

---

app/controllers/api/v1/display_ads_controller.rb
app/models/display_ad.rb
spec/requests/api/v1/docs/display_ads_spec.rb
swagger/v1/api_v1.json

Setting `tags` in DisplayAd throws a 500 and does not set tags. (https://github.com/forem/forem/issues/18642#issuecomment-1362020986)
- Related Issue https://github.com/forem/forem/issues/18642#issuecomment-1362020986
* You can use postman to create (or update an existing DisplayAd)
* Set (or change) its tags via `tag_list` (comma-separated string)
will share this change with the people who …

Update DisplayAd API to allow setting tag_list

---

app/models/organization.rb
app/views/users/_org_admin.html.erb
spec/models/organization_spec.rb

As an organization, the current 18 character limit is insufficient in some contexts. A 30 character limit will expand sensible use cases while still having a reasonable upper limit.
- Closes #18883
appropriately. …

Allow org slug to be up to 30 characters #18883
