forem/forem

app/javascript/actionsPanel/initializeActionsPanelToggle.js
cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
cypress/support/index.js
package.json
yarn.lock

The `adjustPostTags` spec had been occasionally flaking in CI, due to a race condition between the Cypress click event, and the click handler being added asynchronously in `initializeActionsPanelToggle.js`. 
This kind of race condition has tripped us up a few times, and we've solved it ad hoc around the code by adding data attributes when click handlers are attached (so we can then await the data attribute being present in the DOM). This workaround however is far from ideal, leaving random data attributes around our production HTML.
Clicks aren't retriable in Cypress, because normally if X action doesn't occur on click, it should represent a test failure. However they point towards a package called `cypress-pipe` to account for these kind of situations where listeners are attached async. …

add cypress-pipe, fix flaky test

---

app/assets/stylesheets/base/main.scss
app/views/layouts/_logo.html.erb

Ensure that the logo shows up properly within the navbar container whether the Feature Flag is enabled or not.
In your rails console set the following:  
```
Settings::General.original_logo = "https://canary1.forem.wtf/remoteimages/uploads/articles/bcvmn496boszdko7jb09.jpeg"
Settings::General.resized_logo = "https://canary1.forem.wtf/remoteimages/uploads/articles/zn14x1elppv4frwlnbo9.jpeg"
Settings::General.logo_svg = '<svg width="50" height="40" viewBox="0 0 50 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="50" height="40" rx="3" style="fill: currentColor;"></rect><path d="M19.099 23.508c0 1.31-.423 2.388-1.27 3.234-.838.839-1.942 1.258-3.312 1.258h-4.403V12.277h4.492c1.31 0 2.385.423 3.224 1.27.846.838 1.269 1.912 1.269 3.223v6.738zm-2.808 …
```

Logo style updates

---

app/models/html_variant.rb
spec/models/html_variant_spec.rb

Discovered while investigating [a problem reported by @SGGregory in Slack]([this was actually the catalyst for this PR](https://forem-team.slack.com/archives/C7GE84DEJ/p1639508636380800?thread_ts=1639506098.374400&cid=C7GE84DEJ)).
The `HtmlVariant` model is used to populate banners and is keyed on the `name` property. If the name specified in the site settings does not match a variant's name _precisely_ it will not show. It's really easy for a human to overlook leading or trailing whitespace, so this PR strips it out.
Adapted for local development from [Gracie's instructions in Slack](https://forem-team.slack.com/archives/C7GE84DEJ/p1639508207380300?thread_ts=1639506098.374400&cid=C7GE84DEJ):
- Create an [HTML variant](http://localhost:3000/admin/customization/html_variants/new) with a …

Strip surrounding whitespace from HTMLVariant name

---

app/liquid_tags/link_tag.rb
spec/lib/liquid/raw_spec.rb
spec/liquid_tags/unified_embed_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Forem posts/articles.
closes https://github.com/forem/forem/issues/15564
- Before testing, grab (or create then grab) the URLs of an article in your localhost.
- As a user, create a Forem Article liquid tag using this format: `{% embed <forem-article-url> %}`. The Article Liquid Tag should render properly.
- Also create article liquid tag using the old methods: `{% link <forem-article-url> %}` or `{% post <forem-article-url> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present …

Implement Unified Embed for Forem Article/Post URLs

---

app/controllers/stories/tagged_articles_controller.rb
app/views/stories/tagged_articles/_meta.html.erb
app/views/stories/tagged_articles/_sidebar.html.erb
app/views/stories/tagged_articles/_sidebar_additional.html.erb
app/views/stories/tagged_articles/index.html.erb

Having both `@tag` and `@tag_model` as variable names can be confusing.
Given that in the prior implementation `@tag_model.name == @tag`, I
figured I would refactor the controller to remove an instance variable.
In addition, this refactor addresses the temporal coupling of methods;
that is to say we call a method which sets an instance variable then
call another dependent on that instance variable.
Yes, ivars are useful to allow for implicit state.  However, by favoring
parameters its easier to notice temporal dependencies in method calls.
This helps ensure that we're calling methods in the right order.
Futher, we have a guard clause in place, so let's avoid setting any
additional instance variables that aren't needed if the guard clause
executes.
Related to #15359
The tests cover this …

Refactoring instance variable usage in tagged articles controller

---

app/services/users/update.rb
spec/services/users/update_spec.rb

We had 2 users on DEV this morning with `nil` profiles stuck in onboarding because their profiles had not been created. I haven't figure out _why_ they weren't created, but creating the profiles here will help out regardless of reason.
- [Datadog trace](https://app.datadoghq.com/apm/traces?query=env%3Aproduction%20service%3Apractical_developer%20operation_name%3Arack.request%20status%3Aerror%20resource_name%3AUsersController%23onboarding_update&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanID=1508691058460892819&streamTraces=true&timeHint=1639573200000&trace=AQAAAX2-YHKFzy8pqwAAAABBWDItWUlVb0FBQ1dBMXVlOHBtbHc3Y1Q&traceID=1420705037609487267&start=1639554228279&end=1639583028279&paused=t …

Automatically create user profile if it's missing

---

app/liquid_tags/instagram_tag.rb
app/liquid_tags/liquid_tag_base.rb
app/liquid_tags/youtube_tag.rb
spec/liquid_tags/unified_embed_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Instagram posts.
closes https://github.com/forem/forem/issues/15560
Example Instagram URLs:
https://www.instagram.com/p/CXgzXWXroHK/
https://instagram.com/p/CXgzXWXroHK/
http://www.instagram.com/p/CXgzXWXroHK/
www.instagram.com/p/CXgzXWXroHK/
instagram.com/p/CXgzXWXroHK/
- As a user, create an Instagram (IG) liquid tag using this format: `{% embed <instagram-post-url> %}`. Please use all the example URLs provided above. The Instagram Liquid Tag should render properly.
_NOTE: the IG Liquid Tag renders as though it has been truncated, i.e. the height looks too short. I have verified that this is the current appearance in production._
- Also create IG liquid tag using the old method: `{% instagram …

Implement Unified Embed for Instagram Post URLs

---

bin/e2e

Now Spring is disabled when creating a database for end-to-end tests that run locally. Prior to this fix, it was pretty consistent to see this error.
```
Doing a quick bundle check to make sure gems are all up to date.
The Gemfile's dependencies are satisfied
yarn install v1.22.5
[1/6] 🔍  Validating package.json...
[2/6] 🔍  Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
✨  Done in 1.09s.
Choose yes to setup a test database or if you're running the script for the first time, choose no or wait 10 seconds otherwise (y/n) y
Setting up the E2E database before running E2E tests...
[TEST PROF INFO] Spring detected
/Users/taco/dev/forem/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:101:in `block in preload': Spring reloads, and …
```

Disabled Spring for E2E databse when run locally

---

app/views/admin/creator_settings/_form.html.erb
cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js

Changed the copy for a checkbox label for the "Who can join this community?" section of the creator settings form.
```ruby
```
3. Click on the login link. Since the feature flag is enabled, you'll be redirected to Creator Signup Form.
4. Fill in the necessary information and submit the form.
5. Notice in the "Who can join this community?" section that it now says _Invite Only_ instead of _Members Only_ for the second radio button.
6. Ensure both the Terms and Conditions …

Changed members only copy for radio button label to invite only.

---

app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/articles_controller.rb
app/controllers/api/v0/readinglist_controller.rb
app/controllers/api/v0/users_controller.rb
app/controllers/api/v0/webhooks_controller.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/api/v0/listings_spec.rb
spec/requests/api/v0/readinglist_spec.rb
spec/requests/api/v0/users_spec.rb
spec/requests/api/v0/webhooks_spec.rb

In order to be able to completely remove Doorkeeper from our application I needed to remove it from our API. This feature was labeled as "private alpha" before so should be safe to remove. I'll try to get clarity on whether or not this needs a changelog post.
NOTE: I originally tried to remove all of Doorkeeper in a single PR (https://github.com/forem/forem/pull/15749) but that got unwieldy so I intend to break things down as seems appropriate.
https://github.com/forem/forem/issues/15748
All specs should be green
No UI changes

Remove Doorkeeper from API

---

app/controllers/articles_controller.rb
app/helpers/application_helper.rb
app/models/badge_achievement.rb
app/models/display_ad.rb
app/models/html_rendering.rb
app/sanitizers/rendered_markdown_scrubber.rb
app/services/markdown_processor.rb
app/services/markdown_processor/parser.rb
app/views/podcast_episodes/show.html.erb

_**Note:** I'm proposing changing where we store knowledge regarding tags.  The goal is to begin assessing what patterns we have and why. For example, why does DisplayAd have the set of tags that it does?  Are we missing any?_
Prior to this commit, we had several different locations in which we
specified ALLOWED_TAGS and ALLOWED_ATTRIBUTES for HTML rendering and
sanitization.
Curious to see how these either intersected or didn't, I opted to
create a container module that allows for us to more readily normalize
these allowed tags and attributes.  It's possible that we won't do any
normalization, but this work helps make that easier.
Ideally, I'd love us to contextualize "why did we choose the
tags/attributes we chose?"  But for now, I think consolidating these
tags and attributes will help …

Extracting container for allowed tags & attrs

---

spec/system/notifications/notifications_page_spec.rb

This had been failing in builds (my assumption is that the state flag
for .reacted was either out of sync or not yet ready/unhidden, I'm
still getting more information about this).
The behavior being tested is that clicking the greyed out heart on a
reply enables the .reacted class, and clicking again disables
it. There's [a similar test](https://github.com/forem/forem/blob/main/spec/system/notifications/notifications_page_spec.rb#L73-L86) for a trusted user clicking heart, thumbs down,
and monocle/flag/vomit icons one by one and checking the state on the
page.
This is a good candidate to move to a cypress test.
I would run this 10 times to confirm this is solid:
```
bundle exec rspec spec/system/notifications/notifications_page_spec.rb 
```
_If your PR includes UI changes, please replace …

Skip notification interaction with replies spec

---

app/liquid_tags/blogcast_tag.rb
app/liquid_tags/vimeo_tag.rb
app/views/liquids/_blogcast.html.erb
spec/liquid_tags/unified_embed_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Blogcast embeds.
closes https://github.com/forem/forem/issues/15553
Example Blogcast URLs:
https://blogcast.host/embed/4942
https://app.blogcast.host/embed/4942
- As a user, create a Blogcast liquid tag using this format: `{% embed <blogcast-url> %}`. Please use the example URLs provided above. The Blogcast Liquid Tag should render properly.
- Also create Blogcast liquid tag using the old method: `{% blogcast <blogcast-id> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present …

Implement Unified Embed for Blogcast URLs

---

.gitpod.yml

The gitpod-init.sh runs a command to get the expected url for this host when viewing port 3000 (`gp url 3000`) and sets that as the app domain in the .env file. However, the site is not allowing access via this url (it shows blocked host and suggests you update the config.hosts list).
https://www.gitpod.io/docs/environment-variables#terminal-specific-environment-variables
Without this I'm seeing the ENV["APP_DOMAIN"] not set when spring is
loaded (this prevents browsing the site from within gitpod), suggesting the .env file was not loaded the first time a ruby process (gem install? bin/setup) started and consequently is not present when the app starts up here.
Exploration of the issue showed the Settings::General.app_domain was correct, but ENV["APP_DOMAIN"] and …

Add DISABLE_SPRING environment variable to gitpod forem server task

---

app/validators/emoji_only_validator.rb
spec/validators/emoji_only_validator_spec.rb

Don't raise an error when validating a nil emoji, and assert nil and
empty string are permitted values.
This expects no non-emoji characters (so an empty string would be
permitted), and nil should be permitted.
~I believe this might have been introduced by the string settings
cleaner (exchanging "" for nil in form inputs).~
I cargo culted the unique cross model slug validator setup (which is why
value is called name here in the validatable). Replacing with "emoji" or 
"value" seems perfectly sane.
This doesn't actually override the default value for the setting, as #14228 nullifies the `value` and the `default: "🌱"` replaces the nil when loading this setting. Special casing that to permit a blank value (or removing the seedling default) seems like a separate issue from the no method error …

Don't raise error when empty community emoji setting submitted

---

config/fastly/snippets/bad_bot_detection.vcl

We were previously disallowing empty user agents, but we weren't blocking requests where the User-Agent header wasn't set at all. This commit blocks those requests.
This commit also blocks Chrome 74. It's a 2.5-year-old version of an evergreen browser that releases every 6 weeks, so this is clearly a bot spoofing this header.

Disallow null user agent and obsolete browser

---

app/services/users/delete_activity.rb
spec/services/moderator/banish_user_spec.rb

This fixes a bug where we don't clear an account's `profile` properly when banishing. This fixes that.
https://github.com/forem/internalCommunity/issues/127
1. Edit a user's profile via /settings or in console:
```ruby
User.first.profile.update(summary: "blahblah blah", website_url: "www.spam.com")
```
2. banish the user via /admin/users/:id/edit
3. See that the user profile is properly cleared
Nope
No

Remove profile when banish

---

app/helpers/admin_helper.rb
app/views/admin/profile_fields/_add_profile_field_modal.html.erb
app/views/admin/profile_fields/_edit_group_modal.html.erb
app/views/admin/profile_fields/_grouped_profile_fields.html.erb

This fixes a bug where using a period `.` causes some issues with `document.querySelector`, and therefore prevents the buttons from being used when an admin has made a profile field group with a period. For example, a `ProfileFieldGroup` with a `name` of `1. Favorites` will break the buttons, because the HTML IDs that are passed along in the view are not escaped. 
In lieu of trying to escape periods (and any other non-DOM friendly characters), I decided to go with a quicker fix of converting any periods to underscores so that we avoid any problems here. The original intention of using a `profile_field_group.name` of `1. Favorites` was to order them (right now they are alphabetically ordered). Ordering will probably be a feature in the future, so for now the quick fix seems like the right …

Escape periods and display the group name properly

---

app/models/user.rb
app/services/users/update.rb
spec/models/user_spec.rb
spec/requests/stories_show_spec.rb
spec/requests/user/user_profile_spec.rb

Moved code related to changing username from a `before_validation` callback in `User` model  to `Users::Update` service.
#15424
I mentioned this change in #15704
When a user changes their username from /settings/profile, their `old_username` and `old_old_username` should be updated to the previous `username` and previous `old_username` values accordingly (the logic wasn't changed)

Moved setting old_username from before_validation to Users::Update

---

app/services/markdown_processor/fixer/base.rb
app/services/markdown_processor/fixer/fix_all.rb
app/services/markdown_processor/fixer/fix_for_comment.rb
app/services/markdown_processor/fixer/fix_for_preview.rb
spec/services/markdown_processor/fixer/base_spec.rb
spec/services/markdown_processor/fixer/fix_all_spec.rb
spec/services/markdown_processor/fixer/fix_for_comment_spec.rb
spec/services/markdown_processor/fixer/fix_for_preview_spec.rb

There's a filter in the markdown fixer to replace `---` strings of three dashes with `------` strings of 6 dashes, and a comment that this is to prevent mangling the frontmatter.
I'm unable to replicate a situation where this causes problems, and suggest we remove this modification.
Specifically, when a user using the v1 editor (basic markdown) sends a post body with front matter (fenced by `---` lines, retained unmodified) and a code snippet with `---` (for example, an example of a markdown post) the code snippet gets mangled.
For a user using the v2 editor (rich text) the first code block is unmodified, but second and subsequent code blocks replace `---` with `------`.
Fixes https://github.com/forem/forem/issues/15832
https://github.com/forem/forem/issues/237 I think was related to the …

Disable dash replacement filter in markdown fixer 

---

app/assets/javascripts/initializers/initNotifications.js
app/views/notifications/index.html.erb
app/views/notifications/shared/_comment_box.html.erb
cypress/integration/seededFlows/notificationsFlows/commentNotifications.spec.js
spec/support/seeds/seeds_e2e.rb
spec/system/notifications/notifications_page_spec.rb

In https://github.com/forem/forem/pull/15799/ we skipped some rspec tests relating to notification interactions due to flakiness. This PR moves one of those sets of tests over to Cypress, making necessary bug fixes to do that reliably.
The user-facing bugs fixed in this PR include:
- Adding the RunKit script to the notifications page. Previously, if you submitted a reply to a comment from the notifications page, an unhandled error was shown in the console where `activateRunKitTags` was not defined. Although this wasn't hugely impacting user experience, unhandled exceptions cause Cypress tests to fail, so I've fixed it by including the script on that page.
- Accessibility fixes for the accessible name of the 'like' and 'reply' controls. Previously various SVG titles were being relied on …

Add comment notification test to Cypress, including a11y improvements to notification page

---

app/queries/articles/active_threads_query.rb

With this refactor, I'm adding documentation and favoring using a common
method that wasn't available at the time of implementation.
In [this commit][1] we had logic that said "if we have a singular tag
use the cache" otherwise use the join.  At that time, the implementation
of [Article.cached_tag_with][previous] was as follows, allowing only a
singular tag:
```ruby
scope :cached_tagged_with, ->(tag) { where("cached_tag_list ~* ?",
"^#{tag},| #{tag},|, #{tag}$|^#{tag}$") }
```
The [current implementation][current], as of writing this, allows for
multiple tags and is as follows:
```ruby
scope :cached_tagged_with, lambda { |tag|
case tag
when String, Symbol
where("cached_tag_list ~ ?", "[[:<:]]#{tag}[[:>:]]")
when Array
tag.reduce(self) { |acc, elem| acc.cached_tagged_with(elem) }
when Tag …
```

Favoring common method not previously available

---

app/services/notifications/new_mention/send.rb
spec/services/notifications/new_mention/send_spec.rb

@amywtlin reporting seeing mobile notifications that read something like "Amy mentioned you in a post": the mentionee is being listed as the author of a comment/post instead of the actual author! This PR fixes that, and adds a test to check it.
https://github.com/forem/forem/pull/15780
issue template so Community Success can help update …

User correct username in mobile mention notifications

---

app/models/tag.rb

Prior to this commit, we ran a SQL statement to generate a list of
articles then applied some minor randomization.
With this commit, I'm removing the randomization in favor of expected
values, and collapsing the result set into a single inline SQL and some
post query simple arithmatic.
Let's check my math.  For each article we sum:
* `article.score`
* `article.comments_count` * 14
* a random number between 0 and 5 (`rand(6)`) with expected value of 2.5
* the tag's (taggings_count + 1) / 2
The new SQL query sums the `article.score` and the
`article.comments_count` * 14.  I then reduce the remainder of the
equation.  From "for each article sum `(rand(5) + (taggings_count + 1) /
2)`" we have the following:
`article_count * (2.5 + (taggings_count + 1) / 2)`
Which is equivalent to: …

Favoring single SQL and computation over enum

---

app/controllers/profile_pins_controller.rb
app/models/consumer_app.rb

We can use [ActiveRecord::Relation.destroy_by][1] instead of the method
chain.
[1]:https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-destroy_by
None.
None.
None.
not: leveraging a framework method over a chain of framework
methods.

Favor `destroy_by` over `where.first&.destroy`

---

app/controllers/application_controller.rb

The 400 and 401 error pages show json parsing errors in most browsers,
since "Error: Bad Request" is not a valid json body ('"Error: Bad
Request"' would be, or the object with key error and value of the
string which I've selected is _also_ valid).
In firefox I see the following (the body is parsed because the content type was set to json):
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
Do we have frontend code that's looking for this body before it parses
for some reason, or was this just a mistaken copying from the api
controller in the initial PRs (#2293 for not_authorized, and #6248 for
the bad_request method, which may have just replicated the decision
for not_authorized)? I think in 2293 an api method was added to the 
application …

When returning a json error, don't use a raw unescaped string

---

app/models/user.rb
spec/services/search/username_spec.rb

Prevents an error when the username search term includes '\'
PG::SyntaxError: ERROR:  syntax error in tsquery
https://app.honeybadger.io/projects/66984/faults/79391397
I had originally thought to add this cleanup to [Search::Username.search_documents](https://github.com/forem/forem/blob/main/app/services/search/username.rb#L12), but
decided to move it as close to the generated (invalid) query as
possible to prevent alternate paths finding their way here.
It was much easier to add the test case to the search service, however. 
```ruby
string = %{"')\}
Search::Username.search_documents(string)
=> []
```
On main this raises the above error (syntax error in tsquery due to the \ character).
None
development process, …

Remove slash characters from user name search term

---

app/liquid_tags/youtube_tag.rb

We are seeing test failures when an id like "aaabbbcccdd1m" match with
"1m" as the time parameter. I think we only want to match the time
when a ?t= or ?start= (and the permissive &t= or &start=, which might
only be part of the larger REGISTRY_REGEXP and either not effective or
not needed for the video id pattern)
The goal here is these should be valid
```ruby
"aaabbbcccdd"
"aaabbbcccdd?t=1"
"aaabbbcccdd?start=1h23m55s"
"aaabbbcccdd&t=1"
```
but not these
```ruby
"aaabbbcccddt=1"
"aaabbbcccdd?1"
"aaabbbcccddstart=1"
"aaabbbcccdd123456h"
```
The same logic may be appropriate to backfill into the prior regexp as
well, my immediate concern is with randomly generated 12-15 character
strings from Fake getting matched during testing (where they were
expected to raise an error during id …

Require parameter string before matching time for youtube video ids

---

db/seeds.rb
spec/factories/identities.rb
spec/models/identity_spec.rb

Fixed setting `Identity#auth_data_dump` in the seeds and the factory.
`auth_data_dump` was set to a hash in the seeds instead of an instance of `OmniAuth::AuthHash`  which caused an error
```
undefined method `info' for {"extra"=>{"raw_info"=>{"lang"=>"en"}}, "info"=>{"nickname"=>"..."}}:Hash  in Identity#email
```
when accessing `Identity#email`:
https://github.com/forem/forem/blob/c7902a32611ab8b342e70a80112184114ba75cba/app/models/identity.rb#L47-L49
e.g. on `/settings/account` page
- create a user via seeds
- log in as the user
- make sure that enabled providers are not empty (`Authentication::Providers.enabled `, `Settings::Authentication.providers `)
- visit `/settings/account` page
- the page should render successfully, and contain identity email in the `Account emails` block

Fixed setting Identity#auth_data_dump in seeds and factory

---

spec/requests/admin/users_manage_spec.rb

Mock omniauth payload before creating identities.
This pr is created to fix the build of the main branch after merging #15874
I plan to refactor the code so that we wouldn't have to mock the payload explicitly before using `Identity` factory each time.
#15874

Mock omniauth payload before creating identities

---

db/migrate/20211222040359_remove_doorkeeper.rb
db/schema.rb

This PR removes the tables we no longer need after #15749 and #15827. Note that this is a non-reversible migration, so we only provide an `up` method.
#15748
Closes #15826
Nothing specific to QA
No UI changes

Remove Doorkeeper and webhook tables

---

app/controllers/articles_controller.rb
app/controllers/stories/tagged_articles_controller.rb
app/models/article.rb
app/services/articles/feeds/large_forem_experimental.rb

I've been looking at the queries that involve filtering articles based
on scores.  There's several places that seem to be close to consistent,
but have some nuanced difference.
This refactor consolidates one of those "almost the same" cases.
None.  Although tangentially related to Feed algorithm, as I'm trying
to wrestle with how we filter on score.
None.
None.

Refactoring to leverage an Article scope

---

app/services/email_digest_article_collector.rb

We're sometimes sending digest emails to users without respecting their frequency preferences.
At first I thought the was tied to not sorting the 10 messages we sampled to compare (it might be, but I doubt it), and then I tried testing it and found that `should_send_email?` was true when the only message was sent even just a few seconds earlier. The setting for periodic email frequency is an integer, and we were comparing it to a difference between two timestamps (in seconds) - so anything farther apart than a default 2 seconds qualified for resending articles.
~Cast the setting to days prior to comparing `(now - last_time) > setting` to ensure we're not doing this more than we intended to.~
Compare the last time an email was sent to a timestamp a few days ago (based on the setting) to …

Periodic Digest Email frequency should be in days

---

app/views/mailers/notify_mailer/trusted_role_email.html.erb
app/views/mailers/notify_mailer/trusted_role_email.text.erb

This adds new copy with an invitation link to our moderators' Discord.
Preview the two links here to see if they look consistent with the copy from https://github.com/forem/internalCommunity/issues/248:
http://localhost:3000/rails/mailers/notify_mailer/trusted_role_email.html?locale=en
http://localhost:3000/rails/mailers/notify_mailer/trusted_role_email.txt?locale=en

Update trusted user welcome email copy with Discord link

---

app/services/articles/suggest_stickies.rb
spec/services/articles/suggest_stickies_spec.rb

I came to this commit by looking for raw `where` method calls to the
Article object.  Originally, I was looking at `where.not(user_id: :id)`
but found this service class.
In this class, I saw some significant duplication and went with a bit of
refactoring and some documentation.
This refactoring removed some unnecessary guards and calculations (as
documented inline).
None.
None.
None.

Refactoring and documenting class

---

app/views/layouts/_main_nav.html.erb
config/locales/views/main/en.yml
config/locales/views/main/fr.yml
spec/system/homepage/user_visits_homepage_spec.rb

This PR removes the hardcoded "Sign In/Up" link from the left-hand nav menu. So far we only displayed this for non-logged in users which is redudant with the bigger CTA right above:
Closes #15921 15921
The link should be gone
None

Remove sign in/up link from navlinks

---

app/services/feeds/import.rb

dev.to blocks access to the feeds for user agent "Ruby"
Use "Forem Feeds Import" as alternate user agent when fetching feeds.
fixes https://github.com/forem/forem/issues/15939
```ruby
url = "https://dev.to/feed/vickilanger"
HTTParty.get(url, timeout: 10, headers: { "User-agent" => "Forem Feeds Import" })
```
on main the request uses no user agent header, Net::HTTP's default "Ruby" is sent, and we block that in the fastly bad bot detection - gives a 403 response.
on this branch, the custom user agent is permitted (and descriptive), we get a 200 status with xml body.
None

Send custom user agent string when fetching feeds

---

.travis.yml

Travis's dpl tool is including faraday 2.0 which doesn't work well after https://github.com/lostisland/faraday/pull/1354
Can we install faraday here before installing dpl and make this work?
I have no clue how to test this? Maybe debugging the deploy job (that has lots of bad implications w.r.t secrets like the deploy key, I'm hesitant to do that). 
None

Add faraday 1.8.0 before deploying

---

.travis.yml

The [last PR]( https://github.com/forem/forem/pull/15951 ) installed faraday 1.8.0 in _our_ ruby (3.0) but travis's internal ruby is 2.7 and didn't install the gem before calling dpl.
Explicitly (in the deploy stages) install this package (and dpl, why not) before deploying to heroku.
Deploy succeeds? 
None

Work around travis deploy (take two)

---

.travis.yml

This was part of the node 16 upgrade and is no longer helpful - occassionally restoring node modules from cache is resulting in a string of failures where canvas is not available to the frontend tests.
None
None

Stop removing canvas files from CI build cache

---

app/liquid_tags/unified_embed.rb

The deploy of [this PR](https://github.com/forem/forem/pull/15911) broke the use of the `embed` keyword in UnifiedEmbeds in the UI. Upon saving a unified embed of the form `{% embed <url-being-embeded> %}`, the error `Liquid syntax error: Unknown tag 'embed'` was generated.
This PR fixes the above by requiring the `UnfiedEmbed::Tag` for the UnifiedEmbed Registry.
None
Create a post with a Youtube embed like so: `{% embed https://youtu.be/DDWKuo3gXMQ %}`. It should render correctly.
None
None

Require UnifiedEmbed Tag for UnifiedEmbed Registry

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/controllers/display_ad_events_controller.rb
app/models/display_ad_event.rb
spec/factories/display_ad_events.rb
spec/models/display_ad_event_spec.rb
spec/requests/display_ad_events_spec.rb

Prior to this commit, we had a couple of references to magic strings
regarding DisplayAdEvent objects.  This commit seeks to consolidate that
behavior.
In a handful of cases we had javascript variables, but as these JS files
are `erb` templates, we can inject the constant as well.  This reduces
repetition of knowledge.
None.
None.
None.

Extracting constants and tidying tests

---

.travis.yml

[Faraday 2.0.1](https://github.com/lostisland/faraday/releases/tag/v2.0.1) 
re-introduces the default adapter (net_http), which
makes the prior work around (installing faraday 1.8 prior to
installing dpl, preventing it from bringing in 2.0.0 as the current
release).
There's currently a related dependency [issue](https://app.travis-ci.com/github/forem/forem/jobs/554550408) where a circular
dependency between dpl, faraday, and faraday-patron was causing deploy
failures (faraday-patron requiring faraday 2.0.x but we had
specified otherwise).
Remove the temporary shim to enable travis heroku deploys, and let
their team manage that.
This is a change to the deploy stage. I'm not sure how to test this without... deploying?
None …

Remove Faraday work-around for deploys

---

.env_sample
app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/controllers/ga_events_controller.rb
app/views/pages/badge.html.erb

This commit involves short-circuiting Google Analytics calls when the
Forem has not configured a `Settings::General.ga_tracking_id`.  Note,
depending on your local `.env` file (or configured ENV variables) you
may have a `GA_TRACKING_ID` value set; I did, it was set to "Optional"
which overrode the database setting.
We set the HTML data properites in two places: [admin.html.erb][1] and
[application.html.erb][2].
In addition, I'm short-circuiting the local fallback analytics call (via
[Stacato][https://github.com/tpitale/staccato]).  My understanding of
Stacato, based on a cursory read, requires a Google Analytics Tracking
ID to work.
And last, we have a one off of javascript for Google Analytics tracking.
[1]:https://github.com/forem/forem/blob/528bd2baa608292f3e603c7a7587832a46cc791a/app/ …

Skip google analytics when ga_tracking_id is nil

---

.travis.yml

This was an initial attempt at the work-around used yesterday. It was unsuccessful (since the faraday gem installed on _our_ version of ruby, but the conflict was happening in travis's internal ruby used for deployment).
This is safe to remove, since it's not needed, and we'll be uselessly installing a gem during each test build.
None

Remove extra faraday install from travis config

---

app/workers/users/record_field_test_event_worker.rb
spec/workers/users/record_field_test_event_worker_spec.rb

This is the "hardest" goal to reach, but I didn't think it made sense for _no_ conversions yet, especially since I knew at least my own account should have converted. So I found this typo which created the mismatch between the config and the code. Dutifully the tests also included the same typo 😅
Introduced here: https://github.com/forem/forem/pull/15789/files#diff-c604816b4c652e5a874508ece2d282d0dd9fdaa10deb66a45401e1536d278b65R30
Not a great public-facing concern — but a note will be made in this test period's retro.
I am going to manually modify the name of the converted `FieldTest::Events` to sync things back up as they should once this is shipped. I don't think this needs a data update script, this is very much a one-off concern that would work itself out for …

Fix goal conversion field test typo

---

app/controllers/tags_controller.rb
app/models/tag.rb
lib/data_update_scripts/20220104165348_nullify_empty_string_for_alias_for.rb
spec/lib/data_update_scripts/nullify_empty_string_for_alias_for_spec.rb

Prior to this commit we had a custom `where(alias_for: [nil, ""])`
call.  That call highlighted that we lacked a term for a Tag that was
not an alias.  As part of this commit, I named that a "concrete" tag.
Further, I added scopes to assist in helping "name" those concepts.
This commit also adds a data migration and utilization of
StringAttributeCleaner to hopefully get away from `alias_for == ""`
situations.
As of writing this commit <2022-01-04 Tue 17:22 UTC>, in DEV.to we had 5
tags with `alias_for == ""`:
- actionshackathon21
- regex
- atlashackathon
- hotwire
- foremfest
In https://dev.to/admin/blazer I ran the following:
```sql
SELECT name FROM tags WHERE alias_for = ''
```
None.
None.
None.

Tidying up and documenting Tag model

---

app/models/consumer_app.rb
app/queries/consumer_apps/rpush_app_query.rb
spec/queries/consumer_apps/rpush_app_query_spec.rb

[Rpush models are stored in Redis](https://developers.forem.com/backend/push-notifications#rpush-implementation) and we started running into a problem where we couldn't fetch Android Rpush app models (`Rpush::Apns2::App` or `Rpush::Gcm::App`). This started happening after some time of having the Android mobile app in closed beta.
The cause of the error was a conflict in the `name` attribute of the Rpush app models. Since they use Redis storage and not postgres these models rely on different ways to query them. Since the introduction of Android support there was now a case where `app_bundle` was the same for two different `ConsumerApp`s, and this conflict caused the issue reported.
#15959
This is a tricky one to QA. A quick way to try this out locally would be:
- Make …

Fixes a name conflict in Rpush models

---

bin/setup

We had added a forceful removal of a compiled package (canvas) during the setup step to ease the node 16 transition.
This is safe to remove (as it causes canvas to be reinstalled every time setup is called). 
Run bin/setup twice. Yarn should do nothing (install no packages) the second time.
None
I'll add this to the github discussion @cmgorton opened about the node update.

Stop removing canvas before yarn during bin/setup

---

bin/setup

Based on the discussion in #15876 it seems reasonable to include the copying of `.env_sample` to `.env` in our `bin/setup` script, similar to what we're already doing for `database.yml`.
#15876
* Remove `.env` (back it up if you customized it)
* Run `bin/setup`
* You should now have a default `.env` file
No UI changes

Copy `.env_sample` to `.env` in `bin/setup`

---

app/javascript/Snackbar/__stories__/Snackbar.stories.jsx
package.json
yarn.lock

The author of the faker package has decided to no longer maintain the software. The [faker-js](https://github.com/faker-js/faker/#faq---what-happened-to-the-original-fakerjs) project looks like a reasonable alternative (currently they've copied the original packages from the node repo).
This prevents dependabot suggesting we upgrade to the (non-functional) version [6.6.6 of faker](https://github.com/Marak/faker.js/commit/2c4f82f0af819e2bdb2623f0e429754f38c2c2f2), and provides an update path if there's more added in the future.
No changes to behavior expected.
None, this is a test time dependency …

Migrate faker dependency to supported upstream

---

app/views/organizations/_header.html.erb
app/views/users/_account.html.erb
app/views/users/_additional_authentication.html.erb
app/views/users/_main_feed.html.erb
app/views/users/_org_admin.html.erb
app/views/users/_sidebar.html.erb
app/views/users/edit.html.erb
app/views/users/show.html.erb

We recently added a new [`crayons_icon_tag` helper](https://github.com/forem/forem/pull/15878). This PR changes user and organization views to make use of it.
https://github.com/forem/forem/pull/15878
Nothing specific, there should be no visible changes.
No UI changes

Use crayons_icon_tag for user and org views

---

app/controllers/stories/feeds_controller.rb
app/models/ab_experiment.rb
app/services/articles/feeds/weighted_query_strategy.rb
config/field_test.yml
spec/models/ab_experiment_spec.rb

With the challenger winning this round, we feel comfortable moving strictly to the "Weighted Query Strategy", which is more flexible for further adaptation and has the highest potential for computer resources and relevance performance.
I have discussed this with @jeremyf, the original maker of this strategy, and we are in alignment that this is a solid way to continue experimenting. We anticipate future refactors where entire configs are injected into the algorithm, but that is not the most nimble way to achieve our near term goal of ensuring the network gets the relevant feed it deserves.
- Drop "Large Forem experimental" from signed in testing — Weighted Query Strategy seems to be successful this time around and I think we can put more effort into going deep in testing ways to go with …

Proposing feed experiment 3: More comment count weight

---

app/liquid_tags/unified_embed/tag.rb
spec/liquid_tags/unified_embed/tag_spec.rb

When a user passes in a non-URL (or invalid URL) into a unified-embed(`{% embed <non-URL or invalid URL> %}`), the current treatment is to return an `href` (see Image 1 below). However, this is problematic because it creates a link that goes nowhere, but yet sends the message that, though the embed did not work, the resulting link is "valid".
This PR instead raises a `StandardError`, sending a clear message that the embed did not work (see Image 2 below), AND giving the user the opportunity to correct the URL passed in, or decide how else to include their intended content.
As a user, create a post with an embed with a non-URL (`{% embed @msarit/Shell-Challenge %}`) or an invalid URL (`{% embed https://replit.com/msarit/Shell-Challenge %}`). An error message should appear, and the post …

Raise Error with Invalid UnifiedEmbed URL

---

app/services/broadcasts/welcome_notification/generator.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb

The original flow aborted all processing when any
ActiveRecord::RecordNotFound exception was raised. This causes a
situation where a missing broadcast message (by title) causes that
notification message to fail, and each day the same failure to
occur (since it wasn't successfully sent the day before), blocking all
further messages.
We want these to proceed on the schedule implicit in the checks, and
failing early prevents that.
Modify the error handling to catch RecordNotFound on each message, and
continue throught the checks until a notification is enqueued or all
checks have been attempted.
partial fix for https://github.com/forem/forem/issues/16059 (there's a data update script to create a broadcast needed as well).
Set the user's created_at time to 6 days ago. Clear the user's …

Modify welcome notification generator to handle errors per-message

---

db/seeds.rb
lib/data_update_scripts/20220111192031_insert_apple_connect_broadcast_message.rb
spec/lib/data_update_scripts/insert_apple_connect_broadcast_message_spec.rb

We expect there to be a Broadcast with title "Welcome Notification: apple_connect", but no such item exists.
fixes #16059 (in conjunction with #16060)
Run the data update script. A broadcast should be created.
Run it again, nothing should happen.
None

Add apple_connect welcome notification broadcast

---

app/workers/broadcasts/send_welcome_notifications_worker.rb

The download app broadcast (in the Generator) returns early if the
user was [created since 7 days ago](https://github.com/forem/forem/blob/main/app/services/broadcasts/welcome_notification/generator.rb#L79). It seems counterproductive to
select _only_ users created in the last 7 days here before calling the generator.
Add one day to the query range, so users created less than 8 days ago,
but more than 7 days ago, receive the final message.
Clean up the comments (the original intent, to not send more than one message per day, is handled elsewhere, but the setting is required and the logic is still valid, either live at or the trailing 8 days will be used).
https://github.com/forem/forem/pull/16052#discussion_r782413219 
Set user created at to 7 days ago.
Clear user notifications.
Run this …

Add one day to the welcome notification users range

---

app/services/broadcasts/welcome_notification/generator.rb

ActiveSupport adds DateAndTime::Calculations#after? (and before?) -
which clarifies intent (users newer than the relative time are
skipped) of the early returns.
No changes expected.
None

Prefer #after? to numeric time comparisons

---

config/initializers/new_framework_defaults_6_1.rb

In my ongoing quest to bring us closer to current Rails defaults, this PR enables some new 6.1 defaults that seem safe in the context of our application. All the ones that are marked as backward-incompatible are still disabled.

Enable safe Rails 6.1 defaults

---

config/application.rb

Rails 5.2 added AR collection cache versioning and 6.0 added collection cache versioning. We haven't used this option so far but now that we're slowly moving to newer framework defaults (see [recent PR](https://github.com/forem/forem/pull/15988)) I'd like to turn it on. 
Detailed writeup: https://www.bigbinary.com/blog/rails-adds-support-for-recyclable-cache-keys
I believe deploying this may result in cache misses at first but I think there's enough long-term benefit to be ok with this.
No UI changes

Enable AR cache versioning

---

config/application.rb

This PR is part of my ongoing effort to bring us closer to modern Rails defaults. It removes a setting that specifically targets older versions of IE:
```ruby
config.action_view.default_enforce_utf8 = true
```
Given that our codebase generally assumes quite modern browsers, it seems safe to remove this now.

Remove IE-specific setting

---

config/application.rb
config/environments/production.rb
config/environments/test.rb

In `config/application.rb` we generally only load the railties for frameworks we actually use. However, we were still loading the one for `ActiveJob`, even though we use Sidekiq directly. This PR changes that.

Don't load ActiveJob railtie

---

app/services/broadcasts/welcome_notification/generator.rb

Currently we have `:apple` as a restricted provider (you can enable it in admin,
but it's treated as beta here for checking user setup).
While we were correctly checking if you had all GA providers enabled
in `authenticated_with_all_providers?`, we were incorrectly pulling
all enabled provider names in `find_auth_broadcast` (the message to send
the user), and picking `apple_connect`.
Since it doesn't make sense to omit apple id login from consideration
when checking if all available auth methods are used, then recommend
that it be used consistently, capture this "GA" state as a method, and
use it both in the test "does this user have all available identity
providers enabled?" and the selection "which identity provider can I
suggest they setup?" consistently.
Alternately, define "GA" to …

Allow admin control of auth broadcast messages (was: Don't suggest apple authentication)

---

app/liquid_tags/comment_tag.rb
spec/liquid_tags/comment_tag_spec.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Forem comment embeds.
closes https://github.com/forem/forem/issues/15555
- As a user, grab the URLs of some comments. Create a Forem Comment liquid tag using this format: `{% embed <forem-comment-url> %}`. The Comment Liquid Tag should render properly.
- Also create Forem Comment liquid tag using the old method: `{% comment <forem-comment-idcode> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present documentation is still valid. Plus, I will avoid updating the docs piecemeal, and risk confusing users.
None

Implement Forem Comment Unified Embed

---

app/decorators/application_decorator.rb
spec/decorators/application_decorator_spec.rb

Without this method, the `@object` will handle the `decorate` message;
which will go through the logic of determining the decorator class, and
isntantiating a new decorator.
Related to but orthogonal to #16078.
None.
None.
not: This is a minor refactor that doesn't really change the
functional behavior.

Adding a convenience/optimiization method.

---

app/controllers/stories/feeds_controller.rb

This is a minimal adjustment that will affect the functionality of all feed results — I'm curious to a/b test the precise number in the future, but for now consider this a really safe improvement on what we're currently seeing.
The current algorithm creates an `order` for making the initial query, ultimately does not return the results in the order of total compiled order from the prior step.
```ruby
Article.where(
Article.arel_table[:id].in(
Arel.sql(
Article.sanitize_sql(unsanitized_sub_sql),
),
),
).limited_column_select.includes(top_comments: :user)
```
The ultimate query has no order clause, it just takes articles with ids from the `Article.sanitize_sql(unsanitized_sub_sql)` but doesn't order them by their original fetch.
I'm not entirely sure whether this is _intentional_, but I'll …

[feed] Change weighted query limit from 50 (default) to 25

---

spec/models/html_variant_spec.rb

In Travis I found the following message:
> Using `should` from rspec-expectations' old `:should` syntax without
> explicitly enabling the syntax is deprecated. Use the new `:expect`
> syntax or explicitly enable `:should` with
> `config.expect_with(:rspec) > { |c| c.syntax = :should }`
> instead. Called from
> /home/travis/build/forem/forem/spec/models/html_variant_spec.rb:76:in
> `block (2 levels) in <main>'.
None.
None.
None.

Moving from 'should' syntax to 'expect'

---

app/javascript/actionsPanel/actionsPanel.js
cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js

Prior to this PR, there was no feedback to a user if required fields were not filled out. Now, the HTML validation that was present now runs when the form is submitted.
Closes #16050
There are other scenarios other than the two below, but the main fix is displaying the HTML validation error when the reason for tag adjustment text field is not filled out.
1. Log in as the default Forem admin account
email: admin@forem.local
password: password
2. Navigate to any article
3. Click on the shield icon in the sidebar of the article (bottom bar if on mobile)
**Large screen**
**Small screen**
4. The moderation tools panel opens
5. Click on the Adjust tags section to open the tag panel.
1. Click the Submit button.
2. The form does not submit and the user is notified why.
1. Add or remove a tag. …

Now HTML validation works for the adjust tags section of the moderation tools panel

---

app/models/article.rb
app/views/articles/_single_story.html.erb
spec/models/article_spec.rb
spec/models/articles/cached_entity_spec.rb

There's a few things going on:
1. I introduced [a change][1].
2. There was a [data script][2] that should've completed successfully, but
some data was not converted (see [Blazer query on DEV.to][3])
Thus the current state of the data means that we have have serialized
data in an `OpenStruct` format and `Articles::CachedEntity` format.
This patch should work because the OpenStruct should previously have an
`image_profile_90` attribute.
In addition, I have added some recommendations and tests to better
describe what's happening.
[1]:https://github.com/forem/forem/blob/9780dba3807e53e01c4999b863d4d8392d1b8d63/app/models/articles/cached_entity.rb#L4
[2]:https://github.com/forem/forem/blob/9780dba3807e53e01c4999b863d4d8392d1b8d63/lib/data_update_scripts/20200723070918_update_articles_cached_ent …

Replacing custom call with existing cached method

---

config/application.rb

More cleanup of our `config/application.rb`:
1. We enabled the Rails 6.0 defaults so we can remove the explicit enabling of Zeitwerk as autoloader
2. We were explicitly requiring files from `app/middlewares`. However, we don't even have this directory anymore, the files are now in `app/lib/middlewares` and are correctly autoloaded anyway.

Remove explicit Zeitwerk config, require hack

---

config/application.rb

Rails 6 added a handy `config.use_cookies_with_metadata` option which provides some added security by preventing user's from using one cookie's values in a different cookie.
More details: [Rails 6 adds Purpose Metadata to Cookies](https://blog.saeloun.com/2019/11/12/rails-6-adds-purpose-metadata-to-cookies.html)
As the linked article states
> Cookies previously set without this metadata will continue to be honored.
which means this option should be safe to enable. However, in case SRE wants to test this separately on a Canary first I made a separate PR for this change instead of making it part of #16086.

Enable use_cookies_with_metadata option

---

app/models/settings/user_experience.rb
app/views/admin/settings/forms/_user_experience.html.erb
spec/requests/admin/configs_spec.rb

This changes two text fields in the config section of the admin panel to dropdowns. The text fields required specific inputs, so instead of leaving room for invalid entries, typos, etc. we decided to change it to dropdowns.
I did an audit of other text fields but couldn't find any additional ones that had static options.
https://github.com/forem/rfcs/issues/286
1. Go to the User Experience section of [/admin/customization/config](http://localhost:3000/admin/customization/config)
2. Try to update the feed strategy, feed style, default font, and default locale dropdowns
3. See that the values persisted
Nope, using native `<select>` tag should make a11y better.
No

Convert admin/config text fields with static options to dropdowns

---

app/views/articles/_actions.html.erb
app/views/articles/_reaction_button.html.erb
app/views/articles/_sidebar.html.erb
app/views/articles/_single_story.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/articles/_v2_form.html.erb

This PR applies the [recently added](https://github.com/forem/forem/pull/15878) `crayons_icon_tag` helper to article-related views.
https://github.com/forem/forem/pull/15878
Nothing specific, no behavior changed
No UI changes

Use crayons_icon_tag for article views

---

app/helpers/crayons_helper.rb
app/views/articles/_actions.html.erb
app/views/organizations/_header.html.erb
app/views/users/_main_feed.html.erb
app/views/users/_sidebar.html.erb
app/views/users/show.html.erb
spec/helpers/crayons_helper_spec.rb

This PR refactors `crayons_icon_tag` so we no longer need the dedicated `css_class` keyword argument but instead pass through `class` from `**opts` to `inline_svg_tag`. It also updates all existing usages of the helper.
Updated documetation (mention `class`, add new example):
No UI changes

Update crayons_icon_tag helper

---

app/services/articles/feeds/weighted_query_strategy.rb

A prior iteration on the feed disabled this scoring factor config under this pretense:
> Disable a few levers that did little. There really aren't any articles.featured = true articles in the database.
Yes, there are relatively few featured articles (28k total which is _relatively_ few)
Featured has been consistently used as an option for admins to _bump_ any posts within the algorithm. It's not as powerful as pinning, and will still not beat out other ranking factors (appropriate weight is subject to further experimentation), but it is a lever to gently promote content which the _admin_ considers to be valuable to the community.
It is accessible via admin section, but we have not made instructions on how to use it clear. Through the lens of DEV, this adjustment will be paired with finer …

Turn featured back on as query scoring weight

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/decorators/article_decorator.rb
app/decorators/notification_decorator.rb
app/helpers/application_helper.rb
app/models/application_record.rb
app/models/tag.rb
app/models/users/deleted_user.rb
app/view_objects/data_info.rb
app/views/articles/_single_story.html.erb
app/views/organizations/_header.html.erb
app/views/podcast_episodes/index.html.erb
app/views/podcast_episodes/show.html.erb
app/views/stories/tagged_articles/index.html.erb
app/views/tags/index.html.erb
app/views/users/show.html.erb
db/seeds.rb
spec/decorators/application_decorator_spec.rb
spec/decorators/article_decorator_spec.rb
spec/decorators/notification_decorator_spec.rb
spec/factories/users.rb
spec/models/application_record_spec.rb
spec/models/tag_spec.rb
spec/models/users/deleted_user_spec.rb
spec/support/seeds/seeds_e2e.rb
spec/view_objects/data_info_spec.rb

**This is a third attempt.  I'm pushing it up to see if anything's substantively changed.  I assume that there are broken specs and want to see what to address.**
Prior to this commit, we were somewhat naively rendering Hash style data
attributes in our ERB templates.  By rendering each hash attribute
separately, we were rendering characters that could break the
javascript (e.g. double hack or backslash `"` or `\`).
By moving to this view_object rendering, we leverage Rails's `to_json`
behavior to ensure properly escaped values.  As part of this exercise, I
generalized the method to allow for other places to benefit from this
behavior.
This generalization also helps ensure that we have a more conformant
rendering (e.g. we should always have an :id, :className, and :name
value in our …

Patching ERB rendering of the data-info JSON

---

app/liquid_tags/dotnet_fiddle_tag.rb
app/liquid_tags/youtube_tag.rb
spec/liquid_tags/unified_embed/registry_spec.rb
spec/liquid_tags/youtube_tag_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for DotNetFiddle embeds.
closes https://github.com/forem/forem/issues/15556
Example DotNetFiddle URLs:
https://dotnetfiddle.net/PmoDip
https://dotnetfiddle.net/Widget/PmoDip
- As a user, create a DotNet Fiddle liquid tag using this format: `{% embed <dotnetfiddle-url> %}`. The Liquid Tag should render properly.
- Also create DotNet Fiddle liquid tag using the old method: `{% dotnetfiddle <dotnetfiddle-url> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present documentation is still valid. Plus, I will avoid …

Implement DotNetFiddle Unified Embed

---

app/models/user.rb
db/seeds.rb

This change restores setting usernames to something less obnoxious.
Prior to this commit, I would on occassion get the following error in
seeds:
```shell
❯ bin/rails db:seed
Seeding with multiplication factor: 1
1. Creating Organizations.
2. Creating 10 Users.
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Username is too long (maximum is 30 characters)
./forem/db/seeds.rb:67:in `block (2 levels) in <main>'
./forem/db/seeds.rb:60:in `times'
./forem/db/seeds.rb:60:in `block in <main>'
./forem/app/lib/seeder.rb:30:in `create_if_none'
./forem/db/seeds.rb:57:in `<main>'
<internal:~/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:~/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in …
```

Ensuring less obnoxious usernames

---

app/liquid_tags/organization_tag.rb

Prior to this commit, I was seeing a "warning: nested repeat operator
'+' and '?' was replaced with '*' in regular expression"
```shell
> bundle exec rspec spec/liquid_tags/organization_tag_spec.rb
./app/liquid_tags/organization_tag.rb:5: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
[Zonebie] Setting timezone: ZONEBIE_TZ="Dublin"
...
Finished in 0.39363 seconds (files took 2.89 seconds to load)
3 examples, 0 failures
```
After this change, when I run the same spec I get the following:
```shell
❯ bundle exec rspec spec/liquid_tags/organization_tag_spec.rb
[Zonebie] Setting timezone: ZONEBIE_TZ="Saskatchewan"
...
Finished in 0.39327 seconds (files took 3.03 seconds to load)
3 examples, 0 failures
```
The warning is gone.
Originally, I had changed …

Fixing regex warning and removing unneeded groups

---

app/policies/user_policy.rb
app/services/authentication/authenticator.rb
spec/policies/user_policy_spec.rb
spec/services/authentication/authenticator_spec.rb

When we `banish` accounts, it's because they were marked as spam. We don't want to allow them to update their profiles after being banished, so this PR adds that (back?) in.
https://github.com/forem/internalCommunity/issues/127
1. Suspend yourself: `User.find(your_id).add_role :suspended`
2. Go to [/settings](http://localhost:3000/settings)
3. Try to update a field
4. Run into an error
I don't think QAing the login part is worth the effort because I think the tests cover it.
No, backend change
Nope

Prevent banished users from updating their profiles

---

app/models/article.rb
app/services/articles/feeds/large_forem_experimental.rb
app/services/articles/suggest.rb
app/services/articles/suggest_stickies.rb
app/services/badges/award_tag.rb
app/services/email_digest_article_collector.rb
app/services/users/suggest_for_sidebar.rb

In my quest to find `where(attribute: value)` in controllers and even
services, I stumbled upon this pattern.
As of this commit (and prior) an Article's associated user is it's author.
None.
None.
None.

Extracting a not_authored_by scope

---

app/controllers/stories/feeds_controller.rb
app/models/ab_experiment.rb
app/services/articles/feeds/weighted_query_strategy.rb
config/field_test.yml
spec/models/ab_experiment_spec.rb

We have achieved success in figuring out what an initial relevancy query looks like to surface 25 relevant posts to a feed — but we are presenting these results in no particular order. The hypothesis here is that the lowest hanging fruit for a better overall experience is providing a final order that takes these 25 results and re-orders them in the most effective way to float the most useful posts to the top. The way the algorithm is constructed gives us this area for "final ordering" which can be done with different feedback in mind compared to the initial global ordering query.
Given that this is a new final step, we'll test a variety of options and learn as much as we can. The incumbent gets 51% of the results and leaves room for a variety of challengers.
This test will make the …

Feed experiment 4: Final order

---

app/controllers/admin/settings/mandatory_settings_controller.rb
app/controllers/users_controller.rb
app/models/settings/base.rb
app/services/articles/feeds/weighted_query_strategy.rb
app/services/images/optimizer.rb
app/services/settings/upsert.rb

```shell
❯ bundle exec rubocop -A
Inspecting 1856 files
Offenses:
app/controllers/admin/settings/mandatory_settings_controller.rb:17:57: C: [Corrected] Rails/CompactBlank: Use compact_blank instead.
settings_model.public_send("#{key}=", value.reject(&:blank?)) if value.present?
^^^^^^^^^^^^^^^^
app/controllers/users_controller.rb:66:58: C: [Corrected] Rails/CompactBlank: Use compact_blank instead.
Honeycomb.add_field("error", @user.errors.messages.reject { |_, v| v.empty? })
^^^^^^^^^^^^^^^^^^^^^^^^^^
app/controllers/users_controller.rb:280:58: C: [Corrected] Rails/CompactBlank: Use compact_blank instead.
Honeycomb.add_field("error", @user.errors.messages.reject { |_, v| v.empty? })
^^^^^^^^^^^^^^^^^^^^^^^^^^
app/models/settings/base.rb:111:54: C: [Corrected] Rails/CompactBlank: Use …
```

Addressing rubocop violations

---

app/policies/authorizer.rb
lib/tasks/add_navigation_links.rake

This commit provides a possible solution for preventing the re-creation
of a navigation link deleted by a Forem creator.
What I need is a discussion around the life-cycle of the application
installation and updates.
In particular, does this provide a robust enough mechanism for resolving
the issue at hand?
_Note: it pains me to ask about a user's role, but this is provided as a
point of discussion and possible implementationi to address the
underlying issue.  But I'm referencing a constant in the Rake task so
hopefully that will help future refactors.  Also, it's one reason I
needed to remove the `private_constant` declaration._
If we accept this code change, a future task is to document the ENV and
behavior.
- How might we refine this to not be as "role" reliant?
- Could we have a …

Allow for skipping navigation link creation

---

app/services/search/tag.rb

We are loading the badge for each included tag in the
Search::TagSerializer and seeing warnings from bullet
```
Bullet::Notification::UnoptimizedQueryError:
GET /search/tags?name=ta
USE eager loading detected
Tag => [:badge]
Add to your query: .includes([:badge])
Call stack
/home/travis/build/forem/forem/app/serializers/search/tag_serializer.rb:5:in `block in <class:TagSerializer>'
/home/travis/build/forem/forem/app/services/search/tag.rb:11:in `serialize'
/home/travis/build/forem/forem/app/services/search/tag.rb:7:in `search_documents'
/home/travis/build/forem/forem/app/controllers/search_controller.rb:54:in `tags'
/home/travis/build/forem/forem/app/lib/middlewares/set_time_zone.rb:10:in `call'
```
Follow the advice, now when multiple tags are in the result set,
having multiple badges, …

Include badge before serializing tags

---

app/services/users/profile_image_generator.rb

I noticed that the constant `BACKGROUND_HEXES` in `Users::ProfileImageGenerator` seems to be unused:
```
❯ rg BACKGROUND_HEXES
app/services/users/profile_image_generator.rb
19:    BACKGROUND_HEXES = %w[#f68d8e #fce289 #f3f096 #55c1ae #88aedc #f8b4d0].freeze
```
This PR removes it.
No behavior changed
None

Remove unused Users::ProfileImageGenerator::BACKGROUND_HEXES

---

app/controllers/liquid_embeds_controller.rb
app/views/liquid_embeds/show.html.erb
spec/requests/liquid_embeds_spec.rb

While tracking down an exception that came through, I noticed we were doing some work inside a template that made more sense in the controller.
This is technically slightly semantically different in that an error in `@liquid_node.render` would previously have returned a 404 and this turns that into a 500. Arguably, the behavior of this PR is more correct. An error in rendering the Liquid template that it did find seems like it shouldn't return a "Not Found" error since it's an internal logic error. All other behavior should be identical.
When reviewing, it might help to remove whitespace-only changes. This will highlight that only the `@liquid_node.render` call stayed in the template. I simply unindented it since it was no longer inside a `begin` block.
_Will this PR introduce a change …

Move work from template to controller

---

app/liquid_tags/codepen_tag.rb
app/views/pages/_editor_guide_text.html.erb
app/views/pages/_editor_liquid_help.html.erb
spec/liquid_tags/codepen_tag_spec.rb

Adds the following options to codepen liquid tag embeds:
1) allow /pen/preview/ paths (which become /embed/preview/) For #12130 
2) allow height param for #5346
3) allow theme-id for codepen pro users (this is the thing I wanted, just decided to take care of the rest while I was in there)
4) and for the sake of completion, add the last embed option codepen has too: editable=true (also for codepen pro users)
#12130
#5346
Several unit tests are included
N/A
Celebration and joy
https://i.imgur.com/0JE4B1J.mp4

Finishes adding all the codepen embed options available

---

app/services/articles/enrich_image_attributes.rb

There has been a lot of harmless noise caused by the FastImage gem. 
We're getting a lot of `FastImage::CannotParseImage` errors on Datadog and that shouldn't happen because FastImage gem silences them by default. This is my attempt at silencing this error.
n/a
n/a
n/a

Explicitly silence FastImage exceptions

---

app/controllers/feedback_messages_controller.rb
app/views/admin/feedback_messages/_feedback_message.html.erb
app/views/admin/feedback_messages/_style.html.erb
spec/system/feedback_message_spec.rb

When deprecating connect chat (and removing it) from the app, the handling of abuse feedback reporting was left in place (displaying created feedback from a chat channel is independent of using the chat).
Remove the special casing of these messages by type. 
- In the controller, no need to special case this when checking rate limiting (they won't happen any more).
- In the view, the connect feedback had a badge (removed) and some special case handling because these messages had both a reporter and an offender (rather than a reporter and a reported url, as abuse reports do). Change the view to check for offender presence instead of connect type, which should permit us handling other two-party reports correctly in the future (if that happens).
In DEV's db, there is a single (resolved) …

Remove "connect" feedback message special treatment

---

spec/requests/stories_index_spec.rb

In #15680 we disabled some stories specs because of possible interactions with the new feed strategy we were testing at this time. However, it seems both of these specs pass now so it seems like a good idea to reenable them.
#15680

Re-enable stories specs

---

app/liquid_tags/tweet_tag.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Tweet embeds (not to be confused with TwitterTimeline embeds).
closes https://github.com/forem/forem/issues/15581
Example Tweet URLs:
https://twitter.com/aritdeveloper/status/1483614684884484099
https://twitter.com/aritdeveloper/status/1483775972688240643
Example Tweet IDs
1483614684884484099
1483775972688240643
- As a user, create a Tweet liquid tag using this format: `{% embed <tweet-url> %}`. The Liquid Tag should render properly.
- Also create Tweet liquid tag using the old methods: `{% tweet <tweet-id> %}` and `{% twitter <tweet-id> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag …

Implement Unified Embed for Tweet URLs

---

app/views/admin/settings/forms/_onboarding.html.erb

During the removal of the "Get Started" section, the "Suggested Tags" field was removed from the config. This PR fixes this by rehoming the `suggested_tags` field to the "Onboarding" section in the config now. 
Relates to PR #16033 
To QA this PR, please do the following:
- Navigate to `/admin/customization/config`, specifically to the "Onboarding" section and ensure that the "Suggested Tags" field shows as expected:
- To test this field, ensure that you are able to add `suggested_tags` and that the field updates as expected (_heads up:_ you may encounter a misleading error when you click the "Update Settings" button, which is unrelated to this change and happens when there is no "Onboarding Image" set, this may need to be addressed in a separate PR!):
- Finally, navigate to `/onboarding` …

Add suggested_tags to "Onboarding" Section in Config

---

app/controllers/admin/pages_controller.rb
app/models/page.rb
app/views/onboardings/show.html.erb
app/views/pages/code_of_conduct.html.erb
app/views/pages/terms.html.erb
lib/tasks/add_navigation_links.rake
spec/models/page_spec.rb

Prior to this commit any changes to the terms or code of conduct were
not reflected in the onboarding links.
With this commit, I'm leveraging a newly created method that first
checks if there's a page for the given slug.  If there is, use that
page's copy.
Closes #15296
To test:
- Overwrite default /terms page on a Forem
- Navigate to /onboarding or sign up as a new user
- Click on Terms of Use link text
- Review Terms of Use

Let override of ToS and CoC show in onboarding

---

app/javascript/leftSidebar/TagsFollowed.jsx

I have talked with @amywtlin about the expectations regarding the tags that one follows.  This is the lightest weight fix to align with expected behavior.
The fix might be a bit of a work-around for a more general approach, but we're fighting against the magic of the points vs. explicit_points tension as defined in the [Follows::UpdatePointsWorker][1].
That is to say, it's possible (and happens) where I have assigned an `explicit_points` of 1 for a tag, but the calculated `points` are less than 1.  The calculated `points` are what we send forward in the [AsyncInfoController][1] (by way of the [UserDecorator#cached_followed_tags][3] method).
In DEV, I ran the following queries:
**User assigned points `>= 1` but calculated `< 1`**
985,352 records
```sql
SELECT count(id)
FROM follows
WHERE …
```

Expanding the range of followed tags we show

---

app/controllers/concerns/listings_toolkit.rb
app/services/listings/create.rb
spec/services/listings/create_spec.rb

We have a pretty convoluted controller concern called `ListingsToolkit` which is used in 3 different controllers:
* `ListingsController`
* `Admin::ListingsController`
* `Api::V0::ListingsController`
It has several problems, including 
* calling methods that are not defined inside that concern but only exist in the including controllers,
* lots of implicit state in instance variables
If we ever want to extract listings into a plugin as previously discussed we probably should get this code into better shape first. This is a cautious first step, extracting one step of the process into a service. I think I also discovered a bug in the process, see inline comments.
I'm not 100% happy with this service yet, but I think it will do for now. I want to extract functionality from `ListingsToolkit` …

ListingsToolkit refactoring

---

app/models/tag.rb
lib/data_update_scripts/20220121114445_stripping_html_tags_from_tag_short_summary.rb
spec/lib/data_update_scripts/stripping_html_tags_from_tag_short_summary_spec.rb
spec/models/tag_spec.rb

On the DEV.to database, I ran the following SQL:
```sql
SELECT name, short_summary FROM tags WHERE short_summary LIKE '%<%';
```
There were three tags with a `<` in them:
- changelog
- cnc2018
- javascript
This PR will tidy up our short summary as part of saving a tag.  It will
also tidy up the existing tags.
Related to internal conversations.
Umm...create a tag in the UI, adding HTML tags to that tag.  Then save it and see that there's no HTML tag.
Nope.

Stripping tags from "tags.short_summary" column

---

app/models/settings/base.rb
spec/models/settings/base_spec.rb

Sparked by a [discussion in a recent PR](https://github.com/forem/forem/pull/16216#discussion_r789306433) I decided to add a `to_h` method to our `Settings::Base` model which will return all the settings as a hash. I remember wanting something similar several times, i.e. to get a quick overview of my local settings, which can get a bit hard to read with something like `Settings::Model.all`. It also makes it easier to extract subsets of settings where we need that, e.g. by using `Hash#slice` or `Hash#except`.
Note: I was also briefly toying with the idea of making our settings classes themselves `Enumerable` as that's very easy now. But looking through the codebase it seems like we don't actually have any places where this would be useful so I'm shelving this idea for now but may revisit …

Add `Settings::Base.to_h`

---

app/controllers/users_controller.rb
spec/requests/users_onboarding_spec.rb

Every onboarding page, except the "build your profile" page which asks for a username, is receiving a 422 response (because we're validating a non-empty username, but it's only sent in one of the pages). 
Every onboarding page is setting saw_onboarding to true, but we should only disable onboarding _if_ the user has accepted the code of conduct (logged via onboarding checkbox update). 
related to investigation into https://github.com/forem/forem/issues/14483 (but does not solve that).
When onboarding, you shouldn't get a 422 from the onboarding_update endpoint.
On main these are happening on every page except the profile page.
None
will …

Onboarding "improvements"

---

app/liquid_tags/jsitor_tag.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Jsitor embeds.
closes https://github.com/forem/forem/issues/15561
Example Jsitor URL: https://jsitor.com/embed/B7FQ5tHbY
Example Jsitor ID: B7FQ5tHbY
- As a user, create a Jsitor liquid tag using this format: `{% embed <jsitor-url> %}`. The Liquid Tag should render properly.
- Also create Jsitor liquid tag using the old method: `{% jsitor <jsitor-id> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present documentation is still valid. Plus, I will avoid updating the docs piecemeal, and risk confusing users.
None

Implement Unified Embeds for Jsitor URLs

---

app/assets/stylesheets/base/main.scss
app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/ctas.scss
app/assets/stylesheets/components/links.scss

We use `:focus-visible` pseudo class in few places for a11y purposes. However it doesn't work in Safari so we've been also using polyfill for that. So we've been using a combination of polyfill and native browser's functionality. It was causing a lot of repetition and redundant code so the idea is to use **only** polyfill for now (which will work in every browser anyway) at least until Safari add proper support. 
This shouldn't cause any UI changes.
No.
No.
No.

Simplify implementation of :focus-visible

---

app/models/notification.rb
app/services/notifications/new_follower/follow_data.rb
app/services/notifications/new_follower/send.rb
app/services/notifications/reactions/reaction_data.rb
app/services/notifications/reactions/send.rb
spec/services/notifications/new_follower/follow_data_spec.rb
spec/services/notifications/reactions/reaction_data_spec.rb
spec/services/notifications/reactions/send_spec.rb

Adding lightweight structure .coerce methods
I saw the following error in Honeybadger:
```
[PROJECT_ROOT]/app/services/notifications/reactions/send.rb:61 :in `call`
old_json_data = notification.json_data
previous_siblings_size = notification.json_data["reaction"]["aggregated_siblings"].size if old_json_data
notification.json_data = json_data
[PROJECT_ROOT]/app/services/notifications/reactions/send.rb:20 :in `call`
[PROJECT_ROOT]/app/workers/notifications/new_reaction_worker.rb:16 :in `perform`
[PROJECT_ROOT]/app/models/notification.rb:84 :in `send_reaction_notification_without_delay`
[PROJECT_ROOT]/app/controllers/reactions_controller.rb:136 :in `destroy_reaction`
[PROJECT_ROOT]/app/controllers/reactions_controller.rb:168 :in `handle_existing_reaction` …
```

Adding lightweight structure .coerce methods

---

app/liquid_tags/slideshare_tag.rb
app/views/liquids/_slideshare.html.erb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Slideshare embeds.
closes https://github.com/forem/forem/issues/15572
Example Slideshare URL: https://www.slideshare.net/slideshow/embed_code/key/9wjYHLKUR6nCZs
Example Slideshare key: 9wjYHLKUR6nCZs
- As a user, create a Slideshare liquid tag using this format: `{% embed <slideshare-url> %}`. The Liquid Tag should render properly.
- Also create Slideshare liquid tag using the old method: `{% slideshare <slideshare-key> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present documentation is still valid. Plus, I …

Implement Unified Embeds for Slideshare URLs

---

app/javascript/crayons/Modal/Modal.jsx

We recently added the inline-react-svg babel plugin and migrated icons in Preact components to use it. One was missed in the `<Modal />` component.
1. Ensure all frontend dependencies are installed by running `yarn`.
2. Start Storybook by running, `yarn storybook`
3. Navigate to http://localhost:6006/?path=/story/components-modals--default and click on the button to open a modal.
4. Notice the x icon is present and if clicked closes the modal.
N/A
[Changes …

Now the close X SVG icon is imported via the inline-react-svg plugin for the Modal component

---

app/assets/stylesheets/ltags/LiquidTags.scss
app/assets/stylesheets/ltags/SpeakerdeckTag.scss
app/liquid_tags/speakerdeck_tag.rb
app/views/liquids/_speakerdeck.html.erb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Speakerdeck embeds.
closes https://github.com/forem/forem/issues/15573
Example Speakerdeck URLs:
https://speakerdeck.com/player/4dd2e0725753084498000001
https://speakerdeck.com/player/87fa761026bf013092b722000a1d8877
Example Speakerdeck IDs:
4dd2e0725753084498000001
87fa761026bf013092b722000a1d8877
- As a user, create a Speakerdeck liquid tag using this format: `{% embed <speakerdeck-url> %}`. The Liquid Tag should render properly.
- Also create Speakerdeck liquid tag using the old method: `{% speakerdeck <speakerdeck-id> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the …

Implement Unified Embeds for Speakerdeck URLs

---

.github/workflows/rubocop.yml

**The problem (+ some history and context)**
* We use [Husky](https://typicode.github.io/husky/#/) for git pre-commit hooks in local development.
* We repeatedly had issues where the hooks didn't run for various reasons. This can become annoying for everyone else on the team as they will get unrelated warnings/errors in their next branch. We also regularly have minor PRs just fixing Rubocop errors, see [this list](https://github.com/forem/forem/pulls?q=is%3Apr+sort%3Aupdated-desc+rubocop+NOT+bump+in%3Atitle+).
* I tried to move our linting setup to GH actions before, using [super-linter](https://github.com/github/super-linter). Due to the complicated nature of our overall linting setup, I eventually gave up on the [PR](https://github.com/forem/forem/pull/13790).
* We already have use …

Request for Comments: Add Rubocop action

---

app/models/github_repo.rb
spec/models/github_repo_spec.rb

**tl;dr:**
This PR changes our `GithuRepo` model to use Sidekiq's recently added `push_bulk` method. If this works as expected we can then change similar code to use the same method.
**Full context:**
For a while now, Sidekiq had a [`push_bulk` method](https://www.rubydoc.info/github/mperham/sidekiq/Sidekiq%2FClient:push_bulk) which allows pushing large numbers of jobs to Sidekiq. The goal is to reduce Redis roundtrip latency by replacing N calls with 1. The recommended number of jobs to push was < 1000.
Sidekiq 6.3.0 added a higher-level wrapper around this, [`perform_bulk`](https://www.rubydoc.info/gems/sidekiq/Sidekiq%2FWorker%2FSetter:perform_bulk). This encodes the best practice of 1000 jobs per call though one can change that number via the `batch_size` argument.
**Further …

POC: use `Sidekiq.perform_bulk` for Github repos

---

lib/tasks/app_initializer.rake
lib/tasks/cache.rake

During `bin/setup` we display a message saying `== Bust caches ==` which has repeatedly led people to believe that their app cache would be cleared. However, this is not the case:
1. `== Bust Caches ==` is printed from `lib/tasks/app_initializer.rake`
2. This does indeed enqueue a job for clearing caches (`cache:enqueue_path_bust_workers`) so it assumes Sidekiq is running. In all fairness, it should be, we recommend running the app through `Procfile.dev` (e.g. with overmind or with `foreman start -f Procfile.dev, see `bin/startup`) which will start Sidekiq workers.
3. Looking at the tasks in `lib/tasks/cache.rake` you'll notice it calls `BustCachePathWorker`
4. This worker is __not__ about clearing the local Rails cache but the edge cache (it class the `EdgeCache::Bust` service.
To avoid …

Clear app cache during `bin/setup`

---

app/assets/stylesheets/components/tooltips.scss

This PR adds `pointer-events: none;` to tooltips which should prevent them from being accidentally activated with mouse cursor.
1. Spin up `yarn storybook` and go to `/?path=/story/components-buttons--with-tooltip`
2. While hovering the button try to quickly move the cursor to the tooltip. 
3. If you can't make it and tooltip disappear - this works! 👍
This should actually improve accessibility.
No.
It won't.

No pointer events on tooltips

---

app/assets/stylesheets/base/reset.scss
app/assets/stylesheets/components/buttons.scss

There was a missing declaration for outline style on `input[type="number"]` so I've added it in another PR but @nickytonline suggested we could cover more cases.. So here it is.
- Where I initially added it: https://github.com/forem/forem/pull/16174/files#r791169784
Just review the code?
We're dropping native outline because Crayons provides its own outline.
No.
It won't.

Improve reset.css to cover all inputs

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/controllers/search_controller.rb
app/serializers/search/tag_serializer.rb
app/services/search/tag.rb
app/views/stories/articles_search/_nav_menu.html.erb
config/locales/views/misc/en.yml
spec/requests/search_spec.rb
spec/services/search/tag_spec.rb

Added "Tags" category to search results.
Though I added code for pagination, pagination for search results is not working (for both tags and other categories), the bug is described in #16297 by @jeremyf , and is out of the scope of this pr.
#15151 
1. Type something in the search bar and submit the form
2. There should be `Tags` link in the left navigation bar.
3. If you press `Tags` search results by tags should appear in the feed.
Should we communicate this change to the community? That's a relatively small improvement, but could be noticeable for some members, what do …

Added "Tags" category to search results

---

app/liquid_tags/stackery_tag.rb
app/views/liquids/_stackery.html.erb
spec/liquid_tags/stackery_tag_spec.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Stackery embeds.
closes https://github.com/forem/forem/issues/15577
Example Stackery URLs:
https://app.stackery.io/editor/design?owner=stackery&repo=quickstart-ruby&file=template.yaml
Example Stackery Input: deeheber lambda-layer-example master
- As a user, create a Stackery liquid tag using this format: `{% embed <stackery-url> %}`. The Liquid Tag should render properly.
- Also create Stackery liquid tag using the old method: `{% stackery <stackery-input> %}`. This should also work, as I am leaving the old implementation in place for now.
None
Considering the project as a whole, I shall update the Liquid Tag documentation at the end. Since I am not changing the current implementation, the present …

Implement Unified Embeds for Stackery URLs

---

app/services/podcasts/feed.rb

Prior to this commit, we fetched the podcasts that were the first(:limit)
XML `item` nodes in the RSS feed.  Some folks might choose to list those
in descending pubDate order, while others list in ascending pubDate
order.
Closes #3580
Existing tests will cover this.
tests.  The comments communicate what's going on.

Ensuring we fetch latest podcasts by pubDate

---

db/migrate/20220126205052_adding_indices_to_tag.rb
db/schema.rb

This is meant as a conversation.  Throughout the code-base we have have
`Tag.order(hotness_score: :desc)` and with PR #16322 we'll also have
`Tag.order(taggings_count: :desc)`.
My understanding is that if we have sorting, we might want to consider
an index.  I put this forward as a conversation with a possible quick win.
Related to #16322
None
None

Adding possibly missing indices

---

app/controllers/tags_controller.rb

The hotness score is an "opaque to our users" score, it reflects
"activity" on the tag.  However, by also showing the number of tags on
the associated view, there's a bit of a head scratcher when a "hotter"
tag with less tags is rendered ahead of a popular tag.
Closes #16321
None, our tests will cover if this 
None.

Favor tag sort by count over hotness

---

app/models/navigation_link.rb
lib/tasks/add_navigation_links.rake
spec/models/navigation_link_spec.rb

Prior to this commit, we were treating all NavigationLink attributes as
unique.  So, were we to change a position of one of the NavigationLinks
during the add_navigation_links rake task, we would have created a new
NavigationLink (and the only one would have remained).
With this commit, we're introducing the concept of the NavigationLink's
surrogate identity, that is to say if we have two NavigationLink objects
with the same `url` and `name` we should consider them the same
NavigationLink.  This allows us to update properties of those
NavigationLinks (via the rake task) without the risk of creating new
entries.
This unblocks PR #16268 which addresses #16076.
This further helps address some subtle edge cases in our navigation management.
None.

Create/update by NavigationLink identity

---

app/services/articles/feeds/weighted_query_strategy.rb

We only have 0..9 configured for cases to consider, so treat all "large"
numbers as 10, since it will follow the same path in the weighting.
Use least(value, ...) to cap this. See https://www.postgresql.org/docs/11/functions-conditional.html#FUNCTIONS-GREATEST-LEAST
The generated query in question looks like this
```sql
(CASE SUM(followed_tags.points)::integer
WHEN 0 THEN 0.7
WHEN 1 THEN 0.7303030303030302
WHEN 2 THEN 0.7606060606060605
WHEN 3 THEN 0.7909090909090909
WHEN 4 THEN 0.8212121212121212
WHEN 5 THEN 0.8515151515151514
WHEN 6 THEN 0.8818181818181818
WHEN 7 THEN 0.9121212121212121
WHEN 8 THEN 0.9424242424242424
WHEN 9 THEN 0.9727272727272727
ELSE 1.0 END) 
```
10 looks the same as any other large number in this situation
This branch changes the query component to the following …

Cap tag point sum to 10

---

app/views/admin/users/_email_tools.html.erb

This PR removes a redundant, un-styled "Verify Email Ownership" button from `/admin/users/#id`. 
Closes #15183 
N/A
appropriately.
N/A

Removes Redundant, Un-Styled "Verify Email Ownership" Button

---

app/services/podcasts/feed.rb

Since [the initial `perform_bulk` PoC](https://github.com/forem/forem/pull/16293/files) was successful, this PR updates the `Podcast::Feeds` service to also make use of it.
NOTE: I'm doing one PR per change so we can merge them at different times and monitor if we want.
n/a
Nothing specific. There is an existing spec that covers this (`spec/services/podcasts/feed_spec.rb:42`), it's still green.
No UI changes.

Use `peform_bulk` in `Podcasts::Feed`

---

app/workers/podcasts/enqueue_get_episodes_worker.rb

This is the 3rd PR for updating our code to use Sidekiq's relatively new `perform_bulk` feature.
NOTE: I'm doing one PR per change so we can merge them at different times and monitor if we want.
Previous PRs:
#16293
#16324 
n/a
Checked that this is covered by an existing spec (`spec/workers/podcasts/enqueue_get_episodes_worker_spec.rb:9`), which is still green.
No UI changes

Use `perform_bulk` in `Podcasts::EnqueueGetEpisodesWorker`

---

config/routes.rb
config/routes/admin.rb
config/routes/listing.rb
spec/requests/api/v0/organizations_spec.rb

The fundamental goal in this refactor is to make it easier to disable the
Listings feature set.  By extracting a routes file (via the `draw` method [see
implementation details][1]), we can more easily disable those routes _en
masse_.  This "crease in the code" could mean that we wouldn't need to update
the controller action logic.  An update of that logic might mean going into
each controller action related to listing and adding a conditional for render
404 when listing is disabled.
Now, on to why this should work (not I did not open the application and click
around, but instead went with a "let the framework help me" mindset).
I believe that this should work; though there's a caveat†.  Here's why I
believe this will work for extracting the listing routes:
Before making changes I ran the …

Extracting listing routes

---

config/environments/test.rb

For a long time, we had `config.cache_classes = true` set for the test environment.
The docs say that `cache_classes` should be set to `false` for the test env when Spring is enabled:
[Spring readme](https://github.com/rails/spring#enable-reloading)
[Rails guides](https://guides.rubyonrails.org/configuring.html#config-cache-classes)
There are situations when having it set to `true` causes problems. E.g. when trying to run specs when there are pending migrations on a test db (or running migrations on a test db explicitly in this case):
```
/home/light/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/spring-4.0.0/lib/spring/application.rb:101:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in …
```

Set config.cache_classes for test env depending on whether Spring is enabled

---

app/views/admin/profile_fields/_profile_field_form.html.erb
app/views/admin/sponsorships/new.html.erb
app/views/layouts/admin.html.erb

This PR does 3 things (tiny-enough that I decided to combine them):
1. It updates header's UI (less clunky, better crayons usage)
2. It removes Popper JS library and Bootstrap's Select. First hasn't been used, and the latter was replaced with classic select.
3. Added brand colors. 
Log in as admin and go to `/admin` - you should see slightly updated header and maybe some updated accent colors. Everything else should remain the same.
**Before:**
**After:**
No.
No.
It won't.

Admin layout update

---

config/environments/test.rb
spec/routing/all_routes_spec.rb

Prior to this commit, in test, we had two different answers to "what is
the host of this application?"  For Rails generates
URLs (e.g. `root_url`) we would get one answer.  For our custom
`URL.url("/")` we got another answer.
This resolves and patches that up.
Closes #16347, Related to forem/rfcs#291.
None.  The tests exercise this.  And the impact is limited to our test suite.
None.
is a change in our test suite that has minimal impact.

Ensuring that test's URL methods are similar

---

docker-compose.yml

https://github.com/forem/forem/issues/16225#issuecomment-1021459214 based on a discussion point made here after a contributor had difficulty running tests in docker.
This provides a test environment database for anyone using a docker
based development environment.
Expose, rather than bind, the db port (you won't be able to connect to
the db externally, only from the container).
Add tmpfs storage (this alleviates an issue seen with carrierwave
attachments when trying to write to the tmp directory in the image).
- Upgrade db versions from 11 to 13 (this is a breaking change for
anyone using this who had already provisioned the db, since no attempt
to upgrade has been provided, users may either downgrade to the
11-alpine image or recreate their storage volume). This is
separable (the `db` …

Add a minimal test database setup to the docker-compose file

---

lib/data_update_scripts/20220201114309_update_home_navigation_link_position.rb
lib/tasks/add_navigation_links.rake
spec/lib/data_update_scripts/update_home_navigation_link_position_spec.rb

The update in https://github.com/forem/forem/pull/16268 almost went smoothly, but unfortunately there was a logic error in my data update script, which:
- created the new home link
- incremented all links in the section by 2 (including that home link)
This resulted in the Home link appearing below the Reading List link in DEV, and will cause it to appear 2nd in every other Forem once it rolls out to the fleet.
It's my understanding that we can't simply revert that commit, as once a script is marked as "run", the deed is done. To fix the issue, I've instead added _another_ DUS to make sure the home link is placed at position 1. If we can merge this before the fleet deploys this should avoid the Home links appearing in the wrong place.
If there is a more elegant solution, just let me know! …

Fixes for home nav link positioning

---

app/liquid_tags/glitch_tag.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Glitch embeds.
closes https://github.com/forem/forem/issues/15559
Example Glitch URLs:
https://zircon-quixotic-attraction.glitch.me
https://glitch.com/edit/#!/zircon-quixotic-attraction
https://glitch.com/edit/#!/zircon-quixotic-attraction?path=index.html
Also test these Glitch URLs with the following options:
`app` inserts the `previewSize=100` param
`code` inserts the `previewSize=0` param
`no-files` inserts the `sidebarCollapsed=true` param
`preview-first` inserts the `previewFirst=true` param
`no-attribution` inserts the `attributionHidden=true` param
Note: `app` and `code` together cancel each other out because they do not make sense together
- As a user, create a Glitch liquid tag using this …

Implement Unified Embeds for Glitch URLs

---

app/helpers/application_helper.rb
app/views/layouts/_main_nav.html.erb
app/views/layouts/_sidebar_nav_link.html.erb
spec/helpers/application_helper_spec.rb

Prior to this commit we had an inline logic check on whether or not to
render a navigation link.  As we are looking to rollout the feature flag
for Listings, we needed to add another somewhat complex conditional.
This commit moves the inline conditionals to a helper function, which
makes testing the logic far easier.  Especially since we need to bombard
the tests with the combination of 3 different boolean checks.  (And one
of those boolean checks requires even more but could be stubbed).
Related to forem/rfcs#291
There should be no UI differences, as we're presently assuming the
Listings feature is enabled.
None.

Adding conditional rendering of navigation links

---

spec/liquid_tags/unified_embed/registry_spec.rb

In keeping with [MK's suggestion](https://github.com/forem/forem/pull/16378#discussion_r796251306), I am adding `aggregate_failures` metadata to single specs with more than one `expect`. 
None
Modified spec file should pass
None
None

Add "aggregate_failures" metadata to Registry Specs with loops

---

app/javascript/runtimeBanner/RuntimeBanner.jsx

The DEV Android app was decommissioned but we're unable to ship an updated build right now. So we're handling the Runtime Banner as the backup to try and migrate users to the Forem mobile app.
I'd recommend not trying to QA locally (somewhat tricky), I tested this by doing:
1. Boot DEV Android app locally and point to an ngrok endpoint (local forem running this branch)
2. Check the banner opens the Google Play Store when tapped
None - All UI elements used weren't modified
None

Avoid Intent redirect on Runtime Banner for the DEV Android app context

---

spec/models/article_spec.rb

While working on #15473 I started modifying `Article` specs related to the `published_at` field and found out that one of the specs (`"rejects future dates"`) wasn't serving its purpose.
What was actually happening:
An exception `Psych::DisallowedClass:  Tried to load unspecified class: Date` was raised while evaluating markdown:
https://github.com/forem/forem/blob/c1a60539b9b06298e4ea3d1e83291c5a1c7565d9/app/models/article.rb#L566
Then it was rescued later in the method and an error "Tried to load unspecified class: Date" was added to an article record instead of "must be entered in DD/MM/YYYY format with current or past date".
I added a check for the error message to the spec and changed the passed attributes:
- `FrontMatterParser::Parser` is unable to parse date in a `2022-02-03` …

Improved article date specs

---

app/components/admin/users/tools/reactions_component.html.erb
app/javascript/admin/controllers/reaction_controller.js
app/views/admin/feedback_messages/_abuse_reports.html.erb
app/views/admin/privileged_reactions/index.html.erb
app/views/admin/users/_negative_reactions.html.erb
app/views/notifications/shared/_comment_box.html.erb
config/locales/views/moderations/en.yml
config/locales/views/moderations/fr.yml
config/locales/views/reactions/en.yml
config/locales/views/reactions/fr.yml
cypress/integration/seededFlows/adminFlows/users/memberToolsSection.spec.js
spec/components/admin/users/tools/reactions_component_spec.rb

This PR updates any remaining uses of "vomit" in the UI to "flag". I'm pretty sure I've caught them all here, but the term "vomit" persists in our backend as the category for the reaction. I feel like at some point it would be worth refactoring some of the non-user-facing references to avoid any confusion, but definitely out of scope for this piece of work 🙂 
Fixes https://github.com/forem/forem/issues/15671
Changes are fairly straightforward, and relate mostly to the admin area. Have a click around and check that the term "vomit" no longer appears.
N/A …

Change UI instances of "vomit" to "flag"

---

app/assets/stylesheets/article-show.scss
app/javascript/utilities/animatedImageUtils.jsx

To follow up on the deploy of https://github.com/forem/forem/pull/16314, I checked in on @nickytonline's DEV posts as I know he uses gifs a lot 😄 
I noticed they were all aligning strangely to the right, and the cause of this was a `<center>` tag surrounding the gif not playing nicely with the CSS I used to center the freezeframe container.
Since we allow use of the `<center>` tag in posts, it makes sense to update the code to ensure gifs are positioned correctly regardless of whether a `<center>` tag has been used or not. 
This is the "before":
https://github.com/forem/forem/pull/16314
- Make sure you have the feature flag enabled: `FeatureFlag.enable(:detect_animated_images)`
- Try creating one post without a `center` tag, e.g.:
```
some text
```
- And one with a `center` tag, e.g.:
``` …
```

Place gifs correctly regardless of center tag

---

cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js

I noticed this spec was occasionally flaking in CI - I was able to reproduce it locally by throttling my network connection while the test was running... it's a bit strange because the test _does_ wait for the "top tags" to be fetched before checking they appear in the DOM, but it seems even so, it runs that little bit too fast and when the input is focused, the top tags haven't yet reached the autocomplete component via props.
It's not ideal, but it seems like the perfect use case for `cy.pipe`, so we now retry the focus event until the menu expands (there's still a default timeout on the assertion, so if it doesn't pass in a reasonable time frame we'll still get the test failure).
N/A
Just make sure the build goes green 😄 
N/A
_Will this PR introduce a change …

Fix flake in top tags test

---

spec/models/article_spec.rb

A follow-up pr for #16395, as preparation for #15858
- added a test for setting `published_at` from a frontmatter date
- moved `Article` tests from "dates" section to `published_at` section because they are related
#16395, #15858

Reorganized article published_at/dates specs

---

spec/models/article_spec.rb

Our tests expected the old format for edited_at on articles, but this has been changed after localizing.
This passed in the branch for #16124 because the last pre-merge commit was on a two digit
day (so the digit padding wasn't needed or expected, it checked `"Jan 30" ==
"Jan 30"` successfully, but today `"Feb 3" != "Feb  3"` and it fails) …

I18n's short format for times differs from "%b %e", update test

---

app/controllers/application_controller.rb
app/controllers/articles_controller.rb
app/controllers/listings_controller.rb
app/controllers/users/notification_settings_controller.rb
app/controllers/users/settings_controller.rb
app/controllers/users_controller.rb
app/errors/suspended_error.rb
app/views/pages/forbidden.html.erb
config/initializers/honeybadger.rb
spec/initializers/honeybadger_spec.rb
spec/requests/listings_spec.rb
spec/system/banned_user_interactions_spec.rb

Currently, a suspended user requesting certain pages will receive a 500 instead of a 403. This reduces the usefulness of aggregated data about site reliability. If it looks like we're getting 500s all over the place, it makes it so we can't really trust some of our dashboards and burns through SLOs faster than we would like.
Here's a sample of what our error logs look like:
The `SuspendedError` eclipses all other request errors _combined_. And since it's a 500, we can't (and shouldn't need to) filter it out. The purpose of this PR is to make this request failure a proper 4xx response. We aren't failing to handle it, but rather choosing not to based on client identity, so a 5xx is inappropriate.
- Create a banned user account
- In the Rails console, paste this code to create a suspended …

A suspended user returns 403 instead of 500

---

config/routes.rb
spec/routing/all_routes_spec.rb

This commit builds on the conditional rendering of navigation links by
adding a routing constraint to all :listing routes.
The impact is, if we were to disable the listing feature (e.g.,
`FeatureFlag.disable(:listing_feature_enabled)`) all requests to `GET
/listings` (and those drawn in the [config/routes/listings.rb][1] file)
would return a 404 response.
This commit is intended to be the penultimate change before we toggle
the listings section off by default.
[1]:https://github.com/forem/forem/blob/c2ce2c32d5bf768673a3b150642c125d97b462ef/config/routes/listing.rb#L1
Related to forem/rfcs#291, #16335, #16338, #16362.
Testing this change:
1. Start your local application (e.g. `$ bin/startup`)
2. Go to http://localhost:3000/listings
3. You should get a Successful response.
4. Now disable …

Scoping the :listing routes to feature

---

app/services/feature_flag.rb
spec/services/feature_flag_spec.rb

Prior to this commit, we had a single test for `FeatureFlag.enabled?`,
namely that it delegates to `Flipper.enabled?`.  This commit adds some
tests to both verify behavior and communicate to developers the
intentions of the related methods:
- `FeatureFlag.enabled?`
- `FeatureFlag.accessible?`
My hope is the documentation and tests will help address the horrors
mentioned in conversation in #16416:
> I have lived the horrors of having a feature flag accidently
> flipped or incorrectly setup in the first place and half baked
> functionality going live.
Note: I'm not proposing that we test other `Flipper` methods, but
instead to ensure that we're testing and documenting the behavior of
what I believe to be the two primary mechanisms of "putting something
behind a feature flag."
Related to …

Documenting and addl testing FeatureFlag.enabled?

---

app/liquid_tags/github_tag.rb
app/liquid_tags/github_tag/github_issue_tag.rb
app/liquid_tags/github_tag/github_readme_tag.rb
spec/liquid_tags/github_tag/github_issue_tag_spec.rb
spec/models/github_issue_spec.rb
spec/services/github/oauth_client_spec.rb
spec/support/fixtures/vcr_cassettes/github_client_comment.yml
spec/support/fixtures/vcr_cassettes/github_client_issue.yml
spec/support/fixtures/vcr_cassettes/github_client_issue_access_token.yml
spec/support/fixtures/vcr_cassettes/github_client_issue_not_found.yml
spec/support/fixtures/vcr_cassettes/github_client_pull_request.yml
spec/support/fixtures/vcr_cassettes/github_client_pull_request_comment.yml

This PR implements the [unified embed tag](https://github.com/forem/forem/issues/15099) for Github repository, issue, pull-request and comment embeds.
closes https://github.com/forem/forem/issues/15557
closes https://github.com/forem/forem/issues/15558
Example GitHub URLs:
```
https://github.com/forem/forem
https://github.com/forem/forem/issues/15099
https://github.com/forem/forem/pull/16415
https://github.com/forem/forem/pull/16378#issuecomment-1026386485
```
_(the following two URLs are not handled by GitHub's Issue-Comments API, so the embed should fall back to the PR)_
```
https://github.com/forem/forem/pull/16378#discussion_r796201397
https://github.com/forem/forem/pull/16378#pullrequestreview-869248370
```
Old Embed examples:
```
{% github forem/forem %}
{% github forem/forem …
```

Implement Unified Embeds for Github Repo, Issue, Pull-Request and Comment URLs

---

app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
app/views/onboardings/show.html.erb

Prior to this commit, if our community name included a `"` we would
encounter a parse error.  Using the [j][1] which is a terse alias for
[escape_javascript][2], we will now be escaping those characters that
cause grief in some of our parsings.
I believe there is a larger audit that needs to occur regarding all
`data-` renderings.
Hopefully this will catch a flakey test.
[1]:https://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-j
[2]:https://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-escape_javascript
Closes #16440
See if Travis breaks on these.
minimum, if community names include `"` they won't break.

Ensuring that body.dataset is JSON parsable

---

app/assets/javascripts/initializers/initNotifications.js
app/assets/javascripts/initializers/initializeArticleReactions.js
app/assets/javascripts/initializers/initializeBodyData.js
app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/views/admin/articles/_image_upload_script.html.erb
app/views/layouts/_top_bar.html.erb

The conditional assignment of `XMLHttpRequest` or `ActiveXObject('Microsoft.XMLHTTP')` before use supports IE5 and IE6 (IE7 and later included the XMLHttpRequest methods in the normal namespace).
We don't support IE5 or IE6 in a lot of other ways, does it seem necessary to continue this work-around pattern before using XHR?
Nothing should break (cypress and  rails js system tests are using chrome, which fully supports this api).
If someone had been using Internet Explorer 6 still, this will worsen their experience. I assume they have other broken experiences throughout the web already.
will share this change with the people who need to …

remove activex fallback for internet explorer

---

app/views/dashboards/_actions.html.erb
app/views/dashboards/_analytics.html.erb

Don't render listing items in the dashboard if the instance disabled the listing feature.
Relates to forem/rfcs#291, #16420, #16437, #16423, and #16416.
None.

Ensuring optionally rendering dashboard listings

---

cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js

Fixes a flaky E2E test for post moderation that is currently on the main branch.
N/A Fixing a flaky test only.
N/A Fixing a flaky test only, but it does ensure that an `aria-expanded` attribute is present and set to true when expanded.
appropriately. …

Fixed post moderation flaky test

---

app/assets/stylesheets/themes/dark.css

Adds `color-scheme: dark` to dark.css, in order to make browsers use dark versions of scrollbars.
dev.to on Chrome before:
dev.to on Chrome after:
As described by https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme:
> The color-scheme CSS property allows an element to indicate which color schemes it can comfortably be rendered in.
>
> Common choices for operating system color schemes are "light" and "dark", or "day mode" and "night mode". When a user selects one of these color schemes, the operating system makes adjustments to the user interface. This includes form controls, scrollbars, and the used values of CSS system colors.
Accessibility of dark theme improved — perceived contrast of scrollbar thumb vs scrollbar track is increased.

Add color-scheme: dark to dark.css

---

app/controllers/articles_controller.rb
spec/requests/articles/articles_destroy_spec.rb
spec/requests/articles/articles_spec.rb

Prior to this commit, the admin could delete the post but were blocked
by the "delete confirm".  The blocker was because we scoped the finding
of an article to the current user.
With this commit, the admin should be able to confirm the deletion of an
article.
Closes #16461
None.  The tests cover this behavior.
None.

Ensuring an admin can confirm delete a user's post

---

app/liquid_tags/liquid_tag_base.rb
app/services/markdown_processor/parser.rb
spec/liquid_tags/liquid_tag_base_spec.rb
spec/services/markdown_processor/parser_spec.rb

This is the least effort I can presently think of to allow for us to
reprocess user article's and handle the scenario in which the user may
have once had permission to the liquid tag but no longer.
This DI is not something I imagine using, but may highlight a better
approach for liquid tag permissions.
Related to #12146 and #16460
None.
None.

Allowing dependency injection for LiquidTag policy

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

As written in the comments, we're looking at making the smallest change
to deliver on the feature.  The other goal is to move from our
`user.admin?` paradigm towards leveraging Pundit policies.
If we need to move beyond Pundit, it will be easier once we've moved
all of our `user.something_something?` to policy questions.  And please
note, I don't know if we'll move past pundit.
See [Authorization System: use case 1-1 project][1] for details on the
project.
[1]:https://github.com/orgs/forem/projects/46/views/1
Closes #16483
None
None

Adding feature flag for Authorization 1-1

---

app/services/feature_flag.rb
spec/services/feature_flag_spec.rb

The discussion in https://github.com/forem/forem/pull/16416 unearthed that Flipper has a way to list all defined flags (`Flipper.features`) which we don't expose through our `FeatureFlag` wrapper module. This PR changes that by adding `FeatureFlag.all`.
Tests should be sufficient.

Add FeatureFlag.all

---

app/controllers/admin/users_controller.rb

This PR adds flash messages indicating a successful addition or removal of credits from a User via the Admin Member Detail View. Additionally, this PR removes a superfluous `credit_params` method from the `Admin::UsersController` and slightly adjusts the correct, remaining `credit_params` method in the `Admin::UsersController`.
Relates to PR #16174 
Closes #16525 
- Navigate to `/admin/users/:id` and add credits to the user. Observe that you are shown a flash message indicating that the addition of credits was a success:
- Navigate to `/admin/users/:id` and remove credits from the user. Observe that you are shown a flash message indicating that the removal of credits was a success:
Hopefully not, though we are addressing accessibility issues for the Admin Member Detail View separately. …

Display Flash Messages When Adding or Removing Credits via the Admin Member Detail View

---

app/views/admin/tags/_form.html.erb
app/views/tags/edit.html.erb
config/locales/views/tags/en.yml
config/locales/views/tags/fr.yml
spec/system/admin/admin_updates_tag_spec.rb
spec/system/tags/user_updates_a_tag_spec.rb

All this PR is doing is visually hiding the tag text color field and relabelling the tag background color label from `Bg color hex` to `Tag color`.  There is still work to be done to remove the tag.text_color field as well as renaming `tag.bg_color_hex` to `tag.color` but that will come in a subsequent PR.
Also, for a subsequent PR, but there is a new colour picker, which would need to be incorporated here at some point as well. This will probably tie into work that @aitchiss will be doing for updating the branding colour picker.
#16385
https://github.com/forem/rfcs/issues/297
https://github.com/forem/rfcs/issues/321
images for UI …

Now Bg color hex is labeled Tag Color

---

app/policies/admin_policy.rb
app/policies/application_policy.rb
app/policies/article_policy.rb
app/policies/comment_policy.rb
app/policies/discussion_lock_policy.rb
app/policies/html_variant_policy.rb
app/policies/response_template_policy.rb
app/policies/tag_policy.rb
app/policies/user_policy.rb

Our domain of "admin?" method names is already a bit confounding.  The
policy methods renamed the existing Policy::Authorizer methods, and
further obfuscated and confused intention.
This refactor aligns the policy methods with the Policy::Authorizer
methods.  It is a non-breaking change, but one that may add warnings in
the logs.  If you see those, resolve them per instructions.
Related to #16483
None.
None.

Renaming policy methods for consistency

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/base/typography.scss

A small cumulative layout shift was visible as the play/pause functionality for gifs loaded in. This was most noticeable when the gif appeared as the very first item in a post (but also to a smaller degree when within the main content).
This PR addresses the issue by making sure the new `.ff-container` element (inserted by the freezeframe library) receives all the same CSS styles as other images in posts.
Fixes https://github.com/forem/forem/issues/16535
I've found the easiest way to QA this is to:
- open two browser instances side by side
- in one of them, disable javascript (this prevents the play/pause functionality from loading in)
- in both instances, load the same post which contains a gif
- observe the final positions of the gifs; they should be the same
- test this both with gifs …

Avoid gif CLS

---

app/controllers/articles_controller.rb
spec/requests/editor_spec.rb

The `FrontMatterParser::Parser#call` method can return `nil` if the front matter is empty. For example:
```markdown
---
---
Body content
```
This causes [this line](https://github.com/forem/forem/blob/0e8089c4046f196aad5bdbb91e3cb5c9abdcd4c3/app/controllers/articles_controller.rb#L95) to raise a `NoMethodError`. We can default this to an empty hash in this case so that it will respond to the right methods.
I _think_ this bug comes from the fact that `---` is valid Markdown (translates to `<hr/>` in HTML), so the front-matter parser doesn't seem to be able to distinguish between front matter and two consecutive `<hr/>` elements. I'm also guessing that this doesn't come up more often because people probably delete the front matter entirely more often than leaving it empty.
- …

Fix NoMethodError on Nil for article preview

---

app/controllers/api/v0/listings_controller.rb
app/controllers/application_controller.rb

Prior to this commit, I saw the following in the Rails test log:
```
DEPRECATION WARNING: 'include Pundit' is deprecated. Please use 'include Pundit::Authorization' instead.
(called from include at ./app/controllers/application_controller.rb:12)
```
Related to #16483
None.  The tests should cover all of this.
None.

Removing deprecation warning

---

app/controllers/social_previews_controller.rb
app/views/social_previews/tag.html.erb

This PR adds a fallback color choice when there are missing
bg_color_hex or text_color_hex (this is likely going to become more
common as we only show the bg_color_hex in the form).
The choices (black and white) may not be correct - this "custom, or
default" value choice should likely be made in a decorator or on the
model instead.
Moving the object initialization into the controller was only done to avoid repetition
Addresses an error reported in
https://app.honeybadger.io/projects/66984/faults/83671065
From the console, or blazer, or psql cli, find the id of a tag with colors set, and the id of a tag without (in my case, tag 13 was `#discuss`, which did not have any colors set, and tag 12 was `#webdev` which had both set).
The social preview pages can be shown by tag id - thus …

Render social previews for tags with one of the two custom colors set

---

app/javascript/packs/admin/flashMessages.js
app/views/layouts/admin.html.erb
cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js

Currently, flash messages (success/error) aren't announced to screen reader users. The main challenge with this is that the flash messages appear on page reload, and both `aria-live` and `role="alert"` do not reliably announce their content if it is already present in the DOM when the page first loads (they're intended for dynamic changes mid-page use).
I've explored a few different options to solve this, and arrived at the conclusion that the most understandable (and maintainable) way to manage this is to:
- send focus to the message dismiss button (if exists) when the page loads
- add an `aria-describedby` to the button which links the message text with it
I think this is our best option for the time being since we get a few side-effect behaviours that feel like accessibility boosts …

Tweaks to the admin flash messages flow

---

app/liquid_tags/comment_tag.rb
app/liquid_tags/forem_tag.rb
spec/liquid_tags/forem_tag_spec.rb
spec/liquid_tags/unified_embed/registry_spec.rb

When building the [ForemTag](https://github.com/forem/forem/pull/16512) (to handle Forem-specific embeds), I neglected to include [Forem Comments](https://github.com/forem/forem/pull/16081). This PR fixes that.
Grab a comment URL from your localhost.
Create an embed using this format: `{% embed <forem-comment-url> %}`. The Comment embed should render properly.
Also create embed using the 2 old methods (`{% comment forem-comment-slug %}` AND `{% dev-comment forem-comment-slug %}`). These should also work, as I am leaving the old implementation in place for now.
None

Process Comment Embed through ForemTag

---

app/views/admin/invitations/index.html.erb
app/views/admin/users/_menu.html.erb
app/views/admin/users/gdpr_delete_requests/index.html.erb
app/views/admin/users/index.html.erb

This is another step towards removing bootstrap. This one focuses on "People" tab which had some navigations items with bootstrap styling.
It also slightly fixes the behavior of page header and navigation when users jumps between "people", "invitations" and "gdprs"..
**Before:**
**After:**
No.
It won't.

Bootstrap removal: People

---

app/services/notifications/reactions/send.rb
spec/services/notifications/reactions/send_spec.rb

The fix in #16570 worked around an issue where "aggregated_siblings"
wasn't present in the json_data, by only calling size if present.
Unfortunately, this causes a comparison of integer (new json_data
aggregated siblings count) with nil (result of the safe navigation for dig()&.size
assigned nil to `previous_siblings_size`, when we expected it to be
0). The initial error on the same data moved farther down the controller.
If old_json_data is present, but does not have an array in
reaction.aggregated_siblings, we want to have previous size be zero.
Remove guard clause and previous assignment
The issue was not that old_json_data was nil (it came from an existing
notification) but that there were missing keys (or rather that the
json data for some notifications didn't have a reaction key at …

Fix integer > nil error when sending reaction notifications

---

app/liquid_tags/asciinema_tag.rb
app/liquid_tags/dotnet_fiddle_tag.rb
app/liquid_tags/instagram_tag.rb
app/liquid_tags/kotlin_tag.rb
app/liquid_tags/medium_tag.rb
app/liquid_tags/next_tech_tag.rb
app/liquid_tags/reddit_tag.rb
app/liquid_tags/replit_tag.rb
app/liquid_tags/slideshare_tag.rb
app/liquid_tags/soundcloud_tag.rb
app/liquid_tags/speakerdeck_tag.rb
app/liquid_tags/spotify_tag.rb
app/liquid_tags/stackblitz_tag.rb
app/liquid_tags/stackery_tag.rb
app/liquid_tags/tweet_tag.rb
app/liquid_tags/twitch_tag.rb
app/liquid_tags/wikipedia_tag.rb

While working on the Unified Embeds project, I did not yet realize that unescaped dots in regex stand for a single character. This PR escapes all dots within embed regexes so that unintended consequences do not arise.
None; one-off fix
None; all specs should pass
None

Escape non-character dots in Embed Regexes

---

app/views/users/_profile.html.erb
cypress/integration/seededFlows/settingsFlows/updateProfileSettings.spec.js

Adds the new ColorPicker component to the User settings page (brand colors)
Related Issue https://github.com/forem/forem/issues/15179
- Log in and navigate to `/settings`
- Scroll to the bottom and check the new color pickers are present for both brand colors
- Change the values and save the form
- Make sure the user colors are successfully updated
https://user-images.githubusercontent.com/20773163/154517209-2706fec4-a84f-49c2-8696-6dee2524b0eb.mp4
N/A
updated. I have filled out …

Add new color picker to user settings page

---

app/controllers/api/v0/tags_controller.rb
app/javascript/article-form/components/TagsField.jsx
spec/requests/api/v0/tags_spec.rb

Reverts forem/forem#16610
This change is causing a bug when editing existing posts in Forems. When a request is made to the `/tags` endpoint, with e.g. 4 tags, a larger number are being returned, which don't seem to bear a relation to the tag names sent.
Reverting for now so I can investigate further without this negatively impacting users in the meantime.
Expected behaviour after this revert:
- Edit an existing post with a list of tags
- The editor should show only the tags currently added to the post, without injecting new ones

Revert "Only make one network call to fetch all existing tags in editor"

---

app/views/pages/_terms_text.html.erb

Noticed dev.to was hardcoded in the terms page, replaced it with community_name.
Load the /terms and ensure the correct community name is displayed
None
appropriately.
None …

Removed hardcoded dev.to from _terms text and replaced with community_name

---

app/policies/comment_policy.rb
app/policies/follow_policy.rb
app/policies/reaction_policy.rb
spec/policies/comment_policy_spec.rb
spec/policies/follow_policy_spec.rb
spec/policies/reaction_policy_spec.rb

> We heard back from community and product folks on the team and the consensus
> is that we agree with you that suspended users should be able to follow other
> users and add reactions, and they also shouldn't be allowed to edit existing
> comments.
None, tests cover this.
None.

Adjusting suspended user authorizations

---

app/controllers/application_controller.rb
app/controllers/articles_controller.rb
app/controllers/concerns/caching_headers.rb
app/policies/article_policy.rb
config/application.rb
spec/policies/article_policy_spec.rb
spec/requests/comments_spec.rb
spec/requests/editor_spec.rb

The goal of this commit is actually two fold:
1) To add documentation regarding my current emerging understanding of our caching implementation as it relates to our authorization and authentication.
2) Flippiing "on" the feature's core authorization check.
Buried within this is the desired normalization of the authorization between the `ArticlePolicy`'s `#create?`, `#preview?`, `#new?`.
My testing plan for this is to ask for SRE to spin-up a canary, then test.  What does that look like?  I'm uncertain because this is nudge closer towards our edge-caching strategy.  Which makes robust testing more difficult.
As mentioned above, this change likely requires a canary for proper testing.
None.

Adjusting ArticlePolicy for admin only posting

---

app/sanitizers/feed_markdown_scrubber.rb
spec/sanitizers/feed_markdown_scrubber_spec.rb

Since `<a>` with no href is valid html - don't call start_with? on nil. Accept anchor elements with no hyperlink as safe (don't sanitize).
~Deserves a test case~
Just to be pedantic - `<a>` without an href is a normal thing we should handle
https://html.spec.whatwg.org/#htmlanchorelement
> If the [a](https://html.spec.whatwg.org/#the-a-element) element has an [href](https://html.spec.whatwg.org/#attr-hyperlink-href) attribute, then it [represents](https://html.spec.whatwg.org/#represents) a [hyperlink](https://html.spec.whatwg.org/#hyperlink) ([a](https://html.spec.whatwg.org/#the-a-element) hypertext anchor) labeled by its contents.
> If the a element has no [href](https://html.spec.whatwg.org/#attr-hyperlink-href) attribute, then the element …

Don't sanitize anchor elements with no href

---

db/seeds.rb

Today while trying to re-seed my database I ran into the following:
```
Seeding with multiplication factor: 1
1. Creating Organizations.
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Profile image can't be blank, Profile image could not download file: execution expired
...
```
Something similar recently happened to Anna, which she addressed [here](https://github.com/forem/forem/pull/15178/files#diff-9ed171fcb61b660adaad65ce85412195bc1f2b11b93cd4b2ded2acbb8c2c4f07). Since we use the same method for setting user profile images in the seeds file I decided to update organizations too.
Drop your DB and make sure you can re-seed it without running in the above-mentioned error.
None

Update profile image for orgs in seeds

---

lib/data_update_scripts/20220223160059_coerce_identity_auth_data_format.rb
spec/lib/data_update_scripts/coerce_identity_auth_data_format_spec.rb

All but 3 records in DEV have OmniAuth::AuthHash objects serialized as
auth data dump. Normalize the remaining ones so they don't cause no
method errors when we treat the auth_data_dump as an object (sending
`#info` instead of asking for `['info']`).
Add null safety check in a second example (that null values should not
cause an error, and should not be coerced to auth hashes).
should address https://app.honeybadger.io/projects/66984/faults/84183659
For a  development environment, unless you have unusual data, the script should run with no effect.
The spec constructs 2 identities to be modified, and 2 that should not be (on is an omniauth auth hash, the other is null), and verifies they are changed.
None
_Will this PR introduce a change that impacts Forem members …

Update identities where the auth data dump is a plain hash

---

app/views/admin/users/show/profile/_actions.html.erb
cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js

Removal of the duplicate Verify email button. It will only live in the Emails tab.
- Closes #https://github.com/forem/forem/issues/16613
GO to /admin/users/<id> and ensure that the button is removed.
[Changes …

Remove the duplicate verify email button on the admin member view

---

app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/articles_controller.rb
spec/requests/api/v0/articles_spec.rb

As part of the [Authorization System Use Case
1:1](https://github.com/orgs/forem/projects/46) project, we are driving
towards the feature of: "Only admin's may post articles in this Forem."
This commit ensures that the API's "create an article" end-point
delivers on that feature.
Along the way, I've added reading notes and comments, to help us further
flex in the future (namely move all authorization checks into a policy
object).
- Closes forem/forem#16488
None, we've got tests for this.
None.

Ensuring POST api/v0/articles authorizes by policy

---

config/application.rb

I am reenabling this rails option to fix the broken video upload issue. I believe this stems from it being a really old gem and I would rather get it working first before making a custom patch. It was confusing to track this bug down until I came across this comment https://github.com/dwilkie/carrierwave_direct/issues/199#issuecomment-214806926
:crossed_fingers:  resolves https://github.com/forem/forem/issues/16186
I believe this rails option is self-explanatory and setting up a video upload feature is not straightforward.
n/a

Revert "Remove IE-specific setting (#16073)"

---

app/models/reaction.rb
spec/models/reaction_spec.rb

When a moderator flags a user,
and an admin marks this invalid
and the moderator tries to flag the user again
then we destroy the existing reaction, and check whether to notify
Since the points for invalid reactions are set to 0, this was not being
skipped. Now it will be.
Also, there were three documented reasons we should skip notification, but only two cases checked - removed the comment that didn't match the code (and added this one).
fixes https://app.honeybadger.io/projects/66984/faults/84240395 - a no method error trying to get reactable.user_id from a reaction to a user (being destroyed).
As a moderator, flag the user (from the profile page, or the /mod center).
As an admin, select Moderation, visit the Resolved tab, select Toggle flag reactions, and invalidate the created user …

Don't send notification for invalid reactions

---

app/models/tag.rb
app/views/admin/tags/edit.html.erb
app/views/moderations/index.html.erb
app/views/tags/edit.html.erb
app/views/tags/index.html.erb
spec/models/tag_spec.rb

In pairing with Arit, we were able to capture a few small wins in
regards to favoring an accessible tag name.  In other words, where ever
you see a tag's name, we want to render it as camel-case.  This will
greatly help those using a screen reader and frankly visually scanning
the tag (idontknowaboutyoubutthisiskindahardtoread).
However, as we explored the
code base, we found several places that will require further
consideration.  These revolve around the API and caching of tags for
articles and listings as well as the JSON documents we use for
populating drop-down lists.
So, instead of unleashing a large pull request, we're opting to provide
a small non-breaking refactor that demonstrates where we're going and
keeps production working as expected while allowing future …

Adding indirection for Tag#name to ease future work

---

app/policies/video_policy.rb
app/views/dashboards/_actions.html.erb
app/views/dashboards/_actions_mobile.html.erb
spec/policies/video_policy_spec.rb
spec/requests/videos_spec.rb

This commit compresses the policy check that spanned both :new? and :enabled?.  We hide the ability to upload a video (as per the altered html.erb files of this commit) but we didn't enforce the same logic in the controller.
Further, as Videos are a subset of Article, I'm adding the "verify the user is not suspended" test.
For sleuthing this relates:
- #16728
- forem/forem#16537
- #16634
And for historical context, this relates to:
- #10955
- #10954
- forem/internalEngineering#149
- Directly relates to #16483
None, the tests should be adequate.
None.

Ensuring VideoPolicy#new? is canonical

---

app/javascript/packs/articleModerationTools.js

There was very occasional flake in some of the publishing flows Cypress specs, caused by us accessing `dataset` of the article container, when the Cypress test runner had already managed to navigate away from the page (therefore the article container didn't exist).
This is _super_ unlikely to happen in production - Cypress can very quickly locate a link on the article page to leave to another location, but I don't think a user would have ever been able to trigger this error. In saying that though, we still want our code to be robust, and we definitely don't want those specs flaking 😄 
The change just makes sure that the article container is still shown, before going ahead an initializing the mod tools.
N/A
Specs should continue to pass
N/A
_Will this PR introduce a change that impacts …

Only init mod tools if we're still on article page

---

app/assets/stylesheets/components/cards.scss
app/views/sidebars/_homepage_content.html.erb

The DEV home page is currently looking less than ideal in Safari:
This appears to be caused by [this post](https://dev.to/inhuofficial/i-am-warning-you-dont-click-42im) appearing in the "Tags" righthand sidebar list (under multiple tags, but one would be enough!). 
The root issue is the minimum width for a grid column is `auto` and not `0` as you might suspect. Long, unbreakable, content in a column can cause unfortunate overlap and overflow. [See this CSS Tricks article](https://css-tricks.com/preventing-a-grid-blowout/).
We already had a `crayons-layout__content` class which accounted for this, setting `min-width: 0`. The other fix needed was to allow text content to wrap in Safari - we were using `overflow-wrap: anywhere` which isn't supported in Safari, but I've added a fallback 🙂 
- …

Fix grid col overflow in right sidebar in safari

---

app/controllers/stories_controller.rb
config/routes.rb
spec/requests/user/user_profile_spec.rb

This fixes a small bug where `/admin` redirected to a deprecated (but still existing) page. It now redirects to the singular user/member view `/app/admin/users/:id`.
https://forem-team.slack.com/archives/CAA200SH5/p1646313307397169
1. Append /moderate on a user's profile URL
2. Get redirected to `/app/admin/users/:the_users_id`
3. Repeat and get the same result with /admin
Nope
Nope

Redirect appended /moderate and /admin to the same page (admin member view)

---

cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js

I've noticed this spec flaking a fair bit in CI, with the tags dropdown not expanding on click. It seems to be to do with the animation of the mod tools panel opening, causing the button to not be fully clickable yet. I've added use of the `pipe` command to get around it
N/A
N/A
N/A
issue template so Community Success can help update …

Fix flake in post mod tools spec

---

app/controllers/videos_controller.rb

While in essence an idempotent change the purpose of this PR is to also
favor explicit method calls over callbacks.  Note, we don't have an
associated model (e.g. Video) and instead rely on `:video` which Pundit
converts to VideoPolicy.
From my experience in rails it can become challenging to mentally parse
the various before/after action paired with the only and except.  As
well as considering the timing of what happens when.
Further this commit helps provide a record of "work" towards an issue.
- Closes forem/forem#16729
- Reverses forem/forem#3806
None
None

Removing before_action in favor of explicity call

---

app/assets/stylesheets/components/stories.scss

We noticed that when [this particular DEV post](https://dev.to/inhuofficial/i-am-warning-you-dont-click-42im) was in the home feed, the whole home page became horizontally scrollable, with lots of empty space at the right-hand side.
The root cause is a visually hidden duplication of the title, which didn't wrap its content. I've applied some overflow wrap styles to fix the issue for now, but I'm going to raise a separate issue for the overall feature with regards to this hidden link.
It looks like we introduced this as part of a keyboard navigation feature (the ability to skip to next article by pressing 'j'). However, the approach taken with this hidden link is unnecessary (every article card on the home page already has _many_ links in it), and is damaging to accessibility (multiplied …

Prevent hidden link skewing layout of home page

---

app/views/users/_customization.html.erb

Note, I'm not overly keen on writing permission tests for this
component.  Why?  Robust permissioning tests can create combinatorial
explosions.  And there are presently no Rspec request specs for this.
So to add an automated test, we'd need to add a set of seed data that
seeds data that conforms to the emerging business logic of the policy.
And while this is easy with use case 1-1, it gets harder as we move
into more nuanced use cases.  Instead we should rely on bombarding our
policy classes with lots of tests to let them demonstrate what we mean
when we say `if policy(Article).create?`
Note, there is a potential relation to forem/forem#14807, namely if we
add a rich text editor to our comments, we may need to explore the
purpose and intention of this setting.
Closes forem/forem#16516
To …

Conditionally removing the "configure" editor

---

app/policies/article_policy.rb
app/services/feeds/import.rb
spec/policies/article_policy_spec.rb
spec/services/feeds/import_spec.rb

This commit leverages changes from forem/forem#16732 and
forem/forem#16763 to ensure that we're only fetching RSS feeds for
folks who have permission to create articles.
In addition, I chose to rename the variable `user_scope` to
`users_scope` to bring consistency in the variable names.
I also chose to refactor a private method so that it wasn't setting two
instance variables but was instead returning a value that could be used
to set an instance variable.
- Related to forem/forem#16732 and forem/forem#16763
- Closes forem/forem#16487
None, the tests cover the changes.
None.

Only fetch RSS of users who can create articles

---

app/views/admin/invitations/new.html.erb
spec/system/admin/admin_invites_user_spec.rb

When sending an invitation, and smtp isn't configured, we show a broken link
to the old smtp-settings page, which has been renamed email-server-settings in the admin documentation site.
Fix the url to match the documentation site.
- Introduced after the rename in https://github.com/forem/admin-docs/pull/30
With SMTP settings unconfigured, attempt to send an invitation from http://192.168.0.5:3000/admin/invitations/new
On main, a 404 is shown at https://admin.forem.com/docs/advanced-customization/config/smtp-settings
On this branch, the documentation page is shown at https://admin.forem.com/docs/advanced-customization/config/email-server-settings
None
development process, or any of our internal teams? If so, …

Fix broken email settings documentation link

---

app/policies/application_policy.rb
app/policies/article_policy.rb
app/policies/video_policy.rb
spec/policies/application_policy_spec.rb
spec/policies/video_policy_spec.rb

Videos are a conceptual subset of Articles (see
[VideosController#create][1] for supporting "evidence").  As such, we
want to ensure they conform to the expectations of the ArticlePolicy (as
described in forem/forem#16483).
This feature enhancement does a few things:
1. Renames swaps the `VideoPolicy#new?` and `VideoPolicy#create?`
declarations (reversing the alias direction)
2. Moves methods out of the concrete ArticlesPolicy into the
ApplicationPolicy.
3. Exposes these user oriented methods for external
consumers (e.g. making future refactoring work easier).  The happy
benefit is that this already removes a bit of duplicated logic.
4. Highlights that while yes the Policy is correct, we also may be
flirting with the concept of some sort of User "properties as it relates
to authorization" …

Ensuring the VideoPolicy adheres to article creation

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

This commit does three things:
1) Adds and tests the ArticlePolicy#moderate? feature
2) Refactors the spec helpers to be a bit more flexible
3) Adds a few more edge case tests around ArticlePolicy
My apologies for conflating these changes, as it makes this commit
more challenging to review.
The goal is to adequate demonstrate the logic around users who can or
cannot moderate.  At present, the rules for who can moderate is here:
https://github.com/forem/forem/blob/841491c6ee7f9a46d8033b4b55052316db251863/app/javascript/packs/articleModerationTools.js#L17-L27
```js
if (user?.trusted) {
if (user?.id !== articleAuthorId && !isModerationPage()) {
initializeActionsPanel(user, path);
initializeFlagUserModal(articleAuthorId);
// "/mod" page
} else if (isModerationPage()) { …
```

Adding ArticlePolicy#moderate?

---

cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js

We're seeing these fail intermittently (typing the color doesn't
result in the desired color in the form), and will disable e2e tests 
temporarily to avoid unrelated build failures.
- Related PR #16774 attempts to address this
Disabled tests should be disabled and not run.
Not sure if the color picker is only handling input funny for cypress (I suspect this is limited to testing) or if there could be interaction issues with human users.
[Changes …

Disable admin brand color picker tests

---

app/helpers/application_helper.rb
app/views/admin/settings/forms/_user_experience.html.erb
cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js

This PR replaces the last of our old-style color pickers with the new accessible one. The relevant app section is in `/admin/customization/config` in the "User experience and brand' section.
- Related Issue https://github.com/forem/forem/issues/15179
- Log in as an admin user and visit `/admin/customization/config`
- Expand the 'user experience and brand' section
- You should see the new color picker for the "Primary brand color hex"
- Experiment with setting the color either with the picker or the plain text input
- Submit the form with a low contrast color (e.g. `#ababab`)
- You should see a snackbar advising the color has failed validation
- Submit the form with a strong contrast color (e.g. `#000000`)
- You should see a snackbar advising the setting has been updated
- Refresh the page …

Add new color picker to user experience config

---

config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml

As part of removing Stackbit integration, I previously missed removing
the translation key.  This removes an errant key.
This commit was driven by attempting to address the following feature
request:
> Conditional hide "Generate a personal blog from your DEV Community
> posts" in /settings/extensions
There is option for this behavior.
```shell
❯ rg "extensions\.generate"
```
With this commit, the above command exit's status 1 (e.g. nothing found).
- Closes #16819
- Missed as part of #15701
None.
None.

Removing reference to Generate Personal blog

---

app/services/users/suggest_for_sidebar.rb
spec/services/users/suggest_for_sidebar_spec.rb

When rendering the sidebar widget, when attempting to find users to follow for the current tag, when a user is not signed in, sometimes we're seeing an error raised (NoMethodError internally, 500 Internal Server Error externally).
Exit early with User.none (empty relation) when the current user is not signed in. Since both the cache key and the queries expect the user to be present and respond to several methods, this is the safest choice.
- Closes https://app.honeybadger.io/projects/66984/faults/79342962/
Assuming you have a tag locally named "webdev", accessing `http://localhost:3000/users?state=sidebar_suggestions&tag=webdev` as a signed out user (incognito/private window, or a curl request) should raise a 500 error (no method error id for nil) in main, and a 200 response on this …

Don't suggest author follows for anonymous visitors

---

app/workers/feeds/import_articles_worker.rb
spec/workers/feeds/import_articles_worker_spec.rb

We've been running article imports for all users inside a single Sidekiq job. For a large Forem instance like DEV, that takes forever, tying up a Sidekiq worker thread that long and accumulating memory.
Doing all that work within a single Sidekiq job has begun taking over an hour on DEV. Regardless of the reasons we did it that way originally, we should be able to handle this concurrently. If we cannot, ideally we'll investigate why and handle it properly rather than consigning it to sequential work.
The consumer interface to `Feeds::ImportArticleWorker` should be unchanged. Updating a feed for an individual user will still work if you go in through that front door.
development process, or any of our internal …

Fan out Feeds::ImportArticlesWorker

---

spec/services/articles/enrich_image_attributes_spec.rb

We had been disabling webmock in this test, which means vcr was _not_ 
intercepting requests and we were making them live.
This appears to have been a [work-around](https://github.com/forem/forem/pull/15170/commits/7e111a242d192b5d0eff61e35bcaaa2495b12140) for an
issue where the captured URL in the cassette pointed to cloudinary,
while the code was fetching from the source directly, and an unhandled
request error was raised when running the spec, so a live request was made.
However, the upstream source (https://via.placeholder.com/350x150)
has activated cloudflare bot detection, and rather than a png image
response, we were getting an unprocessable html gateway page "Checking
your browser..." from cloudflare, and the test was failing (the enriched image is not saved on the article, …

Stop disabling webmock in test, update vcr cassette to match test

---

cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
cypress/integration/seededFlows/adminFlows/apps/editListingCategory.spec.js
cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js
cypress/integration/seededFlows/adminFlows/tags/createATag.spec.js
cypress/integration/seededFlows/settingsFlows/organisationSettings.spec.js
cypress/integration/seededFlows/settingsFlows/updateProfileSettings.spec.js
cypress/integration/seededFlows/tagsFlows/editTag.spec.js
cypress/support/commands.js

After a bit of investigation into https://github.com/forem/forem/issues/16829, here's what I found:
- I stripped back everything in our `ColorPicker` component to match the simplest version of `react-colorful`'s input - rendering only the input, and the `color`/`setColor` state. This matched the `HexColorInput` in [their example](https://codesandbox.io/s/0k2fx?file=/src/App.js).
- I still pretty reliably saw the issue where if the test entered `#123456`, what arrived in the UI was `#12356`
- I can see in the library's code, that the input value [can be overridden when the `color` prop changes](https://github.com/omgovich/react-colorful/blob/master/src/components/common/ColorInput.tsx#L43)
- The `color` state in our component changes when a valid 3 character hex is entered
- It looks like …

Update color picker input specs

---

app/workers/feeds/import_articles_worker.rb
spec/workers/feeds/import_articles_worker_spec.rb

https://github.com/forem/forem/pull/16818 added a per-user fan out rather than running the full set of users in the Feeds::Import job (because it was taking a long time to run).
However, the Feeds::Import job includes a filtering of users to only process those who have a feed_url setting present. 
We're needlessly enqueuing hundreds of thousands of these workers for users each hour, that are a noop, increasing the latency on the default queue up to ~30m each hour.
I think I updated the test cases correctly. If you wanted to test this manually, you could set a feed url on one user, and ensure the other is not there, and check the process logs for Feeds::ImportArticlesWorker::ForUser jobs enqueued (should only happen for the user with a feed, not those without).
None
_Will this PR introduce …

Limit per-user feed import fanout to users with feed urls set

---

app/models/article.rb
spec/models/article_spec.rb

Rather than deny-listing character classes we want removed, we can instead allow-list the safe ones and remove everything else.
This is in response to a post that broke the DEV homepage yesterday. Its title didn't just use whitespace, which a browser would've merged into a single space, but actually used a whitespace-looking character (`\u2800`, ["Braille Pattern Blank"](https://www.compart.com/en/unicode/U+2800)) so that that wouldn't happen and deliberately messed up the formatting not only of their own post, but any feed the post would appear as a recommended post on (including the homepage).
This PR allow-lists safe character classes:
- Word characters (letters, numbers, underscores)
- Whitespace (spaces, tabs, newlines, etc)
- Punctuation
- Emojis that I could think of
Everything …

Allowlist character classes for post titles

---

app/views/articles/feed.rss.builder
spec/requests/articles/articles_spec.rb

Fix incorrect syntax. `#tag!` is weird.
Resolves https://github.com/forem/forem/issues/16865
Navigate to `localhost:3000/feed` and you should see the author name (within `dc:creator` tag) displaying properly, compared it to DEV where it's currently missing.
yes!
n/a

Fix missing dc:creator on RSS feed

---

app/javascript/article-form/components/TagsField.jsx

Reverts forem/forem#16841
This is once again causing the same bug in production where when a user edits a post, the bulk search for the post's tags is returning 10 top tags, instead of the tags which match the tag names passed in. In the video below - we search for `shecoded` and `career` but we get 10 unrelated tags back.
This is caching related, and was observed when we first attempted to change this network call in https://github.com/forem/forem/pull/16610, but we thought it had been fixed by the API changes in https://github.com/forem/forem/pull/16671. It seems it has not been fixed by this 😓 
https://user-images.githubusercontent.com/20773163/158785231-804b97b4-2995-4e19-a483-9edfda9e7bea.mp4

Revert "Refactor editor tags selector to fetch all tag info in one network call"

---

app/services/edge_cache/bust/fastly.rb
lib/data_update_scripts/20220317151317_remove_fastly_http_purge_flag.rb
spec/lib/data_update_scripts/remove_fastly_http_purge_flag_spec.rb

In https://github.com/forem/forem/pull/12627 we added a feature flag to test moving from (deprecated) POST to the fastly api, to using the Fastly gem's `purge` method (and an HTTP [PURGE](https://developer.fastly.com/reference/api/purging/) verb in the request).
This was delivered and enabled and has run without issue for the past year.
We can remove the feature flag and the fallback code (fastly_post), and always use the preferred method.
This should not impact which edge cache we use (the choice between fastly and nginx is not controlled by this feature flag), and only changes how we communicate with fastly. 
As a small bonus, it shifts the knowledge of fastly's api details into their gem, and out of our code.
follow up after #12627
Unit tests should suffice here.
None, backend only …

Remove fastly http purge feature flag and conditional behavior

---

app/liquid_tags/unified_embed/tag.rb
spec/liquid_tags/loom_tag_spec.rb
spec/liquid_tags/unified_embed/tag_spec.rb
spec/support/embeds_helpers.rb

A Forem team member reported that valid DEV links were failing embeds. The problem was ascertained to be coming from the embed's `validate_link!` method. This PR fixes the problem.
closes https://github.com/forem/forem/issues/16917
Create embeds using forem-specific links. The embeds should render successfully.
None

Fix embed link validation failures

---

app/services/twitter_client/client.rb
spec/services/twitter_client/client_spec.rb

I noticed this branching on parent classes in the twitter client, is there a reason we're not using case for this?
Ideally tests passing is sufficient.
None

Match error class using case instead of if/elsif/else

---

cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
cypress/integration/seededFlows/adminFlows/users/userAdminUtilitites.js

There was the same function created in several E2E test files for the user admin. This consolidates those functions into one import.
- Related Issue #16604 
- Closes #
N/A Code refactor for E2E tests
N/A Code refactor for E2E tests
appropriately. …

Created a utility function for checking the flash success message for user udpates in the admin

---

app/controllers/application_controller.rb

While exploring the DashboardsController, I came across method calls to
`not_found`.  Idiomatically, I assumed that these methods were returning
a value.  However, in looking at the code, it raises an exception.
_Note: I excpect methods that raise exceptions, especially as the only
thing they do, to end in a `!`._
By adding the documentation my "IntelliSense" provides insight into the
expected behavior of this function (e.g. "Raises an exception").
Without the documentation, I don't see any useful information.
The "proposed" state:
The "prior" state.
- Related Issue #forem/forem#16913 (but only in the "I'm in the neighborhood looking at things kind of way").
None.
None.

Adding inline documentation

---

app/services/feeds/validate_url.rb

Users are unable to add DEV as their feed url setting. 
Follow on to #15942 which enabled downloading existing DEV feeds, this
allows setting a feed url to DEV.
It's possible this user agent should be brought inline with the
tags choice of community name and url, but in the short term I'm
making this consistent with the existing feed importer.
- Related Issue #15942
- Closes #16924 
Add a DEV.to user feed like https://dev.to/feeds/ben/ to a local user's RSS feed url (http://localhost:3000/settings/extensions under publishing from rss)
Save should succeed. Import should succeed:
```ruby
User.all.sample.setting.update(feed_url: 'https://dev.to/feed/djuber/')
Feeds::Import.call
```
None
development process, or any …

Feeds::ValidateUrl sends "forem feeds importer" user agent

---

README.md

Gonna miss you, friends! 👋🏻
- Closes #
N/A documentation change
N/A documentation change
appropriately. …

Remove myself from the core team

---

app/lib/url.rb

This method was making a DB query every time, but if the table is there the first time, we can reasonably assume it will continue to exist. This is an assumption generally baked into ActiveRecord — it caches the schema for every table when its corresponding model is used and never checks it again for the life of the process. It's the reason we don't delete tables or even columns until code that uses them is no longer in production.
The reason this is important is that this DB query is now the single most common query, more than 5x the frequency of the second-highest (finding a `User` by their `id`). Results from DEV:
This check was added in #16843. It's perfectly fine that it was done the way it was. It's not putting excessive load on the database (in fact, Postgres is likely caching the …

Optimize `URL.database_available?`

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

As part of our aspirations to only show users what is relevant to them
and "hiding" what is not, this method will help us with the edge case of
"should we show the user a dashboard listing of posts?"
Closes #16908 
Related to forem/forem#16837 and forem/forem#16942
This method is not used in the production codebase, but will be shortly.
None.

Adding ArticlePolicy#has_existing_articles_or_can_create_new_ones?

---

app/models/admin_menu.rb
spec/models/admin_menu_spec.rb

I have requested Amy to review this to make sure from a product standpoint, she understand the consequences of this being merged.  (Note, they are low stakes but I want to give product an opportunity to understand this bit).
So developers, please review for logical accuracy.
This menu item will show up once you have added the
`:limit_post_creation_to_admins` feature flag (regardless of whether
it is enabled or not).
If you wish to add the menu item:
```console
rails runner "FeatureFlag.add(:limit_post_creation_to_admins)"
```
In "adding" the item, it will default to disabled.  However, as an
administrator you should now be able to toggle on and off the
authorization enforcement.
If you wish to remove the menu item:
```console
rails runner …
```

Adding Admin > Content Manager > Spaces menu item

---

app/views/users/_notifications.html.erb
config/locales/helpers/en.yml
config/locales/helpers/fr.yml
config/locales/views/settings/en.yml
config/locales/views/settings/fr.yml

Our language regarding articles needs minor revisions to speak a bit
more generally about content.  This follows on the features of
AuthN/AuthZ work to allow forem admins to configure their forems such
that a subset of their forem members may not have the ability to create
articles.
Closes forem/forem#16890
Closes forem/forem#16891
None
None

Adjusting article copy to be more general

---

app/models/article.rb
spec/models/article_spec.rb

Send slack notification when an article is created (as published) and when an article is updated (from draft to published), don't send slack notification when an article is updated but the `published` status is not changed. (Previously the notification was sent every time when a published article was updated).
- Related Issue #15858 (indirectly)

Fix redundant slack notifications when article was published

---

app/controllers/api/v0/analytics_controller.rb
app/errors/unauthorized_error.rb

We only have one reference to the UnauthorizedError, which is shadows
the ApplicationPolicy::NotAuthorizedError.  This commit removes the
exception.
Related to forem/forem#16985 but only barely
None
None

Favoring re-use of authorization error

---

db/migrate/20220323185428_index_articles_on_feed_source_url.rb
db/schema.rb

We already have a partial unique index for this column scoped on `published = true`, which is still useful. This index does not make that index redundant because that index is used to enforce a constraint that we *only* want to apply to published articles. This index will be used when `WHERE published` is not part of the query.
On DEV, this query takes 800ms-3s, depending on concurrent DB load. Some Sidekiq jobs query articles on this column alone hundreds of times:
From [this trace](https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/xaqnacJMsoQ/trace/Cp7zpKc6EYG?span=6d8c4c822d44e1a5) on Honeycomb. …

Add unscoped index on articles.feed_source_url

---

app/assets/images/chevron-left.svg
app/assets/stylesheets/admin.scss
app/views/admin/users/_member_index.html.erb
app/views/kaminari/admin/_next_page.html.erb
app/views/kaminari/admin/_paginator.html.erb
app/views/kaminari/admin/_prev_page.html.erb
config/locales/kaminari.en.yml

This PR tackles the pagination aspect of https://github.com/forem/forem/issues/16933
We use a gem (`kaminari`) to handle pagination, so I've worked with their default templating to create the new look. This involved creating a new "theme", so we now have:
- "internal" theme - used by all the admin pagination, aside from the new member index view
- "admin" theme - used by member index view when the `member_index_view` feature flag is enabled
Eventually as we work on other parts of the admin area, "admin" will become the main theme, and eventually "internal" can be phased out. As a small side point - the "internal" theme is currently styled with bootstrap which we are also phasing out.
- Related Issue https://github.com/forem/forem/issues/16933
- Seed your DB with more than 50 users. …

Admin member index: Update pagination layout & styles

---

app/javascript/packs/homePageFeed.jsx
cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js

This spec has been flaking a bit in CI recently. After a bit of investigation is seems the main issues at play are:
- The spec assumes the correct profile preview card is _always_ the first on the page (it should be given the seed data, but it's partly impacted by point 2...)
- The feed re-render which happens as the loading UI disappears and the feed items appear
My approach to resolving this is:
1. Wait until the feed has loaded before doing anything
2. Use a `closest` selector to choose the right preview card to assert on
I also noticed a couple of our assertions were dodgy (as in, weren't doing anything) and took the opportunity to refactor to use `pipe` instead of relying on attributes like `data-initialized`, and similarly waiting on the `follows` network requests to make sure those …

Improvements to home feed profile preview card cypress spec

---

app/controllers/dashboards_controller.rb
app/views/dashboards/_actions.html.erb
spec/requests/dashboard_spec.rb

This commit provides two things:
1.  Some notes related to my analysis regarding the dashboard
2.  Conditional redirects and rendering based on article policies
The code comments say most of what I want to say, but to reiterate:
When a user can't create articles nor do they already have published
articles, then we don't want to avoid showing them stats related to
articles.
Closes forem/forem#16913
Related to forem/forem#16908 and forem/forem#16931
If you want to reproduce this in the browser, you'll need to:
`rails runner "FeatureFlag.enable(::limit_post_creation_to_admins)"`
Then login as a user who has no articles, go to `/dashboard` and you should be
redirected to `/dashboard/following_tags`.  You will also not see Posts,
Series, nor Followers on the side panel.
Now, run `rails runner …

Conditionally reducing dashboard chatter for users

---

app/controllers/admin/spaces_controller.rb
app/services/audit/notification.rb

There are two existing listeners for the `Audit::Logger`: `:moderator`
and `:internal`.  (Note: during tests we ignore the :moderator and
:internal logs as defined in [config/initializers/audit_events.rb][1].)
There are two existing listeners for the `Audit::Logger`: `:moderator`
and `:internal`.  (Note: during tests we ignore the :moderator and
:internal logs as defined in [config/initializers/audit_events.rb][1].)
Using `rg "Audit::Logger\.log\(:internal," --files-with-matches`, the
`:internal` listener is found in:
- app/controllers/admin/secrets_controller.rb
- app/controllers/admin/settings/base_controller.rb
- app/controllers/admin/settings/general_settings_controller.rb
Using `rg "Audit::Logger\.log\(:moderator," --files-with-matches`, the
`:moderator` listener is used in:
- …

Adding :internal auditing for admin/spaces#update

---

cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js

This is failing for me (and had been flaky previously).
https://app.travis-ci.com/forem/forem/builds/248455560 blocked a
deployment because of an error (`@followsRequest` timed out waiting).
```
wait [@baseDataRequest, @notificationsRequest, @countsRequest]
wait @followsRequest
request @followsRequest
saved as log in: cypress/logs/failed-profile-preview-cards-home-feed-profile-preview-cards-handles-users-with-punctuation-in-the-name.json
1 passing (33s)
1 failing
1) Home feed profile preview cards
"before each" hook for "handles users with punctuation in the name":
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `followsRequest`. No request ever occurred.
```
I'm able to reproduce this locally and disabling until we …

Skip tests for profile preview cards on the home feed

---

config/initializers/honeycomb.rb

The particular cache fetching that we do with [rendering comments for an article](https://github.com/forem/forem/blob/d9a5c204e11ff01944f0e1ab395a23848f1cadf2/app/views/articles/_full_comment_area.html.erb#L31) doesn't end up getting picked up by `cache_read.active_support`. After some experimentation, I discovered that it does get picked up via `cache_read_multi.active_support`.
See:
- https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch_multi
- https://guides.rubyonrails.org/v6.1.4.7/active_support_instrumentation.html#cache-fetch-hit-active-support
In a Rails console:
- Create an `ActiveSupport::Notifications` subscription
- `ActiveSupport::Notifications.subscribe(/cache_.*\.active_support/) { |*args| pp args: args }`
- Render a tree of comments, as in an …

Instrument `ActiveSupport::Cache#fetch_multi` in Honeycomb

---

app/controllers/api/v0/listings_controller.rb
spec/requests/api/v0/listings_spec.rb

This aligns our behavior with some of [the documentation examples](https://developers.forem.com/api#operation/createListing), while permitting the original name (we don't break the api for existing users).
The renaming [changed the api docs](https://github.com/forem/forem/pull/7910/files#diff-b4ac45b1fc06ab3cfbce2fe69b38d654567302a259e4b867ad82bf84a241e0f0), but the api internals were changed to continue to [use the old name](https://github.com/forem/forem/commit/6f579c6c6f68d77e91eed573b309ae1d55d70ca6)
- Related Issue #7910
- Closes #16927 
I updated the request spec to use the new name by default and added a single example falling back on the old name when the new one is not provided, so there should be adequate coverage.
The failing example in the original issue works correctly on …

Prefer "listing" to "classified_listing" in the api

---

spec/factories/articles.rb
spec/view_objects/cloud_cover_url_spec.rb

`Faker::Avatar.image` uses [robohash.org](https://robohash.org/) to generate a unique image from sample text on each request. This provides a nice diverse set of cover images for articles (and is pretty cool). However, if their service slows down (due to load, availability, denial of service, cloudflare defense enabled), loading the cover image times out in system tests, and causes unrelated test failures.
Use a locally served image file instead (these are the animal art images in app/assets/images/)
We do stub out robohash in unit tests (for user agent = Ruby) but headless chrome was having issues with it.
Test only concern. Tests should pass (but they might anyway). Ideally, the system tests pass with the network disconnected. Maybe you could test this locally by adding a 30-60s delay …

Avoid using robohash for factory generated article cover images

---

app/views/notifications/index.html.erb
app/views/organizations/_sidebar_additional.html.erb

Since i18n-tasks resolved the issue in 1.0.5, and we've upgraded, the
erb comment tags can use the original (natural) syntax, reverting the work-around from #17012
- Related Issue #17012 
This was an issue with the task run in rspec, but is no longer an issue:
```
bundle exec rspec spec/i18n_spec.rb
Finished in 6.49 seconds (files took 0.6829 seconds to load)
4 examples, 0 failures, 2 pending
```
None

Revert ERB comment tag work-around

---

app/javascript/packs/foremCreatorSignup.js
app/views/shared/authentication/_forem_creator_signup.html.erb
config/locales/views/auth/en.yml
config/locales/views/auth/fr.yml

The "New Forem Secret" form can now be toggled as well as the password field.
- Closes #16756
https://user-images.githubusercontent.com/47295890/160245480-4b0eac46-5b1e-4d7a-8b88-78a3f90a0834.mov
None

Add toggle button to 'New Forem Secret' form

---

app/controllers/admin/spaces_controller.rb

In the [app/views/layouts/application.html.erb][1] we use
[ApplicationHelper#release_adjusted_cache_key][2] to define a cache
key.  That cache key includes the
`Settings::General.admin_action_taken_at` time field.
The [ApplicationController#bust_content_change_caches][3] method is
responsible for updating the `Settings::General.admin_action_taken_at` column.
[1]:https://github.com/forem/forem/blob/f5ae2900b5a91d16dac98b9429384c39386163fa/app/views/layouts/application.html.erb#L48
[2]:https://github.com/forem/forem/blob/f5ae2900b5a91d16dac98b9429384c39386163fa/app/helpers/application_helper.rb#L193-L198
[3]:https://github.com/forem/forem/blob/f5ae2900b5a91d16dac98b9429384c39386163fa/app/controllers/application_controller.rb#L255-L258
This relates to forem/forem#16606 and may be necessary …

Bust cache when changing spaces

---

app/services/edge_cache/bust.rb

In helping track down forem/forem#17041 I was looking at our cache
busting logic.  We were looking up a constant via the `.const_get` call
from a string already defined inline.  This refactor short-circuits
naming a string, capitalizing it, then looking in the class's registered
constants.
There's also a subtle bug in the original; When `provider` equals
"another_cache", the `#capitalize` method would return
`"Another_cache"`, whereas `#classify` will return `"AnotherCache"`.
Below are some benchmarks for the change.
```ruby
require "benchmark"
module EdgeCache
class Bust
def by_class
Fastly
end
def by_const_get
self.class.const_get("fastly".classify)
end
end
end
Benchmark.bmbm do |x|
x.report("by_class") do
1000.times do
EdgeCache::Bust.new.by_class
end
end
x.report("by_const_get") do …
```

Favoring explicit class declaration

---

app/views/articles/show.html.erb
spec/system/articles/user_visits_an_article_spec.rb

While adding a similar notice for scheduled articles, I found out that "Click to edit" link was displayed in the draft notice for the users that are not authorized to edit the article. The test was passing because it was checking for the `'display: inline-block;">Click to edit</a>'` not to exist while actually there was `display="none">Click to edit</a>` (which had no effect) on a page.
You should be able to see the incorrect behaviour by visiting [the link](https://dev.to/annaboo/test-draft-2dog-temp-slug-2514949?preview=d10444ef6f58470bc2a55bc97270c8e0bdf8e1170644c192a30e190b4b494e5000ad46c1408db5ad5249da73681a8edff0fcaff3684d128ffad8e034) as a signed in user. 
- Create a draft article
- On the article page you should see the notice and a link "Click to edit"
- (Save the article preview …

Fixed hiding 'Click to edit' link for drafts

---

lib/data_update_scripts/20220330191441_remove_connect_feature_flag.rb
spec/lib/data_update_scripts/remove_connect_feature_flag_spec.rb

There's an existing data update to introduce the connect feature flag,
and it's been disabled. However, since all the code relying on this is
now gone, it makes sense to remove the flag.
My main use case is after resetting the db, in a new environment, I don't need or expect to see connect on the http://localhost:3000/admin/feature_flags/features page
https://github.com/forem/forem/pull/14734 removed all the code dependent on this flag
Ensure there's a connect feature flag (or add it from the ui http://localhost:3000/admin/feature_flags/features)
Run the data update scripts
```
bundle exec rake data_updates:run
```
Refresh the admin feature flag page, connect should be gone.
None
development process, or any of …

Remove the connect feature flag

---

app/controllers/stories/tagged_articles_controller.rb
spec/requests/stories/tagged_articles_spec.rb

Prior to this commit, we determined the 404 status based on the final
scoped query of the articles.  That scoped query would limit to a
timeframe.
However, what we want is to not render a 404 status if we have an
"established" tag.  An established tag means that we have at least one
published article (regardless of when we published).
Fixes forem/forem#16932
With our given test data this might be a bit obnoxious to test.
We _might_ want to consider informing the user that there are no articles for the given timeframe.

Ensuring that established tags don't respond 404

---

app/models/article.rb
app/models/organization.rb
spec/models/organization_spec.rb

There are three major things occurring in this pull request:
1. Renaming `Article#update_cached_user` to `Article#set_cached_entities`.
2. Reducing an organization's direct knowledge of which of the org's
attributes an article caches.
3. Removing duplicate calls to update the article associated with the
organization.
For renaming to `Article#set_cached_entities`, the prior method implied
we were updating the persistence layer.  However, we were not making any
save nor update calls.  This rename should clarify intention.
For reducing knowledge, the comments for
`Article::ATTRIBUTES_CACHED_FOR_RELATED_ENTITY` should explain the details.
And last, removing the duplicate calls; we had three methods that were
attempting to build and update the `Article#cached_organization`'s
value.
Closes …

Ensuring article's cache updates on org image update

---

app/models/user.rb
app/workers/users/resave_articles_worker.rb

Prior to this commit, when we change attributes for a user we might
resave each article.  The purpose of the resave is to update some of the
cached attributes of an article.
This removes some redundant code.  The following removed code has
an `article.save` call.  Which, the callbacks in the article (see below)
already clear the cache.
```ruby
def resave_articles
articles.find_each do |article|
if article.path
cache_bust = EdgeCache::Bust.new
cache_bust.call(article.path)
cache_bust.call("#{article.path}?i=i")
end
article.save
end
end
```
https://github.com/forem/forem/blob/8e6981aac59e86a9a2c69db1e50fb1119f509c8d/app/models/article.rb#L164
https://github.com/forem/forem/blob/8e6981aac59e86a9a2c69db1e50fb1119f509c8d/app/models/article.rb#L881-L888
This was discovered in triaging …

Reducing subtle duplication of effort/logic

---

app/controllers/comments_controller.rb

While reviewing the authorization system, I saw a curious instance
variable and wanted to know more about it.  Turns out, it's no longer
referenced.
`$ rg "on_comments_page"` exits status 1 (e.g. no matches)
None.
None.
None.

Removing unused instance_variable

---

app/controllers/admin/spaces_controller.rb
app/views/admin/spaces/index.html.erb
config/locales/controllers/admin/en.yml
config/locales/controllers/admin/fr.yml

This change delivers an accessible form, and while it doesn't remove the
Save button nor produce a modal it does deliver the minimum viable
functionality.
In conversations with Suzanne, we spent an hour looking at how we might
make an accessible modal with the checkbox and state management
required as we as removing save buttons.
There are two paths:
1. Extend the current, yet deprecated, stimulus modal controller.
2. Extend the Preact modal work done for the Members Detail View.
We spent about 15 minutes pursuing the stimulus modal controller route,
and realized how much cruft it added to the system.  Not ideal and very
opaque in it's interaction.
The second one we talked about, but for our alloted time was inadequate
to begin further work.  To deliver on that generalized preact modal …

Ensuring confirmation and flash message for spaces

---

app/controllers/admin/overview_controller.rb
app/services/admin/charts_data.rb
app/views/admin/overview/_analytics.html.erb
spec/requests/admin/overview_spec.rb
spec/services/admin/charts_data_spec.rb

Stop displaying admin analytics for current day, as the data is incomplete. Instead, show analytics for any given period up to yesterday
To QA this:
- go to `/admin`
- verify that analytics are displayed for a 7-day period leading up to "Yesterday"
- verify that the correct number of total Posts, Comments, Reactions and New Members are displayed
- verify that the chart displays the correct number of Posts, Comments, Reactions and New Members for each day
_Chart data_
https://user-images.githubusercontent.com/22390758/161431648-4be13b58-3330-4984-aa1b-cb2da8774dfb.mov
_Update post `published_at` date to show chart does not display data from today_
https://user-images.githubusercontent.com/22390758/161431611-9b316c8c-b96f-408f-80cf-de758cdc47d0.mov
This is a backend change with no impact on …

Display analytics up to yesterday instead of today

---

app/liquid_tags/poll_tag.rb
config/locales/liquid_tags/en.yml
config/locales/liquid_tags/fr.yml

Introduced in forem/forem#3176, it appears that this method has been
along for the ride.
How did I find this?  I saw an exception and realized that we cast our
comment IDs from base-26 integer format to base-10.  I decided to look
through our code for `/\.to_\w\(26\)/` and stumbled upon the now removed
instance.
Quickly looking at the code, it appeared that this method was never
called.
So ✂✂✂
Barely related to forem/forem#3176
None
None

Removing uncalled method ✂✂✂

---

app/assets/stylesheets/base/layout.scss
app/views/layouts/admin.html.erb

We had [a discussion in the Admin Experience pod](https://forem-team.slack.com/archives/C01S4QZUDNC/p1648562796522479) around our layout breakpoints for the admin area. This PR implements the agreed change - we now only enter the 2 column view at the **large** breakpoint (before this happened at 'medium', same as the user-facing section of the app). This gives us more UI space for the data-centric views we present in the admin area.
Discussion on this was prompted by https://github.com/forem/forem/issues/16935
- On the home page (`/`), adjust your browser size from smallest to larger, just enough to enter the 2 column layout , e.g.
- Now visit the admin area, keeping your browser the same size. The admin overview page should appear in a single column layout, e.g.
- If you continue to …

Tweak crayons layout for admin section

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

Prior to this commit
This would have been a bug, if someone had:
1. Toggled on the :limit_post_creation_to_admins feature flag
2. Wasn't an admin
3. Already had a published post
4. Went to edit the post and attempted to preview it
Related to the following issues:
- forem/forem#16908
- forem/forem#16944
- forem/forem#16837
- forem/forem#16942
None, though I suppose you could try to create this bug with the above steps.
None.

Ensuring users can preview already published posts

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/controllers/async_info_controller.rb
app/javascript/packs/applyApplicationPolicyToggles.js
app/models/async_info.rb
app/policies/application_policy.rb
app/views/layouts/_nav_menu.html.erb
cypress/integration/seededFlows/policyFlows/limitPostCreationToAdmins.spec.js
spec/models/async_info_spec.rb
spec/policies/application_policy_spec.rb

This PR builds on the conversation from forem/forem#17056 and moves in a
slightly different direction.
Important in all of this is that the ability to create a post is
enforced on the server.  If the "Create Post" button were to be visible
but the user couldn't create a post when they clicked the button, they
would get an authorization error (or some such response).
This PR posits a different and perhaps competing approach to
forem/forem#16606.  This PR provides a general approach in which we add
class attributes in our HTML erb files.
Note: I have not included Cypress tests as I don't want to yet commit
that time.  I'm also wondering if this is the "right" thing to do.  I
definitely think we want to add some JS tests.  But could we do JS and
unit tests?  (How do we reach consensus …

Conditional rendering of "Create Post" link

---

spec/requests/admin/reactions_spec.rb
spec/services/analytics_service_spec.rb

This is kind of pedantic, since we _had_ been using a lambda, and
calling as a value. Now explicitly call the proc in a block and expect
the block to raise error.
On main the request example produces the following warning:
```
The implicit block expectation syntax is deprecated, you should pass a block rather 
than an argument to `expect` to use the provided block expectation matcher or the 
matcher must implement `supports_value_expectations?`. e.g  
`expect { value }.to raise Pundit::NotAuthorizedError` 
not `expect(value).to raise Pundit::NotAuthorizedError`
If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, …
```

Expect to raise error should use a block

---

spec/liquid_tags/codesandbox_tag_spec.rb

This was in place to verify the rendered tag matched expectations,
doesn't need to be in the test output anymore.
- Related Issue #15808 added this during development
Run the test, observe no iframe in the output.
None, test only change
Should we have a lint rule that prevents this? I know leaving a debugger breakpoint will trigger a lint failure, it seems like [puts debugerring](https://tenderlovemaking.com/2016/02/05/i-am-a-puts-debuggerer.html) should get caught by a robot, too?

Tiny cleanup of temp debugging puts from spec

---

app/views/stories/articles_search/_nav_menu.html.erb

When a user does not have any posts NOR can they create posts, we are to
hide the "Search > My Posts" section.
I have chosen not to write a test for this as it's exercising a well
tested policy and we don't have a unit test for this view.  As part of
forem/forem#17076 I introduced some cypress tests.  But that feels like
quite a bit of overkill for this feature.
Closes forem/forem#16837
Related to forem/forem#16821
To verify this behavior, I:
1. Enabled ran `bin/rails runner "FeatureFlag.enable(:limit_post_creation_to_admins)"`
2. Found a non-admin user in my local instance (e.g. `bin/rails console` and kept this open)
3. Launched the application (via `bin/startup`)
4. Went to `http://localhost:3000` and logged in as the above mentioned user.
5. I filled in the "Search" section, …

Conditionally rendering "Search > My Posts" by policy

---

app/controllers/async_info_controller.rb
app/views/admin/spaces/index.html.erb

This commit adds instruction as to what's happening when a person
toggles on this feature.  So as to not repeat knowlege, I added a
`NUMBER_OF_MINUTES_FOR_CACHE_EXPIRY` constant so the UI can reference that
instead of dropping a hard-coded 15 in the UI.
- Closes forem/forem#17097
See screen shot
More help text improves a11y-ship.

Adding copy to assist with space toggle decision

---

app/helpers/application_helper.rb
app/views/stories/tagged_articles/_sidebar.html.erb
spec/helpers/application_helper_spec.rb

Prior to this commit, we always assumed a policy based attribute would
have the "hidden" class and then we'd rely on JavaScript to toggle the
visibility.
With this approach, we are "cheating" a bit by specifically referencing
a feature flag that is the driver for the visibility behavior.
This mirrors the one-off behavior of forem/forem#16606.  Namely, when
the flag is off, we render without default hiding.  And when it's on, we
include the "hidden" attribute.
In both cases, we will still leveraged the [applyApplicationPolicyToggles.js][1]
introduced in forem/forem#17076.
An impact could be that if multiple flags are fiddling with the policy,
we could see an area disappear or wrongly remain present.  This would be
a warning to fix (the server would still enforce correct policies so
this …

Narrowing when we apply "hidden" by policy attributes

---

app/services/badges/award_contributor_from_github.rb
spec/services/badges/award_contributor_from_github_spec.rb

Resolve the following error https://app.honeybadger.io/projects/72638/faults/84843802
This is happening to the Forem fleet that doesn't have Github OAuth configured.
n/a
Spec should be enough
n/a

Add Oauth check to AwardContributorFromGithub

---

.github/workflows/issue.yml

We do not have issues labeled as `type: bug` any more. There is only issues labeled as just `bug`.
- Related to forem/forem-docs#57

Issue template: Use label bug instead of type: bug

---

app/views/admin/spaces/index.html.erb

This commit presently links to a missing page, but in consultation with
Ella, she'll be putting the page at the linked URL.
The original copy was:
> Want to learn more about spaces? Check [Admin Guide]
I chose to go with the following, as assistive technology will announce
the link's text as "more about Spaces in the Admin Guide", which I find
more a11y oriented.
> Learn [more about Spaces in the Admin Guide]
See Screenshot
Closes forem/forem#17148
None.
None.

Adding link to Spaces admin guide

---

app/assets/stylesheets/components/tables.scss
app/views/admin/users/_member_index.html.erb

Our `crayons-table` CSS transforms table headers into 100% uppercase characters, whereas the designs for the member index view calls for title casing. Since we're likely to be repeating this styling around new admin views, I've added a class variant for the `crayons-table` to achieve the desired effect. Eventually, as we work through admin refactors, we might want to flip the default behaviour to `text-transform: none`; keeping everything together in `tables.scss` will help make that straightforward as/when we want to.
- Related Issue https://github.com/forem/forem/issues/16911
Not much to see here - the table headers (in largest view) should be title cased:
NB: the text size looks a bit small to me, but I've triple checked this matches the designs at 12px.
N/A …

Admin member index: stop capitalizing table headers

---

lib/data_update_scripts/20220408154416_enable_profile_admin_feature.rb
spec/lib/data_update_scripts/enable_profile_admin_feature_spec.rb

This makes profile fields available for all forems - it has already been enabled in a few for a long time, where this will be a no-op.
There is a [follow up task](https://github.com/forem/forem/pull/17138) to remove the conditionals around this (and
remove the flag).
- Related Issue #12161 and https://github.com/forem/forem-internal-eng/issues/352
Test should be sufficient. Otherwise run data updates (bin/setup does this, or ` bundle exec rake data_updates:run`) and confirm the profile_admin flag is present and enabled at http://localhost:3000/admin/feature_flags/features
[Forem Accessibility …

Enable :profile_admin feature flag

---

app/javascript/packs/stickySaveFooter.js

This PR adds the `z-sticky` class generated at:
https://github.com/forem/forem/blob/d6421923be6f0a41edf4afec404891c2bae2cec0/app/assets/stylesheets/config/_generator.scss#L245
https://github.com/forem/forem/blob/d6421923be6f0a41edf4afec404891c2bae2cec0/app/assets/stylesheets/config/_import.scss#L87-L95
Because `sticky` class only set sticky position:
https://github.com/forem/forem/blob/d6421923be6f0a41edf4afec404891c2bae2cec0/app/assets/stylesheets/config/_generator.scss#L460-L473
- Closes #17160 …

fix: 🐛 Fix Color displaying over button in settings

---

package.json

Use the latest repo URLs (i.e., `https://github.com/forem/forem`) in `package.json`.
n/a
n/a
n/a

Use the latest repo URLs in package.json

---

lib/data_update_scripts/20220408203135_remove_profile_admin_flag.rb
spec/lib/data_update_scripts/remove_profile_admin_flag_spec.rb
spec/models/admin_menu_spec.rb
spec/requests/admin/nested_sidebar_spec.rb
spec/routing/profile_admin_routes_spec.rb

Remove profile admin feature flag, since it does nothing now.
Remove test cases built around it (modified when the guards were removed).
This flag had been enabled, and all conditional code removed, so removing the flag should be a no-op. The test cases removed were asserting the flag was a no-op where behavior had depended on it previously.
- Related Issue #12159 and https://github.com/forem/forem-internal-eng/issues/352
After running the data update script, no profile_admin feature flag should be present (this is created/enabled in a recent PR so it may enabled, then remove, the flag during the migration).
None …

Remove profile admin feature flag

---

app/views/articles/feed.rss.builder

Replaces `TimeWithZone#to_s(:format)` with `TimeWithZone#to_fs`.
Rails 7 deprecated `TimeWithZone#to_s(:format)` in favor of `TimeWithZone#to_fs`.
- https://github.com/rails/rails/pull/43772
- https://github.com/rails/rails/pull/44354
```
DEPRECATION WARNING: TimeWithZone#to_s(:rfc822) is deprecated. Please use TimeWithZone#to_fs(:rfc822) instead. (called from block (4 levels) in _app_views_articles_feed_rss_builder__990977305614084656_3900980 at /home/travis/build/forem/forem/app/views/articles/feed.rss.builder:44)
```
from https://app.travis-ci.com/github/forem/forem/jobs/566636747
No.

Replace #to_s(:format) with #to_fs

---

app/views/admin/users/index/_member_data.html.erb

This PR updates the remaining role tooltips for the Member Index View.
- Related Issue #16911 
- Related PR #17170 
To QA this PR, first ensure that you have the `member_index_view` feature flag enabled, then navigate to `/admin/users`. Next, hover over users' roles and ensure that the tooltips match the role name. For the "Resource Admin" role, the tooltip should also show the `resource_type`(Article, Badge, Comment, etc.). If a user has multiple resources, the `resource_type`s should display as a comma-separated list.
None: all UI concerns were addressed in the previous PR for this work (PR #17170) …

Member Index View: Role Tooltip Refactor Follow-Up

---

app/views/dashboards/show.html.erb
spec/views/dashboards/show.html.erb_spec.rb

As implemented, folks won't see this page if they can't create a post.
However, as our implementation drifts, we should continue to apply the
same policy.
See forem/forem#16999 for the conditional logic that redirects users.
Indirectly to forem/forem#16913
None.
None.

Adding logic to hide Create Post on empty dashboard

---

app/controllers/admin/invitations_controller.rb
app/models/user.rb
app/views/admin/invitations/index.html.erb
app/views/admin/users/index/_controls.html.erb
app/views/admin/users/index/_search_field.html.erb
cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
cypress/support/commands.js

This PR adds the search functionality to the new member invitations view. Following this PR, invitations can be searched by: username, name, or email address.
- Related Issue https://github.com/forem/forem/issues/16960
- Closes https://github.com/forem/forem/issues/17209
- When the `member_index_view` feature flag is disabled, there should be no change to the current UI, and no searchability
With the `member_index_view` feature flag enabled:
- Make sure you have some users invited! You can do this in the console e.g. `User.invite!(email: "test@something.com", name: "test user", username: "test-user", registered: false)`
- You should see a "Search invited members" field
- If you enter text and click the search button (or press enter), the page should reload with the query param …

Member index (phase 2) - Search invitations

---

config/locales/devise.en.yml
spec/system/authentication/user_logs_in_with_email_spec.rb
spec/system/user_logs_in_with_password_spec.rb

Implements language for invalid email/passwords or account lockouts that do not leak security details.
- Closes https://github.com/forem/forem/issues/16736
Sign out of your localhost Forem and sign-in with invalid email and then invalid password. An error message should appear at the top with the words `Unable to login`.
To simulate a lockout, in Rails console, search for the user you are using: `user = User.find_by(email: "email-you-are-using")`. Then attempt to login in the UI; you should see the error `Unable to login`. After testing, unlock your local user by running `user.unlock_access!` in the console.
None; only backend changes.

Show a "Unable to login" message in browser when a user is unable to login.

---

app/javascript/packs/base.jsx
app/javascript/utilities/showModal.jsx

The current generic `showModal`/`closeModal` helpers are only available in `base.jsx`, meaning they are not currently available in the app's admin area. Increasingly we are finding use cases for this minimal show/hide modal functionality in the admin area, and we want to move away from Stimulus (which we currently use to control some modals there).
This PR extracts the modal code from `base.jsx` into its own utility file. This means that older code can still access it in the current way (e.g. `window.Forem.showModal()`), but we can now also call these functions from any admin pack files (or indeed any pack files generally).
This refactor also allows us to add some clearer JSDoc comments to the code.
**Follow up task:**
Once this is merged I will push up a quick follow up task to refactor …

Move showModal/closeModal helpers into their own pack file

---

config/feed/README.md

This documentation outlines the scope and intention of the Feed
Configuration, it's primary purpose is to:
- Reference the historical context
- Establish a draft glossary
- Introduce high-level constraints
- Serve as a document to help with the task break-down
As a note, I'm looking at this document almost through the lens of
[literate programming][1].  In writing the document, I learned about and
attempted to describe the shape of this internal facing project.
Consider for a moment that we are not adding a new user facing feature
to the Forem code base.  Instead we're scoping this project as helping
ease the experimentation process regarding the feed.
In other words the scope of this project is to help name and refine
different feed strategies to understand what each strategy means. …

Adding Feed Configuration documentation

---

app/assets/stylesheets/base/typography.scss
app/views/liquids/_open_graph.html.erb

Fix bug where embed favicons were broken when embedding other Forem URLs.
- Closes https://github.com/forem/forem/issues/17238
Create an embed to another Forem URL. The embeds favicon should render correctly (if it exists).
No significant frontend changes

Fix broken favicons in embeds of other Forem URLs

---

app/services/articles/feeds/weighted_query_strategy.rb

Prior to this commit, we were looking at trusted user's reaction
counts.  This is not the desired column to be testing.
See
https://github.com/forem/forem/blob/f1d6291d0038f4e7131e750c73f31d155ddc6a1f/app/models/reaction.rb#L25-L28
```ruby
counter_culture :reactable,
column_name: proc { |model|
PUBLIC_CATEGORIES.include?(model.category) ? "public_reactions_count" : "reactions_count"
}
```
In the above code, all public reactions (hearts, unicorns, reading
list) go to public_reactions_count.  Other things go to the
`reactions_count`; which is the thumbs up and thumbs down.
- Closes forem/forem#17260
None
None

Correcting public_reactions_count

---

app/controllers/articles_controller.rb
app/services/articles/builder.rb
cypress/integration/seededFlows/loginFlows/userLogin.spec.js
spec/requests/editor_spec.rb
spec/services/articles/builder_spec.rb

There are two problems engrained in this:
1. The undocumented expectation of `/new` needed to other sites linking
with prefill information.
2. The prefill parameters being lost during the authentication process.
The first bug was introduced as part forem/forem#16536.  The second is
likely introduced as part of a Rails upgrade (namely `request.path` most
likely once included the query parameters but with our current
implementation it does not).
- Closes forem/forem#17292
Let's rely on the Cypress test on this one.
None.

Ensuring /new remains a call to action end point for DEV

---

spec/services/articles/builder_spec.rb

In #16536 the tests were updated to match a change in the
logic (rather than "needs authorization" the response was "store
location", and we checked for those values).
In #17294 we re-adjusted the meaning of the second returned value from
Articles::Builder.call, and the call sites now label the second value
as "needs_authorization" again.
Restore consistent naming in the spec as in the service object, and clarify 
the spec description text to match the meaning. 
- Related Issue #17294 follow up
Test only change. Should be green.
None

Update builder spec variable names

---

app/models/article.rb
app/models/context_notification.rb
app/services/articles/updater.rb
app/services/notifications/notifiable_action/send.rb
db/migrate/20220401071321_create_context_notifications.rb
db/schema.rb
spec/factories/context_notifications.rb
spec/models/article_spec.rb
spec/models/context_notification_spec.rb
spec/services/articles/updater_spec.rb
spec/services/notifications/notifiable_action/send_spec.rb

Added a `ContextNotification` model to track that the notifications for a certain article were sent.
The idea of Context Notifications was described by Jeremy [here](https://forem.team/jeremy/comment/85m)
When "Scheduling Posts" will be deployed, notifications about published articles will be sent in a worker which will be working independently (https://forem.team/jamie/comment/860), so we will need a way to find out which notifications have been sent already and which not. So I think that we need to deploy `ContextNotification`s before deploying "Scheduling Posts" to make it easier, that's why I created this pr.
#15858  
When an article is published, and the corresponding notifications are created (asynchronously via `Notifications::NotifiableActionWorker` and …

Context Notifications

---

app/controllers/articles_controller.rb
app/controllers/comments_controller.rb
app/controllers/omniauth_callbacks_controller.rb
spec/models/article_spec.rb

Replace links to the repo in Ruby code comments with newer URLs to avoid useless redirections.
- Related Issue #17208
n/a
n/a

Replace links to the repo with newer URLs

---

scripts/clean_fork.sh
scripts/sync_fork.sh

Replaces Git URL `https://github.com/thepracticaldev/dev.to` with the new one `https://github.com/forem/forem.git`.
- Related Issue #17208
Run `scripts/clean_fork.sh` and `scripts/sync_fork.sh` on the forked repo.
n/a

Replace Git URL with the new one

---

app/javascript/utilities/sendFollowUser.js

Enables error tracking on `sendFollowUser` in client-side. Also removes links to #2501 from the comments.
- Related Issue #2501
- Part of #17208
1. Setup Honeybadger on your local
1. Access to `/t/discuss`
1. Click "Follow" in `who to follow` on sidebar.
1. You can use the following a patch to generate an error on `POST /follows`:
```diff
diff --git a/app/controllers/follows_controller.rb b/app/controllers/follows_controller.rb
index b463758fd..87945858d 100644
--- a/app/controllers/follows_controller.rb
+++ b/app/controllers/follows_controller.rb
@@ -75,7 +75,8 @@ def create
follow(followable, need_notification: need_notification)
end
-    render json: { outcome: @result }
+    # render json: { outcome: @result }
+ …
```

Enable error tracking on sendFollowUser

---

app/services/articles/feeds/weighted_query_strategy.rb
config/field_test.yml

This commit modifies two things:
1.  The sort order of the feed.
2.  Locking in the next incumbent for the feed.
In consultation with Jamie regarding the SQL, I've switched from a WHERE
IN type clause to creating a JOIN.  This allows for the calculated
relevancy score to become a sortable value for the feed.
Second the incumbent feed is a slight modification of the past winner;
based on the results of a long running experiment.  This adjustment is
per conversations with product.
The past experiment ran since early February, so it's time to retire it,
regroup and move forward.
Closes forem/forem#17307
None.  The tests cover the experiments.  I did run the resulting queries in
blazer and did not encounter any issues.

Adjusting feed query to establish a new incumbent

---

app/views/videos/new.html.erb

Updates jQuery from 3.3.1 to 3.6.0 (latest) on `/videos/new`.
- Related Issue #17204
No.

Update jQuery from 3.3.1 to 3.6.0 on /videos/new

---

app/views/stories/tagged_articles/_sidebar.html.erb

This div tag is subsumed by the line below (e.g. `<%=
application_policy_content_tag("div"...`).  When the unclosed div is
present there is some undesirable layout offset.  When it's removed,
things line up a bit nicer.
Discovered while attempting to reproduce forem/forem#17324
- Related Issue forem/forem#17324
Before Screenshot
After Screenshot
None

Removing unclosed div tag

---

app/views/admin/spaces/index.html.erb

From Anuj:
> Going forward we will be using heavy font-weight for the titles of all
> the admin sections. So it’s good consistency-wise.
This resolves that issue.
Closes forem/forem#17327
See screen shot of updated rendering:
None.

Adding fw-heavy to spaces H1

---

config/application.rb
config/initializers/new_framework_defaults_7_0.rb

Adopt the rails 7 default for generated  namespaced UUIDs.
This addresses a noisy deprecation warning showing in specs (it points
to our re-implementation of warden's [login_as helper](https://github.com/forem/forem/blob/main/spec/support/initializers/warden.rb#L8-L13), but I suspect
the issue is within warden since our initializer seems to match the
implementation in the upstream gem).
My understanding of this is that the prior default had been to pass
the provided uuid namespace as-is if it didn't match one of a few
named constants. New behavior is to validate that any string provided
as a namespace looks like a uuid representation or fail).
If nothing breaks, the further assumption is that warden is passing a uuid as a string in the namespace method.
The comment in the …

Enable string uuid as namespace

---

app/javascript/packs/admin/users/controls.js
app/views/admin/users/index/_controls.html.erb
app/views/admin/users/index/_expand_search_button.html.erb
cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js

(this bug isn't live anywhere as it's still behind a feature flag)
My changes to the member index layouts which made sure all inputs have unique IDs had a side effect of breaking the "dot" indicator over the mobile search/filter buttons, which let users know if they have a current search term or filter input. This PR restores that functionality and adds test to make sure it doesn't regress again.
Introduced in https://github.com/forem/forem/pull/17246
- Make sure you have `member_index_view` feature flag enabled and visit `admin/users`
- Reduce your viewport to a mobile screen size
- Click the search button and enter some text
- Click the filter button
- Search button should now have a small dot over it
- Select a role to filter by
- Click the search button
- Filter button should now have …

Fix bug in search and filter indicators (admin member index)

---

app/models/space.rb
app/workers/spaces/bust_caches_for_space_change_worker.rb
spec/models/space_spec.rb
spec/workers/spaces/bust_caches_for_space_change_worker_spec.rb

We avoid busting a user cache for 15 minutes but the tag cache is 5
hours.  So we want to "nudge things along".
What this is trying to solve is the server side rendering of whether we
hide or show a button.
Related to forem/forem#17324
Related to forem/forem#17119
This is part of the UAT we're performing on Canary 1.

Busting tag cache when space changes

---

.gitpod.yml
.travis.yml

Removes `DISABLE_SPRING` variables from tests (Travis CI) and dev (Gitpod) after PR #16848.
- Follows up #16848
See the results on Gitpod and Travis CI logs.
n/a

Remove DISABLE_SPRING variables after PR#16848

---

package.json
yarn.lock

Updates cypress from 8.7.0 to 9.5.4 (latest).
- Related Issue #17338
See logs on CI.
n/a

Update cypress from 8.7.0 to 9.5.4

---

cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js

We had seen an increase in CI timeouts (no output received for 10
minutes).
Running this example (signed out user sees the pinned article)
repeatedly I was able to reproduce the failure seen in Travis, and
checking the last few times this occurred it appears to be linked to
the pinArticle.spec.js last test, which fails with an
ApplicationPolicy when pinning.
The likeliest source of this issue is the POST (pin the article) is
received concurrently with the session delete (logging the admin user
out), resulting in a race. If/when the signout occurs before the
article policy is checked (does the current user have permission to
pin an article), the cypress running stalls.
This occurred both interactively (bin/e2e or cypress open) and
headless (cypress run/CI). The error went away reliably …

Wait for pin article to complete (flaky pinArticles e2e test)

---

cypress/integration/seededFlows/adminFlows/config/authenticationSection.spec.js

The customization submission no longer reloads the page (did it once? it looks like it might have from the test comments), and clicking Authentication after submitting changes collapses the Authentication section (if the page had reloaded after a POST, clicking would have shown the section). 
When the section was hidden, the tests for labels not to be visible pass (for the wrong reason) in Firefox and Electron (CI runs travis's bundled electron version), but the findByLabelText times out in when this is run in Chrome. Moreover, because we don't reload the page after update, the behavior being checked is not happening (for example, the "Email enabled" label is still present if you show the Authentication section, it seems like it's only been passing because we click to hide the section …

e2e: Reload the page after changing authentication

---

cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js

Similar to checking that "Unpin post" is shown after pinning a post, 
wait for "Log in" to show after signing out before checking that signed 
out users can see a pinned post.
Recommended by @aitchiss in a comment on #17385 as a way to limit
false negatives (where we mistakenly check the previously signed in user's view)
- Related Issue #17385 
Since this  is a change to an e2e test, launch cypress and run the test.
None

Confirm signout happened by looking for Log in link

---

app/workers/moderator/sink_articles_worker.rb
spec/workers/moderator/sink_articles_worker_spec.rb

When a moderator flags a user, we attempt to rescore all of their articles (to make them less visible). However, the published timestamp is factored into scoring as `usable_date` in the black box, and draft articles don't have a published timestamp (so a no method error was raised).
When we rescore articles, skip the ones which have not been published (publishing a draft will cause the score calculation, it's fine to defer until then).
https://app.honeybadger.io/projects/66984/faults/83632362
None, background job. …

Skip rescoring draft articles

---

app/javascript/.storybook/main.js
package.json
yarn.lock

Removes [@storybook/addon-notes](https://www.npmjs.com/package/@storybook/addon-notes) 5 from devDependencies since [Storybook 6 deprecated it in 2020](https://storybook.js.org/blog/storybook-6-0/).
This removes 485 (effective) lines from `yarn.lock` 🎉  and 55 (effective) packages 🎉 🎉  including [poper.js v1](https://www.npmjs.com/package/popper.js/v/1.16.1) 🍿 .
- Official migration guide, which was not utilized in this PR: https://github.com/storybookjs/storybook/blob/88b134c13531408022e61737c444f9c0ac5c082a/addons/docs/docs/recipes.md#migrating-from-notesinfo-addons
- Related Issue #17398
- Original introduction of the target package: #8947
Access to https://storybook.forem.com/?path=/docs/components-buttons--default to …

Remove @storybook/addon-notes 5 from devDependencies

---

package.json
yarn.lock

Revisits upgrading `@testing-library/cypress` npm package from 7.x to 8.x, @rhymes stopped in https://github.com/forem/forem/pull/14403#issuecomment-891674975 .
> The PR https://github.com/forem/forem/pull/14324 contained a version bump to pretty-format@27.0.6 which required a later version of node than our buildkite builds can currently use. As a result, all of our latest buildkite builds are failing with the error:
> ```
> error pretty-format@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 \|\| ^12.13.0 \|\| ^14.15.0 \|\| >=15.0.0". Got "14.14.0"
> --
>   | error Found incompatible module.
> ```
> This PR reverts the change until we are able to upgrade the node version in buildkite …

Update @testing-library/cypress from 7.0.7 to 8.0.2

---

app/views/layouts/admin.html.erb

Updates Bootstrap from 4.4.1 to 4.5.3 on `/admin` to update jQuery from 3.4.1 to 3.5.1.
- Bootstrap 4.5 docs: https://getbootstrap.com/docs/4.5/getting-started/introduction/
- jquery@3.4.1 vulnerabilities (snyk): https://snyk.io/vuln/npm:jquery@3.4.1
- Related Issue #17337
- Closes #17204
Access to `/admin` on a test instance to confirm if there is no regression.
No regression should be confirmed.

Update Bootstrap from 4.4.1 to 4.5.3

---

lib/data_update_scripts/20220422141135_disable_creator_onboarding_feature_flag.rb
spec/lib/data_update_scripts/disable_creator_onboarding_feature_flag_spec.rb

As per https://github.com/forem/forem/issues/16188 this DUS should make sure all Forems have the `creator_onboarding` feature flag disabled.
I haven't actually removed the feature flag, since the issue calls specifically for it to only be disabled
- Closes https://github.com/forem/forem/issues/16188
I think the tests cover it, but you could
- On `main`, locally make sure you have the `creator_onboarding` feature flag enabled
- Check out this branch, run `bin/setup && bin/startup`
- Check that the `creator_onboarding` feature flag has been switched to disabled  
N/A …

Disable creator onboarding feature flag

---

spec/system/user_views_logo_spec.rb

This is a small follow up to https://github.com/forem/forem/pull/17404 where we made sure the `creator_onboarding` feature flag was disabled via DUS. @djuber noticed we still had references to the feature flag in this rspec test, even though the code it's testing doesn't vary its logic based on the feature flag anymore.
This PR removes that setup and updates the description to be more generic.
- Related Issue https://github.com/forem/forem/issues/16188
- Related Issue https://github.com/forem/forem/pull/17404
I think it's enough to check the build passes 😄 
N/A
will share this change with the people who need to …

Remove redundant feat flag setup in spec

---

app/services/articles/feeds/variant_query.rb
spec/services/articles/feeds/variant_query_spec.rb

This commit does three things:
1.  Breaks the inheritance of the VariantQuery.
2.  Revisits the in-line documentation to better reflect current state.
3.  Removes branching logic that we don't need.
My goal is to have a VariantQuery that is what we need, conforms to the
method interface of WeightedQueryStrategy but does not rely on it.
After we merge this, we can observe if things break on DEV and fallback
to WeightedQueryStrategy if this doesn't work.  Once the
`Articles::Feeds::VariantQuery` has fledged on it's own, we can remove
the feature flag and then finally remove the weighted query strategy.
But that's the future steps.
I also added tests that help verify that the "not logged in" query path works as well.  We're presently not using this but I know that's part of a desired …

Tidying up the Articles::Feeds::VariantQuery

---

app/models/articles/feeds.rb
config/feed-variants/20220422-jennie-variant.json
config/field_test.yml

Add a new feed-variant as per Jennie's request. Shoutout to @jeremyf and @msarit 
n/a
n/a
n/a

Create new feed-variant 20220422

---

app/controllers/stories/articles_search_controller.rb
app/controllers/stories/tagged_articles_controller.rb
app/controllers/stories_controller.rb

As I was looking into the implementation details of the `/t/:tag_name`
relevancy feed I noticed an instance variable that we do not need.
Below are the results of looking for the instance_variable
`@article_index` or a potential `article_index` local variable or method name.
```shell
❯ rg "@?article_index"
app/controllers/stories_controller.rb
28:    @article_index = true
131:    @article_index = true
162:    @organization_article_index = true
app/controllers/stories/tagged_articles_controller.rb
18:      @article_index = true
app/controllers/stories/articles_search_controller.rb
7:      @article_index = true
app/views/articles/_single_story.html.erb
26:          <% if story.cached_organization && !@organization_article_index %>
32:          <a href="/<%= story.cached_user.username %>" …
```

Removing unused instance variable

---

app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx

The MultiSelectAutocomplete component (as used in the editor tags field) allows users to free-type their selection and 'select' it automatically by typing a space or a comma. When typing quickly, we were seeing a bug this resulted in fetched suggestions being displayed when the input had already cleared/reset (see reproduction in https://github.com/forem/forem/issues/16966).
[A previous PR](https://github.com/forem/forem/pull/17120) attempted to fix this issue by cancelling any in progress suggestions fetch when the user made their selection. Unfortunately, this wasn't robust enough (I suspect because there is a short time when the network request _has_ completed, but Preact is still processing what it returned).
This PR instead adds a quick check once suggestions have been fetched, …

Multi-select autocomplete - ignore fetched suggestions if input already cleared

---

app/models/user.rb
app/services/mailchimp/bot.rb
app/services/moderator/banish_user.rb
app/services/users/delete.rb
config/locales/services/en.yml
config/locales/services/fr.yml
spec/services/mailchimp/bot_spec.rb

Right now, Forem admins on Forems that use Mailchimp have to manually delete users from Mailchimp. This builds that process into our app by sending the request via API.
There are some product decisions to consider, which I've shared in our internal Slack: https://forem-team.slack.com/archives/CAA200SH5/p1650557891042839
- https://github.com/forem/internalCommunity/issues/328
QAing this is a bit of a hassle. That said, I'd really appreciate it if someone would go through with it! 🙏 
1. DM me on Slack for the necessary ENV variables
2. Run this setup script in `rails console`:
```ruby
Settings::General.mailchimp_api_key = "api_key_that_I_give_you"
Settings::General.mailchimp_newsletter_id = "list_id_that_I_give_you"
gibbon = Gibbon::Request.new(api_key: Settings::General.mailchimp_api_key) …
```

Permanently delete users from Mailchimp automatically

---

app/controllers/search_controller.rb
app/queries/homepage/articles_query.rb
app/services/search/article.rb
spec/requests/search_spec.rb

A pentester (or curious user) might send an invalid sort direction in the url params.
We previously passed the provided parameter from the url to the AR query, and would see an error raised if invalid data were passed (like `sort_direction=hhg`).
Remove invalid data, which relies on the default sort direction in each query class overriding a provided nil value, for example in [Search::Comment](https://github.com/forem/forem/blob/main/app/services/search/comment.rb#L41).
Update a few of the search classes to ensure we only sort with a valid direction.
https://app.honeybadger.io/projects/66984/faults/85115617
1. all existing specs should pass
2. when sending an invalid sort direction like "invalid", a default order should be used instead (or sorting skipped) - request spec added should pass …

validate sort direction

---

app/liquid_tags/forem_tag.rb
spec/liquid_tags/unified_embed/registry_spec.rb

This PR sharpens the regular expression that matches Forem-specific links when embedded.
This is my first solution iteration; PR review may reveal more robust regex options. 😅
- Closes https://github.com/forem/forem/issues/16922
Forem-specific embeds should work as expected; embeds of the naked Forem URL (e.g. `https://dev.to` or `https://dev.to/`) will trigger the fallback embed (to avoid validating URLs like `https://dev.to//`).
None; no frontend changes

Sharpen RegEx that matches Forem-specific links

---

app/controllers/dashboards_controller.rb
spec/system/dashboards/user_visits_dashboard_spec.rb

This PR ensures that counts for the user's series (collections) show on every Dashboard Tab.
- Closes https://github.com/forem/forem/issues/16914
Visit `/dashboard`, click through all the Dashboard views (Following Users, Following Organizations, etc) and ensure that the Series count shows in each view.
None

Show Series counts on all Dashboard Tabs

---

spec/requests/stories/feeds_spec.rb

This PR does three things:
1. Removes a feature flag reference## What type of PR is this? (check all applicable)
This PR does three things:
1. Removes a feature flag reference
2. Renames optimized to the large_forem_experimental (a value that
occurs in the code base)
3. Wraps two specs in a similar context as a later appearing spec (hence
the larger appearing change due to indentation adjustments)
Closes forem/forem#17510
None, this is a spec only change.
None.

Removing unused feature flag reference

---

app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb
app/lib/constants/settings/general.rb
app/models/settings/general.rb
app/models/user.rb
app/services/mailchimp/bot.rb
app/views/admin/settings/forms/_newsletter.html.erb
app/views/users/_notifications.html.erb
config/locales/helpers/en.yml
config/locales/helpers/fr.yml
lib/data_update_scripts/20220429142653_remove_mailchimp_sustaining_members_newsletter.rb
spec/lib/data_update_scripts/remove_mailchimp_sustaining_members_newsletter_spec.rb
spec/requests/admin/configs_spec.rb

This removes the concept of sustaining memberships from the system,
and logic related to or dependent on it.
This does not remove the monthly_dues column from the users table (todo).
- Closes #17498
Please let nothing break. Specifically forms in the admin area around mailchimp newsletters were touched and should be spot checked.
None
issue template so …

Remove sustaining member newsletter, and its settings

---

db/migrate/20220429150448_drop_monthly_dues_from_users.rb
db/schema.rb

After #17514 was merged, there are no users of the monthly_dues column. It may be removed.
- Related Issue #17514 and #17498
Running `rails db:migrate` (drop), `db:rollback` (add column back), and `db:migrate` (drop once more)should work without any errors.
And nothing should break.
None

drop monthly dues from users

---

.github/workflows/codeql-analysis.yml
.github/workflows/issue.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

app/javascript/analytics/dashboard.js

Pass options correctly to chart.js on (frontend of) `articles#stats` to remove unnecessary ticks (after the decimal point) and grid lines on y-axis to revert #2037's intention after #3102.
This would lead changes mainly on stats for articles with less 10 pageview per day in specific spans (in 7 days or 30 days).
- Closes #17433
- Relates to #3102 (cause of regression)
- Original implementation: #2037
- Docs on upstream (chart.js 3.7.1)
- Axes: https://chartjs.org/docs/3.7.1/axes/
- Point configuration: https://www.chartjs.org/docs/3.7.1/configuration/elements.html#point-configuration
| before | after |
|-|-|
| ![](https://user-images.githubusercontent.com/10229505/165303114-124e4f12-12a8-4884-a299-fcfb6219069d.png) | …

Pass options correctly to chart.js on articles#stats

---

app/views/users/show.html.erb

We noticed some funky behaviour with caching of the `profileDropdown` JS pack on a user's profile page, and it seems the root of this is because the pack was declared inside a cached rails view. Generally, we shouldn't declare JS packs in the middle of files like this anyway, with our convention being to declare packs outside of the HTML, either at the very top or very bottom.
This PR makes a small change so we won't see these caching issues in future.
- Closes https://github.com/forem/forem/issues/17441
The existing tests should cover this one
N/A …

Move pack declaration outside of cached rails view

---

app/models/articles/feeds.rb
app/models/articles/feeds/relevancy_lever.rb
app/models/articles/feeds/variant_assembler.rb
app/services/articles/feeds/variant_query.rb
config/feed-variants/20220415-incumbent.json
config/feed-variants/20220422-jennie-variant.json
config/feed-variants/README.md
config/feed-variants/original.json
spec/models/articles/feeds/relevancy_lever_spec.rb

Prior to this commit, the SQL fragments included variables that were set
configured at a global level.
With this commit, we're now saying that each lever "knows" what variable
it needs; and providing the means at lever declaration time to "say"
what those variable names are.  (e.g. `Articles::Feeds::LEVER_CATALOG`).
Then as part of the variant configuration (in the
`./config/feed-variants/*.json` files) we now include the expected value
of those parameters; which by convention (and coercion) are integers.
This relates to forem/forem#17584 because we want to move from a
privileged user reaction that has two values (`negative` and `positive`)
into four values (`very_negative`, `negative`, `positive`, and
`very_positive`).  To do that, we'll create a new lever; but that's for
another pull …

Refactoring so relevancy levers define expected variables

---

app/models/ab_experiment/goal_conversion_handler.rb
app/models/article.rb
config/field_test.yml
spec/models/ab_experiment/goal_conversion_handler_spec.rb
spec/models/article_spec.rb
spec/rails_helper.rb

We have page view and comment view "goals" but have not looked at
publication "goals".  We're using these "goals" to help us refine the
feed towards sustainable engagement and community health.
The conjecture on publication goals is that the content on the feed
itself can nudge folks in their decision to publish posts.
Closes forem/forem#17585
The new (and existing) tests cover the changes.
None.

Adding a field test option for post publishing goals

---

app/views/api/v0/organizations/show.json.jbuilder
spec/requests/api/v0/organizations_spec.rb

Ensuring that the `GET /api/organizations/:username` has the organization ID.
Closes forem/forem#17590
None.  The tests cover this behavior.
None.

Adding ID to API organization response document

---

app/javascript/article-form/components/ArticleCoverImage.jsx
app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
app/javascript/article-form/components/__tests__/Close.test.jsx
app/javascript/article-form/components/__tests__/Form.test.jsx
app/javascript/article-form/components/__tests__/Help.test.jsx
app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
app/javascript/article-form/components/__tests__/Options.test.jsx
app/javascript/article-form/components/__tests__/PageTitle.test.jsx
app/javascript/article-form/components/__tests__/Preview.test.jsx
app/javascript/article-form/components/__tests__/Tabs.test.jsx

Some of the UI unit tests using the `testing-library` lib are misusing queries and not applying best practices. This can cause flaky tests, i.e. not catching bugs because we're not looking at the correct elements. This PR aims to improve tests in that regard. 
I used this [blog post](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library) by Kent C. Dodds to base my changes. I didn't refactor all of the tests files because then the PR would get too big. 
My biggest concern here was the use of `.toBeDefined()` paired together with the `queryBy*` queries. This query returns `null` or the element. Whereas the `.toBeDefined()` matcher checks for `undefined` or a truthy value. This can lead to a false positive scenario, where the query returns `null` and the matcher will check …

Improves UI unit tests by correcting wrong use of queries

---

spec/services/articles/feeds/variant_query_spec.rb

As I was working on adding a new variant, I discovered that not all of
our variants were being tested.  This had to do with a faulty assumption
regarding the scoping of the `variant` local variable.
The change ensures that we declare a subject once for each defined
variant within their own `describe` block.  Without that `describe`
block, you end up repurposing the same subject.
I found this because I made a deliberate error in the upcoming variant
and checked the tests.  They passed.
Related to forem/forem#17584
None, you'll need to read the code.
None, these are only tests.

Fixing variant query specs

---

app/controllers/reactions_controller.rb
app/models/reaction.rb
app/policies/reaction_policy.rb
spec/policies/reaction_policy_spec.rb
spec/requests/reactions_spec.rb

There are 2 things going on in this pull request:
1. Reducing duplication of knowledge, by favoring constants found in
Reaction.
2. Creating and enforcing the policies regarding the different
categories of reactions.
I chose to conflate these two as I was working on developing the
ReactionPolicy's finder method.
- Closes forem/forem-internal-eng#454
- Related to forem/forem#17628
Let's rely on the tests for this one.
None.

Ensuring only privileged users may give certain reactions

---

app/assets/stylesheets/ltags/TagTag.scss
app/assets/stylesheets/ltags/UserTag.scss
app/helpers/application_helper.rb
app/views/organizations/_liquid.html.erb
app/views/tags/_liquid.html.erb
app/views/users/_liquid.html.erb

If the brand-colors combination for a user, organization or tag is not accessible, the "Follow" button on their embed does not render clearly. This PR styles these Follow buttons as standard `crayons-btn--secondary`.
- Closes https://github.com/forem/forem/issues/17564
On your localhost, look up links for a user profile, organization profile and tag page, then create embeds for them. The "Follow" button in each embed should have `crayons-btn--secondary` styling.
None

Make Follow Buttons in User, Org and Tag Embeds "secondary"

---

.lintstagedrc.js

Related to forem/forem#17612
Related to forem/forem#17634
Looking at the following error, I *think* this might address the
observed issue.
```shell
✖ jest --findRelatedTests:
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: https://jestjs.io/docs/configuration
```

Passing --passWithNoTests to jest linter

---

app/policies/article_policy.rb

Prior to this commit, if we didn't have an instance of `Article` we
likely had the class `Article`; we would then run a potentially VERY
expensive query (`SELECT user_id FROM articles;`) to provide an
answer; namely if all of the articles are written by the same user then
yes this user is the author.
With this commit, when you're authorizing the `Article` class, let's
just say "Nope, this user isn't the author".
Related to forem/forem#630
Closes forem/forem#17604
None.
None.

Replacing a potentially expensive query

---

app/javascript/packs/articleModerationTools.js
app/models/async_info.rb
app/policies/article_policy.rb
spec/models/async_info_spec.rb

The [`ArticlePolicy#moderate?`][1] method answers the questions around article
moderation.
At present this change does not introduce any significant changes (aside
from the JS logic loop).  The next "step" is to adjust the
`ArticlePolicy#moderate?` method to test if the user has a moderator
role.
Further, we'd need to see what is available on the action panel.
[1]:https://github.com/forem/forem/blob/5ac3216a5ae68edc0a0a41821c3ccf49ff100efd/app/policies/article_policy.rb#L160-L174
Related to forem/forem#17606
None.
None.

Moving from user.trusted tests to policy tests

---

app/views/users/onboardings/_task_card.html.erb
spec/system/onboardings/user_completes_onboarding_spec.rb

Prior to this commit, if the Forem limitted article creation only to
admins, when a new user would sign-up their call to action was to
"Create a Post".  If that new user clicked on the button, they would get
an action unauthorized error.
With this commit, the call to action for Creating a Post is hidden to
that user.
The `users/onboardings/_task_card.html.erb` is rendered as part of the
home page.  The home page, due to our [EdgeCacheSafetyCheck][1], does not
allow us to access attributes of the current user (e.g. are they an
admin); which means we can't add a `if policy(Article).create` to the
HTML erb.  We must instead use the [`application_policy_content_tag`][2]
as well as the [AsyncInfo][3] to help inform the
[applyApplicationPolicyToggles.js pack][4] of the conditional rendering. …

Ensuring we don't render call to action when unauthorized

---

app/views/stories/tagged_articles/_sidebar.html.erb

This PR displays the Create Post button on tag pages, whether or not a submission template exists for the tag. If a submission template exists, the New Post body displays the template.
In addition, this button is hidden for non-admin members in comment-only Spaces.
- Closes https://github.com/forem/forem/issues/16978
For spaces that allow everyone to post:
(1) As as admin, navigate to `Admin >> Content Manager >> Tags`, and choose the tag you wish to test. Under `Submission template`, enter some text and save.
(2) In the Forem, navigate to your chosen tag's page. You should see the `Create Post` button. Click the button to create a post. Your new post should be populated with the content you entered in `Submission template`.
For spaces that are comments-only:
(1) As an admin, navigate to …

Display "Create Post" button on tag page, regardless of submission template presence

---

app/models/ab_experiment/goal_conversion_handler.rb
app/models/reaction.rb
config/field_test.yml
spec/models/ab_experiment/goal_conversion_handler_spec.rb
spec/models/reaction_spec.rb

This commit adds three new feed experiment goals:
* user publishes four posts within a week
* user reacts with a "heart", "unicorn", or "reading list" to an article
* user reacts with a "heart", "unicorn", or "reading list" to an article
four times in a week
In addition it adds it to the existing experiment.  Adding it to the
existing experiment is acceptable because:
1. We can ignore the results
2. The experiments are structured such that these new goals could be met
with prior data.
3. Both variants are playing by the same rules, so the results relative
to each other are valid.
**There is a nuanced assumption in how we handle reactions:**
This implementation does not count by unique article reactions. However,
most folks will :heart: , :unicorn: , and :bookmark: in one swoop; thus
those …

Adding more goals to feed experiments

---

spec/queries/comments/community_wellness_query_spec.rb

There was a problem with the way we are generating the comments for the users in the query spec. The easiest way AFAICT is the way we do it now, which loops from 0 to 33 and calculates `(2+ (i * 7))`. This makes it so 2 comments are created 2 days ago (week 0), then 9 days ago (week 1), then 16 days ago (week 2), and so on.
This comment creation won't match perfectly with the "number of weeks ago since rollout date" (`2022-05-01`) throughout the week (because of the _rigidness_ of creating the days with the formula above). Making the calculation with the oldest comment date post the rollout date (`oldest_comment_date_post_rollout`) will continue to ensure we're restricting the date here (original the purpose of the spec).
- Related Issue #17310
Spec fix only
N/A
None

Fix spec calc that checks date filter expectation

---

app/models/ab_experiment/goal_conversion_handler.rb
config/field_test.yml
spec/models/ab_experiment/goal_conversion_handler_spec.rb

With comments, publishing articles, and reactions we had symmetry on two
goals:
- Create a _subject_ (e.g. Comment, Published Article, Reaction)
- Create four _subjects_ within a week.
For page views we only had "Create four _subjects_ within a week."  This
PR addes the "Create a _subject_".
To do this required adjusting some tests as they were too specific in
nature (looking at an expected count).
In addition, in consultation with Jennie, I've updated the experiment
order to better reflect some hierarchical importance.
**Rollback considerations:**
This also includes a feature flag that we can explicitly disable if we
overload the application with workers handling reaction goals.  Using
`FeatureFlag.accessible?(:field_test_event_single_create_pageview)`
returns `true` unless we explicitly …

Adding page view goal for experiments

---

app/liquid_tags/open_graph_tag.rb
app/services/open_graph.rb
app/views/liquids/_open_graph.html.erb
spec/fixtures/files/guides.rubyonrails.org-routing.html
spec/liquid_tags/unified_embed/tag_spec.rb

Prior to this commit, our fallback HREF was using only the URL's
domain (e.g. `guides.rubyonrails.org/routing.html`) instead of the
provided URL (e.g. `https://guides.rubyonrails.org/routing.html`).  This
resulted in the link resolving to
`<url-of-article>/guides.rubyonrails.org/routing.html`)
With this commit, we're using the given URL for the HREF.
An interesting side note, the Ruby on Rails guides includes an
`og:title` but not an `og:url` so we hit the fallback condition.  Could
we use the given URL if `og:url` does not exist?
Fixes forem/forem#17679
Related to forem/forem#17001
Spin up a local instance:
- go to `/new`
- In the new post's body add `{% embed https://guides.rubyonrails.org/routing.html %}`
- Click Preview
- Then click the embed link; you should be taken to …

Ensuring that embed fallback renders URL

---

app/assets/stylesheets/views/article.scss

The corresponding issue #16455 proposes resizing the image to retain correct aspect ratio via image manipulation done server side. While this can certainly be done, it comes at a slight cost of maintenance and perhaps performance. The cover image is something that is higher touch than setting a company logo or profile picture. Given that, I wanted to propose this css first solution that accomplishes the goal of maintaining the aspect ratio WITHOUT further image manipulation done server side. To me, this gets us moving in the right direction while allowing us to take a half step back and explore if there is a true need to "hard" scale the cover image. This approach also avoids the cumulative layout shift that Pawel mentioned as we are not changing the image height and width inline. …

change the object-fit to scale down to retain ratio on cover images

---

app/assets/stylesheets/views/article-form.scss

When uploading a cover image the preview could sometimes be cut off if the ratio is incorrect. So this applies the same `scale-down` css property that we're using on the actual cover image for consistency.
- closes #17448 
- related PR for cover image #17347 
Upload a cover image and verify that the preview isn't be cut off
no

apply same `scale-down` property to preview cover image

---

app/assets/stylesheets/views/article.scss
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/ArticleCoverImage.jsx
app/views/articles/_single_story.html.erb
app/views/stories/feeds/show.json.jbuilder
spec/requests/stories_index_spec.rb

This PR makes the feed image to be more consistent with the cover image by maintaining the correct aspect ratio. You'll notice in the before/after screenshots that it has a gray background now. This is how we treat cover images. I continued this here.
- Related Issue #16455
- Closes #17447 
No

make feed image consistent with cover image

---

config/initializers/devise.rb

In our OAuth providers we didn't specify all of their scopes explicitly. This wasn't an issue because the underlying Omniauth gems provide a default scope, but it was brought up to our attention that it's better to explicitly specify our scopes for security reasons.
There shouldn't be any real differences in how the code will work, we're just explicitly requesting the scopes we need instead of relying in the upstream gem default scopes.
- Closes https://github.com/forem/forem-internal-eng/issues/459
I ran through the updated providers and didn't find any issues
1. Enable [Google](https://developers.forem.com/backend/auth-google)/[Facebook](https://developers.forem.com/backend/auth-facebook) OAuth flows
2. Sign in/up using those providers
3. Shouldn't find any problems with step 2 …

Add missing explicit scopes to Omniauth adapters

---

app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.test.jsx
app/javascript/utilities/runtime.js

This PR enhances the DateRangePicker component to display dates in format "MM/DD/YYYY" when the user's browser locale is "en-US" and "DD/MM/YYYY" in all other cases.
(The DateRangePicker component is still in "BETA" in Storybook and is not live anywhere in the app)
- Related Issue https://github.com/forem/forem/issues/17493
- Run `yarn install && yarn storybook` locally and navigate to the `BETA>DateRangePicker` story
- Check your browser preferences, and set your language so that "en-US" (US English) is your preferred language
- Refresh the storybook window to make sure the component picks up your changes
- Check that placeholder text reads "MM/DD/YYYY"
- Try selecting a date from the picker, and check it populates in the input in the correct format
- Now change your browser language …

DateRangePicker component: localize US vs non-US date format

---

app/views/admin/users/index.html.erb
cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js

This PR adds an "empty state" to the Member Index View table, which is shown when no results are returned when searching or filtering for a user.
- Closes #17490 
To QA this PR, navigate to `/admin/member_manager/users` and ensure that when there are no search or filtered results, that you are shown the "empty state":
There shouldn't be! …

 "Empty State" for Result-less Search and Filter

---

app/models/ab_experiment.rb
config/field_test.yml
spec/models/ab_experiment_spec.rb

Prior to this commit, as a matter of undocumented practice, we would
overwrite past experiments with upcoming experiments.
With this commit, we're leveraging a feature of the field_test gem:
declaring a winner.  Instead of overwriting an experiment with the next
experiment, we're going to declare the expiring experiment's winner then
prepend to the ./config/field_test.yml the new experiment.
The [field_test/app/views/field_test/experiments/index.html.erb][1] then
uses logic to first render "active" experiments and "completed"
experiments.  A "completed" experiment is one in which we've declared a
winner.
[1]:https://github.com/ankane/field_test/blob/master/app/views/field_test/experiments/index.html.erb
Closes forem/forem#17816
You can spin up a local instance, log in as an admin and go …

Exposing past feed experiments in /admin/abtests

---

app/models/articles/feeds/variant_assembler.rb
app/services/articles/feeds/variant_query.rb
app/views/field_test/experiments/_experiments.html.erb
spec/models/articles/feeds/variant_assembler_spec.rb

Prior to this commit, the `/admin/abtests` was fully rendered by the field_test gem (see https://github.com/ankane/field_test/blob/master/app/views/field_test/experiments/index.html.erb and https://github.com/ankane/field_test/blob/master/app/views/field_test/experiments/show.html.erb).
With this commit, we're pre-pending our own partial (e.g. `app/views/field_test/experiments/_experiments.html.erb`) in the view paths; which means instead of rendering https://github.com/ankane/field_test/blob/master/app/views/field_test/experiments/_experiments.html.erb we render our newly created `app/views/field_test/experiments/_experiments.html.erb`)
Why the ugly antics in the view?  As I'm not fully certain if this will "meet" the full needs of those monitoring the experiments.  I'm also constructing …

Adding more context to `/admin/abtests`

---

config/feed-variants/20220603-variant-a.json
config/feed-variants/20220603-variant-b.json
config/field_test.yml

This commit contains two separate but related changes:
1. A check-list for creating a new experiment.
2. A new experiment along with declaring a winner for the previous experiment.
Below are the diffs of the two new variants versus the incumbent for the
experiment:
```
❯ diff config/feed-variants/20220603-variant-b.json config/feed-variants/20220518-variant.json
3,4c3
<   "description": "As 202205518-variant but with modificiation to `order_by` lever.",
<   "order_by": "final_order_by_random_weighted_to_score",
---
>   "order_by": "relevancy_score_and_publication_date",
```
```
❯ diff config/feed-variants/20220603-variant-a.json config/feed-variants/20220518-variant.json
3d2
<   "description": "As 202205518-variant but with modificiation to `matching_positive_tags_intersection_count`.", …
```

Adding feed experiment for 2022-06-03

---

app/models/articles/feeds.rb
app/services/articles/feeds/variant_query.rb

The commit includes three changes that work to allow us to "seed" the randomization.  When using the same seed, and randomizer should/must return the same sequence of numbers.
First, I added the "seed" parameter to the variant query.  If you want the same sequence of random numbers from query to query, pass the same seed.  Otherwise, we'll use a Ruby generated random seed.
Second, I added a virtual column to the virtual `article_relevancies` table.  If you provide a seed, and call the query twice, the first row in each of `article_relevancies` will have the same `randomized_value`, likewise the second row, etc.
Third, I amended the existing `order_by_lever` that had a `RANDOM()` postgresql function call.  I replaced that with the `randomized_value` which is computed based on the provided …

Adding ability to "seed" feed's SQL randomization

---

app/controllers/admin/articles_controller.rb
app/javascript/admin/controllers/article_controller.js
app/views/admin/articles/_individual_article.html.erb
config/locales/controllers/admin/en.yml
config/locales/controllers/admin/fr.yml
cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
cypress/integration/seededFlows/adminFlows/articles/unpinArticle.spec.js

Before: Was a link, did not use flash as expected
After: Now a button, uses flash as expected
Unpinning an article did not show a confirmation message. While investigating, I noticed that there was a related issue -- the "Unpin" button was implemented as a `link` not a `button`, and thus an background/ajax request, not a form.
This PR changes the "Unpin" button to be a `button` and updates the `flash` confirmation message for "unpinning". (It seems we're using `flash[:danger]` for delete-type actions?) 
- Closes #17417 
- 💬 https://github.com/forem/forem/pull/15090#issuecomment-954957033 for additional background.
* Log in as an admin
* Navigate to Content Manager > Posts
* Pin a post, "Article Pinned!" green banner
* Unpin that post, "Article Unpinned!" red banner
As I understand the …

Unpin article should behave more like Pin article

---

config/initializers/new_framework_defaults_6_1.rb

Slowly updating our rails framework. 
- Enable `has_many_inversing` as a useful feature
- All `active_storage` and `action_mailbox` updates are moot because we don't use them.
https://github.com/forem/forem-internal-eng/issues/463
Boot up the rails app normally and things should work as expected
n/a

Enable/remove some Rails 6.1 framework default

---

app/models/article.rb
spec/models/article_spec.rb

Active Record caches attributes, which would cause problems when removing the `spaminess_rating` column. The recommended fix is to first ignore it in the model, deploy this change, then wrap the migration in a `safety_assured { ... } block`.
- Related Issue #17222 
N/A
N/A
appropriately. …

ignore spaminess rating to safely remove database column

---

app/views/admin/tags/index.html.erb

Fixed spec warnings like this 
> Passing two trailing hashes to `sort_link` is deprecated, merge the trailing hashes into a single one.
appropriately.

Fixes `sort_link` specs warning

---

config/initializers/new_framework_defaults_6_1.rb

The last default of 6.1
This is safe because we are already using :lax as the session store default
https://github.com/forem/forem/blob/77a00d242af81e2f68df2744203dde0115010140/config/initializers/session_store.rb#L21
https://github.com/forem/forem-internal-eng/issues/463
- Users should not be logged out upon boot.
n/a

Enable cookies_same_site_protection :lax

---

app/models/articles/feeds.rb

In the general sense we have an existing `order by` that follows the
following format: `order(x) = f(x) * rand() ^ ( 1 / g(x))`
For the present [20220603-variant-b][1], `g(x)` is the article’s score.
And `f(x)` is 1.
This pull request introduces a few named variations for the above
`order(x)` formula.
The three named formats each use a different `g(x)` function; namely
`greatest(0.1, ln(1 + greatest(0, public_reactions_count)))`.  The more
public_reactions the article has the closer to zero the resulting
positive number will be.  And raising a random number, with range
`(0..1)`, to the inverse of that number will tend to mean that artciles
with many reactions will tend to group towards the higher end of the
random range, whereas articles with few reactions will have a more even …

Adding additional order by levers

---

app/javascript/onboarding/Onboarding.jsx

Fixes a bug where the FocusTrap was stopping users from interacting with the RuntimeBanner (mobile devices) during onboarding.
- Closes #17876
To test this manually:
2. Go through onboarding on a mobile device (or simulate it)
3. The runtime banner should be able to be dismissed or clicked through into the mobile apps
Here's a video of it working on my local environment:
https://user-images.githubusercontent.com/6045239/173097594-e7646a9e-95c2-4ab5-aa84-c3c6552fc344.MP4
I believe there are no accessibility concerns here as the Focus trap isn't quite necessary here compared to a modal

Enable clickOutsideDeactivates on Onboarding FocusTrap

---

app/controllers/admin/invitations_controller.rb
app/controllers/admin/users_controller.rb
app/lib/constants/role.rb
app/queries/admin/users_query.rb
spec/queries/admin/users_query_spec.rb

I had looked at using `User.with_any_roles` but that creates one User query per role passed.  Which is not ideal, given that we want to have an ActiveRecord::Relation object on which we'd paginate.
This adjustment does it's best to mimic Forem's role structure and adhear to how Rolify builds the underlying query.
An astute reader will notice that in these specs we use `role: "admin"` and `roles: ["Admin"]`; the primary reason relates the user interface being worked on in forem/forem#17884.  It is my understanding that the `role` approach and `roles` approach will be separated by a feature flag (we're rolling out the `roles` approach).
On adjustment I made was to move from an :options hash to keywords.  By favoring keywords, out Language Server Protocol (LSP) prompts will provide more …

Allowing UserQuery to filter on multiple roles

---

config/initializers/new_framework_defaults_7_0.rb

This is the first PR to bring up forward framework 7.0
- Remove ActiveStorage options since we don't use them
- Enable ActionMailer timeout.
https://github.com/forem/forem-internal-eng/issues/468
n/a

Enable Rails framework 7.0's ActiveStorage & ActionMailer

---

package.json
yarn.lock

Reverts forem/forem#17915
Checking the changelog for this bump, everything looked fine to me, but since it merged I'm seeing the following error when trying to commit new changes
```
node:internal/modules/cjs/loader:933
const err = new Error(message);
^
Error: Cannot find module '../doc/directives.js'
```
Let's revert and take more time to investigate

Revert "Bump lint-staged from 12.4.1 to 13.0.1"

---

app/models/articles/feeds/variant_assembler.rb
app/services/articles/feeds/variant_query.rb
config/feed-variants/20220415-incumbent.json
config/feed-variants/20220422-variant.json
config/feed-variants/20220509-variant.json
config/feed-variants/20220518-variant.json
config/feed-variants/20220525-variant.json
config/feed-variants/20220603-variant-a.json
config/feed-variants/20220603-variant-b.json
config/feed-variants/README.md
config/feed-variants/original.json

Prior to this change, we setup our feed variant query to have a cached randomization seed.  For a given user this seed is cached for 15 minutes.  The goal of this is to provide mostly consistent sort orders on the feed articles during that 15 minute window.
With this change, we allow for a feed variant to say ignore the cached seed and generate a new one for this call.
I have also added explicit settings to each of the feed variants to reflect our desired intentions for those features.
Relates to
- forem/forem#17833
- forem/forem#17826
Closes forem/forem#17940
None.
None.

Adding VariantQuery reseed randomization option

---

config/feed-variants/20220617-variant-a.json
config/feed-variants/20220617-variant-b.json
config/feed-variants/20220617-variant-c.json
config/field_test.yml

New experiment based on conversations:
```
❯ diff config/feed-variants/20220617-variant-a.json config/feed-variants/20220617-variant-b.json
0a1
>
3c4
<   "description": "Blend of 20220603-variant-b and 20220603-variant-a",
---
>   "description": "Derived from 20220617-variant-a but with re-seeding every request",
5c6
<   "reseed_randomizer_on_each_request": false,
---
>   "reseed_randomizer_on_each_request": true,
```
```
❯ diff config/feed-variants/20220617-variant-a.json config/feed-variants/20220617-variant-c.json
0a1
>
3,4c4,5
<   "description": "Blend of 20220603-variant-b and 20220603-variant-a",
<   "order_by": "final_order_by_random_weighted_to_score",
---
>   "description": "Derived from 20220617-variant-a but with alternate order by",
>   "order_by": …
```

Adding 2022-06-17 feed variant

---

app/controllers/confirmations_controller.rb
app/controllers/omniauth_callbacks_controller.rb
app/services/authentication/authenticator.rb
spec/services/authentication/authenticator_spec.rb

This PR ensures email confirmation is required when authenticating via 3rd party auth service providers. The only reason email confirmation isn't required is when SMTP isn't configured (can't confirm the email in that case).
- Closes #17865
- Make sure it's configured to work with an OAuth service provider (Twitter, Facebook, etc)
- Also make sure emails can be sent from your local environment
2. Register a new account
3. Confirmation email should be delivered if SMTP is enabled
Tests for this situation were modified/included and can be tested locally with:
`bundle exec rspec spec/services/authentication/authenticator_spec.rb`
**Complete flow using GitHub**
https://user-images.githubusercontent.com/6045239/174094827-17b67df9-1806-4219-a112-407c616c9a41.mov
**Same flow …

Fix email confirmation logic when registering via Omniauth

---

app/controllers/admin/users_controller.rb
app/views/admin/users/index.html.erb
app/views/admin/users/index/_user_actions_dropdown.html.erb
cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js

This PR adds an "Adjust credit balance" modal to the member's action panel in the Member Index View by leveraging the reusable modal. Additionally, this PR adds a the ability to adjust credits to `Admin::UsersController#user_status` and an e2e tests behind the `member_index_view` feature flag that test that the modal shows as expected.
- Closes #17482 
**To QA this PR, please first ensure that you have the `member_index_view` feature flag enabled, and then navigate to `/admin/member_manager/users`.**
Next, test that you are able to open the "Adjust credit balance" modal, located within the vertical menu in the righthand corner of each member, by clicking the "Adjust credit balance" button within the menu. 
After, test that you are able to add and remove credits for a user as expected and …

Member Index View Actions: "Adjust Credit Balance"

---

app/assets/stylesheets/components/forms.scss
app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
app/javascript/crayons/formElements/DateRangePicker/__tests__/DateRangePicker.test.jsx

The date picker from `react-dates` allows us to pass an 'earliest' and 'latest' valid date to limit user selections, and it blocks these dates from the calendar picker. However, it doesn't execute any validation on dates typed directly into the inputs. 
This PR adds that validation behaviour into our wrapping DateRangePicker class.
- Closes https://github.com/forem/forem/issues/17959
- Locally run `yarn install && yarn storybook` and navigate to the DateRangePicker story
- Use the storybook controls to configure max and min dates
- Experiment with typing values into the inputs directly (rather than using the calendar popup) 
- Check that when you move away from the input, an error is shown if the date is invalid (either for being too early, too late, or just by not being …

Validate date format and min/max in date range picker component

---

app/assets/stylesheets/views/article.scss

Cover images were being shrunk down slightly creating a border effect. If we don't shrink 'em they'll look alright.
closes #17730
**before:**
**after:**
N/A
N/A
N/A

update aspect ratio to reflect cover image size

---

Gemfile
config/initializers/datadog.rb

- Disable Datadog's auto_instrument because we don't need all the APM it provides us.
- Add back the old instrumentation we use in the new Datadog syntax.
- Give them all proper `service_name` so we can distinguish them.
n/a

Add service_name scope to Datadog

---

app/assets/stylesheets/views/profile.scss
app/views/organizations/_header.html.erb
app/views/users/show.html.erb

When a string becomes too long for the screen truncate it with ellipse rather than breaking the site
https://dev.to/wjplatformer/whats-wrong-foremdev-2-e89
**Before:**
**After:**
N/A

Truncation long text on profile screen

---

app/controllers/articles_controller.rb
spec/requests/articles/articles_admin_unpublish_spec.rb

Use `Articles::Updater` for unpublishing an article from the "Moderate Post" side panel, so that the related notifications would be deleted in that case.
#15675 #18031
- find(create) an article that has notifications
- unpublish the article from the "Moderate Post" side panel
- the related notifications should be deleted
issue template so Community Success can …

Fixed removing notifications on admin unpublishing

---

app/services/html/parser.rb
spec/services/markdown_processor/parser_spec.rb

See https://github.com/forem/forem-internal-eng/issues/480
We seem to be emitting tags we don't want to be, creating the potential for cross-site scripting. Our sanitizer escapes `<` and `>` into `&lt;` and `&gt;`, but later Nokogiri/libxml inflates those "HTML entities" into their respective ASCII characters, which we then emit. @aitchiss and @maestromac traced this to the `wrap_mentions_with_links` block. It turns out that Nokogiri has two _very_ similar methods -- `text` and `to_s` -- that differ with respect to entities.
Reported in https://github.com/forem/forem-internal-eng/issues/480
This text snippet is enough to trigger the behavior:
```
<style>x{animation:s}@Keyframes s{}
<style>{transition:color 1s}:hover{color:red}
``` …

Fix style injection with user mentions

---

.rubocop.yml
app/services/moderator/banish_user.rb
app/services/moderator/manage_activity_and_roles.rb
app/services/users/delete.rb
app/services/users/delete_podcasts.rb
spec/services/moderator/banish_user_spec.rb
spec/services/users/delete_podcasts_spec.rb
spec/services/users/delete_spec.rb

Prior to this commit, we may have left lingering podcast entries that required manual cleanup.  As a bonus, I also added deleting podcasts when we delete users.
In addition I adjusted rubocop to not complain about the require method call
```
spec/services/users/delete_spec.rb:1:1: C: \
Style/TopLevelMethodDefinition: \
Do not define methods at the top-level. \
(https://rubystyle.guide#top-level-methods)
require "rails_helper"
^^^^^^^^^^^^^^^^^^^^^^
```
Closes forem/forem#18041

Ensuring we delete podcasts when we banish a user

---

config/feed-variants/20220712-variant.json
config/field_test.yml

This involves declaring the 20220603-variant-a the winner of the past
experiment; note in the past experiment there was not a statistically
significant winner.
This new experiment adds a variant that deviates from the new
incumbentby way of reintroducing the follows an author and adjusting the
tag follow weights.
```shell
$ diff config/feed-variants/20220617-variant-a.json \
config/feed-variants/20220712-variant.json
```
Results in:
```shell
3c3
<   "description": "Blend of 20220603-variant-b and 20220603-variant-a",
---
>   "description": "Builds from 20220617-variant-a (see https://github.com/forem/forem/issues/18082)",
50a51,57
>     "following_author": {
>       "cases": [
>         [0, 0.8],
>         [1, 1]
>       ],
>       "fallback": 0.8
>     },
70,73c77,80
<         [0, 0.5], …
```

Starting 2022-07-12 Experiment

---

app/javascript/packs/admin/users/filtersModal.js
app/views/admin/users/index/_filters_modal.html.erb

We're no longer going to implement "filter by last activity" as part of this phase of member index work. This PR removes it from the filter modal UI.
This PR also fixes a small bug I found in the filter modal cancel button, following some changes to the `closeWindowModal` code.
Relates to https://github.com/forem/forem/issues/17477
The filters modal should no longer include a "Last activity" section:
N/A
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assig …

Remove filter by last activity, fix close modal bug

---

config/initializers/rpush.rb

Fixes a typo 🤦🏼‍♂️ in Rpush reflection callback. This caused us to never be notified when PN deliveries failed. Noticed this by running the Rpush delivery directly on the console in a production environment (BHC) with `Rpush.push`.
```
E, [2022-07-11T18:05:33.570078 #4] ERROR -- : [2022-07-11 18:05:33][ERROR] NameError, uninitialized constant HoneyBadger
Did you mean?  Honeybadger
/app/config/initializers/rpush.rb:76:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/3.0.0/gems/rpush-7.0.1/lib/rpush/reflection_collection.rb:33:in `__dispatch'
/app/vendor/bundle/ruby/3.0.0/gems/rpush-7.0.1/lib/rpush/reflectable.rb:6:in `block in reflect'
/app/vendor/bundle/ruby/3.0.0/gems/rpush-7.0.1/lib/rpush/reflectable.rb:4:in `each'
/app/vendor/bundle/ruby/3.0.0/gems/rpush-7.0.1/lib/rpush/reflectab …
```

Fix Honeybadger typo in Rpush reflection callback

---

app/javascript/crayons/formElements/DateRangePicker/__tests__/DateRangePicker.test.jsx

I've tested locally and not seeing this flake with these changes, and I've re-run the frontend tests job in CI 5 times with no issue, so I think this is a step in the right direction at least.
Testing this particular part of the date range picker is tricky because `react-dates` renders hidden copies that a component-level test can get confused by.
N/A
Just that the test passes 😄 
N/A
[Changes …

Improve DateRangePickerSpec that was flaking in CI

---

app/services/articles/feeds/basic.rb

Prior to this commit we had a hard-coded 0; there are other hard-coded
score ranges throughout the code-base.  These are unexplained magic
numbers.  The hope with this change is to provide a mechanism for Forem
owners to adjust a configuration and see a change in behavior.
Related to forem/forem-internal-eng#484
None.
None.

Ensuring home feed uses minimum score threshold

---

app/views/pages/_privacy_text.html.erb

This removes the language about using Facebook Pixel since we haven't used it since December 20, 2018 via #1380.
#1380

Remove Facebook Pixel language from default privacy policy 

---

config/feed-variants/20220719-variant-a.json
config/feed-variants/20220719-variant-b.json
config/field_test.yml

Diff between `20220617-variant-a` and `20220719-variant-a` (e.g. the new
incumbent with minor tweaks):
```
3c3
<   "description": "Blend of 20220603-variant-b and 20220603-variant-a",
---
>   "description": "Copy of 20220617-variant-a with tweak to negative privileged user",
84,85c84,85
<       "negative_reaction_threshold": -10,
<       "positive_reaction_threshold": 10
---
>       "negative_reaction_threshold": -9,
>       "positive_reaction_threshold": 4
```
**Note**: In the above I'm adjusting the `negative_reaction_threshold`
and `positive_reaction_threshold` to reflect the value of the privileged
user reaction points:
```ruby
class Reaction < ApplicationRecord
BASE_POINTS = {
"vomit" => -50.0,
"thumbsup" => 5.0,
"thumbsdown" => -10.0
}.freeze
```
See the [current state of …

Adding 2022-07-19 variant

---

app/views/articles/show.html.erb
config/locales/views/articles/en.yml
spec/requests/articles/articles_show_spec.rb

Change "posted on" to "scheduled for" on the scheduled articles preview page
- Related Issue #17939 
- enable the feature flag `FeatureFlag.enable(:schedule_articles)`
- create an article scheduled to the future
- the preview page should include "Scheduled for {published_at}" instead of "Posted on {published_at}"
- for articles, published in the past, the page should include "Posted on {published_at}" (as before the changes)

Change "posted on" to "scheduled for" on the scheduled articles preview page

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/listings_controller.rb
spec/requests/api/v1/users_spec.rb

API requests on V1 don't need authenticity token validation because it only uses API Key authentication.
This validation is required if we're allowing the use of the API from browsers to avoid CSRF attacks, but we are not going to support this anymore.
Before un-feature flagging (#17655) I've been running some tests and we need this fix
1. Enable :api_v1 Feature Flag
2. Create an API Key in /settings/extensions
3. Send in a PUT request to `/api/users/:id/unpublish` with the API Key and `application/vnd.forem.api-v1+json` in the Accept header
I've been testing some stuff [using this Postman collection](https://www.getpostman.com/collections/426f4c6a7f6db55affa8), in case it's helpful for anyone.
N/A
Test again on BHC or another forem instance

API V1 skip authenticity token validation

---

app/services/spam/handler.rb
spec/services/spam/handler_spec.rb

Prior to this commit, we always checked the user's name for spam matching criteria.  With this change, we're allowing a site administrator to toggle on a feature flag for more rigorous profile checking.
The reason for the increased rigor is that there could be unexpected consequences (e.g. marking a user as spam who was previously not caught as a spammer).  If you want the feature, enable the `:more_rigorous_user_profile_spam_checking` flag.
Closes forem/forem#18157
Related to forem/forem-internal-eng#453
Given that this is running against users whenever the user record saves, there could be unintended consequences (e.g. marking a user as a spammer).  That is why this feature is behind a feature flag.

Adding conditional spam handling for user profile

---

app/assets/stylesheets/components/forms.scss

Update the colour picker styles to bring them inline with crayons
closes #18130 
The colour picker should now look like this
You can find it in settings under branding
Don't think so
N/A

Add crayon styles to c-color-picker

---

app/javascript/packs/admin/users/filtersModal.js
app/views/admin/users/index/_filters_modal.html.erb
cypress/e2e/seededFlows/adminFlows/users/filterUserIndex.spec.js

This PR adds the "Clear filters" functionality to the new filters modal - when clicked, it clears all current checkbox selections and date picker values.
- Related Issue https://github.com/forem/forem/issues/17477
- Make sure you have the `member_index_view` feature flag enabled
- Visit `/admin/member_manager/users`
- Click the filter button
- Inside the modal, select some checkboxes and set some dates in the joining date section
- Click the "Clear filters" button at the top right
- Check all values have cleared 
https://user-images.githubusercontent.com/20773163/180730940-ce3e4e6e-c06b-493f-9307-405cb89b4016.mp4
I don't think so. There's not any immediate feedback on the button press, but the intention of the button (I think) is pretty clear, and a user can validate the fields have been …

Member index view: add clear all functionality to filters modal

---

app/controllers/concerns/api/users_controller.rb
spec/requests/api/v1/users_spec.rb

Fixes the `/api/users/:id/unpublish` endpoint. When implemented I missed taking in consideration the deletion of comments along with the unpublishing of posts.
The reasoning of using the `deleted` boolean on the comments instead of completely destroying them is so they can be re-created if needed (`AuditLog` trail implemented in #18167). In contrast, the core app logic is that comments are completely destroyed [if they are childless](https://github.com/forem/forem/blob/main/app/controllers/comments_controller.rb#L175-L180).
- Related Issue #18058
1. Enable :api_v1 Feature Flag
2. Create an API Key in /settings/extensions
3. Send in a PUT request to /api/users/:id/unpublish with the API Key and `application/vnd.forem.api-v1+json` in the `Accept` header
N/A

Add missing action of comment deletion in unpublish API endpoint

---

app/assets/stylesheets/views/article-form.scss
app/assets/stylesheets/views/comments.scss
app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
app/javascript/crayons/MarkdownToolbar/__tests__/MarkdownToolbar.test.jsx
app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.jsx

We had a couple of issues relating to the approach we took to make the toolbar responsive on smaller screens - previously it scrolled horizontally, but there were issues of discoverability and also usability when the scrolling behaviour was triggered on non-touch devices (e.g. in the moderator centre where we render inside a smaller iframe, but also if a user zoomed their viewport for a11y).
Instead of scrolling in small viewports, we now dynamically detect how many items we place in the overflow (3 dots) menu. See the [figma mockups](https://www.figma.com/file/PIPeiiVSADmcpCbiZTdJm9/Editor?node-id=2185%3A8563).
**A small implementation detail:** 
In extremely small screens (super-narrow smartphones like galaxy fold, or mobile devices where a user is choosing to zoom the screen), I've …

Dynamically change number of formatter buttons in md toolbar overflow menu

---

app/assets/stylesheets/preact/onboarding-modal.scss

On small screens (below our xs breakpoint), links to terms & conditions on the onboarding screen break in a visually odd way:
It seems that at a small enough screen dimension, the `label` container becomes a two-column layout, with links and text in separate columns. This feels like a bug in the grid layout -- it doesn't seem to be something we've _asked for_ -- but I might be missing something?
Anyway, after:
- Closes https://github.com/forem/forem-internal-eng/issues/487
To replicate the issue on a desktop browser, I needed to use device emulation mode -- otherwise, the browser's minimum width was wider than the width at which the bug would occur. Depending on browsers, odd wrapping happens somewhere around 400±25px wide.
The links were functional all along, just wrapping in an odd way. …

Try for inline T&C links on small screens

---

app/assets/stylesheets/views/article.scss

Setting the first variable of border-radius to var(--radius-auto) fixed the issue.
Attempting to set the first and second variables of border-radius to var(--radius-auto) resulted in no border radius ever showing.
Using var(--radius-auto) will remove the radius on the article image when it shouldn't have a radius.
closes #18197 
This should only affect mobile renderings of the page.
Old:
New:
I would have preferred to set "overflow: hidden" on the article element itself, to prevent anything from overflowing. But I saw the Dev's fix my previous issue using the radius …

Use --radius-auto for top of article images

---

app/javascript/article-form/articleForm.jsx
app/javascript/article-form/components/EditorActions.jsx
app/javascript/article-form/components/Options.jsx

This pr contains impromevents and a bug fix related to editing a scheduled article:
When removing date from the datepicker in Post Options:
- fixed an error in the console
- change save button text from "Save changes" to "Publish" to make it clear that the article will be published right away
Post Options:
- changed "dangerous" "unpublish post" button to a regular one
Maybe the "design" in questionable, but imo red button is misleading in this case (a scheduled post has not been published yet so it shouldn't be dangerous to unpublish it). I tried the blue button, but it draws too much attention and makes the user (me) want to press it when meaning to press "Done". Any suggestions appreciated.
- Related Issue #15858 
- enable the feature flag `FeatureFlag.enable(:schedule_articles)`
- …

Improved editing scheduled articles

---

app/models/display_ad.rb

Previously (#18141) we added the ability to show DisplayAds in a new placement area, below individual articles. This area is wider than the right sidebar, but code in the DisplayAds model resizes images to maximum 350px wide. That fits in the sidebar, but is too small on the articles view. (Even if one uses CSS/HTML to embiggen them, there's only 350 width of pixels, so it looks bad.)
- Related Issue https://github.com/forem/forem/issues/18241
It may be necessary to edit any DisplayAds to trigger re-processing their images.
No.
issue template so Community Success can help …

Tweak prefix image size for DisplayAds on articles

---

app/models/article.rb
app/services/slack/messengers/article_published.rb
spec/models/article_spec.rb
spec/services/slack/messengers/article_published_spec.rb

Previously, slack notifications for published articles were sent in a callback, right after publishing. So there was a check in the `Slack::Messengers::ArticlePublished` which filtered out all articles older than 30 seconds, and notifications were not sent for them.
Currently, the notifications are sent separately from the publication process, in the `Articles::PublishWorker` which runs every 5 minutes. When the worker calls `Slack::Messengers::ArticlePublished` some articles may be older than 30 seconds, so sending notifications was skipped for them. 
In this pr I increased the time for sending slack notifications to 10 minutes. I also removed the `notify_slack_channel_about_publication` because notifications for updated articles should be handled by the worker too.
- Related Issue …

Fixed sending slack notifications for published articles

---

.gitpod.yml

Replaces `gp await-port` with `gp ports await` in `.gitpod.yml`.
This will remove the following deprecation warnings:
```
Command "await-port" is deprecated, please use `ports await` instead.
```
n/a
n/a
n/a
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

Command update for gp cli in gitpod.yml

---

app/javascript/article-form/components/EditorActions.jsx
app/workers/articles/publish_worker.rb

When using rich markdown editor, we change save button text according to the `published_at` and `published` values, but when using basic markdown editor, the text should always be "Save changes" (as it was before adding scheduling posts feature) 
- Related Issue #15858 
Check button text in situations like:
- creating a post from editor v1
- editing scheduled post from editor v1
- editing published post from editor v1
The save button text should be "Save changes".
appropriately. …

Changed save article button text to be always 'Save changes' when using editor v1

---

app/workers/moderator/unpublish_all_articles_worker.rb
spec/workers/moderator/unpublish_all_articles_worker_spec.rb

Remove context notifications when unpublishing all posts from user by admin, similarly as it's done in `Articles::Updater`.
Context notifications are used to track wether we have sent notifications about an article publication, so when the article is being unpublished, context notifications should be removed along with notifications.
I also added tests for removing notifications and context notifications for `Moderator::UnpublishAllArticlesWorker`
- Related Issue #15858 (tangentially, as it's related to changing sending notifications logic)
- find a user that has articles, notifications for those articles, and context_notifications for those notifications (or create them manually from console)
- visit admin user manage page http://localhost:3000/admin/member_manager/users/%user_id%
- …

Remove context_notifications when unpublishing all posts

---

.lintstagedrc.js

When the git commit hooks are being run, we are getting the following warning: 
```
✖ bundle exec rubocop --require rubocop-rspec --auto-correct --enable-pending-cops:
--auto-correct is deprecated; use --autocorrect instead.
```
In [this PR ](https://github.com/rubocop/rubocop/pull/10547) rubocop changed auto-correct to autocorrect whilst still ensuring there is a deprecated alias.
- Closes #
The git commit hooks should run without any errors and the warning should disappear. 
_Will this PR introduce a change that impacts Forem members or creators, …

Rubocop Update: Change auto-correct to autocorrect

---

app/controllers/articles_controller.rb
app/models/article.rb
spec/requests/articles/articles_update_spec.rb

Fixed publishing a scheduled article:
When a user removes published at date from "Post Options", passed `params` didn't have the corresponding keys, so `published_at` was not updated and kept the future value. After the fix, `published_at` will be set to `nil` explicitly. It will be updated to current time when publising.
- Related Issue #15858 
- edit a scheduled article
- remove published at date
- click "Publish"
- you should be redirected to the article page (not preview page), and see that the article was published. …

 Fix updating articles from scheduled to published (immediately)

---

app/views/comments/_comment_proper.html.erb
config/locales/views/comments/en.yml
config/locales/views/comments/fr.yml

- Сleared up the message when a comment is hidden 
- Adds i18n for "_comment_proper.html.erb" file
- Related Issue #14888
- Closes #17832
Change is consistent with the interface.

Сleared up the message when a comment is hidden 

---

app/models/article.rb
app/services/articles/attributes.rb
app/services/articles/updater.rb
app/workers/moderator/unpublish_all_articles_worker.rb
spec/services/articles/attributes_spec.rb
spec/services/articles/updater_spec.rb

Nullify published_at when unpublishing an article to avoid situations when we have a draft with `published_at` displayed in the "Post options" which can be misleading, especially if published_at is already in the past by the time of editing.
Editing an unpublished draft (that was scheduled before) before the changes:
Keeping `published_at` for unpublished drafts doesn't make a lot of sense, but also doesn't make a lot of harm. There can be potential problems with re-publishing when a draft has `published_at` in the past, but we have the logic to avoid such problems [(we update `published_at` to current in such cases)](https://github.com/forem/forem/blob/d942fa87eb05bb8424a9c0fd7f9f96affc1f3020/app/services/articles/updater.rb#L21-L25)
I haven't added nullifying `published_at` for the …

Nullify published_at when unpublishing an article

---

app/models/article.rb
app/services/articles/attributes.rb
app/services/articles/updater.rb
app/workers/moderator/unpublish_all_articles_worker.rb
spec/services/articles/attributes_spec.rb
spec/services/articles/updater_spec.rb

This reverts commit 414e17aca62f48e0bdaa908a5ba3ab45902f67c8.
Resolves https://github.com/forem/forem/issues/18341

Revert "Nullify published_at when unpublishing an article (#18298)"

---

app/models/articles/feeds.rb

Adds a feed lever for ranking articles by their public reaction score. This value is already calculated by `article.update_score` and held in the database as `articles.score`. It's represents a sum of the points associated with reactions on an article.
- Closes #18271
appropriately.
shared_

Public reactions score feed lever

---

app/models/article.rb
spec/models/article_spec.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb
spec/system/articles/feeds/large_forem_experimental_spec.rb

We only allow future or current published_at for the new articles, but we allow a 15-minute gap, just in case and for convinience when using editor v1 and the user chooses to specify `published_at`.
This pr allows `published_at` to be within 15 minutes in the past (as intended), not 15 hours
- Related Issue #15858 
- enable the feature flag `FeatureFlag.enable(:schedule_articles)`
You can use both editors for the next steps:
- try create an article with `published_at` set to 1 hour ago, press `save` - an article should't be saved, an error message should be displayed
- try create an article with `published_at` set to 10 minutes ago, press `save` - an article should be saved
development …

Allow published_at to be within 15 minutes, not 15 hours

---

app/controllers/articles_controller.rb
app/controllers/comments_controller.rb
config/locales/controllers/en.yml
config/locales/controllers/fr.yml
spec/requests/comments_spec.rb

Currently, when a suspended or comment suspended user tries to take an action that they can't because of their suspension they receive a generic error message "Your comment could not be posted due to a server error". The issue is that users see this error message and think that they're experiencing a bug. They frequently don't realize that they're experiencing this issue because they're suspended.
Hence, in this PR, we change the error message to read "Your comment could not be posted due to an error: Your privileges have been suspended."
- Related Issue #https://github.com/forem/forem/issues/18336
- Closes #https://github.com/forem/forem/issues/18336
- Add the role `comment_suspended` to your logged in user. You can do this by finding the user and assigning it to `user` in the console. …

Update the error message when a user with role "comment_suspended" tries to comment

---

app/javascript/article-form/components/Options.jsx
app/models/article.rb
app/services/articles/attributes.rb
app/services/articles/updater.rb
spec/models/article_spec.rb
spec/requests/articles/articles_update_spec.rb
spec/services/articles/attributes_spec.rb
spec/services/articles/updater_spec.rb

We don't want to allow users to use unpublishing and republishing as a hack, and bump an old post to have a current published at [Slack thread](https://forem-team.slack.com/archives/C7GE84DEJ/p1660845549633789?thread_ts=1660841521.696969&cid=C7GE84DEJ)
In this pr I:
- removed bumping published_at to current on republishing
- rewrote validation for `published_at` on update, currently it:
- allows future or current published_at when publishing for the first time (from a draft)
- allows any published_at for articles that were `published_from_feed` when publishing for the first time (from a draft)
- doesn't allow changing `published_at` for articles that have already been published (had `published_at` already)
- added more specs for unpublishing, publishing, and republishing, including the …

Made published_at immutable after an article has been published once

---

config/application.rb
config/initializers/rack/attack.rb
lib/rack/attack/request.rb
spec/initializers/rack/attack_spec.rb

Fastly HTTP data is not available when Fastly is not being used. This uses remote_ip as the backup.
n/a
n/a
n/a

Use remote_ip in Rack::Attack

---

app/controllers/admin/display_ads_controller.rb
app/models/display_ad.rb
app/views/admin/display_ads/_form.html.erb
app/views/admin/display_ads/index.html.erb
db/migrate/20220830141143_add_name_to_display_ad.rb
db/schema.rb
lib/data_update_scripts/20220830153942_generate_display_ad_names.rb
spec/lib/data_update_scripts/generate_display_ad_names_spec.rb
spec/models/display_ad_spec.rb

The following was done in this PR: 
1. Add the name field to the Display Ads page (edit, index and show)
2. The name field is not mandatory so I generate a name based on the "id" if a user does not enter one. This is so that the columns on the index table is more readable. 
3. In relation to the above, I also add a DUS that generates the name for previous Display Ads
- Related Issue #https://github.com/forem/forem/issues/18391
- Closes #https://github.com/forem/forem/issues/18391
Existing Display Ads:
- Run the Data Update Script `rails data_updates:run`
- Go to http://localhost:3000/admin/customization/display_ads
- You should see a generated name for each Display Ad of the format "Display Ad #{id}"
New Display Ads with a name
- Create a new Display Ad
- Fill out the name and save 
- the …

Add "name" field to Display Ads

---

.travis.yml

Instead of keeping `STATEMENT_TIMEOUT` on Travis config UI, it's better to have it visible in `.travis.yml` as a useful context
n/a
n/a

Add STATEMENT_TIMEOUT to .travis.yml

---

app/controllers/api/v1/reactions_controller.rb
app/policies/reaction_policy.rb
spec/requests/api/v1/docs/reactions_spec.rb
spec/requests/api/v1/reactions_spec.rb

We want to limit access to the Reactions API to admins. With the change in this PR, the Reactions API will respond `unauthorized` for non-admins.
- Related Issue #18263 #18355 
[Changes …

Restrict Reactions API to admins

---

app/javascript/searchableItemList/searchableItemList.js

History pages [were deleted](https://github.com/forem/forem/pull/6127), so the related code is only used for the reading list.
I planned to commit this along with [Removing typeahead reading list search](https://github.com/forem/forem-internal-eng/issues/496) , but I [question](https://github.com/forem/forem-internal-eng/issues/496#issuecomment-1246665182) the need of it, and I still want to update the misleading comment.
- Related Issue https://github.com/forem/forem-internal-eng/issues/496
updated. I …

Modified the comment for searchableItemList

---

app/assets/javascripts/.eslintrc.js
app/assets/javascripts/initializePage.js
app/assets/javascripts/initializers/initializeDisplayAdVisibility.js
app/assets/javascripts/initializers/initializeLocalStorageRender.js

User can toggle a setting to turn off sponsorships, either viewing or seeing them adjacent to their posts. We'd like DisplayAds to honor this setting as well, if it is set. I [initially](https://github.com/forem/forem/pull/18399) went about solving this on the back-end, however we cache rendered DisplayAds, so we need to approach hiding these ads on the front-end. There is prior art in the `initializeSponsorshipVisibility` function, so this follows very much in those foot-steps.
- Related #18399 
- Closes #https://github.com/forem/forem-internal-eng/issues/519
* View an Article, confirm that there's at least one DisplayAd visible (below comments).
* Navigate to `/settings/customization`
* Disable `Display Sponsors (when browsing)`
* Verify that DisplayAd is no longer appearing
Users who …

Try front-end hiding ads for user setting

---

app/controllers/admin/articles_controller.rb
app/decorators/article_decorator.rb
app/lib/black_box.rb
app/models/article.rb
app/models/tag.rb
app/services/article_api_index_service.rb
app/services/articles/suggest_stickies.rb
app/services/edge_cache/bust_article.rb
app/views/admin/articles/_individual_article.html.erb
spec/decorators/article_decorator_spec.rb
spec/models/article_spec.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/api/v1/articles_spec.rb

Perhaps I'm being overly cautious, but I'd rather remove all usage of `featured_number` and replace it with `published_at` first, as mentioned in the issue (#18482). Only after deploying this change and making sure we don't see any unexpected side effects I'll push forward a PR that will remove the column.
The intention behind this approach is to be able to revert the change if needed. If we remove the column along with the logic update (in this same PR) we would've lost the data from the DB and would have to scramble to recover them from backups 🙃 
- #18482
- App should continue to work as expected locally
- The feed where featured posts are being fetched
- `/admin/content_manager/articles` where this value used to be viewed/manipulated
N/A
Once the PR is deployed we should keep an eye …

Remove featured number usage from articles

---

app/javascript/packs/articlePage.jsx
app/javascript/packs/base.jsx
app/javascript/packs/homePage.jsx
app/javascript/utilities/ahoy/trackEvents.jsx

Currently, we pass through the Ahoy Event name but we have specific functions for each event because each one has a unique structure. Hence, we do not need to pass through the name dynamically.
- Related Issue #https://github.com/forem/forem-internal-eng/issues/490
- Closes #
- Logout and Click on the "Create Account" buttons and see them being tracked using Ahoy::Event.last
- You can read more about QA instructions on this PR too https://github.com/forem/forem/pull/18459
development …

Refactor: no need to pass through the ahoy event name dynamically.

---

app/controllers/admin/display_ads_controller.rb
app/models/display_ad.rb
spec/models/display_ad_spec.rb

DisplayAd search was throwing a 500 because of a connection to Organization, which isn't used on modern DisplayAds anyway. I wanted to keep this as a quick bug-fix, but there are potentially interesting things to return to in a future pass:
* It would be nice if this could search the "human-readable" placement areas
* It might be nice to have this use pg_search, but that needs a migration to add the tsvector columns
- Closes #https://github.com/forem/forem/issues/18491 …

Restore DisplayAd search

---

db/migrate/20220928162321_remove_featured_number_from_articles.rb
db/schema.rb

Follow up PR to #18510 to actually remove the column from the articles table.
- Closes #18482
App should continue to work locally
N/A

Remove featured_number from articles table

---

app/helpers/comments_helper.rb
app/lib/url.rb
app/views/articles/_full_comment_area.html.erb
app/views/comments/_comment.html.erb
app/views/comments/_comment_date.erb
app/views/comments/_comment_header.html.erb
app/views/comments/_liquid.html.erb
spec/system/comments/user_views_article_comments_spec.rb

This PR changes the way comment links are rendered on Posts. If you're signed out you should be get a link to the article with an anchor tag to the comment. If you're signed in you should get the same result as the app currently has (comment permalink).
- Closes #18489
1. Boot app locally and open Article with comments without signing in
2. Click on a comment's date
- The link should redirect to the same article with an anchor tag that scrolls you down to the comment
3. Open the comment's dropdown (3 dots icon) and "copy link"
- The link in the clipboard should be the same as the previous step 
4. Sign in and open another article with comments
5. Click on a comment's date
- The link should redirect to the comment's permalink
6. Open the comment's dropdown (3 dots icon) and "copy link"
- …

Comment fragment link when signed out

---

app/views/pages/robots.text.erb

This PR adds `Disallow: /ahoy/*` to `robots.txt`.
Closes #18530

Disallow /ahoy/* in robots.txt

---

app/controllers/admin/users_controller.rb
app/controllers/concerns/api/users_controller.rb
app/javascript/packs/modals/unpublishAllPosts.js
app/services/moderator/unpublish_all_articles.rb
app/views/admin/users/modals/_unpublish_modal.html.erb
app/views/moderations/modals/_unpublish_all_posts.html.erb
app/workers/moderator/unpublish_all_articles_worker.rb
spec/requests/admin/users_spec.rb
spec/requests/api/v1/users_spec.rb
spec/requests/articles/articles_create_spec.rb
spec/services/moderator/unpublish_all_articles_spec.rb
spec/workers/moderator/unpublish_all_articles_worker_spec.rb

- log `target_article_ids` and `target_comment_ids` when unpublishing from admin action
Before the change, this information was logged only when "unpublish all" was done via api. When "unpublish all" was performed via admin action, the log record was created, but it had no information about the affected articles and comments
- moved logging (creating an `AuditLog` record) to the worker. Before the changes, unpublishing was done asyncronously, but the logging was syncronous, so the log was likely created before the unpublishing happened. Now we log when unpublishing has actually happened.
- moved unpublishing and logging logic from `Moderator::UnpublishAllArticlesWorker` to the service `Moderator::UnpublishAllArticles`. Logging for "unpublishing all" is in one place for both unpublishing …

Save list of previously-published articles when user is subject to an "un-publish all" action

---

app/controllers/concerns/api/users_controller.rb
app/services/moderator/unpublish_all_articles.rb
spec/requests/api/v1/admin/users_spec.rb
spec/requests/api/v1/docs/articles_spec.rb
spec/requests/api/v1/users_spec.rb

On unpublishing all articles of a user via API: accept a note text and create a corresponding note if the text was passed.
The note is created the same way as it is when unpublishing all articles from the admin action (implemented in #18535)
[Related discussion](https://github.com/forem/forem/pull/18535#discussion_r987698022)
Do we need to adjust the code that sends requests to the api? @fdocr mentioned that it's used by Forem Shield.
- forem/forem-internal-eng/issues/491
Unpublishing all articles of a user via the api:
- if note text is passed, the note should be created
- if it's not passed, the note shouldn't be created

Create a note when a users' articles are being unpublished via API

---

app/controllers/stories_controller.rb
app/decorators/article_decorator.rb
app/decorators/podcast_episode_decorator.rb
app/helpers/comments_helper.rb
app/views/articles/_comments_actions.html.erb
app/views/articles/_full_comment_area.html.erb
app/views/podcast_episodes/show.html.erb
config/locales/views/comments/en.yml
config/locales/views/comments/fr.yml
spec/decorators/article_decorator_spec.rb
spec/decorators/podcast_episode_decorator_spec.rb
spec/system/articles/user_visits_an_article_spec.rb

This PR combines fixes for two comment-related issues:
1. We want to hide low-quality comments from users who are not logged-in.
2. We want to show fewer comments for logged-out users.
I'm combining them together here because they work similarly. Also both require changes to our cache key (including `user_signed_in?`). 
- Closes https://github.com/forem/forem/issues/18488
- Closes https://github.com/forem/forem/issues/18490
I found it challenging to create a low-quality comment, maybe there's a method I don't know, but what worked for me:
* Disable sidekiq or at least the `CalculateScoreWorker`
* Set a comment score to negative: `Comment.find(id).update score: -5`
accessibility is impacted and tested. For more …

Try hiding low-quality comments

---

app/views/users/show.html.erb

While working on https://github.com/forem/forem/issues/16328#issuecomment-1203937401 I noticed that inbox-modal is actually not getting used. It was first implemented in https://github.com/forem/forem/pull/1563 and was later removed in https://github.com/forem/forem/pull/16376
I went through entire #1563 and have verified that entire implementation has been removed.
- Related Issue #16328
- Closes #
Although there is no direct way to open this modal, after making code changes I was able to show this modal and it looked like this:
No …

✂️ ✂️  Removed inbox send message modal ✂️ ✂️ 

---

app/assets/stylesheets/ltags/UserSubscriptionTag.scss
app/javascript/liquidTags/userSubscriptionLiquidTag.js
app/views/liquids/_user_subscription.html.erb
cypress/e2e/seededFlows/articleFlows/liquidTagFlows/userSubscriptionTagWithSubscribableEmail.spec.js

This PR simply uses the preact modal instead of creating our own modal.
- Related Issue #16328
- Closes #
To test this PR, create a post with following content
```
Test Post User Subscription
{% user_subscription Your call to action text comes here %}
```
After creating the post, signed-in users will see below screen
Click on subscribe to show the modal
No …

Used preact modal for userSubscriptionLiquidTag

---

app/javascript/CommentSubscription/__tests__/commentSubscriptionUtilities.test.js
app/javascript/display-ad/tags.jsx
app/javascript/githubRepos/__tests__/githubRepos.test.jsx
app/javascript/listings/__tests__/ListingTagsField.test.jsx
app/javascript/packs/admin/displayAds.jsx
app/javascript/utilities/__tests__/search.test.js
app/javascript/utilities/http/__tests__/csrfToken.test.js
app/javascript/utilities/http/__tests__/request.test.js
app/javascript/utilities/http/csrfToken.js
app/javascript/utilities/http/request.js
app/views/admin/display_ads/_form.html.erb

This PR partially refactors some code whilst adding some new functionality. 
**Refactor:** 
The asset pipeline (`app/assets/javascripts`) is where we have the "legacy" JavaScript. It's legacy in the sense that it's not EcmaScript Modules (ESM). It's a bunch of JS files concatenated together.
In `app/javascript/utilities/http/request.js` we were using a method called `getCsrfToken` and this method was being included automatically in the [the application layout file](https://github.com/forem/forem/blob/effb2b0a87783106af4b481035699fd34ca1e96f/app/views/layouts/application.html.erb#L21-L22). Hence, it was not being imported in [app/javascript/utilities/http/request.js](https://github.com/forem/forem/blob/effb2b0a87783106af4b481035699fd34ca1e96f/app/javascript/utilities/http/request.js) …

Add a MultiSelect Autocomplete component to the Display Ads Page

---

spec/requests/articles/articles_update_spec.rb

This pr fixes a failing spec that started failing because of the daylight savings time.
In general, I put hardcoded time in the tests of this type because I wanted to test the actual values that are written. Otherwise I would put the logic similar to the logic in `ArticlesController#article_params_json`, so that would not fully test what's happening. 
We would still need some kind of logic to work with dst in tests. But I have also read that Mexico [has abolished dst](https://www.timeanddate.com/news/time/mexico-abolishes-dst-2022.html) recently, so we can just change the values from -5 to -6 in this test. 
I have also checked other places with similar logic in tests and timezones that are used there don't use dst, so they should work, …

Fix a spec failing because of the daylight savings

---

app/controllers/articles_controller.rb
app/services/articles/updater.rb
app/views/dashboards/_dashboard_article.html.erb
app/views/dashboards/_dashboard_article_row.html.erb
spec/requests/articles/articles_update_spec.rb

Fixes a bug described in #18609
While exploring the problem I found out two issues instead of one:
1) Changing an author of a scheduled DRAFT: author was not saved
2)  Changing an author of a scheduled article: author was saved, but `published_at` was updated to current time, and the post was published immediately
This pr should fix both issues.
The problem was that if we don't pass `published_at` to `ArticlesController#update`, we assume that we want to nullify it and publish immediately. But that's not what we want when updating an author.
- Closes #18609
Before testing, I recommend to reproduce the bugs described earlier.
1) create a scheduled article under an org
2) go to the dashboard
3) choose the org from the dropdown
4) press 3 dots in your article row, change the author from the …

Keep `published_at` when changing author of a scheduled article from the dashboard

---

spec/models/ab_experiment/goal_conversion_handler_spec.rb

This PR is an attempt to fix an issue we're seeing in some AbExperiment specs where current time of execution and/or timezones would sometimes break CI due to seed data being created inconsistently.
- #18577
Specs are the change. These are the times that you see when running the specs locally (randomized TZ means same minutes/seconds as local machine but different hour of the day)
When specs are executed at a TZ where seed data overlaps more than one day (i.e. 7 PageViews created over the past 7 hours) the experiment results vary (instead of 7 events in one day they span 2 days). This is what those look like with the Timecop freeze call (consistent):
N/A

Timecop freeze ab_experiment spec

---

app/workers/articles/update_organic_page_views_worker.rb
spec/models/article_spec.rb
spec/requests/page_views_spec.rb

This object queries and then writes to three columns:
- `organic_page_views_count`
- `organic_page_views_past_week_count`,
- `organic_page_views_past_month_count`
And only the last one is being _read_ anywhere else in the app. These are cached columns which serve a purpose only if they are subsequently read by the application — which these are not.
It is always possible that the database is being read directly outside of the context of the application code, but that is not a likely scenario here, and it is not a critical problem in that event.
This would enable a follow up step of removing these unused columns, but that is out of scope of this issue.
Closes https://github.com/forem/forem/issues/18688 …

Remove expensive query which is not necessary within app logic

---

app/models/article.rb
config/locales/models/en.yml
config/locales/models/fr.yml
spec/models/article_spec.rb

Allow removing `published_at` for scheduled drafts.
- Closes #18673 
First, I would recommend reproducing the bug described in #18673 in the main branch.
- Create a scheduled draft article (choose published date and time in "Post options", then click "Save draft" instead of "Publish") 
- Open "edit" page for this article
- In the "Post options" remove published date and time, click "Save draft"
- the draft should be saved, it shouldn't have `published_at` anymore
[Changes …

Fix removing published_at for a scheduled draft

---

app/javascript/article-form/components/Options.jsx

Fixes pasting `canonical_url` to the post options with the right click, the problem is described [here](https://github.com/forem/forem/issues/18622#issuecomment-1301364132) and in the following comments.
- Closes #18622
- go to "Create post" page
- fill in the required fields like title and body
- copy any url
- go to the post options
- paste into the `canonical_url` field with the right click
appropriately.
or in a …

Add missing onInput for `canonical_url`

---

app/controllers/display_ad_events_controller.rb
spec/requests/display_ad_events_spec.rb

We currently throttle the update of Display Ad tabulation to only happen every 15 minutes, but this is 15 minutes globally, not per unit.This change will help it to happen on a per unit basis to make this more uniform and have updates happen in a less globally random way.
- Related Issue #https://github.com/forem/forem/issues/18685
- Closes #https://github.com/forem/forem/issues/18685
None
[Changes …

Throttle display ad event per unit rather than globally

---

app/services/edge_cache/bust/fastly.rb

Reverting work introduced in https://github.com/forem/forem/pull/16903
According to [Fastly ruby gem ](https://github.com/fastly/fastly-ruby#usage-notes)
> If you are performing many purges per second we recommend you use the API directly with an HTTP client of your choice. 
> fastly-ruby has not been audited for thread-safety. If you are performing actions that require multiple threads (such as performing many purges) we recommend you use the API directly.
which explains the problem we've intermittedly experienced. Using our own HTTP client of choice will also allow us to easily tweak timeout when we need it.
n/a
This work was deployed on staging for testing
n/a

Use HTTParty for fastly_purge

---

app/views/admin/display_ads/_form.html.erb
cypress/e2e/seededFlows/adminFlows/displayAds/createDisplayAds.spec.js

Now that Display Ads have been tested, we're ready to remove the feature flag. 
- Related Issue #https://github.com/forem/forem/issues/18519
- Closes #https://github.com/forem/forem/issues/18519
Make sure that you're still able to test the Display Ads targeted tags as per https://forem.team/ridhwana/introducing-targeted-tags-for-display-ads-qa-required-57l5
-
[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template …

Remove `display_ad_tags` Feature Flag

---

app/assets/stylesheets/components/tooltips.scss

The below image shows that on certain screens the content "Jump to comments" is cut-off from screen.
This issue was happening for screens sizes between `768px` and `1024px`. To fix this correctly along with keeping the icon and the tooltip centre aligned I had to reduce the font-size and padding, which does work correctly as show in below screenshots. 
(If, we don't decrease the font-size and padding, then the icon and tooltip content won't be centre aligned.)
- Related Issue #18654
- Closes #18654
- Check out the PR, start up a local forem, and visit /admin/feature_flags. Create a flag named `replace_unicorn_with_jump_to_comments` and enable it.
- Visit article page
- Hover over `comments` icon available below `like` icon.
https://user-images.githubusercontent.com/9396084/203247225-e4e750 …

Comment icon tooltip: css fix

---

app/javascript/article-form/components/ClipboardButton.jsx
app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
app/javascript/listings/listingDashboard.jsx
cypress/e2e/seededFlows/publishingFlows/uploadImage.spec.js
yarn.lock

There were some dependency updates that would break our build in a way that didn't make sense. My hypothesis is there is a redundancy from years of gunk buildup in our `yarn.lock`. While I believe that running `yarn` on its own should run some course correction, erasing and recreating seems to generate a completely different `yarn.lock` that is 1000 lines shorter. Another upside is the more updated testing tool has a stricter evaluation and considered 2 specs failures.
Please let me know if there's an error in my thinking here.
Supersedes https://github.com/forem/forem/pull/18694
n/a

Recreate yarn.lock

---

cypress/support/commands.js

This PR introduces a short delay after the cypress loginUser command first attempt. We've been seeing 500 errors sporadically in cypress tests while logging in users. The logs appear to show DB timeouts and it's been hard to tell what is the cause of this. Perhaps we're hitting the DB too hard on CI and a short delay, which **will only happen when the first request fails**, might get rid of these issues 🤞🏼 
- #18839
CI passes  ✅  😄 
None

Attempt short delay after cypress loginUser failed request

---

app/models/comment.rb
app/services/content_renderer.rb
spec/models/comment_spec.rb

Use `ContentRenderer` for evaluating comment's markdown.  Evaluate with `ContentRenderer` when the feature flag is enabled, evaluate the old way when it's not
I followed a pattern from Joshua's pr #18754
- Related Issue #18649
- Closes [#18650](https://github.com/forem/forem/issues/18650)
This pr changes the implementation details, not the behavior, so the existing tests apply.

Extract comments rendering

---

app/views/comments/_comment_header.html.erb

This PR fixes the double tooltip issue. See screenshots below for better understanding.
- Closes #18856
**How to test?**
1. Checkout this branch and run this code locally.
2. Sign-in
3. Create a new post and add a comment on the post.
4. Now in the comment section, you will see one medal next to username, hover over that.
5. Notice how there is only one tooltip -- means it has been fixed.
| Before  | After |
| ------------- | ------------- |
| <img width="773" alt="Screenshot 2022-12-13 at 10 19 13 PM" src="https://user-images.githubusercontent.com/9396084/207400330-e4817ba8-c1ac-4332-8b04-fa5ae49e561c.png"> | <img width="708" alt="Screenshot 2023-01-12 at 8 08 30 PM" src="https://user-images.githubusercontent.com/9396084/212096848-379159aa-245a-4f88-981d-4c773550fc69.png"> |
No, before …

Fixed double tooltip issue

---

app/models/article.rb
app/models/comment.rb
app/services/content_renderer.rb
spec/services/content_renderer_spec.rb

While working on Extracting `DisplayAd rendering` #18651 , I noticed a couple of issues:
- `processed_content` was set multiple times (though the code assumes that it was cached), `front_matter` which is delegated to `processed_content` is also called multiple times in this case, so it ends up being parsed multiple times. That happens because we check for `!body_markdown_changed?`  inside the `processed_content`  method, and `body_markdown_changed?`  will return true multiple times when it's called inside the callbacks.
- `set_main_image` was using frontmatter which was delegated to `ContentRenderer` even when the feature flag was disabled. The result ended up being the same in this case, but when the feature flag is disabled the "old" code should be used.
In this pr I removed some of the …

Fixed redundant article and comment markdown parsing

---

app/models/reaction.rb
spec/models/reaction_spec.rb

While working on #18808, we discovered an issue where the count of "public reactions" could get out of sync. Some investigation revealed a race condition:
* `counter_culture` works as an callback, sending "increment" or "decrement" instructions to the DB 
* [`sync_reactions_count`](https://github.com/forem/forem/blob/ce23832988a27c74ecf4292fe3d06a6eea0967ee/app/models/concerns/reactable.rb#L9) also invoked via a callback (as part of `UpdateRelevantScoresWorker`), but explicitly "without delay" - this version updates `reactable` with a count of currently public reactions
The issue, then, is if `counter_culture`'s callback should happen _after_ `sync_reactions_count`, it will end up decrementing from what is actually the correct count. It seems like a solution could be introducing a delay, …

Try having sync_reactions_count as a background job

---

app/assets/stylesheets/views/article.scss
app/views/articles/_multiple_reactions.html.erb

This PR fixes three things:
1. Dark mode multiple-reaction icon color fix
2. Show drawer above on screens between 640px to 768px
3. Remove `Add Reaction` hover tooltip
- Related Issue #19008
**How to use multiple reactions?**
1. Enable the `multiple_reactions` FeatureFlag at `/admin/feature_flags/features`
2. View an article
3. Check heart+ icon.
Check dark mode design for multiple reaction icon
| Before  | After |
| ------------- | ------------- |
| <img width="67" alt="Screenshot 2023-01-30 at 8 22 10 PM" src="https://user-images.githubusercontent.com/9396084/215517873-118527cb-f9f3-4027-9f1c-73849e68891a.png"> | <img width="59" alt="Screenshot 2023-01-30 at 8 25 49 PM" src="https://user-images.githubusercontent.com/9396084/215517886-bdebc065-2826-44f3-97f0-fdb3a8188298.png"> |
| <img …

Multiple reactions minor fixes

---

app/assets/stylesheets/base/main.scss
app/views/layouts/_user_config.html.erb
app/views/layouts/application.html.erb

I believe I introduced misinformation about what was, in fact, dead code which lead to a bug.
I think I spoke to casually about what exactly is likely to be "dead code", and pointed to a place and was wrong about it.
We introduced [this PR](https://github.com/forem/forem/pull/19036) which was code which is _mostly_ not used anymore, but it turns out it is. This "hidden shell" code is added to iframes — and since we actually do still use an iframe to load the mod panel, the code is still needed.
This was my bad about introducing confusion.
***
In order to make up for this, I have deleted _one line of code which is in fact un-used in a similar way_.
The line `<div id="message-notice"></div>` is only used in our since retired messaging part of the app, and this _can_ be removed.
There are …

Revert hidden shell cleanup (after I gave bad information 🤦‍♂️ )

---

app/queries/display_ads/filtered_ads_query.rb

Fixing a bug which was introduced in https://github.com/forem/forem/pull/18981
This behavior is somewhat hard to test given the final "randomization" step, so I did not improve on the testing miss, but I believe this will fix the bug.
This bug was introduced in a refactor — which was really caused by a problem with _the old code_.
Here is the old code before the refactor. You'll see that `order` was set in two places, but the second place actually doesn't do anything.
The second statement changes the query in place without actually applying it to the query changing. This bug was in place in the old code, but as noted, we used to actually set this in that first statement.
- Related Issue https://github.com/forem/forem/pull/18981
This chart demonstrates the problem that arised because of …

Fix FilteredAdsQuery ordering bug

---

spec/rails_helper.rb

Not sure how long it has been like this but we do not have proper retry for retry enabled
resolves https://github.com/forem/forem/issues/19097
n/a

Enable rspec-retry on system and request specs

---

spec/rails_helper.rb

I have a reason to believe that the recent uprise of db related failure is related to retries. I have an unverified suspicion that rspec-retry does not work well with rspec's `use_transactional_fixtures`.
n/a

Revert "Enable rspec-retry on system and request specs (#19103)"

---

app/views/articles/_single_story.html.erb

We're still seeing inconsistent behavior from the `multiple_reactions` feature-flag on `#index` views. For initial launch, we're going to remove `multiple_reactions` from `#index` views, restoring the original/current "simple reactions" view. We have a separate issue (#19135) to revert this change, when we're ready to turn `multiple_reactions` on across all `#index` views.
- Closes #19134
- Related Issue #19135
[Changes …

(Temporarily) Remove multiple reactions from #index

---

app/views/articles/_multiple_engagements.html.erb

Flipping the multiple reactions feature flag created a site slowdown and memory issue.
I've tracked it down to calling `image_tag reaction.icon` _without_ including the `.svg`. The _first time this is called_ takes a long time — negligible in development, but basically times out and causes problems in prod.
In both cases, once it tries and fails, it works fine afterwards — but the damage caused on this attempt are pretty severe, and this actually continue to happen every time we redeployed if we didn't deal with it.
- Related Issue https://github.com/forem/forem/issues/19008

Fix icon memory issue

---

.github/workflows/ci-cd.yml
codecov.yml

After speaking with @jaw6 , we both agree that, anecdotally, expanding CI count seems to have made spec flakier. We want to test that assumption here. This adds 3 minutes to CI time but I think not too significant.
- Cut CI node down by 3 each for Rspec and Cypress
- Slightly change how CI-status-check works, hoping that it will re-run more reliably.
- Change CodeCov's patch target to be 90% while removing the wait time.
n/a

Update CI node count

---

app/controllers/admin/reactions_controller.rb
spec/requests/admin/reactions_spec.rb

Occasionally, a reactable will receive a false vomit report. When the report is invalidated, the reactable would need some cache to be purged.
n/a
n/a

Touch reactable after taking admin action

---

.github/workflows/ci-cd.yml

- Remove the now redundant slack notification on CI failure.
- add build concurrency:  You can have only one workflow running at a time per branch/pr. This mean on subsequent push, the previous workflow will be canceled and replaced. However, `main` branch will operate more of a queue style.
n/a

[CI] Add concurrency & remove slack alert

---

.github/workflows/ci-cd.yml

`setup-ruby` action is broken with the latest update. It does not restore cache anymore, making all of my optimization redundant. They are working on a fix, but it's already been a few days.
n/a

[CI] Lock setup-ruby to v1.144.0

---

.github/workflows/ci-cd.yml
config/initializers/sprockets_uglifier_with_source_maps_compressor.rb

For some reason, the suggested Rubocop rule for file append is prohibited during production asset compilation.
n/a
Test should pass. I also updated 1 build environment is be production-like.
n/a

Undo changes to Sprockets::UglifierWithSourceMapsCompressor

---

app/assets/javascripts/initializers/initializeArticleReactions.js

This PR fixes the heart+ icon appearance in the sidebar when all reactions in the drawer are deselected.
- Closes #19138 
1. Log in as admin
2. Enable multiple reactions feature flag
3. Go to any published post
4. Hover your mouse pointer over the heart icon in the sidebar to open up the reaction drawer
5. Select any combination of reactions then deselect all
6. See that the heart icon is inactive
https://user-images.githubusercontent.com/88938117/227767516-7ffff828-6c5b-408d-8115-bd7de0996d9f.mp4
None …

Fix like icon in sidebar

---

.github/workflows/ci-cd.yml
babel.config.js

I figured out why cypress code coverage was working half of the time and stopped working completely on `main`
- The way I checked for env var in `babel.config.js` was incorrect.
- Webpack(er) does not watch `babel.config.js` so it will not recompile when file changes. This requires full cache purge hence the added "v2" in cache name.
- `main` branch was retrieves cache from previous commit, which is still the uninstrumented compiled JavaScript.
n/a
n/a

Fix broken cypress code coverage

---

app/assets/javascripts/utilities/buildArticleHTML.js

Reaction icons in lazy-loaded feed items are unexpectedly joined by commas, which makes the row of icons visibly bloat compared with server-rendered ones.
- Related Issue #19202
- Closes #
Server-rendered reaction icon train:
Lazy-loaded reaction icon train:
The latter has commas between spans:
issue template so Community Success can …

fix lazy-loaded multiple reaction icons joined by commas

---

app/controllers/feedback_messages_controller.rb

Ｗe want to have better cache key convention, and about this key why not use `cache-key-with-version`? 
My idea is that the original `key` itself is not related to `updated_at` or other timestamp colums, so only `cache-key` is used, which can be closer to the convention on one hand and not change the original behavior on the other.
```ruby
Product.new.cache_key     # => "products/new"
Product.find(5).cache_key # => "products/5"
Product.find(5).cache_key_with_version # => "products/5-20071224150000"
```
- Related Issue #19102

Refactor cache-key on FeedbackMessagesController#create

---

config/environments/development.rb

Bullet sometimes complains about an unused eager-loading for `distinct_reaction_categories`, but this is a false-positive. The Bullet error can be seen if you have an entire page's count of articles without reactions. That's situational at best and is very unlikely to be worth addressing with conditional scopes in our code.
* Create a bunch of articles locally in `console` ?
* Or maybe delete seeded reactions?
```
GET /locale/fr?i=i
15:58:55 web.1       | AVOID eager loading detected
15:58:55 web.1       |   Article => [:distinct_reaction_categories]
15:58:55 web.1       |   Remove from your query: .includes([:distinct_reaction_categories])
15:58:55 web.1       | Call stack
15:58:55 web.1       |   /path/to/forem/app/services/articles/feeds/large_forem_experimental.rb:103:in …
```

Tell Bullet to ignore unused `distinct_reaction_categories`

---

app/javascript/packs/baseInitializers.js

If one navigates directly to `/notifications`, there's a background XHR to `/reads` (which marks notifications as read). If one clicks to this page via the "bell icon", there's no XHR to `/reads`.
- Closes #19337
* Navigate to `/notifications` by clicking on the "bell icon"
* Observe that there is a request to `/reads` (via either `log/development.log` or browser console/network)
`cc` @benhalpern @lboogie04

Restore marking notifications as read via InstantClick

---

app/javascript/packs/articlePage.jsx

Removed "Comment section viewable" ahoy event, discussed in https://github.com/forem/forem-internal-eng/issues/523#issuecomment-1506086754
- Related Issue https://github.com/forem/forem-internal-eng/issues/523
The comments section should be viewable/usable as before.

Removed tracking 'comments section viewable' ahoy event

---

config/routes.rb

We've defined routes in the following format: 
```
get "<route>", controller: "<controller_name><action>"
```
for example: 
```
get "/async_info/navigation_links", controller: "async_info#navigation_links
```
Whilst this route works and is an established pattern in our routes the `controller: "<controller_name>#<action>"` syntax _should not work_, however _it does_. 
- 💬 https://github.com/forem/forem/pull/19285#discussion_r1160668865
- Closes #19371 
The changed routes are both pointing at `async_info`, so browser with `console`, `Network` tab, filter for `async_info` — confirm mobile / navigation / hamburger.

Refactor 'controller:' to 'to:' in routes

---

.github/ISSUE_TEMPLATE/-core-team-only---new-approved-feature.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/issue.yml

A few changes to clean up our GitHub / GitHub Discussions flow.
* Adding a new issue template (FYI I used the [GUI here](https://github.com/forem/forem/issues/templates/edit))
* Cleaning up links found on the "[choose issue](https://github.com/forem/forem/issues/new/choose)" page
* Tweaking our (GitHub Actions powered) automated comment that is posted after a new issue is created

Update issue templates and automatic comment on new issues

---

app/models/display_ad.rb

We want to boost ad placements for new ads. This PR adjusts the "random sampling" logic that happens in `DisplayAd.for_display` from a 1/8 chance of a totally random ad to:
*    30% of views should go to "new" billboards, as defined by those from the filter step which also have fewer than 1000 impressions.
*    5% should still go to completely random, from the filter set.
*    The remaining random allotment goes towards that "top" tier.
- Related Issue #18870
- Closes #19302

Tweak 'last step' random sampling to favor new ads

---

app/controllers/articles_controller.rb
app/controllers/comments_controller.rb
spec/requests/articles/articles_show_spec.rb
spec/requests/comments_spec.rb
spec/requests/editor_spec.rb

Use `ContentRenderer` when previewing comments and articles, if the `:consistent_rendering` feature flag is enabled.
- Related Issue #18649 #18650
- Closes #19099
- enable the `:consistent_rendering` feature flag
- you should be able to preview articles and comments as usual

Consistent rendering on preview: comments and articles

---

app/controllers/admin/html_variants_controller.rb
spec/requests/admin/html_variants_spec.rb

While working on the UI interaction initializer, I ran into an issue where the `/admin/customization/html_variants?state=mine` page (which you get redirected to when you create an HTML variant) wouldn't load in development, which turned out to be Bullet complaining about a query.
In fixing that I also realised that the page was buggy (i.e. other admins could not see HTML variants that weren't yet approved, only the person that created them could see/approve them in the "mine" tab) so I fixed that as well + added better specs
We're moving off HTML variants entirely in the (fairly near-term?) future, but in the meantime they are still being used and this seemed like an easy enough win
N/A
- Log in as an admin user
- Navigate to the HtmlVariant admin page …

Bullet and access policy fix for HtmlVariant admin page

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/components/FollowUsers.jsx

If you navigate to `/onboarding`, the `Follow` / `Following` buttons for suggested follows don't appear to obey the "contrast rules" — things initially seem fine, but if followed, the text becomes much too dark. 
The button color setting comes from Admin > Customization > Config > User Experience & Brand > Primary brand color hex.
We [actually have a contrast validator](https://github.com/forem/forem/search?q=low_contrast%3F) that checks this brand color against "white text", but the text in these buttons becomes dark when unfocused.
I was able to track this down to the `.crayons-field__label` extension — without it, the text stays high-contrast white even when unfocused. This class _is_ used in other areas, but I think the bug is specific to onboarding. It's possible there are other ways …

Maintain contrast for onboarding follower button

---

app/assets/stylesheets/components/comments.scss
app/assets/stylesheets/components/stories.scss
app/assets/stylesheets/config/_colors.css
app/assets/stylesheets/ltags/CommentTag.scss
app/assets/stylesheets/ltags/LinkTag.scss
app/assets/stylesheets/themes/dark.css
app/javascript/articles/__tests__/Article.test.jsx
app/javascript/articles/__tests__/utilities/articleUtilities.js
app/javascript/articles/components/CommentListItem.jsx
app/javascript/articles/components/CommentsCount.jsx

We have had some design improvements sitting unimplemented for some time because they likely require additional functionality adjustments to _fully see them through_.
This is a quick low-hanging-fruit pass at some of the tweaks which do not require full-on new functionality. It does add smarter truncation logic as opposed to using the fade-out we had before, with `See more` inserted either as the truncation of a long paragraph or after other rich content.
Otherwise, it tweaks some display logic to limit the vertical space used up by embeds and/or images.
I also fixed a small style bug on the async-rendered feed cards in general along the way.
- Closes https://github.com/forem/forem/issues/19415
**Instructions:** If testing locally and wanting to quickly view comments showing up in feed …

Implement low-hanging-fruit feed card comment frontend tweaks

---

app/assets/stylesheets/components/comments.scss

@anujbhavsar96 noticed that the code-block UI in comments on home-feed card overflows and because of which the design looks bad.
Slack communication: https://forem-team.slack.com/archives/C7GE84DEJ/p1683519258722579
- Related Issue #19415
**How to test?**
1. Open `app/models/article.rb` and change logic in `has_many :top_comments,`, basically change `comments: { score: 0.. }`
2. Copy dummy content for comments from here: https://gist.github.com/rt4914/ca54375f012ff25ebd5f39dc7dd83dcc
3. You can post this comment on any post locally. Maybe past it on 2/3 posts so that you can easily find it in home-feed.
4. Once you have added comment on any post, open home feed and check that comment on various screen sizes and notice that it works now.
| Before  | After |
| ------------- | ------------- …

Design fixes for home feed comments

---

app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/__tests__/FollowUsers.test.jsx
testSetup.js

Part of the onboarding process is a chance to follow some suggested users in that Forem.
Previously by default none of the suggested users were selected to be followed; now the default is that all the suggested users are selected. The user can still opt out with the Deselect all button.
I also updated the `FollowUsers` component's unit tests to properly test for elements' existence
- Related Issue #19363 
- Closes #19363 
- Create a new account and sign in
- Go through the onboarding flow
- Note that when you get to the "Suggested people to follow" section, all the suggested users are already selected
https://user-images.githubusercontent.com/29291843/236564539-08a1d495-4bc3-4fcf-8e58-1105e92f2c80.mp4 …

Follow all suggested users by default when onboarding

---

app/controllers/users_controller.rb
app/lib/constants/settings/general.rb
app/models/settings/general.rb
app/services/settings/general/upsert.rb
app/views/admin/settings/forms/_onboarding.html.erb
spec/requests/admin/configs_spec.rb
spec/requests/user/user_suggestions_spec.rb
spec/system/articles/user_edits_an_article_spec.rb

During `/onboarding`, users are shown a list of users that we recommend they follow. This list is composed by mixing ["recent users"](https://github.com/forem/forem/blob/b09b0207c6b0f3ad32e33452f39ebaf73e1a60e6/app/services/users/suggest_recent.rb) and [admin-defined / manually-curated users](https://github.com/forem/forem/blob/main/app/views/admin/settings/forms/_onboarding.html.erb#L31-L47). This PR removes the latter, removing manual curation for onboarding suggested user follows.
- Closes #19413
QA via `/onboarding`

Remove manual user follow suggestions

---

db/seeds.rb
uffizzi/Dockerfile
uffizzi/docker-compose.uffizzi.yml
uffizzi/entrypoint.sh

Move seeding db a part of rails startup and remove the seed container.
This also fixes the issue where user's profile generated in the seed.rb isn't saving. THis was because it was because the rails container and seed container did not share the same volume.
https://github.com/forem/forem-internal-eng/issues/602
Visit the Preview environment. You should be able to see all profiles pictures and all operation should work normally.
n/a

[CI] Remove seed container from Uffizzi

---

app/services/html/image_uri.rb
app/services/html/parser.rb
spec/services/html/image_uri_spec.rb

There's a subtle problem with GitHub embeds, that's emerging now that we're generally [rendering things consistently](#19091). The mangled images are generally `badge.svg` — the images that are generated from repository CI/CD checks. As a general rule, when embedding, we try to pre-process images to better fit our layout. We exempt `camo.githubusercontent.com` from much of this pre-processing, as we generally trust content coming from github. 
We either need to similarly exempt these badges, or we need pre-processing that does not mangle SVGs. 
- Related Issue #19359
This can be tricky to replicate, as the local development environment generally does not do any of the image pre-processing. It can be best seen on canary, although the pre-processing there differs from what's done on Dev. …

Try to fix mangled github image embed

---

app/assets/stylesheets/components/cards.scss
app/assets/stylesheets/components/stories.scss

1. Change the background of all the sidebar cards + billboards to white _(same as article cards)_ `background: var(--card-bg)`. Changing the style of the CSS class `.crayons-card--secondary` should change all the sidebar cards's backgrounds. 
2. Change the border of the main cards _(article card, header in profile, etc.)_ to `box-shadow: 0 0 0 1px var(--card-secondary-border)`, same as the sidebar cards border. Changing the value in `.crayons-story` & `.crayons-card` should work. 
| Before | After |
| ------ | ------ |
| ![dev to_](https://github.com/forem/forem/assets/84626054/6aeb806a-fe89-4938-a72e-f92eefecd14c) | ![dev to_ (1)](https://github.com/forem/forem/assets/84626054/9b1bdd3d-f7d9-4be3-8939-6a69ddb115f0) |
| ![dev to_arafat4693_hot-css-tools-for-everyone-1b8o …

Background and border color adjustment for the cards 

---

app/models/users/setting.rb
spec/models/users/setting_spec.rb

We are using an incorrect validation that is allowing our users to have negative experience level
Resolves https://github.com/forem/internalCommunity/issues/366
n/a

Update experience_level's validation

---

app/views/stories/_main_stories_feed.html.erb

We currently show three billboards in home-feed:
-`feed_first` - Before all home page posts
-`feed_second` - Between 2nd and 3rd posts in the feed
-`feed_third` - Between 7th and 8th posts in the feed
The placement of `feed_second` and `feed_third` is incorrect in some cases.
- Related #19225
- Closes #19505
[Video Output with all testing related guidelines.](https://www.loom.com/share/48f05a48b9814bbab0921859de23f476)
The reason I have not provided detailed steps here only because:
- it involves using two windows, one for admin and one for incognito user and multiple back & forth between both the windows
- the logic has also been explained in the video just to make sure that it makes sense to reviewer too.
That being said if you still need any help, feel free to ping me to do this review …

Fixed billboard placement on home feed

---

app/assets/stylesheets/config/_generator.scss
app/assets/stylesheets/config/_variables.scss
app/assets/stylesheets/widgets.scss
app/views/shared/_display_ad_header.html.erb

Fixes the styling for overly-long organization names.
While I think this is an okay fix from a code perspective, I'm going to leave the bug open in case we want to circle back with a better design solution.
- Related Issue https://github.com/forem/forem/issues/19527
- Closes #
**Bug:**
**Fix (still sort of awkward, but not totally broken):**
**Validation that it still looks appropriate on shorter orgs:**

Fix styling for orgs-with-long-names promoted billboard

---

app/models/article.rb
spec/models/article_spec.rb

> We've had a report of a trusted user being prompted to look at the articles of a new post author - only that the posts lead to a 404. - The URLs all include 'temp-slug', which is used to create draft posts (e.g. https://dev.to/codenewbieteam/dream-big-whats-your-ideal-job-2ngb-temp-slug-2389119)
- Closes #19562 
You can observe the bug if you have at least one moderator user and create a new draft post as another user.
No.

Fix mod notifications for draft posts

---

app/models/comment.rb
config/locales/models/en.yml
config/locales/models/fr.yml
spec/models/comment_spec.rb

This adds a "title" of `[image]` to comments which otherwise have a "blank" title. This fixes a notification bug and UX issue, as well as providing a page title to comment permalinks which are just an image, and currently just show `- DEV Community`.
This will close a notifications bug, but may not actually address the root cause. I thought this was an appropriate improvement given the multiple problems with a fully blank title in this context.
Overall this is an upstream fix to help a few areas.
- Relates to https://github.com/forem/forem/issues/19336
This may be small enough to just validate via code review, but to see the title in prod:
- Sign in to Uffizzi (`admin@forem.local`, password: `password`)
- Create a comment that is just an image
- Click into that image's permalink. It …

Add image title for comment

---

app/javascript/utilities/videoPlayback.js

There are low-level warnings from eslint about this line that I would rather we didn't ignore. I kinda think I don't like `prefer-destructuring`, but for now I just want to disable the one line that is constantly getting the warning, we can have the larger conversation later.

Try to stop eslint complaining about destructuring

---

app/assets/stylesheets/components/cards.scss

Quick fix as follow up to: https://github.com/forem/forem/pull/19635
It is causing profile images to be cut off. This reduces the scope of the css to only apply to that one type of card.

Quick fix: Only apply overflow conditions to billboard cards

---

app/javascript/onboarding/components/FollowUsers.jsx

@PhilipHow and I were chatting about the follow suggestions page during `/onboarding` (because of the [org suggestions feature](https://github.com/forem/forem/pull/19619)) and how it's a bit slower than we'd like — the network round-trip isn't detectably slower than other `/onboarding` end-points, but subjectively, it feels like there's more delay. We may later decide we want to look more closely at query performance, but for the short-term, it seemed a loading-spinner might help with the user experience around the delay.
_I don't think we have an issue for the performance, specifically..._
For developers, you can add `sleep(10)` to the `onboardings_controller#users_and_organizations` to delay the response.
Here is a recording (with a long `sleep`):
_If your PR includes UI changes, please …

Spinner during onboarding follow suggestions

---

Containerfile.base

This builds a Debian-derived base image that targets Ruby 3.0.2 (our current version lock) to replace `quay.io/forem/ruby`, which is based on Fedora 35 (and as such, lacks ARM64 support).
The building of this image is not yet automated, I intend to add that as a follow-up some time vaguely soon-ish. This has been built and pushed to a temporary tag,
[ghcr.io/forem/ruby:klardotsh-test](https://github.com/orgs/forem/packages/container/ruby/103882793?tag=klardotsh-test). Once this merges, I'll build and push the result in main (pending any revisions that come up in PR review) with the following incantation, which will generate a multiarch manifest:
```sh
docker buildx build --platform linux/amd64,linux/arm64 -f Containerfile.base . -t ghcr.io/forem/ruby:latest -t ghcr.io/forem/ruby:$(git …
```

devxp: Replace forem/ruby image with open-source Debian-based analogue.

---

config/initializers/datadog.rb

I did not realize that DataDog's log_injection was applied to all, making server log a pain to use in development. This will hopefully improve DX.
n/a

Disable DD's log_injection in development

---

app/assets/stylesheets/components/cards.scss
app/assets/stylesheets/widgets.scss

Quick style fix. The max height and overflow is currently applying to below-comment locations when it should only actually apply to the sidebar widget spot.
- Closes https://github.com/forem/forem/issues/19682

Move max-height and overflow auto to proper billboard child

---

app/assets/stylesheets/components/stories.scss
app/assets/stylesheets/ltags/LinkTag.scss
app/views/articles/_liquid.html.erb
spec/liquid_tags/link_tag_spec.rb

As we introduce more dynamic content into the feed via billboards, this is a pass to get the font size just right for this scenario. The current size we'd been using is too large for the varied content and looks out of place in the feed.
This includes an adjustment to make the base paragraph font size in feed billboards `fs-base` as well as some tweaks to make link embeds less gigantic.
Also included is a tweak to remove the read time from link embeds, as a small de-cluttering of a functionality which could use simplification. This will not not break any styling, but won't automatically update old embeds. This falls in line with the approach of making small compatible tweaks to improve liquid embeds where possible given re-rendering constraints.
- Related Issue …

Change feed billboard font size to fs-base and link embed adjustments

---

spec/system/homepage/user_visits_homepage_articles_spec.rb

A tiny commit to fix the deprecation message in tests.
```
DEPRECATION WARNING: Date#to_s("%Y-%M-%d") is deprecated. Please use Date#to_fs("%Y-%M-%d") instead. (called from block (2 levels) in <top (required)> at /home/light/sites/dev.to/spec/system/homepage/user_visits_homepage_articles_spec.rb:7)
```

Fixed deprecation message in specs

---

.github/workflows/build-base-ruby-image.yml
Containerfile.base
scripts/build_base_ruby_image.sh

This refs (but still doesn't *quite* resolve: we're getting close!) #19626, and is some opportunistic/bonus drive-by work on the way to getting #19651 merged. #19632 introduced a new `forem/ruby` image, but those builds have been generated on my workstation up til now. This automates the process with GitHub Actions: assuming I got this right, images will be auto-built and tagged any time we update `.ruby-version` or the `Containerfile.base` itself.
I unfortunately worked ahead of myself a little bit: since I've already built and pushed a `ghcr.io/forem/ruby:3.0.6`, this workflow will fail on #19626 and its merge unless I can get permissions (or can bug @maestromac to do it) to delete that tag from GHCR: it appears I can't do so currently (I can't even delete …

infra: Automatically build and push base container image when Ruby versions are updated.

---

app/assets/stylesheets/components/buttons.scss

When using keyboard navigation on the notifcations page, buttons like the "Like" button would not have the same `focus` styles as some others. Tested across Chrome, Safari and Firefox.
I was a bit clueless when starting to work on this issue and so I'm jotting down some of my learnings for others and my future self:
- The reason that we do not have a focus style on keyboard navigation for the "Like" button, whilst we have the appropriate focus styles for  "Reply" and "View" is because those are links and not actual buttons.
- I noticed that some buttons across the site had working keyboard navigation focus styles whilst others did not. After doing some more digging, I realized that the buttons with class `c-btn` had working focu styles whilst buttons with `crayons-btn` did not have …

Apply focus styles to `crayons-btn`

---

app/controllers/api/v1/billboards_controller.rb
config/routes.rb
spec/requests/api/v1/billboards_spec.rb

- Renamed `Api::V1::DisplayAdsController` to `Api::V1::BillboardsController`
- updated the related routes, kept old routes

Renamed display_ads => billboards in the api

---

app/javascript/packs/base.jsx

Our infinite scroll pattern causes problems with the browser's back button: specifically, if you've scrolled into page 2+, click into a post, then back to the feed, the browser scroll position will not be where you had previously scrolled. This seems to fix it, even though it seems like it should have  the opposite effect.
- Closes #19595 
https://www.loom.com/share/c7e595c9608247e086e4f0b7b00b621d?sid=9b2e1049-695a-4a86-9c9b-a7d5527c04b5
No

Try to fix inconsistent scrolling bug

---

app/controllers/billboard_events_controller.rb
spec/requests/billboard_events_spec.rb

Take both :display_ad_event params and :billboard_event in case of cached js

Take :display_ad_event params as well as :billboard_event 

---

app/assets/javascripts/initializers/initializeDisplayAdVisibility.js
app/controllers/billboard_events_controller.rb
app/javascript/packs/billboardAfterRenderActions.js
app/models/display_ad_event.rb
app/services/billboard_event_rollup.rb
spec/requests/billboard_events_spec.rb
spec/services/billboard_event_rollup_spec.rb

Alias `display_ad_id` to `billboard_id` as suggested [here](https://github.com/forem/forem/pull/19788/files#r1270377284)

Aliased DisplayAdEvent.display_ad_id to billboard_id

---

app/controllers/admin/users_controller.rb
app/queries/audit_log/unpublish_alls_query.rb
spec/queries/audit_log/unpublish_alls_query_spec.rb

Bullet was complaining on member manager => users in development ( `/admin/member_manager/users/:id` ) because of the unused "includes(:user)" (mentioned in https://github.com/forem/forem/pull/19812) .
We could remove the `includes` (it's not a big deal because it's only used by admins), but it's not the ideal solution: we do use `includes` , but only on one tab (`unpublish_logs`).
In this pr I changed the logic so that data will only be requested on a relevant tab, not on all user tabs. So, a bit of optimization along with the bullet warning removal.

Only query unpublish_all data on a relevant tab in the member manager

---

app/policies/application_policy.rb
app/policies/html_variant_policy.rb

I've been seeing a lot of warnings like this recently:
```
DEPRECATION WARNING: minimal_admin? is deprecated and will be removed from Rails 7.1 (Deprecating ApplicationPolicy#user_admin?, use ApplicationPolicy#user_super_admin?) (called from block (3 levels) in <top (required)> at /home/runner/work/forem/forem/spec/policies/html_variant_policy_spec.rb:10)
```
This is a _little_ misleading... the deprecation warning isn't connected to Rails at all, it's [something we did](https://github.com/forem/forem/pull/16523), but the default messaging from the `deprecate` macro assumes Rails' lingo. 
To summarize:
* We used to have a method `minimal_admin?`, which meant something like "at least `admin` but possibly also `super_admin`"
* We refactored, moved some methods around, such that we preferred …

Address minimal_admin deprecation

---

app/controllers/billboard_events_controller.rb
app/models/billboard_event.rb
app/models/display_ad.rb
app/models/user.rb
app/services/billboard_event_rollup.rb
app/views/articles/index.html.erb
app/views/billboards/show.html.erb
app/views/shared/_display_ad.html.erb
app/views/sidebars/_homepage_content.html.erb
app/views/stories/_main_stories_feed.html.erb
spec/factories/billboard_events.rb
spec/models/billboard_event_spec.rb
spec/requests/billboard_events_spec.rb
spec/services/billboard_event_rollup_spec.rb

Renamed `DisplayAdEvent` to `BillboardEvent`: model and factory
Billboard events functionality should work as it did before

Rename DisplayAdEvent to BillboardEvent

---

app/services/fastly_config/snippets.rb

This is the sibling commit to an internal infra PR (which will be linked to anyone who has viz to that repo...) which has more of the context of "why" on this, but for public record keeping's sake, here's a partial copy of that text:
> In forem/forem, there's a FastlyConfig service which uploads various VCL snippets to Fastly and manages versions of them. This is a conflict of concerns in a Terraformed environment: if the Forem service uploads a VCL snippet to the service, the next Terraform apply may wipe those snippets out, as the Terraform state has no idea those snippets are supposed to be part of the service it's managing.
>
> Rather than allowing drift (allow_changes would allow us to create "dummy" snippets with no contents but matching names to what the Ruby side would create, and …

fastly_config: Soft-deprecate FastlyConfig service used only for DEV.

---

app/controllers/application_controller.rb
app/views/notifications/shared/_article_preview.html.erb
app/views/notifications/shared/_comment_box.html.erb
cypress/e2e/seededFlows/notificationsFlows/notificationInitialization.spec.js

When we're ready to "fully launch" subscribe-to-comments, this PR removes the feature flag, enabling the feature for all users.
- Closes #19350 
There's extra queries on the `/notifications` page now, would be good to keep an eye on performance under heavier user-load.

Un-flag subscribe-to-comments

---

db/schema.rb
spec/queries/display_ads/filtered_ads_query_spec.rb

While working on the billboards location targeting, I stumbled on this flaky spec and quickly realised what was wrong with it
Basically, the spec was using `123` as a "no org matches this" id - however, when the full test suite is run in parallel like in CI, there's a small chance that there _will_ have been enough other organizations created in other tests that one of the organizations created _for this spec_ actually has the id `123`. The ads query would then pick up that org's community billboard instead of the in-house one it is supposed to detect and return if the org doesn't exist/doesn't have any community billboards.
To fix it I added an organization that explicitly doesn't have any billboards and used its ID instead of `123`.
- Related Issue #19666 (it's already been closed, but …

Fix flaky FilteredAdsQuery spec

---

app/controllers/admin/billboards_controller.rb
app/controllers/api/v1/billboards_controller.rb
app/controllers/billboards_controller.rb
app/controllers/stories_controller.rb
app/models/display_ad.rb
app/models/organization.rb
app/models/tag.rb
app/queries/billboards/filtered_ads_query.rb
app/services/markdown_processor.rb
app/views/admin/billboards/_form.html.erb
app/views/admin/billboards/edit.html.erb
app/views/admin/billboards/index.html.erb
app/views/admin/billboards/new.html.erb
app/views/billboards/show.html.erb
spec/models/organization_spec.rb
spec/queries/billboards/filtered_ads_query_spec.rb
spec/views/admin/billboards/new_spec.rb

Renamed variables, constants, method names from `display_ad` to `billboard`.
Renamed `DisplayAds` namespace to `Billboards`, user and organization associations (display_ads => billboards)
- Related Issue #19372 
Billboards functionality should continue working as expected

Renamed display_ad variables to billboard

---

.github/workflows/build-base-ruby-image.yml

In #19871 base images changed to referencing `.ruby-version-next` (enabling two-PR sequences for updating our Ruby version target), but the corresponding GitHub Action was not updated, now necessitating a manual CI run for that particular version update. This commit fixes this oversight for future runs.

ci: Track changes to .ruby-version-next for base image builds.

---

.github/workflows/build-base-ruby-image.yml

Turns out I forgot one more condition to make the merge of #19875 actually useful: `workflow_dispatch` has to be allowed to push to GHCR :facepalm: Failure to do so results in actions runs [like this one](https://github.com/forem/forem/actions/runs/5742595405/job/15565026133) which don't populate `ghcr.io/forem/ruby` with a new tag.

ci: Allow workflow_dispatch runs to push to GHCR.

---

app/models/admin_menu.rb
app/models/display_ad.rb
app/views/admin/billboards/_form.html.erb
app/views/admin/billboards/edit.html.erb
app/views/admin/billboards/index.html.erb
app/views/admin/billboards/new.html.erb
app/views/shared/_billboard_header.html.erb
config/environments/development.rb
config/locales/controllers/admin/en.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/views/admin/en.yml
config/locales/views/admin/fr.yml
cypress/e2e/seededFlows/adminFlows/billboards/deleteBillboards.spec.js
cypress/e2e/seededFlows/adminFlows/billboards/editBillboards.spec.js
spec/lib/data_update_scripts/generate_display_ad_names_spec.rb
spec/models/display_ad_spec.rb
spec/queries/admin/users_query_spec.rb

Renamed locales keys and ui language display ads => billboards
I haven't changed locales and texts in the constants related to roles, because it's a more complex issue, I'll address this in a separate pr.
Billboards functionality should continue to work as it used to.

Renaming display ads to billboards: locales keys + UI language

---

app/controllers/application_controller.rb
app/services/feature_flag.rb
spec/controllers/application_controller_spec.rb
spec/services/feature_flag_spec.rb

We're still kinda new at using `flipper`, but we'd like to use it more. Specifically, we'd like to use it for `billboard_location_targeting`, but we don't always have access to a fully-inflated `User`, we sometimes _only_ have `user_id`. This is a quick refactor to make our `FeatureFlag` wrapper utility work better for this case.
- Related [#19757 ](https://github.com/forem/forem/issues/19793)

FeatureFlag.enabled_for_user(_id)

---

app/models/settings/base.rb

One of the major changes in ruby `3.1.4` is that `psych` (the yaml engine) has switched the `load` method so that it's _no longer_ an alias for `unsafe_load` and is now an alias for `safe_load`. In [that PR](https://github.com/forem/forem/pull/19912), it made more sense to rewrite this method to preserve the original "unsafe" functionality, but I suggested we could switch it over to `safe_load` in a follow-up PR. This is that follow-up.
This code is backing the Admin::Settings page (although not _all_ the settings use it), you can test this PR by visiting `http://localhost:3000/admin/customization/config`, changing settings and refreshing to ensure that they are displayed correctly. (Any errors would be at read-time, not at write-time, for what it's worth.)

Switch settings to safe yaml load

---

spec/queries/billboards/filtered_ads_query_spec.rb
spec/requests/billboard_events_spec.rb
spec/services/content_renderer_spec.rb

Renamed a few test descriptions that were left.
I kept a couple of those referencing class name (`DisplayAd`) - it should be changed with the class renaming.

Renamed display ads to billboards in tests descriptions

---

app/services/images/optimizer.rb
spec/services/images/optimizer_spec.rb

In fixing the zoomed image issue recently we passed an argument which breaks some imgproxy profile images.
- Related Issue https://github.com/forem/forem/pull/19975

Fix never_imagga for imgproxy

---

app/queries/articles/active_threads_query.rb
spec/queries/articles/active_threads_query_spec.rb

Remove the _hardcoded_ `MINIMUM_SCORE` for the appropriate score which is configurable by admins.
- Related Issue https://github.com/forem/forem/issues/20003

Adjust ActiveThreadsQuery to use home_feed_minimum_score

---

app/controllers/admin/application_controller.rb

After [changing](https://github.com/forem/admin-docs/pull/42) the `admin-docs` we need to update the corresponding url to point to the correct page.

Changed admin docs url from display-ads url to billboards

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb

- I've added `z-index` of each reaction buttons to fix this [issue](https://github.com/forem/forem/issues/19722).
- According to [the mdn doc](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context), if a element's opacity is changed to less than 1, its stacking context is also changed. It causes that the tooltip is displayed behind the other elements. To fix this issue, I've added a code to set `z-index` explicitly.
- Closes https://github.com/forem/forem/issues/19722
https://github.com/forem/forem/assets/17381979/1d94febe-32c6-436a-8250-8 …

Set reaction's z-index to show the tooltip in front of other comments

---

app/javascript/packs/dashboardTags.js
app/javascript/tags/Tag.jsx
cypress/e2e/seededFlows/dashboardFlows/hiddenTags.spec.js
cypress/e2e/seededFlows/tagsFlows/followTag.spec.js

When we unhide a tag, we should "unfollow" it too, hence the user should see a "Follow" button.
- Related Issue #https://github.com/forem/forem/issues/20039
- Closes #20039 
**TAGS PAGE:** 
- Go to /tags and click the "follow" button to follow tags. Refresh the page and ensure that they stay followed.
- Now click on the "Following" button to unfollow the tags. Refresh the page and ensure that they stay unfollowed.
- Now find a tag card with a "Follow" button and a "Hide" button. Click on the "Hide" button to to hide the tag. The "Follow" Button should disappear and an "Unhide" button should show up in place of the "Hide" button.
- Now find a tag card with a "Following" button and a "Hide" button. Click on the "Hide" button to to hide the tag. The "Following" Button should disappear and an …

Unhiding a tag should unfollow it too

---

app/lib/middlewares/set_cookie_domain.rb

A tiny pr to remove old SiteConfig references which was replaced by `Settings::General` in the comments to remove confusion.
- Related Issue https://github.com/forem/forem/pull/13573

Replace SiteConfig with Settings::General in the comments

---

config/initializers/datadog.rb

Fix a typo for configuring [Redis](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#redis).
- Closes #

Fix typo of configuring redis at datadog initializer

---

app/models/user.rb
app/models/user_language.rb
app/services/languages/detection.rb
db/migrate/20230906112602_create_user_languages.rb
db/schema.rb
spec/factories/user_languages.rb
spec/models/user_language_spec.rb
spec/models/user_spec.rb
spec/services/languages/detection_spec.rb

Store languages, that user understands, in the database
Discussion on how to store the languages can be found in[ the issue comments](https://github.com/forem/forem/issues/19846#issuecomment-1700587945)
The pr doesn't include the "default forem language" part (will be implemented separately) and populating users languages table.
- Related Issue #19846
The pr only provides structure for future usage, so doesn't affect the functionality

Store languages that user understands

---

app/javascript/packs/feedEvents.js
app/models/feed_event.rb
app/services/reaction_handler.rb
cypress/e2e/seededFlows/homeFeedFlows/events.spec.js
spec/models/feed_event_spec.rb
spec/services/reaction_handler_spec.rb

This updates the reaction handling service to record a `reaction` feed event when a user makes a public reaction (including bookmarks) on an article that they reached through their feed.
Per the linked issue, we're determining "reached through their feed" through simply checking if their last click (already being recorded via the UI) was on the article being reacted to.
- Related Issue #19925 
- Closes #19925 
https://www.loom.com/share/1d0e252ad3a045a4875c953294f09c34
Not a gif but ❤️ 🦄 🔥 🙌🏾 🤯 🔖

Record feed events for public reactions

---

app/javascript/actionsPanel/actionsPanel.js
cypress/e2e/seededFlows/moderationFlows/adjustPostTags.spec.js

The commented-out e2e specs in this PR have been increasingly flaky on main as well as other PR branches. Cypress has either been timing out or struggling to locate elements on the page, possibly because deferred JS has not yet arrived to add interactivity to elements that `cy` is meant to click on.
I've added a comment to a possible place to investigate in our JS; if we are able to avoid reloading the window after successful async calls without degrading performance in other ways, then our cypress implementation might be easier to clean up.
- Closes #
_If your PR includes UI changes, please …

comment out flaky specs and add comments for exploration/refactor

---

app/javascript/packs/feedEvents.js
cypress/e2e/seededFlows/homeFeedFlows/events.spec.js

The end-to-end tests introduced for feed events are flaky (which is expected due to Cypress not playing very well with normal browser scroll events, making testing collecting impressions inconsistent). This skips them and adds context for the skip

skip feed events e2e specs

---

app/services/notifications/moderation/send.rb
app/workers/notifications/create_round_robin_moderation_notifications_worker.rb
spec/services/notifications/moderation/send_spec.rb
spec/workers/notifications/create_round_robin_moderation_notifications_worker_spec.rb

Skips triggering round robin notifications if the new comment or article's creator has the `limited` role.
Also I ended up refactoring the round robin notification worker spec quite a bit because it was written a bit weirdly and specs were failing.
- Related Issue #19892 
- Closes #19892 
[coming soon]

Skip round robin mod notifications for limited users

---

app/views/dashboards/_dashboard_article_row.html.erb
config/locales/languages/en.yml
config/locales/languages/fr.yml
config/locales/views/dashboard/en.yml
spec/requests/dashboard_spec.rb

If a post (article) has a detected language: display it in the user dashboard.
I was reluctant to add a gem (like[ `i18n_data`](https://github.com/grosser/i18n_data)) to get the language names, so I "extracted" them from [the cld-related source](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-localenames-full/main/en-001/languages.json) and kept only those that are in `CLD3::TaskContextParams::LANGUAGE_NAMES` (`Languages::Detection.codes`).
Though we display only in the dashbord currently, the names themselfves seem pretty generic, so I put the names into separate locales (however open to other suggestions).
Update: I have [added](https://github.com/forem/forem/pull/20137/commits/b37ef7c4da3d74688af566128c67364612e1247e) several locales for "Latn" variations though we …

Display post languages in the dashboard

---

.rtx.toml
Brewfile
Brewfile.lock.json
README.md

This is the `forem/forem` side of a general simplification of developer onboarding on bare metal that I've been tinkering with for a bit now, and I'm quite happy with it in general (the `forem-docs` PR will get into the specifics of why).
This terseifies the README a bit by getting rid of redundant instructions, and instead defers to `forem-docs` entirely for developer environment setup (in part because choosing a path is a little bit more involved than would reasonably fit into this README). It also provides an [rtx](https://github.com/jdx/rtx) config file - this is loosely similar to the `.tool-versions` file `asdf` uses, but since I currently see no convincing arguments for supporting `asdf` over `rtx`, and since the `.rtx.toml` format supports far more usecases (if we ever need them) …

Developer Onboarding Simplification

---

app/views/admin/overview/_notices.html.erb
app/views/admin/overview/index.html.erb
spec/requests/admin/overview_spec.rb

This adds a notice to the admin section which begins warning admins that their Forem is out of date if it is two weeks since recent re-deployment from `main` and steps from yellow to red notice when the timeframe passes 4 weeks.
This alert could get more sophisticated in the future, but is a minimum notice to help maintain more healthy and up-to-date self-hosted Forems.
- Closes https://github.com/forem/forem-internal-eng/issues/290

Add out-of-date notice to admin overview

---

app/models/follow.rb
app/services/notifications/new_follower/send.rb
spec/models/follow_spec.rb
spec/services/notifications/new_follower/send_spec.rb

Don't show suspended followers in aggregate notification
- Closes https://github.com/forem/forem/issues/20173

Do not show suspended followers in aggregated siblings for notification

---

app/uploaders/logo_uploader.rb
app/uploaders/profile_image_uploader.rb
spec/services/users/update_spec.rb

- [x Feature
This is a small modification to profile image upload max to better meet user expectations. This still falls well below the 25mb max we have for other types of images.
- Closes https://github.com/forem/forem/issues/20182

Change profile image max size to 8 MB

---

config/locales/languages/en.yml
config/locales/languages/fr.yml

"no" is a reserved word in yaml, so `I18n.t "languages.display_name.no"` was giving `"Translation missing: en.languages.display_name.no"`, this pr is fixing the issue.
This lead to [a failing build ](https://github.com/forem/forem/actions/runs/6385030154/job/17329164982?pr=20189)

Fixed Norvegian locale key

---

cypress/e2e/seededFlows/articleFlows/commentOnArticle.spec.js

This PR fixes a flaky Cypress test I encountered during my contribution.
This test appears to verify that a suggestion disappears when a user enters two words following the '@' symbol and deletes two words. However, I think this test is incorrect because, when I try it manually, the suggestion remains until a user deletes the '@' character.
I think this test is supposed to always fail, but in practice, it sometimes passes because Cypress runs these processes quickly.
- Related: https://github.com/forem/forem/actions/runs/6434138956/job/17472750723?pr=20223
- Related: https://github.com/forem/forem/actions/runs/6452622377/job/17515018063?pr=20230
- Related: https://github.com/forem/forem/actions/runs/6446292233/job/17523394422?pr=20229
_Please replace this line with instructions on how to …

Fix flaky Cypress test

---

app/controllers/concerns/api/articles_controller.rb
app/services/articles/creator.rb
spec/requests/api/v1/articles_spec.rb

Allow setting and updating `published_at` via the API (creating and updating articles).
Limitations are the same as when creating from the user interface, they are handled by service objects/model.
Added yard docs for `Articles::Creator`
- Closes #20105
You should be able to create an article via the api with specified current or future `published_at`.
It should also be possible to update `published_at` to current or future values for drafts and scheduled articles.

Make it possible to schedule articles via the API

---

app/controllers/concerns/api/users_controller.rb
app/views/api/v1/shared/_user_show.json.jbuilder
app/views/api/v1/shared/_user_show_extended.json.jbuilder
app/views/api/v1/users/show.json.jbuilder
spec/requests/api/v1/organizations_spec.rb
spec/requests/api/v1/users_spec.rb

~~WIP because the partial is used in other endpoints which is not taken into account in the pr yet.~~
Added `email` field to the users api endpoint `/api/users/{id}`
Email will be displayed if `display_email_on_profile` is set, otherwise `nil` is displayed.
- Closes  #20236
Api should work with the changes described above

Add email to the users api

---

app/liquid_tags/details_tag.rb
spec/liquid_tags/details_tag_spec.rb

This PR fixes the issue of code blocks not working with details/spoiler/collapsible liquid tags.
I used `RenderedMarkdownScrubber` class to sanitize HTML tags. This class can sanitize tags while considering code blocks and is already used in the [`MarkdownProcessor::Parser`](https://github.com/forem/forem/blob/eb52b91f75c5d0c8c4f0dec03b50a72f04f3cc2f/app/services/markdown_processor/parser.rb#L38) class for the same purpose.  
(I believe that the behavior of RenderedMarkdownScrubber class is the same as that of the default scrubber, except for the consideration of code blocks.)
- Closes https://github.com/forem/forem/issues/19900
|before|after|
|---|---|
|<img width="713" alt="スクリーンショット 2023-10-08 17 35 29" src="https://github.com/forem/forem/assets/17381979/10029974-8283-4969-9ef5-7ada4e0c …

Fix code block rendering not working inside details

---

.github/workflows/ci-cd.yml

Our CI is not displaying any Jest related failure. This is due to the default reporter being overridden.
see https://jestjs.io/docs/cli#--reporters
n/a

Update CI's jest reporters

---

app/models/billboard.rb
app/services/html/parser.rb
spec/models/billboard_spec.rb
spec/services/images/optimizer_spec.rb

This adjusts quality input on billboard images because billboard images are most likely to contain text which can look fuzzy on the `q_auto` setting.
This _should not_ re-save anything, but when a billboard is organically re-saved (or as done as an administrative task on a select basis) the value will change.
_Also modified some tests to be compatible with rubocop._
- Closes https://github.com/forem/forem/issues/20308

Adjust image optimization for billboards

---

app/views/api/v1/shared/_user_show_extended.json.jbuilder
spec/requests/api/v1/users_spec.rb

Added achieved badge_ids to the api (`/api/users/{id}` and `/api/users/me`).
- Closes #20341

Added user badge_ids to the api

---

app/views/articles/_full_comment_area.html.erb
spec/requests/articles/articles_show_spec.rb

Or comment sorting buttons have created a huge amount of non-indexed pages which is not good for SEO. This submission fixes the issue.
For signed-out contexts, instead of showing the icon for comment dropdown, nothing appears:
- Closes https://github.com/forem/forem/issues/20397

Only render comment sorting for signed-in users

---

app/controllers/admin/pages_controller.rb
app/controllers/api/v1/pages_controller.rb
spec/requests/api/v1/pages_spec.rb

Allow creating and updating pages with `body_html`, not only `body_markdown` via the api
- Closes #20342

Allow creating and updating pages with body_html via the api

---

app/policies/role_policy.rb
cypress/e2e/seededFlows/adminFlows/users/manageRoles.spec.js
spec/policies/role_policy_spec.rb

We [discussed](https://forem-team.slack.com/archives/C7GE84DEJ/p1701953913307969) earlier that there is an inconsistency in role permissions: e.g. it's possible to add a `suspended` role as a super_admin, but no one could remove this role (though it was possible to remove it implicitly by adding a trusted role).
This pr fixes the inconsistency: allows to remove the `suspended` role similarly to other roles.

Allow to remove suspended role

---

app/controllers/api/v1/user_roles_controller.rb
config/routes.rb
spec/requests/api/v1/docs/user_roles_spec.rb
spec/requests/api/v1/user_roles_spec.rb
swagger/v1/api_v1.json

> Allow admins to `PUT` to a new `/users/:id/trusted` endpoint, to add the `trusted` role to a user.
> Allow admins to `DELETE` to a new `/users/:id/trusted` endpoint, to delete the `trusted` role from a user.
I copied @lightalloy's implementation https://github.com/forem/forem/pull/20445
- Closes #20403
PUT /users/:id/trusted
DELETE /user/:id/trusted

Add trusted role via API

---

.github/workflows/uffizzi-build.yml
.github/workflows/uffizzi-preview.yml

This change sanitizes user input from contributor fork workflows. This mitigates a security vulnerability identified by the `backstage` project.
This builds upon improvements in merged PR #19029 
I've tested these workflows on my fork (and on other open-source projects.) https://github.com/axisofentropy/forem/actions/workflows/uffizzi-preview.yml

GHA Workflows: Sanitize user input from fork workflows.

---

app/views/admin/users/index/_status_indicator.html.erb

In my previous pr I [mentioned](https://github.com/forem/forem/pull/20449/files/cbc05ef50e5d8fd20ce84479a9a2246c292b79ca#diff-86bc446e94f46524b00122f23d033002aecbfdcf9dcddcebe0af15b365af9cda) that there is a span with a background that is useless because user status is outside of it. I did a bit of research and found out that it was this way from the beginning. As far as I know this partial is only used in the users list in admin. There are other places that display user status with a background (e.g. feedback messages list in admin), but they use different code.
I have also talked to @michael-tharrington about the status backgrounds in the users list and found out that the list is usable as is, w/o background, so adding backgrounds doesn't make much sense. 
So, I'm removing the span in …

Remove unused user status span

---

app/javascript/packs/admin.js
package.json
yarn.lock

I did the research for the now deprecated `time-elements` package
(there was a [failed upgrade](https://github.com/forem/forem/pull/20335#pullrequestreview-1724529895) earlier)
The package was added in #14283 and was used at that time. There [was](https://www.npmjs.com/package/@github/time-elements/v/3.2.0) a tag `<local-time>` (the new `relative-time-element` package has `relative-time` tag (as well as the newest `time-elements` one), so it was a bit harder to find out).
Currently, we don't have any `<local-time>` tags, so the deprecated package can be removed.
- Closes #20426

Removed github/time-elements

---

app/controllers/admin/billboards_controller.rb
app/controllers/api/v1/billboards_controller.rb
app/controllers/billboards_controller.rb
app/models/billboard.rb
app/queries/billboards/filtered_ads_query.rb
db/migrate/20240102154708_add_requires_cookies_to_billboards.rb
db/schema.rb
spec/queries/billboards/filtered_ads_query_spec.rb
spec/requests/api/v1/billboards_spec.rb

This is only the data backend of this feature.
Some billboards could rely on cookie consent to be displayed. By default none do, and `requires_cookie` can be false, so if `cookies_allowed` is _not_ passed from the frontend, then we can only use `requires_cookie: false` (which is all billboards now and by default), but in the future if we have billboards which require cookies, then these should only show up when we pass `cookies_allowed` from the request.
- Related Issue https://github.com/forem/forem/issues/20463
- Closes #
Mostly just check if this is logically viable. If we do not pass "allowed" one way or another, we should only return `requires_cookie: false` but if cookies are passes as allowed via param, then we can return any required status (i.e. true and false are valid)
_We …

Add cookie requirement option for billboards

---

app/controllers/concerns/api/articles_controller.rb
app/models/article.rb
app/models/articles/feeds.rb
app/services/articles/attributes.rb
config/feed-variants/20240104-variant-a.json
config/feed-variants/20240104-variant-b.json
config/feed-variants/20240104-variant-c.json
config/field_test.yml
db/migrate/20240103223627_add_clickbait_factor_to_articles.rb
db/schema.rb
spec/requests/api/v1/articles_spec.rb

This adds a new field allowing a new factor in final feed ordering. It adds the A/B tests to examine its impact on community use, and adds an API endpoint to allow labeling experimentation outside of core and the allowance of third party labeling and toolking to be created by any OSS Forem admins.
- Closes https://github.com/forem/forem/issues/20494

Add articles clickbait_score as factor in final feed ordering

---

app/models/article.rb
spec/models/article_spec.rb

Quick bug fix to handle odd edge case
- Closes https://github.com/forem/forem/issues/20503

Nullify published_at if absurdly far in the future

---

app/models/comment.rb
app/workers/articles/publish_worker.rb
spec/services/notifications/moderation/send_spec.rb
spec/workers/articles/publish_worker_spec.rb

This disables calls to the code that triggers round-robin notifications, as we are re-visiting their effectiveness.
- Related Issue #20453 

Remove calls to trigger round robin notifications

---

app/services/articles/attributes.rb
spec/requests/api/v1/articles_spec.rb

This is a hot fix which fixes an issue where hitting the article update endpoint updates tags to empty if the parameter is not passed. Tags should only be updated to empty if the parameter is passed and it is empty.

Do not vacate tags if parameter not passed via API

---

app/controllers/stories/tagged_articles_controller.rb
app/services/articles/feeds/timeframe.rb
spec/requests/stories/tagged_articles_spec.rb
spec/services/articles/feeds/timeframe_spec.rb

Don't show articles with low score on timeframe feeds (/top/week, /top/month) and tag pages by timeframe: (/t/tagname/top/year).
This is part of #20452 , most of the cases were already covered, but some feeds still displayed articles with low score as I described in [the comment]((/top/week, /top/month) and tag pages by timeframe: (/t/tagname/top/year).).
- Closes #20452 
- create an article with a low score, or assign a user with articles a "spam" role
- article should not appear in feeds like `/top/week` or `/t/tagname/top/year` , it's easier to check on tag pages that don't have a lot of articles

Don't show low scoring articles in timeframe feeds

---

app/views/layouts/_top_bar.html.erb

Shows the mod icon in the top bar for trusted members.
- Closes #20520
Login into an account of a trusted member (not a tag moderator) and see the mod icon (shield) in the top menu bar.

Make icon for the mod center visible to trusted members

---

app/controllers/stories_controller.rb
spec/requests/user/user_profile_spec.rb

Return 404 on user profile if user has spam role.
Haven't impemented access for admins because I can't use `current_user` directly because of caching (so need to figure it out), I would address that in a separate pr.
- Related Issue #20473

Return 404 on user profile if user is a spammer

---

app/controllers/stories_controller.rb
app/decorators/comment_decorator.rb
app/models/comment.rb
spec/decorators/comment_decorator_spec.rb
spec/requests/user/user_profile_spec.rb
spec/views/comments/_comment.html.erb_spec.rb

We hide comments with score lower than threshold on articles page, so we need to hide them on users profile for consistency.
- Related Issue #20472

Hide low score comments on user profile

---

app/controllers/comments_controller.rb
app/views/comments/index.html.erb
spec/requests/comments_spec.rb

Render 404 on the comment path if the comment has low score (below threshold) and doesn't have children.
If a comment has children, it is displayed as deleted and children are displayed (it was implemented earlier in a different pr and `/comments` page also uses that logic)
- Related Issue  #20472

Render 404 when root comment has low score and no children

---

app/controllers/comments_controller.rb
app/decorators/comment_decorator.rb
app/helpers/comments_helper.rb
app/models/comment.rb
app/queries/comments/tree.rb
app/views/articles/_comment_tree.html.erb
app/views/comments/_comment_proper.html.erb
app/views/comments/index.html.erb
app/views/podcast_episodes/show.html.erb
spec/models/comment_spec.rb
spec/queries/comments/tree_spec.rb
spec/requests/articles/articles_show_spec.rb
spec/requests/comments_spec.rb
spec/requests/podcasts/podcast_episodes_show_spec.rb
spec/requests/user/user_profile_spec.rb
spec/views/comments/_comment.html.erb_spec.rb

Implemented thresholds described in the  https://github.com/forem/forem/issues/20551#issuecomment-1911950047
Made logic on `/commentable/comments` page the same as on `/commentable/comments` page.
404 on comments direct path when the comment should be hidden
Added more specs for comments/comment/commentable pages.
Moved part of the tree logic from `CommentsHelper` to `Comments::Tree`
- Closes #20551
Comments should be displayed according to the rules described in the https://github.com/forem/forem/issues/20551#issuecomment-1911950047 on both commentable and commentable/comments pages

Changed logic for hiding and displaying low-quality marker for comments based on their score

---

app/mailers/digest_mailer.rb
spec/mailers/digest_mailer_spec.rb

> Add a Category to Digest Emails sent via Sendgrid to distinguish them from other types of emails sent via Forem.
- Closes #20594

Add Sendgrid Category to Digest Emails

---

app/controllers/concerns/api/followers_controller.rb
app/controllers/dashboards_controller.rb
app/models/follow.rb
app/models/user.rb
app/services/notifications/new_follower/send.rb
app/views/api/v1/users/me.json.jbuilder
app/views/dashboards/_actions.html.erb
app/views/dashboards/_actions_mobile.html.erb
app/views/mailers/notify_mailer/new_follower_email.html.erb
spec/requests/api/v1/users_spec.rb
spec/requests/dashboard_spec.rb

Removed users with spam and suspended roles from followers lists:
- user dashboard
- api
Adjusted followers count on the dashboard and in the api.
- Closes  #20587

Removed spammers from followers list

---

app/helpers/comments_helper.rb
app/views/articles/_comment_tree.html.erb
app/views/comments/index.html.erb
spec/requests/comments_spec.rb

Previously, child comments with score < -400 were displayed as deleted when they had no children but were child comments themselves.
Spam comments (with score <-400 ) should be displayed as deleted if they have children and be hidden w/o a deleted message if they don't have children.
This comment fixes the bug.
- Related Issue #20551

Hide spam comments if they are child comments

---

app/workers/comments/calculate_score_worker.rb
spec/workers/comments/calculate_score_worker_spec.rb

`updated_at` is not updated when recalculating score (e.g. after assigning spam role), so the partial cache is not invalidated, and outdated data is displayed to the user. This pr fixed the issue. Also rubocop fixes in the same file.
- Related Issue #[#20472](https://github.com/forem/forem/issues/20472)

Update comment updated_at when changing score

---

app/controllers/application_controller.rb
app/models/async_info.rb
config/field_test.yml

First step for closing the loop in offering users the ability to customize the style of their feed (whether rich, basic, compact).
First step is adding an a/b test so we can make an informed decision on the best new "default".
Let's see if either approach encourages more repeat use of the platform. There is more to the decision than just the results of this experiment but it's an important thing to know.
- Related Issue https://github.com/forem/forem/issues/20665
- Closes #

Add a/b test for feed style on new users

---

app/assets/stylesheets/billboards.scss

Quick tweak to fix a potential edge case where an admin creates content which overflows the screen and the billboard is not closable.
This shouldn't happen in general, but could — so this just adds a max height and makes it scrollable if the max is reached.

[Tiny tweak] Add max style for fixed billboard to ensure it can't overflow the screen

---

app/models/article.rb
spec/models/article_spec.rb

This PR addresses issue #20650 by removing the requirement for authors to have comments for their posts to be indexed by search engines. Additionally, it includes test coverage for this previously uncovered check.
- Related Issue #20650
- Closes #20650
I'm not sure how this could be tested 🤔.

Rremove de-indexing From Accounts With No Comments

---

app/controllers/admin/badge_achievements_controller.rb
app/services/badges/award.rb
app/services/badges/award_first_post.rb
app/services/notifications/new_badge_achievement/send.rb
app/views/admin/badge_achievements/award.html.erb
app/views/mailers/notify_mailer/new_badge_email.html.erb
app/views/mailers/notify_mailer/new_badge_email.text.erb
app/views/notifications/_badgeachievement.html.erb
app/workers/badge_achievements/badge_award_worker.rb
db/migrate/20240227181740_add_include_badge_description_in_email.rb
db/schema.rb
spec/requests/admin/badge_achievements_spec.rb
spec/services/badges/award_spec.rb
spec/workers/badge_achievements/badge_award_worker_spec.rb

This allows admins to unselect whether the "description" is included in the badge awarding process. By default it will continue to be included.
- Closes https://github.com/forem/forem/issues/20683

Allow admin to declare whether to include the badge description in message

---

app/javascript/actionsPanel/services/reactions.js

Fixes issue in #20674 where `fetch` was called with an object body, and swapped it out for `@utilities/http` which automatically converts to JSON.

[Hotfix]] Use request utility on actionsPanel

---

app/controllers/admin/tags/moderators_controller.rb
app/views/admin/tags/edit.html.erb
app/views/admin/users/show/overview/_tag_moderation.html.erb
config/locales/controllers/admin/en.yml
config/locales/controllers/admin/fr.yml
config/locales/views/admin/en.yml
config/locales/views/admin/fr.yml
spec/requests/admin/tags/moderators_spec.rb

Fixes adding tag moderators by removing user autocomplete. The problem is described in #20405 
This pr includes the quick fix:
- remove autocompete for username field
- add tag moderators by submitting username
I have also updated the notice on user's page in member manager on how to add tag mods.
- Related Issue #20405 
Try creating a tag mod by submitting an existing username on the tag page in admin ( content manager => tags => tag page) => the tag mod should be added.
Try creating a tag mod by submitting a non-existant username => a corresponding `flash[:error]` should be displayed
Autocomplete on other admin pages (e.g. in the content manager => articles, change article author or add coauthors) should work as it was working before (no changes there)/

Add tag moderators by username w/o autocomplete

---

app/controllers/billboard_events_controller.rb
app/services/articles/suggest.rb

These are a couple of tweaks to create small efficiency adjustments for our most time-consuming queries.
One is a tweak on throttling of tabulating billboard events, and the other is a restriction on how far back we look for article suggestions.
Since suggestions are ultimately being ordered by "hotness score", this should maintain current approx behavior.
These are two of the most time-consuming queries, so this is some low-hanging fruit.

Small efficiency adjustments

---

app/services/moderator/manage_activity_and_roles.rb
app/services/users/resolve_spam_reports.rb
app/workers/users/resolve_spam_reports_worker.rb
spec/services/moderator/manage_activity_and_roles_spec.rb
spec/services/users/resolve_spam_reports_spec.rb
spec/workers/users/resolve_spam_reports_worker_spec.rb

When a user is marked as spam, automatically mark any user reports with the spam category on their account or any of their content as resolved.
- Closes #20511
Add spam role to the user that has spam reports (`FeedbackMessage` with "spam" `category`) for their profile, articles or comments  => spam reports should be resolved (status changed to "Resolved") after the role is assigned. The reports will be resolved asynchronously, so there may be a slight delay.

Automatically resolve spam reports when the offending user is marked as spam

---

.github/workflows/cleanup-cache.yml

I've noticed that my CI optimization tend to diminish due to cache not being retrieved. The cause of this might because our cache eviction script is flawed. This takes the newest change from https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
n/a

[CI] Update cleanup-cache action

---

app/controllers/comments_controller.rb
app/helpers/comments_helper.rb
app/views/comments/_comment.html.erb
app/views/comments/_comment_proper.html.erb
app/views/comments/_comment_quality_marker.html.erb
app/views/comments/index.html.erb
config/locales/views/comments/en.yml
config/locales/views/comments/fr.yml
spec/requests/comments_spec.rb
spec/requests/comments_with_cache_spec.rb
spec/views/comments/_comment.html.erb_spec.rb

Comments with score below hiding threshold (< -400)  when accessed by direct url:
**Before the pr:**
- 404 when they have no children
- displayed as deleted when they have children (and the user is signed in):
**After the pr:**
- same behaviour for non-admins
- for admins: display comment text, low-quality marker, notice that they're displayed only for admins.
- Closes  #20553

Admin access to spam comments by url

---

app/controllers/users_controller.rb
app/javascript/__tests__/__snapshots__/asyncUserStatusCheck.test.js.snap
app/javascript/packs/asyncUserStatusCheck.js
app/models/user.rb
app/views/admin/feedback_messages/_abuse_reports.html.erb
app/views/admin/users/show/profile/_status.html.erb

- This prioritizes showing `spam` as a user status, over `suspended`, when both are present on a user's profile.
- Additionally this adds `spam` to the async user profile checker shown on a user's profile. This should technically be redundant given we show `spam` as part of the user's name but I think we have some caching issues + showing the `suspended` flag adds confusion. We can remove in the future once we've solved those issues.
- Closes #20795

Prioritize spam label over suspended, add to async profile check

---

app/controllers/users_controller.rb
app/javascript/packs/profileDropdown.js
app/javascript/profileDropdown/spamButton.js
app/policies/user_policy.rb
app/views/users/show.html.erb
config/locales/views/users/en.yml
config/locales/views/users/fr.yml
config/routes.rb

> Add a new option to the user profile dropdown to toggle the user's spam status (i.e. "Mark user as spam"), which only shows and operates for admin users.
- Closes #20796

Add mark as spam button on user profile for admins

---

config/initializers/sidekiq.rb

On running `/bin/startup`, I noticed the warning:
"WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`"
pointing to forem/config/initializers/sidekiq.rb:29.
This commit resolves that warning by removing `.options`
Run the `bin/startup` script locally from `forem/forem:main`. Notice the warning described above. 
Run the `bin/startup` script locally from `medwards1771/forem:resolve-sidekiq-warning-on-startup` (or just make the change on your local copy of forem). Notice the warning disappear.  

Resolve sidekiq warning

---

spec/requests/admin/tags/moderators_spec.rb
spec/services/tag_moderators/add_spec.rb

I have started working on adding tag moderators from users page, and wanted to reuse `TagModerators::Add`, so added several tests for it.
I haven't finished the solution for "adding tag mods", but it wouldn't harm to add tests first.
- Related Issue #20405

Specs for adding tag moderators

---

.vscode/extensions.json
.vscode/launch.json

This PR 
- updates the extension used in the "Attach to Edge" debug task from `edge` to `vscode-edge-devtools.debug`
- places the `name` attribute for each task at top for consistency
`edge`, aka `msjsdiag.debugger-for-edge`, was added to the list of recommended vscode extensions in [PR #4346](https://github.com/forem/forem/pull/4346/files) so developers could use it to run the "Attach to Edge" debug task. since then, [PR #17870](https://github.com/forem/forem/pull/17870/files) has deleted `msjsdiag.debugger-for-edge` from the recommendation list, but the "Attach to Edge" debug task remains, and throws an error since [edge](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge) no longer exists. 
VSCode users: install `vscode-edge-devtools.debug`, then run the …

Update edge VSCode extension

---

.env.test
.github/workflows/ci.yml
.github/workflows/uffizzi-build.yml
spec/system/comments/user_edits_a_comment_spec.rb

This symlink has tripped me so many times. Unlike its counterpart `.env_sample`, this is in a proper format. It will be unintentionally treated as valid `.env.text` file and will overwrite a base `.env`. For example, if you would prefer a certain value to be nil, this file will overwrite it.
n/a

Remove .env.test symlink

---

.vscode/extensions.json

This PR updates the MDX VSCode extension from `silvenon.mdx` to `unifiedjs.vscode-mdx`. `silvenon.mdx` has been deprecated in favor of `unifiedjs.vscode-mdx`, see https://marketplace.visualstudio.com/items?itemName=silvenon.mdx. 
VSCode users:
- open Forem in VSCode
- be prompted to install MDX extension
- notice the old prompt to install a deprecated version of the MDX extension is now gone ! 🎉 

Update the mdx vscode extension

---

db/migrate/20240408101038_add_timestamps_to_users_roles_table.rb
db/schema.rb

This adds timestamps to the `users_roles` table, allowing easy queries to find out when a user was given a specific role. There was no established convention for doing this in the codebase, so I've chosen to just use the timestamp when the migration occurs to backfill the values.
There were a few other approaches [listed here](https://stackoverflow.com/questions/46520907/add-timestamps-to-existing-table-in-db-rails-5), but this seemed the most straightforward approach.

Add timestamp to users roles table

---

app/lib/seeder.rb
app/models/concerns/algolia_searchable.rb
app/models/concerns/algolia_searchable/searchable_user.rb
app/models/user.rb
app/workers/algolia_search/search_index_worker.rb
config/sidekiq.yml
spec/models/user_spec.rb
spec/rails_helper.rb
spec/support/algolia_mock_requester.rb
spec/workers/algolia_search/search_index_worker_spec.rb

Add options to turn on Algolia for user
https://github.com/forem/forem/issues/20833
n/a

 Add AlgoliaSearchable for User

---

app/controllers/api/v1/pages_controller.rb
spec/requests/api/v1/pages_spec.rb

This fixes support for specifying the `social_image` for Pages via the API. The [docs](https://developers.forem.com/api/v1#tag/pages/paths/~1pages~1%7Bid%7D/put) don't specify a format for the URL, I've used the same format as the [GET route](https://developers.forem.com/api/v1#tag/pages/paths/~1pages~1%7Bid%7D/get) `... social_image: { url: "https://blah.png" }`. 

Fix support for adding social image to the Pages API

---

.vscode/settings.json
docker-compose.yml

The esbuild compile output folder `app/assets/builds` is so small and faster to compile, there's no need to mount the volume and have it confusingly remove the `.keep` within in.,
n/a

[Devcontainer] Remove unnecessary volume mount

---

app/services/moderator/manage_activity_and_roles.rb
app/services/users/remove_role.rb
app/views/users/show.html.erb
spec/services/moderator/manage_activity_and_roles_spec.rb
spec/services/users/remove_role_spec.rb

- changed user profile header cache_key
- touch user profile on assigning role/removing role to invalidate that cache fragment
Maybe I would use `users_roles.cache_key_with_version` but we have habtm there (so, the table doesn't have timestamps), so that's not possible.
Touching user profile seemed light and straightforward enough.
Closes #20846
- enable caching on dev
- assing user a spam role
- their profile header should now include "spam" label
- remove spam role
- their profile header shouldn't include "spam" label
We currently have 2 labels: sync and async 🌚

Bust profile header cache on assigning/removing spam role

---

app/controllers/admin/tags/moderators_controller.rb
app/controllers/admin/users_controller.rb
app/services/tag_moderators/add.rb
app/services/users/remove_role.rb
app/views/admin/users/show/overview/_tag_moderation.html.erb
config/locales/controllers/admin/en.yml
config/locales/controllers/admin/fr.yml
config/locales/views/admin/en.yml
config/locales/views/admin/fr.yml
config/routes/admin.rb
spec/requests/admin/tags/moderators_spec.rb
spec/requests/admin/users_manage_spec.rb
spec/services/tag_moderators/add_spec.rb
spec/services/users/remove_role_spec.rb

Implemented adding tag moderators from member manager page for admins.
This feature was "stubbed" for a long time and the tag mods could be only added from the tag page which is not always convenient.
Add tags one at a time.
- Closes #20405
Visit member manager page for admins, go to users page.
You can now add tag moderator roles in the "tags" block and remove them.

Add tag moderators on users page (for admins)

---

app/controllers/sidebars_controller.rb
spec/requests/sidebars_spec.rb

This is an adjustment to add a selection of recently viewed posts to active discussions if they meet criteria of having an ongoing discussion.

Tweak active discussions to include recently viewed posts

---

app/controllers/sidebars_controller.rb
config/field_test.yml

Adds quick field test to modify number of Active Discussion threads to show on home page.

Test number of active discussion threads to show

---

app/liquid_tags/tweet_tag.rb
app/liquid_tags/unified_embed/tag.rb
spec/liquid_tags/unified_embed/registry_spec.rb

Allow x.com to automatically trigger tweet embed.

Add x.com to embed registry

---

app/javascript/packs/articlePage.jsx
app/javascript/utilities/billboardInteractivity.jsx
app/services/markdown_processor/parser.rb
spec/models/comment_spec.rb
spec/services/content_renderer_spec.rb
spec/services/markdown_processor/parser_spec.rb

This modifies behavior so outbound links consistently target new tab. This is already the behavior in some places, but this makes it consistent across UGC.

Add target blank to outbound links

---

app/controllers/admin/articles_controller.rb
app/models/article.rb
app/views/admin/articles/_article_item.html.erb
config/locales/views/moderations/en.yml
config/locales/views/moderations/fr.yml
db/migrate/20240710144409_add_max_score_to_articles.rb
db/schema.rb
spec/models/article_spec.rb

Under some circumstances an admin may need to set a score cap on a post manually, such as an announcement which does not need to rise even with interactivity. This is a feature which won't affect anything unless used.

Allow admin to optionally set score cap on post

---

app/decorators/user_decorator.rb
app/models/user.rb
spec/decorators/user_decorator_spec.rb

This adds cached user role names to the body class, to go along with some things like the trusted class, to give pages and elsewhere something to grab onto to refer to any role.

Add user role names to body class

---

app/assets/javascripts/initializers/initializeBillboardVisibility.js
app/assets/stylesheets/billboards.scss
app/assets/stylesheets/widgets.scss
app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/packs/billboardAfterRenderActions.js
config/routes.rb
spec/requests/billboard_events_spec.rb

This modifies the endpoint we use with billboard events in case the current one is getting caught up by blockers erroneously.

Add alias for billboard events

---

app/controllers/billboard_events_controller.rb

Make throttle time something that can be set from env var and don't re-tabulate half the time for billboards with lots of data already

Adjust billboard event retabulation throttle

---

app/workers/articles/update_page_views_worker.rb
spec/workers/articles/update_page_views_worker_spec.rb

Adds logic to only call this when needed, creating less of a build up of scheduled jobs.

Update organic page views tabulator job logic

---

app/controllers/incoming_webhooks/stripe_events_controller.rb
app/views/comments/_comment_header.html.erb

Subscriber icon was showing up based on author role instead of commenter role on comments.
Also added touch in stripe events for cache clearing.

Fix subscriber icon

---

app/lib/redcarpet/render/html_rouge.rb
app/services/content_renderer.rb

Put this behind feature flag because it's not 100% reliable right now

Put sync detail detection mediastore behind feature flag

---

app/controllers/incoming_webhooks/stripe_events_controller.rb
spec/requests/incoming_webhooks/stripe/stripe_events_spec.rb

Allows multiple billboard events to count for conversion, to give credit if multiple billboards were involved in a conversion funnel.

Allow multiple recent billboard clicks to count for conversion

---

app/services/notifications/notifiable_action/send.rb

The current query is really inefficient. This fixes that. We may want to make the `def followers` method more efficient too, but this inline should help where matters most.

Make notification send query more efficient

---

app/assets/javascripts/initializers/initializeBillboardVisibility.js
app/controllers/stripe_subscriptions_controller.rb
app/models/billboard.rb
app/views/shared/_billboard.html.erb
app/views/users/_account.html.erb
spec/requests/stripe_subscriptions_spec.rb

Adds full proper flow for subscription cancellation. Also include tweak to billboard display logic.

Add proper self-serve subscription cancel flow

---

config/environments/production.rb
config/initializers/redis_monkeypatch.rb

After unsuccessful attempts to define a custom MultiStoreCache, we are going to patch `ActiveSupport::Cache::RedisCacheStore` to write to secondary store

Use monkeypatch to write to secondary redis

---

app/controllers/stories_controller.rb

Non-signed-in comment tree is the source of a lot of latency. This reduces the total we show for non-signed-in contexts.

Adjust signed-out comments-to-show count

---

app/controllers/concerns/caching_headers.rb

For optimization, allow this number to be set via variable.
The default is still 24 hours, but an admin could taper up or down.

Allow cache max age to be set via ENV var

---

app/models/article.rb
app/models/billboard.rb
app/models/comment.rb
app/views/articles/show.html.erb
app/views/shared/_billboard.html.erb
spec/models/article_spec.rb
spec/models/billboard_spec.rb
spec/models/comment_spec.rb

This is a specific, sort of hacky way to migrate some traffic to a new subdomain. It uses code repetition and only adjusts for this one-off change needed. It also does not yet work on pages. It is there for the main traffic-getting areas.
However, I think this could be modified to be a more flexible/context-specific final method. So this method could be used as a future interface for some changes.

Make processed_html_final step to allow final html mods

---

app/services/billboard_event_rollup.rb

This adds a step to step through unique billboard Ids before running the roll up logic to reduce the likelihood of timeouts on individual queries.

Adjust roll up logic to step through billboards for the day

---

app/assets/stylesheets/widgets.scss
app/services/billboard_event_rollup.rb
spec/services/billboard_event_rollup_spec.rb

This removes the outer transaction so that if other transactions succeed, they don't all have to succeed.
This is idempotent so it's okay if it only partially finishes.

Remove outer transaction from billboard rollup

---

app/models/articles/feeds.rb
spec/services/articles/feeds_spec.rb

Currently when a user has any page views (i.e. not new user) but they haven't recorded one in a long time, we look back in the whole timeframe since their last page view, which is not ideal behavior.
This caps the lookback at 18 days.

Max 18 day look back for inactive returning user

---

app/controllers/concerns/api/articles_controller.rb
spec/requests/api/v1/articles_spec.rb

Extends articles api to include subforem

Add subforem_id to articles api

---

app/controllers/admin/feedback_messages_controller.rb
spec/requests/admin/feedback_messages_spec.rb

Adjust to not show old reactions or reactions on reactables "already fully moderated"

Don't show reactions in admin older than two weeks or on posts already fully moderated

---

app/controllers/stories/tagged_articles_controller.rb
app/views/stories/tagged_articles/index.html.erb

This fragment cache has a low hit rate, this removes it. To experimentally observe performance.

Remove unnecessary fragment cache in tags index

---

app/assets/stylesheets/config/_colors.css
app/views/async_info/navigation_links.html.erb
app/views/layouts/_top_bar.html.erb

Move things around, where the search bar goes in the nav links area, and for non-signed in it isn't in the top bar anymore _for mobile_, where it has always been sort of just crammed in.

Add search to nav links sidebar

---

app/assets/stylesheets/components/stories.scss
app/controllers/moderations_controller.rb
app/controllers/stories_controller.rb
app/javascript/articles/components/ContentTitle.jsx
app/javascript/articles/components/Meta.jsx
spec/requests/moderations_spec.rb
spec/requests/stories_index_spec.rb

[Boost] posts do not need to be seen in these contexts or moderated like they are now.
Soon we'll have some visual adjustments so the [Boost] language doesn't show up like now.

Remove [Boost] from mod center and signed out context

---

app/assets/javascripts/initializers/initializeBodyData.js
app/views/layouts/_user_config.html.erb

Currently when dark mode is detected when signining in/changing settings etc it only shows up on refresh due to deferring to the local stored one. This changes so it will immediately change when detected, allowing local one to be the "eager" version.

Immediately set dark mode when detected

---

app/views/sidebars/_homepage_content.html.erb

Quick fix to remove plain "boost" posts from sidebar, could be improved later for DRY.

Skip boost in sidebar posts

---

app/models/settings/user_experience.rb
app/views/layouts/_top_bar.html.erb
spec/requests/stories_index_spec.rb

Allow admins to set "accent background color" — currently only used for navbar.

Add optional accent color for nav bar

---

app/assets/stylesheets/billboards.scss
app/javascript/actionsPanel/initializeActionsPanelToggle.js
app/javascript/packs/billboard.js
app/views/shared/_billboard.html.erb
spec/requests/billboards_spec.rb

Adds button for "Read More" for long billboards in below-post-body so they don't take up too much room.

Add "Read More" button for extra long billboards

---

app/controllers/reactions_controller.rb
spec/requests/reactions_spec.rb

Since reactions are fetched async in this context and because it's a consistent json response, the cache window can be extended. If we need to bulk expire the cache we could easily do so with a fingerprint in the url later.

Extend cache window for reactions endpoint

---

app/models/article.rb
app/services/articles/feeds/custom.rb
db/migrate/20250306204509_add_shuffle_weight_to_feed_configs.rb
db/schema.rb
spec/requests/stories/feeds_spec.rb
spec/services/articles/feeds/custom_spec.rb

Shuffle weight takes the final result and moves elements around slightly to make two consecutive loads more likely to be slightly different.
This is different than the randomness weight which operates on the whole original query.
Since this starts at `0.0` it won't be live unless a config variant is created with another number.

Add final shuffling weight

---

app/models/billboard.rb
spec/models/billboard_spec.rb

When a billboard changes from live to non-live we should tabulate its events, currently we miss some of the last events due to not calculating as a last step essentially.

Tabulate billboard counts when taking down

---

app/helpers/application_helper.rb
app/helpers/rate_limit_checker_helper.rb
app/liquid_tags/unified_embed/tag.rb
app/models/listing.rb
app/views/dashboards/_actions.html.erb
app/views/dashboards/_analytics.html.erb
config/routes.rb
spec/helpers/application_helper_spec.rb
spec/liquid_tags/unified_embed/tag_spec.rb
spec/models/listing_spec.rb
spec/rails_helper.rb

This PR continues the incremental removal of the deprecated Listings feature by focusing on the now-obsolete `Listing.feature_enabled?` class method.
The method itself is removed from the `Listing` model. All calls to this method across various helpers, views, liquid tags, and route constraints have also been removed, along with associated conditional logic that is no longer relevant.
Additionally, related test code was cleaned up:
- The test for `Listing.feature_enabled?` in `listing_spec.rb` was removed.
- A global spec helper stubbing `Listing.feature_enabled?` in `rails_helper.rb` was removed.
- Specs for modified helpers (`application_helper_spec.rb`) were updated.
- Specs for liquid tags (`unified_embed/tag_spec.rb`) were updated/removed where they tested logic dependent on the …

refactor: Remove Listing.feature_enabled? method and usage

---

app/controllers/application_controller.rb
spec/requests/sessions_spec.rb

After signing out and immediately signing back in, users were redirected to the "/signout_confirm" path, resulting in the sign-out confirmation modal appearing again. The problem stemmed from the stored location persisting as "/signout_confirm", causing an unintended user experience.
To resolve this, the `after_sign_in_path_for` method in `ApplicationController` has been updated. Now, if the stored location is "/signout_confirm", the user is redirected to the root path with the `signin=true` parameter, ensuring an expected sign-in process.
- Closes #21753
1. Sign out of the application.
2. Immediately sign back in.
3. Confirm that you are redirected to the homepage without encountering the sign-out confirmation modal again.
This modification was ran using the `dip` gem and an according …

Prevent Sign-out Confirmation Modal From Appearing After Re-login

---

app/models/ahoy/visit.rb
app/workers/visits/remove_old_visits_worker.rb
spec/models/ahoy/visit_spec.rb

Add the ability to delete old ahoy visits (not in use anywhere, but can be called manually)

Add function for deleting old visit analytics

---

app/workers/emails/drip_email_worker.rb
spec/workers/emails/drip_email_worker_spec.rb

Adds the ability to have alternate onboarding emails (no UI yet, just backend)

Add logic for alternative subforem drip emails

---

app/controllers/magic_links_controller.rb
app/views/layouts/_footer.html.erb
app/views/magic_links/new.html.erb
spec/requests/magic_links_spec.rb

If a Forem is in invite-only mode it should not allow registration in this route.

Add invitation-only guard to magic links reg

---

app/models/comment.rb
app/services/articles/destroyer.rb
spec/models/comment_spec.rb

The article destroy action throws a 503 HTTP status code which
that the server is too busy to actually handle the DELETE request
at the moment.
While digging, I noticed that the article's notifications are
removed straight away and therefore this may be the cause of the
server business.
Also, the while the article is being destroyed, its mentions will
also be destroyed due to the
```
has_many :mentions, as: :mentionable,
inverse_of: :mentionable, dependent: :destroy
```
association but this association uses the `dependent: :destroy`
option which means that callbacks will be triggered and therefore
may take some time as well.
- Related Issue #21681 
N/A
N/A

Fix article destroy action

---

app/assets/stylesheets/widgets.scss
app/views/shared/_billboard.html.erb

Mobile web targeting is intended to target _phones_, but user agents can be imprecise. This helps ensure that only smaller screens see these billboards.

Ensure mobile web doesn't show up on larger screens

---

app/models/billboard.rb
app/workers/emails/send_user_digest_worker.rb
db/migrate/20250513181503_add_prefer_paired_with_to_billboards.rb
db/migrate/20250513181655_add_prefer_paired_with_index_to_billboards.rb
db/schema.rb
spec/models/billboard_spec.rb
spec/requests/api/v1/billboards_spec.rb
spec/workers/emails/send_user_digest_worker_spec.rb

Add the ability to "prefer" one billboard to be paired with another, where we fallback if it's not there.

[WIP] Add prefer_paired_with_billboard_id to billboards

---

app/controllers/application_controller.rb
spec/requests/stories_index_spec.rb

Redirect unregistered subforems to root. So if `something-new.forem.com` is visited, we just go to `forem.com`. This could later be adjusted to a different landing page but for now this works.

Redirect unregistered subforems to root

---

config/schedule.yml

This PR addresses a recurring `NameError` for `Listings::ExpireOldListingsWorker` that appears in Honeybadger. The error occurs because a scheduled job in `config/schedule.yml` attempts to enqueue this worker, but the worker class no longer exists as the Listings feature has been removed.
- Closes #21875
- Related to #21624 
**Monitor Honeybadger post-deployment:** After this PR is deployed, observe Honeybadger (specifically after 00:30 UTC, the job's scheduled time) to ensure that new instances of `NameError in Listings::ExpireOldListingsWorker # perform` no longer appear.
*   Note: Existing jobs for this worker that are already in Sidekiq's retry queue may continue to fire and log errors until they exhaust their retries. This PR prevents *new* jobs from being scheduled.
_If your PR …

Fix: Remove schedule for non-existent ExpireOldListingsWorker

---

app/javascript/article-form/components/Options.jsx

…section
#issue 21706
- Added dynamic display of user's current local time, date, and timezone using moment.js
- Helps clarify the scheduling logic by explicitly showing the time context
- Ensures better UX and avoids confusion around what time the post will be scheduled for
This Red marked Area Will be the updated version which was not present before.

feat: display current time and timezone in Post Schedule Publication  (#issue : 21706 )

---

app/liquid_tags/unified_embed/registry.rb
app/liquid_tags/unified_embed/tag.rb
app/liquid_tags/youtube_tag.rb
spec/liquid_tags/youtube_tag_spec.rb

Fixes an issue where YouTube embeds failed for short youtu.be URLs containing si= or t= query parameters. si= and potentially t= params are introduced from default 'share' button on YouTube.
Other embed tag tests in the RSpec suite continue to pass. Manual spot-checks confirmed that GitHub, Spotify, CodePen, Vimeo & Bandcamp embeds still work as expected.
- Closes #22054
_We encourage you to keep the code coverage percentage at 80% and …

Fix: Embed youtu.be URLs with si and t parameters

---

app/controllers/concerns/api/articles_controller.rb
app/models/article.rb
spec/requests/api/v1/articles_spec.rb

Allow api to set video_source_url if youtube

Allow video_source_url in api if youtube

---

config/locales/views/main/en.yml
config/locales/views/main/fr.yml

Update nav_name translation strings in both English and French locale files to properly capitalize 'Terms of Use'.
Updates the default to Terms of **Use** and not Terms of **use**
- Closes https://github.com/forem/forem/issues/22150
This PR doesn't update any _existing_ navigation links with the old capitalization, which is fine.

Fix capitalization: Terms of use -> Terms of Use

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/assets/stylesheets/base/typography.scss
app/assets/stylesheets/components/comments.scss
app/assets/stylesheets/components/stories.scss
app/javascript/articles/components/ContentTitle.jsx
app/liquid_tags/unified_embed/tag.rb
app/models/article.rb
app/views/articles/_single_story.html.erb
app/views/articles/_tag_identifier.html.erb
app/views/articles/show.html.erb
app/views/liquids/_open_graph.html.erb
app/views/stories/feeds/show.json.jbuilder
spec/liquid_tags/unified_embed/tag_spec.rb
spec/models/article_spec.rb

This automatically embeds links which are included in quickie titles. It does not spit out full embeds (though could in future)

Automatically render links included in quickie titles

---

app/controllers/admin/community_bots_controller.rb
app/models/admin_menu.rb
app/models/user.rb
app/policies/community_bot_policy.rb
app/services/community_bots/create_bot.rb
app/services/community_bots/delete_bot.rb
app/services/subforem_moderators/add.rb
app/services/subforem_moderators/add_trusted_role.rb
app/services/subforem_moderators/remove.rb
app/views/admin/community_bots/index.html.erb
app/views/admin/community_bots/new.html.erb
app/views/admin/community_bots/show.html.erb
app/views/admin/subforems/show.html.erb
app/views/subforems/edit.html.erb
config/routes/admin.rb
db/migrate/20250821221829_add_type_of_to_users.rb
db/schema.rb
spec/models/user_spec.rb
spec/policies/community_bot_policy_spec.rb
spec/requests/admin/community_bots_spec.rb
spec/services/community_bots/create_bot_spec.rb
spec/services/community_bots/delete_bot_spec.rb

This establishes the capacity to transparently create a bot account. If bot-generated content is going to be more of a thing (hard to fight), we should maximize the transparency of this. This will also maximize user capacity to not see bot content in feeds. It will be easier to enforce any possible gray area if bot labeling is available.
This primarily introduces "community bots" which can be created by admins — but establishes a notion for member-created bots as well.

Establish explicit transparant bot concept

---

spec/models/timeframe_spec.rb

- Test valid timeframe returns ISO8601 formatted string
- Test latest timeframe returns nil (not a datetime object)
- Test invalid timeframe returns nil
- Follows existing test patterns with Timecop.freeze

Add test coverage for Timeframe.datetime_iso8601 method

---

app/services/ai/content_moderation_labeler.rb
spec/services/ai/content_moderation_labeler_spec.rb

- Implement 2 retry attempts before falling back to no_moderation_label
- Add comprehensive logging for retry attempts and failures
- Include tests for all retry scenarios and logging behavior
- Maintain existing fallback behavior after exhausting retries

Add retry logic to ContentModerationLabeler

---

app/models/reaction.rb
app/services/spam/reaction_ring_detector.rb
app/workers/spam/reaction_ring_detection_worker.rb
spec/models/reaction_ring_detection_spec.rb
spec/services/spam/reaction_ring_detector_spec.rb
spec/workers/spam/reaction_ring_detection_worker_spec.rb

This PR implements a sophisticated reaction ring detection system to identify and prevent coordinated spam behavior where multiple accounts consistently react to the same users' articles without reacting to other users.
- **** - Main service that analyzes user behavior patterns
- **** - Background worker for asynchronous processing  
- **Reaction model hook** - Triggers detection when public reactions are created
- **Comprehensive test suite** - Full coverage of all scenarios
**Threshold Requirements:**
- User must have ≥50 article reactions in the past month
- Minimum 3 users in a potential ring
- ≥80% of reactions must be to the same authors
- ≥2 shared authors between ring members
**False Positive Prevention:**
- ✅ **Self-reaction filtering** - Excludes users reacting to their own …

feat: Add reaction ring detection system

---

app/models/badge_achievement.rb
app/services/badges/award_top_seven.rb
spec/models/badge_achievement_spec.rb
spec/services/badges/award_top_seven_spec.rb

- Double badge recipient's reputation modifier (max 4.0)
- Multiply positive reactors' reputation modifiers by 1.5 (max 4.0)
- Only consider reactions from the last week
- Add comprehensive test coverage for new functionality
- Include proper logging for reputation modifier changes
This enhancement rewards both the badge recipient and users who positively engaged with their content, creating a positive feedback loop for quality content creators.

feat: Add reputation modifier changes to Top 7 badge awarding

---

spec/decorators/user_decorator_spec.rb
spec/factories/subforems.rb
spec/liquid_tags/unified_embed/registry_spec.rb
spec/models/article_spec.rb
spec/models/feed_config_spec.rb
spec/queries/billboards/filtered_ads_query_spec.rb
spec/requests/admin/subforems_spec.rb
spec/requests/admin/tags_spec.rb
spec/requests/api/v0/subforems_spec.rb
spec/requests/api/v1/subforems_spec.rb
spec/requests/registrations_spec.rb
spec/requests/stories_show_spec.rb
spec/view_objects/cloud_cover_url_spec.rb

This PR refactors the subforem testing setup to eliminate the hacky manual random domain generation pattern.
- Updated subforem factory to use sequence for unique domains
- Removed manual domain: "#{rand(10000)}.com" pattern from 15 test files
- All tests passing after refactoring
- Cleaner, more maintainable test code
- Automatic unique domain generation
- Consistent pattern across all subforem tests

Refactor: Remove manual random domain generation from subforem tests

---

app/services/users/cancel_stripe_subscriptions.rb
app/services/users/delete.rb
spec/services/users/cancel_stripe_subscriptions_spec.rb

This PR adds functionality to ensure that all Stripe subscriptions are automatically cancelled when a user account is deleted.
- Safely cancels all active Stripe subscriptions for a user
- Comprehensive error handling to prevent account deletion failures
- Logging and stats tracking for monitoring
- Handles various Stripe API errors gracefully
- Integrated into `Users::Delete` service
- Positioned before user record destruction
- Maintains existing deletion flow without disruption
- **Error Isolation**: All Stripe errors are caught and logged without propagating
- **Graceful Degradation**: Account deletion continues even if Stripe API is unavailable
- **Comprehensive Logging**: All errors logged for debugging and monitoring
- **Stats Tracking**: Failed cancellations tracked for …

Ensure Stripe subscription cancellation to account deletion

---

app/views/layouts/application.html.erb

The home page was using  to load critical resources (stories feed, billboards, sidebar), but  loads resources with low priority only when the browser is idle. Since these resources are needed immediately when the home page loads, this was causing suboptimal performance.
- Replace  with  for all critical home page resources
- Add proper  and  attributes
- These resources are now loaded with high priority immediately when the page starts loading
-  endpoints (JSON data)
- Billboard endpoints , ,  (HTML content)
- Sidebar endpoint  (HTML content)
- Improved perceived performance on home page
- Critical resources are available immediately when JavaScript needs them
- Better user experience with faster loading times
- Verified HTML syntax is correct
- All preload attributes are properly …

Replace prefetch with preload for critical home page resources

---

app/javascript/packs/articlePage.jsx
app/views/articles/show.html.erb

- Add SKIP_BOTTOM_CONTENT='yes' config to completely skip article bottom content
- Maintains compatibility with existing async JavaScript
- Provides performance optimization for high-traffic scenarios
- When enabled, no bottom content queries or rendering occurs

Add SKIP_BOTTOM_CONTENT ApplicationConfig option

---

app/services/spam/reaction_ring_detector.rb
spec/services/spam/reaction_ring_detector_spec.rb

This PR fixes reaction ring legitimacy checks that used a nonexistent user.organization_id.\n\nChanges:\n- Use many-to-many check via users' organizations, considering shared orgs as legitimate connections.\n- Update existing specs to create explicit organization_memberships.\n- Add coverage for users in multiple orgs with overlap.\n\nWhy:\n- Users can belong to many organizations via organization_memberships; the prior equality check was invalid and could misclassify legitimate users as a ring.\n\nValidation:\n- rspec spec/services/spam/reaction_ring_detector_spec.rb: 17 examples, 0 failures\n- rspec spec/workers/spam/reaction_ring_detection_worker_spec.rb spec/models/reaction_ring_detection_spec.rb: 13 examples, 0 failures\n\nNo linter errors detected.

Spam: Fix reaction ring org membership check; rewrite specs

---

app/liquid_tags/cloud_run_tag.rb
app/views/liquids/_cloud_run.html.erb
config/locales/liquid_tags/en.yml
config/locales/liquid_tags/fr.yml
config/locales/liquid_tags/pt.yml
spec/liquid_tags/cloud_run_tag_spec.rb

This PR adds support for embedding Google Cloud Run applications as liquid tags, following the same patterns as existing embeds like Codepen, Replit, etc.
- **Automatic Detection**: URLs are automatically recognized via UnifiedEmbed
- **Keyword Support**: Explicit usage with  tag
- **Proper Validation**: Correct regex pattern for Google Cloud Run URL structure
- **Internationalization**: Error messages in English, French, and Portuguese
**Automatic Detection:**
```liquid
{% embed https://my-service-12ab34cd5e-us-central1.run.app/ %}
```
**Keyword-based:**
```liquid
{% cloudrun https://my-service-12ab34cd5e-us-central1.run.app/ %}
```
- **Regex Pattern**: 
- **URL Structure**: Supports the correct Cloud Run format: 
- **Validation**: Enforces lowercase service names and supports all Google …

Add Cloud Run embed support
