forem/forem

- app/javascript/Search/SearchFormSync.jsx
- app/javascript/Search/__tests__/SearchFormSync.test.jsx
The search bar no longer disappears when the search button on the header is clicked 2 times or more on a mobile browser.
- Closes #16998
**To reproduce the current issue:**
1. Goto [https://dev.to](https://dev.to)
2. Open mobile view from the Dev Tools of your browser or use a mobile browser, not the app.
3. Click on the search icon 2 or more times
4. The search bar should disappear.
**This PR fixes the issue. Added comments in the code for the same**
None
[Changes …
> Fix search bar disappears on mobile

- .github/workflows/uffizzi-build.yml
- .github/workflows/uffizzi-preview.yml
- config/environments/development.rb
- uffizzi/Dockerfile
- uffizzi/db_seed.sh
- uffizzi/docker-compose.uffizzi.yml
This PR is a part of https://github.com/forem/forem/issues/18556 and helps demonstrate Uffizzi integration with **Forem**. 
This will help create preview environments on all of **Forem** Pull Requests and help contributors including the maintainers iterate faster on their PRs. 
I have created a PR over https://github.com/daramayis/f-forem/pull/1#issuecomment-1328990873 to show what it looks like to have a preview environment deployed against your PR.
You can check out the preview over [here](https://app.uffizzi.com/github.com/daramayis/f-forem/pull/1) as well.
@waveywaves
> feat: create environment for every PR using Uffizzi

- app/views/admin/feedback_messages/_feedback_message.html.erb
This is a quick fix to keep the `Reports` section in `Abuse Reports` to expanded state by default.
Problem and solution mentioned in video.
https://loom.com/share/ac357f234efa45948774c7ba2aaaeb3f
https://loom.com/share/ac357f234efa45948774c7ba2aaaeb3f
No
appropriately. …
> Quick fix for abuse reports -- bootstrap

- spec/requests/api/v1/docs/podcast_episodes_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_v1.json
API V1 docs for podcast episodes endpoints with [rswag](https://github.com/rswag/rswag) 
- Closes  #18746
Run the specs
> [API V1 docs] Podcast Episodes

- config/feed-variants/20230110-variant-a.json
- config/feed-variants/20230110-variant-b.json
- config/feed-variants/20230110-variant-c.json
- config/field_test.yml
Updated with three new experiments and elevating the most recent winner
- Closes https://github.com/forem/forem/issues/18950
appropriately.
replace this line with details on why …
> Feed experiment for 01-11-2023

- spec/requests/api/v1/docs/profile_images_spec.rb
- spec/requests/api/v1/docs/users_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_v1.json
API V1 docs for profile image endpoint with [rswag](https://github.com/rswag/rswag)
- Related Issue #https://github.com/forem/forem/issues/18751
- Closes #https://github.com/forem/forem/issues/18751
Run `SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag PATTERN="spec/requests/api/v1/**/*_spec.rb"` 
None
issue template so Community Success …
> [API v1 docs] Profile Images by Username

- .github/workflows/ci-cd.yml
> Add Github CD (2nd attempt)

- app/services/badges/award_yearly_club.rb
> Expand Badges::AwardYearlyClub to include year 8

- .github/workflows/ci-cd.yml
Also deploying to our staging in CD
n/a
> Expand CD to include staging

- .github/workflows/ci-cd.yml
- cypress/support/commands.js
Add screen shot artifact with aid with debugging.
n/a
> Use upload-artifact in CI

- spec/requests/api/v1/docs/followers_spec.rb
- swagger/v1/api_v1.json
Added Documentation for /api/followers/users
- Related Issue #https://github.com/forem/forem/issues/18744
- Closes #https://github.com/forem/forem/issues/18744
- Paste the generated json file into https://editor.swagger.io/ to test. 
None
appropriately. …
> [API v1 docs] Followers

- spec/requests/notifications_spec.rb
> Fix broken notifications spec

- app/views/mailers/notify_mailer/trusted_role_email.html.erb
- app/views/mailers/notify_mailer/trusted_role_email.text.erb
This updates the "trusted" welcome email to reflect a simpler messaging we want in order to expand this functionality more. It's part of an issue we'd already do some of the work towards.
- Related to https://github.com/forem/forem/issues/18796
Here's the screenshot from my local:
> Adjust copy in 'trusted' email

- cypress/e2e/seededFlows/publishingFlows/addTagsToArticle.spec.js
I speed up addTagsToArticle a test file by ~6 seconds while also trying to address flaky spec. This is done by combining a few very similar test together, so there's no wasted resource used for tearing down and re-setting up the test state again.
n/a
> Refactor/Improve addTagsToArticle specs

- app/controllers/admin/creator_settings_controller.rb
- app/forms/creator_settings_form.rb
- spec/forms/creator_settings_form_spec.rb
Bring coverage up for CreatorSettingsForm's spec
Related Issue https://github.com/forem/forem/issues/19013
CodeCov check should be positive.
> Refactor CreatorSettingsForm & spec

- spec/rails_helper.rb
- spec/tasks/add_navigation_links_spec.rb
- spec/tasks/fastly_spec.rb
- spec/tasks/metrics_spec.rb
This setup allows SimpleCov to properly track coverage. Prior to this change, each subsequent spec would clobber the previous result instead of adding to it.
Related Issue https://github.com/forem/forem/issues/19013
I learned it from https://github.com/simplecov-ruby/simplecov/issues/369
CodeCov check should be positive.
> Change rake spec setup

- app/models/notification.rb
- app/models/user.rb
- app/models/users/notification_setting.rb
- app/queries/users/select_moderators_query.rb
- app/services/broadcasts/welcome_notification/generator.rb
- app/services/notifications/moderation/send.rb
- app/workers/notifications/create_round_robin_moderation_notifications_worker.rb
- app/workers/notifications/moderation_notification_worker.rb
- spec/queries/users/select_moderators_query_spec.rb
- spec/requests/user/user_notification_settings_spec.rb
- spec/services/notifications/moderation/send_spec.rb
- spec/workers/notifications/create_round_robin_moderation_notifications_worker_spec.rb
This is a fast follow for https://github.com/forem/forem/issues/18796. https://github.com/forem/forem/issues/18796, the focus is on tweaking the system to produce better outputs. But, in the course of refining that issue, https://github.com/forem/forem/issues/18796#issuecomment-1335348579 that the names and methods involved in this sub-system could be clearer.
- Related Issue #https://github.com/forem/forem/issues/18809
- Closes #https://github.com/forem/forem/issues/18809
I think since this is a refactor the QA instructions for this would be to make sure that the rspec tests pass, and to double chcek that the refactoring makes sense and I havent missed anything.
accessibility is impacted and tested. For more …
> Round Robin Notifications Refactor

- spec/factories/articles.rb
- spec/requests/api/v1/docs/videos_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_v1.json
Implements the missing videos API V1 docs
- Closes #18750
Execute
```
SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag PATTERN="spec/requests/api/v1/**/*_spec.rb"
```
Then check out `swagger/v1/api_v1.json` on https://editor.swagger.io
N/A
> /videos api docs

- app/javascript/utilities/podcastPlayback.js
Clears out old data stored in localstorage by bumping the key to fix an unexpected UX result of a previous PR
- Related Issue #19058
1. Open podcast locally
2. Close tab
3. Open new tab 
4. Check to see if the behavior is what's expected (podcast bar to appear)
None
> Bump localstorage key for podcast player

- spec/requests/api/v1/docs/followed_tags_spec.rb
- spec/requests/api/v1/docs/tags_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_v1.json
Implements the missing tags API V1 docs
- Closes #18748
Execute
```
SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag PATTERN="spec/requests/api/v1/**/*_spec.rb"
```
Then check out `swagger/v1/api_v1.json` on https://editor.swagger.io
N/A
> /tags api docs

- package.json
To account for sudden Heroku yarn version changes.
n/a
> Lock yarn version

- spec/requests/follows_create_spec.rb
- spec/requests/follows_show_spec.rb
FollowsController has a "flaky coverage" issue where a portion of the file is occasionally undercovered.
see https://app.codecov.io/gh/forem/forem/commit/67b4ae71e06601a5a267f94c67c6300ffffe748a
n/a
> Expands Follows request specs

- .github/workflows/ci-cd.yml
- cypress/e2e/seededFlows/loggedOutFlows/homeFeed.spec.js
> [CI] Capture Cypress logs on failure

- config/locales/views/reactions/en.yml
- config/locales/views/reactions/fr.yml
- config/reactions.yml
- spec/models/reaction_category_spec.rb
- swagger/v1/api_v1.json
We [recently noticed](https://github.com/forem/forem/issues/19008#issuecomment-1428819397) that the emoji names weren't consistently using underscores. `exploding-head` becomes `exploding_head`.
- Related Issue #19008
appropriately. …
> Reaction emoji with consistent underscores

- app/controllers/async_info_controller.rb
More succinct cache_key that will also self expire.
https://github.com/forem/forem/issues/19102
n/a
> Update user_data cache key 

- spec/system/articles/user_creates_an_article_spec.rb
Ensure page finish loading first before checking for the correct element
resolves https://github.com/forem/forem/issues/19097
n/a
> Fix flaky runkit spec

- .github/workflows/ci-cd.yml
Seeing red across CI, investigated and it looks like there's a new version of Node available in GitHub Actions (v18) that we aren't (yet) compatible with. Trying out an explicit node version, see if it's any better? `cc` @maestromac 
appropriately. …
> [CI] Specifying node version explicitly

- config/locales/views/admin/users/fr.yml
- config/locales/views/reactions/en.yml
- config/locales/views/reactions/fr.yml
Random bugs in locale files found during testing.
- Related Issue #14888, #18582, #18808
- Closes # …
> [i18n] Remove redundant locale

- .github/workflows/uffizzi-build.yml
- uffizzi/docker-compose.uffizzi.yml
- uffizzi/entrypoint.sh
Hi [fdocr](https://github.com/fdocr), :wave: 
This PR should fix the bug-related sign-in.
> Sign in bug fix - in the preview environment

- app/assets/javascripts/initializers/initializeArticleReactions.js
Related conversation: https://forem-team.slack.com/archives/CAA200SH5/p1677166152826759
Check this video: https://www.loom.com/share/918abc35096b499f926c86c0dfc55cb6
No
No
> Quick fix for null class check

- app/models/display_ad.rb
- spec/models/display_ad_spec.rb
- spec/requests/api/v1/docs/display_ads_spec.rb
- spec/requests/notifications_spec.rb
- swagger/v1/api_v1.json
`community-type` billboards should require an `organization_id` be set. This may eventually become a polymorphic entity called "owner", but MVP attaches to `organization` for now.
- Closes #https://github.com/forem/forem-internal-eng/issues/536
appropriately. …
> Require an owner for 'community' billboards

- .github/workflows/ci-cd.yml
See comments below for my explanations.
n/a
> Add build steps and expand CI node

- app/assets/stylesheets/widgets.scss
- app/views/shared/_display_ad.html.erb
Trying to fix the styling on billboard.
- Closes #
Go through the billboards on the home page and the article page and make sure the header items and dots menu align.
[Changes …
> Tweaks to display ad styling

- app/models/user.rb
- app/services/users/username_generator.rb
- spec/models/user_spec.rb
- spec/services/users/username_generator_spec.rb
Fixes username generation when username is not present
- Closes #19251 …
> Refactor User#temp_username

- README.md
I work here now, hi! :wave: 
Related issue: my Notion TODO list :smile: 
> (I cut most of the template out here intentionally)
> Except I use Linux...
> readme: Add klardotsh to core contributors list.

- app/models/user.rb
- app/policies/authorizer.rb
- app/services/moderator/manage_activity_and_roles.rb
- app/services/tag_moderators/add_trusted_role.rb
Due to [caching](https://github.com/forem/forem/issues/17689#issuecomment-1127541167), removing a user's `trusted` role currently does not work as expected — the `trusted?` check is cached for ~200 hours and only _some_ code paths bust this cache, so the user continues to appear `trusted?` potentially for a long time.
This PR clears the `trusted?` check in a `rolify` callback, so that the cache is cleared _any_ (and _every_) time a user's role changes, whether adding or removing, whichever controller or background or whatever way it gets triggered. 
I don't really like adding a callback if I can avoid it, but it seems like the best approach here.
- Closes #https://github.com/forem/forem/issues/17689
You'll likely want to enable local development caching:
```
❯ rails dev:cache
Development …
```
> Clear trusted cache in rolify callback

- .github/PULL_REQUEST_TEMPLATE.md
Removed some sections we've been using less often to streamline the PR review process.
> PR Template cleanup

- .github/workflows/ci-cd.yml
- .lintstagedrc.js
Make Rubocop behavior identically on all platform.
n/a
n/a
> Keep rubocop's usage consistent

- README.md
Hi 👋🏾  glad to be on the team!
My onboarding checklist 😅 
[cut out a fair bit of the template for brevity]
> docs: Add filleduchaos to core contributors list

- README.md
Hi! Uffizzi has now provided 250 ephemeral environments (and counting) for the forem project! This PR adds an acknowledgment in the README 😃. (Disclaimer: I work on the Uffizzi project)
- Related Issue # N/A
- Closes # N/A
N/A
None
No
> Add Uffizzi acknowledgement

- README.md
Hello all, I'm on the team! So now my name is on the list! 
I had forgotten a config step before the previous PR, so I was submitting as "two contributors" with my local macbook as the first "email. 
Closed that PR in favor of this one since I didn't see a way to change the committer after the fact or to verify a "***Macbook.local" email address on GH. 😅 
- Closes # …
> add duke to list of core contributors

- app/controllers/display_ads_controller.rb
> Change DisplayAds's fastly header

- app/models/display_ad.rb
- spec/models/display_ad_spec.rb
Small fix related to this work which just shipped: https://github.com/forem/forem/issues/19225
The problem is that we added new locations where we can't use the "small" image width. This is sort of an in-between width, but I think sticking with post width here is fine.
- Related Issue https://github.com/forem/forem/issues/19225
- Closes #
Tests should cover this.
> Fix image width for feed location

- app/assets/javascripts/initializers/initializeDisplayAdVisibility.js
- app/javascript/packs/billboard.js
This is a fix to deal with a race condition popping up due to the async loading of billboards.
- Closes https://github.com/forem/forem/issues/19325
> Fix display ad event race condition

- container-compose.yml
This PR replaces dockerize entrypoint used to check dependency availibility (redis, db, rails) by the healthcheck feature added in compose. No need to copy db, redis port information and so one, no need to use an extra entrypoint, conditions are more precise.
appropriately. …
> Add healthchecks to container-compose.yml

- app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
Quick fix to a typo from this PR: https://github.com/forem/forem/pull/19329
> Fix typo in tag mod email

- .github/workflows/ci-cd.yml
Adding this so we can start tracking exceptions by commits.
https://github.com/forem/forem/issues/19248
n/a, only in production
need to add variable.
> Track Deploys with Honeybadger

- app/assets/stylesheets/base/typography.scss
- app/assets/stylesheets/config/_colors.css
- app/assets/stylesheets/ltags/CommentTag.scss
- app/assets/stylesheets/ltags/GithubReadmeTag.scss
- app/assets/stylesheets/ltags/LinkTag.scss
- app/assets/stylesheets/ltags/UserTag.scss
- app/assets/stylesheets/themes/dark.css
This is a low-hanging-fruit and starter PR for an issue related to investigating and [updating liquid styling](https://github.com/forem/forem/issues/19343) issues in order to create a more unified look.
This does not entirely close the issue, but is meant to be a first step, and a helpful example for anyone looking to contribute. I will modify that issue to point to this PR as an example.
We cannot easily modify liquid markup as it stands, but we do have the opportunity to get a start in improving the unified design by hacking out on the existing css. It is a small step towards cleaning up our liquid embed approach in general.
Once we push this, we will eliminate some low-hanging fruit and will have the chance to follow up with other fixes.
- Related Issue …
> Unify some liquid embed styles without modifying markup

- app/assets/stylesheets/ltags/LinkTag.scss
As a follow-up fix from this PR:
https://github.com/forem/forem/pull/19348
Links from org accounts got messed up, and this patches that.
- Related to https://github.com/forem/forem/issues/19343
Bug:
Fix:
> Style bug fix: Profile pic for link liquid embed on org posts misaligned

- config/feed-variants/20230424-variant-a.json
- config/feed-variants/20230424-variant-b.json
- config/feed-variants/20230424-variant-c.json
- config/field_test.yml
Kicking back off the feed experiments we'd deprioritized earlier this year — now that we have a better process in place for tag moderation, it should enable us to focus on the feed delivering better results on a tag basis, as opposed to focusing on overall popularity.
For review, this may be a little tough to read if you're new this. Please ask questions if you want to review, but are confused. Otherwise, these changes are pretty minimal.
Carefully check the config file to make sure no mistakes. Otherwise if the tests pass, this should be valid.
> Add feed experiment for 04/24

- package.json
- yarn.lock
While working on https://github.com/forem/forem/pull/19384, I tried to view the `storybook` documentation with `yarn storybook` but there were missing modules, this PR adds those modules so `yarn storybook` can run.
> Update modules so storybook can run

- app/views/admin/tags/edit.html.erb
This PR does not make any major change, just focuses on improving UX.
So basically there are two sections, one is list-of-moderators (which can be a long list) and second is "add-moderator" section. In current implementation, if the first-section is long the admin will need to make multiple scrolls to visit "add-moderator" section. So in this PR we are fixing this by inter-changing the positions so that admin won't need to scroll.
See below sections for more details.
**Output:** https://www.loom.com/share/eab8907b395247c889df9c96b65dca07
| Before  | After |
| ------------- | ------------- |
| <img width="1001" alt="Screenshot 2023-04-18 at 11 30 26 PM" src="https://user-images.githubusercontent.com/9396084/233150190-2e5add05-8585-48ff-b9b2-df33f8dc657c.png"> | <img width="1011" …
> Changed Add Moderator position for better UX

- app/queries/articles/api_search_query.rb
- spec/queries/articles/api_search_query_spec.rb
Limits results from this query to articles over `Settings::UserExperience.index_minimum_score` in order to limit potential spam from the results
- Related Issue https://github.com/forem/forem-internal-eng/issues/599
> Limit ApiSearchQuery results to index minimum score

- app/assets/stylesheets/themes/dark.css
- app/javascript/articles/components/CommentListItem.jsx
Follow up here with quick fix here: https://github.com/forem/forem/pull/19416
Fixes dark mode, and hot fix for an image edge case where if the image url is long enough it doesn't get rendered as expected due to long paragraph logic.
- Related Issue https://github.com/forem/forem/pull/19416
Bug:
Solution:
> Hotfix: proper darkmode gray, and image inclusion fix

- app/assets/stylesheets/components/comments.scss
Another fast follow here on https://github.com/forem/forem/pull/19416
This fixes a couple long-standing issues of blockquote not having styling in this context, and an image edge case where an image is a direct descendant of a `li` in a way that makes it show up oddly.
These problems have been around for a while, but working on improving this area lifts up their relevancy.
- Related Issue https://github.com/forem/forem/pull/19416
> Fix blockquote and image edge cases in comment previews

- codecov.yml
Having a target at 90% requirement on all PR is unrealistic and a hindrance to a contributor's productivity. 
n/a
n/a
> Reduce Codecov's patch target to 85%

- public/.well-known/ai-plugin.json
- public/openapi.yml
Just updating some copy in the `ai-plugin` description — shouldn't change any functionality meaningfully.
- Related Issue https://github.com/forem/forem-internal-eng/issues/599
> Change copy in ai-plugin

- app/views/users/onboardings/_task_card.html.erb
Many Forems don't have a Welcome Thread — Mostly because I don't think it's clear in any instructions that you should set this up, and things that only apply to new users often get missed.
Performance-wise, while this does add a query, this is in an area which is already globally fragment-cached so should have no practical impact on performance.
Three things is a better number, but at least it's not a broken link :)
- Closes https://github.com/forem/forem/issues/19459
> Do not show link to welcome thread if it doesn't exist

- app/controllers/stories/feeds_controller.rb
- config/feed-variants/20230511-variant-a.json
- config/feed-variants/20230511-variant-b.json
- config/feed-variants/20230511-variant-c.json
- config/field_test.yml
Config adjustments for feed after seeing success from one of the new variants last week.
The intention of each new experiment is located in the `description`.
This change also includes a retroactive adjustment to the winner to fix an issue where 15+ days of decay is not less than 14 and less, causing a problem where older posts show up instead of newer ones sometimes when the user follows no tags.
Inspect for typos or mishaps, but there is no true verifiable "correctness". If the tests pass, it will indicate that there were no major typos.
> Add feed experiment for 5/11

- app/services/users/suggest_recent.rb
- spec/services/users/suggest_recent_spec.rb
Quick feature update to not suggest suspended users accounts.
While we may want to cache roles in general like we do tags on articles to make this more efficient — I think this should be fine for performance.
- Closes https://github.com/forem/forem/issues/19465
Double-checking the logic?
> Do not suggest user who is currently suspended

- app/services/open_graph.rb
- spec/liquid_tags/unified_embed/tag_spec.rb
Fetching other Forems via the OpenGraph meta data fetch seems to fail, and it fails because of a Fastly bot policy we have in place on Fastly-hosted Forems.
I changed from `Net::HTTP.get` to `HTTParty` because setting a user agent is a lot more elegant in HTTParty, but the I/O of the transaction should ultimately be the same.
- Related Issue https://github.com/forem/forem/issues/19461
The issue is related to failures _in general_, so I think it can still be open because there may be other failures.
Go to create or preview a post in the Uffizzi and compare to live site.
You can fetch DEV or ThisMMALIfe as examples
> Send user agent in open graph fetch so we don't block our own requests

- app/models/admin_menu.rb
- app/views/admin/privileged_reactions/index.html.erb
> Fix typo / erroneous word in Admin Section

- db/migrate/20230511194704_add_composite_index_to_segmented_users.rb
Requires approval, but this would fix the problem from https://github.com/forem/forem/pull/19476 where the index migration fails
- Related Issue https://github.com/forem/forem/pull/19476
Verify that this is appropriate
> Remove unique constraint from segmented users index

- spec/services/comment_creator_spec.rb
> Temp disable flaky spec

- .github/PULL_REQUEST_TEMPLATE.md
This addresses an action item from today's internal Engineering roundtable discussion. We decided to add a checklist to put a11y more top of mind for the PR submitter / reviewer.
> Update PR template to include a11y checklist

- app/assets/stylesheets/views/article.scss
- app/views/articles/_multiple_engagements.html.erb
Resolves https://github.com/forem/forem/issues/19474
- Issue: On iPhone 8, seems like emojis were not aligned with the numbers next to them and was overlapping on text below them.
_![image](https://github.com/forem/forem/assets/97286047/1ec73a3e-f519-4c9c-b1bf-90510b1cb504)_
- Resolution: Made use of flex-box to show the emojis + number combination on UI which eliminates unwanted split between emojis followed by its number.
_![image](https://github.com/forem/forem/assets/97286047/1973c939-747c-4b77-8dba-b7ee12538eb7) _
- Just made use of flex-box which I felt to be an ideal solution for the misalignment issue here.
- From accessibility standpoint, I tested this in smallest screen possible and it worked just fine without any overlapping.
> Update multiple_reactions_engagement's alignment

- app/assets/stylesheets/views/article.scss
This fixes a cumulative layout shift caused by a recent change to how this element is rendered.
A `height` attribute was removed, which is fine, but there should still be a `min-height` attribute.
This element is only present if there is at least one reaction, so a min-height is fine.
- Related Issue https://github.com/forem/forem/pull/19484
- Closes https://github.com/forem/forem/issues/19567
**Problem:**
https://github.com/forem/forem/assets/3102842/681295f6-83eb-40ea-9963-dc85576fc37d
**Fix:**
https://github.com/forem/forem/assets/3102842/34de6c8b-d414-4919-9ed7-c81394b78370
> Fix cls with min-height for multiple reactions

- app/models/user.rb
- spec/factories/segmented_user.rb
- spec/models/user_spec.rb
- spec/services/users/delete_spec.rb
Adding missing "segmented" related association to User model and specs.
resolves https://github.com/forem/forem/issues/19624
test should pass.
n/a
> Add has_many associations to User model

- app/javascript/packs/billboard.js
The observing line was removed in a recent PR and we are not currently tracking impressions or clicks in billboards.
- Closes https://github.com/forem/forem/issues/19630
> Patch: Add Removed observeDisplayAds line in billboard.js

- db/migrate/20230622151208_remove_existing_segmented_users.rb
- db/migrate/20230622151553_add_unique_constraint_to_segmented_users.rb
- db/schema.rb
We had a PR to add a unique index to segmented users [here](https://github.com/forem/forem/pull/19476).
We then [removed the unique constraint](https://github.com/forem/forem/pull/19544) since there were existing dupes we didn't account for and got the deployment to go through. However, this left us unable to close the loop on making this feature functional.
The approach was to delete all existing segmented users since these are re-generated and can be effemeral for all intents and purposes. That seems cleanest to me instead of a more complicated de-duping. Since the manual segmentation doesn't fully work with the unique constraint, no manual segments have been fully created.
Since these actions need to happen in sequence, a migration seems like the right approach vs a data update script, …
> Add unique index constraint to segmented users

- app/controllers/follows_controller.rb
- app/javascript/packs/followButtons.js
- app/services/follows/delete_cached.rb
Unfollowing tags isn't working as expected. The problem turns out to be with caching.
- Closes #19517 
`rails dev:cache`
> Fix bug: Unable to unfollow topics

- cypress/e2e/seededFlows/articleFlows/commentModerationTools.spec.js
- spec/models/article_spec.rb
- spec/queries/display_ads/filtered_ads_query_spec.rb
Skip some problematic flaky spesc.
n/a
> Skip flaky specs

- .github/workflows/ci-cd.yml
Codecov uploader is very unreliable. It's driving us nuts.
n/a
> Add retry to codecov upload

- app/models/display_ad.rb
- spec/models/display_ad_spec.rb
This makes several values we assign in `for_display` logic configurable via ENV while falling back to current values if not set.
- Closes https://github.com/forem/forem/issues/19676
> Allow LOW_IMPRESSION_COUNT and related values set by ENV

- app/liquid_tags/tweet_tag.rb
- app/views/liquids/_tweet.html.erb
This fixes a bug found in Windows Chrome where the tweet shrinks after being rendered (demonstrated in the linked issue).
- Closes https://github.com/forem/forem/issues/19640
This fix was verified using Browserstack to confirm the bug and the fix.
Here is a link to an embedded tweet in Uffizzi https://pr-19686-deployment-30227-forem.app.uffizzi.com/admin_mcadmin/test-373o
> Fix Windows tweet schrinking phenomenon

- app/javascript/utilities/__tests__/codeFullscreenModeSwitcher.test.js
- app/javascript/utilities/codeFullscreenModeSwitcher.js
Going back from full screen code block leads to inability to scroll 
- Related Issue #19662 
- Closes #19662 
https://github.com/forem/forem/assets/24551335/8ff57bb3-8040-4a5e-8ec6-617dee6b12c9
> fix scroll when popstate from a full screen code block

- app/controllers/billboards_controller.rb
- app/helpers/billboard_helper.rb
- app/queries/display_ads/filtered_ads_query.rb
- app/views/admin/billboards/_form.html.erb
- spec/helpers/billboard_helper_spec.rb
Renamed `DisplayAdHelper` to `BillboardHelper`
- Related Issue #19372 
Renamed the tests and methods
> Renamed DisplayAdHelper to BillboardHelper

- app/javascript/articles/Feed.jsx
We had some ES lint rules failing on the home feed page. 
The lint rule and details can be found [here](https://github.com/facebook/react/issues/14920) but the gist of it is that we depend some functions in the useEffect hook and it is strongly recommend to include them even the ones that you think won't change. 
- Closes #
Hmmm, I guess test that the home feed renders and there are no errors related to the change. All tests should continue passing as well. 
> Fix Lint rule https://github.com/facebook/react/issues/14920

- app/assets/javascripts/initializers/initializeDisplayAdVisibility.js
- app/controllers/billboard_events_controller.rb
- app/javascript/packs/billboardAfterRenderActions.js
- config/routes.rb
- spec/requests/billboard_events_spec.rb
Renamed `DisplayAdEventsController` to `BillboardEventsController`
> Renamed DisplayAdEventsController to BillboardEventsController

- app/javascript/packs/homePage.jsx
The dropdown on billboards no longer open on the logged in home page feed billboards
The dropdown was not yet in the DOM when we were trying to initialize it, hence we move it to the callback so that it can be initialized correctly adn show up accordingly. 
- Related Issue #https://github.com/forem/forem/issues/19802
- Closes #19802 
- Log in to the app
- Create a billboard for the home page feed, `feed_first`
- Go to the home page
- Click on the three dot menu on a billboard
- The menu should open
> Fix : Ensure that the billboard dropdown shows on billboards in the logged in feed

- .github/ISSUE_TEMPLATE/-core-team-only---new-approved-feature.md
- .github/ISSUE_TEMPLATE/bug_report.md
Includes the "bug" label when using the Bug issue template.
Closes https://github.com/forem/forem/issues/19813
> Add "bug" label to bug issue template

- spec/services/admin/charts_data_spec.rb
- spec/services/article_with_video_creation_service_spec.rb
- spec/services/broadcasts/welcome_notification/generator_spec.rb
- spec/services/comment_creator_spec.rb
- spec/services/homepage/fetch_articles_spec.rb
- spec/services/html/parser_spec.rb
- spec/services/images/optimizer_spec.rb
- spec/services/languages/detection_spec.rb
- spec/services/mailchimp/bot_spec.rb
- spec/services/search/podcast_episode_spec.rb
- spec/services/search/reading_list_spec.rb
- spec/services/search/username_spec.rb
- spec/services/user_subscriptions/create_from_controller_params_spec.rb
- spec/services/users/suggest_for_sidebar_spec.rb
- spec/system/comments/user_delete_a_comment_spec.rb
- spec/views/email_subscriptions/unsubscribe.html.erb_spec.rb
Fixed rubocop issues in `spec/services`
> Rubocop fixes in spec/services

- app/views/users/_sidebar.html.erb
Have a look at QA description directly.
- Closes #19791
[Loom Recording - showing error + solution](https://www.loom.com/share/6a007b27c68246d0a5fae21250c5ba56?sid=24dc32eb-37f6-4194-9e93-81405206d4ee)
1. Create a new account
2. Publish an article
3. Navigate to the new account's profile page (`/<username>`)
4. Unpublish the new account's articles from the dropdown menu on in the member manager (/`admin/member_manager/users/<user_id>`)
5. Navigate back to the account's profile page - the number of posts will not have updated
No UI Change
> Burst cache for user profile page

- app/javascript/articles/__tests__/Feed.test.jsx
- app/views/articles/index.html.erb
- app/views/billboards/show.html.erb
- app/views/shared/_billboard.html.erb
- app/views/shared/_billboard_header.html.erb
- app/views/sidebars/_homepage_content.html.erb
- app/views/stories/_main_stories_feed.html.erb
Renamed variables in the views and a couple of views themselves
> Rename display ads vars in the views

- app/views/admin/feedback_messages/_feedback_message.html.erb
Sometimes the send email button in admin-reports (/admin/moderation/reports) does not work. This PR fixes that issue.
Also, while committing the code there was error mentioning that we should use `autocomplete` attribute and therefore I have added that too.
- Closes #19879
Have a look at this loom video. This should be sufficient: https://www.loom.com/share/16961da0793b42b6b9bd1e29312cd814
No UI Change.
> Bug Fix for Admin Reports Send Email button

- spec/models/comment_spec.rb
Skip problematic comment spec
n/a
> Skip problematic comment spec

- app/controllers/billboards_controller.rb
- app/models/tag.rb
- app/models/user.rb
- spec/models/tag_spec.rb
This is an adjustment to the behavior of `user_tags` to limit the number of tags we send for consideration in billboards, and also weights towards the user's preferred tags while randomly mixing up the number within the range we ask for.
Limiting the tags we send seems to be a solution for a performance bug described in the issue.
- Closes https://github.com/forem/forem/issues/19922
> Limit billboard user_tags number and weight towards preferred tags

- app/services/images/generate_social_image_magickally.rb
- spec/models/hair_trigger_spec.rb
- spec/services/images/generate_social_image_magickally_spec.rb
In using Minimagick to generate social image, we deployed a PR with a feature flag. In testing this behind the flag, the absolute URL path didn't work in production — due to Fastly headers. However, this file can be access directly in this change, and it does work.
Feature still behind feature flag while ensuring it works across environments and apps.
- Related Issue https://github.com/forem/forem/pull/19826
> Use direct relative path to access assets in minimagick

- app/controllers/stories/feeds_controller.rb
- config/feed-variants/20230814-variant-a.json
- config/feed-variants/20230814-variant-b.json
- config/feed-variants/20230814-variant-c.json
- config/field_test.yml
Adding some new home feed variation tweaks to a/b test.
This elevates the most effective variant from the last time we tested.
- Closes #
The adjustments in the files should match the description. I'm pretty sure everything lines up for this one.
Regression tests cover the basic "does this continue to work" grounds.
> Add feed experiment for Aug 14

- app/models/display_ad.rb
- spec/models/display_ad_spec.rb
Small adjustment to a prior change which will ensure safe inputs for ENV vars we pass into billboards. Shouldn't change behavior in happy paths, but will ensure no errors.
- Related Issue https://github.com/forem/forem/issues/19676
> Safer inputs to billboard ENV vars

- app/javascript/articles/LoadingArticle.jsx
- app/services/images/optimizer.rb
- app/services/images/profile.rb
- spec/services/images/optimizer_spec.rb
We use `imagga_scale` as an option in Cloudinary, but it is an add-on we don't necessarily need, but it behooves us to maintain this option if it were previously enabled to maintain consistency for now.
However, in attempting to maintain compatibility while also reducing complexity, we set `imagga_scale` in a location where it had previously been set explicitly to `fill`.
This fixes the issue.
- Closes https://github.com/forem/forem/issues/19970
Tests should cover this as best as we can tell
> Do not crop with imagga if never_imagga is passed

- app/models/settings/base.rb
This reverts commit 66e7f8f5e39a6f8ebdfb49e5dd15e41e86555c8d.
- Closes #
> Revert "Switch settings to safe yaml load (#19928)"

- app/models/navigation_link.rb
- spec/models/navigation_link_spec.rb
Improve SVG regular expression validation to avoid unexpected and unnecessary information.
- Closes #
None
Not applicable
> Improve SVG regexp validation

- app/assets/stylesheets/scaffolds.scss
- app/javascript/actionsPanel/__tests__/initializeActionsPanelToggle.test.js
- app/javascript/actionsPanel/initializeActionsPanelToggle.js
- app/views/articles/_actions.html.erb
- app/views/moderations/mod.html.erb
Fixes a content layout shift in the show view action panel for trusted shield. This re-uses the `trusted-visible-block` which is designed for this type of functionality. 🙂
- Closes https://github.com/forem/forem/issues/19990
Get into any "trusted" state. If you sign in as admin on Uffizzi, you should be able to see this.
(Email: `admin@forem.local`, password: `password`)
This should improve a11y as a side effect.
> Fix content layout shift with mod-actions-menu-btn

- app/views/users/_api_keys.html.erb
- app/views/users/_integrations_github_repositories.html.erb
- app/views/users/_publishing_from_rss.html.erb
- app/views/users/_response_templates.html.erb
- app/views/users/_web_monetization.html.erb
Add id attributes to setting sections in /settings/extensions
- Closes #19869 
> add id attr settings extensions

- spec/factories/articles.rb
- spec/lib/data_update_scripts/generate_display_ad_names_spec.rb
- spec/requests/admin/billboards_spec.rb
- spec/requests/admin/html_variants_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_v1.json
Renamed test descriptions and stuff in swagger that was left.
I have run `rswag` so there are a lot of changes in `api_v1.json`. Should have I done that or not? )
> Renamed display ad leftovers (test descriptions, swagger)

- app/assets/stylesheets/preact/onboarding-modal.scss
- app/javascript/onboarding/components/EmailPreferencesForm.jsx
- app/javascript/onboarding/components/FollowTags.jsx
- app/javascript/onboarding/components/FollowUsers.jsx
- app/javascript/onboarding/components/ProfileForm.jsx
Move navigation to bottom in onboarding
- Closes #19985
[Figma Designs](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2951-5177&mode=design&t=r6NBtzaywCXYCyL6-4)
1. Sign in locally or on Uffizzi
2. Visit `/onboarding` to check all onboarding steps.
1. Moved `Navigation` to bottom in onboarding screens
3. Reduced thickness of the divider line from `2px` to `1px`
4. Changed color of divider line to `grey-200` as per designs.
> Move navigation to bottom in onboarding

- .github/workflows/ci-cd.yml
actions/checkout@v4 just released yesterday. It's sensible to upgrade becuase it provide support to github codespace. Also because github action is kind of broken right now.
n/a
> [CI] Use actions/checkout@v4

- Containerfile
Node distribution couldn't choose a better way to update their path. 
n/a
> Address deprecated nodesource distributions

- app/uploaders/base_uploader.rb
Fixes incorrect orientation of some images
- Closes #19880
Recording: https://www.loom.com/share/c3c1aa3c9a2043b2a7cef3b7c1015c44?sid=6899754f-041f-4af0-bcf9-5ddab7ba8e16
> Image auto orient

- app/controllers/admin/badge_achievements_controller.rb
Order badges in asc order on /admin/content_manager/badge_achievements/award_badges
- Closes #20067
1. Sign in as admin
2. Visit /admin/content_manager/badge_achievements/award_badges
3. Click on Badge dropdown
4. Notice that the badges are not alphabetically arranged.
No test needed
> Order badges in ascending order

- app/controllers/concerns/api/admin/users_controller.rb
- app/services/search/user.rb
- spec/requests/api/v0/admin/users_spec.rb
- spec/requests/api/v1/admin/users_spec.rb
- spec/services/search/user_spec.rb
We have a couple bugs: One where users are not marked `registered: false` when being invited via the API, and one where users appear in the search even before accepting an invitation.
This is a quick fix to both these bugs.
- Closes https://github.com/forem/forem/issues/20070
- Closes https://github.com/forem/forem/issues/20069
Tests should cover this
> Fix "register" bugs in invitations

- app/assets/stylesheets/views/mod-actions.scss
- app/models/article.rb
- app/views/moderations/actions_panel.html.erb
- config/locales/views/moderations/en.yml
- config/locales/views/moderations/fr.yml
- cypress/e2e/seededFlows/moderationFlows/adjustPostTags.spec.js
- cypress/fixtures/users/adminUser.json
- cypress/support/commands.js
- spec/models/article_spec.rb
We want moderators to be able to view the history of tag additions and removals on an article when they are viewing and updating an article's tags.
This PR adds "newest adjustment first" historical context below the tag moderation UI that lives in the "Adjust post" moderation panel for an article.
- Related Issue #19823
- Closes #19823
As a moderator user, go to the moderation center at `/mod` and click into an article. You could also visit an article's show page and click the shield icon in the left sidebar.
A "Moderate Post" panel will appear on the right. 
Scroll down to "Adjust tags" and click to see the dropdown.
Add and remove tags by name, providing reasons (of various lengths, to test UI) when adding
Switch users and have another moderator make an adjustment as well
Verify that …
> display tag moderation history in article's mod panel

- config/fastly/snippets/client_geolocation.vcl
This PR adds the country codes for 13 new countries we want to elevate for more granular cache control for the purpose of broad geotargeting, while allowing all the rest of the traffic to not be considered for geo at this moment.
This is noted as related to [this PR](https://github.com/forem/forem/pull/20083).
- Related Issue https://github.com/forem/forem/issues/19978
- Related PR https://github.com/forem/forem/pull/20083
This should include some post-deploy gut check, and proof-reading, but probably not a lot of other QA we can do.
> Add new countries to edge cache dictionary

- app/controllers/comments_controller.rb
- spec/requests/comments_spec.rb
WIP
- Closes #19927
- Related #19925 
- Built on top of #20079
- Related #19773 
- Related #20043
> Record feed event for article comments

- app/helpers/application_helper.rb
- spec/liquid_tags/user_tag_spec.rb
We need to have the `follow-user` class present in the follow button for bulk following to work.
In the context of liquid tags, we pass a `UserDecorator` object, instead of a `User` object. This fixes that.
- Closes https://github.com/forem/forem/issues/20097
> Add proper follow-user class to liquid when passed UserDecorator

- app/controllers/profile_field_groups_controller.rb
We changed how terms are accepted in the onboarding with a bug, this is a presumed patch.
> Fix onboarding with implicit terms acceptance

- .github/PULL_REQUEST_TEMPLATE.md
- codecov.yml
Reduce across the board threshold -- see: https://forem-team.slack.com/archives/CUJDU2R8D/p1694541980512949
> Reduce Codecov's patch target to 60%

- app/assets/stylesheets/preact/onboarding-modal.scss
- app/javascript/onboarding/components/FollowTags.jsx
This bug was introduced in #19986
- Related Issue #19986
[Loom video for issue + solution](https://www.loom.com/share/82aff27e12894260bfb33ad17f91bd39)
> Bug fix: Opt email design janky issue fix

- app/controllers/comments_controller.rb
- app/policies/comment_policy.rb
- app/policies/response_template_policy.rb
- spec/policies/comment_policy_spec.rb
- spec/policies/response_template_policy_spec.rb
- spec/requests/response_templates_spec.rb
Bug is well described in these videos:
Trusted Members Can't Currently Use Trusted Member Response Templates
https://www.loom.com/share/a69076ffb0674718a887fd9b5fa0411d
Tag Mods CAN Use Trusted Member Response Templates
https://www.loom.com/share/4f904b5fb5b544408b5a444797d27bdb
(And on [the original issue](https://github.com/forem/forem/issues/20138).)
Background:
* I worked on response templates [as one of the first PRs I opened](https://github.com/forem/forem/pull/17978) and did not _really_ understand what I was doing
* Also the feature [changed some time later](https://github.com/forem/forem/pull/18601), further reducing the scope for `trusted user`
* As originally implemented, I'm not entirely sure it ever _actually_ allowed a `trusted user` to comment _as_ a moderator (though the …
> Trusted user _can_ use moderator comment

- README.md
We are making the difficult choice of [making layoffs to our core team today](https://dev.to/devteam/dev-team-update-22c9).
We're going to remove this section for now to limit singling out, etc.
Of course, we have tremendous gratitude for all of our core contributors and team members.
> Update README.md core team

- app/assets/stylesheets/base/typography.scss
- app/assets/stylesheets/components/comments.scss
- app/assets/stylesheets/components/syntax.scss
I thought this one was going to be a simple thing/missing bit of CSS, but it turned out more complicated than that
Basically, normally we parse markdown code snippets (delineated by backticks) into a code-highlighted `pre` element that's wrapped in a div that adds the expand/fullscreen control. Inspecting the article in question showed that the overflowing blocks _weren't_ getting wrapped in this div and were thus being excluded from the styling they should be getting. I still don't understand why; there are other code blocks in the article that are wrapped correctly/don't overflow, and when I pulled the article's markdown from the API there was nothing that seemed to distinguish the blocks that got wrapped and the blocks that didn't.
I wasn't making much progress untangling that knot, so …
> Temporary fix for text sometimes overflowing code blocks in posts

- app/assets/javascripts/initializers/initializeCommentsPage.js.erb
When you hover over `.reaction-drawer` and scroll through the comments, you can see that the like button is on top and even has a different z-index each time. 
- Related Issue https://github.com/forem/forem/commit/40e63a16c9c11ecb2fb84d6d1388cb6fc06250fc and https://github.com/forem/forem/issues/19722
- Closes https://github.com/forem/forem/issues/20164 
#20143
_Before_
https://github.com/forem/forem/assets/14293805/1addf186-c9ef-452f-b330-16158d93834a
_After_
https://github.com/forem/forem/assets/14293805/fbee2f87-2b01-476d-b100-c9ab017c511a
On desktop
On mobile
_We encourage you to keep the code coverage …
> fix: removed z-index on .reaction-button

- config/feed-variants/20230927-variant-a.json
- config/feed-variants/20230927-variant-b.json
- config/field_test.yml
Adds two new feed experiments and elevates the past winner.
These two new ones are small variations on last week's — which all presented a certain amount of success.
> Add new feed experiments

- app/models/role.rb
- app/models/user.rb
- app/policies/authorizer.rb
- app/services/moderator/manage_activity_and_roles.rb
- config/locales/views/admin/en.yml
- config/locales/views/admin/fr.yml
- db/seeds.rb
- spec/models/role_spec.rb
- spec/models/user_spec.rb
Old code related to roles that don't do anything.
> Remove dead code associated with old roles

- app/models/articles/feeds.rb
- config/feed-variants/20231001-variant-a.json
- config/feed-variants/20231001-variant-b.json
- config/field_test.yml
This includes a couple new "final order" options.
- Closes #
> Add new feed experiment for 10-1

- app/models/feed_event.rb
- app/services/articles/page_view_updater.rb
- spec/models/feed_event_spec.rb
- spec/services/articles/page_view_updater_spec.rb
This adds a new type of feed event specifically for page views which hit 60 seconds and aggregates them in the score.
This adds "extra work" to the page view updater, but only on the event which hits 60 and no other ones.
- Closes https://github.com/forem/forem/issues/20197
> Add feed event for extended page view

- app/controllers/admin/feedback_messages_controller.rb
- app/views/admin/feedback_messages/_abuse_reports.html.erb
- app/views/admin/feedback_messages/index.html.erb
- spec/system/admin/admin_manages_reports_spec.rb
Adjusts the default and reconciles some use of direct status param and the ransack param.
This is still kind of weird, but better.
- Closes https://github.com/forem/forem/issues/20199
> Make admin reports default to showing open

- app/assets/stylesheets/components/tabs.scss
- app/assets/stylesheets/themes/dark.css
- app/controllers/admin/feedback_messages_controller.rb
- app/models/reaction.rb
- app/services/admin/data_counts.rb
- app/views/admin/overview/_health_check.html.erb
- app/views/admin/shared/_nested_sidebar.html.erb
- spec/models/reaction_spec.rb
Creates a scope to deal with the type of flags we are actually looking for — and removes the "potential spam users" part.
This also closes some link styling in the process.
- Closes https://github.com/forem/forem/issues/20201
- Closes https://github.com/forem/forem/issues/19530
> Fix irrelevant flag numbers

- app/views/admin/articles/_article_item.html.erb
- app/views/admin/settings/forms/_community.html.erb
- app/views/admin/settings/forms/_mascot.html.erb
- app/views/admin/tags/edit.html.erb
This temporarily removes the user name input functionality. The full fix is a matter of adjusting the logic for this functionality to better scale to production needs.
This will convert these fields back to plain old "ID" fields for now.
- Related Issue https://github.com/forem/forem/issues/20206
> Roll back user name selection for user id boxes

- app/models/reaction.rb
- app/services/admin/data_counts.rb
- app/views/admin/feedback_messages/_abuse_reports.html.erb
- spec/models/reaction_spec.rb
The prior fix for this did not quite do the trick. This makes some tweaks to have the number show up as we expect it to, hopefully as the final fix.
- Related Issue https://github.com/forem/forem/pull/20204
> Follow on adjustments to flag counts fix

- app/models/articles/feeds.rb
Adds the ability to add language_match to feed config. This bumps relevancy, not a strict filter. It is a soft introduction on feed language being used.
This does not immediately change any functionality, but lets us examine how different weights here will affect the feed.
- Related Issue https://github.com/forem/forem/issues/20090
- Closes #
> Add language match as possible feed lever

- app/javascript/packs/toggleUserFlagModal.js
checking if the modal is being rendered inside the iframe, if true it will look for the modal inside the iframe
- Related Issue #20188
- Closes #
Check if opening the modal causes any unwanted behavior.
> fix: issue - modal 'flag user' is not openning [#20188]

- Gemfile
- Gemfile.lock
- spec/models/hair_trigger_spec.rb
This resolves a flaky spec we have
Resolves https://github.com/forem/forem/issues/19944
n/a
> Bump with_model

- app/javascript/utilities/__tests__/localDateTime.test.js
I changed the second parameter of `timestampToLocalDateTime` in test from 'default' to 'en' because, when developers use non-en locale in their computers and run `yarn test`,  this function returns different values than we expected in the tests.
For examples, in Japan locale, this function returns `2019/5/3` not `5/3/2019`. 
- None
> Fix tests that fail when developer uses a non-en locale

- app/assets/stylesheets/components/forms.scss
- app/views/podcasts/_form.html.erb
Add the required field label indicator for the "new podcast suggestion" form fields
- Related Issue #11433
- Closes #11433
Desktop
Mobile
No
> Feat add required field indicador

- app/liquid_tags/stackblitz_tag.rb
- spec/liquid_tags/stackblitz_tag_spec.rb
- Improve `PARAM_REGEXP` in stackblitz_tag.rb to support all options listed in the [guides](https://developer.stackblitz.com/guides/integration/embedding#embed-url-options).
- Closes https://github.com/forem/forem/issues/20226
- None
> Support all embed URL options of Stackblitz

- app/models/user.rb
Ignore unused column before deleting it
> Ignore users.workshop_expiration column

- config/feed-variants/20231017-variant-a.json
- config/feed-variants/20231017-variant-b.json
- config/feed-variants/20231017-variant-c.json
- config/field_test.yml
This includes a couple new "final order" options.
> Add feed experiment for oct 17

- db/migrate/20231017120855_remove_workshop_expiration_from_users.rb
- db/schema.rb
Remove unused column which was ignored earlier
> Remove workshop_expirations column

- db/migrate/20231018102332_remove_tags_mod_chat_channel_id.rb
- db/migrate/20231018104234_remove_html_variants_success_rate.rb
- db/migrate/20231018104259_remove_listings_contact_via_connect.rb
- db/migrate/20231018104337_remove_notification_settings_email_connect_messages.rb
- db/schema.rb
Removed unused columns that were ignored earlier
I will remove `ignored_columns` lines in the next pr.
> Removed columns that were ignored earlier

- app/javascript/packs/base.jsx
This PR changes the timing of setting `history.scrollRestoration` to fix the issue of anchors that are not working.
It seems that in the Safari browser, anchor links do not work because `scrollRestoration` is set to `manual` upon page load.
I add the delay to ensure that the change to `scrollRestoration` is executed after the scroll position has been changed to the anchor position.
- Closes https://github.com/forem/forem/issues/20240
https://github.com/forem/forem/assets/17381979/b3ba8625-1781-4a2f-96da-2e7799cdfc15
> Fix anchors not working

- app/models/user_visit_context.rb
- spec/models/user_visit_context_spec.rb
This automatically adds user languages to a user when a new user visit context is created. A visit context only occurs when a user changes devices/locations/etc. so this check only happens _occasionally_ and is pretty lightweight. But it ensures we keep up to date with default language preferences.
- Closes https://github.com/forem/forem/issues/20262
No UI, so purely verification of code and tests.
> Add language when new user visit context is detected

- app/models/html_variant.rb
- app/models/listing.rb
- app/models/tag.rb
- app/models/user.rb
- app/models/users/notification_setting.rb
Removed `ignored_columns` lines for columns that were removed earlier.
> Remove ignored_columns lines

- config/feed-variants/20231023-variant-a.json
- config/feed-variants/20231023-variant-b.json
- config/field_test.yml
After seeing a winner from this last batch, these new experiments adjust the rate of decay, to reduce the likelihood of a "quite old" post coming up in someone's feed. But if that doesn't improve things, we're good with the current one. 😄 
> New Feed experiment for Oct 23

- app/decorators/user_decorator.rb
- spec/decorators/user_decorator_spec.rb
- spec/models/user_spec.rb
Until we may fix the iOS app in the future (which involves re-submitting for review and other complications), this backfill should fix the issue.
- Closes https://github.com/forem/forem/issues/20268
It's hard to verify so the main thing is just gut checking that noting _breaks_
> Backfill dark theme for app compatibility

- app/javascript/onboarding/components/EmailPreferencesForm.jsx
This fixes an issue where the newsletter checkbox is not being sent properly. The `state` does not actually include the value we're trying to pass here.
- Closes https://github.com/forem/forem/issues/20278
This is hard to test in our current setup (hence the error), so I've validated this via manual QA for now.
> Fix the data passed into the email newsletter

- app/controllers/admin/users_controller.rb
- app/javascript/__tests__/convertCoauthorIdsToUsernameInputs.test.js
- app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
- app/javascript/crayons/MultiSelectAutocomplete/__tests__/MultiSelectAutocomplete.test.jsx
- app/javascript/packs/admin/convertUserIdsToUsernameInputs.js
- app/javascript/packs/dashboards/convertCoauthorIdsToUsernameInputs.js
- app/javascript/shared/components/UserStore.js
- app/javascript/shared/components/__tests__/UserStore.test.js
- app/javascript/shared/components/__tests__/UsernameInput.test.js
- app/queries/admin/users_query.rb
- app/views/admin/articles/_article_item.html.erb
- app/views/admin/settings/forms/_community.html.erb
- app/views/admin/settings/forms/_mascot.html.erb
- app/views/admin/tags/edit.html.erb
- spec/queries/admin/users_query_spec.rb
This PR implements the username combobox with consideration for performance.
- I've added `ids` parameter to the `Admin::UsersQuery` class to allow the combobox to get only the necessary users.
- I've added the `debounceAction` to the `MultiSelectAutocomplete` component to prevent it from making a request every time a user inputs.
- Closes https://github.com/forem/forem/issues/20206
_We encourage you to keep the code coverage percentage …
> Fix username combobox tries to load all users

- app/javascript/crayons/ButtonGroup/__stories__/ButtonGroup.stories.jsx
The story ButtonGroup - button + icon showed a violation in the accessibility section
By adding a title to the SVG icon, which is a "Check" (or checkmark), the violation error disappeared.
Adding a title, I followed MDN documentation https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
closes #11723 
Storybook integrated test as seen in the shared screenshot.
> Add title="Check" to svg icon

- app/javascript/utilities/__tests__/dragAndDrop.test.js
- app/javascript/utilities/dragAndDrop.js
just adding the ondragend event to the element
- Related Issue #20270
- Closes #20270
i believe it's not necessary
> fix: tool editor disappears when dragging words #20270

- app/controllers/articles_controller.rb
- app/controllers/comments_controller.rb
- app/models/article.rb
- app/models/comment.rb
- spec/models/article_spec.rb
- spec/models/comment_spec.rb
- spec/requests/articles/articles_create_spec.rb
- spec/requests/articles/articles_show_spec.rb
- spec/requests/articles/articles_update_spec.rb
- spec/requests/comments_spec.rb
- spec/requests/editor_spec.rb
- spec/services/articles/creator_spec.rb
- spec/services/articles/updater_spec.rb
Removed the `consistent_rendering` feature flag and old code used when the feature flag is not enabled.
- Closes #20289
> Remove feature flag and use consistent rendering by default

- app/models/billboard.rb
- spec/models/billboard_spec.rb
Small additional tweak from recent adjustment on quality 95 to 100 due to billboard images being smaller and needing the best resolution we can manage — still optimized in general, but no quality reduction.
- Related Issue https://github.com/forem/forem/pull/20309
> Tweak billboard image quality

- app/services/articles/feeds/variant_query.rb
- spec/services/articles/feeds/variant_query_spec.rb
Adjusts existing logic for new behavior — since 18 hours was already hardcoded, I think it's reasonable to inline these numbers — however, could make them configurable later.
- Closes https://github.com/forem/forem/issues/20322
> Adjust VariantQuery to dynamically account for recent last_comment_at

- config/feed-variants/20231108-variant-a.json
- config/feed-variants/20231108-variant-b.json
- config/field_test.yml
Winner from last batch selected as the one with steeper default time cliff. This new experiment tests versions where articles with 0-1 comments get _slight_ demotion.
> New Feed experiment for Nov 8

- app/assets/javascripts/initializers/initializeBillboardVisibility.js
- app/controllers/billboard_events_controller.rb
- app/javascript/packs/billboardAfterRenderActions.js
- app/models/billboard_event.rb
- app/services/billboard_event_rollup.rb
- app/views/shared/_billboard.html.erb
- db/migrate/20231108153011_add_new_fields_to_billboard_events.rb
- db/schema.rb
- spec/requests/billboard_events_spec.rb
This adds new data to billboard events relating to what article the event came from if applicable, and what the geolocation context was.
These fields are _not_ designed to be taken into account for rollup, purely for recent analysis, and for use in optimizing targeting of billboards once some info is gathered.
- Closes https://github.com/forem/forem/issues/20062
> Add article id and geolocation info to billboard events

- .github/workflows/cla.yml
> [CI] Move CLA allowist to env var

- .github/workflows/cla.yml
> [CI] Make CLAAssistant reusable

- app/services/badges/award_thumbs_up.rb
- spec/services/badges/award_thumbs_up_spec.rb
Refactored `Badges::AwardThumbsUp` a bit: reduced the number of SQL queries, reorganized tests and added one more.
- Related #20111
> Refactoring `Badges::AwardThumbsUp`

- app/assets/stylesheets/components/cards.scss
- app/controllers/sidebars_controller.rb
- app/models/settings/general.rb
- app/views/sidebars/_homepage_content.html.erb
- config/environments/development.rb
- config/locales/views/main/en.yml
- spec/requests/sidebars_spec.rb
This feature adds a new "Active discussion" box to the home page for a more tailored view of discussions that are currently ongoing (and bumped by `last_comment_at`.
This includes a site config element so this can be turned on and off, but I did not add the admin UI — because there's some cruft that can be removed and I'd rather do that all at once. So for now this is only modifiable via console.
- Related Issue https://github.com/forem/forem/issues/20371
- Closes #
The new box will look like this, and this adds a sub-header with "short summary" of the tag in tag boxes:
> Add active discussions to sidebar

- app/controllers/concerns/api/users_controller.rb
- app/views/api/v0/users/me.json.jbuilder
- app/views/api/v1/users/me.json.jbuilder
- spec/requests/api/v1/docs/users_spec.rb
- spec/requests/api/v1/users_spec.rb
- spec/swagger_helper.rb
- swagger/v1/api_v1.json
Added followers count to `/api/users/me`
Also updated docs for this change, and a couple of previous users api changes.
Suggestions to the docs wording welcome.
- Closes #20326
> Added followers count to /api/users/me endpoint

- app/controllers/api/v1/recommended_articles_lists_controller.rb
- app/models/articles/feeds.rb
- app/models/recommended_articles_list.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20231121133843_create_recommended_articles_lists.rb
- db/migrate/20231121140731_add_indexes_for_recommended_articles_list.rb
- db/schema.rb
- spec/factories/recommended_articles_lists.rb
- spec/models/recommended_articles_list_spec.rb
- spec/requests/api/v1/recommended_articles_lists_spec.rb
This adds an article recommendation list which is settable via API. If it's set it can be included in feed variants to complement the rest of the feed indicators (i.e. these can be set as small nudges or total overrides depending on weights which can be tested).
- Closes https://github.com/forem/forem/issues/20385
> Recommended articles list

- app/services/badges/award_community_wellness.rb
- spec/requests/sidebars_spec.rb
This adds 24 weeks as an option to the community wellness streak.
- Closes #20319
I need some help with this one - I'm not sure whether we would need to do any manual QA on this.
- [x ] No, and this is why: existing test covers this new case
> Add 24 weeks to Community Wellness streak

- config/field_test.yml
Small fix to a misconfiguration in https://github.com/forem/forem/pull/20399
> Fix start date for field test

- app/controllers/api/v1/users_controller.rb
- app/controllers/concerns/api/users_controller.rb
- app/policies/user_policy.rb
- config/routes.rb
- spec/requests/api/v1/users_spec.rb
Search for users by email address via the API
- Closes #20395
> Search users by email address via the api

- app/assets/stylesheets/themes/dark.css
- app/javascript/packs/billboard.js
When images fail, based on the way the css currently works, the failing image will take up the whole page. This hides images if they fail.
This could make for a billboard that is supposed to have an image which doesn't have it — but that is a much better edge case to tolerate than one that ruins the experience. And likely better than showing a broken image as well in any case.
Images sometimes fail, especially for a developer audience where they're more likely to have different types of VPNs running, but this will make so it doesn't mess with the rest of the UX.
I also added a missing bit of css to dark theme — as a small adjacent billboard style bug.
- Closes https://github.com/forem/forem/issues/20384
> Hide images if error on billboards to fix blocking page

- app/controllers/admin/feedback_messages_controller.rb
- app/views/admin/feedback_messages/_feedback_message.html.erb
- app/views/admin/feedback_messages/index.html.erb
https://www.loom.com/share/429d6117d7734cd3805679224294d44d
- Close #20417
[_Please replace this line with instructions on how to test your changes, a note
images for UI changes._](https://www.loom.com/share/429d6117d7734cd3805679224294d44d)
- [] Keyboard operability supported?
- [] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [] Color contrast tested?
- [x ] No, and this is why: because I'm a coward and this is a small change
> Add filters to abuse reports admin page

- config/feed-variants/20231205-variant-a.json
- config/feed-variants/20231205-variant-b.json
- config/feed-variants/20231205-variant-c.json
- config/field_test.yml
Building on the 11/27 experiments, where the most heavily-weighted experiment to the new technique won, we keep that functionality and modify some of the other levers.
> Feed experiment for Dec 5

- app/assets/javascripts/initializers/initializeBillboardVisibility.js
- app/javascript/packs/billboardAfterRenderActions.js
Fixes an issue where we weren't passing all the info we need to.
- Closes https://github.com/forem/forem/issues/20446
> Track article id on billboard clicks

- app/helpers/admin/users_helper.rb
- app/views/admin/users/index/_user_status_indicator.html.erb
- spec/helpers/admin/users_helper_spec.rb
Added code related to the spam role to the `user_status` method (missed this in #20445)
#20430
> Consider spam role in the `user_status` method

- app/controllers/admin/feedback_messages_controller.rb
- app/views/admin/feedback_messages/_feedback_message.html.erb
This fixes an issue with the notes not properly being displayed for each feedback message and I incorrectly attached the save status event to all buttons, not just the save status buttons.
- Add a note on the abuse reports page and refresh the page - you can continue to see the note.
> Fix bug with creating notes on abuse reports

- app/models/article.rb
- app/models/comment.rb
- app/models/user.rb
- app/queries/homepage/articles_query.rb
- app/services/moderator/manage_activity_and_roles.rb
- app/workers/comments/calculate_score_worker.rb
- spec/models/article_spec.rb
- spec/models/user_spec.rb
- spec/workers/comments/calculate_score_worker_spec.rb
These are several downstream functions to immediately make articles from spam-marked users inaccessible. Does not address all scenarios, but many.
- Related Issue https://github.com/forem/forem/issues/20452
- Closes #
> Add downstream score effects from spam role

- app/models/follow.rb
- app/models/notification.rb
- spec/models/follow_spec.rb
- spec/models/notification_spec.rb
- spec/workers/follows/send_email_notification_worker_spec.rb
Additional functionality to remove visibility of spam.
When the user is new, we delay follow notifications by an hour to give time to filter spam out as it is caught.
We also never send an email for followers with fewer than one badge (much higher bar for emailing now, this logic could further be modified)
- Related Issue https://github.com/forem/forem/issues/20452
- Closes #
> Delay and modify follow logic to remove spammers

- app/controllers/admin/pages_controller.rb
- app/controllers/api/v1/pages_controller.rb
- app/controllers/pages_controller.rb
- app/models/page.rb
- app/views/admin/pages/_form.html.erb
- db/migrate/20240111144401_add_css_to_pages.rb
- db/schema.rb
- spec/lib/data_update_scripts/add_css_to_pages_spec.rb
- spec/models/page_spec.rb
- spec/requests/api/v1/pages_spec.rb
Adds a new CSS page template, allowing the publishing of CSS files using the Pages model.
- Closes #20514
> Add CSS as pages template option

- app/models/follow.rb
- spec/models/follow_spec.rb
Follow notifications from new users are delayed (implemented in #20505) so that if the user is assigned `suspended` or `spam` role while the notifications hasn't beed send yet, the worker would be able to check the roles and avoid sending the notification. 
But the worker `Notifications::NewFollower::Send` was using `Follow#non_suspended` , and was not checking for `spam` role. This pr adds logic to prevent sending follow notifications from users with spam role.
- Closes #20510
> Avoid sending follow notifications from spammers

- config/field_test.yml
This is not adding any new tests, just elevating the current winner from the prior batch, but continuing to test these same results because they were not totally conclusive.
> Promote 20240104-variant-b test

- app/lib/constants/settings/user_experience.rb
- app/models/settings/user_experience.rb
- app/views/admin/settings/forms/_user_experience.html.erb
- app/views/layouts/application.html.erb
- config/locales/lib/en.yml
- config/locales/lib/fr.yml
- spec/requests/stories_index_spec.rb
This allows admin to flexibly (and dangerously) add HTML in the head and bottom of body tag to help certain campaigns, etc.
This closes the loop on certain requests which are hard to fulfill through other forms of configuration.
- Closes https://github.com/forem/forem/issues/20532
> Add HTML customization to admin

- app/models/comment.rb
- spec/models/comment_spec.rb
This feature conditionally scores and notifies users based on a few heuristics for low quality and spam which are related to features already in place.
It is a small adjustment to modify and build on certain existing patterns to dissuade some types of spam and low-quality comments.
- Related Issue https://github.com/forem/forem/issues/20452
- Closes #
> Adjust comment notification logic

- app/services/images/optimizer.rb
- spec/services/images/optimizer_spec.rb
This allows DEV admins to flip a feature flag which would allow us to use Cloudinary config _and_ Cloudflare, but prioritize Cloudflare when the source of the image is from the hosted S3 bucket (vs proxied 3rd party images).
- Closes https://github.com/forem/forem/issues/20538
> Allow configuration to conditionally prefer Cloudflare over Cloudinary

- app/controllers/pages_controller.rb
- app/models/page.rb
- config/routes.rb
- spec/requests/pages_spec.rb
This allows admins to create pages which conform to `.txt` format — similar to `robots.txt` but useful in other contexts. It does not interfere with other routes.
- Closes https://github.com/forem/forem/issues/20548
> Allow pages to render .txt requests

- app/controllers/pages_controller.rb
- app/controllers/stories_controller.rb
- app/validators/cross_model_slug_validator.rb
- config/locales/validators/en.yml
- config/locales/validators/fr.yml
- config/routes.rb
- spec/models/page_spec.rb
- spec/requests/pages_spec.rb
This feature allows admins to create pages which span multiple directories, via setting a slug which can accept `/` characters — unlike other top-level-slug models.
These routes come last, so will cede to other routes before they are used in the event of collision, but give admins flexibility to create "subpages".
These "subpages" could later be explicitly made to relate to one another if that functionality is relevant (i.e. a page "belonging to" another), but for now this strictly allows for this behavior to live at the path request level and not be tied to other site functionality.
- Closes https://github.com/forem/forem/issues/20454
> Allow pages to have subdirectories

- app/models/articles/feeds.rb
- config/feed-variants/20240126-variant-a.json
- config/feed-variants/20240126-variant-b.json
- config/feed-variants/20240126-variant-c.json
- config/field_test.yml
Add new field tests, testing more of a random factor building off of the most recent winner, to help the same content not stick to the top for too long.
> Add new feed experiment for Jan 26

- app/views/admin/feedback_messages/_feedback_message.html.erb
Feedback Messages page errored when a note had not author
> Add in safe navigation for note author

- app/workers/audience_segment_refresh_all_worker.rb
- spec/workers/audience_segment_refresh_all_worker_spec.rb
This fixes an args issue where the arguments do not match with `perform_bulk` properly.
- Closes https://github.com/forem/forem/issues/20575
> Fix AudienceSegmentRefreshAllWorker args issue

- cypress/e2e/seededFlows/articleFlows/followOrganization.spec.js
- cypress/e2e/seededFlows/moderationFlows/adjustPostTags.spec.js
- cypress/e2e/seededFlows/profileFlows/profileUserActionsMenu.spec.js
As I am going through implementing `pnpm` , I've decided to tackle some of these errors.
> Fix flaky cypress specs

- app/models/articles/feeds.rb
- app/workers/audience_segment_refresh_all_worker.rb
- config/feed-variants/20240205-variant-a.json
- config/feed-variants/20240205-variant-b.json
- config/feed-variants/20240205-variant-c.json
- config/field_test.yml
- spec/services/articles/feeds_spec.rb
This adds new feed a/b tests for the week of Feb 5.
Also made an adjustment allowing one hardcoded value to be optionally set by ENV var, which by default won't change any existing behavior.
> New a/b test for Feb 5 (and add a variable too a hardcoded value)

- app/workers/audience_segment_refresh_all_worker.rb
- config/field_test.yml
The last PR was valid from a code perspective and didn't break but had the wrong date listed in the config
- Related Issue https://github.com/forem/forem/pull/20588
- Closes #
> Fix fieldtest date typo

- app/assets/stylesheets/onboarding.scss
This fixes the image width when using the new functionality on the newsletter opt-in step.
> Fix image width on newsletter opt-in

- app/services/badges/award_first_post.rb
- spec/services/badges/award_first_post_spec.rb
Adding this here related to the new "first post badge" — we _may_ want to limit this to score at least zero — which could avoid rewarding potential spam or anything that has been marked by mods even if there has not been a full-on spam designation.
Maybe we just want to reward it anyway? But I think this could be another safe filter. Popped this up for discussion rather than slowing down the other PR.
- Related Issue https://github.com/forem/forem/pull/20600
- Closes #
> [Up for discussion] Ensure at least 0 score for new badge award

- app/controllers/application_controller.rb
- app/controllers/application_metal_controller.rb
Quick bug fix: This method is called in helpers and needs to be made available there.
- Related Issue https://github.com/forem/forem/pull/20562
- Closes #
> Add client geo to helper method

- .github/workflows/ci.yml
I'm hoping this action update will help alleviate upload issues. This is the first time in a while this action received an update.
n/a
> Update to codecov-action@v4

- app/services/badges/award_first_post.rb
- spec/services/badges/award_first_post_spec.rb
- Update the name of the first post badge to match what was created by the community team.
- Related Issue #20558
> Update first post badge name

- app/assets/stylesheets/billboards.scss
- app/controllers/api/v1/billboards_controller.rb
- app/javascript/packs/admin/billboards.jsx
- app/javascript/packs/articlePage.jsx
- app/javascript/packs/billboard.js
- app/javascript/packs/billboardAfterRenderActions.js
- app/javascript/packs/homePage.jsx
- app/javascript/utilities/__tests__/billboardInteractivity.test.js
- app/javascript/utilities/billboardInteractivity.jsx
- app/models/billboard.rb
- app/views/articles/show.html.erb
- app/views/shared/_billboard.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- db/migrate/20240212142953_add_special_behavior_to_billboards.rb
- db/schema.rb
- spec/requests/api/v1/billboards_spec.rb
- spec/requests/billboards_spec.rb
This adds a new billboard on the post page which can be "fixed" to the bottom and has an "X" for close-out.
This has new optional functionality called "special behavior" where the billboard does not show up until the user scrolls past the post to the comment section. This field would allow for other special behavior added later.
- Closes https://github.com/forem/forem/issues/20619
> Add billboard for bottom of page with allowance to delay until after reading is finished.

- app/javascript/packs/billboardAfterRenderActions.js
Small tweak to the behavior here which should better reflect the intentions of the behavior. Right now when comments are too large it changes the behavior of the `intersectionObersever` in unintended ways.
Not strictly a bug just a change to better reflect the expected point of intersection.
- Related Issue https://github.com/forem/forem/pull/20616
> Use new_comment as the intersection object for delayed billboard

- app/assets/javascripts/initializers/initializeBillboardVisibility.js
- app/controllers/billboard_events_controller.rb
- app/javascript/onboarding/Onboarding.jsx
- app/javascript/onboarding/__tests__/Onboarding.test.jsx
- app/javascript/packs/billboardAfterRenderActions.js
- app/models/billboard_event.rb
- spec/models/billboard_event_spec.rb
- spec/requests/billboard_events_spec.rb
This stores locally when a billboard was clicked and attributes the most recent one to a sign up during onboarding for newly registered users.
- Closes  https://github.com/forem/forem/issues/20628
> Record billboard signup conversions

- app/models/articles/feeds.rb
- config/feed-variants/20240214-variant-a.json
- config/feed-variants/20240214-variant-b.json
- config/feed-variants/20240214-variant-c.json
- config/field_test.yml
New a/b test makes some small tweaks to config, generally lessening "randomness" from last one.
> New a/b tests for Feb 14

- config/field_test.yml
As we have a clear front runner in this test we want to tweak it so it gets more weight to further confirm before moving to next test.
- Related Issue https://github.com/forem/forem/pull/20632
> Tweak field test weights

- app/models/settings/user_experience.rb
- app/views/admin/settings/forms/_user_experience.html.erb
- app/views/layouts/application.html.erb
- Closes https://github.com/forem/forem/issues/20642
> Make mobile runtime banner optional

- app/controllers/billboard_events_controller.rb
- spec/requests/billboard_events_spec.rb
Slight modification to value of a signup based on observation of relative importance: Giving more credit to the signup conversion in the scoring vs click.
- Related Issue https://github.com/forem/forem/pull/20629
> Change value of signup in success score

- app/assets/stylesheets/billboards.scss
- app/views/devise/registrations/_registration_form.html.erb
This is a quick fix for an issue where if you click over to the registration page then click back you get some messed up styles.
I also made an adjustment so if you click back from this context the popover billboard does not come back, as it is likely the user does not want to see it again in this context.
This is a hot fix on top of the existing hack, there is definitely a better long-term solution.
- Closes https://github.com/forem/forem/issues/20657
> [Hot fix] Fix style bugs with registration page

- app/assets/stylesheets/billboards.scss
- app/views/layouts/_main_nav.html.erb
Super tiny fix where we don't show the proper nav links sometimes because we cache irregardless of sign in status.
> [Hotfix] Fix cache key

- app/models/async_info.rb
Small tweak to ensure the conversion tracking works as expected.
- Related Issue https://github.com/forem/forem/pull/20664
> Unwrap user before passing to field_test

- app/assets/javascripts/initializers/initializeBodyData.js
- app/controllers/application_controller.rb
- app/controllers/async_info_controller.rb
- app/javascript/onboarding/components/FollowTags.jsx
- app/javascript/onboarding/components/__tests__/FollowTags.test.jsx
- app/lib/constants/settings/general.rb
- app/models/settings/general.rb
- app/views/admin/settings/forms/_onboarding.html.erb
- app/views/onboardings/_newsletter.html.erb
- config/locales/lib/en.yml
- config/locales/lib/fr.yml
- spec/requests/async_info_spec.rb
This provides new admin settings for more fine-grained control over email opt-in defaults for more precision in UX/compliance strategies.
- Closes [ben/email-opt-in-config](https://github.com/forem/forem/issues/20662)
> Add configuration for admins to specify compliant email strategies

- spec/models/mention_spec.rb
This pull request improves the test coverage for the `Mention` model. The existing specs were not covering the model validations, associations and callbacks.
I haven't found any addressing this issue.
Simply run the CI.
> Improve Test Coverage for the `Mention` Model

- app/assets/javascripts/initializers/initializeBillboardVisibility.js
- app/javascript/onboarding/Onboarding.jsx
- app/javascript/onboarding/__tests__/Onboarding.test.jsx
- app/javascript/packs/billboardAfterRenderActions.js
We had behavior in place to redirect people to the page they originally came from after onboarding so they can follow through on their original intended action (perhaps commenting on a post) but this behavior was removed — I believe unintentionally.
This takes a different approach by redirecting if the user came from a billboard CTA which originally prompted them to sign up. We are now tracking that and can use it to ultimately redirect.
- address some of https://github.com/forem/forem/issues/20661
> Go to page you came from after onboarding when coming through billboard

- app/views/articles/show.html.erb
We include extra content in the signed-out page which is only relevant for signed-in contexts. Inclusion here can result in text erroneously being selected by search engines as important content on the page (though this would be a mistake on their part if this happens — this could help ensure it does not). 
- Closes https://github.com/forem/forem/issues/20685
> Remove non-contextual content from signed-out version of page

- app/controllers/moderations_controller.rb
- spec/requests/moderations_spec.rb
Exclude articles from users with suspended or spam role from `/mod`
- Closes #20649
> Exclude articles from bad actors on /mod

- cypress/e2e/seededFlows/articleFlows/commentModerationTools.spec.js
- cypress/e2e/seededFlows/articleFlows/postModerationTools.spec.js
- spec/queries/comments/tree_spec.rb
- spec/system/ahoy/tracking_create_account_spec.rb
> Disable flaky specs

- app/queries/users/suggest_prominent.rb
This is a follow-up to functionality which was supposed to improve performance but didn't improve things. But this should further simplify and help that happen.
- Related Issue https://github.com/forem/forem/pull/20682
> Fast follow on follow suggestion efficiency

- app/queries/organizations/suggest_prominent.rb
I forgot to apply this adjustment as well in this optimization shipped just now.
https://github.com/forem/forem/pull/20709
So applying the same tweak here for efficient production query.
- Related Issue https://github.com/forem/forem/pull/20709
- Closes #
> Apply efficiency adjustment to orgs as well

- app/controllers/api/v1/billboards_controller.rb
- app/javascript/__tests__/billboard.test.js
- app/javascript/packs/billboard.js
- app/javascript/utilities/__tests__/billboardInteractivity.test.js
- app/javascript/utilities/billboardInteractivity.jsx
- app/views/shared/_billboard.html.erb
- db/migrate/20240301160047_add_dismissal_sku_to_billboards.rb
- db/schema.rb
- spec/requests/api/v1/billboards_spec.rb
This adds the ability to mark a group of billboards with a certain "dismissal sku" so when someone dismisses one, they will all follow that logic.
- Closes https://github.com/forem/forem/issues/20717
> Add optional client-side dismissal SKU for closable billboards

- app/assets/stylesheets/billboards.scss
- app/javascript/utilities/billboardInteractivity.jsx
Small issue fixing whether contextually this menu should open down or up depending on where it is relative to window.
> [Style patch] Adjust menu popup behavior contextually

- cypress/e2e/seededFlows/adminFlows/articles/privilegedReactions.spec.js
- cypress/e2e/seededFlows/articleFlows/commentModerationTools.spec.js
> Fix flaky E2E specs

- app/javascript/onboarding/components/FollowTags.jsx
- app/javascript/onboarding/components/__tests__/FollowTags.test.jsx
> Fix dataset check in JS

- .github/workflows/create-cache.yml
This is necessary now because we use merge queue. 
The problem is that our `CI` does not run on main branch at all. Because build caches can only be copied from the default branch, we aren't actually using the caching feature effectively.
n/a
> [CI] Add cache creator

- app/javascript/__tests__/billboard.test.js
- app/javascript/articles/Feed.jsx
- app/javascript/packs/billboard.js
- app/javascript/utilities/__tests__/billboardInteractivity.test.js
- app/javascript/utilities/billboardInteractivity.jsx
- app/views/shared/_billboard.html.erb
- spec/requests/billboards_spec.rb
- Related Issue https://github.com/forem/forem/pull/20716
- Closes #
> Allow feed billboards to be dismissible if dismissal_sku is present

- app/javascript/packs/billboard.js
- app/mailers/digest_mailer.rb
- app/services/email_digest_article_collector.rb
- app/views/layouts/mailer.html.erb
- app/views/mailers/digest_mailer/digest_email.html.erb
- config/field_test.yml
- config/initializers/ahoy_email.rb
- spec/mailers/devise_mailer_spec.rb
- spec/mailers/digest_mailer_spec.rb
- spec/mailers/notify_mailer_spec.rb
This is designed to be a first pass to address some concerns around Digest design and functionality.
- Implements an A/B test for titles
- Enables recording of which emails get a clickthrough (not view tracking which has different privacy implications)
- Adjusts billboard behavior for Digest context
- Makes some basic adjustments to algorithm that determines which articles are selected
- Adjusts design to be more in-line with other design elements of the site and to be more aesthetically pleasing across desktop and mobile while also more compatible with different email clients
- Closes #
Here are the new looks:
> Add new simple a/b test for Digest subject and adjust config and design details

- app/views/layouts/mailer.html.erb
- config/initializers/ahoy_email.rb
- config/routes.rb
We had to roll back this deployment
https://github.com/forem/forem/pull/20754
This will allow us to roll forward in a state where we can turn this on in staging envs to better test how this will work.
It will default to false in production but we can turn it on to experiment.
- Related Issue https://github.com/forem/forem/pull/20754
- Closes #
> Make ahoy_email default_options[:click] an env var

- app/views/layouts/mailer.html.erb
- app/views/mailers/digest_mailer/digest_email.html.erb
Small tweaks to ensure the Digest emails look good on all devices.
- Related Issue [#](https://github.com/forem/forem/issues/20755)
> Small digest style tweaks

- app/javascript/packs/followButtons.js
- app/views/podcast_episodes/index.html.erb
- app/views/podcast_episodes/show.html.erb
- config/locales/views/podcasts/en.yml
- config/locales/views/podcasts/fr.yml
Quick optimization here. We do not need to fetch here.
- Closes https://github.com/forem/forem/issues/20760
> Early return from org follow check

- app/javascript/packs/billboard.js
Safe navigation required because `currentParams` is not always present.
- Related Issue https://github.com/forem/forem/pull/20754
> [Hotfix] Add safe navigation to billboard.js conditionals

- app/mailers/digest_mailer.rb
- app/services/email_digest_article_collector.rb
- app/views/mailers/digest_mailer/digest_email.html.erb
- config/field_test.yml
- spec/mailers/digest_mailer_spec.rb
This closes the subject test and names `just_first_title_and_dev_digest` as the winner, with about 7.5% margin win. It's more minimal but includes the Digest call-out.
This introduces a new test on the number of results we display per email.
- Closes #
> Finish Digest subject test and start count test

- app/services/email_digest_article_collector.rb
- config/field_test.yml
This gem seems to infer integers and strings wrong when passing just a number here. This is a quick fix to make sure results are tracked properly.
- Related Issue https://github.com/forem/forem/pull/20773
- Closes #
> Quick fix: Ensure string in field test

- app/views/pages/show.en.html.erb
Quick fix. We were not using the page's custom social image as we should be.
> Use page social_image_url if present

- app/javascript/readingList/readingList.jsx
I am very sorry -- I somehow had a typo [in my previous PR](https://github.com/forem/forem/pull/20762). Without it, #2 point there is not addressed. This is really embarrassing 😞
> typo fix on PR #20762

- app/mailers/devise_mailer.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
This changes the wording on the confirmation email to reference the Forem Community and the user's name to make the email less generic and hopefully get through more spam filters.
> Update Confirmation Email Wording

- app/services/email_digest_article_collector.rb
- config/field_test.yml
Declare winner from recent test
> Declare winner in digest count test

- .github/workflows/create-cache.yml
Create-cache is taking `package.json` from `node_module` confusing the cache retrieval process.
n/a
> [CI] Re-arrange create-cache.yml

- app/views/admin/articles/_article_item.html.erb
- config/initializers/ahoy_email.rb
- config/locales/views/moderations/en.yml
- config/locales/views/moderations/fr.yml
This is a follow up to provide additional configuration needed to for click recognition in our ahoy email use.
Also added a related admin form element which had been missing.
- Related Issue https://github.com/forem/forem/issues/20808
- Closes #
> Digest tracking config

- .github/workflows/ci.yml
- .github/workflows/create-cache.yml
- spec/system/ahoy/tracking_create_account_spec.rb
> [CI] Resolves compiled-assets caching issue

- config/initializers/ahoy_email.rb
Hopefully the final config adjustment in a series of adjustments which could have been avoided if I better understood the functionality in the first place and read more carefully.
- Related Issue https://github.com/forem/forem/pull/20834
- Closes #
> (Hopefully) final ahoy email tweak

- .github/workflows/ci.yml
- .github/workflows/create-cache.yml
The actual solution to the problem is that the cache generated on main branch was not for the `test` environment
n/a
> [CI] Resolves compiled-assets caching issue (2)

- app/views/dashboards/_actions_mobile.html.erb
When you go to https://dev.to/dashboard on a smartphone, you can see in the menu the option "Listings".
[forem/app/views/dashboards/_actions_mobile.html.erb](https://github.com/forem/forem/blob/20f57ab0bec663e2e4b3470f644ee9f253e2b61f/app/views/dashboards/_actions_mobile.html.erb#L10)
- Related Issue #20817
- Closes #20817
- Go to http://localhost:3000/dashboard
- Activate mobile view or directly see the page with your smartphone
- Click on the select menu
- You can see the "Listings" option
- If you click on it, you'll get an error
have not …
> Remove listings option from views/dashboards/_actions_mobile.html

- app/javascript/packs/admin/billboards.jsx
- app/mailers/digest_mailer.rb
- app/models/billboard.rb
- app/views/mailers/digest_mailer/digest_email.html.erb
- app/workers/emails/send_user_digest_worker.rb
- spec/mailers/digest_mailer_spec.rb
- spec/mailers/previews/digest_mailer_preview.rb
- spec/workers/emails/send_user_digest_worker_spec.rb
This adds two new billboard locations, `digest_first` and `digest_second` which go above and below the digest articles.
These have the ability to target on user tags, but they do not (yet) track impressions or clicks — as that will require some new context for digest mailers.
> Add billboards to digest emails

- app/javascript/packs/searchParams.js
- app/views/layouts/application.html.erb
- package.json
- yarn.lock
This does not add any live functionality.
If Algolia keys are in place (as part of an optional enhancement for search), then we display some basic console logs that it is live, but it is a WIP.
- Related Issue https://github.com/forem/forem/issues/20833
> Add Algoliasearch js client

- app/views/dashboards/_dashboard_article_row.html.erb
We're getting `undefined method year for nil` — not totally sure of root cause, but this should fix the error.
- Closes https://github.com/forem/forem/issues/20874
> Add safe navigation to article.displayable_published_at.year

- app/views/mailers/digest_mailer/digest_email.html.erb
- config/field_test.yml
We have a winner based on click-rate.
- Closes #
> Declare winner in digest email subheader test

- app/mailers/digest_mailer.rb
- app/views/mailers/digest_mailer/digest_email.html.erb
- config/field_test.yml
This adds new field tests for Digest mailer, building on the prior winner.
This tests various scenarios of modifying the top content — primarily affecting the "preview" of the email body as shown in many email apps.
We test with/without the first header, and variants with first name only (naively guessed, but should be fine) and a wave emoji as well.
> Add new headers a/b test for digest mailer

- lib/tasks/fetch.rake
We recently changed the default Digest schedule, but DEV does not use the same cron — it uses a rake task. So this adjusts that logic.
- Related Issue https://github.com/forem/forem/pull/20865
> Change digest rake to new schedule

- app/assets/stylesheets/views/profile.scss
- app/controllers/admin/badges_controller.rb
- app/models/badge.rb
- app/models/badge_achievement.rb
- app/views/admin/badges/edit.html.erb
- app/views/admin/badges/new.html.erb
- app/views/users/_badges_area.html.erb
- config/locales/views/misc/en.yml
- config/locales/views/misc/fr.yml
- db/migrate/20240419201108_add_allow_multiple_awards_to_badges.rb
- db/schema.rb
- spec/factories/badges.rb
This allows badges to be awarded multiple times, controlled by a new setting for each badge. Badges are grouped on a user's profile, and shown with an indicator showing how many times they've been awarded the badge.
- Closes #20875
> Allow some badges to be awarded multiple times

- app/models/concerns/algolia_searchable/searchable_tag.rb
- app/models/tag.rb
- spec/models/tag_spec.rb
Add options to turn on Algolia to Tag
https://github.com/forem/forem/issues/20833
n/a
> Add AlgoliaSearchable to Tag

- app/models/concerns/algolia_searchable/searchable_podcast_episode.rb
- app/models/podcast_episode.rb
- spec/models/podcast_episode_spec.rb
Add options to turn on Algolia to Podcast
https://github.com/forem/forem/issues/20833
n/a
> Add AlgoliaSearchable to Podcast

- app/mailers/digest_mailer.rb
- app/views/mailers/digest_mailer/digest_email.html.erb
- config/field_test.yml
Select winner from Digest a/b test
> Pick winner in header field test

- app/mailers/digest_mailer.rb
- app/views/mailers/digest_mailer/digest_email.html.erb
- config/field_test.yml
New field test to add new elements to the list (user name/image, and/or tags) and to see if a bordered card is more effective than plain.
- Closes #
> Add field test for Digest article list design

- app/services/email_digest_article_collector.rb
This needs to be added to the select for this a/b test to fully work.
- Related Issue https://github.com/forem/forem/pull/20912
> Include cached user in select

- app/views/mailers/notify_mailer/_email_header.html.erb
- app/views/mailers/notify_mailer/new_follower_email.html.erb
- app/views/mailers/notify_mailer/new_reply_email.html.erb
- A new style for the new follower email.
- I've made the new header a partial for re-use in other email templates
> Update style for new follower email

- app/controllers/admin/tools_controller.rb
`:last_commented_at` -> `:last_comment_at`
- Closes #19037
> Fix Article Cache Buster

- .vscode/settings.json
- app/assets/stylesheets/config/_generator.scss
- app/controllers/stories_controller.rb
- app/views/users/_badges_area.html.erb
- app/views/users/_sidebar.html.erb
- app/views/users/show.html.erb
- cypress/e2e/seededFlows/profileFlows/userProfile.spec.js
- package.json
- spec/support/seeds/seeds_e2e.rb
- spec/views/users/main_feed_spec.rb
- yarn.lock
- New display location on a user's profile for more than 4 badges
- When 4 or fewer badges, keep the old location but display it first on the left side panel
> New badge display logic on user's profile

- app/views/users/show.html.erb
Small issue that causes erroneous overflow on profile page in mobile
- Related Issue https://github.com/forem/forem/pull/20944
> [Quick patch] Fix margin on profile page

- app/javascript/packs/searchParams.js
- app/models/concerns/algolia_searchable/searchable_article.rb
- app/views/stories/articles_search/_nav_menu.html.erb
Tweak to make search more relevant, and remove podcasts from searchable as that is not something we're leaning in to.
- Related Issue https://github.com/forem/forem/pull/20909
> Small search index modification

- app/javascript/packs/searchParams.js
Ongoing search index tweaking
- Related Issue https://github.com/forem/forem/pull/20947
> Further search tweaking

- app/assets/javascripts/initializers/initializeCommentsPage.js.erb
- app/javascript/packs/initializers/initializeCommentPreview.js
I can't preview a comment that I wrote before publishing it. There is nothing happen when I click the button.
- Related Issue #20389
- Closes #20389
- Closes PR #20394
1. Go to a post.
2. Go to a comment and click reply.
3. Write a reply.
4. Click "preview" button.
> Fix Unable to Preview a Reply for a Comment Before Publishing it

- app/models/concerns/algolia_searchable/searchable_article.rb
Addition of a missing field in algolia indexing
- Related Issue #20909
> Add reaction categories to searchable

- app/javascript/packs/searchParams.js
On the landing page Algolia re-triggers over and over again. This is likely not the permanent fix, but a patch.
- Closes https://github.com/forem/forem/issues/20961
> Fix Algolia infinite loop

- app/javascript/Search/SearchForm.jsx
Prior fix didn't actually work in prod. This should hopefully do it.
- Related Issue https://github.com/forem/forem/pull/20999
> Actual proper fix for Algolia loop

- spec/requests/user/user_profile_spec.rb
Added a spec that makes sure that comments with negative score are displayed in users profile.
- Related Issue  #20905
> Spec for articles in the users profile

- app/models/user.rb
- spec/models/user_spec.rb
Removed user `payment_pointer` validation and related code
- Closes #20401
> Remove user payment_pointer validation and related code

- app/lib/redcarpet/render/html_rouge.rb
- app/models/media_store.rb
- app/uploaders/article_image_uploader.rb
- db/migrate/20240523132708_create_media_stores.rb
- db/schema.rb
- spec/factories/media_stores.rb
- spec/models/media_store_spec.rb
- spec/services/markdown_processor/parser_spec.rb
This adds a `MediaStore` for serving images when they are stored. This doesn't yet implement automatic storing. There is also the opportunity to use different media types, so this could be a video, audio store as well.
This just stores a reference to a URL and an original url. It is not explicitly attached to an uploader.
- Closes https://github.com/forem/forem/issues/21069
> Add Media Store

- app/services/images/optimizer.rb
- spec/services/images/optimizer_spec.rb
Currently if a Cloudflare image is passed already prefixed, it will be treated as a non-prefixed domain. This fixes that and ensures it doesn't get double-prefixed.
> Do not nest cloudflare image results

- app/queries/billboards/filtered_ads_query.rb
- spec/queries/billboards/filtered_ads_query_spec.rb
This adjusts and simplifies logic around whether "promoted" billboards are shown based on settings. This removes some custom functionality which isn't really relevant anymore.
> Simplify adjacent billboard logic

- app/javascript/onboarding/Onboarding.jsx
- app/javascript/onboarding/components/FollowTags.jsx
Adds default tag and reaction behavior for new signups to help them get more relevant feeds if they are zipping through.
> Add tweaks to make onboarding tags more relevant

- app/assets/stylesheets/billboards.scss
- app/assets/stylesheets/widgets.scss
- app/views/admin/billboards/_form.html.erb
- app/views/shared/_billboard.html.erb
- app/views/shared/_billboard_header.html.erb
- spec/requests/billboards_spec.rb
- spec/requests/stories_index_spec.rb
Adjust HTML/CSS to user the `-bb` suffix.
> Refactor billboard styles

- app/controllers/admin/organizations_controller.rb
Organizations can be ordered by name with search (current functionality), but the default should be showing recent. Currently it defaults to name, which is wrong.
> Tweak org ordering in admin

- app/controllers/stories_controller.rb
- app/views/organizations/_header.html.erb
- app/views/users/show.html.erb
It seems like there could be a race condition with the profile existing for some new users?
- Closes https://github.com/forem/forem/issues/21099
> Add safe nav to profile

- app/assets/stylesheets/onboarding.scss
- app/javascript/onboarding/components/EmailPreferencesForm.jsx
- app/javascript/onboarding/components/__tests__/EmailPreferencesForm.test.jsx
This adds a final check for emails if the user does not opt in during onboarding.
- Closes https://github.com/forem/forem/issues/21108
> Add final email CTA to onboarding

- app/views/articles/stats.html.erb
Style patch
- Closes https://github.com/forem/forem/issues/21111
> Fix bottom margin on stats

- app/controllers/users/settings_controller.rb
- app/models/role.rb
- app/models/user.rb
- app/models/users/setting.rb
- app/policies/authorizer.rb
- app/views/users/_content_preferences.html.erb
- app/views/users/_extensions.html.erb
- db/migrate/20240603143820_add_content_preferences_to_users_settings.rb
- db/schema.rb
- spec/models/role_spec.rb
- spec/models/users/setting_spec.rb
This is an experimental feature where we add an "augmented" role. Users with this role will be able to modify their content preferences in plain english.
This functionality is experimental and will be just used internally at first.
- Related Issue https://github.com/forem/forem/issues/21112
> Add augmented content preferences and role

- app/services/email_digest_article_collector.rb
- app/workers/emails/send_user_digest_worker.rb
- spec/services/email_digest_article_collector_spec.rb
Now that we are looking back one day + 12 hours, it's _possible_ to get the same first article two days in a row. This accounts for that.
We are also going to now mark `should_receive_email?` as true if the last email has been clicked. This helps keep up the streak for openers, and removes any "off by one" problems we currently face.
> Adjust digest based on last_email_clicked logic

- config/feed-variants/20240604-variant-a.json
- config/feed-variants/20240604-variant-b.json
- config/feed-variants/20240604-variant-c.json
- config/field_test.yml
> Update feed field tests june 4

- app/decorators/user_decorator.rb
- Closes https://github.com/forem/forem/issues/21117
> Safe nav on profile

- app/decorators/user_decorator.rb
- app/services/email_digest.rb
- lib/tasks/fetch.rake
DEV sends the Digest via a rake task. This hardcode splits into multiple calls so can run in parallel without otherwise changing set up.
> Split up tasks to send DEV Digest

- app/controllers/ahoy/email_clicks_controller.rb
- app/javascript/packs/baseTracking.js
- app/models/billboard_event.rb
- app/workers/emails/send_user_digest_worker.rb
- config/initializers/ahoy_email.rb
- spec/requests/ahoy/email_clicks_spec.rb
- spec/workers/emails/send_user_digest_worker_spec.rb
> Track billboard impressions and clicks in Digest

- app/services/email_digest_article_collector.rb
- spec/services/email_digest_article_collector_spec.rb
We only run the Digest Email check daily so it generally shouldn't send more than once, but there could be edge cases where this gets called. This adds a hard check here to not send if over 18 hours ago (to allow grace period of different times of day)
> Fix possible sending of Digest twice in day

- app/controllers/ahoy/email_clicks_controller.rb
- app/models/feed_event.rb
- spec/requests/ahoy/email_clicks_spec.rb
This adds feed event recordings to digest emails to help create a tighter feedback loop to bubble good stuff up in the top of Digest.
> Record feed events for email

- app/uploaders/base_uploader.rb
This rescues and logs instead of erroring out, as this is a pretty rare case and this will help us debug.
- Related Issue https://github.com/forem/forem/issues/21128
> Catch format problem edge cases with exif manipulation step

- app/models/billboard.rb
Follows current standards to add a "new-only" bucket.
- Closes https://github.com/forem/forem/issues/21130
> Add new-only bucket for billboards

- app/models/user.rb
- app/services/email_digest_article_collector.rb
- config/field_test.yml
- spec/services/email_digest_article_collector_spec.rb
This adds additional logic to make sure that fallback recommendations for digest subscribers who do not follow anything are as relevant as possible.
> Adjust EmailDigestArticleCollector to provide more relevant fallback articles

- app/views/layouts/application.html.erb
Make home page load faster by prefetching key async resources upfront.
> Prefetch key resources on home page

- app/services/email_digest_article_collector.rb
- spec/services/email_digest_article_collector_spec.rb
- spec/workers/emails/send_user_digest_worker_spec.rb
Small tweak to only send the more follow-centric picker if the user follows at least 4 tags.
> Adjust EmailDigestArticleCollector query picker logic

- app/liquid_tags/card_tag.rb
- app/views/liquids/_card.html.erb
- spec/liquid_tags/card_tag_spec.rb
Initial beta functionality for a "card" embed. This does not include it in any instructions for now.
- Related Issue https://github.com/forem/forem/issues/21138
> Add card embed (beta)

- app/assets/stylesheets/billboards.scss
Quick style patch on popover-billboard width for some window widths
> Patch popover-billboard style

- app/services/email_digest_article_collector.rb
- config/feed-variants/20240616-variant-ajson
- config/feed-variants/20240616-variant-b.json
- config/feed-variants/20240616-variant-c.json
- config/field_test.yml
New config testing for home feed
> New feed test june 16

- app/services/email_digest_article_collector.rb
- config/field_test.yml
New A/B tests, further testing more `feed_success_score` weight
> New digest article ordering

- db/migrate/20240617141922_add_organic_page_views_past_month_index.rb
- db/schema.rb
This should improve one of our most time-consuming queries.
> Add index for organic_page_views_past_month_count

- app/models/user.rb
- app/services/email_digest.rb
Adds rescue here in case there is an internal problem as to not break the whole execution
> Add rescue in send_periodic_digest_email

- app/services/email_digest_article_collector.rb
This finds relevant articles for digest if the other methods result in too few.
> Article collector fallback

- app/queries/tags/suggested_for_onboarding.rb
Tags were previously not ordered in any cohesive way
> Order onboarding tags by hotness

- app/models/settings/general.rb
- app/views/layouts/_logo.html.erb
Adds the ability to add an aspect ratio to reduce layout shift.
This is only available in console for now and should be set automatically in future vs directly by admin.
> Add aspect ratio config to logo

- app/controllers/sidebars_controller.rb
- app/models/ab_experiment/goal_conversion_handler.rb
- app/models/feed_event.rb
- app/services/email_digest_article_collector.rb
- config/field_test.yml
- spec/models/ab_experiment/goal_conversion_handler_spec.rb
- spec/models/feed_event_spec.rb
> Add new email feed event goal and new test

- config/feed-variants/20240701-variant-a.json
- config/feed-variants/20240701-variant-b.json
- config/feed-variants/20240701-variant-c.json
- config/field_test.yml
New tweaks to feed field tests.
> New feed experiment

- app/javascript/Search/SearchForm.jsx
- app/models/concerns/algolia_searchable/searchable_tag.rb
> Add debounce to search

- app/javascript/article-form/components/__tests__/Form.test.jsx
- app/javascript/hooks/useTagsField.js
- app/javascript/listings/__tests__/ListingTagsField.test.jsx
- app/models/concerns/algolia_searchable/searchable_tag.rb
Makes algolia an option for editor tag search if present
> Add algolia to tag search

- app/javascript/Search/SearchForm.jsx
- app/javascript/utilities/debounceAction.js
- app/models/concerns/algolia_searchable/searchable_tag.rb
- app/models/concerns/algolia_searchable/searchable_user.rb
Adds a new replica for algolia ordering, and some other tweaks
> Algolia index tweaks

- app/controllers/incoming_webhooks/stripe_events_controller.rb
- app/controllers/stripe_subscriptions_controller.rb
- app/lib/constants/settings/general.rb
- app/models/role.rb
- app/models/settings/general.rb
- app/models/user.rb
- app/policies/authorizer.rb
- app/views/admin/settings/forms/_monetization.html.erb
- app/views/layouts/application.html.erb
- app/views/users/_extensions.html.erb
- config/routes.rb
- spec/models/role_spec.rb
- spec/requests/admin/configs_spec.rb
- spec/requests/incoming_webhooks/stripe/stripe_events_spec.rb
- spec/requests/stripe_subscriptions_spec.rb
A while ago we deprecated the payment pointer as that technology did not advance past its own beta, this closes the loop on some of the removal there.
It also updates some of the Stripe functionality, including a webhook receiver — not yet pointing to anything with downstream effects of consequence. The incoming webhook functionality and related code here will have to be tested in production, but could allow forems some subscription management options.
- Related Issue https://github.com/forem/forem/issues/20401
> Remove deprecated payment pointer and update other payment config/functionality

- app/controllers/sidebars_controller.rb
- app/models/async_info.rb
- app/services/email_digest_article_collector.rb
- config/field_test.yml
This closes and picks final winners for some field tests which seem to have reached local maxima.
> Finalize some field tests

- app/controllers/incoming_webhooks/stripe_events_controller.rb
Adds logging for stripe webhooks
> Add stripe logging

- app/controllers/incoming_webhooks/stripe_events_controller.rb
- spec/requests/incoming_webhooks/stripe/stripe_events_spec.rb
Modification to best stripe event to listen to for this.
> Adjust stripe event listener

- app/javascript/Search/SearchForm.jsx
- app/javascript/packs/Search.jsx
- app/views/layouts/_top_bar.html.erb
Adds new functionality if algolia present
> Add algolia recommendations

- app/models/billboard.rb
- app/views/layouts/_footer.html.erb
- spec/requests/stories_index_spec.rb
New billboard placement area within footer above current links/etc.
> Add footer billboard

- app/views/layouts/_top_bar.html.erb
- app/views/layouts/application.html.erb
Fix the cache key such that it accounts for `@article.present?`
> Fix top bar cache

- config/feed-variants/20240805-variant-a.json
- config/feed-variants/20240805-variant-b.json
- config/feed-variants/20240805-variant-c.json
- config/field_test.yml
> New feed experiment for August 5

- app/controllers/admin/users_controller.rb
- app/models/article.rb
- app/models/user.rb
- app/views/admin/users/show/emails/_verification.html.erb
- app/views/admin/users/show/profile/_actions.html.erb
- app/views/admin/users/show/profile/_status.html.erb
- app/views/admin/users/show/profile/actions/_change_max_score.html.erb
- config/locales/controllers/admin/en.yml
- config/locales/controllers/admin/fr.yml
- config/locales/views/admin/en.yml
- config/locales/views/admin/fr.yml
- config/routes/admin.rb
- db/migrate/20240814184735_add_max_score_to_users.rb
- db/schema.rb
- spec/models/article_spec.rb
- spec/requests/admin/users/users_change_max_score_spec.rb
In order to fight abuse in a more nuanced way, this is a lever that can be pulled.
> Allow admins to set max score for some users

- app/controllers/stripe_subscriptions_controller.rb
- spec/requests/stripe_subscriptions_spec.rb
Require auth for subscription path
> Require authentication for subscription

- app/controllers/billboard_events_controller.rb
- app/controllers/incoming_webhooks/stripe_events_controller.rb
- app/models/billboard_event.rb
- spec/models/billboard_event_spec.rb
- spec/requests/billboard_events_spec.rb
- spec/requests/incoming_webhooks/stripe/stripe_events_spec.rb
Adds a conversion event when subscription is triggered
> Add billboard conversion event

- app/views/onboardings/_task_card.html.erb
- config/locales/views/misc/en.yml
- config/locales/views/misc/fr.yml
This adds the option to add a call-out for subscription in the task card. This could be customized for other subscriptions in future, for now it's coded to the DEV one.
> Add subscription option to task card

- app/models/user.rb
Fix occasional nil error
- Closes https://github.com/forem/forem/issues/21224
> Check for nil list edge case

- app/controllers/incoming_webhooks/stripe_events_controller.rb
- app/views/users/show.html.erb
Adjustment to ensure profile updates more often without stale cache key in some cases.
> Update cache key for user profile

- app/services/authentication/authenticator.rb
Investigating auth edge cases
- Related issue: https://github.com/forem/forem/issues/21216
> Add logging and tweaks to auth

- app/lib/redcarpet/render/html_rouge.rb
- app/services/articles/enrich_image_attributes.rb
- app/services/content_renderer.rb
- app/services/html/parser.rb
- spec/services/markdown_processor/parser_spec.rb
Add MediaStore uploads to synchronous detail detection, used in billboards.
> Add media store to synchronous detail detection

- app/services/reaction_handler.rb
Rescue's database-level validation which would otherwise throw an exception on save. We don't need an exception here.
- Closes https://github.com/forem/forem/issues/21232
> Rescue RecordNotUnique for reactions handler

- app/models/user.rb
- app/services/authentication/providers/google_oauth2.rb
This rescues a low-level validation which we can logically move on from here. Also adjusts the way we store google oauth username
- Closes https://github.com/forem/forem/issues/21215
- Closes https://github.com/forem/forem/issues/21216
> Rescue ActiveRecord::RecordNotUnique for profile and oauth username

- app/controllers/admin/overview_controller.rb
- app/services/admin/charts_data.rb
- app/views/admin/overview/_analytics.html.erb
Adds a 90-day dropdown option to the analytics viewer in `/admin`.  Can serve as the basis for additional enhancements with more date range options.
- Closes https://github.com/forem/forem/issues/21156
> Add 90-day option to /admin analytics dropdown

- app/controllers/stripe_subscriptions_controller.rb
- spec/requests/stripe_subscriptions_spec.rb
Ability to set a special price for tag moderators.
> Add new Stripe code option

- app/controllers/stripe_subscriptions_controller.rb
- spec/requests/stripe_subscriptions_spec.rb
> Add terms to stripe

- app/controllers/incoming_webhooks/stripe_events_controller.rb
- app/controllers/stripe_subscriptions_controller.rb
- app/services/calculate_reaction_points.rb
- app/services/comments/calculate_score.rb
- config/routes.rb
- spec/requests/stripe_subscriptions_spec.rb
Adds route for cancellation of subscription, and also add some functionality for "benefit-of-the-doubt" base score in some cases.
> Add cancel subscription functionality and points tweaks

- app/assets/javascripts/utilities/buildArticleHTML.js
- app/assets/javascripts/utilities/buildCommentHTML.js.erb
- app/assets/stylesheets/scaffolds.scss
- app/helpers/application_helper.rb
- app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
- app/javascript/articles/components/Meta.jsx
- app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
- app/views/articles/_single_story.html.erb
- app/views/comments/_comment.json.jbuilder
- app/views/layouts/application.html.erb
- app/views/stories/feeds/show.json.jbuilder
- spec/requests/user/user_show_spec.rb
Adds subscriber icon to feed by name, like it is on the posts.
> Add subscriber icon to feed cards

- app/assets/stylesheets/scaffolds.scss
> Fix style bug

- app/services/calculate_reaction_points.rb
Error in awarding reaction points, assuming user_id on reactable (User does not have user_id)
- Closes https://github.com/forem/forem/issues/21246
> Fix bug in reacting to user

- app/mailers/notify_mailer.rb
> Return email if blank

- app/services/billboard_event_rollup.rb
- spec/services/billboard_event_rollup_spec.rb
Temp statement timeout for this functionality to help ensure it finishes
> Add specific statement timeout for rollup

- app/javascript/packs/billboard.js
- app/views/layouts/application.html.erb
Skip billboard rendering here for internal nav, when it has already been shown/dismissed and is annoying to see again.
> Make fixed billboard not show up for internal nav

- app/controllers/billboard_events_controller.rb
Force integer even when using env var
> Make throttle time integer

- app/services/notifications/notifiable_action/send.rb
> Add distinct for followers query

- app/controllers/billboard_events_controller.rb
Additional throttling for billboard tabulation
> More throttling for billboard tabulating

- app/services/billboard_event_rollup.rb
- spec/services/billboard_event_rollup_spec.rb
Handle rollup in batches and extend timeout window to ensure these finish
> Do billboard rollup in batches

- app/services/billboard_event_rollup.rb
Putting these actions in transactions to ensure database actions work properly
> Wrap billboard rollups into transactions

- app/assets/javascripts/initializers/initializeBillboardVisibility.js
- app/javascript/packs/billboardAfterRenderActions.js
- app/views/shared/_billboard.html.erb
Interesection observer logic is not working as intended. Changed to basic timeout for delay logic.
> Fix delayed billboard logic

- app/models/billboard.rb
- spec/models/billboard_spec.rb
Add bb id param to better track success of billboards
> Add bb param to billboards after save

- app/controllers/admin/billboards_controller.rb
- app/views/admin/billboards/edit.html.erb
- app/views/admin/billboards/index.html.erb
- app/views/admin/billboards/show.html.erb
- config/routes/admin.rb
- spec/requests/admin/billboards_spec.rb
Adds page which shows details and data for a billboard
> Add billboard admin show page

- app/javascript/packs/homePage.jsx
- app/views/pages/show.en.html.erb
- app/views/pages/show.fr.html.erb
Fix issue where tags don't show up on "Page" sidebar.
> Fix tags on sidebar of pages

- app/services/images/optimizer.rb
Add the ability for technical admin to adjust the subdirectory used to call cloudflare. This allows the admin to use workers to adjust response as needed (bots etc)
Closes https://github.com/forem/forem/issues/21292
> Allow cloudflare directory to be set via variable

- app/javascript/Search/SearchForm.jsx
- app/javascript/packs/application.jsx
- app/views/comments/_form.html.erb
Use dynamic import and rails view logic to wait to load JS which is not necessary on all pageviews.
> Conditionally load javascript optimization

- config/environments/production.rb
- spec/services/mentions/create_all_spec.rb
This adds an option for multi store if the ENV var is present. This can be used for redundancy or swap.
> Add optional backup cache store

- config/environments/production.rb
- lib/multi_store_cache.rb
- spec/lib/multi_store_cache_spec.rb
This fully closes the loop on the optional multicache functionality
> Add full functionality for redis multicache

- config/environments/production.rb
This may be required to load this lib class
> Explicitely require multstore cache

- lib/liquid/variable.rb
- spec/lib/liquid/variable_spec.rb
- spec/services/markdown_processor/parser_spec.rb
Instead of failing on a liquid variable, we should just render the plain text instead of executing.
- Closes https://github.com/forem/forem/issues/6673
> Render liquid variables as plain text instead or raising error

- app/lib/redcarpet/render/html_rouge.rb
- app/services/markdown_processor/parser.rb
- spec/services/markdown_processor/parser_spec.rb
Reverts https://github.com/forem/forem/pull/21288
Takes the lesser of two bugs
- Related Issue https://github.com/forem/forem/pull/21288
- Closes https://github.com/forem/forem/issues/21314
> Revert code block rendering change

- app/controllers/admin/users_controller.rb
- app/lib/constants/user_details.rb
- app/views/admin/users/show.html.erb
- app/views/admin/users/show/_tabs.html.erb
- app/views/admin/users/show/articles/_index.html.erb
- app/views/admin/users/show/comments/_index.html.erb
- config/locales/views/admin/en.yml
Show articles and comments on admin view
> View all posts and comments

- app/lib/constants/role.rb
- app/services/moderator/manage_activity_and_roles.rb
- config/locales/views/admin/en.yml
- config/locales/views/admin/fr.yml
- spec/services/moderator/manage_activity_and_roles_spec.rb
Allow admins to reward "base subscriber" manually — either to individual users or in bulk.
> Allow admin to reward base subscriber role via admin

- app/controllers/admin/users_controller.rb
- app/views/admin/users/show/profile/_actions.html.erb
- app/views/admin/users/show/profile/actions/_update_email.html.erb
- config/locales/views/admin/en.yml
- config/routes/admin.rb
- spec/requests/admin/users/users_update_email_spec.rb
> Allow admins to change emails

- config/initializers/datadog.rb
These don't need to be distributed into different APMs, simpler to roll up.
> Roll up HTTP Clients in datadog tracing

- config/initializers/datadog.rb
Funneling all the redis instances into one APM
> Consolidate dedicated redis tracing

- app/javascript/packs/Search.jsx
- app/javascript/packs/application.jsx
- app/javascript/packs/articleAnimations.jsx
- app/javascript/packs/articlePage.jsx
- app/javascript/packs/articleSignedIn.jsx
- app/views/articles/show.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
Migration to esbuild simplified how our JS is loaded resulting in a lack of capacity to use dynamic inserts.
This change conditionally loads certain scripts to have less loaded on each request.
There are still some additional changes we could make to load less data on each request.
> Conditionally include scripts

- config/initializers/datadog.rb
Allow this to be set via env var, default to false if this isn't set.
> Make tracing log injection available via env var

- config/fastly/snippets/bad_bot_detection.vcl
This adds a couple bot agents to mitigate unnecessary file transfer.
> Add bots to vcl

- app/controllers/articles_controller.rb
- app/controllers/stories_controller.rb
- app/controllers/users_controller.rb
Just some housekeeping — removing some logs we don't need.
> Clean up unnecessary logs

- app/controllers/admin/emails_controller.rb
- app/mailers/custom_mailer.rb
- app/models/admin_menu.rb
- app/models/audience_segment.rb
- app/models/email.rb
- app/views/admin/emails/_form.html.erb
- app/views/admin/emails/index.html.erb
- app/views/admin/emails/new.html.erb
- app/views/admin/emails/show.html.erb
- app/views/mailers/custom_mailer/custom_email.html.erb
- app/workers/emails/batch_custom_send_worker.rb
- config/locales/controllers/admin/en.yml
- config/locales/controllers/admin/fr.yml
- config/locales/mailers/en.yml
- config/locales/mailers/fr.yml
- config/routes/admin.rb
- db/migrate/20241018175616_create_emails.rb
- db/migrate/20241023131302_add_name_to_audience_segments.rb
- db/schema.rb
- spec/factories/emails.rb
- spec/factories/users.rb
- spec/mailers/custom_mailer_spec.rb
- spec/mailers/previews/custom_mailer_preview.rb
- spec/models/email_spec.rb
- spec/requests/admin/emails_spec.rb
Add the capacity to send custom emails — falling under the "newsletter" permission for now as the intention is capacity to send newsletters from in the app, but potentially an area to add more nuance to this subscription.
> Add custom emails to admin area

- app/javascript/packs/organizationDropdown.js
- app/views/organizations/_header.html.erb
- config/locales/views/organizations/en.yml
- Related Discussion #21334
It will likely need a new test fixture for an organization, as there doesn't seem to have any for a test organization. Once In know how to do that I can continue the tests themselves, already made a draft.
> Add report abuse dropdown for organizations

- lib/tasks/fetch.rake
Roll up rake task to help clean up some old data
> Roll up old data

- app/javascript/packs/organizationDropdown.js
- app/views/articles/_actions.html.erb
- app/views/articles/show.html.erb
- app/views/comments/_comment_proper.html.erb
- config/locales/views/actions/en.yml
- config/locales/views/actions/fr.yml
- cypress/e2e/seededFlows/articleFlows/postSidebarActions.spec.js
Logically only include inline scripts if they match content of the page.
Also remove some share links which don't work as expected to further simplify page.
> Remove superfluous content from article show page

- .vscode/settings.json
- app/controllers/admin/application_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/edge_cache_safety_check.rb
- cypress.config.js
- cypress/e2e/seededFlows/articleFlows/playOrPauseAnimatedImages.spec.js
- cypress/e2e/seededFlows/loggedOutFlows/showLoginModal.spec.js
Optimization to remove a bit of lag from things we watch with vscode
> Adjust vscode settings

- app/controllers/auth_pass_controller.rb
- app/views/auth_pass/iframe.html.erb
- config/initializers/session_store.rb
- config/routes.rb
- spec/requests/auth_passes_spec.rb
This is experimental functionality for potentially passing authentication via temp token tied to secret key base. Not for any live functionality at the moment.
> Pass auth token with token generated from secret keybase

- app/controllers/auth_pass_controller.rb
- config/initializers/session_store.rb
- spec/requests/auth_passes_spec.rb
More functionality related to the experimental ability to securely authenticate through iframes and tokens for potential future features.
> Generate session for iframe

- app/controllers/application_controller.rb
- app/controllers/auth_pass_controller.rb
- config/initializers/session_store.rb
- spec/requests/auth_passes_spec.rb
Experimental, incomplete functionality: Setting up the capacity to contextually visit the core Forem from a different domain (if pre-configured to allow for that).
> Adjust for dynamic secondary domains if they exist

- app/controllers/application_controller.rb
Experimentation on ongoing safe adjustments to how cookies can be set dynamically (last attempt didn't properly work)
> Set remember cookie properly (attempt 2)

- app/assets/stylesheets/components/stories.scss
- app/assets/stylesheets/components/tabs.scss
- app/javascript/articles/Feed.jsx
- app/queries/homepage/articles_query.rb
- app/views/users/_comments_section.html.erb
Some fast follow style and context tweaks for quickies.
> Small tweaks for quickies

- app/javascript/articles/Feed.jsx
Tweak to account for whether Instantclick is present here
> Adjust for presence of InstantClick

- app/models/article.rb
- app/services/images/generate_social_image_magickally.rb
- spec/services/images/generate_social_image_magickally_spec.rb
Extra long titles (in quickie posts) need to be truncated.
> Truncate long title in social image card

- app/controllers/application_controller.rb
In some forem cloud contexts, we need to forward to the proper domain, but get an error. This should solve it safely.
> Allow other host in forward_to_app_config_domain

- app/assets/javascripts/initializers/initScrolling.js
- app/assets/javascripts/utilities/buildArticleHTML.js
- app/services/articles/feeds/basic.rb
- app/views/articles/index.html.erb
- config/locales/views/dashboard/en.yml
- config/locales/views/dashboard/fr.yml
We don't properly paginate with the `/stories/feed` endpoint. This gives a feature flag to do this — currently only on the home page. We could move some more stuff over later if this works.
It's sort of a hack to keep things backwards-compatible, but is the road towards cleaning it all up.
> Fix legacy pagination issues

- app/assets/javascripts/utilities/buildArticleHTML.js
Remove accidentally-left placeholder
> Remove erroniously included word

- app/assets/javascripts/utilities/buildArticleHTML.js
Small fix here with html overflow
> Small markup fix

- app/views/articles/show.html.erb
Simple format was added as part of quickie experimenting, but is not appropriate.
> Remove simple format article show

- app/assets/javascripts/initializers/initScrolling.js
- app/controllers/stories/feeds_controller.rb
- app/javascript/articles/Feed.jsx
- app/services/articles/feeds/variant_query.rb
Simplify query for following tab with experimental following tab
> Simplify following tab

- app/assets/javascripts/initializers/initScrolling.js
- app/controllers/stories/feeds_controller.rb
- app/javascript/packs/homePage.jsx
With the experimental "Following" feed, the cached follow ids etc do not actually have all the follow ids. This fixes the query.
> Adjust following query to fetch all

- app/assets/stylesheets/components/stories.scss
- app/views/articles/_feed_nav.html.erb
Fix typo and small style tweaks for consistency
> Fix typo and small style tweaks

- app/controllers/application_controller.rb
Fixes issues where config app_domain is not set properly
> Prefer settings domain to app config domain

- app/mailers/devise_mailer.rb
- app/views/devise/mailer/magic_link.html.erb
- spec/mailers/devise_mailer_spec.rb
- spec/system/authentication/user_logs_in_with_email_spec.rb
Additional tweaks for underlying magic link functionality
> Tweaks to magic link underlying functionality

- app/controllers/admin/emails_controller.rb
- app/mailers/custom_mailer.rb
- app/models/email.rb
- app/views/admin/emails/_form.html.erb
- app/views/admin/emails/edit.html.erb
- app/views/admin/emails/show.html.erb
- app/views/layouts/mailer.html.erb
- spec/mailers/custom_mailer_spec.rb
- spec/mailers/verification_mailer_spec.rb
- spec/requests/admin/emails_spec.rb
Allow merge tags in custom emails, and add ability to edit
> Allow merge tags in custom emails

- app/assets/images/boost.svg
- app/assets/stylesheets/article-show.scss
- app/assets/stylesheets/base/typography.scss
- app/javascript/articles/Article.jsx
- app/javascript/articles/Feed.jsx
- app/javascript/packs/articleReactions.js
- app/models/article.rb
- app/views/articles/_multiple_reactions.html.erb
- app/views/articles/_quickie_form.html.erb
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- app/views/stories/feeds/show.json.jbuilder
- config/locales/views/articles/en.yml
- config/locales/views/articles/fr.yml
- spec/models/article_spec.rb
- spec/models/billboard_spec.rb
Allow members to boost posts via quickie
> Boost posts via quickie

- app/views/articles/_quickie_form.html.erb
Do not include form when unpublished
> Only include form when published

- app/controllers/email_subscriptions_controller.rb
- app/views/articles/_quickie_form.html.erb
- config/locales/controllers/en.yml
- config/locales/controllers/fr.yml
Fix unsubscribe email bug and cache article share content
> Fix unsubscribe and other bug

- app/assets/javascripts/utilities/buildArticleHTML.js
- app/models/article.rb
- app/views/articles/_quickie_form.html.erb
- spec/models/article_spec.rb
> Small fixes to quickie posts

- app/mailers/custom_mailer.rb
- app/models/email.rb
- app/workers/emails/batch_custom_send_worker.rb
- app/workers/emails/drip_email_worker.rb
- spec/mailers/custom_mailer_spec.rb
Adjust from name based on `type_of`. In the future we can also have custom from — but this is a better default.
Also adding rescue and log for edge case failures.
> Adjust from email based on type

- app/controllers/auth_pass_controller.rb
- spec/requests/auth_passes_spec.rb
In the experimental token authentication, we should also set the remember token.
> Set remember token in token login

- config/initializers/devise_monkeypatch.rb
If secondary domains are present, and the request is from that domain, use that domain in the remember cookie
> Make remember_cookie_values more dynamic

- app/views/devise/mailer/confirmation_instructions.html.erb
- spec/mailers/devise_mailer_spec.rb
Because gmail sometimes auto-links urls, we'll make an adjustment to not include names in this email if it includes "http". This can help avoid potential phishing.
> Do not include name in welcome email in some cases

- app/assets/stylesheets/billboards.scss
- app/assets/stylesheets/widgets.scss
- app/views/shared/_billboard.html.erb
- cypress/e2e/seededFlows/homeFeedFlows/billboards.spec.js
Adjustments and edge cases for element visibility
> HTML classes refactor

- app/models/settings/base.rb
Improve caching reliability for settings
> Improve base settings caching

- app/controllers/stories_controller.rb
- spec/requests/user/user_profile_spec.rb
- spec/requests/user/user_show_spec.rb
If user/org has no content in non-default subforem, redirect to default.
> Redirect to default if profile does not exist

- app/controllers/application_controller.rb
- app/javascript/articles/Article.jsx
- app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
- app/javascript/articles/__tests__/utilities/articleUtilities.js
- app/javascript/articles/components/ArticleCoverImage.jsx
- app/javascript/articles/components/ContentTitle.jsx
- app/javascript/articles/components/Meta.jsx
- app/javascript/articles/components/ReactionsCount.jsx
- app/javascript/articles/components/Video.jsx
- app/lib/url.rb
- app/models/article.rb
- app/models/notification.rb
- app/models/subforem.rb
- app/services/articles/feeds/variant_query.rb
- app/views/articles/_liquid.html.erb
- app/views/stories/feeds/show.json.jbuilder
- db/migrate/20241223201958_add_root_to_subforems.rb
- db/schema.rb
- spec/liquid_tags/link_tag_spec.rb
- spec/models/article_spec.rb
- spec/models/subforem_spec.rb
Add the ability to have a root subforem — which for now will adjust the query. There could be other functionality later.
> Add root subforem

- app/models/email.rb
- app/workers/emails/batch_custom_send_worker.rb
- app/workers/emails/enqueue_custom_batch_send_worker.rb
- spec/models/email_spec.rb
- spec/workers/emails/enqueue_custom_batch_send_worker_spec.rb
Make email delivery async so it doesn't ever time out.
> Make custom email delivery async

- lib/tasks/sidekiq_scaler.rake
Add ability to call a rake task which autoscales Heroku _workers_ based on sidekiq load. This is not available with web workers by default.
> Add autoscaling worker task for Heroku

- .github/workflows/ci.yml
- .husky/pre-commit
In order to allow more simple exceptions to style issues in PRs, we'll remove strict linting from the review. These are still live in the project, but not as part of code review per se.
> Remove heavy-handed linting in CI

- app/controllers/admin/billboards_controller.rb
- app/controllers/admin/navigation_links_controller.rb
- app/controllers/api/v1/billboards_controller.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/stories_controller.rb
- app/lib/url.rb
- app/models/billboard.rb
- app/models/navigation_link.rb
- app/models/page.rb
- app/models/subforem.rb
- app/queries/billboards/filtered_ads_query.rb
- app/views/articles/_sidebar.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_main_nav.html.erb
- config/initializers/strong_migrations.rb
- db/migrate/20241231130445_add_subforem_id_to_billboards_and_pages.rb
- db/migrate/20241231130507_add_subforem_id_index_to_billboards_and_pages.rb
- db/schema.rb
- spec/models/navigation_link_spec.rb
- spec/models/page_spec.rb
- spec/queries/billboards/filtered_ads_query_spec.rb
- spec/requests/api/v1/billboards_spec.rb
- spec/requests/api/v1/pages_spec.rb
- spec/requests/pages_spec.rb
Adds subforem id to pages and nav links, while allowing multi-subforem targeting for billboards
> Add subforem to key models

- app/helpers/application_helper.rb
It appears that this is inconsistently a string vs symbol. This fixes that.
> Fix social_media_constructed_url

- app/controllers/stories_controller.rb
- app/models/article.rb
- app/services/articles/feeds/large_forem_experimental.rb
- app/views/articles/_single_story.html.erb
- app/views/sidebars/_homepage_content.html.erb
Use full post url instead of path
> Use full URL in single story html

- app/views/moderations/actions_panel.html.erb
- app/views/sidebars/_homepage_content.html.erb
- app/views/stories/tagged_articles/_sidebar_additional.html.erb
Ensure nothing gets leaked due to cache leak
> Add subforem to cache key for sidebar

- app/controllers/async_info_controller.rb
Ensure subforem-specific user_data
> Fix caching for user_data

- app/controllers/application_controller.rb
- spec/requests/stories_index_spec.rb
If this is not possible to set upstream, this config can be set here
> Allow configuration to redirect www to root

- app/assets/stylesheets/billboards.scss
- app/views/shared/_billboard_header.html.erb
> Refactor billboard html

- app/controllers/notifications/counts_controller.rb
- app/decorators/notification_decorator.rb
- app/models/article.rb
- app/services/notifications.rb
- app/views/notifications/shared/_article_preview.html.erb
- spec/decorators/notification_decorator_spec.rb
Adds full url to notifications for cross-subforem nav
> Use full url for notifications

- app/assets/javascripts/initializers/initializeBodyData.js
- app/controllers/application_controller.rb
- app/controllers/async_info_controller.rb
- app/controllers/auth_pass_controller.rb
- app/controllers/omniauth_callbacks_controller.rb
- app/controllers/sessions_controller.rb
- app/helpers/application_helper.rb
- app/models/subforem.rb
- app/models/user.rb
- app/views/layouts/_bottom_scripts.html.erb
- app/views/layouts/application.html.erb
- config/initializers/devise.rb
- config/initializers/warden_hooks.rb
- config/routes.rb
- spec/models/subforem_spec.rb
- spec/requests/sessions_spec.rb
Additional experimentation with securely passing auth between hosts. This uses an iframe to pass a secure token which can sign in with a secure cookie across multiple domains within the same Forem.
> Add authpass functionality to bottom of page

- app/models/email.rb
- app/workers/emails/batch_custom_send_worker.rb
- app/workers/emails/enqueue_custom_batch_send_worker.rb
- spec/models/email_spec.rb
- spec/workers/emails/batch_custom_send_worker_spec.rb
- spec/workers/emails/enqueue_custom_batch_send_worker_spec.rb
Adds [Test] to test emails, and adds check to not send multiple non-test emails, and remove suspended users from send scope.
> Add [Test] to test emails, and disallow multiple non-test email sends

- app/controllers/concerns/api/articles_controller.rb
- spec/services/email_digest_article_collector_spec.rb
Simple API extension, adding language here.
> Add language to api

- .github/dependabot.yml
> Change dependabot to npm

- app/controllers/concerns/api/articles_controller.rb
- app/views/api/v0/articles/_article.json.jbuilder
- app/views/api/v0/articles/me.json.jbuilder
- app/views/api/v1/articles/_article.json.jbuilder
- spec/requests/api/v0/articles_spec.rb
- spec/requests/api/v1/articles_spec.rb
Small WIP addition to API to extend for more info
> Add language and subforem_id to api

- app/controllers/sessions_controller.rb
- config/fastly/snippets/check_for_remember_user_token_in_cookie_to_set_header.vcl
Continued experimentation with how auth logic and CDN logic work together
> Modify cookie sign in logic

- app/controllers/collections_controller.rb
- app/controllers/moderations_controller.rb
- app/services/article_api_index_service.rb
- app/services/users/suggest_for_sidebar.rb
The `from_subforem` scope is missing in a few places — this might not be everywhere but it's a few I found.
> Add subforem scope to a few places where it's missing

- app/controllers/api/v1/pages_controller.rb
- app/models/page.rb
- spec/requests/api/v1/pages_spec.rb
Extend pages api with subforem id
> Add subforem_id to pages api

- app/views/articles/show.html.erb
This created problems in cypress
> Remove data test-id where not needed

- cypress/e2e/seededFlows/adminFlows/articles/pinArticle.spec.js
- cypress/e2e/seededFlows/adminFlows/billboards/editBillboards.spec.js
- cypress/e2e/seededFlows/articleFlows/commentModerationTools.spec.js
Adjustments to fix some persistent cypress failures
> Fix some cypress failures

- cypress/e2e/seededFlows/searchFlows/previewProfileFromPostSearchResults.spec.js
- spec/rails_helper.rb
Adjust retry number and skip one cypress test for now
> Fix some flakey tests

- app/models/billboard.rb
`.score` is now added to reports dashboard and billboard needs to respond to score.
> Fix moderations dashboard billboard score

- app/services/articles/suggest.rb
Bottom posts need `from_subforem` filter
> Add from subforem to suggested articles

- app/models/billboard.rb
- app/models/concerns/algolia_searchable/searchable_user.rb
- spec/models/user_spec.rb
Reduce unnecessary indexing by not indexing empty users
> Do not index empty profile users in search

- app/controllers/admin/feedback_messages_controller.rb
- app/views/admin/feedback_messages/_feedback_message.html.erb
- app/views/admin/feedback_messages/index.html.erb
Help speed up abuse reports by filtering already-determined reports.
> Filter reports to only show not-yet-dealt-with ones

- app/controllers/pages_controller.rb
Prioritize subforem welcome thread if exists
> Add subforem-specific welcome thread

- app/views/admin/feedback_messages/_feedback_message.html.erb
Adjust the way billboards are shown in admin reports. The billboard doesn't have a path/title
> Adjust billboard render in admin reports

- app/controllers/pages_controller.rb
Prioritize finding page by subforem
> Find page by subforem

- app/controllers/pages_controller.rb
Change so this query filters through subforems first
> Change about query

- app/controllers/articles_controller.rb
- app/controllers/stories_controller.rb
- app/models/article.rb
- app/services/edge_cache/bust_article.rb
- app/services/edge_cache/bust_user.rb
- spec/requests/articles/articles_spec.rb
- spec/services/edge_cache/bust_article_spec.rb
- spec/services/edge_cache/bust_organization_spec.rb
- spec/services/edge_cache/bust_user_spec.rb
Use surrogate keys for cache busting instead of paths
> More efficient article purge via surrogate keys

- app/controllers/admin/emails_controller.rb
- app/models/email.rb
- app/models/user.rb
- app/views/admin/emails/_form.html.erb
- app/views/admin/emails/show.html.erb
- app/workers/emails/enqueue_custom_batch_send_worker.rb
- db/migrate/20250115200745_add_targeted_tags_to_emails.rb
- db/schema.rb
- spec/workers/emails/enqueue_custom_batch_send_worker_spec.rb
Add ability for admin to target member who follows a tag.
> Add targeted tags filter for emails

- app/views/sidebars/_homepage_content.html.erb
- app/views/stories/tagged_articles/_sidebar_additional.html.erb
Removing some unneeded widgets which will improve performance. This is not really functionality being used actively.
> Remove unneeded preamble content

- app/javascript/articles/Article.jsx
- app/javascript/articles/Feed.jsx
Currently if you're on the following tab and don't follow anyone it can hang forever.
This is a bandaid but it's better.
> Render something for empty feed

- .github/workflows/cd.yml
Having deployment issue, this may resolve
> Explicitely update heroku runner to install dependencies

- app/controllers/stories/tagged_articles_controller.rb
Adjustments to tagged articles index to make it more efficient
> Small tagged articles page tweaks

- app/javascript/Search/SearchForm.jsx
- app/javascript/packs/application.jsx
Fix dynamic changing of placeholder and loading of recommendations in some scenarios.
> Fix search loading edge cases

- app/controllers/insights_controller.rb
- app/javascript/Search/SearchForm.jsx
- app/services/algolia_insights_service.rb
- config/routes.rb
- spec/requests/insights_spec.rb
Add search insights if user clicks a result
> Add search insights

- app/controllers/stories/tagged_articles_controller.rb
- spec/requests/stories/tagged_articles_spec.rb
Showing fewer articles per page signed out
> Adjust number of tag page articles

- app/javascript/__tests__/billboard.test.js
- app/javascript/articles/Feed.jsx
- app/views/layouts/application.html.erb
- config/routes.rb
Create alias for accessing billboards routes
> Refactor billboards

- app/controllers/insights_controller.rb
- app/services/algolia_insights_service.rb
- spec/requests/insights_spec.rb
Adjust params to not have timestamp passed, but instead just calculated on server
> Adjust insights params

- app/javascript/Search/SearchForm.jsx
Small adjustment to see about queryid in recommendations as well as searches
> Add queryid to recommendations

- app/workers/emails/enqueue_custom_batch_send_worker.rb
Double statement timeout for this worker
> Statement timeout adjust in enqueue custom batch worker

- app/controllers/sidebars_controller.rb
- app/helpers/application_helper.rb
- app/models/subforem.rb
- app/queries/articles/active_threads_query.rb
- app/views/articles/_widget_list_item.html.erb
- app/views/sidebars/_homepage_content.html.erb
- spec/models/subforem_spec.rb
Sidebar links are plucked and don't have access to all the methods, this includes full domains in the most efficient way we can.
> Add cached constructed url to sidebar (etc) links

- app/controllers/concerns/api/instances_controller.rb
- spec/requests/api/v1/instances_spec.rb
Set short-lived cache header for this endpoint
> Set cache headers on instance endpoint

- .github/workflows/ci.yml
Attempt to fix CI errors with imagemagick
> explicitely install imagemagick in CI

- app/controllers/auth_pass_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/_bottom_scripts.html.erb
- app/views/layouts/_top_bar.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/robots.text.erb
Work out auth pass edge cases to get default and root subforems squared away.
> Adjust auth and nav

- app/views/layouts/application.html.erb
Actually run bottom script in all scenarios unless no subforem exists
> Finalize auth scenarios

- app/controllers/articles_controller.rb
- app/javascript/articles/Feed.jsx
- app/models/subforem.rb
- app/views/articles/_quickie_form.html.erb
- app/views/articles/show.html.erb
- app/views/layouts/_bottom_scripts.html.erb
- db/migrate/20250127210058_add_discoverable_to_subforems.rb
- db/schema.rb
- spec/models/subforem_spec.rb
Add inter-subforem crossposting and some other tweaks
> Adjust quickie share form

- app/models/subforem.rb
Quick fix, this should be discoverable not root
> [FIX] Discoverable true

- app/liquid_tags/link_tag.rb
- app/liquid_tags/unified_embed/registry.rb
- app/models/subforem.rb
- spec/liquid_tags/link_tag_spec.rb
- spec/liquid_tags/unified_embed/registry_spec.rb
- spec/models/subforem_spec.rb
- spec/queries/billboards/filtered_ads_query_spec.rb
Modifications to make link tags work across subforems — possibly not complete functionality, but step in the right direction.
> Modify link tag

- app/views/articles/_quickie_form.html.erb
> Use post's tags for quickie form by default

- app/javascript/articles/Feed.jsx
- app/views/articles/_quickie_form.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
Make the way we call billboards more flexible if we need to change it up
> Make billboard fetching more flexible

- app/views/admin/settings/forms/_community.html.erb
This section in admin was accidentally marked as hidden.
> Add back community tab admin

- app/mailers/custom_mailer.rb
Add additional args to send through to the X-SMTPAPI for tracking
> Add unique args to X-SMTPAPI heading

- app/assets/stylesheets/views/article.scss
- app/javascript/actionsPanel/initializeActionsPanelToggle.js
- app/views/articles/_actions.html.erb
Add boost button to mobile main actions and relegate mod button to the menu _for this context_.
> Add boost button to mobile

- app/controllers/auth_pass_controller.rb
Allow cross-origin requests across subforems within app
> Allow cross-origin between subforems

- app/controllers/auth_pass_controller.rb
- spec/requests/auth_passes_spec.rb
Properly test this functionality
> Finalize proper auth pass headers

- app/javascript/articles/Feed.jsx
Ensure there is a fallback value here
> Add fallback string for feed

- app/javascript/articles/Feed.jsx
- app/lib/middlewares/set_subforem.rb
Explicitely set content security policy to allow for inter-subforem iframes
> Set subforem-oriented CSP

- app/controllers/auth_pass_controller.rb
Safari renders this as a weird "downloadable" document when we return `no_content` here
> Render empty-ish 200 instead of 204 no content

- app/javascript/packs/billboard.js
Small tweak, don't show post fixed bottom billboard in this context
> Tweak: Don't show post_fixed_bottom if native user agent

- app/assets/stylesheets/views/article.scss
Reactions can be too far apart on mobile, causing unwanted line break
> Reaction spacing styling tweak

- app/views/layouts/_top_bar.html.erb
Quick fix to make top bar selected link work when background color exists.
> Top bar style bug

- app/views/layouts/_bottom_scripts.html.erb
Tweak to be able to pass jwt via parameter in for use in token login
> Pass JWT via parameter

- app/views/layouts/_bottom_scripts.html.erb
Experimental feature post message to webview when determined to be authenticated.
> Post message to webview

- app/views/layouts/_bottom_scripts.html.erb
Tweaks for conditions which we trigger auth vs not.
> Adjust paramtoken logic for auth

- app/assets/javascripts/base.js.erb
- app/assets/javascripts/initializers/initializeBodyData.js
- app/assets/javascripts/utilities/sendHapticMessage.js
- app/views/layouts/_user_config.html.erb
The navigation should be hidden when in an iframe and in certain mobile contexts. This was broken in some edge cases recently, this fixes it and rounds out the functionality.
> Fix shell for embedded views

- app/assets/javascripts/base.js.erb
- app/assets/javascripts/initializers/initializeBodyData.js
- app/views/layouts/_user_config.html.erb
> Fix typo in user agent string

- app/assets/javascripts/initializers/initializeBodyData.js
- app/assets/stylesheets/base/main.scss
- app/javascript/article-form/components/Close.jsx
- app/views/articles/_v2_form.html.erb
- app/views/notifications/index.html.erb
Add new functionality to pass via native bridge
> Add new mobile bridge functionality

- app/assets/stylesheets/ltags/LinkTag.scss
- app/liquid_tags/bluesky_tag.rb
- app/liquid_tags/unified_embed/tag.rb
- app/views/articles/show.html.erb
- app/views/liquids/_bluesky.html.erb
- spec/liquid_tags/bluesky_tag_spec.rb
This embeds bluesky via url.
It's basic initial support. It could be modified to render more quickly.
> Initial support for embedding bluesky

- app/controllers/menus_controller.rb
- app/views/menus/show.html.erb
- config/routes.rb
- spec/requests/menus_spec.rb
Add a menu view endpoint for potential use in mobile primarily
> Add menu url

- app/views/articles/show.html.erb
- app/views/layouts/_user_config.html.erb
- app/views/layouts/application.html.erb
Optimization to run hidden shell code earlier and to prefetch reactions endpoint
> Prefetch optimizations

- app/controllers/concerns/api/subforems_controller.rb
- app/controllers/menus_controller.rb
- app/views/menus/show.html.erb
- app/views/notifications/index.html.erb
> Menu tweaks

- app/javascript/packs/profileDropdown.js
- app/views/layouts/_user_config.html.erb
- app/views/users/show.html.erb
Fix content layout shift on profile
> Fix content layout shift on profile

- app/controllers/notifications/counts_controller.rb
- app/controllers/notifications/reads_controller.rb
- app/javascript/packs/initializers/initializeNotifications.js
Make notification counts compatible with mobile auth
> Make notifications compatible with mobile

- app/controllers/application_controller.rb
- app/controllers/notifications/reads_controller.rb
- spec/requests/notifications/reads_spec.rb
Adjust token based auth in this path so it works for post calls.
> Adjust token-based auth for create action

- app/assets/stylesheets/views/article-form.scss
- app/controllers/application_controller.rb
- app/models/subforem.rb
Make signout path `/enter` instead of home, for more intuitive flow.
> Make signout page /enter

- app/workers/emails/enqueue_custom_batch_send_worker.rb
Adjust timeout to help ensure email sending finishes
> Adjust statement timeout for email sends

- app/controllers/registrations_controller.rb
- spec/requests/registrations_spec.rb
Redirect to root subforem when on a non-root, non-default subforem in registrations controller
> Add redirect for registrations

- app/liquid_tags/neon_tag.rb
- app/views/liquids/_neon.html.erb
- spec/liquid_tags/neon_tag_spec.rb
> Add neon tag POC

- CODE_OF_CONDUCT.md
- README.md
> Fix typo in README and code-of-conduct

- app/javascript/packs/billboard.js
Remove some console logs from prod.
> Remove console logs that snuck through

- app/javascript/packs/billboard.js
Refactor to use observe mutation here instead of hacky `setTimoute`
> Observe mutations refactor

- app/controllers/admin/pages_controller.rb
- app/views/admin/pages/index.html.erb
- app/views/admin/pages/new.html.erb
- spec/requests/admin/pages_spec.rb
Allow admins to prefill a page form by forking an existing one.
> Fork pages in admin

- spec/requests/menus_spec.rb
- spec/system/articles/user_creates_an_article_spec.rb
Fix wrong failing test. One just had the wrong result, one is secondary functionality we can deprecate and can mark as pending until a decision is made.
> Fix failing tests

- app/controllers/admin/subforems_controller.rb
- app/models/subforem.rb
- app/views/admin/subforems/_form.html.erb
- app/views/admin/subforems/edit.html.erb
- app/views/admin/subforems/index.html.erb
- app/views/admin/subforems/new.html.erb
- config/locales/controllers/admin/en.yml
- config/locales/controllers/admin/fr.yml
- config/routes/admin.rb
- spec/requests/admin/subforems_spec.rb
Add basic GUI in admin for modifying subforems — currently not in the menu as it's a WIP.
> Add basics of subforems

- app/controllers/stories/feeds_controller.rb
- app/services/articles/feeds/custom.rb
This is an experiment to pass a parameter to the feed endpoint to get a differently calculated feed.
This also adds a placeholder "custom" feed which builds off "basic" which is an internal object that could be swapped out later. It's used here to help test this.
> [Experimental] Pass parameter to feed to get different strategies

- app/controllers/feed_events_controller.rb
- app/controllers/stories/feeds_controller.rb
- app/javascript/articles/Feed.jsx
- app/javascript/packs/feedEvents.js
- app/models/feed_config.rb
- app/models/feed_event.rb
- app/models/settings/user_experience.rb
- app/services/articles/feeds/custom.rb
- app/views/stories/feeds/show.json.jbuilder
- db/migrate/20250227202132_create_feed_configs.rb
- db/migrate/20250228134835_add_feed_config_id_to_feed_events.rb
- db/migrate/20250228183206_add_feed_config_id_index_to_feed_events.rb
- db/schema.rb
- spec/models/feed_config_spec.rb
- spec/services/articles/feeds/custom_spec.rb
Add a model which allows for dynamically adjusted weights in prod for feeds and then a feedback loop for whether the feed leads to reactions/comments etc.
> Add configurable feed weights

- app/controllers/stories/feeds_controller.rb
> Remove temporary debugging line

- app/models/feed_config.rb
- app/services/articles/feeds/custom.rb
- db/migrate/20250228193922_add_new_weights_to_feed_configs.rb
- db/migrate/20250228200054_add_compelling_score_to_articles.rb
- db/schema.rb
Adds some new behavior to feed configs.
> Add attributes to feed config

- app/models/feed_config.rb
Small optimization to only grab first 10 tags.
> Add tag limit

- app/controllers/concerns/api/articles_controller.rb
- app/models/article.rb
- app/services/articles/attributes.rb
- app/services/feed_events/bulk_upsert.rb
- spec/requests/api/v1/articles_spec.rb
Adds `compellingness_score` to API
> Add compellingness_score to API

- app/controllers/stories/feeds_controller.rb
- app/models/feed_event.rb
- spec/models/feed_event_spec.rb
Currently we have an `|| FeedConfig.create` which should only trigger if absolutely necessary. This adjusts so it can't happen just if the item doesn't exist.
> Update feed event and feed config calculation and general functionality

- app/models/feed_config.rb
- spec/models/feed_config_spec.rb
Non-configurable, just default weight associated with language.
> Add basic language to feed config

- app/assets/javascripts/base.js.erb
- app/assets/javascripts/initializers/initializeBodyData.js
- app/javascript/packs/initializers/initializeNotifications.js
- app/views/layouts/_user_config.html.erb
- app/views/layouts/application.html.erb
This fixes an issue where the user-agent matchup between different versions of the mobile app can cause the navbar to be hidden.
- Closes https://github.com/forem/forem/issues/21601
> Fix navbar/useragent version issue

- app/models/feed_config.rb
- app/models/label.rb
- app/models/page_view.rb
- app/models/user.rb
- app/models/user_activity.rb
- app/workers/users/update_user_activities_worker.rb
- db/migrate/20250304151033_create_labels.rb
- db/migrate/20250304155443_create_user_activities.rb
- db/migrate/20250304170910_add_cached_label_list_to_articles.rb
- db/migrate/20250304171201_add_cached_label_list_index_to_articles.rb
- db/schema.rb
- spec/factories/user_activities.rb
- spec/models/feed_config_spec.rb
- spec/models/label_spec.rb
- spec/models/user_activity_spec.rb
Add user activity store for efficiency — and add beginnings of label functionality.
> Create user activity store and beginnings of labels

- app/models/feed_config.rb
- db/migrate/20250304214343_add_recent_article_supression_rate_to_feed_configs.rb
- db/schema.rb
- spec/models/feed_config_spec.rb
Add new features to surpress "recent" articles, add a bonus for current day articles, and turn language weight to configurable.
> Add new columns to feed configs

- app/controllers/concerns/api/articles_controller.rb
- app/models/article.rb
- app/services/articles/attributes.rb
- spec/requests/api/v1/articles_spec.rb
> Add labels to API

- app/models/feed_config.rb
- spec/models/feed_config_spec.rb
Add label matching to the query if available
> Set label weights live in feed config

- app/models/article.rb
- app/models/feed_config.rb
Setting a clone to `0` impressions count right off the bat. This counter is idempotent so there wasn't an issue with it being wrong forever, but it started at the wrong value. This corrects it.
> Clone impressions count zero

- .gitignore
- app/views/menus/show.html.erb
This adds an empty li item specifically to inject the current mobile version if in mobile. This page is only used in mobile contexts.
> Add mobile version list item

- app/views/devise/registrations/_registration_form.html.erb
- db/schema.rb
One more place where mobile version can be injected
> Add mobile version element

- app/controllers/insights_controller.rb
- app/javascript/Search/SearchForm.jsx
- app/services/algolia_insights_service.rb
- spec/requests/insights_spec.rb
Allow position to be sent in algolia
> Accept position in insights api

- app/controllers/concerns/api/listings_controller.rb
- app/controllers/page_views_controller.rb
- app/controllers/reactions_controller.rb
- spec/requests/page_views_spec.rb
- spec/requests/reactions_spec.rb
Listing toolkit was removed, but is still present in this one place. Also creates a small fix in algolia insights interface.
Related to https://github.com/forem/forem/pull/21679
> Fix listing toolkit issue

- app/assets/javascripts/initializers/initializeBillboardVisibility.js
- app/javascript/packs/billboardAfterRenderActions.js
Ensure that if a billboard is clicked twice for any reason, it's only tracked once.
> Ensure no double clicks on billboards

- app/assets/stylesheets/article-show.scss
- app/views/articles/show.html.erb
When the author of the post is viewing their own post on mobile, this area can jump. This fixes it.
> Fix content jump for edit button

- app/services/articles/enrich_image_attributes.rb
Settings automatically use the setting set by the request, but this is outside the context of the request so it needs to be explicit.
If subforem_id is `nil` it will be the same as before.
> Check subforem for image height settings

- app/views/layouts/_user_config.html.erb
Sends message which can be ingested by mobile.
> Send color mode mobile message

- public/.well-known/assetlinks.json
Update this file for app compatibility
> Update Android assetlinks

- app/assets/javascripts/utilities/buildCommentHTML.js.erb
- app/views/comments/_comment_footer.html.erb
- app/views/layouts/_top_bar.html.erb
Send message to mobile whenever we get new notification count.
> Send notification count message

- app/controllers/api/v1/pages_controller.rb
- spec/requests/api/v1/docs/pages_spec.rb
- spec/requests/api/v1/pages_spec.rb
> Update pages API to include error details in header

- app/models/listing.rb
Removes the unused `pg_search_scope :search_listings` and `include PgSearch::Model` from the deprecated `Listing` model.
Related to #21624 
- Closes #
> Remove pg_search configuration from Listing model

- app/uploaders/badge_uploader.rb
- app/uploaders/base_uploader.rb
- config/initializers/carrierwave_bombshelter_monkeypatch.rb
- spec/uploaders/article_image_uploader_spec.rb
- spec/uploaders/badge_uploader_spec.rb
- spec/uploaders/profile_image_uploader_spec.rb
Allows webp as an option for image uploading
> Allow webp format for uploading

- app/lib/constants/settings/user_experience.rb
- app/models/settings/user_experience.rb
- app/services/articles/feeds/custom.rb
- app/views/admin/settings/forms/_user_experience.html.erb
- config/locales/lib/en.yml
- config/locales/lib/fr.yml
- spec/services/articles/feeds/custom_spec.rb
> Allow admins to set lookback period

- app/controllers/omniauth_callbacks_controller.rb
- app/helpers/application_helper.rb
- app/javascript/onboarding/Onboarding.jsx
- app/views/layouts/application.html.erb
Adjust onboarding flow for root contexts — for now just skipping tags.
> Adjust onboarding logic for root

- app/assets/stylesheets/preact/onboarding-modal.scss
- app/controllers/magic_links_controller.rb
- app/controllers/onboardings_controller.rb
- app/javascript/onboarding/components/ProfileForm.jsx
- app/models/user.rb
- app/views/magic_links/create.html.erb
- app/views/magic_links/new.html.erb
- app/views/mailers/verification_mailer/magic_link.html.erb
- spec/mailers/previews/verification_mailer_preview.rb
- spec/requests/magic_links_spec.rb
Adjust the magic link functionality to give the user an option to copy a code instead of just a link — this is in case they are using a device where the link makes less sense.
> Adjust magic link to have a code

- app/controllers/magic_links_controller.rb
- app/mailers/verification_mailer.rb
- app/views/magic_links/new.html.erb
- app/views/mailers/verification_mailer/magic_link.html.erb
- spec/mailers/verification_mailer_spec.rb
- spec/requests/magic_links_spec.rb
Adjust styles and copy for email
> Adjust magic sign in styles

- app/controllers/magic_links_controller.rb
- app/views/magic_links/create.html.erb
- app/views/magic_links/new.html.erb
- spec/requests/magic_links_spec.rb
Adds a link for if the user already has a code for signing in.
> Add link for 'already have a code?'

- app/models/ahoy/visit.rb
- app/workers/visits/remove_old_visits_worker.rb
- spec/models/ahoy/visit_spec.rb
> Old data pruning updates

- app/controllers/magic_links_controller.rb
- app/controllers/registrations_controller.rb
- app/services/authentication/authenticator.rb
- db/migrate/20250424130716_add_onboarding_subforem_id_to_users.rb
- db/migrate/20250424131000_add_onboarding_subforem_id_to_index_users.rb
- db/migrate/20250424133716_add_onboarding_subforem_id_to_emails.rb
- db/migrate/20250424133726_add_onboarding_subforem_id_index_to_emails.rb
- db/schema.rb
- spec/requests/magic_links_spec.rb
- spec/requests/registrations_spec.rb
This records the specific subforem the user registered with which can have downstream affects on onboarding.
Currently no adjustments to onboarding. Just the recording of where they came from.
> Add onboarding subforem id

- app/javascript/hooks/useTagsField.js
- app/models/concerns/algolia_searchable/searchable_tag.rb
- app/models/subforem.rb
- app/models/tag.rb
- app/models/tag_subforem_relationship.rb
- db/migrate/20250425122448_create_tag_subforem_relationships.rb
- db/schema.rb
- spec/models/tag_subforem_relationship_spec.rb
Add the ability to establish a relationship between tag and subforem to replace strict global "supported"
> Add tag subforem relationship

- app/controllers/admin/tags_controller.rb
- app/controllers/tags_controller.rb
- app/models/tag.rb
- app/views/admin/subforems/index.html.erb
- app/views/admin/tags/_form.html.erb
- app/views/layouts/_sidebar_tags.html.erb
- spec/requests/admin/tags_spec.rb
> Add ability for admins to mark tags to subforems

- app/controllers/tags_controller.rb
- app/models/tag_subforem_relationship.rb
- spec/factories/tag_subforem_relationships.rb
- spec/models/tag_subforem_relationship_spec.rb
Subforem-specific suggestions on tags page
> Adjust tags suggested on tag page

- app/models/feed_config.rb
- app/models/user_activity.rb
- db/migrate/20250430124301_add_subforem_weight_to_feed_configs.rb
- db/migrate/20250430130048_add_recent_subforems_to_user_activities.rb
- db/schema.rb
- spec/models/feed_config_spec.rb
- spec/models/user_activity_spec.rb
Add subforems as a factor in feed configs
> Add subforems to feed config

- app/decorators/user_decorator.rb
- app/models/user.rb
Adjust async info so it takes into account the request subforem appropriately in the caches.
> Adjust async info for subforems

- app/models/feed_config.rb
- app/models/user_activity.rb
- spec/models/user_activity_spec.rb
Add one other column to this method
> Adjust user activity store

- app/models/feed_config.rb
- spec/models/feed_config_spec.rb
Adjust to only weight subforem if the request is root.
> Adjust feed configs to only check subforem if it makes sense to

- app/models/user_activity.rb
Small adjustment to not store these as unique
> Store volume of recent subforems

- app/models/article.rb
- app/views/layouts/_footer.html.erb
- spec/models/article_spec.rb
- spec/services/moderator/sink_articles_spec.rb
Adds small score nudges for users with past featured content and small nudge with past negatively marked content.
> Smarter score adjustments

- spec/services/moderator/sink_articles_spec.rb
> Fix test syntax error

- app/views/layouts/_footer.html.erb
> Shorten footer cache

- app/lib/constants/settings/rate_limit.rb
- app/models/settings/rate_limit.rb
- app/views/admin/settings/forms/_rate_limit.html.erb
- config/locales/lib/en.yml
- config/locales/lib/fr.yml
This adds an area to specify for internal reference exactly what is on-topic for a specific subforem vs off-topic and maybe belonging to a different one.
> Internal content description spec in settings

- app/controllers/application_metal_controller.rb
- app/controllers/concerns/session_current_user.rb
- app/controllers/feed_events_controller.rb
- spec/requests/feed_events_spec.rb
> Allow token auth in feed events

- app/javascript/packs/searchParams.js
- app/models/concerns/algolia_searchable/searchable_article.rb
- app/models/concerns/algolia_searchable/searchable_comment.rb
- app/models/concerns/algolia_searchable/searchable_organization.rb
- app/views/notifications/shared/_comment_box.html.erb
- app/views/stories/articles_search/index.html.erb
> Add new searchable attributes and search adjustments

- app/javascript/articles/Article.jsx
- app/javascript/packs/homePageFeed.jsx
If we're on the root subforem, include the subforem domain shortening in the card.
> Include subforem name in index if root

- app/views/admin/overview/index.html.erb
- app/views/devise/mailer/_creator_confirmation_instructions.html.erb
We are switching from `forem.dev` to `core.forem.com` — so this updates the reference.
> Remove forem.dev reference

- app/views/sidebars/_homepage_content.html.erb
On root subforem, show other subforems in sidebar.
> Add subforems to root subforem sidebar

- app/controllers/api/v1/billboards_controller.rb
> Add prefer_paired_with_billboard_id to api

- config/database.yml
Adds the ability to use `NEW_DATABASE_URL` if it is present
> Add optional database env var

- config/database.yml
Optional custom search path defined
> Custom schema search path

- config/database.yml
> Adjust database.yml

- config/database.yml
Just use this one hardcoded for now
> Hardcode search schema

- config/database.yml
> Remove reference to database_name in database.yml

- lib/tasks/app_initializer.rake
- lib/tasks/release_migrate.rake
Adjust to run migration only if needed
> Guarded release task

- Procfile
> Remove pgbouncer reference

- lib/tasks/app_initializer.rake
> Temporarily remove migration at boot

- config/database.yml
This extends the window for finding a db connection
> Adjust timeout configs in database.yml

- config/database.yml
Helps close connections proactively
> Add idle timeout

- app/controllers/stories/feeds_controller.rb
This is currently timing out sometimes and as a measure to not let it hang too long, we'll add a logical return of nothing. This should be improved on and optimized later.
> Add logical timeout to relevant following feed

- app/controllers/billboard_events_controller.rb
- spec/requests/billboard_events_spec.rb
This makes it so only new events have to be counted
> New billboard count update logic

- lib/tasks/app_initializer.rake
Skip migrations via env var if necessary
> Skip migrations env var

- app/controllers/stories/feeds_controller.rb
- app/models/article.rb
Make the following feed more optimized (and more DRY as a consequence)
> Following feed optimization

- config/database.yml
> Adjust db pooling numbers

- config/initializers/sidekiq.rb
> Proper sidekiq reference

- lib/sidekiq/transaction_safe_rescue.rb
> Use sidekiq logger

- app/controllers/stories_controller.rb
This column is not indexed, so we're adjusting the display
> GH repo display optimization

- db/migrate/20250605145211_add_followed_user_ids_and_followed_org_ids_to_user_activity.rb
- db/schema.rb
This will help create an optimization by storing this info in this table. This is just the data part of the change.
> Add followed users/orgs to user_activities

- app/controllers/stories/feeds_controller.rb
- app/models/follow.rb
Adjust to account for potential missing activity
> Guard for no user_activity

- app/models/feed_config.rb
- spec/models/feed_config_spec.rb
Adds a general bonus for past 24 hour articles and a bonus multiplied by the number of page views this user has in the past 24 hours
> Add past day bonus for feed configs

- app/models/reaction.rb
- app/services/ai/base.rb
- app/services/ai/comment_check.rb
- app/services/spam/handler.rb
- config/initializers/ai.rb
- spec/services/spam/handler_spec.rb
Add new checks for comment spam. Only if the comment contains a link, we check for context and history.
> Add extra comment check

- app/services/ai/base.rb
- app/services/ai/comment_check.rb
Adjustments to prompt experiments
> Comment prompt adjustment

- app/services/spam/handler.rb
- spec/rails_helper.rb
- spec/services/spam/handler_spec.rb
Adjust spam check to check for repeat offenders in a small window
> Adjust spam check

- app/services/ai/base.rb
> Make Base Model Variable

- app/views/articles/show.html.erb
> Fix design

- app/controllers/api/v0/badges_controller.rb
- app/controllers/api/v1/badges_controller.rb
- app/controllers/concerns/api/badges_controller.rb
- app/policies/badge_policy.rb
- config/routes/api.rb
- spec/requests/api/v1/badges_spec.rb
This pull request introduces the initial framework and implementation for the Admin Badges API. It adds index, show, and create endpoints for managing Badges, following the existing api/admin controller pattern.
Related #21982 
- Closes #
> Add CRUD endpoints for Admin Badges (Issue #21982)

- app/models/settings/general.rb
- spec/models/settings/general_spec.rb
Use FastImage to automatically set aspect ratio if resized_logo changes
> Automatically set logo aspect ratio

- app/models/billboard.rb
Fix logic where we are not doing the proper pairing logic for digest billboards
> Fix prefer_paired_with_billboard_id logic

- db/migrate/20250625130739_add_composite_index_to_articles.rb
- db/schema.rb
The current index is not being properly used. This should fix it.
> Add composite canonical url index

- app/views/onboardings/_task_card.html.erb
Quick feature to add gemini cta to onboarding — should replace with something more configurable.
> Adjust task card

- app/views/layouts/_footer.html.erb
This is an internal cache not properly accounting for host
> Fix footer billboard cache issue

- app/javascript/articles/Article.jsx
- app/javascript/articles/components/Video.jsx
- app/models/article.rb
- app/view_objects/youtube_parser.rb
- app/views/articles/show.html.erb
Experimental feature, backend only, no ugc version yet
> Experimental youtube cover

- app/controllers/admin/feedback_messages_controller.rb
Fixes an issue where the reactable might not exist
> Check for reactable when selecting

- app/controllers/videos_controller.rb
- app/views/videos/index.html.erb
Show proper tags on page (proper fix)
> Proper tag matchup v2

- app/assets/stylesheets/views/article.scss
- app/controllers/admin/tags_controller.rb
- app/controllers/stories_controller.rb
- app/javascript/articles/Article.jsx
- app/models/article.rb
- app/models/context_note.rb
- app/services/ai/base.rb
- app/services/ai/context_note_generator.rb
- app/services/articles/feeds/basic.rb
- app/services/articles/feeds/custom.rb
- app/services/articles/feeds/large_forem_experimental.rb
- app/services/articles/feeds/tag.rb
- app/services/articles/feeds/variant_query.rb
- app/views/admin/tags/_form.html.erb
- app/views/articles/_single_story.html.erb
- app/views/articles/show.html.erb
- app/views/stories/feeds/show.json.jbuilder
- app/workers/articles/generate_context_note_worker.rb
- db/migrate/20250708151343_create_context_notes.rb
- db/migrate/20250708151708_add_context_note_instructions_to_tags.rb
- db/schema.rb
- spec/factories/context_notes.rb
- spec/factories/tags.rb
- spec/models/article_spec.rb
- spec/models/context_note_spec.rb
- spec/requests/api/v0/videos_spec.rb
- spec/requests/api/v1/videos_spec.rb
- spec/services/ai/context_note_generator_spec.rb
These add context notes to posts to give info related to the context of the post, such as "this is a challenge post" etc. Helps validate valid challenge entries etc.
It is flexible to add other forms of "context" in the future.
> Add context notes

- app/models/article.rb
- spec/models/article_spec.rb
Context note adjusts score by 1, tiny change here just to deliver a nudge.
> Small context note adjustment

- app/assets/stylesheets/base/layout.scss
- app/assets/stylesheets/config/_import.scss
- app/helpers/application_helper.rb
- app/views/layouts/_main_side_bar.html.erb
- app/views/layouts/application.html.erb
Small iteration on the experimental sidebar to update to more proper style variable use etc.
> Adjust sidebar to be proper styles

- app/assets/stylesheets/base/layout.scss
> Tiny nav style tweaks

- app/queries/organizations/suggest_prominent.rb
- app/queries/users/suggest_prominent.rb
This adjusts onboarding suggestions to be more efficient and effective
> More efficient onboarding suggestions

- config/database.yml
Disabling prepared statements will make database changes work more smoothly across different deployments, and advisory locks may optionally need to be disabled.
> Adjust database config

- app/controllers/follows_controller.rb
- app/models/subforem.rb
- app/services/follows/check_cached.rb
Data-only no frontend — add subforems as a followable thing.
> Make subforems followable

- app/models/feed_config.rb
- app/models/follow.rb
- app/models/user_activity.rb
- db/migrate/20250711152834_add_subforem_weights_and_more_to_feed_configs.rb
- db/migrate/20250711153423_add_alltime_subforems_to_user_activities.rb
- db/schema.rb
- spec/models/feed_config_spec.rb
- spec/models/user_activity_spec.rb
Have feed config use subforem follow weights
> Add subforem following weights to feed config

- app/assets/javascripts/utilities/buildArticleHTML.js
Hack to replace images which are out of sync with asset serving. This is a total hack for DEV but won't break any other instances.
> Image replace hack

- app/assets/stylesheets/base/layout.scss
- app/javascript/packs/followButtons.js
- app/javascript/packs/mainSidebar.js
- app/views/layouts/_main_side_bar.html.erb
Fix page-change follow button issues, and some tweaks to sidebar.
> Adjust follow button behavior and tweak sidebar

- app/controllers/concerns/api/subforems_controller.rb
- app/controllers/subforems_controller.rb
- app/models/subforem.rb
- app/views/layouts/_main_side_bar.html.erb
- app/workers/tags/resave_supported_tags_worker.rb
- db/migrate/20250717143815_add_scores_to_subforems.rb
- db/migrate/20250717144002_add_score_indexes_to_subforems.rb
- db/schema.rb
- spec/models/subforem_spec.rb
- spec/requests/subforems_spec.rb
Adds score and hotness score to subforems for ranking like other elements of the platform.
> Add score to subforems

- app/workers/emails/send_user_digest_worker.rb
Simpler fool proof way to ensure billboard pairing
> Simpler pairing logic

- app/controllers/onboardings_controller.rb
- spec/requests/onboardings_spec.rb
Appears to be a boolean type issue here
> Adjust onboarding custom actions

- app/assets/stylesheets/base/layout.scss
> Sidebar style tweaks

- app/helpers/application_helper.rb
- app/view_objects/cloud_cover_url.rb
- app/views/stories/feeds/show.json.jbuilder
- spec/requests/stories/feeds_spec.rb
- spec/view_objects/cloud_cover_url_spec.rb
Currently the `forem.com/stories/feed` images are not aligned with the proper configs of their individual subforem. This should fix that.
> Allow subforem_id to be passed to cloud_cover_url

- app/javascript/packs/feedEvents.js
- app/javascript/packs/mainSidebar.js
- app/models/feed_event.rb
- app/views/layouts/_main_side_bar.html.erb
Adjust feed event tracking so it works on sidebar in addition to home etc.
> Adjust feed event tracking for sidebar

- spec/models/billboard_spec.rb
- spec/services/moderator/sink_articles_spec.rb
Flakey tests. One array is not always the same and one tests functionality not currently being run.
> Fix flakey tests

- app/assets/javascripts/utilities/browserStoreCache.js
- app/javascript/packs/mainSidebar.js
- app/services/articles/feeds/custom.rb
- app/views/layouts/_main_side_bar.html.erb
This sets up logic which prefers cookie storage which can be shared across subdomain vs localstorage which is limited in this regard. All sharing is only between subforems, not further than that.
> Adjust client side storage logic for sidebar

- app/javascript/packs/mainSidebar.js
> Tweak sidebar line spacing style slightly

- app/services/articles/enrich_image_attributes.rb
- app/view_objects/cloud_cover_url.rb
- spec/services/articles/enrich_image_attributes_spec.rb
- spec/view_objects/cloud_cover_url_spec.rb
YT thumbs should always be 1000x500 ratio even if they are default returned otherwise.
> Adjust cover image for yt thumb

- app/assets/stylesheets/articles.scss
- app/views/articles/_v2_form.html.erb
- app/views/layouts/_main_side_bar.html.erb
- app/views/layouts/application.html.erb
Based on feedback:
- Remove sidebar from editor flow to preserve minimal design
- Fix sidebar margin issue which uses legacy styling
> Remove sidebar from compose view and fix tag page style bug

- app/assets/stylesheets/ltags/LiquidTags.scss
- app/assets/stylesheets/ltags/SurveyTag.scss
- app/controllers/poll_votes_controller.rb
- app/controllers/surveys_controller.rb
- app/liquid_tags/survey_tag.rb
- app/models/poll.rb
- app/models/poll_vote.rb
- app/models/survey.rb
- app/views/articles/show.html.erb
- app/views/liquids/_survey.html.erb
- app/views/liquids/_survey_poll.html.erb
- config/routes.rb
- db/migrate/20250805132259_create_surveys.rb
- db/migrate/20250805132547_add_survey_refernce_to_polls.rb
- db/schema.rb
- spec/factories/surveys.rb
- spec/liquid_tags/survey_tag_spec.rb
- spec/models/poll_skip_spec.rb
- spec/models/poll_vote_spec.rb
- spec/models/survey_spec.rb
- spec/requests/poll_skips_spec.rb
- spec/requests/poll_votes_spec.rb
- spec/requests/surveys_spec.rb
New feature allowing for surveys
> Add surveys which polls can belong to

- app/views/users/_comments_section.html.erb
Missing localization string. This is the fix
> Fix missing localization issue

- app/views/users/_comments_section.html.erb
- config/locales/views/users/en.yml
> Fix profile localization issue

- app/javascript/utilities/billboardInteractivity.jsx
- app/views/shared/_billboard_header.html.erb
- config/locales/en.yml
- config/locales/fr.yml
Quality-of-life improvement for admins: Edit button for billboards.
> Billboard edit link for admins

- app/services/ai/article_quality_assessor.rb
- app/workers/articles/quality_reaction_worker.rb
- spec/services/ai/article_quality_assessor_spec.rb
Remove fallback assessment, we'd rather it just not succeed
> Remove fallback assessment

- app/assets/javascripts/initializers/initializeBodyData.js
- app/controllers/magic_links_controller.rb
- app/views/magic_links/create.html.erb
- app/views/menus/show.html.erb
Small tweaks to ensure the user is redirected back appropriately in mobile
> Sign in tweaks for mobile

- app/workers/articles/quality_reaction_worker.rb
- spec/workers/articles/quality_reaction_worker_spec.rb
Adjust this feature to be a bit more subtle in the action taken
> Adjust quality reaction adjustment

- app/assets/javascripts/subforemSelectionModal.js
- app/assets/stylesheets/components/modals.scss
- app/models/subforem.rb
- app/policies/article_policy.rb
- app/views/articles/index.html.erb
- app/views/layouts/_nav_menu.html.erb
- app/views/layouts/_top_bar.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_subforem_selection_modal.html.erb
- spec/requests/stories_show_spec.rb
- spec/requests/subforem_selection_modal_spec.rb
Adds a modal where from the root forem, the place to post to can be chosen.
> Add root subforem compose selecter modal

- app/controllers/subforems_controller.rb
- app/models/article.rb
- app/views/subforems/edit.html.erb
- spec/models/article_spec.rb
- spec/requests/articles_spec.rb
- spec/requests/stories_show_spec.rb
This ensures a default subforem is set if appropriate. Right now there are edge cases where this can be nil.
> Set default subforem if appropriate

- app/assets/stylesheets/preact/onboarding-modal.scss
- app/javascript/onboarding/Onboarding.jsx
- app/javascript/onboarding/components/FollowSubforems.jsx
- app/javascript/packs/signupSubforemStorage.js
- app/javascript/packs/signupSubforemStorage.jsx
- app/views/devise/registrations/_registration_form.html.erb
- app/views/layouts/_signup_modal.html.erb
- app/views/layouts/_top_bar.html.erb
- app/views/shared/_auth_widget.html.erb
- app/views/shared/_authentication_actions.html.erb
- spec/requests/onboardings_spec.rb
If the user is coming in through the root forem, then let's show them subforem options to follow
> Add subforems to flow if signing up via root

- .env_sample
- bin/auto-cleanup
- bin/dev-cleanup
- bin/dev-performance
- bin/dev-performance-demo
- config/environments/development.rb
- config/initializers/development_file_management.rb
- config/initializers/development_performance.rb
- config/initializers/log_rotation.rb
- config/puma.rb
- docs/development-performance.md
Add options to clean up and disable unnecessary stuff to make the site snappier in development mode
> Add performance tweaks for development

- bin/dev-performance
- bin/validate-app
- config/initializers/cache_logger.rb
- config/initializers/development_file_management.rb
- config/initializers/development_performance.rb
- config/initializers/honeybadger.rb
- config/initializers/log_rotation.rb
- lib/tasks/release_migrate.rake
- release-tasks.sh
We made some local optimizations which caused a deployment crash — this should resolve it.
> Fix release issue

- app/assets/stylesheets/ltags/SurveyTag.scss
- app/models/poll.rb
- app/models/poll_option.rb
- app/views/liquids/_survey_poll.html.erb
- spec/models/poll_option_spec.rb
- spec/models/poll_spec.rb
> Adjust poll prompt max length

- app/assets/javascripts/sidebar-sticky.js
- app/views/articles/index.html.erb
- app/views/shared/_billboard_header.html.erb
- app/views/sidebars/_homepage_content.html.erb
The third/last home feed sidebar billboard will now stick when it is scrolled past. Due to a bunch of conflicting styles we couldn't just use css and had to use JS.
> Sticky third billboard home sidebar

- app/assets/stylesheets/base/layout.scss
- app/assets/stylesheets/components/tooltips.scss
- app/views/layouts/_main_side_bar.html.erb
- spec/system/sidebar_tooltip_spec.rb
> Add view all subforems tooltip to menu item

- app/assets/javascripts/utilities/buildArticleHTML.js
- app/javascript/articles/components/ReactionsCount.jsx
- app/models/concerns/reactable.rb
- app/views/articles/_single_story.html.erb
- spec/models/article_spec.rb
Have reactions show up in the feed by number of reactions per category, and limit to 3 so we don't just saturate popular posts with all the reactions.
> Adjust reaction ordering

- app/services/articles/feeds/custom.rb
- db/migrate/20250821230001_add_feed_query_optimization_indexes.rb
- db/schema.rb
- docs/feed_partial_index_optimization.md
- docs/feed_query_optimization.md
Add some indexes to make the feed more performant
> Feed optimizations

- app/views/comments/_comment_header.html.erb
> Style tweak

- app/controllers/subforems_controller.rb
- app/views/subforems/new.html.erb
Allow the subforem survey ID to be present
> Properly render subforem survey

- app/assets/stylesheets/ltags/SurveyTag.scss
Make this left aligned like the rest of the text
> Fix survey css

- spec/models/articles/feeds/variant_assembler_spec.rb
- spec/services/articles/feeds/variant_query_spec.rb
- spec/services/moderator/sink_articles_spec.rb
> Some test optimization

- app/views/articles/_v2_form.html.erb
- app/views/layouts/_logo.html.erb
A couple small fixes to `/new`
- Fix content layout from hydrated html being different from initial
- Added `data-no-instant` to logo because instantclick never quite works as it should here 100%.
> Small /new fixes

- app/controllers/stories/feeds_controller.rb
- spec/requests/stories/feeds_spec.rb
1 minute cache for non-signed-in stories feed
> Cache signed out stories feed

- db/migrate/20250902150028_add_expires_at_to_billboards.rb
Add this to disable transaction
> Add disable_ddl_transaction to latest migration

- app/views/articles/_fullscreen_embed.html.erb
- app/views/articles/show.html.erb
Refactor and take steps in full screen POC
> Refactor full screen mode

- app/assets/stylesheets/base/layout.scss
- app/views/comments/index.html.erb
Small tweak to make sure certain elements which shouldn't be rendered in iframes aren't
> Iframe rendering tweak

- app/assets/stylesheets/ltags/SurveyTag.scss
> Adjust survey styles

- app/services/ai/article_enhancer.rb
- app/workers/articles/handle_spam_worker.rb
- spec/services/ai/article_enhancer_spec.rb
- spec/workers/articles/handle_spam_worker_spec.rb
- Create `Ai::ArticleEnhancer` service for clickbait scoring and tag generation
- Add clickbait_score calculation with retry logic after spam processing
- Implement two-pass AI tag selection: top 10 by relevance, then 2-4 by summaries
- Filter tags by subforem relationships and top 150 hotness score
- Apply tags only to articles with no tags, score >= 0, and clickbait < 0.6
- Add comprehensive error handling and logging throughout
- Include full test coverage for all functionality and edge cases
> Add enhanced article enhancement to HandleSpamWorker

- app/helpers/i18n_helper.rb
- app/javascript/articles/Feed.jsx
- app/javascript/packs/homePageFeed.jsx
- app/javascript/shared/components/NoResults.jsx
- app/views/layouts/application.html.erb
- config/locales/views/stories/en.yml
- config/locales/views/stories/fr.yml
- config/locales/views/stories/pt.yml
When there are no posts, this shows a better empty space
> Add better empty state for feed

- app/models/concerns/algolia_searchable/searchable_article.rb
> Fix article searchable tweak

- app/views/layouts/_top_bar.html.erb
No need to show people a gigantic number. 50+ should suffice.
> Show max notification count of 50+

- app/assets/javascripts/utilities/buildArticleHTML.js
- app/assets/stylesheets/components/stories.scss
- app/assets/stylesheets/views/article.scss
- app/decorators/article_decorator.rb
- app/javascript/articles/components/ContentTitle.jsx
- app/models/article.rb
- app/queries/homepage/articles_query.rb
- app/serializers/homepage/article_serializer.rb
- app/views/articles/_quickie_form.html.erb
- app/views/articles/_single_story.html.erb
- app/views/articles/show.html.erb
- app/views/stories/feeds/show.json.jbuilder
- spec/decorators/article_decorator_spec.rb
- spec/models/article_spec.rb
- spec/requests/search/feed_content_simple_spec.rb
- spec/requests/stories/feeds_spec.rb
- spec/services/homepage/fetch_articles_spec.rb
- Add line break and paragraph support for quickie titles (status posts)
- Implement feed truncation with 'read more' indicator for long quickies (8+ lines)
- Add clean metadata titles for HTML meta tags and social sharing
- Implement keyboard shortcuts (Cmd+Enter/Ctrl+Enter) for quickie submission
- Allow regular Enter key for line breaks in quickie textarea
- Add smooth textarea auto-resize with focus-based expansion
- Update all feed endpoints to include new formatting attributes
- Add comprehensive test coverage for new functionality
- Fix method visibility issues and delegation in ArticleDecorator
Breaking changes: None - all changes are additive and backward compatible
> feat: Enhanced quickie formatting with line breaks, truncation, and keyboard shortcuts

- app/controllers/async_info_controller.rb
> Skip broadcasts

- app/views/articles/_fitvids.html.erb
- app/views/articles/show.html.erb
- app/views/comments/index.html.erb
- app/views/notifications/index.html.erb
These caches are rarely used or are generally unnecessary.
> Remove unnecessary caches rarely read from on article show page

- app/views/articles/show.html.erb
- app/views/layouts/application.html.erb
Preload instead of prefetch and move up in head
> Proper reaction preloading
