forem/forem

app/services/articles/updater.rb, spec/requests/api/v0/articles_spec.rb
This PR adds two missing things from the Articles update API:
* sends the "published" notification only the first time the article gets published
* sets `edited_at` when appropriate
* https://github.com/thepracticaldev/dev.to/pull/2844#issuecomment-493140089
* #2844
=> Articles update API: send publishing notification and set edited_at

app/services/streams/twitch_webhook/register.rb, spec/services/streams/twitch_webhook/register_spec.rb
- don't try to register a webhook when twitch API doesn't return any user data
- added a couple of specs for this case
#2784 
I mentioned an optimization in the issue description, I'll do in another pr along with the refactoring.
=> Don't fail when twitch returns no user data, fixes #2784

Gemfile, Gemfile.lock
This PR adds the gem [awesome_print](https://rubygems.org/gems/awesome_print) to aid debugging locally. An example:
```ruby
[3] pry(main)> p Notification
Notification(id: integer, action: string, created_at: datetime, json_data: jsonb, notifiable_id: integer, notifiable_type: string, notified_at: datetime, organization_id: integer, read: boolean, updated_at: datetime, user_id: integer)
=> Notification(id: integer, action: string, created_at: datetime, json_data: jsonb, notifiable_id: integer, notifiable_type: string, notified_at: datetime, organization_id: integer, read: boolean, updated_at: datetime, user_id: integer)
[4] pry(main)> ap Notification
class Notification < ApplicationRecord {
:id => :integer,
:action => :string,
:created_at => :datetime,
:json_data => :jsonb,
:notifiable_id …
```
=> Add awesome_print to development/test gems

app/views/pages/_editor_guide_text.html.erb
Added an explanation about how to setup anchor links(for things like a Table of Contents) to the blog post Editor Guide. When trying to figure out how to do this myself I ended up messaging a few people and was finally pointed towards [this comment](https://dev.to/rhymes/comment/5apb) from @rhymes. I figured I am probably not the only one that would find this information useful so I decided to add it to the Editor Guide. Let me know what you think!  
NONE
=> Add Anchor Links To The Post Editor Guide

spec/system/articles/user_visits_an_article_spec.rb, spec/system/homepage/user_visits_homepage_articles_spec.rb
Zonebie is the cause of our random spec failures (ie "American Samoa"). Enabling JS on those test will enable the display date be properly updated to browser's locale.
n/a
n/a
=> Fix date related spec failures

app/services/articles/updater.rb, app/views/api/v0/articles/show.json.jbuilder, spec/requests/api/v0/articles_spec.rb
It's not possible to assign an existing article to an org via API, this fixes that.
It also adds relevante datetimes to the article JSON resource, the same available in the export.
=> Articles API: fix update org and add datetimes

app/assets/stylesheets/notifications.scss
Improve text-background contrast for Dev.to badges in notifications
https://github.com/thepracticaldev/dev.to/issues/2883
The bug image is only there for testing purposes (based on which badge I triggered in dev). The only changes were made to the color of the badge message but not the actual content.
=> improve contrast of badge-reward-message

app/assets/javascripts/initializers/initializePWAFunctionality.js
Adds `target="_blank"` to anchor tags if the page is being rendered by a _desktop_ PWA. It seems like this is the appropriate functionality for a computer device, but touch screens should keep opening in the _pseudobrowser_.
Quick solution while we experiment with PWA functionality.
=> Add PWA target blank functionality

app/observers/application_observer.rb, app/observers/article_observer.rb, app/observers/comment_observer.rb, spec/observers/article_observer_spec.rb, spec/observers/comment_observer_spec.rb
Note:  I'm also not totally sure if I updated this properly but it passed all the tests so figured it wouldn't break anything and we can wait to see. Also, are observers actually deprecated? Seems to still be working w/ Slack so not sure there..
- Previously we were displaying when the 'warned' role was created, which is the wrong date. We don't actually track the date of when a user is warned so I removed that. 
- There was a lot of noise in slack bc comments/articles records sometimes get updated, even if the user isn't updating the article or comment. This changes the observer to look for after_create instead of after_save. 
- I think we can rely on community mods if people post inappropriate content by updating existing comments (that wouldn't send a slack alert to us).
- Refactors …
=> Update Slack Notifications

app/controllers/api_secrets_controller.rb
This removes the trailing dot from the API token creation message
=> Remove trailing dot from API token message [ci skip]

app/views/articles/delete_confirm.html.erb
A draft article should not contain the option to unpublish
draft:
published:
=> Do not ask to unpublish a draft article

app/controllers/articles_controller.rb, app/javascript/article-form/elements/errors.jsx, app/services/article_creation_service.rb
`ArticleCreationService` was raising an exception instead of sending back Rails errors.
I also fixed some linting errors in the errors component
Closes https://github.com/thepracticaldev/dev.to/issues/2868 and closes https://github.com/thepracticaldev/dev.to/issues/2916
=> Article creation: fix improper error messaging

app/controllers/articles_controller.rb, spec/requests/articles_update_spec.rb
While changing up the code, we solved some problems with _adding_ orgs and not inappropriately removing them, but that left us with some bugs when deliberately removing an org.
=> Fix bug to allow users to remove org from article

app/views/pages/api.html.erb
I've adjusted the HTML a bit, and added syntax highlighting with https://prismjs.com/ while we have this temporary page.
I've also fixed the two images that were unavailable
=> API docs: Adjust document and add syntax highlight [skip ci]

app/views/liquids/_tweet.html.erb, spec/support/fixtures/approvals/liquid_tweet_tag_spec.approved.html
The `controls` attribute adds video controls, like play, pause, and volume to an HTML <video> element.
#2673 
User should now be able to pause, mute and play embedded video tweets.
closes #2673 .
=> Fixes Twitter video control bug

app/jobs/notifications/notifiable_action_job.rb, app/models/notification.rb, app/services/notifications/notifiable_action/send.rb, spec/jobs/notifications/notifiable_action_job_spec.rb, spec/models/notification_spec.rb, spec/services/notifications/notifiable_action/send_spec.rb
- moved async method `Notification#send_to_followers` to a separate job
- added a check to avoid trying to sort `nil` followers (fix the dj error)
-  bulk-create corresponding notifications to make fewer SQL-queries
#1996
=> Moved notifying followers to a separate ActiveJob #1996

app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/users/_integrations.html.erb, config/routes.rb, spec/requests/user_settings_spec.rb, spec/system/user/user_edits_integrations_spec.rb
- attempt to register a twitch webhook (schedule a job) only when `twitch_username` changes instead of every time when a user updates their profile
- moved `update_twitch_username` to a separate action
- DRYed `UsersController` a bit
- specs for updating twitch username
- redirect to `/settings/integrations` after updating `twitch_username`
#2784
=> Move updating twitch username to a separate action #2784

app/assets/stylesheets/article-show.scss, app/assets/stylesheets/comments.scss, app/views/layouts/_user_config.html.erb
Resolve #2210
Fixed the night-theme mode color contrast for inline code comments + match color scheme with code blocks.
#2210 
article night:
comments night:
article pink:
=> Use consistent colors for inline code, including night theme

config/application.rb, config/environments/test.rb
Rails by defaults loads all its railties and engines, the current app does not use neither ActiveStorage, nor ActionCable nor TestUnit.
This shaves off some memory usage, not much.
=> Require only used parts of Rails

app/assets/stylesheets/readinglist.scss, app/javascript/readingList/readingList.jsx
When filtering reading list and there is no result, it looks like this:
In my opinion, it needs some margin between the highlighted words and the Bookmark icon padding looked extra big. That is likely due to the CSS targetting all [`spans`](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/readinglist.scss#L132) which was intended for Save and Bookmark but apparently it affected the icon as well.
I'm proposing for something like this:
The highlight styling should only affect Save and Bookmark span, and the Bookmark icon should only have margin left. Let me know what you think! Thank you.
- None
- Attached above
=> fix(reading-list): better spacing for Save and Bookmark span

app/services/notifications/reactions/send.rb, spec/models/notification_spec.rb, spec/services/notifications/reactions/send_spec.rb
- do upsert (insert + on conflict update) when trying to create a new reaction notification
That should fix a validation error when 2 notifications are created concurrently #2525
I've used upsert implementation from `activerecord-import` because it is already used in the app. When the app will be upgraded to Rails 6 it'll be possible to refactor and use rails `upsert`. 
- made `Notifications::Reactions::Send` return a more consistent result
#2525
=> Fix a validation error when creating notifications #2525

app/labor/cache_buster.rb, spec/labor/cache_buster_spec.rb
It can happen that `bust_comment` is called on a recently destroyed article, and it fails because such article is the `nil`.
This fixes that.
ps. I think this method should be called either `bust_commentable` or `bust_commentable_comments` or something more appropriate than `bust_comment` because it's busting the cache for the commentable which might include the homepage, the comments and the user's comments.
Closes #1831
=> Guard bust_comment against nil commentable

CONTRIBUTING.md, README.md
I noticed that the links to the testing doc on README.md and CONTRIBUTING.md are pointing to the wrong page (https://docs.dev.to/testing => 404). It should've been https://docs.dev.to/tests.
- None
- None
=> fix(README): link to the testing doc is broken [skip ci]

app/services/notifications/reactions/send.rb
I found out that there is an issue related to notifications unique index on the fields `["user_id", "organization_id", "notifiable_id", "notifiable_type", "action"]`. Several fields can be `nil` and in this case, the unique index allows to create records with the same fields which we don't want. 
In this pr, I returned the validation when saving a reaction notification. This will prevent creating some of the duplicate notifications, though the #2525 error will remain.
This is a temporary workaround. I'm working on finding a way to create correct constraint in the db so we could rely on them.
#2525
=> Validate on creating a reaction notification #2525

app/javascript/listings/listings.jsx
The width of the columns changes when the browser is resized so we will also call `resizeAllMasonryItems` function on window resize to recalculate each grid item height to avoid content overflow.
#2846
=> Fixes Listing Items Spacing Inconsistency and Content Overflow Issue #2846

app/javascript/article-form/articleForm.jsx
I found out that when inserting an image, I have to scroll all the way up to find the upload form.
Maybe it's a different UX problem (maybe using a modal instead, maybe the Image button shouldn't be at the footer), but in my opinion, it should have been scrolled to the top in the first place.
This is my first time doing a PR here, let me know if I'm doing this right! I searched the issues and seems like no one is reporting this (CMIIW) so it could be subjective, let me know. Thank you.
- None
- None
=> fix(article): scroll to top when inserting image

app/javascript/packs/homePage.js, app/javascript/src/components/Search/Search.jsx
This PR fixes two things:
- the `/` search shortcut key wasn't working for me, in my layout the forward slash key requires a modifier
- the `0` minimize shortcut key was triggered also when a modifier was present, see https://github.com/thepracticaldev/dev.to/issues/2968 - which it shouldn't because it overrides the browser's "zoom to normal" shortcut.
Now both work, I've also switched the code to use [event.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) instead of `event.which` which is deprecated (and doesn't work well with modifiers anyway). 
ps. I've also fixed an homepage error because the sidebar listings are not present on local
Closes https://github.com/thepracticaldev/dev.to/issues/2968
**Before**
as you can see the forward slash is not working and the …
=> Fix global keys

config/routes.rb, spec/requests/feedback_messages_create_spec.rb
This fixes an issue where submitting an abuse report would lead to a 404. The report would still successfully submit, but the reporter would see the 404 instead of a successful response page.
Also adds a test to check that.
=> Fix 404 issue when submitting abuse report

app/javascript/chat/chat.jsx
I just noticed an extra `@` sign on the chat screen, which can be removed. 
- None
- None
=> fix(chat): remove an extra at sign

app/controllers/admin/organizations_controller.rb, app/models/user.rb, app/views/users/_switch_organizations.html.erb
This removes the "Switch Organizations" tab and the related partial. Also clears any Rails caches when updating an organization via `/admin`.
=> Remove switch organizations tab from settings and clear Rails cache for PUT /admin/organizations

app/jobs/podcasts/get_episodes_job.rb, app/labor/podcast_feed.rb, app/models/podcast.rb, lib/tasks/fetch.rake, spec/jobs/podcasts/get_episodes_job_spec.rb
- moved Podcast#pull_all_episodes to a separate ActiveJob
- deleted unused `PodcastFeed#get_all_episodes` method
#2952, #2497
=> Moved Podcast#pull_all_episodes to a separate ActiveJob #2952 #2497

app/models/article.rb, app/models/comment.rb
1. Clear the Rails cache for a destroyed comment's ancestors. This will hopefully resolve some caching issues that are caused by comments being destroyed.
2. Add `dependent: :destroy` for `buffer_updates` so there aren't any orphaned `buffer_updates` that cause issues in `/internal/articles`.
=> Clear Rails cache for destroyed comment's ancestors and destroy buffer_updates for articles

app/assets/javascripts/initializers/initializeEllipsisMenu.js, app/controllers/articles_controller.rb, spec/requests/articles_update_spec.rb
We were getting an "improper http loaded to https" issue, which is kind of related to a broader handling of how redirects are handled via ajax on our site.
But the reason this was inducing a redirect had to do with a different logical error. This fixes it up. Could be cleaner but this is solid and adds a test.
Also took the time to add a better visual response to muting a thread—which is related to this area of the code and needed to be improved.
Fixes #2995
=> Fix improper archive redirect

app/javascript/article-form/elements/moreConfig.jsx
Without the space between these two elements, this shows up as Change meta tag`canonical_url`.
https://github.com/prettier/prettier/issues/4223#issuecomment-380093772 describes how composing JSX elements over multiple lines needs `{' '}`.
I haven't actually tried this myself, but I saw the before image at https://www.cdevn.com/why-medium-actually-sucks/:
and looking at the code, I could see why it looked that way, and what to do to fix it.
=> Add a space between "Change meta tag" and canonical_url

db/seeds.rb
ActiveJob jobs are executed inline during `rails db:reset` which means that the app now that https://github.com/thepracticaldev/dev.to/pull/3057 is in, tries to fetch 1000 episodes from each Podcast, which is really slow if successful at all (it crashed after a while on my machine). 
This PR disables fetching during seeding. Episodes can be fetched with `rails get_podcast_episodes` task if needed for local testing.
I know @lightalloy is working on improving Podcast fetching but I believe this was an unintended side effect of the good work she's doing.
The fact that we have to disable a callback it's also a good argument against doing this kind of things in callbacks which hides a lot of business logic in the first place (by separating creation of an object and fetching of dependent …
=> Disable Podcast episodes fetching during seeding

app/controllers/additional_content_boxes_controller.rb
Currently, `AdditionalContentBoxesController#randomize` is a `public` method and it does not make a lot of sense to leave it `public`. This PR makes it `private` as it is only used in `AdditionalContentBoxesController`
=> Make `AdditionalContentBoxesController#randomize` private

app/assets/stylesheets/readinglist.scss
This fixes the input's color of the reading list filters in night theme ( or any future theme that does not have black as theme color )
before
after
=> Fix reading list filters input's color in night theme

app/controllers/api_secrets_controller.rb, app/views/users/_account.html.erb, config/routes.rb, spec/requests/api_secrets_destroy_spec.rb
I'm not 100% sure why but it seems that putting the ID as a keyword parameter for a `DELETE` does not play nice with Rails. I've converted it to use an inline parameter following the same convention Rails uses for any other `DELETE`/destroy action
Closes #3079
=> Fix access token revoking

app/models/user.rb, spec/models/user_spec.rb
Fixes a minor bug where a user's organization memberships were not destroyed when the user was destroyed.
Related #3077
=> Destroy organization memberships if user is destroyed

app/assets/stylesheets/article-show.scss
Bug Fix - Action Space
Buttons Edit and Manage |  Add inline-flex to have action buttons always on same line
Fixes the Action Space Buttons on Mobile to display in the same line. Added `display: inline-flex` to have the elements always maintain the same horizontal space.. causing them to wrap around together when there isn't enough space
Fixes #3061
=> Bug/Action Buttons Fix

app/jobs/slack_bot_ping_job.rb, app/observers/application_observer.rb, app/observers/article_observer.rb, app/observers/organization_observer.rb, app/observers/reaction_observer.rb, app/services/rss_reader.rb, spec/jobs/slack_bot_ping_job_spec.rb, spec/observers/article_observer_spec.rb
Moved SlackBot.delay.ping calls to a separate ActiveJob.
This may seem redundant compared with moving `handle_asynchronous` methods to `ActiveJob`s, but still I think it's worth doing because in such a way:
- we reduce dependency on the DelayedJob 
- it's easier to debug in case of errors
#3136
=> Moved SlackBot.delay.ping calls to ActiveJob #3136

app/controllers/dashboards_controller.rb, app/javascript/analytics/dashboard.js, app/javascript/packs/analyticsDashboard.js, app/javascript/packs/proCharts.js, app/views/dashboards/pro.html.erb
This PR makes the Pro Dashboard work with InstantClick and displays the correct analytics for organizations.
It moves all the code inside functions, removing globals and then loads the "initializer" inside InstantClick `change` event so that the transition between clicks is smooth.
Right now, if you have your own dashboard and your organization's dashboard, clicking between the two doesn't work. Also, if you go from https://dev.to/dashboard to https://dev.to/dashboard/pro from the internal link you have to refresh the page.
Another thing it does is to display the correct analytics for the organization. Right now we never pass the organization ID to the analytics business logic, which means that the data returned it's always that of the user, not that of the organization the user is …
=> Dashboard Pro: support InstantClick and show org analytics

app/assets/stylesheets/chat.scss
The channel with unread messages gets a yellow highlight but the text is hardly readable (See screenshot below). This PR fixes it by making the text black (#0a0a0a).
**Before**
**After**
=> Fix visibility of unread channel name

app/controllers/admin/podcasts_controller.rb, app/models/podcast.rb, db/seeds.rb, spec/factories/podcasts.rb, spec/requests/admin/podcasts_spec.rb
- removed an `after_create` callback for fetching podcast episodes
- added fetching podcast episodes to the admin controller action
- created request specs for podcast creating from `/admin/podcasts/new`
- removed hacks that disable fetching podcasts while seeding and running tests
Creating a podcast and fetching episodes shouldn't be tightly coupled. We sometimes want to create a podcast without fetching episodes, e.g. for tests or for seeding the database.
#2952
=> Removed fetching podcasts from a callback

app/models/podcast.rb, app/models/podcast_episode.rb, db/migrate/20190611102309_add_constraints_to_podcasts.rb, db/migrate/20190611102923_add_unique_indexes_to_podcasts.rb, db/migrate/20190612095748_add_constraints_to_podcast_episodes.rb, db/migrate/20190612095959_add_unique_indexes_to_podcast_episodes.rb, db/schema.rb, spec/models/podcast_episode_spec.rb, spec/models/podcast_spec.rb
Implemented proper validations for podcasts and podcast episodes to avoid failing in the future.
- added model validations: fields presence, `slug` uniqueness, `slug` uniqueness with `username`s and organization `slug`s
- added db constraints
- added validation specs
Before merging need to check that all the `podcasts` and `podcast_episodes` records don't violate the provided constraints (non-null values and uniqueness)
#271
https://github.com/thepracticaldev/team/issues/177
=> Podcasts validations

.vscode/settings.json, app/services/notifications/reactions/send.rb, db/migrate/20190531085252_remove_notifications_unique_index.rb, db/migrate/20190531094609_add_unique_user_id_notifications_index.rb, db/migrate/20190531094926_add_unique_organization_id_notifications_index.rb, db/schema.rb, spec/models/notification_spec.rb, spec/services/notifications/remove_all_spec.rb
- сhanged notifications indexes so that they take into account possible null values in `user_id`, `organization_id`, `action` fields
Postgres allows to create records which contain the same fields if some of them contain null values, so I
- created separate indexes for `user_id` and `organization_id` because notifications has either `user_id` or `organization_id`
- made partial indexes for cases when `action` is null and when it's not null
- added specs to check that notifications are not duplicated even when validations are skipped
Before merging, all the notifications that have duplicate fields `%i[user_id organization_id notifiable_id notifiable_type action]` must be deleted
#2525
=> Change notifications unique indexes #2525

app/models/organization.rb, app/models/user.rb, spec/models/organization_spec.rb, spec/models/user_spec.rb
- validate usernames and organization slugs not only against each other but also against podcast slugs
- added specs to test usernames and org slugs uniqueness and not being equal to reserved words
Podcast `slug`s validation is in another pr #3123
=> Validate usernames and organization slugs against podcast slugs

app/assets/javascripts/initializers/initializeBaseUserData.js, app/assets/javascripts/utilities/userData.js, app/controllers/articles_controller.rb, app/controllers/async_info_controller.rb, app/javascript/analytics/dashboard.js, app/javascript/packs/analyticsArticle.js, app/models/user.rb, app/policies/article_policy.rb, app/services/analytics_service.rb, app/views/articles/stats.html.erb, config/routes.rb, spec/models/user_spec.rb, spec/requests/articles_spec.rb, spec/system/articles/user_visits_article_stats.rb
This PR contains stats/analytics for a single article. 
The feature consists of two parts:
* a "STATS" button, enabled only for the user if they are both the owner and a pro user
* a `/stats` page containing the analytics
NOTE: I'm not sure about wording, titles and links, please let me know if the path of the titles should be different
#3102 
STATS button:
article stats:
=> Pro Analytics: stats for a single article

db/migrate/20190614093041_add_notifications_organization_id_index.rb, db/schema.rb
Added `organization_id` index to the `notifications` table.
Explaining query without an index:
```
Notification.where("organization_id = 3 and read = false").select("count(*)").explain
------------------------------------------------------------------------
Aggregate  (cost=780.32..780.33 rows=1 width=8)
->  Seq Scan on notifications  (cost=0.00..775.94 rows=1753 width=0)
Filter: ((NOT read) AND (organization_id = 3))
(3 rows)
```
With the provided index:
```
Notification.where("organization_id = 3 and read = false").select("count(*)").explain
-----------------------------------------------------------------------------------------------------------------------
Aggregate  (cost=338.36..338.37 rows=1 width=8)
->  Index Scan using index_notifications_on_organization_id on notifications …
```
=> Added organization_id index to notifications

app/services/analytics_service.rb, spec/services/analytics_service_spec.rb
I'm not sure how this is happening on production, but I guess there are page views that have `time_tracked_in_seconds` that is nil for specific articles. If the average results in `NULL` then the analytics page breaks. 
This is a fix for that.
=> Fix analytics grouped by day with nil page views average

app/controllers/internal/feedback_messages_controller.rb, app/controllers/moderations_controller.rb, app/controllers/pages_controller.rb, app/services/mentions/create_all.rb
Rails `pluck` forces an additional SQL query, such query is not always needed when the objects are already in memory or the requested ID is the primary key ID.
=> Performance: save some queries when pluck is not needed

app/assets/stylesheets/article-show.scss
In Safari reader mode, icons become simply huge. I used the **unused** class which is added to icons **only** in reader mode: `.reader-image-tiny`.
Default view: 
Safari reader mode view:
I saw nothing about that.
The same on Apple smartphones
(impatient given that it's my first contribution to this awesome project 🤘)
=> Fix icons size in Safari reader mode

app/controllers/comments_controller.rb, spec/requests/comments_create_spec.rb
Need to create subscription when comment is created (even though we aren't yet using that functionality fully)
=> Create comments notification subscription upon creation

app/models/poll_vote.rb, spec/models/poll_vote_spec.rb
There's a double `presence: true` validator in `PollVote`
=> Remove double presence validator in PollVote

config/environments/development.rb
This should help keeping an eye on the cases where too many records are accidentally loaded in a single query. The comment has been taken from https://guides.rubyonrails.org/configuring.html
=> Add warn_on_records_fetched_greater_than setting in development [skip ci]

app/assets/stylesheets/article-show.scss
I just tried out night mode today (I know, I'm slow... 😋) and I realized that `<hr/>` elements are not that visible:
A little comparison with the default/minimal light/pink theme:
I am proposing to change it to something like this:
So that it reflects night theme. It should not change anything on the default/minimal light/pink theme tho, since it isn't contrast to the background.
I'm not quite sure if what I'm doing with the `themeable` is correct, so let me know. Also if there's a better color suggestion. Thank you.
- None
- None
=> fix(article): `<hr>` should be visible in night theme

app/observers/application_observer.rb
The slack channel `warned-user-activity` was renamed to `warned-user-comments` but not in the code, so the `SlackBot` was unable to send messages to the channel which causes errors `The slack API returned an error: channel_not_found (HTTP Code 404)`
=> Updated slack channel name

app/services/streams/twitch_webhook/register.rb, spec/services/streams/twitch_webhook/register_spec.rb
I had fixed the error when twitch returns no data earlier in #2865
Sometimes twitch returns empty data, we should handle this situation as well.
#2784
#2865
=> Don't try to register webhook when twitch returns empty data

app/models/user.rb, spec/models/user_spec.rb
Stack overflow has 4 sub communities: Spanish, Russian, Japanese and Portuguese. This PR will make it possible to link a profile in one of these communities as well.
Fix #3204
=> Allow stackoverflow sub communities profiles

app/models/mention.rb, spec/factories/mentions.rb, spec/mailers/notify_mailer_spec.rb, spec/models/mention_spec.rb
- fixed `Mention.new.valid?` failing on `undefined method for Nilclass`
- creating a valid mention when using a factory
=> Fix mention validation when validating an empty instance

app/controllers/classified_listings_controller.rb
Right now we're calling the same query twice when we could just call it once and even avoid creating Ruby objects that get instantly discarded
=> Dashboard listings: optimized queries

app/controllers/dashboards_controller.rb, app/views/dashboards/_dashboard_article.html.erb, spec/requests/dashboard_spec.rb
Shows the stats button in the article's dashboard if the current user is a pro user
=> Add article pro stats button in dashboard

app/liquid_tags/liquid_variable.rb, app/services/rss_reader/assembler.rb
- Pre-escape `{{ }}` expression that is breaking MarkdownParser with backtick.
- Loosen up RssReader's youtube id parsing logic.
https://github.com/thepracticaldev/dev.to/issues/3070
=> Update RssReader's liquid & youtube parsing logic

app/assets/stylesheets/notifications.scss, app/models/comment.rb, app/views/comments/index.html.erb, app/views/notifications/_notifications_list.html.erb, spec/models/comment_spec.rb
This adds fixes a bug where a comment's `title` attribute returns some of the comment's text even if it is deleted.
Also fixes a small bug for notification cards where the whole notification card `<div>` showed the pointer cursor.
=> Delete a comment's title if it is deleted

app/models/comment.rb, app/services/notifications.rb, app/services/notifications/remove_each.rb, spec/models/comment_spec.rb, spec/models/notification_spec.rb, spec/requests/stories_index_spec.rb
This adds additional data to comment notifications, specifically data regarding it's ancestors. The data lays the groundwork for more informative and useful comment notifications.
Also:
- Updates descendant comment notifications properly to make sure their associated notification data deleted as well
- changed mention `notifications.destroy_all` to `.delete_all`
=> Add context data to comment notifications

app/assets/stylesheets/articles.scss, app/assets/stylesheets/comments.scss, app/assets/stylesheets/notifications.scss, app/models/comment.rb, app/views/comments/index.html.erb, app/views/notifications/_comment.html.erb, app/views/notifications/index.html.erb, app/views/notifications/shared/_comment_box.html.erb, spec/models/comment_spec.rb, spec/requests/comments_spec.rb, spec/requests/notifications_spec.rb
Add more context to notifications and single comment page.
=> Add comment context for notifications and comment pages

app/services/notifications/new_comment/send.rb
This fixes a strange bug where `comment.title.strip!` would return `nil`, and thus `CGI.unescapeHTML(nil)` would result in a run time error.
I'm not sure why it's an issue now as opposed to before though 🤷‍♂️
Resolves #3272
=> Return original body instead of nil for new comment push notifications

app/models/comment.rb, app/views/comments/index.html.erb, app/views/notifications/shared/_comment_box.html.erb
I've noticed an escaping issue in the new comment view. This fixes it
Before
After
=> Comments: remove double stripping undoing escaping

app/controllers/concerns/classified_listings_toolkit.rb, app/jobs/classified_listings/bust_cache_job.rb, app/jobs/events/bust_cache_job.rb, app/jobs/organizations/bust_cache_job.rb, app/jobs/pages/bust_cache_job.rb, app/jobs/podcast_episodes/bust_cache_job.rb, app/jobs/podcasts/bust_cache_job.rb, app/jobs/tags/bust_cache_job.rb, app/labor/cache_buster.rb, app/models/event.rb, app/models/organization.rb, app/models/page.rb, app/models/podcast.rb, app/models/podcast_episode.rb, app/models/tag.rb, spec/jobs/classified_listings/bust_cache_job_spec.rb, spec/jobs/events/bust_cache_job_spec.rb, spec/jobs/organizations/bust_cache_job_spec.rb, spec/jobs/pages/bust_cache_job_spec.rb, spec/jobs/podcast_episodes/bust_cache_job_spec.rb, spec/jobs/podcasts/bust_cache_job_spec.rb, spec/jobs/tags/bust_cache_job_spec.rb, spec/labor/cache_buster_spec.rb, spec/models/event_spec.rb, spec/models/organization_spec.rb, spec/models/page_spec.rb, spec/models/podcast_episode_spec.rb, spec/models/podcast_spec.rb, spec/models/tag_spec.rb, spec/requests/internal/classified_listings_spec.rb
- that calls cache_buster service
- specs for jobs + service
- for: classified listings, events, organizations, pages, podcast_episodes, podcasts, tags
- refactoring (models, service)
Move bust_cache methods in their own jobs
#2497
=> Move bust_cache methods in own jobs

app/models/article.rb, spec/models/article_spec.rb
Solves #3035 
This commit increases the `tag` length limit from 20 to 30 chars and also increases the `cached_tag_list` length limit to 126 chars aiming to maintain the four tags limit. Specs were adapted to respect the changes.
=> 3035 - Increase tag length limit from 20 to 30 chars

app/javascript/history/history.jsx, app/models/page_view.rb
Right now the history items are duplicated, because each visit counts separately. 
To properly show a history page (like a browser's history) those items need to be de-duplicated. By building the index with `distinct: true` the default response is only unique visits.
Keep in mind that the separate entries are still in the index (they can be accessed with `distinct: false` in the query).
Maybe in the future we can add statistics of frequency (for example: "here's the top 10 articles you visit") but that's another separate feature.
**for whomever is going to merge this: the index for the history (model `PageView` and index name `UserHistory`) needs to be rebuilt**
#3220 
**Before**
**After**
**What happens when you visit again an article that you've already visit**
Notice how the article …
=> Pro: Deduplicate history items

app/views/social_previews/article.html.erb, app/views/social_previews/listing.html.erb, app/views/social_previews/tag.html.erb, app/views/social_previews/user.html.erb, spec/requests/social_previews_spec.rb
This PR improves the social card caching. ⚡️ 
Since we use the generated HTML as the [cache key for social cards](https://github.com/thepracticaldev/dev.to/blob/bfa1bdc37f4bf33c76d767ed815e30a384b369e0/app/lib/html_css_to_image.rb#L16), if there is any randomness at all, it makes the hit rate really low (caches keep regenerating).
This PR adds tests for randomness (to avoid regressions), plus removes the `aria` tags from the SVG (which were random & not needed when generating an image).
Social card endpoint will better use memcached & be even faster. ⚡️
=> Improve social card caching 🚀

app/javascript/readingList/readingList.jsx
Add a count of articles beside the reading list header. This is different from the reading list count in the main page as this will only displays the count of articles based on the `statusView` so the count depends on the number of articles in that view.
Resolves #3124
=> Add Item Count to Reading List Header

app/controllers/users_controller.rb, config/routes.rb
`redirect_to` in `users_controller.rb` was using a hardcoded route path, so I just changed it to using a dynamic route name path
=> use dynamic route name

app/services/notifications.rb, app/views/notifications/_article.html.erb, spec/requests/notifications_spec.rb
This fixes an issue where an article notification was showing the `created_at` date instead of the `published_at` date. I also added some minor adjustments to handle it the way we usually handle notification data.
Resolves #3300
=> Use publish date for article notifications

app/labor/markdown_parser.rb, app/models/comment.rb, spec/models/comment_spec.rb
Added rel="nofollow" to links when parsing the markdown in comments only.
Resolves #3236
=> Add rel="nofollow" to links in comments

app/javascript/listings/listings.jsx
- Handles escape key exit by passing event from KeyDown method to CloseModal method and checking for key value and openedListing state.
- Adds space before name in messaging modal
resolves #3302 
resolves #3303
=> Fix escape key handling and add space in single listing view

app/views/dashboards/_dashboard_article.html.erb, spec/requests/dashboard_spec.rb
This prevents non-authors (org admins, DEV admins, for example) from seeing the delete button in the dashboard and manage views. We currently don't allow org admins and DEV admins to delete other people's posts to begin with; this PR gets the UI to match the backend.
=> Hide delete article button for non-authors

docs/backend/admin.md
According to the Admin Policy, user can see `/admin` page only if `ApplicationPolicy#user_admin?` is `true`. And the [definition](https://github.com/thepracticaldev/dev.to/blob/7ee0350ac525ede462d98d5af7d27b55246f0c50/app/policies/application_policy.rb#L67) of this method, requires for user to have `:super_admin` role, and not :admin role as stand in the documentation
Related [document](https://docs.dev.to/backend/admin/)
=> Documentation update for Admin panel, on Backend instructions

app/javascript/readingList/readingList.jsx
I noticed the count for the reading list header displayed '0' when the reading list is empty. To keep things consistent with the item count on the sidebar. I changed the count to display 'empty' when the reading list is empty. This had been mistakenly omitted with the original PR for adding the item count.
=> Make item count 'empty' instead of '0' when reading list is empty

app/controllers/internal/users_controller.rb, app/models/credit.rb, app/views/internal/users/_credits.erb, spec/requests/internal/users_spec.rb
This fixes an issue where we couldn't give credits to organizations, if the user did not have an `organization_id`. Also adds some tests for adding credits via internal.
=> Fix org credits in internal view

app/controllers/internal/tags_controller.rb, config/routes.rb, spec/requests/internal/tags_spec.rb
This adds the `GET /internal/tags/:id` was accidentally removed. 😅 Also removes `GET /internal/tags/:id/edit` route and controller action, since there wasn't a view for it (we use the show page as the edit page).
=> Add GET /internal/tags/:id route back in

app/uploaders/profile_image_uploader.rb, spec/requests/user_settings_spec.rb
Set max file size limit to 2MB for profile images.
Resolves #3271
=> Set max file size limit for profile images

app/assets/javascripts/utilities/browserStoreCache.js
If cookie is disabled, our use of localStorage will break the page.
Resolves https://github.com/thepracticaldev/dev.to/issues/3298
With cookies disabled
=> Disable use of localStorage when cookie-less

app/models/user.rb, spec/models/user_spec.rb
The current rule does not consider 2 scenarios:
1- Instagram adds a tailing slash to the URL, users who copy paste their URL will be confused when they get "URL not valid error".
2 - Instagram allows no consecutive periods between the characters, also uppercase letters.
Example of profile that won't pass the current implementation
- https://www.instagram.com/dr.Cocktail/
- https://www.instagram.com/mr.america/
=> Fix instagram URL validation rule

app/views/pages/terms.html.erb
This PR adds IDs to all of the Header tags (<h3>) on the terms page so it makes it easier to link someone to a particular section of the terms (i.e. the content policy)
n/a
n/a
=> add ids to terms page so each clause can be linked to directly

app/views/dashboards/_dashboard_article.html.erb
Adds `time` tags to the article publish dates on the user dashboard. This will make the dates on this page easier for machines to parse which can help with accessibility _and_ let folks know the exact date/time they published an article by hovering over it.
I haven't created an issue for this, but I can. It was something I noticed the other day and felt like it was some low-hanging fruit.
This is my first PR to Dev.To and first time setting it all up locally, so please bare with me! 🙏 I didn't notice any view specs or anything that I should add to for this change, but if I'm missing something here I'd be happy to add tests.
Thanks!
=> Use time tags for article publish dates on user dashboard

app/controllers/internal/users_controller.rb, app/models/backup_data.rb, app/models/identity.rb, app/models/user.rb, app/views/internal/users/edit.html.erb, app/views/users/_account.html.erb, config/initializers/reserved_words.rb, config/routes.rb, db/migrate/20190703003817_create_backup_data_table.rb, db/schema.rb, spec/factories/identities.rb, spec/models/backup_data_spec.rb, spec/requests/internal_users_spec.rb
This PR adds the ability for admins to remove identities, as well as recover them. There are instructions in the view that explain the situation(s) when an identity should be removed.
This also adds the groundwork for backing up data via a database table, which is essentially a table like this:
| instance_type | instance_id | instance_user_id | json_data |
| ------------- | ------------- | ------------- | ------------- |
| identity | 1 | 1 | `{ id: 1, uid: 1, auth_data_dump: { lots_of_data } }` |
=> Add functionality to remove and recover identity

app/controllers/articles_controller.rb, spec/requests/articles_update_spec.rb
This fixes an issue where some notifications will linger if an article is published and then unpublished.
=> Remove notifications if article is unpublished

spec/requests/notifications_spec.rb
Escape `comment.title` to fix failing spec in the master build:
=> Escape comment.title to fix failing spec

.travis.yml, app/views/articles/_sidebar_additional.html.erb, app/views/devise/registrations/_registration_form.html.erb, app/views/layouts/_nav_menu.html.erb, app/views/layouts/_signup_modal.html.erb, app/views/shared/_github_sign_in_button.html.erb, app/views/shared/_twitter_sign_in_button.html.erb, app/views/stories/_sign_in_invitation.html.erb, app/views/users/_account.html.erb, app/views/users/_github_sign_in_button.html.erb, app/views/users/_profile.html.erb, app/views/users/_twitter_sign_in_button.html.erb
There's an old vulnerability that has been promoted to a CVE recently, which is blocking all builds. 
Basically omniauth links with GETs are in some cases subject to CSRF attacks.
Unfortunately there's no agreed upon solution at present. There's a gem that mitigates the problem but it conflicts with a [patch in our codebase](https://github.com/thepracticaldev/dev.to/blame/master/config/initializers/persistent_csrf_token_cookie.rb), in addition to the fact that I can't verify this gem is working correctly since we don't use Omniauth directly.
My proposed solution is this PR:
- convert all sign in links to POSTs
- ignore the CVE until a more permanent solution is found, I'll keep monitoring the issue in the foreseeable future
- https://github.com/omniauth/omniauth/pull/809 and discussion
- …
=> Mitigate CVE 2015-9284

app/views/api/v0/articles/show.json.jbuilder, spec/requests/api/v0/articles_spec.rb
When creating an article with the v0 API the article is defined in markdown, however when retrieving that article the markdown is not available, which makes it difficult for consumers of the API that need to read the frontmatter.
=> Add markdown to article api response

app/controllers/admin/sponsorships_controller.rb, app/controllers/admin/tags_controller.rb, app/dashboards/dashboard_manifest.rb, app/dashboards/sponsorship_dashboard.rb, app/dashboards/tag_dashboard.rb, app/models/organization.rb, app/models/sponsorship.rb, db/migrate/20190710081915_create_new_sponsorships.rb, db/schema.rb, lib/tasks/temporary/sponsorships.rake, spec/factories/sponsorships.rb, spec/models/organization_spec.rb, spec/models/sponsorship_spec.rb
Adding the `Sponsorship` model to better track various sponsorships.
The functionality will be split in 3 different PRs:
1. add the sponsorship model and migrate the data to such model, without touching the UI (this PR)
2. replace the current sponsorship code using the Sponsorship model - https://github.com/thepracticaldev/dev.to/pull/3440
3. remove previous sponsorship columns from `Organization` and `Tag` (PR to be written)
I thought about merging step 1 and step 2 into a single PR but it would mean that the website would not display sponsorships right after step 1 until the migration script is run. If that's not a problem, I'll merge the two PRs, let me know.
This PR contains the following things:
- adds the concept of sponsorship to the models and exposes it to Administrate
- most …
=> Sponsorship: add model (step 1)

app/views/pages/information.html.erb
Fixes #3456.
Styling applied to social links is based on the solution from PR #2209.
Before:
After:
=> Add inverted styling for social links in night mode on 'Key Links' page

app/views/pages/badges.html.erb
Added missing `class="dev-badge"` for DEV badges on [this page](https://dev.to/p/badges). This makes the badges display correctly, in white, when night mode is enabled. See the screenshots below for reference.
I also added a missing `alt` to one of the badges, for accessibility reasons, and removed an unnecessary tag closing.
On the page, we give instructions for how users can implement the DEV badge on their own website. However, this is only for the black DEV badge, since I guess there are no actual white ones (the `class="dev-badge"` only adds a filter for night mode.
Should we somehow explain how a white badge can be achieved as well—like the one they're seeing if they're using night mode—or should we leave this for the user to figure out?
**Before**:
**After**:
=> Add missing "dev-badge" class for proper night mode styling

app/views/articles/_actions.html.erb
Ampersand is not escaped on Twitter share from the hamburger menu.
Resolves #3451
N/A
=> Fix ampersand not being escaped in Twitter share from the hamburger menu

app/controllers/pages_controller.rb, spec/requests/pages_spec.rb
This fixes a bug where the latest published welcome / challenge thread SQL query was pulling the last article by ID and not by publish date.
=> Redirect to actual latest published thread

app/labor/cache_buster.rb, app/services/moderator/manage_activity_and_roles.rb
TLDR; this fixes a bug where articles that were cleared with the `CacheBuster.bust_article` method did not have it's direct path `article.path` cleared.
Along with the fix above, I wanted to test out a new method of clearing caches -- credit to @maestromac for thinking of this. We rely on "manual cache clearing", which basically means we clear caches by URL directly. Fastly has a gem that's fairly old, but does a lot of cache clearing under the hood.
Anyway, it has a `purge` method which clears/purges the cache for you, theoretically. I think it's fairly safe to use it, but figured we should test it out in the banisher first. If we agree that it's a good way of clearing caches, I think we should move our from direct URL cache clearing to this, or use a combination of both.
=> Cache bust the article's path and add minor improvement for banishing

app/javascript/article-form/articleForm.jsx, app/javascript/article-form/elements/hotkeyLinstener.jsx, app/javascript/article-form/elements/keyboardShortcutsHandler.jsx
hotkey for toggle article preview <kbd>command shift p</kbd> for mac and <kbd>control shift p</kbd> for window.
I implement `HotkeyLinstener` for handle keyboard shortcuts because I think it's better to separate of concern so that `ArticleForm` component doesn't do too many thing. (more easy to maintenance in my opinion). In React, I'd use custom hook for doing this. (I'm not sure preact have hooks or similar concept). I'd love to hear you thought on this one.
I have some concern, one concern is `componentWillUnmount` doesn't fire when I change route(I tried on other component, e.g., [Listings component](https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/listings/listings.jsx), and it also doesn't fire  `componentWillUnmount`.  so event listener can't be removed. Any …
=> Add support for hotkey to toggle article preview

app/assets/stylesheets/preact/article-form.scss, app/javascript/article-form/elements/imageManagement.jsx, app/views/articles/edit.html.erb, app/views/articles/new.html.erb
Add copy button beside to Markdown Image upload section. Now a user can click the copy button or click the input field with the URL and have the content automatically copied. 
I was unable to test my code on iOS but I followed the example of the article dropdown menu.
Resolves #1313
* Chrome
* Firefox
=> Add copy button to markdown image upload

lib/tasks/temporary/podcasts.rake
We need to re-check the podcasts' availability and set the episodes' and podcasts' statuses accordingly. The task goes through the podcasts that were marked as possibly unplayable before and schedules jobs to re-check them.
The task needs to be run once.
#2952
=> A temp rake task to update podcast statuses

app/views/pages/sponsors.html.erb
This fixes a bug where the order of sponsors was not correct. TIL that `.find_each` nullifies some SQL queries, like `.order` and `.select`, for example.
I originally had a test to go with this but it added 9 to 13 seconds. to our CI. IMO it's just not worth it...
```ruby
describe "GET /sponsors" do
it "shows the sponsors in order of their featured number" do
3.times do |i|
create(:sponsorship, level: "gold", blurb_html: "gold-sponsor-#{i + 1}", featured_number: i + 1)
end
get "/sponsors"
html = Nokogiri::HTML(response.body).search(".body")
Approvals.verify(html, name: "sponsors", format: :html)
end
end
```
=> Use each instead of find_each to keep order

app/assets/javascripts/initializers/initializePodcastPlayback.js
Don't show a warning when a user is playing a podcast and opens a link in a new tab with ctrl + click.
I thought of a case when a user opens a new page with another shortcut, but the fix should handle most situations.
#2958
=> Open a page in a new tab w/o warning when playing a podcast #2958

app/views/podcast_episodes/show.html.erb, lib/tasks/temporary/podcasts.rake, spec/system/podcasts/user_visits_podcast_episode_spec.rb
There are no podcasts left with the "This podcast may not be playable in the browser" status notice, so in this pr I removed the logic related to it. The new status notices are more specific about the podcast's status.
I have also removed the temporary task to update podcasts' statuses.
#2952
=> Remove logic relying on old podcast status

app/views/classified_listings/_form.html.erb
Adds target=_blank to buy credit links in create a listings page to open in new tab/window.
#3454 
N/A
=> Open "buy credits" link in new tab in creating listings

.travis.yml, spec/services/analytics_service_spec.rb, spec/services/credits/ledger_spec.rb, spec/services/notifications/reactions/send_spec.rb
We faced a problem in the #3449 pr build. Some of the tests related to time checking fail on Travis.
You can reproduce the problem by checking out the branch and running all the service specs:
```
bundle exec rspec spec/services
```
Fixes
- made notifications reactions tests more "confident" about the time
- use `Timecop.freeze` to avoid timezone issues
- compare time in seconds for credits ledger spec
- `date` in `before_install` to see in which moment in time the CI build has run
#3449
=> Make unsure specs more confident about time

app/controllers/stories_controller.rb, app/services/messages/send_push.rb, app/services/notifications/new_follower/send.rb, app/services/suggester/users/sidebar.rb, spec/services/messages/send_push_spec.rb
`pluck` is very useful to load in memory a list of IDs, without building AR objects in the process.
However, in the case of `WHERE id IN ()` statements, AR, combining lazy loading and magic, will build the correct subquery instead of loading AR objects, effectively using 1 instead of 2 queries (the one to select the IDs and the one to filter the other set).
Hence, if those IDs are not needed for other purposes, `pluck` has no real advantage.
=> Remove unnecessary `pluck` calls

app/liquid_tags/link_tag.rb, spec/liquid_tags/link_tag_spec.rb
Remove the call to strip_tags on the title of the article, because the string gets escaped a second time in `/app/views/articles/_liquid.html.erb`.
Fixes #3508
=> Remove double string escape by removing stip_tags from title

app/liquid_tags/spotify_tag.rb, app/views/pages/api.html.erb, spec/liquid_tags/spotify_tag_spec.rb
Currently the Spotify tag takes a playlist URI, but it's a bit cryptic and was not added to the editor guide at the time. I played around with it and it seems for whatever reason that there is now a simpler way to embed playlists.
My guess is that the previous iteration relied on Spotify's playlist URI `spotify.com/user/:username/playlist/:playlist_code` which they have now updated to something simpler: `spotify.com/playlist/:playlist_code`
Also updates the API page with the latest info on publishing under an organization.
=> Refactor the Spotify playlist option

app/jobs/podcasts/get_episodes_job.rb, app/models/podcast.rb, app/models/podcast_episode.rb, app/services/podcasts/feed.rb, db/migrate/20190723094834_add_index_to_podcasts_episodes.rb, db/schema.rb, spec/jobs/podcasts/get_episodes_job_spec.rb, spec/jobs/shared_examples/enqueues_job.rb, spec/models/podcast_spec.rb, spec/requests/podcast_episodes_api_spec.rb, spec/requests/stories_index_spec.rb, spec/services/podcasts/feed_spec.rb, spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
- display unreachable podcasts on the site if they have reachable episodes
- recheck episodes' urls when podcast status is set from reachable to unreachable
- added index to `podcast_episodes.podcast_id`
#2952
=> Don't hide podcasts if they have reachable episodes

app/javascript/packs/onboardingRedirectCheck.jsx
This fixes an issue where `window.currentUser` and `window.csrfToken` was no longer available on every page.
I'm not sure we need that info on every page, but this will resolve a critical bug we currently have.
=> Make window.currentUser available globally

app/controllers/internal/podcasts_controller.rb, app/models/podcast.rb, app/models/role.rb, app/views/internal/podcasts/edit.html.erb, app/views/internal/podcasts/index.html.erb, app/views/layouts/internal.html.erb, config/routes.rb, db/schema.rb, spec/models/podcast_spec.rb, spec/requests/internal/podcasts_spec.rb
- defined Podcast admins
- implemented basic internal podcasts section
- adding and removing podcast admins from `internal`
I implemented a basic user interface similar to adding tag moderators, it can be improved, at least adding admins by their usernames.
#3537
=> Podcast ownership

app/models/article.rb, app/models/comment.rb, app/models/user.rb, spec/models/article_spec.rb, spec/models/comment_spec.rb, spec/models/user_spec.rb
- refactor calls to use built-in algolia Active Job
- add spec
Refactored the delayed calls in the trigger_delayed_index by using the built-in AlgoliaJob class provided by the Algolia API.
#3136
=> Move delayed algoliasearch tasks to Active Jobs

app/javascript/packs/onboardingRedirectCheck.jsx
This was another bit of functionality tacked into the `onboarding` script erroneously, and then removed when we migrated this file.
This functionality should be loaded elsewhere but for now just getting things back to the old status quo.
=> Add getunopenedchatchannels to onboardingredirect

app/assets/stylesheets/article-show.scss
The clipboard copy icon in the dropdown share menu was out of place on Chrome. I adjusted the min-width and this looked to resolve the issue.
Resolves #2982
* On Chrome
* On Firefox
=> Fix out of place clipboard-copy icon

Gemfile, Gemfile.lock
Bundler is at 2.0.2 which is supported by Heroku and doesn't need the HTTPS hack.
If you're using a custom buildpack set on an older version of Bundler please ignore and close this.
1. [Heroku - Ruby apps with Bundler 2.x now receive version 2.0.2](https://devcenter.heroku.com/changelog-items/1656)
2. [Heroku - Bundler version](https://devcenter.heroku.com/articles/bundler-version)
=> Update Bundler to 2.0.2

app/services/notifications/welcome_notification/send.rb, app/views/notifications/_broadcast.html.erb
We created the "broadcast" feature with the idea of doing more than just the welcome message, but we also implemented this to only account for the welcome message to this point. This expands the behavior so that we _can_ send alternate types of welcome messages. We still don't have the rest of it in the app but we can at least experiment with this functionality manually now.
This would send any broadcast, including the welcome one if it is passed in. But we can now send other broadcasts this way. (And should likely change the name of this module if we are to keep this structure)
```ruby
Notifications::WelcomeNotification::Send.call(1, Broadcast.last)
```
I added the `title` to the JSON, which will load as `nil` for now so shouldn't break the old functionality.
The line
```
if …
```
=> Allow for the sending of arbitrary broadcasts

app/models/comment.rb, app/models/user.rb, spec/models/comment_spec.rb, spec/models/user_spec.rb
Fixed ActiveJob `DeserializationError`s which appeared after merging #3486
Actually, on `User` and `Comment` destroy, records are removed from the index `synchronously` in `before_destroy` callbacks, so there's no need to do anything in `trigger_index` or `trigger_delayed_index` when `remove` is `true`.
=> Fix failing algolia jobs

app/models/article.rb, spec/models/article_spec.rb
The video duration on DEV videos posts cut off any hours. I added the option of hours to display if a video is long enough. For testing, I added test cases to verify if it converted the given seconds to expected time format with hours.
Resolves #3375
=> Fix Video Duration to include hours

db/migrate/20190410124957_add_index_to_ahoy_messages_to.rb, db/schema.rb
Sometimes delayed jobs fail with the timeout error on this request:
```sql
SELECT COUNT(*) FROM "ahoy_messages" WHERE "ahoy_messages"."to" = $1 AND (sent_at > '2019-04-10 08:44:40.736979')
```
I added index to optimize it. It would also be useful to remove old rows from the table from time to time if that's acceptable.
Adding an index can take a long time if the table is large, which I suppose to be true (same as with `notifications`)
#1621
=> Add index to ahoy_messages to

db/schema.rb
The columns `users.cached_chat_channel_memberships` and `users.summary_html` do not exist in the current version of master. They were wrongly added in #3269 
See https://github.com/thepracticaldev/dev.to/pull/3269/files#diff-1acd2e7e27a227829d5d14a91c863bb6R898 and https://github.com/thepracticaldev/dev.to/pull/3269/files#diff-1acd2e7e27a227829d5d14a91c863bb6R1015
@bolariin noticed this problem while working on https://github.com/thepracticaldev/dev.to/pull/2873 and I've personally tried to reset the DB to the current master and then run the migration in #2873 with no avail since the `summary_html` column is present, the migration then fails locally
They should be safe for removal. They are not part of any existing migration
They shouldn't be present in the production DB for obvious …
=> Remove columns that don't existing from schema.rb

.travis.yml, Gemfile.lock, spec/support/initializers/capybara.rb
I thought it was alright to downgrade Chromedriver to 73 but that ends up being incompatible with my local machine's Chrome 76, hence this update. Capybara's config also need to be updated or else headless does not work.
n/a
n/a
=> Update to Chromedriver 76

app/controllers/admin/podcasts_controller.rb, app/controllers/api/v0/podcast_episodes_controller.rb, app/controllers/podcast_episodes_controller.rb, app/controllers/stories_controller.rb, app/dashboards/podcast_dashboard.rb, app/models/podcast.rb, app/models/podcast_episode.rb, app/views/internal/podcasts/index.html.erb, app/views/layouts/internal.html.erb, db/migrate/20190801083510_add_published_to_podcasts.rb, db/schema.rb, lib/tasks/fetch.rake, spec/factories/podcasts.rb, spec/models/podcast_episode_spec.rb, spec/models/podcast_spec.rb, spec/requests/admin/podcasts_spec.rb, spec/requests/podcasts/podcast_show_spec.rb, spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
- added `published` field to podcasts to prepare for user-added podcasts on the site
- display only published podcasts
- display `published` in admin and internal, edit `published` in admin
- fetch only `published` podcasts
- update all existing podcasts as published, for the new ones the field needs to be set explicitly
#3537
=> Introduced published field to podcasts

config/initializers/doorkeeper.rb
For security purposes I'm proposing to active hashing for OAuth2 access tokens.
Even if they have a temporary validity (2 hours) and at present could seem like an unnecessary precaution, Doorkeeper allows us not to store the tokens themselves but an hash. 
Doorkeeper, in addition, allows us to store encrypted application secrets but there's currently an issue that's going to be fixed in [doorkeeper 5.2.0](https://github.com/doorkeeper-gem/doorkeeper/blob/master/CHANGELOG.md#520rc1) where the secrets are not shown during creation on the website. Once that's out I'd like to enable encryption of application secrets as well, because they are effectively passwords that are always valid, as the [Doorkeeper docs explain](https://doorkeeper.gitbook.io/guides/security/token-and-application-secrets) …
=> Hash OAuth2 access tokens

app/controllers/podcast_episodes_controller.rb, config/routes.rb, spec/requests/podcasts/podcast_episodes_index_spec.rb
Surrogate keys right now contain a bunch of nil, because `record_key` is an attribute.
I've also loaded podcasts to avoid N+1 and added /podcasts to the website, since right now leads to a 404 page.
=> Fix podcasts episodes surrogate key and add "/podcasts"

app/models/article.rb, spec/models/article_spec.rb
It looks the problem was from `article.save` in `article_creation_service`. https://github.com/thepracticaldev/dev.to/blob/4689cdd266e7e678511e733d24c719d9f89948cd/app/services/article_creation_service.rb#L24
This was because of `tags_used` in `MarkdownParser` would raise an error which was not properly handled. 
https://github.com/thepracticaldev/dev.to/blob/4689cdd266e7e678511e733d24c719d9f89948cd/app/labor/markdown_parser.rb#L87-L96
It looks like this error affected other liquid tags.
Resolves #3511
=> Improve Error Message for malformed Github Repo Links

app/liquid_tags/codepen_tag.rb, spec/liquid_tags/codepen_tag_spec.rb
Change CodePen usernames regex to allow up to 30 characters.  ~~I didn't see that character limit was explicitly tested in `codepen_tag_spec.rb` so I'm assuming it's fine to leave it that way.~~ 
Fixes #3487
My first open source commit!
=> Allow CodePen usernames to be up to 30 characters long

app/labor/markdown_parser.rb, spec/labor/markdown_parser_spec.rb, spec/support/fixtures/approvals/user_preview_article_body.approved.html
The error had to do with space and indententation matter with text inside numbered lists. Also, the backticks have to be aligned vertically. When the substitution happens with adding `{% raw %} .. {% endraw %}`, some of the space surrounding the codeblock is lost so the backticks are no longer aligned. I updated the code to preserve the any space character before the backticks.
Resolves #3437
=> Resolve error with code blocks in numbered lists

config/routes.rb
When user get '/:username/:slug/comments/new' or '/:username/:slug/comments/new/:parent_id_code', the user will see 500 Error page.
(ex in development) /ashleigh_wolff/a-farewell-to-arms-113f/comment/new
This error is caused by NoMethodError, because CommentsController don't have "new" method.
I think it should be ActiveRecord::RecordNotFound or Routing Error, and user should get 404 Error page.
=> Remove dead routes

README.md, docs/getting-started/committing.md, docs/getting-started/readme.md, docs/getting-started/start-app.md, docs/getting-started/workflow.md, docs/installation/docker.md, docs/installation/gitpod.md, docs/installation/readme.md
We were starting to have duplicate info between the docs and readme. This shortens the readme but keeps the standard installation, and moves everything else to docs. 
- Remove GitPod installation from readme (it's in docs already)
- Remove Docker installation from readme (its also in docs)
- Point ppl to docs if they want installation guide for GitPod & Docker
- Add engineering standards to docs and remove from readme
=> clean up readme and docs

app/views/users/_sidebar_additional.html.erb, spec/requests/user_profile_spec.rb
Allow emoji in the description for GitHub repos pinned on a user's profile.
Resolves #238
=> Allow emoji in pinned repo description

app/assets/stylesheets/settings.scss, app/views/users/_org_admin.html.erb
In order to improve the copy of the organization secret in desktop and mobile devices, a button is being added besides the secret field to copy them to the clipboard. If you prefer you can just click on the secret to copy them automatically.
I could not login with GitHub account from my iPhone on safari to test the feature, so if someone can test or help me to login on an iPhone I appreciate.
Fixes #3568
=> Add button to copy org secret to clipboard

app/javascript/article-form/elements/imageManagement.jsx
This change will hopefully encourage article authors to include alt text
when they add images to their articles.
=> Add place holder alt text to markdown link

app/services/podcasts/get_media_url.rb, spec/services/podcasts/get_media_url_spec.rb
A couple of podcast episodes fetching jobs are failing with `Errno::EINVAL`, so we need to rescue more types of errors.
#2952
=> Rescue all Errno exceptions while fetching a podcast episode

app/controllers/classified_listings_controller.rb
When you currently visit a listing that is expired, it goes to a 404 page because the controller query uses `find_by!` and doesn't allow nil assignment when searching for the expired slug.
By removing the `!`, this allows `nil` to be the `@displayed_classified_listing`, which is how we prevent viewing expired listings by direct link.
N/A
N/A
=> Expired Listing 404

app/assets/stylesheets/color-picker.scss, app/assets/stylesheets/minimal.scss, app/javascript/packs/colorPicker.js, app/views/internal/tags/index.html.erb, app/views/internal/tags/show.html.erb, app/views/partnerships/index.html.erb, app/views/tags/edit.html.erb, app/views/users/_org_admin.html.erb, app/views/users/_org_non_member.html.erb, app/views/users/_profile.html.erb
This feature moves us away from a pretty hacky use of an external color picker via CDN and into a color picker written in our own code.
I followed along with some example color picker code on the web, so the new stuff is not entirely "not" hacky, but it's a cleaner platform for us to work from if we want to make further changes. I kept old style JS so I wouldn't have to think about the implementation, but this can be fixed later.
Overall way fewer bytes, and one less lightly needed external script.
The functionality is and design is modified to look like this:
=> Switch to internally built color picker

app/controllers/api/v0/articles_controller.rb, config/routes.rb
The endpoint `/api/articles/onboarding` is never used by the frontend, it's likely a leftover from a previous onboarding experience.
It's also not tested anywhere
=> API: Remove /api/articles/onboarding

app/controllers/tag_adjustments_controller.rb, app/models/tag_adjustment.rb, app/views/moderations/mod.html.erb, config/routes.rb, spec/models/tag_adjustment_spec.rb, spec/requests/tag_adjustments_spec.rb
This allows admins to easily undo a tag adjustment. This will remove the tag adjustment by `destroying` it, and therefore `deleting_all` the other notifications related to it.
At first I wanted to preserve the history of the actions, where undoing a tag adjustment would be a new instance of `TagAdjustment` and it wouldn't destroy the tag removal. Removing a tag doesn't happen much though so I think for now we can go with this implementation instead.
=> Allow admins to undo a tag adjustment

app/assets/stylesheets/top-bar.scss
Modifies top-bar.scss to add 'border-right' and 'border-bottom-right-raidus' property
for '.menu' in media query 'mind-width: 1250px' to get even menu appearance on desktop
screens.
It adds border radius of 5px throughout the bottom-end of the menu and has the border running back all the way up on the right side on wide-enough(>=1250px) displays.
Issue #3726 
- night theme desktop
- night theme mobile
- pink theme desktop
- night theme mobile
=> Adds border-right to the menu for displays with min-width 1250 or higher

app/controllers/async_info_controller.rb, app/dashboards/display_ad_dashboard.rb, app/dashboards/html_variant_dashboard.rb, app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap, app/javascript/onboarding/Onboarding.jsx, app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap, app/javascript/onboarding/components/ClosingSlide.jsx, app/javascript/onboarding/components/IntroSlide.jsx, app/services/authorization_service.rb, db/migrate/20190818191954_add_onboarding_variant_to_users.rb, db/schema.rb, spec/models/user_spec.rb
This feature adds the field `onboarding_variant_version` which is randomly assigned to new users. These variants are then applied to onboarding and we can measure the relative effectiveness of various approaches.
For now, I added some mild copy adjustments to the first slide, alongside one variant to just skip the first slide, and one more to add a "challenge" of three constructive comments on the last slide.
All the current active variants are  to be described in comments in the code. When we add new variants we will always increment, so if we deem versions "0" and "2" are to be replaced with new variants, the available variants will be 1,3,4,5,6,7,8 now and 0 and 2 are for historical archive.
Also added `success_rate` to admin dashboard for display units as a random misc improvement for …
=> Add random variants to onboarding for a/b testing

app/assets/javascripts/initializers/initializeCommentsPage.js.erb, app/assets/javascripts/utilities/buildCommentFormHTML.js.erb, app/controllers/image_uploads_controller.rb, spec/requests/image_uploads_spec.rb
This fixes an issue where the image uploads controller accepted only arrays of images, and thus broke uploading images via comments. I looked at #3599 but couldn't quickly figure out how to get the comment's image upload `<form>` working so that it automatically sends an array to the server -- like the multi-image upload for articles does -- so I went with the quickest fix I could think of.
This fix uses a simple `if else` to check if the image is an array; if it's not, then it'll upload like  multiple images would and return an array with one `uploader`.
=> Fix for multi-image upload to handle single imgs for comments

app/models/chat_channel.rb
Fixes an issue where _too large_ objects stop indexing. We no longer need this field to be included.
=> Remove channel_users from chat_channel index

docs/installation/windows.md
Adds solution for the command 'bin/setup' failing while trying to install
'cld-0.8.0' due to absence of 'aclocal-1.10' and 'automake-1.10'. Provides
commands to install 'automake-1.10' from 'ftp.gnu.org' which fixes the problem.
#3740 
- Desktop
- Mobile
=> Updates Possible error messages under windows installation docs

app/views/users/show.html.erb
This fixes the issue where a single pinned article is not appearing if the user has no other articles. 
#3415
=> Show single pinned articles

app/observers/application_observer.rb
This adds a truncated version of a comment's `body_markdown` for the warned user alert. I went with `body_markdown` and not `processed_html` since markdown is _somewhat_ compatible with Slack's messaging system already.
=> Add comment markdown to warned_user_ping

app/controllers/organizations_controller.rb
According to [issue 28060 on the rails project](https://github.com/rails/rails/issues/28060), ``strip_tags`` since v1.0.3 encodes special html characters (&, <, > ...) by default. To restore its previous behaviour, I'm using Loofah directly, which is what ``strip_tags`` uses behind the scene. 
This solution does **NOT** fix existing organizations, they will need to be updated replacing ``&amp;`` with ``&``. I chose this solution over fixing how we show the ``&amp;`` in the view, because:
1. [Storing HTML encoded characters in the database might be a problem if we decide to display the data in a non-HTML format](https://stackoverflow.com/questions/4598802/should-we-html-encode-special-characters-before-storing-them-in-the-database/20700136)
2. This bug was present in all text fields that …
=> Fixes encoding of special characters in org (#3779)

.gitignore, docs/faqs.md
When dev.to is set up on an AWS Cloud9 instance, there is a folder `.c9` automatically created by AWS C9 for storing user specific settings (themes, keybindings of the IDE etc.).
I added this folder to the .gitignore file because it could include sensitive information.
After setting up PostgreSQL on the AWS Cloud9 instance and running `bin/setup` for the new dev.to instance, the error `role "ec2-user" does not exist` occured. I added the fix for this one to the **faqs.md** file in case someone else has this issue.
*Note:*
The pre commit linting messed up the previous PR so I started from fresh with a new one only including the required changes now.
=> Exclude AWS Cloud9 user config directory and resolve AWS install error "role ec2-user does not exist" in FAQ (v2)

db/seeds.rb
When you create new listings locally and then re run DEV, during the setup process, listings 1-22 are recreated, but other listings persist in Algolia (but are not in the db anymore). 
The `listings` page then shows old listings that don't exist anymore because they are still in Algolia.
N/A
N/A
=> Clear previous ClassifiedListings in Algolia during DB Seed

app/assets/javascripts/manifest.json.erb
This PR changes how the dev.to PWA appears on Android. Previously the home screen icon had a white background. Soon, browsers will let you specify an icon to fill the entire space. Since the dev.to icon is already a black square, you can just adjust the `"purpose"` field in the web app manifest!
[Icon preview](https://maskable.app/?demo=https://raw.githubusercontent.com/thepracticaldev/dev.to/master/app/assets/images/devlogo-pwa-512.png)
=> Use maskable icons

app/labor/badge_rewarder.rb, app/labor/bufferizer.rb, app/labor/cache_buster.rb, app/labor/flare_tag.rb, app/labor/html_cleaner.rb, app/labor/mailchimp_bot.rb, app/labor/markdown_fixer.rb, app/labor/markdown_parser.rb, app/liquid_tags/codepen_tag.rb, app/liquid_tags/codesandbox_tag.rb, app/liquid_tags/glitch_tag.rb, app/liquid_tags/jsfiddle_tag.rb, app/liquid_tags/stackblitz_tag.rb, app/models/chat_channel.rb, app/models/comment.rb, app/models/identity.rb, app/models/message.rb, app/models/notification.rb, app/models/organization.rb, app/models/tag.rb, app/models/tweet.rb, app/models/user.rb, app/services/credits/ledger.rb, app/services/notifications/new_follower/send.rb, app/services/notifications/reactions/send.rb
This PR renames a significant number of the single letter variables, which is pretty much just my opinion, but I don't see much benefit to having shorter variable names.
Secondarily, it also removes some commented code from two years ago.
```
Clarify uncommunicative variables in labor classes
Single letter variable names are largely a question of preference, in
some cases I think that convention mitigates the opaque nature of single
letter variable names (e.g., e for error, i for index, etc).
However, in some cases they can be unclear and there isn't much reason
to use single letter variables unless for some reason character length is
really important.
In this case, I would prefer clarity in variable names over brevity of
code so I've used Reek to identify short variable names and I'm …
```
=> Rename uncommunicative variables

spec/liquid_tags/classified_listing_tag_spec.rb, spec/requests/classified_listings_spec.rb
While examining PR https://github.com/thepracticaldev/dev.to/pull/3892 I noticed that `spec/requests/classified_listings_spec.rb` could fail due to missing escaping of auto generated text.
=> Fix flaky listings specs

app/controllers/chat_channels_controller.rb
`chat_channel_valid?` is not the real purpose of this method, the goal
here is to properly render a chat channel in case it's valid or not.
Hence, I renamed the method to make it clearer, hopefully :)
=> Use a clearer method name to render chat channel

app/controllers/api/v0/webhooks_controller.rb, app/models/webhook/endpoint.rb, app/views/api/v0/webhooks/show.json.jbuilder, docs/api_v0.yml, spec/factories/webhook_endpoints.rb, spec/models/webhook/endpoint_spec.rb, spec/requests/api/v0/webhooks_spec.rb
I've fixed a few details about the API that prevented it to be used by a third party client, and also removed the HTTP DELETE body which is useless in this case.
See #3715 and #3783
=> Webhooks: API fixes and docs

CONTRIBUTING.md
The `How to get help` section was removed with #3659. This removes the link to it from the table of contents as well.
=> Remove a link to a missing section in CONTRIBUTING.md

spec/models/article_spec.rb
* update article specs missing dependent destroy
The specs did not cover a number of the dependent destroys and these were added as well.
#3365
=> Update article specs to include missing dependent: :destroy (#3365)

app/assets/stylesheets/notifications.scss
I noticed the colors didn't match up here.
This CSS is complicated and new to me, so please let me know if there is a better pattern for how this is done throughout the app!
Before:
After:
=> Update notifications reply form to use theme colors

app/controllers/api/v0/articles_controller.rb, app/models/article.rb, config/routes.rb, docs/api_v0.yml, spec/requests/api/v0/articles_spec.rb
We want to make it explicit to retrieve unpublished articles, this change defaults `/api/articles/me` to only published articles, also adds `/api/articles/me/published`, `/api/articles/me/unpublished` and `/api/articles/me/all` to make requests more explicit.
This PR potentially breaks current usage of `/api/articles/me` by removing unpublished articles from the response.
Closes https://github.com/thepracticaldev/dev.to/issues/3928
=> API: /api/articles/me defaults to published articles

app/assets/stylesheets/preact/article-form.scss
There is no need for scrollbars in the textarea given the scrollbar at the edge of the browser and that `preact-textarea-autosize` used for the textarea automatically increases the height of the textarea when needed. 
Closes #3898, closes #2939, closes #3330
Nothing of significance changed besides the bugs not appearing anymore.
=> Hide scrollbars in the editor textarea

app/controllers/api_secrets_controller.rb, app/views/users/_account.html.erb, docs/api_v0.yml
Currently the API key section in the website uses the wording "DEV access token", but we call them "api keys" basically everywhere else, in the code and in the API documentation.
Additionally, the wording "access token" might collide with "OAuth access token" in the future if and when OAuth2 support is open to the public (and it's already a bit confusing in the API docs)
This PR replaces "DEV access token" with "DEV API key"
=> Replace "DEV access token" with "DEV API key"

app/controllers/application_controller.rb, config/routes.rb, spec/requests/api/v0/articles_spec.rb
While developing #3937 I noticed how in some cases when the Rails server routes to a 404 page will return the HTML version of the page for API calls expecting JSON. 
This solves this.
We use the catch all lifeline in case the 404 wasn't handled or raised inside the controller actions. This will return the regular 404 page to everything but the API routes.
=> Send JSON 404 response to API error routes

app/controllers/application_controller.rb, config/routes.rb, spec/requests/api/v0/articles_spec.rb
This hotfixes an issue with 404s being mishandled and essentially reverts https://github.com/thepracticaldev/dev.to/pull/3959 temporarily.
=> Revert changes as a hotfix

app/labor/cache_buster.rb
I see a decent amount of `InvalidURIError`s on busting cache jobs related to the #2934 issue (invalid tags containing blanks). These jobs keep retrying and wasting resources.
This pr is a quick solution for this problem, the proper solutions are described in #2934
I thought about checking tags for blanks explicitly because we would like to know if we try to bust cache of an invalid url in other cases, but the `CacheBuster` approach seems to be more like "catch the errors" plus we don't want to waste resources in other cases as well.
#2934
=> Rescue InvalidURIError when busting cache

lib/tasks/fetch.rake
Looks like the counter cache for credits gets out of sync pretty regularly. In the [counter_culture](https://github.com/magnusvk/counter_culture) documentation, they recommend running this regularly (1x a week).
=> Rake task for fixing credit counter cache

app/assets/javascripts/initializers/initNotifications.js, app/assets/stylesheets/_mixins.scss, app/assets/stylesheets/item-list.scss, app/assets/stylesheets/notifications.scss, app/controllers/notifications_controller.rb, app/views/notifications/_comment.html.erb, app/views/notifications/_notifications_list.html.erb, app/views/notifications/index.html.erb, spec/requests/notifications_spec.rb
This PR adds pagination to the notification page, while keeping the offset based pagination already in place.
The load more button looks like the one we have in the reading list and pro history pages.
I've added a bunch of documentation, both in the controller and in the views to explain how all of this currently works. I didn't change the offset based pagination, I just built the feature on top of it.
The only drawback of this approach is that it requires one extra click when you're at the end of the notifications list so that the client knows they are done paginating.
I also lowered the amount of notifications from 48 to 30 but maybe we can raise that.
I had 88 notifications last weekend and I only could read the last 48 so I decided to fix that :D
Closes …
=> Paginate notifications

Gemfile, Gemfile.lock, app/models/webhook/event.rb, app/serializers/webhook/event_serializer.rb, app/services/secrets/generator.rb, spec/models/webhook/event_spec.rb, spec/services/secrets/generator_spec.rb
This PR replaces the temporary event ID with a unique, random and sortable identifier.
I chose [ULID](https://github.com/ulid/spec) over [ksuid](https://github.com/segmentio/ksuid) because it has a clearer spec, ample implementations in various languages and it uses millisecond precision with the timestamp.
I chose ULID over UUID because UUIDs are not sortable, see [A brief history of the UUID](https://segment.com/blog/a-brief-history-of-the-uuid/).
I chose ULID over a custom implementation for obvious reasons as well. 
I created a little interface on ulid to not have the name of the algorithm around in all places, hopefully `Secrets::Generator` will eventually be a place where we have generators for all kinds of secrets, we'll see
Adds to #3872
=> Webhook events: use a sortable unique ID for the event_id

app/labor/badge_rewarder.rb, spec/labor/badge_rewarder_spec.rb
This fixes an edge case where sometimes people were rewarded with the streak badge for unpublished posts.
Closes #3949
=> Fix edge case for rewarding when unpublished

app/controllers/organizations_controller.rb, app/views/articles/_user_metadata.html.erb, app/views/organizations/show.html.erb, app/views/users/_profile_header.html.erb, spec/requests/user_profile_spec.rb
@rhymes as we discussed on PR #3817 I brought back the old code (``strip_tags``) and sanitized the parameters that accept special characters on page rendering. I used ``sanitize`` instead of ``raw`` because the rails docs said it's safer. 
You mentioned some testing, but because I wasn't 100% sure you meant automated tests I didn't write any. I can update my PR with any tests you think it'd be cool to have. 
#3799 and #3817 
No UI changes
=> Fixes encoding of special characters on organization page rendering

app/assets/javascripts/initializers/initNotifications.js, app/assets/stylesheets/notifications.scss, app/controllers/notifications_controller.rb, app/models/notification.rb, app/views/notifications/_notifications_list.html.erb, app/views/notifications/index.html.erb
Right now we filter recently aggregated notifications at runtime, which worked before when there was no pagination, but now filtering is not a good idea combined with offset pagination because it throws off the calculations.
In my case on dev.to/notifications it breaks after the third page.
The filtering should be done in the SQL query before paginating, which is what we've switched to. I added a bunch of scopes to make the code clearer as well.
To avoid nesting tags I've also updated the HTML and the JS logic to insert it in the right place.
=> Notifications: increase efficiency and fix pagination offset issue

app/services/webhook/dispatch_event.rb, spec/requests/articles/articles_create_spec.rb, spec/requests/articles/articles_update_spec.rb, spec/services/webhook/dispatch_event_spec.rb
My previous solution for events dispatching sends all the articles creates/updates/destroys to all the endpoints, not only the corresponding users' ones. This pr fixes it.
#3715
=> Dispatch events only to the corresponding user endpoints

app/services/articles/creator.rb, app/services/articles/destroyer.rb, app/services/articles/updater.rb, spec/requests/articles/articles_create_spec.rb, spec/services/articles/creator_spec.rb, spec/services/articles/destroyer_spec.rb, spec/services/articles/updater_spec.rb
- dispatch "article_create" events only when an article is published
- dispatch "article_update" events only when an article is published or is updated to be unpublished (don't send when a draft is updated w/o being published)
- dispatch "article_destroyed" events only when an article was published
#3715
=> Send only public events to the webhook endpoints #3715 

app/views/api/v0/webhooks/index.json.jbuilder, app/views/api/v0/webhooks/show.json.jbuilder, docs/api_v0.yml
This PR hides the `updated_at` field from the API (we never show expose it anywhere in it), and adds documentation for `/api/webhooks`
See #4013
=> API: add doc for webhooks index

config/environments/production.rb
Apparently we're generating HTTP URLs when using Rails URL helpers, like `user_social_preview_url(user, format: :png)`. By default Rails generates HTTP urls unless told so.
This forces the routes helpers to generate HTTPS URLs.
The redirect works correctly.
See https://github.com/thepracticaldev/dev.to/issues/4055#issuecomment-532582952 for why this is happening
Closes #4055
=> Generate HTTPS urls with Rails url helpers

app/controllers/api/v0/webhooks_controller.rb, app/models/webhook/endpoint.rb, db/migrate/20190918104106_add_oauth_application_id_to_webhook_endpoints.rb, db/schema.rb, spec/requests/api/v0/webhooks_spec.rb
- added `Webhook::Endpoint` `belongs_to` `oauth_application` so that we could remove the corresponding webhooks when the oauth app access is revoked
- added specs to check that the `oauth_application_id` is set properly
- added tests for the webhooks API auth by the doorkeeper token
- limited access to the webhooks if the user is authorized by the doorkeeper token.
#3715
=> Added association between webhook_endpoints and oauth apps

app/labor/markdown_parser.rb, spec/labor/markdown_parser_spec.rb
The current bug https://github.com/thepracticaldev/dev.to/issues/4050 is explained in [this stack overflow answer](https://stackoverflow.com/a/27208749/5494108). We used `//div[contains(text, "some text")]` instead of `//div[contains(., "some text")]`, which limits the texts that we can search for.
On top of that fix, in order to avoid recursively searching for text containing "@" within a node's child, I used a queue system. Let me know if this is a bad idea.
Resolves https://github.com/thepracticaldev/dev.to/issues/4050
=> Fix mention's inconsistent hyperlink

app/models/webhook/endpoint.rb, config/initializers/doorkeeper.rb, spec/models/webhook/endpoint_spec.rb
Defined association on `Doorkeeper::Application` to `Webhook::Endpoint` to be able to specify `inverse_of` on the `Webhook::Endpoint`
#3715
=> Define Doorkeeper::Application association on webhook_endpoints

app/assets/stylesheets/notifications.scss
Another CSS color thing I noticed!
Before:
Pretty hard to read!
After:
Less hard to read!
=> Change reply notification background color

app/liquid_tags/github_tag/github_readme_tag.rb, app/views/liquids/_github_readme.html.erb, app/views/pages/_editor_guide_text.html.erb, spec/liquid_tags/github_tag/github_readme_tag_spec.rb
Add option ``no-readme`` to GitHub liquid tag that hides the readme file from the preview.
Closes #4029
=> Add no-readme option to GitHub tag

app/helpers/application_helper.rb, app/liquid_tags/codepen_tag.rb, app/liquid_tags/glitch_tag.rb, app/liquid_tags/jsfiddle_tag.rb, app/liquid_tags/kotlin_tag.rb, app/liquid_tags/stackblitz_tag.rb, app/liquid_tags/stackexchange_tag.rb, app/liquid_tags/tweet_tag.rb, spec/helpers/application_helper_spec.rb, spec/liquid_tags/codepen_tag_spec.rb, spec/liquid_tags/kotlin_tag_spec.rb, spec/liquid_tags/stackexchange_tag_spec.rb
Ruby has a slightly different meaning with `^` and `$` than other languages, the [Rails security guide](https://guides.rubyonrails.org/security.html#regular-expressions) explains that in detail. 
Not all of these changes are strictly required because some tags are already sanitized and split before the regexps are applied but for peace of mind I've unified the ones I found.
=> Replace ^ and $ with \A and \z in Ruby regexps

app/assets/stylesheets/comments.scss
Prior to this change, the opacity on the comment affects its dropdown menu, making it see-through when expanded. So I've instead applied opacity to all child elements except the dropdown.
Opacity issue before this fix:
=> Fix opacity issue on low quality comments

app/assets/stylesheets/_mixins.scss
[#4068](https://github.com/thepracticaldev/dev.to/issues/4068)
In _mixins.scss:
```css
@mixin load-more() {
text-align: center;
button {
...
color: inherit
}
}
```
=> fixed Load More button not readable in night theme

app/controllers/api/v0/articles_controller.rb, app/controllers/api/v0/webhooks_controller.rb, config/initializers/doorkeeper.rb, config/locales/doorkeeper.en.yml, spec/requests/api/v0/articles_spec.rb, spec/requests/api/v0/webhooks_spec.rb
- created a doorkeeper `public` scope
- added doorkeeper authorization to webhooks and articles API actions
Maybe there are other actions which are accessed with the doorkeeper token and also need authorization.
Existing `Doorkeeper::AccessToken`s' `scopes` need to be updated to `"public"`
#3715
=> Doorkeeper default scope

app/controllers/notifications_controller.rb, app/views/notifications/_article.html.erb
Fragment caching does not support an explicit expiration date for simplicitly, which means that cached resources are tied to the update datetime of the model.
In this case unfortunately this is not sufficient: a cached time that potentially never gets expired can stale quickly when applied to a time sensitive item like a notification.
Since the "time ago" computation is not particularly heavy and notifications are paginated, I ended up removing that part from the cache altogether.
As a byproduct I created two new separate cache keys for the article notification, one of each section surrounding the time.
Closes #4023
=> Do not cache articles notifications "time ago" indication

app/views/feedback_messages/_form.html.erb
This PR fixes label elements on the Report Abuse page which did not match the ID of the corresponding radio input. Improves usability and accessibility.
=> Fix radio button labels on Report Abuse page

app/assets/javascripts/utilities/sendFetch.js
Refactoring sendFetch.js, removes code duplication.
=> Refactoring sendFetch.jsx removes code duplication

app/models/article.rb, app/models/chat_channel.rb, app/models/user.rb
While reviewing other PRs I noticed something and went confirming it with the Rails docs: 
> before_destroy callbacks should be placed before dependent: :destroy associations (or use the prepend: true option), to ensure they execute before the records are deleted by dependent: :destroy.
So if an object has objects that will be destroyed by association, its `before_destroy` callbacks should run *before* those objects are in turn destroyed.
I added `prepend: true` to the three models that match the scenario.
See https://guides.rubyonrails.org/active_record_callbacks.html#destroying-an-object
=> Prepend before_destroy(s) in models with destroy dependents

app/controllers/api/v0/api_controller.rb, app/controllers/api/v0/articles_controller.rb, app/controllers/api/v0/classified_listings_controller.rb, app/controllers/api/v0/users_controller.rb, spec/requests/api/v0/articles_spec.rb, spec/requests/api/v0/classified_listings_spec.rb, spec/requests/api/v0/users_spec.rb
User authorized with an OAuth token should only able to access endpoints that correspond to the selected scopes. In this pr, I limited access to creating and updating records in this case.
#3715
=> Limit access to the API actions when authorized by doorkeeper token

app/assets/stylesheets/tag-edit.scss, app/views/tags/edit.html.erb
Since it's my first time working with Ruby, I decided to learn about ERB and do minor yet pleasing styling changes:
* Decreased indentation for tag-edit.scss
* Imported variables & mixins for code standardisation.
* Moved the section order around to show mainly used ones first.
* `Textarea` resizing is restricted to vertical
* Focusing on a text field will set the border to a different colour
* The 'Save Changes' CTA has been changed to go in accord with DEV's aesthetic
Improve the tag edit pages #3953
=> Improve the tag edit page (Tag moderators only)

app/views/articles/_single_story.html.erb
When navigating through the article cards with a keyboard, currently the engagement icons are tabbed to in different order than what you would expect visually. (Comments are tabbed to first even though visually, it is second). Logical focus order should follow visual order when possible so a keyboard user knows what to expect.
The fix was to change the order of the elements in the markup.
Before:
After:
=> Fix tabbing order of article engagement icons

app/javascript/listings/elements/categories.jsx
=> Mini refactor to make variable names clearer in the Categories component

app/assets/stylesheets/classified_listings.scss
Fixes the text color of the "Load more listings" button at the bottom of the /listings page for night theme.
Before:
After:
=> Fix text color "Load more listings" button

app/labor/cache_buster.rb, spec/labor/cache_buster_spec.rb
`commentable` can be not only an `Article` but at least a `PodcastEpisode`. In this case `bust_comment(commentable)` failed because `PodcastEpisode` doesn't respond_to `last_comment_at`. Checks before busting the main page also are made for the `Article` commentable. This pr fixes these issues, I also added a test which would fail with the previous implementation.
=> Bust non-article comment cache without issues

app/assets/stylesheets/footer.scss
@media tags are fighting. There's a unneeded `margin-left: 310px;` in there for the @media tag for `@media screen and (max-width: 1119px) and (min-width: 950px) footer .container.centered-footer {` removed it to resolve issue.
https://github.com/thepracticaldev/dev.to/issues/3112
before: ![before screenshot of footer](https://i.imgur.com/caE5yGW.png)
after: ![after screenshot of footer](https://i.imgur.com/8M8YWMp.png)
=> removing unneeded margin-left in @media tag

app/controllers/social_previews_controller.rb, app/helpers/social_image_helper.rb, app/views/articles/show.html.erb, app/views/comments/index.html.erb, app/views/social_previews/comment.html.erb, config/routes.rb, spec/requests/social_previews_spec.rb
When a link to a comment on dev.to is shared, a social preview of the comment is generated that includes a preview of the comment, the article it came from, and user-data on the commenter.
Closes [#3990](https://github.com/thepracticaldev/dev.to/issues/3990)
=> Comment Social Preview

app/services/podcasts/feed.rb
Rescue `SocketError` and mark a podcast as unreachable in that case.
=> Rescue SocketError when trying to fetch a podcast

app/assets/stylesheets/user-profile-header.scss
An invert filter was causing the social links in the profile section to be a different color in night theme than the rest of the text. This PR fixes the issue by setting `filter: none`
Fixes #2183
Before:
After:
=> removed invert filter from profile header social icons

app/assets/stylesheets/scaffolds.scss
Added a print style to hide header & footer
See this Issue: https://github.com/thepracticaldev/dev.to/issues/3728#issuecomment-538671665
This is how it looks **now** when printing:
=> Fixed printing issues with header & footer

app/javascript/shared/components/tags.jsx
When typing in tags using the v2 editor, the tag disappears once you've typed in the full word. For example, if you want to type in `javascript` it will appear as a choice all the way up until you add the `t` at the end of the word which causes it to disappear from the choice list. 
In order to fix this functionality I added an `OR` statement to the search method in the app/javascript/shared/components/tags.jsx file. 
I also made a few fixes to this file according to the eslint recommendations. They were minor changes, such as using `prevState` callback and reordering methods. Another suggestion from eslint that I implemented was to change all `!=` comparison to `!==`.  
A possible future edit could be to make sure a tag doesn't appear once it's already been chosen when searching. I'd be …
=> fixes bug in tag search feature

app/assets/stylesheets/ltags/GithubTag.scss
Github liquid tag header goes out of its parent element
Resolves https://github.com/thepracticaldev/dev.to/issues/3661
**Before**
**After**
=> Fixes Github Liquid Tag alignment in notifications page

app/policies/user_policy.rb, spec/requests/user_settings_spec.rb
`mod_roundrobin_notifications` was missing from `permitted_attributes` in `user_policy.rb` which was preventing the community-success notification setting from getting saved. This PR adds `mod_roundrobin_notifications` to `permitted_attributes` in `user_policy.rb`.
Fixes #4210
=> added mod_roundrobin_notifications to user_policy.rb

app/controllers/articles_controller.rb, app/services/article_with_video_creation_service.rb, spec/services/article_with_video_creation_service_spec.rb
After upload video creates an article with body_markdown with an empty description and failed to parse tags
https://github.com/thepracticaldev/dev.to/issues/3846
=> Fixed invalid body_markdown in article with video

app/controllers/chat_channels_controller.rb, app/models/chat_channel.rb
Favors `delete_all` over `destroy` in a deleting a collection of `Message`s. The former is efficient as it doesn't  instantiate any `ActiveRecord` objects. Since the `Message` model has no `before_destroy` callbacks, I believe it's safe to use `delete_all`. Do let me know if I am missing something.
=> Delete messages without instantiating ActiveRecord objects

app/views/articles/_algolia_search.html.erb
```
Given I am a vistor
When I type in the search "#serverless #discuss"
And I press and enter
Then I should only see articles that are tagged  with both "serverless" and "go"
```
I have throughly documented my journey to implement this feature in the original ticket:
https://github.com/thepracticaldev/dev.to/issues/2238
I believe this is expected behaviour and check docs.dev.to and thought it not applicable to add documentation.
=> Combining tags together in a search query (#2238)

.eslintignore
The `app/assets/javascripts/lib` should be completely ignored by eslint as it is a folder that contains 3rd party libs, e.g. pulltorefresh.js and xss.js
This PR adds that entire folder to eslint's ignore list.
#3777
=> Now eslint ignores the app/assets/javascripts/lib folder.

app/assets/stylesheets/settings.scss, app/javascript/packs/colorPreview.js, docs/getting-started/architecture.md
This fixes issues where if the user visits the settings page, and then leaves and comes back, the color preview is not loaded appropriately.
It also adds documentation to give clarity on this a bit.
I also modified the styles a bit here so that the color selector fits nicely alongside the text field.
=> Fix gotchas with color preview and some style adjustments and add docs

spec/factories/badges.rb
We've had multiple times specs failing for this unrelated error:
```ruby
1) Badges GET /badges when logged in shows all the badges
Failure/Error: let!(:badges) { create_list(:badge, 3) }
ActiveRecord::RecordInvalid:
Validation failed: Title has already been taken
```
See https://travis-ci.com/thepracticaldev/dev.to/builds/131156060 for example
I've investigated a bit and I think the issue is that [Faker::Games::Overwatch.title](https://github.com/faker-ruby/faker/blob/master/lib/faker/games/overwatch.rb) has a [sample that's too small](https://github.com/faker-ruby/faker/blob/4555159b7da9813235395d271b1b65a32407086b/lib/locales/en/overwatch.yml)
I've switched to a generator with a bigger sample
=> Specs: use a bigger sample for badges titles

app/lib/redcarpet/render/html_rouge.rb, spec/labor/markdown_parser_spec.rb
Fix invalid anchored links due to "//" prefix.
* Updates app/lib/redcarpet/render/html_rouge.rb
* If link starts with "#", keep link as it is, since it's an anchored link
#4338
=> Fix invalid anchored links due to "//" prefix.

app/assets/javascripts/initializers/initializeCommentDate.js
- add `use strict` to fix eslint errors in the file, the rest of the file is already compliant.
#3777
=> Fix eslint issues in initializeCommentDate.js

app/assets/javascripts/initializers/initializeSettings.js
- eslint configuration moved comments to a separate line on running pre-commit hook allowing the eslint disable-line to not work correctly.
- switched to eslint-disable-next-line to fix the same
#3777
=> Fix eslint issues in initializeSettings.js

spec/jobs/articles/bust_cache_job_spec.rb, spec/jobs/articles/detect_human_language_job_spec.rb, spec/jobs/articles/score_calc_job_spec.rb, spec/jobs/articles/update_main_image_background_hex_job_spec.rb, spec/jobs/comments/calculate_score_job_spec.rb, spec/jobs/comments/create_id_code_job_spec.rb, spec/jobs/comments/send_email_notification_job_spec.rb, spec/jobs/comments/touch_user_job_spec.rb, spec/jobs/pro_memberships/populate_history_job_spec.rb, spec/jobs/users/bust_cache_job_spec.rb, spec/jobs/users/resave_articles_job_spec.rb, spec/jobs/users/subscribe_to_mailchimp_newsletter_job_spec.rb
Resolves #4269 
Many job specs were putting their assertions inside a block provided to
ActiveJob's perform_now. Unfortunately, this syntax does not error and
simply ignores the provided block.
The tests were therefore not executing their assertions. As a result
many of them were actually broken to begin with. Many used incorrect
stubbing, were trying to stub instances of models that wouldn't actually
be returned by ActiveRecord queries, etc.
This commit fixes the syntax and does it's best to fix the tests. Many
of these assertions/spec could use more TLC, but this work at least gets
them passing/executing.
#4269
=> Fix broken job specs

app/javascript/shared/components/__tests__/tags.test.jsx, app/javascript/shared/components/tags.jsx
Move combination key codes to separate const in `tags.jsx` file.
Add test for checking `preventDefault` in `handleKeyDown` method.
Suggestions comes form codeclimate.
https://codeclimate.com/github/thepracticaldev/dev.to/app/javascript/shared/components/tags.jsx/source#issue-a087ee1bf368783e621a0b4563a3aaeb
https://codeclimate.com/github/thepracticaldev/dev.to/app/javascript/shared/components/tags.jsx/source#issue-a087ee1bf368783e621a0b4563a3aaeb
=> Simplify key codes expression in Tags component

app/assets/stylesheets/chat.scss
While using the Night Theme everything is perfectly styled, once you hit the chat, the usernames have a white background, and while having also a white color, the username isn't visible until you hover. 
Couldn't find any issues regarding the chat 
I removed the background-property and tested it on every theme at dev.to itself. Except the Night Theme, all themes have the chat in a white background anyway, so there is no need to have Usernames with a white background either
I wanted to provide a screenshot, but since my local docker version of dev.to just didn't wanted to run as I expected, like 3+ mins to switch from one page to another, also how to have multiple accounts (to create a chat) when you only one github account to logon? 😅 
Edit:
Current:
Live CSS Changes:
=> Dark-Theme: remove white background ChatMessage username link 

app/liquid_tags/link_tag.rb, spec/liquid_tags/liquid/raw_spec.rb
Add a clearer error message when link tag contains non-article URL
Fixing #4271
=> Add a clearer error message when link tag contains non-article URL

app/assets/stylesheets/classified_listings.scss, app/assets/stylesheets/preact/article-form.scss, app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap, app/javascript/article-form/articleForm.jsx, app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap, app/javascript/shared/components/tags.jsx, app/models/tag.rb, app/views/articles/_v2_form.html.erb
This feature adds a toggle to display rules so that it's more straightforward to know whether a tag has mod-enforced rules and guidelines.
Upon merging this we'll need to re-index tags that have rules with Algolia.
I did not fix some existing linting errors.
=> Add tag rules to article v2 editor

app/liquid_tags/link_tag.rb, app/views/pages/_editor_guide_text.html.erb, spec/liquid_tags/link_tag_spec.rb
Added an alias (post) for the 'link_tag' liquid test, along with a test to check that it would function as an alias. It's my first  time contributing to an OSS so any feedback would be appreciated.
Fixes https://github.com/thepracticaldev/dev.to/issues/3376
=> Add post as an alias to the link liquid tag

app/assets/javascripts/initializers/initializeBodyData.js
- [ x] Refactor
This PR deletes an unnecessary line (line 28) in app/assets/javascripts/initializers/initializeBodyData.js. It was a querySelector method assigned to a metaTag variable that was not being used anywhere.
Lint issues with JavaScript Files #3777
- [ x] no documentation needed
=> remove unused variable and querySelector method in initializeBodyData.js

app/assets/stylesheets/comments.scss
Reply actions container has a z-index of 5, and extends over the upload button
and uploaded input.
The editor upload button gets covered by the fixed width of the `.reply-actions` bar. It has a Z-index of 5, so I set the z-index of the Upload button to 6 so the button and associated input are clickable. 
N/a
=> Add Z-Index to Editor Image Upload Container

app/assets/javascripts/.eslintrc.js, app/assets/javascripts/utilities/sendFetch.js
There was an issue with the parsing of the object spread operator in `sendFetch.js`. Bumping the ecmaVersion in the eslintrc file from 2017 => 2018 resolved the issue. However, bumping that introduced/uncovered another linting error with the use of the short circuit logic conditionally appending the authenticity_token. That is now wrapped in a standard if statement.
I did confirm that bumping the ecmaVersion _does not_ introduce any new linting errors.
https://github.com/thepracticaldev/dev.to/issues/3777
=> Resolve linting issue in app/assets/javascript/sendFetch.js

docs/contributing.md, docs/readme.md
The readme should include instructions to run the docs site so that
people don't have to go searching for the contributing.md file if they
are stumbling upon the docs in their code editor instead of via the
docs.dev.to website.
=> Update the docs readme with instructions [ci skip]

app/black_box/black_box.rb, spec/black_box/black_box_spec.rb
Sometimes we need to update the numbers so popular posts don't stick around too long as DEV grows in total use and popularity. In addition to the top secret ranking factors (obfuscated to avoid game-ability), this is an update to the naive public factors.
=> Update feed to have popular posts sink a bit faster

.erb-lint.yml, app/views/internal/articles/_individual_article.html.erb, app/views/layouts/internal.html.erb
I changed the display option for only these forms form in internal/articles to `flex`. Adjust the sizes a little.
Also fixed the code formation to remove extra characters and made it more consistent.
There is a method `html_safe` used in this file, if be honest I don't know how to change it. And I suppose this HTML already processed according to the name of the column, so it's not necessary. I had to exclude it in erb-liner config because it now allows pushing the changes.
Closes #4276
=> Internal article: change display to flex and adjust code to remove the extra characters

CONTRIBUTING.md
To help in code reviews I'm proposing this new scheme of branching, for both contributors and maintainers:
`USERNAME/DESCRIPTION-ISSUE_ID`
I've been reviewing many PRs lately and it's not always easy when you're browsing your local branches to understand who's doing what, related to which issue.
=> Change branching naming scheme for PRs [ci skip]

app/controllers/api/v0/articles_controller.rb, app/services/articles/creator.rb, spec/requests/api/v0/articles_spec.rb
Made a change from `save` to `save!` so an exception is raised in `creator.rb` if an article cannot be saved. The exception is handled by the controller and a more specific error message is sent back to the user.
If the title is missing, you get a response like the example below.
__EDIT__
```
{
"error": [
"Title can't be blank"
],
"status": 422
}
```
An issue I have with the above error message is that title is spelt `Title` and not `title` which could be misleading
Resolves #4402
=> Improve error message when creating article using API

app/assets/javascripts/initializers/initializePodcastPlayback.js
I have refactored the `muteUmute()` function in  `app/assets/javascripts/initializers/initializePodcastPlayback.js` to use ternary statements instead of if/else, as this avoids duplicated code, and fixes [this](https://codeclimate.com/github/thepracticaldev/dev.to/app/assets/javascripts/initializers/initializePodcastPlayback.js/source#issue-09bd665b3a353cb35f9d278d56f3fd41) issue on CodeClimate.
[This CodeClimate Issue](https://codeclimate.com/github/thepracticaldev/dev.to/app/assets/javascripts/initializers/initializePodcastPlayback.js/source#issue-09bd665b3a353cb35f9d278d56f3fd41).
=> update initializePodcastPlayback muteUnmute to use ternaries

app/controllers/api/v0/articles_controller.rb, spec/requests/api/v0/articles_spec.rb
While updating the API docs I've noticed how https://github.com/thepracticaldev/dev.to/pull/4417 broke the error interface (the client expects a string error, not an array of errors, they can't both coexist without the API client breaking).
This fixes it
=> Fix broken error interface in Article creation API

app/services/podcasts/feed.rb, spec/services/podcasts/feed_spec.rb
Increased redirects limit when fetching podcasts to avoid `HTTP redirects too deep` error.
=> Increased redirects limit when fetching podcasts

app/assets/javascripts/initializers/initScrolling.js.erb
Fixes #1805 by changing scrollHeight calculation in initScrolling to use the actual scrollable element vs. the document element.
Re-submission of https://github.com/thepracticaldev/dev.to/pull/4247. Initial commit in that PR was made without having my git identity setup (new laptop). This re-submission is simply to associate my git identity with the commits to satisfy CLA Assistant.
=> fix scrollheight calculation by using scrollable element instead of document element

.gitignore
We've decided as a project to prefer rbenv for version management. I use
asdf for my version management, so I've decided to ignore the dotfile
that asdf creates and relies on.
That lets me keep using asdf without worrying about maintaining two
version indicating dotfiles. People should be able to manually check the
.ruby-version file or Gemfile if they need to know the version for a
tool like asdf.
=> Ignore .tool-versions file

app/views/articles/_full_comment_area.html.erb
Fixes alignment issue for divs appearing outside `home` container
#4379
=> [BUGFIX] Fix weird alignment for additional contents

spec/support/initializers/capybara.rb
Chrome 78 was recently released as a stable version and Travis CI started installing it automatically. Chrome Driver 76 was no longer compatible with Chrome 78 and the builds started failing. So the solution is to bump the required Chrome Driver version to 78.
Issue #4553
=> Bump Chrome Driver version to fix Travis CI builds

.github/CODEOWNERS
Add SRE team to the CODEOWNERS file and assign Gemfile and db and config folders. Often changes in files in the db and config folders need extra care when rolling out which is why I want SRE tagged in the PRs that include them. The Gemfile I thought was important bc staying on top of new dependencies and any gem upgrades is also a good idea when it comes to maintaining site stability.
=> Add SRE team to CODEOWNERS 

spec/support/initializers/capybara.rb
After https://github.com/thepracticaldev/dev.to/pull/4554 was merged, we realized we might not need to track a specific version of Chrome since Travis [automatically tracks Chrome stable](https://docs.travis-ci.com/user/chrome):
```
Take note that the underlying Chrome version can change from one build to another when Google updates the stable or beta version.
```
https://github.com/thepracticaldev/dev.to/issues/4553
=> Remove required Chrome version, allowing Travis to track stable Chrome

app/controllers/concerns/audit_instrumentation.rb, app/controllers/internal/tags_controller.rb, app/jobs/audit/save_to_persistent_storage_job.rb, app/models/audit_log.rb, app/services/audit/event/payload.rb, app/services/audit/event/util.rb, app/services/audit/helper.rb, app/services/audit/notification.rb, app/services/audit/subscribe.rb, config/initializers/audit_events.rb, db/migrate/20190708105607_create_audit_logs.rb, db/migrate/20190801132654_add_additional_columns_to_audit_log.rb, db/migrate/20190906193806_add_jsonb_data_column_to_audit_logs.rb, db/schema.rb, spec/factories/activesupport_events.rb, spec/factories/audit_logs.rb, spec/models/audit_log_spec.rb, spec/requests/internal/moderator_logs_spec.rb, spec/services/audit/event/util_spec.rb, spec/services/audit/helper_spec.rb, spec/services/audit/notification_spec.rb, spec/services/audit/subscribe_spec.rb
Wrapper classes are created under `Audit` namespace, which are able to use the internal Rails Instrumentation [API](https://guides.rubyonrails.org/active_support_instrumentation.html#rails)
To be done:
Fixes #3141
=> Moderators audit logs

.travis.yml, Procfile
By using the release option in our Procfile we can tell Heroku to run migrations before a release is officially deployed. If the migrations succeed the release is deployed. If the migrations fail then the release will not be deployed. This will prevent us from running into the issue of a migration failing but the code relying on it still being deployed. 
The process is shown in the picture below and further details can be found in the [Heroku release-phase docs](https://devcenter.heroku.com/articles/release-phase).
=> Add Release Option to Procfile for Running Migrations

app/controllers/comments_controller.rb, spec/requests/comments_create_spec.rb
Fixes a logic error when there is a valid UserBlock and the blocked user is creating a comment.
=> Fix logic error with creating comment block

spec/services/audit/notification_spec.rb
A few releases ago Faker switched positional arguments to keyword arguments, this fixes a standing warning that was overlooked during the reviews we did of https://github.com/thepracticaldev/dev.to/pull/3449 
https://github.com/thepracticaldev/dev.to/pull/3449
=> Fix warning on missing Faker keyword argument

app/javascript/article-form/elements/bodyPreview.jsx
There's a bug in prod where the cover image area shows up even when the cover image hasn't been added to v2 editor
This adds a conditional to fix that. I couldn't find anyone who reported this.
=> Fix issue where cover image shows up when it shouldn't

app/services/mentions/create_all.rb, spec/services/mentions/create_all_spec.rb
this fixes the issue when an owner of the comment tries to mention itself and it would trigger a notification which is redundant because owner knows already about the comment.
Fixes #4262
=> Fix comment author being notified when mentioning itself

.rubocop.yml, app/controllers/users_controller.rb, app/helpers/application_helper.rb, config/routes.rb
This is an attempt to enforce a style for Ruby hash keys.
I've enabled `ruby19_no_mixed_keys` which as the name implies doesn't allow mixed keys styles.
The default is `ruby19` which allows mixed styles.
See https://github.com/rubocop-hq/rubocop/blob/master/manual/cops_style.md#stylehashsyntax
=> Rubocop: enforce ruby19_no_mixed_keys Style/HashSyntax

app/controllers/reactions_controller.rb
Rather than looking up the user again through the reaction we can use the current_user which was already used to look up the reaction object in the first place.
=> Use Avoid Duplicate Postgres Lookup By Using current_user

db/migrate/20191025185619_add_old_username_index_to_users.rb, db/schema.rb
While in Skylight investigating our recent uptick in response times I noticed this User lookup query that was taken over 500ms to execute. Turns out we have no indexes on old_username or old_old_username which means we have to do a full table scan for this lookup every single time.
=> [deploy] Add Index for old_username and old_old_usernames

app/assets/stylesheets/comments.scss
- Enforces `max-width:100%` on images in `.comment-preview-div` to prevent them from overflowing their container.
Fixes #4382 
**Before:**
**After:**
=> [deploy] Fix Image Overflow in Comment Preview - #4382

app/assets/stylesheets/item-list.scss, app/javascript/readingList/__tests__/__snapshots__/readingList.test.jsx.snap, app/javascript/readingList/readingList.jsx, app/javascript/searchableItemList/searchableItemList.js
This PR adds a "My Tags" heading to the tag filter list in the Reading List view, as well as a "Clear All" button that removes all of the tag filters. The button is only visible when there are active tag filters. The heading is styled to match the "My Tags" heading in the home view sidebar. 
Fixes #3819 
No filters selected (Desktop):
Active filters (Desktop):
No filters selected (Mobile):
Active filters (Mobile):
=> [deploy] Reading list: Add clear filter button/icon

db/migrate/20191025185619_add_old_username_index_to_users.rb
We recently had a migration fail due to a timeout. Even though the migration reported a failure, the first index of the migration was created. However, the migration was never recorded in the database bc of the failure status. This has led to us being in a state where if we try to run the migration we get an error bc the first index already exists but we still need to add the second index. In order to fix this, I have added guard clauses to check for the index before attempting to add or remove it. This will prevent the migration from failing when it sees that the first index has already been created.
=> Add A Guard Clause Before Adding or Removing New User Indexes

db/migrate/20191025202354_add_articles_index_for_feed_source_url.rb, db/schema.rb
Another db lookup that I found was taking a long time(hundreds of ms) was this simple Article lookup by feed_source_url. This time I found the query through Heroku's Postgres dashboard which will show you what queries you are spending the most time on.
=> Add Index to feed_source_url For Articles

app/controllers/buffered_articles_controller.rb
Rather than loading the entire Article object here, let's just select the path column since that is all we are mapping over.
=> Select Path When Loading Buffered Article Urls

public/offline.html
@tworrell and I worked together on this issue at Hacktoberfest Kickoff. To keep the diff manageable, we focused first on adding 1 new element (the selector), and ensuring that modifications to the selector would lead to the color palette controls re-rendering. We would like to put the feature that modifies the DEV stripes in a follow-up PR.
- https://github.com/thepracticaldev/dev.to/issues/3448
<a href="https://cl.ly/9768e443cb5a" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/1e0H2D2S2i2s3T3R1v2n/Screen%20Recording%202019-10-02%20at%2012.49%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>
- TODO: add some more palettes, and test them for high contrast / how they look under different color deficiency conditions
- WIP
=> [feature][offline-page] Add Color Palette Toggle #3448

app/assets/stylesheets/articles.scss
Add focus style to `SAVE` button.
This makes Firefox Accessibility inspector happy. It also makes sense because without this by using the keyboard tabbing, the button doesn't change
=> Add focus styling to SAVE button

app/assets/javascripts/initializers/initializeTouchDevice.js
Multiple event listeners were being added to the navigation button. Changed to add a named function instead of anonymous so that duplicates are discarded.
Looks like the system tests are only running with desktop chrome browser, so I've not made any updates there.
Fixes #4571 
n/a
=> Use named function so duplicate event handlers are discarded

.simplecov, docs/tests/code-coverage.md
Coverage report was not being generated. Now it is generated by default but it will be possible to turn it off.
Resolves #4653
=> Add ability to turn on & off coverage report generation with env variable

lib/redis_rails_cache.rb, spec/lib/redis_rails_cache_spec.rb
Rather than directly talking to our new `RedisClient` I have created a wrapper class that acts similarly to Rails.cache called `RedisRailsCache`. It responds to methods such as read, write, and [fetch](https://github.com/rails/rails/blob/66cabeda2c46c582d19738e1318be8d59584cc5b/activesupport/lib/active_support/cache.rb#L314). I will also need to implement delete at some point but I will save that for a later PR. The VAST majority of our Rails.cache calls are using fetch and from what I can tell the only option we use with fetch is `expires_in` which is why that is the only one I supported. If I come across other options I can update the wrapper to handle them but I think this will cover just about everything. 
I also applied the new wrapper to our following_podcast_ids cache since that …
=> Create RedisRailsCache Object to Mimic Rails.cache And Apply

app/assets/stylesheets/top-bar.scss
As described in #4663, the homepage search bar should be styled when it's focused in order to better indicate that fact. The example in the issue suggests using a different background color, however i want to propose a solution where we use the border for on focus styling. This i think is more in line with the default browser styling and the styling found in many websites (so it's a pattern familiar to users). I used the same color used in the border for the nav controls. Screenshots below.
#4663 
* Default Theme:
* Other Themes:
=> Adds border styling for homepage search bar on focus

app/models/user.rb
Move cached_following_podcasts_ids to Redis. This cache key is only used in one location and since there are a small number of podcasts I figured it would be a small key and safe place to start. 
Issue #4670
=> [deploy] Move cached_following_podcasts_ids to Redis

app/models/user.rb
Move cached_following_organizations_ids to Redis. This cache key is only used in one location, [user_data in the async info controller](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/async_info_controller.rb#L33) which already has a 15 min cache so having this cold should be nbd
Issue #4670
=> Move cached_following_organizations_ids to Redis

app/models/user.rb
The cached_preferred_langs method was caching an array that we don't have to make any external calls to build, we only have to run a little bit of Ruby logic. By adding an external call here we will actually end up slowing our code down. 
```ruby
irb(main):014:0> RedisRailsCache.write("fooo", [1,2,3])
=> "OK"
irb(main):015:0> Benchmark.realtime{  RedisRailsCache.read("fooo") }
=> 0.004682420985773206
irb(main):016:0> Benchmark.realtime{ me.preferred_languages_array }
=> 5.205301567912102e-05
```
Issue #4670
=> Remove Cacheing for preferred_languages_array [deploy]

app/javascript/listings/listingForm.jsx
Fixes the "Contact via Connect" checkbox so that it is actually checkable. `defaultValue` was being passed in, but unused so the state wouldn't update, but using `checked` in its place allows the state to be updated with a default value of checked.
I felt `defaultValue` didn't make a lot of sense in this context since the actual default is determined where `contactViaConnect` is defined in the `ListingForm` state. To me it made more sense to pass this default directly to `checked`. 
Fixes: #4336
=> Listings: fix 'Contact via Connect' checkbox to be checkable [deploy]

app/models/pro_membership.rb, app/models/user.rb
Move `has_pro_membership` cache to redis.
I picked a key that looked quite low risk (based on absolutely nothing else than my gut feeling). Hope that's fine!
> Can this cache safely become cold?
I think so.
> Does this cache key make sense? Is there a better/more clearer one?
I think it does make sense as is.
> Should this be a cache at all? There might be places where we can live without a cache and simply removing it might be the best move rather than switching it to Redis.
I'd leave it here.
> Does the current expiration make sense?
It seems to be one of the longest (if not the longest) expirations on the site. Again, this seems sensible considering what the key represents.
https://github.com/thepracticaldev/dev.to/issues/4670
Tentatively trying to do the right thing
=> Move has_pro_membership cache to Redis

Envfile, Gemfile, Gemfile.lock, config/initializers/honeycomb.rb, config/initializers/honeycomb_event_client.rb
Since in https://github.com/thepracticaldev/dev.to/pull/4692 we added an explicit dependency to [libhoney](https://rubygems.org/gems/libhoney) I've added it to the Gemfile, transitive dependencies are a little bit odd.
I also used `ApplicationConfig` instead of `ENV` and grouped the two initializers in the same place, this should make them easier to configure and avoid that they diverge in the future, since they are both in the same place.
It also uses [LibHoney::TestClient](https://github.com/honeycombio/libhoney-rb/blob/master/lib/libhoney/test_client.rb) during tests
=> Use libhoney explicitly and group initializers

app/labor/assign_tag_moderator.rb, app/models/user.rb, app/services/moderator/manage_activity_and_roles.rb
Move users' has_trusted_role keys to Redis.
Issue #4670
=> Move users' has_trusted_role keys to redis

app/controllers/reactions_controller.rb
Move cached_user_reactions-* keys to Redis. This cache key is only used in one location.
Issue #4670
=> Move cached_user_reactions-* keys to Redis

app/controllers/messages_controller.rb, app/models/message.rb, spec/models/message_spec.rb, spec/requests/messages_spec.rb
After we merged https://github.com/thepracticaldev/dev.to/pull/4411 we have a 500 error when a user attempts to create a message in a blocked channel. This PR updates the validation process in the model so that the whole chain triggers a 401 HTTP response instead.
It also fixes a warning we keep having when running tests:
```text
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST …
```
=> Chat message: return 401 instead of 500 when a channel is blocked [deploy]

config/initializers/honeycomb.rb
Fix the issue of trying to load a honeycomb client without key. There are a few ways to do this. This one makes sense to me.
This is the error I was trying to boot it up with `""` as the key.
`ArgumentError: No WriteKey specified. Can't send event`
=> Check for existence of honeycomb before using it

config/initializers/honeycomb.rb, config/initializers/reserved_words.rb, config/routes.rb
We plan to send people to `dev.to/future` in order to read this blog post. This adds that functionality. We could hypothetically add "redirect" as a less hardcoded functionality, perhaps as a type of `Page` since they are sort of the top level catch all.
But for now I think hardcoded is correct.
We had a handful of old hardcoded redirects from way way way way way way back in the history of the project. I think it's safe to let them die off. All it means is that a handful of links floating around the web will break, but it kind of makes sense to break with the old as we look to the future.
=> Add /future redirect

config/initializers/redcarpet.rb
There are a couple reports about being unable to display backticks within codeblock examples, but sometimes it's helpful to be able to do so.
It looks like we're using the [Redcarpet gem](https://github.com/vmg/redcarpet) to render markdown, and the gem allows [a couple configuration options](https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use)
We are using the `fenced_code_blocks` option, which allows us to create a codeblock with three or more `~` tildes or backticks, but it's recommended to use the `disable_indented_code_blocks` option with this, which would allow ignoring of indented codeblocks. Enabling this option allows users to create a codeblock, and then to display the backticks _within_ the codeblock, indent the backticks by 4 spaces.
NOTE: I am not sure if any …
=> Allow backticks within codeblocks

app/javascript/listings/listings.jsx
When I visited https://dev.to/listings/products/spell-check-your-commits-typo-ci-free-4f1n I noticed the below the "Enter your message here..." box the copy was missing spaces between some of the worlds. It read:
>  All private interactionsmustabide by the code of conduct
So I added some spaces in. Alternatively the copy could also be replaced by something from I18n, but I have no idea how to handle that in React.
Couldn't find a ticket
=> Listings Page: Adding spaces around the words in the listings message form

app/assets/stylesheets/article-show.scss, app/labor/markdown_parser.rb, spec/labor/markdown_parser_spec.rb
This PR has two parts:
- `<figure>` tags area created so that every`<figcaption>` tag is nested under a `<figure>` to produce semantically correct markup
- @Elecweb's change to fix the vertical offset of `<figcaption>` elements is incorporated
Fixes #3439
|Before|After|
|--|---|
|![image](https://user-images.githubusercontent.com/644551/60987393-cbdd7200-a341-11e9-8184-2fa212932998.jpg) | ![image](https://user-images.githubusercontent.com/18223213/67709590-7a520500-f97b-11e9-8e79-9ecfa0ea70bc.png) |
=> Wrap <figcaption> elements and content inside <figure> elements

app/controllers/api/v0/comments_controller.rb, app/models/comment.rb, spec/requests/api/v0/comments_spec.rb
This PR cleans up the comment controller code that was using an otherwise unused `rooted_on` method that was overly complicated.
I decided to submit this PR after starting to look into this https://github.com/thepracticaldev/dev.to/issues/2250 which I believe it's a separate problem that has to do with the fact that those actions both have server side caching and the edge caching active.
In the meantime we can still cleanup the code
=> Comments API: simplify controller code, add tests

.gitpod.dockerfile
Per https://www.gitpod.io/docs/42_config_docker, Gitpod only rebuilds their Docker images when the Dockerfile is changed.
This patch adds an environment variable to the Gitpod Dockerfile that can be changed in order to trigger a rebuild.
PR resolves #4703 
None
=> Add cache breaker variable, resolves #4703

app/assets/stylesheets/article-show.scss, app/views/layouts/_user_config.html.erb
Social icons are discolored on the pink theme, in the about-the-author section. 
The icons appear discolored because `--theme-secondary-color` (#4e57ef) takes priority over `transparent` in this following code snippet from article-show.scss:
```
.icon-img {
...
background: transparent;
@include themeable(
background,
theme-secondary-color,
transparent
);
}
```
This doesn't show up on the Dark or Light themes because their theme-secondary-color doesn't clash with the rest of the theme. If we can add a background for the social icons, we can control their color better for themes in the future.
BEFORE: 
AFTER:
=> Freely color social icon backgrounds for each theme. 

Gemfile, Gemfile.lock, app/models/site_config.rb, db/migrate/20191106095242_create_site_configs.rb, db/migrate/20191106102826_drop_sail_settings.rb, db/schema.rb
This PR contains the groundwork of us switching away from too many environment variables into a "site configuration" that can be managed from the "internal" administration panel.
The first step is to create a `SiteConfig` model (I chose `SiteConfig` over setting because there's pre-existing domain language around the word "setting" relative to the user's settings) and remove `sail`.
I chose to use [rails-settings-cached](http://rubygems.org/gems/rails-settings-cached) for the reasons enumerated here: https://github.com/thepracticaldev/dev.to/issues/4718#issuecomment-549802542
The next steps would be deciding what settings to add to the site config, start using them and build a panel in "internals" to manage those.
Closes 4718
=> Add site config and remove sail

app/controllers/internal/feedback_messages_controller.rb, app/views/internal/feedback_messages/index.html.erb
This adds a list of new posts and users who have a higher likelihood of being "potential spam".
This is a basic addition to our main internal support dashboard, which could maybe be renamed. We'll see how this feature maps to our capacity to catch abuse faster.
=> Add latest articles and possible spam users to internal/reports

.nvmrc
Node v12.13.0 is [the latest LTS](https://nodejs.org/en/blog/release/v12.13.0/), see also the [node download page](https://nodejs.org/en/download/). 
This change tells NVM to use the latest LTS: https://github.com/nvm-sh/nvm#nvmrc
=> Use latest Node LTS

app/controllers/async_info_controller.rb
This fixes an issue where the async info cached object is not cleared when someone is newly blocked or unblocked.
=> Add additional cache value for block

app/models/user.rb
During some cache investigating in Redis, I noticed that we make a lot of duplicate keys for these user keys because some users are updated a lot. For example here are the stats for following_organizations_ids:
```
110k keys total representing 34k users 
79k duplicates for 9100 users who have more than 2 keys in Redis bc of updated_at timestamp being updated
```
To avoid having those old, out of date keys hanging around for 5 days I shortened the expiration to 12 hours. I think having to run these quick commands an additional 10 times possibly over the course of 5 days is not going to be a big hit to performance but I do think it will save us a bit of space in Redis.   
Ideally, I want to come up with a better caching strategy to avoid leaving all these out of date keys hanging around in …
=> Expire Frequently Updated Cache Keys Sooner

app/controllers/async_info_controller.rb
This is a heavily used key that I want to move to Redis to get a better idea of how we are using it. I prepended "user-info" on to the key so that I would have something to grep for when sifting through the keys in Redis.
#4670
=> Move user_data Async Controller Cache to Redis

app/liquid_tags/jsitor_tag.rb, app/views/pages/_editor_guide_text.html.erb, spec/liquid_tags/jsitor_tag_spec.rb, spec/support/fixtures/approvals/jsitor_liquid_tag.approved.html
- can now accept full url with params
- added more test
- redo jsitor guide
as per request. Jsitor should now accept full url with optional parameters
resolves #4734
=> Redo JSitor

app/models/user.rb
This PR will move the cached_followed_tag_names cache key to Redis and it also updates it to use the following_tags_count rather than user updated_at since that is a better indicator of when this cache would become invalid. There is a small chance that a user removes a tag and then adds a new one before hitting the cache again which could cause the incorrect tag names to be grabbed. I think the chances of this are very low and because the cache resets every 24 hours, the tradeoff of more hits for that small chance of a "race condition" adding/removing tags is worth it. As always, let me know what people think of that reasoning!!! 
#4670
=> Move cached_followed_tag_names to Redis 

config/initializers/new_framework_defaults_5_2.rb
We've been running Rails 5.2 since April 3rd (https://github.com/thepracticaldev/dev.to/pull/1408), in an effort to get closer to the defaults and improve security I'm submitting this PR to flip one of the flags that are currently disabled, in this case the one selecting the encryption algorithm for cookies.
It doesn't require any other change, Rails is smart enough to update existing cookies:
https://github.com/thepracticaldev/dev.to/blob/6a8c766322a9af31c97abc42370dcdf9854493b7/config/initializers/new_framework_defaults_5_2.rb#L13-L19
(I've tested this manually)
=> Rails 5.2 features: Enable AES-256-GCM on encrypted cookies

app/services/notifications/reactions/send.rb
In line 30 when we map over the reaction_siblings we end up calling `reaction.user` so we should be preloading user when loading those Reactions to avoid N+1 queires
=> Avoid N+1 queries when sending Notifications for Reactions

app/assets/stylesheets/footer.scss
On screens above 1250px, the footer on the podcast page isn't centered. This PR fixes that. 
Resolves #4768 
Podcast page 
it works well with articles page 
Considering this is my first PR, hopefully this is a first of many 🥂
=> Center podcast page footer.

app/controllers/internal/configs_controller.rb, app/models/site_config.rb, app/views/internal/articles/index.html.erb, app/views/internal/configs/show.html.erb, app/views/internal/shared/_navbar.html.erb, app/views/layouts/internal.html.erb, config/routes.rb, spec/rails_helper.rb, spec/requests/internal/configs_spec.rb
Step 1 in switching to `SiteConfig`.
I created a MVP of how it would work for the internal admin to have the site configuration exposed.
For now I just created a `SiteConfig.main_social_image` which mirrors `MAIN_SOCIAL_IMAGE` in the environment variables.
I've also put the navigation bar on two rows, because one doesn't fit all the keys
https://github.com/thepracticaldev/dev.to/pull/4729 and https://github.com/thepracticaldev/dev.to/issues/4718#issuecomment-549802542
Demo of how it works as of now:
=> Add SiteConfig to internal and enable "main_social_image"

spec/system/dashboards/user_sorts_dashboard_articles_spec.rb
For reasons unknown to me, the `it "shows articles sorted by positive_reactions_count ASC"` test in `user_sorts_dashboard_articles_spec.rb` file failed when I ran it. (It no longer fails.)  I examined that file.  I realize that the style of test code used currently is popular, but think that if the tests were expressed differently they would have been easier for me (and, I believe, future others) to understand. The changes I recommend are in this PR. I believe they would improve the test code by:
* separating high from low level code
* enabling the high level code (`it` clause) to more clearly express the nature of the specific test (as it differs from other tests), because there is no low level code there to dilute the high level code (i.e. the call to the lambda)
* reduce the cost of …
=> Simplify sort tests in user_sorts_dashboard_articles_spec.rb

app/views/podcast_episodes/show.html.erb
Some podcast episodes have `<br>` tags in their `content_encoded`, e.g. [this ep](https://dev.to/founderquest/don-t-let-customer-service-crush-you) . While sanitizing we remove `br`s so the formatting gets broken. Maybe we could allow `br`s so that such descriptions would look better.
=> Allow while displaying podcasts episodes processed html

config/initializers/new_framework_defaults_5_2.rb
After #4216 I'm submitting this PR to get closer to Rails 5.2 default.
This change enables auto generated IDs for `form_with`, we use that only in the listings form:
https://github.com/thepracticaldev/dev.to/blob/fbbb02e241d4d91f5df4941ffe904220f3f636dc/app/views/classified_listings/_form.html.erb#L1
=> Rails 5.2 features: Enable action_view.form_with_generates_ids

app/views/layouts/_user_config.html.erb
Simply updated the `ten-x-hacker-theme` variable `--theme-anchor-color` in order to make links stand out. Currently they are the same color as the rest of the paragraph text with no other identifiers to let the user know it is a link - one literally has to hover over the text and watch the cursor change to find them.
#4794
=> Updated 'ten-x-hacker' var `--theme-anchor-color`

app/controllers/internal/configs_controller.rb, app/models/site_config.rb, app/views/internal/configs/show.html.erb, spec/requests/internal/configs_spec.rb
After https://github.com/thepracticaldev/dev.to/pull/4831 was merged I added all the various site config keys to the new model and to the page.
As agreed, for now none of these are used anywhere in the site.
=> Add additional keys to site configuration

app/controllers/moderations_controller.rb, app/controllers/tag_adjustments_controller.rb, app/models/article.rb, app/models/tag_adjustment.rb, app/services/tag_adjustment_creation_service.rb, app/views/moderations/mod.html.erb, app/views/notifications/_tagadjustment.html.erb, spec/requests/tag_adjustments_spec.rb, spec/services/notifications/tag_adjustment_notification/send_spec.rb, spec/services/tag_adjustment_creation_service_spec.rb, spec/services/tag_adjustment_update_service_spec.rb
Via /mod, This allows admin and tag moderators to add tags to articles similar to how they remove tags. I followed the functionality of the remove tags feature on the related pull requests: #1252 Allow mods to remove tags and send user notification & #3653 Allow admins to undo a tag adjustment.
> Might be some considerations around people re-tagging previously removed tags, but that could be a complication not worth thinking about.
There already is a data validation on TagAdjustment tag_name that would prevent re-tagging previously removed tags for mods. This will also prevent removing tags that were previously added by mods.
I added a second TagAdjustment form to the mod view but could refactor to combine to a single add/remove form if preferred.
Closes …
=> Mod tooling: add tags via /mod

lib/tasks/temporary/migrate_environment_variables_site_config.rake
After https://github.com/thepracticaldev/dev.to/pull/4861 the next step is to migrate environment variables values to their correspondent site configuration.
This temporary script does that.
There are two tasks, the first one displays the content of both environment variables and site configuration: `rails site_config:display_variables`
The second, `rails site_config:migrate_environment_variables` goes through the variables and copies their values from the environment to the site config. It also clears the configuration cache and displays the final values at the end. It does not copy over variables that are empty or valued "Optional" (to avoid overriding defaults).
After the script has run please check the `/internal/config` to make sure all the values are correctly set. 
Only then I'll …
=> Add script to display and migrate environment variables to SiteConfig

config/initializers/new_framework_defaults_5_2.rb
After https://github.com/thepracticaldev/dev.to/pull/4216 I'm submitting this PR to enable `AES-256-GCM` on encrypted messages as well.
Rails uses this algorithm to encrypt messages and to generate `rails secrets`. In our code we use `ActiveSupport::MessageEncryptor` in the Google Analytics controller to scramble the IP:
https://github.com/thepracticaldev/dev.to/blob/fbbb02e241d4d91f5df4941ffe904220f3f636dc/app/controllers/ga_events_controller.rb#L30-L33
After manual test I did determine that indeed the default encryption algorithm has been changed. For obvious reasons switching algorithms will generate different strings, but we do not decrypt those strings anywhere so this shouldn't be a problem.
=> Rails 5.2 features: Enable AES-256-GCM on encrypted messages

.rubocop_todo.yml, app/views/articles/_actions.html.erb
This cache is only caching simple HTML buttons and no external requests so I think it is one that we could do without rather than moving to Redis. Thoughts?
#4670
=> Remove article-main-reactions Cache Key

.rubocop_todo.yml, app/views/articles/show.html.erb
Time to start moving the view cache's to Redis. This PR moves the bottom_content for an article from Memcache to Redis. 
#4670
=> Move bottom_content Article Content to Redis

app/views/articles/_org_branding.html.erb
Initially, we were cacheing this entire org partial in Redis. However, the vast majority of the partial has already been loaded so there is no real need to cache it. The only part making an external request is to get the ProfileImage. I decided to reduce the size of the cache to only cache that external ProfileImage request rather than the entire partial. 
#4670
=> Move Organization Profile Image Cache to Redis

app/controllers/application_metal_controller.rb, app/controllers/page_views_controller.rb, spec/requests/page_views_spec.rb, spec/system/comments/user_fills_out_comment_spec.rb
This PR replaces `ApplicationController` with `ActionController::Metal` because we don't need all the rendering stuff. We instead include the couple modules we need. This should result in less overall compute/memory
Since `session_current_user_id` isn't inherited from `ApplicationController` I redefined it in this controller. Not the cleanest longterm, if anybody has a better idea for how to do this in general, let me know.
=> Remove extra dependencies for PageViewsController

app/views/articles/_org_branding.html.erb, app/views/articles/show.html.erb
The changes in #4927 and #4930 are actually causing no HTML to be rendered.
There should be "bottom content" under these articles, but the output of the fragment cache seems to be nothing.
I have to say, I kind of like the page _without_ this bottom content, which is kind of busy, but it is a bug we should fix anyway. 😋
=> Revert Redis fragment cache

spec/liquid_tags/jsitor_tag_spec.rb, spec/support/fixtures/approvals/jsitor_liquid_tag_with_hyphen.approved.html, spec/support/fixtures/approvals/jsitor_liquid_tag_with_params.approved.html
The full RSpec warning is
- [√ ] Refactor
Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`.
[4862](https://github.com/thepracticaldev/dev.to/issues/4862)
- [√ ] no documentation needed
=> Refactor raise_error(specific_error) expectation

config/initializers/rubyzip.rb
After https://github.com/thepracticaldev/dev.to/pull/4915 was merged, and `rubyzip` has been upgraded to 2.0, this patch is not needed anymore.
The initializer was present to fix a possible security bug in `rubyzip` (which we weren't affected from in production anyway).
=> Remove rubyzip initializer, unnecessary on rubyzip 2

app/controllers/application_controller.rb, app/controllers/application_metal_controller.rb, app/controllers/concerns/session_current_user.rb
This refactors `session_current_user_id` into a shared concern among `ApplicationController` and `ApplicationMetalController`.
Personally [not a huge fan of concerns](https://medium.com/@carlescliment/about-rails-concerns-a6b2f1776d7d) but if limited to actual shared controller behavior they are fine :)
See https://github.com/thepracticaldev/dev.to/pull/4923
=> Refactor session_current_user_id in a shared concern

app/controllers/page_views_controller.rb
This oft-hit endpoint doesn't need to result in a re-count _quite_ as often as it does, especially with the organic pageviews count.
Also found a logical problem where we were only updating the "past week" and "past month" counts for organic pageviews if they incremented, which is wrong for this one.
=> Modify page view recount rate in page_views_controller

CONTRIBUTING.md
Another quick doc cleanup that I realized might be out of date.
This PR includes two commits:
1) Add 80 character linewrap
2) Expand the contributing guide
This commit includes a couple of expansions on the contributing guide
including some notes concerning documentation and the code of conduct.
There are also some small mechanical fixes and a link or two was fixed.
=> Expand the contributing guide

app/services/podcasts/create_episode.rb, spec/services/podcasts/create_episode_spec.rb
`Podcasts::CreateEpisode` can potentially be called more than once with the same arguments. E.g. it can be created when the previous job hasn't finished yet. In this case the job will fail with a validation error. This pr uses `import!` from `activerecord-import` gem so that the service object would perform upsert (`ON CONFLICT DO UPDATE`).
=> Fix podcast episode validation error

.rubocop_todo.yml, Envfile, app/views/articles/_sidebar.html.erb, app/views/layouts/_styles.html.erb, app/views/layouts/application.html.erb, app/views/liquid_embeds/show.html.erb, app/views/pages/live.html.erb, app/views/pages/onboarding.html.erb, app/views/partnerships/index.html.erb, app/views/partnerships/show.html.erb, app/views/pro_memberships/show.html.erb
The original intent of DEPLOYMENT_SIGNATURE was to bust these caches on a new deploy. However, the feature never got fully implemented so currently the DEPLOYMENT_SIGNATURE just stays the same always. To fix this we can use HEROKU_SLUG_COMMIT which is an ENV variable that Heroku provides to us and can be used to bust these caches on deploy.
=> Replace DEPLOYMENT_SIGNATURE with HEROKU_SLUG_COMMIT

config/initializers/timber.rb
This pull request customizes the `UserContext` middleware in Timber to pluck the user's ID from the session instead of querying a user on each request.
This means we won't have the user's name and email natively stored in logs, which is sort of a convenience, but unnecessary since we can reference that info via the ID.
This is a minor performance improvement in a lot of cases, but affects literally every request and could amount to 10-20% gains on some basic requests.
Timber docs... https://docs.timber.io/setup/languages/ruby/integrations/rack#custom_user_hash
=> Customize UserContext Middleware in Timber logs

.gitpod.dockerfile, README.md
The setup for gitpod was not working since the last ruby version update.
This PR fixes it by also making the version being the default used one.
I have simplified the config, to not rely on the `.ruby_version` file as we have to update the dockerfile anyhow. So Instead of adding a strange UPDATE marker I believe just including the ruby version again is simpler for anyone trying to understand the setup.
Also, while at it I added the setup|automated badge to the readme.
=> Fix gitpod setup

config/initializers/fastly.rb, spec/requests/reactions_spec.rb
This set Fastly's default `max-age` parameter in `Cache-Control` back to 30 days, which is the default.
If this were only used for static assets I would raise it to much more, like one year, but it's used also to dynamic responses so the default is fine. We can revisit this when we do a proper audit of how we cache with Fastly and smooth some kinks.
Recommendation from [Google Lighthouse audits on cache policy](https://developers.google.com/web/tools/lighthouse/audits/cache-policy):
> When possible, cache immutable static assets for a long time, such as a year or longer. Configure your build tool to embed a hash in your static asset filenames so that each one is unique.
=> Set default Fastly Rails caching back to 30 days

db/migrate/20191203160028_add_missing_foreign_keys_api_secrets_listings_identities.rb, db/schema.rb, spec/models/identity_spec.rb
Step 2 of 3 of adding missing foreign keys to tables, see #4960
This adds them to `api_secrets`, `classified_listings`, `identities`
(step 1 was https://github.com/thepracticaldev/dev.to/pull/4994)
NOTE: please read the description in #4960 before merging this.
=> Add missing fks to api_secrets, listings and identities

config/initializers/redcarpet.rb, spec/support/fixtures/approvals/user_preview_article_body.approved.html, spec/support/fixtures/sample_article_template_spec.txt
This PR undo https://github.com/thepracticaldev/dev.to/pull/4438 and update a spec for regressions. Our reasoning is that this is a legacy markdown feature that our older articles depend on. We'll have to think of a different solution to resolve backtick in code blocks.
Resolve https://github.com/thepracticaldev/dev.to/issues/4956
n/a
=> Remove disable_indented_code_blocks

config/initializers/new_framework_defaults_5_2.rb
After https://github.com/thepracticaldev/dev.to/pull/4216 I'm submitting this PR to enable "protect from forgery" by default.
This won't affect us as all our controllers (internals included) inherit from our `ApplicationController` which already has a call to `protect_from_forgery`: 
https://github.com/thepracticaldev/dev.to/blob/fbbb02e241d4d91f5df4941ffe904220f3f636dc/app/controllers/application_controller.rb#L2
What Rails does when this is enabled by default is to add the following in the `ActionController::Base` controller:
https://github.com/rails/rails/blob/2b42f33fda9733d0ca91c0c1b88cc4df4b7230e8/actionpack/lib/action_controller/railtie.rb#L77-L79
Our call already overrides any possible default.
=> Rails 5.2 features: Enable default protect from forgery

app/services/notifications/notifiable_action/send.rb, spec/services/notifications/notifiable_action/send_spec.rb
Sometimes duplicate notifications could be attempted to be created in `Notifications::NotifiableAction::Send`. In this pr I specified `on_duplicate_key_update` option so that the existing records would be updated instead of failing with unique constraint violation.
=> Fix unique constraint violation on notifications create

db/migrate/20191203171558_add_missing_foreign_keys_notifications_subs_page_views_users_roles.rb, db/schema.rb, spec/policies/article_policy_spec.rb, spec/policies/chat_channel_policy_spec.rb, spec/policies/comment_policy_spec.rb, spec/policies/follow_policy_spec.rb, spec/policies/github_repo_policy_spec.rb, spec/policies/reaction_policy_spec.rb, spec/policies/user_policy_spec.rb
Step 3 of 3 of adding missing foreign keys to tables, see #4960
This adds them to `notifications_subscriptions`, `page_views`, `users_roles`
(step 1 was #4994, step 2 was https://github.com/thepracticaldev/dev.to/pull/4997)
NOTE: please read the description in #4960 before merging this.
=> Add FKs to notifications_subscriptions, page_views and users_roles

config/initializers/doorkeeper.rb, config/locales/doorkeeper.en.yml
After reading the changelog for https://github.com/thepracticaldev/dev.to/pull/4990 I realized there are quite a few new features/options in doorkeeper 5.2.2 (all disabled by default).
This updates the initializer code and incorporates some new locale strings the new doorkeepers needs for error messaging.
I ran `rails g doorkeeper:install` and merged the changes
No new features have been enabled or existing features have been changed, it just updates the files.
=> Update initializer and locales to doorkeeper 5.2.2

config/initializers/new_framework_defaults_5_2.rb
I've added some notes about why we can't enable some of the Rails 5.2 features in `config/initializers/new_framework_defaults_5_2.rb` just yet:
1. `Rails.application.config.active_record.cache_versioning` changes how cache keys are generated, there's a [nice explanation](https://blog.heroku.com/cache-invalidation-rails-5-2-dalli-store) by Heroku. TLDR; this can be enabled when we'll have migrated all the caching to Redis
2. `Rails.application.config.active_support.use_sha1_digests` changes the algorithm that generates digests when a virtual path is used, I don't know for sure if we indeed are hitting that internal Rails feature but it requires an audit and thorough testing, because it could result in unexpected cache misses
=> Rails 5.2 features: document why we can't enable some of them just yet

config/environments/development.rb, config/environments/production.rb, lib/active_support/cache/dual_rails_store.rb, spec/lib/active_support/cache/dual_rails_store_spec.rb
This new cache store, `dual_rails_store` will allow us to continue to write to Memcache while moving over keys to Redis at our own pace. I modeled this class off of a [gem I found for dual caches](https://github.com/mezis/level2) except I updated it for our purposes. 
* Any cache statement as-is will use Memcache 
* Any cache statement with the option `only: redis` will only use Redis
* Any cache statement with the option `all: true` will write to Redis and Memcache but will read/return the value read from Memcache.
What does everyone think of this approach? I like that we can continue to roll over keys at our own pace and that we can back populate any keys we deem a higher risk to roll over. 
#4670
=> Setup dual Redis store for rolling over fragment cacheing to Redis

config/initializers/honeybadger.rb, spec/initializers/honeybadger_spec.rb
Currently, we are seeing a lot of `SignalException: SIGTERM` errors from our `rake fetch_all_rss` job. I suspect these might be memory related but until we get a chance to dive in further we should group all of these errors together to avoid extra noise. Because the SIGTERM signal is received at different points in the code execution the backtraces for these errors are all different which causes them not to be grouped correctly. 
If you want to read more about how Honeybadger groups its errors checkout these [fingerprinting docs](https://docs.honeybadger.io/lib/ruby/getting-started/customizing-error-grouping.html).
=> Group SIGTERM fetch_all_rss rake task Honeybadger Errors

config/initializers/honeybadger.rb, spec/initializers/honeybadger_spec.rb
If a banned user logs in we will `raise 'BANNED'` from our Application controller. Since the users may be trying to access different routes this error will end up with different stack traces and won't be grouped appropriately in HB.
=> Group all BANNED errors in Honeybadger

config/environments/production.rb
This PR adds an environment variable that will allow us to flip over to using Redis for `Rails.cache` by simply changing an ENV variable. When an ENV variable is changed in Heroku all of the dynos are restarted which is exactly what we need to happen to trigger the use of the new cache. 
#4670 
Once the switch is made and we are confident we don't need to rollback then I will issue a PR to update all relevant docs
=> Add ENV variable to flip on Redis for fragment cacheing

.vscode/extensions.json
This adds the [OpenAPI (Swagger) Editor](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) and [openapi-designer](https://marketplace.visualstudio.com/items?itemName=philosowaffle.openapi-designer) VS Code extensions to the recommended VS Code extensions to install. The [API documentation](https://docs.dev.to/contributing_api/#running-and-editing-the-docs-locally) recommends these extension when working with the API locally.
=> Added API related extensions to the recommended VS Code extensions

config/initializers/honeybadger.rb
Currently every time a Delayed Job fails it reports the error to Honeybadger which is unnecessary since the vast majority of those jobs retry without an issue. We should only report an error when a job runs out of retry attempts. [Documentation for this option](https://docs.honeybadger.io/lib/ruby/gem-reference/configuration.html), scroll to the bottom.
=> Don't Alert Honeybadger until Right before a job is going to fail

app/views/articles/show.html.erb, app/views/users/_profile_header.html.erb, app/views/users/show.html.erb
Currently across a number of pages, there is use of [schema.org](https://schema.org) microdata (all those "itemprop" attributes etc). There are 3 references where there is use of the "mainEntityOfPage" item property however it is incorrectly used.
A ["mainEntityOfPage"](https://schema.org/mainEntityOfPage) isn't to say that this is the main entity of _this_ page, it is to say that this thing (person or article etc) is the main entity described _somewhere else_. A "mainEntityOfPage" needs to be a URL or ["CreativeWork"](https://schema.org/CreativeWork) and while an "Article" extends "CreativeWork", "Person" on the user profile page doesn't.
There is an inverse property to this, ["mainEntity"](https://schema.org/mainEntity), which is what I think you were wanting to use. It is used to say …
=> Fixing microdata main entity reference

config/initializers/honeybadger.rb, spec/initializers/honeybadger_spec.rb
Since it is the core team and moderators that are working in the internal namespace of our application there should be no need to report errors from there to Honeybadger as we would expect those folks to report any issues themselves. I would rather use Honeybadger to report errors for frontline users that may not be able to help themselves so they have to rely on us.
OPTION 2: The other option is to group these errors under an "internal" fingerprint but then I was just going to ignore that fingerprint in HB. I thought this felt cleaner. 
Let me know what you all think! Thank you! 
[More on halting errors in HB](https://docs.honeybadger.io/lib/ruby/getting-started/ignoring-errors.html#ignore-programmatically)
=> Don't send Internal Errors to HoneyBadger

app/controllers/page_views_controller.rb
Currently, we are seeing the following error when we try to call `update_column` on a new PageView
```
ActiveRecord::ActiveRecordError: cannot update a new record
```
To avoid this I choose to use `find_or_create_by` to help combine the find and where into a single statement and then I switched to using `update` rather than `update_column`. If anyone knows of a specific reason as to why we were using `update_column` here over `update` let me know!
=> Use find_or_create_by when updating a PageView 

app/controllers/async_info_controller.rb, spec/requests/async_info_spec.rb
When we cache views in Fastly we use the `remember_user_token` to help us do it. If this key changes then we need to update how we do our Fastly caching. To avoid having this key change unexpectedly, I have added a spec. I also cleaned up the spec above which was actually not stubbing the cookies correctly.
=> Ensure remember_user_token is present for Fastly with Specs

app/controllers/page_views_controller.rb
When we switched to using update the hit to performance from calling the AR callback chain was larger than we thought it would be since this model has only a single `before_create` callback. This PR goes back to using `update_column` which when I tested with `find_or_create_by` in a console did not error out, so we will see what happens!
=> Switch back to update_column For Improved PageView Performance

app/jobs/search/index_job.rb, app/models/article.rb, app/models/comment.rb, app/models/user.rb, spec/jobs/search/index_job_spec.rb, spec/models/article_spec.rb, spec/models/comment_spec.rb, spec/models/user_spec.rb
Replaced calling `AlgoliaSearch::AlgoliaJob` with the job that accepts record ids instead of ActiveRecord objects. This should help to get rid of delayed job deserialization errors.
#3594
=> Fix Algolia deserialization errors

app/controllers/articles_controller.rb
We are seeing this error a bunch in Honeybadger from trying to lookup articles when there is no owner found. This ensures we have an owner before we try to do the lookup
```
NoMethodError: undefined method `articles' for nil:NilClass
articles_controller.rb  221 set_article(...)
[PROJECT_ROOT]/app/controllers/articles_controller.rb:221:in `set_article'
219     owner = User.find_by(username: params[:username]) || Organization.find_by(slug: params[:username])
220     found_article = if params[:slug]
221                       owner.articles.find_by(slug: params[:slug])
222                     else
223                       Article.includes(:user).find(params[:id])
```
=> Ensure that we have a slug and owner before attempting Article Lookup

app/controllers/poll_skips_controller.rb
Recently got a HB(Honeybadger) when trying to create a duplicate record here thanks to our db constraints so I updated this code to be find_or_create_by to avoid that issue.
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint 
```
=> Use find_or_create_by to avoid duplicate records

docs/technical-overview/readme.md
This fixes a "Page Not Found!" error on https://docs.dev.to/technical-overview/ for the "stack" and "A few high-level things to know" links.
N/A
N/A
=> Fix Technical Overview links [ci skip]

app/views/notifications/_article.html.erb
It looks to me like these 3 cached HTML blocks contain no external requests. If that is the case then making 3 additional external requests to the cache to render them is only slowing us down and should be removed. Let me know if I am missing something!
=> Remove Caches for html that Contains No External Requests

app/services/exporter/articles.rb
=> Refactoring app/services/exporter/articles.rb

app/controllers/articles_controller.rb, app/controllers/users_controller.rb, spec/requests/articles/articles_spec.rb, spec/requests/user/user_destroy_spec.rb
Here are a couple of places in the code where we don't check for object presence before attempting to authorize it and that can lead to this error:
```
Pundit::NotDefinedError: unable to find policy `NilClassPolicy` for `nil`
```
In both cases I think it is acceptable to return a not_found response if the object we are working with is not_found.
=> Return not_found Response rather than trying to authorize a nil object

docs/backend/algolia.md
The [Algolia sign up link in the docs](https://docs.dev.to/backend/algolia/) goes to a [user's dashboard](https://www.algolia.com/apps/AJVD3Q9KL3/dashboard) and sends you to the sign-in page with an error. I updated it to go directly to the [sign-up page](https://www.algolia.com/users/sign_up) instead. 
N/A
N/A
=> Fix Algolia sign-up link [ci skip]

app/views/articles/feed.xml
As articulated in related issue below, currently passing `/feed.xml` breaks. As a default, `/feed` passes to an RSS formatter. Whereas XML full formatting is a future possibility, this at least for the moment raises an XML error saying this endpoint does not support XML formatting at this time. 
Raised in issue #5073
=> Raise an error response saying the endpoint does not support the xml format on Articles#feed.xml (#5073)

app/controllers/notifications_controller.rb, spec/requests/notifications_spec.rb
Fixes the issue we are seeing where `:filter` gets set to the value `feed` and ends up returning nil for `filtered_notifications`. I updated that behavior to simply return all user notifications. We should figure out where that feed value is getting set but I thought this solution was very safe and easy to implement so I went with this. 
```
NoMethodError: undefined method `includes' for nil:NilClass
notifications_controller.rb  29 index(...)
[PROJECT_ROOT]/app/controllers/notifications_controller.rb:29:in `index'
27                      end
28 
29     @notifications = @notifications.includes(:notifiable).without_past_aggregations.order(notified_at: :desc)
30 
31     # if offset based pagination is invoked by the frontend code, we filter out all earlier ones
```
=> Default return all user notifications if filter is unknown

app/jobs/search/index_job.rb, app/models/page_view.rb, spec/models/page_view_spec.rb
When triggering an Algolia update it is possible to [do it asynchronously](https://github.com/algolia/algoliasearch-rails#queues--background-jobs). Here I implemented the [suggested approach for delayed_job](https://github.com/algolia/algoliasearch-rails#with-delayedjob)
Any reason why we need this done inline? It seems like asynchronously should be just fine and will save us some db hits in the controller action making it faster.
=> Asynchronously Update Algolia after a PageView Update

app/views/liquids/_glitch.html.erb
Fixes the Glitch tag issue with the full screen button.
Glitch liquid tag opens a ``_blank`` page when full screen is clicked, so it was necessary to ``allow-popups`` in the iframe. 
Fixes #253
=> Fixes glitch tag full screen button

Gemfile.lock
0.17.2 was broken and removed from rubygem.org. Please see https://github.com/jnunemaker/httparty/issues/681
=> Bump httparty from 0.17.2 to 0.17.3

app/assets/javascripts/base.js.erb, app/assets/javascripts/initializers/initializeFooterMod.js, app/views/service_worker/index.js.erb, public/offline.html
We may occasionally run this code in contexts where `document.getElementById("page-content")` isn't present. This guards against that.
=> Guard for presence of page-content in JS

app/assets/javascripts/initializers/initNotifications.js, app/views/layouts/_top_bar.html.erb
This moves some of the code for displaying user profile pic and notifications count into an inline `script` tag so that it can be stored in the shell and run as soon as this code shows up on the site.
Avoids flash of black for users visiting the site. We can add any other relevant code here if we see fit.
This will speed up rendering of user info regardless of serviceworkers, but is primarily effective for the serviceworker context.
=> Move navbar rendering JS inline

app/models/organization.rb, app/models/user.rb, app/services/credits/buyer.rb, app/services/pro_memberships/biller.rb, app/services/pro_memberships/creator.rb, app/services/pro_memberships/expiration_notifier.rb, app/views/partnerships/_form.html.erb, spec/models/organization_spec.rb, spec/models/user_spec.rb
Removes `has_` prefix from question marked methods as suggested by Code Climate
This PR is a refactor as part of #3739
https://codeclimate.com/github/thepracticaldev/dev.to/app/models/organization.rb/source#issue-edd786b140b33ffc163a741d4a5a6d05Mobile & Desktop Screenshots/Recordings (if there are UI changes)
=> Refactor all has_enough_credits to enough_credits

app/controllers/application_controller.rb, spec/requests/articles/articles_spec.rb
We have been seeing a lot of `ActionView::MissingTemplate` errors when people try to request invalid formats for routes. This can lead to a lot of noise in Honeybadger so I updated that error to raise an `ActiveRecord::RecordNotFound` which is ignored by default by Honeybadger
=> Return ActionController::RoutingError error when Invalid Format is Requested

app/views/service_worker/index.js.erb
I've been having issues with the Twitter in-app browser for iOS. Multiple visits to DEV in the same Twitter session causes the browser to hang and just stop working. It seems highly likely that this is related to serviceworkers. I'm not entirely sure what the problem might be or that it is definitely fixable in this way, but it's worth a shot to get this working properly. Shouldn't affect much else.
It's unlikely this would affect Android due to the better serviceworker support. Haven't discovered problems in other iOS apps yet. We may get to the bottom of it, we may forever have this hack in. Who knows?
Also added a condition for `/future` which also has issues with serviceworkers due to our other redirect hacks in place.
=> Skip serviceworker logic for Twitter iOS referrals

app/labor/markdown_parser.rb, spec/labor/markdown_parser_spec.rb
Rather than raising an error that will propagate all the way up to our error reporting service, lets simply alert the user that a liquid tag failed to render and allow them to fix it themselves. Obviously this leads to a little bit of a different user experience so I am interested in what people think. 
**Current Flow: User puts in an invalid tag**
Preview
Save Attempt just hangs
**NEW Flow**
Preview error examples:
Save Attempt either raises an error to the user
OR saves the error message as the html
=> Dont Raise Error For Incorrect Liquid Tags

config/initializers/honeybadger.rb
We get a lot of `ActiveRecord::QueryCanceled` errors in Honeybadger due to PG timeouts. We are not really concerned with these when they occur occasionally, we are more concerned if we suddenly see a large spike in them. For this reason, I choose to ignore this error in Honeybadger and instead set up an alert for it through our logging service Timber. Now if we see more than 200 of these errors in under 100 seconds we will be alerted via slack.
=> Ignore ActiveRecord::QueryCanceled errors in Honeybadger

app/controllers/internal/badges_controller.rb, app/views/internal/badges/index.html.erb, spec/requests/internal/badges_spec.rb, spec/services/notifications/new_badge_achievement/send_spec.rb, spec/system/internal/admin_awards_badges_spec.rb
Add a default message to badge award action
Because:
- The only badges routinely awarded manually use the same message
- Right now, unfriendly/unsafe UI can result in an error notification
The only badges that are currently awarded manually (afaik) have the
message "Congrats!!!" so for the time being, if a message is not
supplied to the UI, it will simply use the "Congrats!!!" message as a
default.
That being said, I'm not totally convinced this message won't work for
the long term. Generally, if we are awarding badges by hand, I'd imagine
we'd want a specific message explaining why we are doing that, or just
be okay with "Congrats!"
After talking with Peter about it, the longer term goal should be to
move badge messages into the database so they can be modified in the app
and not …
=> Add a default message to badge award action

app/controllers/video_states_controller.rb, spec/requests/video_states_update_spec.rb
There are times when we can't find the article in this action. I am not sure why but the quick fix is to handle that not_found case. 
```
NoMethodError: undefined method `update' for nil:NilClass
video_states_controller.rb  21 create(...)
[PROJECT_ROOT]/app/controllers/video_states_controller.rb:21:in `create'
19     message_json = JSON.parse(request_json[:Message], symbolize_names: true)
20     @article = Article.find_by(video_code: message_json[:input][:key])
21 >>> @article.update(video_state: "COMPLETED") # Only is called on completion
22     NotifyMailer.video_upload_complete_email(@article).deliver
23     render json: { message: "Video state updated" }
```
=> Return not_found Response If Video's Related Article is Not Found

app/assets/javascripts/initializers/initializeAllFollowButts.js, app/assets/javascripts/initializers/initializeReadingListIcons.js, app/assets/javascripts/utilities/buildArticleHTML.js.erb, app/assets/stylesheets/articles.scss, app/assets/stylesheets/more-articles.scss, app/views/articles/_single_story.html.erb, app/views/articles/index.html.erb
Inside the [search result page](https://dev.to/search?q=test&filters=class_name:User), when you select to search by people on the sidebar and click the button to follow someone, it was erroneously triggering a reaction ajax request, thus not having the `reactable_id`:
_If you click any of those follow buttons you'll see the failed ajax request on console._
It gets called because all buttons with the `bookmark-engage` class get that event assigned to it. And the follow buttons use that class too, probably only to have the same styling. 
There are many ways to solve this problem, I've updated the CSS classes in a way those buttons have a common styling class `.engage-button` to look the same. Then, the event for the "reactions" is only added …
=> Fix #5072: Remove unnecessary reaction call

app/controllers/social_previews_controller.rb, app/views/social_previews/comment.html.erb
By design, we don't require comments to have a related commentable entity. The reason for this is because the comment first and foremost belongs to a user and we still want them to be able to access that comment even if what they were commenting on is removed. For this reason, we need to handle the situation where commentable is not present rather than assume it always is and end up with errors like this:
```
NoMethodError: undefined method `decorate' for nil:NilClass
social_previews_controller.rb  43 comment(...)
[PROJECT_ROOT]/app/controllers/social_previews_controller.rb:43:in `comment'
41   def comment
42     @comment = Comment.find(params[:id])
43     @tag_badges = Badge.where(id: Tag.where(name: @comment.commentable.decorate.cached_tag_list_array).pluck(:badge_id))
44 
45 …
```
=> Handle missing commentable In Social Preview

app/controllers/organizations_controller.rb, spec/requests/organizations_update_spec.rb
Rather than erroring out like below by trying to authorize nil we should raise an ActiveRecord::RecordNotFound error instead
```
Pundit::NotDefinedError: unable to find policy `NilClassPolicy` for `nil`
organizations_controller.rb  82 set_organization(...)
[PROJECT_ROOT]/app/controllers/organizations_controller.rb:82:in `set_organization'
80   def set_organization
81     @organization = Organization.find_by(id: organization_params[:id])
82     authorize @organization
83   end
84 end
```
=> Raise ActiveRecord::RecordNotFound if Org is Not Found

app/views/service_worker/index.js.erb
This skips serviceworkers on article preview pages, which is sort of a hack because the serviceworker ignores the `3xx` status code we'd expect when redirecting to this page after making an update. However, this conflicts with the patch we have in our edge cache which ignores `3xx` responses in order to ensure we beat any race conditions.
This strikes me as the only overly problematic situation so this fix should help. We should work to ultimately find a better longterm solution for this and similar service worker gotchas.
=> Don't serviceworker cache ?preview= requests

app/controllers/page_views_controller.rb
We have been running into the error `ActiveRecord::ActiveRecordError: cannot update a new record` a lot when we try to call `update_column` on a new record. One attempt I made to avoid this was to change `update_column` to `update` but that led to a big performance hit for this endpoint so we reverted that change. This PR updates that statement to run the exact same SQL as the `update_column` command except we don't try to do it through the AR model object. What do you all think?
=> Use raw SQL to Update page_views so new and existing Records can be updated

lib/tasks/fetch.rake
This adds a rake task to automatically reward tag badges every Thursday (when accompanied by a daily Heroku scheduler).
Currently I've been doing this myself and a robot could do it much better.
I also changed the period where we clean old data for HTML Variants while I was here. 1 week is a bit too erratic for data, even if we're looking to keep things recent and fresh.
After this is merged we then add the Heroku scheduler.
=> Add rake task to reward tag badges weekly

app/controllers/page_views_controller.rb
Reverts thepracticaldev/dev.to#5167
Works in a prod console, works on dev, does not work in prod on the web. Definitely missing something
=> Revert "Use raw SQL to Update page_views so new and existing Records can be updated"

spec/factories/podcast_episodes.rb
I have noticed podcast specs failing intermittently with an invalid error bc slugs and guids are not unique. This can happen when you are using random numbers so I changed them to be sequenced instead.
```
1) User visits /pod page doesn't dsplay a podcast that is not published
Failure/Error: let!(:unpublished_episode) { create(:podcast_episode, podcast: podcast) }
ActiveRecord::RecordInvalid:
Validation failed: Guid has already been taken
```
#4884
=> Flaky Spec Fix: Sequence factory podcast episode slugs and guids to ensure uniqueness

app/controllers/api/v0/articles_controller.rb, spec/requests/api/v0/articles_spec.rb
Instead of raising a 500, let's return a usable error to the user when they are trying to create an article through the API. While I was here I changed the other hash traversals to arrays as well since I think it looks cleaner and avoids those pesky `NoMethodError: undefined method `[]' for nil:NilClass` errors
=> Return 422 if params are missing when creating an article via the API

spec/factories/articles.rb, spec/factories/badges.rb, spec/factories/chat_channels.rb, spec/factories/collections.rb, spec/factories/github_repos.rb
We have a lot of properties of models that are expected to be unique. In order to generate some of these, we are relying on random numbers which could theoretically end up being the same. To ensure uniqueness I have changed a few of these attributes to use the [sequence function offered by factory bot](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences). 
#4884
=> Flaky Spec Fix: Ensure model properties in factories are unique

app/controllers/api/v0/users_controller.rb, spec/requests/api/v0/users_spec.rb
If none of these if statements can be executed then return a not_found response for the users index API.
=> Return not_found response if we cant return users via the api

spec/system/user_selects_looking_for_work_spec.rb
I found this flaky spec after merging another flaky spec fix ironically in [this build](https://travis-ci.com/thepracticaldev/dev.to/builds/141958459). Here is my thought, the [perform_enqueued_jobs](https://api.rubyonrails.org/v5.2.3/classes/ActiveJob/TestHelper.html#method-i-perform_enqueued_jobs) will "Perform all enqueued jobs in the duration of the block." However, if we make an assertion before the end of the block then there is a chance that our job never finished. To ensure that the job finished I believe we should be making the assertion outside of that block. 
What do you all think? There are a lot of spec where we make assertions in these blocks that I think could be made more reliable by moving the assertions outside of the blocks.
#4884 
Flaky specs are like cockroaches...
=> Flaky Spec Fix: Check user follow count AFTER job is run

spec/factories/comments.rb, spec/system/comments/user_edits_a_comment_spec.rb
In this spec we are relying on the comment path in order to visit the comment page and assert that the user can edit it. This path is created in the background by a job, `Comments::CreateIdCodeJob`  which may or may not have time to run after we create a comment hence leading the spec to fail. I updated the factory with a trait that will run that job inline whenever we need the path present for a comment in a spec. There are probably other places this is needed but this is the one that was in the issue so I only tackled that. 
https://github.com/thepracticaldev/dev.to/issues/4889
=> Ensure Comment has a path when created for specs

app/assets/stylesheets/chat.scss, app/assets/stylesheets/scaffolds.scss, app/controllers/chat_channels_controller.rb, app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap, app/javascript/chat/__tests__/channels.test.jsx, app/javascript/chat/actions.js, app/javascript/chat/channels.jsx, app/javascript/chat/chat.jsx, app/javascript/chat/message.jsx, spec/requests/chat_channels_spec.rb
Currently we fetch chat channels on load of `/connect` via Algolia, which means things are fast and the search engine for channel list is also very fast and compatible.
But since Algolia is async, we sometimes run into problems with not properly displaying the "opened" quality of chat channels.
This PR addresses it by breaking things out and offering a separate endpoint to handle the open status.
Using Algolia in this manner is really not ideal in general. The instant search part is great, but everything else is more trouble than it's worth I think. We can seek to change this approach gradually. For now this addresses the biggest source of pain.
=> Separate chat channel unopened status from Algolia

app/javascript/chat/chat.jsx, app/javascript/src/utils/getUnopenedChannels.jsx, app/models/message.rb
Adds the `/new` trigger which opens up a sidecar with the `/new` composer.
This is a simple PR which makes use of the iframe sidecar.
Also tacked on some functionality to ensure the "you received a message" banner doesn't show up _within_ the iframe context and some fix to ensure unpublished posts can be shared with their appropriate password.
=> Add ability to open /new in connect sidecar

app/views/social_previews/article.html.erb, app/views/social_previews/comment.html.erb, app/views/social_previews/user.html.erb, spec/requests/social_previews_spec.rb
Fixing the twitter card caching ⚡️ ⚡️ 
The tests weren't catching this because article/user didn't have Badges in the tests.
Updated to make the badge rotation `not_so_random`. Aka, they are still random and look cool. But don't change each render. Making the caching way more efficient.
=> Improve twitter card caching

app/controllers/api/v0/follows_controller.rb
We should return the actual count of users followed rather than 50
=> Show Count of users followed from API

app/controllers/api/v0/users_controller.rb, spec/requests/api/v0/users_spec.rb
A common response in collection endpoint with REST APIs is to return an empty result set when the requested params end up in an empty result. The reason for this is that the resource itself exists (the collection always exists), it just is empty.
Also, all other collections return no values, not 404.
For more rationale: https://stackoverflow.com/a/13367198/4186181
Basically the difference is:
- if I ask for ID 1 and ID 1 is not present in the DB then `404 Not Found` because the resource does not exist and will never exist
- if I ask for a collection of items (filtered or not), the resource (the collection) exists, it's just it contains nothing, hence `200 OK` with no result
See https://github.com/thepracticaldev/dev.to/pull/5192
=> API: Return an empty result set instead of 404 in case users are not available

app/controllers/api/v0/chat_channels_controller.rb, spec/requests/api/v0/chat_channels_spec.rb
I noticed we were getting a very undescriptive RuntimeError from this endpoint when problems arose with the action. 
```
RuntimeError:
chat_channels_controller.rb  6 show(...)
[PROJECT_ROOT]/app/controllers/api/v0/chat_channels_controller.rb:6:in `show'
4       def show
5         @chat_channel = ChatChannel.find(params[:id])
6         raise unless @chat_channel.has_member?(current_user)
7       end
8     end
```
I updated the logic to return a not_found error in the event that the channel doesnt exist or that the user does not have access to it. I also noticed that this API controller was not using the ApiController base so I updated that. If there was a reason we were not using the ApiController let me know!
=> Use ApiController for ChatChannels and Return not_found If no Channel

app/helpers/application_helper.rb, lib/tasks/fetch.rake
This PR fixes 2 Honeybadger errors:
Having an invalid timeframe when loading a title for an article.
```
ActionView::Template::Error: key not found: "foobar"
application_helper.rb  41 fetch(...)
[PROJECT_ROOT]/app/helpers/application_helper.rb:41:in `fetch'
39     }
40 
41     title_text = "#{page_title} - #{sub_titles.fetch(timeframe)}"
42     content_for ? title(title_text) : title_text
43   end
```
Trying to return from a rake task:
```
LocalJumpError: unexpected return
fetch.rake  53 block in <main>(...)
[PROJECT_ROOT]/lib/tasks/fetch.rake:53:in `block in <main>'
51 
52 task send_email_digest: :environment do
53   return if Time.current.wday < 3
54 
55   EmailDigest.send_periodic_digest_email
```
Nothing to do with the PR but its Xmas eve!!!!
=> Fix title_with_timeframe and Update rake task to not use return

app/services/notifications/new_follower/send.rb, spec/services/notifications/new_follower/send_spec.rb
This fixes a timing error that caused Notifications::NewFollower::Send to sometimes fail. 
Basically the logic relies on the fact that follows never have the same exact creation date, which is not always true for tests. See the following comment for a more thorough explanation on how I tracked the bug and came up with the solution: https://github.com/thepracticaldev/dev.to/issues/5157#issuecomment-568749969
Kudos to @robbkidd https://github.com/thepracticaldev/dev.to/issues/5157#issuecomment-567612116 for the huge help in dissecting with `git bisect` !!!
Closes https://github.com/thepracticaldev/dev.to/issues/5157
=> Fix flaky Notifications::NewFollower::Send spec

app/labor/function_caller.rb, spec/labor/function_caller_spec.rb
Sometimes aws lambda client returns an empty result which leads to `Comments::CalculateScoreJob` failure. This pr handles this case.
I also changed the `FunctionCaller` spec to use `Struct` instead of `OpenStruct`.
=> Handle a case when lambda client returns an empty result

app/controllers/page_views_controller.rb, spec/requests/page_views_spec.rb
OK, folks, I have finally figured it out! This endpoint will raise this error `ActiveRecord::ActiveRecordError: cannot update a new record` when we attempt to make a PageView that is not valid. For example a page view for an article that does not exist. In the event that this happens we should skip attempting to update the page_view.
Why `new_record?` instead of a `valid?` check? The reason I went with the new_record over valid is that valid would have hit the database to validate the Article and User AGAIN. Since we already did that when we attempted to make the PageView we may as well skip that and trust that if the page view is a new record it could not persist bc it is invalid.
=> Only Update page_views When They Are Valid (ie created)

app/controllers/articles_controller.rb, app/controllers/comments_controller.rb, app/controllers/users_controller.rb, app/services/notifications/new_follower/send.rb
As I was browsing the controller code, I saw some especially long lines that were too long to fit on my 13" laptop screen. In addition to accommodating narrower screens:
* some of the changes put key/value pairs on their own lines, which speeds up visual scanning
* `if`'s that were especially far right on the line will even be off the screen on some screens, but even when not, because of their placement, might easily be missed. (My personal preference would be to go even farther than this, but I realize I'm an outlier on this.)
I am now marking this WIP because Rubocop forced the text to the right, making it worse than before; should I revert that change, or do we want to reconsider Rubocop config settings?
Old:
New:
Old:
New:
(See note above about Rubocop changes.)
- [x ] no …
=> Reformat some code to break up especially long lines.

app/controllers/api/v0/api_controller.rb, app/controllers/api/v0/github_repos_controller.rb, spec/requests/api/v0/github_repos_spec.rb
Couple things happening here:
1. Return a human readable error if Github creds do not work.
2. Have the API `GithubReposController inherit from the `ApiController` so that its behavior is consistent with the rest of the API. 
Prevents [this error](https://app.honeybadger.io/projects/66984/faults/58184430) from hitting Honeybadger
```
Octokit::Unauthorized: GET https://api.github.com/user/repos?per_page=100: 401 - Bad credentials // See: https://developer.github.com/v3
github_repos_controller.rb  9 index(...)
[PROJECT_ROOT]/app/controllers/api/v0/github_repos_controller.rb:9:in `index'
7           where(user_id: current_user.id, featured: true).pluck(:github_id_code) #=> [1,2,3]
8         existing_user_repos = Set.new(existing_user_repos)
9         @repos = client.repositories.map do …
```
=> Return a 401 Response when Github creds are bad via the API

db/migrate/20191226202114_add_created_at_index_to_notifications.rb, db/schema.rb
Was trying to run the [new code](https://github.com/thepracticaldev/dev.to/pull/5180) for removing notifications in a console and was still getting timeouts. I discovered we don't have an index on created_at which would be extremely helpful for our `<` queries.
=> Add Index to Notifications created_at

spec/labor/markdown_parser_spec.rb
When running this specific spec you get:
> WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /home/travis/build/thepracticaldev/dev.to/spec/labor/markdown_parser_spec.rb:200:in `block (3 levels) in <top (required)>'
This fixes that
=> Fix deprecation for not_to raise_error

app/views/service_worker/index.js.erb
Through the gems delayed_job and sidekiq we add their respective dashboard. Sidekiq is still not part of the code but it's soon to be so I went ahead and added that exception here as well.
Closes https://github.com/thepracticaldev/dev.to/issues/5261
Before
After
=> Ignore delayed job and sidekiq dashboards in the service worker

spec/models/notification_spec.rb
While refactoring model specs I learned that one of the keys to keeping them fast is to create as few data as possible for a test to complete.
Instead of creating 10 notifications here we only create 3.
=> Create less data for Notification.fast_destroy_old_notifications spec

app/views/articles/show.html.erb, spec/requests/stories_show_spec.rb
Includes canonical URL even in the "internal" version of the page, which we now render for all cases where serviceworkers run the show.
The "machine readable" version still includes the canonical in the head. The user-readable version where service workers are turned on includes it streamed into the body.
This was never "technically" broken, but fixes confusion here:
closes https://github.com/thepracticaldev/dev.to/issues/5156
=> Add canonical url to posts even if internal nav

spec/models/tag_adjustment_spec.rb
Flaky spec popped up in @rhymes recent PR this change ensures that tag list always returns with more than 3 items.
```
1) TagAdjustment validates article tag_list does not allow addition on articles with 4 tags
Failure/Error: expect(tag_adjustment).to be_invalid
expected `#<TagAdjustment id: nil, adjustment_type: "addition", article_id: 378, created_at: nil, reason_for_ad... "reason 8156", status: "committed", tag_id: 1371, tag_name: "tag41", updated_at: nil, user_id: 613>.invalid?` to return true, got false
Finished in 6 minutes 20 seconds (files took 7.13 seconds to load)
3194 examples, 1 failure
Failed examples:
rspec ./spec/models/tag_adjustment_spec.rb:75 # TagAdjustment validates article tag_list does not allow addition on articles with 4 tags
```
=> Flaky Spec Fix: Ensure that article tag_list always has more than 3 tags

lib/tasks/fetch.rake
Here I am gathering the _estimated_ counts for a few key database tables. **Are there any other tables that we want to record data for?** These were the ones the seemed the most important to me. I choose not to use `.count` and instead, go with the estimate from Postgres bc doing a count can be notoriously slow especially on big tables. Trying to do it on Notifications or PageViews will lead to a timeout.  How accurate your estimate depends on how often ANALYZE is run on your postgres database. I was trying to figure that out for our add-on but gave up. It is run enough for our estimates to be pretty accurate which you can see below. 
```
irb(main):095:0> User.count
=> 294448
irb(main):097:0> ActiveRecord::Base.connection.execute("SELECT reltuples::bigint AS estimate FROM pg_class where …
```
=> Record counts for important db tables to help track growth

config/initializers/sidekiq.rb
Right now when I try to view the Sidekiq dashboard I get a runtime error. I dug a little bit and found out that it has issues - https://github.com/redis-store/redis-rails/issues/34 - with the combo `redis-rails` and `devise`, which is what we use for sessions.
Since we rely on Devise to guard the access, we don't need Sidekiq sessions
- [Sidekiq Monitoring: sessions being lost](https://github.com/mperham/sidekiq/wiki/Monitoring#sessions-being-lost)
- [ Not sharing session with sidekiq web-ui](https://github.com/redis-store/redis-rails/issues/34)
- [Allow to disable sessions](https://github.com/mperham/sidekiq/pull/3183)
Before
After
=> Disable Sidekiq web sessions to make it work with Redis sessions

app/controllers/reactions_controller.rb
Sometimes an organization related to an article gets destroyed but the article remains. In those cases when someone reacts to the Article we should not attempt to send notifications to the missing organization. Fixes [this honeybadger](https://app.honeybadger.io/projects/66984/faults/58887009):
```
NoMethodError: undefined method `id' for nil:NilClass
notification.rb  163 reaction_notification_attributes(...)
[PROJECT_ROOT]/app/models/notification.rb:163:in `reaction_notification_attributes'
161         reactable_user_id: reaction.reactable.user_id
162       }
163       receiver_data = { klass: receiver.class.name, id: receiver.id }
164       [reactable_data, receiver_data]
165     end
```
=> Check if an organization is present when creating a reaction

spec/services/medium_article_retrieval_service_spec.rb, spec/support/initializers/capybara.rb, spec/system/internal/admin_bans_or_warns_user_spec.rb, spec/system/user_selects_looking_for_work_spec.rb
What I think is happening when this spec fails is that the request to update a user is not allowed to finish before we validate that the user has been updated. By checking the page for the success message we ensure that Capybara will wait to check the user status until after the request has completed.
I also updated our Capybara wait timeout to 10 to see if that would help us at all. We had a pretty extensive and solid test suite at Kenna and that was our default so I figured it was worth a try. 
#4884
=> Flaky Spec Fix: Ensure submit requests finish before checking status of user

app/views/shell/_top.html.erb
This reverts commit 2312d2e301c77cbb18da861e84f0086bf40248c0.
The reasoning for this revert is that it is a fix for a problem that might not exist.  I had trouble reproducing the escaped ampersand locally and the title in h1 tag on article show renders properly without an escape/unescape. This might be an issue unique to the reported post and the fix should instead target the portion of the process that is escaping the title.
see discussion https://github.com/thepracticaldev/dev.to/pull/5246#issuecomment-569311248
https://github.com/thepracticaldev/dev.to/issues/5226
Creating a post with ampersand
=> Revert "Unescape page title. (#5246)"

app/labor/rate_limit_checker.rb, app/workers/rate_limit_checker_worker.rb, config/initializers/sidekiq.rb, spec/labor/rate_limit_checker_spec.rb, spec/workers/rate_limit_checker_worker_spec.rb
This PR is what I plan to use to lay the foundation for what a Sidekiq worker rollover should look like. For this job, since it is not executed a lot I choose to cut straight over and remove the old worker in the same PR. This moves the RateLimitCheckerJob to Sidekiq and renames it.
I believe tracking the progress of the move will be easier with the rename and it allows us to move jobs over and keep old job classes for those that run frequently and we may need to allow queues to drain.
=> Change RateLimitCheckerJob to RateLimitCheckerWorker and Move to Sidekiq

config/environments/production.rb
`redis_store` was initially introduced to switch sessions from the cookie store to Redis in https://github.com/thepracticaldev/dev.to/pull/4004. When we introduced a dual cache store in https://github.com/thepracticaldev/dev.to/pull/4991 we forgot to use the builtin Rails cache store - [ActiveSupport::Cache::RedisCacheStore](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore) - and instead kept using the external [ActiveSupport::Cache::RedisStore] which comes from the `redis-activesupport` gem included by `redis-rails`.
The gem `redis-activesupport` contains this disclaimer:
> Rails 5.2.0 includes a Redis cache store out of the box, so you don't really need this anymore if you're generating a new Rails application. We are no longer accepting new …
=> Switch external redis_store to Rails supported redis_cache_store

app/assets/stylesheets/minimal.scss, app/assets/stylesheets/theme-selector.scss, app/views/users/_misc.html.erb, app/views/users/_theme_selector.html.erb
Add a theme selector to user settings which displays what the theme looks like. Thanks @Link2Twenty for the cool mock-up :)
Fixes #2158
=> Add theme selector to user settings

config/initializers/datadog_apm.rb, config/initializers/honeybadger.rb
- Track Sidekiq jobs in Datadog
- Only return Sidekiq errors to Honeybadger after the 10 retry or once the job has exhausted retries
=> Add Sidekiq Monitoring for Datadog and Honeybadger

config/sidekiq.yml
Before we start rolling over jobs we need to set up a few more [Sidekiq queues](https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues).  Next to each queue is a number that represents its importance. The higher the number the more important the queue is and the fast those jobs will be executed. The numbers are actually a ratio. In the event that every queue is full we will execute 1000 `high_priority` jobs for every 100 `medium_priority`, every 10 `low_priority` etc.
This is a similar setup we had at Kenna plus a couple more actually based on worker volume. For now, I didn't include those but we can add a couple more depending on how it all balances out. Queue balancing is an art and usually involves monitoring things as they get moved over and then making tweaks.
=> Setup Sidekiq queues for different priority jobs

app/labor/function_caller.rb, spec/labor/function_caller_spec.rb
Sometimes aws lambda client returns an empty result which leads to `Comments::CalculateScoreJob` failure. I started fixing it in #5248 but I still see failing jobs once in a while. I added another check to fix this issue.
=> Add another check to the function caller to avoid exceptions

spec/services/exporter/articles_spec.rb, spec/services/exporter/comments_spec.rb
Use array_match rather than eq to ignore order.
Example of spec failure.
```
4) Exporter::Comments#export when all comments are requested returns only expected fields for the comment
Failure/Error: expect(comments.first.keys).to eq(expected_fields)
expected: ["body_markdown", "created_at", "deleted", "edited", "edited_at", "id_code", "markdown_character_count", "positive_reactions_count", "processed_html", "receive_notifications", "commentable_path"]
got: ["edited", "created_at", "id_code", "deleted", "receive_notifications", "markdown_character_count", "edited_at", "body_markdown", "processed_html", "positive_reactions_count", "commentable_path"]
(compared using ==)
```
#4884
=> Flaky Spec Fix: use match_array instead of eq to ignore ordering

app/services/medium_article_retrieval_service.rb, spec/services/medium_article_retrieval_service_spec.rb
This fixes the following warning:
> MediumArticleRetrievalService
when valid medium url
[DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568
/gems/ruby-2.6.5/gems/nokogiri-1.10.7/lib/nokogiri/html/document.rb:199:in `parse'
returns a valid response
also removes a useless HTTP call and stub in the spec
=> Nokogiri::HTML should receive the body, not the response object

app/assets/stylesheets/moderators.scss, app/controllers/moderations_controller.rb, app/views/moderations/index.html.erb, spec/requests/moderations_spec.rb
While we wait on other ways to display counts, this caches the queries on `/mod` which are currently _just a bit_ too expensive. I'm sure there are better queries than what we have to begin with, but this is probably a solid choice either way. This data doesn't need to be ultra fresh, and the performance win should be really helpful for making this page really usable.
=> Cache data on /mod

app/models/article.rb, app/workers/articles/bust_cache_worker.rb, spec/rails_helper.rb, spec/workers/articles/bust_cache_worker_spec.rb, spec/workers/shared_examples/enqueues_on_correct_queue.rb
This creates a new BustCacheWorker and starts sending jobs to it. Once this is deployed I will open a second PR to remove the old job code.
#5305
=> Create new BustCacheWorker and start sending jobs to it

app/controllers/api/v0/github_repos_controller.rb, spec/requests/api/v0/github_repos_spec.rb
In the event that we don't find a repo in Github we should fail gracefully rather than [raising an error](https://app.honeybadger.io/projects/66984/faults/58896866).
```
NoMethodError: undefined method `id' for nil:NilClass
github_repos_controller.rb  41 fetched_repo_params(...)
[PROJECT_ROOT]/app/controllers/api/v0/github_repos_controller.rb:41:in `fetched_repo_params'
39         end
40         {
41           github_id_code: fetched_repo.id,
42           user_id: current_user.id,
43           name: fetched_repo.name,
```
=> Handle Unfound Github repo in API

datadog/prerun.sh
Datadog charges on a by host basis and since the schedulers only run once a few times a day I dont think it is worth it to track them in Datadog. Furthermore, with moving to Sidekiq, eventually, we might be able to get off Scheduler completely.  
[Here are the Datadog docs on prerun scripts](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script). Looks like you just put it in the expected file path and it just works 🤷
#4925
=> Don't run Datadog Agent on scheduler Dynos

spec/services/bulk_sql_delete_spec.rb
Set timestamp in the future so Notifications created are for sure destroyed and decrease the counts to make it a smidge faster. 
All good now
=> Fix flaky delete spec by setting timestamp in the future and Decrease Notification Counts

spec/rails_helper.rb
Sidekiq doesn't clear the jobs queue between tests, tests should be isolated and thus the job queue should be empty between each test.
This should be merged ASAP because a lot of Sidekiq worker specs will rely on counting the number of jobs in a specific queue, without this counts will likely be off in many cases, see also the failing build here https://travis-ci.com/thepracticaldev/dev.to/builds/142775786
Part of #5305
=> Clear Sidekiq jobs between tests

app/models/notification.rb, app/workers/notifications/mention_worker.rb, spec/requests/notifications_spec.rb, spec/workers/notifications/mention_worker_spec.rb
I followed the PR [here: ](https://github.com/thepracticaldev/dev.to/pull/5302)
This creates a new MentionWorker and starts sending jobs to it from the Notification model. Once this is deployed, I will open a second PR to remove the old code.
Starting small, if this looks good, i can tackle more of the Notification jobs :)
=> Change MentionJob to MentionWorker and move to sidekiq

spec/rails_helper.rb, spec/support/sidekiq_test_helpers.rb, spec/workers/rate_limit_checker_worker_spec.rb
This PR adds some test helpers modeled after [ActiveJob::TestHelper](https://api.rubyonrails.org/v5.2/classes/ActiveJob/TestHelper.html) in Rails.
Those purely "rspeccy" are missing, mostly because I didn't want to go down the RSpec rabbit hole (I admit I find RSpec too "magic" and never fully understood how it works :D). If anyone wants to add them, please be my guest.
I didn't convert all `ActiveJob` test helpers, only those that I found that are used in the codebase.
All helpers are prefixed with `sidekiq_` to avoid name clashing with those in `ActiveJob`, maybe when the transition is finished we can remove the prefix, or not.
I tested all helpers manually :)
#5305
=> Sidekiq: add test helpers

config/initializers/new_framework_defaults_5_2.rb
Among the notable Rails 5.2 features is the ability to recycle cache keys, aka cache versioning. It is supported by all builtin cache stores and now that we've migrated to Redis and are using the builtin `:redis_cache_store` - https://github.com/thepracticaldev/dev.to/blob/ee8fd7cbc22f2edaced8163b4eabb192ebde5849/config/environments/production.rb#L106 - we can effectively enable this feature.
This will get us one step closer to Rails 5.2 defaults and help transitioning to Rails 6
**NOTE: this does NOT generate cache misses, nor it generates new keys, it just helps with a smarter invalidation**
**What does this feature do?**
Adds efficiency to cache invalidation by separating the cache key from the cache version. 
> With the new method of cache versioning, the keys stay consistent, but the …
=> Rails 5.2 features: enable cache versioning (recyclable keys)

app/lib/reverse_markdown/converters/custom_pre.rb, spec/lib/reverse_markdown/converters/custom_pre_spec.rb
Solves thepracticaldev/dev.to#5298
See thepracticaldev/dev.to#5298 - allows detecting `<pre class="language-js">` as a language definition for code. 
thepracticaldev/dev.to#5298 
N/A
=> Allow language-xxx class detection on pre tags in ReverseMarkdown

app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap, app/javascript/article-form/elements/__tests__/tags.test.jsx, app/javascript/shared/components/tags.jsx
This fixes an error in which clicking on the inner rules box would insert `undefined` as a tag, instead of the tag itself.
Closes https://github.com/thepracticaldev/dev.to/issues/5277
=> Fix event propagation for click on tag rules in editor

app/controllers/async_info_controller.rb, app/controllers/dashboards_controller.rb, app/workers/articles/update_analytics_worker.rb, spec/workers/articles/update_analytics_worker_spec.rb
Create UpdateAnalyticsWorker to replace UpdateAnalyticsJob. I choose to remove the optional `analytics_updater` argument since we always are using the default. I think if we need more flexibility in the future that is when we should add it. 
#5305
=> Create UpdateAnalyticsWorker to replace UpdateAnalyticsJob

app/models/comment.rb, app/workers/comments/create_first_reaction_worker.rb, spec/models/comment_spec.rb, spec/workers/comments/create_first_reaction_worker_spec.rb
Add a new sidekiq class with migrated code from creating first reaction
job. Add some missing specs on the comment, and refactor existing specs
for the job.
#5305
=> Change create first reaction job to worker

app/policies/comment_policy.rb
Fixes the [error that occurs](https://app.honeybadger.io/projects/66984/faults/59014101) when commentable no longer exists for a comment. 
```
Honeybadger Style Backtrace
Rails Style Backtrace
NoMethodError: undefined method `user_id' for nil:NilClass
comment_policy.rb  67 user_is_commentable_author?(...)
[PROJECT_ROOT]/app/policies/comment_policy.rb:67:in `user_is_commentable_author?'
65 
66   def user_is_commentable_author?
67     record.commentable.user_id == user.id
68   end
69 end
```
=> Handle missing commentable for user_is_commentable_author? check

app/models/comment.rb
Running this code on `after_create` creates a situation where the `where` clause in the sidekiq worker cannot yet find the data because the record can’t be seen by other database connections, like the one Sidekiq is using, until the database transaction is committed, which happens a little later.
Basically `after_create` runs before the transaction is actually final and this creates a little race condition.
More info here: https://www.justinweiss.com/articles/a-couple-callback-gotchas-and-a-rails-5-fix/
I think this wasn't a problem for Delayed Job because it always happened after at least one other DB transaction to create the job in the first place.
=> Change from after_create to after_create_commit

app/controllers/concerns/valid_request.rb
This error is getting incorrectly scoped to this module which then means we see an [uninitialized constant error](https://app.honeybadger.io/projects/66984/faults/58946304). I looked up the full path for the error and then made sure to add the leading `::` to make sure it wasn't scoped to the module. 
```
NameError: uninitialized constant ValidRequest::InvalidAuthenticityToken
valid_request.rb  15 valid_request_origin?(...)
[PROJECT_ROOT]/app/controllers/concerns/valid_request.rb:15:in `valid_request_origin?'
13       request.referer.start_with?(ApplicationConfig["APP_PROTOCOL"].to_s + ApplicationConfig["APP_DOMAIN"].to_s)
14     else
15       raise InvalidAuthenticityToken, NULL_ORIGIN_MESSAGE if request.origin == "null"
16 
17       request.origin.nil? || request.origin.gsub("https", …
```
=> Correctly Define InvalidAuthenticityToken error in helper module

datadog/prerun.sh
We don't really need to be tracking stats for the console boxes we are using in datadog. This will ignore them.
#4925
=> Ignore dynotype run since that is used for console access

app/controllers/concerns/valid_request.rb
After fixing the error scoping [another error came through](https://app.honeybadger.io/projects/66984/faults/59174341) involving the error message.
```
NameError: uninitialized constant ValidRequest::NULL_ORIGIN_MESSAGE
valid_request.rb  15 valid_request_origin?(...)
[PROJECT_ROOT]/app/controllers/concerns/valid_request.rb:15:in `valid_request_origin?'
13       request.referer.start_with?(ApplicationConfig["APP_PROTOCOL"].to_s + ApplicationConfig["APP_DOMAIN"].to_s)
14     else
15       raise ::ActionController::InvalidAuthenticityToken, NULL_ORIGIN_MESSAGE if request.origin == "null"
16 
17       request.origin.nil? || request.origin.gsub("https", "http") == request.base_url.gsub("https", "http")
```
Tested this fix in a console
```
[7] pry(main)> …
```
=> Scope error message correctly for InvalidAuthenticityToken error

app/models/article.rb, app/workers/articles/bust_multiple_caches_worker.rb, spec/models/article_destroy_spec.rb, spec/workers/articles/bust_multiple_caches_worker_spec.rb
In order to move all the jobs to Sidekiq, this commit creates a new
Articles/BustMultipleCachesWorker using Sidekiq based on the
Articles/BustMultipleCachesJob (this one is not removed until we know
that any job on this one will be performed).
Related to: #5305
=> Migrate Articles/BustMultipleCachesJob to Sidekiq

lib/tasks/fetch.rake
I was going to remove the `Rails.logger` statement but decided not to bc it might be nice for those who want to get a community up and running but don't have Datadog right away. 
In Datadog we can use these stats to add to a public dashboard to show growth or we can use them to create alerts for ourselves.
#4925
=> Record db table sizes in Datadog 

app/controllers/additional_content_boxes_controller.rb, spec/requests/additional_content_boxes_spec.rb
This PR solves [this error](https://app.honeybadger.io/projects/66984/faults/59183991) that occurs when an article_id is missing:
```
NoMethodError: undefined method `split' for nil:NilClass
additional_content_boxes_controller.rb  7 index(...)
[PROJECT_ROOT]/app/controllers/additional_content_boxes_controller.rb:7:in `index'
5 
6   def index
7     article_ids = params[:article_id].split(",")
8     @article = Article.find(article_ids[0])
9     @suggested_articles = Suggester::Articles::Classic.
```
If we don't return a 200 then [we wont render the additional content boxes](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializers/initializeAdditionalContentBoxes.js#L30)
This seemed like a straightforward fix but let me know if I missed anything. There might …
=> Handle Missing article_id When Loading additional_content_boxes

app/models/badge_achievement.rb, app/models/notification.rb, app/workers/notifications/new_badge_achievement_worker.rb, spec/models/badge_achievement_spec.rb, spec/models/notification_spec.rb, spec/requests/notifications_spec.rb, spec/system/internal/admin_awards_badges_spec.rb, spec/workers/notifications/new_badge_achievement_worker_spec.rb
Next on the list is moving the NewBadgeAchievementJob to a worker. Closely followed a previous PR here, see https://github.com/thepracticaldev/dev.to/pull/5312
I have a problem with the specs, as in my environment the spec file that fails, passes 😅 Might be some flakiness in the system?
=> use new_badge_achievement_worker instead of active job

app/uploaders/base_uploader.rb
Currently, we only limit the file size for ProfileImage uploads. It would probably be a good idea to limit the size for all uploads. I set it to 10 MB but am open to other suggestions!
=> Limit ALL Upload file sizes to 25 MB

app/models/organization.rb, app/models/site_config.rb
~When Rails loads validations it does so BEFORE it initializes the rest of the application  and this causes our gem to raise the error [`"You cannot use settings before Rails initialize." `](https://github.com/huacnlee/rails-settings-cached/blob/master/lib/rails-settings/base.rb#L118). In order to fix this we have to make default_site_email [readonly according to the gem docs](default_site_email).~
~To reproduce and validate this was the fix I turned on eager loading locally, tried to load rails, it failed with the above error. I added `readonly: true` to the SiteConfig variable and Rails loaded without a problem.~
Taking the easy way out! Because otherwise SiteConfigs can't be updated
#5384
=> Remove SiteConfig From Org Validation

app/mailers/application_mailer.rb, app/mailers/digest_mailer.rb, app/mailers/pro_membership_mailer.rb, app/models/site_config.rb
Fixes:
```
RuntimeError: You cannot use settings before Rails initialize.
application_mailer.rb  2 <class:ApplicationMailer>(...)
[PROJECT_ROOT]/app/mailers/application_mailer.rb:2:in `<class:ApplicationMailer>'
1 class ApplicationMailer < ActionMailer::Base
2   default from: "DEV Community <#{SiteConfig.default_site_email}>"
3   layout "mailer"
4   default template_path: ->(mailer) { "mailers/#{mailer.class.name.underscore}" }
```
#5384
=> Set default email in application mailer using ENV variable

spec/system/user_selects_looking_for_work_spec.rb
This doesn't really solve much but this spec is a system spec which relies on some Devise integration helpers. Without this tag, those helpers won't get included properly, not even sure how it runs without them tbh. 
#4884 
I'm in flaky spec hell right now
=> Set type for user_selects_looking_for_work_spec to system

Procfile, docs/deployment.md, release-tasks.sh
Last night was a bit of a doozy having a configuration change take down the app twice. The reason for this was that the problem with the config changes was not noticeable until the app was booted up with eager loading enabled and the only place we do that is in production. By adding a `rails runner` command to our release phase we will force the app to boot up prior to the deploy going out. If the app boots successfully and the command is run the deploy will finish. If the app is unable to boot up, like last night, then the release phase will fail, we will be alerted, and the deploy will stop. 
This will likely add 5-10 seconds of time to the deploy process which I think is completely worth it to test these kinds of changes which are SO easy to miss since our development and test …
=> Update Heroku Release to Migrate and Load App

spec/support/initializers/capybara.rb, spec/system/articles/user_edits_an_article_spec.rb, spec/system/articles/user_visits_articles_by_tag_spec.rb, spec/system/comments/user_delete_a_comment_spec.rb, spec/system/comments/user_edits_a_comment_spec.rb, spec/system/comments/user_fills_out_comment_spec.rb
I've added a helper called `wait_for_javascript` that waits for JS to be present in the page before starting the verification. In an ideal world it shouldn't be needed, but unfortunately Capybara and the wait it interacts with the page can lead to situations where the JS has not finished processing before it moves on the next step.
I've added this call using the list of system tests that tend to fail often lately, two perfect examples are the list of failures in these two builds:
- https://travis-ci.com/thepracticaldev/dev.to/builds/143557061#L1443
- https://travis-ci.com/thepracticaldev/dev.to/builds/143490153#L1009 
I got the idea from https://medium.com/doctolib/hunting-flaky-tests-2-waiting-for-ajax-bd76d79d9ee9
=> Add wait_for_javascript to flaky system tests

app/models/comment.rb, app/workers/comments/calculate_score_worker.rb, spec/models/comment_spec.rb, spec/workers/comments/calculate_score_worker_spec.rb
This creates a sidekiq version of the delayed job that calculates comment score and spaminess rating. The delayed job version will be removed and it's associated reference will be updated in a follow up PR.
P.S: My first PR for an open source project! =)
=> Migrate delayed job that calculates comment score to sidekiq

app/controllers/api/v0/follows_controller.rb, app/controllers/users_controller.rb, app/workers/users/follow_worker.rb, spec/requests/api/v0/follows_spec.rb, spec/system/user_selects_looking_for_work_spec.rb, spec/workers/users/follow_worker_spec.rb
In order to move all jobs to Sidekiq, this commit creates a new
Users/FollowWorker using Sidekiq based on Users/FollowJob.
Related to: #5305
=> Migrate Users/FollowJob to Sidekiq

spec/services/pro_memberships/expiration_notifier_spec.rb
After traveling back in time with Timecop, it can be the case that between the call
to the service and the moment we check the current time, we moved on to
the next second.
Using Timecop.freeze takes care of that.
Fixes https://github.com/thepracticaldev/dev.to/issues/5381
=> Fix Time flacky test

app/mailers/application_mailer.rb, app/mailers/digest_mailer.rb, app/mailers/pro_membership_mailer.rb, app/views/service_worker/index.js.erb, spec/mailers/digest_mailer_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/mailers/previews/notify_mailer_preview.rb, spec/mailers/pro_membership_mailer_spec.rb, spec/mailers/scholarship_mailer_spec.rb
With https://github.com/thepracticaldev/dev.to/pull/5394 we learned that `SiteConfig`'s values can't be used in initializers.
`from` (and `to`) in mailer's  `default` method can take procs though, which means that we can restore the usage of `SiteConfig`. These procs will be called when the `mail` method is invoked at runtime to send the email, which is late enough to `SiteConfig` to be available.
I've also improved mailer tests a little bit.
I've also tested a before scenario and after to confirm.
**Before** (with `config.eager_load = true` in development mode):
By setting `default from: "DEV Community <#{SiteConfig.default_site_email}>"`
```shell
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/rails-settings-cached-2.1.1/lib/rails-settings/base.rb:118:in `_all_settings': You cannot use settings …
```
=> Restore default email from SiteConfig for mailers

app/models/comment.rb, spec/models/comment_spec.rb
The column id_code was created with a job in an after create a callback,
that was replaced by an inline creation of the attribute
#5305
=> Change the way that id_code was created 

app/assets/stylesheets/user-profile-header.scss
Users with too much information in their metadata are overflowing the `.user-profile-metadata` section which makes some information inaccessible.
Related to https://github.com/thepracticaldev/dev.to/issues/3253 and https://github.com/thepracticaldev/dev.to/issues/4712
Not 100% fixed.
*Before*
Note that everything after "joined" is missing and there's no way to get to it.
*After*
The `.user-metadata-section` is now scrollable, so all information can be accessed.
=> User profile details fix

app/javascript/searchableItemList/searchableItemList.js
Fixes #5272 
From the issue: "This is probably a regression because I know it used to work, but apparently the count of articles in the reading list takes the value empty when selecting a tag. The same happens when unselecting the tag or going to the archive. The only way to restore the count is to do a full refresh of the page"
#5272 
N/A
=> Reading list count becomes "empty" when selecting a tag

app/views/internal/feedback_messages/index.html.erb
If content is unpublished it shouldn't be immediately necessary for
negative reactions to be acted on.
There is a higher touch solution here, but I'm not sure it's warranted.
I am curious to see if there is any push back here, one could make a pretty solid argument that we should still act on negative feedback on unpublished content. Still, I'd argue that it  would be futile; someone determined enough to flout the system by abusing publishing status is also savvy enough to know how copy + paste works.
Solves #5191
=> Internal feedback: skip negative reactions for unpublished content

app/controllers/notifications_controller.rb, app/services/notifications.rb, app/services/notifications/update.rb, app/views/notifications/_article.html.erb, app/views/notifications/_comment.html.erb, spec/services/notifications/new_comment/send_spec.rb
As a followup to #5294 - see @benhalpern comment https://github.com/thepracticaldev/dev.to/pull/5294#discussion_r362594146 - we're going to remove a trick that was added (in #5294) so that we don't need to ever include notifiable, not even for a single page of notifications.
This has been tested both manually and with unit tests, and I verified that we didn't need the eager loading anymore before and after this change with 
```ruby
BULLET=true bundle exec rspec ./spec/requests/notifications_spec.rb
```
https://github.com/thepracticaldev/dev.to/pull/5294
these two a comment notifications, the one on top has no `created_at`, the one below does
=> Remove notifiable access from articles and comments notifications

app/views/internal/articles/index.html.erb
Michael just DM'd me a request to make this textarea a more useful size.
Before:
After:
=> Internal articles: resize textarea to fill parent

app/views/internal/users/edit.html.erb
Since the "2" is right above "W", I guess this was supposed be "Warned", not "@arned".
=> Internal users edit: fix typo

Envfile
Follow-up to #5385, clean up`Envfile` by removing variables that got moved to `SiteConfig` with this deployment. Leaving WIP until #5399 gets merged so we can also remove `DEFAULT_SITE_EMAIL`.
#5384
=> Remove env variables handled by SiteConfig

app/controllers/api/v0/tags_controller.rb, app/controllers/internal/configs_controller.rb, app/models/site_config.rb, app/models/tag.rb, app/views/internal/configs/show.html.erb, spec/requests/internal/configs_spec.rb, spec/requests/tags_api_spec.rb
This PR adds a new array type of config for `SiteConfig` called `suggested_tags` which is used for onboarding (and anywhere else default "suggested tags" might exist).
The only UI change is adding the config to the `/internal/config`.
This PR also adds edge caching to `/api/tags/onboarding` because it's basically a static endpoint that only changes when this value changes. Added area to bust certain endpoints on change of config values.
This PR will be deployed with the default suggested tags defined here in `site_config.rb`. These should immediately be switched to our production values. We _could_ split this into different PRs, but I think doing them in this order is fine given what's going on here.
Closes #5177
=> Add suggested tags to SiteConfig

app/models/comment.rb, app/workers/comments/send_email_notification_worker.rb, spec/models/comment_spec.rb, spec/workers/comments/send_email_notification_worker_spec.rb
* Add sidekiq version of the corresponding delayed job
* Switch the invocation of the delayed job from `after_create` to
`after_create_commit` to avoid the race condition where the worker can
be executed before the comment is persisted. Added covering spec
for this change.
=> Migrate delayed job to send notification email on comment creation

app/models/notification.rb
Saw [this error](https://app.honeybadger.io/projects/66984/faults/59418712) come in where we were missing the follow record and then trying to send a notification. 
```
NoMethodError: undefined method `followable_type' for nil:NilClass
notification.rb  35 send_new_follower_notification_without_delay(...)
[PROJECT_ROOT]/app/models/notification.rb:35:in `send_new_follower_notification_without_delay'
33 
34     def send_new_follower_notification_without_delay(follow, is_read = false)
35       return unless Follow.need_new_follower_notification_for?(follow.followable_type)
36       return if follow.followable_type == "User" && UserBlock.blocking?(follow.followable_id, follow.follower_id)
```
Fixed by doing a presence check before we attempt to send the notification
=> Check for follow before trying to send a notification

app/models/notification.rb, app/models/user.rb, app/workers/notifications/welcome_notification_worker.rb, spec/requests/notifications_spec.rb, spec/workers/notifications/welcome_notification_worker_spec.rb
Very similar Pr to https://github.com/thepracticaldev/dev.to/pull/5358. In this PR we are moving the WelcomeNotification sending from ActiveJob to a Sidekiq worker. 
=> Move welcome notification job to worker

app/models/chat_channel.rb, spec/models/chat_channel_spec.rb
While reviewing #5460 I tried to destroy a channel and encountered a violation error from the DB. Messages can't not belong to a chat channel so they should be destroyed as a dependency.
See:
https://github.com/thepracticaldev/dev.to/blob/851508f62825c056bb39df122e11ada35fcadbc6/db/schema.rb#L528-L529
and
https://github.com/thepracticaldev/dev.to/blob/851508f62825c056bb39df122e11ada35fcadbc6/db/schema.rb#L1198
=> Destroy messages if chat channels are destroyed

app/controllers/comments_controller.rb, spec/requests/comments_create_spec.rb
#5246  What type of PR is this? (check all applicable)
Instead of raising an exception when the user's comment rate limit has been reached we now return an empty response with a status code of 429.
#5503
=> Return 429 Too Many Requests instead of raising

app/labor/email_logic.rb, app/models/application_record.rb, app/views/internal/users/_notes.erb, app/views/moderations/mod.html.erb, app/views/partnerships/index.html.erb, app/views/stories/_sign_in_invitation.html.erb, app/views/users/_account.html.erb, lib/tasks/fetch.rake, spec/labor/email_logic_spec.rb, spec/models/application_record_spec.rb
Counting effectively is one of the most bothersome things in SQL with big tables and having an ORM like ActiveRecord doesn't always help. 
As I don't think there's a need to display the exact live count of the `users` table and knowing the concept of count estimate has been floating around for a while I went ahead and added a `.estimated_count` class method to all models that uses PostgreSQL internal magic to display counts. You can read more about it here https://www.citusdata.com/blog/2016/10/12/count-performance/#dup_counts_estimated_full
Right now we're calling `SELECT COUNT(*) FROM users` on every unauthenticated page view and I think we can avoid that.
Example of what the method does:
```ruby
[1] pry(main)> User.estimated_count
SQL COUNT ESTIMATE: users (10.6ms)  SELECT …
```
=> ActiveRecord count optimizations

app/views/internal/articles/_article_script.html.erb
Michael asked that this behavior be extended to the buffer actions on
internal/listings as well.
We should probably look for an opportunity to refactor the JS currently
living in article_script.erb.
=> Add visual indication for listing buffer actions

app/models/application_record.rb
We can't use prepared statements in production because of PGBouncer, this uses the `connection.execute` directly to avoid triggering that issue
=> Use .execute to avoid any possibility of prepared statements

app/assets/javascripts/initializePage.js.erb, app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb, app/assets/javascripts/initializers/initializePodcastPlayback.js, app/assets/stylesheets/articles.scss, app/assets/stylesheets/ltags/PodcastTag.scss, app/assets/stylesheets/podcast-episodes-show.scss, app/assets/stylesheets/scaffolds.scss, app/assets/stylesheets/shared.scss, app/controllers/stories_controller.rb, app/models/podcast.rb, app/views/articles/index.html.erb, app/views/podcast_episodes/_liquid.html.erb, app/views/podcast_episodes/_podcast_bar.html.erb, app/views/podcast_episodes/show.html.erb, app/views/stories/_main_stories_feed.html.erb
This feature adds persistence to the podcast player, so that if a user refreshes the page or hits a non-`InstantClick` link, the podcast player will stick around.
The persistence is limited to the window itself, which I think is a neat solution. If a user has one DEV tab open and opens another, it will not show the persisted player. This is done by naming the `window` and storing the name in the `localstorage`.
The old code wasn't exactly perfect, and there is still some iffy JavaScript here, but I think I ripped out a bit of necessary stuff in the process.
Also added the podcast image to the home page and adjusted the design a bit here:
Also made some slight mods to the liquid tag, including adding a `follow` button.
=> Modify podcast design details and functionality

app/assets/javascripts/initializers/initializeCommentsPage.js.erb, app/controllers/comments_controller.rb
When a liquid tag breaks in the comments form, the form hangs forever.
This PR is the result of some investigation prompted by  https://github.com/thepracticaldev/dev.to/pull/5439
The comments form handles nicely errors with the preview:
but doesn't handle the same errors when the `SUBMIT` button is pressed. 
ps. I'm using `window.alert` because it's already used in the JS file in other places, hopefully we can come up with a better error handling UX in the future.
I added a video recording below
https://github.com/thepracticaldev/dev.to/pull/5439
=> Handle liquid tag errors in comments form

app/assets/javascripts/initializers/initializePodcastPlayback.js, app/views/podcast_episodes/_liquid.html.erb, app/views/podcast_episodes/_podcast_bar.html.erb
This PR fixes a small bug where `NaN` flashes for a moment during initialization of a podcast. Also fixes an issue where audio tries to load even if already loaded.
=> Fix podcast NaN time issue

docs/backend/algolia.md
After setting up dev.to on my local environment, I've found out that when you set up Algolia account it puts you automatically on trial plan. You can switch to free plan manually and I think it's worth pointing it out since I'm not really sure what happens after those 14 days.
=> Adding section for switching to free plan on Algolia

config/initializers/honeycomb.rb
After doing a walkthrough of our data with the fine folks at Honeycomb(@lizthegrey) we found that our data is pretty bloated with unnecessary fields that we don't need. By removing these fields we will shrink the size of the data we are sending which will allow us to retain data for a longer period bc we won't be hitting our data cap as quickly as before. 
[Here are the docs on using this method to scrub data](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#augmenting-or-scrubbing-spans) I tested this in a production console and saw the data removed in Honeycomb so I think that means its good to go.
1. "sql.active_record.binds" are the AR models that are bound to the SQL which is useless. We still have the values from the field "sql.active_record.type_casted_binds"
2. …
=> Scrub Unused data sent to Honeycomb to save space

app/views/articles/index.html.erb, app/views/stories/_main_stories_feed.html.erb
PR #5472 introduced two changes in cache keys, which are likely and probably unnecessary after the deployment.
Though I understand the motivation (to quickly refresh something right after deploy), the fact that
the expiration values have been decreased to 90 seconds and 180 seconds respectively, probably invalidates
the need to have them refresh instantly on deploy (we can just wait 3 minutes).
Let me know if I'm wrong about this and I'll modify or close this PR
=> Remove unnecessary heroku slug commit values in cache keys

docs/deployment.md, release-tasks.sh
In the event that we want to prevent deploys, for example after a rollback, we will set DEPLOY_STATUS to "blocked". This will cause the Rails runner to raise an error and prevent the release phase from finishing successfully which will halt the deploy. This ensures that we don't accidentally push out code while we are waiting for a fix or running other tasks.
=> Raise an error if the ENV variable DEPLOY_STATUS is set to blocked 

config/environments/development.rb
Bullet, the gem that helps us stay on top of N + 1 queries, was accidentally disabled in #5020
I've also enabled the floating window (because by only logging in the JS console and terminal there's a high probability people won't notice). See screenshots.
I've also updated its configuration to whitelist two known limitations.
=> Enable Bullet in development mode

app/workers/metrics/record_background_queue_stats_worker.rb, lib/tasks/fetch.rake, spec/workers/metrics/record_background_queue_stats_worker_spec.rb
We are STILL not logging queue stats because currently, we run this task via our scheduler and in an effort to save money and decrease our host counts I disabled the Datadog APM on schedulers bc each task was run on a new host. This PR moves the logic into a worker and will ensure the counts get sent to Datadog bc the actual work will be done in a Sidekiq worker and those do have the APM enabled.
=> Record Background Queue stats in a Sidekiq Worker

.gitpod.dockerfile, .gitpod.yml
Before, the setup in gitpod wasn't working because was missing a running redis-server. Now, the installation of redis-server is been doing on gitpod dockerfile and is running after workspace build.
#5464
=> Fix missing redis server to gitpod configuration

app/views/pages/_editor_guide_text.html.erb, app/views/pages/_v1_editor_guide_preamble.html.erb
Closes #5461 
Editor settings moved from `/settings/misc` to `/settings/ux`. This PR updates both the links and the descriptions to reflect the new wording and URL.
#5461
=> Update settings links + descriptions in editor guide

.travis.yml
> Note that the artifacts addon is not available for pull request builds.
I was originally not going to bother with this bc it wasnt going to help me with my debugging branch since it's not available for PRs but then I reconsidered and figured it would probably be useful to have given how often flaky specs are popping up. I put together the yml file based on [Travis's documentation](https://docs.travis-ci.com/user/uploading-artifacts/) and added the necessary ENV variables to our Travis configuration so this should be good to go. 
#4884
=> Send Travis screenshots to s3 After A Failed Master Build

docs/tests/skip-ci.md
Fixed a small typo in the Docs under Testing/QA Guide/Skipping Continuous Integration.
I'm thinking that the Docs site might just need an update or some sort of "re-build", but I noticed that the files included in `/docs` aren't all on the production site.
For example, you can see in the [code](https://github.com/thepracticaldev/dev.to/blob/master/docs/tests/readme.md) that there should be a link to the [Regression Testing](https://github.com/thepracticaldev/dev.to/blob/master/docs/tests/regression-tests.md) page.
When I run `gitdocs serve` locally, it shows up fine. Regression Testing is included in the left menu, the text containing the typo shows up, and the title matches the [code](https://github.com/thepracticaldev/dev.to/blob/master/docs/tests/skip-ci.md#skipping-continuous-integrati …
=> Fix typo in Skipping CI docs [ci skip]

spec/models/notification_spec.rb, spec/support/initializers/test_prof.rb
This is a **suggestion** for using `let_it_be` more safely, it seems pretty dangerous to me.
TL;DR Use readonly records mainly, and make it clear when records are not readonly.
With let_it_be, we define variables that are created for the whole
context. In case we update them in an example, there might be a
discrepancy between the object and its value in the database, since the
database is cleaned between examples, but not the object itself.
This is what happened here with the `article` object. In one of the
tests, we update its organization, and in another, we reupdate it. The
problem is that the `article` object still thinks it has an
organization, but it has been cleaned in the database. So setting the
same organization id to the object doesn't trigger the SQL query, and
the article in …
=> Add let_it_be_readonly to avoid updating variables

config/initializers/sidekiq.rb, lib/sidekiq/honeycomb_middleware.rb, spec/lib/sidekiq/honeycomb_middleware_spec.rb
To give us a more complete picture of what the app is doing at any given time I thought sending Sidekiq information to Honeycomb would be important. I found [this code in an issue on the beeline ruby gem](https://github.com/honeycombio/beeline-ruby/issues/29) and liked the way it was implemented. Specs included this time :)  
I was going to add a duration field but then realized all Honeycomb spans come with a duration so it would be redundant. 
#4925
=> Send Sidekiq data to Honeycomb

app/controllers/api/v0/comments_controller.rb, app/jobs/comments/bust_cache_job.rb, app/workers/comments/bust_cache_worker.rb, spec/jobs/comments/bust_cache_job_spec.rb, spec/requests/api/v0/comments_spec.rb, spec/workers/comments/bust_cache_worker_spec.rb
After #4744 we successfully setup an auto purging system based on Fastly's surrogate key based cache and purging API.
Unfortunately this worked only in the `:show` action as comments are their own tree-based resource.
The `:index` though, is related to a single article, so without the article's record key in the `Surrogate-Key` header the first time we hit the API the result would become the value stored in Fastly's API, for all articles.
=> Add article's record key to Fastly Surrogate-Key to separate caches

docs/backend/auth-twitter.md
Starting January 21st 2020 Twitter will show _access token_ and _access token secret_ only once.
So I'm updating the docs to ensure devs are aware of this and they copy the tokens.
=> Adding info about disappearing tokens

datadog/prerun.sh
In Honeycomb we have these giant 30k event long spans that are coming from when we run scheduled tasks. The reason for this is bc many of these task iterates through lots of users or articles for processing. In an effort to decrease the size of what we send to Honeycomb in order to increase our data retention I think these are stats we can live without for now so [per the docs I set HONEYCOMB_DISABLE_AUTOCONFIGURE to true](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#using-env-variables-to-control-framework-integrations) which will stop Beeline from including any of the automatic integrations. This script is run by Datadog before dynos are booted up so I figured why not use it to also set this ENV variable 🤷 
Something to consider is that Datadog is also disabled in an effort …
=> Disable Beeline on Schedulers and in Console

app/lib/html_css_to_image.rb, spec/lib/html_css_to_image_spec.rb
The currently default is 24 hours. These images are expensive to generate + don't change often. So we can make it much much longer.
Ideally, these keys would never expire, and get auto evicted by redis when space fills up. But I don't think a `nil` ttl is possible when a default is set in the Rails config (see [production.rb](https://github.com/thepracticaldev/dev.to/blob/e8c623807cdeb2b43d84893eaad10fcd29baf0ab/config/environments/production.rb#L105)).
So I set it to a real long value. + test to guard against it accidentally being changed.
=> Increase cache TTL for social preview images

.travis.yml
We had a [failed travis build](https://travis-ci.com/thepracticaldev/dev.to/builds/144760546) that should have sent artifacts to S3 but did not. I updated our ENV variables bc there is a good chance I had those wrong. I also decided to be more explicit about this path rather than assume we are in the dev.to repo.
=> Update Travis Artifacts Path

app/assets/stylesheets/chat.scss, app/assets/stylesheets/top-bar.scss, app/views/service_worker/index.js.erb
This changes the font size of the nav search and /connect input to `16px` which is the minimum needed to not awkardly zoom in when focusing on these in iOS Safari.
Prior computed value of the nav bar input was `15.3px`, so very minor change.
=> Change font size for search and message input

spec/system/articles/user_edits_an_article_spec.rb
I don't think we should go around removing flaky tests, but this one seems to have way way way more random failures vs the value it's delivering of ensuring this edit button shows up.
We should study this to figure out the underlying problem, but I think we'll all be happier with this test stricken to the underworld.
=> Remove flaky edit button spec

config/initializers/assets.rb
A little while ago we bumped the browser cache expiration for our assets from an erroneous 1 day up to 30 days, but only assets which take affect are ones that change, so our images, svgs, and unchanged files in general don't change unless we bump this number.
=> Bump assets version

app/labor/rate_limit_checker.rb, app/models/site_config.rb, spec/labor/rate_limit_checker_spec.rb, spec/requests/follows_create_spec.rb
The current rate limit checker uses hard-coded limits for everything, and the intention of this PR is to make it externally configurable. Additionally the code will be cleaned up a bit.
#5520
=> Refactor RateLimitChecker

package.json
In https://github.com/thepracticaldev/dev.to/pull/5592 we upgrade `lint-staged` to 1.0 which removed the requirement for `git add` as the last step. Until this is merged we'll get this warning:
```shell
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```
https://github.com/thepracticaldev/dev.to/pull/5592
=> Remove git add from lint staged

app/services/pro_memberships/creator.rb, app/workers/pro_memberships/populate_history_worker.rb, spec/requests/pro_memberships_spec.rb, spec/workers/pro_memberships/populate_history_worker_spec.rb
This change creates a Sidekiq Worker equivalent of ProMemberships::PopulateHistoryJob
#5305
=> Migrate popular history job 5305

.travis.yml
Uploading artifacts to S3 has not been working so I emailed support and got a few insights into why. For starters we just need to declare the addon, we dont actually have to run the script. That happens automatically. I also inquired about the directory and was told to use the TRAVIS_BUILD_DIR.
> TRAVIS_BUILD_DIR: The absolute path to the directory where the repository being built has been copied on the worker.
=> Fix Travis S3 Artifact AddOn

app/controllers/application_controller.rb, app/controllers/stories_controller.rb, app/decorators/organization_decorator.rb, app/decorators/user_decorator.rb, spec/decorators/user_decorator_spec.rb, spec/models/organization_spec.rb, spec/requests/user/user_profile_spec.rb
We ban spam accounts and mark them as spam but don't currently raise not found, which we can essentially do. It's likely not correct to keep those empty profiles visible and discoverable.
=> Raise not_found for spam-banished users

app/workers/articles/update_analytics_worker.rb
[Just saw a bunch of these jobs fail](https://app.honeybadger.io/fault/66984/cbf1f2d80ce7b8d61cde97b8c5ba3063) due to `Google::Apis::RateLimitError` so I decided it would be a good idea to increase the retry limit for this job so that in the event of a rate limit it has more time to retry. This gives it up to 10 hours. 
#5305
=> Retry more for Articles::UpdateAnalyticsWorker

app/controllers/internal/users_controller.rb, app/models/banished_user.rb, app/models/user.rb, app/services/moderator/banish_user.rb, db/migrate/20200120053525_add_banished_users_table.rb, db/schema.rb, spec/decorators/user_decorator_spec.rb, spec/factories/banished_users.rb, spec/models/banished_user_spec.rb, spec/models/user_spec.rb, spec/requests/internal/users_banish_spec.rb, spec/requests/internal/users_spec.rb, spec/requests/user/user_profile_spec.rb
Closes https://github.com/thepracticaldev/tech-private/issues/353
Banished accounts could sign up with a different social media account and reclaim their usernames. There was a workaround for admins, but it was abusing an unrelated feature. This PR introduces a `BanishedUser` table to address this more properly. 
https://github.com/thepracticaldev/tech-private/issues/353
* @benhalpern After our discussion on the issue, I decided to stick with `BanishedUser` after all. I'd rather have something narrow in scope that we refactor/broaden once we have identified more/different use cases, than trying to anticipate what we need and ending up with the wrong abstraction. Once something has been introduced, people will start using it and breaking it apart may be harder than changing something small …
=> Introduce BanishedUser table

Gemfile, Gemfile.lock, app/assets/javascripts/base.js.erb, config/initializers/assets.rb, package.json, yarn.lock
rails-assets.org is often down, and apparently has been down intermittently since yesterday.
In addition to this the only thing the gem does is literally to add `honeybadger.js` to the assets path:
```ruby
gem_path.join('app/assets').each_child.to_a
```
Hence we can ditch the gem and use the library directly thus removing our dependence from `rails-assets.org`
=> Use honeybadger.js from npm

.travis.yml
One minor path fix to get this working. Found out the path was dup'ed in [this build](https://travis-ci.com/thepracticaldev/dev.to/builds/145558324)
```
ERROR: failed to upload: /home/travis/build/thepracticaldev/dev.to/dev.to/tmp/screenshots/*.png
err: open /home/travis/build/thepracticaldev/dev.to/dev.to/tmp/screenshots/*.png: no such file or directory
```
=> Remove extra dev.to from travis upload artifact path

app/models/notification.rb, app/workers/notifications/notifiable_action_worker.rb, spec/models/notification_spec.rb, spec/requests/articles/articles_update_spec.rb, spec/requests/notifications_spec.rb, spec/services/articles/creator_spec.rb, spec/workers/notifications/notifiable_action_worker_spec.rb
In this PR we are replacing NotifiableActionJob with a new NotifiableActionWorker. Will remove the now uncalled job in a subsequent PR 
=> replace notifiable action job with worker

config/initializers/sidekiq.rb, config/routes.rb
Currently, when we try to do anything in the Sidekiq Admin UI besides a GET request we get a Forbidden error. I think the reason for this is because we are not tracking sessions. The reason we are not tracking sessions is because of a [rack bug that was recently fixed](https://github.com/rack/rack/pull/1428). Since the new gem has not been released I applied the patch in the Sidekiq initializer and set the session [the way it is suggested here](https://github.com/mperham/sidekiq/issues/1289#issuecomment-415714146). This works locally but the real test will be production. 
The reason we need this fixed is bc if workers break in Sidekiq I have to go into a console to clean them up. Moving forward as we start an on-call rotation we need to empower everyone to be able to handle and work with …
=> Apply Monkey Patch To Attempt To Fix Sidekiq Admin UI

app/controllers/internal/configs_controller.rb, app/views/internal/configs/show.html.erb, spec/requests/internal/configs_spec.rb
#5521 refactored `RateLimitChecker` to use `SiteConfig` instead of hardcoding values. This PR adds the values to the admin interface at `/internal/config`.
#5520
=> Add rate limits to admin interface

app/controllers/api/v0/articles_controller.rb, app/labor/cache_buster.rb, spec/requests/api/v0/articles_spec.rb
Surrogate keys are about setting expectations on cache purging.
Presently we use a combination of all parameters to set changing surrogate keys depending on the result of the `ArticleApiIndexService`. This approach has two limitations:
- if two set of params lead to the same exact set of articles, we still create two different caches
- deleted articles will remain for 24 hours in the cache because the cache key doesn't take the record keys into account
By simply using record keys we make sure that different params leading to the same result set will share the same cache and that deleted keys won't appear anymore in the cache.
#4744, #5543 and https://github.com/thepracticaldev/dev.to/issues/838
Closes https://github.com/thepracticaldev/dev.to/issues/3611
=> Use correct cache keys on the articles API index endpoint

app/services/podcasts/get_episode.rb, app/workers/podcast_episodes/create_worker.rb, spec/services/podcasts/feed_spec.rb, spec/services/podcasts/get_episode_spec.rb, spec/workers/podcast_episodes/create_worker_spec.rb
* Create sidekiq version and update get episode to use this sidekiq
* Did a mini refactor in `Podcasts::GetEpisode` to make the code a bit more readable
* The tests around `Podcasts::Feed` helped catch a bug around the migration of the podcast episode creation delayed job where the sidekiq version was passing a string version of item hash to
`Podcasts::CreateEpisode` which was in fact expecting the hash to contain symbols.
#5305
=> Migrate creation of podcast episode

Dockerfile
I was unable to fully use pry using the docker version of dev.to.
For instance while trying to examine certain variables or trying to use
`caller` to checkout the backtrace, I would run into the a `multi-call binary error` with
`BusyBox`.
On looking up this error, discovered https://github.com/pry/pry/issues/1248 which also
had the fix which was simply to install less for the docker image.
Verified locally that pry's full functionality works.
=> Install less

app/controllers/users_controller.rb, app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap, app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
The email newsletter field on one of the onboarding steps is using/updating an incorrect property of User. Onboard-er were not able to opt-out of the newsletter because of this. 
for clarity:
- `email_newsletter` is for the weekly email from Jess/Mailchimp
- `email_membership_newsletter` is for sustaining membership campaign
n/a
1) Deselect both choices during onboarding.
2) Setting page does not reflect the choice made during onboarding
This PR fixes that
=> Allow for proper deselect of email_newsletter during onboarding

app/javascript/article-form/elements/__tests__/__snapshots__/bodyPreview.test.jsx.snap, app/javascript/article-form/elements/__tests__/bodyPreview.test.jsx, app/javascript/article-form/elements/bodyPreview.jsx
Fixes an issue where the cover image appeared to be stale and would continue to appear in preview mode even if it had been removed from the front matter data! I also added a new test file for the `bodyPreview` component since there wasn't one yet, and added some tests for both v1 and v2 of the editor.
Note: this is my first time working with Jest, and my first time in _years_ working with (P)React. Happy to hear thoughts and suggestions on those tests if you have them! 🙈 
Related to https://github.com/thepracticaldev/dev.to/issues/5630.
=> Use the correct cover image in article form preview

config/initializers/honeybadger.rb, spec/initializers/honeybadger_spec.rb
We get a lot of these two errors from all over the app. They are usually one-off or a lot of them are actually from our admin which is not very performant. Rather than recording a new error for every different backtrace that produces one of these, let's group them together.
Also included a little refractor, what do you all think? It makes adding a grouping as simple as adding a search key and fingerprint.
=> Group all PG::TRDeadlockDetected and PG::QueryCanceled errors together

app/controllers/api/v0/articles_controller.rb, app/controllers/api/v0/comments_controller.rb, spec/requests/api/v0/articles_spec.rb
Right now we're caching the `/api/articles/{id}` endpoint for 5 minutes on the server side.
Internally it stores the JSON payload in Redis for 300 seconds:
```shell
127.0.0.1:6379> keys "views/*"
1) "views/localhost:3000/api/articles/4.json"
127.0.0.1:6379> ttl "views/localhost:3000/api/articles/4.json"
(integer) 266
127.0.0.1:6379> get "views/localhost:3000/api/articles/4.json"
"\x04\bo: ActiveSupport::Cache::Entry\n:\x0b..."
```
This is not really efficient for multiple reasons:
- the 5 minute duration is quite short for 99% of articles (those that are not updated continuosly, which usually happens in the few minutes / hours right after an article is published, for last minute changes or updates)
- being an API endpoint there's a very HIGH likelyhood that this results in a lot of HTTP …
=> Use edge caching for API Article show endpoint

app/javascript/chat/chat.jsx, app/views/chat_channels/index.html.erb
New mention feature is causing more re-renders than needed because every `keyUp` calls `setState`, when actually we only need to hide member list when it is currently showing, instead of all the time.
Typing latency is the worst. 😝
=> Add conditional to prevent superfluous rerenders in chat compose

app/assets/stylesheets/comments.scss, app/controllers/comments_controller.rb, app/views/comments/_form.html.erb, spec/requests/comments_spec.rb
This PR fixes generic Standard Error that is raised on comments#update if comment contains an invalid liquid tag. With the new changes user can see the error instead of breaking the page.
Honeybadger: https://app.honeybadger.io/fault/66984/6b348042b61c88825e56b6362a3ae2f7
https://github.com/thepracticaldev/dev.to/issues/5608
=> Don't raise StandardError for invalid liquid tags when updating comment

app/views/users/_profile.html.erb
Fixes capitalization of some placeholder sentences on the User Profile settings page. This is pretty minor but was a) annoying me, b) seemed like a good first baby step to committing code!
Before:
After:
=> Fix capitalization in settings placeholders

docs/installation/postgresql.md
I learned about `pgbouncer` (apparently that's a thing!) in my technical walk-through with @benhalpern, and thought it would be nice to add it to our docs. Not entirely sure that _this_ is the right place for it, so if you disagree, just let me know :)
While learning about PgBouncer, I read that PostgreSQL's default connection limit is set to 100 concurrent connections; does anyone know if we use the default connection limit or if we use PgBouncer to change that? If it's relevant, I can add it to the docs here.
Also cleaned up some formatting in the docs for the page that I modified (well, VSCode cleaned it up if we wanna be specific about it 👀)
=> Add documentation around our use of pg-bouncer [ci-skip]

app/decorators/article_decorator.rb, app/models/article.rb, app/views/articles/show.html.erb, spec/decorators/article_decorator_spec.rb, spec/models/article_spec.rb, spec/requests/api/v0/articles_spec.rb
This PR fixes a few logical problems currently with "article description"
- Currently the attempt at a contrived description if it were blank were not resulting in anything because blank strings were being submitted and the `||` wasn't being called.
- Description wasn't present in the "internal navigation" version of the page, which _may or may not_ matter, but just in case it has any impact on SEO, I think this is the right way to go about it.
- The contrived name now includes tags at the end to help possible search engine cases.
Part of this is strictly for hypothetical SEO issues, part is slightly more for user-reading purposes where we use the description in different places where now it's erroneously not present.
=> Fix article description issues

app/views/articles/_actions.html.erb, app/views/users/show.html.erb
I saw in our [search console dashboard](https://search.google.com/search-console/about) that Google is crawling some user-only pages because we link to them in non-logged-in views. There is still a layer of authentication, so it's not a problem other than likely waisting the crawler's time (which could hurt our SEO).
This feature adds a check for `user_signed_in?` where functionality is only needed for signed-in users and the link does not need to be crawled by search engines. ~Also added `nofollow` on some links that should still exist for non-logged-in users but are not links to indexable content per se.~
I removed the "nofollow links" part of this PR because I had hesitations about the exact right choice. Everything else should be a no-brainer.
=> Remove non-indexable logged-out links

app/views/comments/deleted_commentable_comment.html.erb
Saw [this error come through Honeybadger](https://app.honeybadger.io/fault/66984/e30f73ae223c77d00689206f3c231888) where the root comment was missing for a view so I added a blank check to the view to handle this situation. 
```
ActionView::Template::Error: undefined method `deleted' for nil:NilClass
deleted_commentable_comment.html.erb  6 _app_views_comments_deleted_commentable_comment_html_erb___245802387296255488_73890320(...)
[PROJECT_ROOT]/app/views/comments/deleted_commentable_comment.html.erb:6:in `_app_views_comments_deleted_commentable_comment_html_erb___245802387296255488_73890320'
4   <div class="single-comment-node root">
5     <% @user ||= @root_comment.user %>
6     <% if @root_comment.deleted %>
7       <div class="inner-comment">
8         <div class="body">
```
=> Handle Missing Root Comment in Deleted Comment View

.rubocop.yml, app/services/podcasts/feed.rb, app/services/podcasts/get_episode.rb, app/workers/podcast_episodes/update_media_url_worker.rb, spec/services/podcasts/feed_spec.rb, spec/services/podcasts/get_episode_spec.rb, spec/workers/podcast_episodes/update_media_url_worker_spec.rb
* Sidekiq version of delayed job and updating services that used the
delayed job
* Intentionally removed the defensive check in the sidekiq version. If
the episode is missing and there's worker scheduled to update it's media
url then that reveals a bug elsewhere and should fail fast instead of
skipping ahead.
* Also excluded the ambiguous block rule for rspecs since that
conflicts with the rspec `expect` block, found that recommentation
thanks to https://github.com/rubocop-hq/rubocop/issues/4222 (and rubocop
was complaining about this in the pre-commit hook for these changes)
#5305
=> Migrate delayed job that updates media url for podcast episodes

Envfile
To help switch AWS buckets, fixes
```
rails aborted!
NoMethodError: undefined method `AWS_UPLOAD_ID' for ENVied:Class
/app/vendor/bundle/ruby/2.6.0/gems/envied-0.9.3/lib/envied.rb:80:in `method_missing'
```
=> Declare new AWS variables in ENV file

.travis.yml
=> Fix Travis S3 Artifact AddOn [4th attempt]

app/lib/constants.rb
This adds [functional.cafe](https://functional.cafe) to the list of allowed Mastodon instances.
=> Add "functional.cafe" to Mastodon list

app/javascript/shared/components/tags.jsx
I noticed that, in Firefox, when I'm writing an article and attempt to search for a tag, the tags list will disappear if I click "View Rules" for a certain tag. Only after I bring the tags search back up am I able to view the tag rules.
Screencast:
It looks like when the "View Rules" button is clicked, Chrome considers the button to be the `activeElement` while Firefox considers the entire tag row to be the `activeElement`, causing the eventHandler not to work as expected.
This PR fixes it so Firefox works as expected.
=> Fix tags 'View Rules' disappearing bug (Firefox)

app/views/service_worker/index.js.erb
While reviewing https://github.com/thepracticaldev/dev.to/pull/5612 I've noticed how if the feed is opened in a browser it's going to be intercepted by the service worker and thus the shell around it will appear:
=> Don't use the service worker for the feed

docs/installation/docker.md
A very minor update to the Docker documentation. Yarn by default installs packages by simply running `yarn`. See the [Yarn Install](https://legacy.yarnpkg.com/lang/en/docs/cli/install/).
- [] no documentation needed
=> Removed redundant yarn install command

.travis.yml, config/environments/production.rb
As discussed on Slack, this PR adds a verify stage to the Travis pipeline which will try to start a production Rails runner to verify that the app can boot up, so we don't solely rely on `deploy-tasks.sh` for that purpose.
n/a
n/a
=> Add verify stage to TravisCI config

app/controllers/comments_controller.rb, spec/requests/comments_create_spec.rb
A `Pundit::AuthorizationNotPerformedError` in the CommentsController `#create` path (https://app.honeybadger.io/fault/66984/9508988843fe9435805fbb822bbe8242). It appears this is happening in the rescue error block since that is the only data path that doesn't use `skip_authorize` or `authorize`.
It's not immediately clear from HoneyBadger how this occurring and I wasn't able to reproduce the error naturally (I was able to repro it with `binding.pry`). But it appears an error is occurring before the authorization putting `skip_authorization` in the rescue block will ensure all data paths are covered.
Closes #5717 
cc: @mstruve @citizen428 @rhymes
=> comment_controller: add skip_auth to rescue error block

app/services/webhook/dispatch_event.rb, app/workers/webhook/dispatch_event_worker.rb, spec/requests/articles/articles_create_spec.rb, spec/requests/articles/articles_update_spec.rb, spec/services/webhook/dispatch_event_spec.rb, spec/workers/webhook/dispatch_event_worker_spec.rb
This creates a new `Webhook::DispatchEventWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305
=> Move Webhook::DispatchEventJob to Sidekiq

Envfile, config/initializers/carrierwave.rb, config/sitemap.rb
Now that we are pointed at our new AWS bucket swap over the original ENV variables to the new bucket ones and use those. The only variable we have to keep is the region since that is different than our default region and that default region is being used by the SDK which is used by the `AWS_LAMBDA` client.
The ENV variables have all been set properly in Heroku. 
AWS_SECRET = AWS_UPLOAD_SECRET 
AWS_ID = AWS_UPLOAD_ID
AWS_BUCKET_NAME = AWS_UPLOAD_BUCKET_NAME
#5570
=> Remove ENV["USE_NEW_AWS"] and use Orig ENV variables for New Creds

app/views/layouts/_top_bar.html.erb
We check for notifications count in the app shell before the rest of the page loads or is available, so we actually don't know whether `document.getElementById('notifications-container') == null` is a thing either way.
This code used to be called after the rest of the page loads.
This ensures we don't show the number if anyone lands directly on the notifications page.
=> Use page location as indicator for page load

app/controllers/api/v0/podcast_episodes_controller.rb, spec/requests/api/v0/podcasts_episodes_spec.rb
Similar to https://github.com/thepracticaldev/dev.to/pull/5709 we're removing server side caching, adding edge caching and busting and some tests
I haven't added the usual `.purge` call because it's already present, though I'm not sure we need to call it twice, but I'd rather keep things as is in the cache buster for now and then go over it with a fine tooth comb:
https://github.com/thepracticaldev/dev.to/blob/743ac13cec56f50694b00c3874b9d5ce009ccdc6/app/labor/cache_buster.rb#L146-L159
https://github.com/thepracticaldev/dev.to/pull/5709
=> Improve API podcast episodes controller caching and fetching

app/models/comment.rb, app/models/notification.rb, app/workers/notifications/moderation_notification_worker.rb, spec/requests/notifications_spec.rb, spec/services/notifications/moderation/send_spec.rb, spec/workers/notifications/moderation_notification_worker_spec.rb
=> Change ModerationNotificationJob to ModerationNotificationWorker and move to sidekiq

Gemfile, Gemfile.lock
Getting rid of this gem has been a long lasting dream of mine, I'm glad we've finally got to it thanks to the work we've been doing on streamlining edge caching. Page caching has been removed from Rails in version 4 (almost 7 years ago I just found out)
Next up is to get rid of `rails-observers` :D
=> Remove actionpack-action_caching gem

app/models/article.rb, app/models/comment.rb, app/models/notification.rb, app/workers/notifications/update_worker.rb, spec/models/comment_spec.rb, spec/models/notification_spec.rb, spec/workers/notifications/update_worker_spec.rb
=> Change Notifications::UpdateJob to Notifications::UpdateWorker and move to sidekiq

app/controllers/pages_controller.rb, app/views/pages/robots.text.erb, config/initializers/initialization_cachebust.rb, config/routes.rb, public/robots.txt, spec/requests/pages_spec.rb
This PR moves `robots.txt` from the totally static public folder to an action where code and env vars are available.
This is needed to point robots to the new place for our sitemap download and enable any further dynamic elements in the sitemap.
I also took the moment to add a few new `Disallow:` lines to avoid crawling of a few unnecessary pages which either result in errors or result in an endless list of endpoints which don't need indexing.
If you're reviewing this, just double check the format of the new lines to make sure it is appropriate when checked against instructions for `robots.txt`. We definitely don't want to accidentally instruct the bots to not crawl important pages.
This endpoint will be cached, so for all intents and purposes it will be as if it is static. It will rarely …
=> Create dynamic robots.txt page

config/initializers/honeybadger.rb, spec/initializers/honeybadger_spec.rb, spec/initializers/shared_examples/sets_correct_honeybadger_fingerprint.rb, spec/rails_helper.rb
Combine Rack::Timeout::RequestTimeoutErrors with Exceptions in Honeybadger since they are indicative of the same thing. Also did a little spec refractor which I am pretty happy with. 
https://github.com/thepracticaldev/dev.to/projects/5#card-32287886
=> Combine Rack::Timeout::RequestTimeoutErrors with Exceptions in Honeybadger

app/models/badge_achievement.rb, app/workers/badge_achievements/send_email_notification_worker.rb, spec/system/internal/admin_awards_badges_spec.rb, spec/workers/badge_achievements/send_email_notification_worker_spec.rb
This creates a new `BadgeAchievements::SendEmailNotificationWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305
=> Move BadgeAchievements::SendEmailNotificationWorker to Sidekiq

app/controllers/stripe_active_cards_controller.rb, spec/requests/stripe_active_cards_spec.rb
This PR does 2 things:
1) Prevents the `Stripe::InvalidRequestError` from bubbling up to Honeybadger which will solve [this error](https://app.honeybadger.io/fault/66984/25b68173b013c1c37741fbfe2728bfcc)
2) Counts all errors that occur in Datadog so instead of being alerted to one off errors via Honeybadger we instead can be alerted if the number of errors spike which would indicate a possible Stripe issue rather than a one off user problem.
3) BONUS! I added specs! 🙌 
https://github.com/thepracticaldev/dev.to/issues/4925
https://github.com/thepracticaldev/dev.to/projects/5#card-32287854
=> Track stripe errors in Datadog so we can alert on them

docs/installation/mac.md
Missed a `.sha512` in the mac ES docs
https://github.com/thepracticaldev/dev.to/projects/6#card-32124912
=> Add missing sha512 to ES mac docs

config/initializers/strong_migrations.rb
After we merged #5373 we unfortunately broke the development environment because its migration is not compatible with the automatic checks that the gem `strong_migrations` does. I guess it was added to the code after that PR was submit
As that PR is already merged and shipped, we need to bump the minimum version that strong migrations considers
=> Replace the initial migration for strong_migrations gem

app/javascript/article-form/elements/__tests__/__snapshots__/bodyPreview.test.jsx.snap, app/javascript/article-form/elements/__tests__/bodyPreview.test.jsx, app/javascript/article-form/elements/bodyPreview.jsx
Previewing a main image on an article was broken in v2 of the editor 😞 I actually did some work around this last week in [a separate PR](https://github.com/thepracticaldev/dev.to/pull/5660), but I was pretty new and didn't realize all the differences between the metadata of an article in the context of the v1 editor versus the v2 editor! 🙈 
Funnily enough, we actually [had some tests for this](https://github.com/thepracticaldev/dev.to/pull/5660/files#diff-0ef7c0748e1c101451bdd270fbfcc714) (which I wrote!), so I didn't catch this bug until I ran into it manually on the v2 editor. As it turns out, the setup for the tests wasn't quite right! This PR fixes the preview bug, and also refactors and cleans up our tests quite a bit.
It also adds some snapshots for both v1 and v2 editors in a "no …
=> Render main image in article preview for v2 editor

app/views/pages/shecoded.html.erb
Fixes #5741
After the update :
=> Footer in `shecoded` rendered twice

.travis.yml, spec/initializers/elasticsearch_spec.rb
This PR adds Elasticsearch to our list of Travis databases and creates a spec to ensure that we can talk to it. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32288041
=> Hookup Elasticsearch in Travis

app/controllers/application_controller.rb
If the origin URL after signin contains parameters, we can't append `?signin=true` because URL params should be attached with `&`.
This fixes the broken generated URL in case the URL already has params
=> Add signin=true as a param correctly if the URL already has params

CONTRIBUTING.md
After a recent #team-oss discussion involving @jessleenyc, we decided to rename `help wanted` to `ready for dev`. 
Rationale:  “help wanted” can be a bit ambiguous, whereas “ready for dev” clearly communicates that something can be worked on. It'a also a sort of pun, as in "ready for DEV".
NOTE: after merging this PR we need to actually rename the tag. I was holding off on that for now since I didn't want documentation and issue tracker to be out of sync.
n/a
=> Update contributor guide with new tag name

app/javascript/article-form/elements/bodyPreview.jsx
As requested by @rhymes, adds a comment to highlight difference between previewing in v1 and v2 editors.
A follow-up to https://github.com/thepracticaldev/dev.to/pull/5873.
=> Add comment around previewing with v1 vs. v2 editors

app/controllers/internal/badges_controller.rb, app/controllers/internal/tools_controller.rb, app/views/internal/badges/index.html.erb, spec/requests/internal/badges_spec.rb, spec/system/internal/admin_awards_badges_spec.rb
As requested by @michael-tharrington!!
Adds a "blank" option to the dropdown to list of badges on internal/badges route.
Also add some checks to handle if an admin accidentally tries to award a "blank" badge.
Fixes https://github.com/thepracticaldev/dev.to/issues/5876
Adds a blank option to the badges dropdown for `internal/badges`:
=> Improve dropdown UX for internal/badges

app/models/tag.rb, app/workers/tags/bust_cache_worker.rb, spec/models/tag_spec.rb, spec/workers/tags/bust_cache_worker_spec.rb
This creates a new `Tags::BustCacheWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305
=> Move Tags::BustCacheJob to Sidekiq

app/controllers/html_variant_successes_controller.rb, app/jobs/html_variant_success_create_job.rb, spec/jobs/html_variant_success_create_job_spec.rb
I first started moving `HtmlVariantSuccessesCreateJob` to Sidekiq and I'm wondering if we need a background job for this at all. I dug through some history and old PRs and I couldn't see anything that jumped out as to why or why not this was done this way.
If I'm way off base and this should still be delayed in the background I have the PR (#5878) completed for that route as well but marked it as WIP. I figured if nothing else this might prompt some helpful discussion for reference later.
- #5305 
- #5878
=> Move HtmlVariantSuccessesCreate from background job to inline

app/views/internal/broadcasts/_form.html.erb
Found some weird formatting while poking around in the `/internal` pages. Removed the quotes so that the dropdown options would format correctly! 💪 
BEFORE:
AFTER:
=> Remove quotes from broadcast options in internal form

app/services/moderator/banish_user.rb, app/services/moderator/manage_activity_and_roles.rb, app/services/users/cleanup_chat_channels.rb, app/services/users/delete_articles.rb, spec/requests/internal/users_banish_spec.rb, spec/services/users/cleanup_chat_channels_spec.rb, spec/services/users/delete_articles_spec.rb
Closes #3601 
Users who got banished left some dangling associations, most notably direct chat channels. This PR adds code for cleaning them up.
#3601
n/a
=> Remove direct chat channels when banishing user

app/controllers/internal/broadcasts_controller.rb, spec/requests/internal/broadcasts_spec.rb
Was poking around in the notification code again and trying to see how notifications connect to broadcasts. In process, tried to create a new broadcast, and was confused when nothing happened. Turned out, we had a bug (typo?) and no test to catch it! So, I fixed it. 
I also decided to raise errors when necessary in all broadcast endpoints, and cleaned up the tests and add specs for the endpoint that was borked!
To try it out, go to `/internal/broadcasts` and make sure you can create a new one.
Probably no one uses broadcasts but at least the next time someone goes to play with it in some other capacity, it will work 😄
=> Allow broadcasts to be created from internal/broadcasts

app/controllers/html_variant_trials_controller.rb
This moves `HtmlVariantTrialCreateJob` to run inline. The `create!` call does involve a `before_save` callback to `prefix_all_images`, but it seems it's still performant enough to run inline. If not, just let me know and I'll keep this process in the background and move it to Sidekiq instead.
I'll open a separate PR if/when this is merged to remove the old job and spec.
#5305
=> Move HtmlVariantTrialCreateJob from background job to inline

app/models/article.rb, app/workers/articles/update_main_image_background_hex_worker.rb, spec/models/article_spec.rb, spec/workers/articles/update_main_image_background_hex_worker_spec.rb
- [x ] no documentation needed
=> Migrate update main image background job to sidekiq

app/models/reaction.rb, app/models/user.rb
This allows the `User` model to be a `reactable`. This is part of prepping the backend for easier moderation, such as reporting with reacting to a spam acccount.
=> Add user as reactable

app/services/notifications/update.rb, app/services/users/delete_articles.rb, app/views/additional_content_boxes/boxes.html.erb, app/views/articles/_sidebar.html.erb, app/views/articles/_sidebar_additional.html.erb, app/views/articles/tag_index.html.erb, app/views/articles/tags/_sidebar_additional.html.erb, app/views/internal/articles/index.html.erb, app/views/internal/podcasts/edit.html.erb, app/views/moderations/mod.html.erb, app/views/organizations/_sidebar_additional.html.erb, app/views/organizations/show.html.erb, app/views/partnerships/_form.html.erb, app/views/users/_comments_section.html.erb, app/views/users/_main_feed.html.erb, app/views/users/_organizations_area.html.erb
As you know AR has many "presence" methods attached to "has many" relations: `.present?`, `.blank?`, `.any?`, `.empty?`, `.none?`, `.exists?`
Apart from the obvious result we expect due to their names, these are not all intercheangeable, sometimes resulting in unnecessary queries.
Armed with the section "any?, exists? and present?" (I've already submit a PR to optimize counts https://github.com/thepracticaldev/dev.to/pull/5478) in the article [3 ActiveRecord Mistakes That Slow Down Rails Apps: Count, Where and Present](https://www.speedshop.co/2019/01/10/three-activerecord-mistakes.html) by Nate Berkopec I went around the code, replaced those that could be cleverer in how they fetch data, documented the why of some of them and made sure they made sense for our cases.
Please let me know if …
=> Use cleverer patterns to fetch/iterate AR objects when checking presence

app/controllers/internal/users_controller.rb, app/controllers/users_controller.rb, app/services/moderator/delete_user.rb, app/workers/users/delete_worker.rb, spec/requests/internal/users_banish_spec.rb, spec/requests/user/user_destroy_spec.rb, spec/services/moderator/delete_user_spec.rb, spec/system/user/user_self_destroy_spec.rb, spec/workers/users/delete_worker_spec.rb
In #5061 we had planned to move deletion of users by admins/moderators to a background worker. When looking around I noticed we already had `User::SelfDeleteWorker`, which used the same service object (`Users::Delete) as the moderator controller. I therefore decided to reuse the same worker and renamed it to `Users::DeleteWorker`.
Closes #5061
=> Move user deletion by moderator to worker

app/controllers/chat_channel_memberships_controller.rb, spec/requests/chat_channel_memberships_spec.rb
Returns `ActiveRecord::RecordNotFound` instead of `Pundit::NotDefinedError` when chat channel membership is not found.
Fixes https://github.com/thepracticaldev/dev.to/issues/5790
=> Return NotFound error if ChatChannelMembership is not found

app/controllers/follows_controller.rb
It rescues from  ActiveRecord::RecordInvalid assuming that it only be raised in case that we have a race condition trying to create the same Follow model from different threads/request.
closes #5793
My first contribution to an open source project.
=> Fix raising validation if followable already exist(race condition)

lib/tasks/counters.rake
As discussed with @mstruve, I'm optimizing the `rails counters:update_users` task to do the following:
- use autocommitting transactions (Rails default)
- have the batch size customizable (so we don't need to redeploy if we want to tune this), for example `rails counters:update_users[50]` will load 50 items in memory instead of 1000 (the default)
#5373
=> Have counters:update_users use a transaction per user and customizable batch size

.erb-lint.yml
Our current ERB file linting configuration that is run in pre-commit hooks (.erb-lint.yml) checks for use of `html_safe` in ERB files, but based on a conversation with @rhymes we don't actually have a recommended fix for these issues. In addition: this linter was put into place without fixing existing violations, creating a minefield for any contributors that happen across those files. Our guidance to contributors is to do a `git commit --no-verify` to skip these checks: instead we should just have the linter skip the checks.
https://github.com/thepracticaldev/dev.to/pull/1657
=> Ignore `html_safe` in erb files

Gemfile, Gemfile.lock, docs/getting-started/start-app.md, docs/installation/others.md, docs/installation/readme.md
This removes the Foreman gem, as per the author's recommendation:
> Ruby users should take care *not* to install foreman in their project's `Gemfile`. See this [wiki article](https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman) for more details.
n/a
=> Remove Foreman gem

app/controllers/comments_controller.rb, spec/requests/comments_spec.rb
Deleting a comment for an article that had already been deleted failed as we weren't able to construct a `commentable_path`. This PR fixes that by redirecting the user to their profile.
Closes #3967
=> Allow deleting comments if article has already been deleted

Gemfile, Gemfile.lock, spec/labor/emoji_converter_spec.rb, spec/labor/markdown_parser_spec.rb
The version of [gemoji](https://github.com/github/gemoji) we currently use does not support the new disability emojis that were included in the latest Unicode standards.
The test I added if ran with gemoji 3 (the one use now) would fail like this:
```shell
1) EmojiConverter#convert converts disability emojis as well
Failure/Error: unicode = Emoji.find_by_alias(emoji).raw
NoMethodError:
undefined method `raw' for nil:NilClass
```
Note: these new emojis won't render on macOS Mojave because the operating system itself won't render them, but they are supported at least in Windows 10 and in macOS Catalina, see discussion in https://github.com/thepracticaldev/dev.to/issues/5835
In the meantime we add server side support for those :)
Closes #5835
=> Upgrade gemoji to support disability emojis

app/controllers/api/v0/articles_controller.rb, spec/requests/api/v0/articles_spec.rb
Apparently draper doesn't delegate "method missing" for unselected columns and our API specs didn't catch this as it was triggered by a logic branch that was never triggered in the tests.
This fixes https://app.honeybadger.io/fault/66984/ff08766a21fdc662b6a17adba001949f
#5805
=> Fix serialization error with video_thumbnail_url

.travis.yml, app/services/search/cluster.rb, app/services/search/tag.rb, lib/tasks/search.rake, spec/rails_helper.rb, spec/services/search/cluster_spec.rb, spec/services/search/tag_spec.rb
Creating this first index needs to be done in a couple of steps. 
1) THIS PR which lays out the foundation and building blocks to allow us to build any indexes we want to given a `Search::<search model name>` class.
2) Following this PR we will want to actually set up the new indexes in development and production. To accomplish this we will want to use our new setup and mapping rake tasks. Both will be run in the setup scripts for development and in the `release-tasks.sh` script for production.
3) Once all indexes are set up then [we can begin indexing Tags](https://github.com/thepracticaldev/dev.to/tree/mstruve/index-tags-to-es) to the new Elasticsearch index
https://github.com/thepracticaldev/dev.to/projects/6#card-32288079
Documentation will come in the next PR when these new rake …
=> Add Code To Setup the Elasticsearch Tag Index

db/migrate/20200205225813_add_notifiable_id_notifiable_type_action_index_to_notifications.rb, db/schema.rb
[This query](https://github.com/thepracticaldev/dev.to/blob/c6434d377b37e0a15e75736428a62522123ef20c/app/services/notifications/update.rb#L17-L26) in `/services/notification/update.rb` called by `Notifications::UpdateWorker` keeps failing with `PG::QueryCanceled: ERROR: canceling statement due to statement timeout` resulting in several dead Sidekiq workers.
This PR adds an index on the `notifications` table, it looks like an appropriate index was missing.
The query reads:
https://github.com/thepracticaldev/dev.to/blob/c6434d377b37e0a15e75736428a62522123ef20c/app/services/notifications/update.rb#L17-L26
I noticed the indexes on the `notifications` table didn't have an appropriate index. There's not an index for the 3 columns this query is calling for (`notifiable_id`, `notifiable_type`, …
=> Add index to notifications table to optimize query

docs/.nvmrc
It looks like our Netlify builds are broken - https://app.netlify.com/sites/devto/deploys/5e3b23c6d550dc0008794e8d - because they are trying to use Node 8 which is in maintenance mode and deprecated. This should set Netlify to use the same version we build the DEV's app with.
see failure in https://github.com/thepracticaldev/dev.to/pull/5443
=> Use Node lts/erbium (v12) for Netlify builds

app/views/liquids/_speakerdeck.html.erb
Fix #5682 
The speaker deck tag rendered cuts off horizontal edges due to setting 100% height. I had to remove 63px in order to render slide completely and seems to be fine in all screen sizes, including mobile
Didn't find any tests for this part to update, let me know if I missed it
#5682
=> Style: update height of speakerdeck tag to be avoid scaling

bin/startup, docs/getting-started/start-app.md
PR https://docs.dev.to/installation/others/ removed the `foreman` gem, but the startup script at `bin/startup` wasn't adjusted to match documentation. This PR also fixes a link in said documentation.
https://docs.dev.to/installation/others/
=> Correct startup script and docs

README.md
Adding some badges:
- Code climate technical debt
- Netlify builds
- Github code size
- Github commit activity (I chose weekly activity, but it could display monthly activity)
- Our `ready for dev` github issues
- Honeybadger's public dashboard
=> Add various badges to README [skip ci]

app/services/notifications/update.rb
This is a follow-up to the discussion on #5921. Adding the new index wasn't enough, jobs are still dying with the same error.
Following-up on the next hunch (shout out to @mstruve), it seems the issue is `.first`. Since `.first` adds `ORDER BY`, it slows things down. Oddly enough, calling `.last` works in prod.
One idea to fix this was to change the query to:
```ruby
new_json_data = notifications.where.not(json_data: nil).limit(1).json_data || {}
```
This then turned into a discussion of why are we even going through the effort of finding the old `json_data` when all the notifications are going to be updated with `new_json_data` anyways.
This PR removes the query of `notifications.first` altogether and just builds the `json_data` from scratch everytime, which should fix (famous last …
=> Remove .first query in services/notifications/update to fix dying jobs

bin/setup, bin/update, docs/deployment.md, release-tasks.sh
Now that Elasticsearch foundation has been laid, #5919 . This adds the `search:setup` rake task to the deployment pipeline as well as the local app setup and update pipeline. This setup is safe to run multiple times bc we check for the existence of indexes before attempting to create them. Further, if you try to add an alias multiple times Elasticsearch returns true but there is still only 1 alias in Elasticsearch. 
Following this I will [PR the code to index tags!](https://github.com/thepracticaldev/dev.to/compare/mstruve/index-tags-to-es)
https://github.com/thepracticaldev/dev.to/projects/6#card-32288297
=> Setup Elasticsearch indexes during Deploy and Local App Setup

app/controllers/internal/mods_controller.rb, app/controllers/podcasts_controller.rb, app/models/comment.rb, app/models/html_variant.rb, app/models/message.rb, app/models/reaction.rb, app/models/tweet.rb, config/environments/test.rb
This PR is a bit a mashup because it started one way and then it ended in a different way.
I started hunting for N + 1 errors in templates but didn't found any (kudos!) and while I was looking for improper usages of `where` in the view files I noticed we had a few methods that were unused.
I enabled `bullet` because I believe that by keeping it optional means it won't be very useful for contributors or reviewers (right now it's only enabled in development mode, which means that it's the developer that has to make sure there are no N + 1 errors in their PR, but a change in one's code could have ripercussions in other pages that aren't manually checked)
=> Enable bullet during tests to catch N+1 early (and some cleanups)

app/controllers/users_controller.rb, spec/requests/users_onboarding_spec.rb
We recently had two honeybadgers come up that showed us attempting to update a user's onboarding without an actual user. Not sure if these were pentesters or what but we should be making sure we have an authenticated user, aka `current_user` before running these controller methods. 
I am actually surprised we don't authenticate_user for all of these actions in the users controller but for now I wanted to just stick with the ones that were raising errors. 
https://app.honeybadger.io/fault/66984/bb578c35d3383ecd07b204f3a134457a
https://app.honeybadger.io/fault/66984/1dfe25f7fbf3c95456488daf1aca2817
=> Ensure user is authenticated before doing onboarding Actions

app/controllers/omniauth_callbacks_controller.rb, config/environments/development.rb, config/environments/test.rb, spec/services/rss_reader_spec.rb, spec/system/user_logs_in_with_twitter_spec.rb, spec/workers/metrics/record_db_table_counts_worker_spec.rb
We had some unused code for Timber in our config files for our development and test environments. However, this was completely clobbering Rails' default behavior of logging out to `log/development.log` and `log/test.log`!! 😬 We should allow for logging in these environments in particular since this is expected behavior. And, since we're not using Timber in either of these environments, we can just revert to using the Rails default debugging log levels.
Test this out by pulling down this branch and running `tail -f log/development.log` locally. You should see your local development logs 😻
=> Fix logging for dev and test environments

app/views/pages/shecoded.html.erb
There's tiny CSS issue on dev.to/shecoded page causing elements in header being small.
- https://github.com/thepracticaldev/dev.to/issues/5704 (potentially?)
(left is current, right is fixed)
=> Removing border-box from SheCoded landing page

app/controllers/chat_channel_memberships_controller.rb, app/controllers/chat_channels_controller.rb, app/models/chat_channel.rb, app/models/message.rb, app/services/users/cleanup_chat_channels.rb
We are indexing chat channels but we are never searching for them as far as I can tell. I attempted to confirm this by doing a search of the app for any indication of searching that index. I found none. We only search on the `SecuredChatChannelMembership` index. I then went into Algolia and found that no recent searches had been conducted, only updating documents. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32289313
=> Remove Unused ChatChannel Indexing

app/services/user_blocks/channel_handler.rb
We have to access the chat channel membership user when we are updating them during the permission validation so we should be eager loading them to save us some db hits. 
Fixes: https://travis-ci.com/thepracticaldev/dev.to/builds/147961924
Idk I am loving Schitts Creek these days so you get Schitts Creek gifs 🤷‍♀
=> Eager load users when handling chat channel memberships

app/views/pages/robots.text.erb
This PR helps steer search crawlers away from low value pages which will waste their resources and therefore result in fewer crawls of valuable content due to overall crawl budget allocations. Google is generally not looking to link to _our_ long tail or private endpoints, so if we can help guide, that is best.
Example
Some live robots.txt pages for reference...
https://stackoverflow.com/robots.txt
https://www.buzzfeed.com/robots.txt
https://www.nytimes.com/robots.txt
=> Add low-value landing pages to robots.txt disallow

app/services/notifications/reactions/send.rb, spec/models/notification_spec.rb
I tried to fix #5508 by checking the reaction owners' existence in the database when creating `reaction_siblings`. The problem is that the query becomes slower compared to the original code.
If this solution is not acceptable, could you please give me some guidance to improve it?
=> Handle Reactions Without Users When Sending Notifications

config/application.rb
Reverts thepracticaldev/dev.to#5960
We can't merge this until #5305 is complete.
=> Revert "Update queue_adapter to Sidekiq"

lib/tasks/search.rake
This PR fixes the following rubocop violation.
```
lib/tasks/search.rake:9:3: C: Layout/IndentationWidth: Use 2 (not 3) spaces for indentation. (https://rubystyle.guide#spaces-indentation)
Search::Cluster.update_mappings
^^^
```
=> Fix indentation in search.rake

app/controllers/api/v0/articles_controller.rb, spec/requests/api/v0/articles_spec.rb
Fixes #5957. Unhelpful errors from the `articles_controller` were being raised if a user submitted the article param in the wrong format (not a Hash/JSON object).
This PR adds logic to check the format of the article param and specs to test the case where a user submits incorrectly formatted article params.
#5957
=> Validate that API article params are a Hash

db/seeds.rb
Last week we removed indexing from ChatChannels, #5907 bc we were not using it for anything. This means we also need to remove all indexing methods in the rest of the codebase. 
#5907
=> Remove Indexing Helpers from ChatChannel model in seed script

db/seeds.rb, docs/getting-started/db.md
As a follow up to https://github.com/thepracticaldev/dev.to/pull/5948 I've added a "multiplication factor" variable for the seeds file.
You can use it like this:
```shell
$ SEEDS_MULTIPLIER=2 rails db:reset
$ psql PracticalDeveloper_development
PracticalDeveloper_development=# select count(*) from articles; select count(*) from users;
┌───────┐
│ count │
├───────┤
│    50 │
└───────┘
(1 row)
Time: 0.472 ms
┌───────┐
│ count │
├───────┤
│    20 │
└───────┘
(1 row)
```
:)
I haven't added it to the other entities yet, because I wanted to go about it in steps if this approach is deemed the correct one.
- https://github.com/thepracticaldev/dev.to/issues/4149
=> Add multiplier for seeds and use it for articles and users

app/controllers/notification_subscriptions_controller.rb
Here we are saving with a bang which will raise an error if any validations fail and sometimes they do which causes this error:
Honeybadger: https://app.honeybadger.io/fault/66984/4a1644c910a2cb05033dfc47bb35e395
```
ActiveRecord::RecordInvalid: Validation failed: User has already been taken
monitor.rb  235 mon_synchronize(...)
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
233     Thread.handle_interrupt(EXCEPTION_NEVER){ mon_enter }
234     begin
235       yield
236     ensure
237       Thread.handle_interrupt(EXCEPTION_NEVER){ mon_exit }
notification_subscriptions_controller.rb  25 upsert(...)
[PROJECT_ROOT]/app/controllers/notification_subscriptions_controller.rb:25:in `upsert'
```
Since in the next line we are checking if the …
=> Soft save notification_subscription and then check persisted

app/models/page.rb
As we discussed in https://github.com/thepracticaldev/dev.to/pull/5952#discussion_r376470025 `full_page` option is not used currently, so I removed it to avoid confusion.
=> Removed full_page from the Page TEMPLATE_OPTIONS

Dockerfile
It seems we broke our Docker process when merging #5780, as we now can't bundle without a `.ruby-version` file being present.
Closes #5967
=> Copy .ruby-version into Dockerfile

app/controllers/internal/configs_controller.rb, app/views/internal/configs/show.html.erb, spec/requests/internal/configs_spec.rb
Allowing ids to be mutated by admins from the `/internal/config` pages is dangerous.
This could cause issues if an admin tries to update the `SiteConfig.staff_user_id` to an id that is another user's id, or to an id that isn't valid.
We probably don't want to allow admins to do this at all.
=> Do not allow staff_user_id to be mutated

jest.config.js
While looking into a frontend issue for Molly, I cam across this error.
The issue occurs because jest is running a file that it thinks is a test suite that is not. The fix is to exlcude the `./config/webpack` from tests.
=> Fixed false negative of a frontend test suite failing.

app/views/service_worker/index.js.erb
In service workers, we should not be adding the shell to these views.
This will stop serviceworker shell from running in the `/embed/` context.
=> Add `/embed` to list of disallowed path matches

app/models/tag.rb, app/serializers/search/tag_serializer.rb, app/services/search/tag.rb, app/workers/search/tag_es_index_worker.rb, spec/models/tag_spec.rb, spec/services/search/tag_spec.rb, spec/workers/search/tag_es_index_worker_spec.rb
This PR begins indexing Tags into Elasticsearch! The Index and everything is already set up in production so all that is left is to fill it up! Once this goes out I will reindex all the Tags manually from a console and then going forward they should reindex themselves as they are created or updated. NOTE: We are still indexing to Algolia as well since that is where we are searching them still. Algolia will be the last thing removed once the search is rolled over to Elasticsearch
Performance: I realize this is very brute force, ie we are not checking if Elasticsearch attributes actually need to be updated before we reindex, we just do it automatically. I think this is absolutely fine in this instance since we are not creating tags at a rapid rate and they are very quick to index. I also am …
=> Index Tags to Elasticsearch after they are created

app/controllers/feedback_messages_controller.rb, app/controllers/internal/tools_controller.rb, app/controllers/internal/welcome_controller.rb, app/controllers/users_controller.rb, app/labor/badge_rewarder.rb, app/labor/cache_buster.rb
This changes some hardcoded instances of `dev.to` to the `ApplicationConfig['APP_DOMAIN']` version.
The only critical bug this was causing was in `CacheBuster` which causes non-dev.to versions of the site to fail in pinging Fastly.
I decifed to dip in and change some other low-hanging fruit on the backend
=> Replace dev.to with ApplicationConfig in a few locations

Gemfile
`bundle install` used to work from any directory but we kind of broke this behavior when we merged #5780 as now it requires `bundle install` to be run in the same folder where `Gemfile` resides:
```shell
$ cd app; bundle install
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - .ruby-version. Bundler cannot continue.
>  ruby File.read(".ruby-version").strip
#
```
This restores it by using a full path
=> Gemfile should be installable from wherever

app/controllers/users_controller.rb, app/views/users/_account.html.erb, config/routes.rb, spec/requests/user/user_destroy_spec.rb
This updates the request account deletion route to use POST and not GET for CSRF protection.
=> Use POST instead of GET for CSRF protection

spec/decorators/article_decorator_spec.rb
This spec fails any time we create a user that has a name that ends with a period, for example, "Les Schmidt Jr." which you can see below breaks the spec. 
```
1) ArticleDecorator#description_and_tags creates proper description when it is not present and body is not present and long, and tags are present
Failure/Error: expect(created_article.description_and_tags).to eq("A post by #{created_article.user.name}. Tagged with heytag.")
expected: "A post by Les Schmidt Jr.. Tagged with heytag."
got: "A post by Les Schmidt Jr. Tagged with heytag."
(compared using ==)
```
The decorator will not add an extra period but we will in our assertion statement
```
modified_description += "." unless description.end_with?(".")
```
This removes the extra period from the assertion statement to ensure it …
=> Flaky Spec Fix: Article Decorator Spec Remove extra period if name ends with it

app/assets/stylesheets/articles.scss
I introduced a styling bug for dev shop images with some left sidebar work changes to CSS. This fixes that.
Screenshots are different themes, but it's the same issue across all themes.
Before (PROD)
After (LOCAL)
=> Fixed an issue with dev shop logos not being styled properly.

docs/installation/docker.md
As @mstruve rightfully pointed out in the already merged PR, it's Elasticsearch, not ElasticSearch.
n/a
=> Fix spelling of Elastiscsearch in docs

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb, app/controllers/stories_controller.rb, app/services/articles/feed.rb, app/views/articles/_sticky_nav.html.erb, app/views/articles/index.html.erb, app/views/stories/_main_stories_feed.html.erb, spec/services/articles/feed_spec.rb, spec/system/homepage/user_visits_homepage_articles_spec.rb
This consolidates a few methods sprinkled throughout the server side Ruby code used to grab articles for the initial load of the main article feed to a single spot in `Article::Feed` service. This is part of the _Article Feed Content_ scope in the _Home Page Revamp_ project: future PRs will tweak this functionality to make the home page feed more relevant 
Great post from community [piannaf](https://dev.to/piannaf) breaking down how the feed is currently assembled: https://dev.to/piannaf/the-dev-to-feed-algorithm-5em5
=> Consolidate server side main article feed logic

app/controllers/email_subscriptions_controller.rb, app/mailers/notify_mailer.rb
Add unsubscribe option to badge and connect emails
n/a
Adds the `Unsubscribe` link to the two types of email
=> Add unsubscribe option to badge and connect emails

app/models/reaction.rb, app/workers/reactions/bust_reactable_cache_worker.rb, spec/models/reaction_spec.rb, spec/workers/reactions/bust_reactable_cache_worker_spec.rb
=> Change BustReactableCacheJob to BustReactableCacheWorker and move to sidekiq

app/controllers/api/v0/api_controller.rb, app/controllers/api/v0/articles_controller.rb, app/controllers/api/v0/classified_listings_controller.rb, app/controllers/api/v0/comments_controller.rb, app/controllers/api/v0/github_repos_controller.rb, app/controllers/api/v0/podcast_episodes_controller.rb, app/controllers/api/v0/tags_controller.rb, app/controllers/api/v0/videos_controller.rb, app/controllers/api/v0/webhooks_controller.rb, app/controllers/application_controller.rb
- `Api::V0::ApiController` inherits from `ActionController::Base` instead of our `ApplicationController`: I tried using `ActionController::Metal` and `ActionController::API` adding the requested methods but I had some initialization issues with the order of included modules, so I stuck with `ActionController::Base` which is the base class of our `ApplicationController`. The reason for this is that we don't want all modifications to the base UI controller to be inherited to API controllers
- Moved up `respond_to :json` one level
=> Small API controllers refactoring

app/views/users/_account.html.erb
This PR updates the link to the API documentation in the `_account` partial. 
@michael-tharrington I know this would have been a good first issue, but I was doing a `docker build` on my computer and this PR was easy enough to do from Github's web editor while waiting for that to finish. 😃 
Closes #6030
=> Fix API documentation link

app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb
This controller does not need verify authenticity token
n/a
n/a
=> Skips verify_authenticity_token in MailchimpUnsubscribesController

.rubocop.yml
When I [submitted a PR](https://github.com/thepracticaldev/dev.to/pull/6025) recently Rubcop locally told me to use slashes (see random example below)
```
Offenses:
spec/requests/tags_spec.rb:6:7: C: Rails/FilePath: Please use Rails.root.join('path/to') instead.
Rails.root.join("app", "models", "concerns")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
but then codeclimate defaulted to telling me to use arguments. 
Having this in our rubocop file should carry it over to codeclimate and we should be all set. If there is something else I need to do to get codeclimate to respect it let me know!
=> Enforce slashes for file paths with Rubocop 

app/services/search/cluster.rb, lib/tasks/search.rake, spec/services/search/cluster_spec.rb
@rhymes mentioned to me that he had gotten his Elasticsearch cluster into a bad state locally. The reason was because he attemped to index a document before the index was created. Since auto_index_creation is turned on by default the index was created but with the wrong name. This led to a whole lot of things breaking. In this bad state he also had no way to fix it because the destroy rake task was broken(though even in a good state would not have worked). To ensure that the destroy task always works I have updated it to destroy using a wildcard which will ensure any index regardless of name is cleared out and you can start fresh.
https://github.com/thepracticaldev/dev.to/projects/6#card-33018835
=> Prevent Elasticsearch auto index creation and Update Destroy Rake Task

app/assets/stylesheets/syntax.scss
This fixes a bug we have in syntax highlighting where lines that are marked as an error from the parser are not easiliy readable in the two dark modes:
I followed @benhalpern suggestion to actually remove the styling: https://github.com/thepracticaldev/dev.to/pull/4669#issuecomment-548408741
Disclaimer: there's a PR that was started by a contributor https://github.com/thepracticaldev/dev.to/pull/4669 - but as the contributor has seemingly abandoned it (they haven't responded to it for more than 2 months). I also tried to commit to "takeover" the PR but I'm not allowed to commit to it
- closes https://github.com/thepracticaldev/dev.to/issues/4577
- supersedes https://github.com/thepracticaldev/dev.to/pull/4669
This is how it looks now in the two dark modes:
=> Change error styling from syntax highlighting for a better UI in all themes

app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb, config/routes.rb, spec/requests/incoming_webhooks/mailchimp/unsubscribe_spec.rb
When experimenting with the Mailchimp unsubscribe webhook, @maestromac made the following discovery:
> [Mailchimp] sends a `GET` request to verify the URL. We only have a `#create` and it only accepts `POST`. Should we have an `#index` just for this purpose?
This PR adds the corresponding endpoint.
https://github.com/thepracticaldev/tech-private/issues/289
=> Add health check endpoint for Mailchimp unsubscribe webhook

docs/installation/mac.md, docs/tests/readme.md
It was unclear to me that I explicitly needed Elasticsearch in order for certain tests to run locally. We should specify that in the test section of the docs.
Also added a note about installing `wget`, which is required to install Elasticsearch in our docs.
N/A
N/A
=> Add more information about using Elasticsearch to docs

spec/decorators/article_decorator_spec.rb
In a previous PR(#6029) I attempted to fix this flaky spec by removing any periods that might be in the user name figuring if the name is "Sam Jr." then the final period would be removed and we would be good. HOWEVER that doesnt work for a name "Mr. Sam Jr." bc then all of the periods are removed. This updates the spec to use the same `end_with` logic that the method in the decorator uses so it should be super solid now. 
#4884
=> Flaky Spec Try 2: Article Decorator properly handles Names

Envfile, app/models/broadcast.rb, app/models/notification.rb, app/models/user.rb, app/services/notifications/welcome_notification/send.rb, app/views/internal/broadcasts/_form.html.erb, app/workers/notifications/welcome_notification_worker.rb, config/environments/development.rb, config/environments/production.rb, spec/requests/notifications_spec.rb, spec/services/notifications/welcome_notification/send_spec.rb, spec/workers/notifications/welcome_notification_worker_spec.rb
This is the initial work to [port over](https://github.com/thepracticaldev/dev.to/projects/7#card-32224049) the current welcome notification into a new "welcome notification" workflow. 
It's worth noting that this doesn't change the current behavior of the one welcome notification that we send out. It focuses more on setting up a new structure for welcome notifications and maintaining feature parity of the single notification we have on production currently!
Here are the main changes introduced by this PR:
⚠️ **Before this PR can be merged, we need to do the following:** ⚠️
https://github.com/thepracticaldev/dev.to/projects/7#card-32224049
https://github.com/thepracticaldev/dev.to/projects/7#card-32917275
N/A
**No _post-deployment_ tasks, but there ARE some pre-deployment tasks! See the …
=> Allow dynamic authoring of welcome notifications

.github/CODEOWNERS
There are a few more sections of the code that impact team delightful's work on revamping (welcome) notifications. Adding them so that @juliannatetreault and I become code owners of these files and are alerted whenever they come up in a relevant PR! 😸
=> Add more paths for team delightful in CODEOWNERS file

app/services/search/classified_listing.rb, app/services/search/cluster.rb, spec/services/search/classified_listing_spec.rb
This PR creates mappings for the `classifieds_listings` index on Elasticsearch and adds the index to Elasticsearch. This is part 1/4 in the process of getting `classified_listings` on Elasticsearch.
One thing I'd like to call attention to for review is the mappings...I may have gotten a little _"mappy happy"_ by adding the raw fields to certain attributes 🙈For example, `slug`. Since `slug` is based on the original title of the `ClassifiedListing` and doesn't change, I could see where it might be nice to do a full-text search on that field if someone were searching by an original `ClassifiedListing` title that had changed. Maybe?
https://github.com/thepracticaldev/dev.to/projects/6#card-32289262
No, because of the way we have it set up (#5939), the index will automatically be added on …
=> Add Elasticsearch index for classified_listings

app/models/reaction.rb, app/workers/reactions/update_reactable_worker.rb, spec/models/reaction_spec.rb, spec/workers/reactions/update_reactable_worker_spec.rb
=> Change UpdateReactableJob to UpdateReactableWorker and move to sidekiq

app/javascript/internal/controllers/buffer_controller.js, app/views/internal/articles/index.html.erb
This change auto resizes the suggested tweet textareas to satisfy an issue opened by Peter.
After a lot of searching, I came up with a bit of an odd solution. It turns out this is kind of an annoying problem to solve.
#5831
=> Autosize textareas for suggested tweets

db/seeds.rb
After #6003 we introduced a "multiplication factor" to increase the size of the seeded DB.
Unfortunately, this triggers the uniqueness limitations of Faker, the gem we use to generate unique text.
```shell
Faker::UniqueGenerator::RetryLimitExceeded: Retry limit exceeded for title
/Users/rhymes/.rvm/gems/ruby-2.6.5/gems/faker-2.10.1/lib/helpers/unique_generator.rb:30:in `method_missing'
/Users/rhymes/Development/devto/db/seeds.rb:88:in `block in <main>'
```
This PR fixes that by combining multiple random generators and also adds the multiplier to comments
=> Fix uniqueness generator when too much data is seeded

app/views/internal/badges/index.html.erb
Adds a placeholder to the badge award text area. These small tasks are great while waiting for Docker build to finish in the background 😄 
Closes #6023
=> Add placeholder to badge award text area

app/models/article.rb
This is a small PR of a much larger fix. Currently on the #she-coded tag pages we are showing the posts before they are being approved. Algolia is responsible for loading the paginated articles on these pages but it does not seem to have insight into whether the article is approved or not. 
This first step is to make sure that approved is included in the attributes that get sent.
[#372](https://github.com/thepracticaldev/tech-private/issues/372)
@benhalpern and I will need to have a manual task to re-index existing articles.
=> Add the 'approved' attribute to index articles so that we can filter by it later on.

config/initializers/honeybadger.rb
Honeybadger has a [breadcrumbs feature](https://docs.honeybadger.io/lib/ruby/getting-started/breadcrumbs.html#enabling-breadcrumbs) that will record additional context for you around an error when it happens which hopefully can help with debugging. Per the docs
> As of version 4.4.0, Breadcrumbs are available yet disabled by default. You must explicitly enable them if you want breadcrumbs to be reported. We plan on enabling breadcrumbs by default in version 5.0.0
So I figured we should probably turn it on and see what its all about! 
https://github.com/thepracticaldev/dev.to/projects/5#card-33094836
=> Enable bread crumbs for Honeybadger

app/services/search/classified_listing.rb, config/elasticsearch/mappings/classified_listings.json
Following @mstruve's lead on #6051, this PR moves mappings for `classified_listings` to a JSON file to remain consistent with the new setup designed to keep codeclimate from complaining about methods that are too long (> 25 lines).
#6051
=> Move ClassifiedListing mappings to JSON file

app/controllers/internal/configs_controller.rb, app/views/internal/configs/show.html.erb, app/views/internal/permissions/index.html.erb, app/views/layouts/internal.html.erb, spec/factories/users.rb, spec/requests/internal/configs_spec.rb
This related to this issue: #6049
I wouldn't want to say it fully closes it, but is a step in safeguarding this area.
This pull request adds extra safeguards for the `/internal/config` area of the site. This area contains values which could cause big problems if accidentally changed. It makes sense to restrict them even more thoroughly than other parts of the internal experience.
It now makes it so that anyone with `admin`,  `super_admin` or `single_resource_admin Config` can _view_ this area, but only users with the role `single_resource_admin Config` can write to it. And they need to submit this phrase when making a change as confirmation:
`My username is @your_username and this action is 100% safe and appropriate.`
The details here really should not change very often, so I think this …
=> Add additional safeguards for config write access

config/application.rb
We did this once before with #5960 and discovered we were a little eager. Now that [delayed jobs](https://github.com/thepracticaldev/dev.to/tree/master/app/jobs) are all gone, this is round 2 of updating the `queue_adapter` to Sidekiq as part of 🔪 `delayed_job`.
- #5305 
- #5960 
- [Project card](https://github.com/thepracticaldev/dev.to/projects/6#card-32289408)
We'll want to keep an eye on the Sidekiq queues and our monitors. The last time this was merged, the specs past but old jobs were queuing up in Sidekiq and failing.
=> Update queue_adapter to Sidekiq round 2

lib/data_update_scripts/20200214171607_index_tags_to_elasticsearch.rb, spec/lib/data_update_scripts/index_tags_to_elasticsearch_spec.rb
This DataUpdateScript will index all Tags to ensure environments are ready for Searching tags via Elasticsearch. Added a spec so in the future if we change the tag model in such away that this script breaks we will know to update or remove it. Hopefully, at some point, we will version the app so that doesnt happen but for now better safe than sorry.
#6024
=> Create DataUpdateScript to Index all Tags

Procfile, Procfile.dev, docker-compose.yml, docs/backend/notification.md, docs/getting-started/start-app.md
Since we no longer need to run `rake jobs:work` at boot up we can remove references to it from our Procfiles, docs, and docker compose file.
#5305
=> Remove References to rake jobs:work

app/controllers/internal/comments_controller.rb
Bullet doesn't seem to like this, and it makes sense because we don't
want to load ALL reactions, just some of them.
Co-authored-by: nspinazz89 <nspinazz89@gmail.com>
N/A
=> Remove unnecessary eager loading in internal comments controller

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb, app/assets/javascripts/utilities/buildArticleHTML.js.erb, app/assets/javascripts/utilities/timeAgo.js, app/javascript/utilities/__tests__/timeAgo.test.js
The current `timeAgo` function returns a string that includes markup. In Preact component land, we want to avoid that but still support non-Preact.
This is related to feature work for the homepage makeover. I decided to pull this out of my component PR to make things more bite-sized.
=> Made changes to timeAgo function for Preact component usage

app/controllers/stories_controller.rb, app/models/article.rb, app/views/articles/tags/_sidebar.html.erb
In PR [#6703](https://github.com/thepracticaldev/dev.to/pull/6037) I've updated the tag page to take into consideration the tags that require_approval. After PR [#6703](https://github.com/thepracticaldev/dev.to/pull/6037) is merged, the tag page will not show the articles that still need approval where required. 
This PR now updates the `Posts Published` count on the sidebar of the tag page to match up to the articles that have been approved and published on the page(where the tag requires_approval). Instead of counting **all the articles** that match that tag, it will **count the articles that have been approved**.
[#372](https://github.com/thepracticaldev/tech-private/issues/372)
=> Update the number of `Published Posts` to match the approved articles where necessary.

app/models/tag.rb, config/initializers/algoliasearch.rb
Now that we are indexing and searching tags from Elasticsearch we no longer need to be indexing them to Algolia 
#6024 
https://github.com/thepracticaldev/dev.to/projects/6#card-32955019
=> Remove Algolia from Tag model

app/views/notifications/shared/_comment_box.html.erb
When we are loading comments sometimes there will not be a reply found, in this case, we should fail gracefully and not raise a 500 to Honeybadger. 
Honeybadger: https://app.honeybadger.io/fault/66984/14771d0bde65f71e859dd56b8a3a9390
```
ActionView::Template::Error: undefined method `children' for nil:NilClass
_comment_box.html.erb  28 block (2 levels) in _app_views_notifications_shared__comment_box_html_erb(...)
[PROJECT_ROOT]/app/views/notifications/shared/_comment_box.html.erb:28:in `block (2 levels) in _app_views_notifications_shared__comment_box_html_erb'
26       <% end %>
27       <% cache "comment-box-comment-reply-#{@last_user_comment}-#{json_data['comment']['updated_at']}-#{json_data['comment']['id']}" do %>
28         <% reply = Comment.select(:id, :user_id, …
```
=> Add Safety navigators to handle a Missing Comment Reply

app/views/notifications/_notifications_list.html.erb
Adding `notification_id` to a Honeybadger error so that I/we can track it better. :)
See: https://docs.honeybadger.io/lib/ruby/getting-started/adding-context-to-errors.html
=> Add notification_id to honeybadger context

app/assets/stylesheets/scaffolds.scss
There are a few CSS properties on the `body` marked as `!important`. I came across this while integrating styles for articles into Storybook.
I'm trying to modify glaring issues in CSS in very small doses. I've tested this locally and removing the `!importants` does not appear to affect any pages.
=> Removed !important from some CSS properties set on body tag

app/controllers/api/v0/users_controller.rb, spec/requests/api/v0/users_spec.rb
Onboarding was not showing profile pic images—Failing silently with our backup awkward smileyface.
=> Make sure profile images show up in onboarding
