docs/getting-started/architecture.md
docs/getting-started/readme.md

Some new documentation to hopefully clarify some concepts where needed. It's just a start, more to come.

Add some architecture docs [skip ci]

---

app/services/notifications/new_comment/send.rb

Refactoring Notifications::NewComment::Send

---

app/javascript/article-form/articleForm.jsx

Refactoring articleForm.jsx, removes code duplication.

Refactoring articleForm.jsx removes code duplication

---

app/views/pages/_editor_guide_text.html.erb

Added an explanation for HTML comments into the editor guide.
#4130

Add comment syntax explanation #4130

---

docs/technical-overview.md

Consider it DRY for your docs. By removing redundant phrasing, this edit makes the tech stack list (technical overview page) easier to scan visually by putting the product name at the beginning of each line.
N/A
N/A

Remove repetitive docs phrasing to improve readability

---

app/liquid_tags/asciinema_tag.rb
app/views/liquids/_asciinema.html.erb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/asciinema_tag_spec.rb

Closes #4135
Adds a Liquid tag for [Asciinema](https://asciinema.org/) as requested in the issue.
#4135

Add Asciinema Liquid tag

---

spec/models/pro_membership_spec.rb

Fixed a minor rubocop issue so that it would run without any complains.

Fix rubocop issue

---

CONTRIBUTING.md

Fixed contributing docs

---

.gitignore
spec/labor/markdown_parser_spec.rb

Test for parse markdown with snake case words

Added test markdown parse snake case

---

app/assets/stylesheets/footer.scss

When the dashboard is showing, the content is centered and the footer receives `max-width: 606px`, when a post's page is showing the footer receive a `margin-left: 0px` , so when the dashboard is showing again nothing set the `margin-left` to `auto` again.
N/A
Before: https://imgur.com/pAiWgTg
After: https://imgur.com/ulXyobG

Fix footer position bug

---

app/assets/stylesheets/classified_listings.scss

Fixes Dev listings button color in pink theme
Closes https://github.com/thepracticaldev/dev.to/issues/3667

Fixes Dev listings button color in pink theme

---

docs/technical-overview.md

Just fixing a small layout bug!
Before:
After:

Fix technical overview doc layout [ci skip]

---

app/assets/stylesheets/preact/onboarding-modal.scss

Updated the styles in `app/assets/stylesheets/preact/onboarding-modal.scss` to support all themes. I tried to keep all of the default colors intact, so if the default theme is selected, it looks pretty much the same as it used to.
A couple of things I ran into:
* The `input[type='checkbox']:checked` background used to be set to `--theme-top-bar-write-background`, but the minimal light theme uses white for that variable, so I changed it to use `--theme-anchor-color` instead.
* The `/assets/mobile-onboarding-background.png` background image for the mobile view has a slightly transparent white background on it, which makes it difficult to read white text even when the background is dark (see the dark mobile theme screenshot below), so I've set the text color for that part to use `$black` for …

Make onboarding compatible with all themes (#3604)

---

Gemfile.lock

Error during building dev environment due to lacking dependency fix.
Further details: https://github.com/thepracticaldev/dev.to/issues/4179
https://github.com/socketry/nio4r/commit/0e820966453acff44a0e5763224ae91008a43306.
_I was looking for a dependencies meme but that's funnier_

Updates nio4r gem version

---

README.md

- [ X ] Documentation Update
Included basic instructions to run docker container using supplied dockerfile
😰

Added anchor and basic setup using docker

---

Envfile
app/services/ping_admins.rb
config/initializers/slack_notifier.rb
spec/services/ping_admins_spec.rb

Create tests to PingAdmins
#2917

Create tests to PingAdmins

---

app/javascript/onboarding/components/PersonalInfoForm.jsx

Refactors personalInfoForm jsx, removes code duplication.

Refactoring personalInfoForm.jsx removes code duplication

---

app/controllers/api/v0/follows_controller.rb
app/controllers/users_controller.rb
app/jobs/users/follow_job.rb
spec/jobs/users/follow_job_spec.rb
spec/requests/follows_api_spec.rb
spec/system/user_selects_looking_for_work_spec.rb

Move ``user.follow`` delay calls to ActiveJob. 
#3136
No UI changes.

Move user.follow delay calls to ActiveJob (#3136)

---

app/controllers/api/v0/articles_controller.rb
app/services/article_api_index_service.rb
app/views/api/v0/articles/index.json.jbuilder
app/views/api/v0/articles/show.json.jbuilder
spec/requests/api/v0/articles_spec.rb

- refactored controller
- modifyied views
- added tests
Add collection_id field for retrieving and filtering
#3669

Add collection ids to Api (reading + filtering)

---

docs/technical-overview.md

This PR removes periods that were present at the end of only some lines in the technical overview list.
N/A
N/A

Remove periods in technical overview list

---

app/views/liquid_embeds/show.html.erb

No arguments are needed for the template render, passing a string is a bit misleading.

Removed useless argument

---

app/lib/constants.rb

Adding a new instance to the list. This one is very cyberpunk! 
Small change in the list of Mastodon instances. Tthis PR allows any cybre.space user to add the link in their page (as myself!)

Adding cybre.space instance

---

app/assets/stylesheets/credits.scss

- [ x ] Bug Fix
Removed fixed width of .existing-credits and .ledger elements for small/medium screens.  Added breakpoint for larger displays.
Before and after demonstrated in attached image
- [ x  ] no documentation needed

Mobile friendly design for /credits page

---

docs/getting-started/branching.md
docs/getting-started/committing.md
docs/getting-started/config-env.md
docs/getting-started/db.md
docs/getting-started/forking.md
docs/getting-started/start-app.md
docs/getting-started/workflow.md

Because:
- Some areas of these docs are unpolished
- There are a significant number of skill-level assumptions made in
these docs
I've gone through the "Getting Started" docs in order and tried to
address the things I felt were missing or unclear. Largely this was just
adding a bit more context, but there were also some formatting tweaks.
I'm not confident this covers everything I'd like to do for these docs,
but it's a start. One of the things that frustrates me about this set of
onboarding docs is a missing target audience. I think we are trying to
target people who are familiar with GitHub and also those who are new to
contributing to Open Source (as well as some who are new to Rails), but
the docs seem to assume a significant amount of knowledge. I'd like to
revisit that in the …

Update DEV onboarding documentation

---

app/assets/stylesheets/comments.scss

This PR fixes a date alignment issue in a comment embedded by a liquid tag
Fixes #962

Fix embedded comment date alignmemt issue

---

app/javascript/packs/notificationSubscriptionHandler.js

Fix linting issues found in notificationSubscriptionHandler.js
#3777

#3777 Fix lint errors in notificationSubscriptionHander.js

---

app/assets/stylesheets/article-form-needed-legacy.scss
app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/classified_listings.scss
app/assets/stylesheets/comments.scss
app/assets/stylesheets/dashboard.scss
app/assets/stylesheets/footer.scss
app/assets/stylesheets/ltags/DevCommentTag.scss
app/assets/stylesheets/ltags/GithubTag.scss
app/assets/stylesheets/ltags/PodcastTag.scss
app/assets/stylesheets/podcast-episodes-show.scss
app/assets/stylesheets/preact/onboarding-modal.scss
app/assets/stylesheets/shared.scss
app/assets/stylesheets/top-bar.scss
app/assets/stylesheets/user-profile-header.scss

Just cleaning out some commented out SCSS.

Remove commented out SCSS

---

app/assets/stylesheets/badges.scss
app/controllers/badges_controller.rb
app/views/badges/index.html.erb
app/views/layouts/_styles.html.erb
config/routes.rb
spec/requests/badges_spec.rb

Add badges index page.
Closes #4001

Add badges index page.

---

app/views/podcast_episodes/_episodes_feed.html.erb

Podcast title is now a link to the podcast in the episodes feed

Added link to podcats from episodes feed

---

app/javascript/article-form/__tests__/articleForm.test.jsx

I added a little test to the articleForm to test opening the help window.

Test: add test for opening help window on articleForm

---

app/assets/stylesheets/badges.scss

Fixes #4277
**Desktop:-**
**Mobile:-**

Fix badges overlapping in badges index page

---

app/javascript/sidebar-widget/__tests__/__snapshots__/sidebarUser.test.jsx.snap
app/javascript/sidebar-widget/__tests__/sidebarUser.test.jsx

I added another test, this time for the sidebarUser component ☺️

Test: add test for sidebarUser component

---

app/assets/javascripts/.eslintrc.js
app/assets/javascripts/initializers/initializeArticleReactions.js

- Refactors file according to eslint rules
- Add showModal and sendHapticMessage to globals in eslintrc.js
- Shorten initializeArticleReactions() by distributing parts of it into jumpToComments() and requestReactionCounts() (Fixes code-climate issue)
- requestReactionCounts() makes an ajax request to get the reaction counts
- jumpToComments() jumps to comments element directly if the element jump-to-comments is present
#3777

Refactor initializeArticleReactions.js

---

app/labor/flare_tag.rb
docs/frontend/liquid-tags.md
docs/getting-started/architecture.md
docs/getting-started/pull-request.md

Added some app concepts. Will continue to elaborate.

Add more info to architecture

---

app/assets/javascripts/manifest.json.erb

This should fix issue with PWA icon not being adaptive on mobile devices.
Fixes #4111 
Did this edit on Github online editor so haven't been able to make any screenshots yet (or confirm that it indeed fixes it).

Added `purpose` tag to 192x192

---

app/assets/javascripts/initializers/initializeCreditsPage.js

* Refactors file according to eslint rules.
#3777

Refactor: initializeCreditsPage.js

---

app/controllers/internal/comments_controller.rb
app/models/comment.rb
app/policies/internal/comment_policy.rb
spec/policies/internal/comment_policy_spec.rb

Create scoped policy for internal/comment

---

app/labor/markdown_fixer.rb
spec/labor/markdown_fixer_spec.rb
spec/models/article_spec.rb

Regexp `\s?` for some reason did not take into account the absence of a space
https://github.com/thepracticaldev/dev.to/issues/3846

Markdown fixer: fix front matter bug with no space

---

app/assets/javascripts/initializers/initializeCommentDropdown.js

- The file was already compliant, just needed to add  'use strict'.
- Removed an unnecessary `no-unused-vars` rule disable. 
#3777

Refactor/fix initializeCommentDropdown.js

---

app/assets/javascripts/initializers/initializeDashboardSort.js

Refactors file according to eslint rules.
#3777

Refactor: initializeDashboardSort.js

---

app/assets/javascripts/utilities/buildArticleHTML.js.erb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/_single_story.html.erb
app/views/articles/index.html.erb
app/views/articles/tag_index.html.erb
app/views/layouts/_signup_modal.html.erb
app/views/layouts/_top_bar.html.erb
app/views/stories/_sign_in_invitation.html.erb

I ran the website through webhint.io - see [result](https://webhint.io/scanner/49d4a778-ea34-4e05-9567-d08a5c6405e4) - and fixed some of the "quick wins"
FYI: the button element defaults to `type="submit"`, that's why adding `type="button"` is necessary for a11y

Add an alt text and some type="button" attributes

---

app/assets/javascripts/initializers/initializeCommentPreview.js

- add `use strict` to the file; the rest of the file is already compliant.
- has already been refactored mostly by @nickytonline 
#3777 
#3082

Fix eslint issues in initializeCommentPreview.js

---

docs/installation/windows.md

This should address issue #4344
* Updated Windows PostgreSQL install link to point to working official page
* Added link to internal PostgreSQL specific install notes
Updated Windows installation doc so that PostgreSQL section mirrors that of other OS docs and points to correct install page.
Fixes #4344 
NA

Windows Docs: Updated PostgreSQL Section

---

app/assets/javascripts/initializers/initializeBodyData.js

- [ X] Refactor
This pull request resolves ESLint errors and warnings in app/assets/javascripts/initializers/initializeBodyData.js.
Lint issues with JavaScript Files #3777 
- [ X] no documentation needed

Fix ESLint errors in initializeBodyData.js

---

app/javascript/article-form/elements/bodyPreview.jsx

Refactor: BodyPreview.jsx
https://github.com/thepracticaldev/dev.to/issues/2470

Refactor: BodyPreview.jsx

---

app/models/classified_listing.rb

1. Re-creating the same hash on every call to `categories_available` seems wasteful. So, I moved them into a constant, which also simplified `validate_category`.
1. Simplified `select_options_for_categories` and used the `ActiveSupport` string extension instead of dragging a helper into the model layer.
1. Removed repeated calls to `to_s` from `restrict_markdown_input`
Only the first point seemed important, but the others do improve readability.
n/a
n/a

Refactor classified_listings.rb

---

app/javascript/chat/article.jsx

Remove unused import
Removed unused import. Import referenced code that was removed in a commit 5 months ago and was not being used anywhere else in the file.

Remove unused import

---

docs/backend/auth-github.md

Add a sentence to clarify GitHub Authentication
While following the documentation, I was confused about which scopes needed to be selected during the generation of the personal token. It turns out, you don't need any of them, so I added that to the documentation.

Add a sentence to clarify GitHub Authentication

---

app/labor/flare_tag.rb

Add #todayilearned as a flare tag.

Add todayilearned as a flare tag

---

docs/frontend/debugging.md

Fixed a typo

---

docs/installation/mac.md

I ran into those today while trying to get everything set up locally. Hopefully this will help future contributors!

macOS installatoin guide: add two possible problems + solutions

---

app/assets/stylesheets/settings.scss

Rather than centring the preview with padding (which may not always be correct) move to flex to calculate for you.
#4212 
N/A

Centre with flex rather than padding

---

app/javascript/article-form/elements/moreConfig.jsx

Refactor: moreConfig.jsx
https://github.com/thepracticaldev/dev.to/issues/2470

Refactor: moreConfig.jsx

---

app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
app/javascript/src/components/ItemList/__tests__/ItemListItemArchiveButton.test.jsx

I added tiny little extra tests.

Test: add test for ItemListItem and ItemListItemArchiveButton

---

app/lib/constants.rb

Add anarchism.space as a mastodon instance

---

app/views/shared/_logo_design.html.erb
app/views/users/_org_admin.html.erb
app/views/users/_profile.html.erb

- created a shared partial logo_design file
- moved text, bg and logo from profile.html.erb to logo_design.html.erb
- used logo_design to org_admin
org admin can preview dev.to design logo
feature-request #4321. See also #4212
**SAMPLE**
**DB**
**mobile**
**tablet**
**desktop**

preview of organization logo design on settings

---

app/assets/javascripts/initializers/initializeAllTagEditButtons.js
app/assets/javascripts/initializers/initializeArchivedPostFilter.js
app/assets/javascripts/initializers/initializeArticleDate.js

Fix eslint errors in javascript initalizers
- initializeAllTagEditButtons
- initializeArchivedPostFilter
- initializeArticleDate
part of #3777 
N/A

Fix eslint errors in JavaScript initializers

---

app/javascript/packs/sidebarWidget.jsx
app/javascript/sidebar-widget/SidebarWidget.jsx
app/javascript/sidebar-widget/sidebarUser.jsx

Fixed three things from #2470 
/app/javascript/sidebar-widget/SidebarWidget.jsx
/app/javascript/sidebar-widget/sidebarUser.jsx
/app/javascript/packs/sidebarWidget.jsx
#2470

Eslint fix: for sidebarwidget pack, sidebarwidget and sidebaruser

---

app/views/internal/articles/_individual_article.html.erb

Follow up PR https://github.com/thepracticaldev/dev.to/pull/4364 which fix a few more things I forget to push, fix another space I found and refactor conditions by comment https://github.com/thepracticaldev/dev.to/pull/4364#pullrequestreview-300611774
Originally fixes issue https://github.com/thepracticaldev/dev.to/issues/4276

remove a space and refactor conditions

---

app/javascript/onboarding/components/ClosingSlide.jsx

Just a couple of things I noticed while in here

Remove unused import and unused props

---

docs/technical-overview.md

After a previous change that I made to move the other product names to the beginning of the list lines, InstantClick was really bugging me as the odd one out
N/A
N/A

Technical overview docs: move product name/link to beginning of line

---

app/javascript/article-form/elements/__tests__/__snapshots__/errors.test.jsx.snap
app/javascript/article-form/elements/__tests__/__snapshots__/mainImage.test.jsx.snap
app/javascript/article-form/elements/__tests__/__snapshots__/notice.test.jsx.snap
app/javascript/article-form/elements/__tests__/errors.test.jsx
app/javascript/article-form/elements/__tests__/mainImage.test.jsx
app/javascript/article-form/elements/__tests__/notice.test.jsx

Test: add test for errors, mainimage and notice

---

app/views/users/_org_member.html.erb
config/routes.rb
spec/system/organization/user_leaves_an_organization_spec.rb

Fixes issue where leave organization did not include organization id and thus pointed to an invalid route.
Fixes [4387](https://github.com/thepracticaldev/dev.to/issues/4387)

Fixed Leave organization not working (#4387)

---

app/views/api/v0/articles/me.json.jbuilder
docs/api_v0.yml

I added page_views_count to me/articles - published, unpublished, all
Issue: #4250

Add views count for authenticated users articles [#4250]

---

app/assets/javascripts/initializers/initializeCommentDropdown.js

- Make use of `document.body.contains()` to check if the element is present before trying to Add or Remove Event listeners or assign attribute values to the same.
#4377

Fix JavaScript Console errors in /Comments sub-page of any article

---

app/labor/rate_limit_checker.rb
app/models/article.rb
app/models/badge_achievement.rb
app/models/mention.rb
app/models/notification.rb
app/models/user.rb
spec/models/notification_spec.rb
spec/models/user_spec.rb
spec/requests/articles/articles_update_spec.rb
spec/requests/internal/users_spec.rb
spec/requests/notifications_spec.rb
spec/services/notifications/tag_adjustment_notification/send_spec.rb

Removed unused methods _without_delay
https://github.com/thepracticaldev/dev.to/issues/2950

Removed unused methods _without_delay

---

docs/api_v0.yml

We were missing error info on some endpoints

API: docs update to add error info and other small fixes [ci skip]

---

app/views/dashboards/pro.html.erb

This didn't really sound correct, so I slightly reworded it
n/a
n/a
📖

Fix some strange wordings on the pro dashboard

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/more-articles.scss

Updated the style to break word if the post title cannot be displayed in the same line
Fixes #4383

Fix post title going out of the box (#4383)

---

app/assets/javascripts/initializers/initializeTimeFixer.js
app/views/events/_event.html.erb

Refactor `initalizeTimeFixer.js`
part of #3777 
Fixes #4455
N/A

Refactor initializeTimeFixer.js

---

public/offline.html

The current Offline Page loses state on resizing/ zooming operation (the drawing and last colour preference). 
Fixes #4471

Persist Canvas State on Resizing

---

app/javascript/packs/Onboarding.jsx

This function isn't called anywhere in the project.

Remove unused function

---

app/javascript/packs/Onboarding.jsx
app/javascript/packs/articleForm.jsx

Changes:
- Refactored articleForm.jsx by moving loadForm() before document.ready.then()
- Removed 'function' in .then() and modified to .then(() => {
- Removed unused function 'isUserSignedIn' in Onboarding.jsx
See: #2470
Fixing eslint warnings and errors in app/javascript/packs directory
See issue #2470

Fixing eslint errors and warnings under /app/javascript/packs

---

docs/installation/linux.md

On an install of DEV on a fresh instance of Ubuntu 18, I ran into a couple more errors that weren't mentioned in the docs.  The fixes were pretty easy, but I thought I'd add them to reduce friction for everybody else.
Installing on Linux documentation
N/A

[docs] Update "Installing on Linux" docs with more error messages

---

app/javascript/article-form/elements/bodyPreview.jsx

Refactor app/javascript/article-form/elements/bodyPreview.jsx

---

spec/requests/events_spec.rb

This PR adds some events specs

Events page: add specs

---

docs/installation/docker.md

We forgot to update the documentation in #4477

Mention `POSTGRES_VERSION` variable in documentation

---

app/controllers/users_controller.rb

Split tab handling code into smaller handle_#{tab_name}_tab methods.
CodeClimate was complaining about this method being longer than 25 lines, this shrinks it down to 15 lines.
#3739

Refactor UsersController#handle_settings_tab

---

app/javascript/shared/components/tags.jsx

Refactor: component Tags.jsx

---

app/javascript/article-form/__tests__/articleForm.test.jsx
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/elements/__tests__/__snapshots__/errors.test.jsx.snap
app/javascript/article-form/elements/__tests__/__snapshots__/mainImage.test.jsx.snap
app/javascript/article-form/elements/__tests__/tags.test.jsx
app/javascript/article-form/elements/bodyPreview.jsx
app/javascript/article-form/elements/errors.jsx
app/javascript/article-form/elements/mainImage.jsx
app/javascript/article-form/elements/moreConfig.jsx
app/javascript/article-form/elements/orgSettings.jsx

There are a lot of eslint errors in `app/javascript`. According to #2470, we have decided to fix all of them in every .jsx file. To be honest, I don't really understand how you have been able to commit changes, since there's a commit hook which prevents us from committing `jsx` files with eslint errors. I believe you use the `--no-verify` git flag probably. 
This particular PR includes eslint fixes for the files inside the `app/javascript/article-form` folder to keep the review process simpler for the reviewer. You can see all the related files in the associated github issue (#2470) and what's been already taken by a certain contributor.
There are a lot of (not so related) changes because running Prettier on the changed files is already part of the pre-commit hook. I'm not sure if it's ok …

Fix eslint issues in article-form's jsx files

---

README.md

Adding myself to core team members

Add Molly Struve to Core Team Members

---

app/views/users/_org_admin.html.erb
app/views/users/_org_non_member.html.erb

Updated a couple of placeholder texts to encourage using https instead of http.

Little placeholder tweak to encourage using https

---

app/views/layouts/_footer.html.erb

The welcome message in dev tool is nice but it gets in the way when it is used extensively in development.
n/a
n/a

Only show hello-dev.js in production

---

app/views/pages/_editor_guide_text.html.erb

Found that there was an extra curly bracket in liquid tag guide so I just removed it

removed extra bracket from liquid tags in editor guide

---

docs/frontend/liquid-tags.md

I went through all the markdown files inside the 'docs' folder and looked for typos. This PR is the only typo I could find.

Fix typo in liquid tags docs

---

docker-run.sh

Correct the spellings in docker-run.sh file

fix the spellings in docker-run.sh

---

docker-run.sh

Decrement the Retry counter after attempting the operation
Fixes #4536

Docker: fix the issue with retry in docker-run

---

app/assets/javascripts/initializers/initializeTouchDevice.js

Refactor initializeTouchDevice and fix eslint errors
part of #3777 
N/A

Refactor initializeTouchDevice

---

app/services/article_api_index_service.rb
spec/requests/api/v0/articles_spec.rb

Add missing `per_page` parameter to articles request
Fixes #4463

API: Add pagination to articles

---

app/javascript/githubRepos/githubRepos.jsx
app/javascript/listings/elements/title.jsx

Fix eslint errors in listings/elements/title.jsx

---

app/helpers/articles_helper.rb
spec/helpers/articles_helper_spec.rb

Refactor a method in the ArticlesHelper to simplify the code a little bit.  Create ArticlesHelper tests for this method (`get_host_without_www`).  This is mostly a way to get ramped into contributing to the back end code base and writing tests.

[refactor] get_host_without_www Article method.  Add tests.

---

app/labor/random_gif.rb

I added these gifs to milestone notifications:

add gifs to milestone notifications

---

app/services/article_api_index_service.rb
spec/requests/api/v0/articles_spec.rb

#4522 
Add try for decorate if article nor present 
Fixes #4522

Articles API: state=all by itself results in a 500 error

---

app/controllers/chat_channels_controller.rb
app/views/chat_channels/show.json.jbuilder

Eager load users when looping through messages to avoid N+1 queries when looking up user information for a message

Eager load users before looping through messages

---

app/views/api/v0/articles/index.json.jbuilder
app/views/api/v0/articles/show.json.jbuilder
docs/api_v0.yml
spec/requests/api/v0/articles_spec.rb

Fix API inconsistencies between articles 'index' and 'show' by adding missing fields to each request
Closes #4206

Fix API inconsistencies between articles 'index' and 'show'

---

docs/deployment.md
docs/readme.md

Create documentation on deployment CI/CD process. Deployment portion is written by @mstruve 
Resolve https://github.com/thepracticaldev/dev.to/issues/4494
n/a

Create documentation on deployment CI/CD process

---

app/views/articles/index.html.erb

Fix for Issue #4581 / #4580 
#4581 / #4580

Remove climate strike related code

---

app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/IntroSlide.jsx

I went ahead and made these changes because I am working in this file and didn't see another PR for this file.
#3777 and #2470

Fix linter complaints in onboarding/components/IntroSlide.jsx

---

docs/api_v0.yml

I've updated the API docs with a few things:
- added `beta` in the title
- updated the examples of ArticleIndex and ArticleShow now that https://github.com/thepracticaldev/dev.to/pull/4560 has been merged
- added unique `operationId` to each operation (they also generate better urls)

API docs updates

---

app/assets/stylesheets/dashboard.scss

#4568 
Create new rules for css

Pro - Stats view - Buttons are not dark-mode friendly

---

docs/readme.md

just a super-small grammar fix for the docs.

removed unnecessary word from docs

---

README.md

Made a couple of small changes to the README to help new contributors (like myself) get their dev environments get set up quickly. 
- Added ImageMagick to the list of dependencies, since it is listed as a dependency for macOS, Windows, and Linux on docs.dev.to, but not listed in the README.
- Added a sentence to help clarify how to add the Algolia credentials to the project, since it had been a long time since I'd dealt with Rails application config variables and I'd forgotten that they lived in `config/application.yml` (and I just didn't read two lines down and figured I wasn't the only one who'd gotten confused at that step).

README updates for clarification

---

CODE_OF_CONDUCT.md
LICENSE.md
docs/backend/notification.md
docs/design/branding.md
docs/design/theming.md
docs/installation/docker.md
docs/installation/linux.md
docs/self-hosting.md

I came across this accidentally while merging latest upstream master into another branch of mine. The precommit failed because of linting errors but it still modified these files, so just popping in a separate PR as it's not related to my webpack work.

Ran Prettier on some markdown files

---

Dockerfile

Adding ImageMagick as one of the dependencies to be installed inside Docker. Without this change, a new dev is unable to run the Step 2 in https://docs.dev.to/installation/docker/#running-the-docker-app-(basic) `docker-compose run web rails db:setup` as it will run the `rails db:seed`. It fails at the first data seeding `1. Creating Organizations` which requires ImageMagick. 
*Error encountered*:
```
ActiveRecord::RecordInvalid: Validation failed: Profile image can't be blank, Profile image Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: You must have ImageMagick or GraphicsMagick installed
```

Add ImageMagick as one of the dependencies to be installed inside Docker

---

.github/CODEOWNERS
.travis.yml

Update .travis.yml and .codeclimate.yml

---

Envfile
config/environments/production.rb

This is a starting point for trying to extract as much of the DEV-specific stuff out into environment variables and other configuration files to make it easier for people to start their own communities.  Also, helping to document the requirements for a production environment.  I assume there will be a lot more work to do.
**Note: This affects the production build in ways that I'm not able to write tests for, which is scary.**
I'm working on standing up my own production DEV instance to test things out on, but there's a lot of integrations (and a lot to learn! 😄 ), so that's not quite there yet.  But I've got the build through asset pre-compilation so far, which was exciting.
**More note: this change would require the addition of the Env variable `HEROKU_APP_URL` in order to work.**
As …

[deploy] Extract DEV specifics to Env variables

---

app/controllers/internal/permissions_controller.rb
app/views/internal/articles/index.html.erb
app/views/internal/permissions/index.html.erb
config/routes.rb
spec/requests/internal/permissions_spec.rb

Add `<detail>`, `<summary>` tags to help make article view less cluttered. Also added new view to list users with admin permissions.

Add some html to internal articles and new internal view

---

app/assets/javascripts/lib/pulltorefresh.js

Fixes some eslint errors:
1. Use the global form of 'use strict'
2. Unexpected unnamed function
https://github.com/thepracticaldev/dev.to/issues/3777
NA

Fix lint errors in pulltorefresh.js

---

app/liquid_tags/stackexchange_tag.rb
spec/liquid_tags/stackexchange_tag_spec.rb
spec/support/fixtures/vcr_cassettes/stackexchange_api.yml

Fix answers from other stackexchange sites have the wrong link

---

app/assets/javascripts/initializers/initializeBaseUserData.js

Made lint fixes in `/app/assets/javascripts/initializers/initializeBaseUserData.js`
#3777

Lint fixes in initializeBaseUserData

---

Envfile
app/views/layouts/application.html.erb
app/views/layouts/internal.html.erb
app/views/pages/shecoded.html.erb

For generalization of the platform, technical administrators would now be able to provide a URL to a custom favicon of their choice.
Resolves #4659

Add ability to set favicon through environment variable

---

.travis.yml

Add proper deployment condition

---

app/assets/stylesheets/user-profile-header.scss
app/javascript/profileDropdown/blockButton.js

There was an error where `blockButton.dataset` was being called when `blockButton` is `undefined`. This fixes it.
Also added theming to the dropdown menu.

[deploy] Add guard for block button presence and add theming of profile dropdown

---

app/labor/assign_tag_moderator.rb
app/models/user.rb

Move moderator_for_tags to Redis
Issue #4670 
Moderators IRL 👇

Move moderator_for_tags Cache Key to Redis

---

app/controllers/ga_events_controller.rb

Move daily_random_key to Redis. This cache key is only used in one location.
Issue #4670

Move ga daily_random_key to Redis [deploy]

---

.codeclimate.yml

Apply rule 3 for a more reasonable refactoring.
n/a
n/a

Loosen Codeclimate's duplication rule

---

app/controllers/api/v0/reactions_controller.rb
app/controllers/reactions_controller.rb
app/models/reaction.rb

Move count_for_reactable-* keys to Redis.
Issue #4670

Move count_for_reactable-* keys to redis

---

app/labor/flare_tag.rb

Move "article_flare_tag" key to *Redis*
Issue #4670 
No UI changes

Moved article_flare_tag to Redis

---

app/labor/reading_list.rb

Move "reading_list_ids_of_articles" key to *Redis*
Issue #4670 
No UI changes

Moved reading_list_ids_of_articles to Redis [deploy]

---

app/models/user.rb

Moved "following_users_ids" to *Redis*
Issue #4670 
No UI changes

Moved following_users_ids to Redis

---

app/controllers/chat_channels_controller.rb

Move "user-github-token" key to *Redis*
Issue #4670 
No UI changes

Moved user-github-token to Redis

---

app/services/suggester/articles/classic.rb

Move "classic-article-for-tag" key to *Redis*
Issue #4670 
No UI changes

Moved classic-article-for-tag to Redis [deploy]

---

app/labor/follow_checker.rb

move cached_follow_check to redis
handle #4670

move cached_follow_check to redis

---

app/decorators/user_decorator.rb

Move cached_followed_tags to redis
handle #4670

Move cached_followed_tags to redis [deploy]

---

app/liquid_tags/jsitor_tag.rb
app/views/liquids/_jsitor.html.erb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/jsitor_tag_spec.rb
spec/support/fixtures/approvals/jsitor_liquid_tag.approved.html

Added a feature for jsitor liquid
Resolves #4214

Add JSitor liquid tag

---

app/views/pages/_editor_guide_text.html.erb

I fixed some typos in the Editor Guide, corrected (maybe due to copy pasting) description mistakes in the "Glitch embed" section and improved formatting of code blocks (too many spaces, wrong indentation, additional blank lines and similar). This was bothering me quite some time now :)

improve editor guide: typos and formatting issues

---

app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/SlideContent.jsx
app/views/layouts/application.html.erb
app/views/pages/_terms_text.html.erb

This fixes some small complaints from aXe, as one of the steps in refactoring onboarding.
There are a handful of more involved a11y fixes we could make, but I pulled these into a separate PR because they should be easy to merge.

Onboarding a11y fixes

---

app/views/articles/_single_sponsor.html.erb
app/views/comments/_comment_proper.html.erb
app/views/layouts/_signup_modal.html.erb

This is a small thing that checks some boxes in the `best practices` parts of Lighthouse

Add noopener to sponsor links

---

app/views/articles/_single_sponsor.html.erb
app/views/comments/_comment_proper.html.erb
app/views/layouts/_signup_modal.html.erb

Add noopener and a couple lazy loads to be more compliant with lighthouse

---

db/migrate/20191031131016_add_created_at_index_to_users.rb

This line is necessary for `algorithm: :concurrently` to work in migrations.

Add disable_ddl_transaction to user created_at migration

---

app/controllers/follows_controller.rb
spec/requests/follows_create_spec.rb

Part of this functionality was not behaving as expected. So hot fix removed. I think this can stay out anyway.

Remove follow limit for single request

---

app/views/internal/permissions/index.html.erb

Missing closing div caused this internal view to act wacky.

Add missing closing div to internal permissions

---

app/labor/flare_tag.rb
app/views/articles/_sidebar_additional.html.erb

Remove the hacktoberfest code. Til next year!

Remove hacktoberfest from sidebar

---

spec/factories/articles.rb
spec/factories/badges.rb
spec/factories/classified_listings.rb

This PR makes tests less likely to occasionally fail due to duplications in our random library.

Add more randomness to factories

---

app/views/articles/tag_index.html.erb
app/views/stories/_narrow_nav_menu.html.erb

- [ x] Feature
Generalised the 'My Dev' feed text to use the community name variable on both /app/views/articles/tag_index.html.erb & app/views/stories/_narrow_nav_menu.html.erb
Related to generalization tag
- [ x] no documentation needed
Well it my very first commit to any public repo 💃

Generalised my dev feed text to use the community name variable 

---

app/controllers/follows_controller.rb
spec/requests/follows_create_spec.rb

After https://github.com/thepracticaldev/dev.to/pull/4647 and https://github.com/thepracticaldev/dev.to/pull/4738, I noticed how there was a bug in how the server communicates with the browser for the rate limiting
https://github.com/thepracticaldev/dev.to/issues/4640

Fix http status code for daily account follow rate limiting

---

app/services/suggester/users/sidebar.rb

add suggester sidebar class suggest to RedisRailsCache
handle #4670

add suggester sidebar class suggest to RedisRailsCache

---

app/services/analytics_service.rb

Add AnalyticsService to  RedisRailsCache
handle #4670

Add AnalyticsService to  RedisRailsCache

---

config/initializers/session_store.rb

When merging https://github.com/thepracticaldev/dev.to/pull/4789 and https://github.com/thepracticaldev/dev.to/pull/4004 we forgot to change this

Use REDIS_SESSIONS_URL and default to REDIS_URL

---

app/controllers/internal/feedback_messages_controller.rb
app/services/moderator/banish_user.rb

Fix performance, adjust the query.

Add additional conditions to internal/reports page

---

app/helpers/application_helper.rb
app/views/articles/show.html.erb
app/views/moderations/index.html.erb

Add tag_colors cache to redis
handle #4670

Add tag_colors cache to redis

---

docs/technical-overview/architecture.md
docs/technical-overview/readme.md

Update docs with more architecture info

---

app/models/tag.rb

move bufferized tags  to RedisRailsCache
handle #4670

move bufferized tags to RedisCache

---

app/lib/html_css_to_image.rb

This PR is raised to resolve https://github.com/thepracticaldev/dev.to/pull/4753#discussion_r345837599
To handle #4670 
Upon merging this we can go ahead with #4753

Write to RedisCache to avoid cache miss in add html_css_to_image

---

app/models/reaction.rb

move caching of reaction  to RedisRailsCache
handle #4670

move caching of reaction to rediscache

---

app/view_objects/articles/social_image.rb

move social_image cache  to RedisRailsCache
handle #4670

move social_image cache to Redis

---

app/javascript/article-form/articleForm.jsx

Resolved the broken layout resulting from the additional config / settings page overlapping with the preview page. I also resolved the eslint issues present and removed duplicate code.
Resolves #4764

Fix broken layout from "additional config/settings" overlap

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb

Background:
Clicking the like button on a comment triggers a backend call (/reactions) which either creates or destroys the reaction. The response result ('create' or 'destroy') either increments or decrements the DOM element corresponding to the comment like count. If the user repeatedly and rapidly clicks the like button there are a stream of asynch requests that lead to an imbalance of create vs. destroy responses. Usually this results in more destroy reponses (which decrement the DOM count 'variable') than create responses produces a negative like count. 
The reason for this imbalance *may* be cache related (I haven't deeply investigated). One possibility is the use of *destroy* rather than *destroy!* in ReactionsController#create. If the destroy call were to have no effect the …

Fixes count error from multiple clicks on comment like button (#4680)

---

app/javascript/onboarding/__tests__/Onboarding.test.jsx
docs/tests/accessibility-tests.md
docs/tests/readme.md
package.json
yarn.lock

I've spent a non-trivial amount of time learning about accessibility over the last few weeks. It's not something I've done much work around in past (neither is JavaScript testing!), but I'm planning to expand these tests and try to get some basic protection in place for regressions in accessibility as I look for opportunities to improve the experience we currently have.

Javascript automated testing and a11y doc

---

app/assets/stylesheets/preact/article-form.scss
app/javascript/article-form/articleForm.jsx
app/views/articles/_v2_form.html.erb

Series were not being passed into the form properly, but this fixes it.
Also fixed a couple minor styling issues.

Fix missing series in article edit form (v2)

---

app/javascript/onboarding/__tests__/Onboarding.test.jsx

I'm spending some time refactoring the onboarding unit tests. Some of these changes are fairly subjective (formatting, phrasing, comments, etc.), but this change has removed some duplication and made a few of the tests less brittle (while still providing the same coverage).

Onboarding test love

---

app/controllers/application_controller.rb
app/controllers/chat_channels_controller.rb
app/controllers/display_ad_events_controller.rb
app/controllers/messages_controller.rb
app/controllers/page_views_controller.rb
app/controllers/reactions_controller.rb
app/controllers/reading_list_items_controller.rb

This is a micro-optimization in some high leverage areas of the code. Fewer queries, fewer `current_user` objects getting loaded into memory.

Replace current_user.id with session_current_user_id

---

docs/backend/auth-twitter.md

Was adding Twitter auth to my local environment and thought this would be handy.

Add a link for Twitter developer access [ci skip]

---

docs/technical-overview/architecture.md

I fixed document typo. Please confirm.

Fix typo in architecture.md

---

app/labor/reading_list.rb

Remove spaces in timestamps for cache keys

Update reading list updated_at cache key timestamp

---

app/helpers/application_helper.rb
app/helpers/articles_helper.rb
app/views/articles/show.html.erb
app/views/devise/registrations/_registration_form.html.erb
app/views/layouts/_top_bar.html.erb
app/views/social_previews/article.html.erb
app/views/social_previews/comment.html.erb
app/views/social_previews/listing.html.erb
app/views/social_previews/tag.html.erb
app/views/social_previews/user.html.erb
app/views/users/_profile_header.html.erb
app/views/users/show.html.erb
spec/helpers/articles_helper_spec.rb

`inline_svg` replaced by `inline_svg_tag` as per the warning yelling at me

Replace deprecated inline_svg

---

app/models/article.rb
spec/decorators/article_decorator_spec.rb
spec/models/article_spec.rb
spec/models/shared_examples/sync_reactions_count.rb
spec/rails_helper.rb

In an effort to have more efficient tests (and hopefully ultimately faster), I went through `spec/models/article_spec.rb` and refactored it.
I read and applied some tips from [TestProf: a good doctor for slow Ruby tests](https://evilmartians.com/chronicles/testprof-a-good-doctor-for-slow-ruby-tests) (there's room for more improvements I guess but this is already a large refactoring...) and measured and tried something else and measured.
Since our models specs are our second slowest folder (after spec/requests) I started from ther and `article_spec` was at the top of the list.
This is a large refactoring because I went through each test, removed those that were either duplicated or redundant (some were literally testing Rails), added some new ones and reorganized the code in sections also …

Increase efficiency in models/article_spec.rb

---

app/views/users/_account.html.erb

This PR contains the Javascript code cleanup as suggested by @rhymes & @lightalloy. 
Based on the discussions here,
https://github.com/thepracticaldev/dev.to/pull/4480#discussion_r343698671

Cleanup JS part as suggested under users/_account.html.erb

---

app/controllers/application_controller.rb
app/controllers/application_metal_controller.rb
app/controllers/concerns/valid_request.rb
app/controllers/display_ad_events_controller.rb
app/controllers/html_variant_successes_controller.rb
app/controllers/html_variant_trials_controller.rb
spec/factories/articles.rb

Per the success of #4923, this PR moves a few more controllers to `ApplicationMetalController` to remove unnecessary dependencies/compute.
Here's the graph of adding this to `PageViewsController`

Add ApplicationMetalController to relevant controllers

---

app/controllers/social_previews_controller.rb
app/decorators/user_decorator.rb
app/views/shared/_logo_design.html.erb
app/views/social_previews/article.html.erb
app/views/social_previews/comment.html.erb
app/views/social_previews/user.html.erb

This PR mostly fixes the issue where buttons can show up as black-on-black etc.
Also updated the social preview images to have some new flourishes, rounded edges that match up with the way it looks on Twitter and incorporating tag badges into the design.

Fix black-on-black etc. buttons and update social preview cards

---

app/javascript/article-form/articleForm.jsx
app/javascript/article-form/elements/publishToggle.jsx

It looks like the error was caused by a typo in `articleForm.jsx`.
Resolves #4906

Resolve TypeError when clearing new changes in articleform

---

docker-compose.yml
docs/installation/docker.md

Add redis container to docker-compose

---

app/assets/javascripts/initializers/initializeAdditionalContentBoxes.js

This takes a timestamp-oriented cache busting key and changes it so this doesn't change as often—because I don't think it needs to change as often due to other components of this changing often enough themselves.
This should modestly lessen cold hits to this endpoint without much risk.

Modify cache rate for additional_content_boxes

---

app/lib/constants.rb

Add fosstodon to mastadon whitelist

---

db/migrate/20191203114809_add_missing_foreign_keys_tag_adjustments.rb
db/schema.rb

This is step 1 of 3 of adding missing foreign keys to table, see https://github.com/thepracticaldev/dev.to/pull/4960
This adds them to `tag_adjustments`.
**NOTE:** please read the description in https://github.com/thepracticaldev/dev.to/pull/4960 before merging this.

Add missing foreign keys to tag_adjustments

---

app/assets/stylesheets/chat.scss
app/controllers/chat_channels_controller.rb
app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
app/javascript/chat/actions.js
app/javascript/chat/chat.jsx

Ability to see chat history, by scrolling up. Very time you scroll up you 150 messages will be fetched till you reach in the end.

Feature🚀: Ability to see chat history by scrolling up

---

app/assets/stylesheets/chat.scss
app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
app/javascript/chat/chat.jsx

Change copy on jump back button in /connect

---

app/services/medium_article_retrieval_service.rb
app/views/liquids/_medium.html.erb
spec/liquid_tags/medium_tag_spec.rb
spec/services/medium_article_retrieval_service_spec.rb

Adds a publication date to medium liquid tags.
Fixes #4961

Add publication date to medium liquid tag (#4961)

---

app/views/articles/edit.html.erb
app/views/articles/new.html.erb
app/views/articles/show.html.erb
app/views/shared/_webcomponents_loader_script.html.erb
app/views/users/_org_admin.html.erb

Should add SRI support as per https://www.rubydoc.info/gems/sprockets-rails#SRI_support
I have not tested this because I can't set up the build system.
Fixes #4652

Add SRI Support

---

app/labor/cache_buster.rb
app/views/articles/_sticky_nav.html.erb
app/views/articles/show.html.erb
app/views/articles/tags/_sidebar_additional.html.erb

This PR temporarily removes some content which relies more heavily on caching while we migrate from memcached to redis.

Temporarily remove extra cache-oriented content

---

app/labor/cache_buster.rb
app/views/articles/_sticky_nav.html.erb
app/views/articles/tags/_sidebar_additional.html.erb

This is part of the process of safe migration to Redis.

Add additional content back in on sidebars and cache frequency

---

app/views/articles/show.html.erb

This adds the below-article articles back as part of the safe migration to Redis

Add under-article article boxes

---

spec/factories/badges.rb
spec/factories/podcasts.rb
spec/factories/users.rb

Following the suggestion of Factory_bot_rail's maintainer to extract image_path from factories to resolve spring related issues. More info in the link below.
https://github.com/thoughtbot/factory_bot_rails/issues/342#issuecomment-499976484
n/a

Extract image_path out of factories block

---

spec/system/articles/user_edits_an_article_spec.rb
spec/system/user/user_edits_integrations_spec.rb

I noticed a couple of pending tests, this removes those from the test sutie. (one deleted, one no longer pending). Also includes a minor test refactor.

Fix pending tests

---

app/controllers/internal/application_controller.rb
app/models/config.rb
app/models/growth.rb
app/models/mod.rb
app/models/permission.rb
app/models/tool.rb
app/models/webhook_endpoint.rb
app/models/welcome.rb
spec/factories/users.rb
spec/requests/internal/broadcasts_spec.rb
spec/requests/internal/growth_spec.rb
spec/requests/internal/mods_spec.rb
spec/requests/internal/tools_spec.rb
spec/requests/internal/welcome_spec.rb

This PR is a layup based on some of the stuff @maestromac was working on regarding authorization for individual `internal` controllers.
We decided to rely on Rolify rather than writing something bespoke (which might be more elegant), to keep things consistent.
That being said, this is arguably a hack of what Rolify intends us to do -- because Rolify isn't really intended to be used to restrict views so much as access to models. We create empty model classes without DB-backing and call `resourcify` on them to use Rolify for limiting access to their controllers.
There is a strong argument to be made, in my opinion, that many of these views should be refactored into ad-hoc reports (because they are just AR queries spit out on a page). But for the time being, this allows us to divvy up access …

Add single resource admin concept

---

.nvmrc

Made the Node version in `.nvmrc` more implicit to better support some other Node version managers (besides NVM).
https://github.com/thepracticaldev/dev.to/commit/7ed9361139d37e288a32b168b6e50d7ad74415c2

Changed `.nvmrc` to support more Node version managers

---

docs/internal/readme.md
docs/readme.md

This PR adds documentation for the changes in #5069.

Write docs on single_resource_admin workaround

---

.github/PULL_REQUEST_TEMPLATE.md

I keep needing this so I figured it was time to add it. What do you all think?

Add Optimization option to PR template Types

---

app/models/article.rb

#5063 
Removed unused indexing code.

Removed old indexing code from the User model

---

app/views/notifications/_aggregated_reactions.html.erb

This cache is not caching any new external requests so we may as well remove it as well.
https://github.com/thepracticaldev/dev.to/pull/5083

Remove Unused Aggregation Reaction cache

---

package.json

Config/*, lib/*, and Gemfile should be accounted in the pre-commit hook
n/a
n/a

Expand Lint-staged's ruby coverage

---

app/assets/stylesheets/moderators.scss
app/views/moderations/mod.html.erb

Follow up on #5017 to get the styling right.
Also removed some hacks to make this area of the code _a bit cleaner_.

Cosmetic adjustment + code cleanup for article/mod page

---

db/seeds.rb

I was messing around with some of these views and this data seemed like it'd be nice to have seeded.

Add abuse report seed data

---

app/javascript/shared/components/tags.jsx

Use `Array.includes()` to check for existence.
N/A
N/A
Nope

refactor: minor code refactoring

---

docs/backend/roles.md

This fixes a "Page Not Found!" error on https://docs.dev.to/backend/roles/ for the links:
- Another common requirement is changing to the administrative role, and an example of this is found [on the admin page].
- Further Reading # 3. Admin
N/A
N/A

Fix Backend Guide > Roles admin links [ci skip]

---

docs/tests/acceptance-tests.md
docs/tests/readme.md
docs/tests/regression-tests.md
docs/tests/skip-ci.md
docs/tests/unit-functional-tests.md

This change expands and adds to our testing docs :smile:

Expand the testing docs

---

app/views/service_worker/index.js.erb

This line unnecessarily sends stuff to offline

Remove unnecessary catch

---

app/controllers/concerns/valid_request.rb

Currently our app's `https` and `http` do not match up properly due to our legacy hack with not fully supporting `force_ssl`. I hope we can resolve that in due time, but for now this will help resolve some bugs we are encountering.

Monkeypatch method to ensure https redirect

---

app/views/feedback_messages/index.html.erb

This fixes the issue where this page is without styling all of a sudden due to the removal of the catch-all styling fallback. This page slipped through the cracks.
Fixes #5143

Fix feedback_messages styling

---

app/controllers/shell_controller.rb
spec/requests/shells_spec.rb

This feature adds edge caching to the shell. I 100% thought I did this as a part of #5020 but I guess I forgot to.
Everything works fine now, but we are unnecessarily serving these requests from origin.

Add edge caching to shell

---

app/policies/user_policy.rb

Refactoring app/policies/user_policy.rb

---

app/javascript/chat/chat.jsx
app/javascript/searchableItemList/searchableItemList.js
app/javascript/src/components/ItemList/ItemListItem.jsx
app/models/reaction.rb
app/views/chat_channels/index.html.erb
app/views/shell/_top.html.erb

Fixed some issues that _may_ have been caused by serviceworker change or other recent changes.
Also fixed some other small details that had been bugging me while I was at it.

Frontend bug fixes

---

app/controllers/internal/organizations_controller.rb
app/views/internal/organizations/_activity.html.erb
app/views/internal/organizations/index.html.erb
app/views/internal/organizations/show.html.erb
app/views/internal/shared/_navbar.html.erb
config/routes.rb
spec/requests/internal/organizations_spec.rb
spec/system/internal/admin_manages_organizations_spec.rb

This adds only an index and show action for the internal/organizations
page. Eventually we'll flesh this out with features to automate the more
mechanical org management tasks.
https://github.com/thepracticaldev/dev.to/issues/5011

Add view for managing organizations

---

.erb-lint.yml

This was blowing up and making it imposible for me to commit stuff
without bypassing the hooks.

Fix erb-lint config

---

app/liquid_tags/gitpitch_tag.rb
app/views/liquids/_gitpitch.html.erb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/gitpitch_tag_spec.rb

Resolves https://github.com/thepracticaldev/dev.to/issues/4761

Add GitPitchTag resolves #4761

---

lib/tasks/fetch.rake

This code was allegedly simple, but it did not work as expected. This should fix it.

Fix tag badge task logic

---

app/assets/stylesheets/moderators.scss
app/controllers/moderations_controller.rb
app/models/article.rb
app/views/articles/tags/_sidebar.html.erb
app/views/moderations/index.html.erb
config/routes.rb
db/migrate/20191223202251_add_nth_published.rb
db/schema.rb
spec/models/article_spec.rb
spec/requests/moderations_spec.rb

The `/mod` page has not been serving great use of late. It is very slow and its use is not clear.
And while we plan to regroup and give this new focus in 2020 with better collab with mods, I felt inspired to give it a quick makeover to serve us better now.

Redo /mod for performance and usability

---

app/views/service_worker/index.js.erb

Previously shell_top was being checked twice - now we check top + bottom :)

Fix check for whether shell has changed

---

app/models/article.rb
spec/models/article_spec.rb

Logic and test were off. This should fix it.

Fix off-by-one in nth_published_by_author

---

app/models/article.rb
spec/models/article_spec.rb

Fix off by one for nth_published_by_author

---

app/views/moderations/index.html.erb
spec/requests/moderations_spec.rb

Final fixes to /mod

---

config/initializers/honeybadger.rb
spec/initializers/honeybadger_spec.rb

As fun as it is to get 100+ of these when our servers slow down, I think it would be easier to sift through the noise and see surrounding issues if we combined them all into a single error. What do you all think?
YES this class is about ready for a refactor but I'm not quite there yet ;)

Group Honeybadger Rack::Timeout::RequestTimeoutExceptions

---

.vscode/settings.json

We shouldn't force vscode activebar and statusbar colors in our config.

Remove code related to vscode color customization

---

app/views/badges/index.html.erb

Raised in issue #5040
Added title attribute in Badges' image tag for the tooltip

Added Tooltip for Badges in index page (#5040)

---

app/views/shell/_top.html.erb

#4942  What type of PR is this? (check all applicable)
Usescape / Decode HTML codes in page title tag using `CGI.unescapeHTML()`
Closes #5226

#5226 Unescape page title.

---

Gemfile
Gemfile.lock

Three gems didn't have info about what they are and one of them didn't have any version information

Add missing info for gems in Gemfile

---

app/jobs/articles/detect_human_language_job.rb
app/jobs/articles/update_main_image_background_hex_job.rb
app/jobs/classified_listings/bust_cache_job.rb
app/jobs/comments/calculate_score_job.rb
app/jobs/comments/create_first_reaction_job.rb
app/jobs/comments/create_id_code_job.rb
app/jobs/comments/send_email_notification_job.rb
app/jobs/follows/create_chat_channel_job.rb
app/jobs/follows/send_email_notification_job.rb
spec/jobs/articles/bust_cache_job_spec.rb
spec/jobs/articles/detect_human_language_job_spec.rb
spec/jobs/articles/score_calc_job_spec.rb
spec/jobs/articles/update_analytics_job_spec.rb
spec/jobs/articles/update_main_image_background_hex_job_spec.rb
spec/jobs/badge_achievements/send_email_notification_job_spec.rb
spec/jobs/chat_channels/index_job_spec.rb
spec/jobs/classified_listings/bust_cache_job_spec.rb
spec/jobs/comments/bust_cache_job_spec.rb
spec/jobs/comments/calculate_score_job_spec.rb
spec/jobs/comments/create_first_reaction_job_spec.rb
spec/jobs/comments/create_id_code_job_spec.rb
spec/jobs/comments/send_email_notification_job_spec.rb
spec/jobs/comments/touch_user_job_spec.rb
spec/jobs/events/bust_cache_job_spec.rb
spec/jobs/follows/create_chat_channel_job_spec.rb
spec/jobs/follows/send_email_notification_job_spec.rb
spec/jobs/follows/touch_follower_job_spec.rb

I started some optimizations for the `spec/jobs` folder, but just remembered we're going to switch to Sidekiq workers, so i'm submitting this (it was supposed to be a PR in the back burner) to avoid conflicts in the future.
I think I've saved 2 or 3 seconds for now
Continuation after https://github.com/thepracticaldev/dev.to/pull/5016

Optimize (some) jobs specs

---

.github/CODEOWNERS

Add jobs and workers to SRE so I am tagged in all new rollover PRs
#5305

Update CODEOWNERS with jobs and worker files for SRE

---

config/initializers/cache_logger.rb
config/initializers/silence_cache_log.rb

Currently we always disable/silence cache logs, but they can be very useful in development.
This PR enables them only in development and when caching is explicitly enabled.
Example of cache logs:
```shell
Cache read: cached_user_reactions-11-2020-01-02 10:12:49 UTC ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>24 hours, :race_condition_ttl=>nil})
Cache fetch_hit: cached_user_reactions-11-2020-01-02 10:12:49 UTC ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>24 hours, :race_condition_ttl=>nil})
Cache read: views/shell/_top:9f793d4c81018bf45f90a533f1fa8810/application-top-bar--true ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>100 hours, :race_condition_ttl=>nil})
Cache read: …
```

Enable cache logging in development if requested

---

app/jobs/follows/send_email_notification_job.rb
app/mailers/notify_mailer.rb
app/models/follow.rb
app/models/user.rb
app/workers/follows/send_email_notification_worker.rb
spec/models/follow_spec.rb
spec/models/user_spec.rb
spec/workers/follows/send_email_notification_worker_spec.rb

Adds `Follows::SendEmailNotificationWorker` as Sidekiq based replacement for the ActiveJob based `Follows::SendEmailNotificationJob`. After deploy, I shall create another PR to remove the deprecated ActiveJob files.
/
🎉 🙂 happy to make my first real contribution to open source!

Refactors ActiveJob to SidekiqWorker: Follows::SendEmailNotificationWorker

---

docs/design/branding.md

Small typo in a filename referenced in the branding documentation.
N/A
N/A

Fixed a typo in a filename in docs.

---

spec/support/sidekiq_test_helpers.rb

Jobs in Sidekiq testing mode are stored both per queue or per worker, this surfaces both so that people writing tests can access them with the helpers

Sidekiq test helpers: retrieve jobs by worker

---

app/decorators/user_decorator.rb

Refactor method in user_decorator.rb

---

app/views/internal/feedback_messages/_feedback_message.html.erb

The UI refactor broke this query selector.

Fix internal/reports email form

---

app/views/internal/articles/_article_script.html.erb
app/views/internal/articles/index.html.erb

Suggested Tweets got overlooked in my last pass. This PR fixes that and adds a small UI flag that Michael requested.

Fix suggested tweets UI

---

.github/PULL_REQUEST_TEMPLATE.md

~I feel like including a checklist will be a reminder for contributors to~
~be mindful of steps that expedite code review and improve code quality~
~over time when making contributions.~
~It also provides a helpful link to some docs that contributors should be~
~reading before submitting PRs.~
~I'm definitely looking for opinions here (DEV employees and open source contributors). I specifically~ ~want to encourage contributors to think about adding tests and good commit messages. I think we~ ~don't need to identify which piece of documentation was updated in the PR as the diff should make~
~that fairly obvious.~
~I'm also hoping this serves as a reminder for people to take a look at CONTRIBUTING.md before~
~submitting their PR, hopefully making PR review a smoother process for reviewers …

Add a pull request checklist to the PR template

---

app/models/notification.rb
app/workers/notifications/new_reaction_worker.rb
spec/jobs/notifications/new_reaction_job_spec.rb
spec/models/notification_spec.rb
spec/workers/notifications/new_reaction_worker_spec.rb

This change creates a Sidekiq Worker equivalent of Notifications::NewReactionJob
#5305 
PS: This is my second project for Open Source Contribution. And the first project which is on production. Excited :)

Migrate new reaction job 5305

---

app/helpers/application_helper.rb

this fixes image loading on stand alone platforms
Some static images weren't rendering correctly due to hard coded cloudinary path

Updated application_helper.rb with Cloudinary env variable

---

app/views/internal/feedback_messages/index.html.erb

Quick fix for a bug I accidentally introduced in #5392

Remove call to published method on non-articles

---

app/models/user.rb
app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb
spec/models/user_spec.rb
spec/system/internal/admin_awards_badges_spec.rb
spec/workers/users/subscribe_to_mailchimp_newsletter_worker_spec.rb

- Created new SubscribeToMailchimpNewsletterWorker to replace SubscribeToMailchimpNewsletterJob
- Added to `low_priority` queue
- Changed references to call new worker
- Updated tests
I will create a separate PR for removing the old SubscribeToMailchimpNewsletterJob
#5305

Migrate subscribe to mailchimp newsletter job to sidekiq worker

---

app/controllers/admin/users_controller.rb

A little fix to remove an unused password verification, as [requested](https://github.com/thepracticaldev/dev.to/pull/5108#pullrequestreview-336178768)

Remove password verification in admin user controller

---

app/views/service_worker/index.js.erb

Some oauth paths break with serviceworkers, this fixes it.
Closes #5440

Add oauth to list of skipped paths for service workers

---

db/seeds.rb

I wasn't able to finish the setup. This [link](https://stackoverflow.com/questions/42575405/seeding-db-with-users-using-devise-fails-activerecordrecordinvalid-validatio) helped me to understand what was going on.
Closes #5450

Fix hex color in seeds

---

.github/CODEOWNERS

Just including myself for directories specifically pertaining to
internal and to the docs directory.

Add @jacobherrington to CODEOWNERS

---

app/controllers/users_controller.rb
app/views/users/_account.html.erb
app/views/users/confirm_destroy.html.erb
spec/requests/user/user_destroy_spec.rb

- ask users to provide email before deleting an account if they don't have it
- I added additional checks to the controller just in case.
https://github.com/thepracticaldev/tech-private/issues/343

Fix a bug when user tries to delete an account while not having an email

---

app/controllers/oauth/tokens_controller.rb
app/workers/webhook/destroy_worker.rb
spec/requests/oauth/tokens_spec.rb
spec/workers/webhook/destroy_worker_spec.rb

Change DestroyJob to DestroyWorker and move to sidekiq

---

app/models/mention.rb
app/workers/mentions/create_all_worker.rb
spec/models/mention_spec.rb
spec/workers/mentions/create_all_worker_spec.rb

Added a new worker to create all mentions. Once the PR gets approved and merged I will open another one to remove the previous delayed job.
#5305

Add mentions create all worker

---

.github/CODEOWNERS

Add myself to codeowners for internal and moderation pages. :)
May add more later, like liquid_tags.

Add self to codeowners

---

spec/models/organization_spec.rb
spec/models/user_spec.rb
spec/workers/comments/calculate_score_worker_spec.rb
spec/workers/comments/send_email_notification_worker_spec.rb
spec/workers/notifications/new_reaction_worker_spec.rb
spec/workers/podcast_episodes/bust_cache_worker_spec.rb

Fixed rubocop issues

---

app/assets/stylesheets/top-bar.scss

Ben changed .top-bar height but do not changed .menubg top position

Currect .menubg top position

---

spec/jobs/comments/bust_cache_job_spec.rb

Serendipity wasn't in our favor this time

Fix spec that broke after we merged #4744

---

app/models/notification.rb
app/workers/notifications/remove_all_worker.rb
spec/models/comment_spec.rb
spec/models/notification_spec.rb
spec/requests/articles/articles_destroy_spec.rb
spec/services/articles/destroyer_spec.rb
spec/workers/notifications/remove_all_worker_spec.rb

Change RemoveAllJob to RemoveAllWorker and move to sidekiq

---

app/models/notification.rb
app/workers/notifications/milestone_worker.rb
spec/workers/notifications/milestone_worker_spec.rb

Change MilestoneJob to MilestoneWorker and move to sidekiq (Watch DJs when Deployed!)

---

README.md

Adding myself to core team members

Add Alex Smith to core team members [ci skip]

---

app/assets/stylesheets/user-profile-header.scss

Changed `overflow-y: scroll` to `overflow-y: auto`
See issue https://github.com/thepracticaldev/dev.to/issues/5531.
| Before | After |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/14293805/72461780-fb2cda00-37cf-11ea-9061-6bb25eb0107b.png)     | ![image](https://user-images.githubusercontent.com/14293805/72461864-244d6a80-37d0-11ea-9bad-5b677e987cea.png)     |

Changed user-metadata-details to overflow-y: auto

---

README.md

Added myself to the core team in the README as requested by @jessleenyc 
n/a

Add myself to core team in README

---

app/models/comment.rb
app/workers/comments/bust_cache_worker.rb
spec/models/comment_spec.rb
spec/workers/comments/bust_cache_worker_spec.rb

Following the pattern to create a sidekiq version of delayed job and
updating the reference to the delayed job to use the sidekiq worker.
#5305

Migrate delayed job to bust comment cache

---

app/javascript/.eslintrc.js
app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
app/javascript/chat/userDetails.jsx

This pr adds some refactors to `userDetails.jsx` and fix all eslint errors.
#2470

Refactor userDetails

---

docs/technical-overview/architecture.md

Added some more info about core app models/concepts.

Add more info to architecture.md doc

---

app/labor/badge_rewarder.rb
spec/labor/badge_rewarder_spec.rb

- cached `badge_id` in local variables in `BadgeRewarder` to avoid unnecessary queries.
- added a couple of tests for `BadgeRewarder.award_badges`

Improved BadgeRewarder

---

config/initializers/strong_migrations.rb

This is only for development and prod so we should only set it up in those environments.

Only setup StrongMigrations in dev or test

---

docs/internal/internal-search.md
docs/internal/readme.md
docs/technical-overview/stack.md

This change adds a small guide for Ransack to the docs on Internal.

Add guide for Ransack to docs

---

app/models/notification.rb
app/services/notifications/new_follower/send.rb
app/workers/notifications/new_follower_worker.rb
spec/models/notification_spec.rb
spec/services/notifications/new_follower/send_spec.rb
spec/workers/notifications/new_follower_worker_spec.rb

This creates a new `NewFollowerWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
#5305

Create new NewFollowerWorker and start sending jobs to it

---

app/controllers/internal/feedback_messages_controller.rb

Bullet suggested doing some eager loading on these tables. Makes sense to me. :slightly_smiling_face:

Internal Reports: Add eager loading based on Bullet

---

app/javascript/onboarding/components/ClosingSlide.jsx

Fixing sanitization issue in onboarding.

Add onboarding sanitization

---

app/javascript/analytics/dashboard.js

https://dev.to/ben/we-reduced-our-vendorjs-from-210kb-to-16kb-in-about-five-minutes-of-work-and-ten-lines-of-code-1ole

Move Chart.js to dynamic import

---

app/models/follow.rb
app/workers/follows/create_chat_channel_worker.rb
spec/models/follow_spec.rb
spec/workers/follows/create_chat_channel_worker_spec.rb

Moved the follows create chat Delayed Job to a Sidekiq worker and added the related tests. I also removed the old job and its tests.
#5305

Add create chat channel worker

---

app/models/mention.rb
app/workers/mentions/send_email_notification_worker.rb
spec/workers/mentions/send_email_notification_worker_spec.rb

Added a new worker to send mentions email notifications. Once the PR gets approved and merged I will open another one to remove the previous delayed job.
#5305

Add mentions send email notifications worker

---

app/controllers/api/v0/reactions_controller.rb
app/workers/reactions/create_worker.rb
spec/workers/reactions/create_worker_spec.rb

Change CreateJob to CreateWorker and move to sidekiq

---

app/models/notification.rb
app/services/notifications/update.rb
spec/services/notifications/update_spec.rb

Following a note on #5415 - https://github.com/thepracticaldev/dev.to/pull/5415#discussion_r364751316 - I replaced a check for an id with a check for the actual object in `Notifications::Update`.
I also rewrote the specs because they didn't seem to test all scenarios

Optimize Notifications::Update and it specs

---

app/lib/constants.rb

Adds 4estate.media to whitelist. 4estate.media is an instance controlled by myself and is home to several practising journalists/coders.
* Issue #1267
* https://dev.to/nickytonline/comment/7bg0

Adds 4estate.media to Mastodon instance whitelist

---

README.md

[ci skip] Added myself to the core team.

---

README.md

Take 2 at adding myself (@joshpuetz) to the dev.to README/core team list as per the onboarding list (the [first try](https://github.com/thepracticaldev/dev.to/pull/5627) didn't work out so well as I didn't have my local git email set, and ClaAssistantio didn't like it)

Add joshpuetz to core contributors [ci skip]

---

app/models/article.rb
app/models/comment.rb
app/models/page_view.rb
app/models/user.rb
app/workers/search/index_worker.rb
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/models/page_view_spec.rb
spec/models/user_spec.rb
spec/workers/search/index_worker_spec.rb

This creates a new `IndexWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
#5305 
[Pivotal](https://www.pivotaltracker.com/n/projects/2430255/stories/170808428)

Move Search::IndexJob to Sidekiq

---

README.md

Add Vaidehi to core contributors [ci-skip]

---

app/controllers/classified_listings_controller.rb
spec/requests/classified_listings_spec.rb

Return 404 NotFound error if ClassifiedListing is not found during delete
Fixes #5626 
Honeybadger: https://app.honeybadger.io/fault/66984/b75eb6aca94657e7a1f48dcf5b6dce21

Return 404 NotFound error if ClassifiedListing is not found during delete

---

app/helpers/articles_helper.rb

Very occasionally `processed_html` is `nil` and this throws a runtime error.

Add guard clause for presence of processed_html

---

docs/getting-started/start-app.md

When starting the app for the first time, it's possible to run into some issues while trying to run `bin/setup`.
For example, when I started the app, I got an (unhelpful) error when running `bin/setup` and ended up figuring out the issue (needing to `yarn install`) by running the contents of the `Procfile.dev` file directly.
We should help point folks to this file so that they can run a command that gives them a more helpful error message, which should hopefully let them get the app up and running with any problems! :)

Add note to help debug `bin/setup` issues.

---

package.json

This error in the package.json has been bugging me for a while. 😉
Just some cleanup.

Fix package.json name.

---

docs/backend/algolia.md

Fixed a quick typo in the Algolia docs.

Fix typo in Algolia docs [ci skip]

---

app/models/article.rb
app/models/comment.rb
app/models/page_view.rb
app/models/user.rb
app/workers/search/remove_from_index_worker.rb
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/models/page_view_spec.rb
spec/workers/search/remove_from_index_worker_spec.rb

This creates a new `RemoveFromIndexWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305 
- [Pivotal](https://www.pivotaltracker.com/story/show/170808428)

Move Search::RemoveFromIndexJob to Sidekiq

---

.travis.yml

Still seeing the directory not found error on Travis even when the directory is created so after consulting the local resident Travis expert I am going to try this path.

Travis Path Update Try 3

---

app/models/reaction.rb
app/workers/reactions/bust_homepage_cache_worker.rb
spec/models/reaction_spec.rb
spec/workers/reactions/bust_homepage_cache_worker_spec.rb

Change BustHomepageCacheJob to BustHomepageCacheWorker and move to sidekiq

---

config/routes.rb

Setting the session variables alone did not do the trick so I am also adding the Rack block of code from [this user's fix](https://github.com/mperham/sidekiq/issues/1289#issuecomment-415714146) to see if that closes the loop and does it. Everything still works in development. 
#5305 
Pivotal: https://www.pivotaltracker.com/story/show/170820884

Whitelist dev.to for Rack when working with Sidekiq UI

---

app/controllers/users_controller.rb
app/workers/export_content_worker.rb
spec/requests/user/user_settings_spec.rb
spec/workers/export_content_worker_spec.rb

This creates a new `ExportContentWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305

Move ExportContentJob to Sidekiq

---

docs/frontend/instant-click.md
docs/frontend/linting-formatting.md
docs/frontend/readme.md
docs/frontend/styles.md

Some updates to the frontend documentation based on comments in #2507 as well as from my [post on DEV](https://dev.to/nickytonline/dev-to-s-frontend-a-brain-dump-in-one-act-7mg).
#2507

update frontend docs

---

app/controllers/users_controller.rb
app/workers/rss_reader_fetch_user_worker.rb
spec/workers/rss_reader_fetch_user_worker_spec.rb

This creates a new `RssReaderFetchUserWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305

Move RssReaderFetchUserJob to Sidekiq

---

.github/CODEOWNERS

This way Andy and I will both receive notications. Andy was taking
priority over me on some of these files.

Update codeowners for Team snackCase

---

docs/frontend/styles.md

There was a typo that precluded the markdown link to work

Update docs/frontend/styles.md [skip ci]

---

.travis.yml

Y'all merged #5621 too fast, I didn't have time to add a comment to `.travis.yml` as requested by @vaidehijoshi.

Add documentation for dummy variables in .travis.yml

---

app/controllers/comments_controller.rb

Since this specific `rescue` + `raise` instance already [confused at least 2 people](https://github.com/thepracticaldev/dev.to/pull/5728/files#r371326471), I figured a comment won't hurt.

Add comment explaing rescue + reraise in CommentsController

---

docs/contributing.md

We never explicitly say that the deploy preview link only is applicable to docs changes, but we probably should! (I definitely clicked on the link thinking it was for the whole app 🙊)

Add a note to clarify deploy preview link

---

README.md

Add name to Core Team list in README

---

README.md

Adding Ridhwana as a core team contributor

chore: add a core team member

---

app/observers/reaction_observer.rb

Fix typo in ReactionObserver

---

app/views/internal/users/edit.html.erb

This change closes #5839. I worked on it with a friend who is interested in learning web development.
#5839 
(Added whitespace, it's kind of hard to tell :grimacing:)

Add whitespace to internal users edit page

---

app/javascript/sidebar-widget/sidebarUser.jsx
app/javascript/src/components/common-prop-types/default-children-prop-types.js
app/javascript/src/components/common-prop-types/index.js
app/javascript/src/components/common-prop-types/user-prop-types.js

Just doing a bit of cleanup in regards to common prop types. I'll be adding some more common prop types in another PR for work related to the homepage.

Some Proptypes cleanup

---

docs/backend/configuration.md
docs/backend/readme.md

Added some documentation around ENVied and `SiteConfig`, the last out standing to do item in #5384 .
Closes #5384

Add documentation for ENVied & SiteConfig

---

app/models/article.rb
app/workers/articles/score_calc_worker.rb
spec/jobs/reactions/update_reactable_job_spec.rb
spec/models/article_destroy_spec.rb
spec/models/article_spec.rb
spec/models/reaction_spec.rb
spec/workers/articles/score_calc_worker_spec.rb

This creates a new `Articles::ScoreCalcWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305

Move Articles::ScoreCalcJob to Sidekiq

---

app/models/notification.rb
app/workers/notifications/tag_adjustment_notification_worker.rb
spec/services/notifications/tag_adjustment_notification/send_spec.rb
spec/services/tag_adjustment_creation_service_spec.rb
spec/workers/notifications/tag_adjustment_notification_worker_spec.rb

This creates a new `Notifications::TagAdjustmentNotificationWorker` (spec included) and starts sending jobs to it. Once this is merged and deployed, I will open a second PR to remove the old job code and spec.
- #5305

Move Notifications::TagAdjustmentNotificationJob to Sidekiq

---

app/jobs/html_variant_trial_create_job.rb
spec/jobs/html_variant_trial_create_job_spec.rb

Now that #5901 is merged, this is removing the old job.
- #5305 
- #5901

Remove HtmlVariantTrialCreateJob & spec

---

README.md

Adding myself as a core contributor 😇
Onbarding task
First PR even if it's a one line change to the README

Adds core team member

---

docs/frontend/debugging.md

Some documentation updates for debugging Preact components after discussing it on Slack today.

Preact/React developer tools documentation.

---

docs/frontend/preact.md

Adds documentation for PropTypes and our Common PropTypes.
#5882

Created documenation for Common PropTypes.

---

app/javascript/src/components/common-prop-types/index.js
app/javascript/src/components/common-prop-types/tag-prop-types.js

This adds to the set of common prop types. Now if you need to create the prop types for a tag, simply import them from the common types, e.g.
```jsx
import { h } from 'preact';
import PropTypes from 'prop-types';
import { tagPropTypes } from '../../../components/common-prop-types';
const SomeComponentUsingTags = ({ tags = [] }) => (
<ul>
{tags.map(tag => (
<li key={tag.id}>{tag.name}</li>
))}
</ul>
);
SomeComponentUsingTags.displayName = 'SomeComponentUsingTags';
SomeComponentUsingTags.propTypes = {
tags: PropTypes.arrayOf(tagPropTypes).isRequired,
};
```
or if a component is using just one tag
```jsx
import { h } from 'preact';
import { tagPropTypes } from '../../../components/common-prop-types';
const SomeComponentUsingOneTag = ({ tag }) => <li key={tag.id}>{tag.name}</li>; …
```

Added tag prop types to common prop types

---

app/workers/metrics/record_db_table_counts_worker.rb

Added Notification to the list of tables we are tracking in Datadog

Log Notification db table size

---

docs/internal/internal-user-interface.md
docs/internal/readme.md

Adds some docs for the internal UI. Mentions Stimulus and Bootstrap. :)

Add an internal user interface guide

---

docs/installation/mac.md

Rework the Installing DEV example to use an SSH clone rather than an HTTPS clone.

Adjust cloning example to use SSH rather than HTTPS

---

app/assets/javascripts/utilities/userData.js

Just some cleanup on the `userData()` function I did while working on the homepage makeover.

Refactored userData while working on hompage makeover.

---

app/views/users/_account.html.erb
app/views/users/confirm_destroy.html.erb

This updates the ghost account deletion messaging a bit and leaves less room for confusion.

Use simpler messaging for ghost account deletion

---

app/views/internal/articles/_individual_article.html.erb

When adding articles to Buffer via `/internal/articles` there was some extra whitespace at the end. This PR takes care of this.
Closes #5830
**Before**
**After**

Remove extra whitespace from text inputs in Buffer share

---

app/javascript/onboarding/components/BioForm.jsx
app/javascript/onboarding/components/ClosingSlide.jsx
app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/utilities.js

Creates a function in app/javascript/onboarding to share the logic between components, avoiding
repetitive blocks.
See #3739

Onboarding JS: refactor function out of repetitive blocks

---

docs/backend/algolia.md

@joshpuetz pointed out that two weeks after doing the Algolia set up in our documentation search will break because the trial period ends.
I think including it in the set up instructions will eliminate some of the issues that might pop up here.

Include instructions to set Algolia plan

---

docs/getting-started/db.md

After a discussion on Slack today about how to increase seed data, as discussed, I've created a bit of documentation for it.

Updated DB Prep Documentation with Seed Data Section

---

app/controllers/api/v0/reactions_controller.rb
spec/requests/api/v0/reactions_spec.rb

After the conversation - https://github.com/thepracticaldev/dev.to/pull/5805#discussion_r372455193 - I had with @mstruve I set out to fix the check for `article.organization_id`, I then realized we should have more tests for and there were opportunities to optimize :D

Refactor API Reactions controller and add specs

---

app/models/page.rb
app/views/internal/pages/_form.html.erb

Added `template` field to `/internal/pages` form. We'll need it for easier set up landing pages for the campaigns.
#5704

Added template select to the pages admin form

---

config/application.rb

Updating the `queue_adapter` to Sidekiq as part of 🔪 `delayed_job`
- #5305 
- [Project card](https://github.com/thepracticaldev/dev.to/projects/6#card-32289408)

Update queue_adapter to Sidekiq

---

bin/setup

Since Foreman is no longer part of our Gemfile but still play parts of our setup, I've added it as part of the `bin/setup` script
n/a
n/a

Add foreman to setup script

---

.gitignore
Dockerfile
docker-compose.yml
docs/installation/docker.md

We recently introduced ES to our code base but haven't updated our Docker workflow accordingly yet. 
Discussed in Slack with @mstruve 
NOTE: this needs #5976 to be merged first in order to work correctly. I decided to split it into 2 PRs in case ES needs more work, so we can at least merge the fix first.

Add ElasticSearch to Docker Compose

---

.github/CODEOWNERS

Now that we have people organized in teams we're reviewing the `CODEOWNERS` file to structure better who's going to be automatically notified based on which PRs contributors or other team members open.
Further information: 
- [About code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)
- [Introducing code owners](https://github.blog/2017-07-06-introducing-code-owners/)

Assign teams to files and directories

---

app/controllers/moderations_controller.rb
spec/requests/moderations_spec.rb

Return a 404 not found error if moderatable is not found rather than trying and failing to continue to load necessary models.
#5791

Return a 404 not found error if moderatable is not found

---

config/initializers/doorkeeper.rb

I've updated the `config/initializers/doorkeeper.rb` to expose its new features. They are all disabled by default, as generated by its generator.
It's a good idea to keep auto generated initializers refreshed from time to time, so we know what's new in the parent gem
- https://github.com/thepracticaldev/dev.to/pull/5994
- https://github.com/thepracticaldev/dev.to/pull/5854

Update doorkeeper initializer with new (disabled) features

---

app/views/internal/badges/index.html.erb
config/environments/development.rb
docker-compose.yml

When adding ES support to our Docker Compose setup, I noticed lots of little things that could be improved, so I decided to bundle them up  in this PR:
1. Add `REDIS_URL` to `web` container
2. Add Redis as dependency to the `jobs` container
3. Make BetterErrors and web console work within Docker (you'll see something like `INFO -- : Whitelisting 172.26.0.1 for BetterErrors and Web Console` in the logs when starting with `docker-compose up`)

Docker improvements

---

app/models/broadcast.rb
app/services/broadcasts/welcome_notification/generator.rb
app/services/notifications/welcome_notification/send.rb
config/environments/development.rb
db/seeds.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb
spec/services/notifications/welcome_notification/send_spec.rb

This PR is all cleanup and setup for #team-delightful's work on welcome notifications. I was debating keeping these changes on a branch that @juliannatetreault could work on as well, but I decided to just create a PR with these changes for a few reasons:
1. smaller PRs with isolated changes are easier to review rather than big ones (if @juliannatetreault commits to this branch instead of me making a PR, we could end up with a really large PR for this feature)
2. I prefer shipping frequently and often, so even though this PR is just clean up and set up, since the file isn't being used but is a requirement for continuing work on this feature, I think it makes sense as its own PR.
3. This will allow @juliannatetreault to make PRs directly into `master`, rather than committing her changes to …

Add Broadcast seeds + generator service to set up for welcome notifications

---

package.json

I have the VS Code prettier plugin installed and it runs on files whenever I save them including *.scss files. This is great for those that use VS Code and have the prettier plugin installed, but for everyone else, let's just make it a precommit task. We use prettier for several other file formats, so might as well let the robots take care of SASS as well.
I will run prettier on all our *.scss files, but in another PR as we have a lot of work happening in CSS land at the moment.

Configured husky/lint-staged for *.scss files.

---

docs/installation/docker.md

Add a note about `rails data_updates:run` to the Docker section of our documentation.
#6094

Add rails data_updates:run to Docker documentation

---

app/services/users/delete_comments.rb
app/views/notifications/_notifications_list.html.erb
spec/services/users/delete_comments_spec.rb

Delete notifications before comments are deleted and log w/ Honeybadger

---

lib/data_update_scripts/20200217131245_re_index_existing_articles_with_approved.rb
spec/lib/data_update_scripts/re_index_existing_articles_spec.rb

This uses the [Data Update Scripts](https://docs.dev.to/backend/data-update-scripts/) to re-index the existing articles with the approved attribute.
This PR ties into [#6032](https://github.com/thepracticaldev/dev.to/pull/6032) where I've added the approved attribute.
This PR ties into [#6032](https://github.com/thepracticaldev/dev.to/pull/6032) where I've added the approved attribute.
[Issue #372](https://github.com/thepracticaldev/tech-private/issues/372)

Re-index existing articles

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
docs/getting-started/pull-request.md
docs/installation/linux.md

I reviewed bot the `README` and the contributing guide to bring them up to date and add some useful info.

Update README and contributing guide

---

app/javascript/src/components/common-prop-types/article-prop-types.js
app/javascript/src/components/common-prop-types/index.js
app/javascript/src/components/common-prop-types/organization-prop-type.js

Just more feature work related to the homepage makeover. The prop types are for development use only and do not affect any production code.

Updates/adds to prop-types for homepage feed makeover.

---

Gemfile
Gemfile.lock
app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/articles_controller.rb
app/controllers/api/v0/podcast_episodes_controller.rb
app/controllers/api/v0/videos_controller.rb
config/application.rb
docs/api_v0.yml
spec/requests/api/v0/articles_spec.rb

This PR enables CORS **only** on public API endpoints that require no authentication.
[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) aka Cross Origin Resource Sharing enables browsers (and thus JS running on the frontend) to share resources on a different origin. This allows frontend to query our API without incurring in the infamous CORS error in the console.
We have been having some known CORS issues, https://github.com/thepracticaldev/dev.to/issues/4195 and https://github.com/thepracticaldev/dev.to/issues/5877 and this is an initial PR to address at least #4195 
I purposefully left out unauthenticated endpoints because I want to dig deeper in the security implications (in addition to the fact that it'd encourage people to build frontends that might leak DEV API keys). …

Enable CORS on public API endpoints

---

app/models/chat_channel_membership.rb
app/services/search/chat_channel_membership.rb
app/services/search/cluster.rb
config/elasticsearch/mappings/chat_channel_memberships.json
spec/services/search/chat_channel_membership_spec.rb

Set up ChatChannelMembership Index in Elasticsearch.
https://github.com/thepracticaldev/dev.to/projects/6#card-32955421
watch the specs blowup after using that gif 😂

Setup ChatChannelMembership Index

---

config/webpack/environment.js
config/webpack/loaders/erb.js
package.json
yarn.lock

Now webpacker can support processing *.js.erb, *.jsx.erb templates. These files were automatically updated by running `bundle exec rails webpacker:install:erb` which comes from the [official webpacker documentation](https://github.com/rails/webpacker#erb).

Enabled ERB support for webpacker

---

app/models/article.rb
spec/models/article_spec.rb

issue #5808
I'm not sure if the message error is wrong or is correct. Would you tell me? please
This adds a canonical URL without spaces validation and returns a message error
"canonical_url: must has not spaces"

Prevent save invalid canonical url 

---

app/assets/stylesheets/top-bar.scss

Logo is slightly off for narrow screens

Fix logo link placement

---

.gitpod.dockerfile
.gitpod.yml

Elasticsearch is currently missing from our GitPod setup, this PR adds it.
Closes #6137

Add Elasticsearch to GitPod

---

app/decorators/application_decorator.rb
spec/helpers/social_image_helper_spec.rb

Closes https://github.com/thepracticaldev/dev.to/issues/6206

Social previews should also be generated for decorated objects

---

app/assets/stylesheets/leaderboard.scss
app/assets/stylesheets/top-bar.scss
app/views/layouts/_styles.html.erb

We have code for `users-index` but it seems to be never reached.
There's a method that determines what the `view_class` is:
https://github.com/thepracticaldev/dev.to/blob/cea1cf5e12bce9ea0ef841e0ce973adf51bd71d7/app/helpers/application_helper.rb#L10-L16
so from this we learn that the name of the class is "CONTROLLER_NAME-ACTION_NAME", but the UsersController has no `index` action: https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/users_controller.rb
Thus I think it can be safely removed. I also checked the Internal users controller but it doesn't render this partial anyway

Remove unused code for users-index

---

app/assets/stylesheets/index-comments.scss
app/assets/stylesheets/scaffolds.scss

Fixes a problem with the position of the "scroll to refresh" indicator. Also brings consistency to the "comments" section of a user profile and in-iframe content display.

Fix pull-to-refresh and other small styling issues

---

app/assets/stylesheets/user-profile-header.scss
app/controllers/internal/reactions_controller.rb
app/controllers/reactions_controller.rb
app/views/moderations/mod.html.erb
app/views/users/show.html.erb
spec/requests/reactions_spec.rb
spec/system/articles/moderator_moderates_an_article.rb
spec/system/articles/user_visits_an_article_spec.rb

This differs from https://github.com/thepracticaldev/dev.to/pull/6053 in that it only implements the vomitting buttons on the /mod view. Not on the user's profile.
One, to avoid dealing with the edge cached user/show view, and two, to avoid having this functionality live in two places.

Vomit on users from /mod

---

app/labor/mailchimp_bot.rb

Keeping a metric on Gibbon errors
n/a
n/a
n/a

Log Gibbon errors metric on Datadog

---

app/views/articles/_liquid.html.erb
app/views/articles/_sidebar_nav.html.erb
app/views/articles/_user_metadata.html.erb
app/views/articles/show.html.erb
app/views/articles/tags/_sidebar.html.erb
app/views/internal/configs/show.html.erb
spec/liquid_tags/link_tag_spec.rb

erblint was shouting at me. Just fixed a couple of small things.

Fix some erblint complaints

---

app/views/stories/feeds/show.json.jbuilder
db/seeds.rb
spec/requests/stories/feeds_spec.rb

Fixes a issue with home feed json generation that occurred when an article doesn't have an attached organization. Thanks for @nickytonline for finding it!

Fix nil organizations in home page feed endpoint

---

app/controllers/follows_controller.rb
app/controllers/search_controller.rb
app/controllers/stripe_active_cards_controller.rb
app/labor/loggers/log_worker_queue_stats.rb
app/labor/mailchimp_bot.rb
app/workers/metrics/record_daily_usage_worker.rb
app/workers/metrics/record_db_table_counts_worker.rb
app/workers/moderator/sink_articles_worker.rb
app/workers/users/delete_worker.rb
config/initializers/datadog_apm.rb
lib/sidekiq/worker_retries_exhausted_reporter.rb
spec/lib/sidekiq/worker_retries_exhausted_reporter_spec.rb
spec/requests/stripe_active_cards_spec.rb
spec/workers/metrics/record_daily_usage_worker_spec.rb
spec/workers/metrics/record_db_table_counts_worker_spec.rb

According to https://www.datadoghq.com/about/contact/ it's `Datadog`, not `DataDog`

Rename DataDog to Datadog

---

app/assets/javascripts/initializers/initScrolling.js.erb
app/controllers/stories_controller.rb
app/services/articles/feed.rb

Fixed a problem with the Algolia paginate logic.
While I was at it I noticed some other issues with the number of articles being loaded by the feeds and made some adjustments.

Fix algolia paginate issue and other feed problems

---

app/lib/constants.rb

Adds moe.cat to Mastodon instance whitelist 

---

app/models/data_update_script.rb
app/workers/data_update_worker.rb
config/environments/development.rb
docs/installation/docker.md
spec/models/data_update_script_spec.rb
spec/workers/data_update_worker_spec.rb

I've added some logging to data scripts and refactored a bit

Add logging to data scripts runner

---

app/controllers/buffered_articles_controller.rb
app/controllers/reactions_controller.rb
app/labor/mailchimp_bot.rb
app/models/chat_channel.rb
app/models/concerns/reactable.rb
app/models/reaction.rb
app/services/analytics_service.rb
db/seeds.rb
spec/models/reaction_spec.rb
spec/models/shared_examples/sync_reactions_count.rb
spec/requests/buffered_articles_spec.rb
spec/requests/reactions_spec.rb

This set out as replacing some `.map` with `.pluck` to avoid building objects just to discard them a second later but ended up containing the following things:
- refactoring of `ReactionsController#index` plus some improved tests
- refactoring of `BufferedArticlesController`
- addition of `Reaction.positive` to replace the various `where("points > ?", 0)`
- query optimization for `Reaction.count_for_article` to go from 3 queries to 1
- query optimization for `MailchimpBot#manage_tag_moderator_list` to go from building objects in memory to ask the DB for the values

Various optimizations

---

app/assets/stylesheets/internal/layout.scss

This card inside of card thing really triggers me. It's not really
important because we don't have many people poking around in these
views, but just to make myself feel a littler better I added a bit of
padding to make it less cluttered.
_(Padding highlighted for emphasis, there was no color added)_

Add padding to config card container

---

app/controllers/api/v0/followers_controller.rb
app/controllers/dashboards_controller.rb
app/decorators/user_decorator.rb
app/models/follow.rb
app/models/user.rb
app/services/moderator/merge_user.rb
app/services/users/delete_activity.rb
app/views/mailers/notify_mailer/new_follower_email.html.erb
spec/requests/internal/users_banish_spec.rb

Yes to scopes, nay to repeated `WHERE` conditions

Use scopes for Follow instead of where all the time

---

app/controllers/internal/mods_controller.rb
app/views/internal/mods/index.html.erb
spec/requests/internal/mods_spec.rb

This is a request from Peter, and it should make searching for potential
admins a bit less tedious.
https://github.com/thepracticaldev/tech-private/issues/345

Remove existing mods from potential mod list

---

docs/api_v0.yml

Rephrase CORS availability in API documentation

---

app/services/search/classified_listing.rb

There's a leftover `SearchClient` that should be `Search::Client` :)

Replace last SearchClient with Search::Client

---

app/assets/stylesheets/sticky-nav.scss

Fixes a style issue where html variants go overflow on the sidebar in a weird way...
Fixes #6331

Fix width of article sticky sidebar

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/classified_listings.scss
app/assets/stylesheets/top-bar.scss
app/views/layouts/_styles.html.erb

- Fixes an occasional flash-of-unstyled-content with the homepage footer.
- Fixes a recently introduced issue with listing-show

Small CSS fixes

---

app/services/search/base.rb
app/services/search/chat_channel_membership.rb
app/services/search/classified_listing.rb
app/services/search/tag.rb

Since we have 3 classes all using basically the same `search` method I refactored it into the base search class. 
https://github.com/thepracticaldev/dev.to/projects/6#card-33706450

Refactor Search Method to Base Class

---

app/assets/stylesheets/preact/article-form.scss
app/views/articles/_v2_form.html.erb

Fixes small jumps in style when the JS is loaded.

Fix editor style bugs

---

app/controllers/internal/pages_controller.rb
app/views/internal/pages/_form.html.erb

This was missing from pages form

Add social image to internal/pages form

---

app/controllers/notifications_controller.rb

Fix behavior of Organization comments and posts urls

---

app/assets/stylesheets/syntax.scss

Resolves https://github.com/thepracticaldev/dev.to/issues/1685.
I used http://colorsafe.co/ to generate color scheme based on the existing background color. I tried to pick similar colors, but it's really on everybody's taste to pick the right combination. Anyway, I've extracted the color scheme to a handful of SCSS variables, so it should be pretty easy to re-do the colors.

Update Syntax Highlight Color Scheme

---

app/javascript/chat/__tests__/chat.test.jsx
app/javascript/shared/components/__tests__/tags.test.jsx

Removing some leftover Algolia setup test code.

Remove leftover Algolia test code

---

app/javascript/articles/Feed.jsx

Remove console log

---

app/models/article.rb

I went to go and add some callbacks to this list for indexing Articles into Elasticsearch and my OCD got the better of me. Put them in rough order of when they occur in the callback process and grouped them by callback.

Organize Article Callbacks

---

app/controllers/search_controller.rb
app/javascript/listings/listings.jsx
config/routes.rb
spec/requests/search_spec.rb

This is the frontend code for moving the search of `ClassifiedListings` over to Elasticsearch.
~**PLEASE NOTE:** we need to update params in Fastly for `/search/classified_listings`, but I don't have access or know how to do that. I believe the params that need to be added right now are `classified_listing_search`, `category`, and `tags`...assuming `page` and `per_page` are already in Fastly? Not sure if that's by endpoint or not.~
https://github.com/thepracticaldev/dev.to/projects/6#card-33499060
~Before merging, I'll need some assistance whitelisting the new params in Fastly - I do not have access.~

Search ClassifiedListings frontend code

---

app/controllers/concerns/classified_listings_toolkit.rb
app/models/classified_listing.rb
db/seeds.rb

With the merging of #6372, we're no longer using Algolia for searching Classified Listings so time to 🔪.
https://github.com/thepracticaldev/dev.to/projects/6#card-32955601

Remove Algolia for ClassifiedListings

---

app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/classified_listings_controller.rb
app/controllers/classified_listings_controller.rb
app/controllers/concerns/classified_listings_toolkit.rb
app/models/classified_listing.rb
app/views/classified_listings/_form.html.erb
app/views/classified_listings/_form_errors.html.erb
app/views/classified_listings/edit.html.erb
docs/api_v0.yml
docs/contributing_api.md
spec/models/classified_listing_spec.rb
spec/requests/api/v0/classified_listings_spec.rb
spec/requests/classified_listings_spec.rb

This PR contains the following things:
- improvements to the docs for the articles API
- adds documentation for the listings API
- fixes a few bugs found along the way

Improve API docs for articles, add listings to it and fix bugs

---

app/views/layouts/_styles.html.erb
app/views/liquid_embeds/show.html.erb
spec/requests/liquid_embeds_spec.rb

We had been using the `scss` instead of the `css` for liquid embeds.

Fix style issues on liquid tag embed page

---

app/javascript/articles/__tests__/FeaturedArticle.test.jsx
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/__tests__/__snapshots__/FeaturedArticle.test.jsx.snap
app/javascript/articles/components/ReactionsCount.jsx

This fixes a regression caused when the homepage feed for logged on users was migrated to Preact components. I used the same logic that was used to create the HTML for paged articles generated from Algolia data.
I'll create a separate PR for the paged articles as it's not related to the Preactified components.
Before
After

Now reactions are always shown

---

.vscode/extensions.json

- Added a new VSCode Dev.to extension pack to the VSCode extension recommendations
- This Closes #5202
https://github.com/thepracticaldev/dev.to/issues/5202

Added nickytonline.dev-to-extension-pack to the VSCode recommendations

---

app/labor/reaction_image.rb
spec/factories/reactions.rb
spec/requests/notifications_spec.rb

Add Thumbsdown Reaction an Image For View
#6140

Fixing doesn't exist thumbs down image

---

app/assets/stylesheets/notifications.scss

Fix notification cannot be clicked in notifications page
Fixes #6438.

Fix notification cannot be clicked in notifications page

---

app/assets/javascripts/initializers/initializeHeroBannerClose.js

1. @rhymes brought up a really good point in [this comment](https://github.com/thepracticaldev/dev.to/pull/6333/files#r385149183) that we should use addEventListener('click', function) instead of onclick as this would override any other potential listeneners. You can read more about it it [here](https://stackoverflow.com/a/35093997/4186181)
2. I mentioned in [this PR](https://github.com/thepracticaldev/dev.to/pull/6333/files#r385112461) that I will be setting a cookie that will expire a few days after the end of the she coded campaign. I add a function to do that. I also mention that  in the future we probably want to set the expiry value dynamically from the campaign config based on how long the campaign is running for. We probably can implement this once we know more based on running …

Cookie Expiry for the Campaign Hero Banner and Event Listener update

---

app/javascript/chat/channels.jsx

Fixed app/javascript/chat/channels.jsx eslint error
#2470

Fixed app/javascript/chat/channels.jsx eslint error

---

app/controllers/stories_controller.rb
app/views/articles/_sidebar_campaign.html.erb
app/views/layouts/application.html.erb

Removed console log, hardcoded image height to avoid page jump if image is slow to load, bumped to 5 articles from 3 because 3 seemed a a bit sparse 🙃

Small fixes/adjustments

---

app/controllers/internal/classified_listings_controller.rb
app/views/internal/classified_listings/index.html.erb

This is something that was done in most internal views a few months ago. Went ahead and did it here. I also added some eager loading based on Bullet's recommendation. 
Before:
After:

Convert internal listing table view to bootstrap

---

app/javascript/article-form/elements/errors.jsx
app/javascript/articles/Feed.jsx
app/javascript/articles/LoadingArticle.jsx
app/javascript/chat/article.jsx
app/javascript/chat/channelDetails.jsx

Fixed some eslint (some PropTypes, destructuring, etc.)
#2470

fixed some eslint errors

---

app/models/user.rb
app/serializers/search/user_serializer.rb
config/elasticsearch/mappings/users.json
lib/data_update_scripts/20200305201627_index_users_to_elasticsearch.rb
spec/lib/data_update_scripts/index_users_to_elasticsearch_spec.rb
spec/models/user_spec.rb
spec/serializers/search/user_serializer_spec.rb

Index Users into Elasticsearch
https://github.com/thepracticaldev/dev.to/projects/6#card-33956385
The users are always...

Index Users into Elasticsearch

---

app/controllers/users_controller.rb

Propagates error message to Honeycomb and sends HTTP 400 (bad request) on failed user update.
n/a
n/a
-- this should appear in Honeycomb as our validation method.
Watch this appear in the rails dataset.

Error message & bad request on failed user update

---

app/models/article.rb
app/models/podcast_episode.rb
app/serializers/search/article_serializer.rb
app/serializers/search/nested_user_serializer.rb
app/serializers/search/podcast_episode_serializer.rb
config/elasticsearch/mappings/feed_content.json
lib/data_update_scripts/20200305201642_index_feed_content_to_elasticsearch.rb
spec/lib/data_update_scripts/index_feed_content_to_elasticsearch_spec.rb
spec/models/article_spec.rb
spec/models/podcast_episode_spec.rb
spec/serializers/search/article_serializer_spec.rb
spec/serializers/search/podcast_episode_serializer_spec.rb

This PR indexes articles and podcast episodes into our feed content index.
https://github.com/thepracticaldev/dev.to/projects/6#card-32289326
We are getting there!

Index Articles and Podcast Episodes to Elasticsearch

---

spec/services/moderator/banish_user_spec.rb

This is trying to run jobs that are leftover from the article creation, if we ignore them then everything works

Dont Run Indexing Sidekiq Jobs to Fix Banish User Spec

---

db/seeds.rb

While I was reviewing an issue I noticed how one of our seeded podcasts doesn't exist anymore and thought it'd be nice to add CodeNewbie to the list :)

Add CodeNewbie podcast to seeds

---

docs/getting-started/syncing.md
scripts/sync_fork.sh

The question on how to keeping your forked branch up to date was asked on the slack group, and I think that contributors would benefit from this information as well, as it's not super straightforward.
Also, the sync_fork.sh should not bomb out with `fatal: remote upstream already exists` when teh remote is added, it should simply skip that step.

Keeping your forked branch up to date

---

Gemfile
config/initializers/hypershield.rb

Prevent `PG::InvalidSchemaName: ERROR:  schema "hypershield" does not exist ` from occuring in dev and since we dont care about shielding dev data that shouldnt be a problem. Otherwise we would have to require everyone to setup the new schema. Which is also an option.

Only Activate Hypershield in Production

---

.validaterc
docs/api_v0.yml
docs/contributing_api.md
package.json
yarn.lock

Thanks to @fdoxyz and his PR #6514 I had the idea of validating the OpenAPI 3 spec file, as we do for many other file types. I'm using two linters as they take a slightly different take.
I also added a commit hook for the spec file.
#6514 
#4474

Validate API OpenAPI 3 spec

---

app/views/service_worker/index.js.erb

`/ahoy/` endpoints are redirected in Ahoy mailer and can skip service workers

Skip /ahoy/ in serviceworkers

---

app/controllers/users_controller.rb

For reporting to Honeycomb, filter values & summarize.
https://github.com/thepracticaldev/dev.to/pull/6509
n/a

[honeycomb] make error reporting concise

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feed.rb
config/field_test.yml
spec/services/articles/feed_spec.rb

Adds an additional home page feed experiment to test a feed that prioritizes articles with more comments. Inspired by a request from @pkfrank

Create comment ranking feed experiment

---

app/services/articles/feed.rb
spec/services/articles/feed_spec.rb

Fixes: https://app.honeybadger.io/fault/66984/9ed96161c5c079674732f60ac5b9b3cc

Rename feed method to correct name

---

app/services/articles/feed.rb

Rename one more method

---

app/javascript/listings/dashboard/rowElements/location.jsx

Fixed listings/dashboard/rowElements/location.jsx eslint error
#2470

Fixed listings/dashboard/rowElements/location.jsx eslint error

---

docker-compose.yml

Update docker-compose postgres to use password user and database as specified in the dockerfile
Fixes #6563

Set user, password and db for postgres docker

---

docs/api_v0.yml
spec/requests/api/v0/podcasts_episodes_spec.rb

This PR adds documentation to the `/api/podcast_episodes` controller

API: add docs for podcast episodes endpoint

---

docs/api_v0.yml

Added docs for tags API

---

app/javascript/listings/listings.jsx

Keep old listings visible until the new ones populated

---

app/labor/random_gif.rb

We unintentionally included a GIF that showcases a TV personality that has a history of saying offensive or racist things. 
Let's remove it from the list of random gifs.
Closes https://github.com/thepracticaldev/dev.to/issues/6585

Remove GIF

---

app/javascript/.storybook/storybook.scss

This fixes centering components in the Storybook display area.
Before
After

Fixed centering of Storybook display area.

---

app/controllers/chat_channel_memberships_controller.rb
app/controllers/chat_channels_controller.rb
app/views/chat_channel_memberships/edit.html.erb
spec/requests/chat_channel_memberships_spec.rb
spec/requests/chat_channels_spec.rb

Just added some specs for [ben/move-sidecar-to-iframe](https://github.com/thepracticaldev/dev.to/tree/ben/move-sidecar-to-iframe)
Related PR #6088

added spec for chat_channels_memberships_controller.rb

---

app/javascript/chat/chat.jsx

This PR fixes the chat channel pop-out panel for group chats.
I tried to write a test for it, but it was turning out more complicated than I thought... Will revisit 😬

Fix group chat channel details panel

---

app/models/tag.rb
spec/models/tag_spec.rb

It occurred to me while I was testing another PR that tag validation could be cleaned up a little bit

Cleanup tag validation a bit

---

app/controllers/search_controller.rb
app/services/search/query_builders/user.rb
app/services/search/user.rb
app/views/service_worker/index.js.erb
config/routes.rb
spec/services/search/query_builders/user_spec.rb
spec/services/search/user_spec.rb

Hooks up the backend for searching users. This will be followed up by a frontend search PR.
https://github.com/thepracticaldev/dev.to/projects/6#card-34388442

Implement User Search backend

---

datadog/prerun.sh

Reverts thepracticaldev/dev.to#6609

Revert "Make prerun.sh actually set the environment"

---

app/assets/stylesheets/comments.scss

Fix comment count size

---

app/views/internal/mods/index.html.erb

This JS never gets used. There isn't even an element with the `wrapper` class on the page.

Remove unused JavaScript

---

app/controllers/api/v0/videos_controller.rb
docs/api_v0.yml
docs/contributing_api.md

Adding docs for the users and videos APIs.
The index endpoint is going to be moved in https://github.com/thepracticaldev/dev.to/pull/6601 so we don't need to add docs for that.

API: add users and videos docs

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss

Latest style change made the line heights for titles extra big. This gets it back to expected line height for titles. Also made _tiny_ adjustment to font size.

Fix wonky line-heights on titles

---

Gemfile.lock

Bumping these two gems, as there are a few gems to upgrade, so that Monday we won't have a huge influx of dependabot's PRs
- [octokit release notes](https://github.com/octokit/octokit.rb/releases/tag/v4.17.0): nothing of note
- [rouge release notes](https://github.com/rouge-ruby/rouge/blob/master/CHANGELOG.md#version-3170-2020-03-11): improved lexers

Upgrade octokit and rouge

---

app/assets/stylesheets/comments.scss
app/views/devise/shared/_authorization_error.html.erb

Fix a couple margins which have recently moved from other style changes

Fix a couple margins

---

docs/api_v0.yml

Small update to avoid repetition of common parameters

API docs: cleanup parameters

---

app/controllers/internal/configs_controller.rb
app/models/article.rb
app/models/site_config.rb
app/views/articles/_sidebar_additional.html.erb
app/views/internal/configs/show.html.erb
spec/requests/internal/configs_spec.rb

Admins may not want to use the same core functional tags that we do on the sidebar.

Allow admins to define core sidebar tags in config

---

config/initializers/hypershield.rb

this will prevent Hypershield from trying to run migrations when a community does not wish to use it. 
Me when this gem causes another issue

Only Enable Hypershield if ENV variable is present

---

app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/articles/feed.rss.builder
app/views/articles/index.html.erb
app/views/articles/search/_meta.html.erb
app/views/classified_listings/index.html.erb
app/views/internal/configs/show.html.erb
app/views/service_worker/manifest.json.erb
app/views/videos/index.html.erb
spec/requests/internal/configs_spec.rb
spec/requests/stories_index_spec.rb

This gives new communities one place to update the default description anywhere it is to appear.

Allow community admins to alter site description

---

app/controllers/stories/feeds_controller.rb
app/models/page_view.rb
app/services/articles/feed.rb
app/workers/users/record_field_test_event_worker.rb
config/field_test.yml
spec/services/articles/feed_spec.rb
spec/workers/users/record_field_test_event_worker_spec.rb

Add a test which puts more weight on `experience_level` and one which is a mix of all other tests.
Also added a success event based on visiting a post 4/7 past hours which gives us an answer as to which feed could encourage folks to check in and find good content that they click through to read multiple times in a day.

Add two new experiments and one new conversion event

---

package.json

Heroku asset precompile is failing and it looks like Heroku is trying to use a different yarn version which might be the cause 
Heroku: Installing yarn-v1.16.0
Locally:  yarn install v1.21.1

Specify yarn version in package.json

---

package.json
yarn.lock

Attempting to fix a deploy issue.

Moved devDependencies to dependencies to attempt fixing [deploy]

---

app/javascript/leftSidebar/TagsFollowed.jsx
app/javascript/leftSidebar/__tests__/__snapshots__/TagsFollowed.test.jsx.snap
app/javascript/packs/homePage.jsx

I believe our recent upgrade modified some behavior some how with how rendering works and it is causing an issue where the JavaScript re-runs on back button click so that the home page re-renders meaning people will lose their place in the feed.
I think the issue is a change across much of our Preact JS rendering.
This is sort of a quick patch to the hottest path affected, and we can re-examine this tomorrow.

Fix homepage back button flicker

---

app/javascript/packs/homePage.jsx

Fix tag doubel rendering issue

---

app/assets/stylesheets/internal.scss

Remove unused SCSS file

---

app/services/search/base.rb
app/services/search/chat_channel_membership.rb
app/services/search/classified_listing.rb
app/services/search/user.rb

Moved the pagination methods out of the individual search classes and into the base class since they are all exactly the same. 
https://github.com/thepracticaldev/dev.to/projects/6#card-34733815

Refactor Search Classes: Move pagination methods to base class

---

app/services/search/query_builders/chat_channel_membership.rb
app/services/search/query_builders/classified_listing.rb
app/services/search/query_builders/query_base.rb
app/services/search/query_builders/user.rb

Refactor common query methods into a query base class that can be inherited by all query builders. 
https://github.com/thepracticaldev/dev.to/projects/6#card-34490522

Refactor Elasticsearch Query Builders

---

app/assets/stylesheets/chat.scss
app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/compose.test.jsx.snap
app/javascript/chat/compose.jsx

This fixes some styling bugs
**Before:**
**After:**

Fix /connect message composer style bugs

---

package.json
yarn.lock

This reverts commit 432e2c4f299a9676a544ccc7341704fd48603e6c.
No dice trying to move only the recently changed dev dependency to dependencies key in package.json so reverting #6690.

Revert "Get those devDeps back! (#6690)" [deploy]

---

app/assets/stylesheets/internal/layout.scss
app/javascript/internal/__tests__/controllers/article_controller.test.js
app/javascript/internal/__tests__/controllers/buffer_controller.test.js
app/javascript/internal/controllers/article_controller.js
app/javascript/internal/controllers/buffer_controller.js
app/views/internal/articles/_individual_article.html.erb
app/views/internal/articles/rss_articles.html.erb
app/views/internal/classified_listings/index.html.erb
app/views/internal/configs/show.html.erb

This PR probably does a few too many things, but they are all in the internal UI.
- Fix a bug with article highlighting
- Fix a bug with buffer UI indicator badges on suggested tweets
- Fix a formatting issue in the internal listings UI
- Add an AJAX indicator to internal listings UI
- Rename some CSS classes to match Bootstrap's naming convention
- Remove some unused CSS

Internal bug fixes and misc JS/CSS cleanup

---

app/views/internal/articles/_individual_article.html.erb
app/views/internal/articles/index.html.erb
app/views/internal/broadcasts/index.html.erb
app/views/internal/classified_listings/edit.html.erb
app/views/internal/classified_listings/index.html.erb
app/views/internal/comments/index.html.erb
app/views/internal/mods/index.html.erb
app/views/internal/organizations/index.html.erb
app/views/internal/organizations/show.html.erb
app/views/internal/pages/index.html.erb
app/views/internal/tags/index.html.erb
app/views/internal/tools/index.html.erb
app/views/internal/users/edit.html.erb
app/views/internal/users/index.html.erb
app/views/internal/users/show.html.erb
app/views/internal/welcome/index.html.erb

Based on a comment @citizen428 made on another PR, I felt like it was worth spending 20 minutes swapping as many of these manually constructed URLs as possible to Rails generated URLs.

Internal: Use Rails URL helpers where possible

---

app/views/users/_additional_authentication.html.erb

Resolves https://github.com/thepracticaldev/dev.to/issues/6730
n/a
n/a

Resolve infinite loop in User#edit

---

app/views/sitemaps/show.xml.erb
spec/requests/sitemaps_spec.rb

Dynamic sitemap PR mostly works, but time format was not correct.

Update lastmod for generated sitemap

---

app/views/dashboards/_dashboard_article.html.erb

As requested in the related issue, lowered the minimum count of page views that are shown in dashboard from 100 to 25.
Issue #6679

Dashboard page view counts

---

spec/factories/users.rb
spec/labor/badge_rewarder_spec.rb
spec/models/github_repo_spec.rb
spec/requests/github_repos_spec.rb
spec/requests/internal/users_spec.rb
spec/requests/user/user_settings_spec.rb
spec/services/users/delete_spec.rb
spec/views/users/edit.html.erb_spec.rb

Supplementary specs for https://github.com/thepracticaldev/dev.to/pull/6732. I also updated how identity is created in the User factory; it will now only be created when specified. 
https://github.com/thepracticaldev/dev.to/pull/6732
n/a

Create specs for users/edit.html.erb

---

db/seeds.rb

This change just randomly adds members to organizations when seeding the DB.

Add some seeded users to organizations

---

db/seeds.rb

This PR does a small bit of formatting, makes it a lot less annoying to move the order of seed tasks around, and also adds some seed data for pages and vomit reactions.
Once #6712 is merged, it will also make some of the seeded listings behave as organization listings.
Mostly, this is just data that I've wished was seeded for the stuff I'm working on in internal.

Add additional seed data

---

app/views/internal/pages/index.html.erb

Add a link to view pages from internal

---

app/views/articles/show.html.erb
spec/requests/stories_show_spec.rb

Our `noindex` policy was a little too aggressive. This makes it _slightly_ more likely that a post will indeed be indexed by Google.

Loosen noindex rules slightly

---

db/seeds.rb

Add tags to listings in the seed file

Add tags to seeded listings

---

app/assets/stylesheets/settings.scss

Noticed this small thing so I decided to adjust it:

Match textarea width with text input width

---

package.json

Fixes a deployment issue on Heroku where an npm package is not explicitly in the dependencies.

Added @babel/plugin-syntax-dynamic-import to dependencies so Heroku is happy.

---

app/javascript/article-form/elements/imageManagement.jsx
app/javascript/packs/validateFileInputs.js
app/views/comments/_form.html.erb
app/views/podcasts/_form.html.erb
app/views/users/_org_non_member.html.erb
app/views/users/_profile.html.erb
spec/system/comments/user_fills_out_comment_spec.rb

There are cases where file uploads fail silently for various reasons (file type, file size, etc.) so I created some client-side validations to help make the errors more clear to the user.
I intentionally skipped adding this behavior to `/internal`, but I'm happy to add it if we think it's helpful.
I'm looking for feedback on this approach before becoming too far gone. This functionality will likely be replaced by Active Storage in the future so I'm trying to strike a balance of a hacky patch and something reusable. The default error handling behavior is to add red error text explaining the error and resetting the form field. Below will be several comments to explain things in more detail.
**TO DO**
https://github.com/thepracticaldev/dev.to/projects/9#card-34856669
**Adding an image to …

Validate file uploads client-side

---

app/models/organization_membership.rb
app/views/users/_org_admin.html.erb
app/views/users/_organization.html.erb
spec/models/organization_membership_spec.rb

Found another small styling issue 🙃 
Also added a comment and refactored a bit.

Update call to action box text styling

---

app/assets/stylesheets/base_imports.scss
app/assets/stylesheets/minimal.scss
app/views/layouts/_styles.html.erb

Fixes import issue with non-serviceworker context.
This ensures that all styles are loaded in correct order, even with inline-styles with new format.

Add base imports before other inline styles

---

package.json
yarn.lock

Fixes an issue where the addons panel of Storybook does not change when you tab to a different addon, e.g. knobs to actions.
Before
After

Upgraded @storybook/addon-knobs to 5.3.17

---

app/assets/stylesheets/_fonts.scss

Remove erroneous inclusion of open dyslexia

---

app/javascript/packs/clipboardCopy.js
app/javascript/packs/webShare.js

These were causing problems in prod

Comment out mishandled imports

---

app/workers/notifications/moderation_notification_worker.rb
spec/models/comment_spec.rb
spec/requests/comments_spec.rb
spec/support/initializers/test_prof.rb
spec/uploaders/article_image_uploader_spec.rb
spec/uploaders/badge_uploader_spec.rb
spec/uploaders/cover_image_uploader_spec.rb
spec/uploaders/profile_image_uploader_spec.rb
spec/workers/notifications/moderation_notification_worker_spec.rb

These come from some work I did last week in trying to identify tests that failed due to our implicit ordering. There are still a few I can't still wrap my head around but in the meantime I'm going to submit this PR with some lower hanging fruits.

Some RSpec fixes

---

app/views/layouts/_styles.html.erb

This is a small additional fix for the loading of style assets.

Include crayons style tag on pages that load direct from css

---

app/javascript/packs/homePage.jsx

Just a bit of cleanup. `setInterval` was being cleared by `clearTimeout` instead of `clearInterval`. Also, prettier did a bit of tidying up.

Homepage feed fix: cleartimeout to clearinterval

---

app/assets/stylesheets/preact/onboarding-modal.scss

This continues off the work of #6682. The primary button background colour is already set properly with the correct design system colours. This PR simply fixes the text colour for the primary button in the onboarding modals.
Before:
After:

Fixed onboarding primary button color

---

docs/tests/approvals-tests.md
docs/tests/readme.md

Create Approvals test doc

---

app/views/layouts/_user_config.html.erb

Rather than logging this error lets report it to Honeybadger so we can gain more insight into what is happening when this fails. 
Spurred by: https://app.honeybadger.io/fault/66984/c2011e5704098c2f442b358dea119dfa

Notify Honeybadger of js error when selecting a theme template

---

babel.config.js
package.json
yarn.lock

jest has now been upgraded to the latest version, 25.2.0

Upgraded to jest 25.2.0

---

app/models/display_ad_event.rb
db/migrate/20200324113133_remove_unused_columns_from_display_ad_events.rb
db/schema.rb

Removes columns previously ignored in #6783
#6783

Remove unused columns from display_ad_events

---

app/javascript/.storybook/preview.js

Since all the recent CSS updates, we now require crayons.scss in the boot up of Storybook. Visually nothing changes. It simply puts back all the CSS that went missing.
[Latest Storybook](https://devto-storybook.now.sh/)

Added crayons.scss to Storybook

---

package.json
yarn.lock

This was on our list of upgrades to do. Not sure why we didn't delegate this to dependabot, so here it is. 🙃

Upgraded to eslint 6.8.0

---

app/labor/reaction_image.rb

Fixes: https://app.honeybadger.io/fault/66984/d4b4628080a41228eea5314b40dd1275
```
ActionView::Template::Error: Nil location provided. Can't build URI.
_reaction.html.erb  21 _app_views_notifications__reaction_html_erb(...)
[PROJECT_ROOT]/app/views/notifications/_reaction.html.erb:21:in `_app_views_notifications__reaction_html_erb'
19     <span class="reaction-images">
20         <% category = notification.json_data["reaction"]["category"] %>
21         with <%= image_tag(ReactionImage.new(category).path, class: "reaction-image", alt: "a #{category.humanize}") %>
22       </span>
23   </div>
```

Bug Fix: Show the Nausea For Vomit Recation

---

.github/CODEOWNERS

Adding @nickytonline to the `CODEOWNERS` for JavaScript dependencies changes, as now he won't be notified about those.

Add Nick to codeowners for JS deps

---

app/assets/javascripts/initializers/initNotifications.js

Bug fix. CSS classes shifted around so removing the showing isn't quite the right thing here. Just shifted the logic up a bit.

Make notification hide correctly on click

---

.yarnrc

Updates yarn to the latest 1.x version
Closes #6856

Update yarn version

---

babel.config.js

This build improvment is enabled by #6878. `@babel/preset-env` now has the [bugFixes option](https://babeljs.io/docs/en/babel-preset-env#bugfixes) options set to true. Come Babel 8.x, this will be the default and the `bugFixes` option will no longer be necessary.
Things seemed fine on the site as I perused different pages, but reviewers do the same please.

Added Babel 7.9.0 @babel/preset-env bugFixes option

---

docs/api_v0.yml

Before this change the example curl command returns 400 bad request with an appropriate API key and article ID.
After this change the example curl command does not return error 400 bad request.

Add missing } to updateArticle code sample

---

app/models/tweet.rb

Refactor method in tweet models

---

app/controllers/admin/tags_controller.rb
app/dashboards/tag_dashboard.rb
app/models/tag.rb

Ignoring columns that are unused in the `Tag` model:
```text
submission_rules_headsup
```
This will be removed once the PR is live.

Ignore unused tags columns

---

app/models/tweet.rb

Ignoring unused columns in the `Tweet` model:
```text
primary_external_url
```

Ignore unused tweets columns

---

app/views/layouts/_user_config.html.erb

We have instances where bodyClass is null and that causes multiple errors then when we try to see what it includes. This checks for its presence first before checking what it includes. If the presence check doesn't work the way I wrote please tell me and I will fix it! 
Fixes:
https://app.honeybadger.io/fault/67192/e18a58c12b3633ed0a39c42b86795704#notice-trace
https://app.honeybadger.io/fault/66984/fa80b7b23a1a201176492cf90e8dcd48

JS Bug Fix: Check that bodyClass is present before checking what it includes

---

app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/config/_colors.scss
app/views/pages/crayons.html.erb

This PR was initially just to write a demo frontend code for subscribe dropdown. But in Crayons, I also have done some tiny adjustments associated to that demo and eventually to the feature we will ship.

Button & color updates

---

app/dashboards/organization_dashboard.rb
app/models/organization.rb
spec/requests/user/user_organization_spec.rb

Ignoring columns that are unused in the `Organization` model:
```text
address
approved
city
country
jobs_email
jobs_url
state
zip_code
```
These will be removed once this is live.

Ignore unused organizations columns

---

app/views/users/_response_templates.html.erb
spec/system/user/user_settings_response_templates_spec.rb

Fixes a bug where the delete button and the edit buttons were routing to the wrong place.

Fix response templates edit and delete buttons

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/controllers/users_controller.rb
app/javascript/onboarding/components/ClosingSlide.jsx

Fixes a few style bugs with onboarding that didn't crop up with test data.
Notably...
And added a bit of `min-height` to a couple of divs which wait to have their content loaded, reducing "jump".

Fix small onboarding issues

---

app/models/tweet.rb
spec/models/tweet_spec.rb
spec/support/fixtures/vcr_cassettes/twitter_fetch_reply.yml

While preparing #6950 I've noticed how we currently:
- save the wrong `user id` by overwriting it with the `status id`
- don't save `status id` at all

Correctly save Tweet reply ids

---

app/services/users/delete_activity.rb

Refactor method delete_activity

---

app/javascript/.eslintrc.js
app/javascript/.storybook/main.js
config/webpack/environment.js
jsconfig.json

This PR adds [webpack aliases](https://webpack.js.org/configuration/resolve/#resolvealias) for crayons (design system).
Instead of having to import a design system component into a component like this
`import { Dropdown } from '../../crayons/Dropdown'`
we can now do the following in any Preact component.
`import { Dropdown } from '@crayons/Dropdown'`
Also, VS Code Intellisense for webpack aliases is supported via the [VS Code JS configuration file](https://code.visualstudio.com/docs/languages/jsconfig). For other editors, e.g. Sublime, if someone knows how to map webpack aliases into the editor, PRs are welcome. 😉
Intellisense in VS Code for webpack aliases

Add webpack aliases for Crayons components

---

app/javascript/crayons/Dropdown/Dropdown.jsx
app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
app/javascript/crayons/Dropdown/__stories__/dropdown-css-helper.scss
app/javascript/crayons/Dropdown/__stories__/dropdown.description.stories.jsx
app/javascript/crayons/Dropdown/__stories__/dropdown.html.stories.jsx
app/javascript/crayons/Dropdown/__tests__/Dropdown.test.jsx
app/javascript/crayons/Dropdown/__tests__/__snapshots__/Dropdown.test.jsx.snap
app/javascript/crayons/Dropdown/index.js
app/javascript/crayons/index.js
jest.config.js

Creates the `<Dropdown />` component and accompanying Storybook stories. Available via `import { Dropdown } from '@crayons';`

Created preact component for crayons dropdown

---

app/controllers/onboardings_controller.rb
config/initializers/initialization_cachebust.rb

Our onboarding endpoint does not contain any custom user data rendered from the server, yet we don't cache it at the edge. This is a small optimization to make that happen.

Cache onboarding at edge

---

app/services/users/delete_activity.rb

Rename a method name consistently with the other method names in the file and based on its function
I noticed this based on [#6928](https://github.com/thepracticaldev/dev.to/pull/6928) where we renamed the rest of the methods appropriately.

Rename method name consistently in delete_activity

---

README.md

This PR will add Arit's GitHub handle and her DEV profile URL to the list of Core Team members
None
Not Applicable
No

Add my name to Core Team list

---

app/controllers/stories_controller.rb

Reverts thepracticaldev/dev.to#6982
Not the correct fix for this.

Revert "Set search cache header using the current_user id if present"

---

app/assets/javascripts/initializers/initScrolling.js.erb
app/assets/javascripts/utilities/buildArticleHTML.js.erb
app/controllers/search_controller.rb
app/javascript/article-form/__tests__/articleForm.test.jsx
app/javascript/articles/Article.jsx
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/__tests__/utilities/articleUtilities.js
app/javascript/articles/components/SearchSnippet.jsx
app/javascript/src/components/common-prop-types/article-prop-types.js
app/javascript/src/utils/__tests__/search.test.js
app/javascript/src/utils/search.js
app/views/articles/_search.html.erb
app/views/articles/index.html.erb
app/views/articles/search.html.erb
app/views/articles/search/_sidebar.html.erb
app/views/articles/tag_index.html.erb
app/views/organizations/show.html.erb
app/views/podcast_episodes/index.html.erb
app/views/users/show.html.erb

Revert "Serve Feed Content from Elasticsearch"

---

app/models/user.rb
app/services/broadcasts/welcome_notification/generator.rb
spec/requests/user/user_settings_spec.rb

Basically followed https://github.com/thepracticaldev/dev.to/issues/6892#issuecomment-604807667 's suggestion
n/a

Create alias for User's welcome_notification

---

docs/.gitdocs.json

Links in the docs headers should have the `rel` attribute set

Add rel noopener, noreferrer, nofollow to docs header links

---

lib/tasks/badges.rake
lib/tasks/cache.rake
lib/tasks/fetch.rake
lib/tasks/metrics.rake
lib/tasks/notifications.rake

Extract and place some rake tasks into its own domain-specific file. 
n/a
n/a
n/a

Organize rake tasks

---

app/models/article.rb
app/services/broadcasts/welcome_notification/generator.rb
db/seeds.rb
spec/factories/broadcasts.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb

Adds an "ask a question/start a discussion" welcome notification, which will be sent out 6 days after a user has signed up. If a user has already asked a question or started a discussion, the copy will change accordingly; if they have done both of these actions, they will not receive this notification!
Additionally, this reorganizes the notifications and their specs so that they are sent in the order of the user's `created_at`. It also adds a scope to make it easy to check if a user has published an article with a specific tag. 
Closes https://github.com/thepracticaldev/dev.to/issues/6708.
When a user has asked a question but has NOT started a discussion, they will receive this notification:
When a user has started a discussion but has NOT asked a question, they will receive this …

Prompt users to ask a question/start a discussion

---

docs/technical-overview/architecture.md
docs/technical-overview/stack.md

This PR makes a few slight updates to our Technical Documentation, after an informative overview of our stack by Ben 😄 
None
None
No

Update to Docs after Technical Overview with Ben

---

app/models/poll.rb
app/models/poll_option.rb

Ignoring columns that are unused in the `Poll`:
```text
allow_multiple_selections
```
and `PollOption` model:
```text
counts_in_tabulation
```
These will be removed once this PR is live.

Ignore unused polls and poll_options columns

---

app/mailers/application_mailer.rb
app/models/badge_achievement.rb
app/views/mailers/notify_mailer/new_badge_email.html.erb
app/views/mailers/notify_mailer/new_badge_email.text.erb
db/seeds.rb
spec/mailers/notify_mailer_spec.rb

While reviewing #6999 I accidentally noticed how the email expects the "rewarding message" to be there, but it's an optional field.
I also added badges/achievements to the seeds file, refactored a bit the code, added tests and generalized the URLs

Strengthen badge achievement code and fix badge email

---

app/services/search/feed_content.rb
app/services/search/query_builders/feed_content.rb
spec/services/search/feed_content_spec.rb

We need these additional fields to ensure we can properly build a podcast episode in the feed. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35511216

Return Fields needed to Populate the Feed for Podcast Episodes

---

app/assets/javascripts/initializers/initializeHeroBannerClose.js
app/controllers/stories_controller.rb
app/views/layouts/application.html.erb

Exit logic needs to be general, removed the quickly-implemented hardcode from the last campaign.

Remove hardcoded banner exit code

---

app/models/html_variant.rb

We restrict the ability to edit these after they're approved due to an interest in keeping the results tracking accurate. Not necessarily needed for campaign usecase at the moment, so easier to remove that need.

Allow published/approved campaign html variant to be edited

---

.travis.yml

Disable Travis alert on pull request

---

app/views/articles/_sidebar_campaign.html.erb

This is moving from one hardcoded value to another which was felt to be more relevant for the campaign....
If it matters enough going forward we can make sure this is customizable via config.

Share your project instead of story

---

app/mailers/notify_mailer.rb
app/models/chat_channel.rb
app/views/mailers/notify_mailer/channel_invite_email.html.erb
spec/mailers/notify_mailer_spec.rb
spec/mailers/previews/notify_mailer_preview.rb

We had some bugs based on a couple code paths not working as expected. This is more of a hot fix than a sure thing.

Fix up connect group issues

---

spec/services/credits/buyer_spec.rb

This test failed in one of the builds for https://github.com/thepracticaldev/dev.to/pull/7059 and well, let's fix it so it will never fail ever again (👁).
*hopefully not at least in this PR*

Fix flaky credits buyer spec

---

app/javascript/crayons/ButtonGroup/ButtonGroup.jsx
app/javascript/crayons/ButtonGroup/__stories__/ButtonGroup.stories.jsx
app/javascript/crayons/ButtonGroup/__tests__/ButtonGroup.test.jsx
app/javascript/crayons/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
app/javascript/crayons/ButtonGroup/index.js
app/javascript/crayons/index.js

Converted the design system button group to a Preact component.
Here is the [ButtonGroup in Storybook](https://devto-storybook.now.sh/?path=/story/components-buttongroup--default)
An example usage of the <ButtonGroup /> component.

Created the <ButtonGroup /> Preact Component

---

app/assets/stylesheets/base/reset.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/comments.scss

Fix various small style issues.

Fix various small style issues

---

app/assets/stylesheets/moderators.scss

The moderator page does not work properly. It is very hard to see the information. 
See before & after pictures below.
The hover looks very ugly. What do you suggest? 
Removed the hover altogether, as suggested!

Fixed moderators page color

---

app/controllers/video_chats_controller.rb
app/javascript/packs/videoChat.jsx
app/views/video_chats/show.html.erb

Just closing the loop on a bit of low-priority video experimentation.
There is still now path within the app that actually gets here so experimenting in prod with twilio video a bit.

A bit more video experimentation

---

app/controllers/stories/feeds_controller.rb
spec/requests/stories/feeds_spec.rb

This ups the test coverage of `Stories::FeedsController` from 64% to 100% because it is now a dict.
n/a
n/a

Refactor Stories::FeedsController

---

app/controllers/video_chats_controller.rb
app/javascript/chat/chat.jsx
app/javascript/packs/videoChat.jsx
app/models/message.rb
app/views/video_chats/show.html.erb
spec/requests/video_chats_spec.rb

This adds authorization to limit the call to folks in channel and launches call with `/call`.

Add authorization and new styles for sidecar video

---

app/models/poll.rb
db/migrate/20200407083405_remove_unused_columns_from_polls.rb
db/schema.rb

Removes previously ignored columns from `polls`
#6945

Remove unused columns from polls

---

docs/backend/pusher.md

Adds a step by step guide to setup Pusher Beams and the Firebase configuration required to work with Push Notifications
[Android Push Notifications PR](https://github.com/thepracticaldev/dev.to/pull/6883)

Adds Pusher Beams docs for Android PN

---

app/javascript/chat/chat.jsx

I came across this today when accepting a new invitation to a group in Connect. It looked like it needed just a bit of space.
Before
After

Added some space between wave emoji and text

---

app/controllers/stories/feeds_controller.rb
spec/requests/stories/feeds_spec.rb

`.fetch` was used incorrectly. This updates it to it's intended functionality.
n/a
n/a

Account for scenario without `test_variant`

---

app/models/podcast_episode.rb
db/migrate/20200407083732_remove_unused_columns_from_podcast_episodes.rb
db/schema.rb

Removes previously ignored columns from `podcast_episodes`
#6939

Remove unused columns from podcast_episodes

---

jest.config.js

While writing some frontend tests, I realized that the coverage was omitting a lot of files.

Updated jest code coverage configuration.

---

.codeclimate.yml
app/assets/javascripts/initializers/initializeBaseUserData.js

This fixes the issue with barrel files in our modern JS and also upgrades codeclimate to eslint 6 which is what we have running in our codebase.

Upgraded to eslint 6 and fixed barrel file issue for codeclimate

---

app/javascript/CommentSubscription/CommentSubscription.jsx
app/javascript/CommentSubscription/__stories__/CommentSubscription.stories.jsx
app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
app/javascript/CommentSubscription/__tests__/__snapshots__/CommentSubscription.test.jsx.snap
app/javascript/CommentSubscription/index.jsx
app/javascript/crayons/formElements/FormField/FormField.jsx
app/javascript/crayons/formElements/FormField/index.js
app/javascript/crayons/formElements/RadioButton/RadioButton.jsx
app/javascript/crayons/formElements/RadioButton/index.js
app/javascript/crayons/formElements/__stories__/FormField.stories.jsx
app/javascript/crayons/formElements/__stories__/RadioButton.stories.jsx
app/javascript/crayons/formElements/index.js
app/javascript/crayons/index.js

This is the comment subscription component that will be used on the article page. Available on the [latest Storybook](https://devto-storybook.now.sh/?path=/story/app-components-comment-subscription--default).

Comment Subscription Component

---

app/labor/rate_limit_checker.rb

Remove an unused variable `count` 🤦

Remove unused variable oops

---

lib/tasks/temporary/social_media_handles.rake

Remove a temporary script that was used to update the social media handles
No
No

Remove a temporary script

---

app/views/mailers/digest_mailer/digest_email.html.erb
app/views/mailers/notify_mailer/account_deleted_email.html.erb
app/views/mailers/notify_mailer/account_deleted_email.text.erb
app/views/mailers/notify_mailer/account_deletion_requested_email.html.erb
app/views/mailers/notify_mailer/account_deletion_requested_email.txt.erb
app/views/mailers/notify_mailer/new_follower_email.html.erb
app/views/mailers/notify_mailer/new_mention_email.html.erb
app/views/mailers/notify_mailer/new_message_email.html.erb
app/views/mailers/notify_mailer/new_reply_email.html.erb
app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
app/views/mailers/notify_mailer/trusted_role_email.html.erb
app/views/mailers/notify_mailer/trusted_role_email.text.erb

In this PR I update all the static (i.e. DEV or dev.to) text on mailers to use the community_name. I prefer these PR's to be small and testable via the UI and so I have not updated the links as yet. Will tackle in a subsequent PR.
https://github.com/thepracticaldev/dev.to/issues/6858

Update all the static (i.e. DEV or dev.to) text on mailers to be dynamic

---

app/javascript/packs/videoChat.jsx

We determine room type on server but forgot to actually pass the value in.

Fix typo in videochat

---

app/javascript/chat/chat.jsx

Ah the glory of testing in prod. This fixes a typo and does some linting

Fix video chat typo

---

app/assets/javascripts/initializers/initNotifications.js
app/assets/stylesheets/chat.scss
app/assets/stylesheets/top-bar.scss
app/controllers/chat_channels_controller.rb
app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
app/javascript/chat/channels.jsx
app/javascript/chat/chat.jsx
app/javascript/packs/videoChat.jsx
app/models/message.rb
app/views/chat_channels/index.html.erb
app/views/video_chats/show.html.erb
spec/models/message_spec.rb

Several design adjustments and optimizations for `/connect`

Small design and functionality touches to /connect

---

app/views/users/_publishing_from_rss.html.erb
spec/requests/user/user_settings_spec.rb

https://dev.to/settings/publishing-from-rss is currently broken
I also added a test to avoid regressions
Closes #7237

Fix broken RSS settings page

---

app/assets/stylesheets/chat.scss
app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/content.test.jsx.snap
app/javascript/chat/__tests__/content.test.jsx
app/javascript/chat/chat.jsx
app/javascript/chat/content.jsx
app/javascript/chat/videoContent.jsx
app/models/message.rb
app/views/video_chats/show.html.erb

Proof of concept buttons that allow user to expand sidecar content to full area of chat.

Sidecar content fullscreen proof of concept

---

app/assets/stylesheets/chat.scss
app/javascript/chat/__tests__/__snapshots__/content.test.jsx.snap
app/javascript/chat/chat.jsx
app/javascript/chat/content.jsx
app/javascript/chat/videoContent.jsx

We currently have a few superfluous renders and an issue where changing channels does not cause a reset in `allMessagesLoaded`. This fixes those small issues.

Fix scrolling issues and small fixes

---

Dockerfile

Fix fails when run **./docker-run.sh INTERACTIVE-DEMO**
#7240  Docker Installation fails on gemfile install

Fix Install libcurl and curl-dev into Dockerfile

---

app/assets/stylesheets/chat.scss
app/javascript/chat/chat.jsx
app/views/video_chats/show.html.erb

This is a fix to make sure chat re-renders appropriately in case where it's currently having issues.

Fix chat rerender issues

---

app/javascript/chat/chat.jsx

The functionality to jump to the bottom of the chat if you submit a post was missing. Not sure when that started not working properly but this fixes it.
Also tossed in some more proof-of-concept `/` commands.

Ensure proper "jump to bottom"

---

app/models/api_secret.rb
spec/models/api_secret_spec.rb

Adding validation to the API key description field. The size is based on the current existing data.

Validate API key description length

---

package.json
yarn.lock

[Changelog](https://github.com/honeybadger-io/honeybadger-js/blob/master/CHANGELOG.md#fixed)

Upgrade Honeybadger js to 2.2.1

---

.travis.yml
spec/workers/users/resave_articles_worker_spec.rb

Revert "Try out parallel Travis builds (#6645)"

---

app/controllers/stories/feeds_controller.rb

Here we go again. Resolves https://app.honeybadger.io/fault/67335/f734bc8f134358ed0729948f23983a37
n/a
n/a
n/a

Fix Feeds' VARIANTS issue

---

app/controllers/pages_controller.rb
config/routes.rb
spec/requests/pages_spec.rb

As requested by @pkfrank in Slack. Note that this is hardcoded like the previous links, as this needs to be live by tomorrow. We'll tackle the whole issue of generalizing this when we get to #7267.
n/a, Slack conversation

Add CodeNewbie staff redirect

---

Dockerfile

Use yarn version as specified in `.yarnrc` in Dockerfile
Closes #7296

Respect .yarnrc in Dockerfile

---

app/assets/stylesheets/ltags/LinkTag.scss
app/liquid_tags/link_tag.rb
app/views/articles/_liquid.html.erb
spec/liquid_tags/link_tag_spec.rb

Fixes: https://app.honeybadger.io/fault/66984/f69a222c8f2fe4281298a71742c203b8

Display placeholder fo link liquid tags of Deleted Articles

---

app/controllers/stories_controller.rb

Small fix in using the proper keys

Small ld+json fix

---

app/views/articles/_sidebar_campaign.html.erb
app/views/layouts/_styles.html.erb

There is a jump for non-serviceworker driven traffic in the styling due to the way it is rendered. This fixes it.
Also removed the "comments count" as I don't think it's really relevant for this campaign. We can discuss later whether it should be a configurable option for future campaigns.

Adjust styling and rendering of campaign widget

---

config/field_test.yml

Slight adjustment to weights based on what's doing best

Adjust field test weights

---

app/models/organization.rb
app/models/user.rb
app/views/users/_org_admin.html.erb
app/views/users/_profile.html.erb
spec/models/organization_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/requests/user/user_organization_spec.rb
spec/support/fixtures/approvals/liquid_tweet_tag_spec.approved.html
spec/support/initializers/validate_url.rb

Improve some validations

---

app/assets/javascripts/initializers/initNotifications.js
app/javascript/chat/chat.jsx
app/javascript/src/utils/getUnopenedChannels.jsx

Continued battle with small state issues with regards to scroll position. Also adjusted how we are displaying the link and preloading the content.

Small connect js fixes

---

app/javascript/.storybook/preview.js
package.json

Now in Storybook you can look at components in the various themes we support.

Added a theme switcher to Storybook.

---

app/assets/javascripts/initializers/initScrolling.js.erb
app/views/articles/_search.html.erb

Need to properly parse arrays for feed content searches since they don't use `fetchSearch` helper

Properly parse params for feed content Tag searching

---

app/assets/javascripts/utilities/buildArticleHTML.js.erb
app/services/search/query_builders/feed_content.rb

Includes video duration on videos served via `/search/`. Currently displaying as `undefined`.

Add video duration to search results

---

app/assets/javascripts/utilities/buildArticleHTML.js.erb

Missing parentheses from prior PR cause issue.

Add missing parentheses to video html

---

app/helpers/feedback_messages_helper.rb
spec/helpers/feedback_messages_helper_spec.rb

Generalization of feedback message

Update feedback messages to be general

---

app/controllers/user_blocks_controller.rb
spec/requests/user_blocks_spec.rb

Fixes: https://app.honeybadger.io/fault/66984/3309479abac8ae78c1216f2f69ff0cf8
Also refactored the spec a little

Raise ActiveRecord::RecordNotFound: if Userblock is not found

---

db/migrate/20200420130910_add_unique_index_to_badges_slug.rb

As the migration partly failed in production, we need to check if the index exists or not

Fix badges slug migration

---

CONTRIBUTING.md

This PR adds language in our contribution guideline setting expectations about using inclusive language right down to the code level. Relating to https://github.com/thepracticaldev/dev.to/issues/7147

Incluse language about inclusive naming in contributing.md

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/controllers/ga_events_controller.rb
app/controllers/internal/events_controller.rb
app/labor/bufferizer.rb
app/views/email_subscriptions/unsubscribe.html.erb
app/views/events/show.html.erb
app/views/internal/tools/index.html.erb
app/views/internal/users/edit.html.erb
app/views/mailers/notify_mailer/new_mention_email.text.erb
app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
app/views/notifications/index.html.erb
app/views/pages/badges.html.erb
app/views/users/_org_admin.html.erb
app/views/users/_org_non_member.html.erb
app/views/users/show.html.erb
spec/support/fixtures/approvals/email_subscriptionsunsubscribe.approved.html
spec/views/email_subscriptions/unsubscribe.html.erb_spec.rb

Removing even MORRRREE hardcoded links. We now have 90% of the hardcoded links removed. 
Just a couple of more left in some controllers that need some more testing. Will leave those for subsequent PR's 😓, but we getting there 😁.
https://github.com/thepracticaldev/dev.to/projects/15#card-35230751

Removal of morrrre hardcoded dev.to links

---

app/assets/images/chevron-right.svg
app/assets/javascripts/initializers/initializeBaseUserData.js
app/assets/stylesheets/article-show.scss
app/assets/stylesheets/moderators.scss
app/controllers/moderations_controller.rb
app/views/moderations/actions_panel.html.erb
app/views/moderations/mod.html.erb
config/routes.rb

Add the actions panel "Moderate Post" header.

Add header to actions panel

---

app/views/articles/show.html.erb

Basic alt tag so folks know they're looking at the article's cover image.

Add basic default alt for cover image

---

package.json

Enable Erblint's autocorrect in Husky

---

app/assets/stylesheets/components/snackbars.scss
app/assets/stylesheets/themes/night.scss
app/views/pages/crayons.html.erb

This PR changes the way Snackbars are stacked on top of each other.

Snackbars Improvements

---

app/javascript/Snackbar/Snackbar.jsx
app/javascript/Snackbar/SnackbarItem.jsx
app/javascript/Snackbar/SnackbarPoller.jsx
app/javascript/Snackbar/__stories__/Snackbar.stories.jsx
app/javascript/Snackbar/__stories__/SnackbarItem.stories.jsx
app/javascript/Snackbar/__stories__/SnackbarPoller.stories.jsx
app/javascript/Snackbar/__tests__/Snackbar.test.jsx
app/javascript/Snackbar/__tests__/SnackbarItem.test.jsx
app/javascript/Snackbar/__tests__/__snapshots__/Snackbar.test.jsx.snap
app/javascript/Snackbar/__tests__/__snapshots__/SnackbarItem.test.jsx.snap
app/javascript/Snackbar/index.js

This PR gives us the following application components. `<Snackbar />` and `<SnackbarItem />` and `<SnackbarPoller />`.
How the Snackbar works.
* You can have at most 3 snackbar items in the snackbar
* If more than 3 are added, the 3 newest are the ones that remain.
* The last snackbar item added is the first one to appear at the bottom in the snackbar.
* snackbar items have a default lifespan of 5 seconds which is configurable via the lifespan prop on the `<SnackbarPoller />` component. Once the lifespan has completed, the snackbar item is removed from the snackbar
* If a user mouses over the snackbar, all lifespans of snackbar items are paused.
* If a use mouses out of the snackbar area, the lifespan of snackbar items resumes.

Created Snackbar components

---

app/views/pages/contact.html.erb
app/views/pages/information.html.erb
app/views/podcast_episodes/_meta.html.erb
app/views/users/_meta.html.erb

Replaced hardcoded 'the practical dev' with the community name
#6858

Replaced hardcoded 'the practical dev' with the community name

---

app/models/podcast_episode.rb

I decided to remove Algolia from all the FeedContent models in separate PRs to make them a little more digestible and so if any bugs pop up they are easier to track down and fix. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32955089

Remove Algolia from Podcast Episode Model

---

app/models/podcast_episode.rb

Reverts thepracticaldev/dev.to#7453
Will investigate spec failures once Travis issues are fixed.

Revert "Remove Algolia from Podcast Episode Model"

---

app/view_objects/articles/social_image.rb

Fix height/width mismatch

---

app/controllers/application_controller.rb
app/controllers/concerns/image_uploads.rb
app/controllers/image_uploads_controller.rb
app/controllers/organizations_controller.rb
app/controllers/podcasts_controller.rb
app/controllers/users_controller.rb
spec/requests/image_uploads_spec.rb
spec/requests/organizations_update_spec.rb
spec/requests/podcasts/podcast_create_spec.rb
spec/requests/user/user_organization_spec.rb
spec/requests/user/user_settings_spec.rb

This PR validates filename lengths server-side. I'm going to circle back in another PR to remove the excessive Datadog logging and rescues.
https://github.com/thepracticaldev/dev.to/projects/9#card-36356085

Validate filenames server-side

---

app/controllers/stories_controller.rb
spec/requests/stories_show_spec.rb

I recently shipped some work (#7447) to optimize images on DEV for SEO purposes. This PR addresses the concern brought up in the PR that the code was not explicit enough--contributors and team members might not be aware that the images are sized for a specific reason, which might result in someone accidentally altering the sizes. To make the code more explicit, I extracted the images into a method, `seo_optimized_images`, and added inline documentation to give curious contributors and team members more background information on the code.
**Side note**: I did notice that there were some inconsistencies in the `stories_show_spec.rb` while I was working and took care of fixing some of those in this PR as well. 😊 
Closes #7479

Refactor SEO Optimized Images

---

package.json
yarn.lock

Apparently we haven't used this dependency since 2018 and the code for it was removed in #6903 anyway, hence this is not needed anymore.
#7463
#6903

Remove unused markedjs

---

spec/requests/internal/classified_listings_spec.rb

False-negative remnant from the Travis issue
n/a
n/a
n/a

Fix broken listing spec

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/javascript/actionsPanel/actionsPanel.js
app/javascript/actionsPanel/initializeActionsPanelToggle.js
app/javascript/packs/actionsPanel.js
app/views/articles/show.html.erb

This moves some code out of the asset pipeline and into Webpack, where it will only be loaded on the actions panel page.

Move initialize actions panel button to Webpack

---

app/controllers/internal/users_controller.rb
app/helpers/social_link_helper.rb
app/queries/internal/users_query.rb
app/views/internal/users/index.html.erb
spec/helpers/social_link_helper_spec.rb
spec/queries/internal/users_query_spec.rb

- Refactor internal User index html
- Extract filter and search logic from controller to a query object
- Create social link helpers

Refactor internal users index

---

app/javascript/actionsPanel/initializeActionsPanelToggle.js

Fixes the iframe's path from `/:article_path` to `/:article_path/actions_panel`. I made this mistake in a previous PR while fixing merge conflicts.

Fix iframe path

---

app/views/mailers/notify_mailer/new_mention_email.html.erb
app/views/mailers/notify_mailer/new_reply_email.html.erb

Add style for images on email to turn them responsiveness
Closes #1393

Add style for images on email to turn them responsiveness

---

db/seeds.rb

While reviewing #7497 I noticed how I didn't have listings appearing under their categories as in the seeds file we create categories after we create listings.

Create listings categories before listings in seed

---

app/controllers/internal/articles_controller.rb
app/controllers/internal/buffer_updates_controller.rb
app/javascript/internal/controllers/article_controller.js
app/labor/bufferizer.rb
app/models/buffer_update.rb
app/views/internal/articles/_image_upload_script.html.erb
app/views/internal/articles/_individual_article.html.erb
app/views/internal/articles/index.html.erb
spec/labor/bufferizer_spec.rb
spec/requests/buffer_updates_spec.rb
spec/requests/internal/buffer_updates_spec.rb

This PR rearranges and simplifies the interface for `internal/articles` to streamline the process of sharing to Buffer

Update design and functionality of internal/articles

---

app/assets/stylesheets/chat.scss
app/javascript/chat/chat.jsx
app/views/chat_channel_memberships/index.html.erb

Fix issue with channels paginating on scrolling, also fix some css issues.

Fix chatchannel pagination in connect

---

app/labor/bufferizer.rb

Params not properly lined up here

Line up params properly in Bufferizer

---

app/views/chat_channel_memberships/index.html.erb

Fix notice in accepting invites

---

app/javascript/searchableItemList/searchableItemList.js

Currently the pagination for a reading list is broken in production as instead of loading more items at the bottom it will load the new page and replace the existing one. 
You can see the behavior in this demo (I set the page size to 1 to make it easier to see):
There are 3 scenarios where changing the displayed items is correct: new text in the search box, new tag selected or unselected and "clear all tags"
There is a scenario where items need to be appended instead of replaced, which is the behavior of "load more"
(we don't really have JS tests for the reading list)
**after the fix**
**search**
**pagination of search results**
**pagination of tags results**

Fix reading list pagination

---

app/assets/stylesheets/settings.scss
app/models/user.rb
app/views/credits/new.html.erb
app/views/users/_billing.html.erb
app/views/users/_errors.html.erb
app/views/users/edit.html.erb

This PR contains the following:
1. fix for the settings/billing page (currently the buttons don't work)
1. display of server errors in credits/purchase
1. better error notice display for the settings pages
1. small fix to avoid breaking the settings profile page if the username is took long
I tried to write system tests for the billing page but I just can't make them work 🤷‍♂️ - I think it has something to do with the StripeMock library and JS timeouts. 
**truncate username above 30**
**new error notice**
**billing**
(using [Stripe testing cards](https://stripe.com/docs/testing), no leak ;-))
The UI isn't much better than the current one but we can work on that later I think

Fix settings billing section and other profile improvements

---

app/services/edge_cache/commentable/bust.rb
app/views/comments/index.html.erb
spec/services/edge_cache/commentable/bust_spec.rb

Couple small bug fixes that need addressing after [removing Algolia from Podcast Episodes](#7453 )
Spec failure is Flaky.

Bug Fixes: Remove index! From Cache Buster and Check for main_image method in view

---

app/views/internal/feedback_messages/_abuse_reports.html.erb
spec/requests/internal/feedback_messages_spec.rb

This fixes a small bug where `.title` was being called on a `User` instance, and led to `undefined method 'title' on User`.
Resolves https://github.com/thepracticaldev/tech-private/issues/352... again
Resolves Honeybadger error: https://app.honeybadger.io/projects/66984/faults/58419984

Show reactable username for reactable_type == User

---

spec/requests/internal/classified_listings_spec.rb

Closes https://github.com/thepracticaldev/dev.to/issues/7531

Escape titles to avoid encoding issues

---

app/assets/stylesheets/preact/onboarding-modal.scss

Closes https://github.com/thepracticaldev/dev.to/issues/7545.
Closes https://github.com/thepracticaldev/dev.to/issues/7544.
With this PR, you'll see the following changes:

Minor tweaks to onboarding UI

---

app/controllers/notifications_controller.rb
app/views/notifications/index.html.erb

Logic was a little messed up here. This rearranges things to fix it.

Fix notifications org select logic

---

app/controllers/search_controller.rb
app/javascript/listings/listings.jsx
app/services/search/query_builders/classified_listing.rb
spec/services/search/query_builders/classified_listing_spec.rb

This PR will fix the listing tags bug. Changes made in the query for fetching data from ES.After the Change only if all the tags are present the article will be fetched.
Closes https://github.com/thepracticaldev/dev.to/issues/7513

Fix listing tags bug

---

app/javascript/actionsPanel/actionsPanel.js
app/javascript/actionsPanel/initializeActionsPanelToggle.js
app/javascript/packs/actionsPanel.js
app/javascript/packs/loadActionsPanelButton.js
app/views/articles/show.html.erb
app/views/moderations/actions_panel.html.erb

This adds the open/close interaction to the mod actions panel. Also starts to move some of the code into Webpack.
https://share.getcloudapp.com/wbu0PRr7

Add close button interaction

---

app/models/article.rb
app/services/moderator/delete_user.rb
app/services/users/delete_articles.rb
app/workers/articles/score_calc_worker.rb
lib/data_update_scripts/20200217131245_re_index_existing_articles_with_approved.rb
spec/lib/data_update_scripts/re_index_existing_articles_with_approved_spec.rb
spec/models/article_spec.rb

Remove Algolia from Article model since we are no longer using it 🙌 
CodeClimate can be ignored, not sure why it has an issue when this is just removing code. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32955097

Remove Algolia from Article Model

---

app/views/users/_notifications.html.erb
app/views/users/_profile.html.erb
app/views/users/_ux.html.erb

This PR fixes alignment of **Save** button in the profile section in http://dev.to/settings
Closes https://github.com/thepracticaldev/dev.to/issues/7560

Fixing alignment of save button in profile page

---

spec/services/search/query_builders/classified_listing_spec.rb
spec/services/search/query_builders/feed_content_spec.rb
spec/services/search/query_builders/reaction_spec.rb
spec/services/search/query_builders/user_spec.rb

Fix typos in query_builder spec files. Creating a PR as request from https://github.com/thepracticaldev/dev.to/pull/7533

Fix typos in specs

---

app/assets/stylesheets/preact/onboarding-modal.scss

Resolve https://github.com/thepracticaldev/dev.to/issues/6884
Before: 
After:
n/a

Fix 'Suggested people' small viewport issue

---

.github/PULL_REQUEST_TEMPLATE.md

Some updates to the PR template.

Linked to CoC and Contrib guide, plus explicit message about small PRs.

---

app/views/internal/configs/show.html.erb

Rename the name of the field appropriately. `Community member label instead` of `Community member name`.

Rename Config Field Name

---

.github/PULL_REQUEST_TEMPLATE.md
docs/self-hosting.md

In [PR 7569](https://github.com/thepracticaldev/dev.to/pull/7569) the suggestions that were accepted and committed didn't get into the codebase because github is weird sometimes 🤷🏽‍♀️
https://github.com/thepracticaldev/dev.to/pull/7569#issuecomment-620815728
No

Implement sentence construction changes on PR template

---

app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/preact/onboarding-modal.scss

Both of these I guess?
Add `:focus-within` for better tab navigation
Resolve https://github.com/thepracticaldev/dev.to/issues/6843
In this picture, I am using `tab` ,`shift + tab` , and `space bar` to navigate and select each tags.
n/a

Add focus-within for tab navigation in FollowUsers

---

app/models/user.rb

Not sure how this method came to be or why it was ever here but I think its time for it to go.

Remove redundant user method from User Model

---

app/assets/stylesheets/preact/onboarding-modal.scss

The current onboarding flow at https://dev.to/onboarding contains jumpiness when waiting for content to load which can be avoided with some small adjustments.

Fix jumping content in obboarding

---

spec/requests/articles/articles_show_spec.rb

#7633 didn't work in prod, turning off the spec entirely since at this point we're trying to test broken code anyways.
#7633

Turn off broken article show spec - date time

---

app/labor/rate_limit_checker.rb
app/views/internal/configs/show.html.erb

Refactor the HTML used to set Rate limits. Lots more refactoring to come but this was a quickie that eliminated a lot of lines that I thought I could separate from the rest.

Refactor Setting Internal Configurable Rate Limits

---

app/controllers/concerns/image_uploads.rb
app/controllers/image_uploads_controller.rb
app/controllers/organizations_controller.rb
app/controllers/podcasts_controller.rb
app/controllers/users_controller.rb
spec/requests/image_uploads_spec.rb
spec/requests/organizations_update_spec.rb
spec/requests/podcasts/podcast_create_spec.rb
spec/requests/user/user_organization_spec.rb
spec/requests/user/user_settings_spec.rb

IYKYK https://app.honeybadger.io/fault/66984/2a89412ed02b0ef11284dc39723b1d0d
Fixes a bug when validating images to check if the image is a file or not.
https://app.honeybadger.io/projects/66984/faults/63373395

Validate images are files

---

app/controllers/stories_controller.rb
spec/requests/stories_index_spec.rb

While working on handling redirects for uppercase usernames (#7550 ), I came across other methods in the `Stories::Controller` that use `.downcase`. The previous PR (#7550 ) handles redirecting from uppercase usernames to lowercase usernames, making some of the `.downcase`s in the `Stories::Controller` unnecessary. This PR removes some of the`.downcases` from the `Stories::Controller` since the downcasing should be handled by PR #7550 .
To test that this works properly navigate to one of the index pages effected (user, organization, or podcast) by the removal of the `.downcase`s and test that the route (on the index page only) redirects to the lowercase version of the route when the capitalized version is given.
Closes #7580

Remove Unnecessary .downcases From the Stories::Controller

---

docs/installation/windows.md

Node.js 8 is beyond deprecated and unsupported.
Updating the docs to have the contributors install the same version of Node.js we use on Linux and macOS
Closes https://github.com/thepracticaldev/dev.to/issues/7645

Update Windows 10 installation docs

---

app/controllers/api/v0/api_controller.rb
app/controllers/application_controller.rb
app/controllers/comments_controller.rb
app/controllers/follows_controller.rb
app/controllers/image_uploads_controller.rb
app/controllers/organizations_controller.rb
app/labor/rate_limit_checker.rb
app/services/articles/creator.rb
app/services/articles/updater.rb
spec/labor/rate_limit_checker_spec.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/articles/articles_create_spec.rb
spec/requests/comments_create_spec.rb
spec/requests/user/user_organization_spec.rb

Consolidate the controller logic used to check the rate limit for an action and then raise an error if that action has exceeded its limit.

RateLimit Refactor: Consolidate Logic for Checking a Limit and Raising an Error

---

app/controllers/stories_controller.rb
app/models/classified_listing.rb
app/views/classified_listings/index.html.erb
config/routes.rb
db/migrate/20200501032629_remove_category_from_classified_listing.rb
db/schema.rb
db/seeds.rb
spec/requests/api/v0/classified_listings_spec.rb

This PR removes the `category` column from the `classified_listings` table and includes some minor cleanups that were brought up during review of #7498.
Closes #6740. Tears of joy.

Remove column and minor cleanup

---

Gemfile.lock

Upgrade Doorkeeper to 5.3.2

---

app/assets/stylesheets/moderators.scss
app/javascript/actionsPanel/actionsPanel.js
app/javascript/packs/actionsPanel.js
app/views/moderations/actions_panel.html.erb

This moves all of the JS logic into Webpack, and refactors that code a bit. Also adds the tag adjustments section with the proper specs, with conditional rendering.
Note: the interaction logic of the tag adjustment is not here yet, because I'm waiting on https://github.com/thepracticaldev/dev.to/pull/7603. I have some of that code worked out, just won't be including it in this PR so I don't have to deal with weird git issues later on.
https://share.getcloudapp.com/jkul4JNq

Move more code to Webpack and add conditional tag adjustments section

---

app/controllers/image_uploads_controller.rb
app/controllers/organizations_controller.rb
app/labor/rate_limit_checker.rb
app/services/articles/updater.rb
spec/labor/rate_limit_checker_spec.rb

Refactor tracking methods for rate limits.

Refactor Tracking Rate Limits for Actions

---

jest.config.js

Similar how to GitLab does it https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/jest.config.js
Resolves https://github.com/thepracticaldev/dev.to/issues/5279
n/a
n/a

Set Jest's timezone to UTC

---

app/controllers/moderations_controller.rb

Add missing variable oops

---

app/models/organization.rb
app/workers/organizations/update_organization_articles_paths_worker.rb
spec/workers/organizations/update_organization_articles_paths_worker_spec.rb

Handles Organization's articles paths update in a background job
Closes https://github.com/thepracticaldev/dev.to/issues/7355

Fix 503 error on organisation rename

---

CONTRIBUTING.md

changed "biproduct" -> byproduct"
changed "submit" -> "submitted"
used Grammarly to check for typos

two minor typo changes (according to Grammarly)

---

app/services/rate_limit_checker.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/articles/articles_create_spec.rb
spec/requests/image_uploads_spec.rb
spec/requests/user/user_organization_spec.rb
spec/services/rate_limit_checker_spec.rb

This is the last rate limit refactor I am going to do for now. With this final refactor we have the ability to simply add a key to `ACTION_LIMITERS` and `CONFIGURABLE_RATES` and have all the functionality and methods we need to start tracking and limiting simple user actions. I also moved the checker from labor to services since that is what this is really morphing into. 
There is a lot more complicated refactoring that could be done here but I thought this gave us some good bang for our buck and I should be able to whip through some of those rate limit tickets we have now.

Refactor Checking Rate Limits and Their Retry After settings

---

app/assets/stylesheets/comments.scss

We just submitted _two_ quick fixes to the same problem, which happened to not conflict with one another. Nice job jumping on it, this fixes the non-breaking current conflict. 😄

Fix double-fix of comment container

---

app/controllers/users_controller.rb
spec/requests/user/user_destroy_spec.rb

Don't allow users to request destroy multiple times.

Dont Allow Multiple User Destroy Requests

---

app/javascript/crayons/Button/Button.jsx
app/javascript/crayons/Button/__tests__/Button.test.jsx
app/javascript/crayons/Button/__tests__/__snapshots__/Button.test.jsx.snap

I found this prop missing in our current Button component when I needed it.

Adding tabIndex prop to Buttons component

---

db/seeds.rb
spec/factories/broadcasts.rb

This PR adjusts the copy for both the GitHub and Twitter connect notifications.
I will need to update the production Broadcasts to include the new copy.

Adjust GitHub and Twitter Connect Copy for Broadcasts

---

app/dashboards/classified_listing_category_dashboard.rb

Not really a bug per se, but I forgot to add the social preview fields to the actual forms in the Administrate dashboard and #7679 got merged before I had a chance to add them.
#7643

Add social preview fields to dashboard

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/views/layouts/_nav_menu.html.erb

Improve maintainbility 
n/a
n/a
n/a

Move first-nav-link from dynamic JS to erb

---

app/controllers/users_controller.rb

PR #7685 got merged before the comments were implemented, and since several reviewers agreed I took 5 minutes and added them in a separate PR.
PR #7685 follow up

Multiple user destroy request follow up

---

app/controllers/users_controller.rb
app/helpers/rate_limit_checker_helper.rb
app/services/rate_limit_checker.rb
app/views/internal/configs/show.html.erb
spec/helpers/rate_limit_checker_helper_spec.rb

In #7683 we [discussed](https://github.com/thepracticaldev/dev.to/pull/7683/files#r420537240) moving the constant from the model to a view helper:
n/a

Add RateLimitCheckerHelper

---

app/views/layouts/internal.html.erb

Switch from rainbowdev to the sticker as an alt internal logo.

Generalize internal logo

---

app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/IntroSlide.jsx

This PR fixes scrolling issues on mobile resolutions.

Onboarding fix for mobile

---

app/views/articles/search/_meta.html.erb
app/views/articles/show.html.erb
app/views/mailers/pro_membership_mailer/expiring_membership.html.erb
app/views/mailers/pro_membership_mailer/expiring_membership.text.erb
app/views/sitemaps/show.xml.erb
app/views/users/_org_admin.html.erb
app/views/users/_profile.html.erb

Replaced urls that contained`ApplicationConfig["APP_DOMAIN"]` with `app_url` in views.

Replaced ApplicationConfig with app_url in views

---

app/controllers/stories_controller.rb
spec/requests/articles/articles_show_spec.rb

This PR refactors the `articles_show_spec.rb` to better test the structured data for articles and organizations within the `Stories::Controller`.
Relates to #7495

Refactor articles_show_spec to Better Test JSON-LD

---

app/assets/stylesheets/article-show.scss
db/schema.rb

Ensuring that the ModPanel Button does not block the Reactions Bar on mobile devices.
none
https://streamable.com/0l3x7j
none

Adjust ModPanel Button position on mobile

---

app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/ProfileForm.jsx
app/javascript/packs/Onboarding.jsx
app/views/onboardings/show.html.erb
config/environments/production.rb

Replacing some hardcoded values in onboarding.
Pretty small change, but touches 7 files due to snapshot tests and that it adds a new prop to the components.

Add generalized community name and description to onboarding slides

---

app/views/internal/negative_reactions/index.html.erb
spec/factories/reactions.rb
spec/requests/internal/negative_reactions_spec.rb

This fixes a bug that is currently affecting production regarding negative reactions on users.

Fix bug regarding negative reactions on users

---

app/assets/stylesheets/dashboard.scss
app/views/dashboards/followers.html.erb

Add Follow button beside follower's name in the followers section of the Dashboard.
Resolves #3169

Add Follow button to Dashboard Followers view

---

app/javascript/actionsPanel/actionsPanel.js

Final bug fixes mod panel

---

app/controllers/internal/feedback_messages_controller.rb

Following @guivinicius 's work to optimize internal controllers. Adding `limit` and only selecting necessary column to speed up load time.
Resolves https://github.com/thepracticaldev/dev.to/issues/6674
n/a
n/a

Optimize FeedbackMessagesController#index

---

config/initializers/honeycomb.rb
datadog/prerun.sh

Send data from background jobs and scheduled workers to a different data set in Honeycomb to allow us to build up more data in our main rails data set.

Dont configure Honeycomb if its disabled

---

app/liquid_tags/codesandbox_tag.rb
spec/liquid_tags/codesandbox_tag_spec.rb

Added support for a `view` option to CodeSandbox liquid tag.
--
--

Allow to specify view parameter for codesandbox

---

app/javascript/packs/feedIcons.js.erb

The feedIcons.js.erb file is no longer being used.

Removed feedIcons.js.erb as the file is no longer being used.

---

app/assets/stylesheets/components/comments.scss
app/assets/stylesheets/themes/hacker.scss
app/assets/stylesheets/themes/minimal.scss
app/assets/stylesheets/themes/night.scss

This fixes an issue where _all) internal elements are block here. Also hotfixes a coloring issue on different themes. Also modestly reduces max-height for story comment body
👆 this should all be inline...

Fix inline/box issue in story feed comments

---

app/javascript/article-form/elements/__tests__/tags.test.jsx
app/javascript/src/utils/__tests__/search.test.js
app/javascript/src/utils/search.js

This is just some refactoring before I start working on an updated search box implementation.

fetchSearch now uses @utilities/http/request under the hood now.

---

app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap

Currently, these show up when you run `yarn test -u` on `master` locally, so I think they should probably be committed :)

Update Article snapshots

---

app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/__tests__/utilities/articleUtilities.js

Remove hard-coded published_at_int

---

app/javascript/chat/channels.jsx
app/javascript/chat/chat.jsx

There were some inconsistent API issues here fixed. Also removed an errant `console.log`

Fix connect runtime error

---

app/liquid_tags/codesandbox_tag.rb

Implement changes discussed in previous PR (https://github.com/thepracticaldev/dev.to/pull/7781)
--
--

Make a constant for long inline regexp

---

app/assets/javascripts/utilities/buildArticleHTML.js.erb
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap

This PR fixes huge video icon in the feed card.
Closing #7791

Hotfix video icon in feed

---

Procfile.dev
docs/.gitdocs.json
docs/installation/linux.md
docs/installation/mac.md
docs/installation/windows.md

As per #7706, add support for developing dev.to on a remote computer. Update installation docs.

Adapt dev env to use remote box

---

app/javascript/articles/__tests__/Article.test.jsx
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/__tests__/utilities/articleUtilities.js

Adds tests to accompany the work done in #7821
#7821

Added tests.
