forem/forem

config/initializers/sidekiq.rb

For some reason the `Sidekiq::WorkerRetriesExhaustedReporter` is not loading properly in production which is [causing this error] when the Sidekiq dealth handlers are triggered. (https://app.honeybadger.io/fault/66984/9b4d0fd229b813dd9443870cd209b732) when a worker dies:
```
NameError: uninitialized constant Sidekiq::WorkerRetriesExhaustedReporter
sidekiq.rb  31 block (2 levels) in <main>(...)
[PROJECT_ROOT]/config/initializers/sidekiq.rb:31:in `block (2 levels) in <main>'
29   # of it's retries. For more details: https://github.com/mperham/sidekiq/wiki/Error-Handling#death-notification
30   config.death_handlers << lambda do |job, _ex|
31     Sidekiq::WorkerRetriesExhaustedReporter.report_final_failure(job)
32   end
33 end
```
I was able to reproduce this in a production console and fix …

Require worker_retries_exhausted_reporter in Sidekiq initializer

---

docs/installation/docker.md

Recent updates for the Docker `rails data_updates:run` had typos in the command.
https://github.com/thepracticaldev/dev.to/pull/6097
https://github.com/thepracticaldev/dev.to/issues/6094#issuecomment-586807819

Fix markdown and missing command in rails data_updates:run

---

app/services/search/base.rb
app/services/search/classified_listing.rb
app/services/search/tag.rb
spec/models/tag_spec.rb
spec/services/search/classified_listing_spec.rb
spec/services/search/tag_spec.rb

Refactor the common search methods into a single search based class that other search models can inherit from. I choose to do this now bc I am getting ready to roll over our third Elasticsearch model and didn't want to repeat all this logic a 3rd time. I did not refactor the specs in this PR but that should be done at some point. 
Spec coverage is still handled by the individual classes

Refactor Common Search Methods into a Base Class

---

app/assets/javascripts/initializers/initScrolling.js.erb
app/controllers/api/v0/followers_controller.rb
app/controllers/dashboards_controller.rb
app/controllers/notifications_controller.rb
app/views/api/v0/followers/organizations.json.jbuilder
config/routes.rb
spec/requests/api/v0/followers_spec.rb
spec/requests/notifications_spec.rb

Once upon a time a user could belong only to a single organization, but then the mighty @Zhao-Andy submit two PRs - https://github.com/thepracticaldev/dev.to/pull/2471 and https://github.com/thepracticaldev/dev.to/pull/2583 - allowing users to join more than one org.
Some breadcrumbs of those olden times though remain, and as I set to get rid of them I also noticed some oddities in our code:
- we have a `/api/followers/organizations` that returns the list of followers of the original legacy organization of those users that have `users.organization_id` populated (if you don't, as the vast majority of users), it does not return anything
- we don't use `/api/followers/organizations` anywhere in the code, but as it's part of the API we can't remove it, so I set out to simply make it return …

Stop using legacy user's organization_id and remove followers unused code

---

config/initializers/reserved_words.rb

In #6127 we removed `dev.to/history` - I think we should add it as a reserved word before it gets "squatted" :D

Add history as a reserved word

---

app/controllers/internal/configs_controller.rb
app/controllers/stories_controller.rb
app/models/html_variant.rb
app/models/site_config.rb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/_sidebar_campaign.html.erb
app/views/html_variants/_form.html.erb
app/views/html_variants/index.html.erb
app/views/internal/configs/show.html.erb
app/views/layouts/application.html.erb
spec/requests/stories_index_spec.rb

This is basically Anna's PR which I could not contribute to/edit  (but I needed it merged and also the latest master pulled in to order to move forward whilst she's on vacation). The original PR is  (https://github.com/thepracticaldev/dev.to/pull/5892) and I will close it.  I added her changes and some of the fixes based on some of the suggestions.
**Anna's description:** 
I started working on settings for Shecoded 2020 campaign and further campaigns in this pr:
- added `SiteConfig` settings for campaigns:
- `campaign_hero_html_variant_name` (name of the html variant that will be used to display campaign banner/hero over the feed)
- `campaign_background_color`, `campaign_text_color` (these settings will be used to configure a campaign's appearance, not used in the code right now besides …

Campaign settings

---

config/application.rb
spec/requests/api/v0/articles_spec.rb

Now that CORS has been enabled on public APIs - https://github.com/thepracticaldev/dev.to/pull/6116 - I went ahead and tested manually to check if it was working live and it is.
We can now re-enable the CORS preflight cache to a default value. I chose 2 hours because it's the default for `rack-cors` and it's also the lowest maximum value between Chromium and Firefox (Chromium caps the cache to 2 hours, Firefox to 24 hours).
FYI: CORS preflight caching means that the client doesn't have to re-issue the `OPTIONS` HTTP call to query the capabilities of the server before each call that requires CORS
#6116 
#4195

Enable CORS preflight caching for API

---

Procfile.dev

When working on a local environment there's limited access to a "mobile device experience". I've used [xip.io](https://xip.io) before and works like a charm to access your localhost environment from within your LAN using your mobile device.
For those who are not familiar: If your workstation has a DEV server running on `localhost` and your IP address is `192.168.0.100` you can access it from your mobile devices (within the same LAN) by browsing `192.168.0.100.xip.io:3000`.
The problem here is that an explicit bind to `0.0.0.0` is required, because rails connects to the `127.0.0.1` interface only and this is not accessible from within the LAN.
None that I could find
N/A
Nope, this is a change that only affects local environments

Adds explicit 0.0.0.0 bind option to Procfile.dev

---

app/models/concerns/searchable.rb
app/models/tag.rb

I know this logic is only being pulled out of one place here but we are about to add two more searchable models and this will cut down on the code duplication for those.
[ClassifiedListings](https://github.com/thepracticaldev/dev.to/pull/6132 )
ChatChannelMemberships
I thought about also putting the after_commit block in there but I wanted more control in the models for when indexing happens since it might not be after every commit for every model. 
Once again tests could be refactored but I choose to save that for a later PR. For now the testing is handled by the model specs.

Refactor Searchable Interface into a module for AR Models

---

app/workers/search/index_worker.rb

We got some Honeybadgers from trying to index PageViews. I could not find anywhere in the code where we still do that but I did notice the job still considers them valid so I removed PageView from the valid list. My best guess is that the jobs were enqueued from a console with old code maybe 🤷‍♀

PageView is no longer a valid model to index

---

config/initializers/datadog_apm.rb

This should allow us to track and monitor [our requests to Elasticsearch via Datadog.](https://docs.datadoghq.com/tracing/setup/ruby/#elastic-search)
https://github.com/thepracticaldev/dev.to/projects/6#card-33076445

Enable Elasticsearch Tracing with Datadog APM

---

app/assets/stylesheets/classified_listings.scss

We recently merged #2826 and I thought the menu location was a bit off, but it shouldn't hold up the PR, so this is a follow-up.
Small padding adjustment
Current:
New:

Modify padding for classifiedlisting dropdown

---

app/models/article.rb
spec/models/article_spec.rb

Here we rescue one type of parsing error, but another one has been showing up in Honeybadger, `Psych::DisallowedClass:` and I think we should handle that the same as we handle the Syntax error. 
Honeybadger: https://app.honeybadger.io/fault/66984/599a7871be018f4d14f33909795a9c48
https://github.com/thepracticaldev/dev.to/projects/5#card-32287912

Rescue Psych::DisallowedClass when parsing frontmatter

---

app/views/articles/_sidebar_additional.html.erb
app/views/articles/index.html.erb
app/views/stories/_main_stories_feed.html.erb

This adds the `HEROKU_SLUG_COMMIT` environment variable to some fragment caches to ensure that deployments result in fewer cache mismatches.

Add heroku slug commit to some cache keys

---

app/views/stories/feeds/show.json.jbuilder
spec/requests/stories/feeds_spec.rb

Changes the names of some fields in the new home page feed JSON to match key names that were being translated in the template. This will let these JSON values flow directly to Preact components on the new home page.
`cached_user` -> `user`
`cached_organization` -> `organization`
`cached_tag_list_array` -> `tag_list`

Change some feed JSON field names

---

app/models/chat_channel_membership.rb
app/serializers/search/chat_channel_membership_serializer.rb
app/workers/search/chat_channel_membership_es_index_worker.rb
lib/data_update_scripts/20200218195023_index_chat_channel_memberships_to_elasticsearch.rb
spec/lib/data_update_scripts/index_chat_channel_memberships_to_elasticsearch_spec.rb
spec/models/chat_channel_membership_spec.rb
spec/workers/search/chat_channel_membership_es_index_worker_spec.rb

This PR begins indexing all ChatChannelMemberships when they are created or updated. It also has a DataUpdateScript to index all existing ones.
https://github.com/thepracticaldev/dev.to/projects/6#card-32289280

Index ChatChannelMemberships to Elasticsearch 

---

app/labor/random_gif.rb

I removed this gif: https://media.giphy.com/media/82lalqBsmW56Z6E2oV/giphy-downsized.gif
form the rotation because it was not available anymore.
Even if link work in the browser, it does not when displayed in the notifications screen.
See below:
Fixes #4606

Remove unavailable gif

---

spec/requests/stories_index_spec.rb

Some specs randomly fail with:
```text
1) StoriesIndex GET stories index with campaign hero doesn't display when hero html is not approved
Failure/Error: expect(response.body).not_to include(CGI.escapeHTML(hero_html.html))
expected "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <title>DEV(local) C...6a5bca60a4ebf959a6df7f08217acd07ac2bc285164fae041eacb8a148b1bab9.svg\" />\n  </body>\n  </html>\n\n" not to include "A Monstrous Regiment of Women"
```
this happens because when the text contains an escapable char, `CGI.escapeHTML` will change its value. 
The thing is, the hero HTML is not escaped, coming from a trusted source, thus the test itself shouldn't assume it is escaped.

Fix homepage campaign hero spec escaping

---

app/controllers/internal/podcasts_controller.rb
app/views/internal/podcasts/index.html.erb
spec/requests/internal/podcasts_spec.rb

I found out that the `/internal/podcasts` page was broken because of referring to `podcast.podcast_episode.size` instead of `podcast.podcast_episodes.size`, and the test was not failing because we were selecting only podcasts with episodes for the internal.
So, in this pr I:
- fixed the `/internal/podcasts` page by referring to `podcast.episodes_count` because the episodes count was already selected in the controller
- replaced `join` with `left_outer_join` so that the page would display podcasts without episodes

Fix podcasts internal page

---

app/workers/search/tag_es_index_worker.rb

@citizen428 made a [great observation](https://github.com/thepracticaldev/dev.to/pull/6132#discussion_r380437346) about using `find` over `find_by!(id: id)` for better error messaging. This is a quick (nitpick) change to keep things in a consistent pattern across all the search workers.

Change find_by to find for better error messaging on Tags

---

app/views/internal/feedback_messages/index.html.erb

Because confirming a User vomit is a particularly destructive task, we
want to make it a bit more intentional. Ben recommended adding a confirm
dialog for these reports.
This commit also satisfies erblint's complaints regarding the select
element in the ransack search form.
Ben mentioned this in Slack.

Add JS confirm to confirmation of user vomits

---

app/services/notifications/moderation.rb
app/services/notifications/moderation/send.rb
app/workers/notifications/moderation_notification_worker.rb
spec/services/notifications/moderation/send_spec.rb
spec/workers/notifications/moderation_notification_worker_spec.rb

While testing another PR I noticed how I got a moderation notification for a comment that I just left:
The chances for this to appear in production are slim given that we manually select who's a moderator, though we should probably guard against this anyway

Skip moderation notification if the user is the moderator

---

app/views/liquid_embeds/show.html.erb
spec/requests/liquid_embeds_spec.rb

Embeds should open in parent context instead of the iframe itself for expected behavior.
This is accomplished by adding `<base target="_parent">` to the page.

Add base element to open embed links in parent context

---

app/helpers/application_helper.rb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/index.html.erb
app/views/stories/_main_stories_feed.html.erb
spec/helpers/application_helper_spec.rb

Adds a `cache_key` helper which appends `ApplicationConfig['HEROKU_SLUG_COMMIT']` to the provided key.
No ticket, but the result of a [PR discussion with Ben](https://github.com/thepracticaldev/dev.to/pull/6159/files#r381112382).

Add cache_key helper

---

app/views/service_worker/index.js.erb

Now the service worker intercepts social previews:
It shouldn't :D

Disable service worker on social previews

---

app/controllers/search_controller.rb
spec/requests/search_spec.rb

When someone enters an invalid tag name into our search box it can cause an Elasticsearch BadRequest error which gets raised to Honeybadger. Since there is nothing we can really do about it we should record the error and instead return an empty dataset. 
I choose to record the error bc if this happens over and over again either our code is broken or we have a bad actor hitting us that we should address.
https://github.com/thepracticaldev/dev.to/projects/6#card-33292262

Gracefully Handle Elasticsearch BadRequest Errors for Tags

---

app/models/chat_channel_membership.rb
app/models/classified_listing.rb
app/models/concerns/searchable.rb
app/models/tag.rb
app/services/search/base.rb
app/workers/search/remove_from_elasticsearch_index_worker.rb
spec/models/chat_channel_membership_spec.rb
spec/models/classified_listing_spec.rb
spec/models/concerns/searchable_spec.rb
spec/models/tag_spec.rb
spec/services/search/chat_channel_membership_spec.rb
spec/services/search/classified_listing_spec.rb
spec/services/search/tag_spec.rb
spec/workers/search/remove_from_elasticsearch_index_worker_spec.rb

In addition to the ability to index documents we also need the ability to remove them from Elasticsearch when a document is deleted. This PR adds a new method to our `Search::Base` class for deleting documents in Elasticsearch. It also adds a SINGLE 🎉  new worker to handle removing them.  
https://github.com/thepracticaldev/dev.to/projects/6#card-33385085

Add Worker and callback For Removing Elasticsearch docs

---

db/seeds.rb

Currently, we have limitations on usernames to be 30 characters and emails to be 50 characters.
However, we rely on the Faker gem to generate mock data in our `seeds.rb`, which can at times produce larger values and fail the build.
This commit ensures username and email length do not fail on generation.
(To test this yourself, you can run on a clean database `SEEDS_MULTIPLIER=10 rails db:setup` and see it break before finishing)

Ensure seeds.rb does not fail validation

---

app/labor/mailchimp_bot.rb

Fixes https://app.honeybadger.io/fault/66984/0ea3a11ef6835ae5098cb4a92ddf3e08
```
NameError: undefined local variable or method `logger' for #<MailchimpBot:0x00007f43438b34f8>
mailchimp_bot.rb  165 report_error(...)
[PROJECT_ROOT]/app/labor/mailchimp_bot.rb:165:in `report_error'
163 
164   def report_error(exception)
165     logger.error(exception)
166     DataDogStatsClient.increment("mailchimp.errors", tags: [action: "failed", user_id: user.id, source: "gibbon-gem"])
167   end
```

Fix logger in Mailchimp bot

---

app/models/user.rb
spec/liquid_tags/classified_listing_tag_spec.rb
spec/liquid_tags/link_tag_spec.rb
spec/requests/api/v0/followers_spec.rb
spec/requests/articles/articles_update_spec.rb
spec/support/api_analytics_shared_examples.rb

As we stopped using `User.organization_id` in #6079 and nothing broke, we can now do step 1 of 2 of removing the `organization_id` column.
Step 1 is to tell AR to ignore the column
Step 2 will be to actually remove it from the DB with:
```ruby
class RemoveUserOrganizationId < ActiveRecord::Migration[5.2]
def change
safety_assured { remove_column :users, :organization_id, :integer }
end
end
```
Thanks to [strong-migrations](https://github.com/ankane/strong_migrations#removing-a-column) which helps in these cases :)

Ignore User.organization_id

---

app/services/users/delete_activity.rb
spec/services/users/delete_spec.rb

When deleting users we did not properly clean up their private chat channels. I recently did some work of that in the context of banishing users and thought it makes the most sense to use the same service object when deleting users.
Closes #6216

Clean up chat channels when deleting users

---

app/controllers/api/v0/followings_controller.rb
app/controllers/api/v0/github_repos_controller.rb
spec/requests/api/v0/github_repos_spec.rb

This PR fixed incorrect usage of `current_user` instead of `@user` in several API controllers.
Closes #6119

Return a Unauthorized Error from API when Current User is Not Found

---

config/database.yml
config/environments/development.rb
docs/faqs.md

By default Rails to `log/development.log`, but this way we kind of lose the ability to log to STDOUT for who prefers that, and if one doesn't remember they won't see any output when running scripts (both the seed file which use to log in STDOUT and all the new data update scripts).
I'm `RAILS_LOG_TO_STDOUT` which is the default env var that's also enabled in `production.rb`.
If a person wants to log to STDOUT all they need to do is to add that variable to their `application.yml`

Optionally log to stdout

---

app/views/stories/feeds/show.json.jbuilder
spec/requests/stories/feeds_spec.rb

This PR "cloudifies" article main image URLs that are rendered in the new home page feed JSON. This transformation was previously done on the client side: we're doing it server side in our continuing effort to centralize feed logic on the backend.
Related conversation: https://github.com/thepracticaldev/dev.to/pull/6164#discussion_r382371573

Cloudify article main images in feed

---

db/migrate/20200221170905_remove_user_organization_id.rb
db/schema.rb

With #6079 we stopped using `User.organization_id` in favor of `user.organizations`, with #6203 we told the app to ignore the field and fixed the last remaining specs, with this PR we get rid of the field altogether.
Checkout https://github.com/ankane/strong_migrations#removing-a-column for the meaning of `safety_assured`.
#6079 
#6203

Remove User.organization_id

---

.erb-lint.yml

This PR is a part of a work to get rid of calls of html_safe in views. 
Though it is not the case in this very PR.
But the styles file has 55+ warnings when linted. A special case as this file includes assets and make a heavy use of html_safe. And I think it deserves a PR on its own to explain why I chose to exclude the file from linting rather than use an alternate solution.
If the css files are escaped, some css syntax like `table < body `
will be escaped like: `table &gt; body`.
Which is not what we are looking for.
The magic comment frozen_string_literals does not work, applying freeze to:
Rails.application.assets["scaffolds.css"] does not prevents Rails to escape some characters.
raw Rails.application raise the same warning as html_safe.
I think that since the styles are compiled in …

Excludes styles from (future) erb lintings

---

db/migrate/20200221170905_remove_user_organization_id.rb

Strong migrations only runs in dev and test so when we try to run this in prod we get this error
```
undefined method `safety_assured' for #<RemoveUserOrganizationId:0x000000000c64f760>
```

Remove Strong Migration safety_assured From Migration

---

Gemfile
config/initializers/strong_migrations.rb
db/migrate/20200221170905_remove_user_organization_id.rb

When we merged #5522 we weren't familiar with the gem and opted to enable it only in development, but to be effective this gem should be enabled in production as well, being able to catch unsafe migrations if they somehow skip our PR review process.
By merging #6242 we broke deploy because the https://github.com/ankane/strong_migrations gem wasn't enabled in production. @mstruve quickly fixed it with #6277
This should fix the underline problem we have triggered

Enable strong-migrations in all environments

---

docs/faqs.md
docs/installation/postgresql.md
docs/readme.md
docs/troubleshooting.md

I wrote down some notes about the errors I have been having lately with Elasticsearch (kudos to @mstruve for the assistance!).
I also noticed how some sections are not reachable right now in production:
should instead be
Closes https://github.com/thepracticaldev/dev.to/issues/6085 as it's not an error we can control :)

Add troubleshooting section to docs and restore hidden sections

---

.vscode/settings.json
spec/models/comment_spec.rb

Sometimes, the Comment spec named `"retains content from #processed_html"` randomly failed. This was happening only when the Comment model was created with a `body_markdown` that included special characters, e.g. `&` as in: `Migas fingerstache pbr&b tofu.` from `Faker::Hipster` module.
The `expect` part was comparing `&` with `&amp;` which was failing the spec. By unescaping both parts, this flaky is fixed.
Resolves https://github.com/thepracticaldev/dev.to/issues/6251
I'm not sure if there is an existing issue, I couldn't find one.

Fix Flaky Comment Spec

---

app/models/user.rb
spec/models/user_spec.rb

I've also removed mastodon_url validation from
```ruby
validates :website_url, :employer_url,
url: { allow_blank: true, no_local: true, schemes: %w[https http] }
```
because we've already validated in `validate  :validate_mastodon_url`.
Fixes #6142

add rescue InvalidURIError in mastodon_url validation

---

db/migrate/20200224153122_add_title_website_url_indexes_to_podcast_episodes.rb
db/schema.rb

Everytime `Podcasts::GetEpisodesWorker` is called we call `Podcast#get_episode` which executes both or only the first one of these queries:
```sql
SELECT podcast_episodes.* 
FROM podcast_episodes 
WHERE ( ( podcast_episodes.media_url = ? OR podcast_episodes.title = ? ) OR podcast_episodes.guid = ? )
```
```sql
SELECT podcast_episodes.* 
FROM podcast_episodes 
WHERE podcast_episodes.website_url IS NULL -- or = 'link'
```
Although `guid` and `media_url` have indexes, `title` and `website_url` don't.

Add indexes to PodcastEpisode title and website_url

---

app/controllers/api/v0/classified_listings_controller.rb
app/labor/cache_buster.rb
spec/labor/cache_buster_spec.rb
spec/requests/api/v0/classified_listings_spec.rb

Right now `/api/listings` is not edge cached:
```shell
< Cache-Control: max-age=0, private, must-revalidate
< X-Cache: MISS, MISS
< X-Cache-Hits: 0, 0
```
this is because we are not setting the `cache-control` header correctly.
This PR fixes that and adds proper surrogate keys.
I chose to call `listing.purge_all` in the cache buster because the current URL based system purges all listings, let me know if I should just use `listing.purge`
Similar to #5673 and others but for listings :D

API listings: improve caching

---

app/assets/stylesheets/dashboard.scss

It was a bug report from one of our contributors to increase contrast on organization badge/pill in Dashboard. Easy fix.
Closes #6285

Fixing contrast on Organization pill in Dashboard

---

app/lib/index_migration_helpers.rb
db/migrate/20200224153122_add_title_website_url_indexes_to_podcast_episodes.rb
db/schema.rb

When we first ran this migration we got a statement timeout error from Postgres which caused our release phase to fail HOWEVER the index was actually created so when I tried to rerun it we got an Argument Error
```
ArgumentError: Index name 'index_podcast_episodes_on_title' on table 'podcast_episodes' already exists
```
This helper will check if an index already exists before attempting to apply it. I choose to add a full helper bc my guess is as we expand our environments in the future this will not be the last time this happens. We found this helper extremely useful at Kenna dealing with multiple environments. 
I ran the migrations and the extra line got added to the schema file, I'm assuming it accidentally got removed at some point.

Add index missing check to podcast migration

---

app/controllers/comments_controller.rb
app/models/comment.rb
app/views/comments/_form.html.erb
app/views/comments/deleted_commentable_comment.html.erb
app/views/comments/edit.html.erb
spec/models/comment_spec.rb
spec/requests/comments_spec.rb

Allows comments from a deleted articles or podcasts to be edited.  Currently, they are able to be viewed but not edited.
I noticed #5889 had fixed for allowing destroy, so I removed the code for it. It is now only for edit.
#5511

Allow comments without a commentable to be edited and destroyed

---

app/controllers/search_controller.rb
app/errors/search.rb
app/services/search/base.rb
app/services/search/tag.rb
spec/lib/data_update_scripts/index_chat_channel_memberships_to_elasticsearch_spec.rb
spec/lib/data_update_scripts/index_classified_listings_to_elasticsearch_spec.rb
spec/lib/data_update_scripts/index_tags_to_elasticsearch_spec.rb
spec/requests/search_spec.rb
spec/requests/stories_index_spec.rb
spec/services/search/chat_channel_membership_spec.rb
spec/services/search/classified_listing_spec.rb
spec/services/search/tag_spec.rb
spec/workers/search/chat_channel_membership_es_index_worker_spec.rb
spec/workers/search/classified_listing_es_index_worker_spec.rb
spec/workers/search/tag_es_index_worker_spec.rb

Inspired by https://github.com/thepracticaldev/dev.to/pull/6219 and https://github.com/thepracticaldev/dev.to/blob/master/app/services/payments/customer.rb and by the understandable advantage of having centralized error handling and not leaking library errors up to the controllers I went ahead and refactored things a bit
We now have custom errors like `Search::Errors::Transport::BadRequest` :)

Centralize search error handling

---

app/controllers/stripe_active_cards_controller.rb
app/labor/cache_buster.rb
app/services/payments/customer.rb
spec/requests/stripe_active_cards_spec.rb
spec/services/payments/customer_spec.rb

In an effort to move alerts setup on Timber to DataDog, this PR is adding some DataDog monitors that we can set up alerts for.
https://github.com/thepracticaldev/dev.to/projects/5#card-33313304
We'll need to trigger these added errors manually in production after this is deployed so DataDog picks up on it and then I can create a monitor for it.

Add DataDog monitors

---

app/models/chat_channel_membership.rb
app/models/classified_listing.rb
app/models/concerns/searchable.rb
app/models/tag.rb
app/workers/search/index_to_elasticsearch_worker.rb
spec/models/chat_channel_membership_spec.rb
spec/models/classified_listing_spec.rb
spec/models/tag_spec.rb
spec/workers/search/index_to_elasticsearch_worker_spec.rb

This PR follows an idea from #6213 - it moves the logic for indexing documents to Elasticsearch into a single worker. If we need to batch index in the future, we could always add a 3rd optional argument to this worker or create a new worker for that entirely. Let me know what you think!
https://github.com/thepracticaldev/dev.to/projects/6#card-33598410
Monitor the Sidekiq queue just to make sure this new worker isn't failing. I'll open a separate PR to remove the old workers and specs if/when this is merged.

Refactor logic to index to Elasticsearch

---

spec/workers/search/index_to_elasticsearch_worker_spec.rb

Rhymes had a PR #6227 that was merged just before my PR #6286 and I didn't have his changes incorporated so my specs failed. This PR fixes the spec with the changes from #6227.
#6227 
#6286
[Failed build](https://travis-ci.com/thepracticaldev/dev.to/builds/150531125)

Fix index_to_elasticsearch_worker_spec.rb

---

app/models/sponsorship.rb
spec/models/sponsorship_spec.rb

Fixed Sponsorship validations so that they would take `expires_at` into an account:
When a sponsorship has expired we should allow creating another sponsorship for this tag, or another sponsorship of gold, silver or bronze levels for a particular organization.
#6017

Fix Sponsorship validations to take expiration date into an account

---

app/labor/markdown_fixer.rb
app/labor/markdown_traverser.rb
spec/labor/markdown_fixer_spec.rb

```shell
bundle exec rspec spec/labor/markdown_fixer_spec.rb spec/requests/api/v0/articles_spec.rb spec/services/articles/creator_spec.rb spec/services/mentions/create_all_spec.rb
```
starts the server at local, sign in, new post, copy the following to preview and see if things work as expected. You should not see `\` in code and codeblock, and underscored username renders correctly.
<details>
<summary>Code for testing at development</summary>
<pre>
@_dev_
```
@_dev_
```
`@_dev_`
@_dev_
</pre>
</details>
The underscored username got escaped in code and code blocks. We probably do not want that. The fix is only to escape underscored username if they are not in code or code blocks.
Other possible approaches:
- Write regexp that only pull out underscored usernames not in code or code blocks …

[MarkdownFixer] Do not escape username with underscores in code or codeblocks

---

app/controllers/email_subscriptions_controller.rb
app/views/videos/new.html.erb

Add the `accept` attribute to the video upload. Adding `video/*` alone isn't enough because safari will ignore MP4. The other change is a safe fallback for `PREFERRED_EMAIL_NAME`
ref: https://stackoverflow.com/questions/19107685/safari-input-type-file-accept-video-ignores-mp4-files
n/a

Add `accept` attribute to the video upload

---

app/controllers/pages_controller.rb
spec/requests/pages_spec.rb

Going to https://dev.to/report-abuse directly would fill the report URL link with `https://dev.to/serviceworker.js`. This PR makes sure that the form will stay empty.
Resolves https://github.com/thepracticaldev/tech-private/issues/366
n/a

Ignore referer on /report-abuse if it's SW.js

---

app/assets/config/manifest.js
spec/system/admin/admin_dashboard_presented_spec.rb

Local development was showing an error caused by Sprockets (4.0) not finding the `Administrate` gem assets. This happened when trying to browse `/admin` and its nested dashboards. 
This PR adds the files to the manifest & includes a simple test to avoid regressions that might break the `Administrate` dashboards
From the Administrate repo's [README (**Getting Started**)](https://github.com/thoughtbot/administrate#getting-started) you'll find the fix they suggest, which is added by this PR.
N/A
N/A

Adds administrate gem CSS & JS assets to Sprockets Manifest

---

app/assets/stylesheets/preact/sidebar-widget.scss
app/controllers/internal/configs_controller.rb
app/controllers/stories_controller.rb
app/models/site_config.rb
app/views/articles/_sidebar_campaign.html.erb
app/views/internal/configs/show.html.erb

- added comments number to the campaign sidebar
- added a setting to be able to set a campaign image
- added stories count to the sidebar
- added links to "all stories" and "share all story" to the sidebar
#5892 #5701

Changed sidebar campaign view

---

app/controllers/search_controller.rb
app/javascript/chat/actions.js
app/models/chat_channel_membership.rb
app/services/search/chat_channel_membership.rb
app/services/search/query_builders/chat_channel_membership.rb
config/routes.rb
spec/models/chat_channel_membership_spec.rb
spec/requests/search_spec.rb
spec/services/search/chat_channel_membership_spec.rb
spec/services/search/query_builders/chat_channel_membership_spec.rb

This PR moves the searching of chat channels from Algolia to Elasticsearch. Couple things to note.
1) **Pagination:** The backend and js support the ability to pass paging params, however, I did not see any buttons or links on the chat channel pages that implemented those features. Talked with @sarthology briefly and he confirmed he does not think its implemented. Well the backend is in place for when we do. 
2) **Improved Searching:** I updated what we store in the `channel_text` field by removing some common words. These can cause searches to return unwanted results. For example, say you want to search for your friend "Andy" If you type in "And" you will get back every single direct channel bc "and" is in all of the channel texts. With the common words removed typing in "And" will …

Implement Search for Chat Channels with Elasticsearch

---

app/models/sponsorship.rb
app/views/partnerships/_form.html.erb
spec/requests/partnerships_spec.rb

- removed information about the expired sponsorships from the bronze (`/partnerships/bronze-sponsor`) and silver (`/partnerships/silver-sponsor`) level sponsor pages and tag sponsor page (`/partnerships/tag-sponsor`)
- if an org has an expired sponsorship on a tag, this tag now appears as an option in the tag `select` in the "new sponsorship" form
- added specs for the cases when the info about sponsorships should be shown or not
There are a lot of opportunities for optimizations and refactoring, but I kept them for the future, only fixing bugs and adding basic tests here.
#6018

Hide information about expired sponsorships from "partnerships" pages

---

app/models/data_update_script.rb
config/environments/development.rb
spec/models/data_update_script_spec.rb

Right now, everytime we call `rails server` or `rails console` we check if there are scripts to be run, this though has two side effects:
- it issues as many SQL queries as there are scripts (currently 4 but potentially many more in the future) plus one to check existence
- it loads scripts in memory and in the DB, which might be an issue if I'm testing a branch and I generate a script that I then decide to delete
This slows down a little the feedback cycle for developers.
I decided to change to issue only 1 query and check the following:
- if there are more scripts on disk than in the DB (intentional or not), exit
- if there are scripts in the DB that are in the enqueued status, exit
The `DataUpdateWorker` already loads scripts in the DB before running them, so there's no need to have it …

Use DataUpdateScript.scripts_to_run? in development

---

app/views/users/_account.html.erb
spec/requests/user/user_settings_spec.rb

We should only show the option to request an account deletion via email if the user has content to begin with.
No

Only show the ghost option if user has content

---

app/models/user.rb
app/services/users/delete_activity.rb
spec/requests/internal/users_banish_spec.rb
spec/services/users/delete_spec.rb

We didn't clean up classified listings when removing users, which sometimes led to issues. This PR follows the pattern previously established by Anna and adds classified listings to it.
Closes https://github.com/thepracticaldev/tech-private/issues/379

Delete classified listings when deleting user

---

app/javascript/chat/actions.js

Before when a [user would leave a Chat Channel we would remove the Membership from Algolia](https://github.com/thepracticaldev/dev.to/blob/e159217dcea43a5d706e47b6238e1e680c7294d3/app/controllers/chat_channel_memberships_controller.rb#L45). Now we only remove chat channel memberships when they are destroyed we need to set the default filter to "active" so that all memberships with status such as inactive, blocked, or left_channel are not shown. 
Why not remove them from Elasticsearch? I want to keep all of the memberships in Elasticsearch bc we may want to search for other statuses in the future. It is also easier to stay synced when the general principle is that every membership has a document in Elasticsearch rather than making it a conditional of whether it is or isn't
Ideally we …

Only Show users their Active Chat Channels

---

db/migrate/20200226192145_add_active_to_broadcasts.rb
db/schema.rb
lib/data_update_scripts/20200226193303_backfill_column_for_broadcasts.rb

The content of welcome notifications will be sent to users in the form of Broadcasts, which can be added by admins via the `/internal/broadcasts`. We currently have an unused attribute `sent` on Broadcasts.
I propose that we should rename this attribute to `active`, and then make the necessary requirements in the code so that we actually _only_ send a Broadcast if it has explicitly been marked as `active` or not!
This will be super useful for @thepracticaldev/delightful's work on welcome notifications because it will allow admins to begin adding welcome notifications into production without them being sent out (since they can remain "inactive" until we're ready to ship the feature).
I will do the work of _using_ this new attribute and removing the old `sent` attribute in a separate PR. …

Add active attribute to Broadcasts

---

app/javascript/chat/actions.js
app/services/search/query_builders/chat_channel_membership.rb
spec/services/search/chat_channel_membership_spec.rb
spec/services/search/query_builders/chat_channel_membership_spec.rb

#6321 was a hotfix when I discovered we don't remove chat channel memberships when users leave a channel or are blocked(maybe we should revisit this???) While it works, because it is in the params a user could intercept the request and change it allowing them to view chat channel memberships that have other statuses. This PR hard codes the active status into the filter params before we send the query to Elasticsearch, same way we do with the user id. This means users can only ever see their own memberships that are active. 
In the future we may want to allow admins to view those with other statuses, which I noted in a comment, but for now I think this will do just fine. 
https://github.com/thepracticaldev/dev.to/projects/6#card-33722868

ONLY Allow Active ChatChannelMembership Search

---

app/controllers/admin/html_variant_successes_controller.rb
app/controllers/admin/html_variant_trials_controller.rb
app/dashboards/dashboard_manifest.rb
app/dashboards/html_variant_success_dashboard.rb
app/dashboards/html_variant_trial_dashboard.rb

The show page variants on `HtmlVariantDashboard` didn't work. I'm not super familiar with this part of our app, but adding the missing dashboards with `rails generate administrate:dashboard` seemed like the easiest fix. 
Closes #6143

Add HtmlVariantSuccess and HtmlVariantTrial dashboards

---

app/controllers/chat_channel_memberships_controller.rb
app/controllers/chat_channels_controller.rb
app/models/chat_channel.rb
app/models/chat_channel_membership.rb
app/models/message.rb
app/services/user_blocks/channel_handler.rb
app/services/users/cleanup_chat_channels.rb
app/views/chat_channels/index.html.erb

Now that we are no longer using Algolia for searching Chat Channel Memberships we can remove it from the model!
https://github.com/thepracticaldev/dev.to/projects/6#card-32955031

Remove Algolia from ChatChannelMemberships

---

app/javascript/chat/chat.jsx
app/views/chat_channels/index.html.erb

Per the recommendation of @rhymes, I added debounce to our ChatChannel searching to prevent a search request from being sent after every single letter is typed by a person. I thought 500 ms seemed like a good wait time but I am open to suggestions if those more versed frontend folks have a better suggestion. 
https://github.com/thepracticaldev/dev.to/projects/6#card-33706458

Use debounce to limit Chat Channel Searches

---

Envfile
app/lib/release_phase_notifier.rb
release-tasks.sh
spec/lib/release_phase_notifier_spec.rb

Currently the only way we are notified of release phase failures is via an email from Heroku to the Heroku admins. Unfortunately, that's not helpful to anyone else who is trying to deploy their code. This attempts to hook up a command in our release phase script to catch any errors that occur and notify slack about them for everyone to see. 
I am FAR from an expert in bash and actually [found this script on no other than StackOverflow](https://stackoverflow.com/a/41852435/1438582). There is probably a slicker better way to do this so please let me know what that is! 
https://github.com/thepracticaldev/dev.to/projects/5#card-33642543

Notify slack when release phase fails

---

app/controllers/internal/broadcasts_controller.rb
app/models/broadcast.rb
app/views/internal/broadcasts/_form.html.erb
app/views/internal/broadcasts/index.html.erb
app/workers/notifications/welcome_notification_worker.rb
db/seeds.rb
spec/factories/broadcasts.rb
spec/requests/notifications_spec.rb
spec/workers/notifications/welcome_notification_worker_spec.rb

This PR branches off and builds on the work in #6318 .
**⚠️Please review #6318 first, since it needs to be merged FIRST, before this one!** Once #6318 has been merged, I will rebase this PR against master.
This PR uses the `active` attribute on the `Broadcast` model and ensures that we only ever send a notification if the Broadcast itself is active. I've updated the related specs and added an `active` scope that we can explicitly use whenever we deal with Broadcasts.
https://github.com/thepracticaldev/dev.to/projects/7#card-32965274
The only real UI change is that admins can now have active and inactive broadcasts in the `/internal/broadcasts` route:
I also added a note about this at the top of the `/internal/broadcasts` route for all admins:
As mentioned above, #6318 needs to be merged …

Only send notifications that belong to an active broadcast

---

app/assets/javascripts/initializePage.js.erb
app/assets/javascripts/initializers/initializeHeroBannerClose.js
app/controllers/stories_controller.rb

Some Context: 
An HTML Variant is created for the hero banner that we will enable during campaigns. 
The admin will upload the html code from the `/html_variant page`.
This html will have the id's `js-she-coded-hero-banner` and `js-she-coded-hero-banner__x`
When a user clicks on the x (i.e. `js-she-coded-hero-banner__x`) then it should close the banner and ensure that it does not get displayed again
https://github.com/thepracticaldev/dev.to/issues/6259

Close the Hero Banner

---

app/services/search/chat_channel_membership.rb
spec/models/chat_channel_membership_spec.rb
spec/services/search/chat_channel_membership_spec.rb

I noticed the logic for pagination in `Search::ChatChannelMembership` wasn't working as expected.
1. It would return `nil` or `[]`, depending on parameters. This PR fixes that to always return `[]`.
2. The pagination logic was slightly off. This PR fixes that as well.
https://github.com/thepracticaldev/dev.to/projects/6#card-33726279

Fix pagination on Search::ChatChannelMembership

---

app/controllers/stories/feeds_controller.rb
app/controllers/stories_controller.rb
app/services/articles/feed.rb
spec/services/articles/feed_spec.rb

On the Preact version of the home page, we want all logic related to selecting and ordering articles for the feed to happen on the server side. This logic current happens in the browser/client side/Javascript. 
This PR takes the article ranking logic in `app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb` and duplicates it in `app/services/articles/feed.rb`. The client side code has been left in place for now for backwards compatibility.
Please note: we're trying to replicate current logic as closely as we can. Please no feedback on how effect that ranking criteria might be 😄

Implement home page feed article ranking in Ruby

---

.rubocop.yml

This PR is upping the max line limit from 10 to 15 for RSpec files. Especially when it comes to Elasticsearch, we've been bumping up against this limit a lot lately which forces us to make the code less readable (i.e. putting Hashes all on one line). The desired code is still concise and necessary in the Elasticsearch example, there are just more steps involved (mock responses, indexing, etc.). This update will help to accommodate that and keep things readable.

Linter update: update max line limit to 15 for RSpec files

---

spec/services/articles/feed_spec.rb

Fixes a test for the feed service that was poorly structured: instead of just requesting the first tagged article, we request multiple (35 by default). The order or tagged articles isn't consistent in this testing scenario.

Fix flapping test

---

app/labor/mailchimp_bot.rb
app/models/user.rb
spec/factories/users.rb
spec/labor/mailchimp_bot_spec.rb
spec/models/user_spec.rb

If user's who previously subscribed to our newsletter try to resubscribe, it won't work without them explicitly opting in again. Setting their user status to 'pending' should™ trigger a confirmation email and this PR implements this.
There are several things that could be improved once we get the basics working, I'll leave some comments inline/below.
https://github.com/thepracticaldev/tech-private/issues/398

Mailchimp resubscribe

---

app/javascript/shared/components/tags.jsx

Same as #6322 we don't want to necessarily send a search for every single character that is entered. Here we will only run a search every 300ms when the input in the box has changed. Once again, frontend people let me know if you have a better suggestion for wait time!
https://github.com/thepracticaldev/dev.to/projects/6#card-33725394

Add debounce to Tag Search

---

app/controllers/organizations_controller.rb
app/views/users/_org_admin.html.erb
spec/requests/organizations_update_spec.rb

Added `nav_image` and `dark_nav_imag`e fields to org settings form.
Organizations will be able to set up these images by themselves so that the admins won't need to set these while setting up the sponsorships.
#6016

Add nav_image and dark_nav_image fields to org settings form

---

db/migrate/20200227214321_remove_sent_from_broadcasts.rb
db/schema.rb

Now that #6318 and #6319 have been merged, we no longer need the `sent` attribute on the Broadcast model.
https://github.com/thepracticaldev/dev.to/projects/7#card-32965274
N/A
Nope! The data in the `sent` column has been migrate to the `active` column on Broadcasts, so we should be good to go! 🚀

Remove sent attribute from broadcasts table

---

app/views/partnerships/_form.html.erb
spec/requests/partnerships_spec.rb

Removed the information about sponsorships renewal.
Auto-renewal is not implemented, so information about it is misleading.

Removed misleading information about sponsorships renewal

---

app/services/articles/feed.rb
spec/services/articles/feed_spec.rb

@benhalpern rightly pointed out that not all endpoints in the `Articles::Feed` service are respecting the `page` and `number_of_articles` options. This PR makes the endpoints that use a simple ActiveRecord look respect those options. Note that the `default_home-feed` and `default_home_feed_and_featured_story` endpoints will only respect `number_of_articles`: since these methods are doing ranking of stories, I fear that trying to page the results would be tricky (as I can't just rely upon the Kaminari gem to do it for me).

Add page and article limit options to feed service

---

app/services/search/classified_listing.rb
app/services/search/query_builders/classified_listing.rb
spec/rails_helper.rb
spec/services/search/classified_listing_spec.rb
spec/services/search/query_builders/classified_listing_spec.rb
spec/support/elasticsearch_helpers.rb

This is a follow-up/redo of #6239 now that #6282 has been merged. This PR is the backend code that will be used to search `ClassifiedListings` via Elasticsearch. The next PR will create a `classified_listings` action in the `search_controller` and the frontend updates required.
It's worth noting I expect this backend code to still change in the next couple of PRs as I dive into the frontend and then rip Algolia out. It's very likely I'll uncover a few legacy "gotchas" that we'll want to account for in Elasticsearch. But the goal here is also to incrementally do this implementation by breaking it into smaller and more easily reviewable PRs.
https://github.com/thepracticaldev/dev.to/projects/6#card-32289296

Search ClassifiedListings backend code

---

app/javascript/shared/components/tags.jsx

We [were seeing some weird behavior](https://github.com/thepracticaldev/dev.to/pull/6327#issuecomment-592428676) after I lowered the wait time for debounce causing it to interrupt the user typing. I added leading true so that the time starts after the first keystroke instead of the last. Seems to have fixed the issue for me locally.

Add leading: true to Avoid Debounce Interrupting Typing

---

app/controllers/registrations_controller.rb
app/views/service_worker/index.js.erb

The service worker is run on `/enter` but seems to conflict with the automatic redirection to the dashboard and it results on a full page rendered inside the shell (causing the double footer mentioned in the related issue #6347).
You can verify this by going to https://dev.to/enter - you'll not be redirected but still be shown the dashboard, if you scroll down you'll see the double footer
I also noticed it doesn't actually redirects, only shows the dashboard:
This should fix this, let me know if I missed something
Closes #6347

Don't run the service worker on /enter

---

app/lib/redcarpet/render/html_rouge.rb
spec/labor/markdown_parser_spec.rb

Our syntax highlighter, [rouge](https://github.com/rouge-ruby/rouge) requires the hint language in code blocks to be always lowercase:
```ruby
[7] pry(main)> Rouge::Lexer.find("python")
=> Rouge::Lexers::Python
[8] pry(main)> Rouge::Lexer.find("Python")
=> nil
```
It might be neat to allow users to specify whatever casing they prefer. For example the following is specified as `RuBy` and it works:
```RuBy
puts "hello world"
```
Closes https://github.com/thepracticaldev/dev.to/issues/6352

Allow different casings to be specified for syntax highlighting

---

app/models/display_ad.rb
spec/models/display_ad_spec.rb

At the moment the display_ads does not allow us to add a css style of background with an image or linear-gradient. Both @lightalloy and I tried to tackle this today without success. For more info, please read this slack conversation https://dev-internal.slack.com/archives/C7GE84DEJ/p1582892484118100. It's currently impeding us from going live with SheCoded. 
After discussion, we figured that it should be safe to not sanitise this temporarily (and fix and reenable) since it’s an internal admin page.

Sanitisation of Ads

---

spec/services/search/chat_channel_membership_spec.rb
spec/services/search/classified_listing_spec.rb
spec/services/search/tag_spec.rb

With #6348 we introduced a new spec helper to send documents to Elasticsearch called `index_documents`. This is just a quick (somewhat nitpicky) PR to update existing specs to use the helper to keep everything consistent while we're still implementing Elasticearch.
#6348 
https://github.com/thepracticaldev/dev.to/projects/6#card-33783332

Refactor /spec/services/search specs to use index_documents helper

---

app/javascript/article-form/__tests__/articleForm.test.jsx
app/javascript/article-form/articleForm.jsx
app/views/articles/_v2_form.html.erb

[what the bug currently looks like](https://youtu.be/vlbflkoaRgo)
Our frontend app will now check if the locally cached draft's timestamp is newer or older than the draft provided by the backend before attempting to overwrite it. This is fixed by also caching the timestamp of when localstorage draft is created, then the timestamp is compared to decide if the override should occur.
Resolves https://github.com/thepracticaldev/dev.to/issues/3670
TBD
n/a

Make localstorage draft respect newer saved draft

---

app/javascript/articles/Article.jsx

Fixes this issue where we show an empty parentheses instead of nothing on articles over a day old...

Remove parentheses when time ago not present

---

app/controllers/internal/sponsorships_controller.rb
app/views/internal/shared/_navbar.html.erb
app/views/internal/sponsorships/edit.html.erb
app/views/internal/sponsorships/index.html.erb
config/routes.rb
spec/requests/internal/sponsorships_spec.rb

- created `/internal/sponsorships`
- moved part of the functionality from `/admin/sponsorships` to `/internal/sponsorships`
I decided to start with moving displaying, editing and destroying sponsorships to `/internal` to fit the task in this cycle. 
Creating sponsorships from `/internal` should be implemented later in another pr.
#6015

Started moving sponsorships to /internal

---

app/models/article.rb
spec/models/article_spec.rb

When an article is updated the associated collection is touched along with all its articles. This creates a deadlock where two transaction(nested) lock the article that was updated.
With this commit the collection will be touched after the article updates transaction has been committed. Doing so we have two sequential transactions.
Fixes ##5964

Prevent deadlocks with article-collection updates.

---

app/models/comment.rb

Fixes: https://app.honeybadger.io/fault/66984/bb9520df544e22526d7ce1e0c15b5cb9
```
NoMethodError: undefined method `tag_list' for nil:NilClass
comment.rb  61 block (3 levels) in <class:Comment>(...)
[PROJECT_ROOT]/app/models/comment.rb:61:in `block (3 levels) in <class:Comment>'
59       end
60       attribute :tag_list do
61         commentable.tag_list
62       end
63       attribute :root_path do
```

Bug Fix: Use safety operator when indexing comment tag list

---

app/assets/stylesheets/articles.scss

This adds extra padding between tags in feed. Following very good suggestion from @rhymes.

Extra padding on tags

---

app/models/comment.rb

Missed a commentable in the indexing. Fixes: https://app.honeybadger.io/fault/66984/7ca4f1fff0893a0e28c7a09c391bb565
```
NoMethodError: undefined method `tag_list' for nil:NilClass
comment.rb  92 block (3 levels) in <class:Comment>(...)
[PROJECT_ROOT]/app/models/comment.rb:92:in `block (3 levels) in <class:Comment>'
90       end
91       tags do
92         [commentable.tag_list,
93          "user_#{user_id}",
94          "commentable_#{commentable_type}_#{commentable_id}"].flatten.compact
```
I would if we were keeping this but it will be moving to Elasticsearch soon so I skipped it

Bug Fix 2: Use safety operator for commentable in tags tag_list

---

app/models/article.rb

We had `attributesForFaceting` set for the `searchables` index, but not the `ordered_articles` index.
This is a temporary measure before we replicate this in Elastic.

Add attributesForFaceting to ordered_articles

---

app/serializers/search/classified_listing_serializer.rb
app/services/search/query_builders/classified_listing.rb
config/elasticsearch/mappings/classified_listings.json
spec/services/search/query_builders/classified_listing_spec.rb

@mstruve [mentioned](https://github.com/thepracticaldev/dev.to/pull/6372#pullrequestreview-367219294) that we need to filter on `published` for `ClassifiedListings` so that, by default, we're only returning `published` `ClassifiedListings`.
https://github.com/thepracticaldev/dev.to/pull/6372#pullrequestreview-367219294
https://github.com/thepracticaldev/dev.to/projects/6#card-33950122
I'll coordinate with @mstruve to manually reindex `ClassifiedListings`.

Add published field to ClassifiedListing Search

---

app/services/search/cluster.rb
app/services/search/feed_content.rb
app/services/search/user.rb
config/elasticsearch/mappings/feed_content.json
config/elasticsearch/mappings/users.json
spec/services/search/base_spec.rb
spec/services/search/feed_content_spec.rb
spec/services/search/user_spec.rb

Currently, in Algolia, Articles, Podcast Episodes, and Users are all in the same "searchables" index. Podcast Eps and Articles actually share a lot of the same fields when we index them so having them on the same index makes sense. However, users do not. This creates an index for Articles and Podcast Eps and a separate index for Users. 
Eventually, all of these should have their own separate dedicated search areas, but for now we can issue a search to multiple indexes from the Feed page or we can issue 2 searches if no class_name filter is present. I will be playing around to see what makes the most sense. 
I also took the time to make a base_spec class to handle testing the base search class functionality making the additional two search class specs easier to write. Eventually we should …

Create Feed Content index for Articles and Podcast Episodes and User Index

---

Gemfile
Gemfile.lock

Bump [reverse_markdown](https://github.com/xijo/reverse_markdown) to 2.0
The changelog is the following:
```markdown
-    BREAKING: Dropped support for ruby 1.9.3
-    Add support for details and summary tags, see #85
```

Bump reverse_markdown to 2.0

---

app/models/article.rb
spec/models/article_spec.rb

As discussed with @rhymes on Slack, the other day while reading the `Article` model I noticed two places where empty arrays were used as falsy values. This doesn't work in Ruby, so I added `.present?` checks.
n/a
Let me know if you disagree and actually want to see a test for this.

Add .present? check

---

app/javascript/chat/actions.js
app/javascript/shared/components/tags.jsx
app/javascript/src/utils/__tests__/search.test.js
app/javascript/src/utils/search.js

Found by #6372, codeclimate isn't happy that we have very similar code to make API calls to the `search` endpoint/`search_controller` for [tags](https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/shared/components/tags.jsx#L322-L332), [chats](https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/chat/actions.js#L116-L127), and [classified listings](https://github.com/thepracticaldev/dev.to/pull/6372/files#diff-36e94c610b5cf2eb85d87f477113dc14R301-R311). This PR moves this logic into a helper to be reused. I intentionally extracted very little to keep it very flexible.
#6372 
https://github.com/thepracticaldev/dev.to/projects/6#card-33848509

Create fetchSearch helper

---

app/javascript/articles/FeaturedArticle.jsx
app/javascript/articles/__tests__/__snapshots__/FeaturedArticle.test.jsx.snap

Fix invalid featured author link due to jsx / erb mix.
- Updates app/javascript/articles/FeaturedArticle.jsx
- Replace ERB tags (`<%= ... %>`) with JSX tags (`{ ... }`)
- Also updates app/javascript/articles/\_\_tests\_\_/\_\_snapshots\_\_/FeaturedArticle.test.jsx.snap
I've searched all the JSX files and there don't seem to be any other cases.
Fixes #6425

Fix invalid ERB in featured author link.

---

app/views/internal/users/edit.html.erb

Some users' identities have an `auth_data_dump = nil` for some reason. Based on this issue https://github.com/omniauth/omniauth/issues/767, I believe the reason was because we (a long time ago) used to use `env["omniauth.auth"]` which would sometimes return `nil`. We've been using `request.env["omniauth.auth"]` long enough where we don't see this issue anymore.
Long story short, this code solves an edge case for those users who have this edge case.
Honeybadger error: https://app.honeybadger.io/projects/66984/faults/58419984/23a3dd40-5a7a-11ea-9e54-fe85e1e0f780?page=0
Resolves https://github.com/thepracticaldev/tech-private/issues/405
No

Check presence of auth_data_dump

---

app/services/articles/feed.rb

Every time we [score an article](https://github.com/thepracticaldev/dev.to/blob/master/app/services/articles/feed.rb#L74) an article we hit these three methods each of which hit Redis. 
```ruby
article_points += score_followed_user(article)
article_points += score_followed_organization(article)
article_points += score_followed_tags(article)
```
Since we know the data likely is not going to change while we process the articles, rather than hitting Redis for every single article,  we should memoize the results and use those instead. Something, something, Cache(LOCAL!) is King! 
This will remove almost all of these requests

Don't Repeatedly Hit the Cache for User Data

---

app/views/internal/feedback_messages/index.html.erb

Just a quick fix to filter banned users out of the vomit reaction lists,
we are doing essentially the same thing for unpublished articles. It
might worth handling this at the controller level if we experience any
performance issues.
Closes https://github.com/thepracticaldev/tech-private/issues/406

Skip vomit reactions on banned users

---

.erb-lint.yml
app/liquid_tags/liquid_tag_base.rb
app/liquid_tags/podcast_tag.rb
app/liquid_tags/tweet_tag.rb
app/models/comment.rb
app/views/comments/_comment_proper.html.erb
app/views/comments/_liquid.html.erb
app/views/comments/delete_confirm.html.erb
app/views/comments/index.html.erb

Use of html_safe method is replaced or being switched to other areas (models).
This is for comment model. 
Around 12 warnings less when erb-linting.
Approximately 45 warnings left.
#5914

Fixes html_safe issues from comment domain

---

app/controllers/articles_controller.rb
app/helpers/application_helper.rb
app/views/articles/index.html.erb
app/views/users/_meta.html.erb
spec/requests/articles/articles_spec.rb
spec/requests/rss_feed_spec.rb
spec/requests/user/user_profile_spec.rb

We had been linking to empty RSS feeds on user profiles without published articles and rendering `body: nil` for empty RSS feeds.
This PR switches to `not_found` for empty feeds and takes away the reference to RSS feeds for users who have not published articles yet.
This is to help waste less robot time when they crawl our site.
While I was here I switched out a few instances of hardcoded `https://dev.to`.

Do not render or link to empty rss feeds

---

app/assets/stylesheets/scaffolds.scss

Social Icons on the profile page with night theme currently have a very low contrast which makes them difficult to see. This PR fixes the contrast by applying invert filter in case of dark themes.
Closes #6310
**Before**:
**After**:

Invert the text color for social icons in case of dark themes

---

docs/installation/linux.md
docs/installation/mac.md
docs/installation/windows.md

Yesterday while testing https://github.com/thepracticaldev/dev.to/pull/6372 with @atsmith813 we found out that our current code does not fully support ES 7.6 which I inadvertently installed thanks to the Homebrew instructions.
This was confirmed by the [release notes of `elasticsearch-ruby`](https://github.com/elastic/elasticsearch-ruby/releases/tag/v7.5.0), which we recently updated:
```md
- Support for Elasticsearch 7.5.
```
Once downgraded to ES 7.5.2 everything worked well as expected.
Since in the documentation we, until now, recommend "ES 7 or higher" I think we should be more specific, lest we incur on bug reports about features not working locally.
I also updated the `Homebrew` instructions for how to install the correct version (which I tested locally twice).
I tested manually …

Update ES docs for min/max versions and macOS brew

---

app/services/articles/feed.rb

~While trying to figure out how to get this cache call to work better I noticed that we are taking into account page, number_of_articles, and a tag param when we are fetching the articles. However, those params are not in our cache key which I believe means this could return a cache for say the general feed when we want one for a tag. Or return page 1 of articles when we want page 2. I also could totally be missing something here, let me know if I am!~ Going to remove it for performance reasons instead. See comments below

Remove Global Feed cache key 

---

README.md
docs/installation/linux.md
docs/installation/mac.md
docs/installation/windows.md

PostgreSQL is [officially unsupported as of February 13, 2020](https://www.postgresql.org/support/versioning/):
I've updated the minimum required version in the docs. 
AFAIK (or can check) we still don't use any features that are available only on newer versions.

Bump min version of PostgreSQL from 9.4 to 9.5

---

app/views/service_worker/index.js.erb

Right now https://dev.to/search/tags and https://dev.to/search/chat_channels are wrapped in the service worker shell. This fixes it by disabling the SW on those endpoints
**Before**
**After**

Disable service worker on /search endpoints

---

config/environments/development.rb

Since we already require Redis in development (for sessions), I think we should use it for caching as well. It's easier to test caching issues if we use the same store we use in production. I only lowered the default expiration.
This is also an attempt to have `development` and `production` a little bit more similar.
Tip: you can toggle caching on and off in development with `rails dev:cache`

Enable caching in Redis in development

---

app/javascript/shared/components/tags.jsx

After a bit of fiddling and testing I think I found the right combination between wait time and options to not incur in deleting characters during autocomplete.
This is how it would look in the editor:
This is how it would look in the listing form:
I recorded a few examples of other combinations to show what wasn't working:
**150ms with leading aka production right now**
as you can see it deletes characters
**200ms with no leading**
losing the `y`
**200ms with leading**
The first `a` in Java is often replaced
**250ms with leading**
even if now the wait time is okay, the initial call is too fast.
Closes https://github.com/thepracticaldev/dev.to/issues/6436
- [Debouncing and Throttling Explained Through Examples](https://css-tricks.com/debouncing-throttling-explained-examples/)

Fix tags autocomplete deleting input with fast typing

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feed.rb
config/field_test.yml
spec/services/articles/feed_spec.rb

It's too early to be sure, but it looks like both `more_random` and `more_tag_weight` are slightly more successful variants than the base.... so why not combine them!
I think throwing more spaghetti at the wall is a good thing to do.
I like the idea of rolling experimentation so we can add new variants in a more adhoc way like this. 
For now we'll have to sort of just account for the normalization issues ourselves of different tests being introduced at different times as we evolve the rules on how we do this stuff and measure it all.

Add more tag weight/more random variant

---

spec/models/chat_channel_membership_spec.rb
spec/models/classified_listing_spec.rb
spec/models/concerns/searchable_spec.rb
spec/models/tag_spec.rb

This creates a new Searchable spec for the Elasticsearch helper module that we use in our AR models. It also removes the redundant specs from each model.

Create Searchable Specs and Remove Redundant specs from AR models

---

app/controllers/stories/feeds_controller.rb

I'm not sure this is correct or appropriate, and we might want to prefer this kind of line in a wrapper class so we can send this kind of data to several places, but all in all it seems useful to have these alternate paths segmentable in Honeycomb.

Add field test variant info to Honeycomb

---

app/assets/stylesheets/item-list.scss

As title says: this PR is about getting rid of min-height value from container with "saved articles". It was causing a weird gap if there was one article only.

Getting rid of min-height on saved articles contianer

---

Gemfile
Gemfile.lock
config/blazer.yml
config/routes.rb
db/migrate/20200304164719_install_blazer.rb
db/schema.rb

[Blazer is a gem](https://github.com/ankane/blazer) that allows admins to interact with the database. Right now you will notice this is only available to `super_admins`. Once this is merged and released the next step will be to install the [Hypershield gem](https://github.com/ankane/hypershield) to shield sensitive user data from being queried. Think things like message bodies etc. 
https://github.com/thepracticaldev/dev.to/projects/5#card-33593263

Install Blazer for Querying the Database Via Admin

---

config/initializers/algoliasearch.rb
lib/tasks/fetch.rake

In #6435 I missed a couple of spots in removing Algolia from ClassifiedListings. This PR removes the index from the Algolia initializer and removes a reference to removing from Algolia.
#6435
https://app.honeybadger.io/projects/66984/faults/61521259

Remove more Algolia from ClassifiedListing

---

app/labor/mailchimp_bot.rb
app/models/user.rb
db/migrate/20200304220534_remove_user_shipping_fields.rb
db/schema.rb
spec/labor/mailchimp_bot_spec.rb

Per [discussion on](https://github.com/thepracticaldev/dev.to/pull/6461#discussion_r387957319) #6461, we have some sensitive information columns that we are no longer using. Rather than trying to shield them via a second schema, let's just remove them altogether.

Remove Shipping Fields from Users

---

app/javascript/article-form/elements/__mocks__/algoliasearch.js
app/javascript/chat/__mocks__/algoliasearchUsers.js
app/models/comment.rb
app/workers/search/index_worker.rb
config/initializers/algoliasearch.rb
db/seeds.rb
spec/models/comment_spec.rb
spec/workers/search/index_worker_spec.rb

I was in the process of moving Comments from Algolia to Elasticsearch when I realized we are not using that index so this PR 🔪 Algolia from comments. Ben confirmed in Algolia that the index has never been queried before.
https://github.com/thepracticaldev/dev.to/projects/6#card-34096238

Remove Algolia from Comments

---

app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
spec/requests/internal/configs_spec.rb

This PR extracts work that was already being done in #5419, and adds a `mascot_user_id` to the `SiteConfig`. In a separate PR, we will replaced the WELCOMING_USER_ID, introduced in #6045, with this value from the SiteConfig.
I paired with @juliannatetreault on this!
#5419
Adds this to the `/internal/config` page:
I will need someone with super duper admin privileges to set the `mascot_user_id` to the current `staff_user_id`! Eventually, we'll set the `mascot_user_id` to Sloan's account, but for now, we need to set it to the practicaldev account!

Add a mascot_user_id to SiteConfig

---

config/elasticsearch/mappings/users.json

availabe_for != available_for 🤦‍♀ 
Now I am sure many of you are wondering, but wait! You can't change Elasticsearch mappings so what is going to happen when you call `update_mappings` with this? 
Answer: This will just add a new field to our mappings because we are not trying to change any existing fields. This is what will end up in our index.
```
"properties"=>
{"availabe_for"=>{"type"=>"keyword", "copy_to"=>["search_fields"]},
"available_for"=>{"type"=>"keyword", "copy_to"=>["search_fields"]},
```
Besides making my OCD eye twitch having an extra unused single field like this is not a huge deal. There is a teenie tiny amount of overhead at the mapping level bc ES has to track this field but thats it. If you added thousands of unused fields, that is when you can run into problems and …

Fix Spelling for Elasticsearch User Field 

---

app/assets/javascripts/initializers/initializeHeroBannerClose.js
app/controllers/stories_controller.rb
app/views/layouts/application.html.erb

We used cookies in a path where we will share a cached version of the page across user cohorts, so the server logic isn't going to be useful. This takes the same approximate pattern but moves to `localStorage`

Switch from cookies to localstorage for hero banner

---

bin/update

We should be running the Elasticsearch setup before we run the DataUpdateScripts since often the DataUpdateScripts are doing things with new Elasticsearch settings or indexes. We have not run into a problem yet bc we have spaced out the index creation and indexing PRs but I could see this being an issue if not fixed.

Run Elasticsearch update before DataUpdateScripts

---

app/services/articles/feed.rb
spec/services/articles/feed_spec.rb

Under some circumstances, `Articles::Feed` could return an empty array:
- user is logged in
- A small number of "hot stories" (defined as having a `score` higher than 8 or `featured` set to true): due to the way an offset was constructed, if there are fewer than 13 hot stories total an empty array might be created
- No new stories between published between 2 and 6 hours ago
This PR implements 2 fixes to prevent this from happening:
- the randomness offset for hot stories is adjusted downward to a max of the number of hot stories
- Instead of only adding new stories from between 2 and 6 hours ago, the last 15-80 stories are chosen

Guarantee articles in main article feed

---

docs/installation/mac.md

Every time that I have to start ES, I get frustrated that it doesn't work, and then remember that I need to be in the directory for it to work. Seems like this should be documented.

Add explicit note about `cd`ing into Elasticsearch before starting

---

app/assets/javascripts/initializers/initializeSponsorshipVisibility.js

My assumption to the cause of bug report #6468 is that the service worker is trying to load our JS asset twice, causing `SyntaxError: redeclaration of const sponsorClickHandler` and break certain portion of the webpage. This is bandaid solution to avoid that particular error.
Hopefully resolves #6468 
n/a

Change sponsorClickHandler to standard function declaration

---

app/models/user.rb
app/services/moderator/banish_user.rb
app/views/internal/feedback_messages/index.html.erb
spec/services/moderator/banish_user_spec.rb

This updates the vomit confirmation section to hide only vomits on banished users.
**Update: removes any associated vomit reactions on banished users.**

Hide banished users vomit confirmations and delete vomit reactions on banish

---

app/controllers/moderations_controller.rb
app/views/moderations/mod.html.erb
spec/system/articles/moderator_moderates_an_article.rb

This PR adds a list of hidden comments on an article's `/mod` page.
https://github.com/thepracticaldev/tech-private/issues/351

Show hidden comments on article mod page

---

app/views/articles/_sidebar.html.erb
app/views/feedback_messages/index.html.erb
app/views/moderations/mod.html.erb
app/views/pages/live.html.erb
app/views/pages/onboarding.html.erb
app/views/partnerships/index.html.erb
app/views/partnerships/show.html.erb
app/views/pro_memberships/show.html.erb

In #6190 we introduced a helper named `cache_key_heroku_slug` for generating cache keys which include the `HEROKU_SLUG_COMMIT` environment variable. This refactors the remaining views to use this helper for consistency.
n/a
There are a few other places that look like the could use the helper, but they are using different separators between the prefix and `ApplicationConfig['HEROKU_SLUG_COMMIT']`:
```
$  rg -i slug_commit app/views
app/views/shell/_bottom.html.erb
3:  <% cache("footer-and-signup-modal--#{user_signed_in?}--#{ApplicationConfig['HEROKU_SLUG_COMMIT']}", expires_in: 24.hours) do %>
app/views/layouts/_styles.html.erb
1:<% cache "base_inline_styles_#{@story_show}_#{@article_index}_#{@home_page}_#{@article_show}_#{view_class}_#{@notifications_index}_#{@tags_index}_#{@reading_list_i …
```

Use cache_key_heroku_slug helper more consistently

---

app/serializers/search/article_serializer.rb

Turns out flare tag is a hash and therefore needs to be converted to a string before getting sent to ES. I figured json would be the easiest to parse on the way back to the view. 
Patched a console and was able to index a previously failed article. Will plan on adding a spec for this Monday
```
irb(main):047:0> Article.find(74153).index_to_elasticsearch_inline
ETHON: Libcurl initialized
ETHON: performed EASY 
=> {"_index"=>"feed_content_production", "_type"=>"_doc", "_id"=>"74153", "_version"=>1, "result"=>"created", "_shards"=>{"total"=>2, "successful"=>2, "failed"=>0}, "_seq_no"=>7529, "_primary_term"=>1}
```

Convert Flare Tag to json string before indexing

---

app/controllers/api/v0/comments_controller.rb
app/models/comment.rb
app/views/api/v0/comments/_comment.json.jbuilder
docs/api_v0.yml
spec/requests/api/v0/comments_spec.rb

This PR contains the following two fixes:
- deleted comments will appear like this in the tree of comments
```json
{
"type_of": "comment",
"id_code": "16",
"body_html": "<p>[deleted]</p>",
"user": {},
"children": [{}, {}]
}
```
- hidden comments will appear like this in the tree of comments
```json
{
"type_of": "comment",
"id_code": "16",
"body_html": "<p>[hidden by post author]</p>",
"user": {},
"children": [{}, {}]
}
```
I used the same text we use for the website. Their children comments won't be hidden or deleted, the logic checks each single comment to see if it shouldn't appear in full, like the website does.
I also added the comments API to the documentation.
#4474 at least regarding documentation

Comments API: hide deleted and hidden comments (plus docs)

---

public/404.html

The /public/404.html file has local styles for img and p tags. 
Later, 404.html is incorporated in a general dev.to "template" (how ?)
=> All images from this general page conform to the specific css defined in 404.html
I customized the styles defined in the 404.html head to limit their scope.
I think the styles defined locally in 422.html, 500.html and 503.html should also be reviewed. But I don't really understand how they are handled.
Closes #6373

Fix 404 page css

---

app/assets/stylesheets/dashboard.scss

Ensures the complete text 'Share with your co-workers or local communities. Ask people to leave questions for you in the comments. It's a great way to spark additional discussion.' is shown in manage your post page.
It could also be fixed by changing the negative margin, but that may introduce the same error if the text changes. So I added a ::before element with background for the next element.
#6523

removes negative margin and adds backgroundcolor to next element instead

---

app/controllers/article_approvals_controller.rb
spec/requests/article_approvals_spec.rb

Allow users to mark articles as approved if they are trusted and mod of _any_ tag on a post that requires approval, not _all_ of them, as it had been.

Allow tag mods to approve posts even if they mod just one tag

---

docs/api_v0.yml

Doing a PR review I found that Swagger was complaining about `ListingCreate` & `ListingUpdate` having a property declared as `type: date`. It should use `type: string` because it has `format: date-time` to flag it as a Date.
#6482 and that one should be merged first because this PR bumps the patch version.

API Specification: Change type 'date' to 'string' on Create/Update Listings

---

app/services/users/delete_activity.rb

We have a bug in production where our database has become out of sync with Elasticsearch. We identified some `ClassifiedListings` that were in Elasticsearch, but not in our database. This should never be the case.
I found that it was due to deleting user activity when banishing a user. We were calling `.delete_all` on `classified_listings` which skips callbacks and therefore we never deleted it from Elasticsearch.
This PR changes the logic to `.destroy_all` to trigger the callback so that any time a user is banished, their `classified_listings` will also be removed from Elasticsearch.
We'll want to manually remove the handful of affected `ClassifiedListings` from Elasticsearch using the production console to get things back in sync.

destroy_all classified_listings when deleting User activity

---

Envfile
app/models/user.rb
app/services/notifications/welcome_notification/send.rb
config/environments/production.rb
spec/requests/notifications_spec.rb
spec/services/notifications/welcome_notification/send_spec.rb

There is actually only [one relevant commit](https://github.com/thepracticaldev/dev.to/commit/78fde37d122142b5c1fbd4ef596fe61e0d23cf17) in this PR, as it branches off of #6483. 
Once #6483 is merged, and once we want have set the `mascot_user_id` on the SiteConfig, we want to use the mascot_user_id when sending out notifications. We also want to remove `WELCOMING_USER_ID`.
**Note: I will rebase on master once #6483 is merged!**
Paired with @juliannatetreault on this!
Branches off of the work in #6483.
Refactors the concept introduced in #6045.
N/A
**⚠️DO NOT merge this until:**
1)~#6483 has been merged and deployed~ DONE
2) An admin has set the `mascot_user_id` in our internal SiteConfig!

Use mascot_account in place of welcoming_account

---

app/serializers/search/article_serializer.rb
config/elasticsearch/mappings/feed_content.json
spec/serializers/search/article_serializer_spec.rb

Rather than trying to store the flare tag, which is actually a hash(see below), as a string and then having to parse it for the view lets store it as a hash.
```
{:name=>"help", :bg_color_hex=>"#111111", :text_color_hex=>"#FFFFFF"}
```
I also added a test to the serializer to confirm that it makes a valid hash for Elasticsearch. This will prevent us from adding a field to the serializer and then forget to add it to Elasticsearch bc the new test would raise a strict mappings error.

Store Flare Tag as a Hash in Elasticsearch

---

app/models/data_update_script.rb
spec/models/data_update_script_spec.rb

This fixes a bug we see as reviewers.
The startup check checks if the set of files on disk is different than the set of files in the DB. Unfortunately, when reviewing multiple branches, `master` might be ahead of other branches in terms of scripts ran, so this check will prevent the app from loading and it can't be fixed by re-running the scripts, because the number of scripts on disk is fewer than the number of scripts the DB has knowledge of.
To reproduce:
1. run the scripts on master
2. checkout an older PR which is not up to date with master
3. start the console or the server
Thus I think the only check we can do is: does the file system has more files than there are rows in the DB? If so we can be certain there are files to be executed, if there are less, we don't care, as it might …

Fix scripts startup check for development mode

---

app/liquid_tags/liquid_tag_base.rb
app/liquid_tags/podcast_tag.rb
app/liquid_tags/poll_tag.rb
app/liquid_tags/runkit_tag.rb
app/liquid_tags/tweet_tag.rb
app/views/articles/show.html.erb

With #6422 we accidentally broke some liquid tags rendering in articles, mainly those that have JavaScript to run.
I took the opportunity to put the JS in a frozen constant as well.
Closes https://github.com/thepracticaldev/dev.to/issues/6460
Closes https://github.com/thepracticaldev/dev.to/issues/6485
**before**
**after**

Re-enable correct operation of liquid tags with scripts in articles

---

app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb

We ended up not using `SiteConfig.campaign_background_color` and `SiteConfig.campaign_text_color` this time, so I removed these settings to avoid confusion in the future. 
#6141

Removed unused campaign settings

---

app/workers/field_tests/prune_old_experiments_worker.rb
lib/tasks/fetch.rake
spec/factories/field_test_memberships.rb
spec/workers/field_tests/prune_old_experiments_worker_spec.rb

This PR creates a task to remove the oldest 5% of a/b test participants and lets them go back into the pool. This will help the rolling tests stay relevant and let us test old participants with new approaches.
We may not want to do this for certain kinds of tests where we want to send someone through one dedicated path until we fully finish the experiment and ship a winner, but with the kind of everlasting experiment I think this is a solid approach.
Our logic for the ephemerality of a/b test results can change depending on experiment type, but I think something like this should apply to any "rolling/ongoing" test.
**After deploy we need to add this to Heroku Scheduler for once per day.**

Prune old field tests for ongoing experiments

---

app/javascript/chat/chat.jsx
app/javascript/listings/listings.jsx
app/javascript/readingList/readingList.jsx
app/javascript/shared/components/tags.jsx
app/javascript/src/utils/debounceAction.js

We [have been increasingly adding](https://github.com/thepracticaldev/dev.to/pull/6358#discussion_r385807411) `debounce` to various inputs in our app that send search queries to the ES backend. This has resulted in a lot of duplicated code with slightly different variations.
This PR abstracts out the core `debounce` concept into a util function that can be reused across our app whenever we find ourselves having to do this.
As the documentation explains, to use this function, you simply need to call it like so:
```javascript
debounceAction(this.myFunctionToDeounce.bind(this))
```
The default values for this function include a default wait time of `300`ms, and a default config that includes `{ leading: true }`. Both of these can be overridden like so:
```javascript …
```

Refactor debounce usage into debounceAction util

---

app/services/users/cleanup_chat_channels.rb

Lately, we have been seeing Sidekiq jobs fail due to this error which comes from trying to delete a chat channel membership from Elasticsearch that is not present. 
```
Search::Errors::Transport::NotFound: [404] {"_index":"chat_channel_memberships_production","_type":"_doc","_id":"123","_version":1,"result":"not_found","_shards":{"total":2,"successful":2,"failed":0
```
I traced the error back to the banish user endpoint and found in our `Users::CleanupChatChannels` that we were issueing multiple destroy commands on the same chat channels causing multiple jobs for removing them from Elasticsearch to get kicked off. I was able to verify this locally with a bit of logging(see below).
To fix this I refactored the job to allow the chat channel destroy to destroy the memberships and then reload …

Dont Issue Destroy Call to Chat Channel Memberships Multiple Times

---

app/assets/stylesheets/preact/article-form.scss

This change removes a large margin from the "preview image url" input form that:
1) didn't appear to be necessary
2) caused element overlap when viewing a post that had a video attached, which caused the preview image URL form to not be entirely visible!
This fixes #6311!
**As far as I know, we don't have a built-in way of testing this?

Allow preview image URL form to be visible for articles with videos

---

app/views/service_worker/index.js.erb

`/welcome` is a redirect route and should be ignored by our service worker.
https://github.com/thepracticaldev/dev.to/issues/5546#issuecomment-596078464
n/a
n/a

Skip /welcome in serviceworkers

---

app/models/article.rb
spec/factories/articles.rb
spec/fixtures/files/article_published_empty_cover_image.txt
spec/models/article_spec.rb
spec/requests/api/v0/articles_spec.rb

As @rhymes [pointed out to me](https://github.com/thepracticaldev/dev.to/pull/5660#pullrequestreview-347173956) in the context of another PR I made, we have a bug where we do not actually save a user's changes to their cover image on an article.
To see this in action, head over to production and:
1) Create a post with the cover image and save it.
2) Edit the post and remove the cover image and save.
3) Check out the post again; you'll see that the cover image is still there, even though you removed it.
This isn't a great experience, and we should allow users to actually persist this change.
However, I had some trouble getting the logic correct here because we can't just rely on the presence of `cover_image` in the `front_matter`; we need to be able to distinguish the scenario of when the …

Allow `cover_image` of an article to be removed

---

app/views/comments/_form.html.erb

A little while ago we introduced this `flash` message which isn't really used or needed in most context and results in cache leak based on how we do things...

Remove flash notice to avoid cache leak

---

.gitignore
db/seeds.rb

- create published podcasts while seeding, so that they could be displayed on the site after fetching the episodes
- schedule a worker to fetch podcast episodes after creating podcasts while seeding
The episodes will appear on the sire after the sidekiq jobs are executed.
We discussed the problem with the empty `/pod` section with @ludwiczakpawel before.

Improved the podcasts seeds

---

app/views/articles/tags/_sidebar.html.erb
app/views/pages/robots.text.erb

We currently get some bot traffic to endpoints like `/mod/javascript` which is just a waste of their resources since it shows nothing relevant and it's best to prevent that.
But why do they get there in the first place if we don't link to it? Of course, it's a public page so anyone could link to it, but that would be odd.
Ohhhhhhh we do link to it because we have a cache leak because we ask `user_signed_in?` inside a fragment cache that doesn't account for that. Not a sensitive leak or anything, but definitely a bug.

Disallow /mod/ in robots.txt

---

app/controllers/internal/users_controller.rb
app/models/user.rb
app/workers/users/delete_worker.rb
spec/requests/internal/users_spec.rb
spec/system/internal/admin_deletes_user_spec.rb

Deleting users without an email address led to the following error:
The reason for this is that we built the flash message using string concatenation instead of interpolation, which causes the above error when the user's email is `nil`:
```ruby
"email: " + nil
#=> TypeError: no implicit conversion of nil into String
```
Closes https://github.com/thepracticaldev/tech-private/issues/404

Allow admins to delete users without emails

---

app/services/search/client.rb

During @rhymes' recent work on `Search::Client` I suggested an improvement in the form of using `define_method` instead of repeatedly going through `method_missing` ([thread](https://github.com/thepracticaldev/dev.to/pull/6307/files#r384902241)). 
n/a

Search::Client refactor

---

config/initializers/honeycomb.rb

We have an extra Honeycomb client we don't use anywhere, we'll likely re-create it when we need it. In the meantime, one less object in memory :D

Remove extra HoneycombClient

---

app/controllers/api/v0/followers_controller.rb
app/models/follow.rb
app/views/api/v0/followers/_follows.json.jbuilder
app/views/api/v0/followers/organizations.json.jbuilder
docs/api_v0.yml
spec/requests/api/v0/followers_spec.rb

This PR does the following two things:
- documents `/api/followers/users`
- removes `/api/followers/organizations`
The organizations endpoint currently returns all the users of all the organizations a user belongs to, but other than being it'misleading (as the other one instead returns all the followers the authenticated user has), it also doesn't seem to respond to an actual need.
We also checked that it hasn't being recently used in production.
I think it's safe for removal.

API: add docs for /followers/users and remove organizations endpoint

---

app/views/pages/robots.text.erb

This disallows robots from `/internal/*` and `/admin/*` pages where they are not needed.
It still allows, for now, bots to go straight to `/internal` etc. without the trailing slash, which could be a log-in page instead of a strict disallow.

Add internal and admin to robots.txt disallow

---

app/liquid_tags/github_tag/github_readme_tag.rb
app/views/liquids/_github_readme.html.erb
spec/liquid_tags/github_tag/github_readme_tag_spec.rb

Our Github liquid tag raised an error when we tried to display a repository with no README unless the user specified the "no-readme" option. This PR fixes that.
Note: I found the code relatively hard to follow, so I refactored it quite a bit in the process. I'll add some more comments inline regarding the what/why.
Closes #6382 
Before:
After:
Repositories with READMEs work like before:

Github Liquid tag: Fix error when repository has no README + refactor

---

docs/installation/docker.md

`docker-compose up` already covers yarn install
n/a
n/a

Remove redundant yarn step for Docker

---

app/views/shell/_bottom.html.erb

Avoids broken titles like `The DEV &lt;&gt; Stackbit integration is in the running for a Product Hunt "Golden Kitty Award"` by replacing `.innerHTML` with `.textContent` which gets a raw copy of text node content.
❗️This bug only appears when articles are not accessed via internal navigation.
Closes https://github.com/thepracticaldev/dev.to/issues/5226

Don't escape markup sensitive characters in <title>

---

app/controllers/github_repos_controller.rb
spec/requests/github_repos_spec.rb

Removing a Github repo from pinning in the user's settings is currently broken. This PR fixes it.
Closes #6571

Fix Github repo pin and and unpin

---

config/routes.rb

I have implemented Hypershield manually so Blazer is now ready for prime time. Getting Hypershield set up within our application so it is automatic is going to take some work and likely some PRs to the gem itself and I didnt want to wait for all of that to allow devs access to this data. I am actually thinking to implement it ourselves might be the easiest and quickest solution since the gem is only a couple of files. But I wanted to get this out bc I think this will be a huge help for a lot of people. 
FOLLOW UP: https://github.com/thepracticaldev/dev.to/projects/5#card-34379497 
https://github.com/thepracticaldev/dev.to/projects/5#card-33593263

Allow Blazer to be queried by Tech Admins

---

app/assets/stylesheets/notifications.scss

Not really sure why this CSS rule is here and the git history doesn't give much of an explanation. It looks like it might have been added by accident.
before:
after:

Remove unnecessary CSS rule

---

config/application.rb
docs/troubleshooting.md

When we enabled CORS in #6116 we activated debugging only in development. The unfortunate side effect is that there's a lot of verbosity added to the logs and additional debugging headers sent with the request. All of this is unnecessary if a person is not actually trying to debug a CORS issue.
Therefore I propose we disable them by default and add an environment variable that allows quick debug if necessary.

Disable CORS logging by default in development

---

config/blazer.yml

STATEMENT_TIMEOUT is 8 seconds, I lowered Blazer to be closer to that since I am not totally sure that would take precedence over this Blazer setting.

Lower Blazer timeout to be closer to app STATEMENT_TIMEOUT

---

app/controllers/internal/podcasts_controller.rb
app/views/internal/podcasts/edit.html.erb
app/workers/podcasts/get_episodes_worker.rb
config/routes.rb
spec/requests/internal/podcasts_spec.rb

- added a feature for admins to manually fetch podcast's episodes from `/internal/podcasts`
Submitting a form will schedule an async job to fetch episodes.
- reorganized podcasts/edit page a bit
#271

Fetch podcast's episodes from /internal

---

app/serializers/search/user_serializer.rb
config/elasticsearch/mappings/users.json

Even though we dont search this field we need it for presenting the information in the view. 
https://github.com/thepracticaldev/dev.to/projects/6#card-34388442

Add profile image field to Elasticsearch for presenting after search

---

app/assets/stylesheets/base/reset.scss

We're currently not using `box-sizing: border-box;` in our reset.scss because it will probably break things visually with our current CSS. This laser focuses on just our design system components and adds `box-sizing: border-box;` to them.

Added box-sizing border-box to crayon components.

---

datadog/prerun.sh

HONEYCOMB_DISABLE_AUTOCONFIGURE is evaluated within ruby, not as a shell variable.
https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/crZqCFVuCQh/trace/mPgCgm2pUzT
https://ui.honeycomb.io/thepracticaldev/datasets/rails/result/yqQ8KgSJtC9/trace/cqT2zegzRbD
n/a

Make prerun.sh actually set the environment

---

app/assets/stylesheets/preact/article-form.scss
app/views/articles/_v2_form.html.erb

Recent css fixes caused some jumps when JS loads and other small issues. Just a bit of whac-a-mole fixes as we make css adjustments.
The jumps are inconsistent between chrome and ff. Prioritizing chrome if it's tough to make perfect between two.

Fix editor jump

---

app/models/response_template.rb
app/models/user.rb
app/services/users/delete_activity.rb
db/migrate/20200311170959_create_response_templates_table.rb
db/migrate/20200311201103_add_moderator_id_to_comments.rb
db/schema.rb
spec/factories/response_templates.rb
spec/models/response_template_spec.rb

This is a smaller version of https://github.com/thepracticaldev/dev.to/pull/5419, with only the model and database change. The goal is to split the huge PR of #5419 into smaller, more reviewable pieces.
This adds the response templates table to the DB.
No

Add response templates model and table

---

app/javascript/packs/onboardingRedirectCheck.jsx

During onboarding, I cannot access the privacy policy. When I try to do so, I am redirected back to the onboarding page.
- Start the onboarding process as a new user
- Click "Continue" below the cat animgif on dev.to/onboarding
- Click the link for the Terms and Conditions next to the checkbox labeled "You agree to our Terms and Conditions"
- In the "1. Terms" section, click the link for "Privacy Policy"
#5205 
- no

fix cannot read privacy policy redirect to onboarding

---

app/liquid_tags/katex_tag.rb
app/views/liquids/_katex.html.erb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/katex_tag_spec.rb

So far KaTeX tags could only be rendered in block form, this PR adds the option to render them inline instead.
Closes #6627

Allow KaTeX to render inline

---

app/assets/javascripts/initializePage.js.erb
app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb

When trying to find where in the code we search Algolia for articles I came across this `algoliaFollowedArticles` function. We initialize it but I could not find anywhere in the code it is used so I went ahead and removed it. Let me know if I am mistaken and if this is actually used!
https://github.com/thepracticaldev/dev.to/projects/6#card-32289432

Remove Unused algoliaFollowedArticles Function

---

app/services/rss_reader/assembler.rb

A user reported that their feed won't import despite being valid according to the W3C validator. The reason is the way categories are specified:
```xml
<category>
Category1,Category2
</category>
```
instead of 
```xml
<category>Category1</category>
<category>Category2</category>
```
Stripping away leading newlines in the tags fixes this.
https://github.com/thepracticaldev/tech-private/issues/412
* No `lstrip`
```ruby
RssReader.get_all_articles(true)
ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /Users/xxx/.asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/logger.rb:542:in `error'
Caused by ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /Users/xxx/.asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/logger.rb:542:in `error'
Caused by ActiveRecord::RecordInvalid: …
```

Remove leading whitespace in tags during RSS import

---

spec/models/tweet_spec.rb
spec/rails_helper.rb
spec/requests/liquid_embeds_spec.rb
spec/support/initializers/doorkeeper.rb
spec/support/initializers/vcr.rb

This fixes two warnings we've been having lately:
```
/devto/spec/requests/liquid_embeds_spec.rb:3: warning: already initialized constant VCR_OPTIONS
/devto/spec/models/tweet_spec.rb:3: warning: previous definition of VCR_OPTIONS was here
```
as we have two global constants with the same name. I also moved around Doorkeeper test support initializer into its own file

Fix VCR warnings and use initializers

---

db/seeds.rb

@juliannatetreault and I were just doing some 🍐ing and found ourselves wishing that this was just a part of our seeds file, so I went ahead and added it! This will be super useful for some of the work we're doing around welcome notifications for us folks on @thepracticaldev/delightful.
The HEREDOC is what we currently use as the default content when creating a welcome thread via the `/internal/welcome` pages, so I just used that as the default body markdown here for the seeds!
N/A
N/A

Add welcome thread to seeds file

---

Gemfile.lock
app/controllers/feedback_messages_controller.rb

This fixes the report abuse form, which broke because of an upgrade of the recaptcha gem (https://github.com/ambethia/recaptcha) we use: https://github.com/thepracticaldev/dev.to/pull/6657
Related:
- https://github.com/ambethia/recaptcha/pull/356
- https://github.com/ambethia/recaptcha/pull/354

Upgrade recaptcha to 5.4.1 to fix production error

---

app/assets/stylesheets/internal/layout.scss
app/views/internal/shared/_navbar.html.erb
app/views/layouts/internal.html.erb

The navbar in internal is a bit too much for a horizontal nav.
Because we aren't using breadcrumbs, it also indicates to users where
they are, so it needs to be visible and not collapsed.
Making this a sidebar fixes both of those problems. In this state, it is
definitely a barebones implmentation, but it is also an improvement over
the hornizontal nav.
Before:
After:

Add internal sidebar navigation

---

app/models/user.rb
db/seeds.rb
spec/models/user_spec.rb

I noticed how `User.dev_account` returns a `ActiveRecord_Relation` instead of a `User` object. The reason it does it's because it's defined as a `scope` but in this case we should define it as a regular method, as we're loading a specific object, not composing scopes.
I also wasn't able to create the welcome thread in the seed file, when I ran:
```ruby
Article.create!(
body_markdown: welcome_thread_content,
user: User.dev_account,
)
```
I got the following error:
```
ActiveRecord::AssociationTypeMismatch: User(#70164944078580) expected, got #<ActiveRecord::Relation [#<User id: 3
```
https://github.com/thepracticaldev/dev.to/pull/6687

Move dev/mascot account to class methods

---

db/seeds.rb

The seeded welcome thread that I added in #6687 actually included an image that would be broken in local dev, since attempts to use cloudinary locally via its URL.
I just decided to remove it since we don't necessarily _need_ an image there (I just copied what we use as the default content in `/internal/welcome`'s controller 🙃).
Thanks to @rhymes for catching this! 
#6687

Remove broken image from seeded welcome thread

---

app/controllers/search_controller.rb
app/services/search/feed_content.rb
app/services/search/query_builders/feed_content.rb
config/routes.rb
spec/requests/search_spec.rb
spec/services/search/feed_content_spec.rb
spec/services/search/query_builders/feed_content_spec.rb
spec/services/search/user_spec.rb

This PR adds the code to the backend that we will need to search for feed content(articles and podcast episodes) on the front end. Following this will be a PR that hooks up the frontend search which will be pretty involved so I definitely think splitting the front and backend code in this case is ideal. 
https://github.com/thepracticaldev/dev.to/projects/6#card-34785956

Add Feed Content Backend Search Code

---

app/assets/stylesheets/moderators.scss

I think this margin slipped in with another PR. It doesn't seem intentional!
**Before:**
**After:**
-  [x] no documentation needed

Remove negative margin rule

---

app/assets/stylesheets/comments.scss

I noticed how the comments preview doesn't space enough the various paragraphs.
So if this is text:
this is the preview:
I added some `line-height` to space them out a little more

Fix comments preview paragraph spacing

---

app/helpers/application_helper.rb
app/views/articles/index.html.erb
app/views/users/_meta.html.erb
spec/helpers/application_helper_spec.rb

A while ago @rhymes and I [discussed adding a helper for app internal URLs](https://github.com/thepracticaldev/dev.to/pull/6249/files#r383084345). Then @benhalpern added an `app_protocol_and_domain` helper, which has a similar intent.
This PR renames the existing method to `app_url` and refactors it so that we can add paths, fragments, etc. The included specs and YARD documentation illustrate this functionality. It relies on Ruby's `URI` implementation to do the heavy lifting.
NOTE: I did *not* yet refactor all places where this could potentially be used, I can do that in a follow-up PR. This only changes places where `app_protocol_and_domain` was used.
No ticket, this was my last personal TODO item for the cooldown period.

Introduce app_url helper

---

app/services/broadcasts/welcome_notification/generator.rb
spec/factories/broadcasts.rb
spec/requests/notifications_spec.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb
spec/services/notifications/welcome_notification/send_spec.rb
spec/workers/notifications/welcome_notification_worker_spec.rb

This is the first of many Welcome Notification PRs to come! This PR:
Closes #6700.
N/A

Add welcome thread welcome notification

---

app/services/podcasts/feed.rb
spec/services/podcasts/feed_spec.rb

Currently have a couple of Podcasts that have feed URLs that are suffering from too many redirects and try are causing a lot of failed Sidekiq Workers. Rather than trying over and over again lets mark them as problematic and fail gracefully. Also removed the unused `_e` variable.
https://app.honeybadger.io/fault/66984/83055eaafe5a38462a3f2f6e149a6f08

Dont let HTTParty::RedirectionTooDeep Errors kill Podcast Ep. Update Workers

---

app/controllers/search_controller.rb
app/models/podcast_episode.rb
app/serializers/search/article_serializer.rb
app/serializers/search/podcast_episode_serializer.rb
app/services/search/feed_content.rb
app/services/search/query_builders/feed_content.rb
app/services/search/query_builders/query_base.rb
config/elasticsearch/mappings/feed_content.json
spec/services/search/feed_content_spec.rb
spec/services/search/query_builders/feed_content_spec.rb

While hooking up a lot of the front end code I found some fields that we were missing in Elasticsearch so I added them. In addition, we use highlighting in the main feed. For example if you search "Ruby" it will show you the results of your search along with highlighted snippets from the article where "Ruby" was found. This adds that functionality to our searching and updates our docs to return it. 
Notice, a lot of the fields I am adding are purely for display purposes. _Ideally_, you don't want to have fields in Elasticsearch unless you are searching and using them. My hope is that we will end up searching and using these fields in the future. If not, then we can revisit removing them. For now, I think getting us flipped to Elasticsearch is worth putting an additional display field or …

Add Additional Search Fields and Search Highlighting

---

app/assets/javascripts/initializers/initializePodcastPlayback.js
app/models/podcast_episode.rb
app/views/podcast_episodes/show.html.erb
spec/models/podcast_episode_spec.rb
spec/system/podcasts/user_visits_podcast_episode_spec.rb

The Podcast player for mobile apps requires information that is sent through the `metadata` message. This PR adds the Podcast Image to be displayed with the locked screen controls.
It also includes the metadata as JSON in the HTML to avoid having to scrape the HTML using `querySelector`, which makes it more resilient to change in the future.
[The PR in the iOS repo meant to handle the podcast image](https://github.com/thepracticaldev/DEV-ios/pull/222)
Nope

Adds Podcast Episode metadata as JSON to avoid scraping the HTML

---

app/controllers/internal/users_controller.rb
app/workers/moderator/banish_user_worker.rb
spec/requests/internal/users_manage_spec.rb
spec/requests/internal/users_spec.rb
spec/workers/moderator/banish_user_worker_spec.rb

Banishing users sometimes does a lot of work, and can time out. This moves the request to the background and delivers a an appropriate flash message to the user.
It's a `high_priority` job, so the admin should be able to refresh after a few seconds to verify the success. I think in an ideal world we deliver the news as a real-time websocket notice, but all in all this is an improvement.
Should `flash[:success]` be red? Probably not, but outside scope of this issue.

Move banishing spam users to async job

---

app/javascript/listings/__tests__/singleListing.test.jsx
app/javascript/listings/singleListing/index.jsx

Tags were no longer displaying for classified listings. After some digging through our Preact components, I think I found the culprit, which is using `tag_list` instead of `tags` as prop for the `TagLinks` component.
@atsmith813 Tagged you directly, since you made changes to the corresponding serializer not too long ago, so I'm hoping you are better able to assess the validity of this fix.
Closes #6726
Before, tags flashed in and out of existence:
Tags now render fine:
And if they are needed I need help 😉

Use correct attribute for rendering tags in listings

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/preact/article-form.scss
app/views/articles/show.html.erb

This fixes a few issues in spacing.
`h1,h2..etc` tags bump right up against tags because they had zero top margin. This added a smidge of margin to the top of `.body` and a smidge to the top of the header tags as a compromise on each. `p` tags already had margin on top.
Editor buttons misaligned:
I think the basis for this is the space we need to make for this right now:
This PR makes the small adjustments to get rid of these visual bugs.

Fix style bugs on article-show and article-new

---

app/assets/stylesheets/settings.scss
app/views/users/_theme_selector.html.erb

The current color for the API description is invisible for the night theme
and very hard to read in the ten x theme
This fixes those by using a constant color across all themes.
I also added a description for all the themes:
Closes https://github.com/thepracticaldev/dev.to/issues/6339

UX: fix API description color in dark themes

---

app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/articles/show.html.erb
app/views/internal/configs/show.html.erb
app/views/service_worker/manifest.json.erb
app/views/shell/_top.html.erb
spec/requests/internal/configs_spec.rb

This image is used by PWA, but also other contexts similar to favicon etc. I believe Slack and other apps might use this data similar to other meta info like open graph etc.
It needs to be rendered to multiple sizes, but I think downsizing programmatically definitely makes more sense than actually naming a bunch of values.

Add logo_png SiteConfig for manifest etc. use

---

app/controllers/stories_controller.rb
app/views/articles/_collection.html.erb
app/views/articles/show.html.erb
spec/system/articles/user_visits_an_article_spec.rb

If a cross posted article has a publication date that precedes that of a regular article **but** a cross posting date that's more recent than the publication date of the regular article **and** they both belong to a collection, the cross posted article will appear as the first article in the collection, even though it should be the second.
It's easier to understand visually:
As you can see, the first article is published "Mar 21" and the second "Mar 15" but they appear in the wrong order.
This PR takes `crossposted_at` into consideration when ordering articles in a collection.
Closes https://github.com/thepracticaldev/dev.to/issues/6758
Correct order:

Fix collection order with cross posted articles

---

app/views/mailers/notify_mailer/new_reply_email.html.erb

When we send a new_reply_email for a comment we assume that there is a commendable. This is not always the case since an Article can be deleted and its comments will still remain. In the event that this happens, our email should not fail to send. I replaced the missing title with a "Content No Longer Available" message but we could also leave it blank. 
```
ActionView::Template::Error: undefined method `title' for nil:NilClass
new_reply_email.html.erb  12 _app_views_mailers_notify_mailer_new_reply_email_html_erb(...)
[PROJECT_ROOT]/app/views/mailers/notify_mailer/new_reply_email.html.erb:12:in `_app_views_mailers_notify_mailer_new_reply_email_html_erb'
10   <tr>
11     <td style='padding:20px;padding-bottom:30px;border-radius:3px;font-size:19px;background:#f4f4f4'>
12       <h2 …
```

Handle a missing commentable in new reply email

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feed.rb
config/field_test.yml
spec/services/articles/feed_spec.rb

This adds some new variants which take the approach of not randomizing at all _during_ the ranking progress, but entirely shuffling the top half of the results after ranking... This will mean way more variation from the top of the list so new top articles on each load.
But all the randomness is _after_ these are deemed to be top results for the user.

Add feed variants with shuffle post-ranking

---

package.json
yarn.lock

Follow up from attempt one in #6799.
I did the steps I did last time, which I should have done before putting the PR up for the webpack 5 upgrade. Steps to fake a Heroku deploy precompile step:
* run `bin/setup`
* run `yarn install --production=true`
* Temporarily explicitly set NODE_ENV in bin/webpack to “production” and run `bin/webpack`
After running those steps, any dependencies that need to be in dependencies in package.json (not devDependencies) will pop up in the webpack error logs.

Added missing dependencies for Heroku deploys

---

app/models/display_ad_event.rb

The `display_ad_events` table has 9 columns, 2 of them seem to be unused:
```text
context_id
counts_for
```
The first step is to tell Rails to ignore the columns, once tests pass, we deployed and we know nothing has broken, then we can actually remove the columns.
This will also save us memory with SELECT * operations.
Let me know if any of these should be kept for any reason.

Ignore unused display_ad_events columns

---

app/controllers/search_controller.rb
app/services/search/feed_content.rb
app/services/search/query_builders/feed_content.rb
spec/requests/search_spec.rb
spec/services/search/feed_content_spec.rb
spec/services/search/query_builders/feed_content_spec.rb

This PR fills in a few more things we need to search for feed content on the backend
1. Make sure User docs are returns with Articles and Podcast Episodes for the main feed. Optimize the flow for when we do filter by class name
2. By default only return published articles. We can change this later when we decide we want to be able to see unpublished ones like in internal
3. Update returned documents to have fields necessary for the view. 
4. Add fragment options to limit fragments to 2 and 75 characters. I tested this in the view and it seems to return the right chunk of data. 
https://github.com/thepracticaldev/dev.to/projects/6#card-34785956

More Backend Feed Search Updates

---

app/models/comment.rb
app/serializers/search/comment_serializer.rb
spec/models/comment_spec.rb
spec/serializers/search/comment_serializer_spec.rb

With our new Feed search is going to come the ability to also search for Comments.
This PR begins indexing Comments into Elasticsearch. I am not including a full index of them yet, bc like articles I want to hook up the front end to make sure everything we need to present them is in Elasticsearch. Once that is validated I will issue a PR to get everything synced
https://github.com/thepracticaldev/dev.to/projects/6#card-35019750

Index comments into FeedContent index

---

app/controllers/stories_controller.rb

SQL functions calls in strings should be quoted with `Arel.sql()`, otherwise they raise deprecation warnings and eventually errors. Forgot one in #6768 
Thanks for the catch @citizen428!

Add ARel SQL quoting to COALESCE

---

spec/system/articles/user_visits_an_article_spec.rb

This spec has been very flaky lately and I believe its because when we create both articles the published_at times sometimes are the same and therefore the order of them gets messed up. This ensures that the first article has a publised_at date way in the past rather than the current time.

Flaky Spec Fix: Ensure Article Published dates are far enough apart

---

app/views/mailers/notify_mailer/new_reply_email.html.erb

One more place in the new_reply_email where we need to check for commendable. I missed this before bc it was in the HTML and I glazed right over it. 
```
ActionView::Template::Error: undefined method `path' for nil:NilClass
new_reply_email.html.erb  15 _app_views_mailers_notify_mailer_new_reply_email_html_erb(...)
[PROJECT_ROOT]/app/views/mailers/notify_mailer/new_reply_email.html.erb:15:in `_app_views_mailers_notify_mailer_new_reply_email_html_erb'
13       <%= @comment.processed_html.html_safe %>
14       <a style="background:#3c7dc1;color:white;padding:5px 14px;border-radius:3px;text-decoration:none;display:inline-block;margin-top:4px;" href='https://dev.to<%= @comment.path %>'>view on dev.to</a>&nbsp;
15       <a style="background:#1f1f1f;color:white;padding:5px …
```

Only show Commentable link to if Commentable Exists

---

app/helpers/application_helper.rb
app/services/slack/messengers/feedback.rb
app/services/slack/messengers/note.rb
app/services/slack/messengers/potential_spammer.rb
app/services/slack/messengers/rate_limit.rb
lib/app.rb
spec/lib/app_spec.rb
spec/services/slack/messengers/feedback_spec.rb
spec/services/slack/messengers/note_spec.rb
spec/services/slack/messengers/potential_spammer_spec.rb
spec/services/slack/messengers/rate_limit_spec.rb

Thanks to the awesome work by @citizen428 in #6715 and a brief discussion we had in private about extending `ApplicationHelper.app_url` outside the views I added this new module: `App`, which contains this three methods:
- `App.protocol` which returns `ApplicationConfig["APP_PROTOCOL"]`
- `App.domain` which returns `ApplicationConfig["APP_DOMAIN"]`
- `App.url(path)` which can be used to generate a full URL outside the views
I also changed `ApplicationHelper.app_url` to call this, I haven't removed the existing tests.
Finally, I started using in Slack messengers, see #6748 
`App.url()` shoud save us quite a lot of typing, and probably we can add `.protocol` and `.domain` to the `ApplicationHelper` in the future.
ps. initially we were about to call this `Utils.app_url` but `utils` modules …

Add App.url and use it with Slack messengers

---

app/assets/stylesheets/preact/onboarding-modal.scss

Small, somewhat temporary UI change to fix the awkward spacing on onboarding...
(Temporary because we have bigger changes in the pipeline)

Add some margin above onboarding h2

---

app/assets/stylesheets/signup-modal.scss

More px to bottom on .global-signup-modal--inner-a class for small computers. Better design.
With my little screen, I could see the popup like this.
with 
```css
bottom: calc(10% - 33px);
```
it is now better presented :

Edited bottom of .global-signup-modal--inner-a

---

app/services/search/query_builders/feed_content.rb
app/services/search/query_builders/query_base.rb
app/services/search/user.rb

When we are returning documents for the view we don't want to return ALL of the documents since we only need a few fields. Using the [_source filtering option](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-source-filtering) is the same as doing `select(<fields>)` for Postgres. It will limit what fields are returned.

Filter Elasticsearch Source Feed Docs and Add User Fields

---

app/controllers/search_controller.rb
spec/requests/search_spec.rb

While doing some testing for feed searching I noticed that if you are not signed in(Incognito window) then you can't search the feed or classified listings. Since we want people to be able to search for things even if they are not signed in I updated the controller to only force authentication for Tags(only used when writing an article which you have to be signed up to do) and chat channels(have to be signed up to search those as well).

Allow Any User to Search Feed, Users, and Classified Listings

---

app/labor/random_gif.rb
app/services/notifications/milestone/send.rb
app/views/notifications/_milestone.html.erb
spec/labor/random_gif_spec.rb

Refactored this class in order to fix: https://app.honeybadger.io/fault/66984/964ed1cc582e1de60601668839a2a279
```
ActionView::Template::Error: no implicit conversion of Symbol into Integer
random_gif.rb  30 [](...)
[PROJECT_ROOT]/app/labor/random_gif.rb:30:in `[]'
28 
29   def get_aspect_ratio(id)
30     (@random_gifs[id] || "xjZtu4qi1biIo")[:aspect_ratio]
31   end
32 end
```

Bug Fix: Return default aspect ratio of 1 if gif id is not present

---

docs/deploy-script.js

Based on https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata, the environment variable `URL` is taken / used already by Netlify.
This switches the old ENV variable from `URL` to `subdomain`.

Use subdomain env var for Netlify deploys

---

app/controllers/internal/negative_reactions_controller.rb

After looking at this UI in production, I realized that showing only
five negative reactions per page was way too few! Bumping this up to 25
which I feel is more reasonable.

Increase the number of negative reactions per page

---

app/services/search/base.rb
app/workers/metrics/record_data_counts_worker.rb
lib/tasks/fetch.rake
spec/workers/metrics/record_data_counts_worker_spec.rb

This PR renames the `RecordDbTableCountsWorker` to `RecordDataCountsWorker` and adds logic to also record Elasticsearch index sizes to Datadog.
It should be fine to rename the worker in one go without aliasing this since the current task only runs daily. There shouldn't be any hanging jobs as long as we don't deploy this close to the scheduled run time of that task.
https://github.com/thepracticaldev/dev.to/projects/6#card-34722425
Someone with Heroku access will need to remove the `record_db_table_counts` task from the scheduler and replace it with the `record_db_counts` task.

Log Elasticsearch index counts to Datadog

---

app/dashboards/article_dashboard.rb
app/models/article.rb
app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

The `articles` table has 90 columns, I've identified 19 of them that seem to be unused:
```text
abuse_removal_reason
allow_big_edits
allow_small_edits
amount_due
amount_paid
automatically_renew
collection_position
featured_clickthrough_rate
featured_impressions
ids_for_suggested_articles
job_opportunity_id
last_invoiced_at
lat
long
main_tag_name_for_social
name_within_collection
paid
rating_votes_count
removed_for_abuse
```
The first step is to tell Rails to ignore the columns, once tests pass, we deployed and we know nothing has broken,
then we can actually remove the columns.
This will also save us memory with `SELECT *` operations.
Let me know if any of these should be kept for any reason.

Ignore unused articles columns

---

app/controllers/display_ad_events_controller.rb
app/dashboards/display_ad_dashboard.rb
app/models/display_ad.rb

The `display_ads` table has 14 columns, 2 of them seem to be unused:
```
cost_per_click
cost_per_impression
```
The first step is to tell Rails to ignore the columns, once tests pass, we deployed and we know nothing has broken, then we can actually remove the columns.
This will also save us memory with `SELECT *` operations.
Let me know if any of these should be kept for any reason.

Ignore unused display_ads columns

---

app/models/article.rb

I sleepily merged this PR and then realized the problem.
https://github.com/thepracticaldev/dev.to/pull/6781
`rating_votes_count` actually is used via the `counter_culture` gem. I noticed some possible further confusion in the thread to this regard.
This behavior is only found in within the `RatingVote` model.
```ruby
counter_culture :article
```
Sorry about confusion here.

Revert rating_votes_count removal

---

Gemfile.lock

Our bundle was locked to Octokit 4.0.17, which got yanked from RubyGems:
This means we can't bundle on Travis and all builds fail. 
According to the Octokit docs:
> This library aims to adhere to Semantic Versioning 2.0.0. Violations of this scheme should be reported as bugs. Specifically, if a minor or patch version is released that breaks backward compatibility, that version should be immediately yanked and/or a new version should be immediately released that restores compatibility.
n/a

Bump Octokit to 4.0.18

---

spec/requests/internal/response_templates_spec.rb

[This dependabot build](https://travis-ci.com/github/thepracticaldev/dev.to/builds/155520748#L1842) failed because of a single quote:
```text
1) /internal/response_templates GET /internal/response_templates/:id/edit renders the response template's attributes
Failure/Error: expect(response.body).to include(response_template.content, response_template.title, response_template.content_type, response_template.type_of)
expected "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta http-equiv=\"X-UA-C...793a4a09813d06453eaebf59524563d836c30580ab1a1f169d7f7d085733b8.js\"></script>\n\n</body>\n</html>\n" to include "The Needle's Eye684"
```

Fix flaky response_template test

---

app/controllers/classified_listings_controller.rb
spec/requests/classified_listings_spec.rb

Fixes: https://app.honeybadger.io/fault/66984/0d65dc7ed8553fc9234e71bbdf5f059a
```
NoMethodError: undefined method `id' for nil:NilClass
classified_listings_controller.rb  15 index(...)
[PROJECT_ROOT]/app/controllers/classified_listings_controller.rb:15:in `index'
13 
14     if params[:view] == "moderate"
15       return redirect_to "/internal/listings/#{@displayed_classified_listing.id}/edit"
16     end
```

Bug Fix: Handle Missing @displayed_classified_listing for Moderate Views

---

bin/setup

When we setup the app we automatically update Elasticsearch in development mode. This PR adds the setup task for the testing environment as well. 
When you run the entire test suite the first thing we do is set up out Elasticsearch indexes so they are there if a spec needs them. To refresh them for a spec you add the tag `elasticsearch: true`. The problem with this is if you are running a single spec that inadvertently tries to index a document but you have never run an `elasticsearch: true` spec before or the whole suite, you will be missing those Elasticsearch test indexes.  This ensures that never happens. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35229387

Setup ES test environment during bin/setup

---

lib/data_update_scripts/20200326145114_re_index_feed_content_to_elasticsearch.rb
spec/lib/data_update_scripts/re_index_feed_content_to_elasticsearch_spec.rb

First we clear out the incorrectly indexed documents that are in Elasticsearch(due to the ID bug #6729) then we index Articles, Podcast Episodes, and Comments. This PR needs to be merged before #6847 so that we can ensure all documents are in Elasticsearch and ready to go
https://github.com/thepracticaldev/dev.to/projects/6#card-35222706

Sync Feed Content Documents in Elasticsearch

---

app/assets/stylesheets/notifications.scss
app/policies/user_policy.rb
app/services/broadcasts/welcome_notification/generator.rb
app/services/notifications/welcome_notification/send.rb
app/views/notifications/_broadcast.html.erb
app/views/users/_notifications.html.erb
db/migrate/20200324170819_add_welcome_notifications_to_users.rb
db/schema.rb
spec/requests/notifications_spec.rb
spec/requests/user/user_settings_spec.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb

Allows users to opt-out and unsubscribe from welcome notifications! I also refactored the tests and added some `TODO`s for @thepracticaldev/delightful.
Something to note here is that we will _always_ show the "unsubscribe" check box on the `/settings/notifications` page. I went with this approach because it seems weird to not show that option on the settings page (or even on the bottom of the notification) if someone's account was created 7 days ago (imagine someone logging in after 8 days and seeing these welcome notifications and wanting to unsubscribe but not seeing the option to do so?).
In the future, I'm sure we'll have more notifications sent via our platform, so we might want to consider splitting out the `/settings` route into `/settings/email` and `/settings/notifications`. …

Allow users to opt-out of welcome notifications

---

app/assets/stylesheets/settings.scss
app/controllers/response_templates_controller.rb
app/controllers/users_controller.rb
app/views/response_templates/index.json.jbuilder
app/views/users/_response_templates.html.erb
config/routes.rb
spec/requests/response_templates_spec.rb

This adds response templates to the settings page. Note that it does not make a link visible, but it is technically available via the direct route `/settings/response-templates`.
Users who access this page will be able to complete basic CRUD for personal response templates.
Also removes some dead CSS.
#5419 
No

Add response templates to user settings

---

app/views/users/_notifications.html.erb

A quick fix to #6852, which hardcoded `"DEV"` rather than using `ApplicationConfig['COMMUNITY_NAME']`. Oops! 🙈 
Shoutout to @rhymes for [pointing this out](https://github.com/thepracticaldev/dev.to/pull/6852#issuecomment-604605493).

Use dynamic community name rather than hardcoding "DEV"

---

app/views/internal/configs/show.html.erb

In order to give more team members read-only access to `SiteConfig`, we need to further restrict the part where we print the `ApplicationConfig` which contains a bunch of sensitive keys.

Ensure non-super-admins cannot see ApplicationConfig

---

config/routes.rb
spec/requests/user/user_settings_spec.rb

This fixes a routing issue where response templates wouldn't work because the `:id` param was blocked.

Use constraints and different params for settings

---

config/webpack/test.js

webpacker no longer outputs full webpack logs, only errors, if any. For more information, see the webpack [stats](https://webpack.js.org/configuration/stats/) documentation.
Current Travis Build 👇🏻

Now webpack logs only display errors on Travis

---

app/javascript/.storybook/main.js
package.json

Similar to #6897 for webpacker, but Storybook is a little different in regards to webpack. It has two webpack builds. One for the Storybook Manager and one for the Storybook’s preview iframe.
Current Build Log 👇🏻
```
yarn run v1.22.4
$ build-storybook -c app/javascript/.storybook -s app/assets
info @storybook/preact v5.3.17
info 
info clean outputDir..
info => Copying static files from: app/assets
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom manager config.
info => Compiling manager..
info => manager built (7.18 s)
info => Building preview..
info => Loading preview config..
info => Loading presets
info => Loading config/preview file in "app/javascript/.storybook".
info => Adding stories defined …
```

Travis: display only error logs for Storybook preview build

---

spec/support/initializers/capybara.rb

After merging #6865 we don't need to explicitly silence Puma in system tests anymore, as it's the default now: https://github.com/rspec/rspec-rails/pull/2289
#6865

Remove redundant Puma silencing in system specs

---

app/assets/stylesheets/sidebar-data.scss
app/views/articles/tag_index.html.erb
app/views/articles/tags/_sidebar.html.erb

The pagination PR #6771 mostly works as intended with no critical issues, except that is not respecting the `user_signed_in?` logic and proper `@page` logic due to caching in prod.
Also messed with some of the range logic because we weren't really counting all the cases properly. Also added a "midpoint" and "endpoint" link in order to create fewer jumps from the home page to all tagged content
More info here about that concept:
https://www.portent.com/blog/seo/pagination-tunnels-experiment-click-depth.htm
Due to the caching bug in prod right now, I'd like to get this in quickly if tests continue to pass.

Fix fragment caching bug for SEO tag pagination.

---

app/services/search/base.rb
config/elasticsearch/mappings/chat_channel_memberships.json
config/elasticsearch/mappings/classified_listings.json
config/elasticsearch/mappings/feed_content.json
config/elasticsearch/mappings/tags.json
config/elasticsearch/mappings/users.json
spec/services/search/base_spec.rb

The same way we have updated_at on the majority of our Postgres tables, we also want a timestamp on our Elasticsearch documents to tell us when they were indexed. This is not going to be used for anything immediately but in my experience this is something we will want in the future for debugging or just looking up recently created or updated documents. It also gives us a timestamp to use when setting up [Kibana for our cluster](https://www.elastic.co/kibana).
https://github.com/thepracticaldev/dev.to/projects/6#card-35285752

Add last_indexed_at Timestamp to all Elasticsearch indexes

---

.travis.yml

We currently have all of the master build statuses reporting to our #deployment-pipeline channel which makes things a bit noisy. I would like to change this to only report failures, ie times when we need to take action. If this works out how I would like then I will move these alerts to our dev heads-up channel so that we can stay on top of them better. 
We have had a few failed deploys and builds that have gone unnoticed until hours later. Everyone needs to be responsible for their own builds and this will help them do that. 
https://github.com/thepracticaldev/dev.to/projects/5#card-35044387

Report only travis failures and first following success to slack

---

bin/docker_setup
docs/installation/docker.md

In a recent PR @rhymes [suggested](https://github.com/thepracticaldev/dev.to/pull/6803#discussion_r397070289) adding a setup task for Docker. I did that initially, but found no compelling reason for this to be a Rake task, so I moved it to `bin/docker_setup` instead and kept it as close as possible to `bin/setup`. I also made several updates to the README, see comments.
n/a

Add docker_setup script

---

app/javascript/packs/validateFileInputs.js
spec/system/comments/user_fills_out_comment_spec.rb

There was an [error](https://github.com/thepracticaldev/dev.to/projects/9#card-35296954) where a user tried to upload an image with a _very_ long file name. I updated the client-side validation to check the length of the file name. The default max is set to 250 characters and it can be overridden with a data attribute on the file form field as needed.
- https://app.honeybadger.io/projects/66984/faults/62329414
- https://github.com/thepracticaldev/dev.to/projects/9#card-35296954

Validate file name length for file uploads

---

Dockerfile
docker-compose.yml
docs/installation/docker.md

I had an issue when setting up dev.to in my local environment using docker, similar to #4962. I thought I could just add it in my `docker-compose.yml`, and as it turns out there's only one value for the redis setup in docker-compose, which is `REDIS_URL` while it also needs `REDIS_SESSIONS_URL`. And I was supposed to put them in `config/application.yml`.
In my opinion, these are specific setup for the tools, and it should have been in their respective tool's config, not in `application.yml`. My idea is to set them on `docker-compose.yml` and `Dockerfile` and I can confirm it works fine on my local at least on the `docker-compose` approach. Adding it in `application.yml` can also be redundant since `REDIS_URL` is already defined in `docker-compose.yml`.
I might be missing something obvious …

refactor(docker): move redis env config to docker

---

public/offline.html

This is really a minor thing, but when I'm on the offline page, I can't seem to draw freely on top of certain elements:
Since it says I can draw anywhere on the page, it should have been like this:
I think it can be achieved with `pointer-events: none` on both elements when drawing. Looks like a hack, sure, but let me know what you think!
N/A
Yep, up there

refactor(offline.html): allow paint over pallete

---

app/assets/stylesheets/notifications.scss

Whenever someone reacted to a post, the link colour was black, which is hard to read on dark themes.
~~Changed the colour from black to white.~~
Removed `@include themeable-important(color, theme-color, $black);`.
Now the article title (link) uses the default colours for links. This way it is easier to see the links on both light and dark themes.
[Article link in notifications is black #6907](https://github.com/thepracticaldev/dev.to/issues/6907)
Closes #6907
Closes #6911 
`Test post` was black before. It was hard to read on dark themes.

Themes: use default colors for links in notifications

---

app/models/page.rb

Ignoring columns that are unused in the `Page` model:
```text
group
group_order_number
```
These will be removed once this is live.

Ignore unused pages columns

---

app/dashboards/podcast_episode_dashboard.rb
app/models/podcast_episode.rb
app/serializers/search/podcast_episode_serializer.rb

Ignoring columns that are unused in the `PodcastEpisode` model:
```text
deepgram_id_code
duration_in_seconds
featured
featured_number
order_key
```
These will be removed once this is live.

Ignore unused podcast_episodes columns

---

app/services/broadcasts/welcome_notification/generator.rb
app/views/notifications/_broadcast.html.erb
db/seeds.rb
spec/factories/broadcasts.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb

Adds a "customize your experience" welcome notification, which will be sent out 5 days after a user has signed up.
Also fixes an HTML typo, and cleans up some specs/renames some methods for clarity.
**Please note that once this PR is approved, I will add the appropriate broadcast to the `/internal/broadcasts` page!**
Closes #6707

Prompt new users to customize their experience 

---

app/views/internal/broadcasts/_form.html.erb

Makes a few tweaks to the default options when an admin visits `/internal/broadcasts`. Mostly prompted because I have been adding broadcasts and I keep accidentally setting them to be active!
* Ensure that "active" defaults to `false`.
* Ensure that the broadcast type is set to `"Welcome"` by default.
N/A

Tweak /internal/broadcast form

---

app/models/tag.rb
lib/data_update_scripts/20200324133751_update_tag_hotness_scores.rb
spec/lib/data_update_scripts/update_tag_hotness_scores_spec.rb

Through some investigative work, I found that [we are not using reactions_count](https://github.com/thepracticaldev/dev.to/pull/6781#issuecomment-602835034) for articles or comments but instead we only [update `postive_reactions_count`](https://github.com/thepracticaldev/dev.to/blob/master/app/models/concerns/reactable.rb#L9) therefore that is the value we should be used when calculating the Tag hotness score. I included a data update job to fix all Tag hotness scores.

Hotness Score for Tags Should Use Article positive_reactions_count 

---

app/views/users/_account.html.erb

hide api keys in details/summary tag
hides api keys in details/summary tag
closes https://github.com/thepracticaldev/dev.to/issues/6930

Hide API keys in details/summary tag

---

.travis.yml

I noticed that in our Slack we are still getting notifications for branches that are not master. I updated our yml file to use [the current suggested method for only getting the master branch](https://docs.travis-ci.com/user/notifications/#conditional-notifications)

Report ONLY changes in master branch status on Travis

---

spec/services/articles/feed_spec.rb

This change seems like the original intention of `NON_DEFAULT_EXPERIMENTS`. This also boosts our test coverage of `Articles::Feed` and reduce the chance of 
```
codeclimate/total-coverage — 93% (-0.1% change)
```
from appearing on other PRs.
n/a
n/a

Update feed_spec's use of NON_DEFAULT_EXPERIMENTS

---

app/models/article.rb
app/models/reaction.rb
spec/models/article_spec.rb
spec/models/reaction_spec.rb

This PR begins indexing reactions to Elasticsearch. As I have done in the past I am not including a full reindex DataUpdate Worker in this PR bc I want to make sure I am not missing anything which I usually find out when I implement search 😉 
https://github.com/thepracticaldev/dev.to/projects/6#card-35297922

Index Reading List Reactions 

---

app/controllers/internal/users_controller.rb
app/views/internal/users/_activity.erb
app/views/internal/users/_credits.erb
app/views/internal/users/_notes.erb
app/views/internal/users/_user_organizations.html.erb
app/views/internal/users/edit.html.erb

The `/internal/users/{id}` could be very costly to load for users with many notes and organizations, since it was loading all notes and organizations and memberships.
Changes:
- Use counter caches instead of counting from databases. (activities)
- Refactor organization credit UI to one form with select, instead of many forms.
- Loads only 10 most recent notes for the user. (I could add a link to a users/{id}/notes if you guys use that information a lot)
- Refactor Membership UI into a table to minimize screen space usage.
https://github.com/thepracticaldev/dev.to/issues/6674
No.

Refactor internal user page

---

app/dashboards/organization_dashboard.rb

Removes a column from the admin dashboard, since the column is now `ignored`.
Fixes https://app.honeybadger.io/fault/66984/028cfa37ca5f30b75466f31605cc4a09
Resolves https://github.com/thepracticaldev/tech-private/issues/419

Remove ignored column `address`

---

app/controllers/stories_controller.rb

The sidebar HTML uses the current_user.id in order to set a filter for a user's post. However that is cached on the edge in Fastly so we need to make sure the cache key contains the current_user.id if there is one. If not that is fine bc that button is not usable if you are not signed in. It will prompt you to signup

Set search cache header using the current_user id if present

---

app/views/layouts/_user_config.html.erb

We have some logic to hide the top nav if in the context of an iframe. because we use this for spinning up pages in some contexts..
Right now, due to a rearranging of the functions, the logic isn't working and the top bar is showing up _within_ the page, which doesn't make sense.
This was originally rearranged because we were using a guard clause in the original proposal, but if it's a simple `if` statement, there's nothing wrong with it coming after.

Rearrange order to fix iframe logic

---

app/assets/stylesheets/components/indicators.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/themes/minimal.scss
app/assets/stylesheets/themes/night.scss
app/assets/stylesheets/themes/pink.scss
app/views/layouts/_top_bar.html.erb
app/views/pages/crayons.html.erb

This PR is meant to fix some coloring issues for Crayons' indicators. They were looking a a little off on certain themes. I have also introduced variables for these colors.

Fixing Crayons indicators

---

app/assets/javascripts/initializers/initializeArticleReactions.js
app/views/articles/_actions.html.erb

Whenever we show a draft article the client asks the reactions count to the server and the fails abruptly because the actual reaction buttons and countners aren't in the DOM at all:
```erb
<% if @article.published? %>
<button id="reaction-butt-like" class="article-reaction-butt like-reaction-button" data-category="like" alt="heart-emoji" title="heart">
</button>
...
```
With this PR we avoid calling the server at all.

Avoid requesting reaction counts for draft articles

---

app/assets/images/cancel.svg
app/assets/images/external-link-logo.svg
app/assets/images/facebook-logo.svg
app/assets/images/favorite-heart-outline-button.svg
app/assets/images/image-upload.svg
app/assets/images/info.svg
app/assets/images/keyboard-left-arrow-button.svg
app/assets/images/keyboard-right-arrow-button.svg
app/assets/images/lightning.svg
app/assets/images/link.svg
app/assets/images/refresh-button.svg
app/assets/images/ribbon.svg
app/assets/images/star.svg
app/assets/images/three-dots.svg
app/assets/images/video-camera.svg

While reviewing #6964 I've noticed how Google Lighthouse was complaining about non unique IDs on the page:
Some of our SVG icons have the same ID, those IDs are not used anywhere, so I simply remove those that were duplicated.
**after**

Remove non unique SVG ids

---

app/assets/stylesheets/notifications.scss

Replaced `@include themeable(color, theme-color, $dark-gray);` with `color: var(--body-color);`.
The issue is that the text is black regardless of the theme. On light themes, it looks fine, but on dark themes, you cannot see the text. See pictures below:
Closes #6995
The text looks properly now. **I didn't include white/pink themes because the text already works the same with `color: var(--body-color);`**

Replaced themeable with body-color

---

app/services/edge_cache/commentable/bust.rb
app/services/moderator/delete_user.rb
app/workers/articles/score_calc_worker.rb
spec/requests/internal/users_manage_spec.rb
spec/services/edge_cache/commentable/bust_spec.rb
spec/services/moderator/delete_user_spec.rb
spec/workers/articles/score_calc_worker_spec.rb

Few more places we are indexing Articles to Algolia manually and need to also be indexing them to Elasticsearch. In one instance we are not actually updating the article and only updating a relation. In the other instance, we are using update_column which will not trigger the indexing callback.
https://github.com/thepracticaldev/dev.to/projects/6#card-35556485

Index Articles to Elasticsearch when adding Comments and Syncing Scores

---

app/dashboards/user_dashboard.rb

This PR deletes the non-existent method `organization` from the `user_dashboard.rb` model. However, I'm tagging this PR a WIP because this seems too simplistic a solution for me (I'm wary of solutions that involve only deletions, unless working on tech debt lol).
In my mind, there are clear associations between users and organizations; however, when I investigated within the error console, the User instance/object within the admin dashboard has the attributes `org_admin` and `organization_info_updated_at`, but not `organization` or `organizations`.
I don't trust my solution is all I'm saying. Thanks for reading!
[HoneyBadger Error](https://app.honeybadger.io/projects/66984/faults/62413832)
None
None

Delete non-existing method "organization" from user_dashboard model

---

app/views/sitemaps/show.xml.erb

I notice we are _outputting_ the result of this loop at the end. Seems to have not affected the validity of the sitemap, but definitely worth fixing!
This should fix performance for crawlers by radically reducing the number of bytes going over the wire.

Fix erb output on sitemaps

---

app/models/article.rb
spec/models/article_spec.rb

Make sure articles are reindexed in Elasticsearch when reacted to.
https://github.com/thepracticaldev/dev.to/projects/6#card-35510357

Reindex Articles in Elasticsearch When touched by Reactions

---

app/services/users/delete_articles.rb
app/services/users/delete_comments.rb
spec/services/moderator/banish_user_spec.rb
spec/services/users/delete_articles_spec.rb
spec/services/users/delete_comments_spec.rb

Remove Comments and Articles from Elasticsearch when we delete them and no callbacks are triggered. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35563612

Remove Comment and Article docs From Elasticsearch During User Delete

---

app/serializers/search/podcast_episode_serializer.rb

When searching for Feed Content in Elasticsearch we default search for published content. In Algolia we set to true always however there are times when a Podcast might have episodes but has not been published yet. In that case, we will not want to return those episodes in search. 
Lots of bug fixing is going on right now which is why this PR does not contain a full resync

Delegate Podcast Episode published in Elasticsearch to Podcast

---

app/controllers/users_controller.rb
spec/requests/users_onboarding_spec.rb

Ensures that we don't `assign_attributes` on a user blindly. Sanitizes the user params to ignore any blank attributes, and only updates attributes on a user that have a value/are not blank.
Closes #6985.

Avoid clobbering user attributes with empty params during onboarding

---

app/views/social_previews/tag.html.erb

This brings the styles up-to-date with our general look for the tag social preview and ensures longer tag names don't overflow in the design.

Update style for tag social preview

---

config/routes.rb

- removed  `/p/rly`, `/p/scholarships`, `/p/wall_of_patrons` and `/p/twitter_moniter` routes because the corresponding actions were missing in the `PagesController` and these pages are 404 anyway
- added a redirect from `/p/rlyweb` from `/rlyweb` because there is no point in rendering the same action for the 2 urls in this case
#7021

Removed unused pages routes

---

app/models/user.rb
app/serializers/search/user_serializer.rb
app/services/moderator/banish_user.rb
config/elasticsearch/mappings/users.json
spec/rails_helper.rb
spec/serializers/search/user_serializer_spec.rb

In Algolia we remove users when they are banned. In Elasticsearch the goal is to always have all of our data in it but then use filters to ensure we only search for the data we want at any given time. This means we need a way to exclude banned users from our search. I decided rather than having a "user status" adding the roles would likely be more helpful. We could also use these to search for mods and admins in the future. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35575574

Index User Roles to use to Filter out banned users

---

app/workers/rating_votes/assign_rating_worker.rb
spec/workers/rating_votes/assign_rating_worker_spec.rb

Ensure that articles are indexes after their ratings are updated since we store those in our Elasticsearch docs and I believe they will likely be something we want to search on in the future.

Index Articles after Ratings are Updated

---

app/models/article.rb
app/serializers/search/article_serializer.rb
spec/serializers/search/article_serializer_spec.rb

Currently in [Algolia we sort one of our indexes by hotness and search score](https://github.com/thepracticaldev/dev.to/blob/master/app/models/article.rb#L198). In order to try and mimic that as best as possible in Elasticsearch, we need to be indexing that field. 
Once again, there is not sync script in here bc I am in bug fixing and finding mode still. That will be added once all the bugs have been squashed. At least all the important ones. 😉 
NOTE: Travis failure due to github issues

Serialize search_score for Articles For Sorting

---

app/views/mailers/notify_mailer/new_badge_email.html.erb
spec/mailers/notify_mailer_spec.rb

If the message is empty string instead of nil it will render a superflous empty paragraph in the badge email
Thanks @lightalloy for your eagle eye 🦅 
#7000

Make sure there is no empty <p> in the badge email

---

app/models/user.rb
app/services/broadcasts/welcome_notification/generator.rb
db/seeds.rb
spec/factories/broadcasts.rb
spec/models/user_spec.rb
spec/requests/notifications_spec.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb
spec/workers/notifications/welcome_notification_worker_spec.rb

Currently, users get an "onboarding" notification immediately after they are sign up (via an `after_create_commit`). However, as we are planning to launch "welcome notifications" today, we want the initial notification to be slightly different:
* It should introduce Sloan, who is the "author" of all the welcome notifications
* It should prompt users to set up their profile.
I have already added the `Welcome Notification: set_up_profile` broadcast to production (and set it to `active`), so once this is deployed, we'll begin sending out the new, "Sloan-authored" welcome notifications!
Additionally, this PR also ensures that we only look for `Broadcast`s that are explicitly set to `active`. We already have [this check](https://github.com/thepracticaldev/dev.to/blob/3bc0f49861be99c437a840c5cfd …

Add set_up_profile notification, check for active broadcasts

---

app/services/moderator/delete_user.rb
app/services/moderator/merge_user.rb
app/services/users/delete.rb
spec/services/moderator/merge_user_spec.rb
spec/services/users/delete_spec.rb

I found 3 different code paths that we use to delete users and all of them had duplicated code. Rather than continuing to duplicate the code for removing users from Elasticsearch I 
- Updated 2 of the code paths to use the `Users::DeleteWorker`
- Updated the `Users::DeleteWorker` to call destroy on the user rather than delete to trigger all of the callbacks like removing the user from Elasticsearch and, until further notice, Algolia. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35501428

Delete all Users via the DeleteWorker for Consistency and use Destroy in Worker

---

.gitpod.yml
bin/setup

Gitpod sets a `DATABASE_URL` environment variable which defaults to `postgresql://gitpod@localhost`. This doesn't play well with our `bin/setup` script, which won't attempt to create the DB before running migrations because of this. 
I also updated `.gitpod.yml` to only run `bin/setup` once, it was running twice before, once during `init:` and once during `command:`.
Closes #7040 
If you want to confirm that this works, start a Gitpod instance from the link below:

Unset DATABASE_URL in .gitpod.yml

---

app/models/article.rb
app/serializers/search/article_serializer.rb
spec/serializers/search/article_serializer_spec.rb

Reverts thepracticaldev/dev.to#7053
some search_scores are in the billions which doesn't fit in the integer field type and is causing errors

Revert "Serialize search_score for Articles For Sorting"

---

app/views/articles/_sidebar_additional.html.erb

For most widgets in right sidebar, we display 5 items for for two of them (Listings & #help tag) we actually display 8. I'm reducing this number not because 5 is better than 8 but because this is a step towards introducing the new style for widgets. Style that will have more whitespace and therefor will take more space. So I wanna balance that out by reducing number of items in them.

Limiting number of items in sidebar widgets

---

app/models/tag.rb
db/migrate/20200331155903_remove_unused_columns_from_tags.rb
db/schema.rb

Removing recently ignored columns in the `tags` table.
Follow up to https://github.com/thepracticaldev/dev.to/pull/6947
#6947

Remove unused tags columns

---

app/controllers/internal/mods_controller.rb
app/queries/internal/moderators_query.rb
app/views/internal/mods/index.html.erb
app/views/kaminari/internal/_first_page.html.erb
app/views/kaminari/internal/_gap.html.erb
app/views/kaminari/internal/_last_page.html.erb
app/views/kaminari/internal/_next_page.html.erb
app/views/kaminari/internal/_page.html.erb
app/views/kaminari/internal/_paginator.html.erb
app/views/kaminari/internal/_prev_page.html.erb
spec/queries/internal/moderators_query_spec.rb

This PR address performance issues on Internal Mods page and add minor UI improvements.
- Create `Internal::ModeratorsQuery` with specs.
- Controller
- Refactor index action to use new query class.
- Fix rediretion and flash message on update action.
- Require only the necessary user fields.
- Change to 50 moderators per page.
- Index.html.erb
- Refactor forms to use the new `form_with` syntax.
- Pull Kaminari bootstrap theme into internal pages.
- Add missing buttons and form styles.
**Previous Query Plan with 1k users:**
```ruby
User.without_role(:trusted).order("comments_count DESC").explain
Sort  (cost=439.78..441.83 rows=819 width=1924)
Sort Key: comments_count DESC
->  Index Scan using users_pkey on users  (cost=0.28..400.15 rows=819 width=1924)
Index Cond: (id = ANY …
```

Refactor internal mods page

---

app/helpers/application_helper.rb
app/lib/url.rb
app/models/article.rb
app/models/comment.rb
app/models/reaction.rb
app/services/rss_reader.rb
app/services/slack/messengers/article_fetched_feed.rb
app/services/slack/messengers/article_published.rb
app/services/slack/messengers/comment_user_warned.rb
app/services/slack/messengers/reaction_vomit.rb
spec/lib/url_spec.rb
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/models/reaction_spec.rb
spec/services/rss_reader_spec.rb
spec/services/slack/messengers/article_fetched_feed_spec.rb
spec/services/slack/messengers/article_published_spec.rb
spec/services/slack/messengers/comment_user_warned_spec.rb
spec/services/slack/messengers/feedback_spec.rb
spec/services/slack/messengers/potential_spammer_spec.rb
spec/services/slack/messengers/rate_limit_spec.rb
spec/services/slack/messengers/reaction_vomit_spec.rb
spec/services/slack/messengers/sponsorship_spec.rb
spec/support/initializers/vcr.rb

Continuation of #6748 with new messengers:
- `article_published`
- `reaction_vomit`
- `comment_user_warned`
- `article_fetched_feed`
It also adds some URL helpers (comment and reaction)
#6748

Add Slack messengers: part 2

---

app/services/search/query_builders/user.rb
spec/services/search/query_builders/user_spec.rb
spec/services/search/user_spec.rb

When users are banned we remove them from Algolia. However, in Elasticsearch we simply apply the banned role to them. This ensures that none of those banned users are returned in search results. Eventually we will not want to make this hardcoded but for now I think it is fine. 
Per @rhymes in a [previous PR comment](https://github.com/thepracticaldev/dev.to/pull/7014#issuecomment-607663389)
> Adding a note for the implementation in the following PRs: there are users whose role is banned, but there also users whose role comment_bannished, not sure if they shall be filtered out as well. There are also "banished users", see the model BanishedUser and the method User.banished?. There's also warned as a role, but not sure if those should be displayed anyway.
Right now the only time we remove …

By Default Search for Users that are not Banned

---

app/assets/stylesheets/scaffolds.scss

This was taken out from #6987. Not yet sure precisely intent, but is causing most links on the site to revert to the default "underlines" styling.
I feel like removing the color defaults and the hover default is good to go, but we still need the `text-decoration: none` for now eh?

Add text-decoration: none back in for anchor

---

app/models/chat_channel.rb

Fixes: https://app.honeybadger.io/fault/66984/6fd7e14997f49097942c3ef75b84fd93
```
ActiveRecord::RecordInvalid: Validation failed: User has already been taken, Chat channel has already been taken
chat_channel.rb  95 block in add_users(...)
[PROJECT_ROOT]/app/models/chat_channel.rb:95:in `block in add_users'
93   def add_users(users)
94     Array(users).each do |user|
95       ChatChannelMembership.create!(user_id: user.id, chat_channel_id: id)
96     end
97   end
```

Prevent AR Unique errors with find_or_create for ChatChannelMembership

---

app/assets/stylesheets/preact/article-form.scss
app/assets/stylesheets/themes/hacker.scss
app/assets/stylesheets/themes/night.scss

When a dark theme is activated (both night and hacker themes), the "copy to clipboard" button in the article sidebar is not very visible. See https://github.com/thepracticaldev/dev.to/issues/6967
It's also not very visible in general in the images overlay in the editor form. 
Closes https://github.com/thepracticaldev/dev.to/issues/6967

Fix copy to clipboard buttons colors

---

app/models/broadcast.rb
app/services/broadcasts/welcome_notification/generator.rb
spec/factories/broadcasts.rb
spec/requests/internal/broadcasts_spec.rb
spec/services/notifications/welcome_notification/send_spec.rb

Removes the "Onboarding" type of broadcast, since we aren't using that to send any notifications anymore. Closes #6709.
#6709

Remove onboarding type broadcasts

---

app/assets/stylesheets/themes/hacker.scss
app/assets/stylesheets/themes/night.scss

When using a dark theme, the sidebar user's name didn't change its color because of the missing `--theme-color` variable. This pull request fixes it by adding the aforesaid variable.
Fixes #7074

Fix sidebar colors on dark themes

---

app/views/shell/_top.html.erb

The content of `layouts/user_config` contains some inline fetched style like this...
`<%= Rails.application.assets["themes/night.css"].to_s.squish.html_safe %>` which I believe is pretty inefficient in fetching the assets in runtime in production, all else equal.
We had another fragment cache wrapping `top_bar` for no _great_ reason. So removed that and replaced with this fragment cache which wraps the whole area.

Move fragment cache to more efficient location

---

app/models/podcast_episode.rb
app/services/podcasts/create_episode.rb
spec/services/podcasts/create_episode_spec.rb

Who wants to remove callbacks?! 🤚 In https://github.com/thepracticaldev/dev.to/pull/4967 we began to use [activerecord-import](https://github.com/zdennis/activerecord-import#callbacks) to create podcast episodes which means we are NOT triggering any callbacks that create should fire. This became noticeable to me when I realized new episodes were not in Elasticsearch. Rather than manually saving the podcast to fire some of the callbacks I moved the create callbacks to the create podcast episode service since that is the only place we make episodes. (+1 for a single path!!!!) 
In addition, I added a comment warning people not to add after_create callbacks to the PodcastEpisode model since they will never fire. Hopefully we can get a single update path set and then we could remove all …

Move create PodcastEpisode callbacks to create Podcast Service

---

.gitpod.dockerfile

While working on #7060 I realized that the recent update to Ruby 2.7.0 did not take `.gitpod.dockerfile` into account. This PR fixes that. 
n/a

Update Ruby version for Gitpod

---

app/models/comment.rb
app/workers/comments/calculate_score_worker.rb
spec/workers/comments/calculate_score_worker_spec.rb

When you try to save a comment that's parent/root comment has been deleted it will fail with the following error `ActiveRecord::RecordNotFound (Couldn't find Comment with 'id'=123)`. The reason for this is because during the save process we try to touch the parent/root comment. Calling `root` or `parent` on a comment where the parent/root has been deleted raises an AR not found error. Instead, I choose to do the check by hand before calling root to update it.
This will fix the failing `Reactions::UpdateReactableWorker`'s and `Comments::CalculateScoreWorker`'s

Skip updating a root comment if it doesnt exist

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/signup-modal.scss
app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
app/views/layouts/_signup_modal.html.erb
app/views/stories/_sign_in_invitation.html.erb
spec/requests/internal/configs_spec.rb
spec/views/layouts/signup_modal.html.erb_spec.rb
spec/views/stories/sign_in_invitation.html.erb_spec.rb

Adding `community_member_description`, `tagline` and `mascot_image_url` to SiteConfig. Also enabling cloudinary for `primary_sticker_url` which was created by #6746. 
The only thing missing in order to complete issue https://github.com/thepracticaldev/dev.to/issues/5477 is implementing `secondary_sticker_image_url`. However, that purple logo is implemented in jsx. I am not really sure how to push SiteConfig details into javascript.
#5477

Add community_member_description, tagline and mascot_image_url to SiteConfig. Enable Cloudinary for primary_sticker_image

---

app/controllers/video_chats_controller.rb
app/javascript/packs/videoChat.jsx
app/models/message.rb
app/views/video_chats/show.html.erb
config/routes.rb
spec/requests/video_chats_spec.rb

This is a half-built experiment on a new paradigm for doing video chat in `/connect`.
We have a prior experiment live but it never really took the next steps because it's somewhat of complicated mess. This would allow us to remove all that old code and actually build something more maintainable.
The idea is that the "call" happens in the sidecar, and you join the call by accessing the page propped up in the sidecar.
To create a new call, someone creates a message which opens a sidecar link. Then the call happens in the sidecar.
The actual code for the video area is the minimum amount for it to _maybe_ work. But I wanted to shoot it into prod to mess around there.
This is literally 25 minutes of work but I think could be nice to continue the theme of letting`/connect` worry about basic …

Connect Video Chat Experiment

---

app/controllers/application_controller.rb
app/controllers/concerns/fastly_headers.rb

**This PR:**
The [`fastly-rails` gem](https://github.com/fastly/fastly-rails) has been deprecated. I copied over the controller methods we need from it to set the headers for Fastly.
Note: there are some places we set headers manually like this:
https://github.com/thepracticaldev/dev.to/blob/ee594a657f08fecfd22aaffdd03c379ccd1828fe/app/controllers/articles_controller.rb#L27
I'll update those to use the helpers in a separate PR. I'm trying to introduce as little change as possible on each PR so it's easier to debug if it goes off the rails.
**Fastly update overview (will be copied to each PR for convenience):**
We are updating Fastly to get rid of the deprecated [`fastly-rails gem`](https://github.com/fastly/fastly-rails). We use the `fastly-rails` gem to set Fastly headers and to purge …

Copy set_cache_control_headers from fastly-rails

---

app/models/comment.rb
spec/models/comment_spec.rb

This is a followup to #7080 where we choose to skip updating the root comment if it didn't exist. Once deployed I found that we were incorrectly trying to call a private method so I made it public and added some tests. Upon adding some tests and trying to reload the secondary comment I found a few more places we needed to add the `root_exists?` method to allow a comment to reload.

Make root_exists Method Public and Use In Other Callbacks

---

app/assets/javascripts/initializers/initializeArticleReactions.js
app/views/articles/_actions.html.erb
app/views/articles/_reaction_button.html.erb

As noted in https://github.com/thepracticaldev/dev.to/issues/7058 our article reaction buttons don't communicate their checked status. 
This PR fixes that. I also refactored the article reaction buttons in a partial as they are identical save from the category and the emoji
I didn't add tests as they are quite complicated to setup, let me know if you think we shall add them at all costs and if you have suggestions :D
ps. I think the same happens to all the other reaction buttons (in comments and notifications) but I'd rather investigate each in a separate PR
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role
- https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/aria-checkbox/
Closes 7058

Add ARIA checked attribute to article reaction buttons

---

app/controllers/async_info_controller.rb
app/controllers/internal/growth_controller.rb
app/models/user.rb
app/services/authorization_service.rb
app/views/internal/growth/_results.html.erb
app/views/internal/growth/index.html.erb

Since we're no longer using variants in onboarding, we don't need this code anymore!
Also ignores the `onboarding_variant_version` column on the user since it is no longer used,
and removes references to "onboarding variants" from the `/internal/growth` pages.
**Please review #7116 first, as that needs to be merged/deployed before this PR!**
Addresses the second half of #6714. Also closes #6714.
The `internal/growth` page now looks something like this (but with data, lol):

Remove variants from backend portion of onboarding

---

app/models/article.rb
app/models/concerns/searchable.rb
app/services/data_sync/elasticsearch/article.rb
app/services/data_sync/elasticsearch/user.rb
spec/models/article_spec.rb
spec/services/data_sync/elasticsearch/article_spec.rb
spec/services/data_sync/elasticsearch/user_spec.rb

This PR moves the logic for keeping reactions and articles in sync to a `DataSync::Elasticsearch` class. This allows us to have a clearer picture of everything that needs updating when certain fields of an article are updated. 
There are a couple of repeat methods in here that can be refactored but I will address those in a separate PR. I did not forget about [your comments](https://github.com/thepracticaldev/dev.to/pull/7049/files#r402722751) @citizen428 
https://github.com/thepracticaldev/dev.to/projects/6#card-35843915

Hook up Elasticsearch Data Syncing for Articles 

---

netlify.toml

[Netlify will be updating their redirect logic tomorrow](https://community.netlify.com/t/changed-behavior-in-redirects/10084/4), and I think this is the only thing we need to do to keep consistent functionality. I'm not entirely sure if this is the right move; if it's not, we can revert this.
As I understand from the above link, the current behavior of redirects is already a "forced rule", and by adding this, we'll keep behavior consistent with what we've been previously doing.
I think to observe if anything changes, we can either:
1. merge today, see if anything changes, and see if anything changes tomorrow after their logic.
2. see if anything changes tomorrow after their logic, and if it does, merge this and see if it works.
I think the worst thing that would happen is our routes that …

Use force redirects for docs to follow legacy functionality

---

app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap
app/javascript/shared/components/tags.jsx
app/views/classified_listings/_form.html.erb

In #6741 we found a [bug](https://github.com/thepracticaldev/dev.to/pull/6741#issuecomment-601875812) when it comes to adding tags to listings. This PR fixes adding tags to a new listing. Previously, the input field wasn't being included in the form submission because the input field wasn't named properly.
We can ignore my comment about the script being loaded twice. Looks like the conditions are just slightly different.
https://github.com/thepracticaldev/dev.to/pull/6741#issuecomment-601875812

Add name to tags component

---

app/controllers/pages_controller.rb
app/helpers/application_helper.rb
app/lib/url.rb
app/views/comments/_form.html.erb
foo
spec/helpers/application_helper_spec.rb

Under certain circumstances, we were redirecting back to the service worker when canceling a comment edit. This PR fixes that. 
After I did a quick & dirty fix, I noticed that there's at least one other place that could use the same logic, so I added a method to our `URL` helper module and a helper wrapper in `ApplicationHelper`. 
I deliberated a bit on whether `URL` is really the best place for it, but I didn't want to introduce a new module for a single method and it seems to still mostly be on topic, as it's related to URL-based navigation within our app.
Closes #7081

Introduce URL.sanitized_referer helper

---

app/controllers/concerns/fastly_headers.rb

**This PR:**
The [`fastly-rails` gem](https://github.com/fastly/fastly-rails) has been deprecated. I copied over the `set_surrogate_key_header` controller method we need from it to set the headers for Fastly.
Note: there are some places we set headers manually like this:
https://github.com/thepracticaldev/dev.to/blob/ee594a657f08fecfd22aaffdd03c379ccd1828fe/app/controllers/articles_controller.rb#L27
I'll update those to use the helpers in a separate PR. I'm trying to introduce as little change as possible on each PR so it's easier to debug if it goes off the rails.
**Fastly update overview (will be copied to each PR for convenience):**
We are updating Fastly to get rid of the deprecated [`fastly-rails gem`](https://github.com/fastly/fastly-rails). We use the `fastly-rails` gem to set …

Copy set_surrogate_key_header from fastly-rails

---

app/controllers/omniauth_callbacks_controller.rb
spec/system/user_logs_in_with_twitter_spec.rb

Thanks to https://github.com/thepracticaldev/dev.to/issues/7134 I found out the failure path for the sign in process is broken as Timber is not enabled in development anymore. As logging the error in production logs might not actually be beneficial, I moved it to Datadog.
I got the options from https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/
Helping to debug https://github.com/thepracticaldev/dev.to/issues/7134

Send auth failures to Datadog

---

app/services/podcasts/get_media_url.rb
spec/services/podcasts/get_media_url_spec.rb

Currently have a collection of failing workers trying to make podcast episodes with invalid URLs. This allows us to make the podcast episode but then mark the URL as unreachable. 
Fixes: https://app.honeybadger.io/fault/66984/c325e105109b2312cfcaf55fb904c254
```
URI::InvalidURIError: URI must be ascii only "https://codestammtis.ch/podcast/CST048_K%C3%A4ferverfolgung.mp3?ptm_source=feed&ptm_context=mp3&ptm_request
```

Rescue invalid URL errors and Mark as Unreachable for Podcast Episodes

---

app/assets/javascripts/initializers/initializeBaseUserData.js

At one point we lost the ability for post authors to hide comments for their posts. This PR fixes this. While we did set the display attribute correctly, we did not remove the `hidden` CSS class, which caused this issue.
I also refactored the relevant method a little bit, I think the current version is functionally equivalent (sans bug) but easier to read.
https://github.com/thepracticaldev/tech-private/issues/418
I didn't add them yet because I figured we didn't have any, otherwise we'd have caught this somehow. As I'm not super up to date on our frontend testing I may need help. Though we also may choose to get the fix out first.

Fix comment hiding

---

app/controllers/articles_controller.rb
app/controllers/sitemaps_controller.rb
app/controllers/stories_controller.rb
spec/requests/articles/articles_spec.rb
spec/requests/stories_index_spec.rb

**This PR:**
The [`fastly-rails` gem](https://github.com/fastly/fastly-rails) has been deprecated. This a clean up PR on the heels of #7108 to clean up places where we set headers manually like this:
https://github.com/thepracticaldev/dev.to/blob/ee594a657f08fecfd22aaffdd03c379ccd1828fe/app/controllers/articles_controller.rb#L27
I've also added tests (overkill) for the headers in each spot I updated.
**Note:** #7108 doesn't have to be merged first since the method name, `set_cache_control_headers`,  is the same.
**Fastly update overview (will be copied to each PR for convenience):**
We are updating Fastly to get rid of the deprecated [`fastly-rails gem`](https://github.com/fastly/fastly-rails). We use the `fastly-rails` gem to set Fastly headers and to purge the cache in Fastly. We'll be …

Update manual Fastly header assignments

---

app/models/organization.rb
app/services/data_sync/elasticsearch/organization.rb
spec/models/organization_spec.rb
spec/services/data_sync/elasticsearch/organization_spec.rb

Since organization data is indexed on articles we need to ensure that data is updated when an organization is updated. This adds a DataSync class for organizations which is the first model to get a sync class but it is not an indexed model itself which is why I implemented the method for it in the model class itself. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35915671

Keep Articles Updated in Elasticsearch when Organization is Updated

---

app/views/service_worker/index.js.erb

Added exceptions to the serviceworker to the redirect paths, to avoid console errors and double footer rendering. This could also potentially help with an offline page on this paths in production, e.g. https://dev.to/workshops
Example of the double footer:

Add exceptions to the serviceworker code to fix redirects

---

app/views/internal/configs/_card_header.html.erb
app/views/internal/configs/show.html.erb

The site config page has become unmanageable and the submit button has fallen right to the bottom of the page, making it difficult to easily navigate the page and make quick changes.
For now, I have collapsed all the sections by default, until we get around to designing out a tabbed or sidebar format. I've also renamed some section headers to be more reflective of the config that they have in it, since they will be closed by default now. In addition, mascot id has been moved to Community Content.

Make the site config togglable

---

app/views/partnerships/index.html.erb

Saw that [https://dev.to/partnerships](https://dev.to/partnerships) shows the current number of registered users. This is a tiny enhancement to make the number a bit more pleasant to the eye.
From [the docs](https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_with_delimiter) I believe `number_with_delimiter` uses the current locale, although I'm not too sure of the current state of how we manage I18n. This may or may not be useful, so it can be discarded if it's an unwanted change.
**Before:**
**After:**

Adds number_with_delimiter for friendlier visualization in /parternships

---

app/services/search/query_builders/feed_content.rb
spec/services/search/feed_content_spec.rb

This ensures that we return the cloundinary URL which is required to show a video in the feed view
```
var videoHTML = '';
if (article.cloudinary_video_url) {
videoHTML = '<a href="'+article.path+'" class="single-article-video-preview" style="background-image:url('+article.cloudinary_video_url+')"><div class="single-article-video-duration"><img src="<%= asset_path("video-camera.svg") %>" alt="video camera">'+article.video_duration_in_minutes+'</div></a>'
}
```
https://github.com/thepracticaldev/dev.to/projects/6#card-35622089

Return cloudinary url from Elasticsearch to show Videos in Feed

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

To prevent users from abusing endpoints and flooding our workers we should limit how often they can hit the API. 
- Limit get requests to 3 requests/second
- Limit PUT/POST/DELETE requests to 1 request/second

Throttle API get and write Endpoints

---

app/controllers/omniauth_callbacks_controller.rb
config/initializers/omniauth.rb
spec/system/user_logs_in_with_twitter_spec.rb

Fixing this and testing this the right way was a very long trip down a rabbit hole of debugging and metaprogramming through countless Rack apps and undocumented Omniauth methods but I got to the other side :D 
I also found the solution for a OmniAuth bug and filed an OAuth one in the process, so yay! :D 
I also got to use function composition in Ruby which was a first!
- #7135 
- https://app.honeybadger.io/fault/66984/6f34052d8117af6578daef753d6f068a

Fix Datadog auth failure payload and add tests

---

app/views/credits/new.html.erb

The typo is in this page:
https://dev.to/credits/new
Nope.

Fix typo in credits/new

---

app/labor/rate_limit_checker.rb
app/models/site_config.rb
app/services/articles/updater.rb

We currently don't have a rate limit for article update; this adds one. The default is 50 per day.

Add rate limit for article updates

---

.gitpod.yml
Dockerfile
bin/docker-setup

When doing some Gitpod work the other day I thought it might be a good idea to add the Solargraph gem by default for the web-based VSCode editor.
n/a

Add Solargraph gem for Gitpod

---

app/labor/rate_limit_checker.rb

Reverts a refactor of `Rails.cache.increment` back to `Rails.cache.read` and `Rails.cache.write` since it seemed to have issues initializing a write of the first cache key.

Revert refactor of increment back to read/write

---

config/environments/test.rb

Well, apparently `RUBYOPT=-W0` doesn't work with Rails, so we're going the other route for Travis too. 
This PR silences the warnings (they are already silenced in development mode and local testing mode)
#5281

Silence Ruby 2.7 warnings in Travis

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/utilities.js

Quite a few optimizations here:
* Render the user's name on the intro slide for onboarding.
* Style the back button using crayons design system.
* Remove redundant scroll styles in the "terms and conditions" view.
* Ensure that ToC is readable, and that the back button doesn't conflict with ToC content.
* Ensure size of ToC content is same size as "intro slide".
* Remove unnecessary inline styles, use CSS classes instead.
Part of the task list described in #6545, and some minor refactors that seemed like they should happen before the major refactor required by #6545.
Before this PR, the intro slide looked like:
After this PR,  the intro slide will look like:
Before this PR, the ToC view looked like:
After this PR,  the ToC view will look like:

Onboarding intro slide tweaks

---

app/assets/stylesheets/internal/layout.scss
app/views/internal/configs/_card_header.html.erb
app/views/internal/configs/show.html.erb

It was a real pain to click on the button each time the card needed to be expanded or collapsed on the Site Config Page. 
I’ve now made all the cards  collapsable and expandable by clicking anywhere on the card header. Keeping the buttons on the inner cards felt overwhelming and so I replaced it with text just to indicate that its togglable.

Enhance Site Config Togglability

---

app/controllers/application_controller.rb
app/controllers/image_uploads_controller.rb
app/controllers/users_controller.rb
spec/requests/image_uploads_spec.rb
spec/requests/user/user_settings_spec.rb

After #6918, we're still getting some file name too long errors:
https://app.honeybadger.io/projects/66984/faults/62329414
https://app.honeybadger.io/projects/66984/faults/62292062
I think what's happening is Carrierwave has logic to assign unique file names that include encoding. And after encoding very specific files, the resulting (temporary) file name is way too long, even if the original filename is valid (less than 250 characters).
This PR catches the error, sends helpful data to Datadog, and then continues to raise the error as normal. This happens very infrequently. Once this happens again, I can make much more progress for a better fix once I get the data I'm logging with this PR.
https://github.com/thepracticaldev/dev.to/projects/9#card-36038792 …

Log image data to Datadog for file name too long error

---

app/services/search/feed_content.rb
app/services/search/query_builders/feed_content.rb
app/services/search/query_builders/query_base.rb
spec/services/search/feed_content_spec.rb
spec/services/search/query_builders/feed_content_spec.rb

There are a few things happening in this PR which are going to help us get more relevant results from Elasticsearch. 
- Currently, we weight heavily towards search_score, Elasticsearch will weigh more towards match score but I added [function scoring](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#score-functions) to allow us to use the article score to influence the match score. This allows us to return higher quality match results.  
- In Algolia we use the combination operator AND. In Elasticsearch we will be using OR with combined with a [minimum_should_match](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html) value of 2. The minimum_should_match will allow us to get more precise …

Add Custom Sorting and Scoring For Feed Content from Elasticsearch

---

app/services/rss_reader/assembler.rb

An RSS item's `img` tag could be using `data-src` instead of `src`. This account for that instead of silently failing.
n/a
n/a
n/a

Allow img to use data-src in RSS

---

app/models/concerns/searchable.rb
app/models/organization.rb
app/services/data_sync/elasticsearch/article.rb
app/services/data_sync/elasticsearch/base.rb
app/services/data_sync/elasticsearch/organization.rb
app/services/data_sync/elasticsearch/user.rb
spec/services/data_sync/elasticsearch/article_spec.rb
spec/services/data_sync/elasticsearch/base_spec.rb
spec/services/data_sync/elasticsearch/organization_spec.rb
spec/services/data_sync/elasticsearch/user_spec.rb

Refactor Elasticsearch DataSync Classes based on previous PR feedback. 
- Consolidate shared logic into a single base class
- Pass a single record which already has `saved_changes` attached so there's no need for two arguments
- Consolidated tests
I honestly don't feel great about the way the individual classes are tested but really they are just defining constants that the base class then uses so 🤷

Refactor Elasticsearch DataSync Classes

---

app/views/articles/new.html.erb
spec/requests/articles/articles_spec.rb

Because sometimes we link to `/new?prefill=whatever` for article composition page, we need to have a canonical meta tag so that spiders know that these are all the same page regardless of the query params.

Add canonical url to /new

---

app/views/tags/index.html.erb
public/offline.html

An `html` file was among many of the other files that were refactored during the meta generalization process, but unfortunately, unlike the other files that were `html.erb`, this one was just `html`, causing the `erb` tags to render none of the meta content (shown while inspecting the content in the browser), as well as causing a closing tag to render on the offline page. 
The best solution I could come up with was to revert the meta content back to what it was prior to the changes because the offline page is merely an `html` file, but I am very open to ideas on how to better resolve this tiny issue!
While hunting this change down, I also noticed that there was an extra open parenthesis, so I removed that as well.
The PR containing the work I am reverting can be found …

Revert generalization of meta content in offline.html

---

app/labor/rate_limit_checker.rb
spec/labor/rate_limit_checker_spec.rb
spec/requests/image_uploads_spec.rb

Use [atomic Redis increment](https://redis.io/commands/incr) for counters.
I tested this with:
```ruby
key = "key-#{rand(10_000)}"
puts "Initial value: #{Rails.cache.read(key)}"
Rails.cache.increment(key, 1)
value = Rails.cache.read(key)
puts "After increment: #{value}, #{value.class}"
```
and verified with:
```shell
➜  devto ✗ redis-cli
127.0.0.1:6379> get key-1639
"1"
127.0.0.1:6379> incrby key-1639 2
(integer) 3
127.0.0.1:6379> get key-1639
"3"
127.0.0.1:6379>
➜  devto ✗ rails runner "puts Rails.cache.read('key-1639')"
Cache read: key-1639 ({:namespace=>nil, :compress=>true, :compress_threshold=>1024, :expires_in=>3600, :race_condition_ttl=>nil})
3
```
The correct way to make it work in testing is to use the [https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html]( …

Use atomic increment for rate limiter counters

---

lib/data_update_scripts/20200410152018_resync_elasticsearch_documents.rb
spec/lib/data_update_scripts/resync_elasticsearch_documents_spec.rb

I have fixed a lot of bugs related to documents getting indexed and removed. With all of those bugs cleaned up I have been monitoring Elasticsearch vs Postgres counts for about a week and they have matched perfectly every day so I think everything has been fixed. Seeing as DEV is in sync these scripts are mostly so all other environments (development and other communities) can get back in sync as well. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35572605

Resync Elasticsearch Docs that had Previous Bugs

---

app/labor/cache_buster.rb
app/models/application_record.rb
app/models/concerns/purgable.rb
app/models/concerns/purgeable.rb
app/models/tag.rb
spec/models/concerns/purgeable_spec.rb
spec/rails_helper.rb

**This PR:**
The [`fastly-rails` gem](https://github.com/fastly/fastly-rails) has been deprecated. I copied over the ActiveRecord methods we need from it to purge cache in Fastly.
---
It's worth noting that the `fastly` gem states in their [documentation](https://github.com/fastly/fastly-ruby#efficient-purging):
> To purge efficiently you do not want to look up the service every time you issue a purge.
I'm intentionally ignoring that here for a couple of reasons.
1) It's less of a change since `fastly-rails` was [doing this](https://github.com/fastly/fastly-rails/blob/6ed13a694b8753d43515079ae667fe6f8c0fcd23/lib/fastly-rails/client.rb#L11-L13) "incorrectly" as well.
2) The `fastly` [documentation](https://github.com/fastly/fastly-ruby#usage-notes) also states:
>If you are performing many …

Copy ActiveRecord methods from fastly-rails

---

app/workers/search/index_to_elasticsearch_worker.rb
spec/workers/search/index_to_elasticsearch_worker_spec.rb

Reactions are one of those records that can be created and deleted very quickly. For this reason it is not uncommon for us to see Sidekiq Indexing worker failing with a ActiveRecord::NotFound error. To prevent this since it is common I choose to ignore AR NotFound errors when they are raise for Reactions. I don't want to ignore all model types bc other models should never find themselves in this situation and if they do it is likely a bug.
https://github.com/thepracticaldev/dev.to/projects/6#card-36207568

Ignore Reaction Not Found During Indexing

---

app/javascript/chat/__tests__/__snapshots__/article.test.jsx.snap
app/javascript/chat/article.jsx
app/javascript/chat/chat.jsx

Add a few extra keyboard shortcuts to `/connect`.
... `esc` hides active sidecar content
... `right arrow` shows most recent "rich link" in convo when no other text in textbox
... `left arrow` pulls current page from sidecar into body of message when no other text in textbox.

Add some keyboard shortcuts for /connect active content

---

app/lib/acts_as_taggable_on/tag.rb
app/models/tag.rb
app/services/data_sync/elasticsearch/tag.rb
spec/lib/acts_as_taggable_on/tag_spec.rb
spec/models/tag_spec.rb
spec/services/data_sync/elasticsearch/tag_spec.rb

We index keywords_for_search from Tags on Articles, Reactions(articles as reachable) and PodcastEpisodes(well we can, we currently don't use this feature). If they change we need to make sure to update those Elasticsearch documents.
https://github.com/thepracticaldev/dev.to/projects/6#card-35915111

Sync Elasticsearch Articles and Reactions if Tag Search Keywords are Updated

---

app/controllers/search_controller.rb
app/services/search/base.rb
app/services/search/chat_channel_membership.rb
app/services/search/classified_listing.rb
app/services/search/feed_content.rb
app/services/search/query_builders/chat_channel_membership.rb
app/services/search/query_builders/classified_listing.rb
app/services/search/query_builders/feed_content.rb
app/services/search/query_builders/user.rb
app/services/search/user.rb
spec/services/search/chat_channel_membership_spec.rb
spec/services/search/query_builders/chat_channel_membership_spec.rb
spec/services/search/query_builders/classified_listing_spec.rb
spec/services/search/query_builders/feed_content_spec.rb
spec/services/search/query_builders/user_spec.rb

- Move search_documents method into `Search::Base` class
- Update all query builders to use keyword arguments for params
- Remove user_id argument from ChatChannelMembership query builder and add to params
- Choosing to ignore the leftover duplicate code for now. You can't have it all CodeClimate, that's not how this works. 
https://github.com/thepracticaldev/dev.to/projects/6#card-36211320

Refactor search_documents Method Into Search Base.rb Class

---

app/views/articles/edit.html.erb
app/views/articles/new.html.erb

We have a weird and non deterministic bug happening in the article edit page in which it sometimes doesn't render, at all.
Thanks to @caleb15 reporting the console log and @lightalloy's investigation there's strong evidence this is related to the the element whose ID is `editor-help-guide`, which is the editor guide.
Precisely this happens here:
https://github.com/thepracticaldev/dev.to/blob/bca0573a147ceb764ef8d4f2d4acb0f8f587fbc6/app/javascript/article-form/articleForm.jsx#L102
I noticed how we render the JS tag **before** the HTML that contains the editor guide. Even though the script it set to `defer` I guess there might be a situation where the script still starts before the HTML is fully in.
By rendering the HTML before the script runs, at least we're sure the editor guide is in the …

Synchronously render the article editor guide

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/ProfileForm.jsx

Currently shorter screens run into problems of scrolling with the tall profile slide. This might not be the most elegant solution but it's a patch.
Current page: You can see that the buttons are starting to get cut off at the top...
Fixes #7278

Fix onboarding profile slide for short screens

---

app/models/feedback_message.rb
db/schema.rb
spec/models/feedback_message_spec.rb

This adds character limits for the public `reported_url` and `message` fields of an abuse report.

Add character limits for reported_url and message

---

app/models/article.rb
app/services/articles/feed.rb
app/views/stories/feeds/show.json.jbuilder
spec/models/article_spec.rb
spec/requests/stories/feeds_spec.rb

Adjusts the fields included in the home page feed json to only include fields from the `comments` model necessary to render comments on the home page. Also tweaks the way comments to fetched via `article.top_comments` to omit hidden and deleted comments.

Tweak comments in feed

---

app/workers/metrics/record_data_counts_worker.rb
spec/workers/metrics/record_data_counts_worker_spec.rb

We are tracking these counts in Datadog in order to catch and bugs that might appear in our indexing flows. These numbers need to be as close to accurate as possible and since most of our tables are small I decided to attempt to use `count` on each one first. If that timeout then we can fallback on the estimation.

Record DB counts with `count`, Fallback on estimated_count

---

app/assets/stylesheets/settings.scss
app/views/users/_account.html.erb

While testing for https://github.com/thepracticaldev/dev.to/issues/7242 I noticed how the UI for API secrets was a bit off when the `<details>` is opened:
This is how it currently looks like closed:

Fix UI for settings - API secrets

---

app/models/article.rb
app/models/chat_channel_membership.rb
app/models/comment.rb
app/models/podcast.rb
app/models/reaction.rb
app/models/tag.rb
app/models/user.rb
app/services/search/base.rb
app/workers/search/bulk_index_to_elasticsearch_worker.rb
spec/services/search/base_spec.rb
spec/workers/search/bulk_index_to_elasticsearch_worker_spec.rb

Having a [bulk index](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) worker like this will allow us to more quickly reindex large amounts of documents when necessary. One of those necessary times will be when indexing Reading List reactions (which will happen in a followup PR). We have 1.2 million reactions that need to be indexed and we don't want to waste lots of resources having to enqueue 1.2 million Sidekiq jobs. In addition, any time we are doing bulk updates in the future we can make use of this worker to improve performance. 
I tried to make this as optimal as possible by adding an eager load scope to each indexable model so each one can execute the bulk indexing data gathering efficiently. 
You will also notice I am chunking the data into 5 MB …

Create a Bulk Index Elasticsearch Worker

---

app/controllers/application_controller.rb
app/controllers/organizations_controller.rb
app/controllers/podcasts_controller.rb
spec/requests/organizations_update_spec.rb
spec/requests/podcasts/podcast_create_spec.rb
spec/requests/user/user_organization_spec.rb

In #7200 I added logic to log image data to Datadog to help with debugging. I didn't add that logic to organizations and podcasts and the error came up again in organizations.
https://app.honeybadger.io/projects/66984/faults/62863589
This PR adds the same logic to organizations and podcasts.
https://app.honeybadger.io/projects/66984/faults/62863589

Rescue file too long error from podcasts and organizations

---

config/environments/development.rb
config/environments/test.rb

Adding users to the eagerly loaded classes while assembling the feed has lead the the same erroneous "unused eager loading" warning from Bullet as was whitelisted for the `Article.top_comments` association in https://github.com/thepracticaldev/dev.to/pull/7261. This PR added `Comments.user` to Bullet's whitelist. This prevents a warning from showing in log messages and on screen in the `development` and `test` environments: there's no impact to production operation.
https://github.com/thepracticaldev/dev.to/pull/7261

Suppress unused eager loading warning for comment -> user

---

app/models/audit_log.rb
app/models/user.rb
app/views/internal/moderator_actions/index.html.erb
spec/models/audit_log_spec.rb
spec/models/user_spec.rb
spec/requests/internal/moderator_actions_spec.rb
spec/services/users/delete_spec.rb

While testing #7259 I noticed how a user that has audit logs can't be deleted, it will fail saying there's still a foreign key. The reason is that there's no `has_many` on the `User` model. 
That got me thinking and I don't think we should destroy audit logs if a user goes away, so I opted to nullify those rows. They'll be part of the record, just as `NULL`
I also reordered the various `has_many` to simplify reading and scanning :D

Nullify audit logs on users delete

---

app/views/service_worker/index.js.erb

Serviceworkers do not currently behave super well with redirect routes. Since we added the hardcoded `/checkin` url we should also bypass serviceworkers here. Eventually we should figure out how to do this without having to hardcode, to work for redirects in general.

Bypass serviceworkers for /checkin

---

app/models/concerns/searchable.rb
app/workers/search/index_to_elasticsearch_worker.rb
spec/models/article_spec.rb
spec/models/comment_spec.rb
spec/models/concerns/searchable_spec.rb
spec/models/podcast_episode_spec.rb
spec/workers/search/index_to_elasticsearch_worker_spec.rb

When I was making the [search_id change](https://github.com/thepracticaldev/dev.to/pull/6729) I got a little carried away and started passing it everywhere. Turns out we don't need to pass it to the indexing worker since that nearly looks up the model and calls the index inline method which will correctly use the search_id
https://github.com/thepracticaldev/dev.to/projects/6#card-36219698

Use Model IDs for Indexing Worker

---

app/controllers/stories_controller.rb
app/views/articles/_video_player.html.erb
app/views/articles/show.html.erb
app/views/users/_profile_header.html.erb
app/views/users/show.html.erb
spec/requests/articles/articles_show_spec.rb
spec/requests/user/user_show_spec.rb

Towards the end of reviewing #6956 I thought of a few adjustments which I didn't think needed to be blockers because I could whip them up quickly after the fact rather than holding up the other PR.
...Basically we don't need to render the structured data if the user is signed in or if they are accessing the page in the "internal navigation" context.
Also added the proper URL elements to the GitHub/Twitter sections of the `sameAs` section.

Make adjustments in ld+json logic

---

app/controllers/search_controller.rb
app/javascript/src/utils/__tests__/search.test.js
app/javascript/src/utils/search.js
app/services/search/query_builders/classified_listing.rb
spec/services/search/query_builders/classified_listing_spec.rb

If you pass an array to `new URLSearchParams` such as `{ tags: ["one", "two", "three"] }` it will translate it to this in the query string `?tags=one,two,three` which then Rails interrupts in the params as `{ tags: "one,two,three" }` instead of the desired array. To fix this I have created a helper function that will take the arrays and translate them to URL array params that Rails will understand correctly as an array which is `?tags[]=one&tags[]=two&tags[]=three`
Since we are now passing arrays correctly the controller code needed to be updated to handle and accept those arrays which is why there are changes in the `searches_controller.rb`
https://github.com/thepracticaldev/dev.to/projects/6#card-36358983

Update URLSearchParams to handle arrays correctly for Rails

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
app/javascript/onboarding/components/EmailPreferencesForm.jsx
app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/Navigation.jsx
app/javascript/onboarding/components/ProfileForm.jsx

This PR makes two major changes to the onboarding flow:
1) It moves the terms and conditions/code of conduct into the intro slide.
2) It moves the email preferences into the last slide (before the closing slide, which [will ultimately disappear](https://github.com/thepracticaldev/dev.to/issues/6552)).
It also prepends `v2:` to some of the `updateOnboarding()` functions and some lines to ignore linters where necessary. Also reorganizes the tests.
Closes https://github.com/thepracticaldev/dev.to/issues/6545.
Closes https://github.com/thepracticaldev/dev.to/issues/6550.
Before this change, our intro slide didn't have much going on inside of it...
...and all of the "preference" checkboxes lived in the second slide:
With this PR, this is now split up into different slides. The terms and …

Split up content of EmailListTermsConditionsForm within onboarding

---

app/services/articles/analytics_updater.rb
spec/services/articles/analytics_updater_spec.rb

I think I have a handle on why this is a problem with this WIP PR:
https://github.com/thepracticaldev/dev.to/pull/7312
But this PR just removes the behavior so it doesn't annoy more folks while we make sure it works.
I believe there is a bug which has actually been around for quite some time, so the ultimate fix should close this issue:
https://github.com/thepracticaldev/dev.to/issues/4398
But recent updates to this file (not buggy changes in and of themselves) have triggered the bug more often, making this more urgent.

Remove milestone sends

---

app/views/users/show.html.erb

This fragment cache causes the wrong version of the HMTL with regards to whether the user is signed in. Not a huge deal most of the time but is a cache leak.

Add user_signed_in to profile header cache key

---

app/views/articles/_sidebar_nav.html.erb
config/routes.rb
spec/requests/internal/configs_spec.rb
spec/routing/all_routes_spec.rb

Now that #7262 is in, we can remove the last hardcoded shop URL.
I also added a note explaining why we can't remove it from the routes just yet.

Remove leftover harcoded shop string

---

app/views/service_worker/index.js.erb

Before starting to use these new endpoints we should make sure they are exempt from the service worker.

Exempt new search endpoints from the service worker

---

lib/data_update_scripts/20200415200651_index_reading_list_reactions.rb
spec/lib/data_update_scripts/index_reading_list_reactions_spec.rb

Creates a data update script to index all reading list reactions to Elasticsearch. There are 1.2 million of them which is why I put them on the lowest priority queue, `:default` and used the bulk indexing elasticsearch worker. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32289393

Index all readinglist Reactions into Elasticsearch

---

spec/services/credits/buyer_spec.rb

Looks like a little copy/pasta caused us to be comparing the org updated_at with the user updated_at which led to this spec failing intermittently.

Flaky Spec Fix: Credits Spec, Compare org updated_at's Properly 

---

config/fastly/whitelisted_params.yml

Fastly back at it again. Need to add `type_of` to the list for a `GET /response_templates?type_of` request.
#7068 #7279 
No? I think?

Add type_of param to Fastly param list

---

app/models/chat_channel.rb
app/models/organization_membership.rb

The `create_with_users` method by default creates an _invitation_ to private groups rather than adding folks, but the other part of this adds folks directly. This means the _first_ user gets invited but everyone else is just added. It's odd behavior and this fixes it.

Manually create channel and add users for org channels

---

app/javascript/chat/chat.jsx
app/javascript/src/utils/getUnopenedChannels.jsx

Not sure exactly what's going on but in some circumstances the number indicator shows up when in own chat. This should fix it.

Fix connect edge cases

---

app/javascript/src/utils/getUnopenedChannels.jsx

For some reason `window.currentUser` is sometimes a string and sometimes an object. This seems to fix it in either case.

Change window.currentUser to userData()

---

app/services/search/client.rb

When Elasticsearch requests are recorded in Honeycomb we record them under the name "http_client". This changes that to "Elasticsearch" so it is easier to filter for these requests. I also added some more error information to the span.
https://github.com/thepracticaldev/dev.to/projects/6#card-33076459

Make Elasticsearch Data in Honeycomb Distinct

---

app/views/articles/_sidebar_nav.html.erb
spec/system/homepage/user_visits_homepage_spec.rb

Now that the shop URL is an optional configuration parameter, we should hide its like from the homepage. It's already hidden in the other places, just forgot to do it here in #7319 :D

Hide the Shop in homepage if not present

---

app/controllers/search_controller.rb
app/services/search/query_builders/reaction.rb
app/services/search/reaction.rb
config/routes.rb
spec/requests/search_spec.rb
spec/services/search/query_builders/reaction_spec.rb
spec/services/search/reaction_spec.rb

This is the code we will use to search for readinglist Reactions in Elasticsearch. 
* default search for only readinglist reactions
* enforce authorization for reaction searching
* Make a custom `search_documents` method so we can return the total number of documents as well. I think once this goes out it might be a nice refactor to make the base class return the total as well since I foresee us needing it in the future
* Used the same search_field query weighting as the feed content
Ignoring CodeClimate failures for this PR. I will refactor once this is out as I have been doing with everything else. 
https://github.com/thepracticaldev/dev.to/projects/6#card-35297930

Implement Backend Elasticsearch Functionality for readinglist Reactions

---

app/views/service_worker/index.js.erb

The service worker doesn't play well with redirects - see #7156 - this disables it in the `/shop` redirect as well.
**update**: I also added all the remaining redirects in `config/routes.rb`
Closes https://github.com/thepracticaldev/dev.to/issues/7339

Disable service worker on remaining hardcoded redirects

---

app/models/identity.rb
app/services/authentication/authenticator.rb
spec/models/identity_spec.rb
spec/models/user_spec.rb

Added presence validation for `Identity.user_id`
I'm going to address the underlying lack of constraint in a separate PR (as in the DB not having `NOT NULL` on the column)

Add user_id presence validation for Identity

---

app/services/podcasts/get_media_url.rb
spec/services/podcasts/get_media_url_spec.rb

[A couple weeks ago I fixed a similar error](https://github.com/thepracticaldev/dev.to/pull/7137) but apparently there is another type of invalid error to catch. 
Fixes: https://app.honeybadger.io/fault/66984/51226b47c7edbb2ef566c681bbff2e98

Bug Fix: Rescue Addressable::URI::InvalidURIError and Mark Podcast Episode unreachable

---

app/services/authentication/authenticator.rb
spec/services/authentication/authenticator_spec.rb

In order to alert us of problems with our authentication user creation flow lets record every time we create a new identity and if none are created for an extended period of time alert so we can look into it.

Record Identity Creation Metrics

---

app/javascript/responseTemplates/responseTemplates.js

Navigating to pages that don't have the proper response template elements causes a non-intrusive runtime error for non-logged in cases. This moves the `if` statement a few lines to account for that.

Fix response template non-logged-in navigation issue

---

app/services/search/query_builders/feed_content.rb

Feed results are not showing organizations when they should. This simple fix does the trick.

Include organization in feed_content results

---

app/controllers/search_controller.rb
app/views/articles/index.html.erb
app/views/articles/tag_index.html.erb
app/views/organizations/show.html.erb
app/views/users/show.html.erb

We are currently sorting by "the default" on views such as the main feed and user feeds etc. for pagination.
If you scroll down on my profile you'll see that it begins to sort by essentially top all time after the initial articles loaded, when it should sort by `published_at`. This PR modifies the inputs to search by proper value for different scenarios.
`sort_params_present?` also expects `sort_direction` to be available so I made it available via the view. Not 100% sure this is the right way to go about it but it seems to do the trick and seems like an okay approach.

Fix sort_by expectations with pagination

---

app/models/badge.rb
db/migrate/20200420130910_add_unique_index_to_badges_slug.rb
db/schema.rb
spec/models/badge_spec.rb

Our current slug generation doesn't take into account escapable chars, so `C#` as a title becomes `c` as a slug, which is already present as the slug for the language `C`. We also don't have a unique index on slug, otherwise we would have caught this.
I changed how slugs are generated, it doesn't impact existing ones.
Closes #7248 
Pre-deployment we should fix the C# slug to `c-23` in the DB.

Improve badge slug generation

---

app/controllers/search_controller.rb
app/services/search/query_builders/feed_content.rb
app/views/organizations/show.html.erb

Organizations in Elasticsearch need to be searched using their ID not by tags

Filter Elasticsearch by Organization ID Properly

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/views/articles/show.html.erb
app/views/stories/_main_stories_feed.html.erb

We currently use `<div>`s with an image class and a `background-image:url` for cover images in place of `<img>` tags, which is not very semantic. This PR not only replaces the `<div>`s with `<img>`s, but also adjusts the styling of cover images for a particular article's show page accordingly.
**A few days post-merge, the background styling (`background` and `background-size`) will need to be removed from `article-show.scss` since it is now dead code. There is both a comment in the stylesheet, as well as an issue (seen below under "Related Tickets & Documents") for this code removal.**
Closes #7289 
Related To #7401 
**Article Show Page Before:**
**Article Show Page After:**

Replace Cover Image <div> Tags With <img> Tags

---

app/controllers/search_controller.rb
spec/requests/search_spec.rb

Make sure we can filter by the article `approved` attribute

Allow Filtering by Approved Attribute for Articles

---

app/services/users/delete_activity.rb
app/services/users/delete_articles.rb
spec/services/users/delete_spec.rb

When clearing out user data we use `.delete_all` on reactions which does not trigger any callbacks. This means any reading list reactions will be left in Elasticsearch. This PR updates the that delete class to remove the reactions from Elasticsearch after we have removed them from Postgres.
I also made sure to reindex reactions that were updated during a user merge since `update_all` also does not trigger any callbacks. 
https://github.com/thepracticaldev/dev.to/projects/6#card-36679085

Ensure Readinglist Reactions are Removed from Elasticsearch when Deleted

---

app/models/article.rb

When we run the`async_score_calc` callback on articles that kicks off a worker to rescore the article. For starters, there is no point in rescoring an article that is being destroyed. Secondly, this job can become slightly delayed so that it enqueues an indexing job AFTER we have enqueued and processed a remove from index job for the article deletion. This leads to orphaned documents in Elasticsearch.

Only Run scoring, touch_collection, and update background Callbacks on Update and Create

---

app/controllers/stories_controller.rb
app/helpers/application_helper.rb
app/lib/url.rb
app/views/articles/show.html.erb
app/views/users/_profile_header.html.erb
spec/lib/url_spec.rb

A handful of users with `\` in their name are causing JSON LD to not be properly rendered due to unescaped escaping character.
They are only causing problems on the article page, and not the user profile page because the profile page had already been rendered as an object and had `.to_json` called on it, cleaning up all the issues.
The ones rendered directly in erb, while generally working fine, did not hold up to this one issue.
Closes #7403

Render json+ld as proper json

---

app/models/reaction.rb
app/services/moderator/merge_user.rb
app/workers/users/merge_sync_worker.rb
spec/services/moderator/merge_user_spec.rb
spec/support/sidekiq_test_helpers.rb
spec/workers/users/merge_sync_worker_spec.rb

When we merge content for users we use `update_all` which does not trigger any callbacks, This can cause things to get out of sync in Elasticsearch and with scores and caches. This PR moves all that callback syncing into a job that can run after updating the records in Postgres. 
https://github.com/thepracticaldev/dev.to/projects/6#card-36680670

Ensure Records are Updated Properly after a User Merge

---

app/models/comment.rb
spec/models/comment_spec.rb

@aaronpk reported seeing comment texts stored as an entire HTML document in issue https://github.com/thepracticaldev/dev.to/issues/7271, and I've run into the same problem trying to display comments in the home page feed: in the database `comments.processed_html` holds an entire HTML document instead of just an HTML fragment after validation is run on `comment.rb`. This PR changes the `Nokogiri` method we're using from `parse` to `fragment` so that we don't end up with the entire HTML document in the database.
resolves #7271 
This PR will only fix the saved HTML content for new comments, existing comments will not have their HTML corrected in the database. I separate issue has been reported for that: (xxx)

Parse comment html as fragments instead of docs

---

app/controllers/search_controller.rb
app/services/search/query_builders/reaction.rb
spec/services/search/reaction_spec.rb

Last piece of the puzzle before I PR the frontend Readinglist code! When a user filters by tags on their Reading List we want to use the AND operator between those tags. For example a search for #ruby and #rails should only return articles with BOTH tags.
https://github.com/thepracticaldev/dev.to/projects/6#card-36754138

Allow Reaction Search to Use AND Operator for Tag Searching

---

app/assets/stylesheets/chat.scss

Added svg color fill property for search icon
When the website theme changes, the chat search icon was not visible due to the absence of color property. I fixed by adding a default color property to the search icon. 
https://github.com/thepracticaldev/dev.to/issues/7398

Chat search icon color fix

---

app/controllers/api/v0/api_controller.rb
app/labor/rate_limit_checker.rb
app/services/articles/creator.rb
config/initializers/honeybadger.rb
spec/requests/api/v0/articles_spec.rb
spec/requests/articles/articles_spec.rb

Rather than raising a RuntimeError when a user hits a creation limit for articles lets raise a more helpful error like `RateLimitChecker::LimitReached`. We can then *ignore this error in Honeybadger* and rescue it in the API to return a helpful status code and message to the API user. 
Fixes: https://app.honeybadger.io/fault/66984/1558093e60d196166e600f756e4cd9da

Handle rate limit errors gracefully

---

config/database.yml

We have the same database url in `config/database.yml` for dev and test environments, so this can cause problems in case a developer uses custom urls.
In this pr I changed the test db url to use another env variable.

Make database url for test env different from the dev env one

---

app/services/authentication/authenticator.rb
spec/services/authentication/authenticator_spec.rb

Creating a `user` and then setting an `identity` should occur as an all-or-nothing step.
Wrapping this in an `ActiveRecord::Transaction` ensures that we don't update an identity
unless we successfully `create`/`update` the `user` first in the same database transaction.
Lol, #emergency.
N/A

Wrap user/identity coupled logic in a transaction

---

Envfile
app/services/fastly_vcl/whitelisted_params.rb
docs/backend/fastly.md
lib/tasks/fastly.rake
spec/tasks/fastly_spec.rb

In #7279 we added the `fastly:update_whitelisted_params` task to `release-script.sh`. This will fail for other communities who don't have Fastly configured. This PR adds a guard to not run the task if Fastly isn't configured so deployments don't fail.
There's still work to be done to generalize Fastly altogether.
**P.S.**
I updated Rubocop to ignore spec names for rake tasks. It was complaining:
```
RSpec/DescribeClass: The first argument to describe should be the class or module being tested.
```
#7279
https://github.com/thepracticaldev/dev.to/pull/7279#issuecomment-614879618
https://github.com/thepracticaldev/dev.to/projects/9#card-36459306
@mstruve can you add the ENV variable `FASTLY_WHITELIST_PARAMS_SNIPPET_NAME`?

Generalize Fastly rake task

---

app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/__tests__/Onboarding.test.jsx

Reorders the onboarding slides according to the new designs:
Also refactors the Onboarding tests, adding some helpful documentation! 😺 
Closes #7344. 
The "follow tags" slide (below):
now comes before the "profile form" slide (below):

Reorder onboarding slides

---

app/labor/mailchimp_bot.rb
app/services/authentication/authenticator.rb
app/services/search/client.rb
app/workers/metrics/record_daily_usage_worker.rb
app/workers/metrics/record_data_counts_worker.rb
spec/services/authentication/authenticator_spec.rb
spec/workers/metrics/record_daily_usage_worker_spec.rb
spec/workers/metrics/record_data_counts_worker_spec.rb

Using symbols and a hash for tags seems to work OK for `gauge` metrics, however, they do not work for increment and count metrics properly. I am sure the underlying gem code has some differences for each scenario. Rather than worrying about what type of metric we are sending to Datadog we should get in the habit of always using an array with strings.
Since I updated the existing specs so I am inclined to ignore the CodeClimate failure in this case.

Bug Fix: Use strings with colons for all Datadog tags

---

app/views/onboardings/_task_card.html.erb

Because we store styles in the app shell with service workers, certain features can roll out where the body is not lined up with the assets from the shell. This is kind of rare, but a problem we have not yet fully tackled.
This adds some in-html styling to ensure the `display:none` attribute is paid attention to here.
Currently some scenarios result in this...

Fix task card unstyled issue for rollout

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/EmailPreferencesForm.jsx
app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/Navigation.jsx
app/javascript/onboarding/components/ProfileForm.jsx

✨ Adds the world's _cutest-ever_ progress stepper to the onboarding slides! ✨
The four main "interactive" steps of the onboarding flow now are represented by a little progress stepper that shows up in the navigation of the onboarding slides.
As a part of this PR, I have also cleaned up the onboarding JS tests as well. 💪 
Addresses the first half of https://github.com/thepracticaldev/dev.to/issues/6544. (I will address the skip/continue feature in a later PR! 😄)
To QA this, you'll want to step through the onboarding flow locally.
You'll want to check that the stepper does _not_ render for the intro slide:
You'll also want to make sure that the stepper changes based on which slide you're looking at!
For example, the first slide looks like …

Add a progress stepper to onboarding flow

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/Navigation.jsx

Uses a back button svg icon rather than the text `Back` in the onboarding slides! I have used crayon styles (but not crayon "buttons").
Addresses a design change requested in https://github.com/thepracticaldev/dev.to/issues/6544. (More changes related to this issue to come in a later PR!)
To QA this, you'll want to step through the onboarding flow locally. The only difference should be that there is now an icon to step backwards, but everything should function the same:

Use back button svg icon in onboarding slides

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

Don't allow more than 10 requests per second from a single IP address. I am open to suggestions on the limit number. 10 felt like it was super lenient and safe but I could see us ratcheting it down to 5 or less. I just didn't want to bork any background requests Fastly might be making during a page load or things like that.

Throttle General Site Requests

---

app/controllers/stories_controller.rb
app/helpers/social_image_helper.rb

This PR represents the final work necessary to optimize cover images for SEO purposes. In order to ensure that cover images adhere to a `1:1`, `4:3`, and `16:9` ratio, I specified the necessary `height`s and `width`s for cover images in the JSON-LD found in `stories_controller.rb`, using the aspect ratio logic I set up in `social_image.rb` in my last PR (https://github.com/thepracticaldev/dev.to/pull/7417).
Closes #7291 
Closes #7228

Specify SEO-Optimized Width and Height for Cover Images

---

spec/tasks/fastly_spec.rb

Travis builds pass even with failed specs because we were using `exit`. Commenting out the spec for now as a hot fix.

Fix Travis CI

---

lib/tasks/fastly.rake
lib/tasks/search.rake
spec/black_box/black_box_spec.rb
spec/tasks/fastly_spec.rb

Following up on #7486, this should fix Travis CI and the Fastly spec. RSpec in Travis CI doesn't like the use of `exit`, so I changed it to `next`.
#7486

Fix Fastly rake task spec and Travis CI

---

.travis.yml
Dockerfile
config/environments/development.rb
docker-compose.yml
docker-entrypoint.sh

With https://github.com/thepracticaldev/dev.to/pull/7469 and https://github.com/thepracticaldev/dev.to/pull/7466 the whole concept of "yarn integrity checked" was removed from Webpacker.
Also changed `yarn install` to `yarn install --frozen-lockfile` per [new README](https://github.com/rails/webpacker#deployment):
> When compiling assets for production on a remote server, such as a continuous integration environment, it's recommended to use yarn install --frozen-lockfile to install NPM packages on the remote host to ensure that the installed packages match the yarn.lock file.

Removed yarn integrity check

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/Navigation.jsx
app/javascript/onboarding/components/ProfileForm.jsx

Updates the "next" button in the onboarding slides in the three "interactive" components: `FollowTags`, `ProfileForm`, `FollowUsers`. 
For these three slides, the text reads "Skip for now" unless the user has taken an action on the page. If they have (for example, selected a tag, or filled out a field on the form), the button text will update to read "Continue". The button state should return back to "Skip for now" if the user reverts their action (for example, hasn't selected a tag or removes all the text from the form inputs).
Also refactors the `ProfileForm` component to nest values on the `state` within a `formValues` object in order to make it easier to determine whether any of the form inputs have a value or not.
Closes …

Add skip/continue functionality to onboarding navigation

---

app/decorators/podcast_episode_decorator.rb
app/models/podcast_episode.rb
app/serializers/search/podcast_episode_serializer.rb
spec/models/podcast_episode_spec.rb

Specs passing for reallz this time!!!
I decided to remove Algolia from all the FeedContent models in separate PRs to make them a little more digestible and so if any bugs pop up they are easier to track down and fix. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32955089

Remove Algolia from Podcast Episodes w/ Specs 😉

---

app/javascript/listings/listings.jsx

Modal did not close upon choosing the filter tag.
Under the listing page, Modal does not close while choosing a tag. 
Fix method: Passed a static keyword (close-modal) from the addTag function to handleCloseModal. 
Closes https://github.com/thepracticaldev/dev.to/issues/7433

Modal not closing while choosing tag filter

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/controllers/comments_controller.rb
app/models/comment.rb
spec/requests/comments_create_spec.rb

Currently validation errors or other errors are treated as `HTTP 200 OK`, which makes it harder for the client to discern when the posting was successful and when it wasn't.
**when the comment text is too long**

Improve comment posting error handling

---

bin/setup

When we setup Postgres, if it is a new dev environment we will seed the database. Seeding the database involves indexing records to Elasticsearch so we need to make sure Elasticsearch is setup BEFORE we setup the database. 
https://github.com/thepracticaldev/dev.to/projects/6#card-37100951
I could see in the future having a little quick test suite for new env spin up.

Setup Elasticsearch before Postgres for New Dev Envs

---

db/schema.rb

This has to be okay to remove because it still lingers even after `db:reset`
n/a
n/a

Remove index_chat_channels_on_slug from schema

---

app/views/onboardings/_task_card.html.erb

Was "welcome thead" now is "welcome thread".  I noticed the spelling error show up as I recently just joined dev.to
Upon joining, user is presented with a welcome screen to recommend their next activities.  Noticed "thread" was spelled as "thread"

Fixed "Join the Welcome thread" spelling err

---

app/controllers/image_uploads_controller.rb

https://app.honeybadger.io/projects/66984/faults/63232440
We were trying to return a status code of `:server_error` (invalid) when rescuing `CarrierWave::ProcessingError`. This PR returns `:unprocessable_entity` instead.
https://app.honeybadger.io/projects/66984/faults/63232440

Change CarrierWave::ProcessingError error code

---

app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
app/assets/stylesheets/comments.scss
app/javascript/responseTemplates/responseTemplates.js
app/views/comments/_form.html.erb

This adds a more helpful message when opening response templates, in case folks don't know what it is.
This PR is mostly to get deploys going again. 😅

[deploy] Add a more helpful msg for response templates

---

app/views/comments/index.html.erb
spec/system/comments/user_views_podcast_comments_spec.rb

Fixes: https://app.honeybadger.io/fault/66984/e392eecb9f817d1cc07d51ced8a431de
```
ActionView::Template::Error: undefined method `user' for #<PodcastEpisode:0x00007feec9e546c8> Did you mean? user_id
index.html.erb  51 _app_views_comments_index_html_erb(...)
[PROJECT_ROOT]/app/views/comments/index.html.erb:51:in `_app_views_comments_index_html_erb'
49       <h3 id="comments-header"><%= @commentable.title %></h3>
50       <h4>
51         <%= @commentable.user.name %>
52         <span class="published-at"><%= "on " + @commentable.published_at.strftime("%B %d, %Y") if @commentable.published_at %></span>
53       </h4>
```

Bug Fix: Correctly Render Podcast Comments and Add Spec

---

app/assets/stylesheets/article-show.scss

When replacing the article show page `<div>` with an `<img>` tag in `articles/show.html.erb`, styling changes had to be made in `article-show.scss` to accommodate the changes in the template. In order to avoid caching conflicts due to the changes, the background and background-size styling for an article in `article-show.scss` had to remain in the stylesheet. This PR removes what is now dead code from `article-show.scss`.
Closes #7401

Remove Cover Image Background Styling From article-show.css

---

spec/rails_helper.rb
spec/support/elasticsearch_helpers.rb
spec/system/articles/user_visits_articles_by_timeframe_spec.rb

These tests are some of our more flaky tests and it seems to be because they are showing leftover Elasticsearch data from other specs. I "proved" this by [creating a branch that also checked the Postgres db counts](https://github.com/thepracticaldev/dev.to/compare/mstruve/flaky-test-info) before checking the page. If the db counts were as expected then that means what we are loading on the page is not in Postgres but likely in Elasticsearch. [Here is a green spec run](https://travis-ci.com/github/thepracticaldev/dev.to/builds/161705100) that contains a single failure(retried successfully)
```
expected to find visible css ".single-article-small-pic" 4 times, found 10 matches:
```
In an attempt to prevent this from happening I added a statement to clear the feed content data before each …

Flaky Spec Fix: Clear Elasticsearch data for user viewing timeline specs

---

app/javascript/chat/chat.jsx
app/javascript/packs/videoChat.jsx
app/models/message.rb
app/views/video_chats/show.html.erb

This is the last silly proof of concept before refactoring and extending these concepts. Enjoy 🙂.
This adds the `/play x` namespace which can open minigames in connect.

Add /play codenames proof-of-concept to /connect

---

db/migrate/20200409050122_add_listing_category_to_classified_listing.rb

Running `bin/setup` or `rails db:migrate` from scratch will fail as #7476 through the upgrade to `strong_migrations 0.8.4` introduced a new check:
> Added check for add_reference with foreign_key: true
#7476

Fix broken migration after strong_migrations 0.6.4

---

app/views/users/_notifications.html.erb

A fix to the label in the Settings under Mobile Notifications since PN's are now available in Android too. Leaving the label though because there's still a few notifications that could be implemented in the near future.

Removes iOS only label from mobile notifications settings

---

app/workers/search/index_to_elasticsearch_worker.rb
app/workers/search/remove_from_elasticsearch_index_worker.rb
spec/workers/search/remove_from_elasticsearch_index_worker_spec.rb

Often we will never get a chance to execute an indexing job for a Reaction bc it is destroyed before the job can execute. When it is destroyed however we will still attempt to remove it from Elasticsearch. This PR will ignore `Search::Errors::Transport::NotFound` errors for reactions when removing them like we do when adding them.

Ignore Search::Errors::Transport::NotFound error when Removing Reactions

---

db/seeds.rb

Algolia is no longer used by Articles so we can remove this.

Bug Fix: Remove article clear_index! from seeds file

---

app/models/reaction.rb
spec/models/reaction_spec.rb

When we destroy a reaction we will trigger `after_commit` callbacks. This means we were doubling up on busting the reachable cache and updating the reachable. 
```ruby
after_commit :bust_reactable_cache, :update_reactable
before_destroy :update_reactable_without_delay, unless: :destroyed_by_association
before_destroy :bust_reactable_cache_without_delay
```
To fix this I added the condition of `on: %i[create update]` to our after_commit callback so it is not triggered during a destroy

De-duplicate Cache Busting and Reactable Updates when Destroying Reactions

---

app/models/comment.rb

No need to waste resources enqueueing a job to rescore a comment after it has been destroyed.

Only Calculate Comment Score on Update and Create

---

app/assets/stylesheets/moderators.scss
app/views/moderations/index.html.erb

This removes the stats from `/mod`, based on the moderators' feedback. Simple quick win here 👍

Remove stats from /mod

---

app/workers/slack/messengers/worker.rb

In #7484 we removed the last vestiges of the old Slack code, we only left in `SlackBotPingWorker` to transition to the new name so that existing jobs could process without failing.
Now 5 days have passed and the Sidekiq queue definitely doesn't have jobs with the old name anymore, we can remove this.
#7484

Remove SlackBotPingWorker

---

app/models/concerns/searchable.rb
app/services/users/delete_activity.rb
app/services/users/delete_articles.rb
app/workers/search/bulk_index_worker.rb
app/workers/search/index_worker.rb
app/workers/search/remove_from_index_worker.rb
lib/data_update_scripts/20200305201627_index_users_to_elasticsearch.rb
lib/data_update_scripts/20200305201642_index_feed_content_to_elasticsearch.rb
lib/data_update_scripts/20200313123108_index_users_to_elasticsearch.rb
lib/data_update_scripts/20200326145114_re_index_feed_content_to_elasticsearch.rb
lib/data_update_scripts/20200406213152_re_index_users_to_elasticsearch.rb
lib/data_update_scripts/20200410152018_resync_elasticsearch_documents.rb
lib/data_update_scripts/20200415200651_index_reading_list_reactions.rb
spec/models/article_spec.rb
spec/models/chat_channel_membership_spec.rb
spec/models/classified_listing_spec.rb
spec/models/comment_spec.rb
spec/models/concerns/searchable_spec.rb
spec/models/podcast_episode_spec.rb
spec/models/reaction_spec.rb
spec/models/tag_spec.rb
spec/models/user_spec.rb
spec/services/moderator/banish_user_spec.rb
spec/services/users/delete_articles_spec.rb
spec/workers/search/bulk_index_worker_spec.rb
spec/workers/search/index_worker_spec.rb
spec/workers/search/remove_from_index_worker_spec.rb

Sorry for the large dif! Now that we have removed the Algolia Index Workers we can steal their names for our Elasticsearch workers. 
YES, I choose to do it inline, I will deal with any fallout or failed jobs that occur from this switch. I don't expect there to be a ton, we don't have a super high indexing volume yet. 
https://github.com/thepracticaldev/dev.to/projects/6#card-32887789

Search Generalization: Remove Elasticsearch from Index Worker Names

---

config/database.yml
docs/installation/postgresql.md

When relying on `DATABASE_URL` and forgetting to set `DATABASE_URL_TEST`, users would be hit with error similar to the following when setting up database.
```
Couldn't create 'PracticalDeveloper_test' database. Please check your configuration.
```
The need for `DATABASE_URL_TEST` could be pretty niche and I think this a good middle ground for  things to work as expected while providing the option for a separate database URL for those who look within `database.yml`
Resolve https://github.com/thepracticaldev/dev.to/issues/7557
n/a

Make DATABASE_URL_TEST optional

---

app/controllers/internal/configs_controller.rb
app/helpers/authentication_helper.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
app/views/layouts/internal.html.erb
spec/requests/internal/configs_spec.rb

Right now the authentication providers selection in the configuration is a bit cumbersome.
This PR switches to a select (I had to use [bootstrap-select](https://developer.snapappointments.com/bootstrap-select/) as the regular select had issues with multiple selection and default values, too much went into trying to get that right :D).
With this new select, see the `selectpicker` class in the select, it also opens the possibility of it being used in other configuration options. Out of the scope for this PR

Add multiple select to authentication providers configuration

---

app/controllers/users_controller.rb
app/policies/user_policy.rb
app/services/authentication/authenticator.rb
app/services/authentication/providers/github.rb
app/services/authentication/providers/provider.rb
app/services/authentication/providers/twitter.rb
app/views/users/_account.html.erb
app/views/users/_account_providers_settings.html.erb
app/views/users/_additional_authentication.html.erb
config/routes.rb
spec/policies/user_policy_spec.rb
spec/requests/user/user_settings_spec.rb
spec/support/omniauth_helpers.rb

In this PR we generalize the last (hopefully) remaining part of the user facing code, the settings/account panel.
- renamed `remove_association` to `remove_identity`
- made sure one can only remove enabled providers (we don't show disabled providers anyway, but it's good to check server side as well)
- added `settings_url` which points to the URL where the user can land to remove the oauth association
- future proof some code and tests which checked if the total number of identities was 2 (we'll soon have more)
- use `sign_in_path` everywhere
Closes https://github.com/thepracticaldev/dev.to/issues/7585

Authentication refactoring: generalize account settings

---

spec/requests/articles/articles_show_spec.rb

Fixes: https://travis-ci.com/github/thepracticaldev/dev.to/builds/162996347
We are loading the page, then updating the article, then checking the response. Since the date parsing is not super granular usually we get the same on the page anyways despite updating after. To prevent this from failing though we need to update the article THEN load the page.

Flaky Spec Fix: Load article page AFTER updating the article

---

app/controllers/internal/configs_controller.rb
app/controllers/organizations_controller.rb
app/labor/rate_limit_checker.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
docs/backend/elasticsearch.md
spec/labor/rate_limit_checker_spec.rb
spec/requests/internal/configs_spec.rb
spec/requests/user/user_organization_spec.rb

Limit the number of organizations a user can make to 1 per 5 minute period. I went with the same approach as article creation and just raised a rate limit reached error. 
There is A LOT of duplicated code here that could use a good refactor. I plan to tackle that in a separate PR.

Rate Limit Organization Creation

---

spec/lib/data_update_scripts/index_chat_channel_memberships_to_elasticsearch_spec.rb
spec/lib/data_update_scripts/index_classified_listings_to_elasticsearch_spec.rb
spec/lib/data_update_scripts/index_reading_list_reactions_spec.rb
spec/lib/data_update_scripts/re_index_feed_content_to_elasticsearch_spec.rb
spec/lib/data_update_scripts/re_index_users_to_elasticsearch_spec.rb
spec/lib/data_update_scripts/resync_elasticsearch_documents_spec.rb
spec/rails_helper.rb
spec/serializers/search/article_serializer_spec.rb
spec/serializers/search/comment_serializer_spec.rb
spec/serializers/search/user_serializer_spec.rb
spec/services/search/base_spec.rb
spec/services/search/chat_channel_membership_spec.rb
spec/services/search/classified_listing_spec.rb
spec/services/search/feed_content_spec.rb
spec/services/search/reaction_spec.rb
spec/services/search/tag_spec.rb
spec/services/search/user_spec.rb
spec/system/articles/user_visits_articles_by_timeframe_spec.rb
spec/workers/search/bulk_index_worker_spec.rb
spec/workers/search/index_worker_spec.rb

By default if we are using Elasticsearch for a spec we will reset ALL of our indexes with a very brute force approach. This is fine until you have a lot of Elasticsearch dependant tests, then it gets very sloooooow. In all of our search specs I replaced the full elasticsearch reset with a simple clear data method which uses a `delete_by_query` to ensure there is no data in the index.
So how much faster does this make the specs? Here are before and afters of all the `/search/` specs.
```
.........................................................................................................................
Finished in 2 minutes 40.4 seconds (files took 7.88 seconds to load)
121 examples, 0 failures
............................................................................................ …
```

Clear Elasticsearch Data Instead of Resetting Entire Index for Specs

---

spec/requests/articles/articles_show_spec.rb

Grasping at straws on this one..due to the way we're handling time stamps, we have a flakey spec. This PR adds a bandaid to the spec by checking if the date is within 1 day. Another option is to turn off this spec entirely until the bugs are fixed.
The real solution is to fix the current bugs related to how we're rendering the date times:
https://github.com/thepracticaldev/dev.to/issues/7086
https://github.com/thepracticaldev/dev.to/issues/7561
https://github.com/thepracticaldev/dev.to/issues/7086
https://github.com/thepracticaldev/dev.to/issues/7561

Temporary Article show spec fix - rendering correct date time

---

app/models/site_config.rb
app/views/internal/configs/show.html.erb
spec/requests/internal/configs_spec.rb

I am going to be adding some more configs for onboarding, and it is currently hard to find all the onboarding-related configs. I have pulled them all into their own little "Onboarding" section within the `/internal/config` page.
While I was at it, I also pulled all the mascot-related configs into a "Mascot" section when I noticed that the mascot-related configs are scattered across different sections as well.
All of this is the initial work before I tackle https://github.com/thepracticaldev/dev.to/issues/7106.
This PR makes the below visual changes to the `/internal/config` page:
Here's what the mascot section looks like:
And here's what the onboarding section looks like:

Extract onboarding + mascot configs

---

app/controllers/chat_channels_controller.rb
spec/requests/chat_channels_spec.rb

Rather than raising an error and alerting us of an invalid or blocked chat channel that attempted to be created, lets return the error message to the user. These error messages are raised [from the model](https://github.com/thepracticaldev/dev.to/blob/master/app/models/chat_channel.rb#L61) method `create_with_users`.
Fixes: https://app.honeybadger.io/fault/66984/68c73cbac26355e307a9d755712bd8e9

Honeybadger Fix: Return Usable Error Message when chat creation fails

---

Gemfile.lock
app/models/user.rb
config/field_test.yml
spec/factories/field_test_memberships.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/requests/stories/feeds_spec.rb
spec/services/users/delete_spec.rb
spec/workers/field_tests/prune_old_experiments_worker_spec.rb

Upgrading `field_test` to the latest 0.3.2 version. [dependabot tried](https://github.com/thepracticaldev/dev.to/pull/7475) but fortunately one of the tests broke as there's breaking change in one of the transitive dependencies 👀 , the gem `browser`.
Basically the empty user agent, sent by request specs, is considererd a bot now, thus failing to create the new experiment.
For more details, see [browser: Bots](https://github.com/fnando/browser#bots).
**note:**, this will change the behavior in production as well:
- requests with a missing user agent will be considered a bot
- requests with these keywords - `/crawl|fetch|search|monitoring|spider|bot/` - will be considered a bot.
If we want to keep the existing behavior, we need to undo this change like suggested:
> To restore v2's bot …

Upgrade field_test to 0.3.2

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

Limit the number of messages one user can send to another. It is worth it to note that when a [throttle block returns nil, we do NOT hit Redis](https://github.com/kickstarter/rack-attack/blob/master/lib/rack/attack/throttle.rb#L26).

Limit 1 message every second for  single user

---

app/models/podcast.rb
spec/models/podcast_spec.rb

Stop trying to find an existing podcast episode by website url in case item link is empty in the rss.
I also added a comment for our controversial logic related to `unique_website_url?`.

Fix finding existing podcast episode by website url

---

bin/setup
db/seeds.rb

Instead of trying to check if a database exists, this change will run db:migrate and it will run db:setup as a backup. This is more inline with how [Rails 6 will handle this](https://github.com/rails/rails/blob/98754de1412870d7dae9eba1c7bac944b9b90093/activerecord/lib/active_record/railties/databases.rake#L311). The downside is new contributor will see an error briefly. 😬 
I made this change because I rely on `DATABASE_URL` to access postgresql in Docker; Checking if database exist with `psql -o /dev/null...` does not work for me and I can't think of a way for `bin/setup` to access env var in `application.yml`.
Also, I removed dome dupe seeds.
n/a
n/a
n/a

Update bin/setup's db setup logic

---

db/seeds.rb

The combination of changes in https://github.com/thepracticaldev/dev.to/pull/7498 and https://github.com/thepracticaldev/dev.to/pull/7512 and how rails helper is loaded messed me up. Anyway I get this error randomly when I try to set up my db.
```
NoMethodError: undefined method `categories_available' for #<Class:0x000000000e2c75f0>
/home/mac/dev.to/db/seeds.rb:426:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)
```
This fixes it by not using `ClassifiedListing.categories_available.keys`
n/a

Remove ClassifiedListing.categories_available.keys in seed

---

app/controllers/stories_controller.rb
spec/requests/stories_index_spec.rb
spec/requests/stories_show_spec.rb

Current redirects for situations where a user changed their username etc. should be 301: Moved Permanently. This is the proper status for search engines etc. vs the current 302 default which is not meant for this kind of redirect.

Add proper 301 status to username change redirects

---

app/assets/javascripts/initializers/initializePodcastPlayback.js

Since we merged #7554 I ran a quick test and found out we do have older native app versions that won't be able to play podcasts because **they do have** `DEV-Native-android` as user agent but the native bridge side is still not implemented. 
This simple check fixes this issue by falling back to the full on web player until the users have a a version installed that does include the necessary native functions.
#7554 
When the native side is in production (https://github.com/thepracticaldev/DEV-Android/pull/72) we can have this check removed although it wouldn't hurt to keep it for a while since not everyone updates immediately

Adds an extra check for Android Native app for playing podcasts

---

app/controllers/internal/configs_controller.rb
app/controllers/users_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
spec/requests/internal/configs_spec.rb
spec/requests/user/user_suggestions_spec.rb

Closes https://github.com/thepracticaldev/dev.to/issues/7106.
The suggested "users to follow" can now be set by admins via the `SiteConfig`:
Those suggested default users will show up in onboarding as a fallback:

Allow admins to configure default users to follow during onboarding

---

app/views/articles/_sidebar.html.erb

Since the sponsors don't change very often it makes sense to have a cache here, but 5 days is really inconvenient. Currently it only clears when we deploy. This will mean we don't have to wait longer than 15 minutes, but we'll still cache 99% of requests.

Clear sponsor cache more frequently

---

Envfile

In #7654 I forgot to remove `FASTLY_SAFE_PARAMS_SNIPPET_NAME` from the Envfile.
#7654
Remove `FASTLY_SAFE_PARAMS_SNIPPET_NAME` from Heroku cc @mstruve

Remove FASTLY_SAFE_PARAMS_SNIPPET_NAME env var

---

app/models/identity.rb
app/views/users/_account.html.erb
spec/requests/user/user_settings_spec.rb

There's a scenario in which the "remove oauth accounts" section in `Settings -> Account` should not appear:
1. a user has multiple identities
1. one of the related providers is disabled by an admin
1. the user can now disconnect their only visible identity/provider
This last step shouldn't be allowed
**user has 2 identities, but there's only 1 provider enabled**
**before**
**after**

Fix showing "Remove OAuth" in settings with disabled identities

---

spec/factories/users.rb
spec/requests/user/user_show_spec.rb

While the original implementation worked, this PR refactors the `user_show_spec.rb` to better test the JSON-LD data within the `Stories::Controller`. 
Rather than having multiple single-line expectations, the spec now tests against the JSON-LD in one test. In addition to being more concise, the spec now tests for more data and does so against the actual data structure by parsing the data after grabbing the `response.body` with Nokogiri.
These improvements should make refactoring the actual JSON-LD (see issue #7495 ) within the `Stories::Controller` easier and should overall make the `user_show_spec.rb` stronger.
Relates to #7495 - this is the initial refactor needed to ensure further refactoring is accurate

Refactor JSON-LD Within user_show_spec to Improve Testing

---

app/controllers/classified_listings_controller.rb
app/controllers/concerns/classified_listings_toolkit.rb
app/models/site_config.rb
app/services/rate_limit_checker.rb
spec/requests/listings_spec.rb

Limit the number of Classified Listings a user can create in a single minute. Allow it to be configured, default 1.

Rate Limit Classified Listing Creation

---

app/assets/stylesheets/comments.scss

This fixes the width of a comment's permalink page.
**Article show page**
**Comment permalink page**

Fix comment container width issue in comment permalink

---

app/assets/stylesheets/components/navigation.scss
app/assets/stylesheets/components/notices.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/themes/hacker.scss
app/assets/stylesheets/themes/minimal.scss
app/assets/stylesheets/themes/night.scss
app/assets/stylesheets/themes/pink.scss

@lisasy and myself both have been noticing that we may benefit from having additional shades of certain colors. Right now, we have several shades for base colors and two additional shades for each accent color. But sometimes we need extra shades that are not solid colors - instead they are generated by setting certain opacity.
For that reason, this PR brings more variables for `base`:
```
--base-a90: #{rgba(#08090a, 0.9)};
...
--base-a5: #{rgba(#08090a, 0.05)};
```
And one (for now) extra variable for accents:
```
--accent-brand-a10: #{rgba(#3b49df, 0.1)};
--accent-success-a10: #{rgba(#26d9ca, 0.1)};
--accent-warning-a10: #{rgba(#ffcf4c, 0.1)};
--accent-danger-a10: #{rgba(#dc1818, 0.1)};
```

Color Updates

---

app/views/articles/_full_comment_area.html.erb

This solves a small 1-2px content jump when the button loads. This is a quick fix of the issue.

Quick inline style to solve content jump

---

app/workers/articles/bust_cache_worker.rb
app/workers/articles/score_calc_worker.rb
app/workers/articles/update_analytics_worker.rb
app/workers/articles/update_main_image_background_hex_worker.rb
app/workers/bust_cache_base_worker.rb
app/workers/classified_listings/bust_cache_worker.rb
app/workers/comments/bust_cache_worker.rb
app/workers/events/bust_cache_worker.rb
app/workers/export_content_worker.rb
app/workers/organizations/bust_cache_worker.rb
app/workers/pages/bust_cache_worker.rb
app/workers/podcast_episodes/bust_cache_worker.rb
app/workers/podcasts/bust_cache_worker.rb
app/workers/rss_reader_fetch_user_worker.rb
app/workers/tags/bust_cache_worker.rb
app/workers/users/bust_cache_worker.rb
app/workers/users/resave_articles_worker.rb
app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb

This PR introduces unique constraints to all of our CacheBustWorkers and to workers that are kicked off by user actions. These will help ensure that we are not doing duplicate unnecessary work. 
I bumped the default retry for CacheBustWorkers to 15 since 10 gives us 4 hours but I could see a service possibly having issues longer than that so I increased it.

Force Unique Jobs for User Initiated Jobs and Cache Jobs

---

app/controllers/reactions_controller.rb
app/models/site_config.rb
app/services/rate_limit_checker.rb
spec/requests/reactions_spec.rb

Limit the number of reactions created in a 30 second window, default to 10, and allow it to be configurable.

Limit Reactions Created in a 30 second Timeframe

---

app/controllers/concerns/valid_request.rb
app/liquid_tags/organization_tag.rb
app/liquid_tags/user_tag.rb
app/models/article.rb
app/models/event.rb
app/models/user.rb
app/views/organizations/_liquid.html.erb
app/views/users/_liquid.html.erb
spec/labor/cache_buster_spec.rb
spec/requests/page_views_spec.rb
spec/requests/stories_show_spec.rb

String interpolation is often preferred over concatenation in Ruby. While the latter may be faster for two strings, it does generate more intermediate string objects when concatenating more strings. Interpolation also calls `to_s` automatically, which simplifies the resulting code.
This is what I do for fun. I'm also great at parties.

Change string concatenation to interpolation

---

app/controllers/internal/configs_controller.rb

Refactor method in internal controller

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

Allow us to see IPs in Honeycomb to block bad actors. Chatted with Ben about this approach and we agree it seems like a good one.

Track Client IPs to Help Block Bad Actors

---

app/assets/stylesheets/components/stories.scss
app/javascript/articles/Article.jsx

Currently feed cards are completely clickable, but only in the feed. Posts in tag pages or search results do not currently support this (future TODO). This PR adds the cursor pointer to only home page feed posts.

Now pointer cursor is only on feed posts.

---

app/controllers/reactions_controller.rb
app/javascript/actionsPanel/actionsPanel.js
app/views/moderations/actions_panel.html.erb

In production, we are able to select **both** a 'thumbs-down' and a 'vomit' reaction. Now that we have a 'thumbs-up' reaction, it does not make sense to be able to select both 'thumbs-up' and 'thumbs-down' reactions (or 'thumbs-up' and 'vomit' reactions). This PR prevents the selection of these nonsensical reaction pairs.
None
None

Mod Actions Panel: Prevent nonsensical reaction pairs

---

app/views/comments/edit.html.erb

Fixes a small bug with the comment edit container taking up the full width of the screen.
<hr>

Use same class for comment show page

---

app/views/service_worker/index.js.erb

:wrench: :turtle:
Some short-circuiting :zap: logic in the service worker was checking the truthiness of the result to a call to `caches.match`. The match api, however, is asynchronous and always returns a promise.
Hence, this guard did not accomplish what it was supposed to, and now whenever the cache for `shell_top` or `shell_bottom` is empty, the service worker hits a runtime error that, at least in my experience in Safari, blocks the main page from loading. (See the related bug for my _story_ 📚.)
Inspired by this issue: #5434 
No UI changes.
I've never tested a service worker before `¯\_(ツ)_/¯`, and neither I nor the other users who hit this issue ever actually determined the conditions under which it would occur. All I know is it happened to me enough that I was determined to do …

Fix intermittent service worker runtime error 

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

I noticed after merging #7730 that we will only record client IPs for successful requests. Anything that is throttled we will not have the client IP bc we will bail before we get to the tracking. Here is how [rack-attack works](https://github.com/kickstarter/rack-attack#how-it-works) and because of that I added the tracking to the throttles. It's not pretty but it will get the job done and since we are simply adding a key to a hash I am not worried about any performance issues from possibly doing it multiple times. 
```ruby
def call(env)
req = Rack::Attack::Request.new(env)
if safelisted?(req)
@app.call(env)
elsif blocklisted?(req)
self.class.blocklisted_callback.call(req)
elsif throttled?(req)
self.class.throttled_response.call(env)
self.class.throttled_callback.call(req)
else …
```

Track IPs and API Tokens for Throttled Requets, Send Retry After Header

---

app/views/internal/feedback_messages/index.html.erb
spec/system/internal/admin_manages_reports_spec.rb

This just makes it possible to search all reports regardless of status from the feedback messages UI.

Allow empty status option for feedback messages

---

spec/support/elasticsearch_helpers.rb
spec/system/search/display_articles_search_spec.rb
spec/system/search/display_users_search_spec.rb

These two specs test that when we load users and articles from Elasticsearch they have all the data necessary to correctly display on the page. I plan to do this as well for podcasts and comments. We can further expand on these with many scenarios but I thought this was a good base to get us going. 
https://github.com/thepracticaldev/dev.to/projects/6#card-36667928

Add Feature Search Tests for Users and Articles

---

app/controllers/internal/organizations_controller.rb
app/helpers/organization_helper.rb
app/views/internal/organizations/show.html.erb
app/views/internal/users/_credits.erb
config/routes.rb
spec/helpers/organization_helper_spec.rb
spec/requests/internal/organizations_spec.rb
spec/system/internal/admin_manages_organizations_spec.rb

As requested by @michael-tharrington in https://github.com/thepracticaldev/tech-private/issues/427, this PR adds credit management to the org mod page. It also improves the credit editing experience on the user mod page and cleans up/refactors some code.
https://github.com/thepracticaldev/tech-private/issues/427
Org mod page:
1. The forms for managing credits are now directly on `/internal/organizations/:id` and the remove option will only be shown when there are credits to remove. You also see how many credits are currently available:
2. The inputs are now actually of type number, with the little arrows for increasing/decreasing, and all that. In the case of adding credits, values from 1 to 99999 are valid, for removing it's 1 to the number of current credits. So you can't submit the …

Add org credit management to org mod page

---

app/helpers/rate_limit_checker_helper.rb
app/models/site_config.rb
app/models/user.rb
app/services/rate_limit_checker.rb
spec/initializers/rack/attack_spec.rb
spec/models/user_spec.rb
spec/services/rate_limit_checker_spec.rb

Only allow 2 email changes within a 2 minute period. If limit is exceeded show the user an error message with a retry message. As you can see below, since the email is not updated we still show that a verification email was sent to the previous updated email address. At the same time we also tell the user they will have to wait 120 seconds before retrying to update their email.
I also took this opportunity to do a solid refactor of the RateLimitCheck spec. There is more that could be done but this eliminates the needs to add multiple specs when we add simple cache rate limit keys.

Limit User Email Changes

---

app/models/chat_channel.rb
spec/models/chat_channel_spec.rb

Somehow we are allowing people to create chat channels with themselves. When this happens we break our serialization bc the "other_user" is not present. This prevents chat channels for a single user from being created. Their ChatChannelMemberships would be invalid anyways bc we enforce uniqueness between user_id and channel_id
Fixes: https://app.honeybadger.io/fault/66984/436a2859b03e24cb43dda4036b498ab9

Only Allow Direct Channels Between 2 Different People

---

app/controllers/organizations_controller.rb
spec/system/organization/user_updates_org_settings_spec.rb

The `users/edit.html.erb` template uses an intricate logic to decide which partial to render. It was defaulting to the "create a new org" template, instead of of the "edit an org as the admin" template.
Fixes https://github.com/thepracticaldev/dev.to/issues/7750
#7750

Render the correct partial when updating an organization fails

---

app/assets/stylesheets/moderators.scss
app/javascript/packs/loadActionsPanelButton.js
app/views/moderations/index.html.erb

Fixes `dev.to/mod` to use `/:article/actions_panel` over `/:article/mod`

Use actions panel for /mod page

---

config/initializers/honeycomb.rb

`.slice!` will remove how ever many characters you want off the front, return them, and then leave your string with the rest. We want those first 300 so we need to make sure we capture those in our command field in Honeycomb and not what is leftover.

Return the First 300 characters for Redis Commands

---

app/controllers/reactions_controller.rb
spec/requests/reactions_spec.rb

We need to authorize a user before we attempt to rate limit them since rate limiting requires a user. Without one we end up with this error: https://app.honeybadger.io/fault/66984/320e664c50618130dca15f99f128093e. This PR authorizes the user in a before_action executed before the rate limiter action. 
Fixes: https://app.honeybadger.io/fault/66984/320e664c50618130dca15f99f128093e

Ensure Users are Authorized Before Checking Reaction Rate Limit

---

app/models/user.rb
spec/models/user_spec.rb

We will try to validate this confirmation sending rate limit for new users which we should not be doing. I added an additional check to the guard clause to look for an id indicating an existing user. I have a loop clearing the generic cache keys right now. 
Following this, I will issue a PR to raise an error in the RateLimitCheck if user.id is nil bc that should never happen.

Bug Fix: Only Throttle Confirmation Emails for Existing Users

---

app/helpers/application_helper.rb
spec/requests/stories_show_spec.rb
spec/system/organization/user_views_an_organization_spec.rb
spec/system/user/view_user_index_spec.rb

This shortens the page title from `Productive and simple way to deploy Dockerized applications - DEV Community 👩‍💻👨‍💻` to just `Productive and simple way to deploy Dockerized applications - DEV` for non-signed-in traffic. Home page is still `DEV Community 👩‍💻👨‍💻`.
This is because search engines have struggled to display this consistently and moving just to DEV should help. I love the funkiness of the emojis but now that we're not using them for signed-out traffic we can be even funkier with them because we won't care about confusing the bots. We had a PR about randomizing the skin tones of the characters in the emoji and I was sort of unsure about doing that if the search engines are expecting consistency but this could free us up in that regard.

Shorten page title for unauthenticated traffic

---

app/assets/stylesheets/widgets.scss

I attempted to fix the problem with the alignment between the podcast name and image.
*none*

Fixed alignment

---

spec/helpers/organization_helper_spec.rb

A spec introducd in #7761 is flaky:
```
1) OrganizationHelper display the correct options
Failure/Error: expect(options).to include("#{org1.name} (1)")
expected "<option value=\"14\">Murray, Dickinson and D&#39;Amore (1)</option>\n<option value=\"15\">Krajcik-Kozey (0)</option>" to include "Murray, Dickinson and D'Amore (1)"
Diff:
@@ -1,2 +1,3 @@
-Murray, Dickinson and D'Amore (1)
+<option value="14">Murray, Dickinson and D&#39;Amore (1)</option>
+<option value="15">Krajcik-Kozey (0)</option>
```
The Rails tag helpers encode entitities such as `&` or `'`, but rather than duplicating that on the expectations and re-testing Rails I switched to hard-coded org names.
n/a

Fix flaky organization helper spec

---

app/assets/stylesheets/settings.scss
app/controllers/github_repos_controller.rb
app/controllers/stories_controller.rb
app/controllers/users_controller.rb
app/javascript/githubRepos/__tests__/__snapshots__/singleRepo.test.jsx.snap
app/javascript/githubRepos/__tests__/singleRepo.test.jsx
app/javascript/githubRepos/githubRepos.jsx
app/javascript/githubRepos/singleRepo.jsx
app/models/github_repo.rb
app/models/user.rb
app/policies/github_repo_policy.rb
app/services/github/client.rb
app/views/github_repos/index.json.jbuilder
app/views/users/_github_repositories_area.html.erb
app/views/users/_integrations.html.erb
app/views/users/_integrations_github_repositories.html.erb
app/views/users/_response_templates.html.erb
app/views/users/_sidebar_additional.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/models/github_repo_spec.rb
spec/models/user_spec.rb
spec/policies/github_repo_policy_spec.rb
spec/requests/github_repos_spec.rb
spec/requests/internal/negative_reactions_spec.rb
spec/requests/user/user_profile_spec.rb
spec/requests/user/user_settings_spec.rb

In this PR I tried to start refactoring the functionality around displaying GitHub repositories in one's profile.
It contains:
- a "flag" which hides the integration in setting if the user hasn't signed in through GitHub (we use their user's token to fetch repositories)
- `User.authenticated_through?(provider_name)` as a generalized boolean check to see if the user has that particular authentication.
- various cleanups in the code
- "select/remove" of repos doesn't call GitHub by fetching _all_ repositories, but only fetches the one we need
In future installments I plan to address #212 and #7751 by changing the logic we use to fetch/retrieve/update but it'd make this PR too big so I stopped before that.
I haven't replaced the custom Octokit client with our `Github::Client` as well, will …

Refactoring GitHub Repos functionality - step 1

---

config/initializers/rack/attack.rb

After merging #7676 we have decreased the number of hits we make to our backend in a short period of time. After doing some poking around Honeycomb it looks like we max out around 6 req/second and those spikes are usually not sustained so I figured 20 req/2 secs would give us enough buffer for normal functionality. Let me know your thoughts!

Decrease General Site Request Limit

---

app/views/articles/index.html.erb

Since the shell and index page is out of sync, this provides some redundancy of style while users are still on old styles in the cached shell.

Include crayons style in index view for redundency

---

app/assets/stylesheets/components/stories.scss
app/controllers/stories_controller.rb
app/javascript/podcasts/PodcastEpisode.jsx
app/javascript/podcasts/__tests__/__snapshots__/PodcastEpisode.test.jsx.snap
app/javascript/podcasts/__tests__/__snapshots__/TodaysPodcasts.test.jsx.snap

Podcast episode images are currently a little messed up and the titles don't have the proper class. I also took the liberty of downsizing the font _slightly_ even from the intended one because I think as a list they don't need to be so individually pronounced.
Mostly just a style bug fix though.

Fix podcast styling

---

app/services/rate_limit_checker.rb
spec/services/rate_limit_checker_spec.rb

To prevent generic cache keys from incorrectly being made if an unpersisted user is passed to the RateLimitChecker we will raise an error if the user ID is not present when creating the cache key.

Raise an Error If Trying to Rate Limit with a Missing User ID

---

app/assets/stylesheets/components/comments.scss
app/assets/stylesheets/components/stories.scss
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/CommentListItem.jsx
app/javascript/articles/components/__tests__/__snapshots__/CommentsList.test.jsx.snap
app/views/articles/index.html.erb

This makes an adjustment so longer comments subtly fade away... Maybe not the permanent solution but I think it works...
This also fixes the ill-fated inlined `<style>`

Adjust overflow in comments and revert inline css

---

app/models/comment.rb
app/models/concerns/searchable.rb

We recently had two incidents where an Article and a Comment were updated and then right after deleted. This led to index and removal from index jobs to be enqueued close enough together that the removal job finished before the indexing jobs causing the records to still be in Elasticsearch even though they are no longer in Postgres. A big reason for this is our callbacks which ideally we should get rid of. However, that is a huge undertaking so **my "hack" to solve this problem for now is to put a small delay on the removal job of 5 seconds.**
While trying to make heads and tails of our callbacks I went ahead and organized the comment callbacks which were kinda haphazardly thrown together.

Delay RemoveFromIndex Job to Fix Callback Race Conditions

---

app/assets/stylesheets/preact/onboarding-modal.scss

While trying to take some screenshots for a blog post, I found a visual bug in our onboarding flow on Safari. In the "follow users" slide, the background color of the rows of the scrollable table is all wrong:
Notably, this does _not_ happen on Chrome. I investigated and found out that Safari was inheriting the border-bottom color from elsewhere (?). So we'll need to specify the background-color for the content row element explicitly.
N/A
Before this change on Safari:
After this change on Safari:
N/A

Specify background for content row in onboarding

---

app/controllers/users_controller.rb
app/lib/url.rb
app/views/users/_profile.html.erb
app/views/users/edit.html.erb
spec/system/user/user_edits_profile_spec.rb

When a username is invalid and contains spaces, the profile page that is supposed to render the errors will break due to URI parsing. 
Fixes https://github.com/thepracticaldev/dev.to/issues/7758

Fix profile page rendering when a username contains spaces

---

app/assets/stylesheets/components/stories.scss
app/assets/stylesheets/components/tags.scss
app/assets/stylesheets/config/_variables.scss

This PR addresses the issue with flare tag misalignment in the feed card reported here: #7808 . It's a tricky one to test because it feels like everyone nowadays have different browser with different font stack installed locally... Would love several people to take it for a ride on whatever browsers they have and shoot me screenshots if any of the flare tags look misaligned..
Closes #7808

Feed: Flare tag alignment

---

app/views/internal/negative_reactions/index.html.erb
spec/factories/reactions.rb
spec/requests/internal/negative_reactions_spec.rb

It totally slipped my mind that we can create negative reactions on
comments. This PR accounts for that in the internal view that renders
negative reactions.

Handle negative reactions on comments

---

app/models/buffer_update.rb
spec/models/buffer_update_spec.rb

This limits the number of suggestions a user can make for a given social service and given article.

Limit Suggestions for Social Service Posts to 3 Per Article Per Service

---

.erb-lint.yml
app/views/articles/_block.html.erb
app/views/articles/_single_sponsor.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/articles/show.html.erb
app/views/articles/tags/_sidebar.html.erb
app/views/comments/index.html.erb

- protected css + javascript content by not escaping them (with `<%==` for js and a tag for css.
- replaced html_safe with sanitization where possible
Warnings fellt from around 45 to 31 (but I also fount out there is another rubocop file that was excluding some files, so total of warning might be a little above).
#5914

Fixes some html_safe in Articles

---

app/views/articles/_badges_area.html.erb

Instead of an empty sidebar, add a text that is displayed in mobile views except desktop.
Left an ipsum as suggested by @jessleenyc in https://github.com/thepracticaldev/dev.to/issues/4610#issuecomment-549384992
Would close #4610

Show Empty State in Badges List for Mobile Views

---

app/controllers/application_controller.rb
app/helpers/rate_limit_checker_helper.rb
app/services/articles/creator.rb
app/services/articles/updater.rb

We were missing our configurable rate limit for article updates from our config display list in admin, this adds it. Plus I did a little refactoring with the new `user.rate_limiter` method.

Expose Article Update Rate Limit on Config Page

---

app/assets/stylesheets/article-show.scss
app/dashboards/article_dashboard.rb
app/decorators/article_decorator.rb
app/views/articles/show.html.erb
db/migrate/20200511224704_add_query_friendly_admin_fields_to_articles.rb
db/schema.rb
spec/decorators/article_decorator_spec.rb
spec/requests/stories_show_spec.rb

This feature allows admins to add a label which helps clarify the content of a post, primarily for our own search engine as well as Google, and of course clarification for humans. For now this is just going to affect non-logged-in traffic but I could see this being pretty useful across all posts.
It puts a preamble in the `<title>` tag and on the post, but it is distinct from the actual article content—I think it is helpful and appropriate to modify things about _the page_, but not the title/body of the content itself, which is authored by the user.
This also adds an option to re-word the description, which again is part of site meta info and not necessarily part of the content itself.
Here is an example where this could be helpful: The title itself isn't enough to convey that this is a …

Add query-friendly article additions (Initial step)

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/comments.scss

…al space
Currently in comments and articles if we have an image which is _super tall_ it sometimes kind of breaks things because we default to 100% max-width. This PR adds sensible max heights to complement max width and ensure images are more easily consumed if they are super tall.
Tall images like this are now much less out of place.
Screenshots are probably the worst offender in that they tend to be _super tall_ and kind of ugly when blown up huge. This helps account for more types of images. Clicking still lets the user see a bigger pic (And we could close the loop on lighthouse view to really make this a slick experience).

Add max height to content images to ensure they can't over-eat vertical space

---

db/schema.rb

For some reason, after merging #7794, our `schema.rb` has fields in the wrong order.
Just ran `db:migrate` and ended up with this diff.

Fix schema.rb order

---

app/models/feedback_message.rb
spec/factories/feedback_messages.rb
spec/models/feedback_message_spec.rb

Enforce uniqueness between reported_url and feedback type when reporting abuse and reporter_id is present to avoid duplicate reports.

Enforce Uniq Abuse Reports from Reporters

---

app/controllers/api/v0/articles_controller.rb
config/initializers/doorkeeper.rb
config/locales/doorkeeper.en.yml
spec/requests/api/v0/articles_spec.rb

This PR adds `:write_articles` scope to expand our doorkeeper capability. I've also enabled `enforce_configured_scopes` so that application can only be created with scope we provided
n/a
- [y] yes
n/a

Create write_articles oauth scope

---

app/views/dashboards/followers.html.erb
spec/system/dashboards/user_followers_display_spec.rb

This updates the user followers Dashboard buttons to use the same bulk_show endpoint we use in our search for fetching the status for the buttons.

Use bulk_show Endpoint for Follow Buttons on Followers Dashboard

---

app/controllers/application_controller.rb
app/controllers/feedback_messages_controller.rb
app/helpers/rate_limit_checker_helper.rb
app/models/site_config.rb
app/models/user.rb
app/services/rate_limit_checker.rb
spec/requests/feedback_messages_spec.rb
spec/services/rate_limit_checker_spec.rb

Rate limit number of abuse reports a user can create in a 5 minute period. This PR applies the limit to both logged-in and not logged-in users by adding an additional IP option for making the cache keys in our RateLimitChecker.  I think this will be a huge benefit as rate-limiting is most important for those not logged in.

Rate Limit Feedback Message Creation By User ID or IP

---

app/controllers/internal/articles_controller.rb
app/models/article.rb
app/views/articles/show.html.erb

- removed code related to `articles.live_now`
- added `articles.live_now` to ignored columns
#7822

Ignore articles.live_now column

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

Since merging #7834 we may no longer have an API token when an Oauth user uses the API to update or create Articles. With that API key our current throttling will no longer work.  This updates the API write throttle to us IP address like the rest of the throttles. 
On my TODO list I want to extract the fastly env variable and make it configurable so in the future, a community doesn't need a fastly client IP to rate limit.

Track and Limit API writes by IP Address + Rack Attack Refactor 

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

Was going to throw this back in, in my other PR but since that was all approved I decided to push it out as is and make a separate one for this. 
I think we should still be tracking user API keys in Honeycomb. The reason is that we have no way of linking an IP to a user and I could see a case where we have a valid good-intentioned user struggling with rate limits and we might want to proactively reach out to them. Having the API key in the requests would allow us to do that.

Add Back Tracking API-keys in Honeycomb

---

config/initializers/rack/attack.rb

Return from the throttle block [apparently causes an error locally](https://github.com/thepracticaldev/dev.to/commit/8ae486a362131fb8f6f7320bf85848511d28b2b7#r39188524)
```
08:11:38 web.1       | LocalJumpError (unexpected return)
08:11:38 web.1       | LocalJumpError (unexpected return)
08:11:38 web.1       |
```
Not sure why but this fixes it.

Return if there is no ip_address from Method

---

app/models/api_secret.rb
spec/models/api_secret_spec.rb
spec/queries/internal/moderators_query_spec.rb

Prevent users from creating an unlimited number of API keys by capping it at 20. I checked the database and one user has 103 but it is a pentester. I will clean those up before this goes out. The most valid keys I found on a user was 4. The VAST majority have only 1. I figured 20 was plenty for anyone to have.
My first run hit a flaky spec where we got users in the wrong order so I threw in a fix for that.

Limit the Number of API Keys a User Can Have

---

app/helpers/application_helper.rb
app/javascript/src/components/ItemList/ItemListItem.jsx
app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListItem.test.jsx.snap
app/views/articles/show.html.erb
app/views/dashboards/_dashboard_article.html.erb
spec/helpers/application_helper_spec.rb

This PR sanitizes and decodes html entities in article title
Closes https://github.com/thepracticaldev/dev.to/issues/7175
HTML entities are now rendered properly in the article title

Sanitizing and rendering html entities in article title

---

db/migrate/20200515085746_remove_articles_live_now.rb
db/schema.rb

Removed `articles.live_now` column ignored in #7846 
#7846

Removed articles.live_now column

---

docs/api_v0.yml

Oauth with an insufficient scope will receive 403 instead of 401. Updating the docs to reflect that.
https://github.com/thepracticaldev/dev.to/pull/7834
n/a
n/a

Add 403 to API docs

---

app/models/response_template.rb
spec/models/response_template_spec.rb

Limit the number of templates a user can make to 30 unless they are a trusted user. I choose to exclude trusted users since many of those are mods who might need more templates. As it stands the user with the most templates(who is a mod actually) has 19. I figured a normal user would likely have much less and figured 30 was more than enough to cover them

Limit Response Template Count for Users

---

app/controllers/follows_controller.rb

When we update a follow we [automatically touch the follower](https://github.com/thepracticaldev/dev.to/blob/master/app/models/follow.rb#L32) which in the case of the controller is always going to be `current_user` so this touch is redundant.

Don't Touch User Twice for New Follow

---

app/models/article.rb

Removed `self.ignored_columns` from `Article` as the related column was removed already.

Removed ignored_columns from articles

---

app/controllers/internal/classified_listings_controller.rb
spec/requests/internal/classified_listings_spec.rb

While looking into cleaning up some more things related to classified listings, I realized that the internal filtering by category was broken since one of the last refactors. This PR fixes that and also upated the specs a bit.
n/a

Fix internal category filtering for listings

---

db/migrate/20200514212601_add_public_reactions_count_columns.rb
db/schema.rb

This adds the `public_reactions_count` columns to the articles and comments tables. This column will be replacing the `positive_reactions_count` columns soon.
https://github.com/thepracticaldev/dev.to/pull/7777#issuecomment-628165795
Make sure to `[deploy]` this and to ensure that the migration is successful.

Add public reactions count columns

---

app/helpers/rate_limit_checker_helper.rb
app/models/site_config.rb
app/models/user.rb
app/services/rate_limit_checker.rb
spec/models/user_spec.rb

Limit the number of times a user can update themselves and make it configurable. Default to 5 times in 30 seconds

Limit User Updates

---

lib/tasks/search.rake

When the database is dropped in development also drop Elasticsearch

Drop Elasticsearch Indexes When Database is Dropped in Development

---

app/services/articles/feed.rb

The `count` will actually issue a database query for every iteration. Instead lets count in the database once then store the count in a variable and use that.

One Liner: Only Count Hot Stories Once Rather Than Every Iteration

---

app/javascript/onboarding/components/FollowUsers.jsx

Fixes incorrect pluralization when only one user is suggested in the `FollowUsers` component of onboarding.
N/A.
N/A

Fix pluralization in FollowUsers component

---

app/models/user.rb

I noticed this accidentally as users are rightly deleted with `Users::DeleteWorker` both in the frontend and the backend. If you try to delete manually a user in the console with `user.destroy`, `empty_dm_channels.destroy_all` will fail as it's an array, not an ActiveRecord relation.
That got me thinking and I realized this is not needed nor activated normally, as direct message channels are deleted already in 
https://github.com/thepracticaldev/dev.to/blob/decae056f10fe9740769d3154fde08c8794347c8/app/services/users/delete_activity.rb#L49
which calls
https://github.com/thepracticaldev/dev.to/blob/decae056f10fe9740769d3154fde08c8794347c8/app/services/users/cleanup_chat_channels.rb#L4-L6

Remove User#destroy_empty_dm_channels callback

---

app/controllers/application_controller.rb
app/controllers/stripe_active_cards_controller.rb

Saving a user here seems to be completely unnecessary so I am removing it. When we save a user we kick off a bunch of background jobs that waste resources so we should avoid saving them when we don't need to. 
I thought maybe the reason for this was cache-busting but we do that all async so it wouldn't even matter.

Remove Unnecessary User Touch From Stripe Controller

---

app/controllers/buffer_updates_controller.rb
app/labor/bufferizer.rb
app/models/buffer_update.rb
app/models/site_config.rb
app/views/articles/_actions.html.erb
app/views/internal/configs/show.html.erb
spec/labor/bufferizer_spec.rb
spec/requests/buffer_updates_spec.rb
spec/requests/internal/configs_spec.rb

In [this PR](https://github.com/thepracticaldev/dev.to/pull/7573/commits) the twitter hashtag site config variable was added. The next step was to replace all hardcoded #DEVCommunity references with w/ the dynamic `SiteConfig.twitter_hashtag` variable set to "DevCommunity" in `site_config.rb`. Tests were also updated to reflect the dynamic addition.
This PR is in direct relation to [this issue](https://github.com/thepracticaldev/dev.to/issues/7835#event-3340045458)

replace hardcoded twitter hashtag

---

jest.config.js

We have code climate that will complain about code coverage dropping already, but this only runs on CI. This adds [thresholds](https://jestjs.io/docs/en/configuration#coveragethreshold-object) for lines, branches, functions, and statements when jest runs.
Our coverage in the frontend is improving, so let's keep it that way. 😉

Added coverage threshold to jest configuration.

---

app/controllers/reactions_controller.rb
app/labor/reading_list.rb
app/models/reaction.rb
spec/models/reaction_spec.rb

We update users A LOT. We also use `user.updated_at` in a few of our reaction cache keys which is why we have to touch the user after we create and destroy a reaction. However, the majority of the time we update a user we probably don't need to be busting our reaction keys. This switches the reaction based cache keys to use `user.reactions_count` rather than updated_at. Because reaction_counts are updated automatically every time a reaction is created or destroyed there is no longer a need to touch a user to update `updated_at`. This should save us quite a bit of work when creating and destroying reactions.
**TL;DR: I removed a callback!!!! 🙌**

Use User reactions_count for Reaction Cache Keys

---

config/fastly/snippets/safe_params_list.vcl

In the past, we've had issues trying to add Array parameters so the safe list in our VCL snippets in Fastly. This PR demonstrates an updated `safe_params_list.vcl` to work with Array params.
~**Next steps:** if we want to refactor this VCL, just let me know! We can go about it a few ways:~
~- Comment the params that need to be added if we remove the entire guard of `/search` and `/bulk_show` endpoints and I'll add them in and mark this ready for review.~
~- A contributor pulls this PR down and updates the list themself.~
~- Do nothing, I'll close this out and we'll have it for future reference.~
~_I'm leaving this as draft for now as it is a demonstration and not ready to be merged._~
You can see how the updates snippet works on this [Fastly …

Update safe params VCL for Array params

---

app/controllers/reactions_controller.rb
app/models/reaction.rb

We only use the `count_for_reactable` cache key in one place in our codebase and that is for Articles. Since we don't do it for anything else skip deleting cache keys that don't exist if the reactable type is not Article. This will save us some Redis hits. 
I also increased the expiration on the reaction count cache key bc we are explicitly clearing it when we need to so we can have a longer expiration.

Only Remove Article Reaction Count Cache Keys

---

app/controllers/internal/configs_controller.rb
app/controllers/stories_controller.rb
app/models/site_config.rb
app/views/articles/_sidebar_campaign.html.erb
app/views/internal/configs/show.html.erb
spec/requests/stories_index_spec.rb

This features adds a `campaign_url` config which makes the sidebar image clickable...which was acutely pointed out by @maestromac as the expected behavior.
This image should link to the appropriate page for the campaign (in this case we can use the announcement post)

Add campaign url for sidebar link

---

app/services/rate_limit_checker.rb
spec/requests/image_uploads_spec.rb
spec/services/rate_limit_checker_spec.rb

We have been seeing the below warnings in our specs for Rails 6
```
Using a different value for the raw option when reading and writing to a cache key is deprecated for :redis_cache_store and Rails 6.0 will stop automatically detecting the format when reading to avoid marshal loading untrusted raw strings. 
```
this implements the `:raw` option to fix this warning
Rack attack warnings still remain, there is a PR issued for that gem to fix those https://github.com/kickstarter/rack-attack/pull/482 I reviewed it so I should be notified when its merged and can update our gem accordingly 
https://github.com/thepracticaldev/dev.to/projects/9#card-38461033

Use raw Option When Incrementing Redis Keys

---

app/javascript/netlify.toml

Use `npm` instead of `yarn` since using `yarn` will require a `yarn.lock` file in `app/javascript`, which seems unnecessary.

Use npm for deploying Storybook

---

app/javascript/Search/__stories__/SearchForm.stories.jsx

A Storybook story for the `<SearchForm />` component showing off our lovely focus styles.

Added a search form Storybook story where the search is focused

---

app/views/service_worker/index.js.erb

`/new` foregoes the top bar via #7524. So we don't want to load the shell.
There are maybe other ways we could do this ideally but this is quick and easy enough I think.

Remove /new from serviceworkers

---

app/models/user.rb

Here we cache an AR relationship(which we should never do) and that cache has pro membership in the scope so we need to keep it in the user model til the cache expires.
```ruby
Rails.cache.fetch("classic-article-for-tag-#{tag_name}}", expires_in: 90.minutes) do
Article.published.cached_tagged_with(tag_name).
includes(:user).
limited_column_select.
where(featured: true).
where("positive_reactions_count > ?", MIN_REACTION_COUNT).
where("published_at > ?", 10.months.ago).
order(Arel.sql("RANDOM()"))
end
```

Keep Pro Membership Relation Until AR Cache's expire

---

app/models/pro_membership.rb

Description
Followup to #7986 we need the model class for our delete associations to work 
Fixes: https://travis-ci.com/github/thepracticaldev/dev.to/builds/167491034

Add back ProMembership AR class

---

spec/services/users/delete_spec.rb

pro memberships cannot be accurately created in this spec without a bunch of the old validations and constraints which leads to invalid records and the spec fails. This skips that association and I validated the spec passes

Skip pro memberships for spec

---

spec/system/articles/user_visits_articles_by_timeframe_spec.rb

There doesn't seem to be enough of a difference between these snapshots, and, for some reason, the date does not seem to be freezing for some of the data captured within them. Since we already have a snapshot of this page, we don't need so many versions of it.
NOTE: This will also save us some $$$! 🤑

Remove some superfluous Percy snapshots

---

app/models/pro_membership.rb
app/models/user.rb
spec/services/users/delete_spec.rb

Followup to #7894. When I initially deployed the original PR it broke some pages bc we had ActiveRecord relations with the old membership cached. This forced me to add back the relation to ensure that the cache loaded would not break anything. The cache that broke(shown below) expires in 90 minutes so since the Pro model without the code has been out for more than 90 minutes we can merge this.  
```ruby
Rails.cache.fetch("classic-article-for-tag-#{tag_name}}", expires_in: 90.minutes) do
Article.published.cached_tagged_with(tag_name).
includes(:user).
limited_column_select.
where(featured: true).
where("positive_reactions_count > ?", MIN_REACTION_COUNT).
where("published_at > ?", 10.months.ago).
order(Arel.sql("RANDOM()"))
end
```

Remove ProMembership Models

---

db/migrate/20200520091835_add_unique_index_to_webhook_endpoints_target_url.rb
db/migrate/20200520092247_add_unique_index_to_tag_adjustments_tag_name.rb
db/migrate/20200520092613_add_unique_index_to_response_templates_content.rb
db/migrate/20200520092938_add_unique_index_to_profile_pins_pinnable_id.rb
db/migrate/20200520092951_add_unique_index_to_poll_votes_poll_id.rb
db/schema.rb

Our PostgreSQL is missing quite a few unique indexes that are only checked via Rails, with the side-effect of potentially generating slow SQL queries and leaving it open to duplicate rows if the data comes in via other sources.
I tried to group some tables that have relatively little rows. There are still quite a few, I'll send them in "parts"
> This helper validates that the attribute's value is unique right before the object gets saved. It does not create a uniqueness constraint in the database, so it may happen that two different database connections create two records with the same value for a column that you intend to be unique. To avoid that, you must create a unique index on that column in your database.
https://guides.rubyonrails.org/active_record_validations.html#uniqueness …

Add missing unique indexes - part 1

---

app/views/partnerships/_form.html.erb
app/views/partnerships/_metal_level_form.html.erb
app/views/partnerships/_not_enough_credits.html.erb
app/views/partnerships/_tag_form.html.erb
spec/requests/partnerships_spec.rb

Display existing (active) sponsorships even when an org doesn't have enough credits to buy another one. It's confusing that before the change we only showed bought sponsorships only when an org had more credits.
Along with this change:
- put tag and bronze/silver forms and information to separate partials for better understanding
- added tests for gold, devrel, media page sponsorships
There is more room for improvement after this refactoring like refactoring sponsorships views and the controller.

Fix sponsorships show page

---

app/decorators/user_decorator.rb
app/helpers/application_helper.rb
app/liquid_tags/user_tag.rb
app/models/user.rb
app/views/users/_liquid.html.erb
spec/liquid_tags/user_tag_spec.rb

There were issues rendering the liquid `UserTag` when the user in question had been deleted, as described in #6499. This PR fixes the bug.
There is now a `DELETED_USER` constant in the `ApplicationHelper` class, which is an `OpenStruct` object that can be passed into the template in case the user has been deleted. This can be referenced when there is a need to reference a deleted user.
I've also rendered links in the tag conditionally on whether the user is deleted or not.
#6499 
Tag for existing user:
Tag for deleted user:
Note: The "profile image" for the deleted user kept returning a 404 in my local environment. This wasn't a result of the changes I made.

Gracefully handle missing linked users from comments

---

lib/tasks/search.rake

Ran `rails db:reset` locally, ran into "ES index not found", figured the problem was that we drop the indexes but not re-create them after the drop. 
This works.

Fix db:reset by adding search:setup after search:destroy

---

config/fastly/snippets/safe_params_list.vcl

This reverts commit 4eba14f15008564d53470ca7dd7ca2b2c8ad0b11.
- [x ] Bug Fix
Ahoy encodes URL params and our new Fastly way of decoding messes up the URL - therefore breaking Ahoy links.
#7914
https://github.com/thepracticaldev/dev.to/issues/7982
Already tested live in Fastly

Revert "Update safe params for Array params (#7914)"

---

app/controllers/internal/configs_controller.rb
app/controllers/stories_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
spec/requests/stories_index_spec.rb

This adds a configuration for whether a "campaign" requires approval on which posts show up in sidebar.

Add config for whether campaign posts require approval

---

app/services/rss_reader/assembler.rb

`RssReader::Assembler` will only correct image src that starts with `/`. This updates it to account for src without `/`.
Resolves https://github.com/thepracticaldev/dev.to/issues/7918
n/a
n/a

Improve RssReader::Assembler's image path correction

---

spec/factories/articles.rb
spec/factories/users.rb

We need to deterministically generate data for tests tagged with `percy: true` so that our snapshots are reliably the same, each time we try to build Percy. Currently, however, we have a couple factories that do _not_ use `Faker` to do this, which means we can't deterministically generate data.
This PR ensures that we use `Faker` instead of `generate` to make sure that we don't get intermittent Percy diffs where the colors, ~usernames, or emails~ and article titles change on each build. 😢

Use Faker to generate user + article factory data

---

spec/support/initializers/ci_csv_formatter.rb

Based on the CSV upload failures in travis is looks like we are incorrectly parsing the timestamp names of files bc of the colons. Even though it looks weird, I replaced the colons with dashes to try and fix this. The reason for the timestamps is to avoid duplicates so I think its fine if its format is not "pretty"
```
artifact: /home/travis/build/thepracticaldev/dev.to/06Z.csv
err: open /home/travis/build/thepracticaldev/dev.to/06Z.csv: no such file or directory
retry: 1
DEBUG: retrying
artifact: /home/travis/build/thepracticaldev/dev.to/tmp/csvs/2020-05-22T16
err: open /home/travis/build/thepracticaldev/dev.to/tmp/csvs/2020-05-22T16: no such file or directory
retry: 2
DEBUG: retrying
artifact: /home/travis/build/thepracticaldev/dev.to/53
err: open …
```

Dont Use Colons In Timestamps For CI CSVs

---

app/models/tag_adjustment.rb
app/services/tag_adjustment_creation_service.rb
spec/models/tag_adjustment_spec.rb

Our Tags, in general, are messed up. This is a quick band-aid to allow mods to remove tags regardless of case.
_Note: when adding a tag a mod must specify the `name` of the tag and **it is case sensitive**. We can't properly address that issue until we fix the core underlying issue._
https://github.com/thepracticaldev/dev.to/issues/5325

Fix tag removal case sensitivity for mods

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/views/comments/index.html.erb

This PR makes traffic directly to a comment permalink track as an article page_view because now that we have comments in the feed, folks are more likely to jump right into a comment's view. It's a small adjustment which will help better track post popularity.

Add page view tracking to comment permalinks

---

app/assets/stylesheets/classified_listings.scss

The "Load more listings" button text is not clearly visible in dark themes.
Closes https://github.com/thepracticaldev/dev.to/issues/8047

Fix load more listings button colors

---

app/controllers/articles_controller.rb

While trying to debug some failing Sidekiq workers that were handling articles I ran into a little issue. The workers that I was looking at all had the article ID. However, controller request paths that kick off those workers use the article slug. In my case the articles were deleted so the only information I had was the ID and I was unable to match up the workers with any controller requests. This will add the article_id to the request spans so we can easily use that to help us trace the life of a request and its fallout.

Track Article IDs for Controller Requests

---

app/assets/javascripts/initializePage.js.erb
app/assets/javascripts/initializers/initializeSpecialNavigationFunctionality.js
app/assets/stylesheets/top-bar.scss
app/views/layouts/_top_bar.html.erb
app/views/moderations/index.html.erb

This ensures the "current" state for nav links is rendered when users are on the right pages.

Add current state to nav bar links properly

---

app/assets/stylesheets/components/buttons.scss

Specify `[href]` for the `focus` pseudoselector of `.crayons-btn` as I don't believe `:enabled` would work on an anchor tag.
closes #7949 
**Currently**
**PR**

feat(styling): add focus state for crayons-btn class

---

app/assets/stylesheets/comments.scss
app/assets/stylesheets/notifications.scss

Right now when you add a quote in a comment a hit preview you get this:
and if you get a comment notification which includes a quote you get this:
this fixes it to:
and

Fix blockquote styling in comments previews and notifications

---

app/controllers/stories/feeds_controller.rb
app/services/articles/feed.rb
config/field_test.yml
spec/services/articles/feed_spec.rb

The "more comment weight, randomized at end" algorithm is the most appealing according to the data, but I'm concerned that it weighs _just a bit_ too much on raw comment score as the only thing vs individual preferences. This takes comments count as an indicator but dials it back a bit. We'll see how it goes.

Add alternate comment-oriented feed algorithms

---

lib/data_update_scripts/20200518173504_update_public_reactions_count_from_positive_reactions_count.rb
lib/data_update_scripts/20200526181850_update_public_reaction_counts_again.rb

This adds a data update script to sync `article.public_reactions_count`, `article.previous_public_reactions_count`, and `comment.public_reactions_count` with positive reactions count again. This is necessary since #7926 was merged today.

Sync public reactions count with positive reactions count

---

app/services/broadcasts/welcome_notification/generator.rb
db/seeds.rb
spec/factories/broadcasts.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb

This PR adds a "download app" welcome notification, which will be sent out 7 days after a user has signed up. This particular notification prompts new users to download the DEV mobile app.
Closes #8021 
**YES: After this PR is approved, I will have to add this specific Broadcast to `/internal/broadcasts`.**

Add download_app Welcome Notification

---

spec/rails_helper.rb

Specs are currently failing due to having to freeze time for Percy but that timestamp is too far in the past so users are constantly logged out after a single action. This comments out that Percy code until we can come up with a fix for it.

Comment out Percy Code Failing Specs to Unblock Master

---

app/views/internal/broadcasts/_form.html.erb

We removed the `Onboarding` type on the `Broadcast` model [some time ago](https://github.com/thepracticaldev/dev.to/pull/7067/files), but we still show admins this type of Broadcast as an option for select when creating a broadcast. Since selecting this option will fail on the server-side, we shouldn't even show it as an option in the form :)
Related to work in https://github.com/thepracticaldev/dev.to/pull/7067.

Remove type onboarding from broadcast form options

---

app/assets/stylesheets/themes/hacker.scss

--base-50: changed to #fff unreadable text in ten X hacker theme  light-dark text making eye strain their that's why I changed to white it looks good I tested in firefox and another bug in this theme is in case of mail 
and usernames CSS properties are overriding  and that text is getting black out there Ex:-Hidden
--base-50: changed to #fff unreadable text in ten X hacker theme  light-dark text making eye strain their that's why i changed to white it looks i tested in firefox and another bug in this theme is in case of mail 
and usernames CSS properties are overriding  and that text is getting black out there Ex:-Hidden
but name and email property is overridden by something I didn't  get I tried but I am not able to find that property there I think that is overridden by some other …

--base-50: changed to #fff unreadble text in ten X hacker theme

---

app/assets/stylesheets/listings.scss
app/javascript/common-prop-types/selected-tags-prop-types.js
app/javascript/listings/__tests__/ListingFilterTags.test.jsx
app/javascript/listings/__tests__/ListingFilters.test.jsx
app/javascript/listings/__tests__/ListingFiltersCategories.test.jsx
app/javascript/listings/__tests__/SelectedTags.test.jsx
app/javascript/listings/__tests__/__snapshots__/ListingFilters.test.jsx.snap
app/javascript/listings/__tests__/__snapshots__/SelectedTags.test.jsx.snap
app/javascript/listings/components/CategoryLinks.jsx
app/javascript/listings/components/ListingFilters.jsx
app/javascript/listings/components/ListingFiltersCategories.jsx
app/javascript/listings/components/ListingFiltersTags.jsx
app/javascript/listings/components/SelectedTags.jsx

Re-doing of https://github.com/thepracticaldev/dev.to/pull/8055
Currently in production tag filters can't be removed:
This PR fixes it and adds tabbing index to the tags so they can be selected with the keyboard.
While checking for a11y issues I also noticed how `categories` were mis-rendered by using a non existent ID. I fixed that as well.

Fix broken tag filters in listings - take 2

---

jest.config.js

This issue came about due to changes made in #8088. It will only ever happen on a local dev machine if a dev builds storybook (not run it) and then run jest. jest will hang during code coverage because node runs out of memory.
#8088

Fixed issue with jest picking up the built storybook folder causing tests to run out of memory

---

app/controllers/articles_controller.rb
app/controllers/stories_controller.rb

We have two controller actions that waste a lot of resources looking up a value on multiple different tables to determine how to handle a route request. I want to know how often we hit these routes so I added some Honeycomb metrics to them to determine how "big" of a problem this actually is. 
If we hit them a ton, we should consider fixing them sooner. If it turns out they are not crazy active then I know to worry about it less.

Track How Often We Hit Ambiguous Routes

---

config/initializers/rack/attack.rb
spec/initializers/rack/attack_spec.rb

We have some applications that make use of our API for their own users. In this case, we might get a lot of requests from their single IP but with different user API keys which can cause them to hit the throttle limit. This will allow those applications to make requests on the behalf of their users without worrying about different API keys causing them to hit the limit. 
https://github.com/toddanglin/PublishToDev/issues/2

Add API Key to API Write Throttle

---

app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/shared/components/__tests__/tags.test.jsx

This makes all our frontend unit tests uniform. There were two test files that were using `test(...)` instead of `it(...)`.

made all frontend unit tests uniform by preffering it(...) over test(...)

---

app/controllers/articles_controller.rb
app/controllers/stories_controller.rb

Having different fields makes grouping these in Honeycomb difficult. Having a single field with different values makes running a simple field exists query A LOT easier.

Tweak How We Track Ambiguous Routes to Make them Easier to Track

---

.github/workflows/dependabot.yml

We need to update vendor/cache after Dependabot does it's bot duties. This GitHub Action should do the business. 
It was adopted from https://gist.github.com/filipkis/fab89a09f54ffdd8e70c063755e7ce7f which was posted to this Dependabot feedback issue: https://github.com/dependabot/feedback/issues/474#issuecomment-583741305

Update vendor/cache After Dependabot

---

.github/workflows/dependabot.yml

libcurl4-openssl-dev is not installed by default on Ubuntu 18.04.4 LTS. :tada:

Update dependabot.yml to install libcurl4-openssl-dev

---

db/seeds.rb

Yesterday @jdoss mentioned to me that from a systems engineering perspective it would be good for the `db:seed` task to be idempotent. I added a little helper for that purpose, which should also come in handy during development, since it will selectively seed new and/or missing entities.
This is what it looks like in action:
```
$ rails db:seed
Seeding with multiplication factor: 1
1. Creating Organizations.
2. Users already exist. Skipping.
3. Tags already exist. Skipping.
4. Creating 25 Articles.
5. Comments already exist. Skipping.
6. Creating Podcasts.
7. Broadcasts already exist. Skipping.
8. ChatChannels already exist. Skipping.
9. Creating HtmlVariants.
10. Badges already exist. Skipping.
11. FeedbackMessages already exist. Skipping.
12. ListingCategories already exist. Skipping. …
```

Make db:seed idempotent

---

app/controllers/async_info_controller.rb
app/javascript/packs/readingList.jsx

base_data in our AsyncInfo Controller is above and beyond our most hit route(see purple line on the graph below) so it should be as lean and mean as possible. I noticed that we were using two calls and different methods to return tags and their names when one would suffice. I removed the tag names and added a little snippet so our javascript can parse them out itself.
CodeClimate is not a fan of removing code. It can be ignored in this case.

Optimization: Remove cached_followed_tag_names From Async User Data

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb
spec/system/user_uses_the_editor_spec.rb

As I was creating new spec to prep for tag changes. I was getting the following error (after commenting out some VCR codes) and it was leading me down the wrong path.
```ruby
Failures:
1) Using the editor using v2 editor fill out form with rich content and click publish
Got 1 failure and 1 other error:
1.1) Failure/Error: expect(page).to have_text("hello")
expected to find text "hello" in "[manually ommited]". (However, it was found 1 time using a case insensitive search.)
1.2) Failure/Error: // <---- this one
def image_path(source, options = {})
path_to_asset(source, { type: :image }.merge!(options))
end
ArgumentError:
wrong number of arguments (given 0, expected 1..2)
Finished in 17.45 seconds (files took 0.58905 seconds to load)
1 example, 1 failure
```
The error 1.1 is expected but …

Remove redundant include of CloudinaryHelper

---

app/assets/stylesheets/article-show.scss
app/views/articles/show.html.erb

This PR removes the "action-space" for non-logged-in users when it would never be present. We leave space here so if it renders for the appropriate user it doesn't cause a "jump" but it causes this weird gap for non-trusted/non-author posts...
The weird gap will still be present for logged-in non-trusted/author users, but this quick fix will help it for many users and then we can make a further adjustment to fix this in future.

Remove unnecessary "action-space" for non-signed-in users

---

spec/system/user_uses_the_editor_spec.rb

I think this test is legit failing and not flaky eh?
Publish text is now only capitalizing first character:

Change text in failing PUBLISH test

---

app/controllers/internal/broadcasts_controller.rb
app/models/broadcast.rb
app/views/internal/broadcasts/index.html.erb
spec/factories/broadcasts.rb
spec/models/broadcast_spec.rb
spec/requests/internal/broadcasts_spec.rb

In preparation for a new "site-wide messaging" feature (see https://github.com/thepracticaldev/dev.to/issues/8090), I've started cleaning up some of our admin UI around the `Broadcast` model, and adding some constraints around the Broadcasts with a `type_of: "Announcement"`, which is what we'll use for our site-wide messaging service.
This PR does the following:
Closes #8089! 🚀 
**To QA this, you will want to do the following:**
1. Check out the `/internal/broadcasts` page! You'll see an improved UI that lets you filter based on the `type_of` on the broadcast:
2. Check that you can create some inactive announcement broadcasts:
3. Check that you can set one of those announcement broadcasts to `active`, and that you see a super cute flash message:
4. Check that you CANNOT set another …

Leverage announcement broadcasts

---

app/services/broadcasts/welcome_notification/generator.rb
spec/services/broadcasts/welcome_notification/generator_spec.rb

This PR properly enqueues the `customize_feed_notification` within the `WelcomeNotification::Generator` in addition to removing an extra word from the `generator_spec.rb`. 
After a _ton_ of debugging yesterday, it is safe to say that no additional specs are needed for this addition and that the current spec will fail properly if `@notification_enqueued = true` is removed specifically from line 34 of the generator - the only place in the generator where there is a potential enqueuing-related bug. 
The potential bug is caused by the removal of `@notification_enqueued = true` for the _first_ Welcome Notification--if that line is removed, a User could potentially receive the first _and_ second Welcome Notification if the Notification is not properly enqueued, but this would only happen if …

Enqueue feed_customization_notification

---

app/controllers/async_info_controller.rb

These ids are 100% not used anywhere in the codebase so no need for them here.

Optimization:Remove followed_organization_ids from Async user_data

---

app/models/site_config.rb
lib/tasks/app_initializer.rake

Every new community that is spun up with have a randomly generated health_check_token.
https://github.com/thepracticaldev/dev.to/projects/9#card-39168517

Generate Random Health Check Tokens on App Setup

---

app/controllers/async_info_controller.rb
app/labor/email_logic.rb
app/models/user.rb

There are a couple of optimizations being made in this PR.
1) I removed fields that do not appear to be used in the view anywhere from the user_data hash
2) `user.config_body_class` calls `user.trusted` so I updated the trusted method to memoize the trusted value so we dont have to hit the cache twice.
3) While searching around the codebase I found in our email logic file we were looking up 2 sets of cached IDs when technically if the first returns values there is no reason to lookup the second.

Optimization: Remove Unused Fields From Async user_data

---

db/seeds.rb

This PR fixes the error which was raised while seeding the database during the initial project setup.
Fixes #8191

Fix database seeding issue (#8191)

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/controllers/async_info_controller.rb
app/javascript/chat/__tests__/util.test.js

We include a user's comment count in our async user_data hash bc we were using it to validate if the code of conduct had been signed. I am assuming there was some sort of bug in the past but its hard to tell bc [some of the code appears to just be slapped in during this PR](https://github.com/thepracticaldev/dev.to/pull/885) with little explanation besides the comment. I did a lot of testing signing in and out, destroying and resigning up with my user and commenting on things and I never once got served the code of conduct twice so I think our user_data hash is updating correctly and therefore this check is no longer needed.

Optimization: Remove Comment Count From Aysnc user_data

---

db/migrate/20200530084533_add_timestamps_to_broadcasts.rb
db/schema.rb
lib/data_update_scripts/20200530085153_backfill_broadcasts_timestamps.rb

@vaidehijoshi found out that the `broadcasts` table doesn't have the two timestamps (`created_at` and `updated_at`).
As the table is already populated, I need to do this in two steps.
https://github.com/thepracticaldev/dev.to/pull/8150#discussion_r432565867

Add timestamps to broadcasts

---

app/services/github/oauth_client.rb

We're experiencing some timeout issues with getting repos from GitHub API v3.
AFAIK nothing changed in the code recently but as the timeout is 5 seconds, I'm finding it hard to figure out exactl what's going on. 
Temporarily raising the timeout to the Heroku limit, to see if we can get the actual error in the request.
See https://github.com/lostisland/faraday/blob/90b4564cecde7fd35b7d752fc84a785b89efd9e2/lib/faraday/adapter.rb#L91-L114

Temporarily raise read_timeout of Github::OauthClient

---

app/controllers/internal/users_controller.rb
app/services/moderator/merge_user.rb
spec/services/moderator/merge_user_spec.rb

We recently merged two accounts on a user's request, but badges did not show up on the new account. Trying to reassign them also did not work. I did some digging and found the following:
1. The badges had been moved over and assigned to the new user correctly. This is why they couldn't be reassigned. 
2. In `app/views/articles/_badges_area.html.erb` we perform the following conditional check:
```ruby
if @user.badge_achievements_count > 0 
````
3. I checked, and the `badge_achievements_count` for the new user was indeed 0. 
I then had a look at `Moderator::MergeUser` and fixed the count update logic during merges. The newly added spec fails with the old code and succeeds with this change.
https://github.com/thepracticaldev/tech-private/issues/445#issuecomment-636615311

Fix badge count update after merge

---

app/controllers/api/v0/health_checks_controller.rb
config/routes.rb
spec/requests/api/v0/health_checks_spec.rb

This adds a health check endpoint for all of our Redis instances. In this case, I labeled the endpoint "cache" since who knows if we will always use Redis or not.

Add Health Check Endpoint for Cache

---

spec/requests/api/v0/health_checks_spec.rb

I seemed to have broken some specs when the REDIS_URL ENV variable gets set. Since we need at least one redis URL I changed it to the session one.

Set Redis URL that will not be reused in specs

---

app/helpers/application_helper.rb

In a recent alteration of cloudinary logic we have landed in a place where the default is "jpg" when it makes more sense to be "auto", as "jpg" 
Closes https://github.com/thepracticaldev/dev.to/issues/8223

Change default fetch format in cloudinary links

---

app/views/articles/_sidebar.html.erb
app/views/pages/sponsors.html.erb

Pointing potential sponsors to `/sponsorships` instead of `/partnerships` in two locations.
- Location 1, bottom of `/sponsors` page
- Location 2, "Become a sponsor" box on the homepage sidebar

Swap sponsorships link

---

app/workers/search/index_worker.rb
app/workers/search/remove_from_index_worker.rb
spec/workers/search/index_worker_spec.rb
spec/workers/search/remove_from_index_worker_spec.rb

As stated in the comment, we seem to run into a few race conditions where comments are created and destroyed before the Sidekiq workers ever get a chance to index them. Since we have checks every hour to ensure that our db counts match our Elasticsearch counts I think we can safely ignore these missing records and docs and rely on our counts to alert us if there is a problem. 
Failed spec is unrelated, pushing a fix for it: https://github.com/thepracticaldev/dev.to/pull/8227

Ignore Unfound Elasticsearch Docs and Records

---

app/controllers/api/v0/health_checks_controller.rb
spec/requests/api/v0/health_checks_spec.rb

This change allows access to api/health_checks if you are coming from localhost or 127.0.0.1. Pretty sweet huh?
The reason for this change is because I want to easily get to these healthcheck
end points from localhost without having to get the health-check-token beforehand.
Buttttt.... this addition has some issues. You can spoof the host header pretty
easily:
https://daniel.haxx.se/blog/2018/04/05/curl-another-host/
I thought about doing `return if !request.ssl? && request.local?`
to check of the request was over https or not. Any localhost healthcheck we do
directly to puma will be over http. Checking for TLS seemed like a logical next
check, but since we force https on the edge and not necessarily from the edge to
Puma the Host header can still be spoofed to get at these end points. …

Allow localhost or 127.0.0.1 to access api/health_checks without health-check-token

---

spec/system/articles/user_visits_article_stats_spec.rb

Fixes this flaky spec:
```
1) Viewing an article stats shows stats for pro users by clicking on the stats button
Failure/Error: user.add_role(:pro)
ActiveRecord::RecordNotFound:
Couldn't find all Roles with 'id': (512, 514) (found 1 results, but was looking for 2). Couldn't find Role with id 512.
[Screenshot]: tmp/screenshots/r_spec_example_groups_viewing_an_article_stats_shows_stats_for_pro_users_by_clicking_on_the_stats_button_602_2020-06-02T15:-02-53-436Z.png
```

Flaky Spec Fix: Stub pro? on user instead of using real role

---

db/migrate/20200601121243_add_unique_indexes_to_comments_body_markdown_user_id_ancestry_commentable.rb

Migration failed but actually created the index so the retry failed bc the index already exists. This adds a check for the index before adding or removing it.

Add If Statements to Skip Migrations If Index Exists

---

.rubocop_todo.yml
app/models/broadcast.rb
db/schema.rb
spec/models/broadcast_spec.rb
spec/requests/internal/broadcasts_spec.rb

This PR enforces uniqueness on a Broadcast titles, scoped specifically to `type_of` (announcement or welcome), and renders an appropriate error message to an Admin that tries to create a Broadcast with the same title as another Broadcast of the same `type_of`.
Closes #8070 
When attempting to add a Broadcast of the same `type`, with the same `title`:
Also note the successful scoping of Broadcasts with the same `title`, but with different `type_of`s.
Heads-Up Team SRE (@mstruve and @maestromac): I have double-checked that there are no duplicate Broadcast titles, so this should be safe to add and should not cause any uniqueness-related errors when running the migration. :crossed_fingers:

Enforce Uniqueness for Broadcast Titles

---

.travis.yml

Rather than wasting up to 3+ minutes installing gems during a Travis run, lets use the ones we have cached in our vendor/cache file by setting the `--local` flag. I also added [`--jobs 2`](https://bundler.io/bundle_install.html) which allows us to use 2 workers in parallel to load the gems.

CI Speed Up: Use Gems in Vendor Cache for Travis

---

app/assets/config/manifest.js
app/assets/xml/search.xml.erb
app/views/shell/_top.html.erb
config/initializers/assets.rb
public/search.xml

This PR generalizes our [OpenSearch specification](https://developer.mozilla.org/en-US/docs/Web/OpenSearch). The file moved from `dev.to/search.xml` to `dev.to/assets/search.xml` but this should matter since I updated the `link` accordingly. Firefox still recognizes the search engine:
Closes #8247

Generalize search.xml

---

config/routes.rb

Attempts to fix issues using the feature flag UI in production. 
What's going on?
Right now in production, attempting to create a feature flag results in a `403 Forbidden`. There's something happening with Rack, our sessions, authenticity tokens, and the way we're mounting the FlipperUI within our Rails application. This feature works just fine in development!
@mstruve solved this similar issue with the Sidekiq UI in PR #5634. I'm trying to do something similar based on the advice in this issue on the Flipper repo: https://github.com/jnunemaker/flipper/issues/99#issuecomment-533216544 (note many of the comment there are talking about modifying Nginx proxies, which I don't think we are using in production, but I'm not sure!)
[](https://github.com/thepracticaldev/dev.to/pull/5634/) …

Attempt to fix rack protection issue with flipper UI

---

app/controllers/stories_controller.rb
app/views/service_worker/manifest.json.erb
spec/requests/articles/articles_show_spec.rb

The [cloudinary helper](https://github.com/fdoxyz/dev.to/blob/master/app/helpers/application_helper.rb#L77) method has 1 required parameter (url) and 3 optional parameters (width, quality & format). 
Since these are positional params (not [keyword arguments](https://thoughtbot.com/blog/ruby-2-keyword-arguments)) if we want to specify the **format** (4th param) we must also pass in all 3 other params, otherwise there will be a mismatch in them which was causing this bug.
To see this in action check out the `manifest.json` from production and all 3 images have wrong arguments passed in to Cloudinary, which causes this error:
With this fix the URLs generated now have the following valid params: `c_limit,f_png,fl_progressive,q_80,w_192`
This error surfaced because of #8158 which mentioned PWA …

Fixes Cloudinary helper calls that specify custom format

---

app/controllers/internal/broadcasts_controller.rb
app/views/internal/broadcasts/edit.html.erb
config/routes.rb
spec/requests/internal/broadcasts_spec.rb

This PR allows Admins to delete Broadcasts from `/internal/broadcasts`. In addition to this, this PR adds appropriate flash messages when deleting a broadcast and adds a "Destroy Broadcast" button to the `/internal/broadcasts/edit` UI.
Closes #8068 
**Destroy Button:**
**Confirmation Message Shown After Clicking "Destroy Broadcast":**
**Deletion Confirmation:**

Allow Admins to Delete Broadcasts

---

app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/articles/search.html.erb
app/views/internal/configs/show.html.erb
spec/requests/internal/configs_spec.rb

Earlier, I went to go look up one of our posted jobs at DEV. I typed "dev.to jobs" into Chrome and it landed me on dev.to's search page with the search query "jobs" which wasn't quite what I was going for. I wondered how many others might be looking for jobs AT DEV and end up where I did so I brought it up in #hiring and we can up with this little fix. Thanks @ludwiczakpawel for the design and Gracie for the copy. 
We have the ability to turn this on or off using SiteConfig.

Display Jobs Banner if User searches jobs or job

---

app/controllers/api/v0/articles_controller.rb
app/controllers/api_secrets_controller.rb
app/controllers/chat_channels_controller.rb
app/controllers/comments_controller.rb
app/controllers/internal/reactions_controller.rb
app/controllers/internal/response_templates_controller.rb
app/controllers/internal/sponsorships_controller.rb
app/controllers/omniauth_callbacks_controller.rb
app/controllers/reactions_controller.rb
app/controllers/response_templates_controller.rb
app/controllers/user_blocks_controller.rb
app/models/application_record.rb

I've been advocating the use of `errors.full_messages.to_sentence` over `errors.full_messages.join(' ')` for a while now. We're now using it in more places, so I added `ApplicationRecord#errors_as_sentence` to cut down on typing. I updated all existing usages that made sense and also replaced a few more manual `.join(' ')` calls.
n/a

Add ApplicationRecord#errors_as_sentence

---

app/controllers/reactions_controller.rb

Fixes: https://app.honeybadger.io/projects/66984/faults/64426845 which was caused by caching ActiveRecord objects that are not compatible with Rails 6. This changes the cache key so we start fresh. YES it is on my todo list to remove all of the AR object caching, I just haven't gotten to it yet. https://github.com/thepracticaldev/dev.to/projects/9#card-39519016

Bug Fix: Change Cache Key to Bust Cache

---

app/views/articles/search.html.erb

Apparently there are ways to get to the search page without running a query. This ensures we dont break when that happens. 
Fixes: https://app.honeybadger.io/fault/66984/7384a8699e342e581a79a069e69148d0
```
NoMethodError: undefined method `downcase' for nil:NilClass
search.html.erb  12 _app_views_articles_search_html_erb(...)
[PROJECT_ROOT]/app/views/articles/search.html.erb:12:in `_app_views_articles_search_html_erb'
10   <%= render "articles/search/sidebar" %>
11   <div class="articles-list" id="articles-list">
12     <% if (params[:q].downcase == "job" || params[:q].downcase == "jobs") && SiteConfig.display_jobs_banner %>
13       <div class="crayons-notice crayons-notice--info mb-3 fs-base">Interested in joining our team? Explore our <a href=<%= SiteConfig.jobs_url %>>open …
```

Bug Fix: Add Safety Operator When Handling params[:q]

---

.travis.yml

The addition of this line seems to be preventing bundler from using `vendor/cache` and causing it to install all of the gems for new builds so I removed it. These lines were added in our Rails 6 PR #7658 but based [on the comment](https://github.com/thepracticaldev/dev.to/pull/7658/files#r432139357) and the fact that the specs run green I dont think we need it.

Remove Explict Gemfile from travis.yml to Allow vendor/cache to be used

---

.rubocop_todo.yml
db/migrate/20200604133925_add_unique_index_to_notifications_user_id_organization_id_notifiable_action.rb
db/schema.rb

Follow up to https://github.com/thepracticaldev/dev.to/pull/8215
This adds a unique index to the `notifications` table:
- `user_id organization_id notifiable_id notifiable_type action`
**pre-deployment**
we need to check if we have duplicates
```sql
select user_id, organization_id, notifiable_id, notifiable_type, action, count(*)
from notifications
group by user_id, organization_id, notifiable_id, notifiable_type, action
having count(*) > 1
```

Add missing unique indexes to notifications

---

spec/rails_helper.rb

I did some digging into Percy and found that even when we are not running the agent, [`Percy.snapshot` will still attempt to make a request to the agent every time it is called.](https://github.com/percy/percy-capybara/blob/ffe355ef3e2c5544c9a1215eb03d463ada5cc450/lib/percy.rb#L109) which can waste time. It's not a ton but its something. This stubs that request and eliminates the HTTP call. 
What do you all think? Honestly, I want to remove it to try and simplify our spec suite as I try and make the leap to parallel builds but I also didn't want to shut this all down completely if we want to use it in the future. 
Requests being made during a build

Stub Percy.snapshot During Specs

---

app/views/articles/show.html.erb

When debugging, I found that the `beforeWrite` function is sometimes called with the wrong text, causing the bug. The `context` variable seems to be correct, which I think rules out my solution and seems to point to a bug in postscribe itself. Or maybe it should only be called once at a time?
Sending this as an attempt to fix the gist ordering bug (think of it as a place for discussion). I haven't confirmed the fix works (probably not!), since I don't have time to set up the dev environment this weekend, but, looking at the code, this seems like a mistake that could cause it.
I made a small script to reproduce something similar:
```javascript
function randomInt(min, max) {
return min + Math.floor((max - min) * Math.random());
}
function makeRequest() {
return new Promise((resolve) => { …
```

Fix gists sometimes rendered in wrong order (attempt)

---

config/initializers/acts_as_taggable_on.rb

This is a nice default to have. Instead of relying on sql's `LIKE` during tag find_or_create to pick up a bad tag, it will be case strict.
https://github.com/thepracticaldev/dev.to/pull/8175
n/a
n/a

Enable ActsAsTaggableOn.strict_case_match

---

spec/requests/sitemaps_spec.rb
spec/requests/user_blocks_spec.rb

* User block spec: Ensure the id we are using is going to be missing
* Sitemap: Don't rely on a randomly picked datetime (essentially what we get with random Time zone setting) and ensure dates will always be within the month we want. 
Running builds in parallel is totally awesome and fast but it has really exposed some of our flaky specs. Rather than throwing them all in the parallel build PR I want to spread them out in small PRs. This should also help our current build!

Flaky Spec Fixes: User Block and Sitemap Specs

---

Envfile
app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
config/initializers/devise.rb
spec/requests/internal/configs_spec.rb

Our `Devise.mailer_sender` was hardcoded to `dev.to <yo@dev.to>`. This PR changes it to `#{ENV["COMMUNITY_NAME"]} <#{ENV["DEFAULT_EMAIL"]}>` (so `DEV <yo@dev.to>`) as a first attempt at generalizing this. There's more we could do here, but unless we have a comprehensive strategy around `SiteConfig`, default values, etc. this seems sufficient.
Closes #8245 
* Set the `DEFAULT_EMAIL` env variable to `yo@dev.to`. Other communities need to do this as well.

Make Devise.mailer_sender configurable

---

spec/services/bulk_sql_delete_spec.rb

In my Knapsack branch this spec would fail about 50% of the time bc the count of Notifications did not change after the delete was wrong. I think it might be something to so with the way the expect block executes and the SQL statement possibly getting rolledback due to database cleaning before the assertion. Changing it to be explicit like this seems to have fixed the problem. I would get this spec to fail almost every run before and with this change it has yet to fail after 4 runs. 
Failed specs are our internal flaky ones, unrelated to this change.

Flaky Spec Fix: Bulk Delete SQL Spec

---

app/models/role.rb
spec/models/role_spec.rb

When we validate a role we check to make sure it is included in our list of `Role::ROLES` which lists the names of all the roles we have. One of the things we are doing to fix our spec suite is ensure roles are correctly added during tests. This uncovered the fact that this was a role we could not successfully add bc it was not valid. This fixes that.

Make Video Permission a Valid Role

---

config/initializers/docker.rb

Rails [web-console](https://github.com/rails/web-console) officially uses the `.permissions` settings instead of the deprecated `.whitelisted_ips`. I've updated the code to follow suit.
See https://github.com/rails/web-console#configweb_consolepermissions

Replace whitelisted_ips with permissions in Docker init

---

app/models/role.rb
app/services/moderator/manage_activity_and_roles.rb
spec/factories/users.rb
spec/models/role_spec.rb
spec/requests/api/v0/videos_spec.rb
spec/requests/videos_spec.rb
spec/system/internal/admin_bans_or_warns_user_spec.rb

We are not using the video_permissions role that is referenced in our codebase so this removes it and replaces it with the actual video authorization method which is ensuring the user was created more than 2 weeks ago. 
Spec Failure is a flaky one 
@snackattas

Remove video_permissions Role Reference From Specs and Code

---

app/assets/stylesheets/components/stories.scss
app/services/search/feed_content.rb

Issue #8238 is caused by the non-breaking space (`&nbsp`). See below.
To reproduce the issue on production server, follow the directions:
- Search: https://dev.to/search?q=project%20ideas
- Scroll down till article below shows up (should be around 20th-25th result).
I originally thought about 3 ways to solve this issue.
If we want to change it client side, we need to do something on line 221 [here](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/utilities/buildArticleHTML.js#L221) where we just replace `&nbsp` with `" "`. 
```js
// something like this
bodyTextSnippet =
startingEllipsis + article.highlight.body_text.map(x=>x.replace(/&nbsp;/g, " ")).join('...') + '…';
```
If we want to change it server side, it really depends on how downstream or upstream we …

Fix text out of bounds in Search results feed

---

spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb
spec/system/homepage/user_visits_homepage_spec.rb
spec/system/user/view_user_index_spec.rb
spec/system/user_uses_the_editor_spec.rb

We have a few specs that were just being used to take Percy snapshots. When we run these specs we still have to execute all the before actions and possibly setup data. This marks those specs on pending so we dont waste time executing them when they will do nothing. 
Travis Failure due to flaky spec.

Spec Speed Up: Comment Out Percy Only Specs

---

app/assets/javascripts/initializePage.js
app/assets/javascripts/initializers/initializeBodyData.js
app/assets/javascripts/initializers/initializeBroadcast.js
app/assets/stylesheets/scaffolds.scss
app/controllers/async_info_controller.rb
app/views/internal/broadcasts/_form.html.erb
app/views/shell/_top.html.erb
spec/factories/broadcasts.rb
spec/requests/async_info_spec.rb
spec/system/homepage/user_visits_homepage_spec.rb

This feature allows active announcement broadcasts to be displayed, site-wide.
Specifically, this PR does the following: 
The next step in this feature will be https://github.com/thepracticaldev/dev.to/issues/8091, which will allow the user to dismiss this active announcement. But, since this feature isn't being used yet in production and it doesn't affect any users just yet, I'll be handling that in a subsequent PR.
Closes https://github.com/thepracticaldev/dev.to/issues/8090.
**TO QA THIS PR:**
1. Go to `/internal/broadcasts`, and create/update a broadcast with some html/inline css. Once you save it, you can preview the broadcast and update it to be active:
2. Go to any page on the site. You should see the broadcast displayed:
3. Try setting that same broadcast to "inactive" from the …

Display site-wide announcements

---

spec/system/articles/user_creates_an_article_spec.rb
spec/system/articles/user_deletes_an_article_spec.rb
spec/system/articles/user_edits_an_article_spec.rb
spec/system/articles/user_visits_an_article_spec.rb
spec/system/articles/user_visits_articles_by_timeframe_spec.rb
spec/system/comments/user_edits_a_comment_spec.rb
spec/system/internal/admin_awards_badges_spec.rb
spec/system/internal/admin_bans_or_warns_user_spec.rb
spec/system/internal/admin_creates_new_event_spec.rb
spec/system/internal/admin_manages_reports_spec.rb
spec/system/organization/user_updates_org_settings_spec.rb
spec/system/user/user_edits_integrations_spec.rb
spec/system/user/user_settings_response_templates_spec.rb
spec/system/user_selects_looking_for_work_spec.rb
spec/system/user_uses_the_editor_spec.rb

Find all fail! [When I did the first round of these](https://github.com/thepracticaldev/dev.to/pull/8347) I searched with tab indentation in my search string which led to me missing the vast majority of these Percy only specs. Here are the rest of them commented out.  I was also only looking for specs with a single Percy.snapshot line, however, as you can see in this PR, some specs have lines before the Percy snapshot to setup the environment. The key is that NONE of them have any additional expectations. 
Thats ok, its another excuse to put a gif of a hedgehog in a PR 😄

Spec Speedup: Comment Out More Percy Only Specs

---

app/assets/stylesheets/article-show.scss

At the moment I think the mod button is a little too in-your-face on narrow screens (typically mobile experience) in a way that could distract from reading (remember mods are readers too).
Current:
Proposed:

Shrink mod button on narrow screens

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/top-bar.scss

When following links to footnotes and back from footnotes the line with the anchor gets hidden behind the top bar. This is due to the fact that we have to offset an html anchor to adjust for fixed header.
The solution is to add something like this to the CSS:
```css
:target {
padding-top: var(--header-height);
margin-top: calc(-1 * var(--header-height));
}
```
Once we make that change, we no longer have the problem referenced at issue #7760. The header no longer covers the footnote.
The JavaScript solution was originally considered, where we listen to the `onhashchange` event. On change we want to select the dom element and use `window.scrollTo()` to scroll to the correct Y position using position data from `getboundingclientrect()`. Ultimately, the CSS solution was preferred for its …

fix footnote anchor tag misposition

---

app/assets/stylesheets/components/stories.scss

@ludwiczakpawel, oops I guess Mac already merged #8263. I was going to include a commit to address the word-break fix for the title as well. Anyways, here is a separate PR :) 
See #8263 for reference.  
Specifically your comment:
> Would you mind adding the very same fix for post titles too? (Your screenshot has an example like that)

apply word break fix to title as well

---

spec/support/elasticsearch_helpers.rb
spec/workers/metrics/record_data_counts_worker_spec.rb

Two Fixes here:
1) Since we are not clearing out Elasticsearch before running our worker spec we can't assume it is empty so I changed the expectation of 0 to any integer
2) If specs start running really fast there is a chance we try to run a delete_by_query before Elasticsearch has "refreshed" ie committed new data to disk. This causes an error so lets refresh the index before we run delete_by_query and after to ensure no data in flight errors occur.

Flaky Spec Fixes: Dont Assume No Elasticsearch Data, Refresh before delete_by_query

---

app/javascript/githubRepos/githubRepos.jsx

In an attempt to solve https://github.com/thepracticaldev/dev.to/issues/8076, https://github.com/thepracticaldev/dev.to/issues/8104 and https://github.com/thepracticaldev/dev.to/issues/8172 we need better visibility within the errors.
Currently the JS code only sets an error flag to true, eating up the errors. It also tries to render the repositories, before checking the error state.
I rewrote the fetching code of the component to use `async/await` which is infinitely easier to debug than chained callbacks and also added some error code to both log on the console and send to Honeybadger.
Hopefully we can better understand what's going on. As I can't ever reproduce it locally I'm a bit blind on this.
- https://github.com/thepracticaldev/dev.to/issues/8076
- …

Rewrite GithubRepos with async/await for better debugging

---

app/assets/stylesheets/moderators.scss
app/views/moderations/actions_panel.html.erb

Fixes the wrong text shown on Vomit Button when clicked.
Also updates some links to Mod Guides
**Previous:**
**After The Fix:**

Fix Vomit Button text bug upon click

---

db/schema.rb
db/seeds.rb

In the current `db/seeds.rb` file, while assigning roles to fake users, if the script references a non-existent role, the process blows up. Specifically, this code block:
```ruby
if i.zero?
user.add_role(:trusted)
else
user.add_role(roles[rand(0..roles.length)])
end
```
`roles.length` equals `3`; if `rand(0..roles.length)` returns `3`, the loop blows up.
I decided against just modifying to `rand(0..roles.length - 1)` because that solution won't yield any additional no-role users.
***Note: the `db/schema/rb` change is one that has been popping up on all my commits. Until now, I've been reversing it, but @rhymes says it's alright to commit the change.*** 😄

Fix bug in db/seeds that may blow up while assigning fake user roles

---

app/javascript/actionsPanel/initializeActionsPanelToggle.js
app/views/moderations/actions_panel.html.erb

While reviewing another PR I noticed, via Axe and the builtin Firefox a11y inspector, there were some quick wins to be had in terms of accessibility of the moderations panel

Improve accessibility in moderation panel

---

app/assets/javascripts/initializers/initializeBroadcast.js
app/assets/stylesheets/internal/layout.scss
app/controllers/async_info_controller.rb
app/controllers/internal/broadcasts_controller.rb
app/helpers/broadcasts_helper.rb
app/models/broadcast.rb
app/views/internal/broadcasts/_form.html.erb
app/views/internal/broadcasts/edit.html.erb
db/migrate/20200608175130_add_banner_style_to_broadcasts.rb
db/schema.rb
spec/models/broadcast_spec.rb

Closes https://github.com/thepracticaldev/dev.to/issues/8355.
**1. Go to the `/internal/broadcasts` page locally, and pick a `type_of: Announcement` broadcast that you want to activate, or is already active.**
**2. Choose a crayons banner style, or leave it blank. If blank, you should see plain old HTML represented:**
**3. If you select a banner style, you should be able to save the broadcast, and see the banner style reflected. For example, with the style of `warning`:**
**And this is with the style of `brand`:**
**4. Finally, you should see that same banner style from the crayons design system reflected when you view the active announcement throughout the site:**
This PR also fixes a UI regression on the `/internal/broadcasts/:id/edit` page:
_Before:_
_After:_
N/A

Provide default crayon styles when creating banners

---

app/javascript/article-form/articleForm.jsx
app/views/liquids/_asciinema.html.erb

1. While doing the [original PR](4152) we noticed that the Asciinema IFrames are quite small, so added a `vh50` attribute to them (`style="width:100%;height:50vh;"`).
2. The problem with hardcoding this value: every Asciinema recording has a different width and height, and the site doesn't scale them in any way to avoid legibility issues. Instead, they emit an event containing the proper size after the video is loaded.
3. The event is then handled by [this JS function](https://github.com/asciinema/asciinema-server/blob/7250aaca1cc739bf53de9c3e804dbe6a431b4ef2/app/assets/javascripts/widget.js#L71-L82) for resizing the IFrame based on an event. 
All of this is handled by their official player embed and this PR replaces the direct IFrame embed with a script tag. 
#8185
Screenshot of a …

Use official Asciinema player embed
