app/controllers/concerns/image_uploads.rb
app/controllers/image_uploads_controller.rb
app/controllers/organizations_controller.rb
app/controllers/podcasts_controller.rb
app/controllers/users_controller.rb
spec/requests/image_uploads_spec.rb
spec/requests/organizations_update_spec.rb
spec/requests/podcasts/podcast_create_spec.rb
spec/requests/user/user_organization_spec.rb
spec/requests/user/user_settings_spec.rb

Cleaning up work from #7200, we no longer need to log image data. The issues have been solved.
#7200

Remove logging of image data to Datadog

---

config/initializers/honeycomb.rb

Reverts thepracticaldev/dev.to#7833

Revert "filter/sample noisy spans"

---

spec/liquid_tags/classified_listing_tag_spec.rb
spec/liquid_tags/link_tag_spec.rb
spec/requests/articles/articles_spec.rb
spec/requests/articles/articles_update_spec.rb
spec/requests/internal/buffer_updates_spec.rb
spec/requests/internal/moderator_logs_spec.rb
spec/requests/internal/sponsorships_spec.rb
spec/system/admin/admin_dashboard_presented_spec.rb

I got a little sidetracked and found a few places where we could use
build_stubbed.

Use build_stubbed where possible

---

app/javascript/listings/__tests__/AllListings.test.jsx
app/javascript/listings/__tests__/utils.test.js
app/javascript/listings/listings.jsx

This fixes a small bug where individual listings can't be opened properly because the variable wasn't a boolean.

Return boolean value instead of undefined for listings open modal

---

docs/backend/admin.md

Add a section describing the admin panel.
Mostly making this PR to test the Netlify builds and deployments 🙃 
https://5ebd8c4b357a8a00066cba2f--devto.netlify.app/backend/admin/

Add a section about what the admin panel is

---

docs/backend/metrics.md
docs/backend/readme.md

Added some basic docs for sending metrics to DataDog as we currently do it.

Add docs for tallying timeseries metrics

---

app/controllers/concerns/classified_listings_toolkit.rb
app/controllers/internal/organizations_controller.rb
app/controllers/internal/users_controller.rb
app/models/credit.rb
spec/models/credit_spec.rb
spec/requests/internal/organizations_spec.rb
spec/requests/internal/users_manage_spec.rb
spec/requests/partnerships_spec.rb

When working through the classified listings refactorings I noticed that the credit model and related code could also use some love and this PR addresses some of that.
n/a

Credit refactoring

---

spec/requests/api/v0/webhooks_spec.rb
spec/requests/internal/negative_reactions_spec.rb
spec/support/api_analytics_shared_examples.rb

Expand webhook API request specs and some spec refactoring.
Salvaging code from https://github.com/thepracticaldev/dev.to/pull/7779
n/a
n/a

Expand webhook API request specs

---

app/javascript/articles/Article.jsx
app/javascript/articles/components/CommentListItem.jsx

ctrl+click or middle-click should trigger `_blank` in this case as it would by default if this were an anchor...

Open in new window properly on ctrl+click etc

---

package.json

When committing any frontend files, jest will now run but only the tests that are related to the file changes.

Added a lint-staged check for running only related tests to changed frontend files

---

app/controllers/application_controller.rb

In the past when we have had bad actors it takes us a bit to figure out who it is because we have to connect a bunch of dots from different monitoring services. Having this field will make it quick and easy to identify bad actors quickly and address them

Track current_user ID in Honeycomb

---

app/services/github/oauth_client.rb
spec/services/github/oauth_client_spec.rb
spec/support/fixtures/vcr_cassettes/github_client_issue_access_token.yml

Fixes https://app.honeybadger.io/fault/66984/83ac996e85dc0eb620d45ebf0af0846f

Fix Github::OauthClient access token auth

---

app/lib/honeycomb/noise_cancelling_sampler.rb

Removes `rack:` anti-DOS redis queries from the honeycomb instrumentation, as well as the repetitive views/shell controller fetches.

[instrumentation] remove additional cruft

---

docs/technical-overview/architecture.md

Fixed Typo in Docs

---

config/initializers/honeycomb.rb

Track Deploys In Honeycomb

---

app/lib/honeycomb/noise_cancelling_sampler.rb
spec/lib/honeycomb/noise_cancelling_sampler_spec.rb

Correctly use literal matches for some commands, and prefix for others.

[instrumentation] distinguish between literal vs prefix matching for sampling

---

spec/liquid_tags/comment_tag_spec.rb

Fix flaky comment tag spec: hard-code, be happy 😁

---

app/javascript/Search/__stories__/SearchForm.stories.jsx

A small bug fix for a Storybook story. Copy pasta strikes again!

Fixed  a copy pasta error in a Storybook story

---

app/javascript/netlify.toml

This adds the `netlify.toml` configuration file for our Storybook related deploys. We'll have a bit more flexibility in handling different settings, but most of all it'll make it obvious how we deploy Storybook.

Add netlify.toml for storybook

---

app/models/user.rb

Resourcify User model

---

.codeclimate.yml

This rule is pretty annoying. This now follow TSLint's guidline
n/a
n/a

Loosen CodeClimate's method-lines rule

---

app/controllers/stories_controller.rb
spec/requests/user/user_show_spec.rb

This PR refactors the existing structured data that exists in the `Stories::Controller`. In addition to the refactoring, this PR also adds inline documentation to User-related JSON-LD and a test around nonexistent keys/values within `user_show_spec.rb`.
Closes #7495

Refactor User-Specific JSON-LD in the Stories::Controller

---

.travis.yml

This PR adds Percy to Travis CI and enables the base build for our app, which you can get to by clicking through the GitHub integration link below:
1) For security purposes, we're only enabling Percy on against this repo (PRs made from branches). This means that if you fork off of our repo, branch, and PR back up, Percy **will not run**. This is not ideal, but it's the safest way to actually try our Percy without exposing secure information. We need to decide as a team whether we're all going to shift to making PRs from the main repo (which triggers Percy), or continue forking (which means we don't get to use Percy).
2) OSS contributors can _see_ our builds because [our Percy project is public](https://docs.percy.io/docs/public-projects). …

Add Percy to Travis yml

---

app/lib/constants.rb

Added merveilles.town to the list of Mastodon instances
Fixes https://github.com/thepracticaldev/dev.to/issues/7981

Add merveilles.town to list of Mastodon instances

---

app/services/suggester/articles/classic.rb

In general, we should not be catching AR objects in Redis. Redis is meant to store simple data structures, not AR relationships. The reason we dont want to do this is that then that cache key working relies on specific code and if we change that code suddenly the cache key can no longer be loaded. This changes the cache key to store ids rather than an AR relationship. I also updated the actual cache key to ensure we dont load any data that will break with the new code.
The downside to this approach is that when the cache is not present we will make 2 db requests instead of 1. I think this is a small price to pay for having a reliable simple cache. I also updated the code to use `limit` instead of `sample` which will limit the records pulled from the database rather than pulling them all …

Cache Article IDs Rather than ActiveRecord Objects

---

app/services/mentions/create_all.rb

I'm working on the issue #3583 and to understand how mentions work, I've done this refactoring. It's not a fix, it's just a preparation for me to understand how things work.
#3583

Refactor Mentions::CreateAll

---

docs/tests/code-coverage.md
docs/tests/frontend-tests.md

I added some more information to our frontend documentation. These are the things I had to figure out when I was writing frontend tests and I thought it would be helpful to add them to the documentation.

Update frontend test docs

---

config/initializers/reserved_words.rb

Add async_info to ReservedWords

---

app/assets/stylesheets/ltags/PodcastTag.scss
app/views/podcast_episodes/_liquid.html.erb

This is a quick fix for some css issues. There are some bigger things at play with how html is rendered for these in slightly different ways than in articles to tackle later, but this should help make them nicer for now.
Currently:
https://dev.to/ben/comment/pabh

Quick fix for podcast liquid tag in comments

---

app/views/users/_integrations.html.erb

When your integration with Stackbit is activated, the green checkmark is too big.
|| :no_good: | :+1: |
|-:|:-:|:-:|
|Desktop Preview| ![image](https://user-images.githubusercontent.com/14293805/82622493-458af100-9bde-11ea-87b7-a62c031c7a29.png)|![image](https://user-images.githubusercontent.com/14293805/82622671-ab777880-9bde-11ea-8b30-c559f634d5ee.png)|
|| :no_good: | :+1: |
|-:|:-:|:-:|
|Mobile Preview|![image](https://user-images.githubusercontent.com/14293805/82622845-11fc9680-9bdf-11ea-970d-e8a12ea6c825.png)|![image](https://user-images.githubusercontent.com/14293805/82622823-ff825d00-9bde-11ea-93fc-ace8ffcd75a5.png)|

Checkmark stackbit at integration

---

spec/support/initializers/ci_csv_formatter.rb

In my last PR I was removing the colons from the rows, we actually need it removed from the file names! Which I believe is what Travis is trying to parse to send to S3

Actually Replace File Name Colons, Missed a Timestamp

---

config/field_test.yml

I think the comments being in the feed is making posts with comments useful

Adjust a/b weights for feed

---

app/controllers/stories_controller.rb
app/models/html_variant.rb
app/views/articles/_actions.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/articles/show.html.erb
app/views/html_variants/_form.html.erb
app/views/html_variants/index.html.erb
spec/factories/html_variants.rb
spec/requests/html_variants_spec.rb
spec/requests/stories_show_spec.rb

The sidebar CTA is more annoying than helpful. It _does_ convert, but we've collectively decided it's hurting a bit more than helping.

Remove sidebar variant from CTA

---

.gitignore
babel.config.js
bin/webpack
bin/webpack-dev-server
config/initializers/content_security_policy.rb
config/webpack/development.js
config/webpack/production.js
config/webpack/test.js
config/webpacker.yml

As we're slowly approaching upgrading to Rails 6, I'm starting to set foundation stones in place.
This was (hopefully) an easy win.
Ran `rails webpacker:install` and merged the new configuration with the existing one.

Update webpacker configuration

---

app/models/github_issue.rb
db/migrate/20200525115740_add_unique_index_to_github_repo_url_github_id_code.rb
db/migrate/20200525120420_add_unique_index_to_data_update_script_filename.rb
db/migrate/20200525120642_add_unique_index_to_collection_slug.rb
db/migrate/20200525125611_add_unique_index_to_github_issue_url.rb
db/schema.rb
spec/requests/articles/articles_spec.rb

Follow up to https://github.com/thepracticaldev/dev.to/pull/8002
Tables:
- `collections`
- `data_update_scripts`
- `github_issues`
- `github_repos`
**pre-deployment**, we need to remove duplicated results in the following tables:
**collections**
```sql
select slug, user_id, count(*)
from collections
group by slug, user_id
having count(*) > 1
```
**github_repos**
```sql
-- duplicates by github_id_code
select github_id_code, count(*)
from github_repos
group by github_id_code
having count(*) > 1
-- duplicates by url
select url, count(*)
from github_repos
group by url
having count(*) > 1
```

Add unique indexes - part 3

---

app/models/chat_channel.rb
app/models/chat_channel_membership.rb
app/models/organization.rb
app/models/response_template.rb
db/migrate/20200526144234_add_unique_index_to_organizations_secret.rb
db/migrate/20200526145731_add_unique_index_to_chat_channel_memberships_chat_channel_id.rb
db/migrate/20200526151431_add_unique_index_to_chat_channels_slug.rb
db/migrate/20200526151807_add_unique_index_to_badge_achievements_badge_id.rb
db/schema.rb
spec/models/badge_achievement_spec.rb
spec/models/chat_channel_membership_spec.rb
spec/models/chat_channel_spec.rb
spec/models/organization_spec.rb

Follow up to https://github.com/thepracticaldev/dev.to/pull/8050
- `organizations.secret`
- `chat_channel_memberships.chat_channel_id` + `chat_channel_memberships.user_id`
- `chat_channels.slug`
- `badge_achievements.badge_id` + `badge_achievements.user_id`
**pre-deployment**, we need to remove duplicates in the following tables:
**chat channels**
```sql
select slug, count(*)
from chat_channels
group by slug
having count(*) > 1
```
**badge achievements**
```sql
select badge_id, user_id, count(*)
from badge_achievements
group by badge_id, user_id
having count(*) > 1
```

Add unique indexes - part 4

---

app/assets/javascripts/initializers/initializePodcastPlayback.js

This PR refactors the interaction with the Native Bridge for mobile apps. It reduces some `if else` logic and now both Android & iOS rely on "message based" (Pub/Sub style) which also makes it easier to read/understand. 
Meaning this type of code:
```
if (isNativeIOS()) {
// iOS code
} else if (isNativeAndroid()) {
// Android code
} else {
// Web code
}
```
now becomes this:
```
if (isNativePlayer()) {
// message to Native Player (both iOS & Android)
} else {
// Web code
}
```
Also supports some small bug fixes (see PRs linked below for details).
- [Android repo PR](https://github.com/thepracticaldev/DEV-Android/pull/75)
- [iOS repo PR](https://github.com/thepracticaldev/DEV-ios/pull/227)
I tested all three PR's and **there's no problem with merging them in any order** 🎉
The Podcast …

Podcast Player native bridge calls refactor to use message based communication

---

.gitignore
app/javascript/netlify.toml
package.json

Something changed recently on Netlify. Builds of Storybook are broken. I've made the necessary changes to fix the build/deployment of Storybook on Netlify
```
10:53:01 AM: Preparing Git Reference pull/8077/head
10:53:04 AM: Failing build: Failed to parse configuration
10:53:04 AM: Failed during stage 'Reading and parsing configuration files': 
When resolving config file /opt/build/repo/app/javascript/netlify.toml:
Configuration property build.publish must be inside the root directory.
Invalid syntax
[build]
publish = "../../storybook-static"
Valid syntax
[build]
publish = "storybook-static"
: exit status 1
10:53:04 AM: Finished processing build request in 19.983805892s
```
Here is the fixed deployment for this PR, https://deploy-preview-8088--storybookdevto.netlify.app/

Fixed configuration to build Storybook on Netlify.

---

CONTRIBUTING.md

Fix dev.to link in CONTRIBUTING.md
https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md

📗Fix dev.to link in CONTRIBUTING.md

---

.github/workflows/dependabot.yml

Removes `-no-rdoc` and `--no-ri` from the `gem install bundle`

Fix Dependabot workflow

---

app/assets/stylesheets/themes/hacker.scss

This is probably pedantic, but I believe this comment is unclear. There
is also a typo removed by this commit.
The comment got merged in with #8001, I think we should have removed it before merging, but no harm done! :)

Remove unclear comment

---

app/liquid_tags/wikipedia_tag.rb

Ruby has a slightly different meaning with `^` and `$` than other languages, the [Rails security guide](https://guides.rubyonrails.org/security.html#regular-expressions) explains that in detail. 
https://github.com/thepracticaldev/dev.to/pull/4072

Fix WikipediaTag regexp

---

app/javascript/article-form/components/Help.jsx

Small copy adjustment to simplify things.

Update copy on editor help

---

app/controllers/internal/configs_controller.rb
app/models/site_config.rb
app/views/internal/configs/show.html.erb
app/views/mailers/digest_mailer/digest_email.html.erb
app/views/mailers/notify_mailer/trusted_role_email.html.erb
app/views/mailers/notify_mailer/trusted_role_email.text.erb
spec/requests/internal/configs_spec.rb

Generalize the Digest email further.
**The Config Update**
**The Email Update**

Generalize DEV Digest

---

.dockerignore
Containerfile

Set `--disable-march-tune-native` when building sassc due to https://github.com/sass/sassc-ruby/issues/146
Installing sassc 2.2.1 with native extensions...

Set --disable-march-tune-native when building sassc.

---

lib/tasks/pages.rake

Ignore Pages rake task unless in development env. This is currently breaking deploys.

Only load Pages Rake in Development

---

docs/tests/code-coverage.md

Updating the Test Coverage docs with some information about "coverage"
None
None
None

Small update to Test Coverage docs

---

docs/tests/frontend-tests.md

Updated the node debug flag in the frontend debugging documentation from `--inspect` to `--inspect-brk` when debugging jest. Otherwise, the test will simply run and the developer will not be able to debug, even if they have a `debugger` statement in their code.

Updated docs for debugging frontend tests

---

db/migrate/20200602174329_add_unique_index_to_broadcasts.rb

Adds the migration file for #8239 😬 
Relates to PR #8239

Add Migration File to Enforce Broadcast Title Uniqueness

---

db/schema.rb
lib/tasks/app_initializer.rake

Small fix to make the `initializer` work with Rails 6

Fix app_initializer:setup for Rails 6

---

docs/backend/audit-log.md
docs/backend/readme.md

One of the DEV maintainers pointed out that our action logging mechanism
isn't documented anywhere. This add some context for that code!
(Thanks @atsmith813)

Document the usage of Audit:Logger

---

app/liquid_tags/asciinema_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/asciinema_tag_spec.rb

While working on #8185 I noticed a few things about the Asciinema tag that I wanted to change. Since these changes make sense by themselves, I didn't want to hold them back cause of my personal struggly with CSS.
Somewhat related to #8185, but doesn't close it.

Also allow Asciinema URLs, not only IDs

---

app/models/chat_channel.rb

This is needed in order to add roles specifically around this resource (e.g. `single_resource_admin`)

Resourcify ChatChannel

---

Envfile

This is no longer needed/appropriate here as we moved this to `SiteConfig` otherwise.

Remove STAFF_USER_ID from Envfile

---

docs/getting-started/syncing.md
docs/getting-started/workflow.md

Update docs to shine more light on bin/setup and bin/startup
#8249

Update docs to shine more light on bin/setup and bin/startup

---

app/labor/badge_rewarder.rb

I was looking at our `BadgeRewarder` in the context of generalization and while doing so noticed that there are some low hanging fruits for making the code a bit nicer, i.e. using our new `URL` helper module. etc.
n/a

Clean up BadgeRewarder

---

spec/services/articles/feed_spec.rb

Going through our slowest spec list and this one was at the top. Ran through and made a couple quick optimizations by memorizing some feed object, combining some tests, and reducing the number of cycles for testing for empty feed. This doesnt speed it up like crazy but makes it a few seconds faster. 
but its gotta get done!

Spec Speed Up: Memoize Feed objects and Combine some Tests

---

config/environments/development.rb

Rails 6 introduced a security configuration to whitelist requests coming with a custom host. When working in development we sometimes want to use services like [ngrok](https://ngrok.io) or [xip.io](http://xip.io) to access our local dev server from other devices.
This only affects the development environment.
None

Adds config.hosts option in development environment

---

app/assets/stylesheets/settings.scss
app/javascript/githubRepos/__tests__/__snapshots__/githubRepos.test.jsx.snap
app/javascript/githubRepos/__tests__/githubRepos.test.jsx
app/javascript/githubRepos/githubRepos.jsx

There's a bug in the fetch code.
Unfortunately this fix won't get us any closer to what's happening, still needed though

Improve GithubRepos component error handling

---

docs/design/theming.md

The example code block in this doc was outdated!

Update example code

---

app/views/doorkeeper/applications/_delete_form.html.erb
app/views/doorkeeper/applications/_form.html.erb
app/views/doorkeeper/applications/edit.html.erb
app/views/doorkeeper/applications/index.html.erb
app/views/doorkeeper/applications/new.html.erb
app/views/doorkeeper/authorizations/error.html.erb
app/views/doorkeeper/authorizations/new.html.erb
app/views/doorkeeper/authorizations/show.html.erb
app/views/doorkeeper/authorized_applications/_delete_form.html.erb
app/views/doorkeeper/authorized_applications/index.html.erb

This PR fixes the errors resulting from running `bundle exec erblint app/views/doorkeeper`.
This PR is part of #8370.

Fix erblint errors on the `app/views/doorkeeper` folder

---

app/views/mailers/notify_mailer/new_message_email.html.erb
app/views/mailers/notify_mailer/new_reply_email.html.erb
app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
app/views/mailers/notify_mailer/trusted_role_email.html.erb

This PR fixes the errors resulting from running `bundle exec erblint app/views/mailers`.
This PR is part of #8370.

Fix erblint errors on the `app/views/mailers` folder

---

app/assets/stylesheets/moderators.scss
app/controllers/moderations_controller.rb
app/javascript/moderationArticles/moderationArticles.jsx
app/javascript/moderationArticles/singleArticle/articlePropTypes.js
app/javascript/moderationArticles/singleArticle/index.jsx
app/javascript/packs/moderationArticles.jsx
app/views/moderations/index.html.erb

This loads the articles for the new mod center via Preact. It also removes the old mod center code.

Use Preact to load articles for layout

---

.github/PULL_REQUEST_TEMPLATE.md

Based on our internal discussions, it seems like we often don't know how to QA a pull request when it is submitted, and have to ask for instructions on how to do this. This PR updates our `PULL_REQUEST_TEMPLATE.md` and replaces the "screenshots" section with "QA instructions + screenshots", since one often goes along with the other.
N/A
N/A
N/A

Add QA instructions to pull request template

---

app/views/articles/tags/_sidebar.html.erb
app/views/comments/settings.html.erb
app/views/internal/listings/index.html.erb
app/views/partnerships/index.html.erb
app/views/shared/_payment_pointer.html.erb
app/views/tags/_liquid.html.erb
app/views/video_chats/show.html.erb

This PR fixes the remaining errors resulting from running `bundle exec erblint --lint-all` 🎉 I didn't make separate PRs for them because there's only one file affected in each folder and not too many files.
~This PR is part of #8370. I haven't typed `Fixes #8370` because there's still something that requires a fix. I'll comment about that on the issue right now.~
Fixes #8370.
This PR includes a fix that was previously included in #8369, so that PR will need to be rebased after this one is merged!

Fix remaining erblint errors

---

app/controllers/github_repos_controller.rb
spec/requests/github_repos_spec.rb

Clean up inaccessible repositories

---

app/assets/stylesheets/moderators.scss
app/javascript/moderationArticles/singleArticle/index.jsx
db/schema.rb

This PR uses CSS grid to style the Articles List, and also formats the Article Date to show the published_at time if published on the same date, otherwise, displays the Month and Day.
Fire up your local environment, then navigate to `localhost:<port>/mod`

[Mod Center] Implement grid layout; format Date

---

README.md
docs/deployment.md
docs/tests/readme.md

Added documentation about KnapsackPro and our updated Travis build process.

Documentation: Add More Knapsack Information to Docs

---

docs/tests/readme.md
docs/tests/regression-tests.md

I promised I would document the status of Percy in #8348 so here it is. Pretty short and to the point but I think it helps clarify things to anyone wondering about it when they see it in the specs. 
Yet another excuse for a hedgehog gif!

Documentation: Document Status of Percy

---

app/controllers/reactions_controller.rb

Unintentionally added latency due to previous change
https://github.com/thepracticaldev/dev.to/pull/8393
n/a

Partially revert "Update ReactionsController not to cache AR Object (#8393)"

---

app/views/articles/_single_story.html.erb

Fixes lighthouse warning
Closes https://github.com/thepracticaldev/dev.to/issues/8668

Adding aria-label for featured article

---

app/assets/stylesheets/dashboard.scss
app/views/dashboards/followers.html.erb
app/views/dashboards/following_tags.html.erb
app/views/dashboards/following_users.html.erb
spec/system/dashboards/user_followers_display_spec.rb

I reshuffled the HTML from previously added button for follow back under `/dashboard/user_followers` in order to reuse the styling across all dashboard follow buttons.
Closes #4674
and also #3305 (this one has been mistakenly closed when related #7759 was added)

Add button to unfollow tags and users from dashboard

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/views/comments/_comment_proper.html.erb

It's bad for SEO to have these useless links all over the place that act as dead-ends for crawlers. This modifies the logic so instead of having the links right in the markup and then shown with JS, it adds the HTML only when relevant.
Also fixed a logical error with the way we display the settings button.
This whole area isn't the cleanest code, but this doesn't make it any worse.

Remove unnecessary comment links and clean up logic

---

db/migrate/20200615213003_remove_unused_indexes.rb
db/schema.rb

These 3 indexes according to Postgres are unused and 2 of them take up more than a gig of space so I have chosen to remove them.

Optimization: Remove unused indexes from Postgres

---

app/controllers/stories_controller.rb

This caches the number of articles for any given tag which is shown on the tag index page. The reason for this optimization is bc our `cached_tagged_with` query is not very performant and for popular tags, like webdev, it is run a lot. Below you can see that its one of the queries we waste the most time on.
2 hours seemed like a long enough time that the cache would get used but short enough that it wouldn't get too out of date for the number of articles published. I will keep an eye on our pg diagnose tab and if this query still shows up as a problem I can increase the cache time. 
https://github.com/thepracticaldev/dev.to/projects/9#card-40135387
Load any tag index and see the count of quality articles displayed. You can further inspect the cache being set in a console
```ruby …
```

Optimization: Cache Article cache_tagged_with Counts

---

app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/ContentTitle.jsx

It renders html entity in home page
closes https://github.com/thepracticaldev/dev.to/issues/8433

Rendering html entity in home feed

---

app/assets/stylesheets/scaffolds.scss
app/views/articles/index.html.erb
app/views/dashboards/_analytics.html.erb
app/views/dashboards/show.html.erb

This commit fixes most of the accessibility complaints from axe on the user dashboard. There are no visual UI changes.

Fix axe warnings on the user dashboard

---

app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
app/javascript/article-form/__tests__/articleForm.test.jsx
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/components/Header.jsx
app/javascript/packs/articleForm.jsx
app/views/articles/_v2_form.html.erb

New editor has its own logo and it needs to be generalized.
closes #8678

Generalize editor logo

---

app/services/suggester/articles/classic.rb

Recently we have had a couple alerts for requests taking longer than expected in the application. I have been able to trace these requests back to loading `additional_content_boxes` so I went digging in to see if I could find what queries were causing problems. One issue I found was that we were no longer eager loading the user or limiting our columns selected when loading the articles for the view. This fixes that.

Optimization: Eager Load and Limit Columns When Fetching Articles Not IDs

---

app/assets/stylesheets/article-show.scss
app/views/articles/show.html.erb

Hide HTML Variant

---

app/assets/stylesheets/moderators.scss
app/controllers/moderations_controller.rb
app/views/moderations/_mod_sidebar_left.html.erb

Adds a feedback link to mod's Community Mod Chat Channel

[Mod Center] Add feedback link to mod's Community Mod Chat Channel

---

app/assets/stylesheets/scaffolds.scss

hotfix safari code issue

---

app/assets/stylesheets/settings.scss
app/models/identity.rb
app/models/user.rb
app/views/users/_account.html.erb
app/views/users/_account_providers_emails.html.erb
app/views/users/_additional_authentication.html.erb
app/views/users/_profile.html.erb
spec/models/identity_spec.rb
spec/models/user_spec.rb

Add a basic info panel that shows which email is tied to which authentication method, in addition to the primary email.
1. go to http://localhost:3000/settings/account
1. check the emails

Add email panel to settings/account

---

app/assets/stylesheets/moderators.scss
app/javascript/modCenter/singleArticle/index.jsx
app/views/moderations/index.html.erb

This updates the CSS to use utility classes instead of writing more CSS.

Use CSS utility classes for mod center

---

db/seeds.rb

We don't want to do devel seeding in production mode when using db:prepare. This PR fixes that. We can also use seeds.rb to do production seeding for new Forems in the future.

Don't seed in production when using db:prepare

---

app/assets/stylesheets/more-articles.scss
app/labor/article_suggester.rb
app/views/articles/_bottom_content.html.erb
app/views/articles/show.html.erb
spec/labor/article_suggester_spec.rb

This PR does a few things...
- Simplifies UX
- Simplifies our internal logic (only one place to optimize for UX)
- Makes page load way more efficient, reduces need for tons of extra caching.
- Helps SEO by more cleanly presenting related content.
This PR should really help us get rid of a lot of cruft from a windy path of old needs and features.

Modify articles below content for SEO and efficiency

---

app/assets/stylesheets/internal/layout.scss
app/controllers/internal/broadcasts_controller.rb
app/views/internal/broadcasts/_form.html.erb
app/views/internal/broadcasts/edit.html.erb
app/views/internal/broadcasts/index.html.erb
app/views/internal/broadcasts/show.html.erb
config/routes.rb

This PR adds a show view to "/internal/broadcasts" and reformats "/internal/broadcasts" to follow "/internal" styling convention by replacing some of the HTML in `/broadcasts/index.html.erb` with a table. Additionally, this PR adds `#show` to the `Internal::BroadcastsController`, cleans up Broadcast-related routes, adds a redirect to the Broadcast show view on both the #update and #create methods in the `Internal::BroadcastsController`, and fixes an issue where the "Announcement Banner Preview" did not render as expected.
Closes #8371 
**Navigate to "/internal/broadcasts" and observe the new-and-improved Broadcasts table:**
**Click on a Broadcast to render the Broadcast show view:**
**Click on the "Edit Broadcast" button to render the Broadcast edit view:**
**Create an Announcement …

Add a Broadcast Show View

---

app/javascript/packs/articlePage.jsx

We're occasionally getting different variations of "can't perform whatever of null" on this line.
I have some vague theories about what the issue could be, but checking for the existence of this thing here couldn't hurt either way.

Check for snackbar

---

.eslintrc.js
app/javascript/.eslintrc.js

Just some linting configuration updates. Prettier is supposed to be the last extends so that it can override any formatting rules that it manages. I've seen weird issues in at least VS Code, where the linter battles between formatting in the file. This fixes that. More on this in the official prettier docs for [prettier eslint integration](https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules).
Nothing to test.

Fix eslint files for prettier

---

app/javascript/article-form/components/__tests__/Title.test.jsx
app/javascript/listings/__tests__/ModalBackground.test.jsx
app/javascript/onboarding/components/_tests/ProfileForm.test.jsx
app/javascript/readingList/components/__tests__/ItemListItem.test.jsx
app/javascript/sidebar-widget/__tests__/sidebarUser.test.jsx

Just some cleanup of frontend tests post-Preact upgrade.
Run `yarn test` and all the frontend tests should pass.

Cleaned up some tests post-Preact upgrade

---

app/javascript/.eslintrc.js
package.json
yarn.lock

Our eslint configuration previously ignored certain paths (webpack aliases) so that the linter would not complain. This worked, but it was a bit of a hack. This PR fixes that by properly resolving webpack aliases by using the webpack eslint module resolver.
Nothing to test.

webpack aliases resolve properly for eslint now

---

app/javascript/.storybook/main.js
app/javascript/.storybook/preview.js
package.json
yarn.lock

We already have testing of a11y violations in our frontend tests via [jest-axe](), but this is a great addon regardless. You can see pretty descriptive information about a11y violations/passes etc. as you build your component out.
Documentation about our usage of Storybook in general will be in another PR at some point as we're still adding things to Storybook. We were previously being held back for some addons due to being on an older version of Preact. That is no longer the case.
To test:
* Navigate to a Storybook story in the Netlify preview site for Storybook, e.g. the [Article from an organization story](https://deploy-preview-8814--storybookdevto.netlify.app/?path=/story/4-app-components-article-standard--with-organization), to see the a11y panel
* Click on the Accessibility panel …

Added a11y Storybook addon

---

app/assets/stylesheets/views/article.scss

Fixed zindex in Sidebar reactions panel which was overlapping with the navbar.
Very small fix

style: fixed z-indexing bug in sidebar reactions

---

jest.config.js

We have more tests/coverage in the frontend, so bumping up the jest coverage thresholds a tiny bit.
Run `yarn test`, to see the upped coverage numbers.

Coverage thresholds bump for jest

---

spec/support/initializers/ci_csv_formatter.rb

Just adds branch to CI formatter

Adds travis branch to CI formatter

---

CONTRIBUTING.md
docs/contributing_dev.md
docs/contributing_forem.md
docs/readme.md

This pull request moves the contributing guide to the docs site ([Gatsby does something similar](https://github.com/gatsbyjs/gatsby/blob/master/CONTRIBUTING.md)) and adds a link to the `CONTRIBUTING.md` file (which still contains some CoC info!)
It allows adds a few sentences describing the new `difficulty` labels we're going to start using to label issues that are up for grabs. (Thanks for the suggestion @AlbertoPdRF) :)

Move contributing documentation and document difficulty labels

---

app/controllers/page_views_controller.rb
spec/requests/page_views_spec.rb

PR https://github.com/thepracticaldev/dev.to/pull/8836 accidentally removes the trailing slash here, but this is a count for existing page views by referrer and can't change.

Add trailing slash back in

---

app/javascript/listings/__tests__/Modal.test.jsx
app/javascript/listings/components/Modal.jsx
app/javascript/listings/listings.jsx

It fixes send button in listing message modal
Closes https://github.com/thepracticaldev/dev.to/issues/8762
1. Click on a listing
2. Type in message and click it send to send to send it to the message
3. Click on listing again
4. Type white space and click send the message won't be sent

Fixing listing message modal handler

---

bin/setup

We should avoid install foreman during `bin/setup` if it is already
installed.
I'm not sure if we should dictate a version here - anyone have thoughts?

Conditionally install foreman during setup

---

config/initializers/ahoy.rb

A quick fix for ahoy, which seems to not be playing well with Fastly.

Mask ip addresses + no cookies in ahoy

---

app/views/articles/show.html.erb

This commit fixes a few accessibility issues flagged by axe on the article show page!

Fix accessiblity issues flagged by axe on articles

---

app/javascript/.storybook/preview.js

Persisting theme between stories
* Navigate to https://deploy-preview-8855--storybookdevto.netlify.app/?path=/story/1-guidelines--crayons
* Select any Storybook story
* Change the theme
* Select a different Storybook story
* The theme persists
Persisting theme when revisting Storybook site
* Navigate to https://deploy-preview-8855--storybookdevto.netlify.app/?path=/story/1-guidelines--crayons
* Select any Storybook story
* Change the theme
* Close your browser
* Navigate back to https://deploy-preview-8855--storybookdevto.netlify.app/?path=/story/1-guidelines--crayons
* The theme you last selected will have persisted.

Theme switcher in Storybook persists theme between stories and sessions now

---

docs/tests/test-flags.md
spec/support/initializers/capybara.rb
spec/system/user/view_user_index_spec.rb

Adds ability to run spec not headlessly

---

app/javascript/crayons/Notice/__stories__/notice.html.stories.jsx

The warning notice Storybook story name was called "story". It should be called "warning".
Before
After
To test:
* Navigate to https://deploy-preview-8856--storybookdevto.netlify.app/?path=/story/3-components-notices-html--warning to see the fix.

Fixed warning notice Storybook name

---

.github/CODEOWNERS

Removed some directories that no longer exist and added some high touch app points and spec files to the SRE list as well as the travis.yml file.

Update SRE files in CODEOWNERS

---

config/initializers/reserved_words.rb

This removes `github` from the reserved words. :)
1. Update your username to `github` locally

Remove GitHub from reserved words

---

docs/self-hosting.md

We haven't updated this since announcing Forem. This isn't a
comprehensive change, but it links to some more information and is more
current that the old message.

Update self hosting docs with info on Forem

---

app/views/moderations/mod.html.erb

This PR resolves #8832 
Before:
After: 

Change the moderate language to reflect mod panel language

---

app/javascript/actionsPanel/actionsPanel.js
app/views/comments/_comment_proper.html.erb

A couple small bugs with moderating.
The comment dropdown was a little messed up by html tag alignment issues, and the adding/removing of tags had rendering problems due to some class names changing.

Small mod fixes

---

app/workers/users/record_field_test_event_worker.rb
spec/workers/users/record_field_test_event_worker_spec.rb

Bug Fix: Make FieldTestWorker More Resilient

---

config/webpack/environment.js
package.json
yarn.lock

This will only upload our Preact portion source map to help debug errors we see on Honeybadger. The code within `app/assets/javascripts` will require different solution
https://github.com/thepracticaldev/dev.to/projects/9#card-38542511
Followed the instruction on 
1. https://github.com/honeybadger-io/honeybadger-webpack#rails-webpacker-configwebpackenvironmentjs
2. https://docs.honeybadger.io/lib/javascript/guides/using-source-maps.html#uploading-your-source-map
1. QA on production ☠️ 
There shouldn't be. Let's hope it works on the first try 🤞

Add @honeybadger-io/webpack for source-map upload

---

app/javascript/Search/__tests__/Search.test.jsx
app/javascript/article-form/components/Preview.jsx
app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
app/javascript/article-form/components/__tests__/Options.test.jsx
app/javascript/article-form/components/__tests__/Preview.test.jsx
app/javascript/article-form/components/__tests__/Tabs.test.jsx
app/javascript/article-form/components/__tests__/Title.test.jsx
app/javascript/articles/__tests__/Article.test.jsx
app/javascript/articles/__tests__/ArticleLoading.test.jsx
app/javascript/articles/components/__tests__/CommentsList.test.jsx
app/javascript/chat/__tests__/activeMembershipsSection.test.jsx
app/javascript/chat/__tests__/alert.test.jsx
app/javascript/chat/__tests__/article.test.jsx
app/javascript/chat/__tests__/channelRequest.test.jsx
app/javascript/chat/__tests__/channels.test.jsx
app/javascript/chat/__tests__/chatChannelDescription.test.jsx
app/javascript/podcasts/__tests__/TodaysPodcasts.test.jsx

Just some frontend testing cleanup. Mainly lint fixes. I opted for queryBy for lint warnings `jest/expect-expect`. It makes sense as it's clearer what's being test than just having a test with `getByText(/some text/i)`. Both will pass. but using `query*` functions makes it clearer.
e.g.
Before
```js
...
getByText(/some text/i);
```
After
```js
...
expect(queryByText(/some text/i)).toBeDefined();
```
These are all the linting errors that are fixed.
```bash
app/javascript/Search/__tests__/Search.test.jsx
26:3  warning  Test has no assertions  jest/expect-expect
app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
48:5  warning  Test has no assertions  jest/expect-expect
73:5  warning  Skipped test            jest/no-disabled-tests
99:3  warning  Test has no assertions …
```

Some frontend testing cleanup

---

package.json

Weird heroku requirement
https://github.com/thepracticaldev/dev.to/pull/8899
n/a

Move @honebeybadger-io/webpack out of devDependencies

---

docs/backend/metrics.md
docs/backend/tracking.md
docs/frontend/tracking.md

Now that we have `ahoy_matey` and `ahoy.js` set up for first-party tracking, we need some documentation around these libraries, how to use them, and what configurations we have for them and why.
This PR adds all of that :)
I also renamed the "Tracking Metrics" documentation file to just be "Metrics", so that if someone greps our docs for `tracking`, that file won't show up.
N/A
Check out the new documentation files, make sure they make sense/have no typos, and that they can link between each other!
N/A

Add documentation for tracking

---

app/assets/stylesheets/dashboard.scss

Fix article stats page

---

app/assets/stylesheets/settings.scss
app/javascript/githubRepos/singleRepo.jsx

- Fixes #8834 
- Added back in the piece of code removed in #6823 corresponding to the styles of the `Fork` label in the repo list on the "Integrations" tab. 
Before:
After:

Fix incorrect styling of fork in repo list

---

app/javascript/Snackbar/SnackbarItem.jsx
app/javascript/article-form/components/ArticleCoverImage.jsx
app/javascript/article-form/components/EditorActions.jsx
app/javascript/article-form/components/Header.jsx
app/javascript/article-form/components/ImageUploader.jsx
app/javascript/articles/Feed.jsx
app/javascript/articles/components/CommentsList.jsx
app/javascript/articles/components/ContentTitle.jsx
app/javascript/chat/chat.jsx
app/javascript/chat/content.jsx
app/javascript/crayons/Modal/Modal.jsx
app/javascript/githubRepos/githubRepos.jsx
app/javascript/listings/listingForm.jsx
app/javascript/listings/singleListing/index.jsx
app/javascript/onboarding/components/EmailPreferencesForm.jsx
app/javascript/onboarding/components/FollowTags.jsx
app/javascript/onboarding/components/FollowUsers.jsx
app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/ProfileForm.jsx
app/javascript/packs/videoChat.jsx
app/javascript/readingList/components/ItemListItem.jsx
config/webpack/environment.js

Some of the linting issues were existing issues, some are new ones due to the changes made to the linting ruleset for the frontend.
N/A

Fixed a bunch of linting issues in components

---

app/views/layouts/_footer.html.erb

Small reference to Forem as well as our underlying framework Rails. Generally this won't affect the end user in any way, except maybe some curious folks who notice they've landed on a lot of sites of this variety and want to learn more.

Add "Built on Forem" link/explanation to footer.

---

app/javascript/.eslintrc.js
app/javascript/article-form/articleForm.jsx
app/javascript/articles/Feed.jsx
app/javascript/articles/components/SaveButton.jsx
app/javascript/chat/__tests__/util.test.js
app/javascript/chat/content.jsx
app/javascript/contentDisplayPolicy/hideBlockedContent.js
app/javascript/listings/__tests__/utils.test.js
app/javascript/shared/components/tags.jsx
app/javascript/utilities/__tests__/search.test.js

To test:
* Most of this is lint fixes and test cleanup, but the feed is affected in some changes.
* Ensure that on the main page in the logged on feed you can still save bookmarks.
* In the editor, if you have a draft in progress (auto-saved via local storage) that is newer than the last saved date/time of the post (explicit save via the Save Draft button), ensure that the draft in local storage still loads instead of the actual article contents if it is newer.

More frontend lint fixes

---

app/controllers/chat_channels_controller.rb

This isn't called anywhere it seems

Remove dead code in ChatChannelsController

---

docs/backend/configuration.md
docs/installation/readme.md
docs/installation/vault.md

Docs for Vault! 
https://github.com/thepracticaldev/dev.to/projects/9#card-40734895

Documentation: Vault Docs

---

app/javascript/.eslintrc.js

Added a comment explaining why the eslint rule is overridden.

Added a comment mentioning that index.js overrides are for barrel files

---

docs/contributing.md

Adds a link to @jessitron's great blog post, [“Just” don’t](https://jessitron.com/2020/06/26/just-dont), which prompts us to avoid exclusive language.
N/A

Link to @jessitron's blog post in our documentation guides

---

.travis.yml
bin/knapsack_pro_rspec

Reverts thepracticaldev/dev.to#8938 so I can fix the Flaky specs that hit hard with vengeance

Revert "Feature: Introduce KnapsackPro Queue Mode"

---

app/assets/stylesheets/article-show.scss
app/views/articles/_sticky_nav.html.erb
app/views/articles/tag_index.html.erb

As far as I can tell, these are all classes and code that are no longer in use. Let me know if I'm wrong with any of this.

Remove dead styling code

---

app/views/articles/_badges_area.html.erb

- [X ] Bug Fix
Hello ,
I used inspect element inside this https://dev.to/simonholdorf profile ,
I added mx-auto d-block to make badges responsive with all screen sizes.
- [X ] no, because they aren't needed
- [X ] no documentation needed

fix Issue #9013 , badge responsivity

---

app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/ReactionsCount.jsx

Fix listing card view reactions formatting

---

app/views/articles/index.html.erb
app/views/articles/tag_index.html.erb

When we removed some end-of-url slashes we also removed them from root here, resulting in a "" href. This is a quick fix.

Add slash back for root link

---

app/javascript/article-form/components/ArticleCoverImage.jsx
app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx

Adds an upload spinner like the one implemented for post content images in #8986. Closes #7907.
#8986, #7907
To test:
Scenario 1: Add a Cover Image
- Create or edit a new post
- Add a cover image. Notice the upload spinner
Scenario 2: Change a Cover Image
- Create or edit a new post
- Add a cover image. Notice the upload spinner
- Change the cover image. Notice the upload spinner
In both scenarios, upon success or failure of uploading an image, the upload spinner disappears.

Added upload spinner for cover image in editor

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/index-comments.scss
app/views/users/_comments_section.html.erb

Go to profile -> resize the window -> you should see annoying scroll bar in the bottom ,
also same for mobile app.
Screenshot after fixing
this black shadow keep appearing because of this scrollbar

Fixing scrollbar for small screens in the profile page

---

app/views/articles/_sidebar.html.erb

If there are _no_ community sponsors, we don't need this header. Some forems might not have sponsors.

Only include community sponsors header if sponsors truly exist

---

docs/installation/windows.md

Missed a `\n` which led to a blockquote not rendering properly in an earlier PR. GitDocs has been having significant troubles running on WSL lately and I missed to check for this render issue. 😅😅😅😅
#8854 
Check `http://localhost:8000/installation/windows/` for the blockquote after `1. Run bin/setup.`
**Current:**
**Fixed:**
The weird font should be a GitDocs error on my system, but do check on local!
- Font should look like this:

fix blockquote render error windows docs

---

.travis.yml
bin/knapsack_pro_rspec

Take 2 of #8938 but now I have fixed some persistent flaky specs #9001 #9029

Feature: Enable KnapsackPro Queue Mode Take 2

---

app/services/flare_tag.rb

Quick little Flare Tag refactor with some of @citizen428's suggestions from #8987

Refactor Flare Tag Class

---

app/javascript/responseTemplates/responseTemplates.js

Resolves https://github.com/thepracticaldev/dev.to/issues/9058
n/a
n/a

Add null safety to handleLoggedOut()

---

.github/workflows/rebase.yml

Add ability to automatically rebase PRs when a user comments on the PR.
Issue https://github.com/thepracticaldev/dev.to/issues/8927
A Core Dev maintainer will test this after it has been merged by comment "/rebase" on a PR that needs rebasing

Enable Automatic Rebase: Fix #8927

---

app/javascript/chat/__tests__/requestManager.test.jsx

We had one last test in the frontend that was being skipped. The test works now. 🥳
N/A

Fixed <RequestManager /> skipped test

---

docs/frontend/plain-js.md
docs/frontend/webpacker.md
docs/installation/windows.md
docs/maintainers/deploying.md
docs/tests/test-flags.md

Yeah, this was just bothering me...

Standardize capitalization of JavaScript

---

docs/installation/windows.md

- add `nvm` installation.
- switch yarn to install without node.
- add `nvm install` post clone.
- **bug fix** `rbenv` code block not rendering correctly.
Fixes #8446 
Perform an installation of `nvm`, `yarn` and clone repo by performing the modified commands on WSL. If `yarn -v` outputs correctly, then yarn installation succeeded. Also, check for correct rendering of Markdown elements in `gitdocs` under `http://localhost:8000/installation/windows/`.

fix node install windows docs

---

app/assets/javascripts/initializers/initializeCommentDropdown.js

The three dot menu on the article page is currently broken. This fixes it.
Before
After
To test:
- Go to any article page
- Click on the tree dot menu on the left (non-mobile view)
or on the three dot menu on the bottom (mobile view)
- The menu opens

Fixed the three dot menu on the article page.

---

app/assets/javascripts/initializers/initializeCommentDropdown.js
app/views/articles/_actions.html.erb

Our uglifier was not compiling correctly when given this sytnax... And along the way I noticed an issue with `target`, and the best way to solve was to switch from inline svg to `img src` svg to bring consistency between main actions menu and comment menu.

Slight fix in dropdown menu code

---

app/assets/javascripts/initializers/initNotifications.js
app/assets/javascripts/initializers/initializeAllFollowButts.js
app/assets/javascripts/initializers/initializeDrawerSliders.js

Was doing some cleanup and rabbit holed into fixing the remaining lint issues in the frontend. Closes 
#8972, assuming #3777 is closed as well.
#8972, #3777
N/A

Fixed remaining lint issues in the frontend.

---

.github/workflows/welcome.yml

This workflow should drop the following comment into PRs from new contributors:
Congrats on making your first Pull Request to Forem! 🎉
Our core team will review your proposal as soon as possible. Our [code review process is publicly documented](https://docs.dev.to/maintainers/pull_requests/), so you'll know exactly what to expect.
If you haven't had a chance, give our [Contributing Guide](https://docs.dev.to/contributing/forem/) a read.
Thanks for taking the time to improve our platform and our community! ❤️

Add a workflow to greet new contributors

---

app/lib/constants.rb

This will whitelist mastodon.online url, so users from the
mastodon.online instance can link their profile within their dev.to
profile page.
#9101

update: add mastodon.online to the whitelist

---

.vscode/launch.json

Adds node internals to the list of skipped files when debugging a jest test in VS Code. For more information on skipped files, see the [VS Code official documentation on skipping files](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome).
N/A

Added node.js internals to list of skipped files for debugging jest in VS Code

---

app/assets/javascripts/initializers/initializeSwipeGestures.js

Fixes eslint errors in `app/assets/javascripts/initializers/initializeSwipeGestures.js`.
*P.S. not sure if a hook reformatted the file or it was on my end! Will rollback if needed.*
#3777 
Simulate a touch device of Tablet and Mobile sizes and perform the following actions on home page:
- `left swipe` to trigger the left panel (with login, etc) and `right swipe` to close it.
- `right swipe` to trigger the right panel (with tags, more links, etc) and `left swipe` to close it.

fix lint errors in initializeSwipeGestures

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/connect/_channel-details.scss
app/assets/stylesheets/ltags/CommentTag.scss
app/assets/stylesheets/ltags/GithubReadmeTag.scss
app/assets/stylesheets/ltags/GithubTag.scss
app/assets/stylesheets/ltags/LinkTag.scss
app/assets/stylesheets/ltags/ListingTag.scss
app/assets/stylesheets/ltags/PodcastTag.scss
app/assets/stylesheets/ltags/PollTag.scss
app/assets/stylesheets/ltags/RedditTag.scss
app/assets/stylesheets/ltags/StackexchangeTag.scss
app/assets/stylesheets/ltags/TagTag.scss
app/assets/stylesheets/ltags/TweetTag.scss
app/assets/stylesheets/ltags/UserSubscriptionTag.scss
app/assets/stylesheets/ltags/UserTag.scss
app/assets/stylesheets/ltags/WikipediaTag.scss
app/assets/stylesheets/preact/article-form.scss
app/assets/stylesheets/preact/onboarding-modal.scss
app/assets/stylesheets/preact/sidebar-widget.scss
app/javascript/.storybook/main.js
package.json
yarn.lock

sass-loader@9.0.1 had some breaking changes. This fixes those breaking changes.
#9135 
To test:
- load up the application locally and smoke test. The look of the site should be the same
-

Sass loader 9.0.1 upgrade

---

spec/liquid_tags/liquid_tag_base_spec.rb

It wasn't clear how role and contexts with liquid tags would be done or how some other things might settle. Now that we're on the tail end of this feature, here's the spec for the liquid tag role and context validation I added to `LiquidTagBase` a couple of PRs ago.
#8917 
Run the spec 🎉 .

LiquidTagBase spec

---

app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
app/javascript/Search/__tests__/Search.test.jsx
app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
app/javascript/githubRepos/__tests__/githubRepos.test.jsx
app/javascript/onboarding/__tests__/Onboarding.test.jsx
app/javascript/onboarding/components/__tests__/FollowTags.test.jsx
app/javascript/onboarding/components/__tests__/FollowUsers.test.jsx
app/javascript/onboarding/components/__tests__/IntroSlide.test.jsx
app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
app/javascript/shared/components/__tests__/tags.test.jsx
package.json
yarn.lock

Some of the API has been deprecate in Preact testing library. This addresses those deprecations. For more info on the changes, see #8799.
#8799
To test:
- All tests should pass

Upgraded to preact testing library 2.0.0

---

app/controllers/articles_controller.rb

Refactoring articles_controller, reducing lines to below than 250.
Issue about refactoring and code climate
https://github.com/thepracticaldev/dev.to/issues/3739

Refactoring articles_controller reduce lines

---

app/models/badge.rb
app/models/page.rb
spec/requests/internal/badges_spec.rb
spec/requests/internal/pages_spec.rb

Resoucify Page and Badge models 
n/a
n/a
n/a

Resoucify Page and Badge models

---

app/assets/javascripts/base.js.erb

MetaMask is an extension. Its error can be ignored.
n/a
n/a
n/a

Ignore MetaMask errors on Honeybadger

---

app/labor/email_digest.rb
app/lib/release_phase_notifier.rb

1) Send any email digest errors to Honeybadger
2) Send release phase errors to Honeybadger. These we especially want to know about if they happen so I'm not sure why silly past Molly decided to log it
https://github.com/thepracticaldev/dev.to/projects/9#card-41511704

Refactor:Send a Couple More Errors to Honeybadger

---

.github/workflows/codeql-analysis.yml

GitHub released a code analysis engine that scans the code for potential issues called CodeQL.
Among the list of supported languages we only use JavaScript
See "Code scanning alerts" in https://github.com/thepracticaldev/dev.to/security

Add Github CodeQL code scanner for JavaScript

---

app/assets/javascripts/base.js.erb

I'm investigating a large collection of `Unexpected token ':'. Parse error.` we've been experiencing since the beginning. Having source map helps narrow down the location but I still can't figure out what caused the error. Hopefully, these additional contexts will go a long way.
There are a lot of these but here's 1 for example
https://app.honeybadger.io/fault/67192/1d668f90b16383eb3f0f51bf6018757f
n/a
n/a

Log instantClick errors

---

app/views/tags/index.html.erb

Format large numbers with commas on the tags page https://dev.to/tags
**Before**
**After**

Add number_with_delimiter to post count on tags page

---

app/views/pages/badges.html.erb

See the post: https://dev.to/bravemaster619/add-a-markdown-version-for-dev-badge-link-1bep
Nathan Kallman and others suggested me to create a PR

Add markdown version for DEV badge link

---

app/views/tags/index.html.erb

Reverts thepracticaldev/dev.to#9225
As it turns out, [this approach isn't as friendly with locales as I thought](https://github.com/thepracticaldev/dev.to/pull/9225#issuecomment-656587831). Thanks, @rhymes  for catching this!
#9225

Revert "Add number_with_delimiter to post count on tags page"

---

app/controllers/comments_controller.rb
app/views/comments/_comment.json.jbuilder

Refactoring comments_controller#create, reducing lines to below than 50.
Issue about refactoring and code climate
https://github.com/thepracticaldev/dev.to/issues/3739

Refactoring comments_controller#create reducing lines

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/views/articles/show.html.erb

This PR changes spacing within the subheader components. For small screen sizes, the subheader components look squished and do not provide a great UI experience for our users.
Closes #9196 
In your dev environment create a post and head over to your dashboard and select your post. Enter responsive mode within developer tools and begin to resize the browser width. You will begin to see the subheader components to wrap ~473px and below. Before the implemented changes these components were very close to each other vertically. After the changes, it gave the subheader components some spacing equivalent to the tags spacing above the subheader
768px and up
425px and up
320px

Article page: edit and manage button spacing

---

.rubocop.yml
.rubocop_todo.yml
app/models/message.rb
app/views/api/v0/articles/me.json.jbuilder
config/environments/production.rb
config/environments/test.rb
config/initializers/honeycomb.rb
lib/tasks/pages.rake
package.json

Address Metrics/BlockLength violations

Rubocop: Address Metrics/BlockLength violations

---

docs/tests/readme.md

Found some issues while reading
Tests
No

Fixed some minor typos

---

app/views/layouts/_social_media.html.erb
app/views/shell/_top.html.erb

Based on a discussion with @mstruve in #8435 ([link](https://github.com/thepracticaldev/dev.to/pull/8435#discussion_r448605900)) I started looking into the `SiteConfig` conditionals we introduced in views.
However, it doesn't seem like there are substantial improvements to be made:
```
app/views/pages/information.html.erb
42:      <% if SiteConfig.shop_url.present? %>
app/views/pages/privacy.html.erb
103:      <% if SiteConfig.shop_url.present? %>
app/views/layouts/_footer.html.erb
43:        <% if SiteConfig.shop_url.present? %>
app/views/articles/_sidebar_nav.html.erb
57:    <% if SiteConfig.shop_url.present? %>
```
All these usages of `shop_url` are slightly different and no useful partial can be extracted.
```
app/views/layouts/_footer.html.erb
49:    <% if …
```

SiteConfig view refactoring

---

.rubocop.yml
app/controllers/api/v0/articles_controller.rb
app/controllers/api/v0/comments_controller.rb
app/controllers/api/v0/followers_controller.rb
app/controllers/api/v0/listings_controller.rb
app/controllers/api/v0/tags_controller.rb
app/controllers/api/v0/users_controller.rb
app/controllers/api/v0/videos_controller.rb
app/controllers/api/v0/webhooks_controller.rb
app/controllers/chat_channels_controller.rb
app/controllers/followings_controller.rb
app/controllers/internal/listings_controller.rb
app/controllers/tags_controller.rb
app/labor/markdown_traverser.rb
app/models/reaction.rb
app/models/tag.rb
app/view_objects/articles/social_image.rb

Activate [Layout/ClassStructure](https://github.com/rubocop-hq/rubocop/blob/81c39c9a7a8528c22ee5a3a54bacfd11c7373e7e/config/default.yml#L346) which forces a consistent order in declarations inside classes.

Rubocop: activate Layout/ClassStructure

---

app/views/dashboards/following_tags.html.erb

Closes #9211
I updated the language at the top of https://dev.to/dashboard/following_tags as the #9211 described

Change Label Follow Weight Scale for Tags in Dashboard

---

.github/workflows/codeql-analysis.yml
.travis.yml

Remove Github CodeQL Action until we can fix it for the new repo

Tweak Travis File

---

README.md

Update Readme Headline

---

config/routes.rb

Add a redirect to share the https://dev.to/devteam/for-empowering-community-2k6h article.
Pretty sure this doesn't already exist...

Add /forem redirect

---

README.md

Adding in missing word `write` to the forem/README.md file.
Closes #9340

Add missing words in README

---

db/seeds.rb

Trying to review https://github.com/forem/forem/pull/9349 I noticed I didn't have any listings locally.
The seed file was checking the wrong model for idempotent creation.
1. Delete all listings if you have any
1. Run `bundle exec rails db:seed`

Create Listings in seed file

---

app/javascript/article-form/components/TagsField.jsx
app/javascript/listings/listingForm.jsx
app/javascript/shared/components/tags.jsx

This commit updates the regex looking for non-ASCII characters and
also makes it possible to pass a regex as a prop if necessary.
I saw a second issue come in for this bug, so I went ahead and updated the regex to be more explicitly restrictive. It should solve the issue from https://github.com/thepracticaldev/dev.to/issues/8884 for listings and articles without breaking listings.
Fixes https://github.com/thepracticaldev/dev.to/issues/9116
Duplicate https://github.com/thepracticaldev/dev.to/issues/9168
Bug was created in https://github.com/thepracticaldev/dev.to/pull/9006/files
Gif I made was way too big :(

Restrict tags input regex

---

config/routes.rb

#8937  What type of PR is this? (check all applicable)
Turns on logging in Flipper UI's Sinatra app so we can get some idea of what error is causing  https://github.com/thepracticaldev/tech-private/issues/450
https://github.com/thepracticaldev/tech-private/issues/450

Add logging  to Flipper UI

---

db/migrate/20200717203432_remove_blocks_table.rb
db/schema.rb

Refactor:Drop Blocks Table

---

app/javascript/article-form/components/TagsField.jsx
app/javascript/listings/listingForm.jsx
app/javascript/shared/components/__tests__/tags.test.jsx
app/javascript/shared/components/tags.jsx

#9172 was merged in an incomplete state. I committed a suggestion, but did not make the corresponding changes to support that suggestion on the branch yet. This fixes that, but some tests need to be refactored. I'm making this PR so that broken code isn't in production, and will rewrite those tests in another branch.
Note I closed #9356 trying to troubleshoot a CI issue -- but I figured it out. :sweat_smile: 

Fix tag input patterns

---

app/views/pages/_editor_guide_text.html.erb
app/views/pages/_editor_liquid_help.html.erb
app/views/pages/markdown_basics.html.erb

Updated the GitHub links pointing to `thepracticaldev/dev.to` to `forem/forem` in the Markdown Guides

Update GitHub link in Markdown Guides

---

db/migrate/20200720143134_change_role_p_kto_bigint.rb
db/schema.rb

Production table sizes:
Role - 231
UsersRoles - 10k
We have update 10k row tables in place for the last couple of Primary Key changes(#9393 #9372)  and it has been plenty fast so wouldn't expect this to be much different. 

Optimization:Change Role PKs from Int to Bigint

---

app/assets/stylesheets/article-show.scss

This bug was originally fixed in [this pull request](https://github.com/forem/forem/pull/8298).
However there may have been some changes to the names of classes - I couldn't find an `article` class or `body` class when I was inspecting an article.
This fixes issue #7760 
Would be cool to have this tested so it doesn't break again, however not sure if there is a good way to go about it.
Going to admit it was a bit of a struggle setting up Forem locally, and a bit overwhelming to try and find a ticket that I could work on!

Fix hidden footnote content regression

---

docs/troubleshooting.md

This troubleshooting guide was mentioned in a recent Slack discussion. I'm using slightly different commands for the same purpose and wanted to add them since they can be more convenient under certain circumstances (you don't have to start a Rails console, you can alias them in your shell, etc.)
n/a
n/a

Update docs for ES troubleshooting

---

db/migrate/20200720213710_change_tweet_p_kto_bigint.rb
db/schema.rb

Production Data 
Tweets - 10k
We have update 10k row tables in place for the last couple of Primary Key changes(#9393 #9372)  and it has been plenty fast so wouldn't expect this to be much different. 

Optimization:Change Tweet Primary Key to Bigint

---

app/views/layouts/application.html.erb

When we generalized banner code (https://github.com/forem/forem/pull/7018), the comment noting which HTML ID to use wasn't correctly updated.
https://github.com/forem/forem/pull/7018

Correct comment about banner div ids

---

app/assets/javascripts/base.js.erb

Broaden MetaMask ignores and remove useless custom exception tracking.
https://github.com/forem/forem/pull/9226/files
n/a
n/a

Update Honeybadger's ignorePatterns

---

config/initializers/reserved_words.rb

We need to proactively protect the top level path early on because once we have many forems, it would be really hard to do new things off the top of the path.
We automatically protect username signups in cases of the Rails route tree, plus we have this misc list for other reserved words.

Add new reserved words

---

app/decorators/article_decorator.rb
app/helpers/articles_helper.rb
app/views/articles/_about_author.html.erb
app/views/articles/show.html.erb
spec/decorators/article_decorator_spec.rb
spec/system/articles/user_visits_an_article_spec.rb

This PR fixes the issue that the posted date of article does not match author card posted data on the same article page.
To solve it, I relocated the cache method from show article page to about author page to avoid caching the posted date on the author card.
It is unnecessary to delete existing caches related to this. The reason is they are expired as the view is changed.
Here is a related quote from [Rails Guides](https://guides.rubyonrails.org/caching_with_rails.html).
> Cache fragments will also be expired when the view fragment changes (e.g., the HTML in the view changes).
And I also removed has_long_markdown variable in the view file and redefined it as a method in `ArticleHelper` for refactoring.
https://github.com/thepracticaldev/dev.to/issues/8789

Bug Fix: Article Posted Date and Author Card Posted Date do not match

---

app/controllers/chat_channel_memberships_controller.rb

At the moment we need longer expiration times for these links. For the longer term we better include a SiteConfig of some sort so we're able to configure this from the internal tooling.

Changes expiration of chat channel invitation links

---

app/controllers/chat_channel_memberships_controller.rb

Connect redirect issue when following invites

Redirect override

---

docs/Makefile
docs/contributing/docs.md
docs/readme.md
package.json
yarn.lock

Add `gitdocs` as a local dependency
Fixes #9461 

Add gitdocs as devDependency

---

app/assets/config/manifest.js

This is so silly, but I couldn't stop staring at it.

Remove extra spaces in manifest.js

---

app/views/moderations/_mod_sidebar_left.html.erb
app/views/moderations/index.html.erb

Noticed a few small a11y complaints from Axe!

[Mod Center] Fix accessibility issues flagged by axe

---

.rubocop.yml
app/controllers/concerns/fastly_headers.rb
app/services/authentication/paths.rb
app/services/authentication/providers/github.rb
app/services/authentication/providers/provider.rb
app/services/authentication/providers/twitter.rb
config/database.yml
config/initializers/slack_notifier.rb
spec/requests/comments_create_spec.rb
spec/support/initializers/warden.rb

This PR enabled `Style/OptionHash` to remind the dev to possibly avoid generic `params` arguments and instead use keyword arguments for explicitness.

Rubocop: Enable and fix Style/OptionHash

---

config/environments/production.rb

Allow Log level to be changed in production with an ENV variable to aid in possible debugging. 
https://github.com/forem/forem/projects/9#card-41699894

Feature:Allow Log Level to be Set with ENV Variable

---

app/assets/stylesheets/signup-modal.scss
app/views/shared/authentication/_providers_signup_modal.html.erb

Add extra button here to bring consistency in other areas of call-to-action for registration
Closes #9467

Add sign in options button to modal

---

app/views/users/_account.html.erb

On [Settings/Account page](https://dev.to/settings/account) change copy from 
```
You can generate personal API keys to use for authentication with the DEV API. The API is still in early beta though. The DEV <a href="https://docs.dev.to/api">documentation</a> contains further information.
```
to
```
You can generate personal API keys to use for authentication with the API. DEV is built on the Forem public API (beta). The <a href="https://docs.forem.com/api">documentation</a> contains further information.
```
Done on CodeLand's workshop **"Your First Forem Pull Request", hosted by Ben Halpern**. No issue attached.

Change DEV doc to Forem doc on account page

---

db/migrate/20200726215928_change_tag_ids_to_bigints.rb
db/schema.rb

Despite having 700k rows in the taggings table, bc the rows are super small the alter column seems to run pretty damn fast in about 5 seconds. To help mitigate any errors this might cause I plan to increase the postgres STATEMENT_TIMEOUT on the app to 15 seconds so any tagging requests can easily wait for the table to finish updating and still complete their request.
[Here's the timing data](https://gist.github.com/mstruve/1600b29a30b39b9f4edc0c8d79d9ba91)
```
"taggings"
"tag_adjustments"
"tags"
```
https://github.com/forem/forem/projects/9
Increase STATEMENT_TIMEOUT to 15 seconds.

Optimization:Change Tag Related IDs to Bigints

---

app/assets/stylesheets/_functions.scss
package.json
yarn.lock

Fixes the Storybook build for SASS files after css-loader 4.0.0 was introduced. My guess is this code was never correct in the _functions.scss file and the css-loader was just more lenient about it.
#9519 
Nothing to do except visit the deployed [Storybook for this PR](https://deploy-preview-9548--storybookdevto.netlify.app/). It should load and that is the test.

Upgraded to css-loader 4.0.0

---

app/services/authentication/paths.rb
app/services/authentication/providers/github.rb
app/services/authentication/providers/provider.rb
app/services/authentication/providers/twitter.rb
config/database.yml
config/initializers/slack_notifier.rb
spec/requests/comments_create_spec.rb
spec/support/initializers/warden.rb

This PR is to address most of the feedback left by @citizen428 in this PR review https://github.com/forem/forem/pull/9430#pullrequestreview-454005749 which got unaddressed inline unfortunately
https://github.com/forem/forem/pull/9430

Rubocop: address feedback of #9430 and use kwargs 

---

.github/workflows/issue.yml

This PR adds a workflow that posts an automated comment on every new issue, so maintainers don't have to!
Fixes #9442.
I have no idea regarding how to test if this actually works :confused: @Amorpheuz do you perhaps? :slightly_smiling_face: 
No.

Add workflow automating maintainers' comment on new issues

---

.gitpod.yml

This PR improves the Gitpod setup. It now allows you to benefit from prebuilds.
The prebuild feature builds your repo on every commit on the Gitpod servers. Thus, users that open this repo in Gitpod do not need to wait until the build finished but can start coding immediately. All you have to do is to merge this PR and activate Gitpod prebuilds as described there: https://www.gitpod.io/docs/prebuilds/#on-github
My fork has prebuilds enabled. You could try it out by clicking on this link: https://gitpod.io/#https://github.com/corneliusludmann/forem
Please ping me if you have further questions or need help.
Also, Gitpod now waits until the server is ready before opening a preview window.
A user talking about that building this repo in Gitpod takes a lot of time. This can be remedied with …

Prepare Gitpod setup for prebuilds

---

app/javascript/crayons/Modal/Modal.jsx
app/javascript/crayons/Modal/__tests__/Modal.test.jsx

I came across this while looking at #9349. Fixed our `<Modal />` component so that it uses the `<dialog />` HTML element.
The modal component should render the same as before. You can compare the modal in this [PR's storybook](https://deploy-preview-9563--storybookdevto.netlify.app/?path=/story/3-components-modals--default) to the [main storybook](https://storybook.forem.com/?path=/story/3-components-modals--default).

Make <Modal /> component more accessible

---

docs/installation/windows.md

Updates Windows Installation docs to a WSL2 - Linux Only install. The following sections have been updated:
- Installing WSL
- Installing PostgreSQL
- Installing Elasticsearch
- Installing Imagemagick
Fixes #9489 
I created a preview of the same at https://pensive-wright-1336dc.netlify.app/installation/windows/!
<details>
<summary>
Pre-requisites and WSL:
</summary>
<p>
</p>
</details>
<details>
<summary>
PostgreSQL and Imagemagick:
</summary>
<p>
</p>
</details>
<details>
<summary>
Elasticsearch
</summary>
<p>
</p>
</details>

Update Windows Installation docs to WSL 2

---

app/assets/stylesheets/article-show.scss
app/views/layouts/_styles.html.erb

Remove some dead code and remove some scenarios where we have to render inline

Remove a few unnecessary css lines

---

config/blazer.yml

Show status enum string value in Blazer for Data Update Scripts so people dont have to look in the code to figure out what status is what.

Feature:Show Status For DataUpdateScript Enum Column

---

app/views/onboardings/_task_card.html.erb

As a new user, I get a welcome message that includes a button with no discernible text (the close X) and a group of items that should be marked up as a list. This PR introduces those changes!
One thing to note, I couldn't get `erb-lint` to run in my local environment so I used the `--no-verify` flag to keep this work moving along. You might want to double-check it!
The display should be the same, as there is CSS matching UL elements with classes to remove list styles, margins, and padding. The Close Button label can be verified in the Chrome DevTools accessibility inspector or the [axe extension](https://www.deque.com/axe/).
I don't think this part of the code is tested yet, hence no tests.

Improve accessibility of welcome message

---

Containerfile
bin/container-setup
container-compose.yml
docker-compose.yml

This PR moves the away from the devto specific naming to forem w/r/t container things. Also moves to the Forem quay.io org.

Update containers: DEV => Forem

---

docs/netlify.toml

Force redirect for Netlify 🤷‍♂️

Force redirect for docs.dev.to to docs.forem.com

---

container-compose.yml
docker-compose.yml

Sets APP_DOMAIN to rails to fix #9604
#9604

Set APP_DOMAIN to rails to fix #9604

---

app/controllers/resource_admin/comments_controller.rb
app/controllers/resource_admin/tags_controller.rb
app/controllers/stories_controller.rb
app/controllers/tags_controller.rb
spec/requests/user/user_profile_spec.rb

A few paths referring to `/admin` were mistakenly left in the code after https://github.com/forem/forem/pull/9576, this PR corrects them (and fixes editing of tags).

Correct some lingering `/admin` paths

---

config/environments/production.rb
config/initializers/hypershield.rb

Remove "To" email field on ahoy_messages from logs and Blazer queries.

Bug Fix:Hide To Email Field on Ahoy Messages

---

app/views/moderations/_mod_sidebar_left.html.erb
app/views/moderations/index.html.erb

All elements should be contained by a [landmark element](https://dequeuniversity.com/rules/axe/3.5/region).

Ensure all elements are contained by landmarks in mod center

---

docs/design/language.md
docs/design/readme.md

This is a page to better describe some language concepts in the site. We currently do not have a good _canonical_ location here. This is a first pass to be updated continuously. It is not complete, if you have more to add, let's merge this and keep adding to this and other docs.

Add initial language doc page

---

app/views/devise/registrations/_registration_form.html.erb

Fix the self closing div to prevent double rendering of footer.
Closes https://github.com/forem/forem/issues/9629

Fix Footer Page render for unauthorised users

---

docs/creators/configure-forem.md
docs/creators/readme.md
docs/creators/setting-up.md
docs/readme.md

I’ve added a creators section to our current docs in a divided section, until we figure out how we separate out the developer docs from the creator docs. (my thoughts are that they should live on different domains - something like developers.forem.com and creators.forem.com)
This PR simply adds some instructions to a Forem Creator on how to configure their Forem. It will be accompanied by a subsequent PR that improves the descriptions on the Site Config Page for them to understand what the different config sections and variables do and how they tie back into the site.
- Spin up your docs locally with  yarn gitdocs serve
- Navigate to http://localhost:8000/creators/configure-forem/
or go to https://deploy-preview-9664--docsdevto.netlify.app/

Base Documentation for Forem Site Configuration

---

docs/frontend/webpacker.md

Added a link to a visual guide to Webpacker in the Webpacker documentation that @citizen428 shared with me on Slack yesterday.
N/A

Added a link to a visual guide to Webpacker in the Webpacker documentation

---

app/labor/profile_image.rb
app/lib/image_resizer.rb
app/models/html_variant.rb
app/models/message.rb
app/models/podcast_episode.rb
app/view_objects/articles/social_image.rb
app/view_objects/cloud_cover_url.rb
spec/helpers/social_image_helper_spec.rb
spec/labor/profile_image_spec.rb
spec/models/html_variant_spec.rb
spec/models/message_spec.rb
spec/models/podcast_episode_spec.rb
spec/view_objects/cloud_cover_url_spec.rb

This is to pave the way to other future image resizing solution. There will be part 2 to this PR to extract the rest of `cl_image_path` in the codebase
n/a
Navigate around the site locally and see that images are rendered properly.
n/a

Implement ImageResizer module

---

spec/requests/pages_spec.rb

Fix the spec that was failing in https://github.com/forem/forem/pull/9666

dev.docs spec fix

---

app/views/admin/users/_credits.erb

https://app.honeybadger.io/fault/66984/b3199253c016e5178679e3fea86cc341
We missed an update to a path reference in the migration from `/internal` to `/admin`.
#9639

Update left over internal_user_path ref

---

config/fastly/snippets/safe_params_list.vcl

We only allow certain params to adjust the content, others are ignored by the cache to reduce cache misses. We ignore `/admin....` related stuff because they have a longtail of possible params, but it's still listed as the legacy `/internal` in this case.

Change /internal/ to /admin/ in vcl param safelist

---

app/labor/article_suggester.rb

Currently the "Read Next" area mostly doesn't work for naissant communities. This should make the article suggestion more viable for these situations. 😄

Make read next area work for smaller communities

---

app/views/users/_profile.html.erb

This checks for _if DEV_ in a sort of hack, but I think we'd need a bit more functionality in place before this should be present and I think we can keep this check in place until the follow up functionality ships.

Remove DEV-only badge link

---

.rubocop.yml
app/controllers/comments_controller.rb
app/controllers/notifications_controller.rb
app/controllers/video_chats_controller.rb
app/liquid_tags/null_tag.rb
app/services/moderator/banish_user.rb
app/services/moderator/delete_user.rb
app/services/moderator/merge_user.rb
app/services/rate_limit_checker.rb
app/services/search/query_builders/chat_channel_membership.rb
app/services/search/query_builders/feed_content.rb
app/services/search/query_builders/listing.rb
app/services/search/query_builders/reaction.rb
app/services/search/query_builders/user.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/carrierwave.rb
config/initializers/docker.rb
spec/helpers/social_image_helper_spec.rb
spec/models/html_variant_spec.rb
spec/requests/admin/chat_channel_spec.rb
spec/requests/admin/configs_spec.rb
spec/requests/admin/podcasts_spec.rb
spec/requests/admin/profile_fields_spec.rb
spec/requests/admin/users_spec.rb
spec/view_objects/cloud_cover_url_spec.rb

Rubocop 0.89 [added a bunch of cops](https://github.com/forem/forem/pull/9699), here we enable and correct all `Lint/` violations. I'll send separate additional PRs for `Style/` issues as this already contains many files.
https://github.com/forem/forem/pull/9699

Enable Rubocop 0.89 cops and fix Lint/ violations

---

app/assets/javascripts/initializers/initializePaymentPointers.js

This fixes a small bug where if an author added their payment pointer before the Forem's payment pointer was added, the author's article page would fail to load reactions.

Check for the meta payment pointer before loading author payment pointer

---

lib/data_update_scripts/20200810083831_remove_orphaned_ahoy_rows.rb

This PR was excised from https://github.com/forem/forem/pull/9636 so that we can clean up the DB from Ahoy orphaned rows before merging https://github.com/forem/forem/pull/9636
See https://github.com/forem/forem/pull/9636#discussion_r467582799
https://github.com/forem/forem/pull/9636

Cleanup orphaned Ahoy rows in the DB

---

db/migrate/20200809200631_final_bigint_migration.rb
db/schema.rb

Final Migrations to bigints. All of these tables are small and should not cause any problems when running these migrations:
Production Counts:
```
"api_secrets" - 1775
"badge_achievements" - 337,662
"broadcasts" - 13
"display_ads" - 17
"feedback_messages" - 8,520
"html_variant_successes" - 20
"html_variant_trials" - 254,130
"users_roles" - 10,914
```
https://github.com/orgs/forem/projects/6#card-43327500

Optimization:Migrate Final Small Table PKs to Bigints

---

app/controllers/admin/profile_fields_controller.rb
app/views/admin/profile_fields/_form.html.erb
app/views/admin/profile_fields/index.html.erb
spec/factories/profile_fields.rb
spec/requests/admin/profile_fields_spec.rb

Added "groups" and grouped by "groups" on the UI. Still very rough and working on improving this drastically to be smart in another PR but thought I'd get this PR in already to set the base.
Part of https://github.com/forem/forem/issues/6994
Go to http://localhost:3000/internal/profile_fields and the fields will be grouped by 'group'
_Note: when you update or add an item it will go to the bottom, will tackle that in another PR._

v1 of adding the groups to the profile fields admin interface

---

app/assets/stylesheets/config/_generator.scss
app/javascript/netlify.toml

Update Netlify config to handle stylesheet changes for Storybook

---

.github/PULL_REQUEST_TEMPLATE.md

Fixed some links in the PR template.

Update repository links in PR template

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/signin.scss
app/views/stories/_sign_in_invitation.html.erb
spec/system/articles/user_visits_articles_by_timeframe_spec.rb

Update authentication feed card as part of initiative to improve UX & visual design of existing login experiences.
Closes https://github.com/forem/InternalProjectPlanning/issues/17
Small screen:
Large screen:
Small screen:
Large screen:

Update styling of authentication feed card for logged out users

---

app/javascript/packs/commentModPage.js

Fixes a small bug with the mod page, where reactions weren't being submitted properly. The JS had the wrong variable.

Add missing .dataset for comment mod page

---

app/javascript/packs/commentModPage.js

Adds some error handling in case a comment mod page reaction fails.

Add error handling for comment mod page reactions

---

public/offline.html

I added a button on [the offline page](https://dev.to/offline) that allows people to quickly erase the whiteboard to redraw.
https://giphy.com/gifs/j2team-junookyo-devto-J4UpmMIhl0go4sXl5I

Add button to clear the whiteboard

---

docs/frontend/debugging.md

Changing Preact version to 10.x in docs

Changing Preact version to 10.x in docs

---

README.md
docs/backend/resource-admin.md
docs/technical-overview/architecture.md

It changes rails version to 6.0.3 in the docs since the app use that version now

Changing rails version to 6.0.3 in docs

---

lib/tasks/app_initializer.rake

Hypershield refresh stopped working in Heroku and I am not sure why. I confirmed via a console that `ENV["ENABLE_HYPERSHIELD"].present?` is set. I confirmed locally that if I run `bin/rails app_initializer:setup` that without the `if ENV["ENABLE_HYPERSHIELD"].present?` statement the enhance block is correctly triggered. Something is not quite working right on Heroku causing this to not get triggered. Hopefully this logging will help indicate where in the flow we are dying.

Add Logging Statements to Debug Hypershield Refresh Not Working on Heroku

---

lib/tasks/app_initializer.rake

I have confirmed enhance is triggering so there is something wrong with how we are triggering hypershield within the rake task. A step in the right direction. 
Reverts forem/forem#9838

Revert "Add Logging Statements to Debug Hypershield Refresh Not Working on Heroku"

---

app/views/devise/registrations/_registration_form.html.erb

Currently, on [the sign-in page](https://dev.to/enter), I can submit the form without enter an email or password.
So I added the attribute required to make sure the user will enter email and password before submitting.

Add "required" attribute to the login form

---

.rubocop_todo.yml
app/models/article.rb
app/models/html_variant.rb
app/models/html_variant_success.rb
app/models/html_variant_trial.rb
app/models/user.rb
db/migrate/20200818101637_add_missing_foreign_keys_to_html_variants_models.rb
db/migrate/20200818101700_validate_add_missing_foreign_keys_to_html_variants_models.rb
db/schema.rb
spec/models/article_spec.rb
spec/models/html_variant_spec.rb
spec/models/user_spec.rb

This PR is step 2 of 2, step 1 is https://github.com/forem/forem/pull/9845 which has been merged and deployed first.
It contains foreign keys and depedent relations between `HtmlVariant` related models (successes, trails, articles)

Add relations and foreign keys between HtmlVariant related models

---

app/labor/bufferizer.rb
app/models/buffer_update.rb
spec/models/buffer_update_spec.rb
spec/services/users/delete_articles_spec.rb

Refactoring the model `buffer_update.rb` to reduce the arguments in the method `buff!`

Reduce arguments method buff! at model buffer_update

---

app/views/admin/articles/index.html.erb
app/views/admin/badges/award.html.erb
app/views/admin/badges/edit.html.erb
app/views/admin/badges/index.html.erb
app/views/admin/badges/new.html.erb
app/views/admin/broadcasts/_form.html.erb
app/views/admin/broadcasts/edit.html.erb
app/views/admin/broadcasts/index.html.erb
app/views/admin/broadcasts/new.html.erb
app/views/admin/broadcasts/show.html.erb
app/views/layouts/admin.html.erb

This commit contains a handful of fixes for possible accessibility
issues flagged by axe.
I'm currently working through the rest of our admin interface and will
break those changes into seperate commits due to the need for cleanup in
some of the more complicated interfaces.

Apply fixes for axe issues in admin interfaces

---

app/views/articles/manage.html.erb

Some light adjustments just to the copy on this page.

Update suggested tweet copy on manage page

---

config/environments/production.rb

Checks if we have `HEROKU_APP_URL` set before trying additional logic with it.

Check for heroku url presence before working with it

---

app/controllers/admin/configs_controller.rb
app/helpers/application_helper.rb
app/labor/badge_rewarder.rb
app/lib/constants/site_config.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb
config/.env_sample
config/sample_application.yml
spec/helpers/application_helper_spec.rb
spec/labor/badge_rewarder_spec.rb
spec/requests/admin/configs_spec.rb

No reason the environment and our systems teem needs to know anything about this value.

Move community_copyright_start_year to SiteConfig

---

app/labor/badge_rewarder.rb
config/schedule.yml
lib/tasks/badges.rake
spec/labor/badge_rewarder_spec.rb

Move Streak Badges(4, 8, and 16 week) to Sidekiq Cron. 

Refactor:Move Streak Badges to Sidekiq Cron

---

lib/data_update_scripts/20200818170410_remove_orphaned_poll_votes.rb
lib/data_update_scripts/20200818170433_remove_orphaned_poll_skips.rb
lib/data_update_scripts/20200818170505_remove_orphaned_poll_options.rb
lib/data_update_scripts/20200818170523_remove_orphaned_polls.rb

Step 1 of cleaning up polls related rows. Step 2 is https://github.com/forem/forem/pull/9854
We don't have orphaned polls or poll votes in the DB but I thought to be safer to keep those script in case other Forems do.
- orphaned poll votes: https://dev.to/admin/blazer/queries/191-poll_votes-orphan-rows
- orphaned poll skips: https://dev.to/admin/blazer/queries/190-poll_skips-orphan-rows
- orphaned poll options: https://dev.to/admin/blazer/queries/192-poll_options-orphan-rows
https://github.com/forem/forem/pull/9854

Remove orphaned polls related rows

---

.rubocop_todo.yml
app/models/article.rb
app/models/poll.rb
app/models/poll_option.rb
db/migrate/20200818163445_add_missing_foreign_keys_to_poll_models.rb
db/migrate/20200818163834_validate_add_missing_foreign_keys_to_poll_models.rb
db/schema.rb
spec/models/article_spec.rb
spec/models/poll_option_spec.rb
spec/models/poll_spec.rb

`Poll`, `PollOption`, `PollSkip`, `PollVote` are missing a bunch of FK and dependent relations.
Cleanup happens in PR https://github.com/forem/forem/pull/9854 which has to be merged and deployed first

Add relations and foreign keys between Poll related models

---

app/lib/constants/site_config.rb
app/views/admin/configs/show.html.erb

Replace the rest of the placeholders and descriptions from the constants file.
Also, just _loosely_ alphabetized the hash.
No Visual Changes. 
You can just go to http://localhost:3000/admin/config to ensure that the descriptions and placeholders show.

Use and organize constants for the config page 

---

app/controllers/application_controller.rb
config/initializers/stripe.rb

In https://github.com/forem/forem/pull/9862 we moved to a dynamic Stripe initialization. To close the loop the info logger for Stripe needs to be dynamic as well, as in the initializer the `Stripe.api_key` will always be empty.
See https://github.com/forem/forem/pull/9862/files#r473150038
#9862

Move Stripe dev logger in the controller

---

app/controllers/admin/chat_channels_controller.rb
app/controllers/comments_controller.rb

This PR enables logging for comment deletion by admins.

[Admin Tooling] Log comment deletion

---

app/assets/stylesheets/components/stories.scss

This PR makes a little update to the way we display flare tags in the feed so it's more aesthetically in-line with other places on DEV/Forem.

Flare Tag styling update

---

config/webpacker.yml

Fixes the webpacker deprecation mentioned in #9980. (`resolved_paths` is now `additional_paths`)
Closes #9980 

Moved from resolved_paths (deprecated) to additional_paths.

---

docs/frontend/plain-js.md

Fix typo(boostraps/bootstraps)

---

app/workers/podcasts/enqueue_get_episodes_worker.rb
config/schedule.yml
lib/tasks/fetch.rake
spec/workers/podcasts/enqueue_get_episodes_worker_spec.rb

Move enqueueing workers to get new podcasts to a Sidekiq Cron job

Refactor:Move Enqueueing Podcast Workers to Sidekiq Cron

---

app/controllers/articles_controller.rb

Remove method not used at articles_controller, and resolve 2 issues at codeclimate

Remove method not used at artciles controller

---

app/javascript/articles/components/SaveButton.jsx
app/javascript/articles/components/__tests__/SaveButton.test.jsx

The save button wouldn't update if clicked and then quickly moved your mouse away. Now It is able to handle that. The the button is still a slow to update when you click unsave though. Fixes #8167.
https://giphy.com/gifs/gintama-kdM3zfq85XSb6

Fixed save button behavior

---

db/migrate/20200822092853_add_missing_foreign_keys_to_models_related_to_organizations.rb
db/schema.rb
spec/liquid_tags/link_tag_spec.rb
spec/liquid_tags/listing_tag_spec.rb
spec/policies/organization_policy_spec.rb
spec/requests/articles/articles_update_spec.rb

Adding missing FKs to entities related to `organizations`
Part 2 to #9932

Add foreign keys to models related to Organization

---

app/assets/stylesheets/internal/layout.scss
app/views/admin/configs/show.html.erb

Just changed a style on the config page to make it more visible, see screenshot.
Before: 
After:

Quick admin style update

---

app/controllers/admin/configs_controller.rb
spec/requests/admin/configs_spec.rb

These allowed params and specs were missing!

Add missing configs controller params for rate limiting

---

app/assets/stylesheets/components/stories.scss
app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
app/javascript/articles/components/ArticleCoverImage.jsx
app/views/articles/_single_story.html.erb

There was an accessibility violation on the featured post where the header image link was an empty link. See [2.4.4 Link Purpose (In Context) (Level A)](https://webaim.org/standards/wcag/checklist#sc2.4.4) for more info.

Fixed accessibilty issue with empty link on featured post.

---

app/views/comments/deleted_commentable_comment.html.erb

Added `comments-dedicated-page-container` class to set width of `Comment from a deleted article or podcast` page.
Closes #9991
**To Reproduce**
1. Go to https://dev.to/dorshinar/comment/p4g3
2. see no issue
N/A

Fix Comment from a deleted article or podcast

---

spec/services/images/optimizer_spec.rb

This spec file currently does not respect the user-provided Imgproxy's env var keys will be destructive and cause flaky specs. This PR properly stub the env vars.
source: test broke on me when I try to run it with my env vars.
n/a
n/a
n/a

Refactor images/optimizer_spec

---

app/black_box/black_box.rb

We just pushed a change to the way the feed is calculated which put _a bit too much weight_ on the score vs the time published, which is surfacing slightly-too-old posts.
This may take some fiddling and eye-balling to get "right".... But at least now we have a simpler way to fiddle with the nobs.

Fiddle with hotness score calc

---

app/black_box/black_box.rb

In a bit more of "hot fix" to get the algorithm working a little better in prod after adjustment, continued to fiddle with the knobs, going from 25 to 15 for multiplier of score impact, but also capped the max impact of these to 1000 to avoid the big hits from [very popular posts](https://dev.to/simonholdorf/9-projects-you-can-do-to-become-a-frontend-master-in-2020-n2h).

Adjust ranking algo, including max score impact

---

app/black_box/black_box.rb

I'm at the point where I'm just changing some magic numbers to figure out the balance here.

More fiddling with algo score

---

app/black_box/black_box.rb

A little more fiddling, hopefully the last. Algorithm still valuing score slightly too high vs timeframe.

Last algo fiddle I hope

---

app/black_box/black_box.rb

I'll revisit the algorithm in general, but this is my final hot fix fiddle.

Last algorithm fiddle

---

app/black_box/black_box.rb

Just a little bit more fiddling with the algo after the adjustment. Hopefully _this_ will be the last one.

Final final algo fiddle for the day

---

app/black_box/black_box.rb

Still need a little more adjustment.

Adjust score a little bit more

---

app/models/concerns/user_subscription_sourceable.rb
app/models/user_subscription.rb
db/migrate/20200827073520_set_user_subscription_sourceable_columns_to_null.rb
db/schema.rb
spec/models/user_subscription_spec.rb

As we don't want to delete subscriptions if an article disappears, we need to be able to set the fields to null.
See this discussion about this https://github.com/forem/forem/pull/9990#discussion_r477111121
https://github.com/forem/forem/pull/9990

Set UserSubscription sourceable columns to nullable

---

app/controllers/sessions_controller.rb
config/routes.rb

This is designed to help an issue where we have some cookie inconsistencies which need to be remedied on signout, but it's also just pretty decent hygiene in terms of ensuring we're not enabling any extra tracking in an unintended way. This cleans the slate when someone needs to leave.

Delete all cookies when signing out

---

db/migrate/20200826131359_add_missing_foreign_keys_to_models_related_to_articles.rb
db/migrate/20200826132009_validate_add_missing_foreign_keys_to_articles_related_models.rb
db/schema.rb

Adds missing FKs to `articles`: `buffer_updates` and `rating_votes`.
Step 2 of https://github.com/forem/forem/pull/9990

Add foreign keys between buffer_updates, rating_votes and articles

---

spec/services/users/delete_spec.rb

Spec Fix:Nullify Rating Votes when Deleting Users

---

app/models/rating_vote.rb
db/migrate/20200826132639_add_missing_foreign_keys_to_models_related_to_users.rb
db/schema.rb
spec/factories/rating_votes.rb
spec/models/notification_spec.rb
spec/models/rating_vote_spec.rb
spec/policies/organization_policy_spec.rb
spec/services/users/delete_spec.rb

Adds all the missing FKs to models related to users
Part 2 of https://github.com/forem/forem/pull/10011

Add missing foreign keys to models related to users

---

app/views/moderations/mod.html.erb

This PR adjusts the description of what happens when a User is flagged as abusive. Another teammate and I recently misunderstood what happened when a user is flagged as abusive -- we thought that this equated to `vomit`ing on _all_ of the user's Articles, rather than just lowering the score of the user's Articles... _the more you know_. 🤷‍♀️  This misunderstanding ending up surfacing in a [comment](https://github.com/forem/forem/pull/10059#discussion_r479483637) on one of my most recent PRs, which led me to this adjustment (per @Zhao-Andy's suggestion 😄 ).
To QA this PR, navigate to `/<username>/comment/:id/mod` to ensure that the description looks good and has no typos:
N/A

Adjusts the Wording Around Flagging a User as Abusive to be More Explicit

---

app/views/admin/feedback_messages/_latest_articles.html.erb

This PR fixes an issue that was breaking layout on `/admin/reports` page. It was caused by me putting piece of code in a wrong place with my admin updates couple hours ago.

Admin Reports view hot fix

---

app/javascript/article-form/actions.js
app/javascript/chat/chat.jsx
app/javascript/utilities/dragAndUpload.js

Github flavored drag and drop image uploader in connect. Just a small experiment. 😅

🚀 Feature: Ability to upload images to connect by drag and drop

---

app/assets/stylesheets/notifications.scss

Hide overflow text caused be unbreakable words and urls (notification-comment-reacted-link)
closes #10121
1. Leave a long word or URL as a a comment
2. Get a reaction (like/unicorn)
3. See text no longer overflows box.
**Before:**
**After:**
N/A

Hide overflow text

---

app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx

It fixes broken test due to 24hr time format
closes https://github.com/forem/forem/issues/10141
1. Run ```yarn test``` with 12hr time format in your system
1. Run ```yarn test``` again with 24hr time format in your system

Fixing broken jest test

---

app/views/videos/index.html.erb
spec/system/videos/user_visits_videos_spec.rb

So the `app/views/videos/index.html.erb` was invoking the `#title` helper method 3 times.
In each invocation the helper method was calling `content_for(:title) { derived_title }`. Looking at the `content_for` documentation [here](https://github.com/rails/rails/blob/9055156668faa84821097e8fe324aaa1529abdfe/actionview/lib/action_view/helpers/capture_helper.rb#L117), you can find the following comment:
```
Note that <tt>content_for</tt> concatenates (default) the blocks it is given
for a particular identifier in order. For example:
```
Which basically meant that each time the helper got invoked, the title was appended to the end of the existing title.
This commit fixes the issue by making sure that the `#title` helper is only invoked once by the view.
Closes #10166
Open the `/videos` page …

Fixes a duplicate page title on the /videos page

---

app/controllers/admin/sponsorships_controller.rb
app/views/admin/sponsorships/index.html.erb
app/views/admin/sponsorships/new.html.erb
config/routes.rb
spec/requests/admin/sponsorships_spec.rb

Adds the ability to create sponsorships in `/admin/sponsorships` and also adds tabs for filtering by status on `/admin/sponsorships`
Same topic as #10153: Trying to extract missing features from `/resource_admin` to `/admin`
You should now be able to create new sponsorships from within `/admin/sponsorships`

Adds ability to create new sponsorships from admin dashboard

---

db/seeds.rb

Noticed this would have been helpful when I checked out #10187

Add sponsorships to seed data

---

config/initializers/content_security_policy.rb

Basically rollback https://github.com/forem/forem/pull/10144 until someone can devote some time to figuring out the bugs which are blockers for a lot of the team.

Bug Fix:Comment out content security policy

---

app/views/service_worker/index.js.erb

There are a few ways we will need to deal with locale in service workers, but in general any "edge cases" for service workers we should skip them.
A human explicitly visiting the `/locale/...` version of a page will most likely always be an edge case vs other scenarios... Or at least is puntable as something we need to figure out with regards to service workers.... So let's punt, eh?

Don't include locale in service workers

---

docs/backend/auth-facebook.md

Adds details on configuration Facebook for OAuth callback paths. (It turns out I had already merged other Facebook setup instructions!)

Add OAuth callback configuration to facebook docs

---

package.json
yarn.lock

I did two things for this pr
1. Ran `yarn upgrade`
2. Added selective dependency resolutions for gitdocs
n/a
n/a
n/a

Update JS sub-dependencies

---

Containerfile

Install and enable jemalloc to help improve memory usage in Ruby. We already use jemalloc on DEV on Heroku and it works well.

Install and enable jemalloc to help improve memory usage in Ruby.

---

lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb

This script is not quite right and needs a little fixing to ensure Elasticsearch data is removed properly. We dont need this anymore but I want to make sure the script is correct in case anyone else needs it and/or for people who might refer to the code to base their own code off of.

Bug Fix:Fix Data Update feed_source_url Script

---

app/javascript/articles/Article.jsx
spec/system/articles/user_visits_articles_by_timeframe_spec.rb

Fixing id and class of non featured article. It was adding string false before
Closes https://github.com/forem/forem/issues/10246

Fixing id and class of non featured article

---

app/assets/javascripts/utilities/localDateTime.js
app/javascript/listings/__tests__/ListingDashboard.test.jsx
app/javascript/listings/dashboard/rowElements/listingDate.jsx
app/javascript/shared/components/__tests__/dateTime.test.jsx
app/javascript/shared/components/dateTime.jsx

Creates common component and util function for displaying date. I have replaced only one component in this PR if the format is fine I'll create PR's to replace it in other places (so that it won't create noise when reviewing the code).
Closes https://github.com/forem/forem/issues/10233

Using global util function for displaying date in listing dashboard

---

app/models/article.rb

I originally came to this model to move some things into the decorator, but that turned into a dead end since several methods were calling into each other and with some of them also being called in the search serializer it was too hard to untangle them. So instead I decided to just clean up some code.
Cooldown fun.
Nothing specific. This is a refactoring, so I just make sure that we have specs for code I'm changing and that they stay green.

Article refactoring

---

app/controllers/admin/articles_controller.rb
app/models/article.rb
app/views/admin/articles/_individual_article.html.erb
spec/requests/admin/articles_spec.rb

This PR gives admins the ability to add co-authors to posts via a user's ID within `/admin/articles`. To accomplish this, this PR adds `second_user_id` and `third_user_id`s to the `article_params` in the `Admin::Articles::Controller`, adds `second_user_id` and `third_user_id` to `:limited_columns_internal_select` within `article.rb`, adds "Second Author ID" and "Third Author ID" form fields to `_individual_article.html.erb` to match the current "Author ID" form field, and adds tests around adding an additional co-author/additional co-authors to `admin/articles_spec.rb`.
Relates to a private issue.
To QA this PR, first ensure that you have `:super_admin` permissions, then do the following:
- Navigate to `/admin/articles` in your browser:
- Add a "Second Author ID" and a "Third Author ID" …

Give Admins the Ability to Add Co-Authors to Posts

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb

This closes the loop on #10150 which left this out so that it would give plenty of time for caches to clear to make sure this lined up correctly.

Fetch GA Tracking ID from SiteConfig

---

docs/getting-started/start-app.md
docs/installation/windows.md

Tweak a few things in the installation and setup docs for Windows, specifically:
- Fix an issue with the elasticsearch tgz filename being incorrect for a `tar` command
- Add a note to make sure Elasticsearch, the PostgreSQL server, and the Redis server are running before running the `bin/setup` script
- Add a tip for resolving a sidekiq error in `bin/startup`
Resolves #10240
N/A

[Documentation] Improvements to Windows installation & startup docs

---

app/controllers/admin/configs_controller.rb
app/labor/mailchimp_bot.rb
app/lib/constants/site_config.rb
app/models/site_config.rb
config/initializers/gibbon.rb
spec/requests/admin/configs_spec.rb

One more thing systems officially doesn't have to worry about.

Move mailchimp API key to app logic

---

app/views/mailers/notify_mailer/account_deletion_requested_email.text.erb

Update the URL in the account_delete_requested_email to be correct and match the URL in the HTML email. 
closes: https://github.com/thepracticaldev/tech-private/issues/343

Bug Fix:Update Text Request Email with confirm_delete Link

---

db/migrate/20200910205316_remove_active_from_profile_fields2.rb
db/schema.rb

This migration initially didn't run on production bc of a [little typo in the original PR](https://github.com/forem/forem/pull/9911/files#diff-96fd763dbe823dbb9971e988ecbb3390R3). This adds a new migration to do the job. 
https://github.com/orgs/forem/projects/6#card-45085888

Bug Fix:Add New Migration to Remove Active from Profile Fields

---

.github/workflows/codeql-analysis.yml

Now that we have access to Github's CodeQL action again, let's add it back in.
https://github.com/forem/forem/pull/9354#issuecomment-690519174
Should see new check at the bottom of this PR
n/a

Create codeql-analysis.yml again

---

.rubocop_todo.yml
db/migrate/20200911140318_add_unique_index_to_articles_user_id_title_body_markdown.rb
db/schema.rb
spec/models/article_spec.rb

This adds a unique index on the combination `user_id`, `title` and `body_markdown`. 
Part 2 of https://github.com/forem/forem/pull/10273
https://github.com/forem/forem/pull/10273

Add unique index on articles user_id, title and body_markdown

---

app/assets/javascripts/initializers/initializeCommentDropdown.js
app/assets/javascripts/initializers/runtime.js
app/javascript/article-form/components/ImageUploader.jsx
app/javascript/chat/ChatChannelSettings/MembershipManager/InvitationLinkManager.jsx

We already have copy to clipboard code spread in a few different places in the frontend codebase. This PR encapsulates this capability in the `Runtime` abstraction. This has the following effects:
- Easier to maintain all platforms we support
- Easier for contributors to develop features that copies text to the clipboard
#9688
#8311
All the places that use this feature and should continue to work:
- Post Editor ("Write a post") > upload an image >  Copy Image URL
- Post > Sidebar Dropdown (share feature) > Copy URL
- Connect channel (as moderator) > Membership Component > Copy Invite Link URL
This is a tricky feature to test as it uses browser specific features. I'm not sure if a `system` spec would work as I found this detailed response on SO about Capybara + copy to clipboard testing: …

Adds runtime copy to clipboard

---

docs/backend/tracking.md
docs/frontend/tracking.md

Fixing links to tracking in docs

Fixing links to tracking section in docs

---

docs/getting-started/branching.md

It adds note about branch naming to clear confusion for new users.

Adding note about branch naming

---

app/assets/stylesheets/syntax.scss

This PR fixes text wrapping issue on some browser.
- Closes #10336

Code snippets text wrapping fix

---

config/initializers/hypershield.rb

This column contains PII and should be hidden via Hypershield: `json_data` is the JSON dump of an `Identity` object

Hide column backup_data.json_data from Blazer via Hypershield

---

app/controllers/chat_channel_memberships_controller.rb

Remove an exceeded line at `chat_chat_memberships_controller.rb`

Remove exceeded line

---

db/seeds.rb

add image to Podcast model as described in [the carrierwave wiki](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file/7041728c73d24abdfbd4972b9c51aac6b99dcde4)
otherwise seeding fails on Podcast validations:
```
ActiveRecord::RecordInvalid: Validation failed: Image Image has an unsupported type, Image can't be blank
/opt/apps/bundle/gems/activerecord-6.0.3.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/opt/apps/bundle/gems/activerecord-6.0.3.3/lib/active_record/validations.rb:53:in `save!'
...
/opt/apps/forem/db/seeds.rb:267:in `block (2 levels) in <main>'
/opt/apps/forem/db/seeds.rb:266:in `each'
/opt/apps/forem/db/seeds.rb:266:in `block in <main>'
/opt/apps/forem/db/seeds.rb:19:in `create_if_none' …
```

add image in podcast seeds in suggested way

---

app/views/layouts/admin.html.erb

Extra closing html symbol present.

Fix extra character typo in admin section

---

app/views/shell/_top.html.erb

This PR adds missing `brand` variable to the work that Ben put together for custom brand colors #10097 
Thanks @citizen428 for the work with improving HexComparer!
- #10097

Adding missing variable

---

app/assets/stylesheets/syntax.scss

Addresses issue in #10334 - not a biggie though.
Closes #10334

Softer background for inline-code

---

Containerfile

Remove yarn steps since we build nod_modules in the asset:precompile step. Also tell it to precompile in production mode.
#10408

Fix the asset precompile in the Container

---

config/initializers/hypershield.rb
db/migrate/20200921160153_remove_backup_data.rb
db/schema.rb

Refactor:Remove BackupData Table from Postgres

---

lib/data_update_scripts/20200923173148_remove_reaction_index.rb
spec/lib/data_update_scripts/remove_reaction_index_spec.rb

Followup to #10377 where we removed all the search code. This removes the physical index which will free up a bit of space for Elasticsearch. 
https://github.com/orgs/forem/projects/6#card-45751135

Refactor:Remove Reactions Index

---

lib/tasks/forem.rake

Return health check token for @jdoss to use for Forem things.

Feature:Rake Task to Return Health Check Token

---

app/controllers/async_info_controller.rb
app/decorators/user_decorator.rb
app/models/follow.rb

There are two cache methods related to the reason the following tags are not updated, as pointed out in [this comment](https://github.com/forem/forem/issues/10174#issuecomment-687067914). So I fixed code relating to these two, which are cached_followed_tags and user_data methods.
Closes https://github.com/forem/forem/issues/10174
no, because the test environment default cache setting is off.

Fix unable to unfollow tags

---

app/services/users/delete_activity.rb
app/services/users/delete_articles.rb

Followup to #10377 where we removed a lot of the reaction search code. I missed these two blocks that were removing the reactions from Elasticsearch. 
https://github.com/orgs/forem/projects/6#card-46145035

Bug Fix:Remove More ReadingList Index Code

---

.yarnrc

Update to latest yarn version

---

.eslintrc.js
app/assets/javascripts/initializers/initializeSwipeGestures.js
app/javascript/.eslintrc.js

add front-end rule for no console. 
Closes #10360 add no-console rule 

add no console rule front-end

---

app/assets/javascripts/initializers/initializeBaseUserData.js

There were functionally duplicate codes, so I removed one of them and extracted it into a helper method.
n/a
You should be able to browse the site, and see your username and profile image normally on the nav bar.
n/a

Refactor: Create setCurrentUserToNavBar

---

README.md

Update README's Dependabot Badge

---

docs/api_v0.yml

In https://github.com/forem/forem/pull/9108 we added a new endpoint but we didn't requested the contributor to add the API docs as well.
I think in the future we should require those :)
https://github.com/forem/forem/pull/9108
1. Start `yarn api-docs:serve`
2. Browse the docs

API: add docs for api/follows/tags

---

db/migrate/20201002102257_remove_superfluous_indexes_part1.rb
db/migrate/20201002102303_remove_superfluous_indexes_part2.rb
db/schema.rb

As mentioned in https://github.com/forem/forem/pull/10514 we have a few indexes that are redundant. This PR removes a bunch more of them (there are still a few related to tables from gems, I'll send this PR separately next week after verifying each of them).
https://github.com/forem/forem/pull/10514
Same as those in https://github.com/forem/forem/pull/10514

Remove additional superfluous indexes

---

.github/CODEOWNERS

Removing teams delightful and snackcase from the CODEOWNERS file as they have been archived

Update CODEOWNERS to remove old teams

---

app/javascript/chat/chat.jsx
app/javascript/chat/compose.jsx

Hola All !! I was working on this one for a long time. As it was working fine in case of all browsers except Firebase but I was finally able to fix and here we are with this cool feature.
*Note: Copying from filesystem still doesn't work in the case of Firefox. But copying from the web or a MacOS screenshot on clipboard work flawlessly in Firefox.*

🚀Feature: Ability to upload images from clipboard in connect.

---

app/javascript/article-form/components/Options.jsx

Added z-index to the post editor options dropdown to make sure that it always stays on top of other content.
Fixes #10531
**Before**
**After**

added z-index to post editor options dropdown

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/controllers/stories_controller.rb
config/routes.rb
spec/models/article_spec.rb
spec/requests/profile_field_groups_request_spec.rb

I'm not entirely sure why these are failing in Travis, but working locally, but this removes a now unneeded functionality of "warming comments" which dates back to some inefficiencies which no longer exist, and also changes a test which I believe may have some ordering issues in Travis sometimes.....

Modify code to deal with flaky tests

---

docs/backend/authentication.md

Setting up more auth options locally and noticed this

Mention Facebook in authentication docs

---

app/views/notifications/_nav_menu.html.erb

This PR fixes a padding bug when user has multiple organizations.
Before:
After:

Fixing padding on Notifications navigation

---

app/views/admin/configs/show.html.erb

This should show up as text, not as the array...

Fix spam trigger keyword input text

---

app/javascript/chat/chat.jsx

User was not able to paste text in Textarea.

🐞 Hotfix: Clipboard Text Paste Issue Fixed

---

app/controllers/concerns/verify_setup_completed.rb
app/views/admin/configs/show.html.erb
app/views/devise/invitations/edit.html.erb
app/views/layouts/_signup_modal.html.erb
spec/views/layouts/signup_modal.html.erb_spec.rb

We have a concept of a required `tagline` as part of our `SiteConfig`, but in _most_ places, we have a fallback check to only render the `tagline` if it exists:
```ruby
<% if SiteConfig.tagline.present? %>
<%= SiteConfig.tagline %>
<% else %>
Some other text here!
<% end %>
```
This PR makes `SiteConfig.tagline` _not_ required, and fixes any scenarios where we _don't_ have a `SiteConfig.tagline.present?` check. This change will be super useful as we spin up new Forem instances and set up Forem creator onboarding, as it will be _one less thing_ that a Forem creator will need to set up 😸 
Additionally, this PR:
Closes https://github.com/forem/InternalProjectPlanning/issues/90.
This PR removes the formerly required `tagline` input from the "required" set of SiteConfig options...
...and …

Do not require SiteConfig.tagline

---

app/models/article.rb
app/models/comment.rb
app/views/admin/configs/show.html.erb
spec/models/article_spec.rb

This makes our spam detection more sophisticated matches by interpreting the string as a regex... It's also creates more potential for mistakes, so we will need to ensure this is used carefully.
This PR also fixes some issues with missing closing `div`s caused by another PR which had an improperly-resolved merge conflict.

Allow pattern match for spam terms

---

app/controllers/articles_controller.rb
app/services/users/approved_liquid_tags.rb
spec/services/users/approved_liquid_tags_spec.rb

Move a method used at articles_controller to a service.

Move method #approved_liquid_tags to user service

---

app/controllers/concerns/verify_setup_completed.rb

UI tweak to make this step mandatory. Closes https://github.com/forem/InternalProjectPlanning/issues/108
Covered here: https://github.com/forem/forem/blob/a282994e24210edde865c03b306e2e8725927746/spec/system/admin/admin_manages_configuration_spec.rb#L13-L18

Add logo_svg to mandatory config fields

---

app/controllers/admin/users_controller.rb
app/views/admin/users/_reports.html.erb
app/views/admin/users/edit.html.erb
spec/requests/admin/users_spec.rb

It looks like this code got mixed up in a rebase I did and was removed from the Admin UI. 😞 This PR adds the "Recent Reactions" section _back_ to the Admin Users' UI (`/admin/users/:id/edit`). 
Additionally, this PR: 
- Adds all related logic that makes the negative reaction reports render correctly (`#set_related_reactions` in the `Admin::UsersController`)
- Adjusts the JS in `_reports.html.erb` to target the `#reports-row` rather than the `#reactions-row`
- Adds tests for both "Recent Reactions" and "Recent Reports" to `/spec/reqeusts/admin/users_spec.rb`
N/A
- To QA these changes, please ensure that you have an `admin` role and navigate to `/admin/users/:id/edit`. Ensure that the "Recent Reactions" section exists above the "Recent Reports" section:
- Toggle the "Recent Reactions" …

Add Recent Reactions to the Admin Users' Page

---

app/assets/javascripts/base.js.erb

Anchors are not currently caught by the router
closes #10234 
Related to #10238
- Go to [this post](https://dev.to/eduherminio/waiting-in-arduino-ii-millis-function-to-the-rescue-33k6#going-back-to-our-case-study)
- Click on `case study` link
- See anchor be picked up
N/A

Add scroll to Anchor

---

docs/getting-started/db.md

Update default admin password in documentation
#10620
N/A
N/A

Change admin password in docs

---

app/javascript/chat/__tests__/channels.test.jsx
app/javascript/chat/channels.jsx

This PR generalizes the Connect "welcome message" and settings tab in the bottom left of Connect by removing references to DEV. Additionally, this PR updates the Connect spec to handle these changes.
Relates to an internal issue.
To QA these changes please navigate to `/connect` and make sure that both the "welcome message" and settings nav tab look good and do not reference "DEV"!
**Before**:
**After**:
N/A

Generalize Connect "Welcome Message"

---

app/views/shell/_top.html.erb
docs/technical-overview/compatibility.md
docs/technical-overview/readme.md

This PR creates more explicit machine-consumable meta tags that can be used within the forem ecosystem to make things explicitly known about a Forem's information and preferences
These tags can be used by a browser or extension to know that it is on a Forem page. This could allow an extension to prompt the user to add the page they are on to their sidebar. This is meant to remove the need for a centralized list of forems that meet the criteria to be used with the extension. We may want to look for additional cues to ensure a forem is compatible with being added.
A hypothetical future tag could be `forem:listed` to dictate whether it would want to be listed in public forem directories or not.

Add forem meta tags

---

db/migrate/20201009040438_remove_twitch_columns_from_user.rb
db/schema.rb

Follow up to #10732, this PR removes the columns from the `users` table.
n/a
n/a

Remove Twitch-related columns from users table

---

app/assets/stylesheets/base/layout.scss
app/assets/stylesheets/base/main.scss
app/assets/stylesheets/scaffolds.scss
app/views/articles/search.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/invitations/edit.html.erb
app/views/listings/edit.html.erb
app/views/listings/new.html.erb
app/views/pages/_placeholder.html.erb
app/views/pages/code_of_conduct.html.erb
app/views/pages/contact.html.erb
app/views/pages/information.html.erb
app/views/pages/markdown_basics.html.erb
app/views/pages/privacy.html.erb
app/views/pages/report_abuse.html.erb
app/views/pages/show.html.erb
app/views/pages/sponsors.html.erb
app/views/pages/terms.html.erb
app/views/users/edit.html.erb

This PR is another attempt to help Crayons become standalone gem soon. It also provides bunch of classes missing for https://github.com/forem/forem-app/pull/6
This PR should not affect visually any views - it's just adding few classes and renaming others.

Preparing Crayons to be a gem

---

app/views/onboardings/_task_card.html.erb

Adding aria attributes to welcome dialog to help screen reader users
1. Signup as new user to the app
2. Go to home feed
3. Try to navigate the welcome dialog with keyboard and screen reader

Adding role and aria labels to welcome dialog help screen readers

---

spec/system/articles/user_creates_an_article_spec.rb

This test keeps failing for unknown reason, as it's not a core feature, we can temporarily disable the test and investigate, to avoid holding back the CI pipeline
See https://travis-ci.com/github/forem/forem/jobs/398306508 for example

Disable flakey Runkit test

---

app/controllers/admin/configs_controller.rb
app/helpers/application_helper.rb
app/javascript/admin/controllers/config_controller.js
app/lib/constants/site_config.rb
app/models/site_config.rb
app/services/authentication/providers.rb
app/views/admin/configs/show.html.erb
app/views/articles/_sidebar_additional.html.erb
app/views/devise/registrations/_registration_form.html.erb
app/views/devise/shared/_authorization_error.html.erb
spec/requests/admin/configs_spec.rb
spec/system/authentication/user_logs_in_with_facebook_spec.rb
spec/system/authentication/user_logs_in_with_github_spec.rb
spec/system/authentication/user_logs_in_with_twitter_spec.rb

I had to read a bunch of code, but this seemed too easy. :thinking: 
This should allow a Forem admin to check a box and disable all social authorization providers, which will mean users can only join via invitation.
Closes: https://github.com/forem/InternalProjectPlanning/issues/115
This PR builds on the stuff @benhalpern did here: https://github.com/forem/forem/pull/9294
Adds a checkbox to config that disables the auth providers input when checked:
This is what you see if you try to create an account:

Allow Forem admins to enable an invite only mode.

---

spec/requests/admin/configs_spec.rb
spec/system/authentication/user_logs_in_with_facebook_spec.rb
spec/system/authentication/user_logs_in_with_github_spec.rb
spec/system/authentication/user_logs_in_with_twitter_spec.rb

These changes didn't get pushed to https://github.com/forem/forem/pull/10758 before it was merged.
https://github.com/forem/forem/pull/10758

Remove code setting SiteConfig values in specs

---

README.md

- [ X] Documentation Update
Updating the ReadMe to include my name on the core-team per my Role-Specific on-boarding doc.
- [X ] no, because they aren't needed
- [ X] readme

Adding name to core-team per my on-boarding doc

---

app/views/admin/configs/show.html.erb

The big thing is not allowing dashes, but it probably makes sense to just match the restrictions on tags elsewhere.
Closes: https://github.com/forem/InternalProjectPlanning/issues/129

Add input validation for sidebar tags config

---

spec/services/articles/feeds/basic_spec.rb

This spec has failed quite a few builds (example: https://travis-ci.com/github/forem/forem/jobs/398925392) and based on what the Basic Feed class actually does I dont think this is even testing the correct thing. Commenting it out to unblock deploys until we can get it fixed.

Comment out Flaky Basic Feed Spec

---

app/assets/stylesheets/base/main.scss
app/assets/stylesheets/components/header.scss
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/components/Header.jsx
app/javascript/packs/articleForm.jsx
app/views/articles/_v2_form.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_logo.html.erb
app/views/layouts/_top_bar.html.erb
app/views/layouts/admin.html.erb

This PR does few things:
- it helps generalize the logo_svg and drops all DEV-only styling we used to have for our logo
- it takes #10826 a step further and brings similar fix to other places where we use logo (footer and `/new`)
- it **prepares** our codebase to make `logo_svg` **not**  required field: https://github.com/forem/InternalProjectPlanning/issues/83 - in that case it would display a `community_name`. To be more specific: this PR prepares frontend part of our codebase to be able to serve `community_name`. **This PR does not make `logo_svg` optional field** - we'll have another PR for that (see linked issue above).
- #10826 
- https://github.com/forem/InternalProjectPlanning/issues/53
- https://github.com/forem/InternalProjectPlanning/issues/83
Update our `logo_svg` field in …

Logo updates

---

docs/faqs.md

While reviewing #10694, I needed to add credits to my account. I went to the documentation and copy pasted the commands, but it gave a syntax error in the rails console. This PR fixes the commands to run in the rails console to add credits to a user's account.
Before
After

Fixed documentation and command for adding credits to a user's account for local development.

---

app/views/pages/privacy.html.erb

Remove hardcoded Dev Community from privacy policy
https://github.com/forem/InternalProjectPlanning/issues/144
1. Go to privacy policy page and see that the changes have been made

Remove hardcoded Dev Community from privacy policy

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/unlocks/new.html.erb

Noticed a deprecation warning while reviewing a few PRs.
https://github.com/heartcombo/devise/pull/4616
No UI changes as far as I can tell.

Replace deprecated Devise method

---

app/assets/stylesheets/chat.scss
app/javascript/chat/RequestManager/RequestManager.jsx
app/javascript/chat/channelRequest.jsx

- When users click on the request center in mobile UI.  chat text is shown override with request center UI. 
- Closes #10823 

fix request center UI

---

app/views/service_worker/index.js.erb

We need to add `/images` as a path exception in SW
n/a
n/a, test on production!
n/a

Ignore /images in service_worker

---

docs/backend/auth-facebook.md
docs/backend/auth-github.md
docs/backend/auth-twitter.md
docs/getting-started/config-env.md
docs/installation/containers.md
docs/installation/linux.md
docs/installation/mac.md
docs/installation/windows.md

-  [x] Documentation Update
While trying to set up the project locally I had trouble understanding some parts of the documentation. 
I specifically added small pieces to the auth documentation about the fact that the variables should be in the `.env` file. I understand that it might be clear for those of us with a bunch of experience but hopefully it can help out juniors like me as well.
I also saw references to `Envfile`, and while maybe this word was used to refer to the `.env_sample` file, I think it might be clearer to specifically reference that file then. 
#10849 
-

replace Envfile with env_sample and reference env file in auth docs

---

spec/system/authentication/user_logs_in_with_email_spec.rb

Adds a system test for email login. That's it: that's the PR!

System test

---

docs/technical-overview/feed.md

Update the documentation for "the feed" to clarify what `feed style` and `feed strategy` are.
N/A

Update feed docs

---

app/controllers/image_uploads_controller.rb
app/javascript/article-form/actions.js
app/javascript/article-form/components/ArticleCoverImage.jsx
lib/data_update_scripts/20201015190914_update_article_main_image_path.rb
spec/lib/data_update_scripts/update_article_main_image_path_spec.rb

We are unnecessarily altering the image path on upload. Please see below for the explanation.
This also serves as a bugfix for forem-cloud app.
https://github.com/orgs/forem/projects/11#card-47453148
n/a
n/a

Store Article's main_image path unprocessed

---

app/javascript/chat/__tests__/compose.test.jsx
app/javascript/chat/compose.jsx

- In connect input. When user press `shift`+ `enter`. it was clearing the text input. 

fix bug on chat input

---

app/assets/stylesheets/chat.scss

Fixes an issue where a user could not scroll through messages in Connect.

Added back overflow-y scroll to allow users to scroll through chat messages.

---

app/assets/stylesheets/base/main.scss

This PR will prevent shrinking the logo on smaller resolutions.
Before: 
After:

Disable logo resizing on small resolutions

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/controllers/async_info_controller.rb
app/views/layouts/_nav_menu.html.erb

This PR will add a link to admin section if user is an admin...
- Closes https://github.com/forem/InternalProjectPlanning/issues/173

Adding admin link for admins

---

app/controllers/async_info_controller.rb
app/controllers/reading_list_items_controller.rb
app/models/user.rb
db/migrate/20201017160628_add_last_reacted_at_to_user.rb
db/schema.rb
spec/requests/reading_list_items_spec.rb

Revert "Fix reading list counter"

---

app/mailers/application_mailer.rb
app/mailers/devise_mailer.rb
config/initializers/devise.rb
spec/mailers/devise_mailer_spec.rb
spec/mailers/notify_mailer_spec.rb

I'm not sure this is _the entire fix_ but it's something _like_ this.
Fixes https://github.com/forem/InternalProjectPlanning/issues/141

Fix email sender and url issues

---

docs/tests/codeclimate.md

Combined two sentences in the last paragraph of Code Climate to fix sentence fragments.

Fix grammar error in Code Climate

---

app/controllers/resource_admin/users_controller.rb
app/dashboards/user_dashboard.rb

This change will add "registered" and "registered_at" to the Administrate views in case admins need to fix new users manually in a pinch.

Add registered fields to resource_admin

---

README.md

Adds an acknowledgment section and includes a mention of the [Twemoji Project](https://github.com/twitter/twemoji)

Add Acknowledgment section

---

app/models/user.rb
spec/requests/user/user_settings_spec.rb

Add aliases for mod_roundrobin_notifications + email_follower_notifications to user model #6892

---

app/policies/video_policy.rb
app/views/dashboards/_actions.html.erb
app/views/dashboards/_actions_mobile.html.erb
spec/requests/dashboard_spec.rb

As a Forem admin, video upload does not work so I do not want videos highlighted to my community or have it appear as an option to my members.
**Ideal Solution**
One day, we'll figure out whether or not we can support native video for all Forems but until then, let's:
- remove the 'upload a video' button from /dashboard
**Additional Context:**
We'll want to continue supporting videos on DEV so want to note that the upload button should still exist on DEV.
In [this PR](https://github.com/forem/forem/pull/10954) I created a config variable to determine whether to enable videos for a Forem. I do not expose it through the config UI since admins don't need control over this at the moment. We simply want to disable it for all Forems except DEV.
Here I've added the additional check to not show …

Disable ability to upload videos on *some* forems Part 2

---

public/404.html

This change makes the 404 page as generic as possible.
I think we should follow this up with a PR to make 404 pages dynamic (with Forem specifc copy) or even cuztomizable via `/admin/pages`. There are some technical considerations to that, but this is currently being prioritized as an urgent fix for some upcoming Forem launches, so I think we should start with this change.
Closes https://github.com/forem/InternalProjectPlanning/issues/178
After:

Make 404 page generic

---

app/javascript/chat/ChatChannelSettings/ChatChannelSettings.jsx
app/javascript/chat/ChatChannelSettings/ChatChannelSettingsSection.jsx
app/javascript/chat/ChatChannelSettings/ModFaqSection.jsx
app/javascript/chat/__tests__/chat.test.jsx
app/javascript/chat/__tests__/chatChannelSettings.test.jsx
app/javascript/chat/__tests__/content.test.jsx
app/javascript/chat/chat.jsx
app/javascript/chat/content.jsx
app/javascript/packs/Chat.jsx

We cannot include database-fetched elements in JavaScript because it will be compiled before the database is available. The simplest fix here was to slightly change the functionality to direct the user to the `/contact` page, which is a better solution anyway, IMO....
If we need to fetch something from the DB we can do so through the same means we otherwise pass info to the page. Ultimately this is a tiny change which affects a lot of files due to how Preact passes data.

Remove unnecessary email call-to-action

---

app/black_box/black_box.rb

This is just one little feature to ensure posts older than a week sink further. We currently have a DEV post that is "beating" the algo, and I think this will help.
We can circle back on a more sophisticated approach overall, but for now let's make this fix.

Small adjustment to blackbox.rb

---

app/views/users/_liquid.html.erb
lib/data_update_scripts/20201013205258_resave_articles_and_comments_for_imgproxy.rb
lib/data_update_scripts/20201019163242_resave_articles_and_comments_for_imgproxy.rb
lib/data_update_scripts/20201020215535_resave_articles_and_comments_for_imgproxy.rb

Resolves https://github.com/forem/InternalProjectPlanning/issues/154
This really doesn't change any functionality
n/a

Prefer inline svg over image_tag in User Liquid

---

app/views/users/_liquid.html.erb

We had a quick conversation and realized the future of this feature's design does not need these icons. We were having some consistency issues, so this is the expedient solution.

Remove social icons from user liquid tag

---

app/views/articles/_sidebar_nav.html.erb
app/views/articles/_sidebar_nav_link.html.erb

Remove extra space + add back social media icons.
https://github.com/forem/forem/issues/10980#issuecomment-713418826

Sidebar: social media icons + spacing

---

app/views/users/_profile.html.erb

#10733 introduced a bug causing styling issue on form fields in `/settings/profile`. This PR fixes it.
- #10733 
**Before:**
**After:**

Profile forms styling

---

spec/requests/stories_index_spec.rb

We have a test failing due to another fix for the home feed. This should fix it.

Fix spec that relied on hardcoded number

---

app/controllers/admin/configs_controller.rb
app/lib/constants/site_config.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb
spec/requests/admin/configs_spec.rb

[This PR](https://github.com/forem/forem/pull/10958) included some basic admin functionality which will help Forems ensure they can toggle their score minimums to the needs of the community. It was worth merging to create a new more appropriate default, but this PR follows up with adding the interface functionality needed.

Add interface for feed number config

---

app/views/layouts/_nav_menu.html.erb

The newly added admin link doesn't 100% work properly because the admin section is running a different "shell" than the user facing part so InstantClick kind of freaks out. If you click again it works.... So it could go unnoticed and thought of as an issue with a slow request, but it's actually broken if we don't skip instant click here.

Fix admin link

---

app/views/layouts/admin.html.erb

This PR adds a link to the Forem Admin Guide to the /admin interface (in the header). It uses the same styles as the Log In/Create Account buttons on the frontend of the site.
Closes: https://github.com/forem/InternalProjectPlanning/issues/203

Add a link to the Forem Admin Guide to /admin

---

app/lib/constants/site_config.rb

This PR adds a constant, `SVG_PLACEHOLDER`, to `sitr_config.rb` in place of multiple strings. This standardizes the file a bit more and makes it easier for future contributors to change this value.
Relates to PR #10992 
To QA this change, make sure that all of the checks pass and Travis builds green. 
Nope!

Adds SVG_PLACEHOLDER Constant to Site Config

---

config/initializers/reserved_words.rb

An incoming Forem admin is interested in this username.

Remove "mac" from reserved words

---

app/views/layouts/admin.html.erb
app/views/shell/_top.html.erb

Quick fix. This issue definitely highlights some improvements we could stand to make on end-to-end testing to avoid these kinds of things.

Fix honeybadger key typo

---

spec/system/articles/user_visits_an_article_spec.rb

I have been tearing apart this spec all day and cannot for the life of me get the timestamps to not match. I have even tried adding some logging and running it in Travis a few times to no avail. In an effort to try and get more information here I have added a few log lines to one of the flaky specs and uncommented it. IM SORRY, I know, bad Molly adding `puts` but I wouldn't do it if I wasn't out of ideas. I added an additional comment so anyone looking there due to a failure knows its flaky. 
https://github.com/orgs/forem/projects/6#card-47746166

Additional Logging for user_views_an_article Spec

---

.rubocop.yml
app/controllers/admin/configs_controller.rb
app/lib/constants/site_config.rb
app/models/campaign.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb
app/views/articles/_sidebar_campaign.html.erb

Closes: https://github.com/forem/InternalProjectPlanning/issues/191
This has a default value set to the old hardcoded value, so no action should be necessary.

Add campaign call to action to SiteConfig

---

app/views/users/_profile.html.erb

In #10982 I've introduced styling fix for text fields. This PR takes it step further and fixes color type fields and makes them interactive as in the past. It also brings the `field.description` to the frontend.
- #10982 
- #10733 
**Before:**
**After:**

Fix for color fields in settings

---

app/views/users/_profile.html.erb
db/schema.rb

This PR brings back placeholder attribute to new profile fields.
**Before:**
**After:**

Missing placeholders on profile settings

---

app/javascript/chat/__tests__/compose.test.jsx
app/javascript/chat/chat.jsx
app/javascript/chat/compose.jsx

Every small enhancement I would say but this PR made Compose placeholder dynamic.

🚀Feature: Making Compose's Placeholder Dynamic

---

app/views/pages/crayons.html.erb

This PR drops one of the assets I've been using in /page/crayons for testing purpose. Another PR will soon deprecate usage of that asset entirely so I wanted to clean up my playground first.
No testing required.

Drop asset from /page/crayons

---

lib/tasks/add_navigation_links.rake

- Chore 
Remove an inapplicable comment in rake task

Remove inapplicable comment in rake task

---

db/seeds.rb

It is better to be explicit here.

Explicitly set a resource type in seeds

---

app/javascript/article-form/components/Help.jsx

I think? Updates user-facing text, but that documents how to use the product.
Clarify that multiple tags should be comma-separated. Quickly resolves some user confusion (mine, probably others). Added to the help text in the sidebar, not the placeholder text, for greater accessibility. (Screenreader users don't see the placeholder; the placeholder disappears once you've started typing/have your first tag written and are wondering how to get the second one to work.) 
#11048 
Make sure the text looks okay on the new post page; I don't know why it wouldn't, but also, I did not go through the full setup & run this locally.

#11048 - clarify how to add multiple tags to a post

---

.github/PULL_REQUEST_TEMPLATE.md

Our current bullet point “no, because it doesn’t need any” can introduce a bit of an issue—it’s easy to check that box without critically thinking about whether a change actually does or doesn’t need tests. I see this sometimes with contributor PRs as well as our own team PRs occasionally.
I propose that instead of “no, it doesn’t need any”, we edit that bullet point and instead have it read, “no, and this is why: ____”. This would help prompt us all to think a bit deeper about whether testing a code change is actually possible/doable/necessary before checking “no” in the template. I also think it would help give some context to the PR reviewers as well! 
It also capitalizes all of the checkbox "options", and rewords the `No, because I need …

Update PR template's "has tests?" section

---

app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/tooltips.scss
app/assets/stylesheets/crayons.scss
app/views/pages/crayons.html.erb

This PR adds basic tooltips to Crayons as well as _required_ indicator to form elements.
It's not really implements anywhere so you can't really test it, except looking at `/page/crayons`.

Tooltips & Required fields

---

app/assets/stylesheets/base/layout.scss

This PR fixes #11093 making _zen mode_ a bit more smarter..
- Closees #11093 
**Before:**
**After:**

Zen mode fix on profile view

---

spec/helpers/application_helper_spec.rb
spec/helpers/social_image_helper_spec.rb
spec/labor/badge_rewarder_spec.rb
spec/labor/bufferizer_spec.rb
spec/lib/url_spec.rb
spec/rails_helper.rb
spec/requests/admin/configs_spec.rb
spec/requests/api/v0/health_checks_spec.rb
spec/requests/api/v0/users_spec.rb
spec/requests/articles/articles_show_spec.rb
spec/requests/async_info_spec.rb
spec/requests/buffer_updates_spec.rb
spec/requests/dashboard_spec.rb
spec/requests/ga_events_spec.rb
spec/requests/incoming_webhooks/mailchimp/unsubscribe_spec.rb
spec/requests/partnerships_spec.rb
spec/requests/registrations_spec.rb
spec/requests/shells_spec.rb
spec/requests/stories/feeds_spec.rb
spec/requests/stories_index_spec.rb
spec/views/comments/_comment.html.erb_spec.rb
spec/views/dashboards/show.html.erb_spec.rb
spec/workers/broadcasts/send_welcome_notifications_worker_spec.rb

There are a few places that will probably require a closer look, but this gets rid of most of the places that we alter SiteConfig in the test suite.

Do not set SiteConfig values in specs

---

config/fastly/snippets/safe_params_list.vcl

We use the `email` param in one flow in email-based sign up we currently _don't_ use on DEV, but other Fastly-oriented Forems are encountering a subtle bug here.

Add email to safe_params

---

app/controllers/admin/pages_controller.rb
app/views/admin/pages/_form.html.erb
spec/system/admin/admin_manages_pages_spec.rb

We should be rending error messages here and this form needs some client-side validation.
Closes https://github.com/forem/InternalProjectPlanning/issues/232

Improve error messages and validation for admin pages

---

docs/getting-started/config-env.md

Backend guide link currently leads to a Github 404 page. This commit fix the issue and redirects to the correct backend guide link

Fix backend link in config-env.md

---

docs/readme.md

The links on the [documentations](https://github.com/forem/forem/tree/master/docs/) are not correct

Updated docs README URL

---

db/schema.rb

In #11084 there were some things changed in the schema that should not have been. This fixes those.

Schema Fix:Removed accidentally added changes

---

app/controllers/admin/articles_controller.rb
spec/requests/admin/articles_spec.rb

**Issue**:
> We seem to be unable to mark a post as approved via /admin. Instead, we're forced to use /resource_admin.
**Solution**:
This PR gives Admins the ability to mark posts as `published` from `/admin/articles`. To make this work as expected, I refactored the `#update` method in the `Admin::ArticlesController`. Additionally, I added additional tests to the `articles_spec.rb` and refactored the existing tests a little.
Closes https://github.com/forem/InternalProjectPlanning/issues/231
**To QA these changes, first ensure that you have an `admin` role, and then please do the following**:
- Navigate to `/admin/articles`:
- Mark an article of your choice as `approved` and ensure that it updates properly:
- Update other fields on the article to ensure that everything works as expected:
- …

Mark Posts as Published in Admin Articles

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/settings.scss
app/assets/stylesheets/themes/hacker.scss
app/assets/stylesheets/themes/minimal.scss
app/assets/stylesheets/themes/night.scss
app/assets/stylesheets/themes/pink.scss

In the integrations page some colors are statics, so doesn't change with the theme, that's make some colors doesn't match with the theme and text color.
Fixes #11052
Check if the [integrations page](https://dev.to/settings/integrations) show colors relationated with the theme with hover and at select a github project.

Fix: Change static color to theme variable

---

app/models/feedback_message.rb

While researching something for an issue today I had a look at our `FeedbackMessage` model and found a method that seems to be completely unused:
```
rg capitalize_status; echo $status
1
```
n/a
Nothing I can think of, no spec seems to reference this either.

Remove unused method

---

app/controllers/collections_controller.rb
spec/system/collections/user_views_collections_spec.rb

I added a join and distict method to the collections controller index method to only get collections that contain articles. 
Closes https://github.com/forem/forem/issues/9658
To test this functionality, you can create an article, add a series to that article. Save the Series/article, and create another article and a new series. 
After saving the new series/ article, replace the second article series with the first series created.
There should now be one series without any articles. 
Go to the series index view, by clicking on the series of the article, then clicking the "back to all series" link. Here, you should only see the first series created with the two articles.
No

Fix Bug: Series index page showing series with 0 articles -#9658

---

Containerfile

The Containerfile CMD instruction needs some spaces ;)
(Or maybe it doesn't! ... but it has some spaces at the beginning! Consistency is important!)

Improve Containerfile CMD readability

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/assets/javascripts/utilities/showUserAlertModal.js
spec/system/comments/user_fills_out_comment_spec.rb

Here's a non-preact implementation of the same modal I sketched out in https://github.com/forem/forem/pull/11023. After trying (and mostly failing) to integrate the Preact component with arguments on non-Preact pages, I went back to the drawing board and came up with a plain on Javascript implementation. I've hooked it up to the comments page: making too many comments in a short amount of time now triggers this modal.
Concept: we want to create reusable messaging to alert users about exceeding rate limits or user interaction limits. Right now these limits are indicated by backend throwing HTTP status code 429 RATE LIMIT EXCEEDED, but it's up to the frontend to do something with it. Some UIs catch this error and show it in an alert, others just throw it away and don't inform the user. …

Rate Limit Modal - Comments

---

.gitpod.dockerfile

The Elasticsearch source tarball and checksum should be removed once the
files were extracted successfully.
cc #11253

Clean up Gitpod Dockerfile Elasticsearch tarball

---

app/views/users/edit.html.erb

This updates the organization settings dropdown to something much nicer. I'll let @forem/design have the final say but figured this would be a quick and easy update. :)

Update organization <select> to use Crayons

---

app/models/role.rb
app/views/admin/users/_activity.html.erb

This seems like important information to be showing admins.
Before:
After:

List single_resource_admin resources in the UI

---

.travis.yml

I recently updated our Travis deploy process to deploy to DEV and BenHalpern Community. However, the deploys run synchronously instead of in parallel which would be more ideal. This is my attempt to run them in 2 parallel jobs [based off of these Travis docs](https://docs.travis-ci.com/user/deployment/script/#passing-arguments-to-the-script).

Deploy In Parallel to Heroku Apps

---

spec/system/onboardings/user_completes_onboarding_spec.rb

This Spec appears to be failing [on the master branch](https://travis-ci.com/github/forem/forem/jobs/428276212) and locally for me. It appears that [this spec was just added](https://github.com/forem/forem/pull/11259) but the initial build was green. I am not sure why it is causing issues now but this will comment it out until we get a chance to fix it.

Comment out Flaky Onboarding spec

---

app/models/data_update_script.rb

Remove unnecessary where method and Pathname initialization.
About where method, it was originally introduced to select ids of enqueued scripts, so it's no longer needed with enqueued method.

Refactor DataUpdateScript to make its code simpler

---

docs/getting-started/pull-request.md
docs/installation/containers.md
docs/self-hosting.md

The main concern here was the command `docker-compose run web rails data_updates:run`. There is no named instance `web` in docker compose. Changing it to `rails rails` reads poorly but executes. Also a side note if someone already has a running instance `docker-compose exec rails rails data_updates:run` is faster as it doen't have to boot a new instance.
I was confused with the language use **stand up** I'm pressuming it's meant to be **start up** but wasn't sure if this is some community language I'm unfamiliar with.
> from standing up new communities.

Docs: Fix docker-compose instructions

---

docs/installation/containers.md

Reordered and reworked the Setting Up Forem section about the `.env` file for clarification.
11163
Proofreading just in case.
N/A

11163 - documentation - installation/containers

---

app/javascript/actionsPanel/actionsPanel.js
app/javascript/modCenter/singleArticle/index.jsx
app/javascript/packs/flagUserModal.jsx

"Flag user" button was working only first time in /mod route. This PR fixes the way event listener is attached to that button similar to "Unpublish Article" button fixing this issue.
Closes https://github.com/forem/forem/issues/10605
1. Go to /mod
2. Open article flag user
3. Open another article and flag another user 
4. Go to home feed
5. Click on an article
6. Flag the author of that article

Fixing flag user modal

---

app/views/admin/configs/show.html.erb
app/views/comments/_form.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/admin.html.erb
app/views/shell/_top.html.erb

This will ensure some optimized images are called instead of the raw URL provided.

Wrap siteconfig images in optimizer

---

app/assets/javascripts/initializers/runtime.js
spec/system/podcasts/user_visits_podcast_episode_spec.rb

We've had issues in the past where mobile apps have problems being recognized as "trusted" by reCaptcha, this is an attempt to fix that. The ForemWebView refactor makes sure the User Agent repects [the standardized format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent):
```
User-Agent: Mozilla/5.0 (<system-information>) <platform> (<platform-details>) <extensions>
```
In this case we're adding `ForemWebView` as an extension of the default User Agent similar to this (see the very end of the string):
```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1 ForemWebView/0.2.1
```
This is not easy to QA. My recommendation would be to open your local environment and play any podcast …

Makes Runtime.js detect the generalized ForemWebView User Agent

---

app/controllers/listings_controller.rb
spec/requests/listings_spec.rb

Category in listing modal did not show up when refreshed
Closes https://github.com/forem/forem/issues/11302

Fixing missing category in listing modal

---

app/assets/stylesheets/admin.scss
app/javascript/admin/controllers/config_controller.js
app/views/admin/configs/show.html.erb

I stupidly left these changes out of [their intended PR](https://github.com/forem/forem/pull/11185). This PR fixes the omission.
- PR that these changes were erroneously omitted from: https://github.com/forem/forem/pull/11185

[Team Email Login] Make final Auth Provider Refactor code changes

---

app/services/feeds/import.rb

This should give us a bit more visibility and answer the question about how fast each section roughly is
#10998
#11234

Add custom instrumentation to Feeds::Import

---

app/views/articles/show.html.erb
spec/views/articles_spec.rb

The canonical URL link on articles doesn't show up if the article has been updated, with the "Originally published at" text being replaced with the "Updated on" text instead. I'm guessing this behavior wasn't intended since the related issue is marked as a bug.
This fix shows both canonical url and update date at the same time.
Fixes #10028
To test, either add a canonical URL to a preexisting article that is at least one day old, or update an article that is at least one day old that already has a canonical URL.

Show canonical URL on article even after it has been updated

---

app/assets/javascripts/initializers/initializePodcastPlayback.js
app/assets/javascripts/initializers/initializeVideoPlayback.js

This PR tweaks the support for the message handling between the native mobile players and the web UI for both Podcasts & Video Player.
It also fixes an error that prevented Ahoy events to work for the mobile native players
[This is the related PR from ForemWebView-ios](https://github.com/forem/ForemWebView-ios/pull/11)
The web browser capabilities should continue to work as expected, for both Podcasts and Videos.
These are videos of the integration working in the mobile apps using the fixes in my local environment:
- [Android](https://drive.google.com/file/d/1090G3Jky5fLz5zRWs3Al6AbmdBQlQVL2/view?usp=sharing)
- [iOS](https://drive.google.com/file/d/1u353fF9en9WdxCUcRPESFFysZOoAB8IY/view?usp=sharing)

Podcast + Video player native bridge small refactor

---

README.md

This adds me to the Forem "core team" list, as part of my employee onboarding tasks.

Add "andygeorge" to Core team list

---

app/assets/stylesheets/admin.scss
app/views/admin/configs/_auth_provider_settings.html.erb
app/views/admin/configs/show.html.erb

Update styles for Auth Providers in admin/config:
- Update row padding
- Update config form markup and padding
This comes after https://github.com/forem/forem/pull/11185#pullrequestreview-525421905

Update styles for Auth Providers in admin/config

---

app/models/site_config.rb

Noticed these minimum/maximum values were flipped.
We can probably treat this as an Account Management task to let any currently-live Forems that they may want to update this themselves (and give them more instruction on how the feature works).

Flip values of email digest min/max

---

app/lib/constants/site_config.rb

Simple typo fix in the anti-spam placeholder terms

Fix typo in placeholder anti-spam terms

---

app/javascript/shared/components/useKeyboardShortcuts.js

I missed this when merging #11113. It adds a timeout with a default value of 500ms, but this is only supposed to be for chained keyboard strokes. This PR sets the timeout to 0ms by default. We'll look into fixing the actual issue in another PR (see https://github.com/forem/forem/pull/11363#issuecomment-725010112)
Fixes a regression in:
- #10468
- #10878 
- #11116
1. For any of the keystrokes supported in the above mentioned tickets, there should no longer be a 500ms delay.

Set default timeout to 0 ms for keyboard shortcuts.

---

app/views/admin/configs/show.html.erb
app/views/admin/profile_fields/_grouped_profile_fields.html.erb
app/views/admin/profile_fields/_ungrouped_profile_fields.html.erb
app/views/admin/shared/_card_header.html.erb

I noticed we weren't using crayons in the card headers on the Site Config page.
We are also using that shared partial in another view outside of Site Config, so I moved the partial into the admin/shared directory.

Use crayons buttons in card headers

---

spec/system/onboardings/user_completes_onboarding_spec.rb

Failed again despite some of the changes made: https://travis-ci.com/github/forem/forem/jobs/433323181
The js is messing somehow with the sign in.

Comment out Still Flaky Onboarding spec

---

.travis.yml

I suddenly recall, from my previous attempt of toying with Travis, that jobs with identical names are parallelized. To reduce the confusion, they also provide a `name` feature so we can distinguish those builds.
n/a
No QA necessary, but take a look at my POC at https://github.com/forem/forem/runs/1385783569 to see that it is indeed working. That build is from 6dd67a3 which disabled all test and remove keys for deployment.
I will closely monitor the deploy after this PR is merged

Parralelize Travis deploy

---

app/javascript/crayons/Select/__stories__/Select.stories.jsx

I was not sure what to check so I checked "documentation update"
Select option was missing in story book this pull request adds that
closes https://github.com/forem/forem/issues/11339

Adding select option to storybook

---

app/controllers/admin/configs_controller.rb
app/helpers/authentication_helper.rb
app/javascript/admin/controllers/config_controller.js
app/views/admin/configs/_auth_provider_settings.html.erb
app/views/admin/configs/show.html.erb
spec/helpers/authentication_helper_spec.rb
spec/requests/admin/configs_spec.rb

I worked off of Josh's branch called `joshpuetz/email-login-always-on` by running the command `gh pr checkout joshpuetz/email-login-always-on` but I did not know how to push directly to his branch 🤷‍♀️ 
So I'm cutting this PR to merge my updates to his work.
- Josh's Original Work: https://github.com/forem/forem/pull/11307
I briefly explain what my changes accomplish in this video:
https://www.loom.com/share/429ab4c7f84042198bde88c254b52279
None

Some refactoring around fact that Email Login is now always on

---

app/javascript/admin/controllers/modal_controller.js
app/views/admin/profile_fields/_add_group_modal.html.erb
app/views/admin/profile_fields/_add_profile_field_modal.html.erb
app/views/admin/profile_fields/_edit_group_modal.html.erb
app/views/admin/profile_fields/_grouped_profile_fields.html.erb

Nothing special, just refactored some really redundant JS in these partials to a Stimulus controller.
You'll need to run `Flipper.enable(:profile_admin)` in your console to be able to see this UI.
A tiny UX tweak: Converted these to buttons instead of divs.
Before:
After:

Convert inline JS to Stimulus

---

jest.config.js

Our test coverage in the frontend has gone up a few points, so adjusting the coverage thresholds to reflect that and also so we don't dip in our coverage.

Bumped jest test coverage thresholds.

---

spec/system/admin/admin_awards_badges_spec.rb
spec/system/admin/admin_bans_or_warns_user_spec.rb
spec/system/admin/admin_creates_new_event_spec.rb
spec/system/admin/admin_deletes_user_spec.rb
spec/system/admin/admin_updates_tag_spec.rb

We are trying to be more consistent about this, iirc.

Use Rails path helpers in admin system specs

---

app/services/feature_flag.rb
spec/system/admin/admin_manages_profile_fields_spec.rb

Just adding a missing spec for this part of the admin UI.

Add system spec for profile fields

---

app/views/articles/tags/_sidebar.html.erb
app/views/moderations/mod.html.erb
app/views/podcasts/_form.html.erb

While reviewing another PR I noticed how the commit verification failed for the few issues signaled by erblint in this PR so I set out to address them

Fix small ERB linting issues

---

jest.config.js

For yet unknown reasons #10249 dropped code coverage on branches

Jest: Lower branches code coverage to 38 to unblock builds

---

spec/requests/stories_index_spec.rb

Using similar strategies to #11200 I combined some assertions to avoid setting up the same data over and over again to check for different things on the page in order to speed up this spec. 
BEFORE:
AFTER:

Spec Speed Up:Stories Index Spec

---

app/javascript/packs/homePage.jsx

Quick patch on this runtime error that doesn't seem to break the UX but is present in a lot of navigation.

Fix document.body.getElementById is not a function

---

lib/data_update_scripts/20201001173841_add_navigation_links.rb

Just noticed this on a brand new Forem and realized it was _probably_ a quick fix?

Change "use" to "Use" on Nav Link script

---

app/controllers/admin/configs_controller.rb
app/controllers/registrations_controller.rb
app/javascript/admin/controllers/config_controller.js
app/lib/constants/site_config.rb
app/models/site_config.rb
app/views/admin/configs/show.html.erb
app/views/shared/authentication/_email_registration_form.html.erb
spec/requests/admin/configs_spec.rb
spec/requests/registrations_spec.rb

In several cases, email address domains are a great way to restrict access to a certain Forem, whether it's a company-wide Forem, or perhaps one restricted to people with a `harvard.edu` email address, it's a pretty established pattern which has been requested.
In a lot of cases it can be used in conjunction with invitations to help ensure everyone that should have access to a Forem can most easily without adding extra process burden.
We've talked about this but I couldn't find a ticket.
This PR includes the _option_ to make public which domains are allowed. There are legit reasons for not displaying this info if it is private.
I will add to the admin guide after this is merged.
Yes. Add to admin guide.

Allow Forems to specify which domains are allowed for registration

---

app/assets/javascripts/utilities/buildArticleHTML.js

Uses template literals to more clearly interpolate a complex string in buildArticleHTML.js
1. Go to tag page (must have enough posts for infinite loading to kick in as this is what uses the `buildArticleHTML.js` method)
1. Scroll until infinite load populates more cards
1. Click on any card (title)
1. Go back
1. Click on any other card's white space (i.e. not the title link)
It should redirect correctly, unlike what we currently see for example in https://dev.to/t/javascript

Fixes a bug where the data-article-path was malformed and caused 404 links

---

app/javascript/Snackbar/Snackbar.jsx

Fixes the `displayName` property of the `<Snackbar />` component. I cam across this while investigating another issue.

Fix snackbar component displayName

---

app/models/tweet.rb
app/services/feeds/check_item_medium_reply.rb
app/services/feeds/check_item_previously_imported.rb
app/services/feeds/import.rb
app/services/rss_reader.rb

This is an attempt of extracting auxiliary services that are common between the two, they also shorten the length of the classes, making it easier to understand the content without getting lost in the minutiae
#10998

Refactor RssReader and Feeds::Import common parts: take 1

---

app/javascript/Search/Search.jsx
app/javascript/Search/SearchForm.jsx
app/javascript/onboarding/Onboarding.jsx
config/webpack/development.js
docs/frontend/debugging.md

This PR adds the Preact devtools to all our packs (webpack entry points) automatically when running in development mode. This enables folks to leverage the [Preact DevTools browser extension](https://preactjs.github.io/preact-devtools/).
This came about from investigations for #11463.
P.S.: This one's for you @vaidehijoshi!
There is no change to production code and the only thing this will enable is being able to see Preact components in the [Preact DevTools browser extension](https://preactjs.github.io/preact-devtools/).

Add Preact dev tools to development bundles

---

docs/installation/linux.md
docs/installation/mac.md
docs/installation/windows.md

Both DEV and Forems run on Redis 6.0. Even though it should work on 5 and 4, we're not sure about it and we can't provide support for those versions. Thus we should bump the mininum required version.

Recommend Redis 6 for Forem self installation

---

app/controllers/admin/articles_controller.rb
app/models/article.rb
app/views/admin/articles/_individual_article.html.erb
spec/models/article_spec.rb
spec/requests/admin/articles_spec.rb

Adds post `published_at` as an editable datetime select option in the admin side articles index/show views
Closes #10871 
#QA
Check out a published article in admin/articles list/show. Update the published_at date to something else and hit `Submit`. Confirm it has changed
#Additional changes
1. Because `published_at` is added as a rails datetime_select field to fulfil all kinds of datetime requirements, the #update logic in admin/articles controller had to be changed. The existing logic picked up individual values from permitted params, changing a few of them, before saving them But datetime select pushes params as `param(1i)`, `param(2i)` and so on, which doesn't sit well with extracting params. It is custom made to work with `model.create(permitted_params)` or …

Added published date as editable in admin articles list/show

---

app/views/users/_sidebar.html.erb

I was in this file and decided to fix this before I forgot. :upside_down_face:

Fix comment phrasing

---

app/services/profile_fields/add_base_fields.rb
app/services/profile_fields/add_branding_fields.rb
app/services/profile_fields/add_link_fields.rb
app/services/profile_fields/add_work_fields.rb
app/services/profile_fields/field_definition.rb

These were all defaulting to "left_sidebar" which interfered with my
work some and doesn't really reflect how these will probably be used.

Fix seed values for ProfileFields

---

.buildkite/pipeline.containers.yml
.github/CODEOWNERS
Containerfile
container-compose.yml
docker-compose.yml
scripts/build_containers.sh

This will bring multistage container builds to Forem for development, testing, and production container setups.

Multistage container builds

---

.buildkite/pipeline.containers.yml

I guess you can't use env vars for username and server.

Fix buildkite login to quay.io

---

.buildkite/pipeline.containers.yml

This will remove a dupe container block since we are going to run this pipeline on master branch pushes only in Buildkite specifically.

Removes this dupe container block 

---

README.md

Adds "phannon716" to the core team list in the README, as requested in onboarding docs.

Adds phannon716 to the Core team list

---

app/views/moderations/_mod_sidebar_left.html.erb

Update Moderator copy and links to make it a more useful experience for moderators. 
Closes https://github.com/forem/InternalProjectPlanning/issues/258

Update copy and links in Mod Sidebar

---

postcss.config.js
postcssconfig.js

Closes https://github.com/forem/forem/issues/11490
Hopefully this works :D 
- https://github.com/rails/webpacker/blob/master/lib/install/config/postcss.config.js
- https://github.com/csstools/postcss-preset-env#features
- https://stackoverflow.com/a/49629759/4186181
- https://github.com/MoOx/postcss-cssnext/issues/186#issuecomment-123304414

Attempt at disabling postcss-next warnings

---

.travis.yml

Have no idea if this will work, but what if Travis log limit is shared among parallel build stages?
Our build stages are exactly ideantical (the destination server is different) so we might be doubling the log size and pushing beyond [the 4MB log limit](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded)

Disable deploy to BenHalpern server

---

app/views/users/_org_admin.html.erb

Remove the linked example of the call-to-action box (too DEV-specific).
Resolves  #11482

Update Copy for Orgs Call-to-action Box

---

app/assets/javascripts/utilities/buildCommentFormHTML.js.erb

Button text in comment box was overflowing
closes https://github.com/forem/forem/issues/11563

Fixing overflow of comment button

---

app/views/articles/show.html.erb

This helps clarify confusion if a user sees something different than the crawled page due to service workers.
We have confirmed that this is working correctly, but there is still confusion without this comment.
Closes https://github.com/forem/forem/issues/9509

Add comment about canonical url

---

app/javascript/readingList/__tests__/readingList.test.jsx
testSetup.js

I came across this while writing tests for #11525 where I had mocked this initially.
N/A. This is frontend test infrastructure.
N/A

filterXSS is now set up in testSetup.js

---

.env_sample

These keys are required for successful tests

Add Github environments keys to .env_sample file

---

app/views/users/_sidebar.html.erb

rhymes mentioned that this context might be useful regarding this comment.
I removed some of this info in https://github.com/forem/forem/pull/11480, so this commit adds that context along with a link that rhymes shared with me.

Restore some context in comment

---

app/javascript/chat/chat.jsx
app/javascript/crayons/Modal/Modal.jsx
app/javascript/listings/components/Modal.jsx
yarn.lock

Update JS dependencies. The never version of Axe was picking up more a11y issue so I added some quick fix.
n/a
n/a
n/a
nope
n/a

Update JS dependencies with `yarn update`

---

app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/users/_customization.html.erb
app/views/users/_language_settings.html.erb
config/routes.rb
spec/requests/user/user_settings_spec.rb

Currently https://dev.to/settings/customization is not working because of nested forms.
This PR removes the nested forms, keeps the floating "Save" button removing the interim ones and restructures "update language settings" that cannot work inside the `Customization` tab as it is but it should be part of the `update` user's action anyway.
1. Load the PR
1. Go to http://localhost:3000/settings/customization
1. Save stuff, especially check if multiple language settings stick after save

Hotfix: Fix Settings/Customization page

---

app/javascript/article-form/components/Help.jsx
app/views/pages/_editor_guide_text.html.erb
app/views/pages/_v1_editor_guide_preamble.html.erb
db/seeds.rb
spec/factories/broadcasts.rb

Change all `settings/ux` to `settings/customization` url's accross the platform. 

Edited URLs settings/ux to settings/customization

---

docs/frontend/accessibility.md
docs/tests/accessibility-tests.md

An accessibility section was recently [introduced to the PR template](https://github.com/forem/forem/pull/11407). To assist testing through development and PR reviews, this change includes a checklist of suggested accessibility testing steps in the Forem docs. It's meant to be a gentle guide that doesn't overwhelm reviewers who may be new to accessibility–feedback welcome on whether it hits the mark for that purpose. There's always more detail and nuance that could be added, so I tried to strike a balance with _just enough information_ to have a positive impact.
PR template PR 🤯 https://github.com/forem/forem/pull/11407
_If your PR includes UI changes, please replace this line with details on how accessibility is impacted and tested. For more info, check out the [Forem Accessibility …

Start a11y testing checklist in Forem docs

---

app/javascript/readingList/__tests__/readingList.test.jsx
testSetup.js

The work in #11579 did the trick but had some uncessary code in it as well. This PR fixes that.
#11579
This is test infrastructure, so as long as the tests pass, we're all good.
N/A

Fix frontend test setup file

---

docs/api_v0.yml

Add positive_reactions_count to article in api docs, because it was returned in response of the API endpoints.
_If your PR includes UI changes, please replace this line with details on how accessibility is impacted and tested. For more info, check out the [Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

docs(api): add positive_reactions_count to article in api docs

---

app/javascript/organization/__tests__/OrganizationPicker.test.jsx

This is probably a temporary fix as this appears to be an issue in either [jsdom](https://github.com/jsdom/jsdom) or [jest-axe](https://github.com/nickcolley/jest-axe).
https://github.com/nickcolley/jest-axe/issues/147
N/A

Fixed  Error: Not implemented: window.computedStyle(elt, pseudoElt) console error in frontend tests.

---

app/views/liquids/_runkit.html.erb
spec/fixtures/files/article_with_runkit_tag_with_preamble.txt
spec/system/articles/user_creates_an_article_spec.rb

Fixes runkit tags showing embed error when the preamble includes escaped string content like `"<br>\nconst V = a =&gt; b =&gt; c =&gt; c (a) (b)<br>\n"`
Closes #9773 
1. Create a new post with the following two runkit tags in `master`:
```md
{% runkit 
const V = 'This is a simple expression'
%}
const node = data => next => callback => callback (data) (next)
const head = node ('data') (null)
head (data => next => {
return { data, next }
})
{% endrunkit %}
{% runkit
const V = a => b => c => c (a) (b)
%}
const node = V
const leftRight = node ('Left') ('Right')
const callback = a => b => {}
leftRight (callback) //=> 'Left'
{% endrunkit %} 
```
2. On preview, observe that the first tag renders fine, the second one fails to render with the error `Unable to load embed. Syntax error found in …

fix: Parsing of preamble with escaped content in runkit tags

---

app/models/follow.rb
lib/data_update_scripts/20201118141822_gradual_article_cache_bust.rb
spec/requests/stories_show_spec.rb
spec/system/comments/user_edits_a_comment_spec.rb
spec/system/comments/user_views_article_comments_spec.rb

Ran `rubocop -a` on the code base

Routine rubocop fixes

---

config/blazer.yml

I recently added a Blazer query with a [variable](https://github.com/ankane/blazer#variables), but would like to use a [smart variable](https://github.com/ankane/blazer#smart-variables) instead.
n/a

Add tag smart variable to Blazer config

---

app/assets/stylesheets/components/header.scss
app/assets/stylesheets/views/article.scss

When scrolling down in an article page, the action block overlaps with the DEV icon. This pull request fixes it.
Closes https://github.com/forem/forem/issues/11610
_If your PR includes UI changes, please replace this line with details on how accessibility is impacted and tested. For more info, check out the [Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

Fix: action overlapping with header

---

app/javascript/Search/__tests__/SearchFormSync.test.jsx

This is just a little test refinement for the work in #11525
#11525, #10424
N/A. This is just tests being refactored.
N/A

Cleaned up tests I wrote for #11525

---

app/assets/javascripts/initializePage.js
app/assets/javascripts/initializers/initializeColorPicker.js
app/views/users/_profile.html.erb

A small refactor that moves this code to it's own JS file so that it can be linted and compressed.
https://github.com/forem/forem/pull/10984/files#r509247051
- Check that the color picker functions on http://localhost:3000/settings/profile still function correctly
_If your PR includes UI changes, please replace this line with details on how accessibility is impacted and tested. For more info, check out the [Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

Move the color picker to its own initializer file

---

body.json
config/initializers/wrap_parameters.rb
spec/requests/api/v0/articles_spec.rb

Rails by default accepts wrapped and unwrapped parameters in JSON requests (with or without a root object), regardless of the fact that the contract with the client requests wrapped parameters or not. This results in unforeseeable bugs when the client sends unwrapped parameters in lieu of wrapped ones.
As undeterministic bugs are a PITA and this is the classic grey area in Rails apps and as the customer facing API is fully documented and the internal can be manually adjusted, we disable this and be done with this odd feature.
Closes https://github.com/forem/forem/issues/11645
https://github.com/forem/forem/pull/11638
1. send unwrapped parameters to `POST localhost:3000/api/articles`
```json
{
"title": "A test post again",
"description": "Testing article creation bug again", …
```

Disable ActionController auto params wrapping

---

spec/requests/feedback_messages_spec.rb

A previous PR inadvertently introduced too many levels in a spec that broke the rubocop check. This PR addresses this problem.
#10502
Both of these should pass:
`rubocop spec/requests/feedback_messages_spec.rb`
`bundle exec rspec spec/requests/feedback_messages_spec.rb`

Fixes a rubocop failure that slipped through in a previous PR

---

docs/readme.md

This doesn't really make sense because we don't follow it with a list of instructions.

Remove confusing line from readme

---

lib/tasks/temporary/hacktoberfest_badges.rake

Award Hacktoberfest badges to subscribed users. This rake task will be run every 30 min so the 2 hour buffer should be more than enough to make sure we dont miss any. No tests bc I am testing in production right now 😅 
https://github.com/forem/InternalProjectPlanning/issues/334

Temp Feature: Award Hacktoberfest Badges Rake Task

---

app/models/user.rb
spec/models/user_spec.rb

Fixes https://github.com/forem/forem/issues/11784

[Hotfix] Allow blank values for payment_pointer

---

yarn.lock

There's lingering code in `yarn.lock` that should've been removed.
n/a
n/a
n/a
n/a

Remove @storybook/components from yarn.lock

---

app/javascript/actionsPanel/actionsPanel.js
app/javascript/packs/commentModPage.js

Hotfix as the moderation experience level button is broken in production
Closes https://github.com/forem/forem/issues/11793

[Hotfix] Fix broken experience level button in moderation panel

---

app/assets/stylesheets/views/mod-center.scss

Fixes #11647 
I believe this also fixes the final issue remaining from #5738, so closes #5738 
_I don't think this change adds any accessibility concerns, but if there's anything I should be aware of I'm happy to check it out._

Fix Mod Center compatibility issue with dark themes (Date column)

---

.github/workflows/buildkite.yml

Fix a typo in the github action yaml.

Fix google action typo

---

.github/workflows/pr.yml

Fix YAML so it is actually valid GitHub Action YAMLs.

---

app/views/service_worker/index.js.erb
public/error.html
public/not_found.html

We are getting this issue in service workers...
`Uncaught (in promise) TypeError: Failed to execute 'Cache' on 'addAll': Request failed` after https://github.com/forem/forem/pull/11744
Hot fix: I believe the dynamic pages in the service workers are causing some kind of infinite redirect or something along those lines.
There is probably some way to make sure we can properly fetch these dynamic pages, but for now this should fix things.

Use static error files in serviceworker

---

.github/workflows/buildkite.yml
.github/workflows/rebase.yml

Try to fix GitHub Action conditionals again.

---

app/views/layouts/admin.html.erb

Fix for this issue...
This pr: https://github.com/forem/forem/pull/10424 didn't account for the admin header.

Fix admin header links

---

.github/workflows/buildkite.yml
.github/workflows/pr.yml
.github/workflows/rebase.yml

This should be the final round of fixes to the GitHub Actions workflows for triggering `/ci` and `/rebase` workflows and the PR comment workflow from third-party forks.

GitHub Action bug fixes

---

.github/workflows/buildkite.yml
.github/workflows/rebase.yml

Adds debug statements to GitHub Actions.

Add debug to actions.

---

.github/workflows/buildkite.yml

Comment out if conditional for now.

GitHub Actions comment out conditional

---

.github/workflows/buildkite.yml
.github/workflows/dependabot.yml
.github/workflows/pr.yml
.github/workflows/rebase.yml

This should be the last PR to get the `/ci` and `/rebase` commands working in
GitHub Actions. The issue is that our membership settings for `forem/forem` have
everyone set to 'CONTRIBUTOR' instead of 'MEMBER' or 'OWNER'.
Adding github.event.comment.author_association == 'CONTRIBUTOR' should fix this
issue.
I also cleaned up all action files to make the main name of the workflow as
succinct as possible to better organize the left menut of the GitHub Actions
page.
This PR won't fix the issues with the "Run forem/build-containers pipeline"
job in buildkite.yml but I will address those issues in another  PR.

Add github.event.comment.author_association == 'CONTRIBUTOR' to if statement in GitHub Actions

---

lib/data_update_scripts/20201014184856_resave_users_for_imgproxy.rb
lib/data_update_scripts/20201020215535_resave_articles_and_comments_for_imgproxy.rb
lib/data_update_scripts/20201026155851_resave_to_bust_cache_for_imgproxy.rb
lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb

I created a few DUS that does similar tasks. I'm disabling them because they are no longer needed.
n/a
n/a
n/a

Disable duplicate resave data upgrade script

---

.github/workflows/buildkite.yml

Uses `jdoss/trigger-pipeline-action@master` until the PR support features are accepted into upstream.

Update Buildkite workflow trigger-pipeline-action version

---

.travis.yml
cypress/.eslintrc.js
package.json
yarn.lock

Introduces Cypress to our code base. This PR's focus is to get Cypress in, that's it. [Integration with CI](https://github.com/KnapsackPro/knapsack-pro-cypress) will come in another PR.
#382
Nothing for now. This is currently only being used during development
N/A

Add Cypress for end to end testing (E2E)

---

cypress/.eslintrc.js
jest.config.js

I'm in the middle of writing my first e2e test for our code base and realized I missed a couple tweaks to eslint and jest.
#382, #11840
N/A because this is test infrastructure
N/A because this is test infrastructure

Fix eslint and jest configurations for cypress

---

app/validators/profile_validator.rb

At the moment, it is impossible to complete onboarding on master. A NoMethodError is thrown when the `summary_too_long?` method is called. This change makes it possible to complete onboarding. I think we should merge this to fix onboarding, but I think I need to look a little more closely at what is going on here because I might be missing some edgecase where we don't want this validation to be skipped whenever the summary isn't accessible from the profile.
Before this change, the follow steps probably won't work, after they do.
1. Create a new account
2. Go through onboarding
3a. Attempt to "skip for now" on the personal information
3b. Fill out the info and try to continue

Don't attempt to call summary on profile during onboarding

---

app/validators/profile_validator.rb

The previous PR was merged before I could act on some feedback :smile: 
I'm updating this comment based on @citizen428's feedback.
https://github.com/forem/forem/pull/11836#discussion_r539811288

Fix misleading comment

---

lib/data_update_scripts/20201210163704_set_contact_email_address.rb
spec/lib/data_update_scripts/set_contact_email_address_spec.rb

https://dev-internal.slack.com/archives/C5BJE4PGB/p1607611327262300
It was discovered that the contact email is not showing up on DEV. The contact email was [added in this PR](https://github.com/forem/forem/pull/11630), however since we were modifying an existing Site Config field (i.e. email_addresses), we were meant to update the value in the DB as well.
We'd never added this to the db and hence as a result all of the references to SiteConfig[:email_addresses][:contact] are blank and it was not showing up as a field on /admin/config. 
In this PR, I write a data script that will add the contact key to SiteConfig[:email_addresses] should it not exist.
_Note: For existing Cloud Forems setting the SiteConfig.email_addresses[:contact] = ApplicationConfig["DEFAULT_EMAIL"] seems counter …

Update the contact email address in the database

---

.github/workflows/dependabot.yml

Apparently the syntax is not valid:
from https://github.com/forem/forem/actions/runs/415146243
I wish there was a syntax checker of these files because the feedback workflow is such a time waster

Fix Dependabot GitHub action syntax

---

.env_sample

`"Optional"` is not an empty string which leads to unnecessary checks in development and potentially a broken captcha:
https://github.com/forem/forem/blob/bcadebb3efc003f5e46a234d572993ea0cfa6149/app/services/re_captcha/check_enabled.rb#L18-L19
https://github.com/forem/forem/blob/bcadebb3efc003f5e46a234d572993ea0cfa6149/app/services/re_captcha/check_enabled.rb#L33-L35

Disable Google reCAPTCHA in env file sample

---

.github/workflows/buildkite.yml

Add GITHUB_TOKEN to buildkite workflow

Add GITHUB_TOKEN to buildkite workflow

---

scripts/create_buildkite_pr_build.sh

This reworks the logic for tracking down the Pull Request ID from GitHub Action events variables.

Rework the PULL_REQUEST_ID logic

---

.github/workflows/buildkite.yml
scripts/create_buildkite_pr_build.sh

Rework the PULL_REQUEST_ID logic, again and move github.event.issue.number to the workflow file....
https://www.youtube.com/watch?v=SLq-M46ttY4

Rework the PULL_REQUEST_ID logic, again

---

app/labor/cache_buster.rb
app/services/edge_cache/bust_sidebar.rb
spec/services/edge_cache/bust_sidebar_spec.rb

This adds a cachebusting object for the home page sidebar.

Add sidebar bust logic

---

scripts/create_buildkite_pr_build.sh

Changing `${PULL_REQUEST_ID:-}` will allow for `PULL_REQUEST_ID` to be not set in the if statement so the script won't fail.
It fixes the jq lookups on `GITHUB_EVENT_PATH` for setting:
```
PULL_REQUEST_ID
COMMENT_USER_LOGIN
COMMENT_URL
```
from `GITHUB_EVENT_PATH`

Fix a few bugs with the create_buildkite_pr_build.sh script

---

app/javascript/chat/draw/index.jsx

The width on canvas was fixed before. Now canvas will load according to the width it's given.

🐙Enhancement: Making connect Draw Responsive according to Device width 

---

app/controllers/admin/users_controller.rb

Replaced `html_safe` with `tag` and `safe_join` like @rhymes suggested in https://github.com/forem/forem/pull/11039#discussion_r540243907
#11039

Avoid html_safe and violating Rails/OutputSafety

---

.github/dependabot.yml

Although ignoring dependencies can be done with Dependabot's commands, it's better to be explicit here to give context to other team members. Thanks @mstruve [for the nudge](https://github.com/forem/forem/pull/11887#issuecomment-744639190)
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore

Tell Dependabot to ignore Simplecov 0.18+

---

docs/getting-started/start-app.md

A bunch of us have been using [Overmind](https://github.com/DarthSim/overmind) instead of [foreman](https://github.com/ddollar/foreman), the tool launched by`bin/startup`, to work day by day locally.
Its learning curve is steeper but the advantages are many: easier debugging experience, separate `restart` by service, separate navigation of logs.
This is my attempt to write down the bare minimum to set it up as an advaced startup setup. Hopefully others can add tips and tricks in the future to ease the developer experience.

Document the advanced startup setup

---

.travis.yml

We have a few builds that do not go through because `e2e:ci` is missing some bits. Went ahead and disable it in the meantime

Temporarily disable e2e tests

---

app/controllers/concerns/verify_setup_completed.rb
app/helpers/application_helper.rb

Replaced `html_safe` and `raw` with `tag` + `safe_join`

Fix Rails/OutputSafety violations

---

.travis.yml
bin/e2e
package.json

Fixes the issue with a Forem forked repository that does not have a Knapsack Pro API token that enables parallelization. If the API token is not found, `npx cypress run` is run instead.
#382, #11946
Tests should run and pass.
N/A

Fix end to end testing for Forem forked repositories

---

app/controllers/registrations_controller.rb
app/views/admin/configs/_form_submission.html.erb
app/views/admin/configs/show.html.erb
spec/requests/registrations_spec.rb

A little while back we removed the requirement for `configs_controller` to have _an additional permission on top of "super admin" for submitting the form. But we failed to update the UI and other logic.
This fixes that by removing the "single resource admin, Config" logic.
Single resource admins are still a thing as needed, but don't apply to this page, which is for super admins only.
Double-check the logic.
Only a backend logic concern.

Remove config single resource admin from config logic

---

.travis.yml

CI is currently breaking because the rails server running for Cypress is erroring out fairly consistently with a templating error. e.g. `2020-12-18 14:33:07 +0000 Rack app ("GET /" - (127.0.0.1)): #<ActionView::Template::Error: crayons.css>`. I need to investigate this, so temporarily disabling end to end tests.
#382, Potentially related to https://github.com/rails/rails/issues/40613
N/A
N/A

Disabling Cypress temporarily to figure out why the web server errors action template errors.

---

app/controllers/registrations_controller.rb
app/models/user.rb

We are running into an issue where _brand new Forems_ do not have proper profile fields all set up. This may be due to data update scripts not running properly on first provisioning of a new Forem in Forem Cloud.
I am sure there are better ways to account for this, so if we have another solution we should definitely go with that. This is a hack. However failing no better ideas, this should be fine I think. It will at least help validate whether this is the problem.
https://github.com/forem/InternalProjectPlanning/issues/379

Resolve problem where profile fields have not been properly imported

---

.travis.yml
app/views/devise/confirmations/new.html.erb
cypress.json
cypress/integration/loginFlows/initialAdminLogin.spec.js

This depends on the work in #11950. There was an error occurring when creating the initial administrator when starting from a non-seeded database in the test environment. This PR fixes that.
#382, #11946, #11950, #11977
N/A
Added a label for the email confirmation field.

Fixed initial e2e test now that data updates are run.

---

app/assets/javascripts/utilities/buildArticleHTML.js

n/a
n/a
This change should not alter any existing behavior.
n/a

Filter XSS in navigationLink's title

---

app/services/feeds/import.rb
spec/services/feeds/import_spec.rb

Feeds::Import seems to be chugging along just fine (it's enabled on DEV). I have been going through some of the errors and I noticed the error messages missing. This is because we log them separately, which works fine locally but it doesn't in a high traffic context as between two log statements thousands of other parts of the app could have logged things. Adding the error message inline with the error log line will make it far easier to debug errors and act accordingly.
This will also have the side effecting of halving the error logs for this part ;)

Log error message inline when Feeds::Import fails

---

app/views/admin/users/gdpr_delete_requests/index.html.erb

Fix typo on admin page

---

app/views/articles/show.html.erb

There are smarter ways we need to decipher when and when not to include a script, but this is a small naive optimization to help us not always include this expensive third party library, as we are currently doing.

Remove automatic inclusion of Twitter widget.js

---

.gitignore
.travis.yml

Builds are broken, probably for something related to missing packages in `node_modules` - https://travis-ci.com/github/forem/forem/jobs/465368676#L678 - trying to see if by using Travis's builtin caching mechanism - https://docs.travis-ci.com/user/caching/ - things change.

Use Travis builtin caching

---

app/controllers/chat_channel_memberships_controller.rb
app/controllers/comments_controller.rb

Fix "possible unprotected redirect" [Brakeman warning](https://codeclimate.com/github/thepracticaldev/dev.to/issues?status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=brakeman)
#3739

Fix "possible unprotected redirect" warning

---

app/services/email_digest.rb
app/workers/articles/rss_reader_worker.rb
app/workers/emails/enqueue_digest_worker.rb
spec/services/email_digest_spec.rb
spec/workers/articles/rss_reader_worker_spec.rb

Rather than checking the community name which we just found out can change easily, lets check the domain like we do in other places since that is far less likely to change. 
https://github.com/forem/forem/pull/12082

Refactor:Use dev_to? to Check for DEV

---

.rubocop.yml

Adding new cops added by #12043 - no violations this time 🔥

Enable new Rubocop 1.7.0 cops

---

app/assets/stylesheets/chat.scss

Currently on narrow screens, the action to open and close the active chat is, in my opinion, too slow of an animation. This approximately halves the time to be in line with expectations for this behavior on native mobile functionality.
Go to narrow screen size to see the behavior of opening and closing a channel. You need channels to be available to see the behavior.
There shouldn't be any _new_ a11y concerns, but maybe something here should be addressed?
have not been included_ - No new functionality, shouldn't break anything.

Adjust animation on /connect mobile room open-close

---

app/views/admin/users/_negative_reactions.html.erb
app/views/admin/users/_reports.html.erb

While working in the `/admin/users` dashboard, I noticed that the "Recent Reactions" and "Recent Reports" buttons had a different class than the other buttons ("Data Export", etc.). This PR updates the "Recent Reactions" and "Recent Reports" buttons to use the class `crayons-btn` rather than `btn btn-secondary` to match the other buttons in the dashboard.
N/A
**To QA this PR, please first ensure that you have `admin` permissions, then please do the following**:
- Navigate to `/admin/users/:id/edit` and ensure that the "Recent Reports" and "Recent Reactions" buttons match the other buttons below them
- Ensure that all of the checks pass and that Travis builds green ♻️ 
- **Before**:
- **After**:
N/A as I merely updated the button's class to match the other `/admin/user` button classes. …

Update Recent Reactions + Recent Reports Buttons

---

config/initializers/set_release_footprint.rb

Change related to https://github.com/forem/forem/pull/12149.
RELEASE_FOOTPRINT is usually set in the Forem Cloud env environment. However, we need to cater for those Forems that are being deployed on Heroku as well. 
RELEASE_FOOTPRINT is the datetime that the deploy is done, however the fallback variable for Heroku was set to HEROKU_SLUG_COMMIT. This causes the Last deployed time to be a commit id instead of a date when RELEASE_FOOTPRINT is not set (like on heroku envs). See the image below: 
Hence, I've changed the fallback to HEROKU_RELEASE_CREATED_AT. 
https://github.com/forem/forem/pull/12149
1. In the .env file change the following variables as follows:
```
export HEROKU_RELEASE_CREATED_AT="Some Date"
export HEROKU_SLUG_COMMIT="Some Commit ID"
```
2. Now restart your server and go to …

Change HEROKU_SLUG_COMMIT  to HEROKU_RELEASE_CREATED_AT 

---

app/javascript/admin/controllers/config_controller.js
app/views/admin/configs/show.html.erb
app/views/admin/shared/_card_header.html.erb

This changes the confusing "Toggle" labels to "Show xyz"/"Hide xyz" dependending on expanded status.
Closes https://github.com/forem/forem/issues/11484
Wish we could switch to Crayons + Stimulus and that's it. Having jQuery, Bootstrap and Stimulus isn't awesome :D
https://github.com/forem/forem/issues/11484
1. Go to http://localhost:3000/admin/config
2. Click on the toggle buttons and see the text change

Admin: Change label of toggle buttons in Configuration panel

---

README.md

Would like to add a Community section to our Readme to highlight where community members/contributors should go to have discussions around features or other general questions.
- [ x] Documentation Update
Adding a community section in our Readme to highlight where community members/contributors should go to have discussions around features or other general questions. 
This will help address the changes we discussed in our internal team Forem around [Github discussions](https://forem.team/cmgorton/adding-discussions-to-forem-repo-59m). 
- [ x] No, and this is why: This was a minor update to the Readme and does not need any tests. 
- [ x] README

Update to add Community section.

---

README.md

- [x ] Documentation Update
Added a "Scroll Back To Top" link at the end of the README.md file.

Add scroll back to the top to README

---

app/assets/stylesheets/views/comments.scss
app/views/comments/edit.html.erb

Fixing the very wide code blocks in comments preview
References/Closes/Fixes/Resolves #11402 

Bug fix #11402 - Very wide code blocks overflow in comment preview

---

README.md

This adds Katie (me) to the Forem core team list!
I don't think so!

add katie(me) to list of core team members 🎉

---

app/controllers/async_info_controller.rb
spec/models/forem_instance_spec.rb

This is a quick fix for a failing spec
https://github.com/forem/forem/pull/12224

Fix shell version logic in async info controller

---

README.md

I have added hyphens for certain words and corrected the spelling for acknowledgements.

Fixed punctuation mistakes

---

app/models/user.rb

A minor follow-up to https://github.com/forem/forem/pull/12196, removing the column from the AR ignore list after dropping it and removing all usages.
n/a
n/a
n/a

Remove contact_consent column from ignore list

---

README.md

A link to my DEV profile should be added to the readme list of core team members
N/A

add suzanne to list of core team members

---

app/views/podcast_episodes/_meta.html.erb

Small fix. The hardcoded version of this was still in the `else` section.
https://github.com/forem/forem/issues/11708

Fix outstanding /pod main image problem

---

app/controllers/users_controller.rb
app/models/site_config.rb
lib/data_update_scripts/20210114174504_update_user_update_rate_limit_default.rb
spec/lib/data_update_scripts/update_user_update_rate_limit_default_spec.rb
spec/requests/admin/configs_spec.rb

After a few days debugging we finally found the cause of https://github.com/forem/forem/issues/12138, it was rate limiting which became clear thanks to some additional logging. 
closes: https://github.com/forem/forem/issues/12138

Bug Fix:Increase Default Rate Limit for User Updates to 15

---

README.md

When I updated the docs with the community section previously, I forgot to add the link in the Table of Contents. This adds the link.
- [x ] Documentation Update
When I updated the docs with the community section previously I forgot to add the link in the Table of Contents. This adds the link.
- [x ] No, and this is why: This is a small addition to the Readme and does not need to be tested. 
- [ x] README

Adding Community to the table of contents.

---

spec/helpers/application_helper_spec.rb
spec/models/forem_instance_spec.rb
spec/requests/admin/admin_portals_spec.rb

Currently on some PR's there are two tests that are failing: 
My debugging process has been as follows:
A test has run prior to this that has set the "HEROKU_RELEASE_CREATED_AT" ENV variable to `A deploy date set on Heroku`. 
Therefore, when we call the method `release_adjusted_cache_key`, it makes a reference to `ForemInstance.deployed_at` which reads as follows: 
```
@deployed_at ||= ApplicationConfig["RELEASE_FOOTPRINT"].presence || ENV["HEROKU_RELEASE_CREATED_AT"].presence
```
Since the value of `HEROKU_RELEASE_CREATED_AT` at a previous point was `A deploy date set on Heroku`, the `deployed_at` gets cached with that value and now for subsequent tests, that value sticks with `A deploy date set on Heroku`. Hence, causing the rest of the tests to fail. 
To solve this I tried to did two …

Attempt to fix random test failures when dealing with the ForemInstance class 

---

app/views/mailers/digest_mailer/digest_email.html.erb

Replace `/settings/misc` with `/settings/customization` in [`app/views/mailers/digest_mailer/digest_email.html.erb`](https://github.com/forem/forem/blob/master/app/views/mailers/digest_mailer/digest_email.html.erb).
Issue #12299 affecting the digest email.
During development, the digest email can be rendered at http://localhost:3000/rails/mailers/digest_mailer/digest_email. 
_Read more in [Forem docs > Backend Guide > Emails ](https://docs.forem.com/backend/emails/)._
No.

Replace URL /settings/misc with /settings/customization

---

app/views/admin/articles/index.html.erb
app/views/articles/_sidebar.html.erb
app/views/events/index.html.erb
app/views/organizations/_main_feed.html.erb
app/views/users/_main_feed.html.erb

Load partials as collections instead of `.each` + loading a single partial for optimization (description in the related issue).
https://github.com/forem/internalEngineering/issues/273

Optimize loading partials as collections

---

app/controllers/async_info_controller.rb
app/controllers/stories_controller.rb
app/javascript/contentDisplayPolicy/hideBlockedContent.js
app/models/user.rb
app/models/user_block.rb
app/services/articles/feeds/basic.rb
app/services/articles/feeds/large_forem_experimental.rb
spec/models/user_block_spec.rb
spec/services/articles/feeds/basic_spec.rb
spec/services/articles/feeds/large_forem_experimental_spec.rb

This PR does a few things:
- Fix the client-side check for blocked content.
- This had broken because we changed an HTML class, but were still using it for client side reference.
- Add functionality so the blocked content is hiddent _on the server_ for the core feed.
- At the original implementation of blocked content, this was not possible.
- This lays the groundwork for a better overall approach to safely blocking content.
- Identified and fixed a small inefficiency in the way the home page was loaded
- We made a useless query + sort in the home feed.
https://github.com/forem/forem/issues/10744
There are no UI changes which should require much user testing— But you can sanity check that this works as expected.
_Please replace this line with instructions on how to test your changes, as …

Fix and refactor hiding content when a user has blocked someone

---

app/javascript/readingList/components/ItemListItem.jsx
app/javascript/readingList/components/__tests__/ItemListItem.test.jsx

The `children` prop had a default prop value. This is not necessary as the [`children` prop is always an array](https://preactjs.com/guide/v8/differences-to-react/#whats-missing). As well, the `children` prop had a default value of empty object (the bug). This is what is breaking tests in #12289.
```bash
TypeError: Cannot read property 'is' of undefined
108 | 
109 |   it('renders user information', () => {
> 110 |     const { getByText } = render(<ItemListItem item={getItem()} />);
|                           ^
111 | 
112 |     getByText(/Bob/i);
113 | 
at newVNode (node_modules/preact/src/diff/index.js:363:28)
at N (node_modules/preact/src/diff/index.js:247:4)
at newProps (node_modules/preact/src/diff/children.js:163:46)
at newVNode (node_modules/preact/src/diff/index.js:420:16)
at N …
```

Fix broken test pre-Preact upgrade

---

app/views/articles/_sidebar_campaign.html.erb

One more optimization: loading partials as a collection.
https://github.com/forem/internalEngineering/issues/273

Load campaign articles in a widget as a collection

---

config/schedule.yml

A while ago I opened an issue on `sidekiq-cron` repo to request a description field. Apparently it's already there even though I couldn't find it mentioned in the README
https://github.com/ondrejbartas/sidekiq-cron/issues/294
1. Add `tech_admin` to your roles, eg. `user.add_role(:tech_admin)`
2. Go to http://localhost:3000/sidekiq/cron and select any of the tasks, eg. http://localhost:3000/sidekiq/cron/award_beloved_comment_badges
3. See the description in the page:

Add descriptions to scheduled tasks

---

app/helpers/authentication_helper.rb
app/views/admin/configs/_apple_auth_provider_settings.html.erb
app/views/admin/configs/_auth_provider_settings.html.erb
app/views/admin/configs/show.html.erb
spec/helpers/authentication_helper_spec.rb

This PR refactors a bit of logic living in the views into a Helper method. Based on feedback [in this conversation](https://github.com/forem/forem/pull/12287#discussion_r557856664)
1. Boot up locally
2. Go to `/admin/config`
3. Enable/Disable a few Authentication providers
4. Check the configs are being saved correctly (`/enter`)
5. Go to the rails console and enable the Apple auth feature flag (`Flipper.enable(:apple_auth)`
6. Go to `/admin/config` and make sure you are still able to enable/disable OAuth providers
None

Replace authentication_enabled_providers.include? with helper method

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/components/IntroSlide.jsx

1. Removing display content from link
2. Removing extra margin at the top of link
3. Adding before link
https://github.com/forem/forem/issues/9585
https://user-images.githubusercontent.com/8092120/105316092-63ce4400-5be6-11eb-8453-4108eaaa3a78.mp4

Fixing link focus

---

.github/workflows/issue.yml

Updating text to give more time for following up on issues and to let the community know why some feature requests may be closed.
- [ x] Documentation Update
After talking with Molly we decided to update the text for the automated issues message. This will give more time for following up on issues and to let the community know why some feature requests may be closed.
- [x ] No, and this is why: Made changes to text that do not need to be tested.
- [x ] No documentation needed

Update issue.yml text.

---

app/views/devise/shared/_error_messages.html.erb

The issue is related to the device error messages in the dark theme. It becomes difficult to read the error messages. 
#12336

fix devise error messages in the dark theme UI

---

app/views/tags/edit.html.erb

While working with tags, I discovered a broken link at the bottom of the `/t/<tag>/edit` page. This PR updates the link to route to the proper page, rather than an error page by adding `/edit` to the end of the link. Additionally, I have updated the edit link to read `[tag]'s admin page` rather than `[tag] admin` (see screenshot below).
N/A
**BEFORE**:
- Navigate to `/t/<tag of your choice>/edit` and click the "`<tag name>` admin" link at the bottom of the page and run into a routing error:
**AFTER**:
- Navigate to `/t/<tag of your choice>/edit` and click the "`<tag name>` admin" link at the bottom of the page and redirect to the tag's admin edit page as expected:
- With newly updated link copy:
N/A
N/A

Update Tag Link to Route to Proper Admin Page

---

app/helpers/application_helper.rb

closes https://github.com/forem/forem/issues/12394
NA

Prevent text overflow of follow button

---

lib/data_update_scripts/20210104170542_resave_articles_for_code_snippet_fullscreen_icon.rb

This DUS script is no longer necessary.
n/a
n/a
n/a

Disable ResaveArticlesForCodeSnippetFullscreenIcon

---

app/views/users/confirm_destroy.html.erb
spec/system/user/user_self_destroy_spec.rb

refactor the UI for the delete my account page
Closes #12296

Add Crayons classes to the "Destroy your account" page

---

.travis.yml

- Explicitly separate jobs and cut down `script` size.
- Created a 4th node/job strictly for everything else that isn't RSpec.
- Remove Codeclimate test reporter since it hasn't been working.
n/a
Please check out the build https://travis-ci.com/github/forem/forem/builds/214730360
n/a

Add a 4th node to Travis

---

docs/contributing/forem.md

A section of our contributing guide needs some updating to reflect our new internal RFC process and how we use forem.dev. This seemed like a quick fix, so I just whipped up a PR for it 😸 
N/A, but something that needed doing!
Check for typos + formatting 😂 
A docs update, so hopefully not! 🙃 

Update Contributing guide to reflect new processes

---

docs/technical-overview/stack.md

Updated GitDocs link. The project is already archived, the site on Netlify is down.

Update GitDocs link

---

docs/getting-started/committing.md

Fixed spelling:
precommit -> pre-commit
N/A
N/A
[Fixed gif](https://tenor.com/view/brown-and-cony-fix-fixed-gif-12672662)

Fix spelling

---

app/assets/javascripts/base.js.erb

There seems to be some backwards logic here that was preventing users from being able see search results. I'd love if someone with more context could check this to make sure we should be removing that class though. 
https://github.com/forem/forem/issues/12487
Search on local without being logged in and ensure you can search without seeing a classList error that prevents you from changing pages

fix check to remove class from null element

---

app/services/mailchimp/bot.rb

This is following the footstep of https://github.com/forem/forem/pull/12304. There was one more that needed updating.
n/a
n/a

Remove last DatadogStatsClient

---

app/assets/stylesheets/views/article.scss

This adds specific styling for the 'like' reaction buttons on posts. [This PR](https://github.com/forem/forem/pull/4869) added the disabled state to this button because if the user repeatedly and rapidly clicked the like button there would be a stream of async requests that lead to an imbalance of create vs. destroy responses.
This button should be disabled to prevent this, but the default styling for all disabled buttons looks strange during the request. 
[Forem Accessibility …

override disabled for comment like use case

---

app/views/admin/admin_portals/index.html.erb
spec/requests/admin/admin_portals_spec.rb

On some PR's there was the [following failing test on Travis:](https://travis-ci.com/github/forem/forem/jobs/479324871)
**My investigation:** 
To replicate the failing spec locally I'd ran the tests in the related tests in this specific order: 
```
bin/rspec spec/models/forem_instance_spec.rb spec/requests/admin/admin_portals_spec.rb
```
**My findings:**
When [this PR](https://github.com/forem/forem/pull/12500) got merged, the ForemInstance.deployed_at function changed to   always have the current datetime as the fallback value. 
Hence, the reason why the test in the screenshot i.e. `it "shows 'Not Available' if the Last deployed time is missing"` was failing, because the Latest deployed time (i.e. ForemIInstance.deployed_at) would never be missing. It would never need to show `Not …

Remove flakey failing test + code on Forem Instance 

---

app/controllers/admin/articles_controller.rb

Fix typo for buffer updates

---

app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/views/articles/_full_comment_area.html.erb

Add discussion length in brackets
#12324 
None

feature added : add-discussion-length-in-brackets #12324

---

app/javascript/packs/Onboarding.jsx

A default import was missed that causes the onboarding flow to not work in production
closes https://github.com/forem/forem/issues/12540

remove default import for onboarding

---

app/javascript/admin/__tests__/controllers/article_controller.test.js
app/javascript/admin/__tests__/controllers/buffer_controller.test.js
app/javascript/admin/__tests__/controllers/config_controller.test.js
app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
app/javascript/admin/controllers/article_controller.js
app/javascript/admin/controllers/buffer_controller.js
app/javascript/admin/controllers/config_controller.js
app/javascript/admin/controllers/data_update_script_controller.js
app/javascript/admin/controllers/image_upload_controller.js
app/javascript/admin/controllers/modal_controller.js
app/javascript/admin/controllers/reaction_controller.js

Fixes a bug caused by #12512. It was not caught during a smoke test of the admin section.
- #12512 
- #12541
1. Log in as an administrator in your local development environment. email: admin@forem.local, password: password.
2. Ensure that each admin page has a controller associated to it. The best way to test this is to expand the configuration section, e.g. Authentication and click on a button in it. It should work like before instead of saying that a field is required for the message you need to enter to submit the form. i.e. 👇🏻
[Admin …

Stimulus controllers needed to be default exports.

---

app/javascript/admin/controllers/data_update_script_controller.js

Whilst I was making some changes based on review feedback on my DUS PR, I had mistakenly changed the counter to 0 instead of 20 😔
https://github.com/forem/internalEngineering/issues/276
https://github.com/forem/forem/pull/12424

Change counter value

---

app/controllers/feedback_messages_controller.rb
app/mailers/notify_mailer.rb
app/views/mailers/notify_mailer/feedback_response_email.html.erb
app/views/mailers/notify_mailer/feedback_response_email.text.erb
spec/mailers/notify_mailer_spec.rb
spec/requests/feedback_messages_spec.rb

Autoresponse to the user after they send feedback.
I haven't deleted the code for the manual response yet, it will be the next step. 
https://github.com/forem/rfcs/pull/9

Email confirmation to abuse reports

---

app/javascript/chat/RequestManager/RequestManager.jsx

The phrasing of this may reflect the code, but is a little confusing. A
user might not understand what a "joining request" is, so we should
probably just keep things simple for the time being.

Update verbiage around connect invitations

---

app/models/user.rb
spec/models/user_spec.rb

Provide a link to the taken username within the error message.
Closes #11686 
I haven't contributed to OSS in a long time, the forem community is super approachable and friendly 💕

✨ Add link to existing username in uniqueness validation error message

---

docs/frontend/tips.md

There was some confusion around this recently, so at least this is written down now. :grimacing: 
https://github.com/forem/forem/pull/10617
- [x  No, and this is why: only touched docs!

Add a tip for the SKIP_SERVICEWORKERS env variable

---

app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
app/javascript/admin/controllers/data_update_script_controller.js
app/views/admin/data_update_scripts/index.html.erb

Data Update Scripts Page: Use filename on error messages instead of ID
As per [this comment](https://github.com/forem/forem/pull/12424#pullrequestreview-580638347) we want to use the actual filename, instead of the ID, on any error messages. 
forem/internalEngineering#276
An older issue: #6175
It's a bit complicated to mimic a failure, but here goes:
- Follow the instructions [In this PR QA Instructions](QA Instructions) to mimic a failure. 
- Once you have the Re-run button on the UI, just go to [app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js:91](https://github.com/Ridhwana/forem/blob/95b3c9fcd210239ecec2f0dcd671fb33a3d7d9af/app/javascript/admin/controllers/data_update_script_controller.js#L91) and set to ``` if (counter > 0) ```. 
- Then click rerun. …

Data Update Scripts: Use filename on error messages instead of ID's

---

bin/e2e

Adds a `yarn install` command to the `bin/e2e` script to ensure packages are up to date.
#382
1. Run `yarn e2e` and it should run `yarn install`.
N/A. This is testing infrastructure.

Added yarn install to bin/e2e

---

app/models/site_config.rb
app/services/slack/messengers/article_published.rb
spec/services/slack/messengers/article_published_spec.rb

This PR updates [the hardcoded channel name for Slack notifications when an article is published](https://github.com/forem/forem/blob/e1b1fe3ed7364b543bdd3c26267b4e1dcde5cd10/app/services/slack/messengers/article_published.rb#L28). This feature is primarily used internally. Updating this hardcoded string to a `SiteConfig` will allow us to set up notifications _per Forem_ :tada:.
Adjust this value for a few Forems we manage via a console.

Update article published Slack notifications

---

app/javascript/article-form/articleForm.jsx
cypress/fixtures/users/articleEditorV1User.json
cypress/fixtures/users/articleEditorV2User.json
cypress/integration/publishingFlows/previewArticle.js
spec/support/seeds/seeds_e2e.rb

Adds end to end tests for #12585
#12585
On CI, E2E tests should pass.
To test locally, follow the instructions in the [E2E tests documentation](https://docs.forem.com/tests/e2e-tests/).
N/A

Added E2E tests for #12585.

---

.github/PULL_REQUEST_TEMPLATE.md

This PR updates the pull request template to include a documentation option/link for Storybook, in the hope that it helps:
- remind contributors where our "source of truth" lives for Crayons
- encourage updates to the Storybook documentation when components are updated
N/A
Only requires a markdown check
N/A
- We should double check the PR template updates as expected, and the added link is working

Add Storybook as an option for PR documentation

---

app/javascript/chat/__tests__/requestManager.test.jsx

Depends on https://github.com/forem/forem/pull/12558
This test would pass no matter what it was looking for because the result is never `undefined`.
https://github.com/forem/forem/pull/12558#pullrequestreview-582692775

Fix a false positive test

---

spec/workers/follows/update_points_worker_spec.rb

This _should_ update the flakiness of https://github.com/forem/forem/issues/12456
I wasn't able to reproduce it locally but I understood how it might have happened, though I'm not 100% sure.
The function 
https://github.com/forem/forem/blob/11d85f75c7741362d5e5e5e29d84f5f2f0081f00/app/workers/follows/update_points_worker.rb#L66-L68
expects to parameters: occurrences and bonus. I determined that the bonus is always the same in each test, what change between the pre and post condition is the number of occurrences that goes from 1 to 2, when we add a new page view here:
https://github.com/forem/forem/blob/11d85f75c7741362d5e5e5e29d84f5f2f0081f00/spec/workers/follows/update_points_worker_spec.rb#L38
The entire computation is reduced to: `Math.log(3)` in the precondition (`1 occurrence + 1 …

Fix flakiness in Follows::UpdatePointsWorker

---

app/views/podcast_episodes/_liquid.html.erb

Prefer using `asset_path` over hard coding image path.
n/a
Missing piece to https://github.com/forem/forem/pull/11511
n/a

Replace liquid's hardcoded image path with #asset_path

---

app/javascript/chat/chat.jsx

It seems safe to remove these eslint restrictions.
No UI changes

Enable eslint in chat.jsx

---

docs/getting-started/config-env.md
docs/installation/linux.md
docs/installation/windows.md
docs/readme.md

I'm not sure when or how these links broke, but I noticed this when I was checking something unrelated :shrug: 
All of these links end up sending you here:

Fix broken doc links

---

.travis.yml
Gemfile.lock

Noticed that some builds had the following warning:
> Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.0). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.0`.
Decided to update bundler with the latest on https://rubygems.org/gems/bundler and to make sure Travis is using at least "2.2.x"
- https://docs.travis-ci.com/user/languages/ruby/#bundler-20
Hopefully the build will build

Update Bundler to 2.2.9

---

app/javascript/leftSidebar/TagsFollowed.jsx
app/javascript/leftSidebar/__tests__/TagsFollowed.test.jsx
app/javascript/packs/homePage.jsx

Take care of an old TODO :broom: 
Removing this div meant we might experience a regression around a hotfix made 11 months ago (see linked PRs).
https://github.com/forem/forem/pull/6688
https://github.com/forem/forem/pull/6689
If possible, I'd love @nickytonline's input on if it is safe to remove some of the code I removed.
I wasn't able to replicate the issue that led to these hotfixes, so I think it has been solved by a browser update or some dependency update in the last year. I'm including this note as documentation regardless.
No UI changes.
The "My Tags" sidebar should behave exactly the same! If the behavior hasn't changed at all, everything works! :smile: 
accessibility is impacted and tested. For more …

Replace redundant div with Fragment

---

app/javascript/topNavigation/utilities.js

Reverts forem/forem#12602
Rolling back this change as it's caused a regression with the menu during the logged in experience.

Revert "fix dropdown-menu not closing when click outside or click on a item on mobile"

---

docs/backend/auth-github.md

The auth url listed in the screenshot and in the description of the contributing guide to [GitHub OAuth authentication](https://docs.forem.com/backend/auth-github/) is incorrect. It will not authenticate through Devise.
Authenticate utilizing a GitHub application in a local environment using [the new instructions](https://github.com/ChaelCodes/forem/blob/cc-fix-github-auth-docs/docs/backend/auth-github.md).
Whatever tasks deploy changes to the contributing guide.

GitHub auth docs used the wrong url

---

app/javascript/chat/chat.jsx
app/javascript/chat/components/ChannelFilterButton.jsx

Slowly going to pull some of the extractable code out of Chat.jsx (which is like 2000 lines long) into components. Figured this was an easy place to start. Going to try keeping these PRs pretty small so they are reasonable to review.
https://www.loom.com/share/7d7a8bba1d614cdeb79827e8e0cf6d91
Nothing has changed specifically

Extract ChannelFilterButton from Chat.jsx

---

docs/installation/mac.md

- [x ] Documentation Update
Adding additional information to the Ruby section to help contributors who are not used to Ruby.
Also explicitly stating that the project must be cloned and forked before using rbenv install $(cat .ruby-version)
Also adding a common error Nick and I encountered with a solution.
- [ x] No, and this is why: Change to documentation that does not require a test. 
- [ x] This …

Update Ruby Section and Add Additional Error

---

app/views/layouts/application.html.erb

This PR fixes overflow issue for small breakpoint in certain situations.  FWIW this is a workaround until we have proper constraints and/or templates for heros.
I have also additionally updated existing template on https://forem.gitbook.io/forem-admin-guide/admin/html-variants - one of the properties (border) was causing this exact issue that was reported initially by @benhalpern  but adding `box-sizing: border-box` should prevent that from happening.
Closes #12650
Add a hero with some wild markup that would normally a horizontal scrollbar and preview it on mobile breakpoint. It should look just fine. …

Hero overflow fix

---

app/javascript/chat/components/ChannelButton.jsx
app/javascript/chat/components/ChannelFilterButton.jsx
app/javascript/chat/components/ChannelImage.jsx
app/javascript/chat/components/CreateChatModal.jsx

Adding missing JSDoc docstrings for Chat components

Add JSDoc comments to Chat components

---

bin/e2e

Small tweak to the local end to end test script.
- Run `yarn e2e` with out of date gems.
- bundle check should fail and stop the end to end test script without having run yarn.
N/A
shared_

Move yarn install to after potential bundle check failure in bin/e2e

---

app/controllers/chat_channels_controller.rb
app/services/moderator/manage_activity_and_roles.rb
docs/admin/readme.md
docs/backend/roles.md
spec/factories/users.rb
spec/policies/comment_policy_spec.rb
spec/requests/admin/tags/moderators_spec.rb
spec/requests/admin/users_manage_spec.rb
spec/requests/chat_channels_spec.rb
spec/requests/moderations_spec.rb
spec/requests/notifications_spec.rb
spec/services/mailchimp/bot_spec.rb
spec/services/moderator/manage_activity_and_roles_spec.rb
spec/system/admin/admin_bans_or_warns_user_spec.rb

As per the [comment in this PR](https://github.com/forem/forem/pull/12292/files#r572582649) by @citizen428, we're calling add_role and remove_role across the codebase using different code styles for the parenthesis around arguments. The general consensus as per Rubucop is to use them unless it's a DSL method like belongs_to. There were just a couple of cases in the codebase that used no parenthesis that I've amended.
These are some of the related cops. The tl;dr is use parenthesis unless it's an internal or framework DSL or when the method call has no arguments.
https://github.com/rubocop-hq/ruby-style-guide#method-definition-parentheses
https://github.com/rubocop-hq/ruby-style-guide#dsl-method-calls
https://github.com/rubocop-hq/ruby-style-guide#method-calls-with-no-arguments …

Parenthesis consistency for add_role and remove_role

---

app/javascript/chat/chat.jsx
app/javascript/chat/components/ChannelButton.jsx

This PR fixes one critical and one not critical issues on connect.
1. Basically a chat being covered with non-dismissible modal
2. Misaligned button.
Caused by #12625 
Go to Connect and if you can't see a modal on top of everything then it's good. …

Connect styles issues

---

app/controllers/admin/users_controller.rb
app/views/admin/users/_activity.html.erb
app/views/admin/users/_current_roles.html.erb
app/views/admin/users/edit.html.erb
config/routes.rb
spec/requests/admin/users_manage_spec.rb
spec/requests/admin/users_spec.rb

The "Definition of Done" for this RFC is:
> An admin can remove a role from a user successfully through the admin interface.
This PR adds the ability for admins to remove roles from users via the `/admin/users` dashboard. Admins have the ability to remove any role, other than the `super_admin` role, from any user other than themself. To accomplish this, I have done the following:
- Added a `#destroy` action to the `Admin::UsersController` that contains a conditional that prevents admins from removing `super_admin` roles and roles from themselves
- Added a `destroy` route to `routes.rb`
- Removed "Current Roles" from the `_activity.html.erb` partial and into its own partial, `_current_roles.html.erb` for design purposes
- Added a conditional to `_current_roles.html.erb` that conditionally …

Remove Roles via Admin

---

app/assets/javascripts/initializers/initScrolling.js
app/assets/javascripts/lib/pulltorefresh.js
app/assets/javascripts/utilities/slideSidebar.js
app/assets/stylesheets/components/header.scss
app/javascript/packs/homePageFeedShortcuts.jsx
app/views/articles/index.html.erb
app/views/layouts/_top_bar.html.erb
spec/system/articles/user_visits_articles_by_timeframe_spec.rb

This PR lays some groundwork to start rolling out skip link functionality to all pages in the app as per #1153. It applies some styling tweaks to the existing skip link (building on the changes & suggestions put forward in #10839) and changes it to link to `main-content` instead of  `articles-list`. 
The home page main ID is used for testing, as well as in initializers for the pull to refresh and scrolling functionality, so we'll need to make sure we test for any regressions.  
#1153
Behaviour is largely unchanged but I have made a couple of styling tweaks to the skip link itself (to correct the centering and add a focus outline). 
Before:
After:
On desktop:
- Load the home page and press Tab - the skip link should appear. If you tab again forwards/backwards, the skip link should …

Provide skip links: Tweak skip link style, refactor main area ID

---

app/javascript/readingList/readingList.jsx

Just some quick refactoring before working on #11983
The reading list section should still be able to archive and unarchive reading list items.
1. Navigate to http://localhost:3000/
2. In the feed, click on the save button of an article in the feed to add it to the reading list.
2. Navigate to http://localhost:3000/readinglist
2. Click on the _Archive_ button of the reading list item.
4. The archived item will disappear from the reading list.
5. A snackbar item at the bottom left of the screen should say "Archiving..." and then disappear after a second or two.
1. Navigate to http://localhost:3000/
2. In the feed, click on the save button of an article in the feed to add it to the reading list.
2. Navigate to http://localhost:3000/readinglist
3. Click on the _Archive_ button of the reading …

Change fetch to our request utility function.

---

app/assets/stylesheets/views/article-form.scss
app/assets/stylesheets/views/comments.scss
app/javascript/article-form/components/EditorBody.jsx

This PR fixes two issues:
1. Inconsistent padding on commenting textarea
2. Wrong font on `/new` view textarea.
Both were caused by the same optimization I've introduced the other day (unfortunately sometimes little issues like this are hard to catch).
- Closes #12711
If you can't reproduce behavior reported in #12711 then it probably works 👍  :D 
[Admin …

Ghost textarea fixes

---

app/javascript/readingList/readingList.jsx
app/javascript/searchableItemList/searchableItemList.js

Some general cleanup in the reading list component before getting started on #11983.
The reading list section should still be able to archive and unarchive reading list items.
1. Navigate to http://localhost:3000/
2. In the feed, click on the save button of an article in the feed to add it to the reading list.
2. Navigate to http://localhost:3000/readinglist
2. Click on the _Archive_ button of the reading list item.
4. The archived item will disappear from the reading list.
5. A snackbar item at the bottom left of the screen should say "Archiving..." and then disappear after a second or two.
1. Navigate to http://localhost:3000/
2. In the feed, click on the save button of an article in the feed to add it to the reading list.
2. Navigate to http://localhost:3000/readinglist
3. Click on the …

Reading List 15 minute fixes to prepare for #11983

---

.travis.yml

Removed an unnecessary call to `bundle exec rake data_updates:run` before E2E tests run on CI.
#12511 (fixes E2E tests that are failing in that PR)
E2E tests on CI should pass
N/A This is testing infrastructure
shared_

Removed  bundle exec rake data_updates:run for E2E on CI

---

app/javascript/topNavigation/utilities.js

Fixes a bug that made the profile dropdown menu stick forever unless the profile picture is tapped again
Closes #12466
1. Boot locally and use the mobile view in dev tools to preview as if it were a mobile device
2. Sign in -> Land in main feed
3. Tap profile picture (dropdown should appear)
4. Tap on a link from the dropdown (Dashboard, Settings, etc)
5. After the redirect the dropdown should disappear
6. Repeat step 4 a few times with different links and the dropdown should always disappear after the redirect
Video: https://share.getcloudapp.com/yAu6kk61
None (no changes we introduced to the DOM elements) …

Profile navigation menu dropdown fix in mobile

---

spec/requests/articles/articles_update_spec.rb

Added tests for updating article's collection to prepare for the articles update refactoring.
https://github.com/forem/forem/issues/3811

Specs for article collection update

---

app/assets/javascripts/utilities/buildArticleHTML.js
app/views/articles/_single_story.html.erb
spec/system/articles/user_visits_articles_by_tag_spec.rb
spec/system/homepage/user_visits_homepage_articles_spec.rb

Fixes https://github.com/forem/forem/issues/12513
All articles without comments should now read "Add comment" instead of "0 comments" when rendered in the feed.
The seed data should include some articles without comments, refreshing a few times on master should result in at least one "0 comments" example. After applying this commit, that won't happen anymore. :smile: 

Fix irregular comment count buttons

---

app/assets/stylesheets/components/header.scss

Fixes a bug related to Pull down to Refresh on iOS mobile devices
Closes #12786
2. Use mobile view in dev tools (you have to be on macOS Big Sur or use an iOS 14.x device)
3. Using the default theme pull down to refresh
4. Enable custom theme (i.e. Pink theme)
5. Go to main feed and Pull down to Refresh
6. You should not be able to see the "Skip to Content" button
None
None

Make Skip to Content button hide higher up outside of view
