- app/views/layouts/application.html.erb
- app/views/layouts/doorkeeper/admin.html.erb
- app/views/layouts/doorkeeper/application.html.erb
This PR fixes the errors resulting from running `bundle exec erblint app/views/layouts`.
This PR is part of #8370.
> Fix erblint errors on the `app/views/layouts` folder

- app/assets/stylesheets/top-bar.scss
Currently, the announcement feature [has a `z-index` of `101`](https://github.com/thepracticaldev/dev.to/blob/e532ccbe428809f4bda61e71712fc410cc67622e/app/assets/stylesheets/scaffolds.scss#L177), which is exactly the same as the `top-bar` element. The `top-bar` is the parent element for the user dropdown, so with the exact same z-index, the stacking order of these elements means that the `top-bar` always renders below the announcement, even though they have the same z-index. This PR bumps the `top-bar`'s `z-index` by `1`, such that its children (including the user settings dropdown) will always render above the announcement.
@atsmith813 brought this up in a separate PR's review [here](https://github.com/thepracticaldev/dev.to/pull/8409#pullrequestreview-429072836). …
> Bump top-bar's z-index to allow dropdown to render with announcement

- app/assets/javascripts/initializers/initializeBroadcast.js
- spec/factories/users.rb
- spec/system/homepage/user_visits_homepage_with_announcement_spec.rb
Takes the `display_announcements` column on the `user` into account when displaying an announcement. If a logge-in user has opted-out of announcements, the banner will not display. If the user has opted-in to announcements (the default!), then the banner will display.
This should not affect logged-out users, since they are not persisted anywhere (although they can dismiss the announcement still via clicking the `X`, which will persist a key in `localStorage`).
Closes https://github.com/thepracticaldev/dev.to/issues/8262.
HOW TO QA THIS PR:
**1. Create an active broadcast via `/internal/broadcasts`:**
**2. You should see the broadcast render throughout the site:**
**3. Go to your `/settings/misc` page, and opt-out of the announcements in your settings:** 
**4. Navigate throughout the site; …
> Hide site-wide messaging for opted-out users

- app/controllers/internal/broadcasts_controller.rb
Refactors our currently kind of messy `BroadcastsController`. Uses path helpers instead of hard-coded string paths, and uses `render` rather than `redirect_to` wherever applicable.
@atsmith813 brought up this in a separate PR's review [here](https://github.com/thepracticaldev/dev.to/pull/8409#pullrequestreview-429072836).
The best way to QA this is to click through creating/updating/destroying a broadcast and make sure everything works! (The tests for this do pass as well 👍)
> Refactor BroadcastsController

- bin/container-setup
The logic here is wrong. We need to set CONTAINER_RUNTIME before trying to running
docker-compose/podman-compose build.
#8255
> Fix container-setup logic #8255

- spec/services/suggester/users/sidebar_spec.rb
This spec failed for me in another branch bc the users were out of order. We don't care about the order here, just that we have the correct users so use match_array instead of eq
> Flaky Spec Fix: Ignore Order For User Suggestion in Sidebar

- spec/system/articles/user_visits_articles_by_timeframe_spec.rb
The following changes **cut the runtime for this spec in half.** It took it from running around 40 seconds to running around 20 seconds on my computer. Loading the feed page is a big ask and makes a lot of requests so rather than loading it 3 times for each assertion I moved the assertions into a common method since they are all the came and combined them for each scenario. I added the flag `aggregate_failures` so every assertion that fails will be reported, not just the first one. 
@snackattas
> Spec SpeedUp: Refactor and Combine Assertions for Viewing Articles by Timeframe Spec

- docs/tests/test-flags.md
- spec/rails_helper.rb
- spec/system/articles/user_visits_articles_by_tag_spec.rb
- spec/system/articles/user_visits_articles_by_timeframe_spec.rb
- spec/system/homepage/user_visits_homepage_with_announcement_spec.rb
- spec/system/user/view_user_index_spec.rb
Prior to this change, in order to fix a flaky js spec that had unwanted data showing up on the page we would have to clear all the data out of Elasticsearch. Clearing out that data is costly. I think a better way to solve this problem is to stub elasticsearch for these specs. I also think stubbing elasticsearch with the `stub_elasticsearch` flag is more clear about what is happening than having the flag `elasticsearch: <class name>`  on your spec.
Stubbing elasticsearch is also a lot faster than clearing it out and hitting it during the spec so +1 for speed up.
Credit to @vaidehijoshi for making rethink this approach to fixing these specs.
@snackattas 
#8388 
This is me putting Elasticsearch in a timeout
> Flaky Spec Fix: Stub Requests to Elasticsearch For some js: true Specs

- app/assets/javascripts/initializers/initializeBroadcast.js
- app/assets/stylesheets/scaffolds.scss
- app/javascript/packs/articleForm.jsx
- spec/system/articles/user_creates_an_article_spec.rb
Since the editor UI is a bit special, we want to hide any active announcements whenever a (logged-in) user goes to the editor page (`/new`). This PR adds functionality to hide an active announcement on that page, taking care to make sure it reappears on _every other_ page throughout the site.
Closes https://github.com/thepracticaldev/dev.to/issues/8372.
HOW TO QA THIS PR:
**1. Create an active announcement, and click through the site. The announcement should display on all pages.**
**2. Click on "write a post" or go to the `/new` route. The banner should disappear:***
**3. Go back to the main page by clicking the `X` from the editor or click the `DEV` icon in the top left. The banner should display throughout the site once again.**
*Note: there is a slight flicker that sometimes happens …
> Hide active announcements from logged-in users on the editor

- app/views/stories/_narrow_nav_menu.html.erb
- app/views/stories/_sign_in_invitation.html.erb
This PR fixes the errors resulting from running `bundle exec erblint app/views/stories`.
This PR is part of #8370.
> Fix erblint errors on the `app/views/stories` folder

- app/controllers/internal/configs_controller.rb
- app/javascript/onboarding/Onboarding.jsx
- app/javascript/onboarding/__tests__/Onboarding.test.jsx
- app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
- app/javascript/onboarding/components/IntroSlide.jsx
- app/javascript/packs/Onboarding.jsx
- app/models/site_config.rb
- app/views/internal/configs/show.html.erb
- app/views/onboardings/show.html.erb
- spec/requests/internal/configs_spec.rb
- spec/requests/onboardings_spec.rb
This allows admins to define the values for onboarding....
Addresses a portion of this...
https://github.com/thepracticaldev/dev.to/issues/5507
> Allow admins to define onboarding images in config

- app/views/onboardings/show.html.erb
Default `cloudinary` method size is 500 which is too small for splash images like this.
> Modify default size for onboarding graphic

- spec/requests/sitemaps_spec.rb
In this spec we are calling `Article.limit(3)` to update 3 articles and then we are calling `Article.first` and `Article.last` for our assertions with the assumption that `limit(3)` grabbed the first 3 articles. However, `limit()` does not order the articles 
```
[5] pry(main)> Article.limit(2)
Article Load (3.5ms)  SELECT "articles".* FROM "articles" LIMIT $1  [["LIMIT", 2]]
```
so there is no guarantee `Article.first` was in our original limit(3) list. This explicitly splits up the articles and ensures the article we assert is present in the sitemap is one we actually updated.
@snackattas
> Flaky Spec Fix:Sitemap: Don't assume Database Ordering, Explicitly Set Articles for Assertions

- spec/system/homepage/user_visits_homepage_articles_spec.rb
- spec/system/organization/user_views_an_organization_spec.rb
- spec/system/search/display_jobs_banner_spec.rb
- spec/system/user/view_user_comments_spec.rb
- spec/system/user_uses_the_editor_spec.rb
In #8453 I stubbed Elasticsearch for `js: true` specs that had recently failed due to Elasticsearch data displaying on the page when not expected. With the flag now an option I put a puts statement in the Search Controller to see what system specs hit Elasticsearch. Once I got that list I went down and found the ones that don't need it and stubbed it for all of those.
> Spec Cleanup: Stub Elasticsearch for js: true Specs that Dont Need it

- app/services/notifications/reactions/send.rb
- spec/requests/notifications_spec.rb
It appears that in some cases the existence of negative reaction is leaking into notifications.
> Remove private reactions from notifictaions

- .travis.yml
Currently, the Deploy stage will always run but only actually deploy if the branch is master and the deploy flag is present. This wastes a couple of mins to get a passing build on pull requests [so I figured out how to skip that stage altogether for PRs](https://docs.travis-ci.com/user/build-stages/#specifying-stage-order-and-conditions). 
We want notifications when any job fails so I moved the notification block out into the shared resources area which got rid of this warning and I think should fix that problem. Will have to wait til a merge to find out. 
`redis-server` was also giving us a warning so I changed that to redis per the warning suggestion
> Travis Speed Up/Fixes: Dont Run Deploy Stages for PRs, Fix Notification and Service Warnings

- app/controllers/github_repos_controller.rb
- spec/requests/github_repos_spec.rb
While #8382 fixed one problem, it introduced another, because I got confused between `Array#delete_if` (returns the modified array) and `Array#delete_at` (return the deleted element). This PR addresses the problem and 
#7751, specifically [this comment](https://github.com/thepracticaldev/dev.to/issues/7751#issuecomment-643412666)
1. Create a pin for a GH repo.
2. Delete repo.
3. Visit https://dev.to/settings/integrations and make sure the list of pinned/unpinned repositories is what you expect.
> Fix bug in determining if repo is featured

- app/javascript/packs/modCenter.jsx
This fixes the loading bug where the same articles are loaded multiple times.
1. Visit /mod
2. click on a tag view
3. visit "All topics" again
4. see that it shouldn't have duplicate articles
> Fix loading bug with mod center articles

- app/controllers/poll_skips_controller.rb
- app/models/chat_channel.rb
- app/models/data_update_script.rb
- app/models/poll_skip.rb
- spec/models/chat_channel_spec.rb
- spec/models/data_update_script_spec.rb
- spec/requests/chat_channel_memberships_spec.rb
- spec/requests/poll_skips_spec.rb
This PR contains three things:
- usage of [create_or_find_by](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-create_or_find_by) in `PollSkip`: which is a new Rails 6 methods with works only in certain cases, the goal here is to avoid the possible race condition of "find or create" where something can be created by a different thread between the find and the create (given the model this is used and the fact polls are not used much, it's not strictly necessary but it's a good addition to our tools ;)) *[this only works with a corresponding unique index]*
- bulk inserts for both memberships in a chat channel (going from N queries, one per each user, to 1)
- bulk inserts for data update scripts (I also moved stuff that was only used in tests as `private`, no point …
> Small ActiveRecord optimizations: begone race conditions and hello bulk insert

- app/controllers/internal/configs_controller.rb
- app/views/internal/configs/show.html.erb
- spec/requests/internal/configs_spec.rb
Before, whenever a site config was updated via the controller (`/internal/config`), it would remove the `default` email address, but still show it in the UI. This fixes it so the default email address is always set to the ENV variable. It also prevents it from being edited via a duplicate form in the view.
#8246 
1. Go to `/internal/config`
2. Add yourself as site config admin with:
```
me = User.find(your_id) # replace your_id with your actual ID
me.add_role :single_resource_admin, Config
```
2. Submit the form via the update button in the view
3. Check in console that the email address is still present:
```
SiteConfig.email_addresses
#=> :default should point to your ENV variable
```
Don't update any site config variables until this is merged!
> Always set the default email address to ENV variable

- spec/factories/articles.rb
Fixes the following flaky specs(and likely others) by ensuring that ALL article titles are unique: 
```
1) User comments when user is unauthorized does not show user's articles
Failure/Error: expect(page).not_to have_content(article.title)
expected not to find text "Caesar Salad" in "View All Activity\nAll 2 Comments\nre: Souvlaki Jun 15\nDrinking stumptown etsy small batch banh mi tofu flannel medi...\nre: Caesar Salad Jun 15\nTaxidermy quinoa post-ironic shoreditch. Vinegar vice swag."
1) Articles GET /feed when :username param is not given returns only featured articles
Failure/Error: expect(response.body).not_to include(not_featured_article.title)
expected "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rss version=\"2.0\">\n  <channel>\n    <title>DEV(local... …
```
> Flaky Spec Fix: Ensure Article Titles are Unique

- spec/requests/stripe_active_cards_spec.rb
While updating rack to fix our bundle audit failure #8696 I had a bunch of specs in `spec/requests/stripe_active_cards_spec.rb` fail with the following error
```
1) StripeActiveCards POST /stripe_active_cards increments sidekiq.errors.new_subscription in Datadog on failure
Failure/Error: sign_in user
ActiveRecord::RecordNotFound:
Couldn't find User with 'id'=1097
```
Upon looking in the file I noticed we were persisting the user through the spec so if anything removed it the rest of the specs would fail. I updated the spec so the user is created for each spec rather than persisted. 
@snackattas
> Flaky Spec Fix: Replace let_it_be_changeable with let for stripe spec

- app/controllers/internal/configs_controller.rb
- app/models/site_config.rb
- app/views/internal/configs/show.html.erb
- spec/requests/internal/configs_spec.rb
This adds a special footer mascot image for use in #8684. 🦥
> Add special footer mascot image to config 🦥

- app/labor/timeframer.rb
- spec/labor/timeframer_spec.rb
We cannot be freezing Timestamps in our Timeframer bc that will cause it to become inaccurate since the timestamps will be frozen to the time the application boots up. The longer the application has been booted, the more inaccurate these will be. This became very apparent when a spec ordering issued caused this class to be instantiated while Timecop had time frozen in March 2019 which caused later specs to fail.
> Bug Fix: Dont Freeze Timeframer Timestamps bc They Will be Inaccurate

- app/labor/flare_tag.rb
- spec/requests/async_info_spec.rb
Prefer caching ActiveRecord ids instead of ActiveRecord objects. Also updated cache name for clarity and invalidation.
https://github.com/thepracticaldev/dev.to/projects/9#card-39519016
n/a
> Update FlareTag not to cache AR object

- spec/system/articles/user_visits_articles_by_tag_spec.rb
When a title has a special character in it like an apostrophe, the CGI Escape will break this test so I removed it.
Fixes https://travis-ci.com/github/thepracticaldev/dev.to/jobs/349958000:
```
1) User visits articles by tag when user hasn't logged in when 2 articles shows the correct articles
Failure/Error: expect(page).to have_text(CGI.escapeHTML(article3.title))
expected to find text "It&#39;s a Battlefield499" in "FEED WEEK MONTH YEAR INFINITY LATEST\n<MY DEV(local) FEED>\nToney Kozey\nJun 15\nAbsalom, Absalom!497\n#javascript #iot\nReactions 0  reactions\n1 min read Save Saved\nToney Kozey\nJun 3\nIt's a Battlefield499\n#functional #javascript\nReactions 0  reactions\n1 min read Save Saved\nloading..."
```
> Flaky Spec Fix: Dont CGI Escape Title Compare

- spec/services/bulk_sql_delete_spec.rb
This spec tends to be very flaky when run with the entire sweet. The reason for this is because we use transactional fixtures for our tests which means for a test like this we open a transaction but never commit it bc we want to roll it back at the end of the test example. This means our end count is not going to be what we expect. However, the result returned from the delete statement is correct so I choose to assert that it equals the number of records we would expect to delete.
@snackattas
> Flaky Spec Fix: Assert Result of Delete Statement Rather Than DB State

- db/migrate/20200616200005_add_index_to_articles_public_reactions_counts.rb
- db/schema.rb
Another one of our most time consuming queries is fetching articles by timeframe and sorting them by public_reactions_count. The PR adds a sorted index for public_reactions_count which Postgres can use to optimize this query.
> Optimization: Add Index to Article Public Reaction Counts for Sorting

- app/assets/stylesheets/comments.scss
Small issue on small screens for comment dropdown is displayed outside the viewport. This may not be the best way to fix this bug sharing this as it seems to fix the issue for me. Not even sure if we need to move it slightly more.
In production with a mobile device (small screen) try to open the dropdown of an article's comment and you'll see this:
With the fix it should display like this:
Nope
> Makes the dropdown on comments display correctly for small screens

- config/environments/development.rb
PR https://github.com/thepracticaldev/dev.to/pull/8732 had issues passing Travis due to ordering errors. Trying this again on a new branch/pr....
This PR tweaks the allowed host on Gitpod. Gitpod preview URLS are in the format <port>-<workspace_url>. Our currently configuration is only allowing <workspace url>, leading to a 'blocked host' error. I've added a wildcard in front of that url to allow for serving on any port.
> Use regex for gitpod allowed host

- app/views/articles/show.html.erb
- spec/requests/stories_show_spec.rb
The article _preamble_ is not actually part of the title but the latest change made it lose its styling.
This helps place it distinctively separate from the title, like such:
Done with utility classes rather than a hack. Definitely a win 😄
> Fix article preamble style

- Procfile.dev
- config/initializers/0_application_config.rb
- config/initializers/content_security_policy.rb
- config/webpacker.yml
- scripts/app_domain
- spec/initializers/application_config_spec.rb
Developing dev.to on a remote box is currently broken. This PR fixes that.
* webpack-dev-server ignores CLI arguments, so switched to environment
variables.
* Dynamically determine remote webpack host via APP_DOMAIN environment
variable, defined in application.yml.
* Setup content security policy to allow connecting to webpack on a
remote box, defined by APP_DOMAIN environment variable.
#7706
> Adapt dev env to run on a remote box

- app/helpers/articles_helper.rb
- app/views/articles/show.html.erb
- spec/views/articles_spec.rb
So far we only added "Originally published at" for articles imported from feeds, but not for posts that had a canonical URL set. This has confused several users in the past, including your truly.
Closes #8726
Note the missing "on <timestamp>" if we only have a canonical URL.
> Display 'Originally published' for canonical URLs

- app/models/article.rb
- app/models/concerns/user_subscription_sourceable.rb
- app/models/user.rb
- app/models/user_subscription.rb
- db/migrate/20200617014320_add_subscriber_email_to_user_subscriptions.rb
- db/migrate/20200617014509_add_subscriber_email_index_to_user_subscriptions.rb
- db/schema.rb
- spec/factories/user_subscription.rb
- spec/models/article_spec.rb
- spec/models/shared_examples/user_subscription_sourceable_spec.rb
- spec/models/user_subscription_spec.rb
I had another PR ready to go, but it became quite large so this is me breaking it out into smaller chunks. This PR adds a `subscriber_email` field to `user_subscriptions` so we can record the subscriber's email address at the time of subscription to display to an author.
For the scope of this feature and CodeLand, a user can subscribe to an author via an article one time. If they change their email address, they cannot re-subscribe to the same article with the new email address. That functionality will be in a future iteration post-CodeLand.
We are also intentionally allowing an author to subscribe to themself. That way they can test and experiment on their own.
I've included some name changes for some relationships and updated some DB indexes.
```ruby
subscriber = User.last
article = …
```
> Add subscriber_email to user_subscriptions & more backend updates

- app/controllers/application_controller.rb
We recently deployed ahoy for tracking events, but it also tracks _all visits_ by default; this is going to end up being a lot of visits, and we probably want to incrementally add visit tracking in (rather than turning them all on).
This `skip_before_action` will stop us from collecting a ton of visit data.
Pull down this PR, and click around the site. You should not see any new `Ahoy::Visit`s being created in the database. Without this line, you _should_ see them, and that's what is currently live in production.
> Turn off ahoy visit tracking

- app/views/articles/show.html.erb
We are having an issue where the footer sometimes disappears on navigation. This is because it is _inside_ a div it should be _after_, due to a missing closing tag caused by this mismatch.
Missing html closing tags are the worst!!
> Fix div/aside mismatch

- app/javascript/articles/__tests__/Article.test.jsx
- app/javascript/articles/components/CommentsCount.jsx
- app/javascript/articles/components/ReactionsCount.jsx
Comment/reaction counts were accidentally moved to _within_ the span that hides for small screens. It is only supposed to be the _word_ that is hidden.
This PR fixes that.
Currently:
Should look like:
> Fix comment/reaction count hiding issue on narrow screens

- app/javascript/contentDisplayPolicy/initHiddenComments.js
- app/views/comments/_comment_proper.html.erb
#7747  What type of PR is this? (check all applicable)
While triaging an issue I randomly noticed that the "Hide" buttons on comments look quite out of place in the new design:
This PR changes the link from a `button` to an `a` tag and applies Crayon styles.
> Style hide link with Crayons

- app/assets/stylesheets/scaffolds.scss
The PR being referenced by this comment (https://github.com/thepracticaldev/dev.to/pull/8234) has been merged, but I think we actually _do_ want these styles to stay here after testing this feature locally both with and without the explicit `position` and `z-index` properties.
#8234
Here's how these styles look currently after #8234 was merged:
_Fixed header:_
_Static header:_
> Remove outdated comment in scaffolds.scss

- app/views/notifications/index.html.erb
After recently [adding tracking to welcome notifications](https://github.com/thepracticaldev/dev.to/pull/8758), I checked up on the `Ahoy::Event`s associated with welcome notifications. As it turns out, some of the click events for our welcome notifications aren't being tracked with a "title". Here's a screenshot from the [relevant blazer query](https://dev.to/internal/blazer/queries/96-welcome-notification-events):
The "empty" title is due to an empty `target.parentElement.id` on the click `event` object. 
**When I tried to investigate this locally, I could not ever get an empty `id` to appear in tracked events; in other words, I could not reproduce this locally and everything seems to work correctly on dev. This leads me to believe that something is different about the notifications on …
> Notify Honeybadger when no id can be found for a welcome notification

- app/controllers/page_views_controller.rb
- app/javascript/crayons/guidelines/__stories__/guidelines.stories.jsx
- app/javascript/listings/__tests__/ListingDashboard.test.jsx
- app/javascript/listings/dashboard/listingRow.jsx
- app/labor/markdown_parser.rb
- app/models/site_config.rb
- app/views/articles/index.html.erb
- app/views/articles/manage.html.erb
- app/views/articles/tag_index.html.erb
- app/views/internal/pages/_form.html.erb
- app/views/pages/_coc_text.html.erb
- app/views/pages/_editor_frontmatter_help.html.erb
- app/views/pages/_editor_guide_text.html.erb
- app/views/pages/_editor_liquid_help.html.erb
- app/views/pages/_v1_editor_guide_preamble.html.erb
- app/views/pages/generator.html.erb
- app/views/pages/markdown_basics.html.erb
- app/views/pages/privacy.html.erb
- app/views/pages/rlyweb.html.erb
- app/views/stories/_narrow_nav_menu.html.erb
- app/views/users/_account.html.erb
- app/views/users/_publishing_from_rss.html.erb
- config/initializers/s3_direct_upload.rb
- public/404.html
- spec/factories/users.rb
- spec/requests/page_views_spec.rb
Across our app, we have a two different variations of how we link to URLs. In the majority of cases, we link to `/foo`, but in some instances, we link to `/foo/`. Google gets pretty confused when we do this; it interprets these as _two different URLs_. When they both resolves successfully (with a status of `200`), Google is forced to pick between the two. The issue with this is that it splits up our "link equity" for those pages, since Google sees them as two links. Instead, we'd much prefer to consolidate all of our "SEO juice" and link equity around _one, standardized link_.
Thus, in an effort to boost SEO, we really need to standardize around _one_ way of representing links, since, at the end of the day, we only want one representation of each URL.
Ideally, we will want to …
> Remove trailing slashes from URLs to improve SEO

- config/initializers/ahoy.rb
I recently made a change to turn off ahoy from [tracking visits by default](https://github.com/thepracticaldev/dev.to/pull/8782). However, it still seems like we are tracking a small amount of them, and it's unclear where exactly those visits are being "tracked" from. I am honestly still not entirely sure what is causing these to be "tracked".
However, as it turns out, this library defaults to `Ahoy.server_side_visits` being set to `true`. I suspect that this default is what is causing some of this "unexplained tracking" to occur. This PR sets that configuration to `:when_needed`, which should only create an `Ahoy::Visit` when it is needed by an `Ahoy::Event`.
According to the `ahoy` docs:
> You can also defer visit tracking to JavaScript. This is useful for preventing bots (that aren’t …
> Only track server-side events when needed

- spec/requests/listings_spec.rb
- spec/requests/pages_spec.rb
This fixes messages similar to:
> DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (3 levels) in <top (required)> at /home/travis/build/thepracticaldev/dev.to/spec/requests/listings_spec.rb:43)
> Rails 6: replace deprecated content_type with media_type

- app/assets/stylesheets/minimal.scss
- app/assets/stylesheets/notifications-welcome-broadcast.scss
- app/assets/stylesheets/notifications.scss
This PR extracts the styling for Welcome Broadcasts (`.broadcast-content`) into its own stylesheet, `notifications-welcome-broadcast.scss`. Extracting the Welcome Broadcast styles into its own stylesheet will make it easier to revamp our Welcome Notification styling (see #7169).
In addition to this extraction, this PR also adds `notifications-welcome-broadcast.scss` to `minimal.scss` and adds TODOs for future stylesheet iterations.
Related to #7169 
**To QA these changes, pull down this code and poke around your local notifications to ensure that nothing has been broken:**
> Extract Welcome Broadcast Styling Into Its Own Stylesheet

- app/services/rss_reader.rb
I am knee-deep in this spec trying to fix some other issues and the solution to this error we have been seeing for a long time just hit me. Figured I would throw out a fix for it. 
Fixes: https://app.honeybadger.io/fault/66984/da4122ad1fd544ac460dbd445a3b1dd7
```
TypeError:
no implicit conversion of true into Array
```
> Bug Fix: Return An Empty Array if Error Occurs in RSS Reader

- app/assets/javascripts/base.js.erb
We're still getting `ahoy_visits` despite _not_ tracking them on the server side. I am not sure if this change will solve the issue that I'm seeing in terms of the uptick of visits, but I think there are two changes we need to make, setting `trackVisits` to `false`, and setting `cookies` to `false`. I'm going to follow the scientific method and only make one change at a time to see what happens.
**This PR adds `cookies: false` to the ahoy.js configuration.**
According to [the docs](https://github.com/ankane/ahoy#gdpr-compliance-1), if you set `Ahoy.cookies = false`, then you also will need to set `ahoy.configure({cookies: false});`
Blazer query of [growing `ahoy_visits`](https://dev.to/internal/blazer/queries/101-ahoy-visits-per-day).
All tests should pass, and theoretically, when we …
> Disable ahoy.js cookie tracking

- app/models/notification.rb
This popped up as a flaky spec failure where commentable was missing when we went to send the mod notification. To be honest, this scenario could occur as well in the app if a user submits a comment and then the article is deleted at nearly the same time. We support comments without commentable's so this change helps support that in addition to fixing the flaky spec. 
```
1) Comments DELETE /comments/:comment_id deletes a comment if the article has been deleted
Failure/Error: return if UserBlock.blocking?(notifiable.commentable.user_id, notifiable.user_id)
NoMethodError:
undefined method `user_id' for nil:NilClass
```
@snackattas
> Flaky Spec/Bug Fix:Dont Send Mod Notification if No Commentable

- app/controllers/dashboards_controller.rb
- app/views/dashboards/_analytics.html.erb
- app/views/dashboards/_dashboard_article_row.html.erb
- app/views/dashboards/show.html.erb
- spec/requests/dashboard_spec.rb
The dashboard on _my_ account has gotten _super_ slow just due to the raw number of posts that we are rendering all at once if you have _many_ posts. So this wouldn't be an issue for most, but some users (power users) have a really really slow dashboard.
This reduces that worst case scenario by rendering 50 posts at a time.
We use the Kaminari gem which comes with this helper which generates its own classes. Not exactly the most crayons-friendly situation, but we could switch to custom implementation later. I think the plain text links are solid here.
> Paginate /dashboard posts

- app/views/listings/index.html.erb
This should fix ~60 axe warnings on this page. This commit also removes
some markup that is being overwritten by Preact.
There are no UI changes.
> Fix accessiblity warnings on Listings page

- app/assets/javascripts/initializers/initializeDashboardSort.js
- app/views/dashboards/show.html.erb
@joshpuetz caught `dashhboard_sort` so I replaced it with `dashboard_sort` and also cleaned up the initializer
https://github.com/thepracticaldev/dev.to/pull/8868/files#r444518992
Open the dashboard and click on the sorting dropdown
> Fix typo in dashboard sort element name

- app/controllers/reactions_controller.rb
- spec/requests/moderations_spec.rb
- spec/requests/reactions_spec.rb
Currently we remove mod reactions when a new reaction is created, but unless I'm mistaken about what the intended behavior should be, we should _not_ be removing non-mod reactions.
> Only clear negative reactions when using thumbsup

- app/assets/javascripts/base.js.erb
This PR is a continuation of https://github.com/thepracticaldev/dev.to/pull/8866. There are still `ahoy_visits` being created; I actually don't think this configuration is going to help us but I want to try it out since I want to eliminate the JS side of this completely while investigating these "ghost" visits.
According to [the docs](https://github.com/ankane/ahoy.js#configuration):
> When `trackVisits` is set to `false`, Ahoy.js will not attempt to create a visit on the server, but assumes that the server itself will return visit and visitor cookies._
**This PR adds `trackVisits: false` to the ahoy.js configuration.**
Blazer query of [growing `ahoy_visits`](https://dev.to/internal/blazer/queries/101-ahoy-visits-per-day).
All tests should pass, and theoretically, when we deploy this, we …
> Disable ahoy.js visit tracking on server-side

- app/views/comments/index.html.erb
This is a _small_ adjustment which links to `#comments` for non-logged-in users because this is better for SEO than `/comments` because `/comments` is its own URL sucking away link juice.
This is a small fix which won't impact a lot of things, but since not _all_ comments are visible in the `#comments` version at the moment it doesn't make sense to make this a wholesale change all at once.
> Use fragment for linking to comments for SEO

- app/models/application_record.rb
There's a bug in production right now where `User.estimated_count` sometimes returns 0 instead:
This happens because in production, the Postgres result of the query is (sometimes?) an array of two hashes:
```ruby
[{"count" => 0}, {"count" => 401041}]
```
However I couldn't reproduce this locally, and only had one element in my `result` array. So I decided that `max_by` was the best choice, even though it'll make the method a bit slower.
1. Go to `rails console`
2. Run `User.estimated_count`
3. Should run successfully
No, but we'll need to monitor the places where this is used (partnerships page, signed out CTA, and the workers that rely on this method).
> Use max_by to get the highest value, for estimated_count 

- Envfile
- app/lib/app_secrets.rb
- config/initializers/vault.rb
- spec/lib/app_secrets_spec.rb
Envied is setup so that anything we add to the Envfile is REQUIRED to be present in Production which is not what I want for option Vault variables. I always forget this detail 🤦‍♀️  This removes the from the file so the app can load without them present.
> Remove Vault ENV variables from Envfile so they arent Required in Prod

- app/views/notifications/index.html.erb
This builds on https://github.com/thepracticaldev/dev.to/pull/8831 (please read the PR's description for the full context).
The issue I am trying to debug is why this sometimes happens when a user clicks on a welcome notification link:
The Honeybadger call to `notify` in the JS function for tracking a click event on a welcome notification is not reliable right now since our [JS Honeybadger project](https://app.honeybadger.io/projects/67192/faults?q=-is%3Aresolved+-is%3Aignored) does not reliably send _all_ of the frontend errors (because we send too many and get rate limited 😓).
Since I can't rely on the call to `notify`, I need to be able to debug this in another way. My solution is to 
[Relevant Blazer query](https://dev.to/internal/blazer/queries/96-welcome-notification-events)
All …
> Track an event's target when clicking on a welcome notification

- app/javascript/.eslintrc.js
This is just another change to our ESLint rules. We're still keeping with recommended rules, this time with the [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) recommended rules.
Recommended import warnings and errors have been put in place as well as an import order rule. The import order rule enforces an order to imports, but it gets automatically fixed via EsLint's CLI arg `--fix`. This means no friction on a contributor to the code base.
So for example, the snippet below would result in an error because an npm package is imported after a local file.
```javascript
import { h, Component } from 'preact';
import { MyComponent } from './MyComponent';
import PropTypes from 'prop-types';
```
Once committed to the code base though, it gets corrected to the snippet …
> Enabled ESLint canned import rules as well as the import order rule (fixable via --fix)

- app/views/service_worker/index.js.erb
We seem to have a lot more issues with service workers on iOS safari than anywhere else. I think it's probably best to avoid that platform for now. It already had the worst support.
> Avoid running service workers on ios

- app/models/application_record.rb
Follow up to #8890. Our production DB has views created by Blazer, we query by also filtering out only ordinary tables:
From https://www.postgresql.org/docs/11/catalog-pg-class.html
```text
relkind | char |   | r = ordinary table, i = index, S = sequence, t = TOAST table, v = view, m = materialized view, c = composite type, f = foreign table, p = partitioned table, I = partitioned index
```
#8890
> Filter only ordinary tables in estimated count

- .vscode/launch.json
Introduces a small change when debugging jest tests in VS Code. Now all npm packages are blackboxed so they do not get stepped into while debugging.
N/A
> Blackboxed node_modules when debugging jest tests in VS Code

- docs/backend/readme.md
- docs/backend/tracking.md
- docs/frontend/readme.md
- docs/frontend/tracking.md
I added [tracking documentation](https://github.com/thepracticaldev/dev.to/pull/8914) but totally forgot to actually _link_ to it from the sidebar for the frontend and backend sections' readme's! This fixes that so that folks can actually _get to_ the docs :)
Builds on https://github.com/thepracticaldev/dev.to/pull/8914.
Here's what this will now look like when we link to the docs (my local version):
Frontend sidebar:
Backend sidebar:
N/A
> Link to tracking docs from gitdocs sidebar

- config/webpack/environment.js
According to their [troubleshooting section ](https://docs.honeybadger.io/lib/javascript/support/troubleshooting.html#if-you-are-uploading-your-source-map)
> Does the Minified URL for your source map match the minified URL in your JavaScript stack trace? The URLs must match exactly, with the exception of wildcards and query strings (which are ignored).
With that, I can no longer rely on `APP_PROTOCL` and `APP_DOMAIN` because all the errors stack traces are not coming from `dev.to` urls. I have to set a new env var `ASSETS_URL` (already added on Heroku) for this new purpose.
🤞 
https://github.com/thepracticaldev/dev.to/pull/8899
On production ☠️ 
n/a
> Update Honeybadger's assetsUrl

- app/views/dashboards/_analytics.html.erb
- spec/system/dashboards/user_visits_dashboard_spec.rb
We're showing the total amount of credits, including those spent, instead of only the available ones
Closes https://github.com/thepracticaldev/dev.to/issues/8924
1. use `Credit.add_to(user, AMOUNT)` to add yourself credits
1. create a new listing and purchase it with said credits
1. go to http://localhost:3000/dashboard and make sure the count is accurate and it's the same as http://localhost:3000/credits and http://localhost:3000/listings/dashboard
> Fix available credits count in dashboard

- app/assets/javascripts/initializers/initializeArchivedPostFilter.js
Fixes the problem found in #8911 
#8911 
When using the PWA the button to toggle (show/hide) archived posts used to open in a new tab (with a bad URL). It now looks like this:
https://share.getcloudapp.com/6qu2vnNm
> Fixes archived button in dashboard for PWA

- app/views/articles/tag_index.html.erb
- app/views/articles/tags/_meta.html.erb
- spec/requests/stories_index_spec.rb
- spec/system/articles/user_visits_articles_by_tag_spec.rb
This PR updates the tag page to the crayons look. Even though we have plans for further updates, I think unifying this design right now even if we plan to change it again makes sense.
But this PR also removes links to `/top/` `/latest` etc. for non-logged-in, as these extra links are non-value-adding for SEO and create a lot of cruft for our overall link tree. These would still be accessible if visited directly, but it's a simpler model for the crawling of our site.
Here are the two states a user would now see....
Also added "Page X" to title tags to also help create distinct pages that don't share title, for SEO.
> Remove sort links from tags for logged-out (SEO)

- app/views/service_worker/index.js.erb
Both `/feed` and `/rss` point to the same route but we only skip one of the two
> Tell the service worker to skip /rss

- .travis.yml
- bin/knapsack_pro_rspec
This PR enables [Queue mode for KnapsackPro](https://youtu.be/hUEB1XDKEFY). In Regular Mode KnapsackPro will make a single call on each node at the beginning of a CI run to request a set of specs based on historical timing data. In our case since we have 3 nodes, we get 3 batches that are as even as possible. However, as the tests run, one batch may hit some retries or failed specs and end up being much slower than the others. Queue Mode helps mitigate this problem. 
In Queue Mode, each node will start by pulling a small set of a few specs. Once those specs are run then the node will pull another few specs. This will occur until all the specs in our suite have been run. By doing it this way, if one node is cranking through specs quickly then we will end up sending more specs to it rather …
> Feature: Introduce KnapsackPro Queue Mode

- app/assets/javascripts/initializers/initializeBroadcast.js
Because of the way that the mod tools sidebar relies on iframes, any active broadcasts were being rendered twice: once on the main site, and once within the mod tools iframe, which re-invoked all the initializers and their JavaScript when the iframe itself re-rendered. Unfortunately, iframes also create their _own_ window context, which means that this issue can't simply be solved by setting a flag on the window (in other words, something like `window.broadcastVisible` wouldn't work!).
The best solution here is to not re-invoke the `initializeBroadcast` function if its caller is the mod tools sidebar; the best way to determine that is by using the path, which will include `actions_panel` within it. 😓 
Closes https://github.com/thepracticaldev/dev.to/issues/8774.
After …
> Do not render active announcements in iframes

- docs/installation/windows.md
- move `rbenv install` and `rbenv global` to after repository clone
- remove rails install, as `bin/setup` handles it and since ruby is installed after clone, the command wouldn't work earlier in the docs.
Fixes #8186 
For Testing purposes, one would have to perform a clean install on a new `WSL` environment while making sure none of the prerequisites which are to be installed on Linux are served via windows, e.g. Yarn.
> fix `rbenv install` failing for windows docs

- app/controllers/internal/application_controller.rb
- app/controllers/internal/secrets_controller.rb
- app/lib/app_secrets.rb
- app/models/secret.rb
- app/views/internal/secrets/index.html.erb
- config/routes.rb
- spec/lib/app_secrets_spec.rb
- spec/requests/internal/secrets_spec.rb
This PR gives admins the ability to update secrets in Vault from our internal namespace. If Vault is not enabled for an application then we will simply list the secrets with a warning. NOTE: These three keys are probably much better suited for SiteConfig but I wanted something low risk to test the first run of Vault with and I figured these were a good choice. With that said **Vault is still DISABLED** on dev. This PR is simply putting in place the infrastructure to update it once its activated. 
Vault Enabled
Vault Disabled
Vault Secret Updated
https://github.com/thepracticaldev/dev.to/projects/9#card-40734891
If you would like to test this PR you will first need to setup Vault as explained in #8936. Once you have it all setup visit `http://localhost:3000/internal/secrets` and try …
> Feature: Setup Admin Area to Update Vault Secrets

- spec/rails_helper.rb
By removing the scheme here `allow` will then be able to match [only using the host](https://github.com/bblimke/webmock/blob/e386be1cb3652c83d76fec57847ea4bed581b992/lib/webmock/webmock.rb#L79) without worrying about the rest of the URL. This will allow URLs like `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_83.0.4103` to be allowed even though we dont explicitly list that URL.
Fixes:
```
1st Try error in ./spec/system/articles/user_creates_an_article_spec.rb:16:
Real HTTP connections are disabled. Unregistered request: GET https://chromedriver.storage.googleapis.com/LATEST_RELEASE_83.0.4103 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'chromedriver.storage.googleapis.com', 'User-Agent'=>'Ruby'}
You can stub this …
```
> Flaky Spec Fix: Use Host Only For Allowing Webmock Connections

- app/assets/stylesheets/internal/layout.scss
Noticed this weird space in `/internal`. :smile:
It's there to make space for the header elsewhere on the site, but that isn't necessary in internal.
Before:
After:
> Override header padding for internal

- app/views/articles/show.html.erb
This script is causing a bit of noise on honeybadger. This PR temporarily disabled script as it's not currently being utilized.
Supersedes https://github.com/thepracticaldev/dev.to/pull/9004
https://app.honeybadger.io/projects/67192/faults/65072311
https://app.honeybadger.io/projects/67192/faults/65177881
https://app.honeybadger.io/projects/67192/faults/65072294
Start the server and browse the web page normally. There should be no JS errors in browser console.
n/a
> Disable UserSubscriptionTag::script

- app/javascript/chat/chat.jsx
When the channel list is loaded on `loadChannels` the state is asynchronously set, which causes `triggerSwitchChannel` to not receive the channel list.
Bug fixed: https://share.getcloudapp.com/04uYEKPP
> Fixes triggerSwitchChannel on channel list load

- spec/rails_helper.rb
I thought I had finally put the following spec failure behind us but then it popped up again as soon as I turned on queue mode. So I went back to digging and remembered that with queue mode we are resetting `WebMock` between suite runs(batches of tests). When we do that we need to ensure we still allow all the sites we originally allow at the beginning when the code is loaded and not just "api.knapsackpro.com".  
Fixes this in queue mode: 
```
1st Try error in ./spec/system/articles/user_creates_an_article_spec.rb:16:
Real HTTP connections are disabled. Unregistered request: GET https://chromedriver.storage.googleapis.com/LATEST_RELEASE_83.0.4103 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'chromedriver.storage.googleapis.com', …
```
> Flaky Spec Fix: Make Sure to Allow All Sites After Suite

- app/javascript/chat/channels.jsx
- app/javascript/chat/chat.jsx
- app/javascript/chat/components/channelButton.jsx
When a user tries to directly load the URL for a discoverable Connect channel in which they are not members already we should present the CTA to request access.
This PR triggers a click on the `ChannelButton` component after it's mounted if it corresponds to the active channel
With a discoverable channel that you are not a member of yet, follow the link directly to that channel and the CTA to request access should appear automatically.
Video sample of the test:
https://share.getcloudapp.com/JruLO8v7
> Discoverable channel will open CTA to request join if not available

- app/views/users/_org_non_member.html.erb
Currently, the secret code will show up in the input history. That, I think, means that anyone that can open that page in a shared browser instance could join the org.
NOTE: I'm not a Ruby developer, so I'm only guessing that this change will resolve the issue. The intent is to add `autocomplete="off"` to the text input. [More information about the autocomplete attribute can be found here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)
> Hide secret code from input history

- app/controllers/internal/chat_channels_controller.rb
- app/views/internal/chat_channels/index.html.erb
- spec/system/internal/admin_manages_chat_channels_spec.rb
This PR allows for users to search internal chat channels by their name.
Fixes #8997.
Nope.
> Allow internal chat channels to be searched by their name

- app/models/notification.rb
the Notifications table has gotten quite large so we have decided to shrink the time we hold on to notification to 3 months to reduce its size and help performance.
> Optimization: Default Delete Notifications Older than 3 months

- app/services/broadcasts/welcome_notification/generator.rb
Currently, the `Broadcasts::WelcomeNotification::Generator` checks a few things when it runs (once a day) before sending out welcome notifications to new users. Specifically, for each notification, it checks whether the user has already received a notification for a broadcast, as well as whether the user's `created_at` is beyond a certain date or not. Sometimes, the generator also checks for some other conditions to be met, as well.
The generator already has access to the `user` when it runs, so checking the `user.created_at` is a relatively low-effort task, and doesn't require querying the database. However, checking whether a notification for a broadcast _already exists or not_ requires querying the DB. Currently, we're doing the DB query before checking the user's `created_at`, which …
> Optimize WelcomeNotification::Generator by only querying when necessary

- app/assets/stylesheets/chat.scss
References #8998  
On the connect page I hide the scrolling of the chat and make scrolling of the chat channel as auto. This separates the scrolling between the chat and channel which fixed the issue #8998
> change the connect Scrolling

- app/views/dashboards/_dashboard_article_row.html.erb
On our dashboard the IDs for the hidden fields denoting whether or not an article is archived had non unique IDs, which leads to messages like this in the Chrome devtools:
> [DOM] Found 15 elements with non-unique id #article_archived
IDs should be unique so this PR fixes that by appending the article's id.
Closes #8941
1. Go to the article dashboard (`/dashboard`)
2. Inspect the `id` attributes of the hidden `input` tags with name `article[archived]`
> Unique IDs for hidden article_archived fields

- app/javascript/shared/components/tags.jsx
- app/models/tag.rb
- spec/models/tag_spec.rb
This commit will add strict frontend and backend validation for tags
disallowing accented characters.
Closes #8884
Before:
https://d.pr/v/1xSmcP
After:
*Note: HTML5 validation won't let you type accented characters, but you can paste them*
> Stop allowing accented characters in tags

- app/javascript/article-form/components/ArticleCoverImage.jsx
- babel.config.js
Adds support for [terse fragment syntax support](https://babeljs.io/docs/en/next/babel-plugin-transform-react-jsx.html#pragmafrag) in Preact.
New to fragments? The Preact docs [have you covered](https://preactjs.com/guide/v10/components/#fragments).
https://github.com/thepracticaldev/dev.to/pull/9041#discussion_r448047306
N/A. As long as webpack bundles without erroring out, this Babel configuration addition is good.
> Added pragmaFrag so terse Fragment syntax, `<></>`, can be used in Preact

- app/javascript/modCenter/singleArticle/util.js
In the [Tag Moderators](https://dev.to/connect/tag-moderators) channel, user @darksmile92 left a comment (time: June 29, 2:33 AM) about the article dates not appearing correctly in their ModCenter. Reading further, it appears it was a misunderstanding on their part; however, I went ahead and ensured that the ModCenter's `formatDate` utility function properly accounted for the user's locale.
How Article Date appears for the `en-GB` (Great Britain) locale:
How Article Date appears for the `th-TH` (Thailand) locale:
> [ModCenter] Make formatDate function more robust for intl date-time formats

- app/assets/javascripts/initializers/initializeCommentDropdown.js
- app/assets/javascripts/initializers/initializeUserProfilePage.js
- app/views/comments/_comment_proper.html.erb
- app/views/users/show.html.erb
Every comment has a "report abuse" link, which Google sees as useless and a waste of crawler resources since this isn't a link to new "content".
So this PR moves that functionality such that the link does not exist until the user clicks on the dropdown menu.
In this PR, I also fixed some styling for the "hide" button, which is currently not correct.
> Remove report-abuse link from base HTML document into JavaScript

- app/views/dashboards/show.html.erb
In `app/views/dashboards/show.html.erb` we have an `if` that removes some UI elements (post sort order and more) if the user has no posts. Alas the removed elements also include the org switcher, so org admins who don't have posts of their own won't be able to switch. I moved the `if` around as PoC, but has issues too:
1. There's now no margin between the content and the footer when the user has no posts.
2. We're displaying the sort order dropdown even if there are no articles.
I'll leave it up to @ludwiczakpawel what to do with this, i.e. add some styling here or close out this PR and open a better one, as I'm about to go offline.
Closes #9066 
> Show org dropdown for postless users

- app/models/site_config.rb
As discussed in PR #8435, we're going to add this config variable first so @thepracticaldev/sre can set a default before the other PR gets merged.
n/a
> Add secondary_logo_url to SiteConfig

- app/assets/javascripts/base.js.erb
We're getting a bunch of ResizeObserver errors but it is in no way related to our app. I already ignored an error on honeybadger itself, but this will block all future variations of ResizeObserver error.
https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
n/a
Monitor Honeybadger
> Update Honeybadger to ignore ResizeObserver

- .github/workflows/rebase.yml
I think that as it is currently written, @benhalpern or other org owners couldn't actually kick off the automatic rebase workflow added in #9018. This should fix that issue!
Additionally, I changed the logic for determining if the comment was on a pull request, this method relies on the URL, but I believe it's more explicit and more readable than the previous method.
It also adds an explanatory comment to the yaml file, documenting that one's organization membership must be public for the workflow to trigger.
> Allow organization owners to use the Automatic Rebase workflow

- app/services/search/query_builders/feed_content.rb
- spec/services/broadcasts/welcome_notification/generator_spec.rb
- spec/services/search/feed_content_spec.rb
- spec/system/search/display_comments_search_spec.rb
In order to get highlighting from Elasticsearch to work with dark mode we need to switch from using `<em>` to highlight matches to `<mark>`. Luckily Elasticsearch has [a setting for this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#highlighting-settings)
I also snuck in a Broadcast spec fix that was popping up. cc @vaidehijoshi 
```
1) Broadcasts::WelcomeNotification::Generator requires a valid user id
Failure/Error: expect { described_class.call(1) }.to raise_error(ActiveRecord::RecordNotFound)
expected ActiveRecord::RecordNotFound but nothing was raised
```
Run a search and verify that the highlighted works are using mark instead of em
> Change Highlight Tags to mark instead of em

- app/controllers/comments_controller.rb
- spec/requests/comments_spec.rb
Hide notification when comment is hidden
closes https://github.com/thepracticaldev/dev.to/issues/8788
I could not find test for this hide action or even the controller itself so I might need little help on that.
> Hide notification when comment is hidden

- package.json
We've reached the state in the frontend codebase where we no longer have any lint errors. To keep the code maintainable, builds will fail now if a lint error is discovered in frontend code. This was discussed briefly on our internal Slack and there appeared to be no pushback on this.
#3777, #2470
N/A
> Now frontend code is linted before running tests

- app/views/dashboards/_actions.html.erb
- app/views/dashboards/_actions_mobile.html.erb
- config/routes.rb
- spec/requests/dashboard_spec.rb
The "pro analytics for org" link should only appear if the user has the pro role.
Closes https://github.com/thepracticaldev/dev.to/issues/9106
1. create an org
1. add and remove the `:pro` role to see the link appearing or disappearing
> Fix pro link for organization users

- app/assets/stylesheets/settings.scss
Delete `box-shadow` to `.github-repos` class. Why? Could be less visible boxes to [settings](https://dev.to/settings/integrations). Two boxes for GitHub integration is too much.
| :no_good: | :+1: |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/14293805/86523866-2933d280-be73-11ea-8ff5-83363bc0a508.png)|![image](https://user-images.githubusercontent.com/14293805/86523874-3f419300-be73-11ea-93c7-f97fdd3cbb58.png)|
> Delete box-shadow to .github-repos class

- app/liquid_tags/user_subscription_tag.rb
- app/views/articles/show.html.erb
- app/views/liquids/_user_subscription.html.erb
- spec/liquid_tags/user_subscription_tag_spec.rb
This PR cleans up the UserSubscription liquid tag now that we have designs/markup completed. The updates include:
- Making the availability of the subscriber's email completely conditional now that we've postponed that functionality.
- Make the JS null safe.
- Specs 🎉 . Given the way we handle JS for liquid tags with "raw strings", I chose to use Capybara to test this tag.
Closes #9023 
**Open up your browser console and navigate around (i.e. click articles that don't have this liquid tag) and make sure you don't see any JS errors related to the liquid tag.** You'll likely see a few errors related to 3rd party services like Pusher or Cloudinary, but you shouldn't see any from this tag, especially about `null` references.
**Steps**
1. Make sure you're signed in locally as an admin user.
2. …
> UserSubscription liquid tag update & re-enable JS

- app/views/articles/show.html.erb
This fragment cache was causing a bug because the `published` is included and it's different on an article-by-article basis. But then I saw that this cache was not blocking any new queries or intense computation, so I figured it was best to do away with the cache for one less Redis query anyway.
> Remove unnecessary fragment cache

- app/workers/users/follow_worker.rb
We are still getting duplicate follow attempts and it looks like its bc we are kicking off multiple workers at once. This will prevent that from happening so at least part of the problem will be fixed, I am not sure if it will fix all of it. 
Fixes Sidekiq Error:
```
ActiveRecord::RecordInvalid: Validation failed: Followable has already been taken
```
Make sure you can still follow someone
> Bug Fix: Prevent Duplicate Follow Attempts by Preventing Multiple Workers

- config/environments/production.rb
[Rails 6 offers the option of filtering data from logs](https://blog.saeloun.com/2019/12/03/rails-6-adds-activesupport-parameter-filter.html). I think using this we could quickly get logs into Datadog to allow for a more full-featured debugging experience. This can tie us over until we have a full logging solution using Fluentd and Elasticsearch. 
To get logs into Datadog all we have to do is [update our Heroku setup to drain logs to Datadog](https://docs.datadoghq.com/logs/guide/collect-heroku-logs/) and then we should be able to remove Timber. The advantage here is that we can remove the Timber specific code yet all Datadog is doing is tailing the application logs so we dont have to add additional special code to the app to get the logs we want. …
> Feature: Filter Sensitive Data From Production Logs

- config/initializers/honeybadger.rb
When we start running and hosting multiple Forems ourselves we are going to want their errors in a single location for debugging. This will help us split up Forems we host by APP_DOMAIN in Honeybadger. I was originally going to go with community name but since that could contain special characters and spaces I thought APP_DOMAIN was safer and would make it easy to figure out where you need to go if you are looking at a Honeybadger
NOTE: With this change, all of our errors that we have seen in the past will get re-reported since Honeybadger will detect them for a new environment. This will mean a little cleanup on my end initially but after a couple of weeks everything should go back to normal error rates. Could also be a chance to clean up some things we have been ignoring. …
> Feature: Label Honeybadger Env with Community Name

- app/liquid_tags/user_subscription_tag.rb
- spec/liquid_tags/user_subscription_tag_spec.rb
When I re-did the JS in #9082 I accidentally messed up the sign in flow. This PR fixes that bug and adds a spec to check for this case.
1. Make sure you're signed in locally as an admin user.
2. Write a post and include the liquid tag `{% user_subscription Some sweet CTA text %}`.
3. Publish your Article.
4. Sign out.
5. View your Article.
6. Click sign in on the liquid tag - you should be directed to sign in 🎉 .
#9082
> Fix sign in flow for user subscription liquid tag

- app/liquid_tags/user_subscription_tag.rb
@vaidehijoshi noticed an error in her browser console from some JS trying to hit the `/user_subscriptions/subscribed` endpoint while viewing a draft Article. I was unable to reproduce the error in a draft article or a published article, including or excluding the liquid tag.
Either way, it's probably better to not run the JS at all if the liquid tag is not on the page (this PR adds this check). I suspect it was a bad request because some DOM elements/data were missing given the article was a draft and/or didn't have the liquid tag.
n/a
1. Write a draft article without the user subscription liquid tag - check the browser console for failed requests to `/user_subscriptions/subscribed`.
2. Publish the article, view the article - check the browser console for failed requests to …
> Only run UserSubscription JS on appropriate Articles

- config/environments/production.rb
- config/initializers/sprockets_uglifier_with_source_maps_compressor.rb
This PR enables source map for our `app/asset/javascripts` on production. While Sprocket indicate that it is possible to enable source map but there's no documentation anywhere on it. I decided to go with modified UglifierCompressor because it doesn't require `assets.debug = true` and still allow us to use Uglifier as our compressor.
https://blog.experteer.engineering/generating-sourcemaps-with-sprockets-3-and-uglify.html
1. Place `config.assets.js_compressor = :uglify_with_source_maps` in `development.rb`
2. run `bin/rails assets:clobber`
3. run `bin/rails assets:precompile`
4. Start up the server and navigate to homepage.
5. Open up browser console and you should see source map being detected
none
> Use custom UglifierCompressor to enable source-maps

- app/controllers/dashboards_controller.rb
- app/models/user_subscription.rb
- app/policies/article_policy.rb
- app/views/dashboards/_dashboard_article_row.html.erb
- app/views/dashboards/subscriptions.html.erb
- config/routes.rb
- db/migrate/20200706184804_add_user_subscriptions_count_to_articles.rb
- db/schema.rb
- spec/models/shared_examples/user_subscription_sourceable_spec.rb
- spec/requests/dashboard_spec.rb
This PR add subscriptions to the dashboard. Big shoutout to @ludwiczakpawel from #9052 💯 .
**I'll copy and paste this description on each PR.**
We are building a liquid tag where permitted authors can embed a button that users/readers can click to share the email address associated with their DEV account with the author.
_We are restricting this liquid tag only for use in `Articles` (not `Comments` or `Pages`) and for use only by approved organizations for CodeLand (using a new role)._
Closes #8169
1. Make sure you're signed in locally as an admin user.
2. Write a post and include the liquid tag {% user_subscription Some sweet CTA text %}.
3. Preview and publish your Article.
4. View your Article.
5. Subscribe to yourself (allowing this behavior is intentional).
6. Go to your dashboard. …
> Add subscriptions to the dashboard

- app/views/articles/_conduct_and_abuse_actions.html.erb
This PR removes the `?url=` from the `report-abuse` button. This is fine because the report abuse page actually prefills the field based on the referring URL anyway.
Several reasons for this change:
- We already have this functionality in the "three dots" menu on article pages, so this brings parity.
- Currently the `request.url` includes `?i=i` if the page is loaded by service workers (under the hood) so this is a small issue)
- This removes a huge longtail of pages we link to which don't provide SEO value. One less type of page the bots feel they need to crawl every time.
> Remove unnecessary ?url= param from report-abuse

- app/controllers/omniauth_callbacks_controller.rb
- spec/system/authentication/user_logs_in_with_github_spec.rb
- spec/system/authentication/user_logs_in_with_twitter_spec.rb
In an effort to remove PII information from our logs so that we can allow the entire core team to access that data for debugging purposes I have moved these error logs to Honeybadger.
https://github.com/thepracticaldev/dev.to/projects/9#card-33250889
> Refactor: Remove Omniauth Error Logs, Send to Honeybadger

- app/controllers/ga_events_controller.rb
- app/controllers/stripe_active_cards_controller.rb
- app/controllers/video_states_controller.rb
1) Remove logs from Video States Controller and de-dup the JSON parsing. If we receive an error send it to Honeybadger
2) Remove logging from Stripe Creation controller. We are already sending error info to Datadog so there is no need for it in our logs. As for successes, we will have a new card in the database so there is not really a reason to log that either. 
3) Remove unnecessary logging from GA events controller. 
https://github.com/thepracticaldev/dev.to/projects/9#card-41511704
> Refactor: Remove Unnecessary logging from Video States, Stripe, and GA Events

- app/controllers/articles_controller.rb
- app/liquid_tags/user_subscription_tag.rb
- app/models/liquid_tags/user_subscription_tag.rb
- app/models/role.rb
- app/views/pages/_editor_liquid_help.html.erb
- docs/frontend/liquid-tags.md
- spec/factories/articles.rb
- spec/factories/users.rb
- spec/liquid_tags/user_subscription_tag_spec.rb
- spec/models/role_spec.rb
- spec/policies/liquid_tag_policy_spec.rb
- spec/requests/dashboard_spec.rb
This PR adds the new role that's going to be used for the liquid tag and adds some documentation to liquid tags for using it.
A few things to note:
- The way we currently handle documenting liquid tags needs a re-factor, but that's outside the scope of this PR. Currently, we render directions for liquid tags in 3 different pages ([`/app/views/_editor_liquid_help.html.erb`](https://github.com/thepracticaldev/dev.to/blob/master/app/views/pages/_editor_liquid_help.html.erb), [`/app/views/pages/markdown_basics.html.erb`](https://github.com/thepracticaldev/dev.to/blob/master/app/views/pages/markdown_basics.html.erb), [`/app/views/pages/_editor_guide_text.html.erb`](https://github.com/thepracticaldev/dev.to/blob/master/app/views/pages/markdown_basics.html.erb)). Ideally, it would be one …
> Add role and docs for user subscription liquid tag

- app/controllers/comments_controller.rb
- app/controllers/messages_controller.rb
- app/helpers/messages_helper.rb
1) Send pusher errors to Honeybadger and don't just log them
2) Remove logging for comment markdown errors. These will be reported to the user, there is no need for us to also put them in our logs. 
https://github.com/thepracticaldev/dev.to/projects/9#card-41511704
Once this cleanup is done hopefully everyone can view our logs!
> Refactor: Report Pusher Errors to Honeybadger, Remove Comment Error Logging

- app/controllers/users_controller.rb
- app/models/follow.rb
- spec/models/follow_spec.rb
We have been seeing a lot of ActiveRecord validation errors when a record tries to follow a record they are already following. We attempted to prevent this using `create_or_find_by!`, however we were still seeing the error. The reason, and you all can thank @rhymes for figuring this out is
> create_or_find_by! rescues ActiveRecord::RecordNotUnique which is the exception the database sends up through its constraints, but we have “mounted” on top of it a second layer which is Rails’s, through ActiveRecord::RecordInvalid which is not the exception create_or_find_by! handles. 
```ruby
def create_or_find_by!(attributes, &block)
transaction(requires_new: true) { create!(attributes, &block) }
rescue ActiveRecord::RecordNotUnique
find_by!(attributes)
end
```
> Bug Fix: Remove Rails Validation for Follow Uniqueness, Guard against dup Follow Jobs

- app/services/moderator/sink_articles.rb
- spec/services/moderator/sink_articles_spec.rb
Fixes an issue where a single user's articles are flooding the feed.
> Hotfix: Disable Article Sinking

- .rubocop.yml
- .rubocop_todo.yml
- app/labor/markdown_fixer.rb
- spec/lib/data_update_scripts/re_index_feed_content_and_users_to_elasticsearch_spec.rb
- spec/requests/dashboard_spec.rb
- spec/services/broadcasts/welcome_notification/generator_spec.rb
Instead of ignoring `RSpec/MultipleExpectations` which by default is set to 1 `expect()` per test case (with 930 violations) I set it to a more than reasonable 8 (mostly by process of elimination :D) and refactored a couple of tests that had 12 `expect()`.
In general I think we should work towards getting rid of the `.rubocop_todo.yml` over inline `rubocop:disable` statements as they are visible during the process of creating code. The todo file is likely to be overlooked most of the times.
> Fix Style/SingleLineBlockParams, RSpec/MultipleExpectations and remaining Layout/LineLength

- app/services/notifications/welcome_notification/send.rb
- app/workers/metrics/record_daily_notifications_worker.rb
- app/workers/metrics/record_daily_usage_worker.rb
- lib/tasks/metrics.rake
- spec/factories/ahoy.rb
- spec/factories/ahoy_message.rb
- spec/services/notifications/welcome_notification/send_spec.rb
- spec/workers/metrics/record_daily_notifications_worker_spec.rb
While we currently have tracking around welcome notifications, our way of looking up data isn't the greatest (it's just a basic [blazer query](https://dev.to/internal/blazer/queries/99-daily-welcome-notification-events-graph)). It would be great to have these metrics reported to DataDog since we have them now (!!), so this PR does just that.
Specifically, it:
This was one of my cool-down [pebble jar tasks](https://github.com/thepracticaldev/dev.to/projects/7#card-40958551)! 🌱 
I'd say that the tests are the best way to measure this (I've added tests for both forms of logging), but if you want to try to stub out `DataDog` locally and see if this works, you could!
None that I can think of, aside from checking in on DataDog to make sure this is actually getting reported the way we expect :)
> Add metrics around welcome notifications + their click events

- .rubocop.yml
- .rubocop_todo.yml
- app/controllers/articles_controller.rb
- app/controllers/notifications_controller.rb
- app/services/articles/builder.rb
- spec/services/articles/builder_spec.rb
This PR:
- fixes `Metrics/CyclomaticComplexity`
- refactors a bit `Articles::Builder` to use `.call` and to fix `Metrics/CyclomaticComplexity`
- disables `Metrics/AbcSize` as we currently have 278 violations and I believe there's no point into keeping this particular violation activated or to find the threshold to hide some of them "under the rug"
> Rubocop: fix Metrics/CyclomaticComplexity and disable Metrics/AbcSize

- app/assets/stylesheets/ltags/GithubTag.scss
- app/views/liquids/_github_issue.html.erb
I believe we made a style adjustment to how github issues are displayed but this element was still lingering. It only causes problems within comments so I think we just missed it... But it's easy to 🔪
Note the white arrow in the way of the profile image here...
> Remove arrow-left-... from github issue embed

- config/environments/production.rb
**I am close to attempting to switch us over to Datadog for logging.** In order to ensure that we can do it smoothly I rewrote the production logging set up so we only configure it once for `RAILS_LOG_TO_STDOUT` and once if we are using Timber, `SEND_LOGS_TO_TIMBER`.
Next Steps
1) Set `RAILS_LOG_TO_STDOUT` to true 
2) [Add a log drain to Heroku to send logs to Datadog](https://docs.datadoghq.com/logs/guide/collect-heroku-logs/). NOTE: This feature is still in beta so if we do run into problems then I will go the fallback route.
- Fallback Plan: [Follow these directions to use the buildpack to send logs to Datadog](https://www.ironin.it/blog/sending-logs-from-your-heroku-app-to-datadog.html)
https://github.com/thepracticaldev/dev.to/projects/9#card-33250889
> Refactor:Use if/else When Selecting Production Log Strategy

- config/environments/production.rb
Apparently we need the STDOUT logging part bc, [surprise `RAILS_LOG_TO_STDOUT` is present on Heroku.](https://blog.heroku.com/container_ready_rails_5)
> This value can be set by the container or the platform on which your Rails app runs. In our case, the Ruby buildpack detects your Rails version, and if it's Rails 5 or greater will set the RAILS_LOG_TO_STDOUT environment variable.
```
irb(main):002:0> ENV["RAILS_LOG_TO_STDOUT"].present?
=> true
```
> Bug Fix: Setup STDOUT Logger bc we need it

- app/services/rss_reader/assembler.rb
This change interaction with RSS's `@item` as hash instead of method call so it's nullable.
Resolves https://app.honeybadger.io/fault/66984/90d3be76e672b09bcf0fa82d0f7f1be7
warning: this will create a lot of local articles.
1. spin up rails console.
2. Add the feed to your personal account. ie `me.update(feed_url: "http://www.blameless.com/blog/rss.xml")`
3. Run `RssReader.get_all_articles`
4. You should be able to fetch all feed successfully without error.
mark honeybadger item as resolved
> Update RssReader::Assembler#get_content hash syntax

- config/environments/production.rb
@maestromac was helping me scan logs for PII data and found that we expose emails when we log the entire email we send from the app. This occurs bc our logging level in Production is set to debug. Debug is a pretty aggressive logging level to have turned on in Production so I scaled it back to info which should be more than enough. 
If in the future we hit some really devious bugs, we can always flip it on but info should be plenty.
> Optimization:Change Log Level in Prod to Info

- .rubocop_todo.yml
- app/models/article.rb
- app/models/organization.rb
- app/services/notifications/reactions/send.rb
- app/views/stories/feeds/show.json.jbuilder
- spec/models/github_repo_spec.rb
- spec/requests/github_repos_spec.rb
I replaced `OpenStruct` with `Struct` wherever possible (the [latter is faster](http://www.chrisrolle.com/en/blog/struct-vs-openstruct-benchmark)) and disabled it locally where it made sense.
I think we should eventually stop storing serialized objects in the DB and use standard formats like JSON but for now I just replaced a serialized open struct vs a struct. No need to backfill those, they don't have to interact and they behave the same way at runtime so articles will "backfill" themselves on save.
> Rubocop: fix Performance/OpenStruct

- .rubocop_todo.yml
- app/helpers/application_helper.rb
- app/helpers/comments_helper.rb
- app/liquid_tags/github_tag/github_issue_tag.rb
- app/liquid_tags/liquid_tag_base.rb
- app/models/comment.rb
- app/models/display_ad.rb
- app/models/message.rb
- addressed `Rails/OutputSafety` by mostly disabling them locally
- used [safe_join](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsoutputsafety) in one case
- removed a legacy method that wasn't called anywhere
> Rubocop: Address Rails/OutputSafety violations

- .travis.yml
- README.md
- container-compose.yml
- docker-compose.yml
- docs/installation/linux.md
- docs/installation/mac.md
- docs/installation/windows.md
We recently discovered that our migrations are not compatible with Postgres versions <11. Rather than continuing to try and support these versions, we have decided to update our docs to require Postgres version 11 or higher to run DEV.
This PR...
1) Updates all container files to use Postgres 11 images
2) Updates the Docs to say we require Postgres 11
3) Runs migrations in a single Travis job (I confirmed if you drop the Travis version to 10 and the StrongMigrations supported version to 10 you will end up with the migration error that @jdoss saw)
4) Bumps Travis to 10....Wait, what?! Travis does not play nice with Postgres-11. If you install it through [their services](https://travis-ci.community/t/postgresql-11-2-cannot-connect/2680) it will fire up on port 5433 bc Postgres 9 which is …
> Update Docs, Travis,  and Containers to Use Postgres 11

- docs/api_v0.yml
In https://github.com/thepracticaldev/dev.to/pull/8929 the endpoint https://dev.to/api/articles/devteam/for-empowering-community-2k6h was added, this adds the documentation for it.
I think we should do a changelog post as well.
`yarn api-docs:serve` and browse the local API
> API: add docs for get published article by path

- .rubocop_todo.yml
- app/models/article.rb
- app/models/organization.rb
- app/services/notifications/reactions/send.rb
- app/views/stories/feeds/show.json.jbuilder
- spec/models/github_repo_spec.rb
- spec/requests/github_repos_spec.rb
This reverts commit 101cca4a683dba740b094bc93a8281b0815fa174.
Unfortunately I still don't know what's broken but I verified that by reverting this things profile images locally and hopefully in production will work again.
Closes https://github.com/thepracticaldev/dev.to/issues/9290
Pull down the PR, fire it up, verify that as a logged in user, the profile images work
> Revert "Rubocop: fix Performance/OpenStruct (#9241)"

- app/models/announcement.rb
- app/models/welcome_notification.rb
- db/migrate/20200707170245_add_polymorphism_to_broadcasts.rb
- db/migrate/20200707173316_create_announcements.rb
- db/migrate/20200707173524_create_welcome_notifications.rb
- db/migrate/20200710174257_add_index_to_broadcasts.rb
- db/schema.rb
- lib/data_update_scripts/20200708163323_backfill_broadcastable_type_for_broadcasts.rb
- lib/data_update_scripts/20200708163323_backfill_columns_for_broadcasts.rb
This PR is part one of a two-part refactor that creates a polymorphic association between Broadcasts, Announcements, and Welcome Notifications. This PR adds polymorphism to the Broadcasts table and a `data_update` script to properly backfill the newly added `broadcastable_type` column, as shown below. Additionally, this PR adds an Announcement and Welcome Notification table to the database with `created_at` and `updated_at` timestamps on both tables and an additional `banner_style` column on the Announcements table. It also stubs out the Announcement and Welcome Notification models in preparation for the next PR, Part 2 of the move to polymorphic Broadcasts.
Related to #7169 and #8861 
To QA these changes, you can manually run the `data_update` script (as shown below) and make sure that …
> Add Polymorphism to Broadcasts (Part 1)

- lib/data_update_scripts/20200708163323_backfill_broadcastable_for_broadcasts.rb
- lib/data_update_scripts/20200708163323_backfill_broadcastable_type_for_broadcasts.rb
This PR fixes a typo in `backfill_broadcastable_type_for_broadcasts.rb` and uses `.find_each` in place of `.each` when looping through the Broadcasts in the `data_update` script per @rhymes' suggestion in this PR: https://github.com/thepracticaldev/dev.to/pull/9231
Fixes the typo in this PR: https://github.com/thepracticaldev/dev.to/pull/9231
To QA these changes, you can manually run the `data_update` script (as shown below) and make sure that the build passes and that these changes do not break anything else.
To manually run the `data_update` script, do the following:
- Create a Broadcast without a `broadcastable_type`:
```
broadcast = Broadcast.create(title: "Hello, world!", processed_html: "Hello, world!", type_of: "Welcome", active: false, broadcastable_type: nil)
```
```
=> …
```
> Hotfix: Fix Typo in backfill_broadcastable_type_for_broadcasts

- .gitpod.dockerfile
After installing a new node version with nvm it has to be explicitly chosen to use. This adds the nvm use command to fix the `bin/setup` script
#8849 
View the [GitPod workflow for this PR](https://gitpod.io/#https://github.com/thepracticaldev/dev.to/pull/9271) and verify an error is no longer thrown on [yarn install](https://user-images.githubusercontent.com/22113778/85383294-6b990d80-b55d-11ea-92ff-a74d807c917b.png)
> GitPod: Use node version 12.16.3

- app/views/service_worker/index.js.erb
Safari has had issues with the service worker implementation and after some debugging found that when the cache is manually cleared a promise chain is broken because the `cachedResponsed` ([here](https://github.com/fdoxyz/dev.to/blob/master/app/views/service_worker/index.js.erb#L162)) returns `undefined`.
To solve this a default empty object `{}` is passed down when this happens, [as suggested here](https://github.com/thepracticaldev/dev.to/issues/5434#issuecomment-655181637). The intention was to edit as little as possible of the service worker code.
#5434 
This is not easy to debug, the steps I take are the following (Safari):
1. Open page (Safari requires HTTPS in order to enable service workers so I used [ngrok](https://ngrok.com/) for this)
1. Clear all local data for the site
1. …
> Service Worker default value to cached shell version

- app/javascript/profileDropdown/blockButton.js
As [this Honeybadger error](https://app.honeybadger.io/fault/67192/ed6f6b392b5bd791d6dc04732f125123) shows, we sometimes try to call `id` on `userData`, which can occasionally be `null`.
This particular error seems to really only happen to one user, who is on Firefox. I'm not sure why `userData` doesn't seem to exist for this user on this browser specifically (and that too from `initBlock.js`?), but it seems like we shouldn't be throwing a TypeError here if the `userData` object doesn't even exist. 🤷 
As I mentioned in https://github.com/thepracticaldev/dev.to/pull/9298, we probably need to investigate the non-existant user data set on the page, but for now, this should bring down some of the high error counts for _this_ error that we've …
> Fix TypeError: userData is null in blockButton.js

- app/assets/javascripts/initializers/initializeOnboardingTaskCard.js
As [this Honeybadger error](https://app.honeybadger.io/fault/67192/65045742fda3390a067960f53a894e87) shows, we sometimes try to call `created_at` on `userData`, which can occasionally be `null`. My guess is that this error happens sometimes when we call `initializeOnboardingTaskCard` but for some reason (?) the `userData()` isn't there.
This particular error started occurring about 5 days ago, and seems to only be occurring on Firefox.
I suspect that there are times when the `document.body.dataset` doesn't have the `user` within it (for some reason?), and so we are unable to `JSON.parse(user)`, and then this function causes the subsequent `TypeError`. 
Probably, we should have some kind of better, global catchall system for handling the …
> Fix TypeError: userData is null in initializeOnboardingTaskCard.js

- app/assets/javascripts/initializers/initializeArticleReactions.js
As [this Honeybadger error](https://app.honeybadger.io/fault/67192/6f9b4fdf475e2229c968fa26d785b90f) shows, we sometimes try to call `textContent` on an element that is `null`. My guess is that this error happens at some point when `initializeArticleReactions.js` is called, and when the DOM attempts to `getElementById("reaction-number-"+reactionName)`, but can't find that element on the page/`document` yet.
Since we can't continue with that function without the element existing, I'm adding as guard clause here, which should fix this particular error.
Should fix https://app.honeybadger.io/fault/67192/6f9b4fdf475e2229c968fa26d785b90f
Not a great way to test this other than seeing if the Honeybadger error re-occurs after this guard clause (it …
> Fix TypeError: null is not an object in initializeArticleReactions.js

- app/views/articles/_search.html.erb
As [this Honeybadger error](https://app.honeybadger.io/fault/67192/f79e24dfb4e4364da09dda6380e9d2ff) shows, we sometimes try to set `innerHTML` as a property on a "substories" element (`document.getElementById("substories")`), which can occasionally be `null`.
From what I can tell, we don't even want to _call_ on the `searchMain` function if we don't have a `substories` element loaded, since this will throw a TypeError. In the rest of the `searchMain` function, we have guard clauses to make sure that elements exist before we try to do anything to them:
```javascript
if (document.getElementById("query-wrapper")) {
search(query, filters, sortBy, sortDirection);
initializeFilters(query, filters);
initializeSortingTabs(query);
}
```
Given these …
> Fix TypeError: Cannot set property 'innerHTML' of null

- app/controllers/internal/configs_controller.rb
- app/models/site_config.rb
- app/views/articles/_sidebar.html.erb
- app/views/internal/configs/show.html.erb
- spec/requests/internal/configs_spec.rb
This makes the "headline" of the gold sponsor area configurable, in case a community wants to list things differently there, such as describing "partners" or "supporters".
> Make sidebar sponsor headline configurable

- app/services/users/profile_image_generator.rb
- spec/services/users/profile_image_generator_spec.rb
This is a quick and dirty way to create a profile image generator to help push `Sign in with Apple` over the line.
#7952 
The idea is that this helps us have default profile images on sign ups that don't come with avatars.
Usage...
In the GitHub auth we have this...
```ruby
remote_profile_image_url: info.image.to_s
```
So in Apple and elsewhere we can have this...
```ruby
remote_profile_image_url: Users::AvatarGenerator.call
```
And this will create a random profile image from Twemoji and colors from our pastel rainbow.
I don't know if this is the final solution, but I think it's a decent quick way to get this working. I chose Twemoji because it's liberally open source.
I'd love to replace this with something delightful and unique, but I think this is a good starter place for that in the …
> Create profile image generator

- app/models/site_config.rb
In our recent effort to generalize the `SiteConfig` we forgot to remove this comment. Removing it now since it's misleading.
n/a
n/a
> Remove outdated comment

- docs/frontend/webpacker.md
folder path typo `app/javascripts` -> `app/javascript`
Fixes #9328
made use of gitpods could not get the gitdocs to serve docs page.
gif link didn't work 🤦‍♂️ (it was a cat with a fidget spinner)
> Fixes javascript folder typo in webpacker documentation

- lib/tasks/app_initializer.rake
When we switched to using `db:prepare` for our pre-deploy tasks we broke refreshing Hypershield. The reason is because [hypershield hooks into the migrate rake task](https://github.com/ankane/hypershield/blob/master/lib/tasks/hypershield.rake#L19) to trigger the refresh. When using [`db:prepare`, migrate](https://github.com/rails/rails/blob/98754de1412870d7dae9eba1c7bac944b9b90093/activerecord/lib/active_record/railties/databases.rake#L306) is not triggered through rake but rather through the [ActiveRecord::Tasks::DatabaseTasks](https://github.com/rails/rails/blob/98754de1412870d7dae9eba1c7bac944b9b90093/activerecord/lib/active_record/tasks/database_tasks.rb#L224) class.
https://github.com/forem/forem/projects/9#card-41787287
> Bug Fix: Refresh Hypershield after db:prepare if Enabled

- app/lib/honeycomb/noise_cancelling_sampler.rb
- spec/lib/honeycomb/noise_cancelling_sampler_spec.rb
Not technically a refactor since it broke tests, but the functionality is the same.
Refactor `NoiseCancellingSampler`
- break up Redis and SQL commands lists and conditional block
- update conditional statements to use ActiveSupport `.in?` to be a bit more idiomatic Rails
- add default value for `rate` up front
- call `should_sample` at the end on everything to reduce number of conditional paths
- add some comments to explain reasoning for different sample rates
Update spec
- remove stub, so now we're calling `Honeycomb::DeterministicSampler.should_sample` every time
- break up return values into `is_sampled` (boolean) and `rate` (integer) for downsampled test cases
n/a
Should be able to just run the test suite. We can check in Honeycomb to make sure the sample rates are the same before …
> Update NoiseCancellingSampler to make it more self-documenting

- config/routes.rb
One last attempt to get the Flipper UI working before I just write me own (grr). _Something_ is happening in the bowels of the rack app served by Flipper UI and session, CSRF tokens, etc. Based on my reading of the source code (https://github.com/jnunemaker/flipper/blob/master/lib/flipper/ui.rb), Rack::Protect's code (https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection.rb), I believe this will turn off some CSRF protections just within the mounted Flipper UI.
(Logging was also removed as...it didn't log in production for some reason. Grr).
https://github.com/forem/forem/pull/9355
https://github.com/thepracticaldev/tech-private/issues/450
> Attempt to turn off Flipper UI CSRF protections

- app/javascript/packs/readingList.jsx
Should fix reading list rendering multiple times when navigating from home to reading-list pages.
I ran into issues trying to set up a development environment locally and via Gitpod (see #9195), so I wasn't able to test if this actually fixes this issue.
Note: The precommit hook reformatted the `followedTagNames` code; lmk if you want me to remove that.
fixes #9342
See bug reproduction steps in issue.
> Fix reading list rendering multiple times

- app/controllers/application_controller.rb
- app/controllers/internal/configs_controller.rb
- app/models/site_config.rb
- app/views/internal/configs/show.html.erb
- spec/requests/api/v0/users_spec.rb
- spec/requests/async_info_spec.rb
- spec/requests/ga_events_spec.rb
- spec/requests/internal/configs_spec.rb
- spec/requests/shells_spec.rb
- spec/requests/stories_index_spec.rb
This feature allows admins to create entirely private forems— where all requests are returned with the sign up page.
There's some more nuance to other stuff that should go along with this— like whether the footer should display a bunch of pages like `about` etc.
We also need to ensure edge caching is configured in such away to ensure true privacy. This will require some additional configuration alignment. It won't matter for DEV because we won't use this, but we need to ensure in a future PR that we wouldn't be leaking private info via any caches.
> Enable public or private forem config

- db/migrate/20200717220654_change_broadcast_and_github_issue_pks_to_bigint.rb
- db/schema.rb
Switching from Int to Bigint PKs(Primary Keys) for Broadcasts and GithubIssues. Both these tables are small and don't get a lot of writes so I think doing them in place is the way to go. 
Tables Sizes
```
irb(main):022:0> GithubIssue.count
=> 1010
irb(main):023:0> Broadcast.count
=> 11
```
Migration on my computer with 1000 GithubIssues
```
mollystruve$ migrate
== 20200717202342 ChangeBroadcastAndGithubIssuePksToBigint: migrating =========
-- change_column(:broadcasts, :id, :bigint)
-> 0.0624s
-- change_column(:github_issues, :id, :bigint)
-> 0.2294s
== 20200717202342 ChangeBroadcastAndGithubIssuePksToBigint: migrated (0.2920s)
```
> Optimization:Change Broadcast and GithubIssue PKs to Bigint

- docs/api_v0.yml
I have changed a little typo in API docs. 
```ssh
curl https://dev.to/bytesized/byte-sized-episode-2-the-creation-of-graph-theory-34g1
```
```ssh
curl https://dev.to/api/articles/bytesized/byte-sized-episode-2-the-creation-of-graph-theory-34g1
```
> Fixed a Typo at "A Published article by path"

- spec/system/comments/user_delete_a_comment_spec.rb
Same as #8388 we need to clear Elasticsearch data here to avoid trying to load missing user images
> With some logging I confirmed that those users had no images but we were still seeing user profile images on the page. Turns out those were coming from left over Elasticsearch data. The only reason it affects the js: true specs is bc the js runs on the page and loads elasticsearch data.
> Flaky Spec Fix:Clear Elasticsearch FeedContent to avoid trying to load missing data

- db/migrate/20200719205123_change_mentions_and_notes_pks_to_bigint.rb
- db/schema.rb
Production Data:
- Notes: 10k
- Mentions: 6.5k
With 10k notes and mentions in my local environment I ran this migration and it was super speedy so this is another I believe is plenty safe to do in place. 
```
== 20200719205123 ChangeMentionsAndNotesPksToBigint: migrating ================
-- change_column(:mentions, :id, :bigint)
-> 0.0262s
-- change_column(:notes, :id, :bigint)
-> 0.0171s
== 20200719205123 ChangeMentionsAndNotesPksToBigint: migrated (0.0439s) =======
```
> Optimization:Change Primary Keys on Mentions and Notes to Bigint

- app/labor/markdown_parser.rb
- spec/labor/markdown_parser_spec.rb
_Note: All credit for this PR goes to @protium-dev. I just took over the closed PR and incorporated the last few pieces of feedback._
This PR adds two regex to check for possible XSS attempts in Markdown content. They also prevent bypassing checks by using capital letters or blank spaces.
**Note:** as mentioned in the issue, this regex will check if `data:text/html` is followed by `,` or `;` and text. Example of a possible attack:
```
data:text/html;base64,PHNjcmlwdD5hbGVydCgndGVzdDMnKTwvc2NyaXB0Pg
```
Closes #7905
> Add regex to check for possible XSS attempts

- app/views/chat_channel_memberships/join_channel_invitation.html.erb
Changes the use of `_url` in favor of `_path` in Connect Invitation links flow.
Using `_url` worked well when testing locally but in production seems to be changing the protocol to `http` possibly introducing the bug seen in production.
Invitation links introduced in membership management component #8945
If looking into testing this locally:
1. Create channel (`/internal/chat_channels`)
1. Copy invite link from membership management component
1. Open the link using a different user
> Change from url to path in form

- app/liquid_tags/glitch_tag.rb
- app/services/broadcasts/welcome_notification/generator.rb
- app/services/credits/ledger.rb
- app/services/search/query_builders/chat_channel_membership.rb
- app/services/search/query_builders/feed_content.rb
- app/services/search/query_builders/listing.rb
- app/services/search/query_builders/query_base.rb
- app/services/search/query_builders/user.rb
- spec/requests/notifications_spec.rb
[Ruby 2.7 adds Enumerable#filter_map](https://blog.mavenhive.in/ruby-2-7-adds-enumerable-filter-map-d84aad03b6d4) which can replace `map { ... }.compact` in most of cases and it's a bit faster.
> Use Enumerable#filter_map in more places

- app/controllers/pusher_controller.rb
- app/javascript/chat/chat.jsx
- app/models/chat_channel.rb
We've been using Pusher's "presence" channels, which actually have a max occupancy. So in order to create bigger group channels, we need to move to "private", which is fine. As far as I know we aren't using any of the features of presence anyway. (I think we _may_ have in a prior implementation of some features.
Correct me if I'm wrong about this idea.
Here is the info about presence channels:
https://pusher.com/docs/channels/using_channels/presence-channels
> Presence channels have some limits associated with them: 100 members maximum, 1KB limit for user object, and maximum 128 characters for user id. If you use a numeric user id, remember that the maximum size integer that is representable in JavaScript is 2^53.
And FWIW, here is an article about how one might implement some of the …
> Change from presence to private pusher channels

- app/assets/javascripts/initializers/initializeBroadcast.js
- app/assets/stylesheets/components/banners.scss
- app/assets/stylesheets/scaffolds.scss
Update `broadcast` & `crayons-banner` to:
- use `crayons-btn` styles for close button
- support `a` styles
This task will require follow-up considerations & support for the close buttons' colors across the different banner colors.
> Update broadcast styling

- config/fastly/snippets/safe_params_list.vcl
I just happened to be thinking to myself, "I haven't touched Fastly code in a while"...and it dawned on me that I didn't update the safe params list for [user subscriptions on the dashboard](https://github.com/forem/forem/blob/949b092dbd614ffa6a68026b72c4e89fbe1e2190/app/controllers/dashboards_controller.rb#L82-L88). This PR adds `source_id` and `source_type` to the safe params list. Thankfully, we caught this before it even came up 😉 .
#9161 
N/A, this is a production only feature.
> Add source_type and source_id to safe params list

- app/controllers/stripe_active_cards_controller.rb
- docs/backend/audit-log.md
- spec/requests/stripe_active_cards_spec.rb
During a [discussion on a previous PR](https://github.com/forem/forem/pull/7924#pullrequestreview-414059201) we talked about maybe adding more logging around important user events, like adding or removing a credit card:
In a Slack discussion with @rhymes we agreed to reuse the existing `AuditLog` model for this. 
This PR introduces basic logging for credit card CRUD events. There's no interface for looking at them yet.
The created log entries currently look like this:
```ruby
#<AuditLog:0x00000001193ce348> {
category: "user.creditcard.modification",
created_at: Tue, 21 Jul 2020 06:35:13 +03 +03:00,
data: {
"action" => "create",
"controller" => "stripe_active_cards",
"user_action" => "add"
},
id: 4,
roles: [],
slug: "creditcard_add",
updated_at: Tue, 21 Jul 2020 06:35:13 +03 +03:00, …
```
> Add audit logs for credit card actions

- docs/api_v0.yml
Added 'nullable' to fields which may return a null value in API documentation
issue #9061
Currently in the documentation it is listed data to be returned in the response, but does not offer the possibility that it can return null as a value.
For instance, with respect to articles:
Changed so any data which may have a null value is documented accordingly
With users, a user may or may not have a website url, github, or twitter linked to their profile. In these cases where they do not, the API will return null for those fields. The documentation is updated to account for this
> API: add nullable to nullable fields in documentation

- app/assets/javascripts/initializers/initializeReadingListIcons.js
This PR fixes a bug where the badge of the reading list navigation item on the left sidebar won't disappear when the list is left empty.
Fixes #8900.
On the homepage, with an empty reading list:
1. Click on the "Save" button of an article and notice how the badge appears
2. Click on the "Unsave" button of that same article and notice how the badge disappears
No.
> Don't show badge when reading list is left empty

- app/liquid_tags/slideshare_tag.rb
- spec/liquid_tags/slideshare_tag_spec.rb
Slideshare codes can be 13 characters long as well as 14. This updates the regex length validation to 12-14 characters long.
> Update slideshare embed code length limit

- db/migrate/20200721213341_change_podcast_p_ksto_bigint.rb
- db/schema.rb
There are 14k Podcast Episodes in production and 200 Podcasts so updating these inline should be safe seeing as the 10k row ones (#9393 #9372) we have been doing have been finishing very fast and not even close to causing any issues.
> Optimization:Change Podcast and Episode PKs to Bigints

- .rubocop.yml
- app/controllers/concerns/valid_request.rb
- app/helpers/application_helper.rb
- app/lib/redcarpet/render/html_rouge.rb
- app/liquid_tags/codepen_tag.rb
- app/liquid_tags/codesandbox_tag.rb
- app/liquid_tags/gist_tag.rb
- app/liquid_tags/git_pitch_tag.rb
- app/liquid_tags/github_tag/github_issue_tag.rb
- app/liquid_tags/github_tag/github_readme_tag.rb
- app/liquid_tags/js_fiddle_tag.rb
- app/liquid_tags/jsitor_tag.rb
- app/liquid_tags/next_tech_tag.rb
- app/liquid_tags/parler_tag.rb
- app/liquid_tags/reddit_tag.rb
- app/liquid_tags/replit_tag.rb
- app/liquid_tags/soundcloud_tag.rb
- app/models/user.rb
- app/services/rss_reader/assembler.rb
- config/database.yml
- config/initializers/timber.rb
- spec/requests/videos_spec.rb
- spec/support/initializers/vcr.rb
- spec/system/user_uses_the_editor_spec.rb
`Style/RegexpLiteral` is activated by default on Rubocop, we should activate it as well:
https://github.com/rubocop-hq/rubocop/blob/343f62e4555be0470326f47af219689e21c61a37/config/default.yml#L3780-L3783
```yaml
Style/RegexpLiteral:
Description: 'Use / or %r around regular expressions.'
StyleGuide: '#percent-r'
Enabled: true
```
The raw syntax is also very handy because, in addition on not requiring escapes, it allows regexp to be split in multiple lines and inline comments can be used.
For example:
```ruby
regexp = %r{
start         # some text
\s            # white space char
(group)       # first group
(?:alt1|alt2) # some alternation
end
}x
```
> Rubocop: re-activate Style/RegexpLiteral and fix violations

- app/javascript/articles/Feed.jsx
- app/javascript/packs/homePage.jsx
I think there's a better "preacty" way of dealing with this, but this is something we've had on the site for a while.
I don't think people notice it unless they're sensitive but I think it hurts UX and also leads to an extra call to an endpoint and lower performance overall.
Described here, but confirmed locally that we are, in fact, running some code multiple times in a way that is inappropriate.
#9079
This is a pretty straightforward fix in that it is self evident not to proceed with the following step if the element is already on the page.
Fixes #9079
> Fix double render of home feed

- app/controllers/internal/chat_channels_controller.rb
- spec/requests/internal/chat_channel_spec.rb
This fixes a bug where users were being added to chat channels as mods of that channel, when they should just be regular members.
> Default to adding users as members to a chat channel and not mods

- app/controllers/users_controller.rb
- app/models/user.rb
- spec/models/user_spec.rb
- spec/requests/user/user_settings_spec.rb
Validate that a user's password is between 8 and 100 characters long. While setting this up I noticed that submitting an invalid input on the account page of settings would cause a 500 since `@tab` is not set on that page. Rather than try to dig into why I just put in a little workaround.
> Bug Fix:Validate User Password Length is Between 8-100 characters

- app/controllers/chat_channels_controller.rb
- app/javascript/chat/chat.jsx
- app/models/role.rb
- app/policies/chat_channel_policy.rb
- spec/models/role_spec.rb
- spec/policies/chat_channel_policy_spec.rb
- spec/requests/chat_channels_spec.rb
This is the WIP for getting `/ban` working again in Connect. Ideally, we get it with these specifications:
- remove the user from the channel
- ban them, and therefore preventing them from messaging in other channels
- delete all their messages in that specific channel — delete because Pusher already is configured to handle the messages
- can only `/ban andy` if `andy` is in that channel
- will be limited to a new role `codeland-admin`
The current version in this PR makes `/ban` somewhat
The video shows the sad path (user not found) and then the happy path (banning a user):
https://share.getcloudapp.com/6qu26APe
This PR assumes you have Pusher setup locally. Unfortunately it's been too long since I last set it up 😬 
```ruby
cc = ChatChannel.create(channel_name: 'group test', status: …
```
> Update /ban for Connect

- app/models/user.rb
- app/services/authentication/authenticator.rb
- spec/requests/user/user_settings_spec.rb
We recently added passwords to our `User` model. However, we never validated the password confirmation when updating the password, so users could accidentally set them to unexpected values:
```ruby
user.reset_password("newpassword", "nupassword")
#=> true
```
This PR fixes this by adding a validation:
```ruby
user.reset_password("newpassword", "nupassword")
#=> false
user.errors_as_sentence
#=> "Password doesn't match password confirmation"
```
Note: I originally tried to use `Devise::Models::Validatable`, however, this expects the password to be non-blank, despite the following:
```ruby
validates :password, length: { in: 8..100 }, allow_nil: true
```
I thought we can fix this by overriding `password_required?`, but as [the documentation …
> Validate password confirmation when updating password

- .github/CODEOWNERS
- app/assets/stylesheets/notifications-welcome-broadcast.scss
- app/assets/stylesheets/notifications.scss
- app/controllers/concerns/listings_toolkit.rb
- app/models/display_ad.rb
- app/models/identity.rb
- app/services/authentication/authenticator.rb
- app/services/authentication/providers.rb
- app/services/user_subscriptions/create_from_controller_params.rb
- app/views/dashboards/subscriptions.html.erb
- app/views/notifications/index.html.erb
- spec/liquid_tags/user_subscription_tag_spec.rb
- spec/requests/listings_spec.rb
- spec/requests/user_subscriptions_spec.rb
- spec/services/user_subscriptions/create_from_controller_params_spec.rb
This PR
1. updates the `CODEOWNERS`  file to reflect the move to `forem/forem`,
2. changes all TODO comments to the new team names and
3. standardizes the TODO comment format to `@forem/teamname`.
,
It seems we no longer have a "Team Cool", please advice who the `CODEOWNERS` entries and TODO comment should be assigned to.
n/a
> Update CODEOWNERS and team names in TODO comments

- app/models/message.rb
- app/workers/chat_channels/indexes_memberships_worker.rb
- spec/models/message_spec.rb
- spec/workers/chat_channels/indexes_memberships_worker_spec.rb
When a message is sent to a channel that has a very large number of members it can take us seconds to loop through all of those and enqueue indexing jobs for them which means it takes seconds for us to complete creating the message. The only thing being updated for the memberships is the last message sent at. This value on the memberships helps us order the chat channels in connect and I don't think we need it updated in realtime which is why I created a job to update those records asynchronously.
> Optimization:Index Chat Channel Memberships Async on Message Creation

- app/controllers/messages_controller.rb
Let's not waste time building the same message JSON for every single user that needs to be notified in a chat channel.
> Optimization:Create message JSON once when Notifying Users

- app/controllers/credits_controller.rb
- app/controllers/internal/configs_controller.rb
- app/models/site_config.rb
- app/views/internal/configs/show.html.erb
- spec/requests/internal/configs_spec.rb
Our credit prices so far were hardcoded (in cents). This PR makes the values configurable. I went with T-shirt sizing for the names of the limits, i.e. small, medium, large, xlarge (these is the number of credits purchased in a transaction). Note that I set the default in `SiteConfig` to the values currently used by DEV. They seem sensible and I don't want new Forem admins to feel forced to configure this.
Not in scope: making the limits themselves configurable, i.e. setting the limits for small, medium, etc. I'm not sure if we even want to do this, but if we do I'd rather make that follow-up PR.
n/a
> Make credit pricing configurable

- app/controllers/reactions_controller.rb
- app/labor/reading_list.rb
- spec/requests/reactions_spec.rb
I've seen at least two issues pertaining to this bug, so I went ahead and fixed it. 
~However, I found another bug while doing so... Admin reactions have probably been created with a status of `confirmed` in production instead of the expected `valid`. Which means that this proposed change will cause admin users who have saved articles before this point to have an incorrect readinglist count badge going forward, _but_ it will not affect admins from this point forward~
~If that's considered unacceptable, we can come up with a workaround or change those reaction records in production :sweat:~
~The reading list count badge on the home page currently takes all
readinglist reactions into account, but we shouldn't be including those
that are marked "archived."~
~Secondarily this fixes a bug that …
> Fix archived readinglist reactions affecting count

- db/migrate/20200723180841_create_new_comments_body_markdown_index.rb
- db/schema.rb
In order to transition our comment ID fields to bigints, we first have to update this index, `index_comments_on_body_markdown_user_ancestry_commentable` to use a digest for the body markdown to ensure that the index does not get too large for our database. 
> Optimization:Recreate Comments Index with Digest Hash

- .rubocop.yml
- db/migrate/20200723203155_change_mentions_notes_podcasts_roles_related_ids_to_bigints.rb
- db/schema.rb
Update a few more keys on these smaller tables to bigints. All of these tables have 10k or fewer rows which we have seen can be updated very quickly inline. 
You will also notice I am removing the hypershield views before running the migrations! I have noticed in the past and while doing some of the manual migrations(without the `change_column` helper) that the additional views caused the migrations to fail or timeout. When the migration is complete hypershield will be refreshed anyways so those views will get added back. 
> Optimization:Change Mentions, Notes, Podcasts, Roles Related Ids To Bigints

- spec/models/notification_spec.rb
- spec/requests/articles/articles_show_spec.rb
For the notification spec I was able to successfully recreate the errors locally by running the following set of specs.
```
be rspec "spec/labor/email_logic_spec.rb" "spec/requests/notification_subscriptions_spec.rb" "spec/services/search/reaction_spec.rb" "spec/services/search/listing_spec.rb" "spec/system/internal/admin_awards_badges_spec.rb" "spec/services/notifications/new_comment/send_spec.rb" "spec/requests/articles/articles_update_spec.rb" "spec/requests/tag_adjustments_spec.rb" "spec/requests/credits_spec.rb" "spec/system/comments/user_delete_a_comment_spec.rb" "spec/models/notification_spec.rb"
```
What appears to happen is before the first spec failure, the `let_it_be` data gets removed from the database and since the rest of the spec rely on it, the rest of the specs for that …
> Flaky Spec Fix:Remove let_it_be To Prevent Bad Database State Failing Specs

- db/migrate/20200725215546_change_small_table_related_ids_to_bigints.rb
- db/schema.rb
- spec/system/articles/user_visits_an_article_spec.rb
Changing the last of the small table keys from ints to Bigints. All of these tables when I ran these migrations on a copy of prod ran in a second or under. The last few small table migrations I have to run beyond these are around 5-10 second migrations. Then last but not least we have long migrations(#9476)  which I plan to schedule downtime for. 
Prod Data Sizes:
collections - 7k
buffer_updates - 55k ([1 second to update id, .5 seconds to update the other columns](https://gist.github.com/mstruve/1600b29a30b39b9f4edc0c8d79d9ba91))
github_repos - 35k
html_variants - 128
mentions - 6k
organizations - 2k
tweets - 11k
For more information on the spec fix checkout #9512 
> Optimization:Change Multiple Small Table Column IDs to Bigints

- spec/models/comment_spec.rb
- spec/requests/api/v0/webhooks_spec.rb
These specs I saw fail a couple of times in the dependabot update branches so I went ahead and removed the problematic `let_it_be` statements. For more information checkout #9512 
I think one of the dependabot updates must have missed vendoring a gem since after updating with master and bundling I seem to have an extra file.
> Flaky Spec Fix:Remove let_it_be usage from Comment Model Spec

- README.md
Replacing links to https://docs.dev.to in the Getting Started section with links to the newer https://docs.forem.com/ instead
- [ X] Documentation Update
Replacing links to https://docs.dev.to in the Getting Started section with links to the newer https://docs.forem.com/ instead
Closes #9505 
- [X ] no, because they aren't needed
- [ X] readme
> Replace getting started links to point to docs.forem.com

- CONTRIBUTING.md
Replacing https://docs.dev.to/contributing/forem/ new forem docs link per issue #9505.
- [ X] Documentation Update
Replacing https://docs.dev.to/contributing/forem/ new forem docs link per issue #9505.
Closes #9505 
- [ X] no, because they aren't needed
- [ X] readme
> Fix contributing guide link to point to docs.forem.com

- .rubocop_todo.yml
- app/services/notifications/reactions/send.rb
This was one of the remaining Rubocop todos. I decided to do this file by file, so it's easier to notice/rollback when something goes wrong as I seem to remember there previously were issues when we attempted to move from `OpenStruct` to `Struct`.
n/a
> Rubocop: Move from OpenStruct to Struct in Notifications::Reactions::Send

- app/views/shared/authentication/_providers_sidebar.html.erb
This adds a button to the home page sidebar for "more sign in options" to make it consistent with the site-wide navigation.
Closes #9346
> Add more sign in options button to home sidebar

- db/seeds.rb
When adding support for password confirmations in #9458 I forgot to update the seeds. @omenking pointed this out in #9509 and this PR fixes it.
Mentioned in #9509, but does not close that issue.
> Update seeds.rb with password confirmation

- lib/data_update_scripts/20200715140848_backfill_user_registered_at.rb
This backfills the `registered_at` value which we now want to use since we have the capacity to create non-registered users.
Merge after #9294
> [MERGE AFTER INVITATION PR] Add registered_at data script

- app/javascript/packs/stickySaveFooter.js
- app/views/users/_profile.html.erb
- app/views/users/_ux.html.erb
- spec/system/user/user_edits_ux_spec.rb
When a user modifies a field on the UX settings page, the save button footer will become "sticky" along the bottom of the screen (see GIF below).
I re-used the `stickySaveFooter` that we used for profile settings. I modified/added some extra classnames so that this will work for both.
#9240 
#9378
> Make UX settings save button sticky when modified

- lib/tasks/app_initializer.rake
Recently I noticed that our hypershield refresh task was running before our migrations which is a problem bc then our views are not getting updated with new migrations.
```
[hypershield] Refreshing schemas
[hypershield] Success!
== 20200726215928 ChangeTagIdsToBigints: migrating ============================
== 20200726215928 ChangeTagIdsToBigints: migrated (4.9509s) ===================
```
Now, who is ready to get their mind blown? The reason is bc of the way we were invoking/using `enhance`. 
Turns out when you use [`enhance`](https://ruby-doc.org/stdlib-2.0.0/libdoc/rake/rdoc/Rake/Task.html#method-i-enhance) like this and pass it an argument
```ruby
Rake::Task["db:prepare"].enhance(["hypershield:refresh"])
```
The task that is your argument becomes a **prerequisite** and is run …
> Bug Fix:Run Hypershield Refresh AFTER db:prepare

- app/assets/javascripts/base.js.erb
This PR updates a portion of InstantClick's `instantanize()` method to ignore any script on the page that has gone missing. This error is responsible for a lot of JS exception we're getting on honeybadger. The chunk of the code is copied directly from InstantClick's repository with very little change.
- Current latest copy chunk of code is from here https://github.com/dieulot/instantclick/blob/master/src/instantclick.js#L296
- The initial commit for the change https://github.com/dieulot/instantclick/commit/9fb9634c1d400e8b7ce7209c14f870cc0b8ee131
- [Basically 90% of all](https://app.honeybadger.io/projects/67192/faults?sort=last_seen_desc&q=-is%3Aresolved%E2%80%83-is%3Aignored%E2%80%83Unexpected+token) the `Unexpected token ':'` we've been getting on HoneyBadger.
Previous attempt: …
> Update instantClick's script clone logic

- app/models/article.rb
- app/views/articles/show.html.erb
- spec/requests/stories_show_spec.rb
Currently we're not showing the date year when articles were published last year, when we should be.
> Show article year if article published last year

- .github/workflows/rebase.yml
Fixes the `Automatic Rebase` workflow file's `actions/checkout` action to `v2`. I chose `v2` over `main` in order to avoid breaking changes which might get pushed to it, like what happened with `master` being switched to `main`. `v2` fixates it to the version `2.x.x` which will still allow to get critical security patches. More information can be found at [Workflow Syntax for GitHub Actions - jobs.<job_id>.steps.uses](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses).
Issue:
- #9510
Demo PR:
- https://github.com/Amorpheuz/forem/pull/2
Run Logs:
- https://github.com/Amorpheuz/forem/actions/runs/183020180
- https://github.com/Amorpheuz/forem/actions/runs/183020457 
- Requires to be merged into master for testing.
- Comment on a PR in order …
> fix actions/checkout to v2 for rebase workflow

- db/migrate/20200727163200_change_comment_ad_events_github_code_ints_to_bigints.rb
- db/schema.rb
Comments and Display Ad Events are medium size tables that need to have integers updated to bigints. Each table takes between 5-10 seconds to update. I have increased the STATEMENT_TIMEOUT on production to 15 seconds to help deal with these minor delays.
[Here is the timing data against our production fork](https://gist.github.com/mstruve/1600b29a30b39b9f4edc0c8d79d9ba91)
```
"comments"
"display_ad_events"
```
`github_id_code` for GithubRepos should be a non-issue, that table is small and updates in under a second.
> Optimization:Change Comment, Ad Events, and Github ID Code Ints to Bigints

- app/views/articles/show.html.erb
- spec/system/articles/user_visits_an_article_spec.rb
- show edit link when
- logged-in user is the article author
- does not show edit link when
- logged-in user is not the article author
- user does not log in
Closes #6998
> Fix showing unpublished article edit link

- app/services/search/query_builders/feed_content.rb
- app/services/search/query_builders/query_base.rb
- spec/services/search/feed_content_spec.rb
- spec/services/search/query_builders/feed_content_spec.rb
I found a "workaround" for boosting the search scores for articles with words that are adjacent by using a `should` clause in our [`bool` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#query-dsl-bool-query). The way this works is I have added a [`match_phrase`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html) query which focuses on matching phrases. How well you want the phrase matched depends on your `slop` value. A value of 0 means you want to match the phrase exactly. We are using a value of 0. A greater slop value means you are ok with some words in between the words of the phrase you searched. Adding this query ensures that any time we find the exact phrase we are looking for, the …
> Feature:Boost Scores For Adjacent Words

- app/controllers/internal/users_controller.rb
- app/models/user.rb
- app/services/authentication/authenticator.rb
- app/views/internal/users/edit.html.erb
- app/views/internal/users/show.html.erb
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20200727052235_add_lockable_to_devise.rb
- db/schema.rb
- spec/requests/internal/users_spec.rb
- spec/system/user_logs_in_with_password_spec.rb
It was recently brought to our attention that we're not locking out users who attempt to conduct dictionary and brute force attacks against user accounts. This PR activates `Devise::Lockable` to address this.
1. Make sure your user has a password that you know:
```ruby
user.update(password: "...", password_confirmation: "...")
```
2. Go to `/users/sign_in` or `/enter` in your local environment.
3. Enter the wrong password a couple of times and see your account get locked out.
4. You can unlock it in the console with `user.unlock_access!`.
> Activate Devise::Lockable

- app/views/articles/_search.html.erb
Made changes such that user is now able to click through filters in the search bar while clicking the back button does not immediately take them to the home page, but to the previous search filter. Fixes #9433.
> Search: replace replaceState with pushState to fix the back button

- app/models/user.rb
- spec/models/user_spec.rb
- spec/requests/user/user_destroy_spec.rb
- spec/services/users/estimate_default_language_spec.rb
We have a bug where a user might be able to create an account but their email doesn't come through. This adds a validation to prevent that, and lets the user know what the issue is.
1. Go to rails console
2. Instantiate a user: `user = User.new(email: "")`
3. See if the user is valid `user.valid?`
4. Should return false
> Prevent signing up with no email

- app/controllers/internal/badges_controller.rb
- app/workers/badge_achievements/badge_award_worker.rb
- spec/requests/internal/badges_spec.rb
- spec/system/internal/admin_awards_badges_spec.rb
- spec/workers/badge_achievements/badge_award_worker_spec.rb
When we reward badges via `/internal/badges` it can time out with too many usernames. This is a fairly common occurrence. This pull request moves the job to the background so the request will not time out.
> Award badges asynchronously in internal

- app/view_objects/articles/social_image.rb
- app/view_objects/cloud_cover_url.rb
- app/views/articles/show.html.erb
- spec/helpers/social_image_helper_spec.rb
- spec/services/search/feed_content_spec.rb
- spec/view_objects/cloud_cover_url_spec.rb
This gives explicit permission to use images in Google Discover etc.
`<meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1">`
I also adjusted some logic with cloudinary which allows multiple nesting which causes problems with how some of our meta images are displayed.
> Add explicit robots instruction meta tag and adjust cloudinary

- app/services/search/query_builders/listing.rb
- config/elasticsearch/mappings/listings.json
- lib/data_update_scripts/20200803142830_reindex_listing_search_column.rb
- spec/lib/data_update_scripts/reindex_listing_search_column_spec.rb
- spec/services/search/query_builders/listing_spec.rb
Listing search is currently broken because the field in Elasticsearch that we want to query against is `classified_listing_search` but the field we are searching in the view is `listing_search` thanks to simplifying the naming a little while back. This PR updates the Elasticsearch field to match what we are searching in the view. 
closes #9583 
- pull down branch
- run `bin/setup`
- Searching listings
> Bug Fix:Rename Listing Search Field in Elasticsearch to Fix Searching

- app/models/user.rb
- spec/models/user_spec.rb
- spec/requests/user/user_destroy_spec.rb
- spec/services/users/estimate_default_language_spec.rb
This reverts #9584 because it's affecting people from signing up at all, even though they have an email associated with their social account. :(
> Revert "[deploy] Prevent signing up with no email (#9584)"

- app/models/profile_field.rb
- db/migrate/20200731041554_create_profile_fields.rb
- db/schema.rb
- spec/factories/profile_fields.rb
- spec/models/profile_field_spec.rb
This PR introduces a new `ProfileField` model which will be used to store the list of available profile fields.
Notes:
* The list of columns is most likely not complete yet, so this table may get updated in future PRs.
* Integers should be fine as primary keys for this model since I don't expect any Forem to have more than 2 billion profile fields (2,147,483,647 is the max for int IDs).
* For the same reason, there are no indexes apart from the unique index on `label`. Fields numbers should be low enough that the query planner would use a seq scan over an index scan anyway.
Part of #6994
Not much to QA yet, this just adds the model.
> Add ProfileField model

- docs/netlify.toml
This redirects docs.dev.to to docs.forem.com properly. Will update for Storybook too if the deploy preview works.
1. Will update once deploy preview is available
> Add redirects from docs.dev.to to docs.forem.com

- app/javascript/packs/homePageFeed.jsx
During the initial setup, if there are no featuredArticles, the UI breaks. so to avoid this particular scenario I'm adding null checks at appropriate places.
N/A
Try setting up a brand new dev environment without any featured article, to reproduce this particular bug
N/A
> homepageFeed: Add null checks in cases where there's no featured story present

- app/controllers/listings_controller.rb
- app/javascript/listings/__tests__/AllListings.test.jsx
- app/javascript/listings/listings.jsx
This bug has been around for a long time but I never really felt the urgency to dig into it since it didn't occur that often. Finally while testing another branch I hit a 500 that caused me to zero in on the cause of this bug.  The issue here is that when a listing is owned by an organization then the org is considered the author. This means we try to search for the org's slug when trying to find the chat channel created from the message which is incorrect. What we really want is the username for the user who created the listing, not the org's slug. 
https://app.honeybadger.io/fault/66984/e8a80728dc5294c09fc37ca2d0c8f5f2
```
NoMethodError: undefined method `chat_channel_memberships' for nil:NilClass
chat_channels_controller.rb  241 render_channels_html(...) …
```
> Bug Fix:Redirect to Direct User Channel for Org Listings

- Containerfile
This lets other containers like nginx/Openresty  mount the `/opt/apps/forem/public`
directory to get at static files like 500.html.
> Add in a VOLUME directive in the Container file.

- .travis.yml
I noticed recently that we are running bundle install twice in our builds. (I also noticed we are not serving gems from the local vendor/cache also, that fix will be a separate PR.) Travis kicks off a bundle on its own during the install step. To skip this I set `install:true` in our yml file. I also removed 2 unused ENV variables
> CI Optimization:Remove unused ENV variables and Skip install Step

- app/controllers/application_controller.rb
- app/controllers/concerns/caching_headers.rb
As we work to moving away from our strict dependency on Fastly, we want to be able to support Nginx as an alternate mode for caching. We have done work to set this up in our [LFSS repo](https://github.com/forem/lfss) and we also have figured out how to property cache on Nginx by relying on Rails' `Cache-Control` headers.
At first, we thought that we needed to create two separate code paths to handle the two different types of headers: one code path for Fastly-specific headers, and another for Nginx-specific headers:
```ruby
cache_control_headers = if fastly_enabled?
"public, no-cache"
else
"public, max-age=86400"
end
```
As the code snippet above shows, the difference between Nginx and Fastly is `no-cache` existing in one, and `max-age` existing in another. After doing some further …
> Conditionally remove `no-cache` from Fastly headers

- app/controllers/internal/badges_controller.rb
- config/routes.rb
- spec/requests/internal/badges_spec.rb
- spec/system/internal/admin_awards_badges_spec.rb
This PR updates the `/internal/badges` route to `/internal/badge_achievements`. Additionally, it ensures that `/internal/badges` is redirected to `/internal/badge_achievements` in `routes.rb` as well as in the `#award_badges` method in the `Internal::Badges::Controller`. 
N/A
**To QA this PR, please do the following:** 
- Visit `/internal/badges` locally (make sure you have `admin` credentials first!) and observe that it redirects to its new route, `/internal/badge_achievements`:
- Award yourself (or any user) a badge by filling out the below form:
- Observe that after successfully creating a new badge, you are redirected back to the new route, `/internal/badge_achievements`:
N/A
> Update "/internal/badges" route to "/internal/badge_achievements"

- app/models/user.rb
- app/views/users/_language_settings.html.erb
- lib/data_update_scripts/20200805171911_clean_up_language_settings.rb
- spec/models/user_spec.rb
Currently, in production, we store a user's `language_settings` in different ways. This PR consolidates the preferred languages piece into a single format - a single `preferred_languages` Array. This will affect ~150k records.
https://github.com/orgs/forem/projects/3#card-42702165
https://github.com/orgs/forem/projects/3#card-42702170
Double-check the data looks good via Blazer.
> Cleanup preferred_languages language_settings for users

- db/migrate/20200803193841_update_user_follow_identity_reaction_pks_to_bigints.rb
- db/schema.rb
Below is the timing data for each of the migration update statements. Since these migrations are relatively fast I am proposing we just run them and take the brief outage hit. Then the longer table migrations (notifications, ahoy_messages, and articles) we pair with a warning broadcast banner about what exactly is happening. For this group of migrations, since they are so short, I think we could use a single banner stating service might be degraded for a couple of minutes.
```
```
https://github.com/orgs/forem/projects/6#card-43004918
> Update Users, Follows, Identities, and Reaction Pks to Bigints

- config/initializers/hypershield.rb
Introducing per table hiding for specificity. Mostly kickstarted by the need to hide `ahoy_messages.content` in Blazer but not `notes.content` nor `response_templates.content`
I've added a few table qualifiers and sorted the entries.
See also https://github.com/ankane/hypershield#configuration and https://github.com/ankane/hypershield/issues/8
How do I QA this? I also noticed that at the present moment `content` is still accessible in Blazer, probably because the views haven't been refreshed when https://github.com/forem/forem/pull/9634 was merged?
> Hypershield: use per column table hide for specificity

- .rubocop_todo.yml
- app/models/broadcast.rb
- app/models/collection.rb
- spec/models/broadcast_spec.rb
- spec/models/collection_spec.rb
Follow up to https://github.com/forem/forem/pull/9565
I've decided to split #9405 in multiple PR with a smaller scope/surface.
This PR tackles `Rails/HasManyOrHasOneDependent` for `Broadcast` and `Collection`.
I could neither find any orphaned notification belonging to non existing broadcasts (mostly because we don't delete broadcasts, we just deactivate them) nor I could find any article attached to a collection that doesn't exist (mostly because we don't allow people to delete collections yet ;-)).
Thus I didn't add a data update script
#9405
> Rubocop: Fix Rails/HasManyOrHasOneDependent for Broadcast and Collection

- app/views/admin/pages/_form.html.erb
This PR removes two unnecessary forward slashes from the line breaks in the Pages partial, `_form.html.erb`, that I came across while working in `/admin`. 😄 
N/A
Make sure the Travis build passes.
N/A
> Remove Forward Slashes from <br> Tags in Pages Partial

- app/models/role.rb
- app/policies/application_policy.rb
- app/views/admin/users/edit.html.erb
- spec/models/role_spec.rb
This adds a new support admin role to handle a specific DEV use-case. Ideally we have a better solution for this in the context of Forem, but for now this should do.
This allows anyone with the `support_admin` and `single_resource_admin, User` roles to banish users.
> Add new support admin role

- app/controllers/comments_controller.rb
- app/models/article.rb
- app/models/comment.rb
- app/models/notification.rb
- app/workers/comments/create_notification_subscription_worker.rb
- app/workers/comments/send_new_comment_notifications_worker.rb
- app/workers/comments/update_commentable_last_comment_at_worker.rb
- spec/requests/comments_create_spec.rb
- spec/requests/comments_spec.rb
- spec/workers/comments/create_notification_subscription_worker_spec.rb
- spec/workers/comments/send_new_comment_notifications_worker_spec.rb
- spec/workers/comments/update_commentable_last_comment_at_worker_spec.rb
**FWIW my plan would be deploy this, deploy and run the migrations, then roll this back. I think there are some good pieces here that might help performance but I also am not a fan of all the additional sidekiq jobs it creates. I would rather consolidate them.**
When we migrate the notifications table to convert ints to bigints, it is going to take us 35-40 min. The notifications table will be locked during that whole time. Because of this, if a user tries to create a comment with the code as is they will see an error message
However, the comment will get created and if they refresh the page they will see their comment. It's a bit confusing. With this change, users can create comments and all the notification updates will be kicked to the background workers. Those will then fail but …
> Migration Optimization: Async Handle Notifications for Comments When Saved

- db/migrate/20200806193438_large_table_primary_keys_to_bigints.rb
- db/schema.rb
- release-tasks.sh
Plan:
After running all of these migrations one by one and [gathering timing information](https://gist.github.com/mstruve/1600b29a30b39b9f4edc0c8d79d9ba91) we have decided to run them all during a low traffic period and display a banner on the site notifying users that they may experience degraded performance for specific parts of the application. Here is the timing breakdown with performance implications
```
```
Example Banner that we used for another set of migrations except we will explicitly call out for example when notifications are going that people should expect the notification page to be offline. 
You will also notice I am removing the hypershield views before running the migrations! I have noticed in the past and while doing some of the manual migrations(without the …
> Optimization: Change Large Table Primary Keys to Bigints

- config/initializers/honeybadger.rb
This PR is in response to the outage we had that was caused by migrating our notifications table. While the site should have still worked, the overwhelming number of errors caused our servers to crash. Here is the explanation:
> Given the very low number of logs that came into Honeybadger during the outage time I am 90% sure I know what happened and it is exactly the same scenario we saw once at Kenna that I talk about in this post https://dev.to/molly_struve/10-tips-for-debugging-in-production-ko1
> 
> We poll the app for notification counts when a user is on a page. Locally when I tested this it was no big deal, I saw the timeout errors in my logs but the app worked fine minus an updating notification count bubble. In production however every single one of those timeout's triggered a …
> Optimization:Set Honeybadger send_data_at_exit to False

- .travis.yml
- bin/ci-bundle
I noticed recently that our first builds on branches were taking much longer bc they were installing all of the gems instead of using the gem cache. I am not sure why it behaves this way on travis but adding a bash file to run the bundle install seems to have fixed the issue.
> Travis Optimization:Bundle from Bash File to Use Cache

- spec/requests/dashboard_spec.rb
When we display the org name in a dashboard the template will HMTL escape the special characters. This means if we have a name with those special characters in this test, comparing it without escaping it causes the test to fail.
```
1) Dashboards GET /dashboard when logged in as a pro user renders a link to pro analytics for the org
Failure/Error: expect(response.body).to include("Pro Analytics for #{organization.name}")
expected "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <title>Dashboard - ...ba8488d21cd8ee1fee097b8410db9deaa41d0ca30b004c0c63de0a479114156f.svg\" />\n  </body>\n  </html>\n\n" to include "Pro Analytics for O'Kon and Sons"
Diff:
@@ -1,2 +1,420 @@
-Pro Analytics for O'Kon and Sons
+<!DOCTYPE html>
+<html lang="en">
```
> Flaky Spec Fix:HTML Escape Special Characters in Assertion like Template

- app/controllers/chat_channels_controller.rb
- spec/requests/chat_channels_spec.rb
There are times when a user can click on a chat link in the app that has a link with their own username in it. When this happens, we cannot find a chat channel between the user and themselves so we end up with the following error. This exits early without setting active_channel if the chat channel does not exist. 
Honeybadger: https://app.honeybadger.io/fault/66984/e8a80728dc5294c09fc37ca2d0c8f5f2
```
NoMethodError: undefined method `chat_channel_memberships' for nil:NilClass
chat_channels_controller.rb  241 render_channels_html(...)
[PROJECT_ROOT]/app/controllers/chat_channels_controller.rb:241:in `render_channels_html'
239            end
240     chat_channel = ChatChannel.find_by(slug: slug)
241     membership = chat_channel.chat_channel_memberships.find_by(user_id: current_user.id)
242 …
```
> Bug Fix:Dont Set Active Channel if ChatChannel Does Not Exist

- docs/netlify.toml
http://docs.dev.to/api and anything else like http://docs.dev.to/ruby-doc all redirect to http://docs.forem.com/* instead of capturing the path.
See https://docs.netlify.com/routing/redirects/redirect-options/#splats for the correct syntax
> Fix Netlify catch all redirections

- .rubocop.yml
- config/routes.rb
I noticed how a bunch of my bookmarks to Blazer queries are broken because they point to `/internal` which is now called `/admin`. Prompted also by @michael-tharrington's post [here on forem.dev](https://forem.dev/michaelmadcat/renaming-things-and-broken-links-48j1) I added redirections for the old `/internal` links.
- Fire up the branch
- point it to http://localhost:3000/internal/blazer which should redirect to http://localhost:3000/admin/blazer or http://localhost:3000/internal which will redirect to http://localhost:3000/admin which will redirect to http://localhost:3000/admin/articles :)
> Redirect /internal to /admin

- .gitignore
- docs/installation/mac.md
- docs/installation/windows.md
I recently ran into some weird elasticsearch issues and fixed them by uninstalling ES and then re-installing. Once I did that, Git picked up on that as a diff:
```bash
Untracked files:
(use "git add <file>..." to include in what will be committed)
elasticsearch-7.5.2/
```
However, I don't think we want to commit large ES installation files to the repo, so it made sense to me to add it to `.gitignore`, so that massive tar files don't accidentally sneak into a PR or commit.
N/A
Make sure that installing ES locally doesn't cause a `git diff` 😉 
N/A
> Update docs with details on where to install Elasticsearch

- lib/data_update_scripts/20200805171911_clean_up_language_settings.rb
This improves the data update script from #9641  to use `update_column` instead of `update` to skip callbacks. This won't run since the data update script already ran, but in the spirit of keeping this script Idempotent and future-proof, I'm updating it here.
https://github.com/forem/forem/pull/9641
> Improve clean up of user language settings

- app/controllers/admin/invitations_controller.rb
When inviting a user to a Forem, we should have the same defaults of `v2` editor and `saw_onboarding: false` which are not these by default and have to be set on creation.
> Add proper defaults to user invites

- app/black_box/black_box.rb
- spec/black_box/black_box_spec.rb
We presently use a "private/external endpoint" for calculating score, using AWS Lambda. As we get up and running, this is not entirely necessary. I think inserting a basic "is this post good?" calc if the SDK keys are not present should be fine and we can revisit the functionality down the road.
> Create option for calculating score without external black box

- spec/black_box/black_box_spec.rb
Ignores failing flaky spec:
```
1) BlackBox#article_hotness_score returns the correct value
Failure/Error: expect(score).to eq(657_758)
expected: 657758
got: 657760
(compared using ==)
```
> Ignore Flaky Blackbox Spec

- app/mailers/notify_mailer.rb
- app/workers/users/delete_worker.rb
- spec/mailers/notify_mailer_spec.rb
- spec/mailers/previews/notify_mailer_preview.rb
- spec/workers/users/delete_worker_spec.rb
After we merged #9636 a [logic error popped up in Honeybadger](https://app.honeybadger.io/fault/66984/8d581ecec8834ef75034edb89f27593a).
Basically what happens is that the email message is sent after the user and its data is removed from the DB, this message is serialized with the user object and its ID, that user ID doesn't exist anymore in the `users` table, thus PostgreSQL foreign key checks complain that the given ID doesn't exist.
The solution is to pass along only the needed data to register the email message, not the user itself. See also https://github.com/ankane/ahoy_email/blob/5d103b925763648c7b56527dd2318cb96a8b1f9c/lib/ahoy_email.rb#L44
I also made it so that the tests actually delete the object, as with the mocks until now the tests weren't failing (which is why we haven't …
> Account deletion email: serialize only user's details

- app/views/articles/show.html.erb
This removes the flash message from the article show page, because the article show page is cached, and the flash would be cached too.
> Remove flash message from article show page

- app/controllers/admin/badges_controller.rb
This PR makes the switch to using the error message shortcut, `.errors_as_sentence`, in place of the verbose `.errors.full_messages.to_sentence` in the `Admin::Badges::Controller` per @rhymes' suggestion!
This PR relates to #9721 
Make sure the Travis build passes.
N/A
> Use .errors_as_sentece in Admin::Badges::Controller

- app/views/pages/_editor_guide_text.html.erb
- app/views/pages/_editor_liquid_help.html.erb
This PR further generalizes liquid tag documentation by replacing hardcoded `https://dev.to` URLs in examples to be dynamic based on the current domain. I also quickly updated the documentation to show the the `comment` alias instead of `devcomment` - both still work.
Closes #9730 
1. Fire up the app locally.
2. Go to `/new`, focus "body" field, and click "liquid tags" link in the right sidebar. You should _not_ see URLs in the examples that include `https://dev.to`.
3. Go to http://localhost:3000/p/editor_guide. The same thing, you should _not_ see URLs in the examples that include `https://dev.to`.
> Generalize liquid tag docs

- app/controllers/concerns/caching_headers.rb
- spec/requests/api/v0/listings_spec.rb
- spec/requests/articles/articles_spec.rb
- spec/requests/reactions_spec.rb
- spec/requests/stories_index_spec.rb
**PLEASE READ UPDATED DESCRIPTION AT THE BOTTOM OF THIS PR**
~In https://github.com/forem/forem/pull/9631, we conditionally removed the `no-cache` option from the `Cache-Control` headers that are sent along to Fastly + Nginx via our `CachingHeaders` concern, as a way of experimenting to see if Fastly still caches the same way. We did some experiments, and saw that Fastly still picked up on our change, and still caches the way that we'd expect.~
~You can play with our [Fastly fiddle snippet](https://fiddle.fastlydemo.net/fiddle/62626efe) if you'd like, but the TL;DR can be summed up by these specific headers/response from Fastly:~
```bash
HTTP/2 200
cache-control: max-age=86400, public
x-cache-hits: 0, 1, 1
x-cache: MISS, HIT, HIT
x-served-by: cache-den19627-DEN, cache-wdc5547-WDC, …
```
> Add X-Accel-Expires header to support Nginx caching

- spec/black_box/black_box_spec.rb
Failing on master
```
1) BlackBox#article_hotness_score returns the lower correct value if article tagged with watercooler
Failure/Error: expect(score).to be < 657_758 # lower because watercooler tag
expected: < 657758
got:   657758
```
> Comment out flaky Blackbox Spec

- app/models/display_ad.rb
- lib/data_update_scripts/20200813072205_remove_orphaned_display_ad_events.rb
- spec/models/display_ad_spec.rb
Before we add the foreign keys between relations, we need to cleanup the the DB.
This PR assumes that by removing an ad we want to remove its rows of events as well. Let me know if that's not the case.
As we did for ahoy models with [cleanup](https://github.com/forem/forem/pull/9710) and then [adding FKs](https://github.com/forem/forem/pull/9636) we need to do the same here.
Please make sure the query is correct :-D 
We have around 310+ thousand orphan rows in the DB:
https://dev.to/admin/blazer/queries/153-display_ad_events-orphan-rows
> Remove orphaned DisplayAdEvent rows

- app/views/comments/_comment_proper.html.erb
n/a
1. line 14 of `app/views/comments/_comment_proper.html.erb`, change that to  `<% if true %>`
2. Start the server up locally and navigate to an article with at least a comment.
3. You should be able to browse normally.
> Add missing `.call`

- app/models/profile_field.rb
- app/services/profile_fields/add_link_fields.rb
- db/migrate/20200811044202_add_attribute_name_to_profile_field.rb
- db/schema.rb
- lib/data/coding_profile_fields.csv
- lib/data/dev_profile_fields.csv
- lib/tasks/temporary/create_profile_fields.rake
- lib/tasks/temporary/migrate_profiles.rake
- spec/models/profile_field_spec.rb
This PR
* refactors `ProfileField` (attribute names are now generated differently and persisted),
* updates some field labels and placeholders and
* adds a Rake task for creating the existing DEV profile fields.
Note to whoever it may concern (but cc @benhalpern and @ludwiczakpawel so someone feels responsible): This introduces some slight copy changes to `/settings/profile`:
* "Dribble profile URL", "Behance profile URL", etc. will lose the word "profile" in the middle. It was a bit redundant anyway.
*  "I'm getting into" -> "Currently learning" (better reflects the DB column we store this in)
* "My projects and hacks" -> "Currently hacking on" (better reflects the DB column we store this in)
Part of #6994
1. Run `bundle exec rails db:migrate`
1. Run `rails …
> Start using profile model

- docs/technical-overview/architecture.md
It fixes broken link to **dynamic imports** section  in the docs
> Fixing broken link to dynamic imports in docs

- app/views/devise/passwords/new.html.erb
Currently, on [the password reset page](https://dev.to/users/password/new), I can submit the form without enter an email.
So I added the attribute `required` to make sure the user will enter something before submitting.
In addition, adding `autofocus` also improves user experience.
> Add "autofocus" and "required" attributes to the email field

- config/initializers/sidekiq.rb
It takes us a little over 60 seconds to restart Sidekiq workers on Heroku. Our [sidekiq-cron gem however only looks back 60 seconds](https://github.com/ondrejbartas/sidekiq-cron/blob/074a87546f16122c1f508bb2805b9951588f2510/lib/sidekiq/cron/job.rb#L597) to see if it missed any jobs that need to be run. This means that would inadvertently miss some jobs during a deploy. To fix this I increased the time we look back to 120 seconds. This should give us more than enough cushion for the restart and ensure we get all unrun past jobs. 
My plan is to open up some PRs on the gem to fix this issue by making the "look back" time configurable. If I really wanted to get flashy(which I might) I could set a time in Redis for each Sidekiq poll then check for the last poll time and make sure to check for …
> Bug Fix:Increase look back time for Cron jobs to 120 seconds

- app/controllers/application_controller.rb
While working on something unrelated in `ApplicationController` I noticed that we have a constant array inside a method. Normally I'd leave this as a little cleanup task during downtime, but it's an unconditional `before_action` called `verify_private_forem` so we'll create a garbage array on every request.
Only related to my OCD.
Everything should work exactly like before.
> Add PUBLIC_CONTROLLERS constant

- app/services/search/user.rb
I could not find anywhere in the codebase where we were using a user's role data on the frontend from Elasticsearch. For this reason, I have gone ahead and removed it from the data returned to the view. I could go ahead and remove it completely from Elasticsearch and stop serializing it but I could see it being really handy for filtering at some point so I left it in there.
> Refactor:Remove User Roles From Elasticsearch Returned Data

- app/helpers/rate_limit_checker_helper.rb
- docs/api_v0.yml
Quick Fix: Update documentation to reflect Rate Limit for article updates. Also update SiteConfig notes to let the user know to update the API docs when that value is changed. 
Long term here we probably need an API or something for the Rate Limit values so we can change them on the fly without having to open a PR every time. And then we should document the rate limit endpoints and remove all rate limit values from the docs since different Forem's will likely have different values. 
https://github.com/forem/forem/issues/9674
> Documenation: Update API Article Update Rate Limit Value to 30

- app/labor/article_suggester.rb
- spec/labor/article_suggester_spec.rb
Found a couple issues with the Article Suggester class from some recent changes we made.
1) We added [a score filter](https://github.com/forem/forem/pull/9833/files#diff-13b25834b581265292d484e25c446ffdR60) which caused our spec to no longer be able to pull back articles with the same tag. This caused the spec to have to fallback on `other_suggestions` which is not what we wanted to be testing so I updated that.
2) We changed the way we do offsets. One of the changes we made was to use the total number of published articles divided by 10 to help us get that number. However, we were caching that article count in a class method rather than an instance method which I think was what the intention was. I removed the class level caching. I think this may have gotten set during spec runs and we …
> Flaky Spec Fix:Ensure We Find Articles With Tags and Dont Cache Count for Class Method

- Containerfile
This post on https://forem.dev/avalerionv/difficulty-installing-forem-on-ubuntu-18-04-tls-4eh6
talks about issues running Forem on Linux. Digging into the issue it seems that
podman-compose does not pass the `--userns=keep-id` flag correctly to podman so
files and directories mounted as root and not as the user. This causes permission
denied errors.
`podman rmi localhost/forem-rails:latest` might be needed to rebuild the container with the change.
https://forem.dev/avalerionv/difficulty-installing-forem-on-ubuntu-18-04-tls-4eh6
> Comments out the USER directive due to issues with podman-compose.

- app/controllers/api/v0/comments_controller.rb
- app/views/api/v0/comments/_comment.json.jbuilder
- docs/api_v0.yml
- spec/requests/api/v0/comments_spec.rb
Added created_at field for comments in api response
Fixes #6095 
Currently when user requests api/comment they do not see when each comment was created
Now that information is included:
> API: add created_at datetime to comments

- app/labor/badge_rewarder.rb
- app/workers/badge_achievements/badge_award_worker.rb
- config/schedule.yml
- lib/tasks/badges.rake
- spec/labor/badge_rewarder_spec.rb
- spec/workers/badge_achievements/badge_award_worker_spec.rb
This moves the yearly badge awarding method into a Sidekiq Cron job using the already existing `BadgeAchievements::BadgeAwardWorker` which I tweaked. I could make a separate worker for each badge or a different worker for "predefined" badges but I was not sure what to call it and keeping all the badge rewarding in one place seemed like a better idea. 
Rather than doing all badge awarding in a single cron I decided to split them out. This will make the jobs run faster which is what Sidekiq is really made for and it will make them more resilient. If we break something for one badge the rest won't fail bc of it. 
Let me know what you all think of this approach! If you approve then I will continue with the rest of the badges. If not we can discuss and tweak things. …
> Refactor:Move Yearly Badge Awarder to Sidekiq Cron

- app/liquid_tags/details_tag.rb
- app/views/liquids/_details.html.erb
- app/views/pages/_editor_guide_text.html.erb
- app/views/pages/_editor_liquid_help.html.erb
- spec/liquid_tags/details_tag_spec.rb
- spec/support/fixtures/approvals/details_liquid_tag_spec.approved.html
This PR creates a new liquid tag that enables an author to include a `details` HTML element which helps to hide content behind a click.
This concept has been discussed in a few places and I started by registering the tag under `details`, `collapsible`, and `spoiler` so that any/all of these would work and do the same thing. If we want to separate the functionality, like make `spoiler` behave similarly to how [Reddit handles it](https://www.reddit.com/wiki/commenting#wiki_posting), let's decide that now so we can avoid having to re-save a bunch of articles in the future.
I figured since the default styling looks okay we can start there, see some real use cases in the wild, and then update the styling with the design team later.
While this liquid tag is bare-bones by putting text into a …
> Create details liquid tag

- lib/data_update_scripts/20200818103028_nullify_orphaned_by_article_html_variant_trials.rb
The effort to cleanup and fortify the tables continues. In this episode we have `HtmlVariant`, `HtmlVariantSuccess` and `HtmlVariantTrial`.
This is step 1 of 2:
- cleanup the data, this PR
- enforce relations and foreign keys on the various models
- `HtmlVariantSuccess` is linked to both `HtmlVariant` and `Article` (it contains orphaned rows for neither: https://dev.to/admin/blazer/queries/188-html_variant_successes-orphan-rows)
- `HtmlVariantTrial` is linked to both `HtmlVariant` and `Article` (it contains orphaned rows for `Article`, thus this PR: https://dev.to/admin/blazer/queries/153-html_variant_trials-orphan-rows)
As the relation with the `Article` is optional, I chose to set `NULL` those IDs that do not exist anymore. Let me know if instead we should destroy them.
Please review …
> Nullify article_id for HtmlVariantTrials linked to non existing articles

- app/helpers/chat_channel_memberships_helper.rb
- app/javascript/chat/ChatChannelSettings/ChatChannelSettings.jsx
- app/javascript/chat/RequestManager/PersonalInvitationListItem.jsx
- app/javascript/chat/chat.jsx
- app/javascript/chat/content.jsx
After leaving a room and then navigating to the /connect view, the room that was left still shows up in the URL.
Also did some fixes in case of Joining a channel.
Fixes: #9501
> 🐞Bug Fix: Room that has been left still shows up in URL [Fixes: #9501]

- .rubocop.yml
- app/controllers/api/v0/articles_controller.rb
- app/controllers/image_uploads_controller.rb
- app/services/search/base.rb
- app/services/search/feed_content.rb
- app/services/search/tag.rb
- app/services/search/user.rb
- spec/serializers/search/reaction_serializer_spec.rb
- spec/services/search/chat_channel_membership_spec.rb
- spec/services/search/feed_content_spec.rb
- spec/services/search/listing_spec.rb
- spec/services/search/query_builders/chat_channel_membership_spec.rb
- spec/services/search/query_builders/feed_content_spec.rb
- spec/services/search/query_builders/listing_spec.rb
- spec/services/search/query_builders/reaction_spec.rb
- spec/services/search/query_builders/user_spec.rb
- spec/services/search/reaction_spec.rb
- spec/services/search/user_spec.rb
Enabling Rubocop 0.89's `Style/SingleArgumentDig` to replace `hash.dig(:foo)` with `hash[:foo]` which is the most common syntax for single key access
- #9699
- #9709
> Rubocop: Enable and fix Style/SingleArgumentDig

- lib/tasks/app_initializer.rake
For realz, I fixed it this time. Turns out we actually gotta call execute on the task when using the block notation this way. 
If you use argument notation like this you don't have to call execute on your task, it just automatically does it for you.
```ruby
Rake::Task["db:prepare"].enhance(["search:setup"])
```
For block notation, you have to call execute yourself.
> Bug Fix:Execute Hypershield Refresh Task

- .gitignore
- bin/setup
As many of you noticed, when you start using the `.env` file instead of `application.yml` you tend to see these warnings a lot.
```
WARNING: Skipping key "TWITCH_CLIENT_ID". Already set in ENV.
WARNING: Skipping key "TWITCH_CLIENT_SECRET". Already set in ENV.
WARNING: Skipping key "TWITCH_WEBHOOK_SECRET". Already set in ENV.
WARNING: Skipping key "STACK_EXCHANGE_APP_KEY". Already set in ENV.
```
This is because we are still using the Figaro gem. We need to keep that in place for a while until everyone moves over to the new `.env` setup. I was planning to give it a month since deploying the change. In the meantime, removing the `application.yml` will fix the warnings. However, in the event something goes wrong, I dont want to be programmatically removing files that might have lots of …
> Warning Fix: Rename Unused application.yml File to Prevent Warnings

- app/assets/stylesheets/chat.scss
- app/javascript/chat/chat.jsx
- app/views/chat_channels/index.html.erb
So after doing more research into it. I found few things, `navigator.userAgent.match(/iPhone/i) && !navigator.userAgent.match('CriOS')` this logic as added for IOS app which have this tabs
But user agent in case of iOS app is custom and equal to "DEV-Native-ios" that's how I discover that this request never fulfill and classes never got added. So When I removed it everything as working fine.  
Fixes [#4024](https://github.com/forem/forem/issues/4024)
> 🐞Bug Fix: Chat doesn't extend to its frame on Firefox iOS [ Fixes #4024 ]

- app/labor/badge_rewarder.rb
- config/schedule.yml
- lib/tasks/badges.rake
Moves the award_beloved_comment_badges task to a Sidekiq Cron and runs it just after the yearly badges. Since I was here, I also added a little optimization to eager load the users.
nothing to do with the PR but makes me laugh 😅
> Refactor: Move beloved comment Badge to Sidekiq Cron

- .rubocop_todo.yml
- app/models/listing_category.rb
- spec/models/listing_category_spec.rb
Currently the relation between `ListingCategory` has two issues:
- it does not work because it's not able to infer the name of the foreign key, you can verify it this by loading the console in master:
```ruby
category = ListingCategory.first
category.listings # this doesn't return the array of listings
```
- it doesn't define a `dependent` clause. I chose `:restrict_with_error` because removing a category should fail if there are listings assigned to that category.
The foreign key is already in place so no need to add that.
```ruby
category = ListingCategory.first
category.destroy
puts category.errors
```
> Rubocop: Fix ListingCategory has_many relation to Listing

- app/controllers/admin/configs_controller.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- spec/requests/admin/configs_spec.rb
We had the staff user id as a field which existed in `SiteConfig` but was not editable, based on old mental models. This updates it so this is configurable like anything else.
> Allow staff_user_id to be modified

- app/views/admin/chat_channels/index.html.erb
This change gets rid of a bunch of axe warnings in the admin chat_channels interface :tada:
> Fix axe warnings on admin/chat_channels

- config/schedule.yml
After #9872 was merged I went to go and remove the rake task from Heroku. This is when I noticed we were running the rake task twice a day. 12AM UTC and 2:30PM UTC. To keep with that schedule of running it twice a day I updated the cron jobs to run every 12th hour. Not exactly the same schedule as before but it will ensure the job runs twice a day. Not sure if that was a mistake or needed but the easiest thing to do is keep the same schedule for now. 
Keeping the yearly club badge to once a day since that checks the past 2 days for created users so once a day should suffice.
> Bug Fix:Run Badge Award Job Twice a Day

- app/models/user.rb
There are multiple views where we call `current_user.any_admin?` multiple times([4 times in this file](https://github.com/forem/forem/blob/master/app/views/moderations/mod.html.erb)) which as is, leads to multiple database hits. This caches the value locally on the user so we only have to hit the database once. Inspiration from #9873
> Optimization:Locally Cache any_admin? For User Instance

- spec/requests/api/v0/comments_spec.rb
I noticed while reviewing https://github.com/forem/forem/pull/9841 that it had the following flaky spec. When I looked closer at the spec I realized that we were comparing the comment created_at in the response to the article created_at which is incorrect. I updated the spec with the proper root_comment created_at. 
```
-"created_at" => "2020-08-19T15:39:53Z",
+"body_html" => "<p>Neutra kinfolk distillery chartreuse small batch cliche. Polaroid mustache cornhole direct trade 
....
+"created_at" => "2020-08-19T15:39:54Z",
```
> Flaky Spec Fix:Use Comment created_at in Expectation

- lib/sidekiq/honeycomb_middleware.rb
- lib/sidekiq/worker_retries_exhausted_reporter.rb
- spec/lib/sidekiq/worker_retries_exhausted_reporter_spec.rb
We are getting a lot of false alerts in [Datadog from our WorkerRetriesExhaustedReporter.](https://app.datadoghq.com/monitors/15829532) They seem to center around the `Comments::BustCacheWorker` but I am not sure why that is. I did some testing locally but nothing seemed off, the job would fail as expected and the death handler would be triggered as expected. Seeing as we get these alerts when no jobs have died I have added some additional recording data to try and help me figure out what is happening. 
https://github.com/orgs/forem/projects/6#card-43527526
> Optimization:Collect More Specific Data From Sidekiq Jobs

- app/controllers/admin/configs_controller.rb
- app/controllers/application_controller.rb
- app/controllers/credits_controller.rb
- app/controllers/stripe_active_cards_controller.rb
- app/controllers/users_controller.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- app/views/credits/new.html.erb
- app/views/users/_billing.html.erb
- config/.env_sample
- config/initializers/stripe.rb
- spec/requests/admin/configs_spec.rb
This is an example of setting stripe from dynamically, so the keys can be pulled from a storage source instead of `ENV`.... We can do this in several other places as well in order to move away from dependency on boot-time logic which requires us to restart the app if a user were to configure it.
An admin can now go into _their own_ stripe account and put the keys into their forem.... Which really is the way things should be. If we want to modify how storage is done in the future, we could, but the way this all works for now makes sense. I think we can keep plopping more into `SiteConfig` until we're done getting stuff out of `ENV`.
> Set Stripe dynamically instead of at boot

- app/controllers/admin/profile_fields_controller.rb
- app/models/profile.rb
- app/services/profile_fields/add.rb
- app/services/profile_fields/remove.rb
- spec/models/profile_spec.rb
- spec/requests/admin/profile_fields_spec.rb
- spec/services/profile_fields/add_spec.rb
- spec/services/profile_fields/remove_spec.rb
This PR adds two service objects, `ProfileFields::Add` and `ProfileFields::Remove` which take care of adding and removing profile fields and keeping the corresponding store accessors in sync. For now we do not actually modify any data when a profile field is removed, I'm still spiking ideas how to do this without killing our DB. I also updated `Admin::ProfileFieldsController` to make use of the new service objects.
Related to #6994
1. Use the service objects in a Rails console session and ensure that the store accessors automatically update.
2. Use the admin page to add/remove profile fields and ensure that the store accessors automatically update.
> Automatically refresh profile accessors

- config/schedule.yml
- lib/tasks/badges.rake
This moves the `award_contributor_badges_from_github` and `award_tag_badges` rake tasks to Sidekiq Cron jobs.
> Refactor:Move Tag Badge and Github Badge Awards to Sidekiq

- .rubocop_todo.yml
- app/models/podcast.rb
- app/models/podcast_episode.rb
- db/migrate/20200820093731_add_missing_foreign_keys_to_podcast_episodes.rb
- db/migrate/20200820093752_validate_add_missing_foreign_keys_to_podcast_episodes.rb
- db/schema.rb
- spec/models/podcast_episode_spec.rb
- spec/models/podcast_spec.rb
`PodcastEpisode` and `Podcast` are missing a few clauses and one foreign key.
There's should be no need for a cleanup PR as there are no orphan rows in the DB 
See 
- https://dev.to/admin/blazer/queries/194-orphan-podcast-episodes
- https://dev.to/admin/blazer/queries/195-orphan-podcasts
> Add relations and foreign keys between Podcast related models

- app/workers/listings/expire_old_listings_worker.rb
- app/workers/tags/resave_supported_tags_worker.rb
- config/schedule.yml
- lib/tasks/fetch.rake
- spec/workers/listings/expire_old_listings_worker_spec.rb
- spec/workers/tags/resave_supported_tags_worker_spec.rb
This moves the `resave_supported_tags` and `expire_old_listings` rake tasks to Sidekiq Crons. While I was here I made a little optimization to the listing task by adding published to our scope and by looking for published articles with `expires_at` less than the current day. This will ensure that listings get expired even if we run into problems and possibly skip a day for one reason or another. 
> Refactor:Move Listing and Support Tag Tasks to Sidekiq

- app/labor/cache_buster.rb
On Forem.dev we are not currently using any cacheing. This causes our CacheBuster to fail with the following error whenever it is run
```
Fastly::Error: {"msg":"Provided credentials are missing or invalid"}
```
To prevent this from happening I added a guard clause to ensure we dont try to hit the Fastly API unless we have credentials for it. 
https://github.com/orgs/forem/projects/6#card-43527526
> Bug Fix:Skip Busting Edge Caches if Fastly API Key is not Present

- app/labor/badge_rewarder.rb
In new Forem's there will likely be a time before badges are properly set up. During this window we don't want to be stacking up a bunch of job failures. We also don't want every Forem to feel the need that they are required to have all of these preset badges. This allows us to gracefully exit a badge task if the badge is not present. 
https://github.com/orgs/forem/projects/6#card-44035785
Badge jobs should no longer return an error if you pull this branch down, restart your server and enqueue some of the corn jobs by hand
> Bug Fix: Dont Fail Jobs If Badge Does Not Exist

- app/models/profile_field.rb
- db/migrate/20200820055018_add_display_colums_to_profile_fields.rb
- db/schema.rb
- spec/factories/profile_fields.rb
- spec/models/profile_field_spec.rb
This PR adds two more colums to the `ProfileField` model: 
* `display_area`: an enum that for now has 2 options, "header" or "left_sidebar".
* `show_in_onboarding`": Whether or not the profile field wil be shown during the onboarding flow.
Part of #6994
Not much to test yet, this is mostly about unblocking @Ridhwana for the work on the new profile page.
> Add display columns to ProfileField

- app/views/articles/tag_index.html.erb
- app/views/tags/index.html.erb
I was randomly inspecting the rotated images/logos and notice the inline CSS style is missing a closing bracket. It's not breaking anything now, but I figured it's best to fix it. I have also fixed the same occurrence in the "tags" page.
Current: `transform: rotate(5deg`
Update: `transform: rotate(5deg);`
Here is a screenshot of the current one to clarify what I meant (the 2 red boxes):
> Fix incomplete inline CSS style

- app/lib/constants/mastodon.rb
Apparently we have a Mastodon URL in the DB that bypassed validation (or was added before validation was instituted). As it's a legit Mastodon, it's just easier to add it to the list
Closes https://github.com/forem/forem/issues/9938
> Add tech.lgbt to allowed Mastodon instances

- app/models/profile.rb
- app/models/profile_field.rb
- app/views/admin/profile_fields/_form.html.erb
- spec/factories/profile_fields.rb
- spec/models/profile_field_spec.rb
- spec/models/profile_spec.rb
- spec/requests/admin/profile_fields_spec.rb
When creating the new `ProfileField` model I originally added a column called `active`. My rationale was as follows: While admins experiment with setting up their Forem instance the may try out different fields and see how the profile page looks. Deleting and recreating is tiring, so I wanted to give them an option to disable it. However, after discussing this with @Ridhwana we decided that the potential confusion is not worth it and this is a case where less flexibility makes for a better product experience. 
There will be a follow-up PR to remove the column itself.
Part of #6994
Nothing, if the specs are green, we should be good to go.
> Stop using ProfileField#active Part 1

- app/models/profile_field.rb
- db/migrate/20200821035520_remove_active_from_profile_field.rb
- db/schema.rb
__This needs #9910 to be merged first!__
See #9910 for details. tl;dr: we decided against using an `active` attribute on profile fields, so we are removing. Following the practices recommended by the [`strong_migrations` gem](https://github.com/ankane/strong_migrations) we do this in 2 steps. 
**Note:** The diff here will get smaller once the other PR has been merged and we update this PR accordingly. I just wanted to prepare everything in one go.
Part of 6994.
Specs green? Good to go.
> Stop using ProfileField#active Part 2

- .env_sample
- app/views/admin/articles/index.html.erb
DEV sends tweets to Buffer to offload the scheduling functionality to a third party. However, [this functionality has been discontinued by Buffer](https://buffer.com/developers/api) for new developers. DEV's functionality still works, but it will not work for the broader Forem ecosystem.
I think the best scenario is we build in this basic functionality ourselves.
Instead of _sending to Buffer_, we could mark a social media share with a timestamp and then build our own cron job to have it sent at the right time. We might not match Buffer feature-for-feature, but that would make everything much more usable as FOSS and as something without external dependencies like that.
For now, I'm marking this as legacy.
> Mark Buffer as legacy

- app/workers/notifications/remove_old_notifications_worker.rb
- config/schedule.yml
- lib/tasks/notifications.rake
- spec/workers/notifications/remove_old_notifications_worker_spec.rb
Move remove_old_notifications rake task to Sidekiq.
> Refactor:Move remove_old_notifications Rake Task to Sidekiq

- app/workers/bust_cache_path_worker.rb
- config/schedule.yml
- lib/tasks/cache.rake
- spec/workers/bust_cache_path_worker_spec.rb
Move all cache-busting rake tasks to sidekiq. The only cache-busting I did not move was the `/shecoded` path. I think that is very specific to DEV and if that is something we need done in the future we should probably come up with a better way to handle that. 
Update names to match actual run times since before they were flip flopped. 
> Refactor:Move Cache Busting Rake Tasks to Sidekiq

- .rubocop_todo.yml
- app/models/organization.rb
- lib/data_update_scripts/20200821103125_nullify_orphaned_articles_by_organization.rb
- lib/data_update_scripts/20200821103305_nullify_orphaned_collections_by_organization.rb
- lib/data_update_scripts/20200821103405_remove_orphaned_credits_by_organization.rb
- lib/data_update_scripts/20200821103718_remove_orphaned_display_ads_by_organization.rb
- lib/data_update_scripts/20200821103834_nullify_orphaned_listings_by_organization.rb
- lib/data_update_scripts/20200821103834_remove_orphaned_listings_by_organization.rb
- lib/data_update_scripts/20200822082229_remove_orphaned_notifications_by_organization.rb
- lib/data_update_scripts/20200822083050_remove_orphaned_sponsorships_by_organization.rb
- spec/models/organization_spec.rb
This PR adds many missing `dependent` clauses to `has_many` relations of the `Organization` model.
It also adds 7 cleanup scripts to either delete orphaned data or nullify the `*_id` column if the organization doesn't exist. The script reflect the type of relation between the two entities.
Please double check each script while reviewing.
We do have orphaned rows in our DB (and likely in other Forems DB's), see https://dev.to/admin/blazer/queries/197-organization-counts
The following PR will add foreign keys where necessary.
> Add dependent clauses to relations for Organization and add cleanup scripts

- spec/spec_helper.rb
With the way RSpec/test load files, Simplecov doesn't detect any env var because ApplicationConfig isn't loaded immediately. We need to explicitly load it first in `spec_helper.rb` so the content within `.simplecov` can have access to env var.
I think Dotenv will end up loading env twice but I have not notice any side-effect and it doesn't seem to slow down anything.
n/a
Add `export COVERAGE='false'` to your `.env` and run the test, you should be able to disable it properly and not see test coverage slow you down.
n/a
> Explicitly load dotenv first in test

- app/workers/sitemap_refresh_worker.rb
- config/schedule.yml
- spec/workers/sitemap_refresh_worker_spec.rb
Move Sitemap rake task out of Heroku scheduler and into a cron Sidekiq Worker. 
> Refactor:Move Sitemap Refresh Rake Task to Sidekiq

- app/helpers/authentication_helper.rb
- app/mailers/application_mailer.rb
- app/services/authentication/providers.rb
- app/views/layouts/mailer.html.erb
- app/views/users/_account.html.erb
- app/views/users/_account_providers_settings.html.erb
- spec/helpers/authentication_helper_spec.rb
Currently we display either Twitter or GitHub in the mailer footer to nudge a person to sign in with the correct provider. There are a few problems with that:
- a person can be signed in with more than one provider, so it's arbitrary to choose one or the other in the email
- soon we'll have more than one providers
- either or all of these two providers might be disabled in future Forems
This PR makes the footer a little bit more aware
It goes from:
>  Reminder: You used Twitter to authenticate your account, so use that to sign in if prompted. 
to
> Reminder: You used <b>GitHub and Twitter</b> to authenticate your account, so use any of those to sign in if prompted
if more than one is enabled.
1. start the PR
1. sign in with any of the authentication methods
1. check the footer of the …
> Display all authentication providers in mailer footer

- app/workers/credits/sync_counter_cache.rb
- config/schedule.yml
- lib/tasks/fetch.rake
- spec/workers/credits/sync_counter_cache_spec.rb
I was going to dive in and see if we even still need this but decided not to waste time on it [since even the gem docs suggest running a sync periodically](https://github.com/magnusvk/counter_culture#manually-populating-counter-cache-values). To me that seems like a major weakness in the gem but one we can live with for now. 
> Refactor:Move Credit Counter Cache Sync to Sidekiq

- config/environments/production.rb
Per the [Sendgrid docs](https://sendgrid.com/docs/for-developers/sending-email/rubyonrails/#configure-actionmailer-to-use-sendgrid) this is how you would set up ActionMailer if you have an API key present. I kept the old way to ensure backwards compatibility for other communities 
https://github.com/orgs/forem/projects/6#card-44219616
> Update Sendgrid to Use API Key if Present

- config/initializers/0_application_config.rb
- spec/initializers/application_config_spec.rb
These warnings are inundating some of our production environments for variables that we never plan to set. Change the debug level for these to debug so we can access them if we need to but they are not always logged in production. 
https://github.com/orgs/forem/projects/6#card-44230888
My feelings toward @jdoss for this PR 👇
> Refactor:Change Unset Var Warnings to Debug Level

- scripts/entrypoint.sh
RELEASE_FOOTPRINT will be set to the output of `date -u +'%Y-%m-%dT%H:%M:%SZ'` (2020-08-25T02:02:21Z for example) when the container starts. This will be reset to a new date and time string every time the container starts.
Fixes #9904 
https://github.com/forem/forem/pull/9904
> Export RELEASE_FOOTPRINT on container start.

- app/models/github_repo.rb
- app/workers/github_repos/update_latest_worker.rb
- config/schedule.yml
- lib/tasks/fetch.rake
- spec/workers/github_repos/update_latest_worker_spec.rb
This moves the `github_repo_fetch_all` rake task to Sidekiq. I also took the opportunity to optimize the `update_to_latest` method for GithubRepo. 
> Refactor:Fetch New Github Repos From Sidekiq Cron

- app/controllers/async_info_controller.rb
- app/helpers/application_helper.rb
- app/views/articles/_sidebar.html.erb
- app/views/articles/_sidebar_additional.html.erb
- app/views/articles/index.html.erb
- app/views/feedback_messages/index.html.erb
- app/views/layouts/_styles.html.erb
- app/views/liquid_embeds/show.html.erb
- app/views/moderations/actions_panel.html.erb
- app/views/moderations/mod.html.erb
- app/views/onboardings/show.html.erb
- app/views/partnerships/index.html.erb
- app/views/partnerships/show.html.erb
- app/views/shell/_bottom.html.erb
- app/views/shell/_top.html.erb
- config/initializers/honeybadger.rb
- config/initializers/honeycomb.rb
- config/initializers/initialization_cachebust.rb
- config/sample_application.yml
- config/webpack/environment.js
- spec/helpers/application_helper_spec.rb
We use `HEROKU_SLUG_COMMIT` to know when one release is later than another to bust caches and other duties.
This is a Heroku dependency we need to get rid of. This PR introduces a minute-precision timestamp which will be good enough right this moment, but it could be different on a process-by-process basis. For basic cache-busting and the such that is fine, but ideally we can computer a value here which will be more consistent.
If anybody has an idea for the most straightforward way to do that, feel free to drop an idea. Otherwise, I'd say we ship this as "good enough for right now".
> Replace HEROKU_SLUG_COMMIT with custom footprint (naive)

- docs/creators/configure-forem.md
I fixed a odd typo caused by markdown.
Before:
After:
> Fix a typo caused by markdown

- app/assets/stylesheets/moderators.scss
This PR fixes a position of mod actions button on article view on mobile - it will no longer cover the action bar at the bottom.
^ left: before. right: after.
> Mod Button placement fix on mobile

- .dockerignore
- Containerfile
- scripts/entrypoint.sh
In the past it was always useful to have meta data within regards to the SHA and
build date/time. This adds in two new env vars that are written to disk as flat
files and then exported to environment variables when the container starts up.
This motivation comes from this comment:
https://github.com/forem/forem/pull/9987#discussion_r476123829
> Add FOREM_BUILD_SHA and FOREM_BUILD_DATE to the container.

- app/controllers/admin/configs_controller.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- app/views/layouts/_footer.html.erb
- spec/requests/admin/configs_spec.rb
This change allows admins to use footer mascot images of any size without coercing them to the default values. They can manage the default values in site config.
I think ideally this would be removed and replaced with some sort of custom CSS/theming system down the road, but I'm not sure we should anticipate that until we are ready to dedicate resources to it. When that time comes this will be easy to yank out!
Closes https://github.com/forem/forem/issues/9994
Adds these too fields!
*note:* adds site config values
> Allow greater flexibility for footer mascot image

- config/environments/production.rb
A couple of weeks ago I flipped our logging in production to `:error` level to see how it worked. It has been working really well so I want to make that the default and then if we need more color we can lower the level through the ENV variable.
> Optimization:Default Production Logging to Error

- docs/backend/readme.md
I added developer documentation for Sign in with Facebook in https://github.com/forem/forem/pull/9922, but didn't link it up correctly in `docs/backend/readme.md`, which Gitdocs requires to build the file and actually publish it!
> Add facebook page to Backend Guide index

- app/models/github_repo.rb
We have had some [`GithubRepos::UpdateLatestWorker`](https://dev.to/sidekiq/morgue)s die on us due to missing identities. When we try to create a `Github::OauthClient` for a user with a GithubRepo sometimes we can't because that user does not have a Github Identity. I'm not sure how that happens but this will allow us to continue to process the rest of the users in the job.
I will dig in more to why these users are missing identities and if we cant better update this flow but in the meantime this will get the job back up and running and able to finish.
> Bug Fix: Dont Kill Entire Job When User is Missing a Github Identity

- app/controllers/admin/configs_controller.rb
- app/views/admin/configs/show.html.erb
- spec/requests/admin/configs_spec.rb
Right now, you can submit the config form without including the required confirmation text. When you do this, it's a bit frustrating because it's such a large form and you can lose your inputs. 
~Also, this returns an unauthorized status which isn't really true because you can hit this error with all the necessary permissions, so I changed it to return a 422 (unprocessable entity) because most accurately (imo) you're missing a required parameter.~
This change now includes both frontend validation and more specific error messaging for the backend validation.
> Make confirmation text a required field

- app/models/github_repo.rb
- app/workers/github_repos/repo_sync_worker.rb
- spec/models/github_repo_spec.rb
- spec/workers/github_repos/repo_sync_worker_spec.rb
Currently our GithubRepo Update worker is taking over an hour to complete. This breaks up the job into individual jobs for each GithubRepo to help speed things up. 
https://github.com/orgs/forem/projects/6#card-44435765
> Optimization:Break Github Repo Updates into Individual Sidekiq Jobs

- app/labor/email_digest.rb
- app/workers/email/enqueue_digest_worker.rb
- app/workers/email/send_user_digest_worker.rb
- app/workers/send_email_digest_worker.rb
- config/schedule.yml
- spec/labor/email_digest_spec.rb
- spec/workers/email/enqueue_digest_worker_spec.rb
- spec/workers/email/send_user_digest_worker_spec.rb
The SendEmailDigest job is a beast right now bc it loops through nearly 300k users to send email digests. This breaks it down so that the article collection and email sending is handled in individual jobs, one for each user. All the main job, now called `Email::EnqueueDigestWorker` has to do is enqueue those short fast-running jobs. 
The reason we want lots of fast running jobs rather than one long running one is because Sidekiq is built for short running jobs. Also, when we deploy, we shutdown sidekiq and all the jobs that are processing get restarted. This means if you have a long running job and you deploy a lot, it will never get a chance to finish. Its better to have lots of short running jobs. Ideally ones that can finish in under 30 seconds since that is how much grace time Sidekiq …
> Optimization:Break Send User Digest Emails in Single Jobs

- db/seeds.rb
During #9253 the method `ChatChannel.create_with_users` got removed. Alas, it was still used in `seeds.rb`, which raised an exception when trying to seed. This updates the seed file to use the newly introduced service object.
> Fix seeds.rb

- app/controllers/sessions_controller.rb
Cookie deletion should specify the domain as well:
> Please note that if you specify a :domain when setting a cookie, you must also specify the domain when deleting the cookie:
```ruby
cookies[:name] = {
value: 'a yummy cookie',
expires: 1.year,
domain: 'domain.com'
}
cookies.delete(:name, domain: 'domain.com')
```
from https://api.rubyonrails.org/v6.0.3.2/classes/ActionDispatch/Cookies.html
#10036
> Delete cookies correctly by specifying the domain

- app/javascript/article-form/components/ArticleCoverImage.jsx
- app/javascript/leftSidebar/TagsFollowed.jsx
- app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
- app/javascript/modCenter/singleArticle/index.jsx
Following the spirit of "explicit is better than implicit" I think we should consider switching to `<Fragment></Fragment>` instead of `<></>`. 
The latter also breaks syntax highlighting in some editors, also being less intuitive for people that don't already know Preact well. My first instinct was: "why do we have empty tags?", then I remembed about fragments ;-)
> Use explicit name for Preact fragments

- .rubocop_todo.yml
- app/models/article.rb
- app/models/comment.rb
- app/services/articles/destroyer.rb
- lib/data_update_scripts/20200825095213_remove_orphaned_buffer_updates_by_article.rb
- lib/data_update_scripts/20200825095512_nullify_orphaned_comments_by_article.rb
- lib/data_update_scripts/20200825102635_remove_orphaned_notification_subscriptions_by_article.rb
- lib/data_update_scripts/20200825102956_remove_orphaned_notifications_by_article.rb
- lib/data_update_scripts/20200825103119_remove_orphaned_profile_pins_by_article.rb
- lib/data_update_scripts/20200825103244_remove_orphaned_rating_votes_by_article.rb
- spec/models/article_spec.rb
- spec/models/comment_spec.rb
This PR adds a few `dependent` clauses to `has_many` and the correspondent cleanup scripts.
I also fixed `Comment` validation as we currently have 8,987 with invalid article IDs and those comments should be valid and survive even if the article doesn't exist.
As usual, the PR with the foreign keys will be submitted separately
- we have orphaned buffer updates, comments with invalid ids, orphaned notifications subscriptions, pins and rating votes https://dev.to/admin/blazer/queries/197-articles-counts
- we have orphaned notifications https://dev.to/admin/blazer/queries/201-orphan-notifications-by-article
> Add dependent clauses to Article and fix Comment validation

- app/labor/email_logic.rb
- spec/labor/email_logic_spec.rb
I am working on breaking up the SendEmailDigestWorker into individual workers for each user Digest bc the looping through all users is taking hours. Prior to that being ready, this is a small optimization that will save us some time if that long-running job restarts in the middle of its run. **This assumes we would never want to send more than 1 digest email in a day which seems pretty reasonable to me.**
> Optimization:Dont Send Multiple Digest Emails in a Day

- app/workers/github_repos/repo_sync_worker.rb
After Running out Sync worker I noticed a bunch of them failed due to `Github::Errors::Unauthorized` errors. I think if we get these errors we should remove the repo.
> Bug Fix:Destroy Repos that We No Longer Have Credentials For

- app/workers/emails/enqueue_digest_worker.rb
- lib/tasks/fetch.rake
We cannot run our EmailDigest jobs in parallel bc it is too much stress on the database. This adds back in the single file rake task for DEV to use until we can figure out an adequate Sidekiq solution.
> Bug Fix:Add send_email_digest Rake Task for DEV

- app/workers/articles/rss_reader_worker.rb
- config/schedule.yml
- spec/workers/articles/rss_reader_worker_spec.rb
Similar to how we did the EmailDigest job recently (#10065) this allows all other Forems to use Sidekiq to manage and kick off their RssReader imports while keeping DEV on the old rake task. I wanted to get this out bc we currently have a lot of Forems running with no way to import RSS feeds. This will allow them to do it and take the time pressure off SRE to figure out a fix for DEV.
https://github.com/orgs/forem/projects/6#card-44508271
> Feature:Add Ability to Run RssReader via Sidekiq Cron, Prevent for DEV

- app/services/email_digest.rb
- spec/services/email_digest_spec.rb
Followup to https://github.com/forem/forem/pull/10065, we need to also ensure the individual workers run inline and are not piling up in Sidekiq since running them in parallel is what is stressing the database.
> Bug Fix:Run Individual Digest Workers inline for DEV

- app/views/admin/events/_event_form.html.erb
The published checkbox on the events admin page was not associated with it's corresponding `<label />` HTML element. I came across this while reviewing. #10015.
Before
After
To test:
- Ensure that you are logged in.
- You need to have the proper roles to access the admin pages.
- If you do not have access to the admin section, run the following in the rails console
```bash
u = User.last # Me
roles = ["single_resource_admin", "super_admin", "trusted", "tech_admin", "config"]
roles.each { |r| u.add_role(r) } # Add all roles above
u.add_role :single_resource_admin, Config # For internal pages
```
- Navigate to http://localhost:3000/admin/events
- If you click on the label Publish beside the publish checkbox, it should check/uncheck the publish checkbox depending on what state it is currently …
> Fixed label not being associated to published checkbox on events admin page.

- app/controllers/comments_controller.rb
- app/models/comment.rb
- spec/models/comment_spec.rb
Deleting notification when the comment is hidden using after_update method
closes https://github.com/forem/forem/issues/9807
The test is already there for this.
> Deleting hidden comment notification using after_update

- app/controllers/sessions_controller.rb
#10052 contained a bug as `cookies.delete(domain: domain)` doesn't delete any cookies as it's missing the name. 
The correct method to call is [cookies.clear(options)](https://github.com/rails/rails/blob/bdd00fb29dd4c1326a4cc8321b35dbf35f40314a/actionpack/lib/action_dispatch/middleware/cookies.rb#L406-L409), hence `cookies.clear(domain: domain)`
#10052
> Fix clearing of all cookies on logout

- db/migrate/20200828045600_remove_group_from_profile_fields.rb
- db/schema.rb
This PR removes the `group` column from `profile_fields` that we started ignoring in #10045 which needs to be merged first.
Part of #6994.
Nothing
> Remove group column from profile_fields

- app/controllers/admin/configs_controller.rb
Added a few cache busts which can help ensure the relevant areas of the site change as soon as config is changed. We could get more granular with this in the future, but config won't change very often, so not a big deal to not have that optimization right now.
`delete_matched` is not currently in our codebase, so I hope it works as expected with Redis. This looks for any caches that match `RELEASE_FOOTPRINT` which are the caches we expect might need to change when we push new code. This is a similar scenario of new content like logos, etc.
> Purge core edge/fragment caches on config update

- app/workers/github_repos/repo_sync_worker.rb
- spec/workers/github_repos/repo_sync_worker_spec.rb
We have some failing `GithubRepos::RepoSyncWorker` due to the following errors. In the even that a user account is suspended or if they no longer have access to a repo we should destroy the repo. 
Fixes: https://app.honeybadger.io/fault/66984/6cb5b7e34a5b6c538664cfd6135f2c97
https://github.com/orgs/forem/projects/6#card-44619717
> Bug Fix:Destroy GithubRepos with Suspended or Blocked Access

- app/controllers/application_controller.rb
- app/controllers/concerns/verify_setup_completed.rb
- app/controllers/registrations_controller.rb
- app/models/site_config.rb
- app/views/devise/registrations/new.html.erb
- app/views/shared/authentication/_email_registration_form.html.erb
- app/views/shared/authentication/_initial_account_wizard.html.erb
- db/seeds.rb
- docs/getting-started/db.md
- spec/rails_helper.rb
- spec/requests/registrations_spec.rb
Gives users the ability to be the first user and automatically become super users and move into start mode.
Now when a new forem is created, it will start with this screen....
(This is just the MVP, and I figured having a cute gif _for now_ is fun)
Also adds new "mode" functionality to seed data and changes default for new forem to "private"... which makes sense as the default I think, especially pre-configuration.
> Allow initial user to sign up and configure app

- app/controllers/pages_controller.rb
- spec/requests/pages_spec.rb
When redirecting to the welcome, challenge and checkin articles, breakman was complaining about a potential open redirect vulnerability due to the fact that the redirect URL comes from a string stored in the database.
This commit silences breakman by explicitly parsing the database article path (via `URI.parse`) and explicitly stating that only the `path` portion of the URI is to be used (== in an unlikely event of an absolute URI pops up from the db record, the user-agent will still be instructed to be redirected to a page under the app's domain).
#3739
1. Visit the `/welcome`, `/checkin` and `/challenge` routes
1. See that the redirect to the correct articles still stands
---
1. Find out what the welcome, checking and challenge articles are (on a Rails console):
```rb
[12] pry(main)> …
```
> Fixes brakeman open redirect warnings on PagesController

- config/sitemap.rb
UPDATE: Not sure when the related PR will be merged so I went ahead and monkey patched the adapter. 
Currently, Sitemap Refresh does not work on Forems' using IAM profiles. In order to get this working, we need to set `fog_public` to false and get [this PR for sitemap_generator](https://github.com/kjvarga/sitemap_generator/pull/359) merged. But what about `use_iam_profile`? [By default `use_iam_profile` gets set to true when AWS access key and secret are missing](https://github.com/kjvarga/sitemap_generator/blob/0b847f1e7a544ea8ef87bb643a732e30a07a14c9/lib/sitemap_generator/adapters/s3_adapter.rb#L39) but I figured it would help to be more explicit 
In order to test this setup, I copy and pasted the updated `SitemapGenerator::S3Adapter` code into a Forem.dev console and was able to …
> Bug Fix:Update Sitemap Generator to Handle IAM Profiles

- app/views/admin/users/_negative_reactions.html.erb
Today, @ludwiczakpawel shipped some Admin UI changes that affect `/admin/users/:id/edit`. I also shipped some changes to `/admin/users/:id/edit` around the same time, so the UI changes that were made did not apply to my work. This PR applies the UI changes to the "Recent Reactions" section and updates it to use the Crayons styling to keep things consistent.
Relates to PR #10059 and to PR #10015 
- To QA this PR, first make sure that you have `super_admin` privileges and then navigate to `/admin/users/:id/edit`:
- Finally, ensure that the updated "Recent Reactions" UI matches the rest of the page's UI, specifically the "Remove Identity" and "Destructive Actions" toggle styling:
N/A
> Updates "Recent Reactions" UI to Match Admin UI Changes

- .env_sample
- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- app/views/shared/authentication/_email_registration_form.html.erb
- spec/requests/registrations_spec.rb
This adds an extra field to require brand new forems to pass in a value generated by systems stack to ensure a publicly generated forem can't be coopted if someone has the URL.
> Add logic for asking for FOREM_OWNER_SECRET to be present on first user sign up if set by system

- config/sitemap.rb
- lib/sitemap_generator/s3_adapter.rb
Turns out this [config file is explicitly and evaluated when running a sitemap refresh](https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/interpreter.rb#L78). The problem with this is then when we try to initialize the monkey patched class, we end up with this error
```
Traceback (most recent call last):
3: from (irb):34
2: from (irb):35:in `rescue in irb_binding'
1: from config/sitemap.rb:67:in `run'
NameError (uninitialized constant #<Class:0x00007f251b188e08>::SitemapGenerator::Sitemap)
```
This PR moves the monkey patched code out of the config to fix this problem. I was able to uncomment out the `Rails.env.production?` statement and recreate the error locally. I was then able to move the code into the lib directory, fire up a new console and validate that …
> Bug Fix:Monkey Patch Sitemap Generator in lib not Config

- config/initializers/carrierwave.rb
We don't have any cache-control configuration in place for uploaded images to S3. We need to have it in place or else nginx won't cache image from s3.
https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3
QA on production!
n/a, but ideally at somepoint we update all the images on our s3 to have a cache-control
> Add cache-control to CarrierWave when using S3

- spec/services/search/reaction_spec.rb
I know exactly what the problem is with this spec, it has to do with how we are storing this ID field in Elasticsearch making accurately sorting by it not really possible. The fix for it is a bigger PR but in the meantime I dont want this to be a blocker for anyone.
> Comment out Flaky Reaction Search Sort Spec

- app/controllers/dashboards_controller.rb
This one is purely to make CodeClimate/brakeman happy as the code that was already there is equivalent (as the parameter being `constantize`'d was validated before the reflection part kicked in).
I've switch things around and do a lookup on the `UserSubscription::ALLOWED_TYPES` for the subscription `source_type`, which makes brakeman understand that type comes from an allowed list of types (instead the user input).
#3739
Guarantee that no regression was introduced (the code is indeed equivalent):
1. The `requests/dashboard_spec.rb` covers these scenarios
---
1. Visit: http://localhost:3000/dashboard/subscriptions?source_type=Article&source_id=1
1. See that the page loads the subscriptions of the correct article
---
1. Visit: http://localhost:3000/dashboard/subscriptions?source_type=Comment …
> Fixes unsafe reflection warning in dashboards_controller

- app/controllers/application_controller.rb
- app/views/articles/_sidebar_additional.html.erb
- app/views/articles/_sidebar_nav.html.erb
- app/views/articles/tag_index.html.erb
- app/views/devise/registrations/_registration_form.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_nav_menu.html.erb
- app/views/layouts/_signup_modal.html.erb
- app/views/layouts/_top_bar.html.erb
- app/views/pages/badges.html.erb
- app/views/partnerships/show.html.erb
- app/views/shared/authentication/_providers_sidebar.html.erb
- app/views/shared/authentication/_providers_signup_modal.html.erb
- app/views/stories/_sign_in_invitation.html.erb
Now that we have multiple paths, here's a scenario where we have different paths for sign in vs sign up...
This creates two different states for more distinct options... Also moved all the non-path-helpers for `/enter` and moved them to the Railsier way.
> Add multiple /entry page options

- app/views/layouts/_signup_modal.html.erb
This PR fixes an issue where signup modal was not visible blocking rest of the page when user scrolled down a little..
- Closes #10101 
- Closes #10122
> Signup modal fix

- app/models/article.rb
- db/migrate/20200901084210_add_unique_index_to_articles_slug_user_id.rb
- db/schema.rb
In an effort to unpack https://github.com/forem/forem/pull/8072 I'm going to start with the easy part: adding a unique index to two columns that have no duplicates in the table:
- `slug` + `user_id` to make sure that slugs are indeed unique per index, not just at the Rails level but also at the DB level
Currently there are no duplicates: https://dev.to/admin/blazer/queries/78-duplicate-articles-by-slug-and-user_id
https://github.com/forem/forem/pull/8072
> Add unique index on articles slug user_id

- app/controllers/admin/users_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/services/moderator/delete_user.rb
- app/views/admin/users/edit.html.erb
- app/views/users/_account.html.erb
- spec/requests/admin/users_manage_spec.rb
- spec/requests/user/user_settings_spec.rb
- spec/services/moderator/delete_user_spec.rb
This removes the ghostify option from the app. We really don't use this feature much, and it's more confusing to use and keep around than to make it worthwhile.
https://github.com/forem/InternalProjectPlanning/issues/31
1. Search for `ghostify` or `ghost` or `Ghostify` in the app
No
> Remove ghostify from app

- app/services/github/errors.rb
- app/workers/github_repos/repo_sync_worker.rb
- spec/services/github/oauth_client_spec.rb
- spec/workers/github_repos/repo_sync_worker_spec.rb
Makes the `RepoSyncWorker` rely on the error types and not their messages, to make the decision of wether to remove the Github repository reference from the database.
#10106
TBH I don't quite know how have a repository reach that state (have an account suspended or a repository deemed "unavailable"), so I wasn't able to do a proper functional test.
I tried to cover the full codepath with tests as an alternative. But beware, I'm missing a proper functional test.
> Rely on error types to determine when a repo should be removed on the RepoSyncWorker

- app/lib/honeycomb/noise_cancelling_sampler.rb
- spec/lib/honeycomb/noise_cancelling_sampler_spec.rb
We hit our monthly Honeycomb data limit on August 31st which means we need to rein it in a little bit. This PR increases our rate throttling for our noisiest and least informative events. cc @lizthegrey 
https://github.com/orgs/forem/projects/6#card-44710845
> Optimization:Throttle Noisy Honeycomb Events More

- spec/system/articles/user_creates_an_article_spec.rb
There are two ways this spec can fail
1. It took too long to load Runkit content
2. the article was never saved because it was invalid.
This fix scenario two. I've received the following error multiple times. You can see that the body_markdown has two sets of frontmatter. This looks like the markdown was not properly replaced so added a redundency to make sure the markdown is cleared. I ran this spec locally 50x to verify that this solves this.
n/a
> Fix Flaky Runkit system spec

- spec/labor/article_suggester_spec.rb
In our `ArticleSuggester` class we will offset the articles we find by some random number that is calculated using `estimated_count` for articles. Since the estimated count uses postgres statistics from `pg_class` I am wondering if sometimes it comes back with a higher value than expected. This stubs the estimated count for the real count for the class. 
```ruby
QUERY_ESTIMATED_COUNT = <<~SQL.squish.freeze
SELECT (
(reltuples / GREATEST(relpages, 1)) *
(pg_relation_size(?) / (GREATEST(current_setting('block_size')::integer, 1)))
)::bigint AS count
FROM pg_class
WHERE relname = ? AND relkind = 'r';
SQL
``` 
Fixes (hopefully):
```
1) ArticleSuggester returns proper number of articles with post with the same tags
Failure/Error: expect(described_class.new(article).articles.size).to eq(4) …
```
> Flaky Spec Fix:(Attempt)Ensure Article Suggester Count is Consistent

- app/services/profile_fields/import_from_csv.rb
- lib/data_update_scripts/20200901040521_create_profile_fields.rb
- spec/lib/data_update_scripts/create_profile_fields_spec.rb
When we added profile fields to DEV in https://github.com/forem/forem/pull/9724 we should also have added them for all other existing communities via a data update script, as they have to go through the same migration process. Alas, that slipped through the cracks in the original PR. This wasn't much of a problem so far, as the sync/backfilling code relied on a hardcoded field list. This will change when merging #9912, so we need to ensure all existing communities have the necessary profile fields in place.
A data update script seems like the best way to ensure all current communities get the fields. Once we are completely done with this migration we can turn the script into a no-op by commenting out the `run` method, as previously discussed with Molly …
> Add data update script for profile fields

- config/initializers/devise.rb
Currently in production (Forem.dev and MMALife) Facebook login fails with the error: `Could not authenticate you from Facebook because "Invalid credentials".` Based on guidance from https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview, this PR adds a parsing option to the OmniAuth-Facebook setup in an attempt to fix this error.
(Of course this error doesn't occur in development...grr)
https://github.com/forem/forem/pull/9922
> Attempt to fix facebook login

- app/controllers/admin/application_controller.rb
- app/controllers/admin/display_ads_controller.rb
- app/dashboards/dashboard_manifest.rb
- app/lib/constants/role.rb
- app/models/display_ad.rb
- app/views/admin/display_ads/_form.html.erb
- app/views/admin/display_ads/edit.html.erb
- app/views/admin/display_ads/index.html.erb
- app/views/admin/display_ads/new.html.erb
- config/routes.rb
- spec/requests/admin/display_ads_spec.rb
Extracts Display Ads dashboard from `/resource_admin` (Administrate) into `/admin` dashboard
CRUD capabilities to manage Display Ads should be available in `/admin/display_ads`
N/A
> Extracts DisplayAds from Administrate into admin

- app/mailers/digest_mailer.rb
- app/services/email_digest_article_collector.rb
- app/views/mailers/digest_mailer/digest_email.html.erb
- app/workers/emails/send_user_digest_worker.rb
- spec/services/email_digest_article_collector_spec.rb
- spec/workers/emails/send_user_digest_worker_spec.rb
Few improvements here to the Digest Mailer
- rather than `limit(8)` then only taking the `first(6)` in the mailer, lets just make it `limit(6)`
- Articles are big models with a lot of data, we only need title, description, and path in order to populate the body of the email so limit the columns to those. 
- Replace Redis lookup `@user.cached_following_users_ids` with reading a user attribute `@user.following_users_count`
- Replace Postgres db email hits with user attributes: `@user.follows.size` with `@user.following_users_count` and `@user.articles.published` with `@user.articles_count`. Now `follows.size` includes tags but the messaging in the email is for following users so I figured the replacement made sense using the users count.
- Refactor: replaced `published: true` with our …
> Optimization:Select Article Columns for Digest Email, Limit 6, Use User Attributes

- app/serializers/search/reaction_serializer.rb
- config/elasticsearch/mappings/reactions.json
- lib/data_update_scripts/20200415200651_index_reading_list_reactions.rb
- lib/data_update_scripts/20200901194251_reindex_reading_list_reactions.rb
- spec/lib/data_update_scripts/reindex_reading_list_reactions_spec.rb
- spec/serializers/search/reaction_serializer_spec.rb
We store reactions in Elasticsearch and the default way we sort them is by ID desc which will give us the most recent reactions first. HOWEVER, this is not quite the case. IDs are stored in Elasticsearch as strings which means when you are doing a value comparison you end up with weird behavior such as 99 > 100. The means Reactions are not being sorted correctly all the time. This PR introduces `created_at` to Elasticsearch for reactions. Once this is merged and the data is backfilled I will then issue a PR to default sort by `created_at` 
https://github.com/orgs/forem/projects/6#card-44644200
- pull down branch
- run bin/setup
- open a console
- `Reaction.readinglist.last.elasticsearch_doc` should return a document with `created_at` in it
> Index Reaction created_at Timestamp

- app/labor/sticky_article_collection.rb
- app/views/articles/_sticky_nav.html.erb
To pair with #10167, this is on the theme of using the tools at our disposal to avoid extra allocation. Article show pages get a lot of traffic and allocate a lot of extra memory by including users in this query when we don't need them due to our cached user optimization. 😊
The other PR might require more discussion, this one should be more obvious.
> Remove unneeded eager load

- app/controllers/admin/profile_fields_controller.rb
- app/views/admin/profile_fields/_grouped_profile_fields.html.erb
- app/views/admin/profile_fields/_profile_field_form.html.erb
- app/views/admin/profile_fields/index.html.erb
This simply adds two fields display_area & show_in_onboarding to the profile setup ui, and allows them to be updated. 
Part of #6994
1. Go to http://localhost:3000/admin/profile_fields
2. You should see display_area as a select & show_in_onboarding as a checkbox
3. You can update them
> Add display_area & show_in_onboarding to the profile setup ui

- app/labor/sticky_article_collection.rb
- app/views/articles/_sticky_nav.html.erb
After merging this PR we've seen a slow down in requests. #10168
Which makes _zero_ sense to me because the affects of this optimization should be very minimal one way or another as they are behind the fragment cache and generally minimal either way... 
But I figured I'd toss this reversal up unless there's another explanation about activity going on which would cause slower response times.
.... In looking more closely at this code, there are some much bigger optimizations that could be made here either way, but I don't know if this is actually something affecting responses or a coincidence.
> Revert removal of unneeded eager load (if needed)

- app/controllers/profile_field_groups_controller.rb
- app/models/profile_field_group.rb
- app/views/profile_field_groups/index.json.jbuilder
- config/routes.rb
- spec/factories/profile_fields.rb
- spec/models/profile_field_group_spec.rb
- spec/requests/profile_field_groups_request_spec.rb
This PR adds a controller for profile field groups to be used during onboarding. To make the controller more versatile (i.e. for re-use on the new profile page) the filtering is optional (controlled via `?onboarding=true`.
Part of #6994 
1. Make sure you have some profile fields where `show_in_onboarding` is set to `true`.
2. Make a request and ensure you that you get a response, e.g.
```
{
"profile_field_groups": [
{
"description": null,
"id": 11,
"name": "Basic",
"profile_fields": [
[snipped]
}
```
3. Make a request for only retrieving onboarding fields. This should return only a subset of the previous request (unless all your fields are marked as onboarding fields):
```
$ http --print=b :3000/profile_field_groups onboarding==true
{
"profile_field_groups": [
{
"description": null,
"id": …
```
> Add ProfileFieldGroupsController to API

- app/assets/stylesheets/notifications.scss
Fixing vertical alignment of post title in notification
closes https://github.com/forem/forem/issues/10182
1. Go to dev.to/notifications
2. Look for notification with post title
> Vertical alignment of post title in notification

- app/views/service_worker/index.js.erb
Conditions for `/internal` and `/forem` redirects were not added to the serviceworkers file, so these redirects were not working, this pr fixes this problem.
Open `/internal` page, it should redirect to `/admin/articles`.
`/forem` should redirect to `/devteam/for-empowering-community-2k6h`
> Fixed new redirects

- app/controllers/omniauth_callbacks_controller.rb
- app/controllers/sessions_controller.rb
TLDR; we have cases of double cookies that have the same name but differ on domain, regardless on the value of `SameSite` (both were changed at the same time). 
This hotfix should work both for those who can't login and those who can't logout
#9967 
Cross fingers and hope for the best 🤞
> Session cookie domain hotfix for login and logout

- config/initializers/content_security_policy.rb
#10144 added a CSP but the website is too big to be able to encompass all cases ahead of time. I've seen violations related to Pusher and to inline images in the chat for example. Also, the Blazer admin page index is not working for me.
For this reason I propose we use a different approach: enable CSP in report only mode.
This will help us track violations without blocking content, we keep an eye on the rules that need fixing/expanding and then when we have close to no violations we can switch off the reporting mode and keep the report URI for whatever we might have missed.
The alternative is to turn off report only mode but keep the report URI and then keep changing the CSP in the following days until we get close to zero.
We just can't rely on our own browser's console.
I'm using …
> Enable CSP in report only mode and use Honeybadger to track violations

- db/migrate/20200902204028_add_user_id_mailer_index_to_ahoy_messages.rb
- db/schema.rb
In our `EmailDigestArticleCollector` we look up a user's most recent ahoy messages to help us determine if we should be sending them a Digest Email. 
```ruby
@last_user_emails ||= @user.email_messages.where(mailer: "DigestMailer#digest_email").limit(10)
```
The average for the lookup time for this query is almost 2 seconds, with it being closer to 10 when the database is under higher load. This should help speed things up a bit. 
https://github.com/orgs/forem/projects/6#card-44508249
> Optimization:Add Index for User ID and Mailer to Ahoy Messages

- app/controllers/admin/users_controller.rb
- app/models/feedback_message.rb
- app/views/admin/users/_reports.html.erb
- app/views/admin/users/edit.html.erb
This PR adds a "Recent Reports" section to a User's Admin User page (`/admin/users/:id/edit`). The reports section displays a User's most recent `FeedbackMessages` with useful data (`user_types`, `category`, `status`, `created_at`, and `message`). By adding this data to the User's Admin User page, Admins now have the ability to more easily view which reports that a User has and any related detail for the reports, like if the User was Affected, the Offender, the Reporter, or all of the above, allowing Admins to refer back to this data if need be. Additionally, when a report is clicked on, the Admin will be brought to the `/admin/reports/:id`, where they will find the relevant report, giving them more context as to why the report was made in the first place. 
Relates to a private issue and …
> Add Recent Reports to Users' Admin User Page

- app/services/search/query_builders/reaction.rb
- spec/services/search/reaction_spec.rb
We store reactions in Elasticsearch and the default way we sort them is by ID desc which will give us the most recent reactions first. HOWEVER, this is not quite the case. IDs are stored in Elasticsearch as strings which means when you are doing a value comparison you end up with weird behavior such as 99 > 100. The means Reactions are not being sorted correctly all the time. This PR switches from using the ID to sort reactions to created_at
https://github.com/orgs/forem/projects/6#card-44644200
> Bug Fix:Sort Reactions by created_at

- app/controllers/omniauth_callbacks_controller.rb
- app/controllers/sessions_controller.rb
A continuation on https://github.com/forem/forem/pull/10169. As mentioned in that PR, we weren't entirely sure if this was going to work. We had @lisasy test this out on production and we _suspect_ that when signing in with SSO, the cookie might be being deleted too late, so this PR moves it up higher in the `OmniauthCallbacksController#callback_for`.
I also updated the current `NOTE` to a `TODO` with a specific date when we should remove this temporary code :)  
Please see https://github.com/forem/forem/pull/10169 for more context!
Not really possible to test this unless you are in production _and_ if you have the double cookie instance 🙃 
Need to have @lisasy test this out on production once it has been deployed.
> Move deletion of legacy cookie higher in omniauth callback

- app/services/email_digest_article_collector.rb
Only select the columns we need from Ahoy Messages when loading them to check about sending digest emails.
> Optimization:Select Only Necessary Columns from Ahoy Messages For Digest Emails

- app/views/dashboards/following_tags.html.erb
Strip any HTML tags from the following lists tags `short_summary`
Closes #10154 
**Before:**
**After:**
_without the dark mode switch 😅_
There are some inconsistencies with the content of `short_summary`, some are using markdown (Rails) and others are using HTML (JavaScript).
> Strip HTML from following list tags short_summary

- config/routes.rb
- docs/backend/internationalization.md
- docs/backend/readme.md
- spec/routing/all_routes_spec.rb
- spec/routing/i18n_routes_spec.rb
This PR is starting to lay the groundwork to support i18n and viewing Forem in various languages. This introduces the routing structure we want to use in the app by nesting all routes under an optional scope `/locale/:locale` or `/locale/fr-ca`. This will allow routes such as `/locale/fr-ca/username`. As we build on i18n, this is how users will access Forem in various languages (such as French Canadian).
Setting this up as a "sub-folder" enables us to better approach SEO, caching, and server-side code in the future. We are doing it as `/locale/fr-ca/` as opposed to the more widely recognized `/fr/ca` approach to give ourselves more flexibility on how we want to handle future changes. Our routing is also complicated with several clashing top-level, dynamic domains.
The loose gameplan here …
> Add routes for i18n

- app/labor/sticky_article_collection.rb
Limit columns returned for all the sticky nav articles.
> Optimization:Limit Column Select for Sticky Nav Articles

- app/controllers/profiles_controller.rb
- config/routes.rb
- spec/requests/profiles_request_spec.rb
This PR adds a simple `ProfilesController` which uses the service object added in #9912 to separate profile from user updates.
Part of #6994.
> Add profiles controller

- lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
- lib/data_update_scripts/20200904141057_cleanup_articles_with_invalid_feed_source_url.rb
- spec/lib/data_update_scripts/cleanup_articles_with_invalid_feed_source_url_spec.rb
- spec/lib/data_update_scripts/remove_draft_articles_with_duplicate_feed_source_url_spec.rb
Similar to https://github.com/forem/forem/pull/10138 but based on `feed_source_url`.
To be able to close the loop on #8072 and add a unique index on feed_source_url we need first to be remove duplicates that have the same feed_source_url.
This PR contains scripts to accomplish the following things:
1. remove all drafts that in a partition have the same body. A partition is determined as a group of articles with the same feed source URL
2. remove all drafts that in a partition have different bodies by keeping the most recent one. A partition is determined as a group of articles with the same feed source URL
3. fixes invalid data for `feed_source_url`. Currently, unlike with `canonical_url`, we don't have a URL validator on the field, thus I found a bunch of invalid URLs in production data, …
> Remove draft articles with duplicate feed source URL and cleanup invalid data

- app/models/article.rb
- db/migrate/20200902132326_add_unique_index_to_articles_canonical_url.rb
- db/schema.rb
- spec/models/article_spec.rb
Adding the unique index on articles `canonical_url`.
This is in conflict with https://github.com/forem/forem/pull/9788
Thus we need to decide which of these two options:
1. `canonical_url` has to be unique across all articles (drafts and published)
2. `canonical_url` has to be unique only within the scope of published articles (thus this index needs to add `published` in its column list)
I'm not 100% sure what we want here so I though we'd start with this drarft PR
ps. this should be deployed right after https://github.com/forem/forem/pull/10138 - possibly closely after to avoid further duplicates ;)
cc @mstruve @citizen428 due to, respectively, https://github.com/forem/forem/pull/9788#pullrequestreview-472925409 and https://github.com/forem/forem/pull/9788#discussion_r480880463
- …
> Add unique index on articles canonical_url

- spec/lib/data_update_scripts/create_profile_fields_spec.rb
It seems `spec/lib/data_update_scripts/create_profile_fields_spec.rb` is flaky at times. We'll eventually comment out the data update script and this spec, so for now, I wasn't sure if the script has been run on all environments yet, so I decided to  add some manual cleanup steps to the spec.
Part of #10006 
> Fix DataUpdateScripts::CreateProfileFields spec

- spec/requests/admin/profile_field_groups_spec.rb
After merging #10235 another spec seems to consistently fail on master. This PR changes it from making an assertion on an absolute number to use the `change` matcher instead.
n/a
> Fix profile admin spec

- app/controllers/liquid_tags_controller.rb
- config/routes.rb
- spec/requests/liquid_tags_request_spec.rb
This PR adds an internal API controller for receiving a list of our custom Liquid tags. This can then be used by the frontend to display a typeahead liquid tag dropdown in new editor.
#872
It's pretty much all covered by the specs.
> Add LiquidTagsController

- lib/tasks/fastly.rake
In the event of a Fastly outage we need to be able to skip this config update step to allow deploys to happen.
> Feature:Add ENV to Skip Fastly Config Update

- app/javascript/article-form/components/ArticleCoverImage.jsx
- app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
Fixes an issue where Safari fails to upload a cover image in the editor.
#10145
To test:
1. Use the Safari browser
1. Ensure you are logged in.
1. Navigate to http://localhost:3000/new
1. Drag and drop a cover image on the cover image area of the editor
1. The cover image gets uploaded.
1. Ensure it still works in Firefox and Chrome (Edge Chromium) by repeating the steps above.
> Fixed issue with drag and drop image for cover image in editor in Safari

- app/assets/stylesheets/footer.scss
This PR fixes a bug where on small resolutions on article view, the action bar was overlapping footer's content.
- Closes #9362 
- Closes #9751
> Actions bar overlapping footer

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
Only some fragment caches make use of this method...... But it's a starter towards accounting for fragment caches across different locales.
This doesn't account for all fragments (and some we can't just change without thinking through the deployment concerns of cold hits), but this one change should be pretty harmless and let us account for at least this scenario for now.
Let me know what you think.
> Include locale in fragment cache key

- app/services/search/base.rb
- app/services/search/cluster.rb
- app/services/search/feed_content.rb
- app/services/search/reaction.rb
- app/services/search/user.rb
- spec/services/search/base_spec.rb
- spec/services/search/cluster_spec.rb
On 9/3 we had some of our "Slow Elasticsearch Query" alerts go off indicating that Elasticsearch response times were increasing. When I looked further into the issue I noticed that the leading spike came from indexing requests and we did have an increase in indexing at the time. 
Another thing I noticed when digging into the Elasticsearch stats was that our refresh time had also spiked during this time. [By default, Elasticsearch will refresh an index every second](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_unset_or_increase_the_refresh_interval). Refreshing an index takes a considerable amount of resources which can cause indexing to slow down. To alleviate this pressure, if you don't need near-realtime searching then increasing the …
> Optimization:Increase refresh_interval For Possible High Indexing Indexes

- app/controllers/admin/configs_controller.rb
- spec/requests/admin/configs_spec.rb
We had a prior functionality which is meant to delete the core fragment caches that change on every deployment, or in this case, when we update config and want a fresher cache.
This updates it to work as intended (and also tacked on another page purge)...
The original PR did not break anything, but did not appropriately follow the `delete_matched` functionality which requires wildcards to work properly like this. The included test is a basic regression test, not _directly_ exercise this functionality, but at least adds a bit more coverage.
> Proper cache delete_matched

- app/controllers/search_controller.rb
- app/services/search/query_builders/feed_content.rb
- spec/services/search/feed_content_spec.rb
In order to be able to fetch saved articles from our feed_content index we need the ability to search by an article's ID. This allows us to do that. This will be followed by a frontend PR to hook this all up to the frontend. 
https://github.com/orgs/forem/projects/6#card-45322899
> Feature:Allow for Search by ID for FeedContent

- app/labor/cache_buster.rb
- spec/labor/cache_buster_spec.rb
Currently, we don't have a good way of knowing whether Openresty is available before we try to bust an Nginx cache via Openresty's server.
This means that we can potentially make a request to Openresty even when it is unavailable, which causes the app to not be able to boot up when this code path is called.
This PR adds a check to make sure that Openresty is **both** _configured_ **and** _available_ before trying to bust an Nginx cache or before making additional requests to Openresty. Unfortunately, from what I can tell, the only way to know if Openresty is "up" and available is to ping it (make a request to it). In this PR, I'm making a basic `GET` request to the `openresty_path` to just see if it responds with a success or not.
This PR also improves the pre-existing tests and adds some …
> Check that nginx is available before pinging it

- app/labor/reading_list.rb
- spec/labor/reading_list_spec.rb
While setting up the reading list to be served from the feed content index I noticed this labor class and that it had a couple unused methods so I removed them.
> Refactor:Remove unused ReadingList Labor methods

- app/services/authentication/providers.rb
- config/application.rb
- config/initializers/authentication.rb
Currently login is broken in development mode.
Thanks to @maestromac we found a weird interconnection between Zeitwerk's ([Rails 6 autoloader](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html)) loading order, the expectation that `SiteConfig` is ready when it should be inside `URL.domain` and the fact that `SiteConfig.authentication_providers` depends on the providers to be already loaded at runtime.
The solution is to basically move 
```ruby
Rails.application.config.to_prepare do
Dir[Rails.root.join("app/services/authentication/**/*.rb")].each do |f|
require_dependency(f)
end
end
```
from the initializer to the `Authentication::Providers` file. The reason why we can't simply remove the [to_prepare](https://api.rubyonrails.org/classes/Rails/Railtie/Configuration.html …
> Fix URL.domain in development by correctly loading authentication providers

- app/models/article.rb
- app/serializers/search/article_serializer.rb
- lib/data_update_scripts/20200911045602_reindex_articles_with_videos.rb
- spec/serializers/search/article_serializer_spec.rb
In #10256 I refactored `video_duration_in_minutes`. Since this now no longer relies on `video_duration_in_minutes_integer` it was [suggested to move the latter into the search serializer](https://github.com/forem/forem/pull/10256#discussion_r485383795), since that's the only place where it's used.
While doing so I also realized that the method was wrong. Here's the old definition:
```ruby
(video_duration_in_seconds.to_i / 60) % 60
```
This will be wrong for any duration > 1 hour, because of the modulo operation:
```ruby
duration = (1.hour + 1.minute).to_i # should be 61 minutes
#=> 3660
(duration / 60) % 60 # modulo discards the hours
#=> 1 
```
To go from seconds to minutes we only need to divide by 60, so I removed the modulo.
n/a
Nothing specific
> Move video_duration_in_minutes_integer to serializer

- app/javascript/listings/dashboard/listingRow.jsx
It removes duplicate date formatting code for listing expiry date in listing dashboard
> Removing duplicate date formatting for listing expiry date in listing dashboard

- app/assets/javascripts/initializers/initializeBroadcast.js
- app/javascript/packs/articleForm.jsx
Fixes the issue described in https://github.com/forem/forem/issues/9683, wherein an active announcement broadcast would obfuscate the nav bar on `/connect` routes. Since the chat channel code seems to force scrolling down to the latest message, it made the most sense (in my opinion) to completely hide the announcement bar from view on `/connect` (similar to what we do on the `articleForm` component, aka the `/new` routes).
While doing this, I realized that some of this logic could be cleaned up quite nicely. Previously, we had broadcast-related code in both `initializeBroadcast` _and_ within the `articleForm` component. But it would be nicer to have it all live in one place so that we don't need to keep track of that logic in multiple places.
So, to that end, I refactored the …
> Hide active broadcasts from /connect routes

- app/models/site_config.rb
Though I tried logging in by my GitHub account in my local environment, I found no login button there. So I looked into the code getting authentication providers, and I found that was `authentication_enabled_providers` helper method. Inside of it, `SiteConfig.authentication_providers` is called, and it returned an empty array.
After that, I inspected `SiteConfig.authentication_providers` method, and I found `Authentication::Providers.available` was set to default option. But we should pass Proc to the default option to be made lazy evaluation.
| before | after |
|---|---|
| <img width="664" alt="Screen Shot 2020-09-13 at 19 31 35" src="https://user-images.githubusercontent.com/26132902/93015985-c2f8c800-f5f8-11ea-8f82-cd61871b0900.png"> | <img width="665" alt="Screen Shot 2020-09-13 at 19 …
> Fix SiteConfig's default option of authentication_providers field

- lib/data_update_scripts/20200910135958_remove_draft_articles_with_duplicate_user_id_title_body_markdown.rb
- lib/data_update_scripts/20200910140109_cleanup_published_articles_with_duplicate_user_id_title_body_markdown.rb
This PR contains two scripts
1. the first one deletes duplicate draft articles that have the same combination of `user_id`, `title` and `body_markdown`. The algorithm is the same of https://github.com/forem/forem/pull/10138 and https://github.com/forem/forem/pull/10239
1. the second one "merges" published articles:
- basically we divide the articles in groups (some articles have 1 duplicate, some have more)
- of all the groups we take the first article
- we copy over the data from the others onto this first one
- we destroy the others
This is where the data is:
- https://dev.to/admin/blazer/queries/232-duplicate-draft-articles-body_markdown-user_id-title
- https://dev.to/admin/blazer/queries/235-duplicate-published-articles-body_markdown-user_id-title
- …
> Cleanup articles with duplicate user_id, title and body_markdown

- app/models/site_config.rb
- app/workers/sitemap_refresh_worker.rb
- spec/models/site_config_spec.rb
- spec/workers/sitemap_refresh_worker_spec.rb
I noticed the following in the logs:
```
sidekiq   | Pinging with URL 'http://localhost:3000/sitemap.xml.gz':
sidekiq   | Ping failed for Google: #<OpenURI::HTTPError: 400 Bad Request> (URL http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2Flocalhost%3A3000%2Fsitemap.xml.gz)
sidekiq   |   Successful ping of Bing
sidekiq   | 2020-09-14T07:30:12.751Z pid=87981 tid=18p class=SitemapRefreshWorker jid=76604c54535c07b0e2cf6ef8 elapsed=1.328 INFO: done
```
There's no need to ping the sitemap tools when running locally. I've intentionally named the method `local?` instead of `localhost?` as the concept of local installation might be expanded in the future and not just refer to `localhost` (like private instances inside a company DMZ that are not reachable from outside). For now …
> Stop pinging sitemap tools locally

- app/models/article.rb
- spec/models/article_spec.rb
I noticed when playing around in my local env that this job was getting kicked off every single time we touched an article. Including just to update a comment. Since this is a waste of resources I updated the code to only kick of the job when the main image actually changes.
> Optimization:Only Enqueue UpdateMainImageBackgroundHexWorker If Main Image Changes

- spec/workers/listings/expire_old_listings_worker_spec.rb
I saw this spec be flaky once during a Travis run and when I looked at it I noticed in the expired listing worker we are doing `"expires_at < ?", Time.zone.today` and then in the spec, we set the expired_at to 1.day.ago. I think given time zones there is a point where these might overlap so I increased the expired_at in the spec to 2.days.ago so it is always guaranteed to be less that Time.zone.today
Fixes: 
```
[Zonebie] Setting timezone: ZONEBIE_TZ="International Date Line West"
1) Listings::ExpireOldListingsWorker#perform expires only old listings
Failure/Error: expect(expired_listing.reload.published).to eq(false)
expected: false
got: true
(compared using ==)
Diff:
@@ -1,2 +1,2 @@
-false
+true
```
> Flaky Spec Fix:Set Expired Listing to 2 days ago

- spec/system/user_uses_the_editor_spec.rb
In order to recreate this failure I copied this spec 10 times in its spec file and then ran the file. Each time about half of the duplicate examples would fail. When I jumped into the spec with pry I found that it was not filling in the article content and therefore when we went to save the article we would get a validation error, "Title can't be blank". After a little digging, [I found that we could be more targeted with our form fill_in](https://stackoverflow.com/a/18881133/1438582) so I tried that. With the `within` I was able to run the file with the duplicate specs 3 times and none of them ever failed so I think this is the fix we need. Something to keep in mind if we see this in the future. 
Fixes: 
```
1) Using the editor Submitting an article fill out form and submit …
```
> Flaky Spec Fix:Ensure We Fill In Article Content Successfully with More Targeted tag

- app/workers/html_variants/remove_old_data_worker.rb
`HtmlVariantSuccess` and `HtmlVariantTrial`'s are pretty simple objects that have 0 callbacks or relationships we need to worry about cleaning up when we destroy them. For this reason, rather than using [`destroy_by`](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/destroy_by) which will go through and delete them all 1 by 1 executing all callback, let's switch to using a quick [`delete_by`](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/delete_by) which will delete them all in one SQL statement. 
This will eliminate a lot of spans and speed this puppy up quite a bit
> Optimization:Use delete_by when Destroying HtmlVariant Trials and Successes

- scripts/bundle.sh
I noticed when trying to use Docker with BuildKite that we were downloading and installing all of our gems rather than using our local vendor'ed cache. This updates our container bundle script to use our local gem cache which will save us a bit of time.
> Optimization:Use Locally Bundled Gems in Containers

- app/services/podcasts/get_episode.rb
- app/workers/podcast_episodes/create_worker.rb
- spec/services/podcasts/feed_spec.rb
- spec/services/podcasts/get_episode_spec.rb
- spec/workers/podcast_episodes/create_worker_spec.rb
Take it from someone who has made this mistake before, it is a really bad idea to use large Sidekiq arguments. If you end up enqueueing a ton of jobs it will eat up your Redis resources extremely fast from a memory standpoint and from an I/O standpoint bc of all the polling Sidekiq does against the queues. This PR updates our Podcast::CreateWorker so that we store the large `item_data` hash in Redis and send a hashed key representing it instead as an argument to our worker. The worker then looks up the key in Redis and fetches the item data to send to the CreateEpisode service.
https://github.com/orgs/forem/projects/6#card-43005072
> Optimization:Store Podcast Ep Data in Redis, Rather than Sending as Sidekiq Argument

- app/services/github/oauth_client.rb
Our Github Oauth client uses [Faraday::HttpCache](https://github.com/forem/forem/blob/master/app/services/github/oauth_client.rb#L114) to cache request results which can be served in event of an error. The problem with this is every time we fetch Github repos we add another request to our Redis key AND we reset the expiration back to 24 hours. This can cause the key in Redis to grow uncontrollably. When it gets really large we start to timeout trying to add to it. You can see this problem in the response time Honeycomb graph below. You can also see the time spent writing to Redis in the next image which is of a Honeycomb trace. To prevent this I am removing the cache. 
https://github.com/orgs/forem/projects/6#card-45548773
> Bug Fix/Optimization:Remove HttpCache from Github OauthClient

- app/models/user.rb
- app/serializers/search/user_serializer.rb
- config/elasticsearch/mappings/users.json
- lib/data_update_scripts/20200519142908_re_index_feed_content_and_users_to_elasticsearch.rb
- lib/data_update_scripts/20200914042434_reindex_users_for_profiles.rb
- spec/lib/data_update_scripts/re_index_feed_content_and_users_to_elasticsearch_spec.rb
- spec/serializers/search/user_serializer_spec.rb
This PR is part of the ongoing profile generalization work. It specifically deals with how we index the new profile fields in Elasticsearch:
1. Adds two new [nested fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html), `profile_fields` and `custom_profile_fields` to the users mapping.
2. Updates `Search::UserSerializer` to update the two new fields.
3. Adds a data update script for reindexing users.
These are the first 3 steps described in [our Elasticsearch documentation](https://docs.dev.to/backend/elasticsearch/#how-to-add-a-new-field-to-elasticsearch).
Part of #6994
1. Check out this PR
2. Update your mappings, e.g. with `bin/setup`
3. Index a user, e.g. `user.index_to_elasticsearch_inline`
4. Check that the ES document contains the nested attributes: …
> Changes to profile field indexing

- Containerfile
- container-compose.yml
- docker-compose.yml
- scripts/entrypoint-dev.sh
- scripts/entrypoint.sh
This removes the automatic run of `rake app_initializer:setup` in the entrypoint and adds a way to easily call `rake assets:precompile`. It also moves the old entrypoint.sh to entrypoint-dev.sh so the developer experience with Docker / Podman Compose remains the same.
> Better production container precompiling and bootstrapping

- docs/backend/configuration.md
`Page Not Found!` will be shown if we click any admin page links on [this page](https://docs.dev.to/backend/configuration/).
I fixed it.
> Fix broken links to admin guide in documentation

- app/controllers/search_controller.rb
- app/javascript/readingList/__tests__/readingList.test.jsx
- app/javascript/readingList/components/ItemListItem.jsx
- app/javascript/readingList/components/__tests__/ItemListItem.test.jsx
- app/javascript/searchableItemList/searchableItemList.js
- app/services/search/query_builders/feed_content.rb
- app/services/search/reading_list.rb
- spec/requests/search_spec.rb
- spec/services/search/feed_content_spec.rb
- spec/services/search/reading_list_spec.rb
The reactions index is really just a glorified FeedContent index with a couple more bits of information for reading list reactions. Rather than doubling up on data in Elasticsearch lets make use of the FeedContent index instead and cut out the reaction index. Following merging this we can remove the reaction index(by far our biggest index in Elasticsearch) and we no longer will need to index reactions. 
Bug Fix: Ensure paging works for the reading list. 
https://github.com/orgs/forem/projects/6#card-45322899
Fire up the app and check that all the reading list functionality still works.
> Feature: Serve Reading List from FeedContent Index

- app/labor/hex_comparer.rb
- spec/labor/hex_comparer_spec.rb
As requested by @ludwiczakpawel, this PR adds an opacity method to `HexComparer` which turns a hex color into an RGBA value:
```ruby
HexComparer.new(['#123456']).opacity(0.5)
#=> "rgba(18, 52, 86, 0.50)"
```
Following the lead of `brightness`, this uses the smallest of the hex values if more than one was provided. Maybe we should rethink if this class really is a `HexComparor` or if we should call it something else, e.g. `ColorTools`. In the meantime I just refactored the code a bit.
Your friendly neighborhood Slack request.
Nothing special, you can play arouind with it in a Rails console to make sure it behaves as expected.
> Add opacity to HexComparer

- app/controllers/concerns/verify_setup_completed.rb
- spec/system/admin/admin_manages_configuration_spec.rb
Added information about missing fields for admins when the setup is not completed
> More detailed notification when setup is not completed

- config/initializers/initialization_cachebust.rb
- config/initializers/set_release_footprint.rb
- lib/tasks/app_initializer.rake
- lib/tasks/cache.rake
It is not ideal to talk to an external service in order to bust caches while initializing the application code. This moves that cache-busting out of the app initializer and into a background job that is kicked off by our app_initializer script which runs after the app code is loaded.
https://github.com/orgs/forem/projects/6#card-45328906
> Optimization:Move Initialization CacheBust to Background Worker

- app/labor/markdown_fixer.rb
- spec/labor/markdown_fixer_spec.rb
This fixes a bug where articles that are using front matter (also known as v1 articles or basic markdown articles) with `Published: true` will fail to publish. This is because the `published` attribute is case sensitive in the `front_matter_parser` gem we use, and therefore needs to be properly lowercased before sending it to the gem for processing.
1. Go to `localhost:3000/settings/ux` and update your article version to "basic markdown"
2. Click "Write a Post"
3. Try to publish a post with `Published: true`
4. See that it publishes
> Fix case sensitive published bug for basic markdown posts

- app/controllers/concerns/verify_setup_completed.rb
- spec/system/admin/admin_manages_configuration_spec.rb
Follow-up for the #10375 :
- cache `missing_configs` to avoid redundant iteration
- improve notification text
> Improve setup not completed notification

- app/assets/stylesheets/chat.scss
- app/javascript/chat/compose.jsx
connect text input auto grow with the content. There was one PR already but that was not working & no update from last few months. So That's why I took this feature. 
#8842
##
> Bug: auto resize on type message connect

- app/assets/stylesheets/views/article-form.scss
- app/assets/stylesheets/views/article.scss
We've been using `position: sticky` here and there and it looks like we can improve browser support for this feature. By adding -webkit vendor prefix we can cover a bit larger audience now. 
Not sure if this is something that used to work before and now doesn't but if that's correct then potential cause could be related to either:
- some changes to autoprefixing couple weeks ago (cc @nickytonline )
- new version of Safari being released few days ago.
Closes #10286
> Better `position: sticky` support

- config/initializers/omniauth.rb
- spec/support/omniauth_helpers.rb
- spec/system/authentication/user_logs_in_with_facebook_spec.rb
- spec/system/authentication/user_logs_in_with_github_spec.rb
The reason Facebook Authentication provider hasn't been working was due to a mismatch in the redirect URL sent in the OAuth process. 
This PR explicitly adds to the Omniauth initializer so it will rely on `URL.url` to build the redirect URL for callbacks.
fixes #10200 and #10102
All authentication providers in the local development should continue to work as expected. This is a recording of the Facebook authentication working in https://thismmalife.com
https://share.getcloudapp.com/WnuJLJq2
Visual representation of the debugging process (aka rabbit hole):
> Sets Omniauth full_host config to match the environment

- config/initializers/omniauth.rb
- spec/system/authentication/omniauth_redirect_uri_spec.rb
When `SiteConfig.app_domain` is updated in a existing (running) environment we don't get the correct `redirect_uri` generated for OAuth providers. This happens not because we rely on `ApplicationConfig["APP_DOMAIN"]` (since we use `URL.url` for this) but instead because the `full_host` Omniauth config is set in the initializer and it doesn't change if we update `SiteConfig.app_domain` unless we reboot (not what we want).
The fix consists of making `Omniauth.config.full_host` use a Proc instead of a String generated at boot time so the generated value will always use the up-to-date `SiteConfig.app_domain`
1. Boot the app locally and login with any OAuth provider (successfully)
1. Sign out (otherwise after executing the next step you'll be unable t logout bc of cookie domain settings)
1. …
> Fixes Omniauth redirect_uri when SiteConfig.app_domain is updated

- app/controllers/application_controller.rb
We need to be able to hit the health check API with only the health check token and no additional authentication. This allows us to do that for private forems
> Bug Fix:Count the Health Checks Controller as Public

- app/liquid_tags/gist_tag.rb
- spec/liquid_tags/gist_tag_spec.rb
Better error message when user does not provide link to the Gist in liquid tag
closes https://github.com/forem/forem/issues/10410
> Handling empty gist link error in liquid tag

- app/assets/javascripts/initializers/runtime.js
This bug was introduced at some point in the refactor that added the `Runtime` helper class. It will never be true that the user agent will match the regex AND that it will be empty 😅
Playing a podcast locally should continue to work as usual on a browser.
If navigating from the DEV Native iOS app and you start playing a Podcast you'll see that the native audio playback is not being executed (lock the screen and the enhanced controls don't appear). This happens because this check returns `false` (when it should return `true`) and this PR fixes it.
> User agent check fix for native iOS

- app/javascript/actionsPanel/__tests__/initializeActionsPanelToggle.test.js
- app/javascript/actionsPanel/initializeActionsPanelToggle.js
- app/views/moderations/actions_panel.html.erb
Hides close button in moderator view
closes https://github.com/forem/forem/issues/10265
> Removing close button from right panel in moderation view

- app/services/images/optimizer.rb
- config/initializers/imgproxy.rb
- spec/services/images/optimizer_spec.rb
- spec/views/dashboards/show.html.erb_spec.rb
Instead of dedicating an endpoint env var for Imgproxy, we will always default to `/images` to the domain of the Forem instance it belongs to. The also change how we check if Imgproxy should be enabled; now it will check for both KEY and SALT instead of KEY and Endpoint.
https://github.com/orgs/forem/projects/11#card-44712228
This does not change any existing behavior and only applicable on production.
n/a
> Update Imgproxy to use predetermined endpoint

- lib/data_update_scripts/20200917150808_nullify_orphaned_tags_by_mod_chat_channel_id.rb
- lib/data_update_scripts/20200917150838_nullify_orphaned_feedback_messages_by_reporter_id.rb
Prior to add foreign keys to the following 8 columns - https://dev.to/admin/blazer/queries/246-orphan-rows-2 - we need to cleanup some of them.
This PR nullifies invalid `tags.mod_chat_channel_id` and `feedback_messages.reporter_id`
> Cleanup orphan data from tags and feedback_messages

- app/lib/reverse_markdown/converters/custom_text.rb
- config/initializers/reverse_markdown.rb
- spec/lib/reverse_markdown/converters/custom_text_spec.rb
The CustomText converter was monkey patched to fix a bug related to
preserve_tags. Somewhere in that process, remove_inner_newlines was
changed to strip newlines completely, instead of replacing them with a
single space. This restores that functionality.
In development mode, files are not eager loaded. That means that the
converters were not being required, so it was not possible to reproduce
that issue in development mode (since it was falling back to the
original converter, which does not have the bug). This commit also adds
an initializer that requires every converter.
This fixes half of #8457.
> Fix newlines being chomped in RSS import

- app/liquid_tags/link_tag.rb
- spec/lib/liquid/raw_spec.rb
- spec/liquid_tags/link_tag_spec.rb
Shows error message when user uses links from different domain in **link** liquid tag
closes https://github.com/forem/forem/issues/10096
1. Go to comment section in article
2. Paste the comment 
```
{% link https://www.freecodecamp.org/news/ultimate-dynamodb-2020-cheatsheet/ %}
```
3. Click preview it should that link is not valid article link
> Handling links from different domain

- app/controllers/listings_controller.rb
- spec/requests/listings_spec.rb
This refactors `listings#update` to avoid doing a redirect causing a race condition when busting cache. An alternative approach here is to create a listings "show" page/action to render to avoid issuing queries to populate the necessary data for `index`. I'm open to that as well if folks prefer that option!
https://github.com/forem/forem/issues/10338
1. Fire up the app locally and sign in.
2. Add credits to your user if you don't have any already. You can do this in a console by running `Credit.add_to(user, 1_000)` where `user` is the `User` object of your signed-in user.
3. Create a listing.
4. Update the listing - you shouldn't see any errors and you'll see it render the index view as it did before this change.
> Remove redirect for listings#update

- app/services/edge_cache/bust.rb
- spec/labor/cache_buster_spec.rb
- spec/services/edge_cache/bust_spec.rb
When we updated this code to bust the cached paths we went from returning the cache bust response to returning the object we were using to do the busting. This PR adds the cache bust response to that object so we can view it which can be very helpful if you have to manually bust stuff and want to confirm that it was successful or not. Let me know what you all think! 
https://github.com/orgs/forem/projects/6#card-45783449
> Return Cache Bust Response When Busting a Cached Path

- app/services/edge_cache/bust.rb
- app/services/edge_cache/bust/fastly.rb
- app/services/edge_cache/bust/nginx.rb
- spec/services/edge_cache/bust_spec.rb
Back in https://github.com/forem/forem/pull/10369, @citizen428 suggested [the great idea](https://github.com/forem/forem/pull/10369#discussion_r490772050) of splitting up the `EdgeCache::Bust` service into two provider-specific classes:
> What if we made providers their own classes, e.g. `EdgeCache::Bust::Fastly` ... which expose a single `call(path)` class method? This could greatly simplify the local `call` method.
This PR rolls with that suggestion and splits up that service into those classes. Everything should work as expected/as it did before, but now, Fastly-specific logic lives in the `EdgeCache::Bust::Fastly` class, while Nginx-specific logic lives in the `EdgeCache::Bust::Nginx` class! 🙌 
```bash
CacheBuster.bust(some-path-here)
=> #<EdgeCache::Service:0x00007fd6ce30aff0 …
```
> Split EdgeCache::Bust into Fastly + Nginx-specific classes

- db/migrate/20201001154006_remove_superfluous_indexes_from_notifications.rb
- db/schema.rb
We have quite a few indexes in the DB and some of them are overlapping. With the help of the [Removing Extraneous Indexes](https://github.com/gregnavis/active_record_doctor#removing-extraneous-indexes) and `EXPLAIN ANALYZE` I confirmed we can remove a few indexes. I'm going to start with likely two biggest ones, on `notifications`:
```text
index_notifications_on_organization_id (can be handled by index_notifications_on_org_notifiable_action_is_null, index_notifications_on_org_notifiable_and_action_not_null)
index_notifications_on_user_id (can be handled by index_notifications_on_user_notifiable_action_is_null, index_notifications_on_user_notifiable_and_action_not_null, index_notifications_user_id_organization_id_notifiable_action)
```
this is the output from the tool.
These two indexes …
> Remove superfluous indexes on notifications

- app/views/service_worker/index.js.erb
We have a bunch of path we are not running through service worker. This refactor makes this process a bit more manageable. I also added `/i/` and `/uploads` to the exception list.
Resolves https://github.com/forem/InternalProjectPlanning/issues/54
1. Start the app locally and make sure to refresh a few time for the new service worker to kick in.
2. Navigate to any user and try to view a User's profile picture
3. You should be able to see the profile image just fine.
You should _not_ be seeing something like this
n/a
> Refactor: Extract app-shell unsupported paths

- app/queries/admin/moderators_query.rb
- app/views/admin/mods/index.html.erb
- spec/queries/admin/moderators_query_spec.rb
- spec/requests/admin/mods_spec.rb
I think that the issue (#10060) is self-explanatory. What was happening with @msarit was that she was visiting the `/admin/mods?state=tag_moderator` without having a role named `tag_moderator` on the database.
The query class explicitly "blew up" in this condition. I tried to follow the approach proposed by @Zhao-Andy:
1. The query class now doesn't raise an exception in the scenario above. Instead returns an empty result set
1. The mods page now returns a generic "there are mods matching your search" warning if there are no mods matching the query
#10060 
1. Go to the `/admin/mods` page
1. Search by a random text string which yields no results and see that a "no results" message is rendered
1. Delete the `tag_moderator` role from your database (`Role.find_by(name: …
> Fixes 500 error when viewing the "Tag Mods" page without having the role on the database

- spec/system/user/view_user_index_spec.rb
Couple issues I noticed in this spec while working with it in docker.
1) Sometimes I would get invalid user errors bc of the repeated username. Not sure why that would happen with transactions but this ensures that it never will bc the factory will set a unique username for us.
2) Let Factory for article set a unique title instead of us setting it and risking a duplicate.
> Spec Fix:Dont Reuse Same Username and Let Factory Set Title

- app/assets/javascripts/initializers/initializeVideoPlayback.js
I'm not sure it 100% closes #6067 because the issue refers to a user setting for video autoplay.
The general consensus, for the moment, was to simply disable autoplay.
The `autostart` value was removed since [it defaults to false](https://developer.jwplayer.com/jwplayer/docs/jw8-javascript-api-reference#section-jwplayer-set-config), and the `play()` on `ready` was also removed.
#6067 
* Load up any article with a native video
* Verify that it doesn't autoplay
> Disable autoplay on native videos

- app/services/slack/messengers/user_deleted.rb
- app/workers/users/delete_worker.rb
- spec/services/slack/messengers/user_deleted_spec.rb
- spec/workers/users/delete_worker_spec.rb
Send a slack notification to remind to delete gdpr data when a user deletes their account.
https://github.com/forem/forem/projects/31#card-45606967
- self delete the user
- see if a relevant slack message appeared in the #user-deleted slack channel
> Slack notification with reminder to delete user gdpr data

- app/controllers/chat_channel_memberships_controller.rb
- app/models/message.rb
- spec/models/message_spec.rb
- spec/requests/chat_channel_memberships_spec.rb
I find that notifications when people leave a channel, especially big group channels like CodeNewbie are super noisy and not helpful. This would skip sending push notifications for any "removed_from_channel" actions. What do you all think?
> Optimization:Dont Notify of Channel Leavings

- app/controllers/admin/listing_categories_controller.rb
- app/lib/constants/role.rb
- app/models/listing_category.rb
- app/views/admin/listing_categories/_form.html.erb
- app/views/admin/listing_categories/edit.html.erb
- app/views/admin/listing_categories/index.html.erb
- app/views/admin/listing_categories/new.html.erb
- app/views/admin/listings/index.html.erb
- config/routes.rb
- spec/requests/admin/listings_catogires_spec.rb
It adds ability to add/update/remove listing categories in admin panel
closes https://github.com/forem/forem/issues/10481
https://vimeo.com/463735841/dfe6705dab
> Manage listing categories in dashboard

- db/migrate/20200918200231_remove_columns_from_articles.rb
- db/schema.rb
- lib/data_update_scripts/20200916202343_backfill_co_author_ids_for_articles.rb
This PR removes the `second_user_id` and `third_user_id` columns from the Articles table in favor of the newly added `co_author_ids` column.
Related to PR #10339
To QA these changes, please ensure that all checks pass. ✅ 
All post-deployment tasks related to `second_user_id`, `third_user_id`, and `co_author_ids` were taken care of the in the `data_update` script in the previous PR, #10339.
> Removes second_user_id and third_user_id From the Articles Table

- app/assets/stylesheets/base/typography.scss
Currently, the link color for the `code` element within articles is very similar to the color for normal `code` elements, making it hard to distinguish what is a link and what isn't. My solution is to remove the style that defines `code` links, so that it falls back to default color for links.
Fixes #9603
**Before**
**After**
Make an article with the following content:
```
<a href="https://www.php.net/manual/en/function.system.php"><code>system()</code></a>
<code>system()</code>
[`My Example`](https://example.com/)
```
First and third elements should have the blue link color (or whatever `--link-brand-color` var is set to)
The second element should be black color (assuming `--color-body-color` was not changed by the tester)
**edit:** Additional test case:
putting this in an article:
``` …
```
> Remove code link style so it uses the default link color

- app/assets/javascripts/initializers/initializeBaseUserData.js
- app/views/comments/_form.html.erb
This removes `current_user` from the inline HTML because this area is cached and will not work with `current_user` because it will stay in the HTML for the next visitor. This is a hot fix.
> [HOT FIX] Fix current_user cache issue in comments

- spec/labor/markdown_parser_spec.rb
- spec/liquid_tags/link_tag_spec.rb
- spec/liquid_tags/liquid_tag_base_spec.rb
- spec/services/github/oauth_client_spec.rb
- spec/workers/search/index_worker_spec.rb
- spec/workers/search/remove_from_index_worker_spec.rb
A few of our specs used expectation of the form `expect {}.not_to raise_error(<specific error>)`. This is discouraged by RSpec and results in the following warning:
```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`.
```
In the interest of making our codebase more robust, I changed all these instances to the `expect {}.not_to raise_error` form as suggested by the warning.
n/a
n/a
> Don't use "not_to raise_error" with specific class

- app/helpers/articles_helper.rb
- app/liquid_tags/twitch_tag.rb
- app/views/articles/_fitvids.html.erb
- app/views/liquids/_twitch.html.erb
- app/views/pages/_editor_guide_text.html.erb
- app/views/pages/_editor_liquid_help.html.erb
- app/views/pages/markdown_basics.html.erb
- docs/frontend/liquid-tags.md
- spec/liquid_tags/twitch_tag_spec.rb
resolves #10475 
[Twitch Documentation on Embeds](https://dev.twitch.tv/docs/embed/video-and-clips#non-interactive-iframes-for-clips)
[Dev.To docs on Liquid Tags](https://docs.forem.com/frontend/liquid-tags/)
> Add twitch liquid tags

- app/assets/stylesheets/chat.scss
Was going through old issues, bumped into https://github.com/forem/forem/issues/2165, can't find any mention of CodeMirror around the code anymore, except for this CSS class.
🪓 
#2165
> Removed unused CodeMirror CSS class

- db/seeds.rb
- docs/getting-started/db.md
Currently when a developer/contributor sets up a new development environment, they have to manually create an admin user. This adds significant friction and a learning curve for a new contributor to start testing Forem locally. In addition, developers using cloud based IDEs such as GitPod or GitHub Codespaces will have to do this setup ever time a new space is spun up.
This PR adds a default admin user with the email address 'admin@forem.local' to the seed data.
> Add default admin to seeds file

- app/controllers/admin/configs_controller.rb
- app/lib/constants/site_config.rb
- app/models/article.rb
- app/models/comment.rb
- app/models/reaction.rb
- app/models/site_config.rb
- app/services/notifications/new_comment/send.rb
- app/views/admin/configs/show.html.erb
- app/views/admin/feedback_messages/_abuse_reports.html.erb
- spec/models/article_spec.rb
- spec/models/comment_spec.rb
- spec/requests/admin/configs_spec.rb
- spec/services/notifications/new_comment/send_spec.rb
This adds the ability for admins to modify a list of terms which may indicate spam. But unlike past "quiet" spam indicators, this automatically creates a vomit reaction which an admin can later manually reverse or at least be aware of. In the past we have modified spam-related scores but it hasn't really worked effectively into our workflows. I think this reversible action should be how we raise spam automatically in general.
With comments I decided to limit it to newer accounts because we're examining _the whole comment_ and not just the title. But this can be modified over time. If a support admin is seeing false positives with a term they should consider removing those. We can alter the logic over time to ensure as few false-positive scenarios as possible.
> Add ability for admin to add anti-spam terms

- app/javascript/utilities/connect/getUnopenedChannels.jsx
If you have dev.to open in multiple tabs and you send a message in a chat channel you will get an unread notification in the other tabs for your own message.  This PR fixes that by simply exiting from the `receiveNewMessage` callback early if the message received is your own (same user id).
Possible related refactoring: the `receiveNewMessage` function already had a few checks that I think were supposed to solve this exact issue but didn't.  We may be able to adjust or remove them completely but I would want someone who is more familiar with this feature (preact & pusher) to look at it first and make sure I'm not messing something else up.
```javascript
receiveNewMessage = (e) => {
if (
(window.location.pathname.startsWith('/connect') &&
e.user_id === window.currentUser.id && …
```
> Return if receive own message

- app/views/feedback_messages/_form.html.erb
`feedback_message.message` is required on backend validation but not set as required on view https://github.com/forem/forem/blob/0ca4e8b3719995450cec0542ef50268b9bbc3e5c/spec/models/feedback_message_spec.rb#L19
> feedback_message.message is required on backend but not required on view

- app/controllers/admin/configs_controller.rb
- app/controllers/concerns/verify_setup_completed.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- app/views/mailers/digest_mailer/digest_email.html.erb
- app/views/mailers/notify_mailer/trusted_role_email.html.erb
- app/views/mailers/notify_mailer/trusted_role_email.text.erb
- spec/requests/admin/configs_spec.rb
- spec/system/admin/admin_manages_configuration_spec.rb
As part of the Creator Onboarding project, we are removing fields from the SiteConfig that are too DEV-specific and/or that we don't want all Forem creators to have to fill out when they set up a new Forem instance.
Since `community_action` isn't used in too many places (and is currently fairly pretty DEV-specific), we think that it makes more sense to drop this field and update the few instances of where it is used in emails instead.
Fixes https://github.com/forem/InternalProjectPlanning/issues/89.
Since we are just dropping this field, we shouldn't need to take any major action here.
> Remove community_action from SiteConfig

- app/models/article.rb
- app/models/comment.rb
- app/models/reaction.rb
- spec/models/article_spec.rb
- spec/models/comment_spec.rb
This builds on the detection of spam keywords and checks whether that account has at least 3 instances of vomits and automatically suspends them... I figured 3 is decent to not attack false positives too aggressively.
This is a full on "destructive banish", but will inhibit the account's ability to continue creating.
> Auto-suspend multiple-spammers

- app/models/article.rb
- app/models/comment.rb
I realized that the reactions are not getting created as expected _on the first save_ because the ID is not available yet. It's missing silently, and in the tests we're not exercising this effectively. This fixes up the logic.
> Move spam check to after save

- app/controllers/admin/configs_controller.rb
- app/helpers/rate_limit_checker_helper.rb
- app/models/site_config.rb
- app/services/articles/creator.rb
- app/services/rate_limit_checker.rb
- spec/requests/admin/configs_spec.rb
- spec/requests/articles/articles_create_spec.rb
- spec/services/rate_limit_checker_spec.rb
Allows us to treat "newer" users differently when it comes to rate limiting how many articles they can create.
Admins can configure how many articles a 3-day-old user can create within 5 minutes.
N/A
> Limit articles created by newer users

- .env_sample
- app/views/service_worker/index.js.erb
Based on discussions and experience I think _not_ enabling service workers as the default probably makes sense, so that `localhost:3000` does not run the same service workers?
Here is a relevant conversation: https://github.com/forem/forem/issues/10293#issuecomment-691648063
This still makes it easy to have service workers on, but is a pretty straightforward way to turn them off. `ENV` var seems like a decent way to do this, eh?
This still registers service workers, just makes the file empty so no functionality exists. Neither scenario is _perfect_ because either way the user is either dealing with confusion or inconsistency but at least this enables options.
> Skip service workers in development by default

- app/helpers/application_helper.rb
- app/views/admin/configs/show.html.erb
- app/views/onboardings/show.html.erb
- spec/helpers/application_helper_spec.rb
The objective of this change is to remove the random fallback images from onboarding.
Accomplishing that in this way means we won't have to change how this method is being used elsewhere.
Closes https://github.com/forem/InternalProjectPlanning/issues/112
> Remove random onboarding background images

- app/services/articles/feeds/basic.rb
- spec/models/article_spec.rb
- spec/services/articles/feeds/basic_spec.rb
The #10245 pull request's biggest focus was to not break the algo DEV uses, and it did that, but what slipped through the cracks is that the `basic` feed was wrong.
This PR should make things right.
> Fix feed order for basic

- app/services/podcasts/create_episode.rb
- spec/services/podcasts/create_episode_spec.rb
Because we're upserting, and therefore skipping callbacks, the `processed_html` is often not being processed. I imagine there is an efficiency reason we're upserting, so only running this in the `blank?` scenario.
> Ensure podcast episodes are created with processed_html

- config/initializers/carrierwave.rb
Cleaning up `carrierwave.rb` up and Update `config.asset_host` to use `/remoteimages` instead of `/images` when in Forem context.
n/a
n/a
n/a
> Update Carrierwave's asset_host for Forem cloud

- app/assets/stylesheets/components/buttons.scss
- app/javascript/article-form/components/ImageUploader.jsx
In the "Write a post" editor, the "Upload Image" button is skipped while tabbing i.e. while navigating with a keyboard, making it inaccessible to keyboard users. This happens due to the tabindex of -1 set on the "Upload Image" input element. Removing it enables tabbing, thus solving the issue.
Resolves #10521 (second part of the issue) 
[This](https://webaim.org/techniques/keyboard/tabindex) article talks more about how a tabindex of -1 on HTML elements that need to be interacted with, makes them inaccessible to keyboard users
> Remove tabindex of -1 on upload image input in the write a post editor

- app/controllers/admin/configs_controller.rb
- app/controllers/feedback_messages_controller.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- app/views/feedback_messages/_form.html.erb
- spec/requests/admin/configs_spec.rb
- spec/requests/feedback_messages_spec.rb
This adds Google ReCAPTCHA keys into `SiteConfig`, so that Forem admins are able to add ReCAPTCHA without having to go through the `.env` file.
1. Visit /admin/config
2. Find the Google ReCAPTCHA field
3. Update the field to anything
4. Verify that it updated
No
> Add recaptcha keys to as site-configurable keys

- docs/technical-overview/architecture.md
I added a small section in this area of the docs to share some information about collections/ series. 
There is not much information in the documentation about collections or series and I felt like this would be beneficial to others looking to help with the Series feature of the website.
https://github.com/forem/forem/issues/9658
_I am working on updating the series, but when I went through the docs, I didn't find any information on Series which is why I wanted to add this first._
No
> Add Section for Series/Collections

- app/services/images/optimizer.rb
- config/initializers/imgproxy.rb
We cannot set `Imgproxy.config.endpoint = URL.url("/images")` in the initializer because it will use the hardcoded `ApplicationConfig["APP_DOMAIN"]` instead of `SiteConfig.app_domain`. Instead, I have to move it closer to the surface, where the App (mainly `URL` module) is completely booted.
n/a
- Makes sure the app boots correctly.
- For a thorough imgproxy setup guide, please see https://github.com/forem/forem/pull/9909
n/a
> Move Imgproxy endpoint config to Images::Optimizer

- app/assets/stylesheets/components/buttons.scss
- app/views/devise/registrations/new.html.erb
- app/views/shared/authentication/_providers_registration_form.html.erb
- spec/requests/registrations_spec.rb
Adds a button to the existing `Create Account` page allowing users to create a Forem account with an email and password if the corresponding option has been enabled in the admin console. (Text on the existing login options button has been adjusted to reflect different log in versus account creation states as well).
closes https://github.com/forem/InternalProjectPlanning/issues/99
> Link Email Account creation UI to existing Create Account UI

- app/assets/stylesheets/components/cards.scss
Add word-break to crayons-card this will allow words to be broken if the word is too long but will wrap normally otherwise.
closes: #10629
N/A
> Long text goes outside cards

- spec/requests/users_onboarding_spec.rb
While I was working on debugging a forem bug, I noticed that there was an extra `sign_in` in the `users_onboarding_spec.rb` -- this PR removes it.
N/A
Ensure that the Travis build is green. 🟢 
N/A
> Remove Superfluous `sign_in` From `users_onboarding_spec.rb`

- app/liquid_tags/glitch_tag.rb
- spec/liquid_tags/glitch_tag_spec.rb
~This PR improved the regex that is used to validate the glitch id to allow ids starting with `~`.~
This PR improves the `parse_id` method to remove any prefixed `~` before passing it to the template. 
resolves #10427
Create a new blog post, add `{% glitch ~the-super-tiny-compiler %}` and save -> no validation error should appear.
> Allow glitch id starting with ~

- app/models/profile.rb
- app/models/site_config.rb
- app/services/moderator/banish_user.rb
- app/views/users/_profile.html.erb
- spec/models/site_config_spec.rb
Various small changes related to profile generalization.
1. Automatically set up profile attributes on app boot, this time (hopefully) without breaking `bin/setup` (tested locally, works fine).
2. Add `SiteConfig.dev_to?` analogous to `SiteConfig.local?`. This will be used for cases where we don't want DEV to lose a certain feature but don't want to or can't expose it to other communities (see [The path from DEV to Forem](https://forem.dev/citizen428/the-path-from-dev-to-forem-543e))
3. Update `BanishUser#remove_profile_info` to clear profile info via the profile model.
Related to #6994
Nothing much to test here.
> Profile generalization tidbits

- app/assets/stylesheets/components/syntax.scss
Adds styling for `.highlight` to `<pre>` inside `<li>`. I checked out the [`Rouge/redcarpet` plugin file](https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/plugins/redcarpet.rb) which indicates that the `.highlight` class should be applied to all code-blocks by default since DEV is using the default version too. I felt it would be a simpler fix via the CSS Route instead of configuring a custom renderer, which might lead to more bugs.
I did basic testing with the following article piece, to ensure that behavior for other elements didn't get switched:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eget nunc sed dolor molestie eleifend. Nulla ut ante ultricies quam accumsan commodo.
```yml
- name: Get a dad-joke
run: |
echo "::set-env name=TEMP::$(curl -H "Accept: …
> Fix overflow of indented code-blocks in lists

- app/models/user.rb
This finishes the work from #10732 and #10750, removing the `ignored_colums` statement from the `User` model.
n/a
Nothing
> Remove ignored columns from User

- app/lib/constants/mastodon.rb
I added https://im-in.space, a Mastodon instance, to the list of allowed instances.
#7981 
NA
> Add im-in.space Mastodon instance

- spec/system/articles/user_edits_an_article_spec.rb
I noticed this spec failing on some contributor's builds. When I tried to run it locally I also found it failing with the same issue. It appears that the additional template was getting appended to the text field causing the parsing to be incorrect when saved. This change ensures the field is cleared before the new template is applied. I am not sure what causes this in some instances and not in others but this fixed it for me locally.
Fixes:
```
1) Editing with an editor user unpublishes their post
Failure/Error: expect(page).to have_text("Unpublished Post.")
expected to find text "Unpublished Post." in "Write a post\nSetup not completed yet, missing main social image, logo png, logo svg, and others. Please visit the configuration page.\nHeart\n0\nUnicorn\n0\nSaved\n0\nMore...\nSample …
```
> Flaky Spec Fix:Clear Article Content Before Filling In

- app/views/service_worker/index.js.erb
This functionality _naively_ checks for which paths to skip over for service workers. The reason it can be pretty naive is that it is not that big a deal if it's a little too aggressive. Occasionally skipping service workers is fine.
But one problem is that `https://forem.dev` _includes `/forem`........ Which is a problem because it _always_ skipped over and did nothing. This changes the code to check only path, which is what it should have been before.
There is definitely still a need to make this more precise, but for now this solves this particular defect.
> Ensure serviceworker bypass only checks path

- app/assets/stylesheets/components/header.scss
- app/views/admin/configs/show.html.erb
The DEV SVG logo was being resized to 20% height and width on the actual uploaded SVG (and not within the codebase). This allows logo's that are of similar size to work really nicely within our site's header. However, when other forems try to paste an SVG in the config that have huge heights and widths, it causes the header to have a meltdown 😅 See [this issue](https://github.com/forem/InternalProjectPlanning/issues/53) for examples of the meltdown 😊
Hence, I've added some css to allow the header to always accommodate the SVG irrespective of the size that of the SVG that was pasted. In addition, I've also made the site config logo svg preview use the same html/css that is being used on the header to allow a more accurate representation. …
> SVG logo image re-sizing

- app/controllers/admin/configs_controller.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- spec/requests/admin/configs_spec.rb
Currently the AWS video encoder key we use to encode videos is linked to a single user in our database. This should not be the case since this value is used for the entire application. This moves the encoder value to SiteConfig so that it can easily be set by the site admin. Once this is merged then I will update the VideoStatesController to use the new SiteConfig value rather than the individual user's secret. 
As far as I know @leewynne is the only other Forem using this feature. I will be sure to followup with him on getting this key setup properly on his Forem. 
https://github.com/orgs/forem/projects/6#card-46047741
> Feature:Add Video States Encoder Key to SiteConfig

- app/controllers/concerns/caching_headers.rb
- spec/requests/stories_index_spec.rb
Currently if you use a "private" Forem, the ability to peak into internal pages could be spoofed, because the way we differentiate at the edge is not meant for data that needs to remain private. Privacy on DEV is currently reserved for pages which don't add edge cache headers, but our "high traffic public pages" all have heavy caching....
In order to perform caching _within_ private communities we will either want a solution for something akin to Action Caching in place where edge caching would otherwise be, because this kind of caching can happen _after_ authentication. There may also be ways we could do auth _within_ nginx in a clever way in the future, but that path is less obvious to me.
Either way, this PR makes the tradeoff to enable _truly_ private Forems now while we figure out …
> Skip edge caching for private forems

- app/controllers/listings_controller.rb
- spec/requests/listings_spec.rb
The JSON for listings on the listing dashboard page is missing the category key which causes an `undefined` in the delete listing URL. This PR adds the category key in the JSON.
Fixes #10800
**Before**
**After**
> Fix missing category in delete draft listing URL

- spec/services/articles/feeds/basic_spec.rb
In #10831 I commented this spec out because it was not properly testing the basic feed class. This adds 2 tests to deal with the 2 scenarios a Basic Feed class may encounter, with and without a user. Each scenario orders the articles slightly differently which I made sure to account for. I also included the `"does not include low quality"` assertion in both specs so you get more bang for your buck out of them. 
https://github.com/orgs/forem/projects/6#card-47296483
> Add Specs for Basic Feed Class

- app/views/shared/authentication/_providers_registration_form.html.erb
When you try and create an account via email, the UI is broken. The email svg is not getting rendered as html but rather as a string.
https://github.com/forem/InternalProjectPlanning/issues/142
Go to http://localhost:3000/enter?state=new-user, and you should see a fixed version:
> Fix ui for signup with email 

- app/lib/constants/site_config.rb
- app/models/site_config.rb
- spec/requests/registrations_spec.rb
Closes https://github.com/forem/InternalProjectPlanning/issues/91
Technically regardless of registration mechanism, the _default_ for logging in should be to allow this, because even someone who has signed up with social or invitation can _technically_ log in. If a forem wants to disable that for any reason they could do so.
At least for now I think this makes sense.
> Make allow email password login default true

- app/views/admin/configs/_form_submission.html.erb
- app/views/admin/configs/show.html.erb
Every time when we would save a SiteConfig we would update every single config whether or not it actually got changed. This led to 20+ second response times and thousands of unnecessary hits to our databases which you can see in the Honeycomb trace screenshot below. To fix this I split each section into its own form so we only update those values in each section instead of every single one. The view could likely be refactored further and we could get more technical about what is actually changing during updates but this seemed like a quick easy way to get better performance from this endpoint. 
I am also a fan of only updating sections bc I think it ensures that something doesn't get edited and forgotten about and then accidentally changed when other changes are meant to be saved. …
> Optimization:Break up SiteConfig Updates by Groups

- app/assets/javascripts/.eslintrc.js
- babel.config.js
- bin/generate-css-utility-classes-docs.js
- config/webpack/custom.js
- config/webpack/development.js
- config/webpack/environment.js
- config/webpack/loaders/erb.js
- config/webpack/production.js
- config/webpack/test.js
- jest.config.js
It replaces eslint statement ```/* globals process module */ ```  with ```/* eslint-env node */``` and also fixes eslint errors in file missing it
> Replacing globals with node env

- lib/data_update_scripts/20201014184856_resave_users_for_imgproxy.rb
We need to resave users to bust their image cache in order for a proper transition to Imgproxy.
Should've been part of https://github.com/forem/forem/pull/10819
n/a
n/a
> Resave users for Imgproxy migration

- app/assets/stylesheets/admin.scss
- app/helpers/application_helper.rb
While QAing one of @mstruve's [recent PRs to the SiteConfig view](https://github.com/forem/forem/pull/10851#pullrequestreview-508699494), I noticed a regression. This regression was caused by a [different PR](https://github.com/forem/forem/pull/10694), which deprecated old button styling (opting instead for the crayons versions of buttons).
However, in the SiteConfig view, the button styling looked pretty odd and almost missable:
I updated the crayons class used here to be something more obvious:
This is a very close match to what we had in the site config view earlier:
...except that we use a crayons class here now 🖍️ 😄 .
I _also_ added some padding to make sure that the bottom of the button doesn't touch the `<input>`.
Please see [my original …
> Fix required button styling in SiteConfig

- app/assets/javascripts/utilities/buildArticleHTML.js
- app/assets/stylesheets/components/stories.scss
- app/javascript/articles/Article.jsx
- app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
- app/javascript/articles/components/ContentTitle.jsx
- app/javascript/articles/components/TagList.jsx
- app/views/articles/_single_story.html.erb
This PR does 2 things:
1. Remove the Flare Tag from the post title.
2. Moves the flare tag to the first position within the list of tags and highlights it.
Closes #10523
> Remove flare tag from title and hightlight it within the tags row

- app/assets/images/sustaining-membership.svg
- app/views/events/index.html.erb
Let's rewind the clock a few years..... DEV decides to put on live online events as a component of a membership program designed to deliver community value and help develop out a component of the business model.
Despite a good deal success, the overhead of the initiative proves a little much given we're also building out the technical platform and we are radically under-resourced.
Fast forward a few years, we're now rolling out Forems, and this feature we never fully said goodbye to is intriguing to several Forem creators— for good reason. Events make up a good deal of what "community" can be. It's also a feature social platforms like Facebook normalized as a component of the overall experience. DEV itself is now back to putting on events and could use this feature IMO.
We said goodbye to …
> Begin cleaning up and generalizing events

- app/controllers/video_states_controller.rb
- spec/requests/video_states_update_spec.rb
This PR updates the VideoStatesController to use the SiteConfig video_encoder_key value to allow for video processing rather than a single user's secret.
cc @leewynne this is coming down the pipe! Make sure you have this secret set 😃 
https://github.com/orgs/forem/projects/6#card-46047741
> Refactor/Feature:Use SiteConfig video_encoder_key For Processing Videos

- app/queries/admin/moderators_query.rb
- app/views/admin/mods/index.html.erb
- app/views/mailers/notify_mailer/trusted_role_email.html.erb
- app/views/mailers/notify_mailer/trusted_role_email.text.erb
- spec/queries/admin/moderators_query_spec.rb
This changes the language from "community mod" to "trusted" to align with the language we use _in the role_.... So rather than have the role called `trusted` but the email and on-site information mostly speak about "community moderation", we'd rather centralize on these being "trusted" users... They can still _do_ community moderation, but the name of the role and how it is introduced can centralize around `trusted`....
This also removes `banned` users from the query for users to "potentially" make trusted. We do not want to accidentally "entrust" a banned user.
Closes #10734
> Centralize on "trusted" language: Add new copy and some slight feature adjustments.

- spec/system/user/view_user_index_spec.rb
Let me know what you think of using methods and assertions this way with aggregate failures. I noticed we are not doing anything in the individual assertions beyond just looking for different content on the page. To avoid reloading the entire page each time, I combined the assertions into a single one. This took the spec run time from around 6.5 seconds to around 3.5 seconds(excluding about 8 second load time for files). Not a giant win, but if people like it, I think this is a pattern we could repeat for other specs to speed them up. 
While running this spec I just found a flaky component to it where the date asserted and the date shown down match due to straddling a date. Adding Timecop fixes this issue. 
Fixes: 
```
1) User index when user is unauthorized when 1 article shows all …
```
> Optimization/Flaky Fix:Combine Spec Assertions and Use Timecop for Datetime Assertion

- app/controllers/organizations_controller.rb
- app/controllers/users_controller.rb
- app/lib/constants/settings.rb
- app/models/user.rb
- app/views/users/edit.html.erb
- spec/views/users/settings_spec.rb
While working on `User` during profile generalization I noticed the method `settings_tab_list` which returns a constant array. I removed the method, added a constant and changed the code accordingly.
n/a
Nothing specific, the tests should pass and you should still be able to interact with the settings tabs in the app.
> Move settings tabs to constant

- app/views/admin/configs/show.html.erb
- app/views/admin/tags/show.html.erb
This PR makes color pickers in the admin actual color fields instead of text inputs, similar to how we do it on the settings page.
Closes #10872 
This could certainly be prettier, but it's internal, so probably good enough for now. I noticed that there's currently some styling work going on in the admin area anyway, so someone more qualified than me can add the ✨
> User color fields in admin

- docs/faqs.md
Adds `rails dbconsole` to open up database terminal, and explains why it is a better alternative.
Fixes #10843
> Add rails dbconsole

- app/services/rss_reader/assembler.rb
A certain RSS feed is missing feed URL. This technically makes the feed invalid but we should dampen down the error that it's producing.
Resolves https://app.honeybadger.io/fault/66984/41f0215fe0636317d1c0c8b651c0fb42
the test should just pass really.
n/a
> Make feed_url nullable in RssReader

- app/controllers/admin/configs_controller.rb
- spec/requests/admin/configs_spec.rb
PR https://github.com/forem/forem/pull/10812 attempted to fix a longstanding bug that prevents admins from turning off all third party authentication providers. While this worked, it introduced another bug: setting admin config options in any section **other** than the Authentication section would result in all authentication providers being unselected.
Not exactly what we were going for.
PR https://github.com/forem/forem/pull/10758 enabled an 'invite only' mode for forums, which goes a long way towards mitaging the UI issue PR https://github.com/forem/forem/pull/10812 was trying to fix. As a result, I'm submitting this revert.
(There have been significant changes to `app/controllers/admin/configs_controller.rb` since the original PR was merged, so automatic revert via GitHub isn't an …
> Revert "Allow all third party auth providers to be deactivated" 

- app/controllers/resource_admin/users_controller.rb
- app/dashboards/user_dashboard.rb
This is a bit of a temp fix to help admins get out of a jam if they have an invitation for a user with a certain email and need to unblock it for them to register another way.
It's overall reasonable that an admin could do this and override the typical devise settings.
> Allow admins to change user email to fix email edge cases

- app/javascript/onboarding/components/EmailPreferencesForm.jsx
- app/javascript/onboarding/components/__tests__/EmailPreferencesForm.test.jsx
- db/migrate/20201019012200_change_email_preference_default_values.rb
- db/schema.rb
- spec/factories/users.rb
- spec/labor/mailchimp_bot_spec.rb
- spec/requests/incoming_webhooks/mailchimp/unsubscribe_spec.rb
#9876  What type of PR is this? (check all applicable)
I recently noticed a potential GDPR issue in our onboarding flow: the email preference checkboxes should be deselected by default, see[ GDPR Recital 32](https://gdpr-info.eu/recitals/no-32/):
> Consent should be given by a clear affirmative act […] Silence, pre-ticked boxes or inactivity should not therefore constitute consent.
This PR updates the `EmailPreferencesForm` component used during the onboarding flow and also changes the DB-level default value for these two columns from `true` to `false` so we have consistent behavior no matter how an account is created.
Closes https://github.com/forem/InternalProjectPlanning/issues/176
Go through the onboarding flow and verify that the following two checkboxes are unchecked by default:
> Uncheck email preferences by default

- app/lib/middleware/time_zone_setter.rb
- config/environments/test.rb
- spec/rails_helper.rb
Using middleware here we set the timezone for our browser requests from the ENV variable "TZ" rather than the default server timezone. This ensures that the timezone in our browser matches the random timezone set by [zonebie](https://github.com/alindeman/zonebie) which is a gem we use to randomize timezones in our specs to ensure we don't end up with Timezone bugs. 
Fixes this failure and possibly a few others we have seen pop up. 
```
Failures:
1) User index when user is unauthorized when 1 article shows all proper elements
Failure/Error: expect(page).to have_selector(".comment-date", text: comment_date)
expected to find visible css ".comment-date" with text "Oct 17" within #<Capybara::Node::Element tag="div" path="/HTML/BODY[1]/DIV[7]/DIV[2]/DIV[2]/DIV[2]/DIV[2]/DIV[3]/A[1]/DIV[1]"> but …
```
> Flaky Spec Fix:Set TimeZone For All Spec Requests to Match Zonebie

- app/assets/stylesheets/views/footer.scss
- app/views/articles/_sidebar_nav.html.erb
- app/views/layouts/_footer.html.erb
- spec/requests/stories_index_spec.rb
In [another PR](https://github.com/forem/forem/pull/10754) we added a NavigationLinks Table and made all the links on the sidebar dynamic, such that an admin can configure what links they want to show on http://localhost:3000/admin/navigation_links and it will appear on the sidebar. 
We now applying that same workflow to the footer and rendering the items from the NavigationLinks Table instead of hardcoding them. 
_Note: I've had to amend use grids more dynamically and make the template render in a dynamic way. This means that we were not able to group the links in the same manner_
https://github.com/forem/InternalProjectPlanning/projects/5#card-47436154
**Hardcoded Links:** 
**Dynamic Links:**
> Make the footer links dynamic

- spec/system/comments/user_views_a_comment_spec.rb
Here we do not want to be hardcoding our Timestamp and then assuming the displayed date. The reason for this is because that timestamp, depending on our randomly chosen timezone from Zonbie, might actually be a different day which causes this spec to fail. This ensures that we check for the timestamp generated in the random timezone set in our specs. 
Fixes: 
```
1) Viewing a comment when showing the date shows the readable publish date
Failure/Error: expect(page).to have_selector(".comment-date time", text: "Mar 4")
expected to find visible css ".comment-date time" with text "Mar 4" but there were no matches. Also found "Mar 3", which matched the selector but not all filters. 
[Screenshot]: /home/travis/build/forem/forem/tmp/screenshots/failures_r_spec_example_groups_viewing_a_comment_whe …
```
> Flaky Spec Fix:Don't Hard Code Comment Date

- app/controllers/async_info_controller.rb
- app/controllers/reading_list_items_controller.rb
- app/models/user.rb
- db/migrate/20201017160628_add_last_reacted_at_to_user.rb
- db/schema.rb
- spec/requests/reading_list_items_spec.rb
Same as #10763 but without the default for the column which locked up our database for 20+ min. `last_reacted_at` should be fine being nil.
> Fix Reading List Counter Without last_reacted_at Default

- spec/system/articles/user_visits_an_article_spec.rb
- spec/system/comments/user_views_a_comment_spec.rb
- spec/system/homepage/user_visits_homepage_articles_spec.rb
Rather than relying on hard-coded dates in our specs which will sometimes not match our views due to random timezones, I updated those specs to either use fluid dates or to ensure the hardcoded dates are read and parsed correctly for the given timezone.  Honestly, for the first 2 specs I removed the hardcoded dates since they were done incorrectly.  When I got to the final spec, I realized the hard coded date was being "set correctly" but not asserted on correctly so I left it and only updated the assertions.
> Flaky Spec Fixes:Correctly Assert Dates in Views

- app/views/admin/shared/_navbar.html.erb
Noticed this bug, where multiple links can be highlighted in the admin. This change fixes it and seems safe since we can make some assumptions about the request path.
> Fix weird highlighting bug

- app/controllers/pages_controller.rb
- spec/requests/pages_spec.rb
I've added the contact page to the pages controller so that other forems can override the hardcoded version of teh contact page.  
https://github.com/forem/InternalProjectPlanning/issues/184
Create a Page with slug=contact. Add some html, this should override the default contact page.
> Allow the Pages contact page to override the hardcoded one

- app/controllers/application_controller.rb
- spec/requests/invitations_spec.rb
When a forem is private it intercepts _most_ requests and delivers the auth page..... We have a list of controllers which should not have this functionality, and invitations should be one of them.
> Add invitations controller to Allow List

- app/views/shared/authentication/_email_registration_form.html.erb
- config/fastly/snippets/safe_params_list.vcl
- spec/requests/registrations_spec.rb
This PR adds functionality for creators configuring a new Forem instance to read the `forem_owner_secret` from the querystring parameters if provided.
This will be used soon. We'll be emailing creators a URL to their new Forem that includes the `forem_owner_secret` param so that they don't have to type it in. That will be something along the lines of:
```
Hey, Alex! Your new Forem is ready. Please click this link https://localhost:3000?forem_owner_secret=test to configure your new Forem.
```
N/A
The original functionality still works if `?forem_owner_secret` is not present in the URL:
If the param is found, the form field is rendered as a hidden field with the value updated from the parameter automatically - rendering one less field that's required to be completed 🎉 .
1. Set your local …
> Add forem_owner_secret to params

- app/controllers/application_controller.rb
I'm not totally sure what the best way to test this is, so if anyone wants to merge a test in here or suggest something, be my guest.
This functionality redirects from the originally set app domain to the current one. This should take care of some edge cases when domains change.
> Redirect to SiteConfig.app_domain

- docs/backend/emails.md
- docs/backend/previewing-emails.md
- docs/backend/readme.md
Updates documentation relating to emails. In particular, documents how the mailer views can be overridden, especially for `devise_invitable`.
While working on this, I identified that there aren't mailer previews for `devise_invitable` (#10575).
#9849 
Edit the contents of a mailer view under the given directories, and check the mailer previews to make sure they make sense.
> Document overriding mailer templates

- app/assets/stylesheets/video-player.scss
These new CSS rules override the `overflow-wrap: anywhere` and `word-break: break-word` rules in `.crayons-article__header` and also the `overflow-wrap: anywhere` rule in `.crayons-card`, but only for the JW player part of the DOM.
Closes #10799
Before:
After:
> Avoid CSS word wrap in video player duration

- app/models/site_config.rb
As a Forem admin, video upload does not work so I do not want videos highlighted to my community or have it appear as an option to my members.
**Ideal Solution**
One day, we'll figure out whether or not we can support native video for all Forems but until then, let's:
- remove the 'upload a video' button from /dashboard
**Additional Context:**
We'll want to continue supporting videos on DEV so want to note that the upload button should still exist on DEV.
In this PR I create a config variable to determine whether to enable videos for a Forem. I do not expose it through the config UI since admins don't need control over this at the moment. We simply want to disable it for all Forems except DEV.
Once we deploy this, I'll add an additional check:
```
<% if policy(:video).new? && …
```
> Disable ability to upload videos on *some* forems Part 1

- app/lib/reverse_markdown/converters/custom_pre.rb
- spec/lib/reverse_markdown/converters/custom_pre_spec.rb
I tracked down the issue to the `reverse_markdown` gem and found this unmerged fix: https://github.com/xijo/reverse_markdown/pull/78. Since it seems we are already overriding the `<pre>` converter I went ahead and added the fix to our `CustomPre` implementation, together with a simple spec.
Closes #10104 
I tested using the sample RSS feed provided in the issue.
The easiest way I found for me to test the feed parsing was to create a draft Article and then from `rails console` perform an update with the code from `RssReader`:
```ruby
feed = Feedjira.parse(File.read('sample_rss.xml'))
Article.last.update(
body_markdown: RssReader::Assembler.call(feed.entries.first, User.find(4), feed, feed.entries.first.url.strip.split("?source=")[0])
)
```
> Preserve newlines and indentation in <pre> tags from RSS import

- spec/rails_helper.rb
- spec/support/initializers/vcr.rb
When using the Docker dev setup, Elasticsearch is available at `elasticsearch:9200` instead of `localhost:9200` so the VCR testing config was not ignoring the requests needed for RSpec setup when doing `Search::Cluster.recreate_indexes` in `spec/rails_helper.rb`. Also the WebMock setup allows `localhost` requests which should also include Elasticsearch requests.
This seems okay to me, but I'm not sure if there is a better solution. One issue I might have is that a detail related to the Docker dev setup is bleeding into common RSpec configs. What do you think, @citizen428?
Closes #10579 
With this change you can run unit tests when using the Docker dev setup, for example this spec was failing at `Search::Cluster.recreate_indexes` in `spec/rails_helper.rb` and is now passing.
```
bundle …
```
> Fix RSpec unit testing when using Docker dev setup

- lib/data_update_scripts/20201019192035_backfill_registered_for_users.rb
This PR adds a `data_update` script to backfill the `registered` and `registered_at` columns on users who are created, but not registered. Currently, there are some users who still are considered `registered: false` even though they've created an account via an invitation by email. By adding this `data_update` script, we'll "fix" the `registered` columns for those particular users, creating a clean slate for us to test whether or not the root issue of this problem has been fixed via pull request #10882 
Relates to PR #10882 and closes [Internal issue #133](https://github.com/forem/InternalProjectPlanning/issues/133).
Make sure that Travis and all other checks build green! ♻️ 
This _is_ a post-deployment task. 😎
> Data update Script: Backfill Created, but Unregistered Users

- app/controllers/admin/admin_portals_controller.rb
- app/models/admin_portal.rb
- app/views/admin/admin_portals/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
Currently `/admin` redirects straight into `/admin/articles` which may or may not actually be the right place to go.
This PR introduces a simple index which allows users to pick from the right place to go.
This is an MVP, but IMO this dashboard should ultimately have descriptions, at-a-glance analytics, and generally be the most useful initial interface. For now I adopted the card view from tags and I think it's a decent start.
> Add admin index

- app/controllers/admin/invitations_controller.rb
- app/views/admin/invitations/index.html.erb
- config/routes.rb
- spec/requests/admin/invitations_spec.rb
This PR gives Admins the ability to delete any pending invitations in `/admin/invitations`. In order to accomplish this, this PR does the following:
This PR closes Internal [issue #181](https://github.com/forem/InternalProjectPlanning/issues/181).
**To QA these changes, please make sure that you have `admin` status and then do the following**:
- Navigate to `/admin/invitations/new` and invite a new user to the site by filling out the form and clicking "Create User":
- Once you have clicked "Create User" you should be shown a message indicating that the creation was successful and that an invitation has been sent to the user:
- Drop into your console and check that the user you just created exists:
```
User.last
=> #<User id: 55, articles_count: 0, available_for: nil, …
```
> Give Admins Ability to Delete Invitations

- app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
Fixes: 
```
Summary of all failing tests
FAIL  app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
● <SingleArticle /> › renders the new clickable article title
ReferenceError: React is not defined
49 |   it('renders the new clickable article title', () => {
50 |     const { container } = render(
> 51 |       <>
|       ^
52 |         <SingleArticle {...getTestArticle()} toggleArticle={jest.fn()} />
53 |         <div
54 |           data-testid="flag-user-modal"
at Object.<anonymous> (app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx:51:7)
```
> Spec Fix:Add Fragment to test html

- spec/system/articles/user_visits_an_article_spec.rb
These 2 specs have been particularly flaky since fixing our browser date/time issues so I am commenting it out while I investigate.
> Comment out Flaky User Views Article Date Specs

- app/liquid_tags/spotify_tag.rb
- spec/liquid_tags/spotify_tag_spec.rb
The bug was caused by a trailing whitespace character in the embed URL. Using the matched substring from `MatchData` avoids any additional whitespace. Also updated the spec to use explicit values instead of duplicating the logic from the code.
Closes #10951 
Adding a Spotify liquid tag to an Article will now result in a valid embed iframe, while before it would display the text "Bad Request".
For example:
```
{% spotify spotify:track:3GfOAdcoc3X5GPiiXmpBjK %}
```
Before:
After:
> Use matched substring in Spotify liquid tag to avoid trailing whitespace

- db/seeds.rb
There might be a reason we don't do this, but I had to change it when I was testing /resource_admin changes, it seems like there is no harm in starting off with those permissions.
> Make default admin a super admin

- app/assets/javascripts/initializers/initializeBaseUserData.js
- app/assets/stylesheets/articles.scss
- app/assets/stylesheets/base/main.scss
- app/javascript/leftSidebar/TagsFollowed.jsx
- app/javascript/packs/homePage.jsx
- app/views/articles/_sidebar_nav.html.erb
- app/views/articles/index.html.erb
- app/views/dashboards/following_tags.html.erb
- app/views/layouts/_user_config.html.erb
- spec/system/homepage/user_visits_homepage_spec.rb
This pull request fixes a bug where inter-page navigation messes with the display of tags.
It also updates tags to crayons design and adds a quick link to adjusting tags. I made small design and copy adjustments to that page as well.
In my opinion navigating to tags from this area is still a valuable feature but is inhibited by poor design and lack of awareness around the customization.... And the bug that was in place.
(It was my old design so I think I'm allowed to be blunt about its poor quality 😄)
Beyond just the bug fixes I think this is an improvement we should lean in on.
A follow-up feature which I think could add more usability here could be an `indicator` mentioning the number of posts for that tag in the last 24 hours or since you last visited the page. Could encourage simpler …
> Fix tag display bug and crayonsify area

- lib/tasks/app_initializer.rake
Recently we had a migration fail and I noticed that even though it failed the Release Phase script continued on as normal and completed. This led the code depending on that new column being deployed even though the new column failed to be added. This PR updates the system call to check for a return value and if none is given then it will exit the rake task with status 1. This causes the entire bash script to fail and stops the new code from going out. 
FIXED:
```
== Preparing database ==
== 20201020211426 Test: migrating =============================================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
error
/Users/mollystruve/forem/db/migrate/20201020211426_test.rb:3:in `change'
Tasks: TOP => db:prepare
(See full trace by running …
```
> Bug Fix:Fail Release Phase if a Migration Fails

- app/views/admin/pages/_form.html.erb
- spec/system/admin/admin_manages_pages_spec.rb
This change adds a button for admins to delete pages.
Closes https://github.com/forem/InternalProjectPlanning/issues/174
> Add a button to delete pages

- spec/requests/stories_index_spec.rb
When a Navigation link has a name with a special character in it, that character will get escaped in the HTML. This ensures that we also escape the special character in our assertion for the spec. 
Fixes: 
```
1) StoriesIndex GET stories index renders page with proper sidebar
Failure/Error: expect(response.body).to include(navigation_link.name)
expected "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <title>DEV(local) C...ba8488d21cd8ee1fee097b8410db9deaa41d0ca30b004c0c63de0a479114156f.svg\" />\n  </body>\n  </html>\n\n" to include "The Stars' Tennis Balls 901"
Diff:
@@ -1,2 +1,456 @@
-The Stars' Tennis Balls 901
+<!DOCTYPE HTML>
...
+    &nbsp;The Stars&#39; Tennis Balls 901
...
```
> Spec Fix:Ensure Nav Link Names are Escaped for Assertion

- app/assets/stylesheets/views/profile.scss
This PR makes organization user pic background to be fully covered which resolves empty corners issues described in #10815
Closes #10815
> Fill organization userpic background fully to avoid empty corners

- app/assets/javascripts/initializers/initializeCommentDropdown.js
Closes #10842 (bug).
`initializeCommentDropdown` is called when a new comment is added.
`initializeCommentDropdown` calls `addDropdownListener(dropdown)` on all
`.dropbtn` elements. Elements with the `.dropbtn` class already exist on
the page so an extra listener is added to the element whenever a comment is
added. Since there is two listeners on one button, it is as if the user quickly 
clicks the button to open the dropbown, and then instantly clicks again to close 
it every time they click once.
Whenever a dropdown listener is added to an element with the
`.dropbtn` class, an attribute is set on that element so we know it
already has a dropdown listener. When we add listeners to elements with
the `.dropbtn` class in the future, we don't add them to elements with
the attribute.
#10842 …
> Fix dropdowns breaking after adding comment

- app/services/profiles/update.rb
- spec/services/profiles/update_spec.rb
One of our new communities had a problem during profile updates: if they had custom fields that don't exist on user, the saw an error like this:
This PR addresses this. It's a quickfix, since there will soon be a much larger PR that removes the syncing between users and profiles.
Part of #6994
1. Add a profile field that doesn't exist as a column on user.
2. Go to `/settings/profile`
3. Update any value
4. It should work
> Make profile fields without user columns work

- app/javascript/admin/controllers/image_upload_controller.js
- app/views/admin/shared/_image_uploader.html.erb
- app/views/admin/tools/index.html.erb
Adds a little image uploading widget to the admin area. This partial can be rendered on any page, so it might be neat to think of a pattern that makes this tool (and others like it) more generally available kind of like how the mod tools work on article pages.
I spent some time thinking about improvements that needed to be made to image management on the site and started working on those, but scrapped that in order to focus on solving the immediate need.
Closes https://github.com/forem/InternalProjectPlanning/issues/122
> Add a simple image uploader partial

- config/routes.rb
Currently we're looking for the `tech_admin` role to give access to developer tools like Blazer and Feature Flags. In development the default admin account (`admin@forem.local`) only has the `super_admin` and `single_resource_admin` roles, which prevents them from accessing Blazer or Feature Flags locally.
Instead of just this role, we should be using the more inclusive admin check `User.tech_admin?` that looks for both `tech_admin` as well as `super_admin` roles.
- [ x] no documentation needed
> User better admin detection for blazer and feature flags

- app/lib/constants/site_config.rb
This PR standardizes the image placeholder text throughout the SiteConfig. Prior to this change, we used both `https://image.url/` and `https://image.url/image.png` -- this PR makes it so that we only use `https://image.url/image.png` as an image's placeholder text.
Closes [issue #172](https://github.com/forem/InternalProjectPlanning).
**To QA this change, please ensure that all of the checks pass and that all the SiteConfig only uses `https://image.url/image.png` as its image placeholder text and not `https://image.url/`.**
**Before**:
**After**:
Nope!
> Standardize Image Placeholder Text in SiteConfig

- config/initializers/carrierwave.rb
This is the last time I refactor this file I swear.
The last time I refactored this file, I created a bug that prevented Forem from booting up in a VM when not given any keys. This brought back the old logic of how it was done.
This is the previous attempt. https://github.com/forem/forem/pull/10756
You should be able to start up Forem in development/test/production mode without making changes to your env var.
n/a
> Refactor CarrierWave configuration

- app/javascript/listings/listings.jsx
Use the new keyboard shortcut hook to listen for `Escape` keypress to close an open listing modal
#10878 
1. Go to listings
2. Open a listing
3. Press `Escape`
4. Verify that the listing modal closes
I'd like to add tests for this, but the `<Listings />` component does not currently have tests.
It seems to need a lot of stuff in order to set it up (mocking, adding divs to the DOM, etc.).
Any help with that is appreciated.
Closing the modal is probably not the most crucial test to do in this component, but if making the set up opens the door to more tests, then it's a win.
> refactor: Use keyboard shortcut hook in listing modal

- app/controllers/stories/feeds_controller.rb
- app/services/articles/feeds/large_forem_experimental.rb
- config/field_test.yml
- spec/services/articles/feeds/large_forem_experimental_spec.rb
We have been running these feed experiments for a while now and recently they came up in a PR. I took the initiative to start closing the loop on them. The reason I want to close the loop on this is that multiple code paths add complexity to our codebase and additional time to our specs when we test them. If we can narrow down to the ideal paths(doesn't even have to be 1!) then we can begin to optimize those paths for performance and other Forems. 
I recently looked [at the results of our A/B tests](https://dev.to/abtests) and found that because we have so many experiments running it's pretty hard to tell if any are the "true winner". In this case, I took a couple of experiments that seemed to have lower or very middle of the pack results and removed them. After allowing these tests to …
> Optimization:Remove 2 Feed Experiments

- app/javascript/Search/Search.jsx
- app/javascript/Search/__tests__/Search.test.jsx
- app/javascript/utilities/__tests__/search.test.js
- app/javascript/utilities/search/index.js
Prior to this PR, when searching for things on DEV, search in the UI worked but if we went back and forward in browser history, the search input would not reflect the search term in the URL of the browser.
Closes #11010
Before
See it in action in the Loom video
https://www.loom.com/share/0b6cefcfa85a4cce875f99764c107e64
After
See it in action in the Loom video
https://www.loom.com/share/3fa9e1f9892d480199fb2c48be130dd3
1. Go to https://dev.to
2. In the search at the top of the page, type in `ruby` and press enter.
3. The URL in the browser will switch to `https://dev.to/search?q=ruby`.
4. Do another search, but this time for `javascript`
5. The URL in the browser will switch to `https://dev.to/search?q=javascript`.
6. Hit the back button of the browser.
7. The URL in the browser will …
> Fix Search Navigation Disconnect Between URL and Search Input

- app/controllers/admin/podcasts_controller.rb
- app/views/admin/podcasts/edit.html.erb
- spec/requests/admin/podcasts_spec.rb
This PR gives Admins the ability to publish and unpublish podcasts from `/admin/podcasts/:id/edit` via a "Published" checkbox. This change makes it so that Admins no longer have to navigate to `/resource_admin/podcasts` to publish and unpublish podcasts. Additionally, this PR updates the existing `podcast_spec.rb` to test that the checkbox properly updates the podcast.
Closes https://github.com/forem/InternalProjectPlanning/issues/206
**To QA this PR, first ensure that you are and `admin` and then please do the following**:
- Navigate to `/admin/podcasts/:id/edit` and click the "Published" checkbox and then "Update" to publish or unpublish a podcast:
- After updating the podcast, you should be redirected back to `/admin/podcasts` where you will see the status (published or unpublished) of …
> Ability to Mark Podcasts as Published in Admin Podcasts

- app/controllers/registrations_controller.rb
- db/seeds.rb
- lib/data_update_scripts/20201022161311_backfill_user_registrations_in_registrations_controller_path.rb
- spec/requests/registrations_spec.rb
We're currently failing to mark folks as `registered_at`, which we use in certain places after the fact, on the email registration path..... This causes miscellaneous issues.
`registered_at` is different than `created_at` because we create the row in the database when we `invite` them, but they are not yet "registered" for the purpose of application functionality until they actually register.
Of course, this similar functionality exists in several places, and we should refactor this, but for now I think this is good enough with fixing the problem in the place and adding a test.
> Fix missing registration data change

- .env_sample
- app/models/chat_channel.rb
- app/views/shell/_top.html.erb
`APP_NAME` may not always be set (it is not "required" per se), which can cause issues while deriving the `pusher_channels`. 
We should use `APP_DOMAIN`, which is more common and always has a default value.
https://github.com/forem/InternalProjectPlanning/issues/212
Ensure that chat works correctly.
> Use APP_NAME rather than APP_DOMAIN in chat channels

- app/views/layouts/_user_config.html.erb
This was being caused by two reasons: 
1. There was a caught runtime error throwing to Honeybadger (this is what it should do, but I fixed the error so it won't be caught)
2. Honeybadger is not yet defined at this point because the error is happening in the inline portion of the script we run right in the html to help set the theme, etc.
Since we define Honeybadger in an async script, we can't technically call it until later.
This is a hot fix which introduces a race condition, but we should reorganize the code later for a permanent fix.
> Fix honeybadger console error

- app/controllers/registrations_controller.rb
- app/helpers/application_helper.rb
- app/views/articles/_sidebar_additional.html.erb
- app/views/devise/registrations/_registration_form.html.erb
- app/views/layouts/_nav_menu.html.erb
- app/views/shared/_authentication_actions.html.erb
- app/views/shared/_authentication_description.html.erb
- app/views/shared/_authentication_title.html.erb
- app/views/stories/_sign_in_invitation.html.erb
This is a request from one of our early adopter Forems. We should only
render the user count that appears on most of our sign up CTAs when a
Forem has a large userbase (initially, I'm setting that to 1000 users).
The change also removes a lot of duplicated markup by using some
partials to render the copy in the various auth CTAs.
Hopefully, this is written in such a way that changing opening up more
fine-grained control of these partials is trivial.
Closes https://github.com/forem/InternalProjectPlanning/issues/209
Basically, we drop the number of users until there are more than 1000 users.
Mobile Dropdown Menu:
Registration Screen:
In-feed CTA:
Sidebar:
> Only show user count for large userbases

- app/views/admin/configs/show.html.erb
This PR fixes sizing issue in /admin/config where logo_png was stretched.
**Before:**
**After:**
> Fix admin logo_png preview size

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/themes/hacker.scss
- app/assets/stylesheets/themes/minimal.scss
- app/assets/stylesheets/themes/night.scss
- app/assets/stylesheets/themes/pink.scss
- app/helpers/authentication_helper.rb
- app/views/devise/registrations/new.html.erb
- app/views/shared/authentication/_email_registration_form.html.erb
- app/views/shared/authentication/_forem_creator_signup.html.erb
- spec/requests/registrations_spec.rb
Right now, we have many different ways to sign up for a new Forem. When a new Forem creator goes to sign up for and "activate" a new Forem, this is sign up form that they will see:
**This PR adds the new form for the Forem creator onboarding flow, which is hidden behind the `creator_onboarding` feature flag (!!).**
Please note that all this PR is really doing is creating the new form, and hiding it behind the feature flag. This will allow me to ship small, encapsulated PRs without changing what a Forem creator sees. I will eventually remove the "old" Forem creator form and replace it with our new one by removing the feature flag altogether! 👏 
A step towards completing https://github.com/forem/InternalProjectPlanning/issues/81, which will be a series of smaller PRs! 😸 
1. Go into the …
> Forem creator feature flag + onboarding signup form

- app/views/articles/_sidebar_nav.html.erb
- spec/system/homepage/user_visits_homepage_spec.rb
This PR adds an "Explore Tags" section to the sidebar nav for signed-in users who _do not_ follow any tags. Rather than linking to `/dashboard/tags` like the `cog.svg` does for signed-in users who _follow_ tags, the `cog.svg` links to the tags overview, `/tags`. Additionally, below the "Explore Tags" header, the top five tags for the site are displayed with the option to follow them, making it easy for users to begin following loved tags. This PR allows adds a test to ensure that "Explore Tags" works properly.
Closes https://github.com/forem/InternalProjectPlanning/issues/199
**To QA this PR, please do the following:**
- Navigate to `localhost:3000` as a signed-in user. If you are following tags you should see the header, "My Tags" displayed with the tags that you're following below the …
> Add Explore Tags for Signed-In Users

- app/views/articles/_about_author.html.erb
- app/views/dashboards/_dashboard_article_row.html.erb
In https://github.com/forem/forem/pull/9285 we added a `local_date` helper to ensure that article published timestamps were shown in locale time and not server time. However, [this was not applied to all of the published timestamps](https://github.com/forem/forem/issues/7086) leading to continued bugs. This adds the helper to two other places I found that we display article published timestamps
Closes https://github.com/forem/forem/issues/7086
The article show page is already tested and is very flaky which is why I have issued https://github.com/forem/forem/pull/11025 which will set up a testing framework that ensures the locale time on our frontend always matches the server testing time. Once that is merged we can go back and add Dashboard specs if we want to.
> Bug Fix:Use local_date Helper for All Published Timestamps

- app/workers/articles/dev_rss_reader_worker.rb
- spec/workers/articles/dev_rss_reader_worker_spec.rb
In the quest to write a new module to ingest feeds faster, see https://github.com/forem/forem/issues/10996, we need to know how the current one behaves in production on dev.to which is currently the biggest collection of feeds the Forem ecosystem has. We know it's slow, we have a rough idea about why it's slow but as for everything, navigating with real world data would be better. 
I'm adding a Sidekiq worker that we can call manually.
**question**: should we replace the call in 
https://github.com/forem/forem/blob/5b1f05876402fa6ee814c42f9e495ad6c983ff8c/lib/tasks/fetch.rake#L3-L7
with the worker called inline? `Articles::DevRssReaderWorker.new.perform` ?
https://github.com/forem/forem/issues/10996
1. change your community name to DEV
1. run the worker
> Add temporary RSS reader worker to gather monitoring data

- app/javascript/packs/admin.js
- app/views/layouts/admin.html.erb
- docs/admin/admin-user-interface.md
It's not really obvious where all the administration frontend controllers get bootstrapped. This file rename helps with that.
The pack file has been renamed, so the admin section of the application should behave the same.
> Renamed internal.js pack file to admin.js

- app/labor/assign_tag_moderator.rb
- db/seeds.rb
- spec/labor/assign_tag_moderator_spec.rb
Secondarily, it adds this channel to the seeds file, since we pretty
much expect it to exist.
In development, it is possible to hit a NoMethodError when adding a tag
moderator because the "tag-moderator" slug is hard-coded.
This change helps mitigate that by adding a safe navigation operator. We
can always remove it if we decide to get rid of the hard-coded value.
Another solution is creating the channel when it doesn't exist, but I'm not sure we should force that choice on a Forem. If anyone thinks that's fine, we can swap to that approach.
I added a regression test to detect if this bug reappears, but we can cut it out if anyone thinks that is overkill.
1. Navigate to `/admin/tags`
2. Edit a tag > add a tag moderator
3. If the tag moderators channel doesn't exist you'll get a …
> Fix NoMethodError for tag moderators channel

- app/helpers/application_helper.rb
Subtitles don't change so we can move them to a constant and save some memory (if you need stats I can provide them) because this hash and strings are created every time `title_with_timeframe` is called (which is 3 times on https://github.com/forem/forem/blob/467e99556cf1fc088bbd91ec0612d4a64ff91ffd/app/views/articles/index.html.erb).
This PR reduces the number of creations of this hash from 3 * number of calls of `render "articles/index"` to 1. (Similar on `tags/_meta`).
Check if the title contains values from the hash.
> Extract subtitles to a constant to reduce allocations

- app/views/articles/_sidebar_nav.html.erb
[This](https://github.com/forem/forem/commit/8fb1a3824a92942f1c05524d0ede5c27c4b6d90f#diff-60389f4530eeb06208f463974e7bb70cfc9d00d9e85affa395004dff9cfdffdaR48) commit duplicated the `nav` starting element.
Test if the nav works.
> Remove duplicated nav in sidebar_nav

- app/views/admin/mods/index.html.erb
Replaces old button with crayon button it also improves button visibility
Closes https://github.com/forem/forem/issues/11081
> Replacing old button with crayon buttons to make it more visible

- app/assets/stylesheets/widgets.scss
A popular tag with a long name causes a horizontal scrollbar in the sidebar
This PR truncates long tags and shows ellipses on text overflow.
Resolves https://github.com/forem/forem/issues/10990
- In `rails console` create a new tag. Tags must be marked as `supported` to appear in the sidebar. Eg:
```rb
Tag.create!(name: 'longnamethatcausesoverflow', supported: true)
```
- If you have more than 30 tags you may need to change the new tag's `hotness_score` so that it appears in the list. 
For reference: Here's the query that generates the popular tag list
https://github.com/forem/forem/blob/4dde307a43b5d6c901bd4550d122accd86ce587e/app/views/articles/_sidebar_nav.html.erb#L81
- Navigate to `/`
Sidebar after changes
> Truncate long tags in sidebar

- app/assets/javascripts/base.js.erb
- app/assets/javascripts/initializers/initializeTimemachine.js.erb
- package.json
- spec/system/articles/user_visits_an_article_spec.rb
- yarn.lock
I got some information from my logging that was showing that the date we were displaying from the local_date helper did not match UTC or the Timezone set by zonebie.
Broken on Travis
```ruby
```
When I went back to the `local_date()` helper method I tracked it back to the PR that created it. It was here I realized that the helper method was not the final say in the date. Instead, it [actually gets set by a javascript date helper](https://github.com/forem/forem/blob/master/app/assets/javascripts/initializers/initializeArticleDate.js#L6) to ensure it matches the user's locale time. This made me realize we needed to go a step further and not only did the backend of the browser need to match our Time.zone set by Zonebie, but our javascript needed to as well. After a lot of googling I came …
> Spec Fix:Set Javascript Locale to Match Time.zone

- app/views/articles/_sidebar.html.erb
- app/views/articles/index.html.erb
This PR fixes a caching bug that was introduced in PR #11022, as pointed out by a community member (thank you so much!). Please see this comment for further information: https://github.com/forem/forem/pull/11022#issuecomment-716046885
Relates to PR #11022 
To QA this change, please ensure that "Explore" and "My Tags" properly render in the side navbar, that all checks pass, and that Travis builds green. I'm open (as always 😄 ) to any ideas for how to better test these changes!
N/A
> Add following_tags_count to release_adjusted_cache_key

- app/assets/javascripts/initializers/initializeTimemachine.js.erb
If we always try to require timemachine.js then we end up with this production error bc it is not packaged for production.
```
Sprockets::FileNotFound: couldn't find file 'timemachine.js' with type 'application/javascript'
```
This ensures we only require it for testing
> Bug Fix:Only Require Timemachine for Testing envs

- app/views/service_worker/index.js.erb
- config/routes.rb
As a Forem core team member that wants to set up a /forem organization on a new community (Community Club), the hardcoded redirect is causing issues.
As an example @pkfrank has been trying to set up an organization for Forem on Community Club using the /forem slug,it's then redirecting to /devteam/for-empowering-community-2k6h. 
Hence, we only want that to happen for the DEV forem and we want /forem to be available on other forems.
In this PR I remove the hardcoded redirect and reference in the service worker file.
https://github.com/forem/InternalProjectPlanning/issues/227
After pulling down this PR the route should no longer redirect to the hardcoded link.
Yes, we still want this to work on DEV so we want to create **Page** that will create the redirect on DEV. It can either be done …
> Remove the hardcoded forem redirect + add the redirect back to only Forem as a pre/post deployment task

- app/views/shared/_authentication_actions.html.erb
- app/views/shared/authentication/_providers_registration_form.html.erb
This fixes an issue where navigating to the registration page `/users/signup` via InstantClick (clicking the link itself) passes along the InstantClick param `?i=i`, which in turn breaks CSS for the email signup link.
**So the biggest thing to consider is whether we want that InstantClick navigation feeling still when clicking from the homepage to the "Create New Account" registration page.** I think it's a good touch but it is also prone to causing problems with the rest of our sign up links.
1. Add the two changed lines to your respective files, probably easier than pulling this PR and checking out via Git.
2. Have email registration enabled via /admin/config, Authentication section
3. Log out or open an incognito/private window
4. Go to the homepage
5. Click the Create New Account link …
> Don't use instantclick for registration links

- app/views/users/_sidebar.html.erb
Adding `following_tags_count` gets rid of the issue when `@user.last_followed_at` doesn't change.
This line is quite long. Is there any "repo" for cache keys?
Closes #5657
Play with (un)following tags and check if the counter on the user profile changes.
> Add following_tags_count to user sidebar stats cache key

- app/services/images/optimizer.rb
- lib/data_update_scripts/20201026155851_resave_to_bust_cache_for_imgproxy.rb
- spec/services/images/optimizer_spec.rb
This is to fix the distorted profile image in some Forem community. Please take a look at https://github.com/forem/InternalProjectPlanning/issues/215
Resolves https://github.com/forem/InternalProjectPlanning/issues/215
(I'm including a simple imgproxy setup for this QA, if you already know how to set it up please ignore first 2 steps)
1. Install imgproxy (`-> brew install imgproxy`) and start it up (`-> imgproxy`)
1. Just for this demo, please change `app/services/images/optimizer.rb:6` to `if true`, we're forcing the app to use imgproxy.
1. Choose a rectangular image of your choice, or use [this picture](https://magazine.northeast.aaa.com/wp-content/uploads/2018/05/banff-national-park-1-640x423.jpg).
1. Start up a rails console and enter the following …
> Expand cropping options for Imgproxy

- docs/.gitdocs.json
- [ X ] Documentation Update
Updated gitdocs.json links to `https`
The links for `ruby` and `api` on the [docs](https://docs.dev.to/) had an insecure http link.
> Updated gitdocs.json links to `https`

- app/assets/javascripts/utilities/buildArticleHTML.js
- app/javascript/articles/Feed.jsx
- app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
- app/javascript/articles/components/SaveButton.jsx
- app/javascript/packs/homePageFeed.jsx
- app/javascript/packs/homePageFeedShortcuts.jsx
- app/javascript/packs/signupModalShortcuts.jsx
- app/views/articles/_single_story.html.erb
- app/views/layouts/_signup_modal.html.erb
- app/views/stories/_main_stories_feed.html.erb
Adds a shortcut on `b` (for now?) to save an article as long as the user is focused somewhere inside the article.
Also adds a shortcut on the signup modal to close it on `Escape` keypress. It helps to keep the navigation mouseless after pressing `b`.
This will be more useful once #10468 is merged, but it can live on its own.
Also, `b` is to discuss here. Other options have been discussed such as `ctrl+s`.
Closes #11018 
1. Focus on article (anywhere inside)
2. Press `b`
3. Article is saved/unsaved
- Logged in: actually saves it
- Logged out: Opens the signup modal
> A11y: Add shortcut to bookmark an article

- app/services/suggester/users/recent.rb
Was recently looking at some slow traces on Honeycomb when I came across one that had a 1 second SQL query in it. Upon further investigation, I noticed that the query was trying to suggest users to follow and was using the current user's followed tags. This particular user had 20 tags they were following which made the query pretty intense with 20 `OR` tagging statements. To save us some process time and power I decided a good solution would be to limit the number of tags when suggesting users to follow.
> Optimization:Limit Tags Searched For Follow Suggestions

- app/javascript/chat/ChatChannelSettings/ModFaqSection.jsx
- app/javascript/chat/__tests__/modFaqSection.test.jsx
Email displayed in **app/javascript/chat/ChatChannelSettings/ModFaqSection.jsx** is now replaced with link to /contact page but it was still taking in email prop which it does not use. This PR removes that email prop
Closes https://github.com/forem/forem/issues/11109
> Removing email prop and fixing test

- app/helpers/articles_helper.rb
Extract sort options to a constant to reduce the number of allocations.
> Extract dashboard posts sort options to a constant

- app/controllers/articles_controller.rb
Refactor unless statement and remove unused variables from ArticlesController
https://github.com/forem/forem/issues/3739 
> Refactor articles_controller

- app/controllers/stories/feeds_controller.rb
- app/services/articles/feeds/large_forem_experimental.rb
- config/field_test.yml
- spec/services/articles/feeds/large_forem_experimental_spec.rb
Continuing to close the loop on these Feed experiments. After removing a couple of them last week I re-evaluated the remaining ones and it's pretty clear the `more_tag_weight_experiment` alone is not going to be a winner based on the [AB test dashboard](https://dev.to/abtests/). I also took this opportunity to rebalance the weights a little towards the experiments that appear to be more successful to give them a better chance of standing out and maybe "winning"
https://github.com/orgs/forem/projects/6#card-47841833
> Optimization:Remove more_tag_weight_experiment From Feed Tests and Rebalance

- config/puma.rb
Here are a few posts about `GC.compact` in Rails....
- https://dev.to/palkan_tula/cables-profiling-returns-gc-compact-jemalloc-33c9
- https://engineering.appfolio.com/appfolio-engineering/2019/3/22/ruby-27-and-the-compacting-garbage-collector
- https://www.infoworld.com/article/3404481/ruby-27-improves-garbage-collection-pattern-matching.html
My thoughts here are that if tests pass, this is something we could deploy and observe. There may be more ways we could use this in specific cases.
> Enable Puma's nakayoshi_fork feature

- app/assets/javascripts/initializers/initializeAllTagEditButtons.js
- app/assets/stylesheets/sidebar-data.scss
- app/views/articles/tags/_sidebar.html.erb
- app/views/tags/index.html.erb
- spec/requests/stories_index_spec.rb
The problem that this is solving is that setting any admin-only functionality lacks intuitive ergonomics for admins. If they recognize that a tag needs to be adjusted or elevated, it's a pain to get to the proper admin dashboard. This adds an admin button alongside mod buttons. Also made a style adjustment.
Old:
New:
This creates a button a shortcut to admin, alongside moderation to allow admins to more easily modify admin-level tag decisions.
> Add admin shortcut to tag page

- app/javascript/chat/chat.jsx
- app/javascript/utilities/connect/getUnopenedChannels.jsx
- app/models/chat_channel.rb
- app/views/shell/_top.html.erb
- spec/models/chat_channel_spec.rb
https://github.com/forem/forem/pull/11029 fixed a production issue but broke development.`localhost:3000` is not a valid pusher channel name because Pusher [channel specification](https://github.com/pusher/pusher-http-ruby/blob/master/lib/pusher/channel.rb#L11) doesn't allow colon. I was receiving the following error in development and test:
```
Pusher::Error:
Illegal channel name 'private-message-notifications--localhost:3000-25'
```
This feature encodes the domain name, which would fix this issue but also provide the added benefit of obfuscating channel names.
This is an additional update to https://github.com/forem/forem/pull/11029
Prior to this fix you probably can't _send a message and see it appear immediately_ in development.
1. Bootup the app locally and make sure you are logged …
> Encode domain name in pusher channels

- app/controllers/display_ad_events_controller.rb
- spec/requests/display_ad_events_spec.rb
[This controller was added to help us determine the success of DEV shop ads](https://github.com/forem/forem/pull/3589). I think the `Rails.env.production?` was merely added bc this doesn't have a lot of value locally. However, we should get in the habit of setting up our code so that it runs in all environments. This ensures that we don't miss things bc code paths were not run in test or development.
> Refactor: Run Display Ad Events Controller in all Envs

- app/assets/javascripts/initializers/initializeCommentsPage.js.erb
- app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
- app/assets/stylesheets/views/comments.scss
- app/views/comments/_form.html.erb
This PR does two things:
1. Improves autoresizing when writing a comment (not sure why it doesn't work on replying comment form but it also doesn't work currently so at least I'm not breaking it :D...) 
2. Brings back possibility to to hit CMD+Return to submit a comment.
- Closes #10829 
- Closes #11086 
> Autoresize on comment textarea + comment submit on `CMD/CTRL+Return`

- app/models/reaction.rb
Deleted unused methods that are not found/used across the repository in the Reaction model. Also fixed one issue on CodeClimate :) 
https://codeclimate.com/github/forem/forem/pull/11138
> Refactor Reaction model

- app/controllers/concerns/verify_setup_completed.rb
- app/lib/url.rb
- app/models/site_config.rb
- spec/lib/url_spec.rb
- spec/requests/admin/configs_spec.rb
- spec/system/admin/admin_manages_configuration_spec.rb
This PR makes setting the `main_social_image` optional when setting up a Forem by setting a default value in the `SiteConfig`. This is part of @forem/creator-onboarding's efforts to reduce the amount of required configs as much as impossible and follows up on https://github.com/forem/forem/pull/11005 and https://github.com/forem/forem/pull/9747
Closes https://github.com/forem/InternalProjectPlanning/issues/93
1. Fire up the app locally and navigate to [http://localhost:3000/admin/config](http://localhost:3000/admin/config).
2. Verify that under **Get Started** you no longer see a **Main social image** field.
3. Verify that under **Images** you see the default value set for **Main social image**
> Add default for main_social_image

- app/controllers/admin/events_controller.rb
- app/views/admin/events/_event_form.html.erb
- app/views/admin/events/edit.html.erb
- app/views/admin/events/index.html.erb
- app/views/admin/events/new.html.erb
- app/views/admin/pages/index.html.erb
- app/views/events/_event.html.erb
- config/routes.rb
- spec/requests/admin/events_spec.rb
- spec/system/admin/admin_creates_new_event_spec.rb
**The issue**:
> As a Forem admin setting up events, it's pretty unwieldy to open /admin/events because everything is on one page. That includes past events, future events, the event creation page, etc. 
**The solution**:
This PR refactors the `/admin/events` index page by removing the event creation and event edit forms from the index into their own views and by cleaning up the `/admin/events` UI by separating out "Upcoming Events" and "Past Events" by use of a crayons table. Additionally, this PR adds a "New Event" button to the top of the `/admin/events` index and inline "Edit" buttons next to each event for easy editing. This PR also refactors the `Admin::EventsController`, Admin event-related forms, and Admin event-related specs. It also adds additional actions to the …
> Refactor Admin Events Index

- app/controllers/async_info_controller.rb
Removed another unnecessary `Rails.env.production?` check for shell_version. Locally we are not caching the shell_version so this version being unique is not needed. If we do ever implement surrogate header caching locally that will force us to update this shell_version which I think is a good thing as it is pushing us closer to a production like env.
> Refactor:Remove Rails Env Prod Check when Setting Shell Version

- docs/installation/mac.md
If you try to install brew as directed you get this Error:
Error: Calling Installation of elasticsearch-oss from a GitHub commit URL is disabled! Use 'brew extract elasticsearch-oss' to stable tap on GitHub instead.
Brew/ElasticSearch no longer allows you to tap as we previously have suggested in the doc. Also we can no longer grab the 7.5.2 version with brew.
We have decided to remove the instructions for now until we upgrade ElasticSearch if possible.
> Removing ElasticSearch Brew instructions

- app/assets/stylesheets/ltags/LiquidTags.scss
- app/assets/stylesheets/ltags/TwitterTimelineTag.scss
- app/javascript/article-form/components/Preview.jsx
- app/liquid_tags/twitter_timeline_tag.rb
- app/views/articles/show.html.erb
- app/views/comments/index.html.erb
- app/views/liquids/_twitter_timeline.html.erb
- app/views/pages/_editor_guide_text.html.erb
- spec/liquid_tags/twitter_timeline_tag_spec.rb
This PR introduces a new twitter_timeline liquid tag. See #7605
Closes #7605
1. Go to /new
2. Create article with following content:
```{% twitter_timeline https://twitter.com/FreyaHolmer/timelines/1215413954505297922 %}```
3. Click 'Preview'
3. Click 'Save'.
> Introduce twitter_timeline liquid tag (#7605)

- app/labor/assign_tag_moderator.rb
- lib/data_update_scripts/20201030015634_make_tags_with_mods_supported.rb
- spec/labor/assign_tag_moderator_spec.rb
- spec/lib/data_update_scripts/make_tags_with_mods_supported_spec.rb
This PR automatcally marks tags as supported when a tag mod is added. This removes the burden from admins to manually mark the tag. 
Closes #11140 
1. Create a tag: `tag = Tag.create(name: "admintest")`
2. Check that it isn't supported: `tag.supported? #=> false`
3. Assign a tag moderator: `AssignTagModerator.add_tag_moderators([User.last.id], [tag.id])`
4. Ensure the tag is now supported: `tag.reload.supported? #=> true`
> Automatically mark tag supported when adding mod

- docs/getting-started/config-env.md
- docs/installation/linux.md
- docs/installation/mac.md
- docs/installation/windows.md
Since ENVied Gem has been replaced by "dotenv" gem in the recent PR: https://github.com/forem/forem/pull/9767, the documentation should be update too.
Related PRs: https://github.com/forem/forem/pull/9767
> removed envied docs

- .travis.yml
- docs/maintainers/deploying.md
This PR is in response to [a great internal team discussion around our deploy strategies](https://forem.team/vaidehijoshi/responsibilities-around-code-deployment-3mdh). Since many people on the team seem to be in favor of a continuous deploy setup I went ahead and created this PR. However, feel free to jump in if you have differing opinions on this! I simply wanted to get a step ahead.
When I first joined, one of the reasons we never went with a full continuous deploy strategy was because Travis did not have the ability to cancel multiple builds. The build and deploy were also one and the same which meant if you wanted to cancel a deploy you had to cancel the CI build which meant not testing the new code. Now that those problems have been fixed thanks to Travis new "Auto Cancel" feature …
> Feature:Deploy Forem to DEV on every merge

- app/controllers/page_views_controller.rb
- spec/requests/page_views_spec.rb
Just like #11144 this PR removes a couple more `Rails.env.production?` checks. There is really no reason why we can't run these locally so why not. As stated in the other PR, the more we can make development like production the better.
> Refactor:Remove Production Conditional for Page View Updates

- app/models/site_config.rb
Sets the email registration config to default: false.
> Set email registration to default: false

- app/controllers/api/v0/organizations_controller.rb
- app/views/api/v0/organizations/show.json.jbuilder
- config/routes.rb
- docs/api_v0.yml
- spec/requests/api/v0/organizations_spec.rb
This would provide an api show endpoint `dev.to/api/organizations/{org_username}` to search organizations by their username.  
As discussed in issue 9212, This is the first of 4 related endpoints that will include:
```
dev.to/api/organizations/{org_username}/users
dev.to/api/organizations/{org_username}/articles
dev.to/api/organizations/{org_username}/listings
```
https://github.com/forem/forem/issues/9212
> API: Endpoint to get an organization's details

- spec/system/articles/user_visits_an_article_spec.rb
Remove the extra white space that occurs when a published_at day is a single number in the specs
This PR can be merged by any core team member.
> Spec Fix:Remove Extra Space From Single Number Dates in Spec

- app/controllers/admin/application_controller.rb
- app/helpers/admin_helper.rb
- app/views/admin/admin_portals/index.html.erb
- app/views/admin/shared/_navbar.html.erb
- config/routes.rb
- spec/models/profile_field_group_spec.rb
- spec/requests/admin/admin_portals_spec.rb
- spec/requests/admin/profile_field_groups_spec.rb
- spec/requests/admin/profile_fields_spec.rb
- spec/requests/admin/sidebar_spec.rb
- spec/routing/profile_admin_routes_spec.rb
Adds a feature flag `:profile_admin` which removes the menu item from the admin index and sidebar and also disables the routes. 
Anyone should feel free to merge this, it has tests for all scenarios.
https://github.com/forem/InternalProjectPlanning/issues/147
0. Ensure the feature flag is disabled.
1. Go to `/admin`
2. Ensure that you don't see the profile admin link (it would be right after "Config")
3. Enable the feature flag in the Rails console:
```ruby
Flipper.enable(:profile_admin)
```
4. Reload `/admin`, you should now see a "Config: Profile Setup" option:
0. Ensure the feature flag is disabled.
1. Go an admin page, e.g. `/admin/articles`
2. Ensure that you don't see the profile admin link (it would be right under "Config")
3. Enable the feature flag in the Rails console:
```ruby …
```
> Add feature flag for profile admin section

- app/javascript/packs/fullScreenModeControl.js
- app/views/comments/index.html.erb
Fixes #10979 
This fix makes fullscreen functionality for code highlight blocks available on comment page. 
When you open comment page by clicking on 'permalink' from comment menu, you will see url contains **/comment/**. 
If comments contain code highlight block in comments page, on hover you will see fullscreen button.
Currently It won't respond to click events in Production version. 
This PR fixes this issue, making fullscreen block clickable.
> fix for code fullscreen action on comment page

- app/controllers/stories_controller.rb
There is not really a good reason to treat production any different when showing recent podcasts. If devs want to mimic this behavior locally they can always go in and update podcast published dates to be within a day.
> Refactor:Always Load Last 24 Hour Podcasts

- config/elasticsearch/mappings/users.json
- lib/data_update_scripts/20200914042434_reindex_users_for_profiles.rb
- lib/data_update_scripts/20201030134117_reindex_users_for_username_search.rb
- spec/lib/data_update_scripts/reindex_users_for_username_search_spec.rb
- spec/services/search/user_spec.rb
This PR enabled searching a user by username with wildcard. E.g. when a user is `krzysiek1507`, it finds by the whole username but also by a part of it: `krzysiek`, `krzysiek15`. Since the pattern is: `word*`, it won't find by a substring from the middle or the end of the username.
Closes #10967
1. Try to find by a username (NOTE: to fail it, the username cannot be equal or be part of first or last name)
2. Run:
```ruby
Search::User.update_mappings
User.all.each(&:touch) # if your db is small
```
3. Search again for the username
1. Mappings for User have to be updated.
2. Users have to be reindexed.
> Copy username to search_fields

- app/views/comments/_liquid.html.erb
Following the footstep of https://github.com/forem/forem/pull/10977 and removing social icon from comment liquid tag.
n/a
You should be able to use the comment liquid tag and not see the social icon attached for the user.
n/a
> Remove social icons from comment liquid tag

- app/controllers/stories_controller.rb
- spec/requests/stories_index_spec.rb
There is no reason we can't load the same amount of articles for the feed in development and test as we do in production.
> Refactor:Show Same Number of Articles for all Envs

- app/views/service_worker/index.js.erb
- config/routes.rb
Some Forems may want to use the /future url as part of their forems, hence we want to make /future available to all Forems, whilst keeping it reserved on DEV to redirect to the necessary post. 
We did the same thing for route /forem https://github.com/forem/forem/pull/11083
After pulling down this PR the route should no longer redirect to the hardcoded link.
This can be done pre deployment.
We still want this to work on DEV so we want to create Page that will create the redirect on DEV. It can  be done through the interface of the console. See below:
```
Page.create(
title: "Future Redirect",
body_html: "<script>window.location.href = 'https://dev.to/devteam/the-future-of-dev-160n'</script>",
slug: "future",
description: "Redirect the future link to an article written on DEV",
template: …
```
> Remove the hardcoded /future redirect + add the redirect back to only Forem as a pre/post deployment task

- app/views/articles/_widget_list_item.html.erb
In the widgets container, update the "comments" string so that the format is `3 comments` instead of `Comments: 3`.
This format uses more human-friendly language.
> Update comments label in widget

- app/queries/admin/moderators_query.rb
This updates the potential tag mod page `/admin/mods?state=potential` (used for finding and adding new mods) to not show `warned` and `comment_banned` users. Also refactors it a bit.
https://github.com/forem/InternalProjectPlanning/issues/248
1. In Rails console, ban a user `User.first.add_role :banned`
2. Visit `/admin/mods?state=potential`
3. Ensure that user with ID 1 does not appear
> Filter by a few other roles when adding potential mods

- app/javascript/packs/homePage.jsx
If a user doesn't follow any tags, then on the homepage instead of `My tags` section, the `Explore` section is rendered and we can see in the console:
```js
Uncaught TypeError: Cannot read property 'firstElementChild' of null
at renderTagsFollowed (homePage.jsx?a167:53)
at dataLoadedCheck (homePage.jsx?a167:92)
at fn.___hb (base.js:7708)
at base.js:8141
```
This PR changes the code to render followed tags only if the container is present.
1. Check if there is no warning in the console when `Explore` section visible.
2. Check if the followed tags are rendered is any followed.
> Render followed tags only if container available

- app/views/users/_ux.html.erb
Fixes the markup wrapping the UX themes radio button group.
Closes #11243
1. Navigate to http://locahost:3000/settings/ux
1. The UI should look the same as it currently does in production for the themes section.
> UX Settings: wrap radio button group in a fieldset

- config/initializers/carrierwave_monkeypatch.rb
- spec/initializers/carrierwave_monkeypatch_spec.rb
Having patches like this in the code that are only applied in Production can be risky. The reason it is risky is bc if a problem comes up with the patch say because of a gem upgrade we won't have any indication of it(at this point down the road with some more intricate testing strategies we likely will) until the code is in use by users. With the guard removed, there is a chance we can catch issues before then. 
I also added a test for this patch so if the patch is removed accidentally, the test will break as a warning. 
I tested this locally and everything works as expected and with the tests passing **I dont think** there is any reason why we need this guard clause.
> Refactor:Implement Carrierwave Monkeypatch in all Envs

- spec/system/comments/user_edits_a_comment_spec.rb
This fixes a flaky test where the test sometimes doesn't click through to the edit comment page properly.
I'm not really sure why `expect(page).to have_text("Editing comment")` would change anything honestly. But 50/50 runs locally made me believe otherwise...
> Add expectation to ensure on edit comment page

- app/javascript/listings/singleListing/Header.jsx
This PR makes sure the tags always show up in listing modal
Closes https://github.com/forem/forem/issues/11231
1. Go to /listings
2. Click on a listing with tags. It will open up a modal and it will show the tags
3. Now refresh the page
4. The modal will show up but with tags
> Fixing tags in listing modal

- docs/backend/data-update-scripts.md
- lib/generators/data_update/data_update_generator.rb
- lib/generators/data_update/templates/data_update_spec.rb.tt
During my recent profile generalization work, I had to write quite a few data update scripts and got tired of adding the corresponding specs manually. I decided to add `--spec` / `--no-spec`options to the generator, with `--spec` being the deafault:
```
❯ rails generate data_update -h
Usage:
rails generate data_update NAME [options]
Options:
[--skip-namespace], [--no-skip-namespace]  # Skip namespace (affects only isolated applications)
[--spec], [--no-spec]                      # Indicates when to generate spec
[output snipped]
```
The generated specs are simple and follow our current conventions. The included message is borrowed from Rails' default generators:
```ruby
require "rails_helper"
require Rails.root.join(
"20201103044008_do_the_thing.rb",
)
describe …
```
> Add --spec option for data_update generator

- db/seeds.rb
`rails db:setup` or `rails db:seed` commands sometimes fail. This is because in `db/seeds.rb`, 3 'vomit' reactions are created for 3 randomly selected articles (on a total of 25).
```rb
3.times.do
Reaction.create!(
category: "vomit",
reactable_id: Article.order(Arel.sql("RANDOM()")).first.id,
reactable_id: article_id,
reactable_type: "Article",
user_id: mod.id,
)
end
```
If the same article is picked 2 times, the creation of the reaction will crash because according to the validations, it is not allowed to create 2 'vomit' reactions for the same article.
With these changes, we make sure to select an article that does not already have a vomit reaction. 
Closes #11271 
In `db/seeds.rb` on line 188, change `num_articles` to `3`. It is then very likely that `rails db:setup` command will fail …
> Fix rails db:seed error

- app/views/articles/index.html.erb
- app/views/onboardings/_task_card.html.erb
- spec/liquid_tags/user_subscription_tag_spec.rb
- spec/system/authentication/redirects_using_referer_spec.rb
- spec/system/authentication/user_logs_in_with_email_spec.rb
- spec/system/onboardings/user_completes_onboarding_spec.rb
- spec/system/user/user_edits_integrations_spec.rb
- spec/system/user/user_edits_profile_spec.rb
- spec/system/user/user_edits_ux_spec.rb
- spec/system/user/user_self_destroy_spec.rb
As a part of the ✨ NEW CREATOR ONBOARDING FLOW ✨, we need to change how we deal with the onboarding code. There is a lot to untangle, since we currently force _all_ users to go through that flow.
**There will be more PRs that touch onboarding-related code, but in an attempt to make these PRs easy to review + QA, I am attempting to keep them small and encapsulated around incremental changes.**
This PR conditionally renders the onboarding task card by checking that a user `saw_onboarding` before rendering the card. On a practical level, this check doesn't do anything for _current Forems_, because every single user is going to be _forced_ through onboarding. So really, this check is redundant, currently.
HOWEVER! I have more code in the pipeline that assumes that Forem creators will _not_ be …
> Conditionally hide onboarding task card

- .travis.yml
Reverts forem/forem#11258 since it deploys I think(waiting to see what happens) the 2 apps in a single job. I would rather have 2 individual sequential jobs then the jobs combined since if one of them fails its harder to tell which one if the deploys are grouped.
> Revert "Deploy In Parallel to Heroku Apps"

- docs/backend/data-update-scripts.md
- lib/generators/data_update/data_update_generator.rb
- lib/generators/data_update/templates/data_update_spec.rb.tt
Quick follow up to #11245 from yesterday, we need the full path for the require, not just the script name.
```diff
-  "20201103042915_backfill_column_for_articles.rb",
+ "lib/data_updates/20201103042915_backfill_column_for_articles.rb",
```
n/a
* Run the generator and make sure the generated spec requires the full script path (`lib/data_updates/<timestamp_<scriptname>`).
> Data update script generator: Use full path instead of filename for require

- app/controllers/listings_controller.rb
- spec/requests/listings_spec.rb
When listing modal is refreshed the date does not appear this PR fixes that.
Closes https://github.com/forem/forem/issues/11261
1. Go to /listings
2. Click on a listing with date. It will open up a modal and it will show the date
3. Now refresh the page
4. The modal will show up but with date
> Fixing date in listing modal

- config/initializers/datadog_apm.rb
I am noticing a lot of little Datadog trace errors and warnings coming from a Forem that is missing a DD_API_KEY. I think this might be due to trying to enable Datadog in the code but then not having a key present for sending the logs to Datadog. This updates the code to only enable Datadog tracing if a DD_API_KEY is present. This also eliminates the need for it to be a production environment to enable Datadog. This could be useful if you want to use a personal Datadog account to test something locally.
> Refactor:Enable Datadog When DD_API_KEY is Present

- app/assets/stylesheets/components/header.scss
This PR fixes hidden progress bar by replacing `--popover` with `--z-popover`
Fix #11293
1. Simulate slow connection on devtools
2. Go to any page with devtools is opened
3. Progress bar should be displayed while next page is loading
> Fix hidden progress bar

- .env_sample
- app/services/edge_cache/bust.rb
- app/services/edge_cache/bust/nginx.rb
- spec/services/edge_cache/bust_spec.rb
This PR goes along with https://github.com/forem/infra/pull/62, which extracts the concept of `openresty_domain` and `openresty_protocol` (currently hard-coded) into a single variable: `openresty_url`. 
This PR uses that new variable in place of the two variables we were using previously.
https://github.com/forem/infra/pull/62
Ensure that Nginx still works with caching/busting with this ENV var, and ensure that the tests pass.
> Use OPENRESTY_URL over protocol + domain

- app/helpers/comments_helper.rb
- spec/factories/articles.rb
- spec/system/user_visits_a_comments_page_spec.rb
We weren't rendering "OP markers" (author identifying flair) on coauthors. This change fixes that!
Closes https://github.com/forem/forem/issues/11128
> Render op markers for coauthors

- app/controllers/page_views_controller.rb
Users complain that view counters don't update. PR #4945 changed how often they are updated. This PR reverts the previous value.
It doesn't solve the issue but it increases the chance that counters are updated.
#4945
#8425
Hard to test since the code relies on `rand`.
> Update page views counters a little bit more often

- app/models/profile_field.rb
- app/services/profile_fields/field_definition.rb
- app/services/profile_fields/import_from_csv.rb
- lib/data/dev_profile_fields.csv
- lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
- lib/tasks/forem.rake
- spec/fixtures/files/profile_fields.csv
- spec/lib/data_update_scripts/prepare_for_profile_column_drop_spec.rb
This PR came out of a discussion (see [conclusion](https://github.com/forem/forem/pull/10707#issuecomment-719141336) in #10707 and some work done in the closed #11110 branch.
1. Adds a new `:settings_only` option to the `display_area` enum.
2. Updates the CSV importer and the DEV profile fields CSV file to add `display_area` .
3. Adds a data update script for ensuring that all DEV fields are current and profiles are really up to date before starting to ignore the columns in the next PR.
#6994 
> Prepare for profile column drop

- app/controllers/api/v0/videos_controller.rb
- app/views/api/v0/videos/index.json.jbuilder
- docs/api_v0.yml
- spec/requests/api/v0/videos_spec.rb
It adds `video_source_url` attribute in API V0 videos index.
Closes #6299
Go to http://localhost:3000/api/videos and check if `video_source_url` is returned.
> Return video_source_url in API V0 Videos index (#6299)

- app/controllers/stories/feeds_controller.rb
- app/services/articles/feeds/large_forem_experimental.rb
- config/field_test.yml
- spec/services/articles/feeds/large_forem_experimental_spec.rb
When looking at the results from our feed experiments, I noticed that the experience level weighting is by far the lowest performer so I decided it was time to remove those ones. You can see the results below. Meanwhile, the tag experiments seem to be doing well so I moved some of the weight from the removed experiments to the tag ones. 
https://github.com/orgs/forem/projects/6#card-48726981
> Refactor:Remove more_experience_level_weight_experiment From Feed Tests

- app/controllers/admin/application_controller.rb
- app/controllers/async_info_controller.rb
- app/views/shell/_top.html.erb
When an admin makes a change, it will be immediately reflected across the site in general, but for existing users with a cached shell top (cached by service workers) will not immediately get the update.
This makes appropriate changes such that a config change will ensure users fetch the new shell. This will help admin UX because they will see the new stuff right away and not think of this as a bug, as it would now with their own page not clearing the cache right away.
Unrelated line I fixed: Removed an old `fb:pages` hardcoded meta tag we no longer user or need. (If for some reason we still need this, we can add it back in as _generalized_ via config, rather than the hardcoded DEV version).
> Update shell version when admin action taken

- app/models/concerns/acts_as_profile_field.rb
When I extracted the `ActsAsProfileField` concern I was a bit sloppy and just popped a `rubocop:disable` on the end of the constant definition. However, when eager loading the app in production you'll see two warnings like this:
```
/home/travis/build/forem/forem/app/models/concerns/acts_as_profile_field.rb:6: warning: already initialized constant WORD_REGEX
/home/travis/build/forem/forem/app/models/concerns/acts_as_profile_field.rb:6: warning: previous definition of WORD_REGEX was here
```
This PR addresses this by making the concern a "traditional" module (not using the `concern ... do` shorthand) and pulling the constant out of the `included` block.
The alternative would have been to change `included` like this:
```ruby
included do |base|
base.const_set(:WORD_REGEX, /\w+/.freeze)
end …
```
> Correctly set constant in including modules

- spec/system/onboardings/user_completes_onboarding_spec.rb
Small cleanup here. We had one spec that was commented out that I found was a [duplicate to another log in spec](https://github.com/forem/forem/blob/master/spec/system/authentication/user_logs_in_with_email_spec.rb#L84) so I went ahead and removed it. I also switched to using the Warden sign_in helper for the other spec since there is no need to test the actual login flow and we will see if that makes it more reliable
> Refactor:Remove Duplicate from Onboarding Specs

- app/views/layouts/_asset_reconciliation.html.erb
In Heroku, `stylesheet_url` and `stylesheet_path` are the same because of the way asset urls work. In Forem Cloud, the `stylesheet_tag` uses the _path_ variation. So this needs to work as such to work properly in Forem Cloud.
> Change from stylesheet_url to stylesheet_path

- lib/tasks/cache.rake
The purpose of this file is to bust the caches of some key semi-static pages when we redeploy the app. Once it is re-fetched it will be cached globally for everyone.
Currently we wait ten minutes, which is good to wait for Heroku's asynchronous restart, but I think waiting that long isn't ideal for Forem Cloud. I created a new version which runs these commands at three intervals: 30 seconds, 3 minutes, and 10 minutes.
The impact of a few extra cache busts will be minimal, but it will help us better deal with cache inconsistencies. If the new site is up in 30 seconds to receive the cache bust on the lastest, that's great. If it's not up and running the new code, we'll try again a couple more times.
I also added the home page bust to ensure we see the latest there quickly on new …
> Bust caches at different intervals on restart

- .github/PULL_REQUEST_TEMPLATE.md
I'm linking to the GitBook generated version (https://forem.gitbook.io/forem-admin-guide/) and not the GitHub repo (https://github.com/forem/forem-admin-guide) but I could see the opposite being better.  Open to suggestions.
This will help us keep the [Forem Admin Guide](https://forem.gitbook.io/forem-admin-guide/) more up-to-date as we make changes.
> Add admin guide to "added to docs?" section of PR template

- app/helpers/admin_helper.rb
- app/helpers/authentication_helper.rb
- app/services/feature_flag.rb
- config/routes.rb
- spec/models/profile_field_group_spec.rb
- spec/requests/admin/admin_portals_spec.rb
- spec/requests/admin/profile_field_groups_spec.rb
- spec/requests/admin/profile_fields_spec.rb
- spec/requests/admin/sidebar_spec.rb
- spec/requests/registrations_spec.rb
- spec/routing/profile_admin_routes_spec.rb
- spec/services/feature_flag_spec.rb
As we introduced the `FeatureFlag` wrapper in https://github.com/forem/forem/pull/8149 we should try to use that around the code instead of directly accessing Flipper. This will help us if we ever have to switch feature flag framework, would also enable us to add metrics on feature flag calls (eg. "how many times do we access flagged features?") and so on.
Note: the API is the same, just use `FeatureFlag` instead of `Flipper` and if anything missing is needed, add it to the wrapper module.
#8149
1. Load the console, try `FeatureFlag.enable(:foobar)` and check with `Flipper.enabled?(:foobar)` that is indeed enabled
1. Do nothing as this is already tested automatically
> Replace calls to Flipper with FeatureFlag

- app/assets/javascripts/utilities/showUserAlertModal.js
Right now the app is not booting locally because `showUserAlertModal.js.erb` requires `SiteConfig` which is not accessible when the app compiles that template on boot. 
This is just an interim solution, we can find a better way to show the mascot in the modal in a separate PR
cc @lisasy @maestromac @nickytonline 
#11344
> Hotfix: Remove mascot from JS template for modals

- app/assets/javascripts/base.js.erb
Links are currently preloaded on mouse hover.
This adds the same functionality but for keyboard focus.
Fixes some issues with links needing 2 hits on return in order to work.
Closes #11372 
1. Navigate any link using the keyboard
2. Press return
3. Link is followed without delay or the need to press return again
> feat: Preload links on focus

- config/environments/production.rb
From SendGrid
> We are emailing to inform you of an upcoming requirement to update your authentication method with Twilio SendGrid to API keys exclusively by December 10th, 2020 in order to ensure uninterrupted service and improve the security of your account. 
This removes the SENDGRID_USERNAME and SENDGRID_PASSWORD ENV variables and only uses the API key. I have updated all Heroku Forems (practicaldev, benhalpern-community, aechive, and cluster-employment) to use API keys. @andygeorge confirmed that there are not usernames or passwords for SENDGRID in the Forem infra inventory so all AWS Forems should be good to go. 
https://github.com/orgs/forem/projects/6#card-49106309
> Bug Fix:Remove Deprecated SENDGRID_USERNAME and SENDGRID_PASSWORD from production.rb

- app/workers/metrics/check_data_update_script_statuses.rb
- config/schedule.yml
- spec/factories/data_update_script.rb
- spec/workers/metrics/check_data_update_script_statuses_spec.rb
I was [recently asked to check all of our Forems](https://github.com/forem/forem/pull/11350#issuecomment-725164177) to see if a DataUpdateScript had succeeded. Since we have 10+ Forems the idea of having to annoy @forem/systems to let me access every single one seemed a bit daunting and unideal. Rather than check each manually I choose to create a scheduled job that will do it for us. This job will run every hour, 30 minutes after the house, and report any failed DataUpdateScripts. It is then our job to look into them and fix them. 
I think after the initial check we could shrink the time limit down even more to a couple of hours to limit the number of scripts we check, but right now I want to make sure the script in question(run on Monday) is included in the first run. …
> Feature:Send Alerts for Failed DataUpdateScripts to Datadog

- app/controllers/admin/configs_controller.rb
- spec/requests/admin/configs_spec.rb
**The issue**:
> As a Forem Admin, I might make a mistake and add erroneous info into the image URL field. This shouldn't break the site.
**The solution**:
This PR adds validations to the `Admin::ConfigsController` that check an image's URL against some regexp to ensure that the image URL is valid before saving the changes to the SiteConfig.
Closes https://github.com/forem/InternalProjectPlanning/issues/249
**To QA this PR, first ensure that you have an admin role, and then please do the following**:
- Navigate to `/admin/config`:
- Navigate to the "Images" section and attempt to update an image with an invalid image URL, such as `![low_res]https://fjhkfhwk.png`. You should be shown an error message: "😭  Image URL must be a valid URL":
- Navigate back to the "Images" section and update …
> Validate Image URLs in SiteConfig

- app/javascript/packs/readingList.jsx
- app/javascript/readingList/readingList.jsx
- app/javascript/searchableItemList/searchableItemList.js
This updates the reading list to get the tags of the articles in your reading list as opposed to filtering by the tags you follow. General consensus among the team was that we should make this change, since the current version (tags you follow) was not really intuitive.
Closes https://github.com/forem/InternalProjectPlanning/issues/240
1. Save some articles from the home page: localhost:3000
2. Go to your reading list: localhost:3000/readinglist
3. See that the proper tags are displayed, and that there are no duplicates
> Filter by tags of reading list items not tags you follow

- app/services/feeds/import.rb
This is already collected here https://github.com/forem/forem/blob/de5122cb52983c24ac92f091e21889a383e89c7d/app/services/feeds/import.rb#L29
This statement is just incorrect :-(
> Remove wrong metric from Feeds::Import

- app/assets/stylesheets/components/modals.scss
As you guys know, while editing a new post, there is a modal box used for demonstrating markdown formats and liquid tags. In Safari, I realized that the scroll bar is overflowing at the bottom of the modal as shown in Screenshot no.1. So, adding "overflow: hidden;" to the class of that modal, which is "crayons-modal__box", fixed the problem. 
I've also checked it on Firefox and Google Chrome and they do not have any bug like this.(Screenshot no.2 and Screenshot no.3)
**Folder location:** `forem/app/assets/stylesheets/components/modal.scss`
<p align="center">Screenshot no.1 - Problem in Safari</p>
<p align="center">Screenshot no.2 - Firefox</p>
<p align="center">Screenshot no.3 - Google Chrome</p>
_You may test the changes by entering to "write a new post page" and clicking on Markdown or …
> Fixed the scroll bar problem in Safari

- lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
- spec/lib/data_update_scripts/prepare_for_profile_column_drop_spec.rb
In #11246 I added a data update script to do two things:
1. Ensure all current DEV profile fields are present so we can drop the columns from `User` and rely on delegation.
2. Migrate the data one more time just in case and compact it (remove `nil` values) while doing so.
The second point wasn't strictly necessary, but it felt better to do this before we drop columns and data is gone for good. Alas the process errored out without any exception **and** the call to `compact` was in the wrong place, so it isn't even easy to see which records were process already. Yeah, me! 👏 🙄 
This PR does the following:
1. Puts the call to `compact` in the correct place. 
2. Explicitly logs errors to Honeycomb and continues after an error.
3. Stores the last processed user id in the Rails cache so if …
> Update data update script

- db/migrate/20201114151157_add_partial_index_to_users_feed_url.rb
- db/schema.rb
Rows with `feed_url` populated are traversed each time the rss/feed reader/import runs, but there's no index on those. We add a partial index as rows with `feed_url` are a tiny percentage of the total (less than 0.7% on DEV for example).
Kudos to @citizen428 for the initial suggestion https://github.com/forem/forem/pull/11234#discussion_r516391885
https://github.com/forem/forem/pull/10998
> Add partial index on users.feed_url

- .rubocop.yml
- lib/data_update_scripts/20200901085230_remove_draft_articles_with_duplicate_canonical_url.rb
- lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
- lib/data_update_scripts/20200910135958_remove_draft_articles_with_duplicate_user_id_title_body_markdown.rb
Some of our SQL scripts do not play nice with `.squish` so I went ahead and removed `.squish` from all the scripts that were failing because of it. I also turned off the Rubocop that enforces its use. 
https://github.com/orgs/forem/projects/6#card-49457249
Copy and paste the SQL commands into a console and watch them run successfully.
> Bug Fix:Update Remove Draft Articles Scripts to not use Squish

- app/controllers/stories/feeds_controller.rb
- app/services/articles/feeds/large_forem_experimental.rb
- config/field_test.yml
- spec/services/articles/feeds/large_forem_experimental_spec.rb
This has been the most recent underperforming experiment in our group so I am removing it and redistributing the weight to other more successful experiments. 
https://github.com/orgs/forem/projects/6#card-48726981
Make sure the Feed page still loads :)
> Refactor: Remove more_tag_weight_more_random_experiment

- app/workers/metrics/check_data_update_script_statuses.rb
As described in #11381, I originally set this at 1 week to figure out if a particular DataUpdateScript had failed. Turns out it did not so now we can set this to something a little shorter. I choose 1 day even though we check every hour so that in the event say Sidekiq goes down or for some reason, the check job doesn't run we can still get alerted of the failure for a while after.
> Optimization:Only Check Past Day for DataUpdateScript failures

- app/views/users/show.html.erb
- docs/technical-overview/architecture.md
- spec/requests/user/user_profile_spec.rb
Small adjustment.
We recently shipped this button which just said "user", but I think adding the user's name here is more human.
It's a small thing and totally cool that we shipped the first copy as something we could later improve on.
> Add username to profile more info button

- app/controllers/admin/configs_controller.rb
- app/helpers/application_helper.rb
- app/lib/constants/site_config.rb
- app/models/site_config.rb
- app/views/admin/configs/show.html.erb
- app/views/articles/index.html.erb
- app/views/chat_channels/index.html.erb
- spec/liquid_tags/tweet_tag_spec.rb
- spec/requests/admin/configs_spec.rb
- spec/requests/stories_show_spec.rb
As mentioned in https://github.com/forem/forem/issues/11449, we currently hardcode some emojis in the `<title>` tags of our site, but that locks in other Forem creators to the hardcoded emojis that we chose 😕 
Instead, we want to allow Forem creators to choose _their own_ emojis to associate with the site (or to not have an emoji at all!). This PR removes the hardcoded emojis and add an optional `community_emoji` field to `SiteConfig`, which can be blank or which a Forem creator can override with their own choice of emoji.
It also removes a hardcoded emoji on the `/connect` page, since associating an emoji with a specific _page_ is a much larger feature and seems like it deserves a product discussion.
Closes https://github.com/forem/forem/issues/11449.
Starting with a fresh …
> Add community_emoji to SiteConfig

- app/assets/javascripts/utilities/buildArticleHTML.js
As mentioned in #11463, [this commit](https://github.com/forem/forem/commit/449cf89737) removed the hidden navigation link from the article HTML. This PR adds it back.
- Keyboard feed navigation: #10468
- No ticket for the bug yet
Navigate the feed up and down with `j` and `k`. It should reach the end of the feed.
> Fix broken article feed keyboard navigation

- app/controllers/search_controller.rb
- app/services/search/user.rb
- config/routes.rb
- spec/requests/search_spec.rb
- spec/services/search/user_spec.rb
For a while many have been asking for an autocomplete functionality for mentions. This provides the backend endpoint to get the job done. When given a username or part of a username it will pass that to Elasticsearch, run a search, and then return all matching usernames in an array.
https://github.com/forem/forem/issues/354
> Feature:Backend Username Search Endpoint for Mention Completion

- lib/data_update_scripts/20201118141822_gradual_article_cache_bust.rb
This is a script proposed to be paired with https://github.com/forem/forem/pull/11283
That PR makes pretty significant changes which could cause inconsistencies in navigation if we do not pair it with a cache-busting approach.
We cannot bust all the site at once, but when we go to merge that I think we need some kind of gradual cachebust.
This would create lots of short running jobs that would gradually run gradually more spaced out over time and be done in a few hours.
This script should be abundantly safe with small communities, but we need something or else there could be stale cache issues. With DEV I think it's a script similar to the manual steps we've taken in the past in similar situations.
> Add article cachebust backoff update script

- spec/models/follow_spec.rb
- spec/models/profile_field_spec.rb
- spec/models/user_spec.rb
If you run `spec/models/user_spec.rb` or any of the other files in this PR you'll notice the following warning:
> Warning from shoulda-matchers:
> 
> You are using `validate_inclusion_of` to assert that a boolean column
> allows boolean values and disallows non-boolean ones. Be aware that it
> is not possible to fully test this, as boolean columns will
> automatically convert non-boolean values to boolean ones. Hence, you
> should consider removing this test.
Thus I'm removing those explicit checks
> Remove boolean checks for validate_inclusion_of in specs

- app/views/mailers/notify_mailer/trusted_role_email.html.erb
- app/views/mailers/notify_mailer/trusted_role_email.text.erb
closes https://github.com/forem/InternalProjectPlanning/issues/345
Update trusted user email copy to enable us to successfully onboard more trusted users. Here are the email previews:
Plain text:
HTML
> Update Trusted User Email Copy

- app/helpers/application_helper.rb
- app/views/podcast_episodes/_podcast_bar.html.erb
We were generating assets path ourselves instead of using `image_tag` with the asset that's already in our asset folder. This is broken in Forem because we don't use Cloudinary there.
n/a
0. Pull down this PR and boot up the app locally.
1. Make sure you have podcasts locally. You need to have developing caching enabled and running sidekiq. 
2. Navigate to any podcast episodes and press play.
3. You should be able to see the volume and volume mute icon.
n/a
n/a
> Replace podcast bar helpers with image_tag

- app/mailers/notify_mailer.rb
- spec/mailers/notify_mailer_spec.rb
Quick Subject line update for the Trusted Mod Email to make the wording and copy more clear and and consistent
> Update trusted role email Subject
