forem/forem

app/controllers/internal/articles_controller.rb

Fix indentation in articles_controller.rb, per RuboCop and Code Climate
n/a
n/a
Actual footage of @benhalpern and I making the same commits at the same instant.

Fix indentation in articles_controller.rb

---

app/controllers/internal/users_controller.rb
app/models/mentor_relationship.rb
app/views/internal/users/show.html.erb
spec/models/mentor_relationship_spec.rb

Add feature to quick match mentors and then be served with a new one right after.

Add automatic random mentee show page after quick match

---

app/views/badges/show.html.erb

Badge page didn't have a title. Now it does! ❤️

Fixed badge page not having a title

---

app/views/mailers/notify_mailer/mentee_email.html.erb
app/views/mailers/notify_mailer/mentee_email.text.erb

Mentee email with copy from original mailchimp emails.
Updated copy of mentee email

Update Mentee Email

---

app/views/mailers/notify_mailer/mentor_email.html.erb
app/views/mailers/notify_mailer/mentor_email.text.erb

Update Mentor Emails with original Mailchimp copy

Update Mentor Email

---

app/services/suggester/users/sidebar.rb

Summary was not selected in API

Add summary to select fields in sidebar follow suggestions

---

app/controllers/internal/users_controller.rb
app/labor/user_similarity.rb
app/views/internal/users/show.html.erb
spec/labor/user_similarity_spec.rb
spec/mailers/notify_mailer_spec.rb

Match mentors more easily by ranking by similarity score 👋

Add similarity score for users

---

app/views/internal/users/show.html.erb

Update link to mentor internal user profile
Update typo in link on mentorship page

Fix Typo in Internal/users

---

app/assets/javascripts/initializers/initializeArticleReactions.js
app/assets/stylesheets/article-show.scss
app/assets/stylesheets/dashboard.scss
app/assets/stylesheets/scaffolds.scss
app/views/articles/show.html.erb
app/views/dashboards/show.html.erb
app/views/layouts/application.html.erb

Revert sticky css stuff and adjust look of the buttons.

Adjust article show view css (revert sticky css)

---

app/views/users/_misc.html.erb

Add missing verb "control"
Capitalize first letter "English"

Fix typo in settings/misc

---

app/controllers/github_repos_controller.rb
app/liquid_tags/glitch_tag.rb
app/services/suggester/users/recent.rb

- Array#select.first is slower than Array#detect.
- Array#shuffle.first is slower than Array#sample.

Performance: replace ruby methods with their faster alternatives

---

app/controllers/internal/articles_controller.rb
app/helpers/feedback_messages_helper.rb
spec/mailers/notify_mailer_spec.rb

- Seems like `.month` doesn't work on floats so switched top X months query in internal/articles to an integer.  
- Also changed some language on the support email template that seems more accurate for members to receive.

Fix internal article query

---

app/views/articles/show.html.erb

Fix sidebar caching issue for articles

---

app/assets/stylesheets/preact/article-form.scss
app/controllers/api/v0/articles_controller.rb
app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/elements/imageManagement.jsx
app/javascript/article-form/elements/moreConfig.jsx
app/policies/article_policy.rb
app/views/articles/_v2_form.html.erb

Adds support for editing things like `canonical_url` and unpublishing posts.
Fixes #967
Fixes #899

Add additional config to v2 editor

---

public/maintenance.html

Resolves a mixed content warning on maintenance page, gif used `http` and not `https`
none

resolves mixed content warning on maintenance.html

---

app/assets/javascripts/base.js.erb

Mute Pusher errors

---

app/assets/stylesheets/sticky-nav.scss
app/labor/markdown_parser.rb
app/models/organization.rb
app/views/articles/_sticky_nav.html.erb
app/views/users/_org_admin.html.erb

Adjust copy for organization settings and fix issue with cta box not showing up as it should.

Add/fix org call-to-action box/copy

---

app/helpers/application_helper.rb
app/models/comment.rb
app/models/html_variant.rb

Small issues with HTML Variant, and other fix with comment busting

Fix html variant image prefix issue + other small fixes

---

Dockerfile

Moved off starefossen's to vanilla Ruby library and manually include node/yarn dependencies. Also moved a few things around.
What I think would be cool is to dynamically update the ruby version in Dockerfile.
Resolves #1007

Update Dockerfile's ruby library

---

app/controllers/organizations_controller.rb
app/services/article_api_index_service.rb

Even though we added new fields to the UI, they weren't allowed.

Fix issue where only approved orgs could make CTAs

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/preact/article-form.scss
app/controllers/api/v0/articles_controller.rb
app/controllers/articles_controller.rb
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/elements/imageManagement.jsx
app/javascript/article-form/elements/moreConfig.jsx
app/models/article.rb
app/models/collection.rb
app/services/article_creation_service.rb
app/views/articles/_collection.html.erb
app/views/articles/_v2_form.html.erb
app/views/articles/show.html.erb
lib/tasks/fetch.rake
spec/models/article_spec.rb
spec/requests/articles_api_spec.rb
spec/requests/articles_create_spec.rb

Users can finally create series. I was probably holding this up by overthinking it with wanting the perfect UI. Finally ripped of the band aid and just did it.
New editor:
Old editor:

Add ability for users to publish series

---

app/controllers/api/v0/articles_controller.rb
app/models/article.rb
spec/models/article_spec.rb
spec/requests/articles_api_spec.rb

First push didn't allow for _removal_ of series.

Allow removal of collection element

---

app/javascript/chat/__tests__/__snapshots__/alert.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/codeEditor.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/compose.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/githubRepo.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/view.test.jsx.snap
app/javascript/chat/__tests__/alert.test.jsx
app/javascript/chat/__tests__/codeEditor.test.jsx
app/javascript/chat/__tests__/compose.test.jsx
app/javascript/chat/__tests__/githubRepo.test.jsx
app/javascript/chat/__tests__/message.test.jsx
app/javascript/chat/__tests__/userDetails.test.jsx
app/javascript/chat/__tests__/view.test.jsx
docs/testing.md

Adding some testing coverage for the Preact components for Dev Connect using preact-render-spy. Includes snapshot testing, component testing with stubbed functions. 
N/A so far
Just added preact-render-spy to the testing page

Testing Preact components for Dev Connect

---

app/javascript/packs/githubRepos.jsx

Fix issue in previously merged GithubRepo PR. #986

Fix issue where Instantclick navigation fails

---

app/views/articles/_sidebar.html.erb
app/views/pages/sponsors.html.erb

Add Raygun sponsor

---

app/liquid_tags/codesandbox_tag.rb
app/views/pages/_editor_guide_text.html.erb

Add codesandbox support

---

app/views/pages/_editor_guide_text.html.erb

Fix typo for codesandbox and replit

---

app/labor/badge_rewarder.rb
lib/tasks/fetch.rake
spec/labor/badge_rewarder_spec.rb

Rake task to award fab 5 top commenter award. 👀 @pkfrank 
Pattern matching pretty hard rn

Add Fab Five BadgeRewarder + Rake Task

---

public/apple-app-site-association

- [] Bug Fix
Add necessary file for future universal linking.

Add Apple deep link page

---

app/liquid_tags/codepen_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/codepen_tag_spec.rb
spec/support/fixtures/approvals/codepen_liquid_tag.approved.html

Adding default-tab parameter to codepen embed
Still need to update help page before ready
#869

codepen embed add default-tab param

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/more-articles.scss
app/views/additional_content_boxes/_article_content_area.html.erb
app/views/additional_content_boxes/_article_followable_area.html.erb
app/views/articles/_actions.html.erb
app/views/articles/index.html.erb

Change footer to tan. I think it looks pretty good this way, and also makes it seamless for app.

Adjust article actions footer

---

app/observers/application_observer.rb

This should happen asynchronously to not slow down comment creation

Add delay to slackbot ping

---

app/views/articles/_sidebar_additional.html.erb

Limit number of posts in top sidebar thing to 5. Removed some code we're not using to eliminate a couple queries. Can be added again later if/when needed.

Modify number of posts in home sidebar tags

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/assets/javascripts/utilities/buildArticleHTML.js.erb
app/assets/stylesheets/articles.scss
app/assets/stylesheets/sticky-nav.scss
app/assets/stylesheets/variables.scss
app/controllers/async_info_controller.rb
app/models/article.rb
app/models/user.rb
app/views/articles/_main_stories_feed.html.erb
app/views/articles/_single_story.html.erb
app/views/articles/_sticky_nav.html.erb

When article is published under org, it now shows up on feed as such

Add organization to feed and adjust page styling

---

docs/installation/linux.md
docs/installation/mac-os.md
docs/installation/windows.md

Fixing typos as well as wording in the installation docs.

Fix typos and wording in installation docs.

---

app/views/articles/_sidebar.html.erb
app/views/articles/_single_story.html.erb
app/views/layouts/_footer.html.erb
app/views/pages/information.html.erb

Removed issue where org name was hardcoded in one place instead of dynamic by accident. Also removed sustaining membership info to ensure we fit Apple guidelines for now. We can probably add it back in shortly once we make sure we're in the clear.

Fix typo and (temporarily) remove sustaining membership from some views

---

app/black_box/google_analytics.rb
app/labor/article_analytics_fetcher.rb
app/views/dashboards/_dashboard_article.html.erb
app/views/dashboards/show.html.erb

This is going to be generally available shortly:

Finalize new analytics style

---

app/assets/stylesheets/comments.scss
app/controllers/internal/users_controller.rb
app/decorators/comment_decorator.rb
app/models/comment.rb
app/views/comments/_comment.html.erb
app/views/internal/users/edit.html.erb
spec/rails_helper.rb

This adds indication of community indications of code-of-conduct validations. Some comments have a gray area in terms of removal, or admins are not able to respond quickly enough. This gives a bit more non-destructive agency to those with community moderation privileges.

Add sloan as marker of low quality and adjust banishment logic

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/assets/javascripts/initializers/initializeTouchDevice.js
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/top-bar.scss
app/views/layouts/_nav_menu.html.erb

Remove harmful `outline: 0` from most of the site. Still used in certain inputs for now. Will work to make better in future.

Remove outline: 0 and add keyboard accessibility for nav menu

---

app/controllers/stories_controller.rb

We want to hide posts deemed low quality from several different views. This plops this check in a couple places it was missing.

Add score minimum to a couple missing places

---

app/views/internal/feedback_messages/index.html.erb

Minor addition to internal/reports

Add check for whether reactable exists in internal/reports

---

CONTRIBUTING.md

Fixed  a typo in CONTRIBUTING.md

fix a typo in CONTRIBUTING.md

---

app/liquid_tags/stackblitz_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/stackblitz_tag_spec.rb

New Stackblitz liquid tag. Adds usage instructions to editor guide.
Meant to do this during Hacktoberfest, but better late than never! 😄 
Resolves #206

Add stackblitz support

---

app/labor/notification_counter.rb
app/views/notifications/_aggregated_reactions.html.erb
app/views/notifications/_article.html.erb
app/views/notifications/_badgeachievement.html.erb
app/views/notifications/_comment.html.erb
app/views/notifications/_reaction.html.erb
spec/requests/notifications_spec.rb

Make reads controller async and sanitize notification titles

---

app/assets/javascripts/initializers/initNotifications.js
app/controllers/notifications_controller.rb

Small fix to speed up inefficient query, for now.

Lessen amount of notifications queried slightly to improve performance

---

app/assets/javascripts/initializers/initNotifications.js
app/assets/javascripts/serviceworker.js.erb
app/assets/stylesheets/articles.scss
app/assets/stylesheets/user-profile-header.scss
app/controllers/comments_controller.rb
app/controllers/notifications_controller.rb
app/models/notification.rb
app/views/articles/_sidebar.html.erb
app/views/notifications/_aggregated_reactions.html.erb
app/views/notifications/_comment.html.erb
app/views/notifications/index.html.erb
config/routes.rb

Small adjustments in how notifications are displaying, _plus_ new notification filters.

Fix small details in notification results and add filtering

---

app/assets/stylesheets/articles.scss
app/controllers/notifications_controller.rb
app/views/notifications/index.html.erb

Fix one query issue and a couple pixel design change

Small notification update

---

app/javascript/src/utils/getUnopenedChannels.jsx
app/models/message.rb

Small fix (not really a fix) that might make the hanging channel thing less likely to show up

Fix hanging /connect notification issue

---

app/controllers/notifications_controller.rb
app/views/notifications/_notifications_list.html.erb
app/views/notifications/_reaction.html.erb

There was an issue where single reactions were not showing up properly due to some logic issues. This should fix it.

Fix notification logic bug

---

app/lib/redcarpet/render/html_rouge.rb
spec/features/user_uses_the_editor_spec.rb

Fixes #1179 by stripping tags in generation of `name` tags in headers.

Fix parsing error in header tags.

---

app/assets/javascripts/initializers/initNotifications.js

Small bug which did not load in interactive behavior in some contexts with new notifications implementation.

Fix notification pagination reaction issue

---

app/views/articles/index.html.erb

`rel='me'` is used on hyperlinks from one page about a person to other pages about that same person. (http://microformats.org/wiki/rel-me)
`rel='me'` is supported on other social sites, such as Twitter and GitHub. Thought it might have a place here on DEV too.

Adds rel='me' to profile links.

---

app/models/notification.rb
spec/models/notification_spec.rb

Quick fix issue where some notifications were being sent.

Add guard to stop negative notifications

---

docs/get-api-keys-dev-env.md

Just removing Stream from API key set up in the documentation.

Remove Stream from docs.dev

---

app/models/notification.rb
app/services/read_notifications_service.rb

We had attempted to remove notifications on lock screen by sending a REMOVE_NOTIFICATIONS message but it doesn't seem to be working properly. This removes it, as it's better to have no behavior than wrong behavior here.

Removing clear notifications attempt

---

app/controllers/api/v0/articles_controller.rb

Replace long string with array and join

---

app/models/mentor_relationship.rb
app/views/internal/users/show.html.erb
app/views/mailers/notify_mailer/mentor_email.html.erb
app/views/mailers/notify_mailer/mentor_email.text.erb
spec/models/mentor_relationship_spec.rb

Add functionality to mentor matching page to show more info on mentee, show more possible matches and show more

Update mentor matching page

---

app/views/pages/code_of_conduct.html.erb

Updates the code of conduct page on dev.to to be more specific and clear.

Code of Conduct Update

---

app/assets/javascripts/initializers/initializeReadingListPage.js.erb
app/views/reading_list_items/index.html.erb

Fix reading list styling issues on mobile/also reading list was breaking at over 1000 items.

Fix readinglist issue

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/views/dashboards/show.html.erb

Add language for "anti-following" tags. Also removed anti-followed tags from left sidebar.

Add anti-follow language

---

app/lib/constants.rb

- [ x] Feature
I've added the infosec.exchange domain to the whitelist for mastodon instances. 
- [ x ] no documentation needed

Add infosec.exchange to mastodon whitelist.

---

app/assets/stylesheets/articles.scss

- [ x] Bug Fix
Update the contrast of the save button to improve it's accessibility.
#1204
Top left: Previous save button background color
Bottom left: Previous save button background color on hover
Top right: Updated save button background color
Bottom right: Updated save button background color on hover
- [x ] no documentation needed
Feeling awesome since it's my first PR to dev.to repository.

Change save button contrast

---

app/assets/stylesheets/user-profile-header.scss

Fixes the profile follow button issue.
Screenshot:

Remove some unnecessary CSS

---

app/assets/stylesheets/article-show.scss

Fix css z-index style bug on series indicator

---

.github/stale.yml
app/controllers/internal/users_controller.rb
app/services/moderator/banisher.rb
spec/controllers/internal_users_controller_spec.rb

Revert banisher

---

app/lib/constants.rb

Adds toot.cafe to the Mastodon whitelist.
* Issue #1267 
* https://dev.to/nickytonline/comment/7bg0

added toot.cafe to Mastodon whitelist.

---

app/models/comment.rb

Fixes an issue where posting a comment and refreshing the article would seem like your comment never posted.

Synchronously bust cache after save for comments

---

app/lib/constants.rb

This adds [radical.town](https://radical.town) to the list of allowed Mastodon instances.

Add "radical.town" to Mastodon list

---

app/javascript/chat/githubRepo.jsx

remove unnecessary console log that takes up too much console space on travis

clean up consolelog

---

app/assets/javascripts/base.js.erb
app/assets/javascripts/initializers/initializeArticleReactions.js
app/assets/javascripts/initializers/initializeReadingListIcons.js
app/assets/javascripts/lib/pulltorefresh.js
app/assets/javascripts/utilities/sendHapticMessage.js

This adds the code to trigger haptic feedback such as vibration in different parts within the app when it is in the context of iOS.

Add haptic message for iOS feedback

---

app/lib/constants.rb

Add ruby.social to ALLOWED_MASTADON_INSTANCES

---

app/javascript/chat/chat.jsx

Whenever any message is highlighted or even clicked, the component updates thus not allowing words to stay highlighted. This happens because every message checks for `onContentTrigger={this.triggerActiveContent}` where `setState` happens every-time the function runs.
To avoid this, I've moved `setState` into the if statements in `triggerActiveContent` so that the state and component only update when actual content is being triggered. 
aims to address issue #568

connect highlight messages

---

app/views/users/_membership.html.erb

Links to the appropriate item in the shop.
related to #1249 
N/A

Fix member's only sticker pack link

---

app/liquid_tags/tweet_tag.rb

Fixes issue where quoted text in tweets is missing

Fix twitter missing quote text

---

app/views/users/_meta.html.erb
app/views/users/show.html.erb
spec/features/user/view_user_index_spec.rb

Fixing a previous PR which had accidentally removed this and we didn't catch it.

Add missing title attribute to user profile page

---

app/views/admin/application/_collection.html.erb
app/views/admin/application/index.html.erb

This should fix admin index and show pages, but not sure if it'll fix the CSRF issue. Going to make a second PR for that, if it's still an issue.

Use latest admin page views from gem

---

app/views/organizations/show.html.erb
spec/features/organization/user_views_an_organization_spec.rb

Adds the title to organization profile page. Also added a test for it.

Add title to organization profile page

---

app/labor/assign_tag_moderator.rb

Fixes tag moderation slug typo

---

app/labor/assign_tag_moderator.rb
spec/labor/assign_tag_moderator_spec.rb

Third time's the charm. Fixing the specs that broke from earlier typo fixes.

Fix tag mod spec

---

app/labor/assign_tag_moderator.rb
spec/labor/assign_tag_moderator_spec.rb

Well, at least this was a more substantial issue to be fixed than a bunch of typos... 
Adding a statement that doesn't add the user to the tag moderator channel if they are already in the channel.

Include conditional for adding tag mods to connect channel

---

app/views/pages/tag_moderation.html.erb

Based on some initial chatter in the tag moderators connect channel, thought these notes would be helpful.

Add more details about tag moderation

---

docs/frontend.md

I realized we never added browser support to docs. We had an internal wiki.

Add browser support to docs [skip ci]

---

app/assets/stylesheets/top-bar.scss

Adding both --theme-top-bar-search-color and --theme-top-bar-search-background to change the colour and background colour of the search box.
#1104 and #1377

Adding --theme-top-bar-search-*

---

app/assets/stylesheets/notifications.scss

The background colour is different, by default, on the notification page so I missed it on my initial sweep
#1104 #1377 and #1306

Add --theme-background to notifications page

---

app/views/users/_org_admin.html.erb

Fixes Organization Settings CTA link url label
#1370

Fixes Organization Settings CTA link url label (#1370)

---

app/assets/stylesheets/top-bar.scss

Adding `--theme-top-bar-color` to change the colour of the text in the nav bar
Currently, this only changes the colours of the icons fill.
#1104 and #1377
At some point, we'll need to write up a list of all the variables and what they do.

Adding --theme-top-bar-color

---

app/labor/badge_rewarder.rb
spec/labor/badge_rewarder_spec.rb

Modify birthday badge rewarder method to also reward badges for sophomore DEVs.
Bonus: Removed silly hardcoded ID hack.

Add two-year-club auto-rewarder

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/article_form.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/comments.scss
app/assets/stylesheets/ltags/DevCommentTag.scss
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/top-bar.scss

Make IE look alright again.
Won't be theme-able but will at least work.
#1377

CSS Variables: Support for IE

---

app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/top-bar.scss

Adding both --theme-top-bar-write-color and --theme-top-bar-write-background to change the text/border colour and background colour of the write a post button
#1377

Added --theme-top-bar-write-*

---

app/assets/stylesheets/comments.scss

The background colour tag is different, by default, on the comment page so I missed it on my initial sweep
#1377

Add --theme-background to comments page

---

app/assets/stylesheets/scaffolds.scss

Adding `--theme-color` to change the colour of the text in the body
#1377

Adding --theme-color

---

app/javascript/article-form/elements/imageManagement.jsx

I was going to take a stab at https://github.com/thepracticaldev/dev.to/issues/1313 (this is how I found out about https://github.com/thepracticaldev/dev.to/issues/1389) to see if I could get a work in progress quickly.
I don't really know React/Preact but I was trying to integrate https://github.com/nkbt/react-copy-to-clipboard, then I realized is not based on the new async Clipboard API, see comment https://github.com/thepracticaldev/dev.to/issues/1313#issuecomment-448868132, and since I'm not familiar with the frontend framework I stopped short of trying to create a new "Copy To Clipboard" component which uses the new async API and defaults to execCommand.
In the meantime I'm contributing a cleanup of the image management file (a mix of prettier and me destructuring and specifying …

Cleanup Image management file

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/dashboard.scss
app/assets/stylesheets/index-comments.scss
app/assets/stylesheets/ltags/UserTag.scss
app/assets/stylesheets/preact/article-form.scss
app/assets/stylesheets/sticky-nav.scss

Box-shadow settings for articles and nav-elements
#1377

Add --theme-container-box-shadow

---

app/controllers/api/v0/articles_controller.rb
spec/requests/articles_api_spec.rb

Move from calling `current_user` directly to creating a `@user` reference. Will allow for easier API key integration.

Refactor articles api controller

---

app/helpers/application_helper.rb
app/views/articles/index.html.erb
app/views/articles/tags/_meta.html.erb

This PR fixes the page titles of 'Latest' and 'Infinity' posts pages. It also uses the capitalized version of the tag name in the meta tags as it looks better IMO (I can change it back if you guys don't prefer it).
Fixes https://github.com/thepracticaldev/dev.to/issues/1316
/cc @Zhao-Andy

Fix page titles on Latest and Infinity posts pages

---

app/assets/stylesheets/ltags/LiquidTags.scss
app/assets/stylesheets/ltags/TagTag.scss
app/liquid_tags/tag_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/tag_tag_spec.rb

Add tag liquid tag to posts.
`{% tag git %}`

Create tag liquid tag

---

app/observers/reaction_observer.rb

Remove unnecessary variable assignment left over from a previous refactor.
[![smurf sweeping animation](https://media.giphy.com/media/5t1YusAYxmRn474Sid/giphy.gif)](https://gph.is/2KE6mRn)

Remove unnecessary variable assignment

---

app/views/layouts/_footer.html.erb
app/views/users/_profile.html.erb

Updated Copyright year from 2018 to 2019
https://twitter.com/bendhalpern/status/1079909285960867840
This is my very first PR ^_^ .

updated copyright year to 2019

---

app/views/articles/_sidebar.html.erb
app/views/pages/sponsors.html.erb

Swap Triplebyte with Twilio sponsors

---

app/services/user_role_service.rb

- Rescues `ActiveRecord::RecordNotFound` exception instead of `StandardError` in `UserRoleService#update_tag_moderators`
- Replaces `!blank?` method call with `present?`

Minor refactor

---

app/controllers/api/v0/articles_controller.rb
app/helpers/application_helper.rb
spec/requests/internal_reactions_spec.rb
spec/support/omniauth_macros.rb

Fix Rubocop offenses

---

app/models/comment.rb

Removes a commented out debug statement

Remove debug line

---

app/assets/stylesheets/articles.scss
spec/features/user_delete_a_comment_spec.rb

Add list-style to Widget

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/index-comments.scss
app/assets/stylesheets/sticky-nav.scss

Add the --theme-container-border variable for styling.
#1377

Add --theme-container-border

---

app/models/comment.rb
app/views/articles/_org_branding.html.erb
app/views/articles/show.html.erb
app/views/comments/_comment.html.erb

Broaden cache surface so that there are fewer cold cache hits on article comment trees.

Improve caching on article show view

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/dashboard.scss
app/assets/stylesheets/footer.scss

A few more places to be updated by --theme-container-box-shadow
#1377

Add --theme-container-box-shadow places missed

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/sticky-nav.scss

Add --theme-container-color for theming all containing elements
#1377

 Add --theme-container-color

---

app/assets/javascripts/initializers/initializeArticleReactions.js
app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/assets/stylesheets/comments.scss
app/assets/stylesheets/scaffolds.scss
app/views/articles/show.html.erb
app/views/comments/_comment.html.erb
app/views/comments/_comment_proper.html.erb

Allow users to toggle comments.
Closes #173

Add details to toggles and modify some styling

---

app/policies/article_policy.rb
app/policies/user_policy.rb

Allow default admin access to :admins

 Update dashboard_show admin permissions

---

app/assets/stylesheets/comments.scss

Fix issue where user select is too broad.

Fix user-select issue in comments

---

README.md

Add myself to the core contributors! 🎉

add myself to the core contributors

---

docs/get-api-keys-dev-env.md

Resolved #1497 on [Getting API Keys for Dev Environment](https://docs.dev.to/get-api-keys-dev-env/).
The [documentation](https://docs.dev.to/get-api-keys-dev-env/) for getting the API keys for DEV development was outdated. New questions and steps appeared in time. I updated the steps, questions, and screenshots.

Update the installation documentation

---

app/views/internal/users/show.html.erb

Updates query so only mentors with descriptions appear in internal/users/unmatched_mentees
#1454

Update unmatched mentor query

---

app/liquid_tags/raw_tag.rb
spec/features/user_logs_in_with_twitter_spec.rb

Fix accordingly to the rubocop config.

Rubocop fixes

---

app/controllers/omniauth_callbacks_controller.rb
app/services/authorization_service.rb

This adds some logging info to our sign in/up process in case something fails.

Add logging info in case sign in fails

---

app/assets/javascripts/utilities/buildArticleHTML.js.erb

Fix issue with reading time showing up on users in search

Fix search page reading time issue

---

spec/requests/feedback_messages_create_spec.rb

Added a spec for feedback messages controller.

Add spec for invalid captcha

---

app/controllers/api/v0/follows_controller.rb
spec/requests/follows_api_spec.rb

This reduces the number of queries in the onboarding bulk-follow from n+1 (up to 50) to just 1.

Reduce queries in bulk follow

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/black_box/black_box.rb
app/controllers/stories_controller.rb
app/services/article_api_index_service.rb
spec/factories/articles.rb
spec/features/homepage/user_visits_homepage_articles_spec.rb

This will make it less likely for super popular stuff to overstay its welcome. That is always a balancing act.
Also introduced a bit of additional randomness which should make the feed appear more fresh.

Improve feed and add more randomness

---

app/liquid_tags/codepen_tag.rb

Fixed bug that allows XSS with the codepen embed. See #1577 for full details.
Resolves #1577

Fixed bug that allows XSS with the codepen embed.

---

app/assets/stylesheets/article-show.scss

This removes unnecessary CSS property.
https://github.com/thepracticaldev/dev.to/blob/b8117775e3c17d08096962deb5f4cc2c977d03c9/app/assets/stylesheets/article-show.scss#L306-L308

Remove unnecessary CSS property

---

Procfile

Fixing mistake in procfile with adding pgbouncer

Update procfile for pgbouncer

---

app/controllers/stories_controller.rb
app/views/articles/index.html.erb
app/views/articles/search.html.erb
app/views/articles/tag_index.html.erb
app/views/articles/tags/_main_feed.html.erb
app/views/organizations/_main_feed.html.erb
app/views/organizations/show.html.erb
app/views/stories/_main_stories_feed.html.erb
app/views/stories/_sign_in_invitation.html.erb
app/views/users/_main_feed.html.erb
app/views/users/show.html.erb
spec/features/articles/user_visits_articles_by_tag_spec.rb
spec/features/homepage/user_visits_homepage_articles_spec.rb
spec/features/organization/user_views_an_organization_spec.rb
spec/features/shared_examples/no_sign_in_invitation.rb
spec/features/shared_examples/shows_sign_in_invitation.rb
spec/features/user/view_user_index_spec.rb
spec/rails_helper.rb

- separated stories `main_feed`'s (articles by tag, organization show, user show, homepage)
- removed unneeded variables from the stories controller
- refactored stories views a bit
- added more stories specs

Refactored stories views

---

app/labor/cache_buster.rb
app/views/articles/show.html.erb

This should modestly improve performance.
WIP because I want to sanity check in the morning

Cache collection so it doesn't have to be re-fetched

---

app/labor/cache_buster.rb
app/views/articles/show.html.erb

Unforeseen caching issues with this one. Removing makes sense.

Remove article collection area caching

---

app/views/articles/_actions.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/articles/show.html.erb

A few small optimizations on a key path page.

Add a couple cache optimizations and query guards

---

app/models/comment.rb
app/views/articles/_sticky_nav.html.erb

Make comment not touch article and add caching to stickies

Modify side stickies and comment.rb caching/touching

---

app/controllers/stories_controller.rb
app/views/articles/_sidebar_additional.html.erb

Adds some caching to some areas that do not need to refresh _every time_ the feed changes on the home page.

Add additional home page caching

---

app/controllers/omniauth_callbacks_controller.rb

This changes updates the formatting of failed OAuth requests for Timber to log properly.

Use proper formats for env hash variables

---

app/labor/article_analytics_fetcher.rb

Add a few more occasional fetches to complement existing fetches.
closes #1600

Add occasional random fetches to article page_views_count

---

config/initializers/liquid.rb

Enable require_dependency for Liquid tags

---

app/controllers/internal/articles_controller.rb
app/models/article.rb
app/views/internal/articles/_individual_article.html.erb

Adds an input to internal/articles to update author id. I think it's worth moving some of these items to its own /edit page eventually the way we do for more destructive changes w/ internal/users.

Adds internal/articles input to update author

---

app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

Modify org admin logic for changing article author

---

app/controllers/internal/users_controller.rb
app/services/moderator/banisher.rb
app/views/internal/users/edit.html.erb
app/views/internal/users/index.html.erb
app/views/internal/users/show.html.erb
config/routes.rb
spec/controllers/internal_users_controller_spec.rb

- Allows super admins to delete users from internal/users/edit
- Allows super admins to banish users regardless of their existing activity
- Allow super admins to unban users from internal/users
- Hide banned mentors/mentees from internal/users/unmatched_mentee
- Tweak some styling for these additional features
- Add some specs

Delete User Functionality

---

app/controllers/stories_controller.rb

Showing a few less comments on the first page should not negatively affect user experience and will have a good impact on performance.

Lower number of comments showing on first page of article show

---

app/controllers/follows_controller.rb

This `.save` serves no purpose that I can tell of and slows down the action.

Remove unnecessary save from follows controller

---

app/controllers/api/v0/articles_controller.rb
app/controllers/articles_controller.rb
app/policies/article_policy.rb
spec/policies/article_policy_spec.rb

Fix logic bug introduced in moving logic around. This checks if org admin has appropriate privilege within controller.

Move org admin privilege check into controller

---

app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/views/comments/settings.html.erb
app/views/layouts/_styles.html.erb

Noticed a few spots that needed either style or copy tweaks, including that initially-generated comments still had down-chevron instead of three dots.

Small copy/styling tweaks in comment area

---

app/controllers/articles_controller.rb

Fix bug where user could be redirected to wrong post

Fix article taken redirect issue

---

app/liquid_tags/stackblitz_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/stackblitz_tag_spec.rb

I refactored the stackblitz liquid tag to make it more consistent with other tags but also added the ability to choose a default view.

Coding style consistency (stackblitz liquid tag)

---

app/labor/badge_rewarder.rb
lib/tasks/fetch.rake
spec/labor/badge_rewarder_spec.rb

Add  streak badges comparable with other badge-rewarding algorithms.

Add writing streak badge rewarding algorithm

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/assets/stylesheets/article-show.scss
app/controllers/html_variants_controller.rb
app/controllers/stories_controller.rb
app/models/html_variant.rb
app/policies/html_variant_policy.rb
app/views/articles/_actions.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/html_variants/_form.html.erb
app/views/html_variants/_page_styles.html.erb
app/views/html_variants/_single_html_variant.html.erb
app/views/html_variants/index.html.erb
app/views/html_variants/show.html.erb
spec/requests/html_variants_spec.rb
spec/requests/stories_show_spec.rb

This PR adds the ability to test community join call-to-actions below articles, in addition to the sidebar. It will only show one or the other, not both.

Add below-article html variant

---

app/views/articles/_sticky_nav.html.erb
app/views/articles/show.html.erb

Fix logic to make sure HTML variant only shows up in one place on post. Minor issue relating to new HTML Variant stuff but nothing too big of a deal either way.

Modify sidebar cache

---

app/controllers/internal/users_controller.rb
app/views/internal/users/edit.html.erb

- Fixed banish permissions based on user role
- Fix dialog confirmation so it fires for banish + delete
- Update flash notice with user email and id for reference.

Fix conditional so super admins can ban older spammers

---

app/services/user_role_service.rb

- `.find_each` -> `.each` when looking up users to add as mods, since its a simple array and not an ActiveRecord object.

Fix /admin tag moderator update

---

app/views/articles/_sticky_nav.html.erb

Small performance adjustment. Fewer cache misses with this value.

Modify cache key for article-sticky-nav-articles

---

.travis.yml
app/labor/article_analytics_fetcher.rb
spec/features/articles/user_deletes_an_article_spec.rb
spec/features/articles/user_visits_articles_by_tag_spec.rb
spec/features/homepage/user_visits_homepage_articles_spec.rb

Fix inconsistent specs

---

app/controllers/internal/users_controller.rb
app/views/internal/users/index.html.erb

Allows admins to filter by user fields and roles.

Add search filtering for internal/users

---

app/labor/cache_buster.rb
app/views/articles/_sidebar_additional.html.erb

I noticed we're leaking the wrong "timeframe" occasionally. This fixes that and makes some other small modifications

Modify cache on home page

---

package.json

Husky is changing how it's precommit or any hook runs. The current way is being deprecated. This is the new way for the config.
```
// package.json
{
"husky": {
"hooks": {
"pre-commit": "npm test",
"pre-push": "npm test",
"...": "..."
}
}
}
```

Upgraded husky config.

---

app/services/moderator/banisher.rb

- Sets old_username so cache busts
- Saves old_username in case we need to reference in the future

Clear profile cache on banish

---

docs/vocabulary.md

We had created this vocabulary modeled after how Shopify does things but it seemed like we always felt the scale was non-intuitively backwards. This flips the severity levels so 5 is worst instead of 1 being worst.

Change issue level to be more intuitive [skip ci]

---

docs/get-api-keys-dev-env.md

* Updated the grammar and punctuation for 'Getting API Keys for Dev Environment.'
* Corrected the pairing of the API keys for Twitter with the correct `ENV` variables to match the image in the docs.

Correct grammar and punctuation in 'Getting API Keys for Dev Environment' [skip ci]

---

app/models/user.rb
app/services/moderator/banisher.rb
app/views/internal/users/edit.html.erb

- Fix previous typo.. so we bust cache on /username not /name
- Display whether or not a user has been banished on internal/users/edit

Fix Banisher Updates

---

app/controllers/stories_controller.rb
app/models/article.rb
app/services/article_api_index_service.rb
app/services/suggester/articles/classic.rb
app/views/articles/tags/_sidebar.html.erb
app/views/stories/_main_stories_feed.html.erb
config/sitemap.rb
spec/features/articles/user_visits_articles_by_tag_spec.rb

Move query inside fragment cache and remove outdated hiring tag filter.

Remove unnecessary queries

---

lib/tasks/fetch.rake

Bump hardcoded memcache limit we allow before flushing

Modify memcache hardcoded limit

---

app/views/articles/_badges_area.html.erb

I noticed the badge images don't display a title, so I made this small change

Add title to badge images

---

app/controllers/internal/tags_controller.rb
app/labor/assign_tag_moderator.rb
app/models/tag.rb
app/services/user_role_service.rb
app/views/internal/tags/index.html.erb
app/views/internal/tags/show.html.erb
app/views/internal/users/index.html.erb
app/views/layouts/internal.html.erb
spec/labor/assign_tag_moderator_spec.rb

On Tags: 
- Moved editing tags to internal/tags/:Id
- Added editing for aliases and tag moderators to internal/tags/:id
- **When adding a tag moderator to a tag, the user will now automatically receive an email.**
- Added search/pagination to internal/tags index and improved styling/info displayed
On Users:
- Added more info on user index

Enhance Internal Index Pages

---

app/labor/badge_rewarder.rb
spec/labor/badge_rewarder_spec.rb

Added 3 year anniversary badge, I hope to get this badge some day 😉 
Btw this is the very first time I ever did anything in Ruby so please let me know if I did anything wrong.
Closes #1562

Added 3 year anniversary badge

---

app/assets/javascripts/initializers/initializeAdditionalContentBoxes.js
app/controllers/additional_content_boxes_controller.rb
app/controllers/followed_articles_controller.rb
app/labor/article_suggester.rb
app/models/tag.rb
app/services/suggester/articles/boosted.rb
app/services/suggester/articles/classic.rb
app/services/suggester/articles/high_quality.rb
app/views/additional_content_boxes/boxes.html.erb
app/views/articles/show.html.erb
app/views/articles/tags/_sidebar.html.erb
db/migrate/20190206164319_add_timestamps_to_tags.rb
db/schema.rb
spec/models/tag_spec.rb
spec/requests/additional_content_boxes_spec.rb
spec/requests/tags_spec.rb
spec/services/suggester/articles/boosted_spec.rb
spec/services/suggester/articles/classic_spec.rb

This simplifies the queries in `additional_content_boxes` for better performance. Also adds caching to tag index to avoid need for repeated queries.
Added linting as well.

Improve performance for additional content boxes and tags index

---

app/views/pages/terms.html.erb

Updated the `/terms` page with new Content Policy language

Update terms with content policy

---

app/views/articles/_sidebar.html.erb
app/views/pages/sponsors.html.erb

- Updated DigitalOcean tagline/link
- On homepage and sponsors page

Update DigitalOcean links/tagline

---

app/controllers/articles_controller.rb
app/views/articles/feed.rss.builder

Small optimization to lessen memory footprint

RSS feed optimizations

---

app/views/users/_sidebar.html.erb
app/views/users/show.html.erb

Fix bug where users with same `profile_updated_at` share the same fragment cache.

Fix profile cache leak issue

---

app/controllers/internal/users_controller.rb
app/views/internal/users/show.html.erb

- Updates cache on `user.trusted` if their trusted privileges are toggled
- Removes timestamp from 'current roles' in internal/users
- Show which tags a user is moderating

Update 'trusted' cache when updating role

---

app/models/article.rb

Fix mistaken cloudinary_video_url in article

---

.travis.yml
app/models/article.rb
spec/models/article_spec.rb

19:1 should be 19:01 when displayed in time. Also adds ffmpeg to travis.

Add padding to video duration

---

app/views/articles/_single_story.html.erb
app/views/stories/_main_stories_feed.html.erb

Add additional location for video to show up in feed.

Add video to additional home feed context

---

app/javascript/chat/content.jsx
app/javascript/chat/githubRepo.jsx

Add sanitization to marked (already done on backend)

add sanitization to github on chat

---

app/views/pages/faq.html.erb

Fix typo on faq page

---

app/controllers/async_info_controller.rb
app/controllers/push_notification_subscriptions_controller.rb
spec/decorators/podcast_episode_decorator_spec.rb
spec/requests/api/v0/github_repos_spec.rb
spec/requests/article_mutes_spec.rb
spec/requests/push_notification_subscriptions_spec.rb
spec/services/article_with_video_creation_service_spec.rb
spec/services/moderation_service_spec.rb

Up our test coverage a bit
n/a
n/a

Add more test coverage

---

app/views/pages/badge.html.erb

Add Google Analytics to /badge

---

app/views/badges/show.html.erb

Only contained 1 small linting error.
#1842

Fix linting issues in app/views/badges

---

app/views/blocks/_actions.html.erb
app/views/blocks/_form.html.erb
app/views/blocks/edit.html.erb
app/views/blocks/index.html.erb
app/views/blocks/new.html.erb
app/views/blocks/show.html.erb

Fix linting issues in app/views/blocks

---

app/views/chat_channels/index.html.erb

Fix linting issues in app/views/chat_channels

---

app/views/feedback_messages/_form.html.erb
app/views/feedback_messages/index.html.erb
app/views/feedback_messages/new.html.erb

Fix linting issues in app/views/feedback_messages

---

app/views/email_subscriptions/invalid_token.html.erb
app/views/email_subscriptions/unsubscribe.html.erb

Was able to fix all linting errors.
#1842

Fix linting issues in app/views/email_subscriptions

---

app/views/comments/_comment.html.erb
app/views/comments/_comment_proper.html.erb
app/views/comments/_form.html.erb
app/views/comments/_login_cta_comment.html.erb
app/views/comments/delete_confirm.html.erb
app/views/comments/edit.html.erb
app/views/comments/index.html.erb
app/views/comments/new.html.erb
app/views/comments/settings.html.erb

Fix linting issues in app/views/comments

---

app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/registrations/_registration_form.html.erb
app/views/devise/shared/_authorization_error.html.erb

Was able to fix all linting errors.
#1842

Fix linting issues in app/views/devise

---

app/views/events/_event.html.erb
app/views/events/_widget_events_item.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb

Was able to fix all linting errors.
#1842

Fix linting issues in app/views/events

---

app/views/layouts/_nav_menu.html.erb
app/views/layouts/_signup_modal.html.erb
app/views/layouts/_styles.html.erb
app/views/layouts/_top_bar.html.erb
app/views/layouts/application.html.erb
app/views/layouts/internal.html.erb
app/views/layouts/mailer.html.erb

Fix linting issues in views located in `app/views/layouts`. The remaining `Lint/UselessAssignment` issues are just left alone since it's already going to be disabled in #1886 .
#1842

Fix linting issues in app/views/layouts

---

app/views/internal/articles/_individual_article.html.erb
app/views/internal/articles/index.html.erb
app/views/internal/articles/rss_articles.html.erb

Fix linting issues for views in `app/views/internal/articles`. The remaining `Lint/UselessAssignment` issues are just left alone since they are already being disabled in #1886 .
#1842

Fix linting issues for app/views/internal/articles

---

app/views/admin/application/_collection.html.erb
app/views/admin/application/index.html.erb

Fix linting issues in view files located in `app/views/admin` directory.
#1842

Fix linting issues in app/views/admin

---

app/views/organizations/_main_feed.html.erb
app/views/organizations/_sidebar_additional.html.erb
app/views/organizations/show.html.erb

Fix linting issues in app/views/organizations

---

app/views/notifications/_aggregated_reactions.html.erb
app/views/notifications/_article.html.erb
app/views/notifications/_badgeachievement.html.erb
app/views/notifications/_broadcast.html.erb
app/views/notifications/_comment.html.erb
app/views/notifications/_follow.html.erb
app/views/notifications/_mention.html.erb
app/views/notifications/_notifications_list.html.erb
app/views/notifications/_reaction.html.erb
app/views/notifications/_signup_cta_test.html.erb
app/views/notifications/_tagadjustment.html.erb
app/views/notifications/index.html.erb
app/views/notifications/shared/_comment_box.html.erb

Fix linting issues in app/views/notifications

---

lib/tasks/fetch.rake

Add additional streak badge rewarding

---

app/controllers/pages_controller.rb
app/views/badges/show.html.erb

Typo and missing array element

Fix typo in badge show page and fix unrelated badge missing word

---

app/controllers/api/v0/reactions_controller.rb

This adds a missing argument that was left out by accident. The same functionality is used in:
https://github.com/thepracticaldev/dev.to/blob/d9e1ab2caa8b73596e610b69675f8c4d8cf13692/app/controllers/reactions_controller.rb#L68-L69

Add missing argument for reaction notification

---

app/views/stories/_main_stories_feed.html.erb
app/views/stories/_narrow_nav_menu.html.erb
app/views/stories/_sign_in_invitation.html.erb

Fix linting issues for views located in `app/views/stories`.
#1842

Fix linting issues for app/views/stories

---

app/views/social_previews/article.html.erb
app/views/social_previews/tag.html.erb
app/views/social_previews/user.html.erb

Fix linting issues for views located in `app/views/social_previews`.
#1842

Fix linting issues in app/views/social_previews

---

app/views/tags/edit.html.erb
app/views/tags/index.html.erb

Fix linting issues for views located in `app/views/tags`.
#1842

Fix linting issues for app/views/tags

---

app/views/reading_list_items/index.html.erb

Fix linting issues and incorrect HTML for views located in `app/views/reading_list_items`.
#1842

Fix linting issues in app/views/reading_list_items

---

app/views/moderations/mod.html.erb

Fix linting issues in views located in `app/views/moderations`.
#1842

Fix linting issues in app/views/moderations

---

app/views/podcast_episodes/_episodes_feed.html.erb
app/views/podcast_episodes/_meta.html.erb
app/views/podcast_episodes/_podcast_bar.html.erb
app/views/podcast_episodes/_sidebar.html.erb
app/views/podcast_episodes/_subscribe_buttons.html.erb
app/views/podcast_episodes/admin.html.erb
app/views/podcast_episodes/edit.html.erb
app/views/podcast_episodes/index.html.erb
app/views/podcast_episodes/show.html.erb

Fix linting issues in app/views/podcast_episodes

---

app/views/stripe_subscriptions/create.html.erb

Fix linting issues for views located in `app/views/stripe_subscriptions`.
#1842

Fix linting issues in app/views/stripe_subscriptions

---

app/views/users/_account.html.erb
app/views/users/_billing.html.erb
app/views/users/_comments_section.html.erb
app/views/users/_integrations.html.erb
app/views/users/_main_feed.html.erb
app/views/users/_membership.html.erb
app/views/users/_mentorship.html.erb
app/views/users/_meta.html.erb
app/views/users/_misc.html.erb
app/views/users/_org_admin.html.erb
app/views/users/_organization.html.erb
app/views/users/_profile.html.erb
app/views/users/_profile_header.html.erb
app/views/users/_publishing_from_rss.html.erb
app/views/users/_sidebar_additional.html.erb
app/views/users/_switch_organizations.html.erb
app/views/users/edit.html.erb
app/views/users/show.html.erb
app/views/users/signout_confirm.html.erb

Fix linting issues in views located in `app/views/users`.
#1842

Fix linting issues in app/views/users

---

app/views/users/_mentorship.html.erb
app/views/users/_org_member.html.erb

Remove string addition that caused syntax error.
#1908 
N/A

Fix settings/mentorship SyntaxError

---

app/models/follow.rb

Several methods were kept in the `Follow` model in case there were jobs, which had been created but not yet executed by the deploy time. For now, all the old jobs should be finished, so the methods can be removed.

Remove unused Follow methods #1621

---

spec/models/badge_spec.rb

Add test for validation badge image

Add test for validation badge image

---

app/helpers/comments_helper.rb

Change wording for more clarity

Change OP to AUTHOR

---

app/models/html_variant.rb
spec/models/html_variant_spec.rb

This had been working originally, but had stopped. Something we changed elsewhere affected this. Additional test should help catch this next time. Bug only affected some admin behavior.

Add missing CloudinaryHelper inclusion in HtmlVariant

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/controllers/moderations_controller.rb

A couple minor adjustments on the experience level functionality.

Slight modification in /mod for exp level stuff

---

app/controllers/moderations_controller.rb
app/views/moderations/index.html.erb

Adds copy on the new `/mod` page for users who are not mods or not logged in.

Add non-mod functionality to /mod

---

.erb-lint.yml
app/views/videos/new.html.erb

All linting errors have been fixed.
~~Stil 1 linting error that I wasn't sure how to fix:~~
```
Avoid using "text/x-tmpl" as type for `<script>` tag. Must be one of: text/javascript (or no type attribute).
In file: app/views/videos/new.html.erb:25
```
#1842

Fix linting issues in app/views/videos

---

app/labor/random_gif.rb
app/models/notification.rb

Story of "changed one thing in one place, forgot to change it another place."
Also removed a duplicate line in `random_gif.rb`.

Add missing data for org milestone notifications

---

app/labor/random_gif.rb

It appends new gifs to generate for milestone notifications

add gifs to random_gif.rb

---

docs/addl-tech.md

I just added GitDocs to "🔑 Key App tech/services" section of the documentation.

Add GitDocs to "🔑 Key App tech/services" [skip ci]

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/controllers/internal/articles_controller.rb
app/controllers/users_controller.rb
app/labor/email_digest.rb
app/labor/email_logic.rb
app/views/internal/articles/index.html.erb
app/views/layouts/internal.html.erb
app/views/mailers/digest_mailer/digest_email.html.erb

Fixed some styling hiccups that snuck through with the lint fixing. Also added satellite tab in internal/articles and added some experience level logic to digest emails.

Fix some internal styling and add some internal tooling

---

app/controllers/internal/articles_controller.rb

Quick adjustment to previous internal logic push

Switch satellite view to any: true for tags

---

.rubocop.yml
.rubocop_todo.yml
app/views/articles/feed.rss.builder
config/environments/development.rb
config/environments/production.rb
config/routes.rb
spec/requests/organizations_update_spec.rb
spec/requests/stripe_cancellations_spec.rb

Fix rubocop issues

---

app/views/pages/shecoded.html.erb

Social cards, etc. for /shecoded

Add shecoded meta tags

---

app/controllers/dashboards_controller.rb
app/models/role.rb
app/policies/user_policy.rb
app/views/dashboards/pro.html.erb
config/routes.rb
spec/requests/dashboard_spec.rb

This is a concept feature which will live in private beta for a little while. It will help some users with specific needs and act as a test ground for general rollout features. This is the basic first cut just to get an idea into the universe.

Basics of pro dashboard

---

app/controllers/articles_controller.rb
app/models/tag.rb
app/views/articles/_v2_form.html.erb

Add tag template to v2 editor

---

app/views/pages/shecoded.html.erb

Add they coded and update copy for #SheCoded

update shecoded copy

---

app/controllers/social_previews_controller.rb
app/views/social_previews/shecoded.html.erb

Add shecoded social preview template

---

app/labor/flare_tag.rb
app/models/article.rb
app/views/articles/_tag_identifier.html.erb
spec/labor/flare_tag_spec.rb
spec/models/article_spec.rb

- cached flare tag in a variable for the view
- refactored `FlareTag`
- moved `FlareTag` specs to its own file

Make less queries when displaying articles flare tags

---

app/labor/random_gif.rb

This adds a few more success/celebration gifs to the random gif file!
N/A
Here's all the ones I added. They all are a good representation!

Add new gifs to random_gif.rb

---

app/black_box/black_box.rb

Minor adjustment in the ranking to keep some posts from sticking around too long.
We could make less naive incremental adjustments, but I feel like we don't want to mess with rankings too much at once.

Adjust rankings to squash lingering popular stuff

---

app/controllers/internal/users_controller.rb
app/models/user.rb
app/policies/user_policy.rb
app/views/internal/users/show.html.erb

This lets us adds pros via GUI instead of going through console.

Add ability to add pro role to internal

---

app/views/pages/shecoded.html.erb

Was looking a little funky on smaller screens

change media query to 950 instead of 800px

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/assets/javascripts/utilities/buildArticleHTML.js.erb
app/assets/javascripts/utilities/timeAgo.js
app/assets/stylesheets/articles.scss
app/decorators/article_decorator.rb
app/views/articles/_single_story.html.erb
app/views/articles/index.html.erb
app/views/stories/_main_stories_feed.html.erb

For posts published within the day, indicate how many seconds, minutes, hours ago the post was made.

Add time ago to recent posts in feed

---

app/views/pages/generator.html.erb

I was going through the routes file and found some interesting pages.
I also noticed that this page wasn't working correctly, 2 images were not being displayed correctly.
1 fixed the first one, the second one doesn't seem to exist anymore but looking at the url it seems to be a heart GIF. If anyone has a good replacement let me know and I will add it, for now I have hidden it so you don't see a broken image.
Before:
After:

Fix Mixed Content error in O RLY Parody Book Generator

---

.nvmrc

Use latest LTS Dubnium release instead of a fixed version.
#1997

Use latest Node.js LTS Dubnium version

---

app/controllers/pages_controller.rb
app/views/pages/shecoded.html.erb
lib/tasks/fetch.rake

Add she coded posts to landing page

Nevertheless, She Coded

---

app/assets/stylesheets/articles.scss
app/controllers/pages_controller.rb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/index.html.erb
app/views/pages/shecoded.html.erb

Add shecoded sidebar/homepage decorations

---

app/views/social_previews/shecoded.html.erb

Quick fix for images which were not being cropped properly. We should always use `ProfileImage.new` because that's when appropriate cropping happens, vs using the raw image.

Fix social card aspect ratio problem

---

app/views/articles/_sidebar_additional.html.erb

The sidebar widget header should point to the she coded page :)

Fix sidebar widget header for she coded

---

app/views/pages/shecoded.html.erb

Update shecoded.html.erb copy!

---

app/assets/stylesheets/articles.scss
app/controllers/stories_controller.rb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/index.html.erb

Remove some of the stuff that was specific to today, keep some stuff that will stay live through the weekend and beyond. More adjustments to come.

Remove some hardcoded shecoded stuff

---

app/assets/stylesheets/dashboard.scss
app/decorators/chart_decorator.rb
app/views/dashboards/pro.html.erb
app/views/dashboards/show.html.erb

Added navigation buttons between regular dashboard and pro dashboard. Also fixes the chart by using the correct date to group by, via `reaction.created_at.beginning_of_day`.

Fix charts and add nav buttons

---

app/controllers/omniauth_callbacks_controller.rb

Add more logging and use `.inspect` for more details. Also redirect rescued errors to a proper page.

Add more logging to sign in failures

---

app/helpers/application_helper.rb
app/labor/flare_tag.rb
app/labor/sticky_article_collection.rb
app/views/articles/_sticky_nav.html.erb
db/migrate/20190306082543_add_index_to_articles_path.rb
db/schema.rb

- Added index to articles path, since queries by path are popular when retrieving articles
- select only needed columns for tag colors
- Make fewer SQL queries on retrieving sticky article collection

Optimize stories

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb

The time ago label in latest page was getting rendered on every alternative posts.
#2012 
No Documentation required.

Fixed time ago bug.

---

app/javascript/chat/chat.jsx

"Notificatins" ☹
"Notifications" 🙂

Fixed typo on notifications state

---

app/views/articles/_sidebar_additional.html.erb

We still have some updates to the /shecoded page coming soon, so the celebration isn't fully over yet 😄

Remove shecoded sidebar

---

app/assets/stylesheets/dashboard.scss
app/views/dashboards/pro.html.erb

give the pro dashboard a dashboard-y makeover

---

app/assets/stylesheets/variables.scss

Quick fix to make helvetica globally a thing

Quick css adjustment on sans-serif config

---

app/assets/stylesheets/top-bar.scss
app/assets/stylesheets/variables.scss
app/views/dashboards/pro.html.erb
app/views/layouts/_top_bar.html.erb

- fix html indentation
- change greater to greater or equal
- moved one week var to month

a couple bug fixes for the pro dashboard!

---

db/migrate/20190315222044_add_originally_published_at.rb

Add originally published at migration

---

docs/addl-tech.md

- [X ] Documentation Update
Update addl-tech, with two kinda-pedanctic options.
- [ x] docs.dev.to

Updated addl-tech.md

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/comments.scss
app/assets/stylesheets/footer.scss
app/assets/stylesheets/index-comments.scss
app/assets/stylesheets/more-articles.scss
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/settings.scss
app/assets/stylesheets/sticky-nav.scss
app/assets/stylesheets/top-bar.scss
app/assets/stylesheets/user-profile-header.scss
app/assets/stylesheets/variables.scss
app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/_misc.html.erb

This renders the proper night theme using CSS variables. This currently takes hardcoded theme info right in `application.html.erb` but could be modified to take variables in the future.
Also added another font option: `comic sans`.

Add proper css vars to user style config

---

app/controllers/articles_controller.rb

This feature allows users to supply a url like `dev.to/new?prefill=A BUNCH OF MARKDOWN` in order to supply arbitrary templates. This is similar to the tag prefilled templates.

Add arbitrary prefilled markdown for /new

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/more-articles.scss

Add --theme-container-background-hover to sidebar-nav-element hover
Remove bacground from sidebar-nav-readinglist hover
#1377

Add --theme-container-background-hover

---

.rubocop.yml

Enabled Naming/AsciiIdentifier Cop and Naming/FileName Cop
#2021

Enabled Rubocop/Naming Cop

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/ltags/LinkTag.scss
app/assets/stylesheets/notifications.scss
app/controllers/page_views_controller.rb
app/views/articles/_sidebar_additional.html.erb
app/views/layouts/application.html.erb

Add additional changes to make night theme look right.

Night theme improvements + small fixes

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/comments.scss
app/views/layouts/application.html.erb

Improve night theme in missing areas.

Add theme to loading gradient, comment form, about author

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/notifications.scss

Add themes to main list, notifications, and chat

---

Envfile
app/helpers/application_helper.rb
app/views/layouts/_top_bar.html.erb

This allows admins to set new logos for special events as well as generalized instances of the platform.

Add ability to set site logo via ENV variable

---

app/views/internal/articles/_individual_article.html.erb
spec/features/admin_bans_or_warns_user_spec.rb

- Removed unnecessary 'reason for warning' that's breaking the internal/articles view. 
- Re-added/fixed a feature spec for banning and warning.

Fix Internal/Articles

---

.rubocop.yml

Enabled Rubocop/Rails cops
#2021

Enabled Rubocop/Rails cops

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/notifications.scss

Add night theme vars for notifications and org branding

---

app/labor/badge_rewarder.rb
spec/labor/badge_rewarder_spec.rb

Refactor `award_yearly_club_badges` so that adding new yearly badges will be easier and require less changes.
I got a couple of questions about the refactor:
- Do you want it in a loop or more like `award_streak_badge(num_weeks)`? I think the for loop is a better option, you will only need to increase a variable and not add a new line to `fetch.rake`
https://github.com/thepracticaldev/dev.to/blob/0b84ae9acba3658af1112aeb520a049e852ffd27/app/labor/badge_rewarder.rb#L47
https://github.com/thepracticaldev/dev.to/blob/0b84ae9acba3658af1112aeb520a049e852ffd27/lib/tasks/fetch.rake#L73-L75
- What do you guys think is the best way to set the parameter? I currently added it as a variable in the function.
- Will changing the slug to a numeric number value instead of the word value (`one-year-club` …

Refactor award_yearly_club_badges

---

app/assets/stylesheets/article-show.scss

Add night theme to article actions

---

app/assets/stylesheets/article-show.scss

Make app look right on ios app view

Adjust ios theme background bottom

---

app/assets/javascripts/lib/pulltorefresh.js
app/assets/stylesheets/articles.scss
app/assets/stylesheets/comments.scss
app/assets/stylesheets/variables.scss

Make pull to refresh night theme, plus invert icons in night theme

---

Gemfile
Gemfile.lock
db/schema.rb

Switch from fork to published version.

Switch fix-db-schema-conflicts to published version

---

app/assets/stylesheets/comments.scss

Update form styles to remove white border and add colour distinction to the background
Before:
After:

[Theme] Change comment form styles

---

app/assets/stylesheets/articles.scss

Remove the white border from the sidebars
Before: 
After:

[Theme] Remove white border from sidebar

---

app/assets/stylesheets/articles.scss

Change the reading list styles to work for night mode.
Before:
After:

[Theme]Update reading list

---

app/assets/stylesheets/dashboard.scss

Closes #2167
Bring the theme to the dashboard

[Theme] Dashboard makeover

---

app/views/notifications/_milestone.html.erb

Fixes incorrect giphy url so that gif gets loaded correctly.
Fixes #2179

Bug fix broken giphy url

---

app/models/tag.rb

This adds some popular tags to the onboarding flow.

Add several recommended tags for onboarding

---

app/assets/javascripts/utilities/sendFetch.js
app/controllers/chat_channels_controller.rb
app/policies/chat_channel_policy.rb
config/routes.rb
spec/requests/chat_channels_spec.rb

Refactor and add tests for chat channel functionality. Kept the general code arrangement about the same.

Clean up new chat channel functionality and add tests

---

Gemfile
config/scout_apm.yml

- Adds scout gem and config file

add scout config and gem

---

app/services/moderator/merge_user.rb

- Update counter cache
- Keep older created_at date
- Bust fastly cache

Clear Cache When Merging Users

---

app/models/identity.rb
db/migrate/20190327090030_add_indexes_to_indentities.rb
db/schema.rb
spec/models/identity_spec.rb

- added missing unique indexes on `Identity`
- removed redundant unique validation (`provider` + `uid` vs `uid` + `provider`)
- made uniqueness validation conditional: only check for uniqueness when one of the fields of the scope was changed
This is a slight optimization to start with for the ticket #2061 
- Check for existing invalid `Identity` records, they need to be fixed
- `identities` table could be large, so adding indexes may take a long time

Optimize sign in: Identity #2061

---

app/assets/stylesheets/article_form.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/comments.scss
app/assets/stylesheets/preact/article-form.scss
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/user-profile-header.scss
app/views/layouts/application.html.erb

Adds night theme to compose forms and misc other places. Also fiddles with the variables for this particular theme.

Add night theme styling in various places

---

app/controllers/api/v0/articles_controller.rb
spec/requests/api/v0/articles_spec.rb

Since we're already asking the DB to retrieve an article, we can directly ask it to filter out published articles without checking at runtime.

Add published in the SQL query to retrieve article

---

app/assets/stylesheets/variables.scss
app/views/articles/_actions.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/layouts/application.html.erb

Make comic sans default

---

app/dashboards/organization_dashboard.rb
app/views/articles/_sidebar.html.erb
db/migrate/20190401193017_add_sponsor_link_to_organizations.rb
db/schema.rb
spec/requests/stories_index_spec.rb

Rather than hardcoding monthly sponsors, the change will let us put sponsorship info right on organization models.

Allow orgs to be marked as sponsors

---

app/views/articles/_sidebar.html.erb
app/views/pages/sponsors.html.erb
db/migrate/20190401213605_add_sponsorship_order_to_organizations.rb
db/schema.rb

Featured number here goes ASCENDING order

Add sponsors to sponsors page and add sponsor order field

---

Envfile
app/assets/javascripts/manifest.json.erb
app/assets/stylesheets/articles.scss
app/assets/stylesheets/preact/article-form.scss
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/sidebar-data.scss
app/helpers/application_helper.rb
app/views/articles/_sidebar.html.erb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/index.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_signup_modal.html.erb
app/views/layouts/_top_bar.html.erb
app/views/layouts/application.html.erb
app/views/pages/about.html.erb
app/views/pages/sponsors.html.erb
app/views/users/_comments_section.html.erb
app/views/users/show.html.erb
spec/features/homepage/user_visits_homepage_spec.rb
spec/features/organization/user_views_an_organization_spec.rb
spec/features/user/view_user_index_spec.rb
spec/features/user_logs_in_with_twitter_spec.rb

Adjusted style of this CTA box and the "start a xxxxx thread" button. To stand out and look nicer. 
Also created `COMMUNITY_NAME` config variable for future generalization convenience. Made local default DEV(local) to exemplify the difference here. In prod, it is `DEV`.

Some night theme code, other style adjustments, and extracted app name into ENV var

---

app/assets/stylesheets/comments.scss

Fixes night mode issue #2244

---

app/models/user.rb

Checking RSS feed validation is pretty costly in the current setup. We should only do it if something has changed with it.

Conditionally run feed validation

---

app/controllers/api/v0/podcast_episodes_controller.rb
config/routes.rb
spec/requests/api/v0/podcasts_episodes_spec.rb

This PR does two things:
* adds tests for the Api::V0::PodcastEpisodesController
* removes unused routes and code

Add tests to PodcastEpisodesController

---

app/views/videos/new.html.erb

Here are the styling fixes:
Closes: #2245

Fixes Upload Video Section Background Color in Night Mode Theme #2245

---

app/controllers/buffer_updates_controller.rb
app/views/internal/articles/_individual_article.html.erb
app/views/internal/articles/index.html.erb
spec/requests/buffer_updates_spec.rb

Fix some of the issues with the initial push

Finalize suggest-a-tweet functionality

---

app/assets/stylesheets/video-collection.scss
app/controllers/api/v0/videos_controller.rb
app/controllers/videos_controller.rb
app/labor/cache_buster.rb
app/views/layouts/_styles.html.erb
app/views/videos/index.html.erb
spec/requests/videos_api_spec.rb
spec/requests/videos_spec.rb

Clean up some of the functionality from the initial `/videos` push and add tests.

Clean up videos page and add tests

---

.rubocop.yml
.rubocop_todo.yml
app/labor/hex_comparer.rb
app/liquid_tags/github_tag/github_issue_tag.rb
app/models/github_issue.rb
app/services/rss_reader.rb
config/initializers/honeycomb.rb
config/initializers/reserved_words.rb
spec/labor/hex_comparer_spec.rb

- [] Bug Fix
Fixed a bunch of "Style/*" rubocop violations and added a couple of tests 
See #2021

Fixed some Style/* rubocop violations

---

app/assets/stylesheets/article-show.scss
app/assets/stylesheets/articles.scss
app/assets/stylesheets/chat.scss
app/assets/stylesheets/ltags/GithubReadmeTag.scss
app/assets/stylesheets/ltags/GithubTag.scss
app/controllers/buffer_updates_controller.rb
app/controllers/internal/articles_controller.rb
app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
app/javascript/chat/chat.jsx
app/javascript/chat/message.jsx
app/views/articles/_actions.html.erb
app/views/articles/_sticky_nav.html.erb
app/views/moderations/index.html.erb
app/views/moderations/mod.html.erb
spec/requests/buffer_updates_spec.rb

Adjustments to suggested tweet flow

Modify social share button and functionality

---

app/controllers/buffer_updates_controller.rb
app/views/internal/articles/index.html.erb

Fix issue where link doesn't show up for Facebook.

Fix social share text bugs

---

app/controllers/api/v0/analytics_controller.rb
app/services/analytics_service.rb
spec/services/analytics/analytics_service_spec.rb
spec/support/api_analytics_shared_examples.rb

This PR adds single article functionality. I went with a pretty basic implementation that adds another argument. There's also a guard to prevent unauthorized requests, like viewing another person's article.
Example routes:
```
https://dev.to/api/analytics/totals?article_id=1
https://dev.to/api/analytics/historical?start=2019-04-01&article_id=1
https://dev.to/api/analytics/past_day?article_id=1
```

Add single article functionality to articles analytics

---

app/views/internal/users/_notes.erb

We didn't use to require authors for notes so some older notes do not have this info and might be breaking an internal page.

Do not require author for displaying notes in /internal

---

app/lib/constants.rb

Adding "phpc.social" as an accepted Mastodon URL. 
resolves #2345 
N/A

Add phpc.social to Mastodon List

---

app/assets/stylesheets/dashboard.scss

Replaced the sloan.png with a transparent version
Closes #2349

UX: Made sloan transparent -> now working in night theme

---

app/assets/stylesheets/comments.scss

This fixes the comment preview in darkmode
Closes #2286

UX: Fixed comment preview in darkmode

---

config.ru

Part of the process of removing honeycomb from the app effectively

Remove honeycomb code from config.ru

---

app/views/pages/community_moderation.html.erb
app/views/pages/tag_moderation.html.erb
config/routes.rb

Create community moderation page and update tag moderation page.

Community Moderation Page

---

app/assets/stylesheets/article-show.scss

Fixed the figcaption tag in nightmode
Closes #2181

 [SMALL] UX: Fixed figcaption in nightmode

---

app/assets/stylesheets/articles.scss

This fixes the "No results found" in search in nightmode

[SMALL] UX: Fixed no results found in nightmode

---

app/views/pages/community_moderation.html.erb

Updated grammar from "articles that only has a teaser paragraph and sends the reader to an external link for the rest" "to articles that only have a teaser paragraph and send the reader to an external link for the rest" :)

Grammatical fix

---

app/views/pages/community_moderation.html.erb

Fixes a typo in file `community_moderation.html.erb`

Fixed spacing typo

---

app/controllers/stories_controller.rb
app/views/articles/index.html.erb
app/views/stories/_main_stories_feed.html.erb

This is quick and dirty but should make the home page a bit more efficient

Add additional fragment caching to home page

---

app/views/articles/index.html.erb

Add sidebar condition for homepage cache

---

app/controllers/articles_controller.rb
app/controllers/stories_controller.rb

I am pretty sure these queries are unnecessary in the way we are using surrogate headers

Remove unnecessary map functions in stories controller

---

app/views/articles/tag_index.html.erb

Add high level fragment caching to wrap most of the tag page html.
Just a couple line change, looks like more because of indenting everything.

Add fragment cache to tag page

---

db/migrate/20190412093614_add_comment_indexes.rb
db/schema.rb

Added indexes to `comments` `commentable` fiedls and `user_id`

Added missing indexes to the comments table

---

app/assets/stylesheets/dashboard.scss
app/views/dashboards/show.html.erb

This fixes drafts in nightmode (dashboard)
Also changed the make video cta to now look more like a button
Keeping the background a bit more greyed-out so users can easily see that it's a draft 🙂
Closes #2182

UX: Fixed draft in nightmode

---

app/views/pages/community_moderation.html.erb

There was an incorrect " in the Thumbsdown description, so I changed it to match!
Screenshot of the initial display: https://cl.ly/5e8a52d25344

fixed grammar error in "thumbsdown" description

---

app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/_misc.html.erb
spec/models/user_spec.rb

pinkify DEV

---

app/assets/stylesheets/chat.scss
app/assets/stylesheets/connect/_channel-details.scss
app/assets/stylesheets/variables.scss
app/javascript/chat/__tests__/__snapshots__/article.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/channels.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
app/javascript/chat/__tests__/article.test.jsx
app/javascript/chat/article.jsx
app/javascript/chat/channels.jsx
app/javascript/chat/chat.jsx
app/javascript/chat/userDetails.jsx

Serveral improvements for chat in nightmode
Also, husky has linted some react files I made changes to.
Closes #2417

UX: Several improvements for chat in nightmode

---

app/views/layouts/_user_config.html.erb
app/views/layouts/application.html.erb

Make pink mode headers grey for A11y reasons!

Feature/pink mode - make text grey

---

app/assets/stylesheets/variables.scss
app/views/users/_profile.html.erb

This fixes the dev badge in profile settings in nightmode
Closes #2420

[SMALL] UX: Fixed dev badge in nightmode

---

Gemfile
Gemfile.lock

The app uses many gems and it's not always clear which does what, I added a short description (taken from either the RubyGems page or the GitHub page) to each and every one of them.

Add short description for gems

---

app/models/article.rb
app/views/articles/_sidebar_additional.html.erb
app/views/articles/tags/_sidebar_additional.html.erb

Modifying cache so the wrong data doesn't get included in output.

Modify sidebar seo-boostable cache

---

app/services/moderator/merge_user.rb

Adds db transactions to allow for rollbacks if exceptions are raised.  This will guard the data against program errors or database break-downs and make for safer merging of user accounts.
#2230
N/A

db transactions for safer merging of users

---

app/services/article_api_index_service.rb
spec/requests/api/v0/articles_spec.rb

Allow `/api/articles` to deliver "top" articles based on a timeframe.

Allow API to return top articles

---

app/assets/javascripts/initializers/initScrolling.js.erb
app/assets/stylesheets/user-profile-header.scss
app/javascript/chat/content.jsx
app/policies/user_policy.rb
app/views/users/_misc.html.erb
app/views/users/show.html.erb
db/migrate/20190417171019_add_inbox_instructions_to_users.rb
db/schema.rb

Allow users to define instructions related to how they would like to be interacted with via open inbox.

Add inbox guidelines to users

---

app/assets/images/keyboard-left-arrow-button.svg
app/assets/images/keyboard-right-arrow-button.svg
app/assets/images/refresh-button.svg
app/assets/javascripts/initializePage.js.erb
app/assets/javascripts/initializers/initializePWAFunctionality.js
app/assets/javascripts/manifest.json.erb
app/assets/stylesheets/top-bar.scss
app/views/layouts/_footer.html.erb
app/views/layouts/_top_bar.html.erb

This is still entirely experimental, but this adds functionality for nav buttons for desktop PWA.
There are still missing features/open questions for desktop PWA, but this is an interesting step.

Add nav buttons to pwa desktop

---

app/views/layouts/_footer.html.erb

Current behavior:
(I did not test locally)

Fix <br/> in footer.

---

docs/installation/mac-os.md

Added troubleshooting steps for the byebug withouout readline issue you may encounter during setup.

Added troubleshooting for byebug without readline issue

---

app/views/layouts/_styles.html.erb

Determine on-page cached styles based on whether user is signed in or not for cache key

Add user_signed_in? to cache key for styles

---

app/javascript/src/utils/sendFollowUser.js

Disabled the `no-console` rule for a line where we use `console.log` to report errors.
#2501, #1828

Disabled no-console for where we currently log an error.

---

app/views/internal/users/show.html.erb

Disclaimer: I don't know how to run the CouponGenerator locally, so I didn't, which means I don't know if this actually works or not.
- I basically took Andy's notes that this should be the same code from the user settings view and copied it over. 
- This *should* add the member discount code to our internal view if we ever need to reference it but I'm not confident. It might be generating a new code altogether?

Show coupon codes on internal/users

---

Gemfile
Gemfile.lock

Upgraded [capybara](https://rubygems.org/gems/capybara) to 3.18, see [changelog](https://github.com/teamcapybara/capybara/blob/master/History.md).
This change should also improve performance a bit, though I'm not sure it's noticeable:
```text
Selenium driver now defaults to using a persistent http client connection
```

Upgrade capybara to 3.18

---

Gemfile
Gemfile.lock
config/initializers/airbrake.rb

Upgrade [airbrake](https://github.com/airbrake/airbrake) to v9.1.0, see [changelog](https://github.com/airbrake/airbrake/blob/master/CHANGELOG.md)

Upgrade airbrake to 9.1.0

---

Gemfile
Gemfile.lock

Upgraded [brakeman](https://github.com/presidentbeef/brakeman) to version 4.5, see [changelog](https://github.com/presidentbeef/brakeman/blob/master/CHANGES.md).

Upgrade brakeman to 4.5

---

app/views/classified_listings/_form.html.erb
app/views/classified_listings/index.html.erb

A couple bugs noticed in the early minutes of the feature.

A couple small /listings fixes

---

app/assets/javascripts/initializers/initScrolling.js.erb

Fix style issue video image on scroll

---

app/services/moderator/banish_user.rb

If a spam account does not have an email address, do not try to unsubscribe them from mailchimp.

Banish User: only unsubscribe if user has an email address

---

app/controllers/admin/users_controller.rb
app/dashboards/user_dashboard.rb
app/models/user.rb
app/policies/user_policy.rb
app/services/moderator/banish_user.rb
app/views/users/_profile.html.erb
app/views/users/_profile_header.html.erb
app/views/users/show.html.erb
db/migrate/20180707162348_add_social_icons_to_user.rb
db/schema.rb
spec/models/user_spec.rb

Add Twitch to the list of profile links. For implementation, I followed the pattern for other profile links to include twitch.
Resolves #2505

Add Twitch to Profile Links

---

db/migrate/20180707162348_add_social_icons_to_user.rb
db/migrate/20190425210432_add_twitch_url_to_users.rb
db/schema.rb

The PR which added the Twitch URL did not handle migrations properly, but in a way which didn't break tests. I failed to notice the mistake in the file while reviewing.
This should fix it.

Add proper twitch url migration

---

Gemfile.lock

[test-prof](https://github.com/palkan/test-prof) 0.8.0 introduces a [few enhancements](https://github.com/palkan/test-prof/blob/master/CHANGELOG.md#080-2019-04-12-) regarding Rspec's `before_all`

Upgrade test-prof to 0.8.0

---

app/assets/javascripts/initializers/initNotifications.js
app/assets/javascripts/initializers/initializeBodyData.js
app/assets/javascripts/initializers/initializeCommentsPage.js.erb
app/views/pages/badge.html.erb

I've noticed a statement like this during a review, I checked around and they seem to be copy and pasted in a few places but never used.

Removed unused timeString statements

---

app/controllers/internal/users_controller.rb
app/models/user.rb
app/views/internal/users/_activity.erb
app/views/internal/users/_credits.erb
app/views/internal/users/show.html.erb

Allows admins to add credits to individual users.

Add credit form to internal/users

---

app/assets/stylesheets/classified_listings.scss
app/javascript/listings/singleListing.jsx
app/liquid_tags/codepen_tag.rb
app/views/classified_listings/_form.html.erb
app/views/classified_listings/edit.html.erb
app/views/credits/index.html.erb
lib/tasks/fetch.rake
spec/liquid_tags/codepen_tag_spec.rb
spec/requests/credits_spec.rb

Fix some listing/credit bugs

---

app/assets/stylesheets/classified_listings.scss
app/models/article.rb
app/views/articles/index.html.erb
app/views/articles/tag_index.html.erb

Modify some styles and caching logic style, also modify timeframe for "seo boostables"

Adjust cache settings and some styling

---

app/jobs/notifications/moderation_notification_job.rb
app/models/notification.rb
app/services/notifications/moderation.rb
app/services/notifications/moderation/send.rb
spec/jobs/notifications/moderation_notification_job_spec.rb
spec/requests/moderations_spec.rb
spec/services/notifications/moderation/send_spec.rb

- send_moderation_notification in own job
- specs for job + service
#1996

Move moderation notification to Active Jobs

---

app/labor/markdown_parser.rb
app/models/classified_listing.rb
spec/models/classified_listing_spec.rb

Add _actual_ filtering for improper tags in listings

Add proper filtering for inappropriate tags in listings

---

app/services/exporter/service.rb
spec/services/exporter/service_spec.rb

Fix name resolving error on export by specifying namespace in the `Exporter::Service::EXPORTERS`
#2580

Fix name resolving error on export

---

app/views/pages/live.html.erb
app/views/users/_integrations.html.erb
app/views/users/_profile.html.erb
config/routes.rb
spec/requests/pages_spec.rb

I moved the Twitch integration into "integrations", and added the `/live/:username` route which I think is the right place for this. `/live` can become an index of all community members who are live.

Make a couple changes to Twitch MVP before push

---

db/migrate/20190430123156_add_indexes_to_classified_listings.rb
db/schema.rb

Added index to `classified_listings` `user_id` and `organization_id`

Add indexes to classified_listings

---

Gemfile

Removes pry and pry-rails from the production environment
Closes #2626

Removes pry and pry-rails from production

---

README.md

Updates the links in the Getting Started section to point to the correct pages on docs.dev.to
- [X ] readme

Updates links within repo README for setting up environment variables

---

db/seeds.rb

The two last seed steps were numbered 10. So I chance the last one to be 11 instead.

Fix typo in seed log information

---

app/assets/stylesheets/_mixins.scss
app/assets/stylesheets/articles.scss

Adds the themeable SASS mixin to the project with a SASS file using it. This PR gets the ball rolling.
#2539
Here is the built SASS, notice the CSS vars with fallbacks.

Added the themeable mixin.

---

app/assets/javascripts/initializers/initializeBaseUserData.js
app/assets/stylesheets/article-show.scss
app/assets/stylesheets/dashboard.scss
app/controllers/articles_controller.rb
app/controllers/buffer_updates_controller.rb
app/models/rating_vote.rb
app/policies/application_policy.rb
app/policies/buffer_update_policy.rb
app/views/articles/manage.html.erb
app/views/dashboards/_dashboard_article.html.erb
app/views/dashboards/show.html.erb
config/routes.rb
spec/models/rating_vote_spec.rb
spec/policies/article_policy_spec.rb
spec/policies/buffer_update_policy_spec.rb
spec/requests/articles_spec.rb
spec/requests/buffer_updates_spec.rb
spec/system/articles/user_deletes_an_article_spec.rb

This is a page where people can add additional info about their posts behind the scenes for purposes of distribution of the content, etc.
TODO: Notification after publish that guides people here.

Add page for users to "manage" their posts after publication (distribution, etc.)

---

app/controllers/articles_controller.rb

Fix bug where we query for all buffers by user and not just one for this article.

Fix buffer_updates conditional in /manage

---

app/controllers/internal/users_controller.rb
app/models/user.rb
app/views/internal/users/_credits.erb
spec/requests/internal/users_spec.rb

Allows admins to remove available user credits from internal/users.

Allow admins to remove credits from internal/users

---

app/assets/stylesheets/articles.scss

Making UX improvement on chronofiter link hover

[SMALL] UX improvement on chronofiter hover

---

app/liquid_tags/stackblitz_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/stackblitz_tag_spec.rb

Add support for the `file` argument in Stackblitz embeds.
fixes #2589

Add file argument to Stackblitz embed.

---

app/helpers/social_image_helper.rb

Move the guard until after the main image return

Fix social image order logic

---

app/liquid_tags/tag_tag.rb
app/views/tags/_liquid.html.erb

Refactor render to use html.erb instead of markdown_parser
#2559 Tracker

dev tag liquid tag render utilize html.erb

---

app/views/articles/tag_index.html.erb

This should help some key pages get cached and stay cached a bit better.

Quick minor cache improvements to tag index

---

app/models/article.rb
app/models/organization.rb
spec/models/article_spec.rb

One more field that needs to go in for this to work.

Add profile_image_90 to serialized data on article

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/controllers/stories_controller.rb
app/models/article.rb
app/models/organization.rb
app/views/additional_content_boxes/_article_box.html.erb
app/views/articles/_single_story.html.erb
app/views/articles/_tag_identifier.html.erb
app/views/articles/index.html.erb
app/views/stories/_main_stories_feed.html.erb
spec/models/article_spec.rb

The minimal info we need to serve this content now lives on the user.

Remove includes user from stories query to reduce num queries and memory

---

app/assets/stylesheets/credits.scss
app/controllers/credits_controller.rb
app/views/classified_listings/_form.html.erb
app/views/credits/new.html.erb

- Adjust styling on /credits/new
- Update pricing logic

Update Listings Price

---

app/views/credits/new.html.erb

Updated the condition to let users input keypad numbers. 
[Javascript Char Codes (Key Codes)](https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes)
N/A

Fixes custom listing credit amount bug #2566

---

app/assets/stylesheets/classified_listings.scss
app/assets/stylesheets/classified_listings_form.scss
app/javascript/listings/elements/bodyMarkdown.jsx
app/javascript/listings/elements/categories.jsx
app/javascript/listings/elements/tags.jsx
app/javascript/listings/elements/title.jsx
app/javascript/listings/listingForm.jsx
app/javascript/packs/listingForm.jsx
app/models/classified_listing.rb
app/views/classified_listings/_form.html.erb
app/views/classified_listings/new.html.erb

This moves the listing form over to Preact, and more notably adds autocomplete for tags.
As a side note, I changed some CSS and made them less nested. It still relies on the old CSS though and that should probably be updated at some point.

Move new listing form to Preact

---

app/javascript/listings/elements/tags.jsx
app/javascript/packs/listingForm.jsx

- Make "create listing" button work with InstantClick
- prevent autocomplete in tags `<input>`

Make "create listing" button work with InstantClick

---

app/assets/stylesheets/_mixins.scss
app/assets/stylesheets/ltags/TagTag.scss
app/assets/stylesheets/more-articles.scss
app/assets/stylesheets/notifications.scss
app/assets/stylesheets/settings.scss

Continuing on the refactor of using the `themeable` SASS mixin.
#2539
N/A

More themeable mixin in action.

---

app/controllers/articles_controller.rb
config/routes.rb
spec/requests/articles_spec.rb
spec/requests/rss_feed_spec.rb

As a user of the feed, this is something I'm excited about having 😄 
This change adds a tag param to the RSS feed, allowing a consumer of the feed to filter the returned articles on a single tag. I wanted to keep this first pass simple, but down the road this could potentially grow to:
- Support for multiple tags
- Support for a specific user's followed tags
Resolves #201
N/A

Customize RSS feed by tag

---

app/controllers/classified_listings_controller.rb

- Should update credit spend from org account if user select org, and not user's personal account.

Deduct credits from proper account (personal vs org)

---

app/models/classified_listing.rb

- Add rules to all categories
- Update names for two categories

Update category rules

---

app/controllers/internal/users_controller.rb
app/models/credit.rb

- Create methods to add/remove credits
- Refactor internal/user to use the new methods

Add method to award & remove credits

---

app/assets/stylesheets/_mixins.scss
app/assets/stylesheets/article-show.scss
app/assets/stylesheets/article_form.scss
app/assets/stylesheets/ltags/TagTag.scss
app/assets/stylesheets/more-articles.scss
app/assets/stylesheets/notifications.scss
app/assets/stylesheets/settings.scss

Continuing on the refactor of using the themeable SASS mixin initiated by @nickytonline.
According to [this comment](https://github.com/thepracticaldev/dev.to/pull/2667/commits/c0748936670e8485b1cc11ed08df70a0e5348eec#r280650480), [this PR](https://github.com/thepracticaldev/dev.to/pull/2667) needs to be approved and merged first, in order for my changes to work(themable-important).
[#2539](https://github.com/thepracticaldev/dev.to/issues/2539)
N/A

More themeable mixin

---

app/liquid_tags/stackblitz_tag.rb
app/views/liquids/_stackblitz.html.erb

TBA
https://github.com/thepracticaldev/dev.to/issues/2559
n/a

Change StackBlitz to utilize ActionController

---

app/models/badge_achievement.rb
spec/models/badge_achievement_spec.rb

I didn't change the copy just yet. I figured we can adjust that when we roll these out as a real thing early next week.

Award credits along with badge achievements

---

app/labor/badge_rewarder.rb

Award contributor badge to DEV Android contributors
Fixes #2685

Award contributor badge to DEV Android contributors

---

app/controllers/internal/users_controller.rb
app/models/credit.rb
app/models/user.rb
app/views/internal/users/_credits.erb

- If a user is part of an org, display org credits and option to add/remove credits.

Manage org credits in internal

---

app/models/credit.rb
db/migrate/20190504131412_add_credits_count_to_users.rb
db/schema.rb
spec/models/credit_spec.rb

Allows us to sort and query based on number of credits more easily.

Add credits counter_culter to users and orgs

---

app/helpers/social_image_helper.rb

Previous fixes did not account for "" effectively.

Accurately guard against blank social image

---

app/assets/stylesheets/classified_listings.scss
app/javascript/listings/elements/categories.jsx
app/javascript/listings/listings.jsx
app/javascript/listings/singleListing.jsx
app/views/classified_listings/index.html.erb

So far I've added:
- A link to the title of on the single listing card
- JS and CSS that allows you toggle between an overlay by clicking the link and outside of the overlay
- Changing the URL of the browser when you click a single listing
Still need to add:

WIP Add modal for single listings

---

README.md

Fixes broken link of `maintain your fork` guide in README.md. Currently it shows `page not found` message.

Bug Fix: Broken Link in README.md

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/classified_listings.scss
app/controllers/classified_listings_controller.rb
app/javascript/listings/elements/title.jsx
app/javascript/listings/listings.jsx
app/javascript/listings/singleListing.jsx
app/javascript/packs/listingForm.jsx
app/views/classified_listings/_form.html.erb
app/views/classified_listings/index.html.erb
app/views/podcast_episodes/_meta.html.erb
config/routes.rb

Allow modal to be displayed, and misc advances

Update JS listings form and other tweaks

---

app/models/buffer_update.rb

Fix issue where we're taking the old text instead of new text for buffer updates

Fix buffer text not updating

---

app/controllers/reading_list_items_controller.rb

Fix caching issue on initial readinglist push

---

app/javascript/readingList/readingList.jsx

Currently querying way too much on load. Wasteful.

Change number of reactions queried

---

app/models/reaction.rb

This line wasn't doing anything because it's currently being overridden in the Algolia console. Better to remove it altogether.

Remove unnecessary line in reaction algolia

---

app/controllers/credits_controller.rb
spec/requests/credits_spec.rb

This adds a bunch of tests for purchasing credits. I think it covers most cases, and this should be a good start.

Add tests for purchasing credits

---

app/controllers/dashboards_controller.rb
app/views/dashboards/_actions.html.erb
app/views/dashboards/following.html.erb

Now that we have the ability to follow podcasts, this commit updates the
following page to reflect these changes.
https://github.com/thepracticaldev/dev.to/pull/2690

Update following page with podcasts

---

app/assets/stylesheets/classified_listings.scss
app/assets/stylesheets/credits.scss
app/views/classified_listings/_form.html.erb
app/views/classified_listings/new.html.erb
app/views/credits/new.html.erb

Finalize the look of the forms

Modify form style on listing and credit forms

---

app/assets/stylesheets/classified_listings.scss
app/controllers/credits_controller.rb
app/views/classified_listings/_form.html.erb
app/views/credits/index.html.erb
app/views/credits/new.html.erb
config/routes.rb

Fix problems with mobile view. Also change from `/credits/new` to `/credits/purchase` which makes more sense IMO.

Fix listings form styles

---

app/controllers/classified_listings_controller.rb
config/routes.rb

- An admin feature for managing listings

Enable /moderate for listings

---

app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
app/assets/javascripts/utilities/buildCommentHTML.js.erb
app/assets/stylesheets/articles.scss
app/helpers/articles_helper.rb
app/views/articles/_actions.html.erb
app/views/articles/_bottom_content.html.erb
app/views/comments/_comment_proper.html.erb
app/views/comments/_form.html.erb
app/views/notifications/_article.html.erb

This PR improves accessibility on the homepage and the "article show" page.
Aside from the "loading" text loader, I've avoided changing colors when it complained about contrast ratios.
Maybe this #2370 
**homepage before**
**homepage after**
**article show before**
**article show after**

Improve accessibility score on homepage and article show page

---

app/assets/stylesheets/chat.scss

Continuing on the refactor of using the themeable SASS mixin.
#2539

Refactors SASS themeable style discussed at #2539

---

app/views/users/_billing.html.erb

Removing the routes for `StripeSubscriptionsController` caused an issue with the billing page. 
Fixes #2743

Use proper stripe card path for the form

---

app/liquid_tags/runkit_tag.rb
app/views/liquids/_runkit.html.erb
spec/liquid_tags/runkit_tag_spec.rb
spec/support/fixtures/approvals/runkit_liquid_tag_spec.approved.html

Refactor runkit liquid tag to render using ActionController
Tracker #2559

Change Runkit liquid tag to utilize ActionController

---

app/liquid_tags/replit_tag.rb
app/views/liquids/_replit.html.erb

Refactor the Repl.it Liquid tag to render using ActionController
#2559 Tracker

Repl.it Liquid tag render to utilize ActionController

---

app/liquid_tags/jsfiddle_tag.rb
app/views/liquids/_jsfiddle.html.erb
spec/support/fixtures/approvals/jsfiddle_liquid_tag.approved.html

JS Fiddle Liquid tag rendering to use ActionController
#2559 Tracker

JS Fiddle Liquid tag render to utilize ActionController

---

app/liquid_tags/codesandbox_tag.rb
app/views/liquids/_codesandbox.html.erb

Refactor render method to utilize ActionController
#2559 Tracker

Codesandbox Liquid tag render to utilize ActionController

---

app/liquid_tags/instagram_tag.rb
app/views/liquids/_instagram.html.erb
spec/liquid_tags/instagram_tag_spec.rb
spec/support/fixtures/approvals/instagram_liquid_tag.approved.html

Refactor render method to utilize ActionController
#2559 Tracker

Instagram Liquid tag render to utilize ActionController

---

app/liquid_tags/blogcast_tag.rb
app/views/liquids/_blogcast.html.erb

Refactor render method to utilize ActionController
#2559 Tracker

Blogcast Liquid tag render to utilize ActionController

---

app/javascript/listings/listings.jsx

This PR enables closing an opened listing by pressing the Escape key.
https://github.com/thepracticaldev/dev.to/issues/1154

Close open listing modal when Escape key is pressed

---

app/jobs/notifications/tag_adjustment_notification_job.rb
app/models/notification.rb
app/services/notifications/tag_adjustment_notification/send.rb
spec/jobs/notifications/tag_adjustment_notification_job_spec.rb
spec/models/notification_spec.rb
spec/services/notifications/tag_adjustment_notification/send_spec.rb
spec/services/tag_adjustment_creation_service_spec.rb

- send_tag_adjustment_notification in own job
- specs for job + service
- send_tag_adjustment_notification in own job
- specs for job + service
#1996

Move tag adjustment notification to Active Jobs

---

docs/installation/linux.md
docs/installation/mac.md

This will fix the broken links to dev.to's PostgreSQL configuration documentation.

Docs: Fixes broken links

---

docs/design/theming.md

Updated [Theming Guidelines](https://docs.dev.to/design/theming/#theming-guidelines) section to explain how to use `themeable` and `themeable-important` SASS mixins.
#2539 
N/A

Docs: Added themeable styling documentation using SASS mixins

---

app/javascript/readingList/readingList.jsx

I fixed the empty message for an empty archive list. Some changes made based on the eslint errors and by eslint.
Resolves #2734

Fix Empty Message for Archive List

---

app/controllers/pages_controller.rb
app/models/page.rb
app/views/pages/information.html.erb
app/views/pages/show.html.erb
app/views/users/_publishing_from_rss.html.erb

We can now update the security and faq pages as a model, with the old thing as a fallback. Part of the journey towards having all the app pages non-hardcoded.

Add security and faq pages as generatable via the Page model

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb

Current user was occasionally not present on home page

Fix bug where user was not present on home page sometimes

---

app/javascript/article-form/articleForm.jsx

Didn't universally update the localstorage key stuff

Fix localstorage key

---

app/assets/stylesheets/dashboard.scss
app/views/dashboards/_dashboard_article.html.erb
app/views/layouts/application.html.erb

Some small adjustments to get this looking right.

Finalize archived posts in dashboard

---

app/assets/javascripts/initializers/initializeArchivedPostFilter.js

Add JS guard

---

app/models/article.rb

We have issues with blank canonical urls. This should fix it in many cases.
Fixes #2818

Turn blank canonical url into nil

---

app/liquid_tags/gist_tag.rb
app/views/liquids/_gist.html.erb
spec/liquid_tags/gist_tag_spec.rb

Refactor render method to use ActionController
#2559

Gist Liquid tag render to utilize ActionController

---

app/assets/javascripts/initializers/initializeReadingListIcons.js

The SAVE action triggers a bug due to a typo (not sure why it wasn't caught by ESLint nor it only appearad now)

Fix save article button action

---

app/liquid_tags/parler_tag.rb
app/views/liquids/_parler.html.erb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/parler_tag_spec.rb

Refactor render method to use ActionController
#2559

Parler Liquid tag render to utilize ActionController

---

app/liquid_tags/slideshare_tag.rb
app/views/liquids/_slideshare.html.erb

Refactor render method to use ActionController
#2559

SlideShare Liquid tag render to utilize ActionController

---

app/liquid_tags/glitch_tag.rb
app/views/liquids/_glitch.html.erb
spec/liquid_tags/glitch_tag_spec.rb

Refactor render to use ActionController
#2559

Glitch Liquid tag render to utilize ActionController

---

app/liquid_tags/medium_tag.rb
app/views/liquids/_medium.html.erb

Refactor render method to use ActionController
#2559

Medium Liquid tag render to utilize ActionController

---

app/javascript/article-form/articleForm.jsx
app/javascript/article-form/elements/notice.jsx
app/views/users/_misc.html.erb

Fixed the issue where v1 always said "publishing" on save even if it were a draft.

Fix text that says publishing for v1

---

app/views/users/_account.html.erb

Use proper `label` HTML tag for some field inputs that were missing them.
[#2834](https://github.com/thepracticaldev/dev.to/issues/2834)
BEFORE:
AFTER:

use <label>'s for input field labels on account settings page

---

app/assets/javascripts/initializers/initializeCommentDropdown.js
app/assets/stylesheets/article-show.scss

It looks like my previous PR failed to merge with master effectively. This is the fix for the JS and the other design adjustments.

Actually make fixes to uglification

---

app/assets/stylesheets/article-show.scss

Adjust bottom action bar padding

---

app/labor/email_digest.rb

Looks like the digest was still delivering to some people who had opt-ed out. This additional check should help prevent that from happening.

Double check opt-in before sending digest

---

app/jobs/notifications/update_job.rb
app/models/article.rb
app/models/notification.rb
app/services/notifications.rb
app/services/notifications/update.rb
spec/jobs/notifications/update_job_spec.rb
spec/models/notification_spec.rb
spec/services/notifications/update_spec.rb

- moved `Notification#update_notifications` method to ActiveJob
#1996 
#2497

ActiveJob for updating notifications #1996

---

app/assets/javascripts/initializers/initializeTouchDevice.js
app/assets/stylesheets/article-show.scss

Adjust some colors and padding on article show page related to design adjustments.

Fiddle with padding and adjust colors on show page

---

app/javascript/src/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/src/components/OnboardingSingleTag.jsx
app/javascript/src/components/OnboardingTags.jsx
app/javascript/src/components/__tests__/__snapshots__/OnboardingFollowTags.test.jsx.snap
app/javascript/src/components/__tests__/__snapshots__/OnboardingSingleTag.test.jsx.snap
app/javascript/src/utils/getUnopenedChannels.jsx

Started working on refactoring the *.jsx files for onboarding to make codeclimate and eslint happy
#2470

REF: Started refactoring onboarding react

---

app/jobs/notifications/milestone_job.rb
app/labor/article_analytics_fetcher.rb
app/models/notification.rb
app/services/notifications/milestone/send.rb
spec/jobs/notifications/milestone_job_spec.rb
spec/labor/article_analytics_fetcher_spec.rb
spec/models/notification_spec.rb
spec/services/notifications/milestone/send_spec.rb

- spec for job + move spec to service
Move send milestone notification in its on job and service
#1996

send_milestone_notification in own job

---

app/assets/stylesheets/preact/article-form.scss
app/controllers/articles_controller.rb
app/javascript/article-form/articleForm.jsx
app/services/article_creation_service.rb
app/views/articles/_v2_form.html.erb
spec/factories/users.rb
spec/requests/articles_create_spec.rb
spec/requests/articles_update_spec.rb

Add some features that have been missing in certain cases...
Proper notifications when saved and `edited_at`in all cases.

Fix up articles controller

---

app/controllers/articles_controller.rb
app/models/article.rb
app/views/articles/_v2_form.html.erb
app/views/articles/edit.html.erb
spec/models/article_spec.rb
spec/requests/articles_spec.rb

If a user has used a different editor to create an article, render that editor instead of their current one.

Render correct editor based on article's existing format

---

app/jobs/notifications/milestone_job.rb
app/models/notification.rb
spec/jobs/notifications/milestone_job_spec.rb

Make milestone hash more explicit, see https://github.com/thepracticaldev/dev.to/pull/2804#issuecomment-493032711 and following comments
#2804

Unpack milestone hash

---

app/views/api/v0/articles/show.json.jbuilder
spec/requests/api/v0/articles_spec.rb

Using `cached_tag_list_array` for consistency
See https://github.com/thepracticaldev/dev.to/pull/2844#discussion_r284698546

Use cached_tag_list_array for tags

---

app/views/users/_integrations.html.erb
spec/system/user/user_edits_integrations_spec.rb

Was just browsing around dev.to and realized there wasn't a submit
button on this page, so I added one!
I also got a system spec stood up to test this tab. I did not test the Github integration at all, but I tested that the twitch box saves

 Add Submit Button to Integrations Tab

---

app/controllers/image_uploads_controller.rb
app/errors/image_rate_limit_error.rb
app/labor/rate_limit_checker.rb
spec/requests/image_uploads_spec.rb

- Adds a custom exception for upload limit
- Displays appropriate error message

Limit number of cover image uploads per 30 seconds

---

README.md

This adds me to the core team's README list

Add rhymes to core team in README [ci skip]

---

app/jobs/notifications/remove_all_job.rb
app/models/notification.rb
app/services/notifications/remove_all.rb
spec/jobs/notifications/remove_all_job_spec.rb
spec/services/notifications/remove_all_spec.rb

- spec for job + service
- check actual integration spec
Move remove_all notifications method in its own job
#1996

Move remove_all notifications method in own job

---

app/controllers/articles_controller.rb
spec/requests/articles_update_spec.rb

After recent changes we lost a bit of organization logic that wasn't tested, so this is my attempt at fixing the bug. Thanks @Zhao-Andy for pointing me in the right direction :D
I plan to refactor the whole "article update" logic so that both the API and the frontend have the same capabilities and there's a central place where this logic resides, but this is for a future PR
Closes https://github.com/thepracticaldev/dev.to/issues/2871

Fix organization article ownership code

---

app/assets/stylesheets/articles.scss
app/controllers/classified_listings_controller.rb
app/controllers/stories_controller.rb
app/models/article.rb
app/models/classified_listing.rb
app/views/articles/_sidebar_additional.html.erb
app/views/layouts/_user_config.html.erb
spec/requests/stories_index_spec.rb

Adds the most recent classified listings to the home page right sidebar.

Add latest listings to home page

---

app/views/pages/api.html.erb
config/routes.rb
spec/requests/pages_spec.rb

Create a dev.to/api page where folks can go for all info about the API. I added it to the `pages_controller` but we will want to refactor this whole area later to better define what is and is not a "page".

Add API portal

---

app/assets/javascripts/initializers/initializePWAFunctionality.js
db/schema.rb

Add `noopener` to the PR to avoid any vulnerabilities or unwanted functionality here (Though I'm not sure this would apply to PWAs in the first place.) Better safe than sorry.

 Add noopener to external target blank links

---

app/assets/stylesheets/preact/onboarding-modal.scss

- [ ✅] Bug Fix
Make welcome message fit in the onboarding modal for all display sizes.
[Issue](https://github.com/thepracticaldev/dev.to/issues/2671)
[GIF](http://g.recordit.co/lSh90pp1QX.gif)
- [ ✅] no documentation needed

Closes #2671 by fixing the issue with the welcome message.

---

app/controllers/credits_controller.rb
spec/requests/credits_spec.rb

- Adds guard to make sure credits are only awarded if payment is successful

Award credits only if payment is successful 

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/scaffolds.scss
app/javascript/packs/homePage.js
app/views/articles/_sidebar_additional.html.erb
app/views/articles/index.html.erb
app/views/layouts/_user_config.html.erb

This adds the ability for the use to minimize listings on the home page, and localstorage will remember this for the next visit unless they un-minimize.

Make home page listings minimizeable

---

app/labor/markdown_parser.rb
spec/labor/markdown_parser_spec.rb

Fixes the generic error message with a proper one
Refers to (but does not completely solve) #2924

Add a proper exception in case of XSS attempt in markdown

---

app/controllers/internal/classified_listings_controller.rb
app/views/internal/users/_credits.erb

I accidentally pushed this to the same branch! They're somewhat related though.
- Busts cache and reindexes a listing when it's updated from internal/listings
- Required an admin to leave a reason for removing/adding credits to individuals/organizations.

Internal Updates - Bust Cache for Listings and Add Note for Credits

---

app/controllers/internal/classified_listings_controller.rb
app/models/organization.rb
app/models/user.rb
app/views/internal/classified_listings/edit.html.erb
app/views/internal/classified_listings/index.html.erb
app/views/layouts/internal.html.erb

- Adds pagination
- Adds username/organization 
- Tiny style adjustment to internal/listings/edit
- Adds search by username or listing title

Internal Listings View Enhancement

---

README.md

* Renamed "Basic Installation" to the correct "Standard Installation"
* Added link to Standard Installation

Fix wording in readme.md [skip ci]

---

app/controllers/internal/classified_listings_controller.rb

- Sorts listings index by most recently bumped.

Sort internal/listings by recently bumped listings

---

docs/getting-started/pull-request.md
docs/installation/readme.md
docs/tests/integration-tests.md

This will fix several links within the docs.dev.to's Getting Started, Installation, and Tests.

Docs: Fixes broken doc links

---

app/jobs/badge_achievements/send_email_notification_job.rb
app/models/badge_achievement.rb
spec/jobs/badge_achievements/send_email_notification_job_spec.rb

Uses ActiveJob to send an email for `BadgeAchivement`
#2497

Implemented ActiveJob for badge_achievements#send_email_notification

---

app/assets/stylesheets/article-form-needed-legacy.scss
app/assets/stylesheets/minimal.scss
app/views/layouts/_styles.html.erb

Fix css missing

---

app/liquid_tags/codepen_tag.rb
spec/liquid_tags/codepen_tag_spec.rb

Updates the liquid tag regex to allow underscores. Also adds a test using an underscore in the username section of the url to verify changes work.
Closes #2981 
N/A

Codepen Links with Underscore Usernames Flagged as Invalid

---

app/views/articles/_sticky_nav.html.erb

Slight modification of the article show sidebar cache so the cache doesn't last so long and has more variation at once.

Modify cache key for article sidebar cta

---

app/controllers/articles_controller.rb
app/javascript/article-form/elements/bodyPreview.jsx

Just a general cleanup of the `bodyPreview` component following eslint errors.
I was going through a bugfix that I'm unsure I'll be able to accomplish but I thought that this cleanup it's valid by itself so I'm submitting it separately

Cleanup bodyPreview component

---

app/jobs/notifications/remove_each_job.rb
app/models/notification.rb
app/services/notifications/remove_each.rb
spec/jobs/notifications/remove_each_job_spec.rb
spec/models/notification_spec.rb
spec/services/notifications/remove_each_spec.rb

- spec for job + service + notification
Move remove_each notifications method in its own job
#1996

Move remove_each notifications method in own job

---

app/controllers/articles_controller.rb
app/labor/cache_buster.rb
app/views/dashboards/_dashboard_article.html.erb

- I'm not sure exactly what was going on but I don't think `@org_members` was getting properly passed through to the view. This is a quick fix that doesn't rely on that variable.

Two fixes: org admin manage page & busting rails cache on comments

---

app/assets/stylesheets/classified_listings.scss
app/javascript/listings/listings.jsx
app/models/classified_listing.rb
app/views/classified_listings/_form.html.erb
app/views/classified_listings/edit.html.erb

Allow's listings creators to be contacted directly via DEV Connect

Finalize DEV Connect for listings

---

app/javascript/listings/listings.jsx

Fix the list of targets which trigger modal close

Fix close modal click action

---

app/assets/stylesheets/comments.scss

[Theme] Fixes inappropriate comment header background color bug #3020

---

app/views/users/_profile.html.erb

This was so upsetting I fixed it on mobile.
- [ X ] Bug Fix
🔐

User website URL should be https

---

app/assets/stylesheets/classified_listings.scss

Adds spacing to fully access messaging modal and hides scrollbar
#3026

Adjust listing modal view spacing and hide scroll bar

---

app/assets/stylesheets/dashboard.scss
app/controllers/credits_controller.rb
app/javascript/article-form/articleForm.jsx
app/javascript/listings/listingForm.jsx
app/views/articles/_v2_form.html.erb
app/views/classified_listings/_form.html.erb
app/views/credits/index.html.erb
app/views/dashboards/_actions.html.erb
app/views/dashboards/pro.html.erb
app/views/dashboards/show.html.erb

- Modify dashboard design to de-clutter
- Ensure org dropdown only shows up when user is part of org
- Ensure proper credit counts are tabulated
- Add a couple missing `title` tags (which were always missing)

Finalize multi-org features

---

app/labor/podcast_feed.rb
spec/labor/podcast_feed_spec.rb

- added more `PodcastFeed` specs
- small refactorings
#2952

Added specs for the PodcastFeed #2952

---

README.md

Keeping it simple. Let me know if i should add more.
https://github.com/thepracticaldev/dev.to/issues/3042
n/a

Add Vulnerability disclosure to README

---

app/services/moderator/manage_activity_and_roles.rb

This potentially fixes a bug where banishing a user for spam doesn't clear the cache properly. The possible reason might be that the articles need to be cache busted _after_ being deleted.

Cache bust banished users' posts after the posts are deleted

---

CONTRIBUTING.md

Format issue label in CONTRIBUTING.md

Format issue label in CONTRIBUTING.md [skip ci]

---

app/lib/constants.rb

Add the linuxrocks.online Mastodon instance to the whitelist
Following the directions from [this comment](https://dev.to/citizen428/comment/7bk4)
N/A

Add linuxrocks.online to Mastodon whitelist

---

app/views/pages/contact.html.erb

Adds bug bounty info to contact page 
https://github.com/thepracticaldev/dev.to/issues/3042

Adds bug bounty and security info to contact page

---

app/assets/javascripts/hello-dev.js

Adds bug bounty info to console
https://github.com/thepracticaldev/dev.to/issues/3042

Adds bug bounty link

---

spec/services/analytics_service_spec.rb
spec/system/articles/user_edits_an_article_spec.rb

Fix inconsistent spec

---

app/views/users/_account.html.erb

Added the DEV API link (dev.to/api/) in the account settings UI.
PR Closes https://github.com/thepracticaldev/dev.to/issues/3114
N/A

docs: add DEV API link in the account settings UI

---

app/controllers/api/v0/articles_controller.rb
app/models/credit.rb

Refactors array creation in `Api::V0::ArticlesController` and `Credit` using `Array.new`

Refactor array creation

---

app/labor/timeframer.rb

Replaces conditional in `Timeframer#datetime` with a hash.

Refactor `Timeframer#datetime` to use a hash instead of a conditional

---

app/views/classified_listings/_form.html.erb

Set default state of "Contact via Connect" to be checked (true) by default.
resolves #3088

"Contact via Connect" checked by default

---

app/models/tag_adjustment.rb

Extracts compound conditional in `TagAdjustment#user_permissions` to a method.

Extracts compound conditional to a private method

---

spec/requests/admin/podcasts_spec.rb

Fix broken spec

---

app/controllers/notifications_controller.rb
app/views/notifications/index.html.erb

We're having some performance issues with org notifications and this is a quick fix to help it out before we get to the final fix.

Remove org notifications count from notifications view

---

app/assets/stylesheets/article-show.scss
app/controllers/notification_subscriptions_controller.rb
app/javascript/packs/notificationSubscriptionHandler.js
app/models/notification_subscription.rb
app/services/notifications/new_comment/send.rb
app/views/articles/_actions.html.erb
app/views/comments/settings.html.erb
app/views/dashboards/_dashboard_article.html.erb
spec/requests/notification_subscriptions_spec.rb
spec/services/notifications/new_comment/send_spec.rb

Allow users to subscribe to threads in a variety of ways.

Finalize UI for all types of notification settings

---

app/assets/stylesheets/article-show.scss
app/javascript/packs/notificationSubscriptionHandler.js

Small fixes in the notifications look and functionality

Adjust notification subscriptions JS and css

---

Envfile
app/controllers/internal/buffer_updates_controller.rb
app/controllers/social_previews_controller.rb
app/helpers/social_image_helper.rb
app/labor/bufferizer.rb
app/models/buffer_update.rb
app/models/classified_listing.rb
app/views/classified_listings/index.html.erb
app/views/internal/articles/_article_script.html.erb
app/views/internal/articles/_individual_article.html.erb
app/views/internal/classified_listings/index.html.erb
app/views/layouts/internal.html.erb
app/views/social_previews/listing.html.erb
config/initializers/assets.rb
config/routes.rb
db/migrate/20190524214445_add_last_buffered_to_classified_listings.rb
db/schema.rb
db/seeds.rb
spec/labor/bufferizer_spec.rb
spec/requests/social_previews_spec.rb

- Refactors `_article_script.html.erb` so it can be used with listings buffer form submission.
- Keeps track of whether or not a listing has been buffered but _DOES NOT_ store the buffered text which means it does not create a BufferUpdate row. 
- Only submits to Twitter listings buffer (no facebook)
- Adds a spec to Bufferizer
- Add dynamic twitter card for individual listing.
**Before deploy: Add Buffer ID Code**

Buffer Listings

---

app/services/notifications/new_comment/send.rb

Modify text just a bit to mess with the formatting

Adjust text in mobile notification title

---

app/models/comment.rb
app/services/notifications/new_comment/send.rb

Make use of full space on ios notifications

Add subtitle to ios push notification

---

docs/installation/windows.md

I faced an undocumented error during the installation of DEV :  `ERROR:  Error installing pg`. This PR adds the required resolution for that.

Add a possible error resolution for windows installation

---

app/assets/stylesheets/ltags/PollTag.scss
app/controllers/html_variants_controller.rb
app/models/user.rb
app/views/html_variants/index.html.erb
app/views/html_variants/show.html.erb
app/views/layouts/_user_config.html.erb
app/views/users/_misc.html.erb
spec/models/user_spec.rb

Add new theme "minimal light" which includes more overall white and minimalism compared with the default theme.
Also tossed in some adjustments to the `html_variants` backend.

Add minimal light theme

---

app/liquid_tags/organization_tag.rb
app/views/organizations/_liquid.html.erb
spec/liquid_tags/organization_tag_spec.rb

Add organization liquid tag

---

Dockerfile

Fix some typos in Dockerfile comments

Fix some typos in Dockerfile comments

---

app/controllers/html_variant_successes_controller.rb
app/jobs/html_variant_success_create_job.rb
spec/jobs/html_variant_success_create_job_spec.rb
spec/requests/html_variant_successes_spec.rb

- add AJ job + job spec
- refactor call
Move HtmlVariantSuccess.create delay calls to ActiveJob
#3136

Move HtmlVariantSuccess.create delay calls to ActiveJob

---

app/controllers/articles_controller.rb
app/javascript/analytics/dashboard.js
app/javascript/packs/analyticsArticle.js
app/javascript/src/utils/errors.js
app/services/analytics_service.rb
app/views/articles/stats.html.erb

There was a bug where the frontend was not passing the organization id to the backend, and thus the fetching of the stats failed for organization articles.
This also adds a bit of error handling for `fetch` API

Display stats for organization article

---

app/models/chat_channel_membership.rb

Switch out hardcoded image for dynamic reference of file

Remove hardcoded image from chat channel images

---

app/controllers/internal/articles_controller.rb
app/views/internal/articles/_individual_article.html.erb
app/views/internal/tools/index.html.erb

- Gives admin the option to mark an article as buffered even if it didn't go through the usual buffer flow.

add buffered checkbox to individual articles

---

app/views/internal/classified_listings/index.html.erb

- updates text for listings buffer field

Update Listings Buffer Text

---

docs/installation/windows.md

https://github.com/thepracticaldev/dev.to/issues/3180

Update doc on statement_timeout errors

---

app/controllers/html_variant_trials_controller.rb
app/jobs/html_variant_trial_create_job.rb
spec/jobs/html_variant_trial_create_job_spec.rb
spec/requests/html_variant_trials_spec.rb

- add AJ job + job spec
- refactor call
Move HtmlVariantTrial.create delay calls to ActiveJob
#3136

    Move HtmlVariantTrial.create delay calls to ActiveJob (#3173)

---

app/labor/badge_rewarder.rb
spec/labor/badge_rewarder_spec.rb

Fix bug where tag badge rewarder wasn't accounting for only past week articles

Fix logic and adjust copy for tag rewarding

---

README.md

Adds the Dependabot badge to the readme.
https://github.com/dependabot/feedback/issues/6

Added the dependabot badge.

---

app/liquid_tags/gist_tag.rb
app/views/pages/_editor_guide_text.html.erb
spec/liquid_tags/gist_tag_spec.rb

Allow users to embed specific gist version.
Resolves #3267

Allow Embed of specific gist version

---

app/controllers/admin/users_controller.rb
app/dashboards/user_dashboard.rb
app/models/user.rb
app/policies/user_policy.rb
app/services/moderator/banish_user.rb
app/views/users/_profile.html.erb
app/views/users/_profile_header.html.erb
app/views/users/show.html.erb
db/migrate/20190626022355_add_instagram_url_to_users.rb
db/schema.rb
spec/models/user_spec.rb

Added Instagram Link option to profile links.
Resolves #3224

Add Instagram URL to profile links

---

app/black_box/black_box.rb

Quick fix to help sink post that is too popular 😄

Tweak black box so posts won't stick

---

app/models/podcast.rb
app/services/podcasts/get_episode.rb
spec/models/podcast_spec.rb

- optimized the query to get an existing podcast episode (@rhymes suggestion in the previous pr)
- added specs for getting the podcast episode
- fixed "undefined method #to_a" error when `unique_website_url?` is false
#2952

Refactored and optimized getting existing podcast episode

---

app/models/user.rb
app/views/internal/users/edit.html.erb

This allows admins to previously banished accounts again, in case something failed with the first attempt at banishing.

Allow multiple banishes on the same account

---

docs/installation/mac.md

Added two errors to the *possible error messages* section of the MacOS install guide. Both have to do with PostgresSQL installation issues.
Added horizontal rules to divide each *error* visually for better readability.
#768 faced similar issues.

expand common errors on macOS install

---

app/assets/javascripts/.eslintrc.js
app/assets/javascripts/initializers/initializeCommentPreview.js

Just some cleanup in the frontend.
N/A
N/A

frontend refactor/eslint fixes

---

app/controllers/pages_controller.rb
config/routes.rb
spec/requests/pages_spec.rb

This adds the `/challenge` redirect to the DEV team's latest challenge post/thread. Also refactors a wee bit.

Add /challenge redirect

---

app/controllers/internal/tools_controller.rb
app/views/internal/tools/index.html.erb
app/views/layouts/internal.html.erb

This allows full links for the internal cache buster tool. Also adds `tools` to the internal navbar.

Allow full links for cache buster tool

---

app/services/podcasts/feed.rb
config/locales/en.yml
spec/services/podcasts/feed_spec.rb
spec/support/fixtures/podcasts/arresteddevops.xml

Rescue possible `SSLError` when fetching a podcast 
#2952

Rescue possible SSLError when fetching a podcast 

---

spec/models/credit_spec.rb
yarn.lock

Drop vulnerabilities from
```
78 vulnerabilities found - Packages audited: 42457
Severity: 64 Low | 4 Moderate | 10 High
```
To
```
68 vulnerabilities found - Packages audited: 43826
Severity: 63 Low | 3 Moderate | 2 High
```
n/a
n/a

Run `yarn upgrade`

---

app/controllers/messages_controller.rb
app/jobs/messages/send_push_job.rb
app/models/message.rb
app/services/messages/send_push.rb
spec/jobs/messages/send_push_job_spec.rb
spec/services/messages/send_push_spec.rb

- add service + spec
- add AJ job + job spec
- refactor call
Move messages send_push delay calls to ActiveJob
#3136

Move messages send_push delay calls to ActiveJob

---

app/controllers/users_controller.rb
app/jobs/rss_reader_fetch_user_job.rb
spec/jobs/rss_reader_fetch_user_job_spec.rb

- add job + spec job
- refactor call
Move RssReader fetch_user to Active Jobs
#3136

Move RssReader fetch_user to Active Jobs

---

app/controllers/partnerships_controller.rb
config/routes.rb
spec/models/collection_spec.rb
spec/requests/partnerships_spec.rb
spec/requests/user_profile_spec.rb

Small rubocop fixes

---

app/controllers/profile_pins_controller.rb
app/models/profile_pin.rb
spec/models/profile_pin_spec.rb
spec/requests/profile_pins_spec.rb

Allow only five pins, not six.

Fix profile pin max off-by-one errror

---

app/controllers/pro_accounts_controller.rb
app/helpers/application_helper.rb
app/views/pro_accounts/index.html.erb
config/routes.rb
spec/requests/pro_accounts_spec.rb

If you're a casual observer, here is some insider info about upcoming stuff. The copy here is very raw but I promise that we will better nail down the offering here before we truly make this live.
Hopefully you love these new features 😄

Add basic (preliminary) pro accounts lander placeholder

---

app/controllers/partnerships_controller.rb
app/views/partnerships/_form.html.erb
app/views/partnerships/_tag_sponsor_copy.html.erb

Fix slackbot ping issue and tag copy

---

public/offline.html

* This add `cursor:pointer` to the color in dev.to Offline Page [https://dev.to/offline](https://dev.to/offline)
* Currently, when user hover over the colors, the opacity is reduced to 0.7
* To indicate that those colors are clickable, we can add `cursor: pointer`, this will make it works on Safari in Mobile too.
https://giphy.com/gifs/l57eptMN5gDTWfu2gB

Add cursor for color select in Offline Page

---

app/assets/stylesheets/credits.scss
app/services/credits/ledger.rb
app/views/credits/_ledger.html.erb
app/views/credits/_ledger_classified_listing.html.erb
app/views/credits/_ledger_sponsorship.html.erb
app/views/credits/index.html.erb
spec/requests/credits_spec.rb
spec/services/credits/ledger_spec.rb

Add Sponsorships to credits ledger

Credits ledger: show sponsorships

---

app/views/partnerships/_devrel_consult_copy.html.erb
app/views/partnerships/index.html.erb

Adjust copy and replace an accidentally-hardcoded number with a dynamic one.

Fix copy on sponsorship page

---

app/models/chat_channel.rb
app/views/api/v0/chat_channels/show.json.jbuilder

Fix unnecessary issue where we cut off the profile images for chat groups.

Fix chat channel details profile pic issue

---

app/javascript/listings/singleListing.jsx

Location value should be captured by query in URL. 
resolves #3463 
N/A

Fix location link in single listing

---

app/assets/stylesheets/articles.scss
app/black_box/black_box.rb
app/labor/flare_tag.rb
app/views/articles/_sidebar_additional.html.erb
app/views/classified_listings/_form.html.erb
spec/black_box/black_box_spec.rb

Adding a place for off-topic chitchat

Add watercooler as sidebar tag and watercooler flare

---

app/assets/stylesheets/classified_listings.scss
app/controllers/profile_pins_controller.rb
app/javascript/listings/listings.jsx
app/views/social_previews/listing.html.erb

Made social image have bigger font and more contrast. Added "About DEV Listings" button to the show view.

Adjust listings social image and add "About Listings" button to show page.

---

app/views/articles/_sidebar.html.erb

Forgot a missing `.find_each` for sponsors 🙈

Use each instead of find_each to preserve order

---

Dockerfile
app/controllers/classified_listings_controller.rb
app/controllers/internal/tools_controller.rb
app/controllers/twitch_stream_updates_controller.rb
app/javascript/chat/chat.jsx
app/labor/mailchimp_bot.rb
app/models/chat_channel.rb
app/models/profile_pin.rb
app/views/pages/faq.html.erb
config/environments/development.rb
config/initializers/reverse_markdown.rb
docker-run.sh
docs/backend/pusher.md
docs/getting-started/config-env.md
docs/installation/docker.md
spec/labor/email_logic_spec.rb
spec/lib/acts_as_taggable_on/tag_parser_spec.rb
spec/requests/twitch_stream_updates_spec.rb

Fix typos across **dev.to repository**
**Fixed files**
```
dev.to/Dockerfile:211:20: "requried" is a misspelling of "required"
dev.to/app/controllers/classified_listings_controller.rb:108:8: "substract" is a misspelling of "subtract"
dev.to/app/controllers/internal/tools_controller.rb:25:37: "artice" is a misspelling of "article"
dev.to/app/controllers/twitch_stream_updates_controller.rb:17:43: "Recieved" is a misspelling of "Received"
dev.to/app/javascript/chat/chat.jsx:388:36: "priviledge" is a misspelling of "privilege"
dev.to/app/labor/mailchimp_bot.rb:108:33: "unsubscibe" is a misspelling of "unsubscribe"
dev.to/app/models/chat_channel.rb:111:47: "reciever" is a misspelling of "receiver"
dev.to/app/models/chat_channel.rb:113:34: "reciever" is a misspelling of "receiver" …
```

Fix typos across dev.to repository

---

app/views/notifications/_milestone.html.erb

Change 'Your post **** just passed x views/reactions' to 'Your post **** passed x views/reactions' to avoid confusion as milestone notifications are not in real time.
Closes [#3520](https://github.com/thepracticaldev/dev.to/issues/3520)
First PR to dev.to so

Change milestone notification statement to make it more clear

---

app/assets/stylesheets/comments.scss

#3175  What type of PR is this? (check all applicable)
Remove duplicate property `border-top-left-radius: 3px;` for css class details.

Remove duplicate property border-top-left-radius

---

app/assets/stylesheets/preact/onboarding-modal.scss
app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/ClosingSlide.jsx
app/javascript/onboarding/components/IntroSlide.jsx

This adjusts some copy and spacing in the onboarding flow.

Tiny adjustments to copy and functionality of onboarding

---

app/assets/stylesheets/comments.scss

#3175  What type of PR is this? (check all applicable)
Without overflow-x: auto an unintended scrollbar appeared below codeblocks in some browsers.
Fixes #3544

Added overflow-x: auto to comments.scss

---

app/views/partnerships/_bronze_sponsor_copy.html.erb
app/views/partnerships/_devrel_consult_copy.html.erb
app/views/partnerships/_gold_sponsor_copy.html.erb
app/views/partnerships/_media_sponsor_copy.html.erb
app/views/partnerships/_silver_sponsor_copy.html.erb
app/views/partnerships/_tag_sponsor_copy.html.erb

Add better details for partnership pricing

Add more partnership pricing info

---

app/models/article.rb
app/views/dashboards/_dashboard_article.html.erb
spec/models/article_spec.rb
spec/requests/dashboard_spec.rb

* Create edited? and readable_edit_date methods for article model
* Show article edit date in dashboard for edited articles
* Add some styling
Add article edited date in dashboard 
closes #3274
Desktop:
Mobile:

Show article edit date in dashboard

---

config/initializers/doorkeeper.rb
spec/requests/api/v0/articles_spec.rb

Also refactored some test
n/a
n/a

Make Doorkeeper inherit from ApplicationController

---

spec/requests/internal/podcasts_spec.rb

This fixes a couple of deprecation warnings I've noticed in the build

Fix deprecations in internal/podcasts_spec

---

app/controllers/articles_controller.rb
app/models/collection.rb
spec/factories/collections.rb
spec/models/collection_spec.rb

Collection: remove optional user and add tests

---

README.md

Remove ali from dev core team :(

remove ali from readme :(

---

app/assets/javascripts/hello-dev.js
app/views/layouts/_footer.html.erb

The Hello DEV banner had been accidentaly disabled by #3220, this re-enables it

Re-enable hello dev in console

---

Gemfile

All PRs from Dependabot is updating our git protocol (see https://github.com/thepracticaldev/dev.to/pull/3626/commits/487357f955307ba103378c19f267d61cdb3e7757 for example). I also have personally ran into this issue on my dev machine. As per https://github.com/dependabot/feedback/issues/480#issuecomment-496018298 , this is the recommended course of action.
see description

Add git source to Gem file

---

README.md
app/views/pages/_terms_text.html.erb
app/views/pages/sponsors.html.erb
app/views/pages/sponsorship_faq.html.erb

- Point ppl to partnerships page instead of peter@dev.to
- Update content policy to reflect affiliate link disclosure.
- Update broken licensing link in readme

Update content policy and faqs about sponsorship

---

app/lib/constants.rb

This adds [hackers.town](https://hackers.town) to the list of allowed Mastodon instances.

Add hackers.town to allowed Mastodon instances

---

app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
app/javascript/article-form/articleForm.jsx

Resolved the issue of the upload and config page overlapping with the help page and preview page. I also made some changes based on the eslint. I am not so familiar with Preact so only made changes I was comfortable with.
Resolves #3316

Fix upload overlap with editor/help page

---

CONTRIBUTING.md
README.md

Seems like the contributing guide was just pasted into the readme previously, no point in updating two areas. Also updated language for some clarity.

[skip ci] update contributing.md and readme for clarity

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This PR contains some updates to our contributing guide in line with the current state of the project

Updates to the contributing guide

---

.github/PULL_REQUEST_TEMPLATE.md

Add force push notice to the PR template

---

app/views/pages/sponsors.html.erb

- Only attempt to display sponsor blurb if a blurb exists
- Remove blurb from bronze sponsorships (that was previously added by accident!)

Fix /sponsors page

---

docs/backend/algolia.md

Small change to improve a sentence

Adjust Algolia documentation

---

app/controllers/api/v0/articles_controller.rb
app/views/api/v0/articles/_flare_tag.json.jbuilder
app/views/api/v0/articles/_organization.json.jbuilder
app/views/api/v0/articles/_user.json.jbuilder
app/views/api/v0/articles/index.json.jbuilder
app/views/api/v0/articles/me.json.jbuilder
app/views/api/v0/articles/show.json.jbuilder
docs/api_v0.yml
spec/requests/api/v0/articles_spec.rb

This PR adds info about OAuth2 auth flows to the API doc, tests the ordering of unpublished articles and documents `/api/articles/me`

API docs: Document OAuth2 and /api/articles/me

---

docs/backend/notification.md
docs/backend/readme.md

Add notification section to docs/backend
#3672

Add notification section to docs

---

app/services/notifications/new_mention/send.rb
spec/services/notifications/new_mention/send_spec.rb

The bug was introduced here: https://github.com/thepracticaldev/dev.to/commit/f9da88b006a7d721b8331ad9851892494ca3434c
Fixes #3718

Fix mention notification to mention proper user

---

app/javascript/article-form/articleForm.jsx

This deletes some unused, commented-out code in the article form.

Delete unused, commented-out code

---

app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx

- [x ] Bug Fix
emailing related <input>  were missing an id to refer to their  <label> parent.
Issue #3720
- [x ] no documentation needed

Onboarding : fixed bug that prevented toggle by clicking on label

---

app/assets/javascripts/initializers/initializeBaseTracking.js.erb
app/views/pages/badge.html.erb

We already take measures on the back end to ensure user privacy, but this adds one additional measure of obvious privacy protection for users. We don't do any granular tracking and want to increasingly make it impossible to do so.

Adjust Google Analytics params to further increase user privacy

---

app/views/articles/_badges_area.html.erb
app/views/users/_sidebar_additional.html.erb

Make sure the layout is consistent when rendering badges on the sidebar
fixes #3724

Fix badges order on profile sidebar

---

app/assets/stylesheets/articles.scss
app/assets/stylesheets/variables.scss
app/controllers/partnerships_controller.rb
app/models/sponsorship.rb
app/views/articles/_single_sponsor.html.erb
app/views/articles/tags/_sidebar.html.erb
app/views/pages/_sponsor_image.html.erb
app/views/pages/sponsors.html.erb
app/views/partnerships/_tag_sponsor_copy.html.erb
app/views/tags/index.html.erb
spec/requests/partnerships_spec.rb
spec/requests/stories_index_spec.rb

- I didn't touch gold sponsors since I think we still handle that somewhat manually.
- Made sure bronze, silver, tag sponsors only appear in areas if the sponsorship is marked as live and not expired.
- Automatically add 30 day expiration date to tag sponsors (did not add it directly to levels because that was a uniqueness constraint)
- Updated the tag sponsorship copy to reflect current offering
- Added a blurb for tag sponsors and removed tagline
- Update /sponsors for night theme 
- Updated our internal docs that tag sponsorships must include a short blurb, which is consistent with the offering.
#3713

Sponsorship Updates

---

package.json
yarn.lock

Simply upgrading Preact fixes the React DevTools issue. I know Dependabot handles updates, but not sure when it's going to create a PR for this, so I just went ahead and created one. I figure the sooner it gets fixed, the less people panic about a bug that is a false negative
#3744

Updated Preact to fix React DevTools errors.

---

app/controllers/internal/growth_controller.rb
app/views/internal/growth/_results.html.erb
app/views/internal/growth/index.html.erb
config/routes.rb

Simple dashboard to track "growth" tests

Add internal dashboard for growth

---

app/assets/javascripts/initializers/initializeArticleReactions.js
app/assets/stylesheets/article-show.scss
app/views/articles/_collection.html.erb
app/views/layouts/_user_config.html.erb

This PR redesigns the series display feature for articles.
It shows the title of each article and squishes the middle ones so a series can have a lot of posts without an overflow design.

Redesign series style

---

.rubocop.yml
.rubocop_todo.yml
app/liquid_tags/stackexchange_tag.rb
spec/models/user_spec.rb

- made a couple of rubocop fixes
- altered configuration so that there would be no violations

Rubocop fixes and config update

---

app/controllers/articles_controller.rb
spec/requests/articles_update_spec.rb

Fixes erroneous response for video image changes

Fix video image redirect issue

---

app/assets/javascripts/.eslintrc.js
app/assets/javascripts/utilities/sendFetch.js
app/assets/javascripts/utilities/sendHapticMessage.js
app/assets/javascripts/utilities/showModal.js
app/assets/javascripts/utilities/slideSidebar.js
app/assets/javascripts/utilities/timeAgo.js
app/assets/javascripts/utilities/userData.js

Fixed some lint issues in the frontend.
Part of the work for #3777

Fixed some lint issues

---

app/assets/javascripts/initializePage.js.erb
app/assets/javascripts/initializers/initializeUserProfilePage.js
app/assets/stylesheets/user-profile-header.scss
app/views/users/show.html.erb

This feature adds a dropdown menu on user profiles. For now it just has a report abuse button but in the future could have a block button or any other supplementary functionality for users.
Closes #398

Add dropdown and report-abuse for users

---

app/controllers/classified_listings_controller.rb
spec/requests/classified_listings_spec.rb

Do not allow users with `banned` role to create/update listings. Anti-spam measure.

Remove listings privileges from banned users (Anti-spam)

---

app/controllers/chat_channels_controller.rb

Adding `set_channel` private method for not repeating query code.

Refactoring chat_channels_controller.rb.

---

app/assets/javascripts/utilities/browserStoreCache.js
app/assets/javascripts/utilities/checkUserLoggedIn.js
app/assets/javascripts/utilities/createAjaxReq.js
app/assets/javascripts/utilities/getCurrentPage.js
app/assets/javascripts/utilities/getImageForLink.js
app/assets/javascripts/utilities/insertAfter.js
app/assets/javascripts/utilities/localDateTime.js
app/assets/javascripts/utilities/localStorageTest.js
app/assets/javascripts/utilities/preventDefaultAction.js

Fixes lint issues in ./dev.to/app/assets/javascripts/utilities/
- browserStoreCache.js
- checkUserLoggedIn.js
- createAjaxReq.js
- getCurrentPage.js
- getImageForLink.js
- insertAfter.js
- localDateTime.js
- localStorageTest.js
- preventDefaultAction.js
Partial work under #3777

Fixes some lint issues

---

app/controllers/dashboards_controller.rb

Refactoring dashboards_controller.rb.

---

app/controllers/organizations_controller.rb

Adding set_organization method for not repeating query code.

Refactoring organizations_controller.rb.

---

app/controllers/downloads_controller.rb
app/views/downloads/index.html.erb
app/views/pages/information.html.erb
config/routes.rb
spec/system/user_visits_downloads_page_spec.rb

Add a page ``/downloads`` with links to the DEV app on the play store and app store. 
Related to #3736

Add android and ios apps download page (#3736)

---

app/controllers/internal/growth_controller.rb
app/javascript/onboarding/Onboarding.jsx
app/javascript/onboarding/components/ClosingSlide.jsx
app/services/authorization_service.rb
app/views/internal/growth/_results.html.erb
app/views/internal/growth/index.html.erb
spec/models/user_spec.rb

This PR adds variants to onboarding that emphasize posting in the welcome thread primarily. Also adds more data to growth slide.

Add onboarding variants and update variant display ratio

---

docs/backend/auth-github.md

Backend github authentication
- first item says "sign in" when it actually links you to
creation of a OAuth application

Backend docs: github authentication updated

---

app/controllers/liquid_embeds_controller.rb
app/views/liquid_embeds/show.html.erb
config/routes.rb
spec/requests/liquid_embeds_spec.rb
spec/support/fixtures/vcr_cassettes/LiquidEmbeds/get_/embeds/renders_proper_tweet.yml

Gives an endpoint for rendering individual "liquid tags" based on the info provided. For the rendering of DEV posts off-site.

Create endpoint for liquid tag embed

---

app/controllers/social_previews_controller.rb

Refactoring repeated `respond_to` code.
#3739

Refactoring social_previews_controller.rb.

---

app/views/mailers/digest_mailer/digest_email.html.erb

Add listings links to DEV digests
n/a

Add listings to DEV digests

---

app/controllers/internal/mods_controller.rb
app/labor/assign_tag_moderator.rb
app/views/internal/mods/index.html.erb
app/views/layouts/internal.html.erb

Update mod internal backend to be safer and more intuitive

---

app/controllers/api/v0/webhooks_controller.rb
app/models/user.rb
app/models/webhook/endpoint.rb
app/models/webhook/event.rb
app/views/api/v0/webhooks/show.json.jbuilder
config/routes.rb
db/migrate/20190819104106_create_webhook_endpoints.rb
db/schema.rb
spec/factories/webhook_endpoints.rb
spec/models/webhook/endpoint_spec.rb
spec/requests/api/v0/webhooks_spec.rb

- `WebhookEndpoint` model
- api to create and destroy webhooks
#3715

Webhook endpoints and webhook API #3715

---

app/controllers/internal/mods_controller.rb
app/views/internal/mods/index.html.erb
app/views/layouts/internal.html.erb

This feature fixes a prod-only redirect issue in internal and adds a few niceties to improve the admi flow here.

Fix internal mods interactivity and improve layout

---

app/helpers/feedback_messages_helper.rb
spec/helpers/feedback_messages_helper_spec.rb

We updated our email copy for internal/reports.

Update Email Copy for internal/reports

---

app/javascript/listings/__tests__/__snapshots__/singleListing.test.jsx.snap
app/javascript/listings/__tests__/singleListing.test.jsx
app/javascript/listings/singleListing.jsx

Adds Preact testing to `singleListing.jsx`
N/A
N/A

singleListing Testing

---

.vscode/settings.json

The newer versions [(0.25.0+)](https://github.com/rubyide/vscode-ruby/blob/master/CHANGELOG.md#0250---sept-1-2019) of vscode-ruby have updated some of their settings configuration. This commit updates the vscode settings to conform to the upstream changes.
Test failure is unrelated.

update vscode settings

---

app/liquid_tags/kotlin_tag.rb
spec/liquid_tags/kotlin_tag_spec.rb
spec/system/user_visits_downloads_page_spec.rb

My editor was really upset with me, so I made most of the suggested fixes with Rubocop.
Generally, I like the changes it suggested, but I'm happy to hear if someone has a different opinion, or if there is a problem with the changes that Rubocop made.

Fix rubocop complaints

---

app/views/pages/_editor_guide_text.html.erb

Added the pixel limit per frame/page to the Editors Guide as a first step described by jessleenyc 
resolves #3828

Adding pixel limit to Editors Guide

---

app/controllers/comments_controller.rb
app/controllers/image_uploads_controller.rb
app/jobs/rate_limit_checker_job.rb
app/labor/rate_limit_checker.rb
app/services/articles/creator.rb
app/services/ping_admins.rb
spec/jobs/rate_limit_checker_job_spec.rb
spec/labor/rate_limit_checker_spec.rb

Update PingAdmins to triggering event

---

README.md

Split infinitives are super subjective:
https://www.quickanddirtytips.com/education/grammar/split-infinitives

Add commas and fix split infinitive

---

app/views/partnerships/_bronze_sponsor_copy.html.erb
app/views/partnerships/_silver_sponsor_copy.html.erb
app/views/partnerships/index.html.erb

Update copy for partnerships index and show pages.

Remove homepage placement for bronze and silver

---

docs/backend/roles.md

This PR updates the roles docs to avoid a deprecation error.
All queries have been tested

Roles docs: Fix aggregated query to avoid deprecation

---

app/javascript/src/components/ItemList/ItemListItem.jsx
app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListItem.test.jsx.snap

fixes 0 min reading time in reading list by setting the default reading time to 1 min
See #3217

Reading list: set default reading time to 1 minute

---

app/assets/javascripts/hello-dev.js

Added some line breaks to make this more readable!
Before:
After:

Update and format console copy [ci skip]

---

app/controllers/liquid_embeds_controller.rb

Modify headers to allow iframes for embed endpoints

Modify headers to allow embed

---

docs/deploy-script.js
netlify.toml

This enables https://storybook.dev.to and allows us to show our Storybook components. Our current Storybook setup still has issues to be resolved, but the groundwork for deployment is available.
The script used to deploy to Netlify is a custom script, big thanks to https://stackoverflow.com/questions/54165581/any-way-to-have-a-common-netlify-toml-file-for-a-single-repository-and-multiple
Closes #338

Add Setup for storybook.dev.to

---

app/controllers/image_uploads_controller.rb

This PR simplifies a bit the uploading method and removes the if condition

Simplify the images uploading code

---

docs/deploy-script.js

This fixes a bug where the incorrect build command was being run for docs.dev.to.

Use make build instead of only gitdocs command

---

app/assets/stylesheets/feedback_messages.scss

Add some missing theme colors!
Before:
After:

Make report notification use theme colors

---

app/assets/stylesheets/preact/article-form.scss
app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
app/javascript/article-form/articleForm.jsx
app/javascript/article-form/elements/imageManagement.jsx

Now that #3599 is in, I've updated the wording (and the spacing in a button) for the fact that we allow multiple images to be uploaded at a time.
See #3599

Images uploads: fix UI for multiple images

---

CONTRIBUTING.md

joining the ~tres~ cuatro comma club

Add missing commas [ci skip]

---

docs/backend/algolia.md

Updating backend guide docs >Algolia>Step 7
Resolves #3799 
- Desktop 
-Mobile

Update image of Algolia backend docs

---

app/controllers/api/v0/comments_controller.rb
app/controllers/api/v0/tags_controller.rb
app/controllers/chat_channels_controller.rb
app/controllers/comments_controller.rb
app/controllers/internal/articles_controller.rb
app/controllers/internal/reactions_controller.rb
spec/models/article_spec.rb
spec/requests/pusher_auth_spec.rb

Commented out code is generally harmless, but there is no need to
include this code because it is in version control. Remove this code
should have no negative impact, but make the code a little easier to
follow.
Commented out tests should be removed or marked pending so they aren't
forgotten about.

Remove commented code and tests

---

app/controllers/internal/webhook_endpoints_controller.rb
app/views/internal/shared/_navbar.html.erb
app/views/internal/webhook_endpoints/index.html.erb
app/views/layouts/internal.html.erb
config/routes.rb

Added a list of the webhook endpoints for admins in internal.
#3715 
I feel bad for the menu, we should do something about it, as the number of items grows.

Show webhooks list in internal

---

app/controllers/notifications_controller.rb
app/models/notification.rb

This fixes the notifications query logic to fetch the expected notifications

Fix notifications past aggregation query logic

---

app/views/doorkeeper/applications/_delete_form.html.erb
app/views/doorkeeper/applications/_form.html.erb
app/views/doorkeeper/applications/edit.html.erb
app/views/doorkeeper/applications/index.html.erb
app/views/doorkeeper/applications/new.html.erb
app/views/doorkeeper/applications/show.html.erb
app/views/doorkeeper/authorizations/error.html.erb
app/views/doorkeeper/authorizations/new.html.erb
app/views/doorkeeper/authorizations/show.html.erb
app/views/doorkeeper/authorized_applications/_delete_form.html.erb
app/views/doorkeeper/authorized_applications/index.html.erb
app/views/layouts/doorkeeper/admin.html.erb
app/views/layouts/doorkeeper/application.html.erb

https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views

Generate doorkeeper's view

---

app/views/mailers/notify_mailer/new_badge_email.html.erb

Fixes #3848 
Hey @maestromac !
The only way I could find to correctly render the links here was to hard code them, and that's what I did.
Let me know if there was any another way around it, and I'll do that.
Thanks!

fixed links in badge email

---

app/models/tweet.rb

⌘ + ⇧ + F
Safe navigation is faster than `try`, so in my opinion, it's better to avoid any instance of `try` if possible.

Replace try with safe navigation operator

---

app/controllers/internal/classified_listings_controller.rb
app/views/internal/classified_listings/index.html.erb

Adds dropdown filter with categories.
N/A

Internal Listings: Filter by Category

---

spec/policies/admin_policy_spec.rb
spec/policies/api_secret_policy_spec.rb
spec/policies/article_policy_spec.rb
spec/policies/block_policy_spec.rb
spec/policies/buffer_update_policy_spec.rb
spec/policies/chat_channel_membership_policy_spec.rb
spec/policies/chat_channel_policy_spec.rb
spec/policies/comment_policy_spec.rb
spec/policies/follow_policy_spec.rb
spec/policies/github_repo_policy_spec.rb
spec/policies/html_variant_policy_spec.rb
spec/policies/image_upload_policy_spec.rb
spec/policies/organization_policy_spec.rb
spec/policies/reaction_policy_spec.rb
spec/policies/stripe_active_card_policy_spec.rb
spec/policies/stripe_subscription_policy_spec.rb
spec/policies/tag_policy_spec.rb
spec/policies/user_policy_spec.rb

Experimenting with `build_stubbed` vs `build`. Not a huge different but was able to replace optimize some specs
n/a
n/a

Use build_stubbed in Policy specs

---

app/assets/javascripts/utilities/buildArticleHTML.js.erb

This fix the reading time issue caused by a tiny logic error 
Resolves https://github.com/thepracticaldev/dev.to/issues/4047

Fix reading time logic

---

app/controllers/api/v0/webhooks_controller.rb
app/views/api/v0/webhooks/index.json.jbuilder
config/routes.rb
spec/requests/api/v0/webhooks_spec.rb

Added an API endpoint so that users would be able to access their webhook endpoints list.
#3715

Api endpoint for user webhooks

---

app/assets/stylesheets/scaffolds.scss

The text alignment on this screen feels a little wrong. I think centering it looks quite a bit better. This PR also includes some formatting of the CSS.
I think in general there is a lot of opportunity for CSS love in this application 😅
Before:
After:

Fix delete container alignment

---

config/initializers/timber.rb

Implemented based on [this documention](https://docs.timber.io/setup/languages/ruby/integrations/rack#silence_request)
n/a
n/a
n/a
n/a

Silence page views log

---

app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
app/black_box/black_box.rb
app/controllers/stories_controller.rb
app/views/stories/_main_stories_feed.html.erb
spec/black_box/black_box_spec.rb

Modest algorithm adjustments to mix up the home feed a bit more.

Add more variation to home feed

---

app/views/articles/index.html.erb

Add climate strike widget

---

docs/api_v0.yml

Fixes `tags` format in the API docs
Closes #4073

Fix tags format in Article create API

---

app/controllers/internal/buffer_updates_controller.rb
app/models/article.rb
app/models/buffer_update.rb
app/models/role.rb
app/policies/application_policy.rb
app/policies/internal/article_policy.rb
app/policies/internal/buffer_update_policy.rb
spec/models/role_spec.rb
spec/policies/internal/buffer_update_policy_spec.rb

Change how authorization is done in `Internal::BufferUpdateController`
n/a
n/a

Adjust BufferUpdatesController's authorization

---

app/javascript/onboarding/components/IntroSlide.jsx
app/javascript/onboarding/components/SlideContent.jsx

Just a simple refactor that should make Code Climate a teeny bit happier.
https://www.loom.com/share/ad00613e55d9486f817510f9c1cc6fbc

Refactor intro slide component

---

app/models/pro_membership.rb
app/models/user.rb

Add a cache to the `pro?` method.

Cache pro membership

---

app/views/doorkeeper/authorizations/new.html.erb

Add styling for oauth page

---

app/javascript/chat/userDetails.jsx

Adds setUpButton function to avoid code duplication in userDetails.jsx.

Refactoring userDetails.jsx removes button code duplication

---

app/javascript/packs/notificationSubscriptionHandler.js
app/views/articles/_actions.html.erb

Unsubscribe to a notification subscription when clicking on the previously selected option. 
Fixes #3800 
No UI changes.

Unsubscribe to notification clicking on selected option (#3800)

---

spec/liquid_tags/classified_listing_tag_spec.rb
spec/services/pro_memberships/biller_spec.rb

Fix timezone issue in rspec
Similar to https://github.com/thepracticaldev/dev.to/pull/3113
n/a
n/a

Fix biller spec's zonebie issue

---

app/controllers/oauth/tokens_controller.rb
app/jobs/webhook/destroy_job.rb
config/locales/doorkeeper.en.yml
config/routes.rb
spec/jobs/webhook/destroy_job_spec.rb
spec/requests/oauth/tokens_spec.rb

Destroy webhook endpoints when the user revokes oauth app access
#3715

Destroy webhook endpoints when user revokes oaurh app access

---

app/views/users/_integrations.html.erb

Change stackbit integrations page details

---

app/views/credits/new.html.erb
app/views/internal/shared/_navbar.html.erb
app/views/layouts/internal.html.erb
app/views/notifications/_mention.html.erb
app/views/pages/code_of_conduct.html.erb
app/views/pages/faq.html.erb
app/views/pages/generator.html.erb
app/views/pages/information.html.erb
app/views/pages/privacy.html.erb
app/views/pages/show.html.erb
app/views/pages/swagnets.html.erb
app/views/pages/terms.html.erb
app/views/users/_billing.html.erb
docs/api_template.hbs

Switching client side HTML comments for server side ones that won't appear in the final code

Use server side comments for templates

---

app/assets/stylesheets/chat.scss

Fix images in chat overflowing outside chat window.

---

config/initializers/rubyzip.rb

Require rubyzip

---

README.md

Adding myself and removing mariocsee

Update core team members [ci skip]

---

app/labor/flare_tag.rb
app/views/articles/_sidebar_additional.html.erb

Add the sidebar hacktoberfest tag and flare for posts

Add hacktoberfest sidebar and flare

---

app/javascript/chat/__tests__/__snapshots__/view.test.jsx.snap
app/javascript/chat/view.jsx

Refactors View jsx, removes code duplication.

Refactoring view.jsx removes code duplication
